from typing import Any, ClassVar, overload
from java.math.BigDecimal import BigDecimal
from java.math.BigInteger import BigInteger
from java.util.GregorianCalendar import GregorianCalendar
from java.util.Locale import Locale
from java.util.TimeZone import TimeZone
from javax.xml.datatype.Duration import Duration
from javax.xml.namespace.QName import QName

class XMLGregorianCalendar:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def reset(self) -> None: ...
    @overload
    def setYear(self, arg0: BigInteger) -> None: ...
    @overload
    def setYear(self, arg0: int) -> None: ...
    def setMonth(self, arg0: int) -> None: ...
    def setDay(self, arg0: int) -> None: ...
    def setTimezone(self, arg0: int) -> None: ...
    @overload
    def setTime(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def setTime(self, arg0: int, arg1: int, arg2: int, arg3: BigDecimal) -> None: ...
    @overload
    def setTime(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def setHour(self, arg0: int) -> None: ...
    def setMinute(self, arg0: int) -> None: ...
    def setSecond(self, arg0: int) -> None: ...
    def setMillisecond(self, arg0: int) -> None: ...
    def setFractionalSecond(self, arg0: BigDecimal) -> None: ...
    def getEon(self) -> BigInteger: ...
    def getYear(self) -> int: ...
    def getEonAndYear(self) -> BigInteger: ...
    def getMonth(self) -> int: ...
    def getDay(self) -> int: ...
    def getTimezone(self) -> int: ...
    def getHour(self) -> int: ...
    def getMinute(self) -> int: ...
    def getSecond(self) -> int: ...
    def getMillisecond(self) -> int: ...
    def getFractionalSecond(self) -> BigDecimal: ...
    def compare(self, arg0: "XMLGregorianCalendar") -> int: ...
    def normalize(self) -> "XMLGregorianCalendar": ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toXMLFormat(self) -> str: ...
    def getXMLSchemaType(self) -> QName: ...
    def toString(self) -> str: ...
    def isValid(self) -> bool: ...
    def add(self, arg0: Duration) -> None: ...
    @overload
    def toGregorianCalendar(self) -> GregorianCalendar: ...
    @overload
    def toGregorianCalendar(self, arg0: TimeZone, arg1: Locale, arg2: "XMLGregorianCalendar") -> GregorianCalendar: ...
    def getTimeZone(self, arg0: int) -> TimeZone: ...
    def clone(self) -> Any: ...
