from typing import Any, ClassVar, overload

class LongUnaryOperator:
    def applyAsLong(self, arg0: int) -> int: ...
    def compose(self, arg0: "LongUnaryOperator") -> "LongUnaryOperator": ...
    def andThen(self, arg0: "LongUnaryOperator") -> "LongUnaryOperator": ...
    @staticmethod
    def identity() -> "LongUnaryOperator": ...
