from typing import Any, ClassVar, overload
from android.media.effect.EffectFactory import EffectFactory

class EffectContext:
    @staticmethod
    def createWithCurrentGlContext() -> "EffectContext": ...
    def getFactory(self) -> EffectFactory: ...
    def release(self) -> None: ...
