from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.os.Parcel import Parcel
from android.os.UserHandle import UserHandle
from java.io.File import File
from java.util.UUID import UUID

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class StorageVolume:
    CREATOR: ClassVar[Creator]
    EXTRA_STORAGE_VOLUME: ClassVar[str]
    def getDirectory(self) -> File: ...
    def getDescription(self, arg0: Context) -> str: ...
    def isPrimary(self) -> bool: ...
    def isRemovable(self) -> bool: ...
    def isEmulated(self) -> bool: ...
    def getOwner(self) -> UserHandle: ...
    def getStorageUuid(self) -> UUID: ...
    def getUuid(self) -> str: ...
    def getMediaStoreVolumeName(self) -> str: ...
    def getState(self) -> str: ...
    def createAccessIntent(self, arg0: str) -> Intent: ...
    def createOpenDocumentTreeIntent(self) -> Intent: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
