from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle

class RecognitionListener:
    def onReadyForSpeech(self, arg0: Bundle) -> None: ...
    def onBeginningOfSpeech(self) -> None: ...
    def onRmsChanged(self, arg0: float) -> None: ...
    def onBufferReceived(self, arg0: list[int]) -> None: ...
    def onEndOfSpeech(self) -> None: ...
    def onError(self, arg0: int) -> None: ...
    def onResults(self, arg0: Bundle) -> None: ...
    def onPartialResults(self, arg0: Bundle) -> None: ...
    def onSegmentResults(self, arg0: Bundle) -> None: ...
    def onEndOfSegmentedSession(self) -> None: ...
    def onLanguageDetection(self, arg0: Bundle) -> None: ...
    def onEvent(self, arg0: int, arg1: Bundle) -> None: ...
