from typing import Any, ClassVar, overload
from android.content.AttributionSource import AttributionSource
from android.content.Context import Context
from android.content.ContextParams import ContextParams
from android.content.Intent import Intent
from android.os.Bundle import Bundle
from android.os.IBinder import IBinder
from android.speech.ModelDownloadListener import ModelDownloadListener
from android.speech.RecognitionSupport import RecognitionSupport

class RecognitionService:
    SERVICE_INTERFACE: ClassVar[str]
    SERVICE_META_DATA: ClassVar[str]
    def __init__(self) -> None: ...
    def onStartListening(self, arg0: Intent, arg1: "Callback") -> None: ...
    def onCancel(self, arg0: "Callback") -> None: ...
    def onStopListening(self, arg0: "Callback") -> None: ...
    @overload
    def onCheckRecognitionSupport(self, arg0: Intent, arg1: "SupportCallback") -> None: ...
    @overload
    def onCheckRecognitionSupport(self, arg0: Intent, arg1: AttributionSource, arg2: "SupportCallback") -> None: ...
    @overload
    def onTriggerModelDownload(self, arg0: Intent) -> None: ...
    @overload
    def onTriggerModelDownload(self, arg0: Intent, arg1: AttributionSource) -> None: ...
    @overload
    def onTriggerModelDownload(self, arg0: Intent, arg1: AttributionSource, arg2: ModelDownloadListener) -> None: ...
    def createContext(self, arg0: ContextParams) -> Context: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onDestroy(self) -> None: ...
    def getMaxConcurrentSessionsCount(self) -> int: ...

    class Callback:
        def beginningOfSpeech(self) -> None: ...
        def bufferReceived(self, arg0: list[int]) -> None: ...
        def endOfSpeech(self) -> None: ...
        def error(self, arg0: int) -> None: ...
        def partialResults(self, arg0: Bundle) -> None: ...
        def readyForSpeech(self, arg0: Bundle) -> None: ...
        def results(self, arg0: Bundle) -> None: ...
        def rmsChanged(self, arg0: float) -> None: ...
        def segmentResults(self, arg0: Bundle) -> None: ...
        def endOfSegmentedSession(self) -> None: ...
        def languageDetection(self, arg0: Bundle) -> None: ...
        def getCallingUid(self) -> int: ...
        def getCallingAttributionSource(self) -> AttributionSource: ...

    class SupportCallback:
        def onSupportResult(self, arg0: RecognitionSupport) -> None: ...
        def onError(self, arg0: int) -> None: ...
