from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class NdefRecord:
    CREATOR: ClassVar[Creator]
    RTD_ALTERNATIVE_CARRIER: ClassVar[list[int]]
    RTD_HANDOVER_CARRIER: ClassVar[list[int]]
    RTD_HANDOVER_REQUEST: ClassVar[list[int]]
    RTD_HANDOVER_SELECT: ClassVar[list[int]]
    RTD_SMART_POSTER: ClassVar[list[int]]
    RTD_TEXT: ClassVar[list[int]]
    RTD_URI: ClassVar[list[int]]
    TNF_ABSOLUTE_URI: ClassVar[int]
    TNF_EMPTY: ClassVar[int]
    TNF_EXTERNAL_TYPE: ClassVar[int]
    TNF_MIME_MEDIA: ClassVar[int]
    TNF_UNCHANGED: ClassVar[int]
    TNF_UNKNOWN: ClassVar[int]
    TNF_WELL_KNOWN: ClassVar[int]
    @overload
    def __init__(self, arg0: int, arg1: list[int], arg2: list[int], arg3: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: list[int]) -> None: ...
    @staticmethod
    def createApplicationRecord(arg0: str) -> "NdefRecord": ...
    @overload
    @staticmethod
    def createUri(arg0: Uri) -> "NdefRecord": ...
    @overload
    @staticmethod
    def createUri(arg0: str) -> "NdefRecord": ...
    @staticmethod
    def createMime(arg0: str, arg1: list[int]) -> "NdefRecord": ...
    @staticmethod
    def createExternal(arg0: str, arg1: str, arg2: list[int]) -> "NdefRecord": ...
    @staticmethod
    def createTextRecord(arg0: str, arg1: str) -> "NdefRecord": ...
    def getTnf(self) -> int: ...
    def getType(self) -> list[int]: ...
    def getId(self) -> list[int]: ...
    def getPayload(self) -> list[int]: ...
    def toByteArray(self) -> list[int]: ...
    def toMimeType(self) -> str: ...
    def toUri(self) -> Uri: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
