from typing import Any, ClassVar, overload
from android.gms.ads.AdFormat import AdFormat
from android.gms.ads.AdSize import AdSize
from android.gms.ads.internal.client.zzfp import zzfp
from android.gms.ads.internal.client.zzr import zzr
from android.gms.ads.internal.util.client.zze import zze
from android.gms.ads.preload.PreloadConfiguration import PreloadConfiguration

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Handler: ...  # android.os.Handler
class Context: ...  # android.content.Context
class ViewGroup: ...  # android.view.ViewGroup
class MemoryInfo: ...  # android.app.ActivityManager.MemoryInfo
class Bundle: ...  # android.os.Bundle
class JSONObject: ...  # org.json.JSONObject
class DisplayMetrics: ...  # android.util.DisplayMetrics
class StackTraceElement: ...  # java.lang.StackTraceElement

class zzf:
    zza: ClassVar[Handler]
    def __init__(self) -> None: ...
    def zza(self, arg0: Context, arg1: int) -> int: ...
    def zzb(self, arg0: ViewGroup, arg1: zzr, arg2: str, arg3: str) -> None: ...
    def zzc(self, arg0: ViewGroup, arg1: zzr, arg2: str) -> None: ...
    @staticmethod
    def zzd(arg0: dict, arg1: Any, arg2: Any) -> Any: ...
    @staticmethod
    def zze(arg0: Context) -> MemoryInfo: ...
    @staticmethod
    def zzf(arg0: Context) -> str: ...
    @staticmethod
    def zzg(arg0: str) -> str: ...
    @staticmethod
    def zzh(arg0: str) -> str: ...
    def zzi(self, arg0: Context, arg1: str, arg2: str, arg3: Bundle, arg4: bool) -> None: ...
    @staticmethod
    def zzj() -> str: ...
    @staticmethod
    def zzk(arg0: Context, arg1: int, arg2: int, arg3: int) -> AdSize: ...
    @staticmethod
    def zzl(arg0: Context, arg1: int, arg2: int) -> AdSize: ...
    def zzm(self, arg0: dict) -> JSONObject: ...
    def zzn(self, arg0: Bundle, arg1: JSONObject) -> JSONObject: ...
    def zzo(self, arg0: Bundle) -> JSONObject: ...
    @staticmethod
    def zzq(arg0: str) -> bool: ...
    @staticmethod
    def zzr(arg0: Context, arg1: int) -> int: ...
    @staticmethod
    def zzs(arg0: zzfp) -> PreloadConfiguration: ...
    @staticmethod
    def zzt(arg0: zzfp) -> PreloadConfiguration: ...
    @staticmethod
    def zzu(arg0: Context, arg1: PreloadConfiguration, arg2: AdFormat) -> zzfp: ...
    @staticmethod
    def zzv(arg0: Context, arg1: PreloadConfiguration, arg2: int) -> zzfp: ...
    @staticmethod
    def zzw(arg0: DisplayMetrics, arg1: int) -> int: ...
    @staticmethod
    def zzx(arg0: list[StackTraceElement], arg1: str) -> str: ...
    @staticmethod
    def zzy() -> bool: ...
    @staticmethod
    def zzz(arg0: Context, arg1: int) -> bool: ...
    @staticmethod
    def zzA(arg0: Context) -> bool: ...
    @staticmethod
    def zzB() -> bool: ...
    @staticmethod
    def zzC(arg0: DisplayMetrics, arg1: int) -> int: ...
    @staticmethod
    def zzD(arg0: Context, arg1: str, arg2: str, arg3: Bundle, arg4: bool, arg5: zze) -> None: ...
    @staticmethod
    def zzE(arg0: Context, arg1: int) -> int: ...
    @staticmethod
    def zzF(arg0: Context) -> str: ...
