from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzgug import zzgug

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Throwable: ...  # java.lang.Throwable

class zzo:
    zzb: ClassVar[zzgug]
    @staticmethod
    def zzd(arg0: str) -> None: ...
    @staticmethod
    def zze(arg0: str, arg1: Throwable) -> None: ...
    @staticmethod
    def zzf(arg0: str) -> None: ...
    @staticmethod
    def zzg(arg0: str, arg1: Throwable) -> None: ...
    @staticmethod
    def zzh(arg0: str) -> None: ...
    @staticmethod
    def zzi(arg0: str) -> None: ...
    @staticmethod
    def zzj(arg0: str, arg1: Throwable) -> None: ...
    @staticmethod
    def zzl(arg0: str, arg1: Throwable) -> None: ...
    @staticmethod
    def zzm(arg0: int) -> bool: ...
