from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.gms.ads.internal.util.client.zzt import zzt

class zzu:
    def __init__(self, arg0: Context, arg1: str) -> None: ...
    def zzb(self) -> str: ...
    def zza(self, arg0: str) -> zzt: ...
    def zzc(self, arg0: str, arg1: dict) -> zzt: ...
