from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject: ...  # org.json.JSONObject

class zzw:
    def __init__(self) -> None: ...
    def zza(self) -> int: ...
    def zzb(self) -> int: ...
    def zzc(self) -> bool: ...
    @staticmethod
    def zzd(arg0: JSONObject) -> "zzw": ...
