from typing import Any, ClassVar, overload
from java.security.PublicKey import PublicKey

class Certificate:
    def __init__(self) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getEncoded(self) -> list[int]: ...
    @overload
    def verify(self, arg0: PublicKey) -> None: ...
    @overload
    def verify(self, arg0: PublicKey, arg1: str) -> None: ...
    def toString(self) -> str: ...
    def getPublicKey(self) -> PublicKey: ...
