from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.math.BigInteger import BigInteger
from java.security.Principal import Principal
from java.util.Date import Date

class X509Certificate:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def getInstance(arg0: InputStream) -> "X509Certificate": ...
    @overload
    @staticmethod
    def getInstance(arg0: list[int]) -> "X509Certificate": ...
    @overload
    def checkValidity(self) -> None: ...
    @overload
    def checkValidity(self, arg0: Date) -> None: ...
    def getVersion(self) -> int: ...
    def getSerialNumber(self) -> BigInteger: ...
    def getIssuerDN(self) -> Principal: ...
    def getSubjectDN(self) -> Principal: ...
    def getNotBefore(self) -> Date: ...
    def getNotAfter(self) -> Date: ...
    def getSigAlgName(self) -> str: ...
    def getSigAlgOID(self) -> str: ...
    def getSigAlgParams(self) -> list[int]: ...
