from typing import Any, ClassVar, overload
from android.os.IInterface import IInterface
from android.os.Parcel import Parcel
from android.os.Parcelable import Parcelable
from android.os.Parcelable.Creator import Creator

class zzben:
    @staticmethod
    def zza(arg0: Parcel) -> bool: ...
    @staticmethod
    def zzb(arg0: Parcel, arg1: Creator) -> Parcelable: ...
    @staticmethod
    def zzc(arg0: Parcel, arg1: Parcelable) -> None: ...
    @staticmethod
    def zzd(arg0: Parcel, arg1: Parcelable) -> None: ...
    @staticmethod
    def zze(arg0: Parcel, arg1: IInterface) -> None: ...
    @staticmethod
    def zzf(arg0: Parcel) -> list: ...
    @staticmethod
    def zzg(arg0: Parcel) -> dict: ...
    @staticmethod
    def zzh(arg0: Parcel) -> None: ...
