from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.gms.ads.FullScreenContentCallback import FullScreenContentCallback
from android.gms.ads.OnPaidEventListener import OnPaidEventListener
from android.gms.ads.ResponseInfo import ResponseInfo
from android.gms.internal.ads.zzbgq import zzbgq

class zzbgm:
    @overload
    def __init__(self, arg0: zzbgq, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: zzbgq) -> None: ...
    def show(self, arg0: Activity) -> None: ...
    def getResponseInfo(self) -> ResponseInfo: ...
    def getAdUnitId(self) -> str: ...
    def setFullScreenContentCallback(self, arg0: FullScreenContentCallback) -> None: ...
    def getFullScreenContentCallback(self) -> FullScreenContentCallback: ...
    def setImmersiveMode(self, arg0: bool) -> None: ...
    def setOnPaidEventListener(self, arg0: OnPaidEventListener) -> None: ...
    def getOnPaidEventListener(self) -> OnPaidEventListener: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
