from typing import Any, ClassVar, overload

class zzbgn:
    def __init__(self) -> None: ...
    def zzb(self, arg0: "FullScreenContentCallback") -> None: ...
    def zzc(self) -> None: ...
    def zzd(self) -> None: ...
    def zze(self, arg0: "zze") -> None: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
