from typing import Any, ClassVar, overload

class zzbgx:
    def zzc(self) -> None: ...
    def zzd(self) -> None: ...
    def zze(self, arg0: "zze") -> None: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
