from typing import Any, ClassVar, overload
from android.gms.ads.FullScreenContentCallback import FullScreenContentCallback
from android.gms.ads.internal.client.zze import zze

class zzbgn:
    def __init__(self) -> None: ...
    def zzb(self, arg0: FullScreenContentCallback) -> None: ...
    def zzc(self) -> None: ...
    def zzd(self) -> None: ...
    def zze(self, arg0: zze) -> None: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
