from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zze import zze
from android.gms.internal.ads.zzbgq import zzbgq

class zzbgr:
    def zzb(self, arg0: zzbgq) -> None: ...
    def zzc(self, arg0: int) -> None: ...
    def zzd(self, arg0: zze) -> None: ...
