from typing import Any, ClassVar, overload

class zzbgs:
    def __init__(self) -> None: ...
    @staticmethod
    def zze(arg0: "IBinder") -> "zzbgt": ...
    def zzdd(self, arg0: int, arg1: "Parcel", arg2: "Parcel", arg3: int) -> bool: ...
