from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzbio import zzbio

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Editor: ...  # android.content.SharedPreferences.Editor
class JSONObject: ...  # org.json.JSONObject

class zzbip:
    def __init__(self) -> None: ...
    def zza(self, arg0: zzbio) -> None: ...
    def zzb(self, arg0: zzbio) -> None: ...
    def zzc(self, arg0: zzbio) -> None: ...
    def zzd(self, arg0: Editor, arg1: int, arg2: JSONObject) -> None: ...
    def zze(self) -> list: ...
    def zzf(self) -> list: ...
