from typing import Any, ClassVar, overload

class zzbiq:
    def __init__(self) -> None: ...
    @staticmethod
    def zza(arg0: "Context") -> "SharedPreferences": ...
    @staticmethod
    def zzb(arg0: "Context") -> "SharedPreferences": ...
