from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class SharedPreferences: ...  # android.content.SharedPreferences
class JSONObject: ...  # org.json.JSONObject
class Editor: ...  # android.content.SharedPreferences.Editor
class Bundle: ...  # android.os.Bundle

class zzbio:
    def zze(self) -> str: ...
    def zzf(self) -> Any: ...
    def zzg(self) -> Any: ...
    @staticmethod
    def zzh(arg0: int, arg1: str, arg2: int, arg3: int) -> "zzbio": ...
    @staticmethod
    def zzi(arg0: int, arg1: str, arg2: int, arg3: int) -> "zzbio": ...
    @staticmethod
    def zzj(arg0: int, arg1: str, arg2: float, arg3: float) -> "zzbio": ...
    @staticmethod
    def zzk(arg0: int, arg1: str) -> "zzbio": ...
    @staticmethod
    def zzl(arg0: int, arg1: str) -> "zzbio": ...
    def zzm(self) -> int: ...
    def zzd(self, arg0: SharedPreferences) -> Any: ...
    def zzc(self, arg0: JSONObject) -> Any: ...
    def zzb(self, arg0: Editor, arg1: Any) -> None: ...
    def zza(self, arg0: Bundle) -> Any: ...
