from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class SharedPreferences: ...  # android.content.SharedPreferences

class zzbig:
    def __init__(self) -> None: ...
    def zza(self, arg0: Context) -> None: ...
    def onSharedPreferenceChanged(self, arg0: SharedPreferences, arg1: str) -> None: ...
    def zzb(self, arg0: str, arg1: str) -> str: ...
    def zzc(self, arg0: str, arg1: int) -> int: ...
    def zzd(self, arg0: str, arg1: int) -> int: ...
    def zze(self, arg0: str, arg1: float) -> float: ...
    def zzf(self, arg0: str, arg1: bool) -> bool: ...
