from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper: ...  # com.google.android.gms.dynamic.IObjectWrapper

class zzbjp:
    def zzb(self) -> str: ...
    def zzc(self) -> str: ...
    def zzd(self, arg0: IObjectWrapper) -> None: ...
    def zze(self) -> None: ...
    def zzf(self) -> None: ...
