from typing import Any, ClassVar, overload

class zzbjp:
    def zzb(self) -> str: ...
    def zzc(self) -> str: ...
    def zzd(self, arg0: "IObjectWrapper") -> None: ...
    def zze(self) -> None: ...
    def zzf(self) -> None: ...
