from typing import Any, ClassVar, overload

class zzbku:
    zza: ClassVar["zzbkh"]
    zzb: ClassVar["zzbkh"]
    zzc: ClassVar["zzbkh"]
    zzd: ClassVar["zzbkh"]
    zze: ClassVar["zzbkh"]
    zzf: ClassVar["zzbkh"]
    zzg: ClassVar["zzbkh"]
    zzh: ClassVar["zzbkh"]
    zzi: ClassVar["zzbkh"]
    zzj: ClassVar["zzbkh"]
    zzk: ClassVar["zzbkh"]
    zzl: ClassVar["zzbkh"]
    zzm: ClassVar["zzbkh"]
    zzn: ClassVar["zzbkh"]
    zzo: ClassVar["zzbkh"]
    zzp: ClassVar["zzbkh"]
    zzq: ClassVar["zzbkh"]
    zzr: ClassVar["zzbkh"]
    zzs: ClassVar["zzbkh"]
    zzt: ClassVar["zzbkh"]
    zzu: ClassVar["zzbkh"]
