from typing import Any, ClassVar, overload

class zzbln:
    def zza(self, arg0: str, arg1: bool) -> bool: ...
    def zzb(self, arg0: str, arg1: int) -> int: ...
    def zzc(self, arg0: str, arg1: float) -> float: ...
    def zzd(self, arg0: str, arg1: str) -> str: ...
