from typing import Any, ClassVar, overload

class zzblw:
    def __init__(self, arg0: "Drawable", arg1: "Uri", arg2: float, arg3: int, arg4: int, arg5: dict) -> None: ...
    def zzb(self) -> "IObjectWrapper": ...
    def zzc(self) -> "Uri": ...
    def zzd(self) -> float: ...
    def zze(self) -> int: ...
    def zzf(self) -> int: ...
    def zzg(self) -> dict: ...
