from typing import Any, ClassVar, overload
from android.graphics.drawable.Drawable import Drawable
from android.net.Uri import Uri

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...

class zzblw:
    def __init__(self, arg0: Drawable, arg1: Uri, arg2: float, arg3: int, arg4: int, arg5: dict) -> None: ...
    def zzb(self) -> IObjectWrapper: ...
    def zzc(self) -> Uri: ...
    def zzd(self) -> float: ...
    def zze(self) -> int: ...
    def zzf(self) -> int: ...
    def zzg(self) -> dict: ...
