from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzbmi import zzbmi

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...

class zzbmn:
    def zzb(self, arg0: str, arg1: IObjectWrapper) -> None: ...
    def zzc(self, arg0: str) -> IObjectWrapper: ...
    def zzd(self, arg0: IObjectWrapper) -> None: ...
    def zze(self) -> None: ...
    def zzf(self, arg0: IObjectWrapper, arg1: int) -> None: ...
    def zzdB(self, arg0: IObjectWrapper) -> None: ...
    def zzdD(self, arg0: IObjectWrapper) -> None: ...
    def zzdE(self, arg0: zzbmi) -> None: ...
    def zzdC(self, arg0: IObjectWrapper) -> None: ...
