from typing import Any, ClassVar, overload

class zzbmx:
    def zzb(self) -> "IObjectWrapper": ...
    def zzc(self) -> str: ...
    def zzd(self) -> list: ...
    def zze(self) -> str: ...
    def zzf(self) -> "zzbml": ...
    def zzg(self) -> str: ...
    def zzh(self) -> float: ...
    def zzi(self) -> str: ...
    def zzj(self) -> str: ...
    def zzk(self) -> "Bundle": ...
    def zzl(self) -> None: ...
    def zzm(self) -> "zzea": ...
    def zzn(self, arg0: "Bundle") -> None: ...
    def zzo(self, arg0: "Bundle") -> bool: ...
    def zzp(self, arg0: "Bundle") -> None: ...
    def zzq(self) -> "zzbme": ...
    def zzr(self) -> "IObjectWrapper": ...
    def zzs(self) -> str: ...
