from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzea import zzea
from android.gms.internal.ads.zzbme import zzbme
from android.gms.internal.ads.zzbml import zzbml
from android.os.Bundle import Bundle

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...

class zzbmz:
    def zzb(self) -> IObjectWrapper: ...
    def zzc(self) -> str: ...
    def zzd(self) -> list: ...
    def zze(self) -> str: ...
    def zzf(self) -> zzbml: ...
    def zzg(self) -> str: ...
    def zzh(self) -> str: ...
    def zzi(self) -> Bundle: ...
    def zzj(self) -> None: ...
    def zzk(self) -> zzea: ...
    def zzl(self, arg0: Bundle) -> None: ...
    def zzm(self, arg0: Bundle) -> bool: ...
    def zzn(self, arg0: Bundle) -> None: ...
    def zzo(self) -> zzbme: ...
    def zzp(self) -> IObjectWrapper: ...
    def zzq(self) -> str: ...
