from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzbml import zzbml
from android.graphics.drawable.Drawable import Drawable
from android.net.Uri import Uri

class zzbmm:
    def __init__(self, arg0: zzbml) -> None: ...
    def getDrawable(self) -> Drawable: ...
    def getUri(self) -> Uri: ...
    def getScale(self) -> float: ...
    def zza(self) -> int: ...
    def zzb(self) -> int: ...
