from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzbme import zzbme

class zzbmf:
    def __init__(self, arg0: zzbme) -> None: ...
    def getText(self) -> str: ...
    def getImages(self) -> list: ...
