from typing import Any, ClassVar, overload

class zzbml:
    def zzb(self) -> "IObjectWrapper": ...
    def zzc(self) -> "Uri": ...
    def zzd(self) -> float: ...
    def zze(self) -> int: ...
    def zzf(self) -> int: ...
    def zzg(self) -> dict: ...
