from typing import Any, ClassVar, overload

class zzbmk:
    def __init__(self) -> None: ...
    @staticmethod
    def zzh(arg0: "IBinder") -> "zzbml": ...
    def zzdd(self, arg0: int, arg1: "Parcel", arg2: "Parcel", arg3: int) -> bool: ...
