from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzea import zzea
from android.gms.internal.ads.zzbmi import zzbmi
from android.gms.internal.ads.zzbml import zzbml

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...

class zzbnc:
    def zze(self, arg0: str) -> str: ...
    def zzf(self, arg0: str) -> zzbml: ...
    def zzg(self) -> list: ...
    def zzh(self) -> str: ...
    def zzi(self, arg0: str) -> None: ...
    def zzj(self) -> None: ...
    def zzk(self) -> zzea: ...
    def zzl(self) -> None: ...
    def zzm(self) -> IObjectWrapper: ...
    def zzn(self, arg0: IObjectWrapper) -> bool: ...
    def zzo(self) -> bool: ...
    def zzp(self) -> bool: ...
    def zzq(self, arg0: IObjectWrapper) -> None: ...
    def zzr(self) -> None: ...
    def zzs(self) -> zzbmi: ...
    def zzt(self, arg0: IObjectWrapper) -> bool: ...
