from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzea import zzea
from android.gms.internal.ads.zzbmi import zzbmi
from android.gms.internal.ads.zzbml import zzbml

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper: ...  # com.google.android.gms.dynamic.IObjectWrapper

class zzbna:
    def zze(self, arg0: str) -> str: ...
    def zzf(self, arg0: str) -> zzbml: ...
    def zzg(self) -> list: ...
    def zzh(self) -> str: ...
    def zzi(self, arg0: str) -> None: ...
    def zzj(self) -> None: ...
    def zzk(self) -> zzea: ...
    def zzl(self) -> None: ...
    def zzm(self) -> IObjectWrapper: ...
    def zzn(self, arg0: IObjectWrapper) -> bool: ...
    def zzo(self) -> bool: ...
    def zzp(self) -> bool: ...
    def zzq(self, arg0: IObjectWrapper) -> None: ...
    def zzr(self) -> None: ...
    def zzs(self) -> zzbmi: ...
    def zzt(self, arg0: IObjectWrapper) -> bool: ...
