from typing import Any, ClassVar, overload

class zzbnv:
    def __init__(self) -> None: ...
    @staticmethod
    def zzb(arg0: "IBinder") -> "zzbnw": ...
    def zzdd(self, arg0: int, arg1: "Parcel", arg2: "Parcel", arg3: int) -> bool: ...
