from typing import Any, ClassVar, overload
from android.gms.ads.VideoController import VideoController
from android.gms.internal.ads.zzboc import zzboc

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Bundle:
    """Forward declaration for ``android.os.Bundle``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Bundle')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Bundle
    """
    ...
class Image:
    """Forward declaration for ``com.google.android.gms.ads.formats.NativeAd.Image``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.ads.formats.NativeAd.Image')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/ads/formats/NativeAd/Image
    """
    ...

class zzbod:
    def __init__(self, arg0: zzboc) -> None: ...
    def zzk(self) -> Any: ...
    def performClick(self, arg0: Bundle) -> None: ...
    def recordImpression(self, arg0: Bundle) -> bool: ...
    def reportTouchEvent(self, arg0: Bundle) -> None: ...
    def zza(self) -> str: ...
    def zzb(self) -> list: ...
    def zzc(self) -> str: ...
    def zzd(self) -> Image: ...
    def zze(self) -> str: ...
    def zzg(self) -> float: ...
    def zzh(self) -> str: ...
    def zzi(self) -> str: ...
    def zzj(self) -> VideoController: ...
    def zzf(self) -> str: ...
