from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzdc import zzdc
from android.gms.ads.internal.client.zzdg import zzdg
from android.gms.ads.internal.client.zzdq import zzdq
from android.gms.ads.internal.client.zzdx import zzdx
from android.gms.ads.internal.client.zzea import zzea
from android.gms.internal.ads.zzbme import zzbme
from android.gms.internal.ads.zzbmi import zzbmi
from android.gms.internal.ads.zzbml import zzbml
from android.gms.internal.ads.zzbnz import zzbnz
from android.os.Bundle import Bundle

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...

class zzboa:
    def zze(self) -> str: ...
    def zzf(self) -> list: ...
    def zzg(self) -> str: ...
    def zzh(self) -> zzbml: ...
    def zzi(self) -> str: ...
    def zzj(self) -> str: ...
    def zzk(self) -> float: ...
    def zzl(self) -> str: ...
    def zzm(self) -> str: ...
    def zzn(self) -> zzea: ...
    def zzo(self) -> str: ...
    def zzp(self) -> None: ...
    def zzq(self) -> zzbme: ...
    def zzr(self, arg0: Bundle) -> None: ...
    def zzs(self, arg0: Bundle) -> bool: ...
    def zzt(self, arg0: Bundle) -> None: ...
    def zzu(self) -> IObjectWrapper: ...
    def zzv(self) -> IObjectWrapper: ...
    def zzw(self) -> Bundle: ...
    def zzx(self, arg0: zzbnz) -> None: ...
    def zzy(self) -> None: ...
    def zzz(self) -> list: ...
    def zzA(self) -> bool: ...
    def zzB(self, arg0: zzdg) -> None: ...
    def zzC(self, arg0: zzdc) -> None: ...
    def zzD(self) -> None: ...
    def zzE(self) -> None: ...
    def zzF(self) -> zzbmi: ...
    def zzG(self) -> bool: ...
    def zzH(self) -> zzdx: ...
    def zzI(self, arg0: zzdq) -> None: ...
    def zzJ(self, arg0: Bundle) -> None: ...
    def zzK(self) -> int: ...
    def zzL(self, arg0: int) -> None: ...
