from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class WebViewClient: ...  # android.webkit.WebViewClient
class WebView: ...  # android.webkit.WebView
class WebResourceRequest: ...  # android.webkit.WebResourceRequest
class Bitmap: ...  # android.graphics.Bitmap
class WebResourceResponse: ...  # android.webkit.WebResourceResponse
class Message: ...  # android.os.Message
class WebResourceError: ...  # android.webkit.WebResourceError
class SslErrorHandler: ...  # android.webkit.SslErrorHandler
class SslError: ...  # android.net.http.SslError
class ClientCertRequest: ...  # android.webkit.ClientCertRequest
class HttpAuthHandler: ...  # android.webkit.HttpAuthHandler
class KeyEvent: ...  # android.view.KeyEvent
class RenderProcessGoneDetail: ...  # android.webkit.RenderProcessGoneDetail
class SafeBrowsingResponse: ...  # android.webkit.SafeBrowsingResponse

class zzbqt:
    def __init__(self) -> None: ...
    def getDelegate(self) -> WebViewClient: ...
    @overload
    def shouldOverrideUrlLoading(self, arg0: WebView, arg1: str) -> bool: ...
    @overload
    def shouldOverrideUrlLoading(self, arg0: WebView, arg1: WebResourceRequest) -> bool: ...
    def onPageStarted(self, arg0: WebView, arg1: str, arg2: Bitmap) -> None: ...
    def onPageFinished(self, arg0: WebView, arg1: str) -> None: ...
    def onLoadResource(self, arg0: WebView, arg1: str) -> None: ...
    def onPageCommitVisible(self, arg0: WebView, arg1: str) -> None: ...
    @overload
    def shouldInterceptRequest(self, arg0: WebView, arg1: str) -> WebResourceResponse: ...
    @overload
    def shouldInterceptRequest(self, arg0: WebView, arg1: WebResourceRequest) -> WebResourceResponse: ...
    def onTooManyRedirects(self, arg0: WebView, arg1: Message, arg2: Message) -> None: ...
    @overload
    def onReceivedError(self, arg0: WebView, arg1: int, arg2: str, arg3: str) -> None: ...
    @overload
    def onReceivedError(self, arg0: WebView, arg1: WebResourceRequest, arg2: WebResourceError) -> None: ...
    def onReceivedHttpError(self, arg0: WebView, arg1: WebResourceRequest, arg2: WebResourceResponse) -> None: ...
    def onFormResubmission(self, arg0: WebView, arg1: Message, arg2: Message) -> None: ...
    def doUpdateVisitedHistory(self, arg0: WebView, arg1: str, arg2: bool) -> None: ...
    def onReceivedSslError(self, arg0: WebView, arg1: SslErrorHandler, arg2: SslError) -> None: ...
    def onReceivedClientCertRequest(self, arg0: WebView, arg1: ClientCertRequest) -> None: ...
    def onReceivedHttpAuthRequest(self, arg0: WebView, arg1: HttpAuthHandler, arg2: str, arg3: str) -> None: ...
    def shouldOverrideKeyEvent(self, arg0: WebView, arg1: KeyEvent) -> bool: ...
    def onUnhandledKeyEvent(self, arg0: WebView, arg1: KeyEvent) -> None: ...
    def onScaleChanged(self, arg0: WebView, arg1: float, arg2: float) -> None: ...
    def onReceivedLoginRequest(self, arg0: WebView, arg1: str, arg2: str, arg3: str) -> None: ...
    def onRenderProcessGone(self, arg0: WebView, arg1: RenderProcessGoneDetail) -> bool: ...
    def onSafeBrowsingHit(self, arg0: WebView, arg1: WebResourceRequest, arg2: int, arg3: SafeBrowsingResponse) -> None: ...
