from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.gms.ads.h5.OnH5AdsEventListener import OnH5AdsEventListener

class zzbre:
    def __init__(self, arg0: Context, arg1: OnH5AdsEventListener) -> None: ...
    def zza(self, arg0: str) -> bool: ...
    def zzb(self) -> None: ...
    @staticmethod
    def zzc(arg0: str) -> bool: ...
