from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class WebView: ...  # android.webkit.WebView
class WebViewClient: ...  # android.webkit.WebViewClient
class WebResourceRequest: ...  # android.webkit.WebResourceRequest

class zzbrg:
    def __init__(self, arg0: Context, arg1: WebView) -> None: ...
    def zza(self) -> None: ...
    def zzb(self, arg0: WebViewClient) -> None: ...
    def getDelegate(self) -> WebViewClient: ...
    @overload
    def shouldOverrideUrlLoading(self, arg0: WebView, arg1: WebResourceRequest) -> bool: ...
    @overload
    def shouldOverrideUrlLoading(self, arg0: WebView, arg1: str) -> bool: ...
    def onLoadResource(self, arg0: WebView, arg1: str) -> None: ...
