from typing import Any, ClassVar, overload
from android.gms.ads.AdLoadCallback import AdLoadCallback
from android.gms.ads.FullScreenContentCallback import FullScreenContentCallback
from android.gms.ads.OnPaidEventListener import OnPaidEventListener
from android.gms.ads.ResponseInfo import ResponseInfo
from android.gms.ads.admanager.AppEventListener import AppEventListener
from android.gms.ads.internal.client.zzbu import zzbu
from android.gms.ads.internal.client.zzeh import zzeh

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class Activity: ...  # android.app.Activity

class zzbss:
    @overload
    def __init__(self, arg0: Context, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: str, arg2: zzbu) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: zzbu) -> None: ...
    def getAdUnitId(self) -> str: ...
    def zza(self, arg0: zzeh, arg1: AdLoadCallback) -> None: ...
    def getResponseInfo(self) -> ResponseInfo: ...
    def show(self, arg0: Activity) -> None: ...
    def setImmersiveMode(self, arg0: bool) -> None: ...
    def setOnPaidEventListener(self, arg0: OnPaidEventListener) -> None: ...
    def getOnPaidEventListener(self) -> OnPaidEventListener: ...
    def setFullScreenContentCallback(self, arg0: FullScreenContentCallback) -> None: ...
    def getFullScreenContentCallback(self) -> FullScreenContentCallback: ...
    def getAppEventListener(self) -> AppEventListener: ...
    def setAppEventListener(self, arg0: AppEventListener) -> None: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
