from typing import Any, ClassVar, overload

class zzbsl:
    def zzb(self) -> "zzea": ...
    def zzc(self) -> None: ...
    def zzd(self, arg0: "IObjectWrapper", arg1: "zzbso") -> None: ...
    def zze(self, arg0: "IObjectWrapper") -> None: ...
    def zzf(self) -> "zzbmi": ...
