from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zze import zze
from android.gms.internal.ads.zzbsl import zzbsl

class zzbsr:
    def zze(self, arg0: zzbsl) -> None: ...
    def zzf(self, arg0: int) -> None: ...
    def zzg(self, arg0: zze) -> None: ...
