from typing import Any, ClassVar, overload

class zzbsc:
    def __init__(self) -> None: ...
    @staticmethod
    def zzc(arg0: "IBinder") -> "zzbsd": ...
    def zzdd(self, arg0: int, arg1: "Parcel", arg2: "Parcel", arg3: int) -> bool: ...
