from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzea import zzea
from android.gms.internal.ads.zzbme import zzbme
from android.gms.internal.ads.zzbml import zzbml

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...
class Bundle:
    """Forward declaration for ``android.os.Bundle``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Bundle')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Bundle
    """
    ...

class zzbvu:
    def zze(self) -> str: ...
    def zzf(self) -> list: ...
    def zzg(self) -> str: ...
    def zzh(self) -> zzbml: ...
    def zzi(self) -> str: ...
    def zzj(self) -> float: ...
    def zzk(self) -> str: ...
    def zzl(self) -> str: ...
    def zzm(self) -> None: ...
    def zzn(self, arg0: IObjectWrapper) -> None: ...
    def zzo(self, arg0: IObjectWrapper) -> None: ...
    def zzp(self) -> bool: ...
    def zzq(self) -> bool: ...
    def zzr(self) -> Bundle: ...
    def zzs(self, arg0: IObjectWrapper) -> None: ...
    def zzt(self) -> zzea: ...
    def zzu(self) -> IObjectWrapper: ...
    def zzv(self) -> zzbme: ...
    def zzw(self) -> IObjectWrapper: ...
    def zzx(self) -> IObjectWrapper: ...
    def zzy(self, arg0: IObjectWrapper, arg1: IObjectWrapper, arg2: IObjectWrapper) -> None: ...
