from typing import Any, ClassVar, overload

class zzbvj:
    def zzb(self, arg0: str) -> "zzbvm": ...
    def zzc(self, arg0: str) -> bool: ...
    def zze(self, arg0: str) -> "zzbxi": ...
    def zzd(self, arg0: str) -> bool: ...
