from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zze import zze
from android.gms.internal.ads.zzbnc import zzbnc
from android.gms.internal.ads.zzcci import zzcci
from android.gms.internal.ads.zzccm import zzccm

class zzbvp:
    def zze(self) -> None: ...
    def zzf(self) -> None: ...
    def zzg(self, arg0: int) -> None: ...
    def zzh(self) -> None: ...
    def zzi(self) -> None: ...
    def zzj(self) -> None: ...
    def zzk(self) -> None: ...
    def zzl(self, arg0: str, arg1: str) -> None: ...
    def zzm(self, arg0: zzbnc, arg1: str) -> None: ...
    def zzn(self) -> None: ...
    def zzo(self) -> None: ...
    def zzp(self, arg0: zzcci) -> None: ...
    def zzq(self) -> None: ...
    def zzr(self, arg0: zzccm) -> None: ...
    def zzs(self, arg0: int) -> None: ...
    def zzt(self) -> None: ...
    def zzu(self) -> None: ...
    def zzv(self, arg0: str) -> None: ...
    def zzw(self, arg0: int, arg1: str) -> None: ...
    def zzx(self, arg0: zze) -> None: ...
    def zzy(self, arg0: zze) -> None: ...
    def zzz(self) -> None: ...
