from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzbvm import zzbvm
from android.gms.internal.ads.zzbxi import zzbxi

class zzbvf:
    def __init__(self) -> None: ...
    def zzb(self, arg0: str) -> zzbvm: ...
    def zzc(self, arg0: str) -> bool: ...
    def zzd(self, arg0: str) -> bool: ...
    def zze(self, arg0: str) -> zzbxi: ...
