from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzea import zzea
from android.gms.ads.internal.client.zzm import zzm
from android.gms.ads.internal.client.zzr import zzr
from android.gms.ads.mediation.Adapter import Adapter
from android.gms.ads.mediation.MediationAdapter import MediationAdapter
from android.gms.internal.ads.zzbma import zzbma
from android.gms.internal.ads.zzbnc import zzbnc
from android.gms.internal.ads.zzbsa import zzbsa
from android.gms.internal.ads.zzbvp import zzbvp
from android.gms.internal.ads.zzbvs import zzbvs
from android.gms.internal.ads.zzbvu import zzbvu
from android.gms.internal.ads.zzbvv import zzbvv
from android.gms.internal.ads.zzbvy import zzbvy
from android.gms.internal.ads.zzbxx import zzbxx
from android.gms.internal.ads.zzcch import zzcch

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper: ...  # com.google.android.gms.dynamic.IObjectWrapper
class Bundle: ...  # android.os.Bundle

class zzbwk:
    @overload
    def __init__(self, arg0: MediationAdapter) -> None: ...
    @overload
    def __init__(self, arg0: Adapter) -> None: ...
    def zzf(self) -> IObjectWrapper: ...
    def zze(self, arg0: IObjectWrapper, arg1: zzr, arg2: zzm, arg3: str, arg4: zzbvp) -> None: ...
    def zzj(self, arg0: IObjectWrapper, arg1: zzr, arg2: zzm, arg3: str, arg4: str, arg5: zzbvp) -> None: ...
    def zzs(self) -> Bundle: ...
    def zzg(self, arg0: IObjectWrapper, arg1: zzm, arg2: str, arg3: zzbvp) -> None: ...
    def zzk(self, arg0: IObjectWrapper, arg1: zzm, arg2: str, arg3: str, arg4: zzbvp) -> None: ...
    def zzt(self) -> Bundle: ...
    def zzr(self, arg0: IObjectWrapper, arg1: zzm, arg2: str, arg3: str, arg4: zzbvp, arg5: zzbma, arg6: list) -> None: ...
    def zzu(self) -> Bundle: ...
    def zzC(self) -> zzbvy: ...
    def zzz(self) -> zzbnc: ...
    def zzx(self) -> bool: ...
    def zzn(self, arg0: IObjectWrapper, arg1: zzm, arg2: str, arg3: zzcch, arg4: str) -> None: ...
    def zzy(self, arg0: IObjectWrapper, arg1: zzcch, arg2: list) -> None: ...
    def zzo(self, arg0: zzm, arg1: str) -> None: ...
    def zzv(self, arg0: zzm, arg1: str, arg2: str) -> None: ...
    def zzp(self) -> None: ...
    def zzq(self) -> bool: ...
    def zzD(self, arg0: IObjectWrapper, arg1: zzm, arg2: str, arg3: zzbvp) -> None: ...
    def zzG(self, arg0: IObjectWrapper, arg1: zzm, arg2: str, arg3: zzbvp) -> None: ...
    def zzJ(self, arg0: IObjectWrapper, arg1: zzr, arg2: zzm, arg3: str, arg4: str, arg5: zzbvp) -> None: ...
    def zzM(self, arg0: IObjectWrapper, arg1: zzm, arg2: str, arg3: zzbvp) -> None: ...
    def zzK(self) -> zzbvs: ...
    def zzE(self, arg0: IObjectWrapper) -> None: ...
    def zzA(self, arg0: bool) -> None: ...
    def zzB(self) -> zzea: ...
    def zzL(self, arg0: IObjectWrapper) -> None: ...
    def zzh(self) -> None: ...
    def zzN(self, arg0: IObjectWrapper) -> None: ...
    def zzi(self) -> None: ...
    def zzl(self) -> None: ...
    def zzm(self) -> None: ...
    def zzw(self, arg0: IObjectWrapper) -> None: ...
    def zzF(self, arg0: IObjectWrapper, arg1: zzbsa, arg2: list) -> None: ...
    def zzH(self) -> zzbxx: ...
    def zzI(self) -> zzbxx: ...
    def zzO(self) -> zzbvu: ...
    def zzP(self) -> zzbvv: ...
