from typing import Any, ClassVar, overload
from android.gms.ads.AdError import AdError
from android.gms.ads.mediation.MediationBannerAdapter import MediationBannerAdapter
from android.gms.ads.mediation.MediationInterstitialAdapter import MediationInterstitialAdapter
from android.gms.ads.mediation.MediationNativeAdapter import MediationNativeAdapter
from android.gms.ads.mediation.UnifiedNativeAdMapper import UnifiedNativeAdMapper
from android.gms.internal.ads.zzbnd import zzbnd
from android.gms.internal.ads.zzbvp import zzbvp

class zzbwm:
    def __init__(self, arg0: zzbvp) -> None: ...
    def zza(self, arg0: MediationBannerAdapter, arg1: str, arg2: str) -> None: ...
    @overload
    def onAdClicked(self, arg0: MediationBannerAdapter) -> None: ...
    @overload
    def onAdClicked(self, arg0: MediationInterstitialAdapter) -> None: ...
    @overload
    def onAdClicked(self, arg0: MediationNativeAdapter) -> None: ...
    @overload
    def onAdClosed(self, arg0: MediationBannerAdapter) -> None: ...
    @overload
    def onAdClosed(self, arg0: MediationInterstitialAdapter) -> None: ...
    @overload
    def onAdClosed(self, arg0: MediationNativeAdapter) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: MediationBannerAdapter, arg1: int) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: MediationBannerAdapter, arg1: AdError) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: MediationInterstitialAdapter, arg1: int) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: MediationInterstitialAdapter, arg1: AdError) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: MediationNativeAdapter, arg1: int) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: MediationNativeAdapter, arg1: AdError) -> None: ...
    @overload
    def onAdLeftApplication(self, arg0: MediationBannerAdapter) -> None: ...
    @overload
    def onAdLeftApplication(self, arg0: MediationInterstitialAdapter) -> None: ...
    @overload
    def onAdLeftApplication(self, arg0: MediationNativeAdapter) -> None: ...
    @overload
    def onAdOpened(self, arg0: MediationBannerAdapter) -> None: ...
    @overload
    def onAdOpened(self, arg0: MediationInterstitialAdapter) -> None: ...
    @overload
    def onAdOpened(self, arg0: MediationNativeAdapter) -> None: ...
    @overload
    def onAdLoaded(self, arg0: MediationBannerAdapter) -> None: ...
    @overload
    def onAdLoaded(self, arg0: MediationInterstitialAdapter) -> None: ...
    @overload
    def onAdLoaded(self, arg0: MediationNativeAdapter, arg1: UnifiedNativeAdMapper) -> None: ...
    def onAdImpression(self, arg0: MediationNativeAdapter) -> None: ...
    def onVideoEnd(self, arg0: MediationNativeAdapter) -> None: ...
    def zzb(self) -> UnifiedNativeAdMapper: ...
    def zzc(self, arg0: MediationNativeAdapter, arg1: zzbnd) -> None: ...
    def zzd(self, arg0: MediationNativeAdapter, arg1: zzbnd, arg2: str) -> None: ...
    def zze(self) -> zzbnd: ...
