from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zze import zze

class zzbxj:
    def zze(self, arg0: str) -> None: ...
    def zzf(self, arg0: str) -> None: ...
    def zzg(self, arg0: zze) -> None: ...
