from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzea import zzea
from android.gms.ads.internal.client.zzm import zzm
from android.gms.ads.internal.client.zzr import zzr
from android.gms.internal.ads.zzbma import zzbma
from android.gms.internal.ads.zzbvp import zzbvp
from android.gms.internal.ads.zzbwt import zzbwt
from android.gms.internal.ads.zzbww import zzbww
from android.gms.internal.ads.zzbwz import zzbwz
from android.gms.internal.ads.zzbxc import zzbxc
from android.gms.internal.ads.zzbxf import zzbxf
from android.gms.internal.ads.zzbxl import zzbxl
from android.gms.internal.ads.zzbxx import zzbxx

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper: ...  # com.google.android.gms.dynamic.IObjectWrapper
class Bundle: ...  # android.os.Bundle

class zzbxg:
    def zze(self, arg0: IObjectWrapper, arg1: str, arg2: Bundle, arg3: Bundle, arg4: zzr, arg5: zzbxl) -> None: ...
    def zzf(self) -> zzbxx: ...
    def zzg(self) -> zzbxx: ...
    def zzh(self) -> zzea: ...
    def zzi(self, arg0: str, arg1: str, arg2: zzm, arg3: IObjectWrapper, arg4: zzbww, arg5: zzbvp, arg6: zzr) -> None: ...
    def zzj(self, arg0: str, arg1: str, arg2: zzm, arg3: IObjectWrapper, arg4: zzbwz, arg5: zzbvp) -> None: ...
    def zzk(self, arg0: IObjectWrapper) -> bool: ...
    def zzl(self, arg0: str, arg1: str, arg2: zzm, arg3: IObjectWrapper, arg4: zzbxf, arg5: zzbvp) -> None: ...
    def zzm(self, arg0: IObjectWrapper) -> bool: ...
    def zzn(self, arg0: str, arg1: str, arg2: zzm, arg3: IObjectWrapper, arg4: zzbxc, arg5: zzbvp) -> None: ...
    def zzo(self, arg0: str) -> None: ...
    def zzp(self, arg0: str, arg1: str, arg2: zzm, arg3: IObjectWrapper, arg4: zzbxf, arg5: zzbvp) -> None: ...
    def zzq(self, arg0: str, arg1: str, arg2: zzm, arg3: IObjectWrapper, arg4: zzbww, arg5: zzbvp, arg6: zzr) -> None: ...
    def zzr(self, arg0: str, arg1: str, arg2: zzm, arg3: IObjectWrapper, arg4: zzbxc, arg5: zzbvp, arg6: zzbma) -> None: ...
    def zzs(self, arg0: str, arg1: str, arg2: zzm, arg3: IObjectWrapper, arg4: zzbwt, arg5: zzbvp) -> None: ...
    def zzt(self, arg0: IObjectWrapper) -> bool: ...
