from typing import Any, ClassVar, overload

class zzbxg:
    def zze(self, arg0: "IObjectWrapper", arg1: str, arg2: "Bundle", arg3: "Bundle", arg4: "zzr", arg5: "zzbxl") -> None: ...
    def zzf(self) -> "zzbxx": ...
    def zzg(self) -> "zzbxx": ...
    def zzh(self) -> "zzea": ...
    def zzi(self, arg0: str, arg1: str, arg2: "zzm", arg3: "IObjectWrapper", arg4: "zzbww", arg5: "zzbvp", arg6: "zzr") -> None: ...
    def zzj(self, arg0: str, arg1: str, arg2: "zzm", arg3: "IObjectWrapper", arg4: "zzbwz", arg5: "zzbvp") -> None: ...
    def zzk(self, arg0: "IObjectWrapper") -> bool: ...
    def zzl(self, arg0: str, arg1: str, arg2: "zzm", arg3: "IObjectWrapper", arg4: "zzbxf", arg5: "zzbvp") -> None: ...
    def zzm(self, arg0: "IObjectWrapper") -> bool: ...
    def zzn(self, arg0: str, arg1: str, arg2: "zzm", arg3: "IObjectWrapper", arg4: "zzbxc", arg5: "zzbvp") -> None: ...
    def zzo(self, arg0: str) -> None: ...
    def zzp(self, arg0: str, arg1: str, arg2: "zzm", arg3: "IObjectWrapper", arg4: "zzbxf", arg5: "zzbvp") -> None: ...
    def zzq(self, arg0: str, arg1: str, arg2: "zzm", arg3: "IObjectWrapper", arg4: "zzbww", arg5: "zzbvp", arg6: "zzr") -> None: ...
    def zzr(self, arg0: str, arg1: str, arg2: "zzm", arg3: "IObjectWrapper", arg4: "zzbxc", arg5: "zzbvp", arg6: "zzbma") -> None: ...
    def zzs(self, arg0: str, arg1: str, arg2: "zzm", arg3: "IObjectWrapper", arg4: "zzbwt", arg5: "zzbvp") -> None: ...
    def zzt(self, arg0: "IObjectWrapper") -> bool: ...
