from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzbml import zzbml

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Drawable: ...  # android.graphics.drawable.Drawable
class Uri: ...  # android.net.Uri

class zzbyr:
    def __init__(self, arg0: zzbml) -> None: ...
    def getDrawable(self) -> Drawable: ...
    def getUri(self) -> Uri: ...
    def getScale(self) -> float: ...
    def zza(self) -> int: ...
    def zzb(self) -> int: ...
