from typing import Any, ClassVar, overload
from android.gms.ads.MediaContent import MediaContent
from android.gms.ads.MuteThisAdListener import MuteThisAdListener
from android.gms.ads.MuteThisAdReason import MuteThisAdReason
from android.gms.ads.OnPaidEventListener import OnPaidEventListener
from android.gms.ads.ResponseInfo import ResponseInfo
from android.gms.internal.ads.zzboc import zzboc

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Bundle: ...  # android.os.Bundle
class Image: ...  # com.google.android.gms.ads.nativead.NativeAd.Image
class AdChoicesInfo: ...  # com.google.android.gms.ads.nativead.NativeAd.AdChoicesInfo
class UnconfirmedClickListener: ...  # com.google.android.gms.ads.nativead.NativeAd.UnconfirmedClickListener

class zzbys:
    def __init__(self, arg0: zzboc) -> None: ...
    def performClick(self, arg0: Bundle) -> None: ...
    def recordImpression(self, arg0: Bundle) -> bool: ...
    def reportTouchEvent(self, arg0: Bundle) -> None: ...
    def getHeadline(self) -> str: ...
    def getImages(self) -> list: ...
    def getBody(self) -> str: ...
    def getIcon(self) -> Image: ...
    def getCallToAction(self) -> str: ...
    def getStarRating(self) -> float: ...
    def getStore(self) -> str: ...
    def getPrice(self) -> str: ...
    def getAdChoicesInfo(self) -> AdChoicesInfo: ...
    def getExtras(self) -> Bundle: ...
    def enableCustomClickGesture(self) -> None: ...
    def isCustomClickGestureEnabled(self) -> bool: ...
    def recordCustomClickGesture(self) -> None: ...
    def getMuteThisAdReasons(self) -> list: ...
    def isCustomMuteThisAdEnabled(self) -> bool: ...
    def destroy(self) -> None: ...
    def setUnconfirmedClickListener(self, arg0: UnconfirmedClickListener) -> None: ...
    def muteThisAd(self, arg0: MuteThisAdReason) -> None: ...
    def setMuteThisAdListener(self, arg0: MuteThisAdListener) -> None: ...
    def cancelUnconfirmedClick(self) -> None: ...
    def getAdvertiser(self) -> str: ...
    def getMediaContent(self) -> MediaContent: ...
    def getResponseInfo(self) -> ResponseInfo: ...
    def setOnPaidEventListener(self, arg0: OnPaidEventListener) -> None: ...
    def recordEvent(self, arg0: Bundle) -> None: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
