from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Bundle: ...  # android.os.Bundle
class Intent: ...  # android.content.Intent
class IObjectWrapper: ...  # com.google.android.gms.dynamic.IObjectWrapper

class zzbzg:
    def zzh(self, arg0: Bundle) -> None: ...
    def zzi(self) -> None: ...
    def zzj(self) -> None: ...
    def zzk(self) -> None: ...
    def zzl(self) -> None: ...
    def zzo(self, arg0: Bundle) -> None: ...
    def zzp(self) -> None: ...
    def zzq(self) -> None: ...
    def zzs(self) -> None: ...
    def zze(self) -> None: ...
    def zzg(self) -> bool: ...
    def zzm(self, arg0: int, arg1: int, arg2: Intent) -> None: ...
    def zzn(self, arg0: IObjectWrapper) -> None: ...
    def zzf(self) -> None: ...
    def zzH(self, arg0: int, arg1: list[str], arg2: list[int]) -> None: ...
