from typing import Any, ClassVar, overload

class zzbzh:
    def __init__(self) -> None: ...
    @staticmethod
    def zzI(arg0: "IBinder") -> "zzbzi": ...
    def zzdd(self, arg0: int, arg1: "Parcel", arg2: "Parcel", arg3: int) -> bool: ...
