from typing import Any, ClassVar, overload

class zzbzz:
    def __init__(self, arg0: "Context", arg1: "AdFormat", arg2: "zzeh", arg3: str) -> None: ...
    @staticmethod
    def zza(arg0: "Context") -> "zzcet": ...
    def zzb(self, arg0: "QueryInfoGenerationCallback") -> None: ...
