from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzby import zzby
from android.gms.ads.internal.client.zzdx import zzdx
from android.gms.internal.ads.zzcbx import zzcbx
from android.gms.internal.ads.zzccc import zzccc
from android.gms.internal.ads.zzccd import zzccd

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...
class Bundle:
    """Forward declaration for ``android.os.Bundle``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Bundle')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Bundle
    """
    ...

class zzcbz:
    def zzb(self, arg0: zzccd) -> None: ...
    def zzc(self) -> None: ...
    def zzd(self, arg0: zzccc) -> None: ...
    def zze(self) -> bool: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzh(self) -> None: ...
    def zzi(self, arg0: IObjectWrapper) -> None: ...
    def zzj(self, arg0: IObjectWrapper) -> None: ...
    def zzk(self, arg0: IObjectWrapper) -> None: ...
    def zzl(self) -> str: ...
    def zzm(self, arg0: str) -> None: ...
    def zzn(self, arg0: zzby) -> None: ...
    def zzo(self) -> Bundle: ...
    def zzp(self, arg0: IObjectWrapper) -> None: ...
    def zzq(self, arg0: str) -> None: ...
    def zzr(self, arg0: bool) -> None: ...
    def zzs(self) -> bool: ...
    def zzt(self) -> zzdx: ...
    def zzu(self, arg0: zzcbx) -> None: ...
