from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzby import zzby
from android.gms.ads.internal.client.zzdx import zzdx
from android.gms.internal.ads.zzcbx import zzcbx
from android.gms.internal.ads.zzccc import zzccc
from android.gms.internal.ads.zzccd import zzccd

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper: ...  # com.google.android.gms.dynamic.IObjectWrapper
class Bundle: ...  # android.os.Bundle

class zzcbz:
    def zzb(self, arg0: zzccd) -> None: ...
    def zzc(self) -> None: ...
    def zzd(self, arg0: zzccc) -> None: ...
    def zze(self) -> bool: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzh(self) -> None: ...
    def zzi(self, arg0: IObjectWrapper) -> None: ...
    def zzj(self, arg0: IObjectWrapper) -> None: ...
    def zzk(self, arg0: IObjectWrapper) -> None: ...
    def zzl(self) -> str: ...
    def zzm(self, arg0: str) -> None: ...
    def zzn(self, arg0: zzby) -> None: ...
    def zzo(self) -> Bundle: ...
    def zzp(self, arg0: IObjectWrapper) -> None: ...
    def zzq(self, arg0: str) -> None: ...
    def zzr(self, arg0: bool) -> None: ...
    def zzs(self) -> bool: ...
    def zzt(self) -> zzdx: ...
    def zzu(self, arg0: zzcbx) -> None: ...
