from typing import Any, ClassVar, overload

class zzccc:
    def zze(self) -> None: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzh(self) -> None: ...
    def zzi(self, arg0: "zzcbw") -> None: ...
    def zzj(self) -> None: ...
    def zzk(self, arg0: int) -> None: ...
    def zzl(self) -> None: ...
