from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzdn import zzdn
from android.gms.ads.internal.client.zzdq import zzdq
from android.gms.ads.internal.client.zzdx import zzdx
from android.gms.ads.internal.client.zzm import zzm
from android.gms.internal.ads.zzccm import zzccm
from android.gms.internal.ads.zzccs import zzccs
from android.gms.internal.ads.zzccw import zzccw
from android.gms.internal.ads.zzccx import zzccx
from android.gms.internal.ads.zzcdd import zzcdd
from android.os.Bundle import Bundle

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...

class zzccp:
    def zzc(self, arg0: zzm, arg1: zzccw) -> None: ...
    def zze(self, arg0: zzccs) -> None: ...
    def zzi(self) -> bool: ...
    def zzj(self) -> str: ...
    def zzb(self, arg0: IObjectWrapper) -> None: ...
    def zzh(self, arg0: zzcdd) -> None: ...
    def zzf(self, arg0: zzdn) -> None: ...
    def zzg(self) -> Bundle: ...
    def zzk(self, arg0: IObjectWrapper, arg1: bool) -> None: ...
    def zzl(self) -> zzccm: ...
    def zzm(self) -> zzdx: ...
    def zzo(self, arg0: zzdq) -> None: ...
    def zzd(self, arg0: zzm, arg1: zzccw) -> None: ...
    def zzp(self, arg0: bool) -> None: ...
    def zzn(self) -> str: ...
    def zzq(self) -> int: ...
    def zzr(self, arg0: int) -> None: ...
    def zzs(self, arg0: zzccx) -> None: ...
