from typing import Any, ClassVar, overload

class zzccy:
    @overload
    def __init__(self, arg0: "Context", arg1: str, arg2: "zzccp") -> None: ...
    @overload
    def __init__(self, arg0: "Context", arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: "Context", arg1: "zzccp") -> None: ...
    def zza(self, arg0: "zzeh", arg1: "RewardedAdLoadCallback") -> None: ...
    def setServerSideVerificationOptions(self, arg0: "ServerSideVerificationOptions") -> None: ...
    def setOnAdMetadataChangedListener(self, arg0: "OnAdMetadataChangedListener") -> None: ...
    def getAdMetadata(self) -> "Bundle": ...
    def show(self, arg0: "Activity", arg1: "OnUserEarnedRewardListener") -> None: ...
    def getRewardItem(self) -> "RewardItem": ...
    def getResponseInfo(self) -> "ResponseInfo": ...
    def setOnPaidEventListener(self, arg0: "OnPaidEventListener") -> None: ...
    def getOnAdMetadataChangedListener(self) -> "OnAdMetadataChangedListener": ...
    def getOnPaidEventListener(self) -> "OnPaidEventListener": ...
    def setFullScreenContentCallback(self, arg0: "FullScreenContentCallback") -> None: ...
    def getFullScreenContentCallback(self) -> "FullScreenContentCallback": ...
    def getAdUnitId(self) -> str: ...
    def setImmersiveMode(self, arg0: bool) -> None: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
