from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zze import zze

class zzccu:
    def zze(self) -> None: ...
    def zzf(self, arg0: int) -> None: ...
    def zzg(self, arg0: zze) -> None: ...
