from typing import Any, ClassVar, overload
from android.gms.ads.FullScreenContentCallback import FullScreenContentCallback
from android.gms.ads.OnPaidEventListener import OnPaidEventListener
from android.gms.ads.OnUserEarnedRewardListener import OnUserEarnedRewardListener
from android.gms.ads.ResponseInfo import ResponseInfo
from android.gms.ads.internal.client.zzeh import zzeh
from android.gms.ads.rewarded.OnAdMetadataChangedListener import OnAdMetadataChangedListener
from android.gms.ads.rewarded.RewardItem import RewardItem
from android.gms.ads.rewarded.RewardedAdLoadCallback import RewardedAdLoadCallback
from android.gms.ads.rewarded.ServerSideVerificationOptions import ServerSideVerificationOptions
from android.gms.internal.ads.zzccp import zzccp

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class Bundle: ...  # android.os.Bundle
class Activity: ...  # android.app.Activity

class zzccy:
    @overload
    def __init__(self, arg0: Context, arg1: str, arg2: zzccp) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: zzccp) -> None: ...
    def zza(self, arg0: zzeh, arg1: RewardedAdLoadCallback) -> None: ...
    def setServerSideVerificationOptions(self, arg0: ServerSideVerificationOptions) -> None: ...
    def setOnAdMetadataChangedListener(self, arg0: OnAdMetadataChangedListener) -> None: ...
    def getAdMetadata(self) -> Bundle: ...
    def show(self, arg0: Activity, arg1: OnUserEarnedRewardListener) -> None: ...
    def getRewardItem(self) -> RewardItem: ...
    def getResponseInfo(self) -> ResponseInfo: ...
    def setOnPaidEventListener(self, arg0: OnPaidEventListener) -> None: ...
    def getOnAdMetadataChangedListener(self) -> OnAdMetadataChangedListener: ...
    def getOnPaidEventListener(self) -> OnPaidEventListener: ...
    def setFullScreenContentCallback(self, arg0: FullScreenContentCallback) -> None: ...
    def getFullScreenContentCallback(self) -> FullScreenContentCallback: ...
    def getAdUnitId(self) -> str: ...
    def setImmersiveMode(self, arg0: bool) -> None: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
