from typing import Any, ClassVar, overload

class zzcco:
    def __init__(self) -> None: ...
    @staticmethod
    def zzt(arg0: "IBinder") -> "zzccp": ...
    def zzdd(self, arg0: int, arg1: "Parcel", arg2: "Parcel", arg3: int) -> bool: ...
