from typing import Any, ClassVar, overload
from android.gms.ads.AdError import AdError
from android.gms.ads.rewarded.RewardItem import RewardItem
from android.gms.internal.ads.zzbvp import zzbvp

class zzcdf:
    def __init__(self, arg0: zzbvp) -> None: ...
    def onAdOpened(self) -> None: ...
    def onAdClosed(self) -> None: ...
    @overload
    def onUserEarnedReward(self, arg0: RewardItem) -> None: ...
    @overload
    def onUserEarnedReward(self) -> None: ...
    def reportAdClicked(self) -> None: ...
    def reportAdImpression(self) -> None: ...
    def onAdFailedToShow(self, arg0: AdError) -> None: ...
    def onVideoStart(self) -> None: ...
    def onVideoComplete(self) -> None: ...
