from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zze import zze
from android.gms.ads.rewardedinterstitial.RewardedInterstitialAdLoadCallback import RewardedInterstitialAdLoadCallback
from android.gms.internal.ads.zzcdj import zzcdj

class zzcdi:
    def __init__(self, arg0: RewardedInterstitialAdLoadCallback, arg1: zzcdj) -> None: ...
    def zze(self) -> None: ...
    def zzf(self, arg0: int) -> None: ...
    def zzg(self, arg0: zze) -> None: ...
