from typing import Any, ClassVar, overload
from android.gms.ads.rewarded.RewardItem import RewardItem

class zzcdg:
    @overload
    def __init__(self, arg0: RewardItem) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int) -> None: ...
    def zze(self) -> str: ...
    def zzf(self) -> int: ...
