from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzbzx import zzbzx
from android.gms.internal.ads.zzcaa import zzcaa
from android.gms.internal.ads.zzceq import zzceq
from android.gms.internal.ads.zzcex import zzcex

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper: ...  # com.google.android.gms.dynamic.IObjectWrapper

class zzcet:
    def zze(self, arg0: IObjectWrapper, arg1: zzcex, arg2: zzceq) -> None: ...
    def zzf(self, arg0: IObjectWrapper) -> None: ...
    def zzg(self, arg0: list, arg1: IObjectWrapper, arg2: zzbzx) -> None: ...
    def zzh(self, arg0: list, arg1: IObjectWrapper, arg2: zzbzx) -> None: ...
    def zzi(self, arg0: zzcaa) -> None: ...
    def zzj(self, arg0: IObjectWrapper) -> None: ...
    def zzk(self, arg0: list, arg1: IObjectWrapper, arg2: zzbzx) -> None: ...
    def zzl(self, arg0: list, arg1: IObjectWrapper, arg2: zzbzx) -> None: ...
    def zzm(self, arg0: IObjectWrapper, arg1: IObjectWrapper, arg2: str, arg3: IObjectWrapper) -> IObjectWrapper: ...
