from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle

class zzceo:
    def zzb(self, arg0: str) -> None: ...
    def zzc(self, arg0: str, arg1: str, arg2: Bundle) -> None: ...
