from typing import Any, ClassVar, overload

class zzcer:
    def zze(self, arg0: "IObjectWrapper", arg1: "zzcex", arg2: "zzceq") -> None: ...
    def zzf(self, arg0: "IObjectWrapper") -> None: ...
    def zzg(self, arg0: list, arg1: "IObjectWrapper", arg2: "zzbzx") -> None: ...
    def zzh(self, arg0: list, arg1: "IObjectWrapper", arg2: "zzbzx") -> None: ...
    def zzi(self, arg0: "zzcaa") -> None: ...
    def zzj(self, arg0: "IObjectWrapper") -> None: ...
    def zzk(self, arg0: list, arg1: "IObjectWrapper", arg2: "zzbzx") -> None: ...
    def zzl(self, arg0: list, arg1: "IObjectWrapper", arg2: "zzbzx") -> None: ...
    def zzm(self, arg0: "IObjectWrapper", arg1: "IObjectWrapper", arg2: str, arg3: "IObjectWrapper") -> "IObjectWrapper": ...
