from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzgai import zzgai

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class URL: ...  # java.net.URL
class URLConnection: ...  # java.net.URLConnection
class Network: ...  # android.net.Network
class HttpURLConnection: ...  # java.net.HttpURLConnection

class zzgas:
    def zzf(self, arg0: URL, arg1: int) -> URLConnection: ...
    def zzg(self, arg0: Network, arg1: URL, arg2: int, arg3: int) -> HttpURLConnection: ...
    def zzh(self, arg0: zzgai, arg1: int, arg2: int) -> HttpURLConnection: ...
    @staticmethod
    def zzi(arg0: HttpURLConnection) -> None: ...
    def zzj(self) -> HttpURLConnection: ...
    def close(self) -> None: ...
