from typing import Any, ClassVar, overload

class zzgax:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "Looper") -> None: ...
    def dispatchMessage(self, arg0: "Message") -> None: ...
    def zza(self, arg0: "Message") -> None: ...
