from typing import Any, ClassVar, overload

class zzgsz:
    @staticmethod
    def zza(arg0: str) -> str: ...
    @staticmethod
    def zzb(arg0: str) -> str: ...
    @staticmethod
    def zzc(arg0: str) -> bool: ...
    @staticmethod
    def zzd(arg0: str) -> bool: ...
    @staticmethod
    def zze(arg0: str, arg1: str) -> bool: ...
