from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzgti import zzgti

class zzgtp:
    @staticmethod
    def zzc() -> "zzgtp": ...
    @staticmethod
    def zzd(arg0: Any) -> "zzgtp": ...
    def zza(self, arg0: Any) -> Any: ...
    def zzb(self, arg0: zzgti) -> "zzgtp": ...
