from typing import Any, ClassVar, overload

class zzgug:
    @staticmethod
    def zza(arg0: "zzgtf") -> "zzgug": ...
    @staticmethod
    def zzb(arg0: "Pattern") -> "zzgug": ...
    @staticmethod
    def zzc(arg0: int) -> "zzgug": ...
    def zzd(self) -> "zzgug": ...
    def zze(self, arg0: "zzgtf") -> "zzgug": ...
    def zzf(self, arg0: str) -> "Iterable": ...
    def zzg(self, arg0: str) -> list: ...
