from typing import Any, ClassVar, overload

class zzict:
    def __init__(self) -> None: ...
    def zzaC(self) -> "zzict": ...
    def zzaD(self, arg0: "zzidp") -> "zzict": ...
    def zzaE(self, arg0: "zzidp", arg1: "zzidz") -> "zzict": ...
    def zzaF(self, arg0: "zzidl") -> "zzict": ...
    def zzaG(self, arg0: "zzidl", arg1: "zzidz") -> "zzict": ...
    def zzaH(self, arg0: list[int]) -> "zzict": ...
    def zzaI(self, arg0: list[int], arg1: int, arg2: int) -> "zzict": ...
    def zzaJ(self, arg0: list[int], arg1: "zzidz") -> "zzict": ...
    def zzaK(self, arg0: list[int], arg1: int, arg2: int, arg3: "zzidz") -> "zzict": ...
    def zzaL(self, arg0: "InputStream") -> "zzict": ...
    def zzaM(self, arg0: "InputStream", arg1: "zzidz") -> "zzict": ...
    def zzaN(self, arg0: "InputStream", arg1: "zzidz") -> bool: ...
    def zzaO(self, arg0: "InputStream") -> bool: ...
    def zzaP(self, arg0: "zzifz") -> "zzict": ...
    def zzaQ(self, arg0: "zzicu") -> "zzict": ...
    @staticmethod
    def zzaR(arg0: "zzifz") -> "zzihc": ...
    @staticmethod
    def zzaS(arg0: "Iterable", arg1: list) -> None: ...
    @staticmethod
    def zzaT(arg0: "Iterable", arg1: list) -> None: ...
