from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzidl import zzidl
from android.gms.internal.ads.zzige import zzige

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OutputStream: ...  # java.io.OutputStream
class Iterable: ...  # java.lang.Iterable

class zzicu:
    zzq: int
    def __init__(self) -> None: ...
    def zzaM(self) -> zzidl: ...
    def zzaN(self) -> list[int]: ...
    def zzaO(self, arg0: OutputStream) -> None: ...
    def zzaP(self, arg0: OutputStream) -> None: ...
    def zzaS(self) -> zzige: ...
    @staticmethod
    def zzaV(arg0: zzidl) -> None: ...
    @staticmethod
    def zzaW(arg0: Iterable, arg1: list) -> None: ...
