from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzidl import zzidl
from android.gms.internal.ads.zzidu import zzidu
from android.gms.internal.ads.zzify import zzify

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OutputStream: ...  # java.io.OutputStream

class zzicv:
    def __init__(self) -> None: ...
    def zzcY(self) -> zzify: ...
    def zzaM(self) -> zzidl: ...
    def zzaO(self, arg0: OutputStream) -> None: ...
    def zzcX(self, arg0: zzidu) -> None: ...
