from typing import Any, ClassVar, overload

class zzidk:
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    def zza(self) -> "zzidl": ...
    def zzb(self) -> int: ...
    def toString(self) -> str: ...
