from typing import Any, ClassVar, overload

class zzidu:
    def zzb(self, arg0: int, arg1: int) -> None: ...
    def zzc(self, arg0: int, arg1: int) -> None: ...
    def zzd(self, arg0: int, arg1: int) -> None: ...
    def zze(self, arg0: int, arg1: int) -> None: ...
    def zzf(self, arg0: int, arg1: int) -> None: ...
    def zzg(self, arg0: int, arg1: int) -> None: ...
    def zzh(self, arg0: int, arg1: bool) -> None: ...
    def zzi(self, arg0: int, arg1: str) -> None: ...
    def zzj(self, arg0: int, arg1: "zzidl") -> None: ...
    def zzm(self, arg0: int, arg1: "zzifz") -> None: ...
    def zzn(self, arg0: int, arg1: "zzidl") -> None: ...
    def zzq(self, arg0: int) -> None: ...
    def zzr(self, arg0: int) -> None: ...
    def zzs(self, arg0: int) -> None: ...
    def zzt(self, arg0: int) -> None: ...
    def zzu(self, arg0: int) -> None: ...
    def zzw(self, arg0: str) -> None: ...
    def zzk(self, arg0: "zzidl") -> None: ...
    def zzo(self, arg0: "zzifz") -> None: ...
    def zzp(self, arg0: int) -> None: ...
    @staticmethod
    def zzF(arg0: int) -> int: ...
    @staticmethod
    def zzG(arg0: int) -> int: ...
    @staticmethod
    def zzH(arg0: "zzifz") -> int: ...
    def zzx(self) -> None: ...
    def zzy(self) -> int: ...
    def zzI(self) -> None: ...
