from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzidl import zzidl
from android.gms.internal.ads.zzidp import zzidp
from android.gms.internal.ads.zzidu import zzidu
from android.gms.internal.ads.zzidz import zzidz
from android.gms.internal.ads.zziej import zziej
from android.gms.internal.ads.zzien import zzien
from android.gms.internal.ads.zzieo import zzieo
from android.gms.internal.ads.zzier import zzier
from android.gms.internal.ads.zzies import zzies
from android.gms.internal.ads.zzieu import zzieu
from android.gms.internal.ads.zziew import zziew
from android.gms.internal.ads.zziex import zziex
from android.gms.internal.ads.zzifa import zzifa
from android.gms.internal.ads.zzifb import zzifb
from android.gms.internal.ads.zzifz import zzifz
from android.gms.internal.ads.zzigh import zzigh
from android.gms.internal.ads.zzihe import zzihe
from android.gms.internal.ads.zzihq import zzihq

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class ByteBuffer: ...  # java.nio.ByteBuffer
class InputStream: ...  # java.io.InputStream

class zziep:
    zzt: zzihe
    def __init__(self) -> None: ...
    def zzbd(self) -> zzigh: ...
    def zzbe(self) -> "zziep": ...
    def zzbf(self) -> zziej: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def zzbj(self, arg0: int, arg1: zzidp) -> bool: ...
    def zzbk(self, arg0: int, arg1: int) -> None: ...
    def zzbl(self, arg0: int, arg1: zzidl) -> None: ...
    def zzbm(self) -> None: ...
    def zzbn(self) -> zziej: ...
    def zzbo(self, arg0: "zziep") -> zziej: ...
    def zzbi(self) -> bool: ...
    def zzbp(self) -> zziej: ...
    def zzdc(self, arg0: zzieo, arg1: Any, arg2: Any) -> Any: ...
    def zzcX(self, arg0: zzidu) -> None: ...
    def zzbr(self) -> int: ...
    @staticmethod
    def zzbu(arg0: type, arg1: "zziep") -> None: ...
    @staticmethod
    def zzbv(arg0: zzifz, arg1: str, arg2: list) -> Any: ...
    def zzbx(self, arg0: zzihe) -> None: ...
    @staticmethod
    def zzby(arg0: zzifz, arg1: Any, arg2: zzifz, arg3: zzieu, arg4: int, arg5: zzihq, arg6: type) -> zzien: ...
    @staticmethod
    def zzbz(arg0: zzifz, arg1: zzifz, arg2: zzieu, arg3: int, arg4: zzihq, arg5: bool, arg6: type) -> zzien: ...
    @staticmethod
    def zzbC() -> zziex: ...
    @staticmethod
    def zzbD(arg0: zziex) -> zziex: ...
    @staticmethod
    def zzbE() -> zzifa: ...
    @staticmethod
    def zzbF(arg0: zzifa) -> zzifa: ...
    @staticmethod
    def zzbG() -> zziew: ...
    @staticmethod
    def zzbH(arg0: zziew) -> zziew: ...
    @staticmethod
    def zzbI() -> zzies: ...
    @staticmethod
    def zzbJ(arg0: zzies) -> zzies: ...
    @staticmethod
    def zzbK() -> zzier: ...
    @staticmethod
    def zzbL(arg0: zzier) -> zzier: ...
    @staticmethod
    def zzbM() -> zzifb: ...
    @staticmethod
    def zzbN(arg0: zzifb) -> zzifb: ...
    @staticmethod
    def zzbP(arg0: "zziep", arg1: zzidp) -> "zziep": ...
    @staticmethod
    def zzbQ(arg0: "zziep", arg1: ByteBuffer, arg2: zzidz) -> "zziep": ...
    @staticmethod
    def zzbR(arg0: "zziep", arg1: ByteBuffer) -> "zziep": ...
    @staticmethod
    def zzbS(arg0: "zziep", arg1: zzidl) -> "zziep": ...
    @staticmethod
    def zzbT(arg0: "zziep", arg1: zzidl, arg2: zzidz) -> "zziep": ...
    @staticmethod
    def zzbU(arg0: "zziep", arg1: list[int]) -> "zziep": ...
    @staticmethod
    def zzbV(arg0: "zziep", arg1: list[int], arg2: zzidz) -> "zziep": ...
    @staticmethod
    def zzbW(arg0: "zziep", arg1: InputStream) -> "zziep": ...
    @staticmethod
    def zzbX(arg0: "zziep", arg1: InputStream, arg2: zzidz) -> "zziep": ...
    @staticmethod
    def zzbY(arg0: "zziep", arg1: zzidp) -> "zziep": ...
    @staticmethod
    def zzbZ(arg0: "zziep", arg1: zzidp, arg2: zzidz) -> "zziep": ...
    @staticmethod
    def zzca(arg0: "zziep", arg1: InputStream) -> "zziep": ...
    @staticmethod
    def zzcb(arg0: "zziep", arg1: InputStream, arg2: zzidz) -> "zziep": ...
