from typing import Any, ClassVar, overload

class zzied:
    def zza(self) -> int: ...
    def zzb(self) -> "zzihq": ...
    def zzc(self) -> "zzihr": ...
    def zzd(self) -> bool: ...
    def zze(self) -> bool: ...
