from typing import Any, ClassVar, overload
from android.gms.internal.ads.zzihq import zzihq
from android.gms.internal.ads.zzihr import zzihr

class zzied:
    def zza(self) -> int: ...
    def zzb(self) -> zzihq: ...
    def zzc(self) -> zzihr: ...
    def zzd(self) -> bool: ...
    def zze(self) -> bool: ...
