from typing import Any, ClassVar, overload

class zzifa:
    def zzc(self, arg0: int) -> int: ...
    def zzd(self, arg0: int) -> None: ...
    def zze(self, arg0: int, arg1: int) -> int: ...
    def zzf(self, arg0: int) -> "zzifa": ...
