from typing import Any, ClassVar, overload

class zzigh:
    def zzc(self, arg0: "zzidp", arg1: "zzidz") -> Any: ...
    def zzb(self, arg0: "zzidl", arg1: "zzidz") -> Any: ...
    def zza(self, arg0: "InputStream", arg1: "zzidz") -> Any: ...
