from typing import Any, ClassVar, overload

class zzihe:
    @staticmethod
    def zza() -> "zzihe": ...
    def zzd(self) -> None: ...
    def zzg(self, arg0: "zzihs") -> None: ...
    def zzh(self) -> int: ...
    def zzi(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
