from typing import Any, ClassVar, overload
from org.xmlpull.v1.XmlPullParser import XmlPullParser
from org.xmlpull.v1.XmlSerializer import XmlSerializer

class XmlPullParserFactory:
    PROPERTY_NAME: ClassVar[str]
    classNamesLocation: str
    features: dict
    parserClasses: list
    serializerClasses: list
    def __init__(self) -> None: ...
    def setFeature(self, arg0: str, arg1: bool) -> None: ...
    def getFeature(self, arg0: str) -> bool: ...
    def setNamespaceAware(self, arg0: bool) -> None: ...
    def isNamespaceAware(self) -> bool: ...
    def setValidating(self, arg0: bool) -> None: ...
    def isValidating(self) -> bool: ...
    def newPullParser(self) -> XmlPullParser: ...
    def newSerializer(self) -> XmlSerializer: ...
    @overload
    @staticmethod
    def newInstance() -> "XmlPullParserFactory": ...
    @overload
    @staticmethod
    def newInstance(arg0: str, arg1: type) -> "XmlPullParserFactory": ...
