from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.inputmethod.ExtractedText import ExtractedText

class ExtractEditText:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def startInternalChanges(self) -> None: ...
    def finishInternalChanges(self) -> None: ...
    def setExtractedText(self, arg0: ExtractedText) -> None: ...
    def onSelectionChanged(self, arg0: int, arg1: int) -> None: ...
    def performClick(self) -> bool: ...
    def onTextContextMenuItem(self, arg0: int) -> bool: ...
    def isInputMethodTarget(self) -> bool: ...
    def hasVerticalScrollBar(self) -> bool: ...
    def hasWindowFocus(self) -> bool: ...
    def isFocused(self) -> bool: ...
    def hasFocus(self) -> bool: ...
