from typing import Any, ClassVar, overload
from android.app.appsearch.AppSearchResult import AppSearchResult

class AppSearchBatchResult:
    def isSuccess(self) -> bool: ...
    def getSuccesses(self) -> dict: ...
    def getFailures(self) -> dict: ...
    def getAll(self) -> dict: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setSuccess(self, arg0: Any, arg1: Any) -> "Builder": ...
        def setFailure(self, arg0: Any, arg1: int, arg2: str) -> "Builder": ...
        def setResult(self, arg0: Any, arg1: AppSearchResult) -> "Builder": ...
        def build(self) -> "AppSearchBatchResult": ...
