from typing import Any, ClassVar, overload
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class AppSearchManager:
    def createSearchSession(self, arg0: "SearchContext", arg1: Executor, arg2: Consumer) -> None: ...
    def createGlobalSearchSession(self, arg0: Executor, arg1: Consumer) -> None: ...
    def createEnterpriseGlobalSearchSession(self, arg0: Executor, arg1: Consumer) -> None: ...

    class SearchContext:
        def getDatabaseName(self) -> str: ...

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def build(self) -> "SearchContext": ...
