from typing import Any, ClassVar, overload
from android.app.appsearch.PropertyPath import PropertyPath
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AppSearchSchema:
    CREATOR: ClassVar[Creator]
    def toString(self) -> str: ...
    def getSchemaType(self) -> str: ...
    def getProperties(self) -> list: ...
    def getParentTypes(self) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class BooleanPropertyConfig:

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setCardinality(self, arg0: int) -> "Builder": ...
            def build(self) -> "BooleanPropertyConfig": ...

    class Builder:
        def __init__(self, arg0: str) -> None: ...
        def addProperty(self, arg0: "PropertyConfig") -> "Builder": ...
        def addParentType(self, arg0: str) -> "Builder": ...
        def build(self) -> "AppSearchSchema": ...

    class BytesPropertyConfig:

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setCardinality(self, arg0: int) -> "Builder": ...
            def build(self) -> "BytesPropertyConfig": ...

    class DocumentPropertyConfig:
        def getSchemaType(self) -> str: ...
        def shouldIndexNestedProperties(self) -> bool: ...
        def getIndexableNestedProperties(self) -> list: ...

        class Builder:
            def __init__(self, arg0: str, arg1: str) -> None: ...
            def setCardinality(self, arg0: int) -> "Builder": ...
            def setShouldIndexNestedProperties(self, arg0: bool) -> "Builder": ...
            @overload
            def addIndexableNestedProperties(self, *arg0: str) -> "Builder": ...
            @overload
            def addIndexableNestedProperties(self, arg0: list) -> "Builder": ...
            @overload
            def addIndexableNestedPropertyPaths(self, *arg0: PropertyPath) -> "Builder": ...
            @overload
            def addIndexableNestedPropertyPaths(self, arg0: list) -> "Builder": ...
            def build(self) -> "DocumentPropertyConfig": ...

    class DoublePropertyConfig:

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setCardinality(self, arg0: int) -> "Builder": ...
            def build(self) -> "DoublePropertyConfig": ...

    class LongPropertyConfig:
        INDEXING_TYPE_NONE: ClassVar[int]
        INDEXING_TYPE_RANGE: ClassVar[int]
        def getIndexingType(self) -> int: ...

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setCardinality(self, arg0: int) -> "Builder": ...
            def setIndexingType(self, arg0: int) -> "Builder": ...
            def build(self) -> "LongPropertyConfig": ...

    class PropertyConfig:
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]
        def toString(self) -> str: ...
        def getName(self) -> str: ...
        def getCardinality(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class StringPropertyConfig:
        INDEXING_TYPE_EXACT_TERMS: ClassVar[int]
        INDEXING_TYPE_NONE: ClassVar[int]
        INDEXING_TYPE_PREFIXES: ClassVar[int]
        JOINABLE_VALUE_TYPE_NONE: ClassVar[int]
        JOINABLE_VALUE_TYPE_QUALIFIED_ID: ClassVar[int]
        TOKENIZER_TYPE_NONE: ClassVar[int]
        TOKENIZER_TYPE_PLAIN: ClassVar[int]
        TOKENIZER_TYPE_RFC822: ClassVar[int]
        TOKENIZER_TYPE_VERBATIM: ClassVar[int]
        def getIndexingType(self) -> int: ...
        def getTokenizerType(self) -> int: ...
        def getJoinableValueType(self) -> int: ...

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setCardinality(self, arg0: int) -> "Builder": ...
            def setIndexingType(self, arg0: int) -> "Builder": ...
            def setTokenizerType(self, arg0: int) -> "Builder": ...
            def setJoinableValueType(self, arg0: int) -> "Builder": ...
            def build(self) -> "StringPropertyConfig": ...
