from typing import Any, ClassVar, overload
from android.app.appsearch.BatchResultCallback import BatchResultCallback
from android.app.appsearch.GetByDocumentIdRequest import GetByDocumentIdRequest
from android.app.appsearch.PutDocumentsRequest import PutDocumentsRequest
from android.app.appsearch.RemoveByDocumentIdRequest import RemoveByDocumentIdRequest
from android.app.appsearch.ReportUsageRequest import ReportUsageRequest
from android.app.appsearch.SearchResults import SearchResults
from android.app.appsearch.SearchSpec import SearchSpec
from android.app.appsearch.SearchSuggestionSpec import SearchSuggestionSpec
from android.app.appsearch.SetSchemaRequest import SetSchemaRequest
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class AppSearchSession:
    def setSchema(self, arg0: SetSchemaRequest, arg1: Executor, arg2: Executor, arg3: Consumer) -> None: ...
    def getSchema(self, arg0: Executor, arg1: Consumer) -> None: ...
    def getNamespaces(self, arg0: Executor, arg1: Consumer) -> None: ...
    def put(self, arg0: PutDocumentsRequest, arg1: Executor, arg2: BatchResultCallback) -> None: ...
    def getByDocumentId(self, arg0: GetByDocumentIdRequest, arg1: Executor, arg2: BatchResultCallback) -> None: ...
    def search(self, arg0: str, arg1: SearchSpec) -> SearchResults: ...
    def searchSuggestion(self, arg0: str, arg1: SearchSuggestionSpec, arg2: Executor, arg3: Consumer) -> None: ...
    def reportUsage(self, arg0: ReportUsageRequest, arg1: Executor, arg2: Consumer) -> None: ...
    @overload
    def remove(self, arg0: RemoveByDocumentIdRequest, arg1: Executor, arg2: BatchResultCallback) -> None: ...
    @overload
    def remove(self, arg0: str, arg1: SearchSpec, arg2: Executor, arg3: Consumer) -> None: ...
    def getStorageInfo(self, arg0: Executor, arg1: Consumer) -> None: ...
    def close(self) -> None: ...
