from typing import Any, ClassVar, overload

class GenericDocument:
    def __init__(self, arg0: "GenericDocument") -> None: ...
    @staticmethod
    def getMaxIndexedProperties() -> int: ...
    def getId(self) -> str: ...
    def getNamespace(self) -> str: ...
    def getSchemaType(self) -> str: ...
    def getCreationTimestampMillis(self) -> int: ...
    def getTtlMillis(self) -> int: ...
    def getScore(self) -> int: ...
    def getPropertyNames(self) -> set: ...
    def getProperty(self, arg0: str) -> Any: ...
    def getPropertyString(self, arg0: str) -> str: ...
    def getPropertyLong(self, arg0: str) -> int: ...
    def getPropertyDouble(self, arg0: str) -> float: ...
    def getPropertyBoolean(self, arg0: str) -> bool: ...
    def getPropertyBytes(self, arg0: str) -> list[int]: ...
    def getPropertyDocument(self, arg0: str) -> "GenericDocument": ...
    def getPropertyStringArray(self, arg0: str) -> list[str]: ...
    def getPropertyLongArray(self, arg0: str) -> list[int]: ...
    def getPropertyDoubleArray(self, arg0: str) -> list[float]: ...
    def getPropertyBooleanArray(self, arg0: str) -> list[bool]: ...
    def getPropertyBytesArray(self, arg0: str) -> list[list[int]]: ...
    def getPropertyDocumentArray(self, arg0: str) -> list["GenericDocument"]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        @overload
        def __init__(self, arg0: str, arg1: str, arg2: str) -> None: ...
        @overload
        def __init__(self, arg0: "GenericDocument") -> None: ...
        def setNamespace(self, arg0: str) -> "Builder": ...
        def setId(self, arg0: str) -> "Builder": ...
        def setSchemaType(self, arg0: str) -> "Builder": ...
        def setScore(self, arg0: int) -> "Builder": ...
        def setCreationTimestampMillis(self, arg0: int) -> "Builder": ...
        def setTtlMillis(self, arg0: int) -> "Builder": ...
        def setPropertyString(self, arg0: str, *arg1: str) -> "Builder": ...
        def setPropertyBoolean(self, arg0: str, *arg1: bool) -> "Builder": ...
        def setPropertyLong(self, arg0: str, *arg1: int) -> "Builder": ...
        def setPropertyDouble(self, arg0: str, *arg1: float) -> "Builder": ...
        def setPropertyBytes(self, arg0: str, *arg1: list[int]) -> "Builder": ...
        def setPropertyDocument(self, arg0: str, *arg1: "GenericDocument") -> "Builder": ...
        def clearProperty(self, arg0: str) -> "Builder": ...
        def build(self) -> "GenericDocument": ...
