from typing import Any, ClassVar, overload
from android.app.appsearch.AppSearchSchema import AppSearchSchema
from android.app.appsearch.PackageIdentifier import PackageIdentifier
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class GetSchemaResponse:
    CREATOR: ClassVar[Creator]
    def getVersion(self) -> int: ...
    def getSchemas(self) -> set: ...
    def getSchemaTypesNotDisplayedBySystem(self) -> set: ...
    def getSchemaTypesVisibleToPackages(self) -> dict: ...
    def getRequiredPermissionsForSchemaTypeVisibility(self) -> dict: ...
    def getPubliclyVisibleSchemas(self) -> dict: ...
    def getSchemaTypesVisibleToConfigs(self) -> dict: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setVersion(self, arg0: int) -> "Builder": ...
        def addSchema(self, arg0: AppSearchSchema) -> "Builder": ...
        def addSchemaTypeNotDisplayedBySystem(self, arg0: str) -> "Builder": ...
        def setSchemaTypeVisibleToPackages(self, arg0: str, arg1: set) -> "Builder": ...
        def setRequiredPermissionsForSchemaTypeVisibility(self, arg0: str, arg1: set) -> "Builder": ...
        def setPubliclyVisibleSchema(self, arg0: str, arg1: PackageIdentifier) -> "Builder": ...
        def setSchemaTypeVisibleToConfigs(self, arg0: str, arg1: set) -> "Builder": ...
        def build(self) -> "GetSchemaResponse": ...
