from typing import Any, ClassVar, overload
from android.app.appsearch.BatchResultCallback import BatchResultCallback
from android.app.appsearch.GetByDocumentIdRequest import GetByDocumentIdRequest
from android.app.appsearch.ReportSystemUsageRequest import ReportSystemUsageRequest
from android.app.appsearch.SearchResults import SearchResults
from android.app.appsearch.SearchSpec import SearchSpec
from android.app.appsearch.observer.ObserverCallback import ObserverCallback
from android.app.appsearch.observer.ObserverSpec import ObserverSpec
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class GlobalSearchSession:
    def getByDocumentId(self, arg0: str, arg1: str, arg2: GetByDocumentIdRequest, arg3: Executor, arg4: BatchResultCallback) -> None: ...
    def search(self, arg0: str, arg1: SearchSpec) -> SearchResults: ...
    def getSchema(self, arg0: str, arg1: str, arg2: Executor, arg3: Consumer) -> None: ...
    def reportSystemUsage(self, arg0: ReportSystemUsageRequest, arg1: Executor, arg2: Consumer) -> None: ...
    def registerObserverCallback(self, arg0: str, arg1: ObserverSpec, arg2: Executor, arg3: ObserverCallback) -> None: ...
    def unregisterObserverCallback(self, arg0: str, arg1: ObserverCallback) -> None: ...
    def close(self) -> None: ...
