from typing import Any, ClassVar, overload
from android.app.appsearch.GenericDocument import GenericDocument

class Migrator:
    def __init__(self) -> None: ...
    def shouldMigrate(self, arg0: int, arg1: int) -> bool: ...
    def onUpgrade(self, arg0: int, arg1: int, arg2: GenericDocument) -> GenericDocument: ...
    def onDowngrade(self, arg0: int, arg1: int, arg2: GenericDocument) -> GenericDocument: ...
