from typing import Any, ClassVar, overload

class PackageIdentifier:
    def __init__(self, arg0: str, arg1: list[int]) -> None: ...
    def getPackageName(self) -> str: ...
    def getSha256Certificate(self) -> list[int]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
