from typing import Any, ClassVar, overload
from android.app.appsearch.GenericDocument import GenericDocument

class PutDocumentsRequest:
    def getGenericDocuments(self) -> list: ...
    def getTakenActionGenericDocuments(self) -> list: ...

    class Builder:
        def __init__(self) -> None: ...
        @overload
        def addGenericDocuments(self, *arg0: GenericDocument) -> "Builder": ...
        @overload
        def addGenericDocuments(self, arg0: list) -> "Builder": ...
        @overload
        def addTakenActionGenericDocuments(self, *arg0: GenericDocument) -> "Builder": ...
        @overload
        def addTakenActionGenericDocuments(self, arg0: list) -> "Builder": ...
        def build(self) -> "PutDocumentsRequest": ...
