from typing import Any, ClassVar, overload

class ReportSystemUsageRequest:
    def getPackageName(self) -> str: ...
    def getDatabaseName(self) -> str: ...
    def getNamespace(self) -> str: ...
    def getDocumentId(self) -> str: ...
    def getUsageTimestampMillis(self) -> int: ...

    class Builder:
        def __init__(self, arg0: str, arg1: str, arg2: str, arg3: str) -> None: ...
        def setUsageTimestampMillis(self, arg0: int) -> "Builder": ...
        def build(self) -> "ReportSystemUsageRequest": ...
