from typing import Any, ClassVar, overload
from android.app.appsearch.JoinSpec import JoinSpec
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SearchSpec:
    CREATOR: ClassVar[Creator]
    GROUPING_TYPE_PER_NAMESPACE: ClassVar[int]
    GROUPING_TYPE_PER_PACKAGE: ClassVar[int]
    GROUPING_TYPE_PER_SCHEMA: ClassVar[int]
    ORDER_ASCENDING: ClassVar[int]
    ORDER_DESCENDING: ClassVar[int]
    PROJECTION_SCHEMA_TYPE_WILDCARD: ClassVar[str]
    RANKING_STRATEGY_ADVANCED_RANKING_EXPRESSION: ClassVar[int]
    RANKING_STRATEGY_CREATION_TIMESTAMP: ClassVar[int]
    RANKING_STRATEGY_DOCUMENT_SCORE: ClassVar[int]
    RANKING_STRATEGY_JOIN_AGGREGATE_SCORE: ClassVar[int]
    RANKING_STRATEGY_NONE: ClassVar[int]
    RANKING_STRATEGY_RELEVANCE_SCORE: ClassVar[int]
    RANKING_STRATEGY_SYSTEM_USAGE_COUNT: ClassVar[int]
    RANKING_STRATEGY_SYSTEM_USAGE_LAST_USED_TIMESTAMP: ClassVar[int]
    RANKING_STRATEGY_USAGE_COUNT: ClassVar[int]
    RANKING_STRATEGY_USAGE_LAST_USED_TIMESTAMP: ClassVar[int]
    SCHEMA_TYPE_WILDCARD: ClassVar[str]
    TERM_MATCH_EXACT_ONLY: ClassVar[int]
    TERM_MATCH_PREFIX: ClassVar[int]
    def getTermMatch(self) -> int: ...
    def getFilterSchemas(self) -> list: ...
    def getFilterProperties(self) -> dict: ...
    def getFilterNamespaces(self) -> list: ...
    def getFilterPackageNames(self) -> list: ...
    def getResultCountPerPage(self) -> int: ...
    def getRankingStrategy(self) -> int: ...
    def getOrder(self) -> int: ...
    def getSnippetCount(self) -> int: ...
    def getSnippetCountPerProperty(self) -> int: ...
    def getMaxSnippetSize(self) -> int: ...
    def getProjections(self) -> dict: ...
    def getProjectionPaths(self) -> dict: ...
    def getPropertyWeights(self) -> dict: ...
    def getPropertyWeightPaths(self) -> dict: ...
    def getResultGroupingTypeFlags(self) -> int: ...
    def getResultGroupingLimit(self) -> int: ...
    def getJoinSpec(self) -> JoinSpec: ...
    def getAdvancedRankingExpression(self) -> str: ...
    def getSearchSourceLogTag(self) -> str: ...
    def isNumericSearchEnabled(self) -> bool: ...
    def isVerbatimSearchEnabled(self) -> bool: ...
    def isListFilterQueryLanguageEnabled(self) -> bool: ...
    def isListFilterHasPropertyFunctionEnabled(self) -> bool: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setTermMatch(self, arg0: int) -> "Builder": ...
        @overload
        def addFilterSchemas(self, *arg0: str) -> "Builder": ...
        @overload
        def addFilterSchemas(self, arg0: list) -> "Builder": ...
        def addFilterProperties(self, arg0: str, arg1: list) -> "Builder": ...
        def addFilterPropertyPaths(self, arg0: str, arg1: list) -> "Builder": ...
        @overload
        def addFilterNamespaces(self, *arg0: str) -> "Builder": ...
        @overload
        def addFilterNamespaces(self, arg0: list) -> "Builder": ...
        @overload
        def addFilterPackageNames(self, *arg0: str) -> "Builder": ...
        @overload
        def addFilterPackageNames(self, arg0: list) -> "Builder": ...
        def setResultCountPerPage(self, arg0: int) -> "Builder": ...
        @overload
        def setRankingStrategy(self, arg0: int) -> "Builder": ...
        @overload
        def setRankingStrategy(self, arg0: str) -> "Builder": ...
        def setSearchSourceLogTag(self, arg0: str) -> "Builder": ...
        def setOrder(self, arg0: int) -> "Builder": ...
        def setSnippetCount(self, arg0: int) -> "Builder": ...
        def setSnippetCountPerProperty(self, arg0: int) -> "Builder": ...
        def setMaxSnippetSize(self, arg0: int) -> "Builder": ...
        def addProjection(self, arg0: str, arg1: list) -> "Builder": ...
        def addProjectionPaths(self, arg0: str, arg1: list) -> "Builder": ...
        def setResultGrouping(self, arg0: int, arg1: int) -> "Builder": ...
        def setPropertyWeights(self, arg0: str, arg1: dict) -> "Builder": ...
        def setJoinSpec(self, arg0: JoinSpec) -> "Builder": ...
        def setPropertyWeightPaths(self, arg0: str, arg1: dict) -> "Builder": ...
        def setNumericSearchEnabled(self, arg0: bool) -> "Builder": ...
        def setVerbatimSearchEnabled(self, arg0: bool) -> "Builder": ...
        def setListFilterQueryLanguageEnabled(self, arg0: bool) -> "Builder": ...
        def setListFilterHasPropertyFunctionEnabled(self, arg0: bool) -> "Builder": ...
        def build(self) -> "SearchSpec": ...
