from typing import Any, ClassVar, overload
from android.app.appsearch.GenericDocument import GenericDocument
from android.app.appsearch.PropertyPath import PropertyPath
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SearchResult:
    CREATOR: ClassVar[Creator]
    def getGenericDocument(self) -> GenericDocument: ...
    def getMatchInfos(self) -> list: ...
    def getPackageName(self) -> str: ...
    def getDatabaseName(self) -> str: ...
    def getRankingSignal(self) -> float: ...
    def getJoinedResults(self) -> list: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self, arg0: str, arg1: str) -> None: ...
        def setGenericDocument(self, arg0: GenericDocument) -> "Builder": ...
        def addMatchInfo(self, arg0: "MatchInfo") -> "Builder": ...
        def setRankingSignal(self, arg0: float) -> "Builder": ...
        def addJoinedResult(self, arg0: "SearchResult") -> "Builder": ...
        def build(self) -> "SearchResult": ...

    class MatchInfo:
        CREATOR: ClassVar[Creator]
        def getPropertyPath(self) -> str: ...
        def getPropertyPathObject(self) -> PropertyPath: ...
        def getFullText(self) -> str: ...
        def getExactMatchRange(self) -> "MatchRange": ...
        def getExactMatch(self) -> str: ...
        def getSubmatchRange(self) -> "MatchRange": ...
        def getSubmatch(self) -> str: ...
        def getSnippetRange(self) -> "MatchRange": ...
        def getSnippet(self) -> str: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def describeContents(self) -> int: ...

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setExactMatchRange(self, arg0: "MatchRange") -> "Builder": ...
            def setSubmatchRange(self, arg0: "MatchRange") -> "Builder": ...
            def setSnippetRange(self, arg0: "MatchRange") -> "Builder": ...
            def build(self) -> "MatchInfo": ...

    class MatchRange:
        def __init__(self, arg0: int, arg1: int) -> None: ...
        def getStart(self) -> int: ...
        def getEnd(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
