from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.Executor import Executor
from java.util.concurrent.TimeUnit import TimeUnit

class AsyncTask:
    SERIAL_EXECUTOR: ClassVar[Executor]
    THREAD_POOL_EXECUTOR: ClassVar[Executor]
    def __init__(self) -> None: ...
    def getStatus(self) -> "Status": ...
    def doInBackground(self, *arg0: Any) -> Any: ...
    def onPreExecute(self) -> None: ...
    def onPostExecute(self, arg0: Any) -> None: ...
    def onProgressUpdate(self, *arg0: Any) -> None: ...
    @overload
    def onCancelled(self, arg0: Any) -> None: ...
    @overload
    def onCancelled(self) -> None: ...
    def isCancelled(self) -> bool: ...
    def cancel(self, arg0: bool) -> bool: ...
    @overload
    def get(self) -> Any: ...
    @overload
    def get(self, arg0: int, arg1: TimeUnit) -> Any: ...
    @overload
    def execute(self, *arg0: Any) -> "AsyncTask": ...
    @overload
    @staticmethod
    def execute(arg0: Runnable) -> None: ...
    def executeOnExecutor(self, arg0: Executor, *arg1: Any) -> "AsyncTask": ...
    def publishProgress(self, *arg0: Any) -> None: ...

    class Status:
        PENDING: ClassVar["Status"]
        RUNNING: ClassVar["Status"]
        FINISHED: ClassVar["Status"]
        @staticmethod
        def values() -> list["Status"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Status": ...
