from typing import Any, ClassVar, overload
from android.os.PersistableBundle import PersistableBundle

class BaseBundle:
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def clear(self) -> None: ...
    def containsKey(self, arg0: str) -> bool: ...
    def get(self, arg0: str) -> Any: ...
    def remove(self, arg0: str) -> None: ...
    def putAll(self, arg0: PersistableBundle) -> None: ...
    def keySet(self) -> set: ...
    def putBoolean(self, arg0: str, arg1: bool) -> None: ...
    def putInt(self, arg0: str, arg1: int) -> None: ...
    def putLong(self, arg0: str, arg1: int) -> None: ...
    def putDouble(self, arg0: str, arg1: float) -> None: ...
    def putString(self, arg0: str, arg1: str) -> None: ...
    def putBooleanArray(self, arg0: str, arg1: list[bool]) -> None: ...
    def putIntArray(self, arg0: str, arg1: list[int]) -> None: ...
    def putLongArray(self, arg0: str, arg1: list[int]) -> None: ...
    def putDoubleArray(self, arg0: str, arg1: list[float]) -> None: ...
    def putStringArray(self, arg0: str, arg1: list[str]) -> None: ...
    @overload
    def getBoolean(self, arg0: str) -> bool: ...
    @overload
    def getBoolean(self, arg0: str, arg1: bool) -> bool: ...
    @overload
    def getInt(self, arg0: str) -> int: ...
    @overload
    def getInt(self, arg0: str, arg1: int) -> int: ...
    @overload
    def getLong(self, arg0: str) -> int: ...
    @overload
    def getLong(self, arg0: str, arg1: int) -> int: ...
    @overload
    def getDouble(self, arg0: str) -> float: ...
    @overload
    def getDouble(self, arg0: str, arg1: float) -> float: ...
    @overload
    def getString(self, arg0: str) -> str: ...
    @overload
    def getString(self, arg0: str, arg1: str) -> str: ...
    def getBooleanArray(self, arg0: str) -> list[bool]: ...
    def getIntArray(self, arg0: str) -> list[int]: ...
    def getLongArray(self, arg0: str) -> list[int]: ...
    def getDoubleArray(self, arg0: str) -> list[float]: ...
    def getStringArray(self, arg0: str) -> list[str]: ...
