from typing import Any, ClassVar, overload
from android.os.IBinder import IBinder
from android.os.Parcel import Parcel
from android.os.Parcelable import Parcelable
from android.os.PersistableBundle import PersistableBundle
from android.util.Size import Size
from android.util.SizeF import SizeF
from android.util.SparseArray import SparseArray
from java.io.Serializable import Serializable
from java.lang.ClassLoader import ClassLoader

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Bundle:
    CREATOR: ClassVar[Creator]
    EMPTY: ClassVar["Bundle"]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ClassLoader) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: "Bundle") -> None: ...
    @overload
    def __init__(self, arg0: PersistableBundle) -> None: ...
    def setClassLoader(self, arg0: ClassLoader) -> None: ...
    def getClassLoader(self) -> ClassLoader: ...
    def clone(self) -> Any: ...
    def deepCopy(self) -> "Bundle": ...
    def clear(self) -> None: ...
    def remove(self, arg0: str) -> None: ...
    def putAll(self, arg0: "Bundle") -> None: ...
    def hasFileDescriptors(self) -> bool: ...
    def putByte(self, arg0: str, arg1: int) -> None: ...
    def putChar(self, arg0: str, arg1: str) -> None: ...
    def putShort(self, arg0: str, arg1: int) -> None: ...
    def putFloat(self, arg0: str, arg1: float) -> None: ...
    def putCharSequence(self, arg0: str, arg1: str) -> None: ...
    def putParcelable(self, arg0: str, arg1: Parcelable) -> None: ...
    def putSize(self, arg0: str, arg1: Size) -> None: ...
    def putSizeF(self, arg0: str, arg1: SizeF) -> None: ...
    def putParcelableArray(self, arg0: str, arg1: list[Parcelable]) -> None: ...
    def putParcelableArrayList(self, arg0: str, arg1: list) -> None: ...
    def putSparseParcelableArray(self, arg0: str, arg1: SparseArray) -> None: ...
    def putIntegerArrayList(self, arg0: str, arg1: list) -> None: ...
    def putStringArrayList(self, arg0: str, arg1: list) -> None: ...
    def putCharSequenceArrayList(self, arg0: str, arg1: list) -> None: ...
    def putSerializable(self, arg0: str, arg1: Serializable) -> None: ...
    def putByteArray(self, arg0: str, arg1: list[int]) -> None: ...
    def putShortArray(self, arg0: str, arg1: list[int]) -> None: ...
    def putCharArray(self, arg0: str, arg1: list[str]) -> None: ...
    def putFloatArray(self, arg0: str, arg1: list[float]) -> None: ...
    def putCharSequenceArray(self, arg0: str, arg1: list[str]) -> None: ...
    def putBundle(self, arg0: str, arg1: "Bundle") -> None: ...
    def putBinder(self, arg0: str, arg1: IBinder) -> None: ...
    @overload
    def getByte(self, arg0: str) -> int: ...
    @overload
    def getByte(self, arg0: str, arg1: int) -> int: ...
    @overload
    def getChar(self, arg0: str) -> str: ...
    @overload
    def getChar(self, arg0: str, arg1: str) -> str: ...
    @overload
    def getShort(self, arg0: str) -> int: ...
    @overload
    def getShort(self, arg0: str, arg1: int) -> int: ...
    @overload
    def getFloat(self, arg0: str) -> float: ...
    @overload
    def getFloat(self, arg0: str, arg1: float) -> float: ...
    @overload
    def getCharSequence(self, arg0: str) -> str: ...
    @overload
    def getCharSequence(self, arg0: str, arg1: str) -> str: ...
    def getSize(self, arg0: str) -> Size: ...
    def getSizeF(self, arg0: str) -> SizeF: ...
    def getBundle(self, arg0: str) -> "Bundle": ...
    @overload
    def getParcelable(self, arg0: str) -> Parcelable: ...
    @overload
    def getParcelable(self, arg0: str, arg1: type) -> Any: ...
    @overload
    def getParcelableArray(self, arg0: str) -> list[Parcelable]: ...
    @overload
    def getParcelableArray(self, arg0: str, arg1: type) -> list: ...
    @overload
    def getParcelableArrayList(self, arg0: str) -> list: ...
    @overload
    def getParcelableArrayList(self, arg0: str, arg1: type) -> list: ...
    @overload
    def getSparseParcelableArray(self, arg0: str) -> SparseArray: ...
    @overload
    def getSparseParcelableArray(self, arg0: str, arg1: type) -> SparseArray: ...
    @overload
    def getSerializable(self, arg0: str) -> Serializable: ...
    @overload
    def getSerializable(self, arg0: str, arg1: type) -> Serializable: ...
    def getIntegerArrayList(self, arg0: str) -> list: ...
    def getStringArrayList(self, arg0: str) -> list: ...
    def getCharSequenceArrayList(self, arg0: str) -> list: ...
    def getByteArray(self, arg0: str) -> list[int]: ...
    def getShortArray(self, arg0: str) -> list[int]: ...
    def getCharArray(self, arg0: str) -> list[str]: ...
    def getFloatArray(self, arg0: str) -> list[float]: ...
    def getCharSequenceArray(self, arg0: str) -> list[str]: ...
    def getBinder(self, arg0: str) -> IBinder: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def readFromParcel(self, arg0: Parcel) -> None: ...
    def toString(self) -> str: ...
