from typing import Any, ClassVar, overload

class CountDownTimer:
    def __init__(self, arg0: int, arg1: int) -> None: ...
    def cancel(self) -> None: ...
    def start(self) -> "CountDownTimer": ...
    def onTick(self, arg0: int) -> None: ...
    def onFinish(self) -> None: ...
