from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.io.FileDescriptor import FileDescriptor
from java.lang.ClassLoader import ClassLoader

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Debug:
    SHOW_CLASSLOADER: ClassVar[int]
    SHOW_FULL_DETAIL: ClassVar[int]
    SHOW_INITIALIZED: ClassVar[int]
    TRACE_COUNT_ALLOCS: ClassVar[int]
    @staticmethod
    def waitForDebugger() -> None: ...
    @staticmethod
    def waitingForDebugger() -> bool: ...
    @staticmethod
    def isDebuggerConnected() -> bool: ...
    @staticmethod
    def changeDebugPort(arg0: int) -> None: ...
    @staticmethod
    def startNativeTracing() -> None: ...
    @staticmethod
    def stopNativeTracing() -> None: ...
    @staticmethod
    def enableEmulatorTraceOutput() -> None: ...
    @overload
    @staticmethod
    def startMethodTracing() -> None: ...
    @overload
    @staticmethod
    def startMethodTracing(arg0: str) -> None: ...
    @overload
    @staticmethod
    def startMethodTracing(arg0: str, arg1: int) -> None: ...
    @overload
    @staticmethod
    def startMethodTracing(arg0: str, arg1: int, arg2: int) -> None: ...
    @staticmethod
    def startMethodTracingSampling(arg0: str, arg1: int, arg2: int) -> None: ...
    @staticmethod
    def stopMethodTracing() -> None: ...
    @staticmethod
    def threadCpuTimeNanos() -> int: ...
    @staticmethod
    def startAllocCounting() -> None: ...
    @staticmethod
    def stopAllocCounting() -> None: ...
    @staticmethod
    def getGlobalAllocCount() -> int: ...
    @staticmethod
    def resetGlobalAllocCount() -> None: ...
    @staticmethod
    def getGlobalAllocSize() -> int: ...
    @staticmethod
    def resetGlobalAllocSize() -> None: ...
    @staticmethod
    def getGlobalFreedCount() -> int: ...
    @staticmethod
    def resetGlobalFreedCount() -> None: ...
    @staticmethod
    def getGlobalFreedSize() -> int: ...
    @staticmethod
    def resetGlobalFreedSize() -> None: ...
    @staticmethod
    def getGlobalGcInvocationCount() -> int: ...
    @staticmethod
    def resetGlobalGcInvocationCount() -> None: ...
    @staticmethod
    def getGlobalClassInitCount() -> int: ...
    @staticmethod
    def resetGlobalClassInitCount() -> None: ...
    @staticmethod
    def getGlobalClassInitTime() -> int: ...
    @staticmethod
    def resetGlobalClassInitTime() -> None: ...
    @staticmethod
    def getGlobalExternalAllocCount() -> int: ...
    @staticmethod
    def resetGlobalExternalAllocSize() -> None: ...
    @staticmethod
    def resetGlobalExternalAllocCount() -> None: ...
    @staticmethod
    def getGlobalExternalAllocSize() -> int: ...
    @staticmethod
    def getGlobalExternalFreedCount() -> int: ...
    @staticmethod
    def resetGlobalExternalFreedCount() -> None: ...
    @staticmethod
    def getGlobalExternalFreedSize() -> int: ...
    @staticmethod
    def resetGlobalExternalFreedSize() -> None: ...
    @staticmethod
    def getThreadAllocCount() -> int: ...
    @staticmethod
    def resetThreadAllocCount() -> None: ...
    @staticmethod
    def getThreadAllocSize() -> int: ...
    @staticmethod
    def resetThreadAllocSize() -> None: ...
    @staticmethod
    def getThreadExternalAllocCount() -> int: ...
    @staticmethod
    def resetThreadExternalAllocCount() -> None: ...
    @staticmethod
    def getThreadExternalAllocSize() -> int: ...
    @staticmethod
    def resetThreadExternalAllocSize() -> None: ...
    @staticmethod
    def getThreadGcInvocationCount() -> int: ...
    @staticmethod
    def resetThreadGcInvocationCount() -> None: ...
    @staticmethod
    def resetAllCounts() -> None: ...
    @staticmethod
    def getRuntimeStat(arg0: str) -> str: ...
    @staticmethod
    def getRuntimeStats() -> dict: ...
    @staticmethod
    def getNativeHeapSize() -> int: ...
    @staticmethod
    def getNativeHeapAllocatedSize() -> int: ...
    @staticmethod
    def getNativeHeapFreeSize() -> int: ...
    @staticmethod
    def getMemoryInfo(arg0: "MemoryInfo") -> None: ...
    @staticmethod
    def getPss() -> int: ...
    @staticmethod
    def getRss() -> int: ...
    @staticmethod
    def setAllocationLimit(arg0: int) -> int: ...
    @staticmethod
    def setGlobalAllocationLimit(arg0: int) -> int: ...
    @staticmethod
    def printLoadedClasses(arg0: int) -> None: ...
    @staticmethod
    def getLoadedClassCount() -> int: ...
    @staticmethod
    def dumpHprofData(arg0: str) -> None: ...
    @staticmethod
    def getBinderSentTransactions() -> int: ...
    @staticmethod
    def getBinderReceivedTransactions() -> int: ...
    @staticmethod
    def getBinderLocalObjectCount() -> int: ...
    @staticmethod
    def getBinderProxyObjectCount() -> int: ...
    @staticmethod
    def getBinderDeathObjectCount() -> int: ...
    @staticmethod
    def dumpService(arg0: str, arg1: FileDescriptor, arg2: list[str]) -> bool: ...
    @staticmethod
    def attachJvmtiAgent(arg0: str, arg1: str, arg2: ClassLoader) -> None: ...

    class InstructionCount:
        def __init__(self) -> None: ...
        def resetAndStart(self) -> bool: ...
        def collect(self) -> bool: ...
        def globalTotal(self) -> int: ...
        def globalMethodInvocations(self) -> int: ...

    class MemoryInfo:
        CREATOR: ClassVar[Creator]
        dalvikPrivateDirty: int
        dalvikPss: int
        dalvikSharedDirty: int
        nativePrivateDirty: int
        nativePss: int
        nativeSharedDirty: int
        otherPrivateDirty: int
        otherPss: int
        otherSharedDirty: int
        def __init__(self) -> None: ...
        def getTotalPss(self) -> int: ...
        def getTotalSwappablePss(self) -> int: ...
        def getTotalPrivateDirty(self) -> int: ...
        def getTotalSharedDirty(self) -> int: ...
        def getTotalPrivateClean(self) -> int: ...
        def getTotalSharedClean(self) -> int: ...
        def getMemoryStat(self, arg0: str) -> str: ...
        def getMemoryStats(self) -> dict: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def readFromParcel(self, arg0: Parcel) -> None: ...
