from typing import Any, ClassVar, overload
from android.os.Looper import Looper
from android.os.Message import Message
from android.util.Printer import Printer
from java.lang.Runnable import Runnable

class Handler:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "Callback") -> None: ...
    @overload
    def __init__(self, arg0: Looper) -> None: ...
    @overload
    def __init__(self, arg0: Looper, arg1: "Callback") -> None: ...
    def handleMessage(self, arg0: Message) -> None: ...
    def dispatchMessage(self, arg0: Message) -> None: ...
    @overload
    @staticmethod
    def createAsync(arg0: Looper) -> "Handler": ...
    @overload
    @staticmethod
    def createAsync(arg0: Looper, arg1: "Callback") -> "Handler": ...
    def getMessageName(self, arg0: Message) -> str: ...
    @overload
    def obtainMessage(self) -> Message: ...
    @overload
    def obtainMessage(self, arg0: int) -> Message: ...
    @overload
    def obtainMessage(self, arg0: int, arg1: Any) -> Message: ...
    @overload
    def obtainMessage(self, arg0: int, arg1: int, arg2: int) -> Message: ...
    @overload
    def obtainMessage(self, arg0: int, arg1: int, arg2: int, arg3: Any) -> Message: ...
    def post(self, arg0: Runnable) -> bool: ...
    @overload
    def postAtTime(self, arg0: Runnable, arg1: int) -> bool: ...
    @overload
    def postAtTime(self, arg0: Runnable, arg1: Any, arg2: int) -> bool: ...
    @overload
    def postDelayed(self, arg0: Runnable, arg1: int) -> bool: ...
    @overload
    def postDelayed(self, arg0: Runnable, arg1: Any, arg2: int) -> bool: ...
    def postAtFrontOfQueue(self, arg0: Runnable) -> bool: ...
    @overload
    def removeCallbacks(self, arg0: Runnable) -> None: ...
    @overload
    def removeCallbacks(self, arg0: Runnable, arg1: Any) -> None: ...
    def sendMessage(self, arg0: Message) -> bool: ...
    def sendEmptyMessage(self, arg0: int) -> bool: ...
    def sendEmptyMessageDelayed(self, arg0: int, arg1: int) -> bool: ...
    def sendEmptyMessageAtTime(self, arg0: int, arg1: int) -> bool: ...
    def sendMessageDelayed(self, arg0: Message, arg1: int) -> bool: ...
    def sendMessageAtTime(self, arg0: Message, arg1: int) -> bool: ...
    def sendMessageAtFrontOfQueue(self, arg0: Message) -> bool: ...
    @overload
    def removeMessages(self, arg0: int) -> None: ...
    @overload
    def removeMessages(self, arg0: int, arg1: Any) -> None: ...
    def removeCallbacksAndMessages(self, arg0: Any) -> None: ...
    @overload
    def hasMessages(self, arg0: int) -> bool: ...
    @overload
    def hasMessages(self, arg0: int, arg1: Any) -> bool: ...
    def hasCallbacks(self, arg0: Runnable) -> bool: ...
    def getLooper(self) -> Looper: ...
    def dump(self, arg0: Printer, arg1: str) -> None: ...
    def toString(self) -> str: ...

    class Callback:
        def handleMessage(self, arg0: Message) -> bool: ...
