from typing import Any, ClassVar, overload
from java.io.FileDescriptor import FileDescriptor

class MessageQueue:
    def finalize(self) -> None: ...
    def isIdle(self) -> bool: ...
    def addIdleHandler(self, arg0: "IdleHandler") -> None: ...
    def removeIdleHandler(self, arg0: "IdleHandler") -> None: ...
    def addOnFileDescriptorEventListener(self, arg0: FileDescriptor, arg1: int, arg2: "OnFileDescriptorEventListener") -> None: ...
    def removeOnFileDescriptorEventListener(self, arg0: FileDescriptor) -> None: ...

    class IdleHandler:
        def queueIdle(self) -> bool: ...

    class OnFileDescriptorEventListener:
        EVENT_ERROR: ClassVar[int]
        EVENT_INPUT: ClassVar[int]
        EVENT_OUTPUT: ClassVar[int]
        def onFileDescriptorEvents(self, arg0: FileDescriptor, arg1: int) -> int: ...
