from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.lang.ClassLoader import ClassLoader

class Parcelable:
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class ClassLoaderCreator:
        def createFromParcel(self, arg0: Parcel, arg1: ClassLoader) -> Any: ...

    class Creator:
        def createFromParcel(self, arg0: Parcel) -> Any: ...
        def newArray(self, arg0: int) -> list: ...
