from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class PersistableBundle:
    CREATOR: ClassVar[Creator]
    EMPTY: ClassVar["PersistableBundle"]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: "PersistableBundle") -> None: ...
    def clone(self) -> Any: ...
    def deepCopy(self) -> "PersistableBundle": ...
    def putPersistableBundle(self, arg0: str, arg1: "PersistableBundle") -> None: ...
    def getPersistableBundle(self, arg0: str) -> "PersistableBundle": ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...
    def writeToStream(self, arg0: OutputStream) -> None: ...
    @staticmethod
    def readFromStream(arg0: InputStream) -> "PersistableBundle": ...
