from typing import Any, ClassVar, overload
from android.os.UserHandle import UserHandle

class Process:
    BLUETOOTH_UID: ClassVar[int]
    FIRST_APPLICATION_UID: ClassVar[int]
    INVALID_PID: ClassVar[int]
    INVALID_UID: ClassVar[int]
    LAST_APPLICATION_UID: ClassVar[int]
    PHONE_UID: ClassVar[int]
    ROOT_UID: ClassVar[int]
    SHELL_UID: ClassVar[int]
    SIGNAL_KILL: ClassVar[int]
    SIGNAL_QUIT: ClassVar[int]
    SIGNAL_USR1: ClassVar[int]
    SYSTEM_UID: ClassVar[int]
    THREAD_PRIORITY_AUDIO: ClassVar[int]
    THREAD_PRIORITY_BACKGROUND: ClassVar[int]
    THREAD_PRIORITY_DEFAULT: ClassVar[int]
    THREAD_PRIORITY_DISPLAY: ClassVar[int]
    THREAD_PRIORITY_FOREGROUND: ClassVar[int]
    THREAD_PRIORITY_LESS_FAVORABLE: ClassVar[int]
    THREAD_PRIORITY_LOWEST: ClassVar[int]
    THREAD_PRIORITY_MORE_FAVORABLE: ClassVar[int]
    THREAD_PRIORITY_URGENT_AUDIO: ClassVar[int]
    THREAD_PRIORITY_URGENT_DISPLAY: ClassVar[int]
    THREAD_PRIORITY_VIDEO: ClassVar[int]
    WIFI_UID: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def getElapsedCpuTime() -> int: ...
    @staticmethod
    def getStartElapsedRealtime() -> int: ...
    @staticmethod
    def getStartUptimeMillis() -> int: ...
    @staticmethod
    def getStartRequestedElapsedRealtime() -> int: ...
    @staticmethod
    def getStartRequestedUptimeMillis() -> int: ...
    @staticmethod
    def is64Bit() -> bool: ...
    @staticmethod
    def myPid() -> int: ...
    @staticmethod
    def myTid() -> int: ...
    @staticmethod
    def myUid() -> int: ...
    @staticmethod
    def myUserHandle() -> UserHandle: ...
    @staticmethod
    def isApplicationUid(arg0: int) -> bool: ...
    @staticmethod
    def isIsolated() -> bool: ...
    @staticmethod
    def isIsolatedUid(arg0: int) -> bool: ...
    @staticmethod
    def isSdkSandboxUid(arg0: int) -> bool: ...
    @staticmethod
    def getAppUidForSdkSandboxUid(arg0: int) -> int: ...
    @staticmethod
    def getSdkSandboxUidForAppUid(arg0: int) -> int: ...
    @staticmethod
    def isSdkSandbox() -> bool: ...
    @staticmethod
    def getUidForName(arg0: str) -> int: ...
    @staticmethod
    def getGidForName(arg0: str) -> int: ...
    @overload
    @staticmethod
    def setThreadPriority(arg0: int, arg1: int) -> None: ...
    @overload
    @staticmethod
    def setThreadPriority(arg0: int) -> None: ...
    @staticmethod
    def getExclusiveCores() -> list[int]: ...
    @staticmethod
    def getThreadPriority(arg0: int) -> int: ...
    @staticmethod
    def supportsProcesses() -> bool: ...
    @staticmethod
    def myProcessName() -> str: ...
    @staticmethod
    def killProcess(arg0: int) -> None: ...
    @staticmethod
    def sendSignal(arg0: int, arg1: int) -> None: ...
