from typing import Any, ClassVar, overload

class ProxyFileDescriptorCallback:
    def __init__(self) -> None: ...
    def onGetSize(self) -> int: ...
    def onRead(self, arg0: int, arg1: int, arg2: list[int]) -> int: ...
    def onWrite(self, arg0: int, arg1: int, arg2: list[int]) -> int: ...
    def onFsync(self) -> None: ...
    def onRelease(self) -> None: ...
