from typing import Any, ClassVar, overload
from android.content.Context import Context
from java.io.File import File

class RecoverySystem:
    @staticmethod
    def verifyPackage(arg0: File, arg1: "ProgressListener", arg2: File) -> None: ...
    @staticmethod
    def installPackage(arg0: Context, arg1: File) -> None: ...
    @staticmethod
    def rebootWipeUserData(arg0: Context) -> None: ...
    @staticmethod
    def rebootWipeCache(arg0: Context) -> None: ...

    class ProgressListener:
        def onProgress(self, arg0: int) -> None: ...
