from typing import Any, ClassVar, overload
from android.os.IInterface import IInterface

class RemoteCallbackList:
    def __init__(self) -> None: ...
    @overload
    def register(self, arg0: IInterface) -> bool: ...
    @overload
    def register(self, arg0: IInterface, arg1: Any) -> bool: ...
    def unregister(self, arg0: IInterface) -> bool: ...
    def kill(self) -> None: ...
    @overload
    def onCallbackDied(self, arg0: IInterface) -> None: ...
    @overload
    def onCallbackDied(self, arg0: IInterface, arg1: Any) -> None: ...
    def beginBroadcast(self) -> int: ...
    def getBroadcastItem(self, arg0: int) -> IInterface: ...
    def getBroadcastCookie(self, arg0: int) -> Any: ...
    def finishBroadcast(self) -> None: ...
    def getRegisteredCallbackCount(self) -> int: ...
    def getRegisteredCallbackItem(self, arg0: int) -> IInterface: ...
    def getRegisteredCallbackCookie(self, arg0: int) -> Any: ...
