from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.os.ParcelFileDescriptor import ParcelFileDescriptor
from java.nio.ByteBuffer import ByteBuffer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SharedMemory:
    CREATOR: ClassVar[Creator]
    @staticmethod
    def create(arg0: str, arg1: int) -> "SharedMemory": ...
    @staticmethod
    def fromFileDescriptor(arg0: ParcelFileDescriptor) -> "SharedMemory": ...
    def setProtect(self, arg0: int) -> bool: ...
    def getSize(self) -> int: ...
    def mapReadWrite(self) -> ByteBuffer: ...
    def mapReadOnly(self) -> ByteBuffer: ...
    def map(self, arg0: int, arg1: int, arg2: int) -> ByteBuffer: ...
    @staticmethod
    def unmap(arg0: ByteBuffer) -> None: ...
    def close(self) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
