from typing import Any, ClassVar, overload

class StatFs:
    def __init__(self, arg0: str) -> None: ...
    def restat(self, arg0: str) -> None: ...
    def getBlockSize(self) -> int: ...
    def getBlockSizeLong(self) -> int: ...
    def getBlockCount(self) -> int: ...
    def getBlockCountLong(self) -> int: ...
    def getFreeBlocks(self) -> int: ...
    def getFreeBlocksLong(self) -> int: ...
    def getFreeBytes(self) -> int: ...
    def getAvailableBlocks(self) -> int: ...
    def getAvailableBlocksLong(self) -> int: ...
    def getAvailableBytes(self) -> int: ...
    def getTotalBytes(self) -> int: ...
