from typing import Any, ClassVar, overload
from android.os.strictmode.Violation import Violation
from java.util.concurrent.Executor import Executor

class StrictMode:
    @staticmethod
    def setThreadPolicy(arg0: "ThreadPolicy") -> None: ...
    @staticmethod
    def getThreadPolicy() -> "ThreadPolicy": ...
    @staticmethod
    def allowThreadDiskWrites() -> "ThreadPolicy": ...
    @staticmethod
    def allowThreadDiskReads() -> "ThreadPolicy": ...
    @staticmethod
    def setVmPolicy(arg0: "VmPolicy") -> None: ...
    @staticmethod
    def getVmPolicy() -> "VmPolicy": ...
    @staticmethod
    def enableDefaults() -> None: ...
    @staticmethod
    def noteSlowCall(arg0: str) -> None: ...

    class OnThreadViolationListener:
        def onThreadViolation(self, arg0: Violation) -> None: ...

    class OnVmViolationListener:
        def onVmViolation(self, arg0: Violation) -> None: ...

    class ThreadPolicy:
        LAX: ClassVar["ThreadPolicy"]
        def toString(self) -> str: ...

        class Builder:
            @overload
            def __init__(self) -> None: ...
            @overload
            def __init__(self, arg0: "ThreadPolicy") -> None: ...
            def detectAll(self) -> "Builder": ...
            def permitAll(self) -> "Builder": ...
            def detectNetwork(self) -> "Builder": ...
            def permitNetwork(self) -> "Builder": ...
            def detectDiskReads(self) -> "Builder": ...
            def permitDiskReads(self) -> "Builder": ...
            def detectCustomSlowCalls(self) -> "Builder": ...
            def permitCustomSlowCalls(self) -> "Builder": ...
            def permitResourceMismatches(self) -> "Builder": ...
            def detectUnbufferedIo(self) -> "Builder": ...
            def permitUnbufferedIo(self) -> "Builder": ...
            def detectResourceMismatches(self) -> "Builder": ...
            def detectDiskWrites(self) -> "Builder": ...
            def permitDiskWrites(self) -> "Builder": ...
            def detectExplicitGc(self) -> "Builder": ...
            def permitExplicitGc(self) -> "Builder": ...
            def penaltyDialog(self) -> "Builder": ...
            def penaltyDeath(self) -> "Builder": ...
            def penaltyDeathOnNetwork(self) -> "Builder": ...
            def penaltyFlashScreen(self) -> "Builder": ...
            def penaltyLog(self) -> "Builder": ...
            def penaltyDropBox(self) -> "Builder": ...
            def penaltyListener(self, arg0: Executor, arg1: "OnThreadViolationListener") -> "Builder": ...
            def build(self) -> "ThreadPolicy": ...

    class VmPolicy:
        LAX: ClassVar["VmPolicy"]
        def toString(self) -> str: ...

        class Builder:
            @overload
            def __init__(self) -> None: ...
            @overload
            def __init__(self, arg0: "VmPolicy") -> None: ...
            def setClassInstanceLimit(self, arg0: type, arg1: int) -> "Builder": ...
            def detectActivityLeaks(self) -> "Builder": ...
            def detectNonSdkApiUsage(self) -> "Builder": ...
            def permitNonSdkApiUsage(self) -> "Builder": ...
            def detectAll(self) -> "Builder": ...
            def detectLeakedSqlLiteObjects(self) -> "Builder": ...
            def detectLeakedClosableObjects(self) -> "Builder": ...
            def detectLeakedRegistrationObjects(self) -> "Builder": ...
            def detectFileUriExposure(self) -> "Builder": ...
            def detectCleartextNetwork(self) -> "Builder": ...
            def detectContentUriWithoutPermission(self) -> "Builder": ...
            def detectUntaggedSockets(self) -> "Builder": ...
            def detectImplicitDirectBoot(self) -> "Builder": ...
            def detectCredentialProtectedWhileLocked(self) -> "Builder": ...
            def detectIncorrectContextUse(self) -> "Builder": ...
            def detectUnsafeIntentLaunch(self) -> "Builder": ...
            def permitUnsafeIntentLaunch(self) -> "Builder": ...
            def penaltyDeath(self) -> "Builder": ...
            def penaltyDeathOnCleartextNetwork(self) -> "Builder": ...
            def penaltyDeathOnFileUriExposure(self) -> "Builder": ...
            def penaltyLog(self) -> "Builder": ...
            def penaltyDropBox(self) -> "Builder": ...
            def penaltyListener(self, arg0: Executor, arg1: "OnVmViolationListener") -> "Builder": ...
            def build(self) -> "VmPolicy": ...
