from typing import Any, ClassVar, overload
from android.os.Handler import Handler
from android.os.Message import Message
from android.os.MessageQueue import MessageQueue
from java.lang.Runnable import Runnable

class TestLooperManager:
    def getMessageQueue(self) -> MessageQueue: ...
    def next(self) -> Message: ...
    def release(self) -> None: ...
    def execute(self, arg0: Message) -> None: ...
    def recycle(self, arg0: Message) -> None: ...
    @overload
    def hasMessages(self, arg0: Handler, arg1: Any, arg2: int) -> bool: ...
    @overload
    def hasMessages(self, arg0: Handler, arg1: Any, arg2: Runnable) -> bool: ...
