from typing import Any, ClassVar, overload

class Trace:
    @staticmethod
    def isEnabled() -> bool: ...
    @staticmethod
    def beginSection(arg0: str) -> None: ...
    @staticmethod
    def endSection() -> None: ...
    @staticmethod
    def beginAsyncSection(arg0: str, arg1: int) -> None: ...
    @staticmethod
    def endAsyncSection(arg0: str, arg1: int) -> None: ...
    @staticmethod
    def setCounter(arg0: str, arg1: int) -> None: ...
