from typing import Any, ClassVar, overload
from android.os.CombinedVibration import CombinedVibration
from android.os.VibrationAttributes import VibrationAttributes
from android.os.Vibrator import Vibrator

class VibratorManager:
    def getVibratorIds(self) -> list[int]: ...
    def getVibrator(self, arg0: int) -> Vibrator: ...
    def getDefaultVibrator(self) -> Vibrator: ...
    @overload
    def vibrate(self, arg0: CombinedVibration) -> None: ...
    @overload
    def vibrate(self, arg0: CombinedVibration, arg1: VibrationAttributes) -> None: ...
    def cancel(self) -> None: ...
