from typing import Any, ClassVar, overload

class WorkDuration:
    def __init__(self) -> None: ...
    def setActualTotalDurationNanos(self, arg0: int) -> None: ...
    def setWorkPeriodStartTimestampNanos(self, arg0: int) -> None: ...
    def setActualCpuDurationNanos(self, arg0: int) -> None: ...
    def setActualGpuDurationNanos(self, arg0: int) -> None: ...
    def getActualTotalDurationNanos(self) -> int: ...
    def getWorkPeriodStartTimestampNanos(self) -> int: ...
    def getActualCpuDurationNanos(self) -> int: ...
    def getActualGpuDurationNanos(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
