from typing import Any, ClassVar, overload

class RewardedInterstitialAd:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def load(arg0: "Context", arg1: str, arg2: "AdRequest", arg3: "RewardedInterstitialAdLoadCallback") -> None: ...
    @overload
    @staticmethod
    def load(arg0: "Context", arg1: str, arg2: "AdManagerAdRequest", arg3: "RewardedInterstitialAdLoadCallback") -> None: ...
    def setFullScreenContentCallback(self, arg0: "FullScreenContentCallback") -> None: ...
    def getFullScreenContentCallback(self) -> "FullScreenContentCallback": ...
    def setServerSideVerificationOptions(self, arg0: "ServerSideVerificationOptions") -> None: ...
    def setOnAdMetadataChangedListener(self, arg0: "OnAdMetadataChangedListener") -> None: ...
    def getOnAdMetadataChangedListener(self) -> "OnAdMetadataChangedListener": ...
    def setOnPaidEventListener(self, arg0: "OnPaidEventListener") -> None: ...
    def getOnPaidEventListener(self) -> "OnPaidEventListener": ...
    def getAdMetadata(self) -> "Bundle": ...
    def getRewardItem(self) -> "RewardItem": ...
    def getResponseInfo(self) -> "ResponseInfo": ...
    def show(self, arg0: "Activity", arg1: "OnUserEarnedRewardListener") -> None: ...
    def getAdUnitId(self) -> str: ...
    def setImmersiveMode(self, arg0: bool) -> None: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
