from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.Context import Context
from android.gms.ads.AdRequest import AdRequest
from android.gms.ads.FullScreenContentCallback import FullScreenContentCallback
from android.gms.ads.OnPaidEventListener import OnPaidEventListener
from android.gms.ads.OnUserEarnedRewardListener import OnUserEarnedRewardListener
from android.gms.ads.ResponseInfo import ResponseInfo
from android.gms.ads.admanager.AdManagerAdRequest import AdManagerAdRequest
from android.gms.ads.rewarded.OnAdMetadataChangedListener import OnAdMetadataChangedListener
from android.gms.ads.rewarded.RewardItem import RewardItem
from android.gms.ads.rewarded.ServerSideVerificationOptions import ServerSideVerificationOptions
from android.gms.ads.rewardedinterstitial.RewardedInterstitialAdLoadCallback import RewardedInterstitialAdLoadCallback
from android.os.Bundle import Bundle

class RewardedInterstitialAd:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def load(arg0: Context, arg1: str, arg2: AdRequest, arg3: RewardedInterstitialAdLoadCallback) -> None: ...
    @overload
    @staticmethod
    def load(arg0: Context, arg1: str, arg2: AdManagerAdRequest, arg3: RewardedInterstitialAdLoadCallback) -> None: ...
    def setFullScreenContentCallback(self, arg0: FullScreenContentCallback) -> None: ...
    def getFullScreenContentCallback(self) -> FullScreenContentCallback: ...
    def setServerSideVerificationOptions(self, arg0: ServerSideVerificationOptions) -> None: ...
    def setOnAdMetadataChangedListener(self, arg0: OnAdMetadataChangedListener) -> None: ...
    def getOnAdMetadataChangedListener(self) -> OnAdMetadataChangedListener: ...
    def setOnPaidEventListener(self, arg0: OnPaidEventListener) -> None: ...
    def getOnPaidEventListener(self) -> OnPaidEventListener: ...
    def getAdMetadata(self) -> Bundle: ...
    def getRewardItem(self) -> RewardItem: ...
    def getResponseInfo(self) -> ResponseInfo: ...
    def show(self, arg0: Activity, arg1: OnUserEarnedRewardListener) -> None: ...
    def getAdUnitId(self) -> str: ...
    def setImmersiveMode(self, arg0: bool) -> None: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
