from typing import Any, ClassVar, overload

class PreloadConfiguration:
    def getAdUnitId(self) -> str: ...
    def getAdFormat(self) -> "AdFormat": ...
    def getAdRequest(self) -> "AdRequest": ...
    def getBufferSize(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, arg0: str, arg1: "AdFormat") -> None: ...
        @overload
        def __init__(self, arg0: str) -> None: ...
        def setAdRequest(self, arg0: "AdRequest") -> "Builder": ...
        def setBufferSize(self, arg0: int) -> "Builder": ...
        def build(self) -> "PreloadConfiguration": ...
