from typing import Any, ClassVar, overload

class PreloadCallbackV2:
    def __init__(self) -> None: ...
    def onAdsExhausted(self, arg0: str) -> None: ...
    def onAdPreloaded(self, arg0: str, arg1: "ResponseInfo") -> None: ...
    def onAdFailedToPreload(self, arg0: str, arg1: "AdError") -> None: ...
