from typing import Any, ClassVar, overload
from android.gms.ads.AdFormat import AdFormat
from android.gms.ads.internal.client.zzch import zzch
from android.gms.ads.preload.PreloadCallbackV2 import PreloadCallbackV2
from android.gms.ads.preload.PreloadConfiguration import PreloadConfiguration

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context

class zzb:
    zza: zzch
    def __init__(self, arg0: Context, arg1: AdFormat) -> None: ...
    def zzb(self, arg0: str, arg1: PreloadConfiguration, arg2: PreloadCallbackV2) -> bool: ...
    def zzc(self, arg0: str, arg1: PreloadConfiguration) -> bool: ...
    def zzd(self, arg0: str) -> bool: ...
    def zze(self, arg0: str) -> int: ...
    def zzf(self, arg0: str) -> bool: ...
    def zzg(self) -> None: ...
    def zzh(self) -> dict: ...
    def zzi(self, arg0: str) -> PreloadConfiguration: ...
    def zzj(self) -> Context: ...
