from typing import Any, ClassVar, overload
from influence.domain.OSInfluenceChannel import OSInfluenceChannel

class OSCachedUniqueOutcome:
    def __init__(self, arg0: str, arg1: OSInfluenceChannel) -> None: ...
    def getInfluenceId(self) -> str: ...
    def getChannel(self) -> OSInfluenceChannel: ...
