from typing import Any, ClassVar, overload

class OSOutcomeSourceBody:
    @overload
    def __init__(self, arg0: "JSONArray", arg1: "JSONArray") -> None: ...
    @overload
    def __init__(self, arg0: "JSONArray") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getNotificationIds(self) -> "JSONArray": ...
    def setNotificationIds(self, arg0: "JSONArray") -> None: ...
    def getInAppMessagesIds(self) -> "JSONArray": ...
    def setInAppMessagesIds(self, arg0: "JSONArray") -> None: ...
    def toJSONObject(self) -> "JSONObject": ...
    def toString(self) -> str: ...
