from typing import Any, ClassVar, overload
from outcomes.domain.OSOutcomeSourceBody import OSOutcomeSourceBody

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class OSOutcomeSource:
    def __init__(self, arg0: OSOutcomeSourceBody, arg1: OSOutcomeSourceBody) -> None: ...
    def getDirectBody(self) -> OSOutcomeSourceBody: ...
    @overload
    def setDirectBody(self, arg0: OSOutcomeSourceBody) -> None: ...
    @overload
    def setDirectBody(self, arg0: OSOutcomeSourceBody) -> "OSOutcomeSource": ...
    def getIndirectBody(self) -> OSOutcomeSourceBody: ...
    @overload
    def setIndirectBody(self, arg0: OSOutcomeSourceBody) -> None: ...
    @overload
    def setIndirectBody(self, arg0: OSOutcomeSourceBody) -> "OSOutcomeSource": ...
    def toJSONObject(self) -> JSONObject: ...
    def toString(self) -> str: ...
