from typing import Any, ClassVar, overload
from java.sql.Connection import Connection
from javax.sql.ConnectionEventListener import ConnectionEventListener
from javax.sql.StatementEventListener import StatementEventListener

class PooledConnection:
    def getConnection(self) -> Connection: ...
    def close(self) -> None: ...
    def addConnectionEventListener(self, arg0: ConnectionEventListener) -> None: ...
    def removeConnectionEventListener(self, arg0: ConnectionEventListener) -> None: ...
    def addStatementEventListener(self, arg0: StatementEventListener) -> None: ...
    def removeStatementEventListener(self, arg0: StatementEventListener) -> None: ...
