from typing import Any, ClassVar, overload
from java.sql.Connection import Connection
from java.sql.ResultSet import ResultSet
from javax.sql.RowSetMetaData import RowSetMetaData

class RowSetInternal:
    def getParams(self) -> list: ...
    def getConnection(self) -> Connection: ...
    def setMetaData(self, arg0: RowSetMetaData) -> None: ...
    def getOriginal(self) -> ResultSet: ...
    def getOriginalRow(self) -> ResultSet: ...
