from typing import Any, ClassVar, overload
from javax.sql.RowSetEvent import RowSetEvent

class RowSetListener:
    def rowSetChanged(self, arg0: RowSetEvent) -> None: ...
    def rowChanged(self, arg0: RowSetEvent) -> None: ...
    def cursorMoved(self, arg0: RowSetEvent) -> None: ...
