from typing import Any, ClassVar, overload

class RenderParams:
    FLAG_RENDER_HIGHLIGHT_ANNOTATIONS: ClassVar[int]
    FLAG_RENDER_TEXT_ANNOTATIONS: ClassVar[int]
    RENDER_MODE_FOR_DISPLAY: ClassVar[int]
    RENDER_MODE_FOR_PRINT: ClassVar[int]
    def getRenderMode(self) -> int: ...
    def getRenderFlags(self) -> int: ...

    class Builder:
        def __init__(self, arg0: int) -> None: ...
        @overload
        def setRenderFlags(self, arg0: int) -> "Builder": ...
        @overload
        def setRenderFlags(self, arg0: int, arg1: int) -> "Builder": ...
        def build(self) -> "RenderParams": ...
