from typing import Any, ClassVar, overload
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.Chronology import Chronology
from java.time.format.ResolverStyle import ResolverStyle

class AbstractChronology:
    def __init__(self) -> None: ...
    def resolveDate(self, arg0: dict, arg1: ResolverStyle) -> ChronoLocalDate: ...
    def compareTo(self, arg0: Chronology) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
