from typing import Any, ClassVar, overload
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.Chronology import Chronology
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalUnit import TemporalUnit

class ChronoPeriod:
    @staticmethod
    def between(arg0: ChronoLocalDate, arg1: ChronoLocalDate) -> "ChronoPeriod": ...
    def get(self, arg0: TemporalUnit) -> int: ...
    def getUnits(self) -> list: ...
    def getChronology(self) -> Chronology: ...
    def isZero(self) -> bool: ...
    def isNegative(self) -> bool: ...
    def plus(self, arg0: TemporalAmount) -> "ChronoPeriod": ...
    def minus(self, arg0: TemporalAmount) -> "ChronoPeriod": ...
    def multipliedBy(self, arg0: int) -> "ChronoPeriod": ...
    def negated(self) -> "ChronoPeriod": ...
    def normalized(self) -> "ChronoPeriod": ...
    def addTo(self, arg0: Temporal) -> Temporal: ...
    def subtractFrom(self, arg0: Temporal) -> Temporal: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
