from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Chronology import Chronology
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.util.Comparator import Comparator

class ChronoLocalDateTime:
    @staticmethod
    def timeLineOrder() -> Comparator: ...
    @staticmethod
    def from_(arg0: TemporalAccessor) -> "ChronoLocalDateTime": ...
    def getChronology(self) -> Chronology: ...
    def toLocalDate(self) -> ChronoLocalDate: ...
    def toLocalTime(self) -> LocalTime: ...
    @overload
    def isSupported(self, arg0: TemporalField) -> bool: ...
    @overload
    def isSupported(self, arg0: TemporalUnit) -> bool: ...
    @overload
    def with_(self, arg0: TemporalAdjuster) -> "ChronoLocalDateTime": ...
    @overload
    def with_(self, arg0: TemporalField, arg1: int) -> "ChronoLocalDateTime": ...
    @overload
    def plus(self, arg0: TemporalAmount) -> "ChronoLocalDateTime": ...
    @overload
    def plus(self, arg0: int, arg1: TemporalUnit) -> "ChronoLocalDateTime": ...
    @overload
    def minus(self, arg0: TemporalAmount) -> "ChronoLocalDateTime": ...
    @overload
    def minus(self, arg0: int, arg1: TemporalUnit) -> "ChronoLocalDateTime": ...
    def query(self, arg0: TemporalQuery) -> Any: ...
    def adjustInto(self, arg0: Temporal) -> Temporal: ...
    def format(self, arg0: DateTimeFormatter) -> str: ...
    def atZone(self, arg0: ZoneId) -> ChronoZonedDateTime: ...
    def toInstant(self, arg0: ZoneOffset) -> Instant: ...
    def toEpochSecond(self, arg0: ZoneOffset) -> int: ...
    def compareTo(self, arg0: "ChronoLocalDateTime") -> int: ...
    def isAfter(self, arg0: "ChronoLocalDateTime") -> bool: ...
    def isBefore(self, arg0: "ChronoLocalDateTime") -> bool: ...
    def isEqual(self, arg0: "ChronoLocalDateTime") -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
