from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Era import Era
from java.time.format.ResolverStyle import ResolverStyle
from java.time.format.TextStyle import TextStyle
from java.time.temporal.ChronoField import ChronoField
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class Chronology:
    @staticmethod
    def from_(arg0: TemporalAccessor) -> "Chronology": ...
    @staticmethod
    def ofLocale(arg0: Locale) -> "Chronology": ...
    @staticmethod
    def of(arg0: str) -> "Chronology": ...
    @staticmethod
    def getAvailableChronologies() -> set: ...
    def getId(self) -> str: ...
    def getCalendarType(self) -> str: ...
    @overload
    def date(self, arg0: Era, arg1: int, arg2: int, arg3: int) -> ChronoLocalDate: ...
    @overload
    def date(self, arg0: int, arg1: int, arg2: int) -> ChronoLocalDate: ...
    @overload
    def date(self, arg0: TemporalAccessor) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, arg0: Era, arg1: int, arg2: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, arg0: int, arg1: int) -> ChronoLocalDate: ...
    def dateEpochDay(self, arg0: int) -> ChronoLocalDate: ...
    @overload
    def dateNow(self) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, arg0: ZoneId) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, arg0: Clock) -> ChronoLocalDate: ...
    def localDateTime(self, arg0: TemporalAccessor) -> ChronoLocalDateTime: ...
    @overload
    def zonedDateTime(self, arg0: TemporalAccessor) -> ChronoZonedDateTime: ...
    @overload
    def zonedDateTime(self, arg0: Instant, arg1: ZoneId) -> ChronoZonedDateTime: ...
    def isLeapYear(self, arg0: int) -> bool: ...
    def prolepticYear(self, arg0: Era, arg1: int) -> int: ...
    def eraOf(self, arg0: int) -> Era: ...
    def eras(self) -> list: ...
    def range(self, arg0: ChronoField) -> ValueRange: ...
    def getDisplayName(self, arg0: TextStyle, arg1: Locale) -> str: ...
    def resolveDate(self, arg0: dict, arg1: ResolverStyle) -> ChronoLocalDate: ...
    def period(self, arg0: int, arg1: int, arg2: int) -> ChronoPeriod: ...
    @overload
    def epochSecond(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: ZoneOffset) -> int: ...
    @overload
    def epochSecond(self, arg0: Era, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: ZoneOffset) -> int: ...
    def compareTo(self, arg0: "Chronology") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
