from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class Era:
    def getValue(self) -> int: ...
    def isSupported(self, arg0: TemporalField) -> bool: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def get(self, arg0: TemporalField) -> int: ...
    def getLong(self, arg0: TemporalField) -> int: ...
    def query(self, arg0: TemporalQuery) -> Any: ...
    def adjustInto(self, arg0: Temporal) -> Temporal: ...
    def getDisplayName(self, arg0: TextStyle, arg1: Locale) -> str: ...
