from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class HijrahEra:
    AH: ClassVar["HijrahEra"]
    @staticmethod
    def values() -> list["HijrahEra"]: ...
    @staticmethod
    def valueOf(arg0: str) -> "HijrahEra": ...
    @staticmethod
    def of(arg0: int) -> "HijrahEra": ...
    def getValue(self) -> int: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def getDisplayName(self, arg0: TextStyle, arg1: Locale) -> str: ...
