from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.HijrahChronology import HijrahChronology
from java.time.chrono.HijrahEra import HijrahEra
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class HijrahDate:
    @overload
    @staticmethod
    def now() -> "HijrahDate": ...
    @overload
    @staticmethod
    def now(arg0: ZoneId) -> "HijrahDate": ...
    @overload
    @staticmethod
    def now(arg0: Clock) -> "HijrahDate": ...
    @staticmethod
    def of(arg0: int, arg1: int, arg2: int) -> "HijrahDate": ...
    @staticmethod
    def from_(arg0: TemporalAccessor) -> "HijrahDate": ...
    def getChronology(self) -> HijrahChronology: ...
    def getEra(self) -> HijrahEra: ...
    def lengthOfMonth(self) -> int: ...
    def lengthOfYear(self) -> int: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def getLong(self, arg0: TemporalField) -> int: ...
    @overload
    def with_(self, arg0: TemporalField, arg1: int) -> "HijrahDate": ...
    @overload
    def with_(self, arg0: TemporalAdjuster) -> "HijrahDate": ...
    def withVariant(self, arg0: HijrahChronology) -> "HijrahDate": ...
    @overload
    def plus(self, arg0: TemporalAmount) -> "HijrahDate": ...
    @overload
    def plus(self, arg0: int, arg1: TemporalUnit) -> "HijrahDate": ...
    @overload
    def minus(self, arg0: TemporalAmount) -> "HijrahDate": ...
    @overload
    def minus(self, arg0: int, arg1: TemporalUnit) -> "HijrahDate": ...
    def toEpochDay(self) -> int: ...
    def isLeapYear(self) -> bool: ...
    def atTime(self, arg0: LocalTime) -> ChronoLocalDateTime: ...
    @overload
    def until(self, arg0: ChronoLocalDate) -> ChronoPeriod: ...
    @overload
    def until(self, arg0: Temporal, arg1: TemporalUnit) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
