from typing import Any, ClassVar, overload

class IsoEra:
    BCE: ClassVar["IsoEra"]
    CE: ClassVar["IsoEra"]
    @staticmethod
    def values() -> list["IsoEra"]: ...
    @staticmethod
    def valueOf(arg0: str) -> "IsoEra": ...
    @staticmethod
    def of(arg0: int) -> "IsoEra": ...
    def getValue(self) -> int: ...
