from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class JapaneseEra:
    HEISEI: ClassVar["JapaneseEra"]
    MEIJI: ClassVar["JapaneseEra"]
    REIWA: ClassVar["JapaneseEra"]
    SHOWA: ClassVar["JapaneseEra"]
    TAISHO: ClassVar["JapaneseEra"]
    @staticmethod
    def of(arg0: int) -> "JapaneseEra": ...
    @staticmethod
    def valueOf(arg0: str) -> "JapaneseEra": ...
    @staticmethod
    def values() -> list["JapaneseEra"]: ...
    def getDisplayName(self, arg0: TextStyle, arg1: Locale) -> str: ...
    def getValue(self) -> int: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def toString(self) -> str: ...
