from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.MinguoChronology import MinguoChronology
from java.time.chrono.MinguoEra import MinguoEra
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class MinguoDate:
    @overload
    @staticmethod
    def now() -> "MinguoDate": ...
    @overload
    @staticmethod
    def now(arg0: ZoneId) -> "MinguoDate": ...
    @overload
    @staticmethod
    def now(arg0: Clock) -> "MinguoDate": ...
    @staticmethod
    def of(arg0: int, arg1: int, arg2: int) -> "MinguoDate": ...
    @staticmethod
    def from_(arg0: TemporalAccessor) -> "MinguoDate": ...
    def getChronology(self) -> MinguoChronology: ...
    def getEra(self) -> MinguoEra: ...
    def lengthOfMonth(self) -> int: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def getLong(self, arg0: TemporalField) -> int: ...
    @overload
    def with_(self, arg0: TemporalField, arg1: int) -> "MinguoDate": ...
    @overload
    def with_(self, arg0: TemporalAdjuster) -> "MinguoDate": ...
    @overload
    def plus(self, arg0: TemporalAmount) -> "MinguoDate": ...
    @overload
    def plus(self, arg0: int, arg1: TemporalUnit) -> "MinguoDate": ...
    @overload
    def minus(self, arg0: TemporalAmount) -> "MinguoDate": ...
    @overload
    def minus(self, arg0: int, arg1: TemporalUnit) -> "MinguoDate": ...
    def atTime(self, arg0: LocalTime) -> ChronoLocalDateTime: ...
    @overload
    def until(self, arg0: ChronoLocalDate) -> ChronoPeriod: ...
    @overload
    def until(self, arg0: Temporal, arg1: TemporalUnit) -> int: ...
    def toEpochDay(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
