from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.util.Locale import Locale

class ThaiBuddhistEra:
    BEFORE_BE: ClassVar["ThaiBuddhistEra"]
    BE: ClassVar["ThaiBuddhistEra"]
    @staticmethod
    def values() -> list["ThaiBuddhistEra"]: ...
    @staticmethod
    def valueOf(arg0: str) -> "ThaiBuddhistEra": ...
    @staticmethod
    def of(arg0: int) -> "ThaiBuddhistEra": ...
    def getValue(self) -> int: ...
    def getDisplayName(self, arg0: TextStyle, arg1: Locale) -> str: ...
