from typing import Any, ClassVar, overload
from java.net.URL import URL
from java.security.Principal import Principal
from java.security.cert.Certificate import Certificate
from javax.net.ssl.HostnameVerifier import HostnameVerifier
from javax.net.ssl.SSLSocketFactory import SSLSocketFactory

class HttpsURLConnection:
    hostnameVerifier: HostnameVerifier
    def __init__(self, arg0: URL) -> None: ...
    def getCipherSuite(self) -> str: ...
    def getLocalCertificates(self) -> list[Certificate]: ...
    def getServerCertificates(self) -> list[Certificate]: ...
    def getPeerPrincipal(self) -> Principal: ...
    def getLocalPrincipal(self) -> Principal: ...
    @staticmethod
    def setDefaultHostnameVerifier(arg0: HostnameVerifier) -> None: ...
    @staticmethod
    def getDefaultHostnameVerifier() -> HostnameVerifier: ...
    def setHostnameVerifier(self, arg0: HostnameVerifier) -> None: ...
    def getHostnameVerifier(self) -> HostnameVerifier: ...
    @staticmethod
    def setDefaultSSLSocketFactory(arg0: SSLSocketFactory) -> None: ...
    @staticmethod
    def getDefaultSSLSocketFactory() -> SSLSocketFactory: ...
    def setSSLSocketFactory(self, arg0: SSLSocketFactory) -> None: ...
    def getSSLSocketFactory(self) -> SSLSocketFactory: ...
