from typing import Any, ClassVar, overload
from javax.net.ssl.SNIMatcher import SNIMatcher

class SNIHostName:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: list[int]) -> None: ...
    def getAsciiName(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    @staticmethod
    def createSNIMatcher(arg0: str) -> SNIMatcher: ...
