from typing import Any, ClassVar, overload
from javax.net.ssl.SNIServerName import SNIServerName

class SNIMatcher:
    def __init__(self, arg0: int) -> None: ...
    def getType(self) -> int: ...
    def matches(self, arg0: SNIServerName) -> bool: ...
