from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.nio.ByteBuffer import ByteBuffer
from java.util.function.BiFunction import BiFunction
from javax.net.ssl.SSLEngineResult import SSLEngineResult
from javax.net.ssl.SSLParameters import SSLParameters
from javax.net.ssl.SSLSession import SSLSession

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class HandshakeStatus:
    """Forward declaration for ``javax.net.ssl.SSLEngineResult.HandshakeStatus``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('javax.net.ssl.SSLEngineResult.HandshakeStatus')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLEngineResult/HandshakeStatus.html
    """
    ...

class SSLEngine:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int) -> None: ...
    def getPeerHost(self) -> str: ...
    def getPeerPort(self) -> int: ...
    @overload
    def wrap(self, arg0: ByteBuffer, arg1: ByteBuffer) -> SSLEngineResult: ...
    @overload
    def wrap(self, arg0: list[ByteBuffer], arg1: ByteBuffer) -> SSLEngineResult: ...
    @overload
    def wrap(self, arg0: list[ByteBuffer], arg1: int, arg2: int, arg3: ByteBuffer) -> SSLEngineResult: ...
    @overload
    def unwrap(self, arg0: ByteBuffer, arg1: ByteBuffer) -> SSLEngineResult: ...
    @overload
    def unwrap(self, arg0: ByteBuffer, arg1: list[ByteBuffer]) -> SSLEngineResult: ...
    @overload
    def unwrap(self, arg0: ByteBuffer, arg1: list[ByteBuffer], arg2: int, arg3: int) -> SSLEngineResult: ...
    def getDelegatedTask(self) -> Runnable: ...
    def closeInbound(self) -> None: ...
    def isInboundDone(self) -> bool: ...
    def closeOutbound(self) -> None: ...
    def isOutboundDone(self) -> bool: ...
    def getSupportedCipherSuites(self) -> list[str]: ...
    def getEnabledCipherSuites(self) -> list[str]: ...
    def setEnabledCipherSuites(self, arg0: list[str]) -> None: ...
    def getSupportedProtocols(self) -> list[str]: ...
    def getEnabledProtocols(self) -> list[str]: ...
    def setEnabledProtocols(self, arg0: list[str]) -> None: ...
    def getSession(self) -> SSLSession: ...
    def getHandshakeSession(self) -> SSLSession: ...
    def beginHandshake(self) -> None: ...
    def getHandshakeStatus(self) -> HandshakeStatus: ...
    def setUseClientMode(self, arg0: bool) -> None: ...
    def getUseClientMode(self) -> bool: ...
    def setNeedClientAuth(self, arg0: bool) -> None: ...
    def getNeedClientAuth(self) -> bool: ...
    def setWantClientAuth(self, arg0: bool) -> None: ...
    def getWantClientAuth(self) -> bool: ...
    def setEnableSessionCreation(self, arg0: bool) -> None: ...
    def getEnableSessionCreation(self) -> bool: ...
    def getSSLParameters(self) -> SSLParameters: ...
    def setSSLParameters(self, arg0: SSLParameters) -> None: ...
    def getApplicationProtocol(self) -> str: ...
    def getHandshakeApplicationProtocol(self) -> str: ...
    def setHandshakeApplicationProtocolSelector(self, arg0: BiFunction) -> None: ...
    def getHandshakeApplicationProtocolSelector(self) -> BiFunction: ...
