from typing import Any, ClassVar, overload
from java.security.AlgorithmConstraints import AlgorithmConstraints

class SSLParameters:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: list[str]) -> None: ...
    @overload
    def __init__(self, arg0: list[str], arg1: list[str]) -> None: ...
    def getCipherSuites(self) -> list[str]: ...
    def setCipherSuites(self, arg0: list[str]) -> None: ...
    def getProtocols(self) -> list[str]: ...
    def setProtocols(self, arg0: list[str]) -> None: ...
    def getWantClientAuth(self) -> bool: ...
    def setWantClientAuth(self, arg0: bool) -> None: ...
    def getNeedClientAuth(self) -> bool: ...
    def setNeedClientAuth(self, arg0: bool) -> None: ...
    def getAlgorithmConstraints(self) -> AlgorithmConstraints: ...
    def setAlgorithmConstraints(self, arg0: AlgorithmConstraints) -> None: ...
    def getEndpointIdentificationAlgorithm(self) -> str: ...
    def setEndpointIdentificationAlgorithm(self, arg0: str) -> None: ...
    def setServerNames(self, arg0: list) -> None: ...
    def getServerNames(self) -> list: ...
    def setSNIMatchers(self, arg0: list) -> None: ...
    def getSNIMatchers(self) -> list: ...
    def setUseCipherSuitesOrder(self, arg0: bool) -> None: ...
    def getUseCipherSuitesOrder(self) -> bool: ...
    def getApplicationProtocols(self) -> list[str]: ...
    def setApplicationProtocols(self, arg0: list[str]) -> None: ...
