from typing import Any, ClassVar, overload
from javax.net.ssl.SSLSession import SSLSession

class SSLSessionBindingEvent:
    def __init__(self, arg0: SSLSession, arg1: str) -> None: ...
    def getName(self) -> str: ...
    def getSession(self) -> SSLSession: ...
