from typing import Any, ClassVar, overload
from java.security.KeyStore import KeyStore
from java.security.Provider import Provider
from javax.net.ssl.ManagerFactoryParameters import ManagerFactoryParameters
from javax.net.ssl.TrustManager import TrustManager
from javax.net.ssl.TrustManagerFactorySpi import TrustManagerFactorySpi

class TrustManagerFactory:
    def __init__(self, arg0: TrustManagerFactorySpi, arg1: Provider, arg2: str) -> None: ...
    @staticmethod
    def getDefaultAlgorithm() -> str: ...
    def getAlgorithm(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "TrustManagerFactory": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "TrustManagerFactory": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "TrustManagerFactory": ...
    def getProvider(self) -> Provider: ...
    @overload
    def init(self, arg0: KeyStore) -> None: ...
    @overload
    def init(self, arg0: ManagerFactoryParameters) -> None: ...
    def getTrustManagers(self) -> list[TrustManager]: ...
