from typing import Any, ClassVar, overload
from java.net.Socket import Socket
from java.security.cert.X509Certificate import X509Certificate
from javax.net.ssl.SSLEngine import SSLEngine

class X509ExtendedTrustManager:
    def __init__(self) -> None: ...
    @overload
    def checkClientTrusted(self, arg0: list[X509Certificate], arg1: str, arg2: Socket) -> None: ...
    @overload
    def checkClientTrusted(self, arg0: list[X509Certificate], arg1: str, arg2: SSLEngine) -> None: ...
    @overload
    def checkServerTrusted(self, arg0: list[X509Certificate], arg1: str, arg2: Socket) -> None: ...
    @overload
    def checkServerTrusted(self, arg0: list[X509Certificate], arg1: str, arg2: SSLEngine) -> None: ...
