from typing import Any, ClassVar, overload
from java.security.cert.X509Certificate import X509Certificate

class X509TrustManager:
    def checkClientTrusted(self, arg0: list[X509Certificate], arg1: str) -> None: ...
    def checkServerTrusted(self, arg0: list[X509Certificate], arg1: str) -> None: ...
    def getAcceptedIssuers(self) -> list[X509Certificate]: ...
