from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class BaseMovementMethod:
    def __init__(self) -> None: ...
    def canSelectArbitrarily(self) -> bool: ...
    def initialize(self, arg0: TextView, arg1: Spannable) -> None: ...
    def onKeyDown(self, arg0: TextView, arg1: Spannable, arg2: int, arg3: KeyEvent) -> bool: ...
    def onKeyOther(self, arg0: TextView, arg1: Spannable, arg2: KeyEvent) -> bool: ...
    def onKeyUp(self, arg0: TextView, arg1: Spannable, arg2: int, arg3: KeyEvent) -> bool: ...
    def onTakeFocus(self, arg0: TextView, arg1: Spannable, arg2: int) -> None: ...
    def onTouchEvent(self, arg0: TextView, arg1: Spannable, arg2: MotionEvent) -> bool: ...
    def onTrackballEvent(self, arg0: TextView, arg1: Spannable, arg2: MotionEvent) -> bool: ...
    def onGenericMotionEvent(self, arg0: TextView, arg1: Spannable, arg2: MotionEvent) -> bool: ...
    def getMovementMetaState(self, arg0: Spannable, arg1: KeyEvent) -> int: ...
    def handleMovementKey(self, arg0: TextView, arg1: Spannable, arg2: int, arg3: int, arg4: KeyEvent) -> bool: ...
    def left(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def right(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def up(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def down(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def pageUp(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def pageDown(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def top(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def bottom(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def lineStart(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def lineEnd(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def home(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def end(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def previousParagraph(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def nextParagraph(self, arg0: TextView, arg1: Spannable) -> bool: ...
