from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Bundle import Bundle
from android.text.Editable import Editable
from android.view.View import View
from android.widget.AdapterView import AdapterView

class CharacterPickerDialog:
    def __init__(self, arg0: Context, arg1: View, arg2: Editable, arg3: str, arg4: bool) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onItemClick(self, arg0: AdapterView, arg1: View, arg2: int, arg3: int) -> None: ...
    def onClick(self, arg0: View) -> None: ...
