from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent

class DialerKeyListener:
    CHARACTERS: ClassVar[list[str]]
    def __init__(self) -> None: ...
    def getAcceptedChars(self) -> list[str]: ...
    @staticmethod
    def getInstance() -> "DialerKeyListener": ...
    def getInputType(self) -> int: ...
    def lookup(self, arg0: KeyEvent, arg1: Spannable) -> int: ...
