from typing import Any, ClassVar, overload

class HideReturnsTransformationMethod:
    def __init__(self) -> None: ...
    def getOriginal(self) -> list[str]: ...
    def getReplacement(self) -> list[str]: ...
    @staticmethod
    def getInstance() -> "HideReturnsTransformationMethod": ...
