from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class KeyListener:
    def getInputType(self) -> int: ...
    def onKeyDown(self, arg0: View, arg1: Editable, arg2: int, arg3: KeyEvent) -> bool: ...
    def onKeyUp(self, arg0: View, arg1: Editable, arg2: int, arg3: KeyEvent) -> bool: ...
    def onKeyOther(self, arg0: View, arg1: Editable, arg2: KeyEvent) -> bool: ...
    def clearMetaKeyState(self, arg0: View, arg1: Editable, arg2: int) -> None: ...
