from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.text.method.MovementMethod import MovementMethod
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class LinkMovementMethod:
    def __init__(self) -> None: ...
    def canSelectArbitrarily(self) -> bool: ...
    def handleMovementKey(self, arg0: TextView, arg1: Spannable, arg2: int, arg3: int, arg4: KeyEvent) -> bool: ...
    def up(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def down(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def left(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def right(self, arg0: TextView, arg1: Spannable) -> bool: ...
    def onTouchEvent(self, arg0: TextView, arg1: Spannable, arg2: MotionEvent) -> bool: ...
    def initialize(self, arg0: TextView, arg1: Spannable) -> None: ...
    def onTakeFocus(self, arg0: TextView, arg1: Spannable, arg2: int) -> None: ...
    @staticmethod
    def getInstance() -> MovementMethod: ...
