from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class MovementMethod:
    def initialize(self, arg0: TextView, arg1: Spannable) -> None: ...
    def onKeyDown(self, arg0: TextView, arg1: Spannable, arg2: int, arg3: KeyEvent) -> bool: ...
    def onKeyUp(self, arg0: TextView, arg1: Spannable, arg2: int, arg3: KeyEvent) -> bool: ...
    def onKeyOther(self, arg0: TextView, arg1: Spannable, arg2: KeyEvent) -> bool: ...
    def onTakeFocus(self, arg0: TextView, arg1: Spannable, arg2: int) -> None: ...
    def onTrackballEvent(self, arg0: TextView, arg1: Spannable, arg2: MotionEvent) -> bool: ...
    def onTouchEvent(self, arg0: TextView, arg1: Spannable, arg2: MotionEvent) -> bool: ...
    def onGenericMotionEvent(self, arg0: TextView, arg1: Spannable, arg2: MotionEvent) -> bool: ...
    def canSelectArbitrarily(self) -> bool: ...
