from typing import Any, ClassVar, overload
from java.lang.Iterable import Iterable
from java.nio.file.Path import Path
from java.nio.file.PathMatcher import PathMatcher
from java.nio.file.WatchService import WatchService
from java.nio.file.attribute.UserPrincipalLookupService import UserPrincipalLookupService
from java.nio.file.spi.FileSystemProvider import FileSystemProvider

class FileSystem:
    def __init__(self) -> None: ...
    def provider(self) -> FileSystemProvider: ...
    def close(self) -> None: ...
    def isOpen(self) -> bool: ...
    def isReadOnly(self) -> bool: ...
    def getSeparator(self) -> str: ...
    def getRootDirectories(self) -> Iterable: ...
    def getFileStores(self) -> Iterable: ...
    def supportedFileAttributeViews(self) -> set: ...
    def getPath(self, arg0: str, *arg1: str) -> Path: ...
    def getPathMatcher(self, arg0: str) -> PathMatcher: ...
    def getUserPrincipalLookupService(self) -> UserPrincipalLookupService: ...
    def newWatchService(self) -> WatchService: ...
