from typing import Any, ClassVar, overload

class FileSystemException:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: str) -> None: ...
    def getFile(self) -> str: ...
    def getOtherFile(self) -> str: ...
    def getReason(self) -> str: ...
    def getMessage(self) -> str: ...
