from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["Files"]

class Files(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/nio/file/Files"
    newInputStream = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/InputStream;", varargs=True)
    newOutputStream = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/OutputStream;", varargs=True)
    newByteChannel = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/util/Set;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/channels/SeekableByteChannel;", True, True), ("(Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/nio/channels/SeekableByteChannel;", True, True)])
    newDirectoryStream = JavaMultipleMethod([("(Ljava/nio/file/Path;)Ljava/nio/file/DirectoryStream;", True, False), ("(Ljava/nio/file/Path;Ljava/lang/String;)Ljava/nio/file/DirectoryStream;", True, False), ("(Ljava/nio/file/Path;Ljava/nio/file/DirectoryStream$Filter;)Ljava/nio/file/DirectoryStream;", True, False)])
    createFile = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;", varargs=True)
    createDirectory = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;", varargs=True)
    createDirectories = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;", varargs=True)
    createTempFile = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/lang/String;Ljava/lang/String;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;", True, True), ("(Ljava/lang/String;Ljava/lang/String;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;", True, True)])
    createTempDirectory = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/lang/String;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;", True, True), ("(Ljava/lang/String;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;", True, True)])
    createSymbolicLink = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/nio/file/Path;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;", varargs=True)
    createLink = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/nio/file/Path;)Ljava/nio/file/Path;")
    delete = JavaStaticMethod("(Ljava/nio/file/Path;)V")
    deleteIfExists = JavaStaticMethod("(Ljava/nio/file/Path;)Z")
    copy = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/nio/file/Path;[Ljava/nio/file/CopyOption;)Ljava/nio/file/Path;", True, True), ("(Ljava/io/InputStream;Ljava/nio/file/Path;[Ljava/nio/file/CopyOption;)J", True, True), ("(Ljava/nio/file/Path;Ljava/io/OutputStream;)J", True, False)])
    move = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/nio/file/Path;[Ljava/nio/file/CopyOption;)Ljava/nio/file/Path;", varargs=True)
    readSymbolicLink = JavaStaticMethod("(Ljava/nio/file/Path;)Ljava/nio/file/Path;")
    getFileStore = JavaStaticMethod("(Ljava/nio/file/Path;)Ljava/nio/file/FileStore;")
    isSameFile = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/nio/file/Path;)Z")
    isHidden = JavaStaticMethod("(Ljava/nio/file/Path;)Z")
    probeContentType = JavaStaticMethod("(Ljava/nio/file/Path;)Ljava/lang/String;")
    getFileAttributeView = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/lang/Class;[Ljava/nio/file/LinkOption;)Ljava/nio/file/attribute/FileAttributeView;", varargs=True)
    readAttributes = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/lang/Class;[Ljava/nio/file/LinkOption;)Ljava/nio/file/attribute/BasicFileAttributes;", True, True), ("(Ljava/nio/file/Path;Ljava/lang/String;[Ljava/nio/file/LinkOption;)Ljava/util/Map;", True, True)])
    setAttribute = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/lang/String;Ljava/lang/Object;[Ljava/nio/file/LinkOption;)Ljava/nio/file/Path;", varargs=True)
    getAttribute = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/lang/String;[Ljava/nio/file/LinkOption;)Ljava/lang/Object;", varargs=True)
    getPosixFilePermissions = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Ljava/util/Set;", varargs=True)
    setPosixFilePermissions = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/util/Set;)Ljava/nio/file/Path;")
    getOwner = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Ljava/nio/file/attribute/UserPrincipal;", varargs=True)
    setOwner = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/nio/file/attribute/UserPrincipal;)Ljava/nio/file/Path;")
    isSymbolicLink = JavaStaticMethod("(Ljava/nio/file/Path;)Z")
    isDirectory = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Z", varargs=True)
    isRegularFile = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Z", varargs=True)
    getLastModifiedTime = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Ljava/nio/file/attribute/FileTime;", varargs=True)
    setLastModifiedTime = JavaStaticMethod("(Ljava/nio/file/Path;Ljava/nio/file/attribute/FileTime;)Ljava/nio/file/Path;")
    size = JavaStaticMethod("(Ljava/nio/file/Path;)J")
    exists = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Z", varargs=True)
    notExists = JavaStaticMethod("(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Z", varargs=True)
    isReadable = JavaStaticMethod("(Ljava/nio/file/Path;)Z")
    isWritable = JavaStaticMethod("(Ljava/nio/file/Path;)Z")
    isExecutable = JavaStaticMethod("(Ljava/nio/file/Path;)Z")
    walkFileTree = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/util/Set;ILjava/nio/file/FileVisitor;)Ljava/nio/file/Path;", True, False), ("(Ljava/nio/file/Path;Ljava/nio/file/FileVisitor;)Ljava/nio/file/Path;", True, False)])
    newBufferedReader = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/nio/charset/Charset;)Ljava/io/BufferedReader;", True, False), ("(Ljava/nio/file/Path;)Ljava/io/BufferedReader;", True, False)])
    newBufferedWriter = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/nio/charset/Charset;[Ljava/nio/file/OpenOption;)Ljava/io/BufferedWriter;", True, True), ("(Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/BufferedWriter;", True, True)])
    readAllBytes = JavaStaticMethod("(Ljava/nio/file/Path;)[B")
    readAllLines = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/nio/charset/Charset;)Ljava/util/List;", True, False), ("(Ljava/nio/file/Path;)Ljava/util/List;", True, False)])
    write = JavaMultipleMethod([("(Ljava/nio/file/Path;[B[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;", True, True), ("(Ljava/nio/file/Path;Ljava/lang/Iterable;Ljava/nio/charset/Charset;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;", True, True), ("(Ljava/nio/file/Path;Ljava/lang/Iterable;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;", True, True)])
    list = JavaStaticMethod("(Ljava/nio/file/Path;)Ljava/util/stream/Stream;")
    walk = JavaMultipleMethod([("(Ljava/nio/file/Path;I[Ljava/nio/file/FileVisitOption;)Ljava/util/stream/Stream;", True, True), ("(Ljava/nio/file/Path;[Ljava/nio/file/FileVisitOption;)Ljava/util/stream/Stream;", True, True)])
    find = JavaStaticMethod("(Ljava/nio/file/Path;ILjava/util/function/BiPredicate;[Ljava/nio/file/FileVisitOption;)Ljava/util/stream/Stream;", varargs=True)
    lines = JavaMultipleMethod([("(Ljava/nio/file/Path;Ljava/nio/charset/Charset;)Ljava/util/stream/Stream;", True, False), ("(Ljava/nio/file/Path;)Ljava/util/stream/Stream;", True, False)])