from typing import Any, ClassVar, overload
from java.io.File import File
from java.net.URI import URI
from java.nio.file.FileSystem import FileSystem
from java.nio.file.LinkOption import LinkOption
from java.nio.file.WatchKey import WatchKey
from java.nio.file.WatchService import WatchService
from java.util.Iterator import Iterator

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Kind:
    """Forward declaration for ``java.nio.file.WatchEvent.Kind``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.nio.file.WatchEvent.Kind')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchEvent/Kind.html
    """
    ...
class Modifier:
    """Forward declaration for ``java.nio.file.WatchEvent.Modifier``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.nio.file.WatchEvent.Modifier')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchEvent/Modifier.html
    """
    ...

class Path:
    @overload
    @staticmethod
    def of(arg0: str, *arg1: str) -> "Path": ...
    @overload
    @staticmethod
    def of(arg0: URI) -> "Path": ...
    def getFileSystem(self) -> FileSystem: ...
    def isAbsolute(self) -> bool: ...
    def getRoot(self) -> "Path": ...
    def getFileName(self) -> "Path": ...
    def getParent(self) -> "Path": ...
    def getNameCount(self) -> int: ...
    def getName(self, arg0: int) -> "Path": ...
    def subpath(self, arg0: int, arg1: int) -> "Path": ...
    @overload
    def startsWith(self, arg0: "Path") -> bool: ...
    @overload
    def startsWith(self, arg0: str) -> bool: ...
    @overload
    def endsWith(self, arg0: "Path") -> bool: ...
    @overload
    def endsWith(self, arg0: str) -> bool: ...
    def normalize(self) -> "Path": ...
    @overload
    def resolve(self, arg0: "Path") -> "Path": ...
    @overload
    def resolve(self, arg0: str) -> "Path": ...
    @overload
    def resolveSibling(self, arg0: "Path") -> "Path": ...
    @overload
    def resolveSibling(self, arg0: str) -> "Path": ...
    def relativize(self, arg0: "Path") -> "Path": ...
    def toUri(self) -> URI: ...
    def toAbsolutePath(self) -> "Path": ...
    def toRealPath(self, *arg0: LinkOption) -> "Path": ...
    def toFile(self) -> File: ...
    @overload
    def register(self, arg0: WatchService, arg1: list[Kind], *arg2: Modifier) -> WatchKey: ...
    @overload
    def register(self, arg0: WatchService, *arg1: Kind) -> WatchKey: ...
    def iterator(self) -> Iterator: ...
    def compareTo(self, arg0: "Path") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
