from typing import Any, ClassVar, overload
from java.nio.file.WatchKey import WatchKey
from java.util.concurrent.TimeUnit import TimeUnit

class WatchService:
    def close(self) -> None: ...
    @overload
    def poll(self) -> WatchKey: ...
    @overload
    def poll(self, arg0: int, arg1: TimeUnit) -> WatchKey: ...
    def take(self) -> WatchKey: ...
