from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.text.Editable import Editable
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.View import View
from android.view.inputmethod.CompletionInfo import CompletionInfo
from android.view.inputmethod.CorrectionInfo import CorrectionInfo
from android.view.inputmethod.ExtractedText import ExtractedText
from android.view.inputmethod.ExtractedTextRequest import ExtractedTextRequest
from android.view.inputmethod.InputContentInfo import InputContentInfo
from android.view.inputmethod.SurroundingText import SurroundingText
from android.view.inputmethod.TextAttribute import TextAttribute
from android.view.inputmethod.TextSnapshot import TextSnapshot

class BaseInputConnection:
    def __init__(self, arg0: View, arg1: bool) -> None: ...
    @staticmethod
    def removeComposingSpans(arg0: Spannable) -> None: ...
    @staticmethod
    def setComposingSpans(arg0: Spannable) -> None: ...
    @staticmethod
    def getComposingSpanStart(arg0: Spannable) -> int: ...
    @staticmethod
    def getComposingSpanEnd(arg0: Spannable) -> int: ...
    def getEditable(self) -> Editable: ...
    def beginBatchEdit(self) -> bool: ...
    def endBatchEdit(self) -> bool: ...
    def closeConnection(self) -> None: ...
    def clearMetaKeyStates(self, arg0: int) -> bool: ...
    def commitCompletion(self, arg0: CompletionInfo) -> bool: ...
    def commitCorrection(self, arg0: CorrectionInfo) -> bool: ...
    def commitText(self, arg0: str, arg1: int) -> bool: ...
    def deleteSurroundingText(self, arg0: int, arg1: int) -> bool: ...
    def deleteSurroundingTextInCodePoints(self, arg0: int, arg1: int) -> bool: ...
    def finishComposingText(self) -> bool: ...
    def getCursorCapsMode(self, arg0: int) -> int: ...
    def getExtractedText(self, arg0: ExtractedTextRequest, arg1: int) -> ExtractedText: ...
    def getTextBeforeCursor(self, arg0: int, arg1: int) -> str: ...
    def getSelectedText(self, arg0: int) -> str: ...
    def getTextAfterCursor(self, arg0: int, arg1: int) -> str: ...
    def getSurroundingText(self, arg0: int, arg1: int, arg2: int) -> SurroundingText: ...
    def performEditorAction(self, arg0: int) -> bool: ...
    def performContextMenuAction(self, arg0: int) -> bool: ...
    def performPrivateCommand(self, arg0: str, arg1: Bundle) -> bool: ...
    def requestCursorUpdates(self, arg0: int) -> bool: ...
    def getHandler(self) -> Handler: ...
    def setComposingText(self, arg0: str, arg1: int) -> bool: ...
    def setComposingRegion(self, arg0: int, arg1: int) -> bool: ...
    def setSelection(self, arg0: int, arg1: int) -> bool: ...
    def sendKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def reportFullscreenMode(self, arg0: bool) -> bool: ...
    def replaceText(self, arg0: int, arg1: int, arg2: str, arg3: int, arg4: TextAttribute) -> bool: ...
    def commitContent(self, arg0: InputContentInfo, arg1: int, arg2: Bundle) -> bool: ...
    def takeSnapshot(self) -> TextSnapshot: ...
