from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from android.widget.inline.InlinePresentationSpec import InlinePresentationSpec

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class InlineSuggestionsRequest:
    CREATOR: ClassVar[Creator]
    SUGGESTION_COUNT_UNLIMITED: ClassVar[int]
    def getMaxSuggestionCount(self) -> int: ...
    def getInlinePresentationSpecs(self) -> list: ...
    def getHostPackageName(self) -> str: ...
    def getSupportedLocales(self) -> LocaleList: ...
    def getExtras(self) -> Bundle: ...
    def getInlineTooltipPresentationSpec(self) -> InlinePresentationSpec: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self, arg0: list) -> None: ...
        def setMaxSuggestionCount(self, arg0: int) -> "Builder": ...
        def setInlinePresentationSpecs(self, arg0: list) -> "Builder": ...
        def addInlinePresentationSpecs(self, arg0: InlinePresentationSpec) -> "Builder": ...
        def setSupportedLocales(self, arg0: LocaleList) -> "Builder": ...
        def setExtras(self, arg0: Bundle) -> "Builder": ...
        def setInlineTooltipPresentationSpec(self, arg0: InlinePresentationSpec) -> "Builder": ...
        def build(self) -> "InlineSuggestionsRequest": ...
