from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.widget.inline.InlinePresentationSpec import InlinePresentationSpec

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class InlineSuggestionInfo:
    CREATOR: ClassVar[Creator]
    SOURCE_AUTOFILL: ClassVar[str]
    SOURCE_PLATFORM: ClassVar[str]
    TYPE_ACTION: ClassVar[str]
    TYPE_SUGGESTION: ClassVar[str]
    def getInlinePresentationSpec(self) -> InlinePresentationSpec: ...
    def getSource(self) -> str: ...
    def getAutofillHints(self) -> list[str]: ...
    def getType(self) -> str: ...
    def isPinned(self) -> bool: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
