from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.pm.PackageManager import PackageManager
from android.content.pm.ResolveInfo import ResolveInfo
from android.content.pm.ServiceInfo import ServiceInfo
from android.graphics.drawable.Drawable import Drawable
from android.os.Parcel import Parcel
from android.util.Printer import Printer
from android.view.inputmethod.InputMethodSubtype import InputMethodSubtype

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class InputMethodInfo:
    ACTION_STYLUS_HANDWRITING_SETTINGS: ClassVar[str]
    CREATOR: ClassVar[Creator]
    @overload
    def __init__(self, arg0: Context, arg1: ResolveInfo) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: str, arg3: str) -> None: ...
    def getId(self) -> str: ...
    def getPackageName(self) -> str: ...
    def getServiceName(self) -> str: ...
    def getServiceInfo(self) -> ServiceInfo: ...
    def getComponent(self) -> ComponentName: ...
    def loadLabel(self, arg0: PackageManager) -> str: ...
    def loadIcon(self, arg0: PackageManager) -> Drawable: ...
    def getSettingsActivity(self) -> str: ...
    def getSubtypeCount(self) -> int: ...
    def getSubtypeAt(self, arg0: int) -> InputMethodSubtype: ...
    def getIsDefaultResourceId(self) -> int: ...
    def getConfigChanges(self) -> int: ...
    def supportsStylusHandwriting(self) -> bool: ...
    def supportsConnectionlessStylusHandwriting(self) -> bool: ...
    def createStylusHandwritingSettingsActivityIntent(self) -> Intent: ...
    def dump(self, arg0: Printer, arg1: str) -> None: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def suppressesSpellChecker(self) -> bool: ...
    def shouldShowInInputMethodPicker(self) -> bool: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
