from typing import Any, ClassVar, overload
from android.os.IBinder import IBinder
from android.os.ResultReceiver import ResultReceiver
from android.view.inputmethod.EditorInfo import EditorInfo
from android.view.inputmethod.InputBinding import InputBinding
from android.view.inputmethod.InputConnection import InputConnection
from android.view.inputmethod.InputMethodSession import InputMethodSession
from android.view.inputmethod.InputMethodSubtype import InputMethodSubtype

class InputMethod:
    SERVICE_INTERFACE: ClassVar[str]
    SERVICE_META_DATA: ClassVar[str]
    SHOW_EXPLICIT: ClassVar[int]
    SHOW_FORCED: ClassVar[int]
    def attachToken(self, arg0: IBinder) -> None: ...
    def bindInput(self, arg0: InputBinding) -> None: ...
    def unbindInput(self) -> None: ...
    def startInput(self, arg0: InputConnection, arg1: EditorInfo) -> None: ...
    def restartInput(self, arg0: InputConnection, arg1: EditorInfo) -> None: ...
    def createSession(self, arg0: "SessionCallback") -> None: ...
    def setSessionEnabled(self, arg0: InputMethodSession, arg1: bool) -> None: ...
    def revokeSession(self, arg0: InputMethodSession) -> None: ...
    def showSoftInput(self, arg0: int, arg1: ResultReceiver) -> None: ...
    def hideSoftInput(self, arg0: int, arg1: ResultReceiver) -> None: ...
    def changeInputMethodSubtype(self, arg0: InputMethodSubtype) -> None: ...

    class SessionCallback:
        def sessionCreated(self, arg0: InputMethodSession) -> None: ...
