from typing import Any, ClassVar, overload
from android.graphics.RectF import RectF
from android.os.Bundle import Bundle
from android.os.CancellationSignal import CancellationSignal
from android.os.Handler import Handler
from android.view.KeyEvent import KeyEvent
from android.view.inputmethod.CompletionInfo import CompletionInfo
from android.view.inputmethod.CorrectionInfo import CorrectionInfo
from android.view.inputmethod.ExtractedText import ExtractedText
from android.view.inputmethod.ExtractedTextRequest import ExtractedTextRequest
from android.view.inputmethod.HandwritingGesture import HandwritingGesture
from android.view.inputmethod.InputContentInfo import InputContentInfo
from android.view.inputmethod.PreviewableHandwritingGesture import PreviewableHandwritingGesture
from android.view.inputmethod.SurroundingText import SurroundingText
from android.view.inputmethod.TextAttribute import TextAttribute
from android.view.inputmethod.TextSnapshot import TextSnapshot
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer
from java.util.function.IntConsumer import IntConsumer

class InputConnection:
    CURSOR_UPDATE_FILTER_CHARACTER_BOUNDS: ClassVar[int]
    CURSOR_UPDATE_FILTER_EDITOR_BOUNDS: ClassVar[int]
    CURSOR_UPDATE_FILTER_INSERTION_MARKER: ClassVar[int]
    CURSOR_UPDATE_FILTER_TEXT_APPEARANCE: ClassVar[int]
    CURSOR_UPDATE_FILTER_VISIBLE_LINE_BOUNDS: ClassVar[int]
    CURSOR_UPDATE_IMMEDIATE: ClassVar[int]
    CURSOR_UPDATE_MONITOR: ClassVar[int]
    GET_EXTRACTED_TEXT_MONITOR: ClassVar[int]
    GET_TEXT_WITH_STYLES: ClassVar[int]
    HANDWRITING_GESTURE_RESULT_CANCELLED: ClassVar[int]
    HANDWRITING_GESTURE_RESULT_FAILED: ClassVar[int]
    HANDWRITING_GESTURE_RESULT_FALLBACK: ClassVar[int]
    HANDWRITING_GESTURE_RESULT_SUCCESS: ClassVar[int]
    HANDWRITING_GESTURE_RESULT_UNKNOWN: ClassVar[int]
    HANDWRITING_GESTURE_RESULT_UNSUPPORTED: ClassVar[int]
    INPUT_CONTENT_GRANT_READ_URI_PERMISSION: ClassVar[int]
    def getTextBeforeCursor(self, arg0: int, arg1: int) -> str: ...
    def getTextAfterCursor(self, arg0: int, arg1: int) -> str: ...
    def getSelectedText(self, arg0: int) -> str: ...
    def getSurroundingText(self, arg0: int, arg1: int, arg2: int) -> SurroundingText: ...
    def getCursorCapsMode(self, arg0: int) -> int: ...
    def getExtractedText(self, arg0: ExtractedTextRequest, arg1: int) -> ExtractedText: ...
    def deleteSurroundingText(self, arg0: int, arg1: int) -> bool: ...
    def deleteSurroundingTextInCodePoints(self, arg0: int, arg1: int) -> bool: ...
    @overload
    def setComposingText(self, arg0: str, arg1: int) -> bool: ...
    @overload
    def setComposingText(self, arg0: str, arg1: int, arg2: TextAttribute) -> bool: ...
    @overload
    def setComposingRegion(self, arg0: int, arg1: int) -> bool: ...
    @overload
    def setComposingRegion(self, arg0: int, arg1: int, arg2: TextAttribute) -> bool: ...
    def finishComposingText(self) -> bool: ...
    @overload
    def commitText(self, arg0: str, arg1: int) -> bool: ...
    @overload
    def commitText(self, arg0: str, arg1: int, arg2: TextAttribute) -> bool: ...
    def commitCompletion(self, arg0: CompletionInfo) -> bool: ...
    def commitCorrection(self, arg0: CorrectionInfo) -> bool: ...
    def setSelection(self, arg0: int, arg1: int) -> bool: ...
    def performEditorAction(self, arg0: int) -> bool: ...
    def performContextMenuAction(self, arg0: int) -> bool: ...
    def beginBatchEdit(self) -> bool: ...
    def endBatchEdit(self) -> bool: ...
    def sendKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def clearMetaKeyStates(self, arg0: int) -> bool: ...
    def reportFullscreenMode(self, arg0: bool) -> bool: ...
    def performSpellCheck(self) -> bool: ...
    def performPrivateCommand(self, arg0: str, arg1: Bundle) -> bool: ...
    def performHandwritingGesture(self, arg0: HandwritingGesture, arg1: Executor, arg2: IntConsumer) -> None: ...
    def previewHandwritingGesture(self, arg0: PreviewableHandwritingGesture, arg1: CancellationSignal) -> bool: ...
    @overload
    def requestCursorUpdates(self, arg0: int) -> bool: ...
    @overload
    def requestCursorUpdates(self, arg0: int, arg1: int) -> bool: ...
    def requestTextBoundsInfo(self, arg0: RectF, arg1: Executor, arg2: Consumer) -> None: ...
    def getHandler(self) -> Handler: ...
    def closeConnection(self) -> None: ...
    def commitContent(self, arg0: InputContentInfo, arg1: int, arg2: Bundle) -> bool: ...
    def setImeConsumesInput(self, arg0: bool) -> bool: ...
    def takeSnapshot(self) -> TextSnapshot: ...
    def replaceText(self, arg0: int, arg1: int, arg2: str, arg3: int, arg4: TextAttribute) -> bool: ...
