from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.os.Bundle import Bundle
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.inputmethod.CompletionInfo import CompletionInfo
from android.view.inputmethod.CursorAnchorInfo import CursorAnchorInfo
from android.view.inputmethod.ExtractedText import ExtractedText

class InputMethodSession:
    def finishInput(self) -> None: ...
    def updateSelection(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    def viewClicked(self, arg0: bool) -> None: ...
    def updateCursor(self, arg0: Rect) -> None: ...
    def displayCompletions(self, arg0: list[CompletionInfo]) -> None: ...
    def updateExtractedText(self, arg0: int, arg1: ExtractedText) -> None: ...
    def dispatchKeyEvent(self, arg0: int, arg1: KeyEvent, arg2: "EventCallback") -> None: ...
    def dispatchTrackballEvent(self, arg0: int, arg1: MotionEvent, arg2: "EventCallback") -> None: ...
    def dispatchGenericMotionEvent(self, arg0: int, arg1: MotionEvent, arg2: "EventCallback") -> None: ...
    def appPrivateCommand(self, arg0: str, arg1: Bundle) -> None: ...
    def toggleSoftInput(self, arg0: int, arg1: int) -> None: ...
    def updateCursorAnchorInfo(self, arg0: CursorAnchorInfo) -> None: ...

    class EventCallback:
        def finishedEvent(self, arg0: int, arg1: bool) -> None: ...
