from typing import Any, ClassVar, overload
from android.graphics.Matrix import Matrix
from android.graphics.RectF import RectF
from android.os.Parcel import Parcel
from android.text.SegmentFinder import SegmentFinder

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...
class TextInclusionStrategy:
    """Forward declaration for ``android.text.Layout.TextInclusionStrategy``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.text.Layout.TextInclusionStrategy')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/text/Layout/TextInclusionStrategy
    """
    ...

class TextBoundsInfo:
    CREATOR: ClassVar[Creator]
    FLAG_CHARACTER_LINEFEED: ClassVar[int]
    FLAG_CHARACTER_PUNCTUATION: ClassVar[int]
    FLAG_CHARACTER_WHITESPACE: ClassVar[int]
    FLAG_LINE_IS_RTL: ClassVar[int]
    def getMatrix(self, arg0: Matrix) -> None: ...
    def getStartIndex(self) -> int: ...
    def getEndIndex(self) -> int: ...
    def getCharacterBounds(self, arg0: int, arg1: RectF) -> None: ...
    def getCharacterFlags(self, arg0: int) -> int: ...
    def getCharacterBidiLevel(self, arg0: int) -> int: ...
    def getWordSegmentFinder(self) -> SegmentFinder: ...
    def getGraphemeSegmentFinder(self) -> SegmentFinder: ...
    def getLineSegmentFinder(self) -> SegmentFinder: ...
    def getOffsetForPosition(self, arg0: float, arg1: float) -> int: ...
    def getRangeForRect(self, arg0: RectF, arg1: SegmentFinder, arg2: TextInclusionStrategy) -> list[int]: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self, arg0: int, arg1: int) -> None: ...
        def clear(self) -> "Builder": ...
        def setMatrix(self, arg0: Matrix) -> "Builder": ...
        def setStartAndEnd(self, arg0: int, arg1: int) -> "Builder": ...
        def setCharacterBounds(self, arg0: list[float]) -> "Builder": ...
        def setCharacterFlags(self, arg0: list[int]) -> "Builder": ...
        def setCharacterBidiLevel(self, arg0: list[int]) -> "Builder": ...
        def setGraphemeSegmentFinder(self, arg0: SegmentFinder) -> "Builder": ...
        def setWordSegmentFinder(self, arg0: SegmentFinder) -> "Builder": ...
        def setLineSegmentFinder(self, arg0: SegmentFinder) -> "Builder": ...
        def build(self) -> "TextBoundsInfo": ...
