from typing import Any, ClassVar, overload
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class TextAppearanceInfo:
    CREATOR: ClassVar[Creator]
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getTextSize(self) -> float: ...
    def getTextLocales(self) -> LocaleList: ...
    def getSystemFontFamilyName(self) -> str: ...
    def getTextFontWeight(self) -> int: ...
    def getTextStyle(self) -> int: ...
    def isAllCaps(self) -> bool: ...
    def getShadowDx(self) -> float: ...
    def getShadowDy(self) -> float: ...
    def getShadowRadius(self) -> float: ...
    def getShadowColor(self) -> int: ...
    def isElegantTextHeight(self) -> bool: ...
    def isFallbackLineSpacing(self) -> bool: ...
    def getLetterSpacing(self) -> float: ...
    def getFontFeatureSettings(self) -> str: ...
    def getFontVariationSettings(self) -> str: ...
    def getLineBreakStyle(self) -> int: ...
    def getLineBreakWordStyle(self) -> int: ...
    def getTextScaleX(self) -> float: ...
    def getHighlightTextColor(self) -> int: ...
    def getTextColor(self) -> int: ...
    def getHintTextColor(self) -> int: ...
    def getLinkTextColor(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setTextSize(self, arg0: float) -> "Builder": ...
        def setTextLocales(self, arg0: LocaleList) -> "Builder": ...
        def setSystemFontFamilyName(self, arg0: str) -> "Builder": ...
        def setTextFontWeight(self, arg0: int) -> "Builder": ...
        def setTextStyle(self, arg0: int) -> "Builder": ...
        def setAllCaps(self, arg0: bool) -> "Builder": ...
        def setShadowDx(self, arg0: float) -> "Builder": ...
        def setShadowDy(self, arg0: float) -> "Builder": ...
        def setShadowRadius(self, arg0: float) -> "Builder": ...
        def setShadowColor(self, arg0: int) -> "Builder": ...
        def setElegantTextHeight(self, arg0: bool) -> "Builder": ...
        def setFallbackLineSpacing(self, arg0: bool) -> "Builder": ...
        def setLetterSpacing(self, arg0: float) -> "Builder": ...
        def setFontFeatureSettings(self, arg0: str) -> "Builder": ...
        def setFontVariationSettings(self, arg0: str) -> "Builder": ...
        def setLineBreakStyle(self, arg0: int) -> "Builder": ...
        def setLineBreakWordStyle(self, arg0: int) -> "Builder": ...
        def setTextScaleX(self, arg0: float) -> "Builder": ...
        def setHighlightTextColor(self, arg0: int) -> "Builder": ...
        def setTextColor(self, arg0: int) -> "Builder": ...
        def setHintTextColor(self, arg0: int) -> "Builder": ...
        def setLinkTextColor(self, arg0: int) -> "Builder": ...
        def build(self) -> "TextAppearanceInfo": ...
