from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.Intent import Intent
from android.os.IBinder import IBinder
from android.service.quickaccesswallet.GetWalletCardsCallback import GetWalletCardsCallback
from android.service.quickaccesswallet.GetWalletCardsRequest import GetWalletCardsRequest
from android.service.quickaccesswallet.SelectWalletCardRequest import SelectWalletCardRequest
from android.service.quickaccesswallet.WalletServiceEvent import WalletServiceEvent

class QuickAccessWalletService:
    ACTION_VIEW_WALLET: ClassVar[str]
    ACTION_VIEW_WALLET_SETTINGS: ClassVar[str]
    SERVICE_INTERFACE: ClassVar[str]
    SERVICE_META_DATA: ClassVar[str]
    def __init__(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onWalletCardsRequested(self, arg0: GetWalletCardsRequest, arg1: GetWalletCardsCallback) -> None: ...
    def onWalletCardSelected(self, arg0: SelectWalletCardRequest) -> None: ...
    def onWalletDismissed(self) -> None: ...
    def sendWalletServiceEvent(self, arg0: WalletServiceEvent) -> None: ...
    def getTargetActivityPendingIntent(self) -> PendingIntent: ...
