from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class LineBreakConfig:
    CREATOR: ClassVar[Creator]
    HYPHENATION_DISABLED: ClassVar[int]
    HYPHENATION_ENABLED: ClassVar[int]
    HYPHENATION_UNSPECIFIED: ClassVar[int]
    LINE_BREAK_STYLE_AUTO: ClassVar[int]
    LINE_BREAK_STYLE_LOOSE: ClassVar[int]
    LINE_BREAK_STYLE_NONE: ClassVar[int]
    LINE_BREAK_STYLE_NORMAL: ClassVar[int]
    LINE_BREAK_STYLE_NO_BREAK: ClassVar[int]
    LINE_BREAK_STYLE_STRICT: ClassVar[int]
    LINE_BREAK_STYLE_UNSPECIFIED: ClassVar[int]
    LINE_BREAK_WORD_STYLE_AUTO: ClassVar[int]
    LINE_BREAK_WORD_STYLE_NONE: ClassVar[int]
    LINE_BREAK_WORD_STYLE_PHRASE: ClassVar[int]
    LINE_BREAK_WORD_STYLE_UNSPECIFIED: ClassVar[int]
    def getLineBreakStyle(self) -> int: ...
    def getLineBreakWordStyle(self) -> int: ...
    def getHyphenation(self) -> int: ...
    def merge(self, arg0: "LineBreakConfig") -> "LineBreakConfig": ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def merge(self, arg0: "LineBreakConfig") -> "Builder": ...
        def setLineBreakStyle(self, arg0: int) -> "Builder": ...
        def setLineBreakWordStyle(self, arg0: int) -> "Builder": ...
        def setHyphenation(self, arg0: int) -> "Builder": ...
        def build(self) -> "LineBreakConfig": ...
