from typing import Any, ClassVar, overload

class BatteryState:
    STATUS_CHARGING: ClassVar[int]
    STATUS_DISCHARGING: ClassVar[int]
    STATUS_FULL: ClassVar[int]
    STATUS_NOT_CHARGING: ClassVar[int]
    STATUS_UNKNOWN: ClassVar[int]
    def __init__(self) -> None: ...
    def isPresent(self) -> bool: ...
    def getStatus(self) -> int: ...
    def getCapacity(self) -> float: ...
