from typing import Any, ClassVar, overload

class GeomagneticField:
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: int) -> None: ...
    def getX(self) -> float: ...
    def getY(self) -> float: ...
    def getZ(self) -> float: ...
    def getDeclination(self) -> float: ...
    def getInclination(self) -> float: ...
    def getHorizontalStrength(self) -> float: ...
    def getFieldStrength(self) -> float: ...
