from typing import Any, ClassVar, overload

class SensorListener:
    def onSensorChanged(self, arg0: int, arg1: list[float]) -> None: ...
    def onAccuracyChanged(self, arg0: int, arg1: int) -> None: ...
