from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from java.util.Locale import Locale

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Address:
    CREATOR: ClassVar[Creator]
    def __init__(self, arg0: Locale) -> None: ...
    def getLocale(self) -> Locale: ...
    def getMaxAddressLineIndex(self) -> int: ...
    def getAddressLine(self, arg0: int) -> str: ...
    def setAddressLine(self, arg0: int, arg1: str) -> None: ...
    def getFeatureName(self) -> str: ...
    def setFeatureName(self, arg0: str) -> None: ...
    def getAdminArea(self) -> str: ...
    def setAdminArea(self, arg0: str) -> None: ...
    def getSubAdminArea(self) -> str: ...
    def setSubAdminArea(self, arg0: str) -> None: ...
    def getLocality(self) -> str: ...
    def setLocality(self, arg0: str) -> None: ...
    def getSubLocality(self) -> str: ...
    def setSubLocality(self, arg0: str) -> None: ...
    def getThoroughfare(self) -> str: ...
    def setThoroughfare(self, arg0: str) -> None: ...
    def getSubThoroughfare(self) -> str: ...
    def setSubThoroughfare(self, arg0: str) -> None: ...
    def getPremises(self) -> str: ...
    def setPremises(self, arg0: str) -> None: ...
    def getPostalCode(self) -> str: ...
    def setPostalCode(self, arg0: str) -> None: ...
    def getCountryCode(self) -> str: ...
    def setCountryCode(self, arg0: str) -> None: ...
    def getCountryName(self) -> str: ...
    def setCountryName(self, arg0: str) -> None: ...
    def hasLatitude(self) -> bool: ...
    def getLatitude(self) -> float: ...
    def setLatitude(self, arg0: float) -> None: ...
    def clearLatitude(self) -> None: ...
    def hasLongitude(self) -> bool: ...
    def getLongitude(self) -> float: ...
    def setLongitude(self, arg0: float) -> None: ...
    def clearLongitude(self) -> None: ...
    def getPhone(self) -> str: ...
    def setPhone(self, arg0: str) -> None: ...
    def getUrl(self) -> str: ...
    def setUrl(self, arg0: str) -> None: ...
    def getExtras(self) -> Bundle: ...
    def setExtras(self, arg0: Bundle) -> None: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
