from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Criteria:
    ACCURACY_COARSE: ClassVar[int]
    ACCURACY_FINE: ClassVar[int]
    ACCURACY_HIGH: ClassVar[int]
    ACCURACY_LOW: ClassVar[int]
    ACCURACY_MEDIUM: ClassVar[int]
    CREATOR: ClassVar[Creator]
    NO_REQUIREMENT: ClassVar[int]
    POWER_HIGH: ClassVar[int]
    POWER_LOW: ClassVar[int]
    POWER_MEDIUM: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "Criteria") -> None: ...
    def setHorizontalAccuracy(self, arg0: int) -> None: ...
    def getHorizontalAccuracy(self) -> int: ...
    def setVerticalAccuracy(self, arg0: int) -> None: ...
    def getVerticalAccuracy(self) -> int: ...
    def setSpeedAccuracy(self, arg0: int) -> None: ...
    def getSpeedAccuracy(self) -> int: ...
    def setBearingAccuracy(self, arg0: int) -> None: ...
    def getBearingAccuracy(self) -> int: ...
    def setAccuracy(self, arg0: int) -> None: ...
    def getAccuracy(self) -> int: ...
    def setPowerRequirement(self, arg0: int) -> None: ...
    def getPowerRequirement(self) -> int: ...
    def setCostAllowed(self, arg0: bool) -> None: ...
    def isCostAllowed(self) -> bool: ...
    def setAltitudeRequired(self, arg0: bool) -> None: ...
    def isAltitudeRequired(self) -> bool: ...
    def setSpeedRequired(self, arg0: bool) -> None: ...
    def isSpeedRequired(self) -> bool: ...
    def setBearingRequired(self, arg0: bool) -> None: ...
    def isBearingRequired(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...
