from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.util.Printer import Printer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Location:
    CREATOR: ClassVar[Creator]
    FORMAT_DEGREES: ClassVar[int]
    FORMAT_MINUTES: ClassVar[int]
    FORMAT_SECONDS: ClassVar[int]
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: "Location") -> None: ...
    def set(self, arg0: "Location") -> None: ...
    def reset(self) -> None: ...
    def distanceTo(self, arg0: "Location") -> float: ...
    def bearingTo(self, arg0: "Location") -> float: ...
    def getProvider(self) -> str: ...
    def setProvider(self, arg0: str) -> None: ...
    def getTime(self) -> int: ...
    def setTime(self, arg0: int) -> None: ...
    def getElapsedRealtimeNanos(self) -> int: ...
    def getElapsedRealtimeMillis(self) -> int: ...
    @overload
    def getElapsedRealtimeAgeMillis(self) -> int: ...
    @overload
    def getElapsedRealtimeAgeMillis(self, arg0: int) -> int: ...
    def setElapsedRealtimeNanos(self, arg0: int) -> None: ...
    def getElapsedRealtimeUncertaintyNanos(self) -> float: ...
    def setElapsedRealtimeUncertaintyNanos(self, arg0: float) -> None: ...
    def hasElapsedRealtimeUncertaintyNanos(self) -> bool: ...
    def removeElapsedRealtimeUncertaintyNanos(self) -> None: ...
    def getLatitude(self) -> float: ...
    def setLatitude(self, arg0: float) -> None: ...
    def getLongitude(self) -> float: ...
    def setLongitude(self, arg0: float) -> None: ...
    def getAccuracy(self) -> float: ...
    def setAccuracy(self, arg0: float) -> None: ...
    def hasAccuracy(self) -> bool: ...
    def removeAccuracy(self) -> None: ...
    def getAltitude(self) -> float: ...
    def setAltitude(self, arg0: float) -> None: ...
    def hasAltitude(self) -> bool: ...
    def removeAltitude(self) -> None: ...
    def getVerticalAccuracyMeters(self) -> float: ...
    def setVerticalAccuracyMeters(self, arg0: float) -> None: ...
    def hasVerticalAccuracy(self) -> bool: ...
    def removeVerticalAccuracy(self) -> None: ...
    def getSpeed(self) -> float: ...
    def setSpeed(self, arg0: float) -> None: ...
    def hasSpeed(self) -> bool: ...
    def removeSpeed(self) -> None: ...
    def getSpeedAccuracyMetersPerSecond(self) -> float: ...
    def setSpeedAccuracyMetersPerSecond(self, arg0: float) -> None: ...
    def hasSpeedAccuracy(self) -> bool: ...
    def removeSpeedAccuracy(self) -> None: ...
    def getBearing(self) -> float: ...
    def setBearing(self, arg0: float) -> None: ...
    def hasBearing(self) -> bool: ...
    def removeBearing(self) -> None: ...
    def getBearingAccuracyDegrees(self) -> float: ...
    def setBearingAccuracyDegrees(self, arg0: float) -> None: ...
    def hasBearingAccuracy(self) -> bool: ...
    def removeBearingAccuracy(self) -> None: ...
    def getMslAltitudeMeters(self) -> float: ...
    def setMslAltitudeMeters(self, arg0: float) -> None: ...
    def hasMslAltitude(self) -> bool: ...
    def removeMslAltitude(self) -> None: ...
    def getMslAltitudeAccuracyMeters(self) -> float: ...
    def setMslAltitudeAccuracyMeters(self, arg0: float) -> None: ...
    def hasMslAltitudeAccuracy(self) -> bool: ...
    def removeMslAltitudeAccuracy(self) -> None: ...
    def isFromMockProvider(self) -> bool: ...
    def isMock(self) -> bool: ...
    def setMock(self, arg0: bool) -> None: ...
    def getExtras(self) -> Bundle: ...
    def setExtras(self, arg0: Bundle) -> None: ...
    def isComplete(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def dump(self, arg0: Printer, arg1: str) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    @overload
    @staticmethod
    def convert(arg0: float, arg1: int) -> str: ...
    @overload
    @staticmethod
    def convert(arg0: str) -> float: ...
    @staticmethod
    def distanceBetween(arg0: float, arg1: float, arg2: float, arg3: float, arg4: list[float]) -> None: ...
