from typing import Any, ClassVar, overload
from android.location.Location import Location
from android.os.Bundle import Bundle

class LocationListener:
    @overload
    def onLocationChanged(self, arg0: Location) -> None: ...
    @overload
    def onLocationChanged(self, arg0: list) -> None: ...
    def onFlushComplete(self, arg0: int) -> None: ...
    def onStatusChanged(self, arg0: str, arg1: int, arg2: Bundle) -> None: ...
    def onProviderEnabled(self, arg0: str) -> None: ...
    def onProviderDisabled(self, arg0: str) -> None: ...
