from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.os.IBinder import IBinder

class SettingInjectorService:
    ACTION_INJECTED_SETTING_CHANGED: ClassVar[str]
    ACTION_SERVICE_INTENT: ClassVar[str]
    ATTRIBUTES_NAME: ClassVar[str]
    META_DATA_NAME: ClassVar[str]
    def __init__(self, arg0: str) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onStart(self, arg0: Intent, arg1: int) -> None: ...
    def onStartCommand(self, arg0: Intent, arg1: int, arg2: int) -> int: ...
    def onGetSummary(self) -> str: ...
    def onGetEnabled(self) -> bool: ...
    @staticmethod
    def refreshSettings(arg0: Context) -> None: ...
