from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.units.Power import Power
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class BasalMetabolicRateRecord:
    BASAL_CALORIES_TOTAL: ClassVar[AggregationType]
    def getBasalMetabolicRate(self) -> Power: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: Power) -> None: ...
        def setZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearZoneOffset(self) -> "Builder": ...
        def build(self) -> "BasalMetabolicRateRecord": ...
