from typing import Any, ClassVar, overload
from android.health.connect.datatypes.units.Energy import Energy
from android.health.connect.datatypes.units.Length import Length
from java.time.Duration import Duration

class ExerciseCompletionGoal:

    class ActiveCaloriesBurnedGoal:
        def __init__(self, arg0: Energy) -> None: ...
        def getActiveCalories(self) -> Energy: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class DistanceGoal:
        def __init__(self, arg0: Length) -> None: ...
        def getDistance(self) -> Length: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class DistanceWithVariableRestGoal:
        def __init__(self, arg0: Length, arg1: Duration) -> None: ...
        def getDistance(self) -> Length: ...
        def getDuration(self) -> Duration: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class DurationGoal:
        def __init__(self, arg0: Duration) -> None: ...
        def getDuration(self) -> Duration: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class RepetitionsGoal:
        def __init__(self, arg0: int) -> None: ...
        def getRepetitions(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class StepsGoal:
        def __init__(self, arg0: int) -> None: ...
        def getSteps(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class TotalCaloriesBurnedGoal:
        def __init__(self, arg0: Energy) -> None: ...
        def getTotalCalories(self) -> Energy: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class UnknownGoal:
        INSTANCE: ClassVar["UnknownGoal"]

    class UnspecifiedGoal:
        INSTANCE: ClassVar["UnspecifiedGoal"]
