from typing import Any, ClassVar, overload
from android.health.connect.datatypes.units.Length import Length
from java.time.Instant import Instant

class ExerciseLap:
    def getLength(self) -> Length: ...
    def getStartTime(self) -> Instant: ...
    def getEndTime(self) -> Instant: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Instant, arg1: Instant) -> None: ...
        def setLength(self, arg0: Length) -> "Builder": ...
        def build(self) -> "ExerciseLap": ...
