from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.ExerciseRoute import ExerciseRoute
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class ExerciseSessionRecord:
    EXERCISE_DURATION_TOTAL: ClassVar[AggregationType]
    def getExerciseType(self) -> int: ...
    def getNotes(self) -> str: ...
    def getTitle(self) -> str: ...
    def getRoute(self) -> ExerciseRoute: ...
    def getSegments(self) -> list: ...
    def getLaps(self) -> list: ...
    def hasRoute(self) -> bool: ...
    def getPlannedExerciseSessionId(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: Instant, arg3: int) -> None: ...
        def setStartZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def setEndZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearStartZoneOffset(self) -> "Builder": ...
        def clearEndZoneOffset(self) -> "Builder": ...
        def setNotes(self, arg0: str) -> "Builder": ...
        def setTitle(self, arg0: str) -> "Builder": ...
        def setRoute(self, arg0: ExerciseRoute) -> "Builder": ...
        def setLaps(self, arg0: list) -> "Builder": ...
        def setSegments(self, arg0: list) -> "Builder": ...
        def setPlannedExerciseSessionId(self, arg0: str) -> "Builder": ...
        def build(self) -> "ExerciseSessionRecord": ...
