from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class HeartRateRecord:
    BPM_AVG: ClassVar[AggregationType]
    BPM_MAX: ClassVar[AggregationType]
    BPM_MIN: ClassVar[AggregationType]
    HEART_MEASUREMENTS_COUNT: ClassVar[AggregationType]
    def getSamples(self) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: Instant, arg3: list) -> None: ...
        def setStartZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def setEndZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearStartZoneOffset(self) -> "Builder": ...
        def clearEndZoneOffset(self) -> "Builder": ...
        def build(self) -> "HeartRateRecord": ...

    class HeartRateSample:
        def __init__(self, arg0: int, arg1: Instant) -> None: ...
        def getBeatsPerMinute(self) -> int: ...
        def getTime(self) -> Instant: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
