from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.units.Length import Length
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class HeightRecord:
    HEIGHT_AVG: ClassVar[AggregationType]
    HEIGHT_MAX: ClassVar[AggregationType]
    HEIGHT_MIN: ClassVar[AggregationType]
    def getHeight(self) -> Length: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: Length) -> None: ...
        def setZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearZoneOffset(self) -> "Builder": ...
        def build(self) -> "HeightRecord": ...
