from typing import Any, ClassVar, overload
from android.health.connect.datatypes.DataOrigin import DataOrigin
from android.health.connect.datatypes.Device import Device
from java.time.Instant import Instant

class Metadata:
    RECORDING_METHOD_ACTIVELY_RECORDED: ClassVar[int]
    RECORDING_METHOD_AUTOMATICALLY_RECORDED: ClassVar[int]
    RECORDING_METHOD_MANUAL_ENTRY: ClassVar[int]
    RECORDING_METHOD_UNKNOWN: ClassVar[int]
    def getClientRecordId(self) -> str: ...
    def getClientRecordVersion(self) -> int: ...
    def getDataOrigin(self) -> DataOrigin: ...
    def getId(self) -> str: ...
    def getRecordingMethod(self) -> int: ...
    def getLastModifiedTime(self) -> Instant: ...
    def getDevice(self) -> Device: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setDevice(self, arg0: Device) -> "Builder": ...
        def setDataOrigin(self, arg0: DataOrigin) -> "Builder": ...
        def setId(self, arg0: str) -> "Builder": ...
        def setLastModifiedTime(self, arg0: Instant) -> "Builder": ...
        def setClientRecordId(self, arg0: str) -> "Builder": ...
        def setClientRecordVersion(self, arg0: int) -> "Builder": ...
        def setRecordingMethod(self, arg0: int) -> "Builder": ...
        def build(self) -> "Metadata": ...
