from typing import Any, ClassVar, overload
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class OvulationTestRecord:
    def getResult(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: int) -> None: ...
        def setZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearZoneOffset(self) -> "Builder": ...
        def build(self) -> "OvulationTestRecord": ...

    class OvulationTestResult:
        RESULT_HIGH: ClassVar[int]
        RESULT_INCONCLUSIVE: ClassVar[int]
        RESULT_NEGATIVE: ClassVar[int]
        RESULT_POSITIVE: ClassVar[int]
