from typing import Any, ClassVar, overload
from android.health.connect.datatypes.ExerciseCompletionGoal import ExerciseCompletionGoal
from android.health.connect.datatypes.ExercisePerformanceGoal import ExercisePerformanceGoal

class PlannedExerciseStep:
    EXERCISE_CATEGORY_ACTIVE: ClassVar[int]
    EXERCISE_CATEGORY_COOLDOWN: ClassVar[int]
    EXERCISE_CATEGORY_RECOVERY: ClassVar[int]
    EXERCISE_CATEGORY_REST: ClassVar[int]
    EXERCISE_CATEGORY_UNKNOWN: ClassVar[int]
    EXERCISE_CATEGORY_WARMUP: ClassVar[int]
    def getExerciseType(self) -> int: ...
    def getDescription(self) -> str: ...
    def getExerciseCategory(self) -> int: ...
    def getCompletionGoal(self) -> ExerciseCompletionGoal: ...
    def getPerformanceGoals(self) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: int, arg1: int, arg2: ExerciseCompletionGoal) -> None: ...
        def setExerciseType(self, arg0: int) -> "Builder": ...
        def setExerciseCategory(self, arg0: int) -> "Builder": ...
        def setDescription(self, arg0: str) -> "Builder": ...
        def setCompletionGoal(self, arg0: ExerciseCompletionGoal) -> "Builder": ...
        def addPerformanceGoal(self, arg0: ExercisePerformanceGoal) -> "Builder": ...
        def setPerformanceGoals(self, arg0: list) -> "Builder": ...
        def clearPerformanceGoals(self) -> "Builder": ...
        def build(self) -> "PlannedExerciseStep": ...
