from typing import Any, ClassVar, overload
from android.health.connect.datatypes.PlannedExerciseStep import PlannedExerciseStep

class PlannedExerciseBlock:
    def getDescription(self) -> str: ...
    def getSteps(self) -> list: ...
    def getRepetitions(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: int) -> None: ...
        def setRepetitions(self, arg0: int) -> "Builder": ...
        def setDescription(self, arg0: str) -> "Builder": ...
        def addStep(self, arg0: PlannedExerciseStep) -> "Builder": ...
        def setSteps(self, arg0: list) -> "Builder": ...
        def clearSteps(self) -> "Builder": ...
        def build(self) -> "PlannedExerciseBlock": ...
