from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.units.Power import Power
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class PowerRecord:
    POWER_AVG: ClassVar[AggregationType]
    POWER_MAX: ClassVar[AggregationType]
    POWER_MIN: ClassVar[AggregationType]
    def getSamples(self) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: Instant, arg3: list) -> None: ...
        def setStartZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def setEndZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearStartZoneOffset(self) -> "Builder": ...
        def clearEndZoneOffset(self) -> "Builder": ...
        def build(self) -> "PowerRecord": ...

    class PowerRecordSample:
        def __init__(self, arg0: Power, arg1: Instant) -> None: ...
        def getPower(self) -> Power: ...
        def getTime(self) -> Instant: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
