from typing import Any, ClassVar, overload
from android.health.connect.datatypes.Metadata import Metadata

class Record:
    def getMetadata(self) -> Metadata: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
