from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.units.Temperature import Temperature
from android.health.connect.datatypes.units.TemperatureDelta import TemperatureDelta
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class SkinTemperatureRecord:
    MEASUREMENT_LOCATION_FINGER: ClassVar[int]
    MEASUREMENT_LOCATION_TOE: ClassVar[int]
    MEASUREMENT_LOCATION_UNKNOWN: ClassVar[int]
    MEASUREMENT_LOCATION_WRIST: ClassVar[int]
    SKIN_TEMPERATURE_DELTA_AVG: ClassVar[AggregationType]
    SKIN_TEMPERATURE_DELTA_MAX: ClassVar[AggregationType]
    SKIN_TEMPERATURE_DELTA_MIN: ClassVar[AggregationType]
    def getBaseline(self) -> Temperature: ...
    def getDeltas(self) -> list: ...
    def getMeasurementLocation(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: Instant) -> None: ...
        def setStartZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def setEndZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearStartZoneOffset(self) -> "Builder": ...
        def clearEndZoneOffset(self) -> "Builder": ...
        def setBaseline(self, arg0: Temperature) -> "Builder": ...
        def setDeltas(self, arg0: list) -> "Builder": ...
        def setMeasurementLocation(self, arg0: int) -> "Builder": ...
        def build(self) -> "SkinTemperatureRecord": ...

    class Delta:
        def __init__(self, arg0: TemperatureDelta, arg1: Instant) -> None: ...
        def getDelta(self) -> TemperatureDelta: ...
        def getTime(self) -> Instant: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
