from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class StepsCadenceRecord:
    STEPS_CADENCE_RATE_AVG: ClassVar[AggregationType]
    STEPS_CADENCE_RATE_MAX: ClassVar[AggregationType]
    STEPS_CADENCE_RATE_MIN: ClassVar[AggregationType]
    def getSamples(self) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: Instant, arg3: list) -> None: ...
        def setStartZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def setEndZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearStartZoneOffset(self) -> "Builder": ...
        def clearEndZoneOffset(self) -> "Builder": ...
        def build(self) -> "StepsCadenceRecord": ...

    class StepsCadenceRecordSample:
        def __init__(self, arg0: float, arg1: Instant) -> None: ...
        def getRate(self) -> float: ...
        def getTime(self) -> Instant: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
