from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.units.Mass import Mass
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class WeightRecord:
    WEIGHT_AVG: ClassVar[AggregationType]
    WEIGHT_MAX: ClassVar[AggregationType]
    WEIGHT_MIN: ClassVar[AggregationType]
    def getWeight(self) -> Mass: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Metadata, arg1: Instant, arg2: Mass) -> None: ...
        def setZoneOffset(self, arg0: ZoneOffset) -> "Builder": ...
        def clearZoneOffset(self) -> "Builder": ...
        def build(self) -> "WeightRecord": ...
