from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.Context import Context
from android.content.Intent import Intent
from android.net.sip.SipAudioCall import SipAudioCall
from android.net.sip.SipProfile import SipProfile
from android.net.sip.SipRegistrationListener import SipRegistrationListener
from android.net.sip.SipSession import SipSession

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Listener:
    """Forward declaration for ``android.net.sip.SipAudioCall.Listener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.net.sip.SipAudioCall.Listener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/net/sip/SipAudioCall/Listener
    """
    ...

class SipManager:
    EXTRA_CALL_ID: ClassVar[str]
    EXTRA_OFFER_SD: ClassVar[str]
    INCOMING_CALL_RESULT_CODE: ClassVar[int]
    @staticmethod
    def newInstance(arg0: Context) -> "SipManager": ...
    @staticmethod
    def isApiSupported(arg0: Context) -> bool: ...
    @staticmethod
    def isVoipSupported(arg0: Context) -> bool: ...
    @staticmethod
    def isSipWifiOnly(arg0: Context) -> bool: ...
    @overload
    def open(self, arg0: SipProfile) -> None: ...
    @overload
    def open(self, arg0: SipProfile, arg1: PendingIntent, arg2: SipRegistrationListener) -> None: ...
    def setRegistrationListener(self, arg0: str, arg1: SipRegistrationListener) -> None: ...
    def close(self, arg0: str) -> None: ...
    def isOpened(self, arg0: str) -> bool: ...
    def isRegistered(self, arg0: str) -> bool: ...
    @overload
    def makeAudioCall(self, arg0: SipProfile, arg1: SipProfile, arg2: Listener, arg3: int) -> SipAudioCall: ...
    @overload
    def makeAudioCall(self, arg0: str, arg1: str, arg2: Listener, arg3: int) -> SipAudioCall: ...
    def takeAudioCall(self, arg0: Intent, arg1: Listener) -> SipAudioCall: ...
    @staticmethod
    def isIncomingCallIntent(arg0: Intent) -> bool: ...
    @staticmethod
    def getCallId(arg0: Intent) -> str: ...
    @staticmethod
    def getOfferSessionDescription(arg0: Intent) -> str: ...
    def register(self, arg0: SipProfile, arg1: int, arg2: SipRegistrationListener) -> None: ...
    def unregister(self, arg0: SipProfile, arg1: SipRegistrationListener) -> None: ...
    def getSessionFor(self, arg0: Intent) -> SipSession: ...
    def createSipSession(self, arg0: SipProfile, arg1: Listener) -> SipSession: ...
