from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SipProfile:
    CREATOR: ClassVar[Creator]
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getUriString(self) -> str: ...
    def getDisplayName(self) -> str: ...
    def getUserName(self) -> str: ...
    def getAuthUserName(self) -> str: ...
    def getPassword(self) -> str: ...
    def getSipDomain(self) -> str: ...
    def getPort(self) -> int: ...
    def getProtocol(self) -> str: ...
    def getProxyAddress(self) -> str: ...
    def getProfileName(self) -> str: ...
    def getSendKeepAlive(self) -> bool: ...
    def getAutoRegistration(self) -> bool: ...
    def setCallingUid(self, arg0: int) -> None: ...

    class Builder:
        @overload
        def __init__(self, arg0: "SipProfile") -> None: ...
        @overload
        def __init__(self, arg0: str) -> None: ...
        @overload
        def __init__(self, arg0: str, arg1: str) -> None: ...
        def setAuthUserName(self, arg0: str) -> "Builder": ...
        def setProfileName(self, arg0: str) -> "Builder": ...
        def setPassword(self, arg0: str) -> "Builder": ...
        def setPort(self, arg0: int) -> "Builder": ...
        def setProtocol(self, arg0: str) -> "Builder": ...
        def setOutboundProxy(self, arg0: str) -> "Builder": ...
        def setDisplayName(self, arg0: str) -> "Builder": ...
        def setSendKeepAlive(self, arg0: bool) -> "Builder": ...
        def setAutoRegistration(self, arg0: bool) -> "Builder": ...
        def build(self) -> "SipProfile": ...
