from typing import Any, ClassVar, overload

class SipRegistrationListener:
    def onRegistering(self, arg0: str) -> None: ...
    def onRegistrationDone(self, arg0: str, arg1: int) -> None: ...
    def onRegistrationFailed(self, arg0: str, arg1: int, arg2: str) -> None: ...
