from typing import Any, ClassVar, overload
from android.net.sip.SipProfile import SipProfile

class SipSession:
    def getLocalIp(self) -> str: ...
    def getLocalProfile(self) -> SipProfile: ...
    def getPeerProfile(self) -> SipProfile: ...
    def getState(self) -> int: ...
    def isInCall(self) -> bool: ...
    def getCallId(self) -> str: ...
    def setListener(self, arg0: "Listener") -> None: ...
    def register(self, arg0: int) -> None: ...
    def unregister(self) -> None: ...
    def makeCall(self, arg0: SipProfile, arg1: str, arg2: int) -> None: ...
    def answerCall(self, arg0: str, arg1: int) -> None: ...
    def endCall(self) -> None: ...
    def changeCall(self, arg0: str, arg1: int) -> None: ...

    class Listener:
        def __init__(self) -> None: ...
        def onCalling(self, arg0: "SipSession") -> None: ...
        def onRinging(self, arg0: "SipSession", arg1: SipProfile, arg2: str) -> None: ...
        def onRingingBack(self, arg0: "SipSession") -> None: ...
        def onCallEstablished(self, arg0: "SipSession", arg1: str) -> None: ...
        def onCallEnded(self, arg0: "SipSession") -> None: ...
        def onCallBusy(self, arg0: "SipSession") -> None: ...
        def onError(self, arg0: "SipSession", arg1: int, arg2: str) -> None: ...
        def onCallChangeFailed(self, arg0: "SipSession", arg1: int, arg2: str) -> None: ...
        def onRegistering(self, arg0: "SipSession") -> None: ...
        def onRegistrationDone(self, arg0: "SipSession", arg1: int) -> None: ...
        def onRegistrationFailed(self, arg0: "SipSession", arg1: int, arg2: str) -> None: ...
        def onRegistrationTimeout(self, arg0: "SipSession") -> None: ...

    class State:
        DEREGISTERING: ClassVar[int]
        INCOMING_CALL: ClassVar[int]
        INCOMING_CALL_ANSWERING: ClassVar[int]
        IN_CALL: ClassVar[int]
        NOT_DEFINED: ClassVar[int]
        OUTGOING_CALL: ClassVar[int]
        OUTGOING_CALL_CANCELING: ClassVar[int]
        OUTGOING_CALL_RING_BACK: ClassVar[int]
        PINGING: ClassVar[int]
        READY_TO_CALL: ClassVar[int]
        REGISTERING: ClassVar[int]
        @staticmethod
        def toString(arg0: int) -> str: ...
