from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.gms.ads.MediaContent import MediaContent
from android.gms.internal.ads.zzblx import zzblx
from android.gms.internal.ads.zzblz import zzblz
from android.util.AttributeSet import AttributeSet
from android.widget.ImageView.ScaleType import ScaleType

class MediaView:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setMediaContent(self, arg0: MediaContent) -> None: ...
    def getMediaContent(self) -> MediaContent: ...
    def setImageScaleType(self, arg0: ScaleType) -> None: ...
    def zza(self, arg0: zzblx) -> None: ...
    def zzb(self, arg0: zzblz) -> None: ...
