from typing import Any, ClassVar, overload

class NativeAdOptions:
    NATIVE_MEDIA_ASPECT_RATIO_UNKNOWN: ClassVar[int]
    NATIVE_MEDIA_ASPECT_RATIO_ANY: ClassVar[int]
    NATIVE_MEDIA_ASPECT_RATIO_LANDSCAPE: ClassVar[int]
    NATIVE_MEDIA_ASPECT_RATIO_PORTRAIT: ClassVar[int]
    NATIVE_MEDIA_ASPECT_RATIO_SQUARE: ClassVar[int]
    ADCHOICES_TOP_LEFT: ClassVar[int]
    ADCHOICES_TOP_RIGHT: ClassVar[int]
    ADCHOICES_BOTTOM_RIGHT: ClassVar[int]
    ADCHOICES_BOTTOM_LEFT: ClassVar[int]
    SWIPE_GESTURE_DIRECTION_RIGHT: ClassVar[int]
    SWIPE_GESTURE_DIRECTION_LEFT: ClassVar[int]
    SWIPE_GESTURE_DIRECTION_UP: ClassVar[int]
    SWIPE_GESTURE_DIRECTION_DOWN: ClassVar[int]
    def shouldReturnUrlsForImageAssets(self) -> bool: ...
    def getMediaAspectRatio(self) -> int: ...
    def shouldRequestMultipleImages(self) -> bool: ...
    def getAdChoicesPlacement(self) -> int: ...
    def getVideoOptions(self) -> "VideoOptions": ...
    def zza(self) -> bool: ...
    def zzb(self) -> int: ...
    def zzc(self) -> bool: ...
    def zzd(self) -> int: ...

    class AdChoicesPlacement:
        ...

    class Builder:
        def __init__(self) -> None: ...
        def setReturnUrlsForImageAssets(self, arg0: bool) -> "Builder": ...
        def setMediaAspectRatio(self, arg0: int) -> "Builder": ...
        def setRequestMultipleImages(self, arg0: bool) -> "Builder": ...
        def setAdChoicesPlacement(self, arg0: int) -> "Builder": ...
        def setVideoOptions(self, arg0: "VideoOptions") -> "Builder": ...
        def enableCustomClickGestureDirection(self, arg0: int, arg1: bool) -> "Builder": ...
        def setRequestCustomMuteThisAd(self, arg0: bool) -> "Builder": ...
        def build(self) -> "NativeAdOptions": ...
        def zzi(self, arg0: int) -> "Builder": ...

    class NativeMediaAspectRatio:
        ...

    class SwipeGestureDirection:
        ...
