from typing import Any, ClassVar, overload
from android.gms.ads.MediaContent import MediaContent
from android.gms.ads.MuteThisAdListener import MuteThisAdListener
from android.gms.ads.MuteThisAdReason import MuteThisAdReason
from android.gms.ads.OnPaidEventListener import OnPaidEventListener
from android.gms.ads.ResponseInfo import ResponseInfo

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Bundle: ...  # android.os.Bundle
class Drawable: ...  # android.graphics.drawable.Drawable
class Uri: ...  # android.net.Uri

class NativeAd:
    def __init__(self) -> None: ...
    def getHeadline(self) -> str: ...
    def getImages(self) -> list: ...
    def getBody(self) -> str: ...
    def getIcon(self) -> "Image": ...
    def getCallToAction(self) -> str: ...
    def getAdvertiser(self) -> str: ...
    def getStarRating(self) -> float: ...
    def getStore(self) -> str: ...
    def getPrice(self) -> str: ...
    def getAdChoicesInfo(self) -> "AdChoicesInfo": ...
    def isCustomMuteThisAdEnabled(self) -> bool: ...
    def getMuteThisAdReasons(self) -> list: ...
    def muteThisAd(self, arg0: MuteThisAdReason) -> None: ...
    def setMuteThisAdListener(self, arg0: MuteThisAdListener) -> None: ...
    def getExtras(self) -> Bundle: ...
    def destroy(self) -> None: ...
    def setUnconfirmedClickListener(self, arg0: "UnconfirmedClickListener") -> None: ...
    def cancelUnconfirmedClick(self) -> None: ...
    def enableCustomClickGesture(self) -> None: ...
    def isCustomClickGestureEnabled(self) -> bool: ...
    def recordCustomClickGesture(self) -> None: ...
    def performClick(self, arg0: Bundle) -> None: ...
    def recordImpression(self, arg0: Bundle) -> bool: ...
    def reportTouchEvent(self, arg0: Bundle) -> None: ...
    def getMediaContent(self) -> MediaContent: ...
    def getResponseInfo(self) -> ResponseInfo: ...
    def setOnPaidEventListener(self, arg0: OnPaidEventListener) -> None: ...
    def recordEvent(self, arg0: Bundle) -> None: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
    def zza(self) -> Any: ...

    class AdChoicesInfo:
        def __init__(self) -> None: ...
        def getText(self) -> str: ...
        def getImages(self) -> list: ...

    class Image:
        zza: dict
        def __init__(self) -> None: ...
        def getDrawable(self) -> Drawable: ...
        def getUri(self) -> Uri: ...
        def getScale(self) -> float: ...
        def zza(self) -> int: ...
        def zzb(self) -> int: ...

    class OnNativeAdLoadedListener:
        def onNativeAdLoaded(self, arg0: "NativeAd") -> None: ...

    class UnconfirmedClickListener:
        def onUnconfirmedClickReceived(self, arg0: str) -> None: ...
        def onUnconfirmedClickCancelled(self) -> None: ...
