from typing import Any, ClassVar, overload
from android.gms.ads.MediaContent import MediaContent

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Image: ...  # com.google.android.gms.ads.nativead.NativeAd.Image
class View: ...  # android.view.View

class NativeCustomFormatAd:
    ASSET_NAME_VIDEO: ClassVar[str]
    def getText(self, arg0: str) -> str: ...
    def getImage(self, arg0: str) -> Image: ...
    def getMediaContent(self) -> MediaContent: ...
    def getAvailableAssetNames(self) -> list: ...
    def getCustomFormatId(self) -> str: ...
    def performClick(self, arg0: str) -> None: ...
    def recordImpression(self) -> None: ...
    def getDisplayOpenMeasurement(self) -> "DisplayOpenMeasurement": ...
    def destroy(self) -> None: ...

    class DisplayOpenMeasurement:
        def start(self) -> bool: ...
        def setView(self, arg0: View) -> None: ...

    class OnCustomClickListener:
        def onCustomClick(self, arg0: "NativeCustomFormatAd", arg1: str) -> None: ...

    class OnCustomFormatAdLoadedListener:
        def onCustomFormatAdLoaded(self, arg0: "NativeCustomFormatAd") -> None: ...
