from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from java.util.prefs.NodeChangeListener import NodeChangeListener
from java.util.prefs.PreferenceChangeListener import PreferenceChangeListener
from java.util.prefs.Preferences import Preferences

class AbstractPreferences:
    lock: Any
    newNode: bool
    def __init__(self, arg0: "AbstractPreferences", arg1: str) -> None: ...
    def put(self, arg0: str, arg1: str) -> None: ...
    def get(self, arg0: str, arg1: str) -> str: ...
    def remove(self, arg0: str) -> None: ...
    def clear(self) -> None: ...
    def putInt(self, arg0: str, arg1: int) -> None: ...
    def getInt(self, arg0: str, arg1: int) -> int: ...
    def putLong(self, arg0: str, arg1: int) -> None: ...
    def getLong(self, arg0: str, arg1: int) -> int: ...
    def putBoolean(self, arg0: str, arg1: bool) -> None: ...
    def getBoolean(self, arg0: str, arg1: bool) -> bool: ...
    def putFloat(self, arg0: str, arg1: float) -> None: ...
    def getFloat(self, arg0: str, arg1: float) -> float: ...
    def putDouble(self, arg0: str, arg1: float) -> None: ...
    def getDouble(self, arg0: str, arg1: float) -> float: ...
    def putByteArray(self, arg0: str, arg1: list[int]) -> None: ...
    def getByteArray(self, arg0: str, arg1: list[int]) -> list[int]: ...
    def keys(self) -> list[str]: ...
    def childrenNames(self) -> list[str]: ...
    def cachedChildren(self) -> list["AbstractPreferences"]: ...
    def parent(self) -> Preferences: ...
    def node(self, arg0: str) -> Preferences: ...
    def nodeExists(self, arg0: str) -> bool: ...
    def removeNode(self) -> None: ...
    def name(self) -> str: ...
    def absolutePath(self) -> str: ...
    def isUserNode(self) -> bool: ...
    def addPreferenceChangeListener(self, arg0: PreferenceChangeListener) -> None: ...
    def removePreferenceChangeListener(self, arg0: PreferenceChangeListener) -> None: ...
    def addNodeChangeListener(self, arg0: NodeChangeListener) -> None: ...
    def removeNodeChangeListener(self, arg0: NodeChangeListener) -> None: ...
    def putSpi(self, arg0: str, arg1: str) -> None: ...
    def getSpi(self, arg0: str) -> str: ...
    def removeSpi(self, arg0: str) -> None: ...
    def removeNodeSpi(self) -> None: ...
    def keysSpi(self) -> list[str]: ...
    def childrenNamesSpi(self) -> list[str]: ...
    def getChild(self, arg0: str) -> "AbstractPreferences": ...
    def childSpi(self, arg0: str) -> "AbstractPreferences": ...
    def toString(self) -> str: ...
    def sync(self) -> None: ...
    def syncSpi(self) -> None: ...
    def flush(self) -> None: ...
    def flushSpi(self) -> None: ...
    def isRemoved(self) -> bool: ...
    def exportNode(self, arg0: OutputStream) -> None: ...
    def exportSubtree(self, arg0: OutputStream) -> None: ...
