from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.time.Instant import Instant

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ChangeLogsResponse:
    CREATOR: ClassVar[Creator]
    def getUpsertedRecords(self) -> list: ...
    def getDeletedLogs(self) -> list: ...
    def getNextChangesToken(self) -> str: ...
    def hasMorePages(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class DeletedLog:
        def __init__(self, arg0: str, arg1: int) -> None: ...
        def getDeletedRecordId(self) -> str: ...
        def getDeletedTime(self) -> Instant: ...
