from typing import Any, ClassVar, overload
from javax.xml.namespace.NamespaceContext import NamespaceContext
from javax.xml.namespace.QName import QName
from javax.xml.xpath.XPathExpression import XPathExpression
from javax.xml.xpath.XPathFunctionResolver import XPathFunctionResolver
from javax.xml.xpath.XPathVariableResolver import XPathVariableResolver
from org.xml.sax.InputSource import InputSource

class XPath:
    def reset(self) -> None: ...
    def setXPathVariableResolver(self, arg0: XPathVariableResolver) -> None: ...
    def getXPathVariableResolver(self) -> XPathVariableResolver: ...
    def setXPathFunctionResolver(self, arg0: XPathFunctionResolver) -> None: ...
    def getXPathFunctionResolver(self) -> XPathFunctionResolver: ...
    def setNamespaceContext(self, arg0: NamespaceContext) -> None: ...
    def getNamespaceContext(self) -> NamespaceContext: ...
    def compile(self, arg0: str) -> XPathExpression: ...
    @overload
    def evaluate(self, arg0: str, arg1: Any, arg2: QName) -> Any: ...
    @overload
    def evaluate(self, arg0: str, arg1: Any) -> str: ...
    @overload
    def evaluate(self, arg0: str, arg1: InputSource, arg2: QName) -> Any: ...
    @overload
    def evaluate(self, arg0: str, arg1: InputSource) -> str: ...
