from typing import Any, ClassVar, overload
from org.xml.sax.Attributes import Attributes

class AttributesImpl:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Attributes) -> None: ...
    def getLength(self) -> int: ...
    def getURI(self, arg0: int) -> str: ...
    def getLocalName(self, arg0: int) -> str: ...
    def getQName(self, arg0: int) -> str: ...
    @overload
    def getType(self, arg0: int) -> str: ...
    @overload
    def getType(self, arg0: str, arg1: str) -> str: ...
    @overload
    def getType(self, arg0: str) -> str: ...
    @overload
    def getValue(self, arg0: int) -> str: ...
    @overload
    def getValue(self, arg0: str, arg1: str) -> str: ...
    @overload
    def getValue(self, arg0: str) -> str: ...
    @overload
    def getIndex(self, arg0: str, arg1: str) -> int: ...
    @overload
    def getIndex(self, arg0: str) -> int: ...
    def clear(self) -> None: ...
    def setAttributes(self, arg0: Attributes) -> None: ...
    def addAttribute(self, arg0: str, arg1: str, arg2: str, arg3: str, arg4: str) -> None: ...
    def setAttribute(self, arg0: int, arg1: str, arg2: str, arg3: str, arg4: str, arg5: str) -> None: ...
    def removeAttribute(self, arg0: int) -> None: ...
    def setURI(self, arg0: int, arg1: str) -> None: ...
    def setLocalName(self, arg0: int, arg1: str) -> None: ...
    def setQName(self, arg0: int, arg1: str) -> None: ...
    def setType(self, arg0: int, arg1: str) -> None: ...
    def setValue(self, arg0: int, arg1: str) -> None: ...
