from typing import Any, ClassVar, overload
from org.xml.sax.AttributeList import AttributeList
from org.xml.sax.ContentHandler import ContentHandler
from org.xml.sax.DTDHandler import DTDHandler
from org.xml.sax.EntityResolver import EntityResolver
from org.xml.sax.ErrorHandler import ErrorHandler
from org.xml.sax.InputSource import InputSource
from org.xml.sax.Locator import Locator
from org.xml.sax.Parser import Parser

class ParserAdapter:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Parser) -> None: ...
    def setFeature(self, arg0: str, arg1: bool) -> None: ...
    def getFeature(self, arg0: str) -> bool: ...
    def setProperty(self, arg0: str, arg1: Any) -> None: ...
    def getProperty(self, arg0: str) -> Any: ...
    def setEntityResolver(self, arg0: EntityResolver) -> None: ...
    def getEntityResolver(self) -> EntityResolver: ...
    def setDTDHandler(self, arg0: DTDHandler) -> None: ...
    def getDTDHandler(self) -> DTDHandler: ...
    def setContentHandler(self, arg0: ContentHandler) -> None: ...
    def getContentHandler(self) -> ContentHandler: ...
    def setErrorHandler(self, arg0: ErrorHandler) -> None: ...
    def getErrorHandler(self) -> ErrorHandler: ...
    @overload
    def parse(self, arg0: str) -> None: ...
    @overload
    def parse(self, arg0: InputSource) -> None: ...
    def setDocumentLocator(self, arg0: Locator) -> None: ...
    def startDocument(self) -> None: ...
    def endDocument(self) -> None: ...
    def startElement(self, arg0: str, arg1: AttributeList) -> None: ...
    def endElement(self, arg0: str) -> None: ...
    def characters(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    def ignorableWhitespace(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    def processingInstruction(self, arg0: str, arg1: str) -> None: ...
