from typing import Any, ClassVar, overload
from java.util.Locale import Locale
from org.xml.sax.Attributes import Attributes
from org.xml.sax.DTDHandler import DTDHandler
from org.xml.sax.DocumentHandler import DocumentHandler
from org.xml.sax.EntityResolver import EntityResolver
from org.xml.sax.ErrorHandler import ErrorHandler
from org.xml.sax.InputSource import InputSource
from org.xml.sax.Locator import Locator
from org.xml.sax.XMLReader import XMLReader

class XMLReaderAdapter:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: XMLReader) -> None: ...
    def setLocale(self, arg0: Locale) -> None: ...
    def setEntityResolver(self, arg0: EntityResolver) -> None: ...
    def setDTDHandler(self, arg0: DTDHandler) -> None: ...
    def setDocumentHandler(self, arg0: DocumentHandler) -> None: ...
    def setErrorHandler(self, arg0: ErrorHandler) -> None: ...
    @overload
    def parse(self, arg0: str) -> None: ...
    @overload
    def parse(self, arg0: InputSource) -> None: ...
    def setDocumentLocator(self, arg0: Locator) -> None: ...
    def startDocument(self) -> None: ...
    def endDocument(self) -> None: ...
    def startPrefixMapping(self, arg0: str, arg1: str) -> None: ...
    def endPrefixMapping(self, arg0: str) -> None: ...
    def startElement(self, arg0: str, arg1: str, arg2: str, arg3: Attributes) -> None: ...
    def endElement(self, arg0: str, arg1: str, arg2: str) -> None: ...
    def characters(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    def ignorableWhitespace(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    def processingInstruction(self, arg0: str, arg1: str) -> None: ...
    def skippedEntity(self, arg0: str) -> None: ...
