from typing import Any, ClassVar, overload

class UsbConstants:
    USB_CLASS_APP_SPEC: ClassVar[int]
    USB_CLASS_AUDIO: ClassVar[int]
    USB_CLASS_CDC_DATA: ClassVar[int]
    USB_CLASS_COMM: ClassVar[int]
    USB_CLASS_CONTENT_SEC: ClassVar[int]
    USB_CLASS_CSCID: ClassVar[int]
    USB_CLASS_HID: ClassVar[int]
    USB_CLASS_HUB: ClassVar[int]
    USB_CLASS_MASS_STORAGE: ClassVar[int]
    USB_CLASS_MISC: ClassVar[int]
    USB_CLASS_PER_INTERFACE: ClassVar[int]
    USB_CLASS_PHYSICA: ClassVar[int]
    USB_CLASS_PRINTER: ClassVar[int]
    USB_CLASS_STILL_IMAGE: ClassVar[int]
    USB_CLASS_VENDOR_SPEC: ClassVar[int]
    USB_CLASS_VIDEO: ClassVar[int]
    USB_CLASS_WIRELESS_CONTROLLER: ClassVar[int]
    USB_DIR_IN: ClassVar[int]
    USB_DIR_OUT: ClassVar[int]
    USB_ENDPOINT_DIR_MASK: ClassVar[int]
    USB_ENDPOINT_NUMBER_MASK: ClassVar[int]
    USB_ENDPOINT_XFERTYPE_MASK: ClassVar[int]
    USB_ENDPOINT_XFER_BULK: ClassVar[int]
    USB_ENDPOINT_XFER_CONTROL: ClassVar[int]
    USB_ENDPOINT_XFER_INT: ClassVar[int]
    USB_ENDPOINT_XFER_ISOC: ClassVar[int]
    USB_INTERFACE_SUBCLASS_BOOT: ClassVar[int]
    USB_SUBCLASS_VENDOR_SPEC: ClassVar[int]
    USB_TYPE_CLASS: ClassVar[int]
    USB_TYPE_MASK: ClassVar[int]
    USB_TYPE_RESERVED: ClassVar[int]
    USB_TYPE_STANDARD: ClassVar[int]
    USB_TYPE_VENDOR: ClassVar[int]
    def __init__(self) -> None: ...
