from typing import Any, ClassVar, overload
from android.hardware.usb.UsbConfiguration import UsbConfiguration
from android.hardware.usb.UsbInterface import UsbInterface
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class UsbDevice:
    CREATOR: ClassVar[Creator]
    @overload
    def getDeviceName(self) -> str: ...
    @overload
    @staticmethod
    def getDeviceName(arg0: int) -> str: ...
    def getManufacturerName(self) -> str: ...
    def getProductName(self) -> str: ...
    def getVersion(self) -> str: ...
    def getSerialNumber(self) -> str: ...
    @overload
    def getDeviceId(self) -> int: ...
    @overload
    @staticmethod
    def getDeviceId(arg0: str) -> int: ...
    def getVendorId(self) -> int: ...
    def getProductId(self) -> int: ...
    def getDeviceClass(self) -> int: ...
    def getDeviceSubclass(self) -> int: ...
    def getDeviceProtocol(self) -> int: ...
    def getConfigurationCount(self) -> int: ...
    def getConfiguration(self, arg0: int) -> UsbConfiguration: ...
    def getInterfaceCount(self) -> int: ...
    def getInterface(self, arg0: int) -> UsbInterface: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
