from typing import Any, ClassVar, overload
from android.hardware.usb.UsbConfiguration import UsbConfiguration
from android.hardware.usb.UsbEndpoint import UsbEndpoint
from android.hardware.usb.UsbInterface import UsbInterface
from android.hardware.usb.UsbRequest import UsbRequest

class UsbDeviceConnection:
    def close(self) -> None: ...
    def getFileDescriptor(self) -> int: ...
    def getRawDescriptors(self) -> list[int]: ...
    def claimInterface(self, arg0: UsbInterface, arg1: bool) -> bool: ...
    def releaseInterface(self, arg0: UsbInterface) -> bool: ...
    def setInterface(self, arg0: UsbInterface) -> bool: ...
    def setConfiguration(self, arg0: UsbConfiguration) -> bool: ...
    @overload
    def controlTransfer(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[int], arg5: int, arg6: int) -> int: ...
    @overload
    def controlTransfer(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[int], arg5: int, arg6: int, arg7: int) -> int: ...
    @overload
    def bulkTransfer(self, arg0: UsbEndpoint, arg1: list[int], arg2: int, arg3: int) -> int: ...
    @overload
    def bulkTransfer(self, arg0: UsbEndpoint, arg1: list[int], arg2: int, arg3: int, arg4: int) -> int: ...
    @overload
    def requestWait(self) -> UsbRequest: ...
    @overload
    def requestWait(self, arg0: int) -> UsbRequest: ...
    def getSerial(self) -> str: ...
    def finalize(self) -> None: ...
