from typing import Any, ClassVar, overload
from android.app.people.ConversationStatus import ConversationStatus

class PeopleManager:
    def addOrUpdateStatus(self, arg0: str, arg1: ConversationStatus) -> None: ...
    def clearStatus(self, arg0: str, arg1: str) -> None: ...
    def clearStatuses(self, arg0: str) -> None: ...
    def getStatuses(self, arg0: str) -> list: ...
