from typing import Any, ClassVar, overload
from java.util.Random import Random

class BigInteger:
    ONE: ClassVar["BigInteger"]
    TEN: ClassVar["BigInteger"]
    TWO: ClassVar["BigInteger"]
    ZERO: ClassVar["BigInteger"]
    @overload
    def __init__(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: list[int], arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: Random) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: Random) -> None: ...
    @staticmethod
    def probablePrime(arg0: int, arg1: Random) -> "BigInteger": ...
    def nextProbablePrime(self) -> "BigInteger": ...
    @staticmethod
    def valueOf(arg0: int) -> "BigInteger": ...
    def add(self, arg0: "BigInteger") -> "BigInteger": ...
    def subtract(self, arg0: "BigInteger") -> "BigInteger": ...
    def multiply(self, arg0: "BigInteger") -> "BigInteger": ...
    def divide(self, arg0: "BigInteger") -> "BigInteger": ...
    def divideAndRemainder(self, arg0: "BigInteger") -> list["BigInteger"]: ...
    def remainder(self, arg0: "BigInteger") -> "BigInteger": ...
    def pow(self, arg0: int) -> "BigInteger": ...
    def sqrt(self) -> "BigInteger": ...
    def sqrtAndRemainder(self) -> list["BigInteger"]: ...
    def gcd(self, arg0: "BigInteger") -> "BigInteger": ...
    def abs(self) -> "BigInteger": ...
    def negate(self) -> "BigInteger": ...
    def signum(self) -> int: ...
    def mod(self, arg0: "BigInteger") -> "BigInteger": ...
    def modPow(self, arg0: "BigInteger", arg1: "BigInteger") -> "BigInteger": ...
    def modInverse(self, arg0: "BigInteger") -> "BigInteger": ...
    def shiftLeft(self, arg0: int) -> "BigInteger": ...
    def shiftRight(self, arg0: int) -> "BigInteger": ...
    def and_(self, arg0: "BigInteger") -> "BigInteger": ...
    def or_(self, arg0: "BigInteger") -> "BigInteger": ...
    def xor(self, arg0: "BigInteger") -> "BigInteger": ...
    def not_(self) -> "BigInteger": ...
    def andNot(self, arg0: "BigInteger") -> "BigInteger": ...
    def testBit(self, arg0: int) -> bool: ...
    def setBit(self, arg0: int) -> "BigInteger": ...
    def clearBit(self, arg0: int) -> "BigInteger": ...
    def flipBit(self, arg0: int) -> "BigInteger": ...
    def getLowestSetBit(self) -> int: ...
    def bitLength(self) -> int: ...
    def bitCount(self) -> int: ...
    def isProbablePrime(self, arg0: int) -> bool: ...
    def compareTo(self, arg0: "BigInteger") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def min(self, arg0: "BigInteger") -> "BigInteger": ...
    def max(self, arg0: "BigInteger") -> "BigInteger": ...
    def hashCode(self) -> int: ...
    @overload
    def toString(self, arg0: int) -> str: ...
    @overload
    def toString(self) -> str: ...
    def toByteArray(self) -> list[int]: ...
    def intValue(self) -> int: ...
    def longValue(self) -> int: ...
    def floatValue(self) -> float: ...
    def doubleValue(self) -> float: ...
    def longValueExact(self) -> int: ...
    def intValueExact(self) -> int: ...
    def shortValueExact(self) -> int: ...
    def byteValueExact(self) -> int: ...
