from typing import Any, ClassVar, overload
from java.math.RoundingMode import RoundingMode

class MathContext:
    DECIMAL128: ClassVar["MathContext"]
    DECIMAL32: ClassVar["MathContext"]
    DECIMAL64: ClassVar["MathContext"]
    UNLIMITED: ClassVar["MathContext"]
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: RoundingMode) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    def getPrecision(self) -> int: ...
    def getRoundingMode(self) -> RoundingMode: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
