from typing import Any, ClassVar, overload
from android.os.OutcomeReceiver import OutcomeReceiver
from android.os.health.HealthStats import HealthStats
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class SystemHealthManager:
    def takeUidSnapshot(self, arg0: int) -> HealthStats: ...
    def takeMyUidSnapshot(self) -> HealthStats: ...
    def takeUidSnapshots(self, arg0: list[int]) -> list[HealthStats]: ...
    def getSupportedPowerMonitors(self, arg0: Executor, arg1: Consumer) -> None: ...
    def getPowerMonitorReadings(self, arg0: list, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
