from typing import Any, ClassVar, overload
from java.lang.Thread import Thread
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.concurrent.locks.Condition import Condition

class ReentrantLock:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: bool) -> None: ...
    def lock(self) -> None: ...
    def lockInterruptibly(self) -> None: ...
    @overload
    def tryLock(self) -> bool: ...
    @overload
    def tryLock(self, arg0: int, arg1: TimeUnit) -> bool: ...
    def unlock(self) -> None: ...
    def newCondition(self) -> Condition: ...
    def getHoldCount(self) -> int: ...
    def isHeldByCurrentThread(self) -> bool: ...
    def isLocked(self) -> bool: ...
    def isFair(self) -> bool: ...
    def getOwner(self) -> Thread: ...
    def hasQueuedThreads(self) -> bool: ...
    def hasQueuedThread(self, arg0: Thread) -> bool: ...
    def getQueueLength(self) -> int: ...
    def getQueuedThreads(self) -> list: ...
    def hasWaiters(self, arg0: Condition) -> bool: ...
    def getWaitQueueLength(self, arg0: Condition) -> int: ...
    def getWaitingThreads(self, arg0: Condition) -> list: ...
    def toString(self) -> str: ...
