from typing import Any, ClassVar, overload
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.concurrent.locks.Lock import Lock
from java.util.concurrent.locks.ReadWriteLock import ReadWriteLock

class StampedLock:
    def __init__(self) -> None: ...
    def writeLock(self) -> int: ...
    @overload
    def tryWriteLock(self) -> int: ...
    @overload
    def tryWriteLock(self, arg0: int, arg1: TimeUnit) -> int: ...
    def writeLockInterruptibly(self) -> int: ...
    def readLock(self) -> int: ...
    @overload
    def tryReadLock(self) -> int: ...
    @overload
    def tryReadLock(self, arg0: int, arg1: TimeUnit) -> int: ...
    def readLockInterruptibly(self) -> int: ...
    def tryOptimisticRead(self) -> int: ...
    def validate(self, arg0: int) -> bool: ...
    def unlockWrite(self, arg0: int) -> None: ...
    def unlockRead(self, arg0: int) -> None: ...
    def unlock(self, arg0: int) -> None: ...
    def tryConvertToWriteLock(self, arg0: int) -> int: ...
    def tryConvertToReadLock(self, arg0: int) -> int: ...
    def tryConvertToOptimisticRead(self, arg0: int) -> int: ...
    def tryUnlockWrite(self) -> bool: ...
    def tryUnlockRead(self) -> bool: ...
    def isWriteLocked(self) -> bool: ...
    def isReadLocked(self) -> bool: ...
    @staticmethod
    def isWriteLockStamp(arg0: int) -> bool: ...
    @staticmethod
    def isReadLockStamp(arg0: int) -> bool: ...
    @staticmethod
    def isLockStamp(arg0: int) -> bool: ...
    @staticmethod
    def isOptimisticReadStamp(arg0: int) -> bool: ...
    def getReadLockCount(self) -> int: ...
    def toString(self) -> str: ...
    def asReadLock(self) -> Lock: ...
    def asWriteLock(self) -> Lock: ...
    def asReadWriteLock(self) -> ReadWriteLock: ...
