from typing import Any, ClassVar, overload
from java.io.File import File
from java.lang.ClassLoader import ClassLoader
from java.net.URL import URL
from javax.xml.transform.Source import Source
from javax.xml.validation.Schema import Schema
from org.w3c.dom.ls.LSResourceResolver import LSResourceResolver
from org.xml.sax.ErrorHandler import ErrorHandler

class SchemaFactory:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def newInstance(arg0: str) -> "SchemaFactory": ...
    @overload
    @staticmethod
    def newInstance(arg0: str, arg1: str, arg2: ClassLoader) -> "SchemaFactory": ...
    def isSchemaLanguageSupported(self, arg0: str) -> bool: ...
    def getFeature(self, arg0: str) -> bool: ...
    def setFeature(self, arg0: str, arg1: bool) -> None: ...
    def setProperty(self, arg0: str, arg1: Any) -> None: ...
    def getProperty(self, arg0: str) -> Any: ...
    def setErrorHandler(self, arg0: ErrorHandler) -> None: ...
    def getErrorHandler(self) -> ErrorHandler: ...
    def setResourceResolver(self, arg0: LSResourceResolver) -> None: ...
    def getResourceResolver(self) -> LSResourceResolver: ...
    @overload
    def newSchema(self, arg0: Source) -> Schema: ...
    @overload
    def newSchema(self, arg0: File) -> Schema: ...
    @overload
    def newSchema(self, arg0: URL) -> Schema: ...
    @overload
    def newSchema(self, arg0: list[Source]) -> Schema: ...
    @overload
    def newSchema(self) -> Schema: ...
