from typing import Any, ClassVar, overload
from org.w3c.dom.TypeInfo import TypeInfo

class TypeInfoProvider:
    def __init__(self) -> None: ...
    def getElementTypeInfo(self) -> TypeInfo: ...
    def getAttributeTypeInfo(self, arg0: int) -> TypeInfo: ...
    def isIdAttribute(self, arg0: int) -> bool: ...
    def isSpecified(self, arg0: int) -> bool: ...
