from typing import Any, ClassVar, overload
from javax.xml.transform.Result import Result
from javax.xml.transform.Source import Source
from org.w3c.dom.ls.LSResourceResolver import LSResourceResolver
from org.xml.sax.ErrorHandler import ErrorHandler

class Validator:
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    @overload
    def validate(self, arg0: Source) -> None: ...
    @overload
    def validate(self, arg0: Source, arg1: Result) -> None: ...
    def setErrorHandler(self, arg0: ErrorHandler) -> None: ...
    def getErrorHandler(self) -> ErrorHandler: ...
    def setResourceResolver(self, arg0: LSResourceResolver) -> None: ...
    def getResourceResolver(self) -> LSResourceResolver: ...
    def getFeature(self, arg0: str) -> bool: ...
    def setFeature(self, arg0: str, arg1: bool) -> None: ...
    def setProperty(self, arg0: str, arg1: Any) -> None: ...
    def getProperty(self, arg0: str) -> Any: ...
