from typing import Any, ClassVar, overload
from android.content.ClipData import ClipData
from android.content.Intent import Intent
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AssistContent:
    CREATOR: ClassVar[Creator]
    def __init__(self) -> None: ...
    def setIntent(self, arg0: Intent) -> None: ...
    def getIntent(self) -> Intent: ...
    def isAppProvidedIntent(self) -> bool: ...
    def setClipData(self, arg0: ClipData) -> None: ...
    def getClipData(self) -> ClipData: ...
    def setStructuredData(self, arg0: str) -> None: ...
    def getStructuredData(self) -> str: ...
    def setWebUri(self, arg0: Uri) -> None: ...
    def getWebUri(self) -> Uri: ...
    def isAppProvidedWebUri(self) -> bool: ...
    def getExtras(self) -> Bundle: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
