from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.res.ColorStateList import ColorStateList
from android.graphics.drawable.Icon import Icon
from android.os.Parcel import Parcel
from android.service.controls.templates.ControlTemplate import ControlTemplate

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Control:
    CREATOR: ClassVar[Creator]
    STATUS_DISABLED: ClassVar[int]
    STATUS_ERROR: ClassVar[int]
    STATUS_NOT_FOUND: ClassVar[int]
    STATUS_OK: ClassVar[int]
    STATUS_UNKNOWN: ClassVar[int]
    def getControlId(self) -> str: ...
    def getDeviceType(self) -> int: ...
    def getTitle(self) -> str: ...
    def getSubtitle(self) -> str: ...
    def getStructure(self) -> str: ...
    def getZone(self) -> str: ...
    def getAppIntent(self) -> PendingIntent: ...
    def getCustomIcon(self) -> Icon: ...
    def getCustomColor(self) -> ColorStateList: ...
    def getStatus(self) -> int: ...
    def getControlTemplate(self) -> ControlTemplate: ...
    def getStatusText(self) -> str: ...
    def isAuthRequired(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class StatefulBuilder:
        @overload
        def __init__(self, arg0: str, arg1: PendingIntent) -> None: ...
        @overload
        def __init__(self, arg0: "Control") -> None: ...
        def setControlId(self, arg0: str) -> "StatefulBuilder": ...
        def setDeviceType(self, arg0: int) -> "StatefulBuilder": ...
        def setTitle(self, arg0: str) -> "StatefulBuilder": ...
        def setSubtitle(self, arg0: str) -> "StatefulBuilder": ...
        def setStructure(self, arg0: str) -> "StatefulBuilder": ...
        def setZone(self, arg0: str) -> "StatefulBuilder": ...
        def setAppIntent(self, arg0: PendingIntent) -> "StatefulBuilder": ...
        def setCustomIcon(self, arg0: Icon) -> "StatefulBuilder": ...
        def setCustomColor(self, arg0: ColorStateList) -> "StatefulBuilder": ...
        def setStatus(self, arg0: int) -> "StatefulBuilder": ...
        def setControlTemplate(self, arg0: ControlTemplate) -> "StatefulBuilder": ...
        def setStatusText(self, arg0: str) -> "StatefulBuilder": ...
        def setAuthRequired(self, arg0: bool) -> "StatefulBuilder": ...
        def build(self) -> "Control": ...

    class StatelessBuilder:
        @overload
        def __init__(self, arg0: str, arg1: PendingIntent) -> None: ...
        @overload
        def __init__(self, arg0: "Control") -> None: ...
        def setControlId(self, arg0: str) -> "StatelessBuilder": ...
        def setDeviceType(self, arg0: int) -> "StatelessBuilder": ...
        def setTitle(self, arg0: str) -> "StatelessBuilder": ...
        def setSubtitle(self, arg0: str) -> "StatelessBuilder": ...
        def setStructure(self, arg0: str) -> "StatelessBuilder": ...
        def setZone(self, arg0: str) -> "StatelessBuilder": ...
        def setAppIntent(self, arg0: PendingIntent) -> "StatelessBuilder": ...
        def setCustomIcon(self, arg0: Icon) -> "StatelessBuilder": ...
        def setCustomColor(self, arg0: ColorStateList) -> "StatelessBuilder": ...
        def build(self) -> "Control": ...
