from typing import Any, ClassVar, overload
from android.graphics.Insets import Insets
from android.view.View import View
from android.view.ViewStructure import ViewStructure
from android.view.autofill.AutofillId import AutofillId
from android.view.contentcapture.ContentCaptureContext import ContentCaptureContext
from android.view.contentcapture.ContentCaptureSessionId import ContentCaptureSessionId

class ContentCaptureSession:
    def getContentCaptureSessionId(self) -> ContentCaptureSessionId: ...
    def createContentCaptureSession(self, arg0: ContentCaptureContext) -> "ContentCaptureSession": ...
    def setContentCaptureContext(self, arg0: ContentCaptureContext) -> None: ...
    def getContentCaptureContext(self) -> ContentCaptureContext: ...
    def destroy(self) -> None: ...
    def close(self) -> None: ...
    def notifyViewAppeared(self, arg0: ViewStructure) -> None: ...
    def notifyViewDisappeared(self, arg0: AutofillId) -> None: ...
    def notifyViewsAppeared(self, arg0: list) -> None: ...
    def notifyViewsDisappeared(self, arg0: AutofillId, arg1: list[int]) -> None: ...
    def notifyViewTextChanged(self, arg0: AutofillId, arg1: str) -> None: ...
    def notifyViewInsetsChanged(self, arg0: Insets) -> None: ...
    def notifySessionResumed(self) -> None: ...
    def notifySessionPaused(self) -> None: ...
    def newViewStructure(self, arg0: View) -> ViewStructure: ...
    def newAutofillId(self, arg0: AutofillId, arg1: int) -> AutofillId: ...
    def newVirtualViewStructure(self, arg0: AutofillId, arg1: int) -> ViewStructure: ...
    def toString(self) -> str: ...
