from typing import Any, ClassVar, overload
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class DataShareWriteAdapter:
    def onWrite(self, arg0: ParcelFileDescriptor) -> None: ...
    def onRejected(self) -> None: ...
    def onError(self, arg0: int) -> None: ...
