from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AvailableNetworkInfo:
    CREATOR: ClassVar[Creator]
    PRIORITY_HIGH: ClassVar[int]
    PRIORITY_LOW: ClassVar[int]
    PRIORITY_MED: ClassVar[int]
    def __init__(self, arg0: int, arg1: int, arg2: list, arg3: list) -> None: ...
    def getSubId(self) -> int: ...
    def getPriority(self) -> int: ...
    def getMccMncs(self) -> list: ...
    def getBands(self) -> list: ...
    def getRadioAccessSpecifiers(self) -> list: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: int) -> None: ...
        def setPriority(self, arg0: int) -> "Builder": ...
        def setMccMncs(self, arg0: list) -> "Builder": ...
        def setRadioAccessSpecifiers(self, arg0: list) -> "Builder": ...
        def build(self) -> "AvailableNetworkInfo": ...
