from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class BarringInfo:
    BARRING_SERVICE_TYPE_CS_FALLBACK: ClassVar[int]
    BARRING_SERVICE_TYPE_CS_SERVICE: ClassVar[int]
    BARRING_SERVICE_TYPE_CS_VOICE: ClassVar[int]
    BARRING_SERVICE_TYPE_EMERGENCY: ClassVar[int]
    BARRING_SERVICE_TYPE_MMTEL_VIDEO: ClassVar[int]
    BARRING_SERVICE_TYPE_MMTEL_VOICE: ClassVar[int]
    BARRING_SERVICE_TYPE_MO_DATA: ClassVar[int]
    BARRING_SERVICE_TYPE_MO_SIGNALLING: ClassVar[int]
    BARRING_SERVICE_TYPE_PS_SERVICE: ClassVar[int]
    BARRING_SERVICE_TYPE_SMS: ClassVar[int]
    CREATOR: ClassVar[Creator]
    def getBarringServiceInfo(self, arg0: int) -> "BarringServiceInfo": ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...

    class BarringServiceInfo:
        BARRING_TYPE_CONDITIONAL: ClassVar[int]
        BARRING_TYPE_NONE: ClassVar[int]
        BARRING_TYPE_UNCONDITIONAL: ClassVar[int]
        BARRING_TYPE_UNKNOWN: ClassVar[int]
        CREATOR: ClassVar[Creator]
        def getBarringType(self) -> int: ...
        def isConditionallyBarred(self) -> bool: ...
        def getConditionalBarringFactor(self) -> int: ...
        def getConditionalBarringTimeSeconds(self) -> int: ...
        def isBarred(self) -> bool: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def toString(self) -> str: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def describeContents(self) -> int: ...
