from typing import Any, ClassVar, overload

class CellSignalStrength:
    SIGNAL_STRENGTH_GOOD: ClassVar[int]
    SIGNAL_STRENGTH_GREAT: ClassVar[int]
    SIGNAL_STRENGTH_MODERATE: ClassVar[int]
    SIGNAL_STRENGTH_NONE_OR_UNKNOWN: ClassVar[int]
    SIGNAL_STRENGTH_POOR: ClassVar[int]
    def getLevel(self) -> int: ...
    def getAsuLevel(self) -> int: ...
    def getDbm(self) -> int: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
