from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.text.Editable import Editable
from android.text.Spannable import Spannable
from android.text.style.TtsSpan import TtsSpan
from java.util.Locale import Locale

class PhoneNumberUtils:
    BCD_EXTENDED_TYPE_CALLED_PARTY: ClassVar[int]
    BCD_EXTENDED_TYPE_EF_ADN: ClassVar[int]
    FORMAT_JAPAN: ClassVar[int]
    FORMAT_NANP: ClassVar[int]
    FORMAT_UNKNOWN: ClassVar[int]
    PAUSE: ClassVar[str]
    TOA_International: ClassVar[int]
    TOA_Unknown: ClassVar[int]
    WAIT: ClassVar[str]
    WILD: ClassVar[str]
    def __init__(self) -> None: ...
    @staticmethod
    def isISODigit(arg0: str) -> bool: ...
    @staticmethod
    def is12Key(arg0: str) -> bool: ...
    @staticmethod
    def isDialable(arg0: str) -> bool: ...
    @staticmethod
    def isReallyDialable(arg0: str) -> bool: ...
    @staticmethod
    def isNonSeparator(arg0: str) -> bool: ...
    @staticmethod
    def isStartsPostDial(arg0: str) -> bool: ...
    @staticmethod
    def getNumberFromIntent(arg0: Intent, arg1: Context) -> str: ...
    @staticmethod
    def extractNetworkPortion(arg0: str) -> str: ...
    @staticmethod
    def stripSeparators(arg0: str) -> str: ...
    @staticmethod
    def extractPostDialPortion(arg0: str) -> str: ...
    @overload
    @staticmethod
    def compare(arg0: str, arg1: str) -> bool: ...
    @overload
    @staticmethod
    def compare(arg0: Context, arg1: str, arg2: str) -> bool: ...
    @staticmethod
    def toCallerIDMinMatch(arg0: str) -> str: ...
    @staticmethod
    def getStrippedReversed(arg0: str) -> str: ...
    @staticmethod
    def stringFromStringAndTOA(arg0: str, arg1: int) -> str: ...
    @staticmethod
    def toaFromString(arg0: str) -> int: ...
    @overload
    @staticmethod
    def calledPartyBCDToString(arg0: list[int], arg1: int, arg2: int) -> str: ...
    @overload
    @staticmethod
    def calledPartyBCDToString(arg0: list[int], arg1: int, arg2: int, arg3: int) -> str: ...
    @overload
    @staticmethod
    def calledPartyBCDFragmentToString(arg0: list[int], arg1: int, arg2: int) -> str: ...
    @overload
    @staticmethod
    def calledPartyBCDFragmentToString(arg0: list[int], arg1: int, arg2: int, arg3: int) -> str: ...
    @staticmethod
    def isWellFormedSmsAddress(arg0: str) -> bool: ...
    @staticmethod
    def isGlobalPhoneNumber(arg0: str) -> bool: ...
    @staticmethod
    def networkPortionToCalledPartyBCD(arg0: str) -> list[int]: ...
    @staticmethod
    def networkPortionToCalledPartyBCDWithLength(arg0: str) -> list[int]: ...
    @overload
    @staticmethod
    def numberToCalledPartyBCD(arg0: str) -> list[int]: ...
    @overload
    @staticmethod
    def numberToCalledPartyBCD(arg0: str, arg1: int) -> list[int]: ...
    @overload
    @staticmethod
    def formatNumber(arg0: str) -> str: ...
    @overload
    @staticmethod
    def formatNumber(arg0: Editable, arg1: int) -> None: ...
    @overload
    @staticmethod
    def formatNumber(arg0: str, arg1: str) -> str: ...
    @overload
    @staticmethod
    def formatNumber(arg0: str, arg1: str, arg2: str) -> str: ...
    @staticmethod
    def getFormatTypeForLocale(arg0: Locale) -> int: ...
    @staticmethod
    def formatNanpNumber(arg0: Editable) -> None: ...
    @staticmethod
    def formatJapaneseNumber(arg0: Editable) -> None: ...
    @staticmethod
    def formatNumberToE164(arg0: str, arg1: str) -> str: ...
    @staticmethod
    def formatNumberToRFC3966(arg0: str, arg1: str) -> str: ...
    @staticmethod
    def normalizeNumber(arg0: str) -> str: ...
    @staticmethod
    def replaceUnicodeDigits(arg0: str) -> str: ...
    @staticmethod
    def isEmergencyNumber(arg0: str) -> bool: ...
    @staticmethod
    def isLocalEmergencyNumber(arg0: Context, arg1: str) -> bool: ...
    @staticmethod
    def isVoiceMailNumber(arg0: str) -> bool: ...
    @staticmethod
    def convertKeypadLettersToDigits(arg0: str) -> str: ...
    @staticmethod
    def createTtsSpannable(arg0: str) -> str: ...
    @staticmethod
    def addTtsSpan(arg0: Spannable, arg1: int, arg2: int) -> None: ...
    @staticmethod
    def createTtsSpan(arg0: str) -> TtsSpan: ...
    @staticmethod
    def areSamePhoneNumber(arg0: str, arg1: str, arg2: str) -> bool: ...
    @staticmethod
    def isWpsCallNumber(arg0: str) -> bool: ...
