from typing import Any, ClassVar, overload
from android.net.LinkProperties import LinkProperties
from android.os.Parcel import Parcel
from android.telephony.data.ApnSetting import ApnSetting

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class PreciseDataConnectionState:
    CREATOR: ClassVar[Creator]
    NETWORK_VALIDATION_FAILURE: ClassVar[int]
    NETWORK_VALIDATION_IN_PROGRESS: ClassVar[int]
    NETWORK_VALIDATION_NOT_REQUESTED: ClassVar[int]
    NETWORK_VALIDATION_SUCCESS: ClassVar[int]
    NETWORK_VALIDATION_UNSUPPORTED: ClassVar[int]
    def getTransportType(self) -> int: ...
    def getId(self) -> int: ...
    def getState(self) -> int: ...
    def getNetworkType(self) -> int: ...
    def getLinkProperties(self) -> LinkProperties: ...
    def getLastCauseCode(self) -> int: ...
    def getApnSetting(self) -> ApnSetting: ...
    def getNetworkValidationStatus(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
