from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SignalStrength:
    CREATOR: ClassVar[Creator]
    INVALID: ClassVar[int]
    def __init__(self, arg0: "SignalStrength") -> None: ...
    @overload
    def getCellSignalStrengths(self) -> list: ...
    @overload
    def getCellSignalStrengths(self, arg0: type) -> list: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getTimestampMillis(self) -> int: ...
    def describeContents(self) -> int: ...
    def getGsmSignalStrength(self) -> int: ...
    def getGsmBitErrorRate(self) -> int: ...
    def getCdmaDbm(self) -> int: ...
    def getCdmaEcio(self) -> int: ...
    def getEvdoDbm(self) -> int: ...
    def getEvdoEcio(self) -> int: ...
    def getEvdoSnr(self) -> int: ...
    def getLevel(self) -> int: ...
    def isGsm(self) -> bool: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
