from typing import Any, ClassVar, overload

class SmsMessage:
    ENCODING_16BIT: ClassVar[int]
    ENCODING_7BIT: ClassVar[int]
    ENCODING_8BIT: ClassVar[int]
    ENCODING_KSC5601: ClassVar[int]
    ENCODING_UNKNOWN: ClassVar[int]
    FORMAT_3GPP: ClassVar[str]
    FORMAT_3GPP2: ClassVar[str]
    MAX_USER_DATA_BYTES: ClassVar[int]
    MAX_USER_DATA_BYTES_WITH_HEADER: ClassVar[int]
    MAX_USER_DATA_SEPTETS: ClassVar[int]
    MAX_USER_DATA_SEPTETS_WITH_HEADER: ClassVar[int]
    @overload
    @staticmethod
    def createFromPdu(arg0: list[int]) -> "SmsMessage": ...
    @overload
    @staticmethod
    def createFromPdu(arg0: list[int], arg1: str) -> "SmsMessage": ...
    @staticmethod
    def getTPLayerLengthForPDU(arg0: str) -> int: ...
    @overload
    @staticmethod
    def calculateLength(arg0: str, arg1: bool) -> list[int]: ...
    @overload
    @staticmethod
    def calculateLength(arg0: str, arg1: bool) -> list[int]: ...
    @overload
    @staticmethod
    def getSubmitPdu(arg0: str, arg1: str, arg2: str, arg3: bool) -> "SubmitPdu": ...
    @overload
    @staticmethod
    def getSubmitPdu(arg0: str, arg1: str, arg2: int, arg3: list[int], arg4: bool) -> "SubmitPdu": ...
    def getServiceCenterAddress(self) -> str: ...
    def getOriginatingAddress(self) -> str: ...
    def getDisplayOriginatingAddress(self) -> str: ...
    def getMessageBody(self) -> str: ...
    def getMessageClass(self) -> "MessageClass": ...
    def getDisplayMessageBody(self) -> str: ...
    def getPseudoSubject(self) -> str: ...
    def getTimestampMillis(self) -> int: ...
    def isEmail(self) -> bool: ...
    def getEmailBody(self) -> str: ...
    def getEmailFrom(self) -> str: ...
    def getProtocolIdentifier(self) -> int: ...
    def isReplace(self) -> bool: ...
    def isCphsMwiMessage(self) -> bool: ...
    def isMWIClearMessage(self) -> bool: ...
    def isMWISetMessage(self) -> bool: ...
    def isMwiDontStore(self) -> bool: ...
    def getUserData(self) -> list[int]: ...
    def getPdu(self) -> list[int]: ...
    def getStatusOnSim(self) -> int: ...
    def getStatusOnIcc(self) -> int: ...
    def getIndexOnSim(self) -> int: ...
    def getIndexOnIcc(self) -> int: ...
    def getStatus(self) -> int: ...
    def isStatusReportMessage(self) -> bool: ...
    def isReplyPathPresent(self) -> bool: ...

    class MessageClass:
        UNKNOWN: ClassVar["MessageClass"]
        CLASS_0: ClassVar["MessageClass"]
        CLASS_1: ClassVar["MessageClass"]
        CLASS_2: ClassVar["MessageClass"]
        CLASS_3: ClassVar["MessageClass"]
        @staticmethod
        def values() -> list["MessageClass"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "MessageClass": ...

    class SubmitPdu:
        encodedMessage: list[int]
        encodedScAddress: list[int]
        def toString(self) -> str: ...
