from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.net.Uri import Uri
from android.os.Handler import Handler
from android.os.OutcomeReceiver import OutcomeReceiver
from android.os.PersistableBundle import PersistableBundle
from android.telecom.PhoneAccountHandle import PhoneAccountHandle
from android.telephony.CellLocation import CellLocation
from android.telephony.IccOpenLogicalChannelResponse import IccOpenLogicalChannelResponse
from android.telephony.NetworkScan import NetworkScan
from android.telephony.NetworkScanRequest import NetworkScanRequest
from android.telephony.PhoneStateListener import PhoneStateListener
from android.telephony.ServiceState import ServiceState
from android.telephony.SignalStrength import SignalStrength
from android.telephony.SignalStrengthUpdateRequest import SignalStrengthUpdateRequest
from android.telephony.TelephonyCallback import TelephonyCallback
from android.telephony.VisualVoicemailSmsFilterSettings import VisualVoicemailSmsFilterSettings
from java.io.IOException import IOException
from java.io.InputStream import InputStream
from java.lang.Throwable import Throwable
from java.nio.file.Path import Path
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class NetworkScanCallback:
    """Forward declaration for ``android.telephony.TelephonyScanManager.NetworkScanCallback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.telephony.TelephonyScanManager.NetworkScanCallback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/telephony/TelephonyScanManager/NetworkScanCallback
    """
    ...

class TelephonyManager:
    ACTION_CARRIER_MESSAGING_CLIENT_SERVICE: ClassVar[str]
    ACTION_CARRIER_SIGNAL_DEFAULT_NETWORK_AVAILABLE: ClassVar[str]
    ACTION_CARRIER_SIGNAL_PCO_VALUE: ClassVar[str]
    ACTION_CARRIER_SIGNAL_REDIRECTED: ClassVar[str]
    ACTION_CARRIER_SIGNAL_REQUEST_NETWORK_FAILED: ClassVar[str]
    ACTION_CARRIER_SIGNAL_RESET: ClassVar[str]
    ACTION_CONFIGURE_VOICEMAIL: ClassVar[str]
    ACTION_MULTI_SIM_CONFIG_CHANGED: ClassVar[str]
    ACTION_NETWORK_COUNTRY_CHANGED: ClassVar[str]
    ACTION_PHONE_STATE_CHANGED: ClassVar[str]
    ACTION_RESET_MOBILE_NETWORK_SETTINGS: ClassVar[str]
    ACTION_RESPOND_VIA_MESSAGE: ClassVar[str]
    ACTION_SECRET_CODE: ClassVar[str]
    ACTION_SHOW_VOICEMAIL_NOTIFICATION: ClassVar[str]
    ACTION_SUBSCRIPTION_CARRIER_IDENTITY_CHANGED: ClassVar[str]
    ACTION_SUBSCRIPTION_SPECIFIC_CARRIER_IDENTITY_CHANGED: ClassVar[str]
    ALLOWED_NETWORK_TYPES_REASON_CARRIER: ClassVar[int]
    ALLOWED_NETWORK_TYPES_REASON_USER: ClassVar[int]
    APPTYPE_CSIM: ClassVar[int]
    APPTYPE_ISIM: ClassVar[int]
    APPTYPE_RUIM: ClassVar[int]
    APPTYPE_SIM: ClassVar[int]
    APPTYPE_UNKNOWN: ClassVar[int]
    APPTYPE_USIM: ClassVar[int]
    AUTHTYPE_EAP_AKA: ClassVar[int]
    AUTHTYPE_EAP_SIM: ClassVar[int]
    AUTHTYPE_GBA_BOOTSTRAP: ClassVar[int]
    AUTHTYPE_GBA_NAF_KEY_EXTERNAL: ClassVar[int]
    CALL_COMPOSER_STATUS_BUSINESS_ONLY: ClassVar[int]
    CALL_COMPOSER_STATUS_OFF: ClassVar[int]
    CALL_COMPOSER_STATUS_ON: ClassVar[int]
    CALL_STATE_IDLE: ClassVar[int]
    CALL_STATE_OFFHOOK: ClassVar[int]
    CALL_STATE_RINGING: ClassVar[int]
    CAPABILITY_SLICING_CONFIG_SUPPORTED: ClassVar[str]
    CARRIER_RESTRICTION_STATUS_NOT_RESTRICTED: ClassVar[int]
    CARRIER_RESTRICTION_STATUS_RESTRICTED: ClassVar[int]
    CARRIER_RESTRICTION_STATUS_RESTRICTED_TO_CALLER: ClassVar[int]
    CARRIER_RESTRICTION_STATUS_UNKNOWN: ClassVar[int]
    CDMA_ROAMING_MODE_AFFILIATED: ClassVar[int]
    CDMA_ROAMING_MODE_ANY: ClassVar[int]
    CDMA_ROAMING_MODE_HOME: ClassVar[int]
    CDMA_ROAMING_MODE_RADIO_DEFAULT: ClassVar[int]
    DATA_ACTIVITY_DORMANT: ClassVar[int]
    DATA_ACTIVITY_IN: ClassVar[int]
    DATA_ACTIVITY_INOUT: ClassVar[int]
    DATA_ACTIVITY_NONE: ClassVar[int]
    DATA_ACTIVITY_OUT: ClassVar[int]
    DATA_CONNECTED: ClassVar[int]
    DATA_CONNECTING: ClassVar[int]
    DATA_DISCONNECTED: ClassVar[int]
    DATA_DISCONNECTING: ClassVar[int]
    DATA_ENABLED_REASON_CARRIER: ClassVar[int]
    DATA_ENABLED_REASON_OVERRIDE: ClassVar[int]
    DATA_ENABLED_REASON_POLICY: ClassVar[int]
    DATA_ENABLED_REASON_THERMAL: ClassVar[int]
    DATA_ENABLED_REASON_UNKNOWN: ClassVar[int]
    DATA_ENABLED_REASON_USER: ClassVar[int]
    DATA_HANDOVER_IN_PROGRESS: ClassVar[int]
    DATA_SUSPENDED: ClassVar[int]
    DATA_UNKNOWN: ClassVar[int]
    DEFAULT_PORT_INDEX: ClassVar[int]
    ERI_FLASH: ClassVar[int]
    ERI_OFF: ClassVar[int]
    ERI_ON: ClassVar[int]
    EVENT_DISPLAY_EMERGENCY_MESSAGE: ClassVar[str]
    EXTRA_ACTIVE_SIM_SUPPORTED_COUNT: ClassVar[str]
    EXTRA_APN_PROTOCOL: ClassVar[str]
    EXTRA_APN_TYPE: ClassVar[str]
    EXTRA_CALL_VOICEMAIL_INTENT: ClassVar[str]
    EXTRA_CARRIER_ID: ClassVar[str]
    EXTRA_CARRIER_NAME: ClassVar[str]
    EXTRA_DATA_FAIL_CAUSE: ClassVar[str]
    EXTRA_DEFAULT_NETWORK_AVAILABLE: ClassVar[str]
    EXTRA_EMERGENCY_CALL_TO_SATELLITE_HANDOVER_TYPE: ClassVar[str]
    EXTRA_EMERGENCY_CALL_TO_SATELLITE_LAUNCH_INTENT: ClassVar[str]
    EXTRA_HIDE_PUBLIC_SETTINGS: ClassVar[str]
    EXTRA_INCOMING_NUMBER: ClassVar[str]
    EXTRA_IS_REFRESH: ClassVar[str]
    EXTRA_LAST_KNOWN_NETWORK_COUNTRY: ClassVar[str]
    EXTRA_LAUNCH_VOICEMAIL_SETTINGS_INTENT: ClassVar[str]
    EXTRA_NETWORK_COUNTRY: ClassVar[str]
    EXTRA_NOTIFICATION_COUNT: ClassVar[str]
    EXTRA_PCO_ID: ClassVar[str]
    EXTRA_PCO_VALUE: ClassVar[str]
    EXTRA_PHONE_ACCOUNT_HANDLE: ClassVar[str]
    EXTRA_REDIRECTION_URL: ClassVar[str]
    EXTRA_SPECIFIC_CARRIER_ID: ClassVar[str]
    EXTRA_SPECIFIC_CARRIER_NAME: ClassVar[str]
    EXTRA_STATE: ClassVar[str]
    EXTRA_STATE_IDLE: ClassVar[str]
    EXTRA_STATE_OFFHOOK: ClassVar[str]
    EXTRA_STATE_RINGING: ClassVar[str]
    EXTRA_SUBSCRIPTION_ID: ClassVar[str]
    EXTRA_VOICEMAIL_NUMBER: ClassVar[str]
    INCLUDE_LOCATION_DATA_COARSE: ClassVar[int]
    INCLUDE_LOCATION_DATA_FINE: ClassVar[int]
    INCLUDE_LOCATION_DATA_NONE: ClassVar[int]
    METADATA_HIDE_VOICEMAIL_SETTINGS_MENU: ClassVar[str]
    MULTISIM_ALLOWED: ClassVar[int]
    MULTISIM_NOT_SUPPORTED_BY_CARRIER: ClassVar[int]
    MULTISIM_NOT_SUPPORTED_BY_HARDWARE: ClassVar[int]
    NETWORK_SELECTION_MODE_AUTO: ClassVar[int]
    NETWORK_SELECTION_MODE_MANUAL: ClassVar[int]
    NETWORK_SELECTION_MODE_UNKNOWN: ClassVar[int]
    NETWORK_TYPE_1xRTT: ClassVar[int]
    NETWORK_TYPE_BITMASK_1xRTT: ClassVar[int]
    NETWORK_TYPE_BITMASK_CDMA: ClassVar[int]
    NETWORK_TYPE_BITMASK_EDGE: ClassVar[int]
    NETWORK_TYPE_BITMASK_EHRPD: ClassVar[int]
    NETWORK_TYPE_BITMASK_EVDO_0: ClassVar[int]
    NETWORK_TYPE_BITMASK_EVDO_A: ClassVar[int]
    NETWORK_TYPE_BITMASK_EVDO_B: ClassVar[int]
    NETWORK_TYPE_BITMASK_GPRS: ClassVar[int]
    NETWORK_TYPE_BITMASK_GSM: ClassVar[int]
    NETWORK_TYPE_BITMASK_HSDPA: ClassVar[int]
    NETWORK_TYPE_BITMASK_HSPA: ClassVar[int]
    NETWORK_TYPE_BITMASK_HSPAP: ClassVar[int]
    NETWORK_TYPE_BITMASK_HSUPA: ClassVar[int]
    NETWORK_TYPE_BITMASK_IWLAN: ClassVar[int]
    NETWORK_TYPE_BITMASK_LTE: ClassVar[int]
    NETWORK_TYPE_BITMASK_LTE_CA: ClassVar[int]
    NETWORK_TYPE_BITMASK_NR: ClassVar[int]
    NETWORK_TYPE_BITMASK_TD_SCDMA: ClassVar[int]
    NETWORK_TYPE_BITMASK_UMTS: ClassVar[int]
    NETWORK_TYPE_BITMASK_UNKNOWN: ClassVar[int]
    NETWORK_TYPE_CDMA: ClassVar[int]
    NETWORK_TYPE_EDGE: ClassVar[int]
    NETWORK_TYPE_EHRPD: ClassVar[int]
    NETWORK_TYPE_EVDO_0: ClassVar[int]
    NETWORK_TYPE_EVDO_A: ClassVar[int]
    NETWORK_TYPE_EVDO_B: ClassVar[int]
    NETWORK_TYPE_GPRS: ClassVar[int]
    NETWORK_TYPE_GSM: ClassVar[int]
    NETWORK_TYPE_HSDPA: ClassVar[int]
    NETWORK_TYPE_HSPA: ClassVar[int]
    NETWORK_TYPE_HSPAP: ClassVar[int]
    NETWORK_TYPE_HSUPA: ClassVar[int]
    NETWORK_TYPE_IDEN: ClassVar[int]
    NETWORK_TYPE_IWLAN: ClassVar[int]
    NETWORK_TYPE_LTE: ClassVar[int]
    NETWORK_TYPE_NR: ClassVar[int]
    NETWORK_TYPE_TD_SCDMA: ClassVar[int]
    NETWORK_TYPE_UMTS: ClassVar[int]
    NETWORK_TYPE_UNKNOWN: ClassVar[int]
    PHONE_TYPE_CDMA: ClassVar[int]
    PHONE_TYPE_GSM: ClassVar[int]
    PHONE_TYPE_NONE: ClassVar[int]
    PHONE_TYPE_SIP: ClassVar[int]
    PREMIUM_CAPABILITY_PRIORITIZE_LATENCY: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_ALREADY_IN_PROGRESS: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_ALREADY_PURCHASED: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_CARRIER_DISABLED: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_CARRIER_ERROR: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_ENTITLEMENT_CHECK_FAILED: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_FEATURE_NOT_SUPPORTED: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_NETWORK_NOT_AVAILABLE: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_NOT_DEFAULT_DATA_SUBSCRIPTION: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_NOT_FOREGROUND: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_PENDING_NETWORK_SETUP: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_REQUEST_FAILED: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_SUCCESS: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_THROTTLED: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_TIMEOUT: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_USER_CANCELED: ClassVar[int]
    PURCHASE_PREMIUM_CAPABILITY_RESULT_USER_DISABLED: ClassVar[int]
    SET_OPPORTUNISTIC_SUB_INACTIVE_SUBSCRIPTION: ClassVar[int]
    SET_OPPORTUNISTIC_SUB_NO_OPPORTUNISTIC_SUB_AVAILABLE: ClassVar[int]
    SET_OPPORTUNISTIC_SUB_REMOTE_SERVICE_EXCEPTION: ClassVar[int]
    SET_OPPORTUNISTIC_SUB_SUCCESS: ClassVar[int]
    SET_OPPORTUNISTIC_SUB_VALIDATION_FAILED: ClassVar[int]
    SIM_STATE_ABSENT: ClassVar[int]
    SIM_STATE_CARD_IO_ERROR: ClassVar[int]
    SIM_STATE_CARD_RESTRICTED: ClassVar[int]
    SIM_STATE_NETWORK_LOCKED: ClassVar[int]
    SIM_STATE_NOT_READY: ClassVar[int]
    SIM_STATE_PERM_DISABLED: ClassVar[int]
    SIM_STATE_PIN_REQUIRED: ClassVar[int]
    SIM_STATE_PUK_REQUIRED: ClassVar[int]
    SIM_STATE_READY: ClassVar[int]
    SIM_STATE_UNKNOWN: ClassVar[int]
    UNINITIALIZED_CARD_ID: ClassVar[int]
    UNKNOWN_CARRIER_ID: ClassVar[int]
    UNSUPPORTED_CARD_ID: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_ABORTED: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_DISABLE_MODEM_FAIL: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_ENABLE_MODEM_FAIL: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_INVALID_ARGUMENTS: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_MULTIPLE_NETWORKS_NOT_SUPPORTED: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_NO_CARRIER_PRIVILEGE: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_NO_OPPORTUNISTIC_SUB_AVAILABLE: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_REMOTE_SERVICE_EXCEPTION: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_SERVICE_IS_DISABLED: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_SUCCESS: ClassVar[int]
    UPDATE_AVAILABLE_NETWORKS_UNKNOWN_FAILURE: ClassVar[int]
    USSD_ERROR_SERVICE_UNAVAIL: ClassVar[int]
    USSD_RETURN_FAILURE: ClassVar[int]
    VVM_TYPE_CVVM: ClassVar[str]
    VVM_TYPE_OMTP: ClassVar[str]
    def getPhoneCount(self) -> int: ...
    def getActiveModemCount(self) -> int: ...
    def getSupportedModemCount(self) -> int: ...
    def createForSubscriptionId(self, arg0: int) -> "TelephonyManager": ...
    def createForPhoneAccountHandle(self, arg0: PhoneAccountHandle) -> "TelephonyManager": ...
    @staticmethod
    def getMaximumCallComposerPictureSize() -> int: ...
    def getDeviceSoftwareVersion(self) -> str: ...
    @overload
    def getDeviceId(self) -> str: ...
    @overload
    def getDeviceId(self, arg0: int) -> str: ...
    @overload
    def getImei(self) -> str: ...
    @overload
    def getImei(self, arg0: int) -> str: ...
    @overload
    def getTypeAllocationCode(self) -> str: ...
    @overload
    def getTypeAllocationCode(self, arg0: int) -> str: ...
    @overload
    def getMeid(self) -> str: ...
    @overload
    def getMeid(self, arg0: int) -> str: ...
    @overload
    def getManufacturerCode(self) -> str: ...
    @overload
    def getManufacturerCode(self, arg0: int) -> str: ...
    def getNai(self) -> str: ...
    def getCellLocation(self) -> CellLocation: ...
    def getPhoneType(self) -> int: ...
    def getNetworkOperatorName(self) -> str: ...
    def getNetworkOperator(self) -> str: ...
    def getNetworkSpecifier(self) -> str: ...
    def getCarrierConfig(self) -> PersistableBundle: ...
    def isNetworkRoaming(self) -> bool: ...
    @overload
    def getNetworkCountryIso(self) -> str: ...
    @overload
    def getNetworkCountryIso(self, arg0: int) -> str: ...
    def getNetworkType(self) -> int: ...
    def getDataNetworkType(self) -> int: ...
    def getVoiceNetworkType(self) -> int: ...
    def hasIccCard(self) -> bool: ...
    @overload
    def getSimState(self) -> int: ...
    @overload
    def getSimState(self, arg0: int) -> int: ...
    def getSimOperator(self) -> str: ...
    def getSimOperatorName(self) -> str: ...
    def getSimCountryIso(self) -> str: ...
    def getSimSerialNumber(self) -> str: ...
    def getCardIdForDefaultEuicc(self) -> int: ...
    def getUiccCardsInfo(self) -> list: ...
    def getSubscriberId(self) -> str: ...
    @overload
    def uploadCallComposerPicture(self, arg0: Path, arg1: str, arg2: Executor, arg3: OutcomeReceiver) -> None: ...
    @overload
    def uploadCallComposerPicture(self, arg0: InputStream, arg1: str, arg2: Executor, arg3: OutcomeReceiver) -> None: ...
    def getGroupIdLevel1(self) -> str: ...
    def getLine1Number(self) -> str: ...
    def setLine1NumberForDisplay(self, arg0: str, arg1: str) -> bool: ...
    def getVoiceMailNumber(self) -> str: ...
    def setVoiceMailNumber(self, arg0: str, arg1: str) -> bool: ...
    def getVisualVoicemailPackageName(self) -> str: ...
    def setVisualVoicemailSmsFilterSettings(self, arg0: VisualVoicemailSmsFilterSettings) -> None: ...
    def sendVisualVoicemailSms(self, arg0: str, arg1: int, arg2: str, arg3: PendingIntent) -> None: ...
    def getVoiceMailAlphaTag(self) -> str: ...
    def sendDialerSpecialCode(self, arg0: str) -> None: ...
    def getCallState(self) -> int: ...
    def getCallStateForSubscription(self) -> int: ...
    def getDataActivity(self) -> int: ...
    def getDataState(self) -> int: ...
    def listen(self, arg0: PhoneStateListener, arg1: int) -> None: ...
    def isVoiceCapable(self) -> bool: ...
    def isDeviceVoiceCapable(self) -> bool: ...
    def isSmsCapable(self) -> bool: ...
    def isDeviceSmsCapable(self) -> bool: ...
    def getAllCellInfo(self) -> list: ...
    def requestCellInfoUpdate(self, arg0: Executor, arg1: "CellInfoCallback") -> None: ...
    def getMmsUserAgent(self) -> str: ...
    def getMmsUAProfUrl(self) -> str: ...
    @overload
    def iccOpenLogicalChannel(self, arg0: str) -> IccOpenLogicalChannelResponse: ...
    @overload
    def iccOpenLogicalChannel(self, arg0: str, arg1: int) -> IccOpenLogicalChannelResponse: ...
    def iccCloseLogicalChannel(self, arg0: int) -> bool: ...
    def iccTransmitApduLogicalChannel(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: str) -> str: ...
    def iccTransmitApduBasicChannel(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: str) -> str: ...
    def iccExchangeSimIO(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: str) -> list[int]: ...
    def sendEnvelopeWithStatus(self, arg0: str) -> str: ...
    def rebootModem(self) -> None: ...
    @overload
    def getSubscriptionId(self) -> int: ...
    @overload
    def getSubscriptionId(self, arg0: PhoneAccountHandle) -> int: ...
    def getIccAuthentication(self, arg0: int, arg1: int, arg2: str) -> str: ...
    def getForbiddenPlmns(self) -> list[str]: ...
    def setForbiddenPlmns(self, arg0: list) -> int: ...
    def setNetworkSelectionModeAutomatic(self) -> None: ...
    @overload
    def requestNetworkScan(self, arg0: NetworkScanRequest, arg1: Executor, arg2: NetworkScanCallback) -> NetworkScan: ...
    @overload
    def requestNetworkScan(self, arg0: int, arg1: NetworkScanRequest, arg2: Executor, arg3: NetworkScanCallback) -> NetworkScan: ...
    @overload
    def setNetworkSelectionModeManual(self, arg0: str, arg1: bool) -> bool: ...
    @overload
    def setNetworkSelectionModeManual(self, arg0: str, arg1: bool, arg2: int) -> bool: ...
    def getNetworkSelectionMode(self) -> int: ...
    def getManualNetworkSelectionPlmn(self) -> str: ...
    def setAllowedNetworkTypesForReason(self, arg0: int, arg1: int) -> None: ...
    def getAllowedNetworkTypesForReason(self, arg0: int) -> int: ...
    def setPreferredNetworkTypeToGlobal(self) -> bool: ...
    def hasCarrierPrivileges(self) -> bool: ...
    def setOperatorBrandOverride(self, arg0: str) -> bool: ...
    def setCallComposerStatus(self, arg0: int) -> None: ...
    def getCallComposerStatus(self) -> int: ...
    def sendUssdRequest(self, arg0: str, arg1: "UssdResponseCallback", arg2: Handler) -> None: ...
    def isConcurrentVoiceAndDataSupported(self) -> bool: ...
    def setDataEnabled(self, arg0: bool) -> None: ...
    def isDataEnabled(self) -> bool: ...
    def isDataRoamingEnabled(self) -> bool: ...
    def canChangeDtmfToneLength(self) -> bool: ...
    def isWorldPhone(self) -> bool: ...
    def isTtyModeSupported(self) -> bool: ...
    def isRttSupported(self) -> bool: ...
    def isHearingAidCompatibilitySupported(self) -> bool: ...
    def getPhoneAccountHandle(self) -> PhoneAccountHandle: ...
    @overload
    def getServiceState(self) -> ServiceState: ...
    @overload
    def getServiceState(self, arg0: int) -> ServiceState: ...
    def getVoicemailRingtoneUri(self, arg0: PhoneAccountHandle) -> Uri: ...
    def setVoicemailRingtoneUri(self, arg0: PhoneAccountHandle, arg1: Uri) -> None: ...
    def isVoicemailVibrationEnabled(self, arg0: PhoneAccountHandle) -> bool: ...
    def setVoicemailVibrationEnabled(self, arg0: PhoneAccountHandle, arg1: bool) -> None: ...
    def getSimCarrierId(self) -> int: ...
    def getSimCarrierIdName(self) -> str: ...
    def getSimSpecificCarrierId(self) -> int: ...
    def getSimSpecificCarrierIdName(self) -> str: ...
    def getCarrierIdFromSimMccMnc(self) -> int: ...
    def getCarrierRestrictionStatus(self, arg0: Executor, arg1: Consumer) -> None: ...
    def setDataEnabledForReason(self, arg0: int, arg1: bool) -> None: ...
    def isDataEnabledForReason(self, arg0: int) -> bool: ...
    def isManualNetworkSelectionAllowed(self) -> bool: ...
    def getSignalStrength(self) -> SignalStrength: ...
    def isDataConnectionAllowed(self) -> bool: ...
    def isDataCapable(self) -> bool: ...
    def getSupportedRadioAccessFamily(self) -> int: ...
    @overload
    def getEmergencyNumberList(self) -> dict: ...
    @overload
    def getEmergencyNumberList(self, arg0: int) -> dict: ...
    def isEmergencyNumber(self, arg0: str) -> bool: ...
    def setPreferredOpportunisticDataSubscription(self, arg0: int, arg1: bool, arg2: Executor, arg3: Consumer) -> None: ...
    def getPreferredOpportunisticDataSubscription(self) -> int: ...
    def updateAvailableNetworks(self, arg0: list, arg1: Executor, arg2: Consumer) -> None: ...
    def isModemEnabledForSlot(self, arg0: int) -> bool: ...
    def isMultiSimSupported(self) -> int: ...
    def switchMultiSimConfig(self, arg0: int) -> None: ...
    def doesSwitchMultiSimConfigTriggerReboot(self) -> bool: ...
    def getEquivalentHomePlmns(self) -> list: ...
    def isRadioInterfaceCapabilitySupported(self, arg0: str) -> bool: ...
    @overload
    def registerTelephonyCallback(self, arg0: Executor, arg1: TelephonyCallback) -> None: ...
    @overload
    def registerTelephonyCallback(self, arg0: int, arg1: Executor, arg2: TelephonyCallback) -> None: ...
    def unregisterTelephonyCallback(self, arg0: TelephonyCallback) -> None: ...
    def setSignalStrengthUpdateRequest(self, arg0: SignalStrengthUpdateRequest) -> None: ...
    def clearSignalStrengthUpdateRequest(self, arg0: SignalStrengthUpdateRequest) -> None: ...
    def getNetworkSlicingConfiguration(self, arg0: Executor, arg1: OutcomeReceiver) -> None: ...
    def isPremiumCapabilityAvailableForPurchase(self, arg0: int) -> bool: ...
    def purchasePremiumCapability(self, arg0: int, arg1: Executor, arg2: Consumer) -> None: ...
    def getPrimaryImei(self) -> str: ...

    class CallComposerException:
        ERROR_AUTHENTICATION_FAILED: ClassVar[int]
        ERROR_FILE_TOO_LARGE: ClassVar[int]
        ERROR_INPUT_CLOSED: ClassVar[int]
        ERROR_IO_EXCEPTION: ClassVar[int]
        ERROR_NETWORK_UNAVAILABLE: ClassVar[int]
        ERROR_REMOTE_END_CLOSED: ClassVar[int]
        ERROR_UNKNOWN: ClassVar[int]
        def __init__(self, arg0: int, arg1: IOException) -> None: ...
        def getErrorCode(self) -> int: ...
        def getIOException(self) -> IOException: ...

    class CellInfoCallback:
        ERROR_MODEM_ERROR: ClassVar[int]
        ERROR_TIMEOUT: ClassVar[int]
        def __init__(self) -> None: ...
        def onCellInfo(self, arg0: list) -> None: ...
        def onError(self, arg0: int, arg1: Throwable) -> None: ...

    class ModemErrorException:
        ...

    class NetworkSlicingException:
        def toString(self) -> str: ...

    class TimeoutException:
        ...

    class UssdResponseCallback:
        def __init__(self) -> None: ...
        def onReceiveUssdResponse(self, arg0: "TelephonyManager", arg1: str, arg2: str) -> None: ...
        def onReceiveUssdResponseFailed(self, arg0: "TelephonyManager", arg1: str, arg2: int) -> None: ...
