from typing import Any, ClassVar, overload
from android.adservices.common.AdTechIdentifier import AdTechIdentifier

class LeaveCustomAudienceRequest:
    def getBuyer(self) -> AdTechIdentifier: ...
    def getName(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setBuyer(self, arg0: AdTechIdentifier) -> "Builder": ...
        def setName(self, arg0: str) -> "Builder": ...
        def build(self) -> "LeaveCustomAudienceRequest": ...
