from typing import Any, ClassVar, overload
from java.security.Permission import Permission

class AccessControlException:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Permission) -> None: ...
    def getPermission(self) -> Permission: ...
