from typing import Any, ClassVar, overload
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class AlgorithmParametersSpi:
    def __init__(self) -> None: ...
    @overload
    def engineInit(self, arg0: AlgorithmParameterSpec) -> None: ...
    @overload
    def engineInit(self, arg0: list[int]) -> None: ...
    @overload
    def engineInit(self, arg0: list[int], arg1: str) -> None: ...
    def engineGetParameterSpec(self, arg0: type) -> AlgorithmParameterSpec: ...
    @overload
    def engineGetEncoded(self) -> list[int]: ...
    @overload
    def engineGetEncoded(self, arg0: str) -> list[int]: ...
    def engineToString(self) -> str: ...
