from typing import Any, ClassVar, overload
from java.security.AlgorithmParameterGeneratorSpi import AlgorithmParameterGeneratorSpi
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class AlgorithmParameterGenerator:
    def __init__(self, arg0: AlgorithmParameterGeneratorSpi, arg1: Provider, arg2: str) -> None: ...
    def getAlgorithm(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "AlgorithmParameterGenerator": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "AlgorithmParameterGenerator": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "AlgorithmParameterGenerator": ...
    def getProvider(self) -> Provider: ...
    @overload
    def init(self, arg0: int) -> None: ...
    @overload
    def init(self, arg0: int, arg1: SecureRandom) -> None: ...
    @overload
    def init(self, arg0: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, arg0: AlgorithmParameterSpec, arg1: SecureRandom) -> None: ...
    def generateParameters(self) -> AlgorithmParameters: ...
