from typing import Any, ClassVar, overload
from java.security.AlgorithmParametersSpi import AlgorithmParametersSpi
from java.security.Provider import Provider
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class AlgorithmParameters:
    def __init__(self, arg0: AlgorithmParametersSpi, arg1: Provider, arg2: str) -> None: ...
    def getAlgorithm(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "AlgorithmParameters": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "AlgorithmParameters": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "AlgorithmParameters": ...
    def getProvider(self) -> Provider: ...
    @overload
    def init(self, arg0: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, arg0: list[int]) -> None: ...
    @overload
    def init(self, arg0: list[int], arg1: str) -> None: ...
    def getParameterSpec(self, arg0: type) -> AlgorithmParameterSpec: ...
    @overload
    def getEncoded(self) -> list[int]: ...
    @overload
    def getEncoded(self, arg0: str) -> list[int]: ...
    def toString(self) -> str: ...
