from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.security.Principal import Principal
from java.security.PublicKey import PublicKey

class Certificate:
    def getGuarantor(self) -> Principal: ...
    def getPrincipal(self) -> Principal: ...
    def getPublicKey(self) -> PublicKey: ...
    def encode(self, arg0: OutputStream) -> None: ...
    def decode(self, arg0: InputStream) -> None: ...
    def getFormat(self) -> str: ...
    def toString(self, arg0: bool) -> str: ...
