from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.security.MessageDigest import MessageDigest

class DigestInputStream:
    digest: MessageDigest
    def __init__(self, arg0: InputStream, arg1: MessageDigest) -> None: ...
    def getMessageDigest(self) -> MessageDigest: ...
    def setMessageDigest(self, arg0: MessageDigest) -> None: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    def on(self, arg0: bool) -> None: ...
    def toString(self) -> str: ...
