from typing import Any, ClassVar, overload
from java.security.Key import Key
from java.security.KeyFactorySpi import KeyFactorySpi
from java.security.PrivateKey import PrivateKey
from java.security.Provider import Provider
from java.security.PublicKey import PublicKey
from java.security.spec.KeySpec import KeySpec

class KeyFactory:
    def __init__(self, arg0: KeyFactorySpi, arg1: Provider, arg2: str) -> None: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "KeyFactory": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "KeyFactory": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "KeyFactory": ...
    def getProvider(self) -> Provider: ...
    def getAlgorithm(self) -> str: ...
    def generatePublic(self, arg0: KeySpec) -> PublicKey: ...
    def generatePrivate(self, arg0: KeySpec) -> PrivateKey: ...
    def getKeySpec(self, arg0: Key, arg1: type) -> KeySpec: ...
    def translateKey(self, arg0: Key) -> Key: ...
