from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.security.Key import Key
from java.security.cert.Certificate import Certificate
from java.util.Date import Date
from java.util.Enumeration import Enumeration

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class LoadStoreParameter:
    """Forward declaration for ``java.security.KeyStore.LoadStoreParameter``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.security.KeyStore.LoadStoreParameter')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore/LoadStoreParameter.html
    """
    ...
class ProtectionParameter:
    """Forward declaration for ``java.security.KeyStore.ProtectionParameter``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.security.KeyStore.ProtectionParameter')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore/ProtectionParameter.html
    """
    ...
class Entry:
    """Forward declaration for ``java.security.KeyStore.Entry``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.security.KeyStore.Entry')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore/Entry.html
    """
    ...

class KeyStoreSpi:
    def __init__(self) -> None: ...
    def engineGetKey(self, arg0: str, arg1: list[str]) -> Key: ...
    def engineGetCertificateChain(self, arg0: str) -> list[Certificate]: ...
    def engineGetCertificate(self, arg0: str) -> Certificate: ...
    def engineGetCreationDate(self, arg0: str) -> Date: ...
    @overload
    def engineSetKeyEntry(self, arg0: str, arg1: Key, arg2: list[str], arg3: list[Certificate]) -> None: ...
    @overload
    def engineSetKeyEntry(self, arg0: str, arg1: list[int], arg2: list[Certificate]) -> None: ...
    def engineSetCertificateEntry(self, arg0: str, arg1: Certificate) -> None: ...
    def engineDeleteEntry(self, arg0: str) -> None: ...
    def engineAliases(self) -> Enumeration: ...
    def engineContainsAlias(self, arg0: str) -> bool: ...
    def engineSize(self) -> int: ...
    def engineIsKeyEntry(self, arg0: str) -> bool: ...
    def engineIsCertificateEntry(self, arg0: str) -> bool: ...
    def engineGetCertificateAlias(self, arg0: Certificate) -> str: ...
    @overload
    def engineStore(self, arg0: OutputStream, arg1: list[str]) -> None: ...
    @overload
    def engineStore(self, arg0: LoadStoreParameter) -> None: ...
    @overload
    def engineLoad(self, arg0: InputStream, arg1: list[str]) -> None: ...
    @overload
    def engineLoad(self, arg0: LoadStoreParameter) -> None: ...
    def engineGetEntry(self, arg0: str, arg1: ProtectionParameter) -> Entry: ...
    def engineSetEntry(self, arg0: str, arg1: Entry, arg2: ProtectionParameter) -> None: ...
    def engineEntryInstanceOf(self, arg0: str, arg1: type) -> bool: ...
    def engineProbe(self, arg0: InputStream) -> bool: ...
