from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.security.Provider import Provider

class MessageDigest:
    def __init__(self, arg0: str) -> None: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "MessageDigest": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "MessageDigest": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "MessageDigest": ...
    def getProvider(self) -> Provider: ...
    @overload
    def update(self, arg0: int) -> None: ...
    @overload
    def update(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    def update(self, arg0: list[int]) -> None: ...
    @overload
    def update(self, arg0: ByteBuffer) -> None: ...
    @overload
    def digest(self) -> list[int]: ...
    @overload
    def digest(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    @overload
    def digest(self, arg0: list[int]) -> list[int]: ...
    def toString(self) -> str: ...
    @staticmethod
    def isEqual(arg0: list[int], arg1: list[int]) -> bool: ...
    def reset(self) -> None: ...
    def getAlgorithm(self) -> str: ...
    def getDigestLength(self) -> int: ...
    def clone(self) -> Any: ...
