from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class MessageDigestSpi:
    def __init__(self) -> None: ...
    def engineGetDigestLength(self) -> int: ...
    @overload
    def engineUpdate(self, arg0: int) -> None: ...
    @overload
    def engineUpdate(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    def engineUpdate(self, arg0: ByteBuffer) -> None: ...
    @overload
    def engineDigest(self) -> list[int]: ...
    @overload
    def engineDigest(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    def engineReset(self) -> None: ...
    def clone(self) -> Any: ...
