from typing import Any, ClassVar, overload
from java.security.PermissionCollection import PermissionCollection

class Permission:
    def __init__(self, arg0: str) -> None: ...
    def checkGuard(self, arg0: Any) -> None: ...
    def implies(self, arg0: "Permission") -> bool: ...
    def getName(self) -> str: ...
    def getActions(self) -> str: ...
    def newPermissionCollection(self) -> PermissionCollection: ...
