from typing import Any, ClassVar, overload
from java.security.CodeSource import CodeSource
from java.security.Permission import Permission
from java.security.PermissionCollection import PermissionCollection
from java.security.ProtectionDomain import ProtectionDomain

class PolicySpi:
    def __init__(self) -> None: ...
    def engineImplies(self, arg0: ProtectionDomain, arg1: Permission) -> bool: ...
    def engineRefresh(self) -> None: ...
    @overload
    def engineGetPermissions(self, arg0: CodeSource) -> PermissionCollection: ...
    @overload
    def engineGetPermissions(self, arg0: ProtectionDomain) -> PermissionCollection: ...
