from typing import Any, ClassVar, overload
from java.lang.Exception import Exception
from java.lang.Throwable import Throwable

class PrivilegedActionException:
    def __init__(self, arg0: Exception) -> None: ...
    def getException(self) -> Exception: ...
    def getCause(self) -> Throwable: ...
    def toString(self) -> str: ...
