from typing import Any, ClassVar, overload
from java.security.Provider import Provider

class Security:
    @staticmethod
    def getAlgorithmProperty(arg0: str, arg1: str) -> str: ...
    @staticmethod
    def insertProviderAt(arg0: Provider, arg1: int) -> int: ...
    @staticmethod
    def addProvider(arg0: Provider) -> int: ...
    @staticmethod
    def removeProvider(arg0: str) -> None: ...
    @overload
    @staticmethod
    def getProviders() -> list[Provider]: ...
    @overload
    @staticmethod
    def getProviders(arg0: str) -> list[Provider]: ...
    @overload
    @staticmethod
    def getProviders(arg0: dict) -> list[Provider]: ...
    @staticmethod
    def getProvider(arg0: str) -> Provider: ...
    @staticmethod
    def getProperty(arg0: str) -> str: ...
    @staticmethod
    def setProperty(arg0: str, arg1: str) -> None: ...
    @staticmethod
    def getAlgorithms(arg0: str) -> set: ...
