from typing import Any, ClassVar, overload
from java.security.Provider import Provider
from java.security.SecureRandomParameters import SecureRandomParameters
from java.security.SecureRandomSpi import SecureRandomSpi

class SecureRandom:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: SecureRandomSpi, arg1: Provider) -> None: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "SecureRandom": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "SecureRandom": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "SecureRandom": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: SecureRandomParameters) -> "SecureRandom": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: SecureRandomParameters, arg2: str) -> "SecureRandom": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: SecureRandomParameters, arg2: Provider) -> "SecureRandom": ...
    def getProvider(self) -> Provider: ...
    def getAlgorithm(self) -> str: ...
    def toString(self) -> str: ...
    def getParameters(self) -> SecureRandomParameters: ...
    @overload
    def setSeed(self, arg0: list[int]) -> None: ...
    @overload
    def setSeed(self, arg0: int) -> None: ...
    @overload
    def nextBytes(self, arg0: list[int]) -> None: ...
    @overload
    def nextBytes(self, arg0: list[int], arg1: SecureRandomParameters) -> None: ...
    def next(self, arg0: int) -> int: ...
    @staticmethod
    def getSeed(arg0: int) -> list[int]: ...
    def generateSeed(self, arg0: int) -> list[int]: ...
    @staticmethod
    def getInstanceStrong() -> "SecureRandom": ...
    @overload
    def reseed(self) -> None: ...
    @overload
    def reseed(self, arg0: SecureRandomParameters) -> None: ...
