from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.PrivateKey import PrivateKey
from java.security.PublicKey import PublicKey
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class SignatureSpi:
    appRandom: SecureRandom
    def __init__(self) -> None: ...
    def engineInitVerify(self, arg0: PublicKey) -> None: ...
    @overload
    def engineInitSign(self, arg0: PrivateKey) -> None: ...
    @overload
    def engineInitSign(self, arg0: PrivateKey, arg1: SecureRandom) -> None: ...
    @overload
    def engineUpdate(self, arg0: int) -> None: ...
    @overload
    def engineUpdate(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    def engineUpdate(self, arg0: ByteBuffer) -> None: ...
    @overload
    def engineSign(self) -> list[int]: ...
    @overload
    def engineSign(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    @overload
    def engineVerify(self, arg0: list[int]) -> bool: ...
    @overload
    def engineVerify(self, arg0: list[int], arg1: int, arg2: int) -> bool: ...
    @overload
    def engineSetParameter(self, arg0: str, arg1: Any) -> None: ...
    @overload
    def engineSetParameter(self, arg0: AlgorithmParameterSpec) -> None: ...
    def engineGetParameters(self) -> AlgorithmParameters: ...
    def engineGetParameter(self, arg0: str) -> Any: ...
    def clone(self) -> Any: ...
