from typing import Any, ClassVar, overload
from java.security.cert.CertPath import CertPath
from java.util.Date import Date

class Timestamp:
    def __init__(self, arg0: Date, arg1: CertPath) -> None: ...
    def getTimestamp(self) -> Date: ...
    def getSignerCertPath(self) -> CertPath: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
