from typing import Any, ClassVar, overload
from android.graphics.text.LineBreakConfig import LineBreakConfig
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Alignment:
    """Forward declaration for ``android.text.Layout.Alignment``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.text.Layout.Alignment')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/text/Layout/Alignment
    """
    ...
class TruncateAt:
    """Forward declaration for ``android.text.TextUtils.TruncateAt``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.text.TextUtils.TruncateAt')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/text/TextUtils/TruncateAt
    """
    ...
class Directions:
    """Forward declaration for ``android.text.Layout.Directions``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.text.Layout.Directions')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/text/Layout/Directions
    """
    ...
class FontMetrics:
    """Forward declaration for ``android.graphics.Paint.FontMetrics``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.Paint.FontMetrics')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/Paint/FontMetrics
    """
    ...

class DynamicLayout:
    @overload
    def __init__(self, arg0: str, arg1: TextPaint, arg2: int, arg3: Alignment, arg4: float, arg5: float, arg6: bool) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: TextPaint, arg3: int, arg4: Alignment, arg5: float, arg6: float, arg7: bool) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: TextPaint, arg3: int, arg4: Alignment, arg5: float, arg6: float, arg7: bool, arg8: TruncateAt, arg9: int) -> None: ...
    def getLineCount(self) -> int: ...
    def getLineTop(self, arg0: int) -> int: ...
    def getLineDescent(self, arg0: int) -> int: ...
    def getLineStart(self, arg0: int) -> int: ...
    def getLineContainsTab(self, arg0: int) -> bool: ...
    def getParagraphDirection(self, arg0: int) -> int: ...
    def getLineDirections(self, arg0: int) -> Directions: ...
    def getTopPadding(self) -> int: ...
    def getBottomPadding(self) -> int: ...
    def getEllipsizedWidth(self) -> int: ...
    def getEllipsisStart(self, arg0: int) -> int: ...
    def getEllipsisCount(self, arg0: int) -> int: ...
    def getLineBreakConfig(self) -> LineBreakConfig: ...

    class Builder:
        @staticmethod
        def obtain(arg0: str, arg1: TextPaint, arg2: int) -> "Builder": ...
        def setDisplayText(self, arg0: str) -> "Builder": ...
        def setAlignment(self, arg0: Alignment) -> "Builder": ...
        def setTextDirection(self, arg0: TextDirectionHeuristic) -> "Builder": ...
        def setLineSpacing(self, arg0: float, arg1: float) -> "Builder": ...
        def setIncludePad(self, arg0: bool) -> "Builder": ...
        def setUseLineSpacingFromFallbacks(self, arg0: bool) -> "Builder": ...
        def setEllipsizedWidth(self, arg0: int) -> "Builder": ...
        def setEllipsize(self, arg0: TruncateAt) -> "Builder": ...
        def setBreakStrategy(self, arg0: int) -> "Builder": ...
        def setHyphenationFrequency(self, arg0: int) -> "Builder": ...
        def setJustificationMode(self, arg0: int) -> "Builder": ...
        def setLineBreakConfig(self, arg0: LineBreakConfig) -> "Builder": ...
        def setUseBoundsForWidth(self, arg0: bool) -> "Builder": ...
        def setShiftDrawingOffsetForStartOverhang(self, arg0: bool) -> "Builder": ...
        def setMinimumFontMetrics(self, arg0: FontMetrics) -> "Builder": ...
        def build(self) -> "DynamicLayout": ...
