from typing import Any, ClassVar, overload
from android.text.Spanned import Spanned
from java.util.Locale import Locale

class InputFilter:
    def filter(self, arg0: str, arg1: int, arg2: int, arg3: Spanned, arg4: int, arg5: int) -> str: ...

    class AllCaps:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: Locale) -> None: ...
        def filter(self, arg0: str, arg1: int, arg2: int, arg3: Spanned, arg4: int, arg5: int) -> str: ...

    class LengthFilter:
        def __init__(self, arg0: int) -> None: ...
        def filter(self, arg0: str, arg1: int, arg2: int, arg3: Spanned, arg4: int, arg5: int) -> str: ...
        def getMax(self) -> int: ...
