from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Paint import Paint
from android.graphics.Path import Path
from android.graphics.Rect import Rect
from android.graphics.RectF import RectF
from android.graphics.text.LineBreakConfig import LineBreakConfig
from android.text.SegmentFinder import SegmentFinder
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class TruncateAt:
    """Forward declaration for ``android.text.TextUtils.TruncateAt``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.text.TextUtils.TruncateAt')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/text/TextUtils/TruncateAt
    """
    ...
class FontMetrics:
    """Forward declaration for ``android.graphics.Paint.FontMetrics``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.Paint.FontMetrics')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/Paint/FontMetrics
    """
    ...

class Layout:
    BREAK_STRATEGY_BALANCED: ClassVar[int]
    BREAK_STRATEGY_HIGH_QUALITY: ClassVar[int]
    BREAK_STRATEGY_SIMPLE: ClassVar[int]
    DEFAULT_LINESPACING_ADDITION: ClassVar[float]
    DEFAULT_LINESPACING_MULTIPLIER: ClassVar[float]
    DIR_LEFT_TO_RIGHT: ClassVar[int]
    DIR_RIGHT_TO_LEFT: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL_FAST: ClassVar[int]
    HYPHENATION_FREQUENCY_NONE: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL_FAST: ClassVar[int]
    INCLUSION_STRATEGY_ANY_OVERLAP: ClassVar["TextInclusionStrategy"]
    INCLUSION_STRATEGY_CONTAINS_ALL: ClassVar["TextInclusionStrategy"]
    INCLUSION_STRATEGY_CONTAINS_CENTER: ClassVar["TextInclusionStrategy"]
    JUSTIFICATION_MODE_INTER_CHARACTER: ClassVar[int]
    JUSTIFICATION_MODE_INTER_WORD: ClassVar[int]
    JUSTIFICATION_MODE_NONE: ClassVar[int]
    def __init__(self, arg0: str, arg1: TextPaint, arg2: int, arg3: "Alignment", arg4: float, arg5: float) -> None: ...
    @overload
    @staticmethod
    def getDesiredWidth(arg0: str, arg1: TextPaint) -> float: ...
    @overload
    @staticmethod
    def getDesiredWidth(arg0: str, arg1: int, arg2: int, arg3: TextPaint) -> float: ...
    @overload
    def draw(self, arg0: Canvas) -> None: ...
    @overload
    def draw(self, arg0: Canvas, arg1: Path, arg2: Paint, arg3: int) -> None: ...
    @overload
    def draw(self, arg0: Canvas, arg1: list, arg2: list, arg3: Path, arg4: Paint, arg5: int) -> None: ...
    def drawText(self, arg0: Canvas) -> None: ...
    def drawBackground(self, arg0: Canvas) -> None: ...
    def increaseWidthTo(self, arg0: int) -> None: ...
    def getHeight(self) -> int: ...
    def getLineCount(self) -> int: ...
    def computeDrawingBoundingBox(self) -> RectF: ...
    def getLineBounds(self, arg0: int, arg1: Rect) -> int: ...
    def getLineTop(self, arg0: int) -> int: ...
    def getLineDescent(self, arg0: int) -> int: ...
    def getLineStart(self, arg0: int) -> int: ...
    def getParagraphDirection(self, arg0: int) -> int: ...
    def getLineContainsTab(self, arg0: int) -> bool: ...
    def getLineDirections(self, arg0: int) -> "Directions": ...
    def getTopPadding(self) -> int: ...
    def getBottomPadding(self) -> int: ...
    def isRtlCharAt(self, arg0: int) -> bool: ...
    def getPrimaryHorizontal(self, arg0: int) -> float: ...
    def getSecondaryHorizontal(self, arg0: int) -> float: ...
    def fillCharacterBounds(self, arg0: int, arg1: int, arg2: list[float], arg3: int) -> None: ...
    def getLineLeft(self, arg0: int) -> float: ...
    def getLineRight(self, arg0: int) -> float: ...
    def getLineMax(self, arg0: int) -> float: ...
    def getLineWidth(self, arg0: int) -> float: ...
    def getLineLetterSpacingUnitCount(self, arg0: int, arg1: bool) -> int: ...
    def getLineForVertical(self, arg0: int) -> int: ...
    def getLineForOffset(self, arg0: int) -> int: ...
    def getOffsetForHorizontal(self, arg0: int, arg1: float) -> int: ...
    def getRangeForRect(self, arg0: RectF, arg1: SegmentFinder, arg2: "TextInclusionStrategy") -> list[int]: ...
    def getLineEnd(self, arg0: int) -> int: ...
    def getLineVisibleEnd(self, arg0: int) -> int: ...
    @overload
    def getLineBottom(self, arg0: int) -> int: ...
    @overload
    def getLineBottom(self, arg0: int, arg1: bool) -> int: ...
    def getLineBaseline(self, arg0: int) -> int: ...
    def getLineAscent(self, arg0: int) -> int: ...
    def getOffsetToLeftOf(self, arg0: int) -> int: ...
    def getOffsetToRightOf(self, arg0: int) -> int: ...
    def getCursorPath(self, arg0: int, arg1: Path, arg2: str) -> None: ...
    def getSelectionPath(self, arg0: int, arg1: int, arg2: Path) -> None: ...
    def getParagraphAlignment(self, arg0: int) -> "Alignment": ...
    def getParagraphLeft(self, arg0: int) -> int: ...
    def getParagraphRight(self, arg0: int) -> int: ...
    def isSpanned(self) -> bool: ...
    def getEllipsisStart(self, arg0: int) -> int: ...
    def getEllipsisCount(self, arg0: int) -> int: ...
    def getText(self) -> str: ...
    def getPaint(self) -> TextPaint: ...
    def getWidth(self) -> int: ...
    def getAlignment(self) -> "Alignment": ...
    def getTextDirectionHeuristic(self) -> TextDirectionHeuristic: ...
    def getSpacingMultiplier(self) -> float: ...
    def getLineSpacingMultiplier(self) -> float: ...
    def getSpacingAdd(self) -> float: ...
    def getLineSpacingAmount(self) -> float: ...
    def isFontPaddingIncluded(self) -> bool: ...
    def isFallbackLineSpacingEnabled(self) -> bool: ...
    def getEllipsizedWidth(self) -> int: ...
    def getEllipsize(self) -> TruncateAt: ...
    def getMaxLines(self) -> int: ...
    def getBreakStrategy(self) -> int: ...
    def getHyphenationFrequency(self) -> int: ...
    def getLeftIndents(self) -> list[int]: ...
    def getRightIndents(self) -> list[int]: ...
    def getJustificationMode(self) -> int: ...
    def getLineBreakConfig(self) -> LineBreakConfig: ...
    def getUseBoundsForWidth(self) -> bool: ...
    def getShiftDrawingOffsetForStartOverhang(self) -> bool: ...
    def getMinimumFontMetrics(self) -> FontMetrics: ...

    class Alignment:
        ALIGN_NORMAL: ClassVar["Alignment"]
        ALIGN_OPPOSITE: ClassVar["Alignment"]
        ALIGN_CENTER: ClassVar["Alignment"]
        @staticmethod
        def values() -> list["Alignment"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Alignment": ...

    class Builder:
        def __init__(self, arg0: str, arg1: int, arg2: int, arg3: TextPaint, arg4: int) -> None: ...
        def setAlignment(self, arg0: "Alignment") -> "Builder": ...
        def setTextDirectionHeuristic(self, arg0: TextDirectionHeuristic) -> "Builder": ...
        def setLineSpacingAmount(self, arg0: float) -> "Builder": ...
        def setLineSpacingMultiplier(self, arg0: float) -> "Builder": ...
        def setFontPaddingIncluded(self, arg0: bool) -> "Builder": ...
        def setFallbackLineSpacingEnabled(self, arg0: bool) -> "Builder": ...
        def setEllipsizedWidth(self, arg0: int) -> "Builder": ...
        def setEllipsize(self, arg0: TruncateAt) -> "Builder": ...
        def setMaxLines(self, arg0: int) -> "Builder": ...
        def setBreakStrategy(self, arg0: int) -> "Builder": ...
        def setHyphenationFrequency(self, arg0: int) -> "Builder": ...
        def setLeftIndents(self, arg0: list[int]) -> "Builder": ...
        def setRightIndents(self, arg0: list[int]) -> "Builder": ...
        def setJustificationMode(self, arg0: int) -> "Builder": ...
        def setLineBreakConfig(self, arg0: LineBreakConfig) -> "Builder": ...
        def setUseBoundsForWidth(self, arg0: bool) -> "Builder": ...
        def setShiftDrawingOffsetForStartOverhang(self, arg0: bool) -> "Builder": ...
        def setMinimumFontMetrics(self, arg0: FontMetrics) -> "Builder": ...
        def build(self) -> "Layout": ...

    class Directions:
        ...

    class TextInclusionStrategy:
        def isSegmentInside(self, arg0: RectF, arg1: RectF) -> bool: ...
