from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.graphics.text.LineBreakConfig import LineBreakConfig
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class FontMetricsInt:
    """Forward declaration for ``android.graphics.Paint.FontMetricsInt``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.Paint.FontMetricsInt')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/Paint/FontMetricsInt
    """
    ...

class PrecomputedText:
    @staticmethod
    def create(arg0: str, arg1: "Params") -> "PrecomputedText": ...
    def getParams(self) -> "Params": ...
    def getParagraphCount(self) -> int: ...
    def getParagraphStart(self, arg0: int) -> int: ...
    def getParagraphEnd(self, arg0: int) -> int: ...
    def getWidth(self, arg0: int, arg1: int) -> float: ...
    def getBounds(self, arg0: int, arg1: int, arg2: Rect) -> None: ...
    def getFontMetricsInt(self, arg0: int, arg1: int, arg2: FontMetricsInt) -> None: ...
    def setSpan(self, arg0: Any, arg1: int, arg2: int, arg3: int) -> None: ...
    def removeSpan(self, arg0: Any) -> None: ...
    def getSpans(self, arg0: int, arg1: int, arg2: type) -> list: ...
    def getSpanStart(self, arg0: Any) -> int: ...
    def getSpanEnd(self, arg0: Any) -> int: ...
    def getSpanFlags(self, arg0: Any) -> int: ...
    def nextSpanTransition(self, arg0: int, arg1: int, arg2: type) -> int: ...
    def length(self) -> int: ...
    def charAt(self, arg0: int) -> str: ...
    def subSequence(self, arg0: int, arg1: int) -> str: ...
    def toString(self) -> str: ...

    class Params:
        def getTextPaint(self) -> TextPaint: ...
        def getTextDirection(self) -> TextDirectionHeuristic: ...
        def getBreakStrategy(self) -> int: ...
        def getHyphenationFrequency(self) -> int: ...
        def getLineBreakConfig(self) -> LineBreakConfig: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

        class Builder:
            @overload
            def __init__(self, arg0: TextPaint) -> None: ...
            @overload
            def __init__(self, arg0: "Params") -> None: ...
            def setBreakStrategy(self, arg0: int) -> "Builder": ...
            def setHyphenationFrequency(self, arg0: int) -> "Builder": ...
            def setTextDirection(self, arg0: TextDirectionHeuristic) -> "Builder": ...
            def setLineBreakConfig(self, arg0: LineBreakConfig) -> "Builder": ...
            def build(self) -> "Params": ...
