from typing import Any, ClassVar, overload
from android.graphics.Paint import Paint
from android.text.InputFilter import InputFilter

class SpannableStringBuilder:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int, arg2: int) -> None: ...
    @staticmethod
    def valueOf(arg0: str) -> "SpannableStringBuilder": ...
    def charAt(self, arg0: int) -> str: ...
    def length(self) -> int: ...
    @overload
    def insert(self, arg0: int, arg1: str, arg2: int, arg3: int) -> "SpannableStringBuilder": ...
    @overload
    def insert(self, arg0: int, arg1: str) -> "SpannableStringBuilder": ...
    def delete(self, arg0: int, arg1: int) -> "SpannableStringBuilder": ...
    def clear(self) -> None: ...
    def clearSpans(self) -> None: ...
    @overload
    def append(self, arg0: str) -> "SpannableStringBuilder": ...
    @overload
    def append(self, arg0: str, arg1: Any, arg2: int) -> "SpannableStringBuilder": ...
    @overload
    def append(self, arg0: str, arg1: int, arg2: int) -> "SpannableStringBuilder": ...
    @overload
    def append(self, arg0: str) -> "SpannableStringBuilder": ...
    @overload
    def replace(self, arg0: int, arg1: int, arg2: str) -> "SpannableStringBuilder": ...
    @overload
    def replace(self, arg0: int, arg1: int, arg2: str, arg3: int, arg4: int) -> "SpannableStringBuilder": ...
    def setSpan(self, arg0: Any, arg1: int, arg2: int, arg3: int) -> None: ...
    def removeSpan(self, arg0: Any) -> None: ...
    def getSpanStart(self, arg0: Any) -> int: ...
    def getSpanEnd(self, arg0: Any) -> int: ...
    def getSpanFlags(self, arg0: Any) -> int: ...
    def getSpans(self, arg0: int, arg1: int, arg2: type) -> list: ...
    def nextSpanTransition(self, arg0: int, arg1: int, arg2: type) -> int: ...
    def subSequence(self, arg0: int, arg1: int) -> str: ...
    def getChars(self, arg0: int, arg1: int, arg2: list[str], arg3: int) -> None: ...
    def toString(self) -> str: ...
    def getTextWatcherDepth(self) -> int: ...
    def getTextRunCursor(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: Paint) -> int: ...
    def setFilters(self, arg0: list[InputFilter]) -> None: ...
    def getFilters(self) -> list[InputFilter]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
