from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable

class SpanWatcher:
    def onSpanAdded(self, arg0: Spannable, arg1: Any, arg2: int, arg3: int) -> None: ...
    def onSpanRemoved(self, arg0: Spannable, arg1: Any, arg2: int, arg3: int) -> None: ...
    def onSpanChanged(self, arg0: Spannable, arg1: Any, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
