from typing import Any, ClassVar, overload

class SpannableString:
    def __init__(self, arg0: str) -> None: ...
    @staticmethod
    def valueOf(arg0: str) -> "SpannableString": ...
    def setSpan(self, arg0: Any, arg1: int, arg2: int, arg3: int) -> None: ...
    def removeSpan(self, arg0: Any) -> None: ...
    def subSequence(self, arg0: int, arg1: int) -> str: ...
    def getChars(self, arg0: int, arg1: int, arg2: list[str], arg3: int) -> None: ...
    def length(self) -> int: ...
    def getSpanStart(self, arg0: Any) -> int: ...
    def getSpanFlags(self, arg0: Any) -> int: ...
    def nextSpanTransition(self, arg0: int, arg1: int, arg2: type) -> int: ...
    def getSpans(self, arg0: int, arg1: int, arg2: type) -> list: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def getSpanEnd(self, arg0: Any) -> int: ...
    def toString(self) -> str: ...
    def charAt(self, arg0: int) -> str: ...
