from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Parcel import Parcel
from android.text.Spannable import Spannable
from android.text.Spanned import Spanned
from android.text.TextPaint import TextPaint
from android.util.Printer import Printer
from java.lang.Iterable import Iterable
from java.util.Iterator import Iterator
from java.util.Locale import Locale
from java.util.regex.Pattern import Pattern

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class TextUtils:
    CAP_MODE_CHARACTERS: ClassVar[int]
    CAP_MODE_SENTENCES: ClassVar[int]
    CAP_MODE_WORDS: ClassVar[int]
    CHAR_SEQUENCE_CREATOR: ClassVar[Creator]
    SAFE_STRING_FLAG_FIRST_LINE: ClassVar[int]
    SAFE_STRING_FLAG_SINGLE_LINE: ClassVar[int]
    SAFE_STRING_FLAG_TRIM: ClassVar[int]
    @staticmethod
    def getChars(arg0: str, arg1: int, arg2: int, arg3: list[str], arg4: int) -> None: ...
    @overload
    @staticmethod
    def indexOf(arg0: str, arg1: str) -> int: ...
    @overload
    @staticmethod
    def indexOf(arg0: str, arg1: str, arg2: int) -> int: ...
    @overload
    @staticmethod
    def indexOf(arg0: str, arg1: str, arg2: int, arg3: int) -> int: ...
    @overload
    @staticmethod
    def indexOf(arg0: str, arg1: str) -> int: ...
    @overload
    @staticmethod
    def indexOf(arg0: str, arg1: str, arg2: int) -> int: ...
    @overload
    @staticmethod
    def indexOf(arg0: str, arg1: str, arg2: int, arg3: int) -> int: ...
    @overload
    @staticmethod
    def lastIndexOf(arg0: str, arg1: str) -> int: ...
    @overload
    @staticmethod
    def lastIndexOf(arg0: str, arg1: str, arg2: int) -> int: ...
    @overload
    @staticmethod
    def lastIndexOf(arg0: str, arg1: str, arg2: int, arg3: int) -> int: ...
    @staticmethod
    def regionMatches(arg0: str, arg1: int, arg2: str, arg3: int, arg4: int) -> bool: ...
    @staticmethod
    def substring(arg0: str, arg1: int, arg2: int) -> str: ...
    @overload
    @staticmethod
    def join(arg0: str, arg1: list) -> str: ...
    @overload
    @staticmethod
    def join(arg0: str, arg1: Iterable) -> str: ...
    @overload
    @staticmethod
    def split(arg0: str, arg1: str) -> list[str]: ...
    @overload
    @staticmethod
    def split(arg0: str, arg1: Pattern) -> list[str]: ...
    @staticmethod
    def stringOrSpannedString(arg0: str) -> str: ...
    @staticmethod
    def isEmpty(arg0: str) -> bool: ...
    @staticmethod
    def getTrimmedLength(arg0: str) -> int: ...
    @staticmethod
    def equals(arg0: str, arg1: str) -> bool: ...
    @staticmethod
    def getReverse(arg0: str, arg1: int, arg2: int) -> str: ...
    @staticmethod
    def writeToParcel(arg0: str, arg1: Parcel, arg2: int) -> None: ...
    @staticmethod
    def dumpSpans(arg0: str, arg1: Printer, arg2: str) -> None: ...
    @staticmethod
    def replace(arg0: str, arg1: list[str], arg2: list[str]) -> str: ...
    @staticmethod
    def expandTemplate(arg0: str, *arg1: str) -> str: ...
    @staticmethod
    def getOffsetBefore(arg0: str, arg1: int) -> int: ...
    @staticmethod
    def getOffsetAfter(arg0: str, arg1: int) -> int: ...
    @staticmethod
    def copySpansFrom(arg0: Spanned, arg1: int, arg2: int, arg3: type, arg4: Spannable, arg5: int) -> None: ...
    @overload
    @staticmethod
    def ellipsize(arg0: str, arg1: TextPaint, arg2: float, arg3: "TruncateAt") -> str: ...
    @overload
    @staticmethod
    def ellipsize(arg0: str, arg1: TextPaint, arg2: float, arg3: "TruncateAt", arg4: bool, arg5: "EllipsizeCallback") -> str: ...
    @staticmethod
    def listEllipsize(arg0: Context, arg1: list, arg2: str, arg3: TextPaint, arg4: float, arg5: int) -> str: ...
    @staticmethod
    def commaEllipsize(arg0: str, arg1: TextPaint, arg2: float, arg3: str, arg4: str) -> str: ...
    @staticmethod
    def htmlEncode(arg0: str) -> str: ...
    @staticmethod
    def concat(*arg0: str) -> str: ...
    @overload
    @staticmethod
    def isGraphic(arg0: str) -> bool: ...
    @overload
    @staticmethod
    def isGraphic(arg0: str) -> bool: ...
    @staticmethod
    def isDigitsOnly(arg0: str) -> bool: ...
    @staticmethod
    def getCapsMode(arg0: str, arg1: int, arg2: int) -> int: ...
    @staticmethod
    def getLayoutDirectionFromLocale(arg0: Locale) -> int: ...
    @staticmethod
    def makeSafeForPresentation(arg0: str, arg1: int, arg2: float, arg3: int) -> str: ...

    class EllipsizeCallback:
        def ellipsized(self, arg0: int, arg1: int) -> None: ...

    class SimpleStringSplitter:
        def __init__(self, arg0: str) -> None: ...
        def setString(self, arg0: str) -> None: ...
        def iterator(self) -> Iterator: ...
        def hasNext(self) -> bool: ...
        def next(self) -> str: ...
        def remove(self) -> None: ...

    class StringSplitter:
        def setString(self, arg0: str) -> None: ...

    class TruncateAt:
        START: ClassVar["TruncateAt"]
        MIDDLE: ClassVar["TruncateAt"]
        END: ClassVar["TruncateAt"]
        MARQUEE: ClassVar["TruncateAt"]
        @staticmethod
        def values() -> list["TruncateAt"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "TruncateAt": ...
