from typing import Any, ClassVar, overload

class CharacterData:
    def getData(self) -> str: ...
    def setData(self, arg0: str) -> None: ...
    def getLength(self) -> int: ...
    def substringData(self, arg0: int, arg1: int) -> str: ...
    def appendData(self, arg0: str) -> None: ...
    def insertData(self, arg0: int, arg1: str) -> None: ...
    def deleteData(self, arg0: int, arg1: int) -> None: ...
    def replaceData(self, arg0: int, arg1: int, arg2: str) -> None: ...
