from typing import Any, ClassVar, overload
from org.w3c.dom.DOMStringList import DOMStringList

class DOMConfiguration:
    def setParameter(self, arg0: str, arg1: Any) -> None: ...
    def getParameter(self, arg0: str) -> Any: ...
    def canSetParameter(self, arg0: str, arg1: Any) -> bool: ...
    def getParameterNames(self) -> DOMStringList: ...
