from typing import Any, ClassVar, overload
from org.w3c.dom.DOMLocator import DOMLocator

class DOMError:
    SEVERITY_ERROR: ClassVar[int]
    SEVERITY_FATAL_ERROR: ClassVar[int]
    SEVERITY_WARNING: ClassVar[int]
    def getSeverity(self) -> int: ...
    def getMessage(self) -> str: ...
    def getType(self) -> str: ...
    def getRelatedException(self) -> Any: ...
    def getRelatedData(self) -> Any: ...
    def getLocation(self) -> DOMLocator: ...
