from typing import Any, ClassVar, overload
from org.w3c.dom.Document import Document
from org.w3c.dom.DocumentType import DocumentType

class DOMImplementation:
    def hasFeature(self, arg0: str, arg1: str) -> bool: ...
    def createDocumentType(self, arg0: str, arg1: str, arg2: str) -> DocumentType: ...
    def createDocument(self, arg0: str, arg1: str, arg2: DocumentType) -> Document: ...
    def getFeature(self, arg0: str, arg1: str) -> Any: ...
