from typing import Any, ClassVar, overload
from org.w3c.dom.Node import Node

class DOMLocator:
    def getLineNumber(self) -> int: ...
    def getColumnNumber(self) -> int: ...
    def getByteOffset(self) -> int: ...
    def getUtf16Offset(self) -> int: ...
    def getRelatedNode(self) -> Node: ...
    def getUri(self) -> str: ...
