from typing import Any, ClassVar, overload

class Entity:
    def getPublicId(self) -> str: ...
    def getSystemId(self) -> str: ...
    def getNotationName(self) -> str: ...
    def getInputEncoding(self) -> str: ...
    def getXmlEncoding(self) -> str: ...
    def getXmlVersion(self) -> str: ...
