from typing import Any, ClassVar, overload

class NameList:
    def getName(self, arg0: int) -> str: ...
    def getNamespaceURI(self, arg0: int) -> str: ...
    def getLength(self) -> int: ...
    def contains(self, arg0: str) -> bool: ...
    def containsNS(self, arg0: str, arg1: str) -> bool: ...
