from typing import Any, ClassVar, overload
from org.w3c.dom.Node import Node

class NamedNodeMap:
    def getNamedItem(self, arg0: str) -> Node: ...
    def setNamedItem(self, arg0: Node) -> Node: ...
    def removeNamedItem(self, arg0: str) -> Node: ...
    def item(self, arg0: int) -> Node: ...
    def getLength(self) -> int: ...
    def getNamedItemNS(self, arg0: str, arg1: str) -> Node: ...
    def setNamedItemNS(self, arg0: Node) -> Node: ...
    def removeNamedItemNS(self, arg0: str, arg1: str) -> Node: ...
