from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.FloatBuffer import FloatBuffer
from java.nio.IntBuffer import IntBuffer

class GL10:
    GL_ADD: ClassVar[int]
    GL_ALIASED_LINE_WIDTH_RANGE: ClassVar[int]
    GL_ALIASED_POINT_SIZE_RANGE: ClassVar[int]
    GL_ALPHA: ClassVar[int]
    GL_ALPHA_BITS: ClassVar[int]
    GL_ALPHA_TEST: ClassVar[int]
    GL_ALWAYS: ClassVar[int]
    GL_AMBIENT: ClassVar[int]
    GL_AMBIENT_AND_DIFFUSE: ClassVar[int]
    GL_AND: ClassVar[int]
    GL_AND_INVERTED: ClassVar[int]
    GL_AND_REVERSE: ClassVar[int]
    GL_BACK: ClassVar[int]
    GL_BLEND: ClassVar[int]
    GL_BLUE_BITS: ClassVar[int]
    GL_BYTE: ClassVar[int]
    GL_CCW: ClassVar[int]
    GL_CLAMP_TO_EDGE: ClassVar[int]
    GL_CLEAR: ClassVar[int]
    GL_COLOR_ARRAY: ClassVar[int]
    GL_COLOR_BUFFER_BIT: ClassVar[int]
    GL_COLOR_LOGIC_OP: ClassVar[int]
    GL_COLOR_MATERIAL: ClassVar[int]
    GL_COMPRESSED_TEXTURE_FORMATS: ClassVar[int]
    GL_CONSTANT_ATTENUATION: ClassVar[int]
    GL_COPY: ClassVar[int]
    GL_COPY_INVERTED: ClassVar[int]
    GL_CULL_FACE: ClassVar[int]
    GL_CW: ClassVar[int]
    GL_DECAL: ClassVar[int]
    GL_DECR: ClassVar[int]
    GL_DEPTH_BITS: ClassVar[int]
    GL_DEPTH_BUFFER_BIT: ClassVar[int]
    GL_DEPTH_TEST: ClassVar[int]
    GL_DIFFUSE: ClassVar[int]
    GL_DITHER: ClassVar[int]
    GL_DONT_CARE: ClassVar[int]
    GL_DST_ALPHA: ClassVar[int]
    GL_DST_COLOR: ClassVar[int]
    GL_EMISSION: ClassVar[int]
    GL_EQUAL: ClassVar[int]
    GL_EQUIV: ClassVar[int]
    GL_EXP: ClassVar[int]
    GL_EXP2: ClassVar[int]
    GL_EXTENSIONS: ClassVar[int]
    GL_FALSE: ClassVar[int]
    GL_FASTEST: ClassVar[int]
    GL_FIXED: ClassVar[int]
    GL_FLAT: ClassVar[int]
    GL_FLOAT: ClassVar[int]
    GL_FOG: ClassVar[int]
    GL_FOG_COLOR: ClassVar[int]
    GL_FOG_DENSITY: ClassVar[int]
    GL_FOG_END: ClassVar[int]
    GL_FOG_HINT: ClassVar[int]
    GL_FOG_MODE: ClassVar[int]
    GL_FOG_START: ClassVar[int]
    GL_FRONT: ClassVar[int]
    GL_FRONT_AND_BACK: ClassVar[int]
    GL_GEQUAL: ClassVar[int]
    GL_GREATER: ClassVar[int]
    GL_GREEN_BITS: ClassVar[int]
    GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES: ClassVar[int]
    GL_IMPLEMENTATION_COLOR_READ_TYPE_OES: ClassVar[int]
    GL_INCR: ClassVar[int]
    GL_INVALID_ENUM: ClassVar[int]
    GL_INVALID_OPERATION: ClassVar[int]
    GL_INVALID_VALUE: ClassVar[int]
    GL_INVERT: ClassVar[int]
    GL_KEEP: ClassVar[int]
    GL_LEQUAL: ClassVar[int]
    GL_LESS: ClassVar[int]
    GL_LIGHT0: ClassVar[int]
    GL_LIGHT1: ClassVar[int]
    GL_LIGHT2: ClassVar[int]
    GL_LIGHT3: ClassVar[int]
    GL_LIGHT4: ClassVar[int]
    GL_LIGHT5: ClassVar[int]
    GL_LIGHT6: ClassVar[int]
    GL_LIGHT7: ClassVar[int]
    GL_LIGHTING: ClassVar[int]
    GL_LIGHT_MODEL_AMBIENT: ClassVar[int]
    GL_LIGHT_MODEL_TWO_SIDE: ClassVar[int]
    GL_LINEAR: ClassVar[int]
    GL_LINEAR_ATTENUATION: ClassVar[int]
    GL_LINEAR_MIPMAP_LINEAR: ClassVar[int]
    GL_LINEAR_MIPMAP_NEAREST: ClassVar[int]
    GL_LINES: ClassVar[int]
    GL_LINE_LOOP: ClassVar[int]
    GL_LINE_SMOOTH: ClassVar[int]
    GL_LINE_SMOOTH_HINT: ClassVar[int]
    GL_LINE_STRIP: ClassVar[int]
    GL_LUMINANCE: ClassVar[int]
    GL_LUMINANCE_ALPHA: ClassVar[int]
    GL_MAX_ELEMENTS_INDICES: ClassVar[int]
    GL_MAX_ELEMENTS_VERTICES: ClassVar[int]
    GL_MAX_LIGHTS: ClassVar[int]
    GL_MAX_MODELVIEW_STACK_DEPTH: ClassVar[int]
    GL_MAX_PROJECTION_STACK_DEPTH: ClassVar[int]
    GL_MAX_TEXTURE_SIZE: ClassVar[int]
    GL_MAX_TEXTURE_STACK_DEPTH: ClassVar[int]
    GL_MAX_TEXTURE_UNITS: ClassVar[int]
    GL_MAX_VIEWPORT_DIMS: ClassVar[int]
    GL_MODELVIEW: ClassVar[int]
    GL_MODULATE: ClassVar[int]
    GL_MULTISAMPLE: ClassVar[int]
    GL_NAND: ClassVar[int]
    GL_NEAREST: ClassVar[int]
    GL_NEAREST_MIPMAP_LINEAR: ClassVar[int]
    GL_NEAREST_MIPMAP_NEAREST: ClassVar[int]
    GL_NEVER: ClassVar[int]
    GL_NICEST: ClassVar[int]
    GL_NOOP: ClassVar[int]
    GL_NOR: ClassVar[int]
    GL_NORMALIZE: ClassVar[int]
    GL_NORMAL_ARRAY: ClassVar[int]
    GL_NOTEQUAL: ClassVar[int]
    GL_NO_ERROR: ClassVar[int]
    GL_NUM_COMPRESSED_TEXTURE_FORMATS: ClassVar[int]
    GL_ONE: ClassVar[int]
    GL_ONE_MINUS_DST_ALPHA: ClassVar[int]
    GL_ONE_MINUS_DST_COLOR: ClassVar[int]
    GL_ONE_MINUS_SRC_ALPHA: ClassVar[int]
    GL_ONE_MINUS_SRC_COLOR: ClassVar[int]
    GL_OR: ClassVar[int]
    GL_OR_INVERTED: ClassVar[int]
    GL_OR_REVERSE: ClassVar[int]
    GL_OUT_OF_MEMORY: ClassVar[int]
    GL_PACK_ALIGNMENT: ClassVar[int]
    GL_PALETTE4_R5_G6_B5_OES: ClassVar[int]
    GL_PALETTE4_RGB5_A1_OES: ClassVar[int]
    GL_PALETTE4_RGB8_OES: ClassVar[int]
    GL_PALETTE4_RGBA4_OES: ClassVar[int]
    GL_PALETTE4_RGBA8_OES: ClassVar[int]
    GL_PALETTE8_R5_G6_B5_OES: ClassVar[int]
    GL_PALETTE8_RGB5_A1_OES: ClassVar[int]
    GL_PALETTE8_RGB8_OES: ClassVar[int]
    GL_PALETTE8_RGBA4_OES: ClassVar[int]
    GL_PALETTE8_RGBA8_OES: ClassVar[int]
    GL_PERSPECTIVE_CORRECTION_HINT: ClassVar[int]
    GL_POINTS: ClassVar[int]
    GL_POINT_FADE_THRESHOLD_SIZE: ClassVar[int]
    GL_POINT_SIZE: ClassVar[int]
    GL_POINT_SMOOTH: ClassVar[int]
    GL_POINT_SMOOTH_HINT: ClassVar[int]
    GL_POLYGON_OFFSET_FILL: ClassVar[int]
    GL_POLYGON_SMOOTH_HINT: ClassVar[int]
    GL_POSITION: ClassVar[int]
    GL_PROJECTION: ClassVar[int]
    GL_QUADRATIC_ATTENUATION: ClassVar[int]
    GL_RED_BITS: ClassVar[int]
    GL_RENDERER: ClassVar[int]
    GL_REPEAT: ClassVar[int]
    GL_REPLACE: ClassVar[int]
    GL_RESCALE_NORMAL: ClassVar[int]
    GL_RGB: ClassVar[int]
    GL_RGBA: ClassVar[int]
    GL_SAMPLE_ALPHA_TO_COVERAGE: ClassVar[int]
    GL_SAMPLE_ALPHA_TO_ONE: ClassVar[int]
    GL_SAMPLE_COVERAGE: ClassVar[int]
    GL_SCISSOR_TEST: ClassVar[int]
    GL_SET: ClassVar[int]
    GL_SHININESS: ClassVar[int]
    GL_SHORT: ClassVar[int]
    GL_SMOOTH: ClassVar[int]
    GL_SMOOTH_LINE_WIDTH_RANGE: ClassVar[int]
    GL_SMOOTH_POINT_SIZE_RANGE: ClassVar[int]
    GL_SPECULAR: ClassVar[int]
    GL_SPOT_CUTOFF: ClassVar[int]
    GL_SPOT_DIRECTION: ClassVar[int]
    GL_SPOT_EXPONENT: ClassVar[int]
    GL_SRC_ALPHA: ClassVar[int]
    GL_SRC_ALPHA_SATURATE: ClassVar[int]
    GL_SRC_COLOR: ClassVar[int]
    GL_STACK_OVERFLOW: ClassVar[int]
    GL_STACK_UNDERFLOW: ClassVar[int]
    GL_STENCIL_BITS: ClassVar[int]
    GL_STENCIL_BUFFER_BIT: ClassVar[int]
    GL_STENCIL_TEST: ClassVar[int]
    GL_SUBPIXEL_BITS: ClassVar[int]
    GL_TEXTURE: ClassVar[int]
    GL_TEXTURE0: ClassVar[int]
    GL_TEXTURE1: ClassVar[int]
    GL_TEXTURE10: ClassVar[int]
    GL_TEXTURE11: ClassVar[int]
    GL_TEXTURE12: ClassVar[int]
    GL_TEXTURE13: ClassVar[int]
    GL_TEXTURE14: ClassVar[int]
    GL_TEXTURE15: ClassVar[int]
    GL_TEXTURE16: ClassVar[int]
    GL_TEXTURE17: ClassVar[int]
    GL_TEXTURE18: ClassVar[int]
    GL_TEXTURE19: ClassVar[int]
    GL_TEXTURE2: ClassVar[int]
    GL_TEXTURE20: ClassVar[int]
    GL_TEXTURE21: ClassVar[int]
    GL_TEXTURE22: ClassVar[int]
    GL_TEXTURE23: ClassVar[int]
    GL_TEXTURE24: ClassVar[int]
    GL_TEXTURE25: ClassVar[int]
    GL_TEXTURE26: ClassVar[int]
    GL_TEXTURE27: ClassVar[int]
    GL_TEXTURE28: ClassVar[int]
    GL_TEXTURE29: ClassVar[int]
    GL_TEXTURE3: ClassVar[int]
    GL_TEXTURE30: ClassVar[int]
    GL_TEXTURE31: ClassVar[int]
    GL_TEXTURE4: ClassVar[int]
    GL_TEXTURE5: ClassVar[int]
    GL_TEXTURE6: ClassVar[int]
    GL_TEXTURE7: ClassVar[int]
    GL_TEXTURE8: ClassVar[int]
    GL_TEXTURE9: ClassVar[int]
    GL_TEXTURE_2D: ClassVar[int]
    GL_TEXTURE_COORD_ARRAY: ClassVar[int]
    GL_TEXTURE_ENV: ClassVar[int]
    GL_TEXTURE_ENV_COLOR: ClassVar[int]
    GL_TEXTURE_ENV_MODE: ClassVar[int]
    GL_TEXTURE_MAG_FILTER: ClassVar[int]
    GL_TEXTURE_MIN_FILTER: ClassVar[int]
    GL_TEXTURE_WRAP_S: ClassVar[int]
    GL_TEXTURE_WRAP_T: ClassVar[int]
    GL_TRIANGLES: ClassVar[int]
    GL_TRIANGLE_FAN: ClassVar[int]
    GL_TRIANGLE_STRIP: ClassVar[int]
    GL_TRUE: ClassVar[int]
    GL_UNPACK_ALIGNMENT: ClassVar[int]
    GL_UNSIGNED_BYTE: ClassVar[int]
    GL_UNSIGNED_SHORT: ClassVar[int]
    GL_UNSIGNED_SHORT_4_4_4_4: ClassVar[int]
    GL_UNSIGNED_SHORT_5_5_5_1: ClassVar[int]
    GL_UNSIGNED_SHORT_5_6_5: ClassVar[int]
    GL_VENDOR: ClassVar[int]
    GL_VERSION: ClassVar[int]
    GL_VERTEX_ARRAY: ClassVar[int]
    GL_XOR: ClassVar[int]
    GL_ZERO: ClassVar[int]
    def glActiveTexture(self, arg0: int) -> None: ...
    def glAlphaFunc(self, arg0: int, arg1: float) -> None: ...
    def glAlphaFuncx(self, arg0: int, arg1: int) -> None: ...
    def glBindTexture(self, arg0: int, arg1: int) -> None: ...
    def glBlendFunc(self, arg0: int, arg1: int) -> None: ...
    def glClear(self, arg0: int) -> None: ...
    def glClearColor(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def glClearColorx(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def glClearDepthf(self, arg0: float) -> None: ...
    def glClearDepthx(self, arg0: int) -> None: ...
    def glClearStencil(self, arg0: int) -> None: ...
    def glClientActiveTexture(self, arg0: int) -> None: ...
    def glColor4f(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def glColor4x(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def glColorMask(self, arg0: bool, arg1: bool, arg2: bool, arg3: bool) -> None: ...
    def glColorPointer(self, arg0: int, arg1: int, arg2: int, arg3: Buffer) -> None: ...
    def glCompressedTexImage2D(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: Buffer) -> None: ...
    def glCompressedTexSubImage2D(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int, arg8: Buffer) -> None: ...
    def glCopyTexImage2D(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int) -> None: ...
    def glCopyTexSubImage2D(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int) -> None: ...
    def glCullFace(self, arg0: int) -> None: ...
    @overload
    def glDeleteTextures(self, arg0: int, arg1: list[int], arg2: int) -> None: ...
    @overload
    def glDeleteTextures(self, arg0: int, arg1: IntBuffer) -> None: ...
    def glDepthFunc(self, arg0: int) -> None: ...
    def glDepthMask(self, arg0: bool) -> None: ...
    def glDepthRangef(self, arg0: float, arg1: float) -> None: ...
    def glDepthRangex(self, arg0: int, arg1: int) -> None: ...
    def glDisable(self, arg0: int) -> None: ...
    def glDisableClientState(self, arg0: int) -> None: ...
    def glDrawArrays(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def glDrawElements(self, arg0: int, arg1: int, arg2: int, arg3: Buffer) -> None: ...
    def glEnable(self, arg0: int) -> None: ...
    def glEnableClientState(self, arg0: int) -> None: ...
    def glFinish(self) -> None: ...
    def glFlush(self) -> None: ...
    def glFogf(self, arg0: int, arg1: float) -> None: ...
    @overload
    def glFogfv(self, arg0: int, arg1: list[float], arg2: int) -> None: ...
    @overload
    def glFogfv(self, arg0: int, arg1: FloatBuffer) -> None: ...
    def glFogx(self, arg0: int, arg1: int) -> None: ...
    @overload
    def glFogxv(self, arg0: int, arg1: list[int], arg2: int) -> None: ...
    @overload
    def glFogxv(self, arg0: int, arg1: IntBuffer) -> None: ...
    def glFrontFace(self, arg0: int) -> None: ...
    def glFrustumf(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None: ...
    def glFrustumx(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    @overload
    def glGenTextures(self, arg0: int, arg1: list[int], arg2: int) -> None: ...
    @overload
    def glGenTextures(self, arg0: int, arg1: IntBuffer) -> None: ...
    def glGetError(self) -> int: ...
    @overload
    def glGetIntegerv(self, arg0: int, arg1: list[int], arg2: int) -> None: ...
    @overload
    def glGetIntegerv(self, arg0: int, arg1: IntBuffer) -> None: ...
    def glGetString(self, arg0: int) -> str: ...
    def glHint(self, arg0: int, arg1: int) -> None: ...
    def glLightModelf(self, arg0: int, arg1: float) -> None: ...
    @overload
    def glLightModelfv(self, arg0: int, arg1: list[float], arg2: int) -> None: ...
    @overload
    def glLightModelfv(self, arg0: int, arg1: FloatBuffer) -> None: ...
    def glLightModelx(self, arg0: int, arg1: int) -> None: ...
    @overload
    def glLightModelxv(self, arg0: int, arg1: list[int], arg2: int) -> None: ...
    @overload
    def glLightModelxv(self, arg0: int, arg1: IntBuffer) -> None: ...
    def glLightf(self, arg0: int, arg1: int, arg2: float) -> None: ...
    @overload
    def glLightfv(self, arg0: int, arg1: int, arg2: list[float], arg3: int) -> None: ...
    @overload
    def glLightfv(self, arg0: int, arg1: int, arg2: FloatBuffer) -> None: ...
    def glLightx(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def glLightxv(self, arg0: int, arg1: int, arg2: list[int], arg3: int) -> None: ...
    @overload
    def glLightxv(self, arg0: int, arg1: int, arg2: IntBuffer) -> None: ...
    def glLineWidth(self, arg0: float) -> None: ...
    def glLineWidthx(self, arg0: int) -> None: ...
    def glLoadIdentity(self) -> None: ...
    @overload
    def glLoadMatrixf(self, arg0: list[float], arg1: int) -> None: ...
    @overload
    def glLoadMatrixf(self, arg0: FloatBuffer) -> None: ...
    @overload
    def glLoadMatrixx(self, arg0: list[int], arg1: int) -> None: ...
    @overload
    def glLoadMatrixx(self, arg0: IntBuffer) -> None: ...
    def glLogicOp(self, arg0: int) -> None: ...
    def glMaterialf(self, arg0: int, arg1: int, arg2: float) -> None: ...
    @overload
    def glMaterialfv(self, arg0: int, arg1: int, arg2: list[float], arg3: int) -> None: ...
    @overload
    def glMaterialfv(self, arg0: int, arg1: int, arg2: FloatBuffer) -> None: ...
    def glMaterialx(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def glMaterialxv(self, arg0: int, arg1: int, arg2: list[int], arg3: int) -> None: ...
    @overload
    def glMaterialxv(self, arg0: int, arg1: int, arg2: IntBuffer) -> None: ...
    def glMatrixMode(self, arg0: int) -> None: ...
    @overload
    def glMultMatrixf(self, arg0: list[float], arg1: int) -> None: ...
    @overload
    def glMultMatrixf(self, arg0: FloatBuffer) -> None: ...
    @overload
    def glMultMatrixx(self, arg0: list[int], arg1: int) -> None: ...
    @overload
    def glMultMatrixx(self, arg0: IntBuffer) -> None: ...
    def glMultiTexCoord4f(self, arg0: int, arg1: float, arg2: float, arg3: float, arg4: float) -> None: ...
    def glMultiTexCoord4x(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def glNormal3f(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def glNormal3x(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def glNormalPointer(self, arg0: int, arg1: int, arg2: Buffer) -> None: ...
    def glOrthof(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None: ...
    def glOrthox(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    def glPixelStorei(self, arg0: int, arg1: int) -> None: ...
    def glPointSize(self, arg0: float) -> None: ...
    def glPointSizex(self, arg0: int) -> None: ...
    def glPolygonOffset(self, arg0: float, arg1: float) -> None: ...
    def glPolygonOffsetx(self, arg0: int, arg1: int) -> None: ...
    def glPopMatrix(self) -> None: ...
    def glPushMatrix(self) -> None: ...
    def glReadPixels(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: Buffer) -> None: ...
    def glRotatef(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def glRotatex(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def glSampleCoverage(self, arg0: float, arg1: bool) -> None: ...
    def glSampleCoveragex(self, arg0: int, arg1: bool) -> None: ...
    def glScalef(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def glScalex(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def glScissor(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def glShadeModel(self, arg0: int) -> None: ...
    def glStencilFunc(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def glStencilMask(self, arg0: int) -> None: ...
    def glStencilOp(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def glTexCoordPointer(self, arg0: int, arg1: int, arg2: int, arg3: Buffer) -> None: ...
    def glTexEnvf(self, arg0: int, arg1: int, arg2: float) -> None: ...
    @overload
    def glTexEnvfv(self, arg0: int, arg1: int, arg2: list[float], arg3: int) -> None: ...
    @overload
    def glTexEnvfv(self, arg0: int, arg1: int, arg2: FloatBuffer) -> None: ...
    def glTexEnvx(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def glTexEnvxv(self, arg0: int, arg1: int, arg2: list[int], arg3: int) -> None: ...
    @overload
    def glTexEnvxv(self, arg0: int, arg1: int, arg2: IntBuffer) -> None: ...
    def glTexImage2D(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int, arg8: Buffer) -> None: ...
    def glTexParameterf(self, arg0: int, arg1: int, arg2: float) -> None: ...
    def glTexParameterx(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def glTexSubImage2D(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int, arg8: Buffer) -> None: ...
    def glTranslatef(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def glTranslatex(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def glVertexPointer(self, arg0: int, arg1: int, arg2: int, arg3: Buffer) -> None: ...
    def glViewport(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
