from typing import Any, ClassVar, overload

class RtbAdapter:
    def __init__(self) -> None: ...
    def collectSignals(self, arg0: "RtbSignalData", arg1: "SignalCallbacks") -> None: ...
    def loadRtbBannerAd(self, arg0: "MediationBannerAdConfiguration", arg1: "MediationAdLoadCallback") -> None: ...
    def loadRtbInterstitialAd(self, arg0: "MediationInterstitialAdConfiguration", arg1: "MediationAdLoadCallback") -> None: ...
    def loadRtbRewardedAd(self, arg0: "MediationRewardedAdConfiguration", arg1: "MediationAdLoadCallback") -> None: ...
    def loadRtbRewardedInterstitialAd(self, arg0: "MediationRewardedAdConfiguration", arg1: "MediationAdLoadCallback") -> None: ...
    def loadRtbNativeAd(self, arg0: "MediationNativeAdConfiguration", arg1: "MediationAdLoadCallback") -> None: ...
    def loadRtbNativeAdMapper(self, arg0: "MediationNativeAdConfiguration", arg1: "MediationAdLoadCallback") -> None: ...
    def loadRtbAppOpenAd(self, arg0: "MediationAppOpenAdConfiguration", arg1: "MediationAdLoadCallback") -> None: ...
