from typing import Any, ClassVar, overload
from android.gms.ads.AdSize import AdSize

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class Bundle: ...  # android.os.Bundle

class RtbSignalData:
    def __init__(self, arg0: Context, arg1: list, arg2: Bundle, arg3: AdSize) -> None: ...
    def getContext(self) -> Context: ...
    def getConfigurations(self) -> list: ...
    def getNetworkExtras(self) -> Bundle: ...
    def getAdSize(self) -> AdSize: ...
