from typing import Any, ClassVar, overload
from android.text.util.Rfc822Token import Rfc822Token

class Rfc822Tokenizer:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def tokenize(arg0: str, arg1: list) -> None: ...
    @overload
    @staticmethod
    def tokenize(arg0: str) -> list[Rfc822Token]: ...
    def findTokenStart(self, arg0: str, arg1: int) -> int: ...
    def findTokenEnd(self, arg0: str, arg1: int) -> int: ...
    def terminateToken(self, arg0: str) -> str: ...
