from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.IBinder import IBinder
from android.view.ActionMode import ActionMode
from android.view.KeyEvent import KeyEvent
from android.view.Menu import Menu
from android.view.MenuItem import MenuItem
from android.view.MotionEvent import MotionEvent
from android.view.SearchEvent import SearchEvent
from android.view.View import View
from android.view.Window import Window
from android.view.WindowManager import WindowManager
from android.view.accessibility.AccessibilityEvent import AccessibilityEvent
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class LayoutParams:
    """Forward declaration for ``android.view.WindowManager.LayoutParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.WindowManager.LayoutParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/WindowManager/LayoutParams
    """
    ...
class Callback:
    """Forward declaration for ``android.view.ActionMode.Callback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ActionMode.Callback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ActionMode/Callback
    """
    ...

class DreamService:
    DREAM_META_DATA: ClassVar[str]
    SERVICE_INTERFACE: ClassVar[str]
    def __init__(self) -> None: ...
    def dispatchKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def dispatchKeyShortcutEvent(self, arg0: KeyEvent) -> bool: ...
    def dispatchTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchTrackballEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchGenericMotionEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchPopulateAccessibilityEvent(self, arg0: AccessibilityEvent) -> bool: ...
    def onCreatePanelView(self, arg0: int) -> View: ...
    def onCreatePanelMenu(self, arg0: int, arg1: Menu) -> bool: ...
    def onPreparePanel(self, arg0: int, arg1: View, arg2: Menu) -> bool: ...
    def onMenuOpened(self, arg0: int, arg1: Menu) -> bool: ...
    def onMenuItemSelected(self, arg0: int, arg1: MenuItem) -> bool: ...
    def onWindowAttributesChanged(self, arg0: LayoutParams) -> None: ...
    def onContentChanged(self) -> None: ...
    def onWindowFocusChanged(self, arg0: bool) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onPanelClosed(self, arg0: int, arg1: Menu) -> None: ...
    @overload
    def onSearchRequested(self, arg0: SearchEvent) -> bool: ...
    @overload
    def onSearchRequested(self) -> bool: ...
    @overload
    def onWindowStartingActionMode(self, arg0: Callback) -> ActionMode: ...
    @overload
    def onWindowStartingActionMode(self, arg0: Callback, arg1: int) -> ActionMode: ...
    def onActionModeStarted(self, arg0: ActionMode) -> None: ...
    def onActionModeFinished(self, arg0: ActionMode) -> None: ...
    def getWindowManager(self) -> WindowManager: ...
    def getWindow(self) -> Window: ...
    @overload
    def setContentView(self, arg0: int) -> None: ...
    @overload
    def setContentView(self, arg0: View) -> None: ...
    @overload
    def setContentView(self, arg0: View, arg1: LayoutParams) -> None: ...
    def addContentView(self, arg0: View, arg1: LayoutParams) -> None: ...
    def findViewById(self, arg0: int) -> View: ...
    def requireViewById(self, arg0: int) -> View: ...
    def setInteractive(self, arg0: bool) -> None: ...
    def isInteractive(self) -> bool: ...
    def setFullscreen(self, arg0: bool) -> None: ...
    def isFullscreen(self) -> bool: ...
    def setScreenBright(self, arg0: bool) -> None: ...
    def isScreenBright(self) -> bool: ...
    def onCreate(self) -> None: ...
    def onDreamingStarted(self) -> None: ...
    def onDreamingStopped(self) -> None: ...
    def onWakeUp(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onUnbind(self, arg0: Intent) -> bool: ...
    def finish(self) -> None: ...
    def wakeUp(self) -> None: ...
    def onDestroy(self) -> None: ...
    def dump(self, arg0: FileDescriptor, arg1: PrintWriter, arg2: list[str]) -> None: ...
