from typing import Any, ClassVar, overload
from android.content.Context import Context

class KeyStoreParameter:
    def isEncryptionRequired(self) -> bool: ...

    class Builder:
        def __init__(self, arg0: Context) -> None: ...
        def setEncryptionRequired(self, arg0: bool) -> "Builder": ...
        def build(self) -> "KeyStoreParameter": ...
