from typing import Any, ClassVar, overload
from java.util.function.IntFunction import IntFunction

class PropertyMapper:
    def mapBoolean(self, arg0: str, arg1: int) -> int: ...
    def mapByte(self, arg0: str, arg1: int) -> int: ...
    def mapChar(self, arg0: str, arg1: int) -> int: ...
    def mapDouble(self, arg0: str, arg1: int) -> int: ...
    def mapFloat(self, arg0: str, arg1: int) -> int: ...
    def mapInt(self, arg0: str, arg1: int) -> int: ...
    def mapLong(self, arg0: str, arg1: int) -> int: ...
    def mapShort(self, arg0: str, arg1: int) -> int: ...
    def mapObject(self, arg0: str, arg1: int) -> int: ...
    def mapColor(self, arg0: str, arg1: int) -> int: ...
    def mapGravity(self, arg0: str, arg1: int) -> int: ...
    def mapIntEnum(self, arg0: str, arg1: int, arg2: IntFunction) -> int: ...
    def mapResourceId(self, arg0: str, arg1: int) -> int: ...
    def mapIntFlag(self, arg0: str, arg1: int, arg2: IntFunction) -> int: ...

    class PropertyConflictException:
        def __init__(self, arg0: str, arg1: str, arg2: str) -> None: ...
