from typing import Any, ClassVar, overload
from android.graphics.Color import Color

class PropertyReader:
    def readBoolean(self, arg0: int, arg1: bool) -> None: ...
    def readByte(self, arg0: int, arg1: int) -> None: ...
    def readChar(self, arg0: int, arg1: str) -> None: ...
    def readDouble(self, arg0: int, arg1: float) -> None: ...
    def readFloat(self, arg0: int, arg1: float) -> None: ...
    def readInt(self, arg0: int, arg1: int) -> None: ...
    def readLong(self, arg0: int, arg1: int) -> None: ...
    def readShort(self, arg0: int, arg1: int) -> None: ...
    def readObject(self, arg0: int, arg1: Any) -> None: ...
    @overload
    def readColor(self, arg0: int, arg1: int) -> None: ...
    @overload
    def readColor(self, arg0: int, arg1: int) -> None: ...
    @overload
    def readColor(self, arg0: int, arg1: Color) -> None: ...
    def readGravity(self, arg0: int, arg1: int) -> None: ...
    def readIntEnum(self, arg0: int, arg1: int) -> None: ...
    def readIntFlag(self, arg0: int, arg1: int) -> None: ...
    def readResourceId(self, arg0: int, arg1: int) -> None: ...

    class PropertyTypeMismatchException:
        @overload
        def __init__(self, arg0: int, arg1: str, arg2: str, arg3: str) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: str, arg2: str) -> None: ...
