from typing import Any, ClassVar, overload
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.Chronology import Chronology
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.format.FormatStyle import FormatStyle
from java.time.format.SignStyle import SignStyle
from java.time.format.TextStyle import TextStyle
from java.time.temporal.TemporalField import TemporalField
from java.util.Locale import Locale

class DateTimeFormatterBuilder:
    def __init__(self) -> None: ...
    @staticmethod
    def getLocalizedDateTimePattern(arg0: FormatStyle, arg1: FormatStyle, arg2: Chronology, arg3: Locale) -> str: ...
    def parseCaseSensitive(self) -> "DateTimeFormatterBuilder": ...
    def parseCaseInsensitive(self) -> "DateTimeFormatterBuilder": ...
    def parseStrict(self) -> "DateTimeFormatterBuilder": ...
    def parseLenient(self) -> "DateTimeFormatterBuilder": ...
    def parseDefaulting(self, arg0: TemporalField, arg1: int) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendValue(self, arg0: TemporalField) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendValue(self, arg0: TemporalField, arg1: int) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendValue(self, arg0: TemporalField, arg1: int, arg2: int, arg3: SignStyle) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendValueReduced(self, arg0: TemporalField, arg1: int, arg2: int, arg3: int) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendValueReduced(self, arg0: TemporalField, arg1: int, arg2: int, arg3: ChronoLocalDate) -> "DateTimeFormatterBuilder": ...
    def appendFraction(self, arg0: TemporalField, arg1: int, arg2: int, arg3: bool) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendText(self, arg0: TemporalField) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendText(self, arg0: TemporalField, arg1: TextStyle) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendText(self, arg0: TemporalField, arg1: dict) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendInstant(self) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendInstant(self, arg0: int) -> "DateTimeFormatterBuilder": ...
    def appendOffsetId(self) -> "DateTimeFormatterBuilder": ...
    def appendOffset(self, arg0: str, arg1: str) -> "DateTimeFormatterBuilder": ...
    def appendLocalizedOffset(self, arg0: TextStyle) -> "DateTimeFormatterBuilder": ...
    def appendZoneId(self) -> "DateTimeFormatterBuilder": ...
    def appendZoneRegionId(self) -> "DateTimeFormatterBuilder": ...
    def appendZoneOrOffsetId(self) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendZoneText(self, arg0: TextStyle) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendZoneText(self, arg0: TextStyle, arg1: set) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendGenericZoneText(self, arg0: TextStyle) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendGenericZoneText(self, arg0: TextStyle, arg1: set) -> "DateTimeFormatterBuilder": ...
    def appendChronologyId(self) -> "DateTimeFormatterBuilder": ...
    def appendChronologyText(self, arg0: TextStyle) -> "DateTimeFormatterBuilder": ...
    def appendLocalized(self, arg0: FormatStyle, arg1: FormatStyle) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendLiteral(self, arg0: str) -> "DateTimeFormatterBuilder": ...
    @overload
    def appendLiteral(self, arg0: str) -> "DateTimeFormatterBuilder": ...
    def append(self, arg0: DateTimeFormatter) -> "DateTimeFormatterBuilder": ...
    def appendOptional(self, arg0: DateTimeFormatter) -> "DateTimeFormatterBuilder": ...
    def appendPattern(self, arg0: str) -> "DateTimeFormatterBuilder": ...
    @overload
    def padNext(self, arg0: int) -> "DateTimeFormatterBuilder": ...
    @overload
    def padNext(self, arg0: int, arg1: str) -> "DateTimeFormatterBuilder": ...
    def optionalStart(self) -> "DateTimeFormatterBuilder": ...
    def optionalEnd(self) -> "DateTimeFormatterBuilder": ...
    @overload
    def toFormatter(self) -> DateTimeFormatter: ...
    @overload
    def toFormatter(self, arg0: Locale) -> DateTimeFormatter: ...
