from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent

class BroadcastHelper:
    def __init__(self) -> None: ...
    @staticmethod
    def canResolveBroadcast(arg0: Context, arg1: Intent) -> bool: ...
    @staticmethod
    def resolveBroadcast(arg0: Context, arg1: Intent) -> list: ...
    @staticmethod
    def sendIntentExplicitly(arg0: Context, arg1: Intent) -> None: ...
