from typing import Any, ClassVar, overload

class CloseHelper:
    def __init__(self) -> None: ...
    @staticmethod
    def close(arg0: "Cursor") -> None: ...
    @staticmethod
    def closeQuietly(arg0: "Closeable") -> None: ...
