from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Rect import Rect
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...
class AnimationCallback:
    """Forward declaration for ``android.graphics.drawable.Animatable2.AnimationCallback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.drawable.Animatable2.AnimationCallback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/drawable/Animatable2/AnimationCallback
    """
    ...

class AnimatedImageDrawable:
    REPEAT_INFINITE: ClassVar[int]
    def __init__(self) -> None: ...
    def setRepeatCount(self, arg0: int) -> None: ...
    def getRepeatCount(self) -> int: ...
    def inflate(self, arg0: Resources, arg1: XmlPullParser, arg2: AttributeSet, arg3: Theme) -> None: ...
    def getIntrinsicWidth(self) -> int: ...
    def getIntrinsicHeight(self) -> int: ...
    def draw(self, arg0: Canvas) -> None: ...
    def setAlpha(self, arg0: int) -> None: ...
    def getAlpha(self) -> int: ...
    def setColorFilter(self, arg0: ColorFilter) -> None: ...
    def getColorFilter(self) -> ColorFilter: ...
    def getOpacity(self) -> int: ...
    def setAutoMirrored(self, arg0: bool) -> None: ...
    def onLayoutDirectionChanged(self, arg0: int) -> bool: ...
    def isAutoMirrored(self) -> bool: ...
    def isRunning(self) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def registerAnimationCallback(self, arg0: AnimationCallback) -> None: ...
    def unregisterAnimationCallback(self, arg0: AnimationCallback) -> bool: ...
    def clearAnimationCallbacks(self) -> None: ...
    def onBoundsChange(self, arg0: Rect) -> None: ...
