from typing import Any, ClassVar, overload
from android.content.res.ColorStateList import ColorStateList
from android.content.res.Resources import Resources
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Insets import Insets
from android.graphics.Outline import Outline
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class ConstantState:
    """Forward declaration for ``android.graphics.drawable.Drawable.ConstantState``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.drawable.Drawable.ConstantState')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/drawable/Drawable/ConstantState
    """
    ...
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...
class AnimationCallback:
    """Forward declaration for ``android.graphics.drawable.Animatable2.AnimationCallback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.drawable.Animatable2.AnimationCallback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/drawable/Animatable2/AnimationCallback
    """
    ...

class AnimatedVectorDrawable:
    def __init__(self) -> None: ...
    def mutate(self) -> Drawable: ...
    def getConstantState(self) -> ConstantState: ...
    def getChangingConfigurations(self) -> int: ...
    def draw(self, arg0: Canvas) -> None: ...
    def onBoundsChange(self, arg0: Rect) -> None: ...
    def onStateChange(self, arg0: list[int]) -> bool: ...
    def onLevelChange(self, arg0: int) -> bool: ...
    def onLayoutDirectionChanged(self, arg0: int) -> bool: ...
    def getAlpha(self) -> int: ...
    def setAlpha(self, arg0: int) -> None: ...
    def setColorFilter(self, arg0: ColorFilter) -> None: ...
    def getColorFilter(self) -> ColorFilter: ...
    def setTintList(self, arg0: ColorStateList) -> None: ...
    def setHotspot(self, arg0: float, arg1: float) -> None: ...
    def setHotspotBounds(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def setTintBlendMode(self, arg0: BlendMode) -> None: ...
    def setVisible(self, arg0: bool, arg1: bool) -> bool: ...
    def isStateful(self) -> bool: ...
    def getOpacity(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getIntrinsicHeight(self) -> int: ...
    def getOutline(self, arg0: Outline) -> None: ...
    def getOpticalInsets(self) -> Insets: ...
    def inflate(self, arg0: Resources, arg1: XmlPullParser, arg2: AttributeSet, arg3: Theme) -> None: ...
    def canApplyTheme(self) -> bool: ...
    def applyTheme(self, arg0: Theme) -> None: ...
    def isRunning(self) -> bool: ...
    def reset(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def registerAnimationCallback(self, arg0: AnimationCallback) -> None: ...
    def unregisterAnimationCallback(self, arg0: AnimationCallback) -> bool: ...
    def clearAnimationCallbacks(self) -> None: ...
