from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from java.lang.Runnable import Runnable
from org.xmlpull.v1.XmlPullParser import XmlPullParser

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...
class DrawableContainerState:
    """Forward declaration for ``android.graphics.drawable.DrawableContainer.DrawableContainerState``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.drawable.DrawableContainer.DrawableContainerState')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/drawable/DrawableContainer/DrawableContainerState
    """
    ...

class AnimationDrawable:
    def __init__(self) -> None: ...
    def setVisible(self, arg0: bool, arg1: bool) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def isRunning(self) -> bool: ...
    def run(self) -> None: ...
    def unscheduleSelf(self, arg0: Runnable) -> None: ...
    def getNumberOfFrames(self) -> int: ...
    def getFrame(self, arg0: int) -> Drawable: ...
    def getDuration(self, arg0: int) -> int: ...
    def isOneShot(self) -> bool: ...
    def setOneShot(self, arg0: bool) -> None: ...
    def addFrame(self, arg0: Drawable, arg1: int) -> None: ...
    def inflate(self, arg0: Resources, arg1: XmlPullParser, arg2: AttributeSet, arg3: Theme) -> None: ...
    def mutate(self) -> Drawable: ...
    def setConstantState(self, arg0: DrawableContainerState) -> None: ...
