from typing import Any, ClassVar, overload
from android.content.res.ColorStateList import ColorStateList
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from java.lang.Runnable import Runnable

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...
class ConstantState:
    """Forward declaration for ``android.graphics.drawable.Drawable.ConstantState``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.drawable.Drawable.ConstantState')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/drawable/Drawable/ConstantState
    """
    ...

class ColorStateListDrawable:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ColorStateList) -> None: ...
    def draw(self, arg0: Canvas) -> None: ...
    def getAlpha(self) -> int: ...
    def isStateful(self) -> bool: ...
    def hasFocusStateSpecified(self) -> bool: ...
    def getCurrent(self) -> Drawable: ...
    def applyTheme(self, arg0: Theme) -> None: ...
    def canApplyTheme(self) -> bool: ...
    def setAlpha(self, arg0: int) -> None: ...
    def clearAlpha(self) -> None: ...
    def setTintList(self, arg0: ColorStateList) -> None: ...
    def setTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getColorFilter(self) -> ColorFilter: ...
    def setColorFilter(self, arg0: ColorFilter) -> None: ...
    def getOpacity(self) -> int: ...
    def onBoundsChange(self, arg0: Rect) -> None: ...
    def onStateChange(self, arg0: list[int]) -> bool: ...
    def invalidateDrawable(self, arg0: Drawable) -> None: ...
    def scheduleDrawable(self, arg0: Drawable, arg1: Runnable, arg2: int) -> None: ...
    def unscheduleDrawable(self, arg0: Drawable, arg1: Runnable) -> None: ...
    def getConstantState(self) -> ConstantState: ...
    def getColorStateList(self) -> ColorStateList: ...
    def getChangingConfigurations(self) -> int: ...
    def mutate(self) -> Drawable: ...
    def setColorStateList(self, arg0: ColorStateList) -> None: ...
