from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class PaintDrawable:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    def setCornerRadius(self, arg0: float) -> None: ...
    def setCornerRadii(self, arg0: list[float]) -> None: ...
    def inflateTag(self, arg0: str, arg1: Resources, arg2: XmlPullParser, arg3: AttributeSet) -> bool: ...
