from typing import Any, ClassVar, overload
from android.content.res.ColorStateList import ColorStateList
from android.content.res.Resources import Resources
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint
from android.graphics.Rect import Rect
from android.graphics.Shader import Shader
from android.graphics.drawable.Drawable import Drawable
from android.graphics.drawable.shapes.Shape import Shape
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...
class ConstantState:
    """Forward declaration for ``android.graphics.drawable.Drawable.ConstantState``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.drawable.Drawable.ConstantState')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/drawable/Drawable/ConstantState
    """
    ...

class ShapeDrawable:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Shape) -> None: ...
    def getShape(self) -> Shape: ...
    def setShape(self, arg0: Shape) -> None: ...
    def setShaderFactory(self, arg0: "ShaderFactory") -> None: ...
    def getShaderFactory(self) -> "ShaderFactory": ...
    def getPaint(self) -> Paint: ...
    @overload
    def setPadding(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def setPadding(self, arg0: Rect) -> None: ...
    def setIntrinsicWidth(self, arg0: int) -> None: ...
    def setIntrinsicHeight(self, arg0: int) -> None: ...
    def getIntrinsicWidth(self) -> int: ...
    def getIntrinsicHeight(self) -> int: ...
    def getPadding(self, arg0: Rect) -> bool: ...
    def onDraw(self, arg0: Shape, arg1: Canvas, arg2: Paint) -> None: ...
    def draw(self, arg0: Canvas) -> None: ...
    def getChangingConfigurations(self) -> int: ...
    def setAlpha(self, arg0: int) -> None: ...
    def getAlpha(self) -> int: ...
    def setTintList(self, arg0: ColorStateList) -> None: ...
    def setTintBlendMode(self, arg0: BlendMode) -> None: ...
    def setColorFilter(self, arg0: ColorFilter) -> None: ...
    def getOpacity(self) -> int: ...
    def setDither(self, arg0: bool) -> None: ...
    def onBoundsChange(self, arg0: Rect) -> None: ...
    def onStateChange(self, arg0: list[int]) -> bool: ...
    def isStateful(self) -> bool: ...
    def hasFocusStateSpecified(self) -> bool: ...
    def inflateTag(self, arg0: str, arg1: Resources, arg2: XmlPullParser, arg3: AttributeSet) -> bool: ...
    def inflate(self, arg0: Resources, arg1: XmlPullParser, arg2: AttributeSet, arg3: Theme) -> None: ...
    def applyTheme(self, arg0: Theme) -> None: ...
    def getOutline(self, arg0: Outline) -> None: ...
    def getConstantState(self) -> ConstantState: ...
    def mutate(self) -> Drawable: ...

    class ShaderFactory:
        def __init__(self) -> None: ...
        def resize(self, arg0: int, arg1: int) -> Shader: ...
