from typing import Any, ClassVar, overload
from android.content.res.ColorStateList import ColorStateList
from android.content.res.Resources import Resources
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Insets import Insets
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class ConstantState:
    """Forward declaration for ``android.graphics.drawable.Drawable.ConstantState``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.drawable.Drawable.ConstantState')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/drawable/Drawable/ConstantState
    """
    ...
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...

class VectorDrawable:
    def __init__(self) -> None: ...
    def mutate(self) -> Drawable: ...
    def getConstantState(self) -> ConstantState: ...
    def draw(self, arg0: Canvas) -> None: ...
    def getAlpha(self) -> int: ...
    def setAlpha(self, arg0: int) -> None: ...
    def setColorFilter(self, arg0: ColorFilter) -> None: ...
    def getColorFilter(self) -> ColorFilter: ...
    def setTintList(self, arg0: ColorStateList) -> None: ...
    def setTintBlendMode(self, arg0: BlendMode) -> None: ...
    def isStateful(self) -> bool: ...
    def hasFocusStateSpecified(self) -> bool: ...
    def onStateChange(self, arg0: list[int]) -> bool: ...
    def getOpacity(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getIntrinsicHeight(self) -> int: ...
    def getOpticalInsets(self) -> Insets: ...
    def canApplyTheme(self) -> bool: ...
    def applyTheme(self, arg0: Theme) -> None: ...
    def inflate(self, arg0: Resources, arg1: XmlPullParser, arg2: AttributeSet, arg3: Theme) -> None: ...
    def getChangingConfigurations(self) -> int: ...
    def setAutoMirrored(self, arg0: bool) -> None: ...
    def isAutoMirrored(self) -> bool: ...
