from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.graphics.Bitmap import Bitmap
from android.renderscript.BaseObj import BaseObj
from android.renderscript.Element import Element
from android.renderscript.FieldPacker import FieldPacker
from android.renderscript.RenderScript import RenderScript
from android.renderscript.Type import Type
from android.view.Surface import Surface
from java.nio.ByteBuffer import ByteBuffer

class Allocation:
    USAGE_GRAPHICS_CONSTANTS: ClassVar[int]
    USAGE_GRAPHICS_RENDER_TARGET: ClassVar[int]
    USAGE_GRAPHICS_TEXTURE: ClassVar[int]
    USAGE_GRAPHICS_VERTEX: ClassVar[int]
    USAGE_IO_INPUT: ClassVar[int]
    USAGE_IO_OUTPUT: ClassVar[int]
    USAGE_SCRIPT: ClassVar[int]
    USAGE_SHARED: ClassVar[int]
    def getElement(self) -> Element: ...
    def getUsage(self) -> int: ...
    def setAutoPadding(self, arg0: bool) -> None: ...
    def getBytesSize(self) -> int: ...
    def finalize(self) -> None: ...
    def getType(self) -> Type: ...
    def syncAll(self, arg0: int) -> None: ...
    def ioSend(self) -> None: ...
    def ioReceive(self) -> None: ...
    @overload
    def copyFrom(self, arg0: list[BaseObj]) -> None: ...
    @overload
    def copyFrom(self, arg0: Any) -> None: ...
    @overload
    def copyFrom(self, arg0: list[int]) -> None: ...
    @overload
    def copyFrom(self, arg0: list[int]) -> None: ...
    @overload
    def copyFrom(self, arg0: list[int]) -> None: ...
    @overload
    def copyFrom(self, arg0: list[float]) -> None: ...
    @overload
    def copyFrom(self, arg0: Bitmap) -> None: ...
    @overload
    def copyFrom(self, arg0: "Allocation") -> None: ...
    @overload
    def copyFromUnchecked(self, arg0: Any) -> None: ...
    @overload
    def copyFromUnchecked(self, arg0: list[int]) -> None: ...
    @overload
    def copyFromUnchecked(self, arg0: list[int]) -> None: ...
    @overload
    def copyFromUnchecked(self, arg0: list[int]) -> None: ...
    @overload
    def copyFromUnchecked(self, arg0: list[float]) -> None: ...
    @overload
    def setFromFieldPacker(self, arg0: int, arg1: FieldPacker) -> None: ...
    @overload
    def setFromFieldPacker(self, arg0: int, arg1: int, arg2: FieldPacker) -> None: ...
    @overload
    def setFromFieldPacker(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: FieldPacker) -> None: ...
    def generateMipmaps(self) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, arg0: int, arg1: int, arg2: Any) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, arg0: int, arg1: int, arg2: list[float]) -> None: ...
    @overload
    def copy1DRangeFrom(self, arg0: int, arg1: int, arg2: Any) -> None: ...
    @overload
    def copy1DRangeFrom(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeFrom(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeFrom(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeFrom(self, arg0: int, arg1: int, arg2: list[float]) -> None: ...
    @overload
    def copy1DRangeFrom(self, arg0: int, arg1: int, arg2: "Allocation", arg3: int) -> None: ...
    @overload
    def copy2DRangeFrom(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: Any) -> None: ...
    @overload
    def copy2DRangeFrom(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[int]) -> None: ...
    @overload
    def copy2DRangeFrom(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[int]) -> None: ...
    @overload
    def copy2DRangeFrom(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[int]) -> None: ...
    @overload
    def copy2DRangeFrom(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[float]) -> None: ...
    @overload
    def copy2DRangeFrom(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: "Allocation", arg5: int, arg6: int) -> None: ...
    @overload
    def copy2DRangeFrom(self, arg0: int, arg1: int, arg2: Bitmap) -> None: ...
    @overload
    def copy3DRangeFrom(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: Any) -> None: ...
    @overload
    def copy3DRangeFrom(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: "Allocation", arg7: int, arg8: int, arg9: int) -> None: ...
    @overload
    def copyTo(self, arg0: Bitmap) -> None: ...
    @overload
    def copyTo(self, arg0: Any) -> None: ...
    @overload
    def copyTo(self, arg0: list[int]) -> None: ...
    @overload
    def copyTo(self, arg0: list[int]) -> None: ...
    @overload
    def copyTo(self, arg0: list[int]) -> None: ...
    @overload
    def copyTo(self, arg0: list[float]) -> None: ...
    def resize(self, arg0: int) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, arg0: int, arg1: int, arg2: Any) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, arg0: int, arg1: int, arg2: list[float]) -> None: ...
    @overload
    def copy1DRangeTo(self, arg0: int, arg1: int, arg2: Any) -> None: ...
    @overload
    def copy1DRangeTo(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeTo(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeTo(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
    @overload
    def copy1DRangeTo(self, arg0: int, arg1: int, arg2: list[float]) -> None: ...
    @overload
    def copy2DRangeTo(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: Any) -> None: ...
    @overload
    def copy2DRangeTo(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[int]) -> None: ...
    @overload
    def copy2DRangeTo(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[int]) -> None: ...
    @overload
    def copy2DRangeTo(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[int]) -> None: ...
    @overload
    def copy2DRangeTo(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: list[float]) -> None: ...
    def copy3DRangeTo(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: Any) -> None: ...
    @overload
    @staticmethod
    def createTyped(arg0: RenderScript, arg1: Type, arg2: "MipmapControl", arg3: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createTyped(arg0: RenderScript, arg1: Type, arg2: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createTyped(arg0: RenderScript, arg1: Type) -> "Allocation": ...
    @overload
    @staticmethod
    def createSized(arg0: RenderScript, arg1: Element, arg2: int, arg3: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createSized(arg0: RenderScript, arg1: Element, arg2: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createFromBitmap(arg0: RenderScript, arg1: Bitmap, arg2: "MipmapControl", arg3: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createFromBitmap(arg0: RenderScript, arg1: Bitmap) -> "Allocation": ...
    def getByteBuffer(self) -> ByteBuffer: ...
    @staticmethod
    def createAllocations(arg0: RenderScript, arg1: Type, arg2: int, arg3: int) -> list["Allocation"]: ...
    def getStride(self) -> int: ...
    def getTimeStamp(self) -> int: ...
    def getSurface(self) -> Surface: ...
    def setSurface(self, arg0: Surface) -> None: ...
    @overload
    @staticmethod
    def createCubemapFromBitmap(arg0: RenderScript, arg1: Bitmap, arg2: "MipmapControl", arg3: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createCubemapFromBitmap(arg0: RenderScript, arg1: Bitmap) -> "Allocation": ...
    @overload
    @staticmethod
    def createCubemapFromCubeFaces(arg0: RenderScript, arg1: Bitmap, arg2: Bitmap, arg3: Bitmap, arg4: Bitmap, arg5: Bitmap, arg6: Bitmap, arg7: "MipmapControl", arg8: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createCubemapFromCubeFaces(arg0: RenderScript, arg1: Bitmap, arg2: Bitmap, arg3: Bitmap, arg4: Bitmap, arg5: Bitmap, arg6: Bitmap) -> "Allocation": ...
    @overload
    @staticmethod
    def createFromBitmapResource(arg0: RenderScript, arg1: Resources, arg2: int, arg3: "MipmapControl", arg4: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createFromBitmapResource(arg0: RenderScript, arg1: Resources, arg2: int) -> "Allocation": ...
    @staticmethod
    def createFromString(arg0: RenderScript, arg1: str, arg2: int) -> "Allocation": ...
    def setOnBufferAvailableListener(self, arg0: "OnBufferAvailableListener") -> None: ...
    def destroy(self) -> None: ...

    class MipmapControl:
        MIPMAP_NONE: ClassVar["MipmapControl"]
        MIPMAP_FULL: ClassVar["MipmapControl"]
        MIPMAP_ON_SYNC_TO_TEXTURE: ClassVar["MipmapControl"]
        @staticmethod
        def values() -> list["MipmapControl"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "MipmapControl": ...

    class OnBufferAvailableListener:
        def onBufferAvailable(self, arg0: "Allocation") -> None: ...
