from typing import Any, ClassVar, overload
from android.renderscript.Allocation import Allocation
from android.renderscript.RenderScript import RenderScript
from android.renderscript.Type import Type

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class CubemapFace:
    """Forward declaration for ``android.renderscript.Type.CubemapFace``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.renderscript.Type.CubemapFace')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/renderscript/Type/CubemapFace
    """
    ...

class AllocationAdapter:
    def setLOD(self, arg0: int) -> None: ...
    def setFace(self, arg0: CubemapFace) -> None: ...
    def setX(self, arg0: int) -> None: ...
    def setY(self, arg0: int) -> None: ...
    def setZ(self, arg0: int) -> None: ...
    @staticmethod
    def create1D(arg0: RenderScript, arg1: Allocation) -> "AllocationAdapter": ...
    @staticmethod
    def create2D(arg0: RenderScript, arg1: Allocation) -> "AllocationAdapter": ...
    @staticmethod
    def createTyped(arg0: RenderScript, arg1: Allocation, arg2: Type) -> "AllocationAdapter": ...
    def resize(self, arg0: int) -> None: ...
