from typing import Any, ClassVar, overload
from android.renderscript.RenderScript import RenderScript

class Element:
    def getBytesSize(self) -> int: ...
    def getVectorSize(self) -> int: ...
    def isComplex(self) -> bool: ...
    def getSubElementCount(self) -> int: ...
    def getSubElement(self, arg0: int) -> "Element": ...
    def getSubElementName(self, arg0: int) -> str: ...
    def getSubElementArraySize(self, arg0: int) -> int: ...
    def getSubElementOffsetBytes(self, arg0: int) -> int: ...
    def getDataType(self) -> "DataType": ...
    def getDataKind(self) -> "DataKind": ...
    @staticmethod
    def BOOLEAN(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U8(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I8(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U16(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I16(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U32(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I32(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U64(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I64(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F16(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F32(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F64(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def ELEMENT(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def TYPE(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def ALLOCATION(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def SAMPLER(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def SCRIPT(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def MESH(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def PROGRAM_FRAGMENT(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def PROGRAM_VERTEX(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def PROGRAM_RASTER(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def PROGRAM_STORE(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def FONT(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def A_8(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def RGB_565(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def RGB_888(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def RGBA_5551(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def RGBA_4444(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def RGBA_8888(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F16_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F16_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F16_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F32_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F32_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F32_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F64_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F64_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def F64_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U8_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U8_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U8_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I8_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I8_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I8_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U16_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U16_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U16_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I16_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I16_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I16_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U32_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U32_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U32_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I32_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I32_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I32_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U64_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U64_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def U64_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I64_2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I64_3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def I64_4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def YUV(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def MATRIX_4X4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def MATRIX4X4(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def MATRIX_3X3(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def MATRIX_2X2(arg0: RenderScript) -> "Element": ...
    @staticmethod
    def createVector(arg0: RenderScript, arg1: "DataType", arg2: int) -> "Element": ...
    @staticmethod
    def createPixel(arg0: RenderScript, arg1: "DataType", arg2: "DataKind") -> "Element": ...
    def isCompatible(self, arg0: "Element") -> bool: ...

    class Builder:
        def __init__(self, arg0: RenderScript) -> None: ...
        @overload
        def add(self, arg0: "Element", arg1: str, arg2: int) -> "Builder": ...
        @overload
        def add(self, arg0: "Element", arg1: str) -> "Builder": ...
        def create(self) -> "Element": ...

    class DataKind:
        USER: ClassVar["DataKind"]
        PIXEL_L: ClassVar["DataKind"]
        PIXEL_A: ClassVar["DataKind"]
        PIXEL_LA: ClassVar["DataKind"]
        PIXEL_RGB: ClassVar["DataKind"]
        PIXEL_RGBA: ClassVar["DataKind"]
        PIXEL_DEPTH: ClassVar["DataKind"]
        PIXEL_YUV: ClassVar["DataKind"]
        @staticmethod
        def values() -> list["DataKind"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "DataKind": ...

    class DataType:
        NONE: ClassVar["DataType"]
        FLOAT_16: ClassVar["DataType"]
        FLOAT_32: ClassVar["DataType"]
        FLOAT_64: ClassVar["DataType"]
        SIGNED_8: ClassVar["DataType"]
        SIGNED_16: ClassVar["DataType"]
        SIGNED_32: ClassVar["DataType"]
        SIGNED_64: ClassVar["DataType"]
        UNSIGNED_8: ClassVar["DataType"]
        UNSIGNED_16: ClassVar["DataType"]
        UNSIGNED_32: ClassVar["DataType"]
        UNSIGNED_64: ClassVar["DataType"]
        BOOLEAN: ClassVar["DataType"]
        UNSIGNED_5_6_5: ClassVar["DataType"]
        UNSIGNED_5_5_5_1: ClassVar["DataType"]
        UNSIGNED_4_4_4_4: ClassVar["DataType"]
        MATRIX_4X4: ClassVar["DataType"]
        MATRIX_3X3: ClassVar["DataType"]
        MATRIX_2X2: ClassVar["DataType"]
        RS_ELEMENT: ClassVar["DataType"]
        RS_TYPE: ClassVar["DataType"]
        RS_ALLOCATION: ClassVar["DataType"]
        RS_SAMPLER: ClassVar["DataType"]
        RS_SCRIPT: ClassVar["DataType"]
        RS_MESH: ClassVar["DataType"]
        RS_PROGRAM_FRAGMENT: ClassVar["DataType"]
        RS_PROGRAM_VERTEX: ClassVar["DataType"]
        RS_PROGRAM_RASTER: ClassVar["DataType"]
        RS_PROGRAM_STORE: ClassVar["DataType"]
        RS_FONT: ClassVar["DataType"]
        @staticmethod
        def values() -> list["DataType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "DataType": ...
