from typing import Any, ClassVar, overload

class Matrix3f:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: list[float]) -> None: ...
    def getArray(self) -> list[float]: ...
    def get(self, arg0: int, arg1: int) -> float: ...
    def set(self, arg0: int, arg1: int, arg2: float) -> None: ...
    def loadIdentity(self) -> None: ...
    def load(self, arg0: "Matrix3f") -> None: ...
    @overload
    def loadRotate(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    @overload
    def loadRotate(self, arg0: float) -> None: ...
    @overload
    def loadScale(self, arg0: float, arg1: float) -> None: ...
    @overload
    def loadScale(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def loadTranslate(self, arg0: float, arg1: float) -> None: ...
    def loadMultiply(self, arg0: "Matrix3f", arg1: "Matrix3f") -> None: ...
    def multiply(self, arg0: "Matrix3f") -> None: ...
    @overload
    def rotate(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    @overload
    def rotate(self, arg0: float) -> None: ...
    @overload
    def scale(self, arg0: float, arg1: float) -> None: ...
    @overload
    def scale(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def translate(self, arg0: float, arg1: float) -> None: ...
    def transpose(self) -> None: ...
