from typing import Any, ClassVar, overload

class Matrix4f:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: list[float]) -> None: ...
    def getArray(self) -> list[float]: ...
    def get(self, arg0: int, arg1: int) -> float: ...
    def set(self, arg0: int, arg1: int, arg2: float) -> None: ...
    def loadIdentity(self) -> None: ...
    def load(self, arg0: "Matrix4f") -> None: ...
    def loadRotate(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def loadScale(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def loadTranslate(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def loadMultiply(self, arg0: "Matrix4f", arg1: "Matrix4f") -> None: ...
    def loadOrtho(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None: ...
    def loadOrthoWindow(self, arg0: int, arg1: int) -> None: ...
    def loadFrustum(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None: ...
    def loadPerspective(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def loadProjectionNormalized(self, arg0: int, arg1: int) -> None: ...
    def multiply(self, arg0: "Matrix4f") -> None: ...
    def rotate(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def scale(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def translate(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def inverse(self) -> bool: ...
    def inverseTranspose(self) -> bool: ...
    def transpose(self) -> None: ...
