from typing import Any, ClassVar, overload
from android.renderscript.Allocation import Allocation
from android.renderscript.BaseObj import BaseObj
from android.renderscript.Element import Element
from android.renderscript.FieldPacker import FieldPacker
from android.renderscript.RenderScript import RenderScript
from android.renderscript.Type import Type

class Script:
    def createKernelID(self, arg0: int, arg1: int, arg2: Element, arg3: Element) -> "KernelID": ...
    def createInvokeID(self, arg0: int) -> "InvokeID": ...
    def createFieldID(self, arg0: int, arg1: Element) -> "FieldID": ...
    @overload
    def invoke(self, arg0: int) -> None: ...
    @overload
    def invoke(self, arg0: int, arg1: FieldPacker) -> None: ...
    @overload
    def forEach(self, arg0: int, arg1: Allocation, arg2: Allocation, arg3: FieldPacker) -> None: ...
    @overload
    def forEach(self, arg0: int, arg1: Allocation, arg2: Allocation, arg3: FieldPacker, arg4: "LaunchOptions") -> None: ...
    @overload
    def forEach(self, arg0: int, arg1: list[Allocation], arg2: Allocation, arg3: FieldPacker) -> None: ...
    @overload
    def forEach(self, arg0: int, arg1: list[Allocation], arg2: Allocation, arg3: FieldPacker, arg4: "LaunchOptions") -> None: ...
    def reduce(self, arg0: int, arg1: list[Allocation], arg2: Allocation, arg3: "LaunchOptions") -> None: ...
    def bindAllocation(self, arg0: Allocation, arg1: int) -> None: ...
    @overload
    def setVar(self, arg0: int, arg1: float) -> None: ...
    @overload
    def setVar(self, arg0: int, arg1: float) -> None: ...
    @overload
    def setVar(self, arg0: int, arg1: int) -> None: ...
    @overload
    def setVar(self, arg0: int, arg1: int) -> None: ...
    @overload
    def setVar(self, arg0: int, arg1: bool) -> None: ...
    @overload
    def setVar(self, arg0: int, arg1: BaseObj) -> None: ...
    @overload
    def setVar(self, arg0: int, arg1: FieldPacker) -> None: ...
    @overload
    def setVar(self, arg0: int, arg1: FieldPacker, arg2: Element, arg3: list[int]) -> None: ...
    def getVarF(self, arg0: int) -> float: ...
    def getVarD(self, arg0: int) -> float: ...
    def getVarI(self, arg0: int) -> int: ...
    def getVarJ(self, arg0: int) -> int: ...
    def getVarB(self, arg0: int) -> bool: ...
    def getVarV(self, arg0: int, arg1: FieldPacker) -> None: ...
    def setTimeZone(self, arg0: str) -> None: ...

    class Builder:
        ...

    class FieldBase:
        mAllocation: Allocation
        mElement: Element
        def __init__(self) -> None: ...
        @overload
        def init(self, arg0: RenderScript, arg1: int) -> None: ...
        @overload
        def init(self, arg0: RenderScript, arg1: int, arg2: int) -> None: ...
        def getElement(self) -> Element: ...
        def getType(self) -> Type: ...
        def getAllocation(self) -> Allocation: ...
        def updateAllocation(self) -> None: ...

    class FieldID:
        ...

    class InvokeID:
        ...

    class KernelID:
        ...

    class LaunchOptions:
        def __init__(self) -> None: ...
        def setX(self, arg0: int, arg1: int) -> "LaunchOptions": ...
        def setY(self, arg0: int, arg1: int) -> "LaunchOptions": ...
        def setZ(self, arg0: int, arg1: int) -> "LaunchOptions": ...
        def getXStart(self) -> int: ...
        def getXEnd(self) -> int: ...
        def getYStart(self) -> int: ...
        def getYEnd(self) -> int: ...
        def getZStart(self) -> int: ...
        def getZEnd(self) -> int: ...
