from typing import Any, ClassVar, overload
from android.renderscript.Allocation import Allocation
from android.renderscript.Element import Element
from android.renderscript.RenderScript import RenderScript

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class LaunchOptions:
    """Forward declaration for ``android.renderscript.Script.LaunchOptions``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.renderscript.Script.LaunchOptions')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/renderscript/Script/LaunchOptions
    """
    ...
class KernelID:
    """Forward declaration for ``android.renderscript.Script.KernelID``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.renderscript.Script.KernelID')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/renderscript/Script/KernelID
    """
    ...

class ScriptIntrinsicBlend:
    @staticmethod
    def create(arg0: RenderScript, arg1: Element) -> "ScriptIntrinsicBlend": ...
    @overload
    def forEachClear(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachClear(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDClear(self) -> KernelID: ...
    @overload
    def forEachSrc(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachSrc(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDSrc(self) -> KernelID: ...
    @overload
    def forEachDst(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachDst(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDDst(self) -> KernelID: ...
    @overload
    def forEachSrcOver(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachSrcOver(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDSrcOver(self) -> KernelID: ...
    @overload
    def forEachDstOver(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachDstOver(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDDstOver(self) -> KernelID: ...
    @overload
    def forEachSrcIn(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachSrcIn(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDSrcIn(self) -> KernelID: ...
    @overload
    def forEachDstIn(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachDstIn(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDDstIn(self) -> KernelID: ...
    @overload
    def forEachSrcOut(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachSrcOut(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDSrcOut(self) -> KernelID: ...
    @overload
    def forEachDstOut(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachDstOut(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDDstOut(self) -> KernelID: ...
    @overload
    def forEachSrcAtop(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachSrcAtop(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDSrcAtop(self) -> KernelID: ...
    @overload
    def forEachDstAtop(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachDstAtop(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDDstAtop(self) -> KernelID: ...
    @overload
    def forEachXor(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachXor(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDXor(self) -> KernelID: ...
    @overload
    def forEachMultiply(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachMultiply(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDMultiply(self) -> KernelID: ...
    @overload
    def forEachAdd(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachAdd(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDAdd(self) -> KernelID: ...
    @overload
    def forEachSubtract(self, arg0: Allocation, arg1: Allocation) -> None: ...
    @overload
    def forEachSubtract(self, arg0: Allocation, arg1: Allocation, arg2: LaunchOptions) -> None: ...
    def getKernelIDSubtract(self) -> KernelID: ...
