from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.nio.CharBuffer import CharBuffer
from java.nio.charset.Charset import Charset
from java.nio.charset.CoderResult import CoderResult
from java.nio.charset.CodingErrorAction import CodingErrorAction

class CharsetDecoder:
    def __init__(self, arg0: Charset, arg1: float, arg2: float) -> None: ...
    def charset(self) -> Charset: ...
    def replacement(self) -> str: ...
    def replaceWith(self, arg0: str) -> "CharsetDecoder": ...
    def implReplaceWith(self, arg0: str) -> None: ...
    def malformedInputAction(self) -> CodingErrorAction: ...
    def onMalformedInput(self, arg0: CodingErrorAction) -> "CharsetDecoder": ...
    def implOnMalformedInput(self, arg0: CodingErrorAction) -> None: ...
    def unmappableCharacterAction(self) -> CodingErrorAction: ...
    def onUnmappableCharacter(self, arg0: CodingErrorAction) -> "CharsetDecoder": ...
    def implOnUnmappableCharacter(self, arg0: CodingErrorAction) -> None: ...
    def averageCharsPerByte(self) -> float: ...
    def maxCharsPerByte(self) -> float: ...
    @overload
    def decode(self, arg0: ByteBuffer, arg1: CharBuffer, arg2: bool) -> CoderResult: ...
    @overload
    def decode(self, arg0: ByteBuffer) -> CharBuffer: ...
    def flush(self, arg0: CharBuffer) -> CoderResult: ...
    def implFlush(self, arg0: CharBuffer) -> CoderResult: ...
    def reset(self) -> "CharsetDecoder": ...
    def implReset(self) -> None: ...
    def decodeLoop(self, arg0: ByteBuffer, arg1: CharBuffer) -> CoderResult: ...
    def isAutoDetecting(self) -> bool: ...
    def isCharsetDetected(self) -> bool: ...
    def detectedCharset(self) -> Charset: ...
