from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.nio.CharBuffer import CharBuffer
from java.nio.charset.CharsetDecoder import CharsetDecoder
from java.nio.charset.CharsetEncoder import CharsetEncoder
from java.util.Locale import Locale
from java.util.SortedMap import SortedMap

class Charset:
    def __init__(self, arg0: str, arg1: list[str]) -> None: ...
    @staticmethod
    def isSupported(arg0: str) -> bool: ...
    @staticmethod
    def forName(arg0: str) -> "Charset": ...
    @staticmethod
    def availableCharsets() -> SortedMap: ...
    @staticmethod
    def defaultCharset() -> "Charset": ...
    def name(self) -> str: ...
    def aliases(self) -> set: ...
    @overload
    def displayName(self) -> str: ...
    @overload
    def displayName(self, arg0: Locale) -> str: ...
    def isRegistered(self) -> bool: ...
    def contains(self, arg0: "Charset") -> bool: ...
    def newDecoder(self) -> CharsetDecoder: ...
    def newEncoder(self) -> CharsetEncoder: ...
    def canEncode(self) -> bool: ...
    def decode(self, arg0: ByteBuffer) -> CharBuffer: ...
    @overload
    def encode(self, arg0: CharBuffer) -> ByteBuffer: ...
    @overload
    def encode(self, arg0: str) -> ByteBuffer: ...
    def compareTo(self, arg0: "Charset") -> int: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
