from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.nio.CharBuffer import CharBuffer
from java.nio.charset.Charset import Charset
from java.nio.charset.CoderResult import CoderResult
from java.nio.charset.CodingErrorAction import CodingErrorAction

class CharsetEncoder:
    @overload
    def __init__(self, arg0: Charset, arg1: float, arg2: float, arg3: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: Charset, arg1: float, arg2: float) -> None: ...
    def charset(self) -> Charset: ...
    def replacement(self) -> list[int]: ...
    def replaceWith(self, arg0: list[int]) -> "CharsetEncoder": ...
    def implReplaceWith(self, arg0: list[int]) -> None: ...
    def isLegalReplacement(self, arg0: list[int]) -> bool: ...
    def malformedInputAction(self) -> CodingErrorAction: ...
    def onMalformedInput(self, arg0: CodingErrorAction) -> "CharsetEncoder": ...
    def implOnMalformedInput(self, arg0: CodingErrorAction) -> None: ...
    def unmappableCharacterAction(self) -> CodingErrorAction: ...
    def onUnmappableCharacter(self, arg0: CodingErrorAction) -> "CharsetEncoder": ...
    def implOnUnmappableCharacter(self, arg0: CodingErrorAction) -> None: ...
    def averageBytesPerChar(self) -> float: ...
    def maxBytesPerChar(self) -> float: ...
    @overload
    def encode(self, arg0: CharBuffer, arg1: ByteBuffer, arg2: bool) -> CoderResult: ...
    @overload
    def encode(self, arg0: CharBuffer) -> ByteBuffer: ...
    def flush(self, arg0: ByteBuffer) -> CoderResult: ...
    def implFlush(self, arg0: ByteBuffer) -> CoderResult: ...
    def reset(self) -> "CharsetEncoder": ...
    def implReset(self) -> None: ...
    def encodeLoop(self, arg0: CharBuffer, arg1: ByteBuffer) -> CoderResult: ...
    @overload
    def canEncode(self, arg0: str) -> bool: ...
    @overload
    def canEncode(self, arg0: str) -> bool: ...
