from typing import Any, ClassVar, overload

class UnmappableCharacterException:
    def __init__(self, arg0: int) -> None: ...
    def getInputLength(self) -> int: ...
    def getMessage(self) -> str: ...
