from typing import Any, ClassVar, overload
from android.gms.ads.preload.PreloadCallbackV2 import PreloadCallbackV2
from android.gms.ads.preload.PreloadConfiguration import PreloadConfiguration
from android.gms.ads.rewarded.RewardedAd import RewardedAd

class RewardedAdPreloader:
    @overload
    @staticmethod
    def start(arg0: str, arg1: PreloadConfiguration, arg2: PreloadCallbackV2) -> bool: ...
    @overload
    @staticmethod
    def start(arg0: str, arg1: PreloadConfiguration) -> bool: ...
    @staticmethod
    def isAdAvailable(arg0: str) -> bool: ...
    @staticmethod
    def getNumAdsAvailable(arg0: str) -> int: ...
    @staticmethod
    def destroy(arg0: str) -> bool: ...
    @staticmethod
    def destroyAll() -> None: ...
    @staticmethod
    def getConfigurations() -> dict: ...
    @staticmethod
    def getConfiguration(arg0: str) -> PreloadConfiguration: ...
    @staticmethod
    def pollAd(arg0: str) -> RewardedAd: ...
