from typing import Any, ClassVar, overload

class ServerSideVerificationOptions:
    def getUserId(self) -> str: ...
    def getCustomData(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setUserId(self, arg0: str) -> "Builder": ...
        def setCustomData(self, arg0: str) -> "Builder": ...
        def build(self) -> "ServerSideVerificationOptions": ...
