from typing import Any, ClassVar, overload
from java.security.ProtectionDomain import ProtectionDomain
from javax.security.auth.Subject import Subject

class SubjectDomainCombiner:
    def __init__(self, arg0: Subject) -> None: ...
    def getSubject(self) -> Subject: ...
    def combine(self, arg0: list[ProtectionDomain], arg1: list[ProtectionDomain]) -> list[ProtectionDomain]: ...
