from typing import Any, ClassVar, overload
from java.security.AccessControlContext import AccessControlContext
from java.security.PrivilegedAction import PrivilegedAction
from java.security.PrivilegedExceptionAction import PrivilegedExceptionAction

class Subject:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: bool, arg1: set, arg2: set, arg3: set) -> None: ...
    def setReadOnly(self) -> None: ...
    def isReadOnly(self) -> bool: ...
    @staticmethod
    def getSubject(arg0: AccessControlContext) -> "Subject": ...
    @overload
    @staticmethod
    def doAs(arg0: "Subject", arg1: PrivilegedAction) -> Any: ...
    @overload
    @staticmethod
    def doAs(arg0: "Subject", arg1: PrivilegedExceptionAction) -> Any: ...
    @overload
    @staticmethod
    def doAsPrivileged(arg0: "Subject", arg1: PrivilegedAction, arg2: AccessControlContext) -> Any: ...
    @overload
    @staticmethod
    def doAsPrivileged(arg0: "Subject", arg1: PrivilegedExceptionAction, arg2: AccessControlContext) -> Any: ...
    @overload
    def getPrincipals(self) -> set: ...
    @overload
    def getPrincipals(self, arg0: type) -> set: ...
    @overload
    def getPublicCredentials(self) -> set: ...
    @overload
    def getPublicCredentials(self, arg0: type) -> set: ...
    @overload
    def getPrivateCredentials(self) -> set: ...
    @overload
    def getPrivateCredentials(self, arg0: type) -> set: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
