from typing import Any, ClassVar, overload
from java.io.File import File
from java.lang.ClassLoader import ClassLoader
from java.lang.Package import Package
from java.net.URL import URL
from java.util.Enumeration import Enumeration

class BaseDexClassLoader:
    def __init__(self, arg0: str, arg1: File, arg2: str, arg3: ClassLoader) -> None: ...
    def findClass(self, arg0: str) -> type: ...
    def findResource(self, arg0: str) -> URL: ...
    def findResources(self, arg0: str) -> Enumeration: ...
    def findLibrary(self, arg0: str) -> str: ...
    def getPackage(self, arg0: str) -> Package: ...
    def toString(self) -> str: ...
