from typing import Any, ClassVar, overload
from android.icu.text.ConstrainedFieldPosition import ConstrainedFieldPosition
from android.icu.util.MeasureUnit import MeasureUnit
from java.lang.Appendable import Appendable
from java.math.BigDecimal import BigDecimal
from java.text.AttributedCharacterIterator import AttributedCharacterIterator

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class NounClass:
    """Forward declaration for ``android.icu.text.DisplayOptions.NounClass``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.icu.text.DisplayOptions.NounClass')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/icu/text/DisplayOptions/NounClass
    """
    ...

class FormattedNumber:
    def toString(self) -> str: ...
    def length(self) -> int: ...
    def charAt(self, arg0: int) -> str: ...
    def subSequence(self, arg0: int, arg1: int) -> str: ...
    def appendTo(self, arg0: Appendable) -> Appendable: ...
    def nextPosition(self, arg0: ConstrainedFieldPosition) -> bool: ...
    def toCharacterIterator(self) -> AttributedCharacterIterator: ...
    def toBigDecimal(self) -> BigDecimal: ...
    def getOutputUnit(self) -> MeasureUnit: ...
    def getNounClass(self) -> NounClass: ...
