from typing import Any, ClassVar, overload
from android.gms.ads.VersionInfo import VersionInfo
from android.gms.ads.mediation.InitializationCompleteCallback import InitializationCompleteCallback
from android.gms.ads.mediation.MediationAdLoadCallback import MediationAdLoadCallback
from android.gms.ads.mediation.MediationAppOpenAdConfiguration import MediationAppOpenAdConfiguration
from android.gms.ads.mediation.MediationBannerAdConfiguration import MediationBannerAdConfiguration
from android.gms.ads.mediation.MediationInterstitialAdConfiguration import MediationInterstitialAdConfiguration
from android.gms.ads.mediation.MediationNativeAdConfiguration import MediationNativeAdConfiguration
from android.gms.ads.mediation.MediationRewardedAdConfiguration import MediationRewardedAdConfiguration

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context

class Adapter:
    def __init__(self) -> None: ...
    def loadBannerAd(self, arg0: MediationBannerAdConfiguration, arg1: MediationAdLoadCallback) -> None: ...
    def loadInterstitialAd(self, arg0: MediationInterstitialAdConfiguration, arg1: MediationAdLoadCallback) -> None: ...
    def loadRewardedAd(self, arg0: MediationRewardedAdConfiguration, arg1: MediationAdLoadCallback) -> None: ...
    def loadRewardedInterstitialAd(self, arg0: MediationRewardedAdConfiguration, arg1: MediationAdLoadCallback) -> None: ...
    def loadNativeAd(self, arg0: MediationNativeAdConfiguration, arg1: MediationAdLoadCallback) -> None: ...
    def loadNativeAdMapper(self, arg0: MediationNativeAdConfiguration, arg1: MediationAdLoadCallback) -> None: ...
    def loadAppOpenAd(self, arg0: MediationAppOpenAdConfiguration, arg1: MediationAdLoadCallback) -> None: ...
    def initialize(self, arg0: Context, arg1: InitializationCompleteCallback, arg2: list) -> None: ...
    def getVersionInfo(self) -> VersionInfo: ...
    def getSDKVersionInfo(self) -> VersionInfo: ...
