from typing import Any, ClassVar, overload

class MediationNativeAdCallback:
    def onAdLeftApplication(self) -> None: ...
    def onVideoPause(self) -> None: ...
    def onVideoPlay(self) -> None: ...
    def onVideoComplete(self) -> None: ...
    def onVideoMute(self) -> None: ...
    def onVideoUnmute(self) -> None: ...
