from typing import Any, ClassVar, overload

class MediationBannerAdapter:
    def requestBannerAd(self, arg0: "Context", arg1: "MediationBannerListener", arg2: "Bundle", arg3: "AdSize", arg4: "MediationAdRequest", arg5: "Bundle") -> None: ...
    def getBannerView(self) -> "View": ...
