from typing import Any, ClassVar, overload

class MediationBannerListener:
    def onAdLoaded(self, arg0: "MediationBannerAdapter") -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: "MediationBannerAdapter", arg1: int) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: "MediationBannerAdapter", arg1: "AdError") -> None: ...
    def onAdOpened(self, arg0: "MediationBannerAdapter") -> None: ...
    def onAdClosed(self, arg0: "MediationBannerAdapter") -> None: ...
    def onAdLeftApplication(self, arg0: "MediationBannerAdapter") -> None: ...
    def onAdClicked(self, arg0: "MediationBannerAdapter") -> None: ...
    def zza(self, arg0: "MediationBannerAdapter", arg1: str, arg2: str) -> None: ...
