from typing import Any, ClassVar, overload

class MediationInterstitialAdapter:
    def requestInterstitialAd(self, arg0: "Context", arg1: "MediationInterstitialListener", arg2: "Bundle", arg3: "MediationAdRequest", arg4: "Bundle") -> None: ...
    def showInterstitial(self) -> None: ...
