from typing import Any, ClassVar, overload
from android.gms.ads.AdError import AdError
from android.gms.ads.mediation.MediationNativeAdapter import MediationNativeAdapter
from android.gms.ads.mediation.UnifiedNativeAdMapper import UnifiedNativeAdMapper
from android.gms.internal.ads.zzbnd import zzbnd

class MediationNativeListener:
    def onAdLoaded(self, arg0: MediationNativeAdapter, arg1: UnifiedNativeAdMapper) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: MediationNativeAdapter, arg1: int) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: MediationNativeAdapter, arg1: AdError) -> None: ...
    def onAdOpened(self, arg0: MediationNativeAdapter) -> None: ...
    def onAdClosed(self, arg0: MediationNativeAdapter) -> None: ...
    def onAdLeftApplication(self, arg0: MediationNativeAdapter) -> None: ...
    def onAdClicked(self, arg0: MediationNativeAdapter) -> None: ...
    def onAdImpression(self, arg0: MediationNativeAdapter) -> None: ...
    def onVideoEnd(self, arg0: MediationNativeAdapter) -> None: ...
    def zzc(self, arg0: MediationNativeAdapter, arg1: zzbnd) -> None: ...
    def zzd(self, arg0: MediationNativeAdapter, arg1: zzbnd, arg2: str) -> None: ...
