from typing import Any, ClassVar, overload

class MediationInterstitialListener:
    def onAdLoaded(self, arg0: "MediationInterstitialAdapter") -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: "MediationInterstitialAdapter", arg1: int) -> None: ...
    @overload
    def onAdFailedToLoad(self, arg0: "MediationInterstitialAdapter", arg1: "AdError") -> None: ...
    def onAdOpened(self, arg0: "MediationInterstitialAdapter") -> None: ...
    def onAdClosed(self, arg0: "MediationInterstitialAdapter") -> None: ...
    def onAdLeftApplication(self, arg0: "MediationInterstitialAdapter") -> None: ...
    def onAdClicked(self, arg0: "MediationInterstitialAdapter") -> None: ...
