from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Image:
    """Forward declaration for ``com.google.android.gms.ads.nativead.NativeAd.Image``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.ads.nativead.NativeAd.Image')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/ads/nativead/NativeAd/Image
    """
    ...
class View:
    """Forward declaration for ``android.view.View``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.View')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/View
    """
    ...
class Bundle:
    """Forward declaration for ``android.os.Bundle``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Bundle')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Bundle
    """
    ...

class NativeAdMapper:
    def __init__(self) -> None: ...
    def setHeadline(self, arg0: str) -> None: ...
    def setImages(self, arg0: list) -> None: ...
    def setBody(self, arg0: str) -> None: ...
    def setIcon(self, arg0: Image) -> None: ...
    def setCallToAction(self, arg0: str) -> None: ...
    def setAdvertiser(self, arg0: str) -> None: ...
    def setStarRating(self, arg0: float) -> None: ...
    def setStore(self, arg0: str) -> None: ...
    def setPrice(self, arg0: str) -> None: ...
    def setHasVideoContent(self, arg0: bool) -> None: ...
    def setAdChoicesContent(self, arg0: View) -> None: ...
    def setMediaView(self, arg0: View) -> None: ...
    def setMediaContentAspectRatio(self, arg0: float) -> None: ...
    def setExtras(self, arg0: Bundle) -> None: ...
    def setOverrideImpressionRecording(self, arg0: bool) -> None: ...
    def setOverrideClickHandling(self, arg0: bool) -> None: ...
    def getHeadline(self) -> str: ...
    def getImages(self) -> list: ...
    def getBody(self) -> str: ...
    def getIcon(self) -> Image: ...
    def getCallToAction(self) -> str: ...
    def getAdvertiser(self) -> str: ...
    def getStarRating(self) -> float: ...
    def getStore(self) -> str: ...
    def getPrice(self) -> str: ...
    def hasVideoContent(self) -> bool: ...
    def getAdChoicesContent(self) -> View: ...
    def getMediaContentAspectRatio(self) -> float: ...
    def getDuration(self) -> float: ...
    def getCurrentTime(self) -> float: ...
    def getExtras(self) -> Bundle: ...
    def getOverrideImpressionRecording(self) -> bool: ...
    def getOverrideClickHandling(self) -> bool: ...
    def recordImpression(self) -> None: ...
    def handleClick(self, arg0: View) -> None: ...
    def trackViews(self, arg0: View, arg1: dict, arg2: dict) -> None: ...
    def untrackView(self, arg0: View) -> None: ...
    def destroy(self) -> None: ...
    def zza(self) -> View: ...
