from typing import Any, ClassVar, overload
from android.gms.ads.formats.NativeAdOptions import NativeAdOptions
from android.gms.ads.nativead.NativeAdOptions import NativeAdOptions

class NativeMediationAdRequest:
    def getNativeAdOptions(self) -> NativeAdOptions: ...
    def getNativeAdRequestOptions(self) -> NativeAdOptions: ...
    def isUnifiedNativeAdRequested(self) -> bool: ...
    def isAdMuted(self) -> bool: ...
    def getAdVolume(self) -> float: ...
    def zza(self) -> bool: ...
    def zzb(self) -> dict: ...
