from typing import Any, ClassVar, overload
from android.se.omapi.Session import Session

class Channel:
    def close(self) -> None: ...
    def isOpen(self) -> bool: ...
    def isBasicChannel(self) -> bool: ...
    def transmit(self, arg0: list[int]) -> list[int]: ...
    def getSession(self) -> Session: ...
    def getSelectResponse(self) -> list[int]: ...
    def selectNext(self) -> bool: ...
