from typing import Any, ClassVar, overload
from android.se.omapi.Channel import Channel
from android.se.omapi.Reader import Reader

class Session:
    def getReader(self) -> Reader: ...
    def getATR(self) -> list[int]: ...
    def close(self) -> None: ...
    def isClosed(self) -> bool: ...
    def closeChannels(self) -> None: ...
    @overload
    def openBasicChannel(self, arg0: list[int], arg1: int) -> Channel: ...
    @overload
    def openBasicChannel(self, arg0: list[int]) -> Channel: ...
    @overload
    def openLogicalChannel(self, arg0: list[int], arg1: int) -> Channel: ...
    @overload
    def openLogicalChannel(self, arg0: list[int]) -> Channel: ...
