from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.os.SharedMemory import SharedMemory

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AdBuffer:
    CREATOR: ClassVar[Creator]
    def __init__(self, arg0: int, arg1: str, arg2: SharedMemory, arg3: int, arg4: int, arg5: int, arg6: int) -> None: ...
    def getId(self) -> int: ...
    def getMimeType(self) -> str: ...
    def getSharedMemory(self) -> SharedMemory: ...
    def getOffset(self) -> int: ...
    def getLength(self) -> int: ...
    def getPresentationTimeUs(self) -> int: ...
    def getFlags(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
