from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.net.Uri import Uri

class TvContract:
    ACTION_INITIALIZE_PROGRAMS: ClassVar[str]
    ACTION_PREVIEW_PROGRAM_ADDED_TO_WATCH_NEXT: ClassVar[str]
    ACTION_PREVIEW_PROGRAM_BROWSABLE_DISABLED: ClassVar[str]
    ACTION_REQUEST_CHANNEL_BROWSABLE: ClassVar[str]
    ACTION_WATCH_NEXT_PROGRAM_BROWSABLE_DISABLED: ClassVar[str]
    AUTHORITY: ClassVar[str]
    EXTRA_CHANNEL_ID: ClassVar[str]
    EXTRA_PREVIEW_PROGRAM_ID: ClassVar[str]
    EXTRA_WATCH_NEXT_PROGRAM_ID: ClassVar[str]
    @staticmethod
    def buildInputId(arg0: ComponentName) -> str: ...
    @staticmethod
    def buildChannelUri(arg0: int) -> Uri: ...
    @staticmethod
    def buildChannelUriForPassthroughInput(arg0: str) -> Uri: ...
    @overload
    @staticmethod
    def buildChannelLogoUri(arg0: int) -> Uri: ...
    @overload
    @staticmethod
    def buildChannelLogoUri(arg0: Uri) -> Uri: ...
    @staticmethod
    def buildChannelsUriForInput(arg0: str) -> Uri: ...
    @staticmethod
    def buildProgramUri(arg0: int) -> Uri: ...
    @overload
    @staticmethod
    def buildProgramsUriForChannel(arg0: int) -> Uri: ...
    @overload
    @staticmethod
    def buildProgramsUriForChannel(arg0: Uri) -> Uri: ...
    @overload
    @staticmethod
    def buildProgramsUriForChannel(arg0: int, arg1: int, arg2: int) -> Uri: ...
    @overload
    @staticmethod
    def buildProgramsUriForChannel(arg0: Uri, arg1: int, arg2: int) -> Uri: ...
    @staticmethod
    def buildRecordedProgramUri(arg0: int) -> Uri: ...
    @staticmethod
    def buildPreviewProgramUri(arg0: int) -> Uri: ...
    @overload
    @staticmethod
    def buildPreviewProgramsUriForChannel(arg0: int) -> Uri: ...
    @overload
    @staticmethod
    def buildPreviewProgramsUriForChannel(arg0: Uri) -> Uri: ...
    @staticmethod
    def buildWatchNextProgramUri(arg0: int) -> Uri: ...
    @staticmethod
    def isChannelUri(arg0: Uri) -> bool: ...
    @staticmethod
    def isChannelUriForTunerInput(arg0: Uri) -> bool: ...
    @staticmethod
    def isChannelUriForPassthroughInput(arg0: Uri) -> bool: ...
    @staticmethod
    def isProgramUri(arg0: Uri) -> bool: ...
    @staticmethod
    def isRecordedProgramUri(arg0: Uri) -> bool: ...
    @staticmethod
    def requestChannelBrowsable(arg0: Context, arg1: int) -> None: ...

    class BaseTvColumns:
        COLUMN_PACKAGE_NAME: ClassVar[str]

    class Channels:
        COLUMN_APP_LINK_COLOR: ClassVar[str]
        COLUMN_APP_LINK_ICON_URI: ClassVar[str]
        COLUMN_APP_LINK_INTENT_URI: ClassVar[str]
        COLUMN_APP_LINK_POSTER_ART_URI: ClassVar[str]
        COLUMN_APP_LINK_TEXT: ClassVar[str]
        COLUMN_BROADCAST_GENRE: ClassVar[str]
        COLUMN_BROWSABLE: ClassVar[str]
        COLUMN_CHANNEL_LIST_ID: ClassVar[str]
        COLUMN_DESCRIPTION: ClassVar[str]
        COLUMN_DISPLAY_NAME: ClassVar[str]
        COLUMN_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_GLOBAL_CONTENT_ID: ClassVar[str]
        COLUMN_INPUT_ID: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_DATA: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG1: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG2: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG3: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG4: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_ID: ClassVar[str]
        COLUMN_LOCKED: ClassVar[str]
        COLUMN_NETWORK_AFFILIATION: ClassVar[str]
        COLUMN_ORIGINAL_NETWORK_ID: ClassVar[str]
        COLUMN_REMOTE_CONTROL_KEY_PRESET_NUMBER: ClassVar[str]
        COLUMN_SCRAMBLED: ClassVar[str]
        COLUMN_SEARCHABLE: ClassVar[str]
        COLUMN_SERVICE_ID: ClassVar[str]
        COLUMN_SERVICE_TYPE: ClassVar[str]
        COLUMN_TRANSIENT: ClassVar[str]
        COLUMN_TRANSPORT_STREAM_ID: ClassVar[str]
        COLUMN_TYPE: ClassVar[str]
        COLUMN_VERSION_NUMBER: ClassVar[str]
        COLUMN_VIDEO_FORMAT: ClassVar[str]
        COLUMN_VIDEO_RESOLUTION: ClassVar[str]
        CONTENT_ITEM_TYPE: ClassVar[str]
        CONTENT_TYPE: ClassVar[str]
        CONTENT_URI: ClassVar[Uri]
        SERVICE_TYPE_AUDIO: ClassVar[str]
        SERVICE_TYPE_AUDIO_VIDEO: ClassVar[str]
        SERVICE_TYPE_OTHER: ClassVar[str]
        TYPE_1SEG: ClassVar[str]
        TYPE_ATSC3_T: ClassVar[str]
        TYPE_ATSC_C: ClassVar[str]
        TYPE_ATSC_M_H: ClassVar[str]
        TYPE_ATSC_T: ClassVar[str]
        TYPE_CMMB: ClassVar[str]
        TYPE_DTMB: ClassVar[str]
        TYPE_DVB_C: ClassVar[str]
        TYPE_DVB_C2: ClassVar[str]
        TYPE_DVB_H: ClassVar[str]
        TYPE_DVB_S: ClassVar[str]
        TYPE_DVB_S2: ClassVar[str]
        TYPE_DVB_SH: ClassVar[str]
        TYPE_DVB_T: ClassVar[str]
        TYPE_DVB_T2: ClassVar[str]
        TYPE_ISDB_C: ClassVar[str]
        TYPE_ISDB_S: ClassVar[str]
        TYPE_ISDB_S3: ClassVar[str]
        TYPE_ISDB_T: ClassVar[str]
        TYPE_ISDB_TB: ClassVar[str]
        TYPE_NTSC: ClassVar[str]
        TYPE_OTHER: ClassVar[str]
        TYPE_PAL: ClassVar[str]
        TYPE_PREVIEW: ClassVar[str]
        TYPE_SECAM: ClassVar[str]
        TYPE_S_DMB: ClassVar[str]
        TYPE_T_DMB: ClassVar[str]
        VIDEO_FORMAT_1080I: ClassVar[str]
        VIDEO_FORMAT_1080P: ClassVar[str]
        VIDEO_FORMAT_2160P: ClassVar[str]
        VIDEO_FORMAT_240P: ClassVar[str]
        VIDEO_FORMAT_360P: ClassVar[str]
        VIDEO_FORMAT_4320P: ClassVar[str]
        VIDEO_FORMAT_480I: ClassVar[str]
        VIDEO_FORMAT_480P: ClassVar[str]
        VIDEO_FORMAT_576I: ClassVar[str]
        VIDEO_FORMAT_576P: ClassVar[str]
        VIDEO_FORMAT_720P: ClassVar[str]
        VIDEO_RESOLUTION_ED: ClassVar[str]
        VIDEO_RESOLUTION_FHD: ClassVar[str]
        VIDEO_RESOLUTION_HD: ClassVar[str]
        VIDEO_RESOLUTION_SD: ClassVar[str]
        VIDEO_RESOLUTION_UHD: ClassVar[str]
        @staticmethod
        def getVideoResolution(arg0: str) -> str: ...

        class Logo:
            CONTENT_DIRECTORY: ClassVar[str]

    class PreviewPrograms:
        ASPECT_RATIO_16_9: ClassVar[int]
        ASPECT_RATIO_1_1: ClassVar[int]
        ASPECT_RATIO_2_3: ClassVar[int]
        ASPECT_RATIO_3_2: ClassVar[int]
        ASPECT_RATIO_4_3: ClassVar[int]
        AVAILABILITY_AVAILABLE: ClassVar[int]
        AVAILABILITY_FREE_WITH_SUBSCRIPTION: ClassVar[int]
        AVAILABILITY_PAID_CONTENT: ClassVar[int]
        COLUMN_AUDIO_LANGUAGE: ClassVar[str]
        COLUMN_AUTHOR: ClassVar[str]
        COLUMN_AVAILABILITY: ClassVar[str]
        COLUMN_BROWSABLE: ClassVar[str]
        COLUMN_CANONICAL_GENRE: ClassVar[str]
        COLUMN_CHANNEL_ID: ClassVar[str]
        COLUMN_CONTENT_ID: ClassVar[str]
        COLUMN_CONTENT_RATING: ClassVar[str]
        COLUMN_DURATION_MILLIS: ClassVar[str]
        COLUMN_END_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_EPISODE_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_EPISODE_TITLE: ClassVar[str]
        COLUMN_INTENT_URI: ClassVar[str]
        COLUMN_INTERACTION_COUNT: ClassVar[str]
        COLUMN_INTERACTION_TYPE: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_DATA: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG1: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG2: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG3: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG4: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_ID: ClassVar[str]
        COLUMN_ITEM_COUNT: ClassVar[str]
        COLUMN_LAST_PLAYBACK_POSITION_MILLIS: ClassVar[str]
        COLUMN_LIVE: ClassVar[str]
        COLUMN_LOGO_URI: ClassVar[str]
        COLUMN_LONG_DESCRIPTION: ClassVar[str]
        COLUMN_OFFER_PRICE: ClassVar[str]
        COLUMN_POSTER_ART_ASPECT_RATIO: ClassVar[str]
        COLUMN_POSTER_ART_URI: ClassVar[str]
        COLUMN_PREVIEW_VIDEO_URI: ClassVar[str]
        COLUMN_RELEASE_DATE: ClassVar[str]
        COLUMN_REVIEW_RATING: ClassVar[str]
        COLUMN_REVIEW_RATING_STYLE: ClassVar[str]
        COLUMN_SEARCHABLE: ClassVar[str]
        COLUMN_SEASON_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_SEASON_TITLE: ClassVar[str]
        COLUMN_SERIES_ID: ClassVar[str]
        COLUMN_SHORT_DESCRIPTION: ClassVar[str]
        COLUMN_SPLIT_ID: ClassVar[str]
        COLUMN_STARTING_PRICE: ClassVar[str]
        COLUMN_START_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_THUMBNAIL_ASPECT_RATIO: ClassVar[str]
        COLUMN_THUMBNAIL_URI: ClassVar[str]
        COLUMN_TITLE: ClassVar[str]
        COLUMN_TRANSIENT: ClassVar[str]
        COLUMN_TYPE: ClassVar[str]
        COLUMN_VERSION_NUMBER: ClassVar[str]
        COLUMN_VIDEO_HEIGHT: ClassVar[str]
        COLUMN_VIDEO_WIDTH: ClassVar[str]
        COLUMN_WEIGHT: ClassVar[str]
        CONTENT_ITEM_TYPE: ClassVar[str]
        CONTENT_TYPE: ClassVar[str]
        CONTENT_URI: ClassVar[Uri]
        INTERACTION_TYPE_FANS: ClassVar[int]
        INTERACTION_TYPE_FOLLOWERS: ClassVar[int]
        INTERACTION_TYPE_LIKES: ClassVar[int]
        INTERACTION_TYPE_LISTENS: ClassVar[int]
        INTERACTION_TYPE_THUMBS: ClassVar[int]
        INTERACTION_TYPE_VIEWERS: ClassVar[int]
        INTERACTION_TYPE_VIEWS: ClassVar[int]
        REVIEW_RATING_STYLE_PERCENTAGE: ClassVar[int]
        REVIEW_RATING_STYLE_STARS: ClassVar[int]
        REVIEW_RATING_STYLE_THUMBS_UP_DOWN: ClassVar[int]
        TYPE_ALBUM: ClassVar[int]
        TYPE_ARTIST: ClassVar[int]
        TYPE_CHANNEL: ClassVar[int]
        TYPE_CLIP: ClassVar[int]
        TYPE_EVENT: ClassVar[int]
        TYPE_MOVIE: ClassVar[int]
        TYPE_PLAYLIST: ClassVar[int]
        TYPE_STATION: ClassVar[int]
        TYPE_TRACK: ClassVar[int]
        TYPE_TV_EPISODE: ClassVar[int]
        TYPE_TV_SEASON: ClassVar[int]
        TYPE_TV_SERIES: ClassVar[int]

    class Programs:
        COLUMN_AUDIO_LANGUAGE: ClassVar[str]
        COLUMN_BROADCAST_GENRE: ClassVar[str]
        COLUMN_CANONICAL_GENRE: ClassVar[str]
        COLUMN_CHANNEL_ID: ClassVar[str]
        COLUMN_CONTENT_RATING: ClassVar[str]
        COLUMN_END_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_EPISODE_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_EPISODE_NUMBER: ClassVar[str]
        COLUMN_EPISODE_TITLE: ClassVar[str]
        COLUMN_EVENT_ID: ClassVar[str]
        COLUMN_GLOBAL_CONTENT_ID: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_DATA: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG1: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG2: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG3: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG4: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_ID: ClassVar[str]
        COLUMN_LONG_DESCRIPTION: ClassVar[str]
        COLUMN_MULTI_SERIES_ID: ClassVar[str]
        COLUMN_POSTER_ART_URI: ClassVar[str]
        COLUMN_RECORDING_PROHIBITED: ClassVar[str]
        COLUMN_REVIEW_RATING: ClassVar[str]
        COLUMN_REVIEW_RATING_STYLE: ClassVar[str]
        COLUMN_SCRAMBLED: ClassVar[str]
        COLUMN_SEARCHABLE: ClassVar[str]
        COLUMN_SEASON_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_SEASON_NUMBER: ClassVar[str]
        COLUMN_SEASON_TITLE: ClassVar[str]
        COLUMN_SERIES_ID: ClassVar[str]
        COLUMN_SHORT_DESCRIPTION: ClassVar[str]
        COLUMN_SPLIT_ID: ClassVar[str]
        COLUMN_START_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_THUMBNAIL_URI: ClassVar[str]
        COLUMN_TITLE: ClassVar[str]
        COLUMN_VERSION_NUMBER: ClassVar[str]
        COLUMN_VIDEO_HEIGHT: ClassVar[str]
        COLUMN_VIDEO_WIDTH: ClassVar[str]
        CONTENT_ITEM_TYPE: ClassVar[str]
        CONTENT_TYPE: ClassVar[str]
        CONTENT_URI: ClassVar[Uri]
        REVIEW_RATING_STYLE_PERCENTAGE: ClassVar[int]
        REVIEW_RATING_STYLE_STARS: ClassVar[int]
        REVIEW_RATING_STYLE_THUMBS_UP_DOWN: ClassVar[int]

        class Genres:
            ANIMAL_WILDLIFE: ClassVar[str]
            ARTS: ClassVar[str]
            COMEDY: ClassVar[str]
            DRAMA: ClassVar[str]
            EDUCATION: ClassVar[str]
            ENTERTAINMENT: ClassVar[str]
            FAMILY_KIDS: ClassVar[str]
            GAMING: ClassVar[str]
            LIFE_STYLE: ClassVar[str]
            MOVIES: ClassVar[str]
            MUSIC: ClassVar[str]
            NEWS: ClassVar[str]
            PREMIER: ClassVar[str]
            SHOPPING: ClassVar[str]
            SPORTS: ClassVar[str]
            TECH_SCIENCE: ClassVar[str]
            TRAVEL: ClassVar[str]
            @staticmethod
            def encode(*arg0: str) -> str: ...
            @staticmethod
            def decode(arg0: str) -> list[str]: ...
            @staticmethod
            def isCanonical(arg0: str) -> bool: ...

    class RecordedPrograms:
        COLUMN_AUDIO_LANGUAGE: ClassVar[str]
        COLUMN_BROADCAST_GENRE: ClassVar[str]
        COLUMN_CANONICAL_GENRE: ClassVar[str]
        COLUMN_CHANNEL_ID: ClassVar[str]
        COLUMN_CONTENT_RATING: ClassVar[str]
        COLUMN_END_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_EPISODE_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_EPISODE_TITLE: ClassVar[str]
        COLUMN_INPUT_ID: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_DATA: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG1: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG2: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG3: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG4: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_ID: ClassVar[str]
        COLUMN_LONG_DESCRIPTION: ClassVar[str]
        COLUMN_MULTI_SERIES_ID: ClassVar[str]
        COLUMN_POSTER_ART_URI: ClassVar[str]
        COLUMN_RECORDING_DATA_BYTES: ClassVar[str]
        COLUMN_RECORDING_DATA_URI: ClassVar[str]
        COLUMN_RECORDING_DURATION_MILLIS: ClassVar[str]
        COLUMN_RECORDING_EXPIRE_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_REVIEW_RATING: ClassVar[str]
        COLUMN_REVIEW_RATING_STYLE: ClassVar[str]
        COLUMN_SEARCHABLE: ClassVar[str]
        COLUMN_SEASON_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_SEASON_TITLE: ClassVar[str]
        COLUMN_SERIES_ID: ClassVar[str]
        COLUMN_SHORT_DESCRIPTION: ClassVar[str]
        COLUMN_SPLIT_ID: ClassVar[str]
        COLUMN_START_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_THUMBNAIL_URI: ClassVar[str]
        COLUMN_TITLE: ClassVar[str]
        COLUMN_VERSION_NUMBER: ClassVar[str]
        COLUMN_VIDEO_HEIGHT: ClassVar[str]
        COLUMN_VIDEO_WIDTH: ClassVar[str]
        CONTENT_ITEM_TYPE: ClassVar[str]
        CONTENT_TYPE: ClassVar[str]
        CONTENT_URI: ClassVar[Uri]
        REVIEW_RATING_STYLE_PERCENTAGE: ClassVar[int]
        REVIEW_RATING_STYLE_STARS: ClassVar[int]
        REVIEW_RATING_STYLE_THUMBS_UP_DOWN: ClassVar[int]

    class WatchNextPrograms:
        ASPECT_RATIO_16_9: ClassVar[int]
        ASPECT_RATIO_1_1: ClassVar[int]
        ASPECT_RATIO_2_3: ClassVar[int]
        ASPECT_RATIO_3_2: ClassVar[int]
        ASPECT_RATIO_4_3: ClassVar[int]
        AVAILABILITY_AVAILABLE: ClassVar[int]
        AVAILABILITY_FREE_WITH_SUBSCRIPTION: ClassVar[int]
        AVAILABILITY_PAID_CONTENT: ClassVar[int]
        COLUMN_AUDIO_LANGUAGE: ClassVar[str]
        COLUMN_AUTHOR: ClassVar[str]
        COLUMN_AVAILABILITY: ClassVar[str]
        COLUMN_BROWSABLE: ClassVar[str]
        COLUMN_CANONICAL_GENRE: ClassVar[str]
        COLUMN_CONTENT_ID: ClassVar[str]
        COLUMN_CONTENT_RATING: ClassVar[str]
        COLUMN_DURATION_MILLIS: ClassVar[str]
        COLUMN_END_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_EPISODE_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_EPISODE_TITLE: ClassVar[str]
        COLUMN_INTENT_URI: ClassVar[str]
        COLUMN_INTERACTION_COUNT: ClassVar[str]
        COLUMN_INTERACTION_TYPE: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_DATA: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG1: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG2: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG3: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_FLAG4: ClassVar[str]
        COLUMN_INTERNAL_PROVIDER_ID: ClassVar[str]
        COLUMN_ITEM_COUNT: ClassVar[str]
        COLUMN_LAST_ENGAGEMENT_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_LAST_PLAYBACK_POSITION_MILLIS: ClassVar[str]
        COLUMN_LIVE: ClassVar[str]
        COLUMN_LOGO_URI: ClassVar[str]
        COLUMN_LONG_DESCRIPTION: ClassVar[str]
        COLUMN_OFFER_PRICE: ClassVar[str]
        COLUMN_POSTER_ART_ASPECT_RATIO: ClassVar[str]
        COLUMN_POSTER_ART_URI: ClassVar[str]
        COLUMN_PREVIEW_VIDEO_URI: ClassVar[str]
        COLUMN_RELEASE_DATE: ClassVar[str]
        COLUMN_REVIEW_RATING: ClassVar[str]
        COLUMN_REVIEW_RATING_STYLE: ClassVar[str]
        COLUMN_SEARCHABLE: ClassVar[str]
        COLUMN_SEASON_DISPLAY_NUMBER: ClassVar[str]
        COLUMN_SEASON_TITLE: ClassVar[str]
        COLUMN_SERIES_ID: ClassVar[str]
        COLUMN_SHORT_DESCRIPTION: ClassVar[str]
        COLUMN_SPLIT_ID: ClassVar[str]
        COLUMN_STARTING_PRICE: ClassVar[str]
        COLUMN_START_TIME_UTC_MILLIS: ClassVar[str]
        COLUMN_THUMBNAIL_ASPECT_RATIO: ClassVar[str]
        COLUMN_THUMBNAIL_URI: ClassVar[str]
        COLUMN_TITLE: ClassVar[str]
        COLUMN_TRANSIENT: ClassVar[str]
        COLUMN_TYPE: ClassVar[str]
        COLUMN_VERSION_NUMBER: ClassVar[str]
        COLUMN_VIDEO_HEIGHT: ClassVar[str]
        COLUMN_VIDEO_WIDTH: ClassVar[str]
        COLUMN_WATCH_NEXT_TYPE: ClassVar[str]
        CONTENT_ITEM_TYPE: ClassVar[str]
        CONTENT_TYPE: ClassVar[str]
        CONTENT_URI: ClassVar[Uri]
        INTERACTION_TYPE_FANS: ClassVar[int]
        INTERACTION_TYPE_FOLLOWERS: ClassVar[int]
        INTERACTION_TYPE_LIKES: ClassVar[int]
        INTERACTION_TYPE_LISTENS: ClassVar[int]
        INTERACTION_TYPE_THUMBS: ClassVar[int]
        INTERACTION_TYPE_VIEWERS: ClassVar[int]
        INTERACTION_TYPE_VIEWS: ClassVar[int]
        REVIEW_RATING_STYLE_PERCENTAGE: ClassVar[int]
        REVIEW_RATING_STYLE_STARS: ClassVar[int]
        REVIEW_RATING_STYLE_THUMBS_UP_DOWN: ClassVar[int]
        TYPE_ALBUM: ClassVar[int]
        TYPE_ARTIST: ClassVar[int]
        TYPE_CHANNEL: ClassVar[int]
        TYPE_CLIP: ClassVar[int]
        TYPE_EVENT: ClassVar[int]
        TYPE_MOVIE: ClassVar[int]
        TYPE_PLAYLIST: ClassVar[int]
        TYPE_STATION: ClassVar[int]
        TYPE_TRACK: ClassVar[int]
        TYPE_TV_EPISODE: ClassVar[int]
        TYPE_TV_SEASON: ClassVar[int]
        TYPE_TV_SERIES: ClassVar[int]
        WATCH_NEXT_TYPE_CONTINUE: ClassVar[int]
        WATCH_NEXT_TYPE_NEW: ClassVar[int]
        WATCH_NEXT_TYPE_NEXT: ClassVar[int]
        WATCH_NEXT_TYPE_WATCHLIST: ClassVar[int]
