from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["TvInputService"]

class TvInputService(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/tv/TvInputService"
    __javaconstructor__ = [("()V", False)]
    PRIORITY_HINT_USE_CASE_TYPE_BACKGROUND = JavaStaticField("I")
    PRIORITY_HINT_USE_CASE_TYPE_LIVE = JavaStaticField("I")
    PRIORITY_HINT_USE_CASE_TYPE_PLAYBACK = JavaStaticField("I")
    PRIORITY_HINT_USE_CASE_TYPE_RECORD = JavaStaticField("I")
    PRIORITY_HINT_USE_CASE_TYPE_SCAN = JavaStaticField("I")
    SERVICE_INTERFACE = JavaStaticField("Ljava/lang/String;")
    SERVICE_META_DATA = JavaStaticField("Ljava/lang/String;")
    onBind = JavaMethod("(Landroid/content/Intent;)Landroid/os/IBinder;")
    onCreateSession = JavaMultipleMethod([("(Ljava/lang/String;)Landroid/media/tv/TvInputService$Session;", False, False), ("(Ljava/lang/String;Ljava/lang/String;)Landroid/media/tv/TvInputService$Session;", False, False), ("(Ljava/lang/String;Ljava/lang/String;Landroid/content/AttributionSource;)Landroid/media/tv/TvInputService$Session;", False, False)])
    onCreateRecordingSession = JavaMultipleMethod([("(Ljava/lang/String;)Landroid/media/tv/TvInputService$RecordingSession;", False, False), ("(Ljava/lang/String;Ljava/lang/String;)Landroid/media/tv/TvInputService$RecordingSession;", False, False)])

    class HardwareSession(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/tv/TvInputService/HardwareSession"
        __javaconstructor__ = [("(Landroid/content/Context;)V", False)]
        getHardwareInputId = JavaMethod("()Ljava/lang/String;")
        onSetSurface = JavaMethod("(Landroid/view/Surface;)Z")
        onHardwareVideoAvailable = JavaMethod("()V")
        onHardwareVideoUnavailable = JavaMethod("(I)V")

    class RecordingSession(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/tv/TvInputService/RecordingSession"
        __javaconstructor__ = [("(Landroid/content/Context;)V", False)]
        notifyTuned = JavaMethod("(Landroid/net/Uri;)V")
        notifyRecordingStopped = JavaMethod("(Landroid/net/Uri;)V")
        notifyError = JavaMethod("(I)V")
        onTune = JavaMultipleMethod([("(Landroid/net/Uri;)V", False, False), ("(Landroid/net/Uri;Landroid/os/Bundle;)V", False, False)])
        onStartRecording = JavaMultipleMethod([("(Landroid/net/Uri;)V", False, False), ("(Landroid/net/Uri;Landroid/os/Bundle;)V", False, False)])
        onStopRecording = JavaMethod("()V")
        onPauseRecording = JavaMethod("(Landroid/os/Bundle;)V")
        onResumeRecording = JavaMethod("(Landroid/os/Bundle;)V")
        onRelease = JavaMethod("()V")
        onAppPrivateCommand = JavaMethod("(Ljava/lang/String;Landroid/os/Bundle;)V")

    class Session(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/tv/TvInputService/Session"
        __javaconstructor__ = [("(Landroid/content/Context;)V", False)]
        setOverlayViewEnabled = JavaMethod("(Z)V")
        notifyChannelRetuned = JavaMethod("(Landroid/net/Uri;)V")
        notifyTuned = JavaMethod("(Landroid/net/Uri;)V")
        notifyTracksChanged = JavaMethod("(Ljava/util/List;)V")
        notifyTrackSelected = JavaMethod("(ILjava/lang/String;)V")
        notifyVideoAvailable = JavaMethod("()V")
        notifyVideoUnavailable = JavaMethod("(I)V")
        notifyAudioPresentationChanged = JavaMethod("(Ljava/util/List;)V")
        notifyAudioPresentationSelected = JavaMethod("(II)V")
        notifyContentAllowed = JavaMethod("()V")
        notifyContentBlocked = JavaMethod("(Landroid/media/tv/TvContentRating;)V")
        notifyTimeShiftStatusChanged = JavaMethod("(I)V")
        notifyBroadcastInfoResponse = JavaMethod("(Landroid/media/tv/BroadcastInfoResponse;)V")
        notifyAdResponse = JavaMethod("(Landroid/media/tv/AdResponse;)V")
        notifyAdBufferConsumed = JavaMethod("(Landroid/media/tv/AdBuffer;)V")
        notifyTvMessage = JavaMethod("(ILandroid/os/Bundle;)V")
        notifyAitInfoUpdated = JavaMethod("(Landroid/media/tv/AitInfo;)V")
        notifyTimeShiftMode = JavaMethod("(I)V")
        notifyAvailableSpeeds = JavaMethod("([F)V")
        notifySignalStrength = JavaMethod("(I)V")
        notifyCueingMessageAvailability = JavaMethod("(Z)V")
        layoutSurface = JavaMethod("(IIII)V")
        onRelease = JavaMethod("()V")
        onSetSurface = JavaMethod("(Landroid/view/Surface;)Z")
        onSurfaceChanged = JavaMethod("(III)V")
        onOverlayViewSizeChanged = JavaMethod("(II)V")
        onSetStreamVolume = JavaMethod("(F)V")
        onRequestBroadcastInfo = JavaMethod("(Landroid/media/tv/BroadcastInfoRequest;)V")
        onRemoveBroadcastInfo = JavaMethod("(I)V")
        onRequestAd = JavaMethod("(Landroid/media/tv/AdRequest;)V")
        onAdBufferReady = JavaMethod("(Landroid/media/tv/AdBuffer;)V")
        onTune = JavaMultipleMethod([("(Landroid/net/Uri;)Z", False, False), ("(Landroid/net/Uri;Landroid/os/Bundle;)Z", False, False)])
        onSetCaptionEnabled = JavaMethod("(Z)V")
        onUnblockContent = JavaMethod("(Landroid/media/tv/TvContentRating;)V")
        onSelectTrack = JavaMethod("(ILjava/lang/String;)Z")
        onSetInteractiveAppNotificationEnabled = JavaMethod("(Z)V")
        onSelectAudioPresentation = JavaMethod("(II)Z")
        onAppPrivateCommand = JavaMethod("(Ljava/lang/String;Landroid/os/Bundle;)V")
        onCreateOverlayView = JavaMethod("()Landroid/view/View;")
        onSetTvMessageEnabled = JavaMethod("(IZ)V")
        onTvMessage = JavaMethod("(ILandroid/os/Bundle;)V")
        onTimeShiftPlay = JavaMethod("(Landroid/net/Uri;)V")
        onTimeShiftPause = JavaMethod("()V")
        onTimeShiftResume = JavaMethod("()V")
        onTimeShiftSeekTo = JavaMethod("(J)V")
        onTimeShiftSetPlaybackParams = JavaMethod("(Landroid/media/PlaybackParams;)V")
        onTimeShiftSetMode = JavaMethod("(I)V")
        onTimeShiftGetStartPosition = JavaMethod("()J")
        onTimeShiftGetCurrentPosition = JavaMethod("()J")
        onKeyDown = JavaMethod("(ILandroid/view/KeyEvent;)Z")
        onKeyLongPress = JavaMethod("(ILandroid/view/KeyEvent;)Z")
        onKeyMultiple = JavaMethod("(IILandroid/view/KeyEvent;)Z")
        onKeyUp = JavaMethod("(ILandroid/view/KeyEvent;)Z")
        onTouchEvent = JavaMethod("(Landroid/view/MotionEvent;)Z")
        onTrackballEvent = JavaMethod("(Landroid/view/MotionEvent;)Z")
        onGenericMotionEvent = JavaMethod("(Landroid/view/MotionEvent;)Z")