from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class TvTrackInfo:
    CREATOR: ClassVar[Creator]
    TYPE_AUDIO: ClassVar[int]
    TYPE_SUBTITLE: ClassVar[int]
    TYPE_VIDEO: ClassVar[int]
    def getType(self) -> int: ...
    def getId(self) -> str: ...
    def getLanguage(self) -> str: ...
    def getDescription(self) -> str: ...
    def getEncoding(self) -> str: ...
    def isEncrypted(self) -> bool: ...
    def getAudioChannelCount(self) -> int: ...
    def getAudioSampleRate(self) -> int: ...
    def isAudioDescription(self) -> bool: ...
    def isHardOfHearing(self) -> bool: ...
    def isSpokenSubtitle(self) -> bool: ...
    def getVideoWidth(self) -> int: ...
    def getVideoHeight(self) -> int: ...
    def getVideoFrameRate(self) -> float: ...
    def getVideoPixelAspectRatio(self) -> float: ...
    def getVideoActiveFormatDescription(self) -> int: ...
    def getExtra(self) -> Bundle: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: int, arg1: str) -> None: ...
        def setLanguage(self, arg0: str) -> "Builder": ...
        def setDescription(self, arg0: str) -> "Builder": ...
        def setEncoding(self, arg0: str) -> "Builder": ...
        def setEncrypted(self, arg0: bool) -> "Builder": ...
        def setAudioChannelCount(self, arg0: int) -> "Builder": ...
        def setAudioSampleRate(self, arg0: int) -> "Builder": ...
        def setAudioDescription(self, arg0: bool) -> "Builder": ...
        def setHardOfHearing(self, arg0: bool) -> "Builder": ...
        def setSpokenSubtitle(self, arg0: bool) -> "Builder": ...
        def setVideoWidth(self, arg0: int) -> "Builder": ...
        def setVideoHeight(self, arg0: int) -> "Builder": ...
        def setVideoFrameRate(self, arg0: float) -> "Builder": ...
        def setVideoPixelAspectRatio(self, arg0: float) -> "Builder": ...
        def setVideoActiveFormatDescription(self, arg0: int) -> "Builder": ...
        def setExtra(self, arg0: Bundle) -> "Builder": ...
        def build(self) -> "TvTrackInfo": ...
