from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["TvView"]

class TvView(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/tv/TvView"
    __javaconstructor__ = [("(Landroid/content/Context;)V", False), ("(Landroid/content/Context;Landroid/util/AttributeSet;)V", False), ("(Landroid/content/Context;Landroid/util/AttributeSet;I)V", False)]
    setCallback = JavaMethod("(Landroid/media/tv/TvView$TvInputCallback;)V")
    setZOrderMediaOverlay = JavaMethod("(Z)V")
    setZOrderOnTop = JavaMethod("(Z)V")
    setStreamVolume = JavaMethod("(F)V")
    overrideTvAppAttributionSource = JavaMethod("(Landroid/content/AttributionSource;)V")
    tune = JavaMultipleMethod([("(Ljava/lang/String;Landroid/net/Uri;)V", False, False), ("(Ljava/lang/String;Landroid/net/Uri;Landroid/os/Bundle;)V", False, False)])
    reset = JavaMethod("()V")
    setCaptionEnabled = JavaMethod("(Z)V")
    selectAudioPresentation = JavaMethod("(II)V")
    getAudioPresentations = JavaMethod("()Ljava/util/List;")
    selectTrack = JavaMethod("(ILjava/lang/String;)V")
    getTracks = JavaMethod("(I)Ljava/util/List;")
    getSelectedTrack = JavaMethod("(I)Ljava/lang/String;")
    setInteractiveAppNotificationEnabled = JavaMethod("(Z)V")
    timeShiftPlay = JavaMethod("(Ljava/lang/String;Landroid/net/Uri;)V")
    timeShiftPause = JavaMethod("()V")
    timeShiftResume = JavaMethod("()V")
    timeShiftSeekTo = JavaMethod("(J)V")
    timeShiftSetPlaybackParams = JavaMethod("(Landroid/media/PlaybackParams;)V")
    timeShiftSetMode = JavaMethod("(I)V")
    setTimeShiftPositionCallback = JavaMethod("(Landroid/media/tv/TvView$TimeShiftPositionCallback;)V")
    sendAppPrivateCommand = JavaMethod("(Ljava/lang/String;Landroid/os/Bundle;)V")
    dispatchUnhandledInputEvent = JavaMethod("(Landroid/view/InputEvent;)Z")
    onUnhandledInputEvent = JavaMethod("(Landroid/view/InputEvent;)Z")
    setOnUnhandledInputEventListener = JavaMethod("(Landroid/media/tv/TvView$OnUnhandledInputEventListener;)V")
    setTvMessageEnabled = JavaMethod("(IZ)V")
    dispatchKeyEvent = JavaMethod("(Landroid/view/KeyEvent;)Z")
    dispatchTouchEvent = JavaMethod("(Landroid/view/MotionEvent;)Z")
    dispatchTrackballEvent = JavaMethod("(Landroid/view/MotionEvent;)Z")
    dispatchGenericMotionEvent = JavaMethod("(Landroid/view/MotionEvent;)Z")
    dispatchWindowFocusChanged = JavaMethod("(Z)V")
    onAttachedToWindow = JavaMethod("()V")
    onDetachedFromWindow = JavaMethod("()V")
    onLayout = JavaMethod("(ZIIII)V")
    onMeasure = JavaMethod("(II)V")
    gatherTransparentRegion = JavaMethod("(Landroid/graphics/Region;)Z")
    draw = JavaMethod("(Landroid/graphics/Canvas;)V")
    dispatchDraw = JavaMethod("(Landroid/graphics/Canvas;)V")
    onVisibilityChanged = JavaMethod("(Landroid/view/View;I)V")

    class OnUnhandledInputEventListener(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/tv/TvView/OnUnhandledInputEventListener"
        onUnhandledInputEvent = JavaMethod("(Landroid/view/InputEvent;)Z")

    class TimeShiftPositionCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/tv/TvView/TimeShiftPositionCallback"
        __javaconstructor__ = [("()V", False)]
        onTimeShiftStartPositionChanged = JavaMethod("(Ljava/lang/String;J)V")
        onTimeShiftCurrentPositionChanged = JavaMethod("(Ljava/lang/String;J)V")

    class TvInputCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/tv/TvView/TvInputCallback"
        __javaconstructor__ = [("()V", False)]
        onConnectionFailed = JavaMethod("(Ljava/lang/String;)V")
        onDisconnected = JavaMethod("(Ljava/lang/String;)V")
        onChannelRetuned = JavaMethod("(Ljava/lang/String;Landroid/net/Uri;)V")
        onAudioPresentationsChanged = JavaMethod("(Ljava/lang/String;Ljava/util/List;)V")
        onAudioPresentationSelected = JavaMethod("(Ljava/lang/String;II)V")
        onTracksChanged = JavaMethod("(Ljava/lang/String;Ljava/util/List;)V")
        onTrackSelected = JavaMethod("(Ljava/lang/String;ILjava/lang/String;)V")
        onVideoSizeChanged = JavaMethod("(Ljava/lang/String;II)V")
        onVideoAvailable = JavaMethod("(Ljava/lang/String;)V")
        onVideoUnavailable = JavaMethod("(Ljava/lang/String;I)V")
        onContentAllowed = JavaMethod("(Ljava/lang/String;)V")
        onContentBlocked = JavaMethod("(Ljava/lang/String;Landroid/media/tv/TvContentRating;)V")
        onTimeShiftStatusChanged = JavaMethod("(Ljava/lang/String;I)V")
        onAitInfoUpdated = JavaMethod("(Ljava/lang/String;Landroid/media/tv/AitInfo;)V")
        onSignalStrengthUpdated = JavaMethod("(Ljava/lang/String;I)V")
        onCueingMessageAvailability = JavaMethod("(Ljava/lang/String;Z)V")
        onTimeShiftMode = JavaMethod("(Ljava/lang/String;I)V")
        onAvailableSpeeds = JavaMethod("(Ljava/lang/String;[F)V")
        onTuned = JavaMethod("(Ljava/lang/String;Landroid/net/Uri;)V")
        onTvMessage = JavaMethod("(Ljava/lang/String;ILandroid/os/Bundle;)V")