from typing import Any, ClassVar, overload
from android.content.AttributionSource import AttributionSource
from android.content.Context import Context
from android.graphics.Canvas import Canvas
from android.graphics.Region import Region
from android.media.PlaybackParams import PlaybackParams
from android.media.tv.AitInfo import AitInfo
from android.media.tv.TvContentRating import TvContentRating
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.util.AttributeSet import AttributeSet
from android.view.InputEvent import InputEvent
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.View import View

class TvView:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    def setCallback(self, arg0: "TvInputCallback") -> None: ...
    def setZOrderMediaOverlay(self, arg0: bool) -> None: ...
    def setZOrderOnTop(self, arg0: bool) -> None: ...
    def setStreamVolume(self, arg0: float) -> None: ...
    def overrideTvAppAttributionSource(self, arg0: AttributionSource) -> None: ...
    @overload
    def tune(self, arg0: str, arg1: Uri) -> None: ...
    @overload
    def tune(self, arg0: str, arg1: Uri, arg2: Bundle) -> None: ...
    def reset(self) -> None: ...
    def setCaptionEnabled(self, arg0: bool) -> None: ...
    def selectAudioPresentation(self, arg0: int, arg1: int) -> None: ...
    def getAudioPresentations(self) -> list: ...
    def selectTrack(self, arg0: int, arg1: str) -> None: ...
    def getTracks(self, arg0: int) -> list: ...
    def getSelectedTrack(self, arg0: int) -> str: ...
    def setInteractiveAppNotificationEnabled(self, arg0: bool) -> None: ...
    def timeShiftPlay(self, arg0: str, arg1: Uri) -> None: ...
    def timeShiftPause(self) -> None: ...
    def timeShiftResume(self) -> None: ...
    def timeShiftSeekTo(self, arg0: int) -> None: ...
    def timeShiftSetPlaybackParams(self, arg0: PlaybackParams) -> None: ...
    def timeShiftSetMode(self, arg0: int) -> None: ...
    def setTimeShiftPositionCallback(self, arg0: "TimeShiftPositionCallback") -> None: ...
    def sendAppPrivateCommand(self, arg0: str, arg1: Bundle) -> None: ...
    def dispatchUnhandledInputEvent(self, arg0: InputEvent) -> bool: ...
    def onUnhandledInputEvent(self, arg0: InputEvent) -> bool: ...
    def setOnUnhandledInputEventListener(self, arg0: "OnUnhandledInputEventListener") -> None: ...
    def setTvMessageEnabled(self, arg0: int, arg1: bool) -> None: ...
    def dispatchKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def dispatchTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchTrackballEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchGenericMotionEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchWindowFocusChanged(self, arg0: bool) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def gatherTransparentRegion(self, arg0: Region) -> bool: ...
    def draw(self, arg0: Canvas) -> None: ...
    def dispatchDraw(self, arg0: Canvas) -> None: ...
    def onVisibilityChanged(self, arg0: View, arg1: int) -> None: ...

    class OnUnhandledInputEventListener:
        def onUnhandledInputEvent(self, arg0: InputEvent) -> bool: ...

    class TimeShiftPositionCallback:
        def __init__(self) -> None: ...
        def onTimeShiftStartPositionChanged(self, arg0: str, arg1: int) -> None: ...
        def onTimeShiftCurrentPositionChanged(self, arg0: str, arg1: int) -> None: ...

    class TvInputCallback:
        def __init__(self) -> None: ...
        def onConnectionFailed(self, arg0: str) -> None: ...
        def onDisconnected(self, arg0: str) -> None: ...
        def onChannelRetuned(self, arg0: str, arg1: Uri) -> None: ...
        def onAudioPresentationsChanged(self, arg0: str, arg1: list) -> None: ...
        def onAudioPresentationSelected(self, arg0: str, arg1: int, arg2: int) -> None: ...
        def onTracksChanged(self, arg0: str, arg1: list) -> None: ...
        def onTrackSelected(self, arg0: str, arg1: int, arg2: str) -> None: ...
        def onVideoSizeChanged(self, arg0: str, arg1: int, arg2: int) -> None: ...
        def onVideoAvailable(self, arg0: str) -> None: ...
        def onVideoUnavailable(self, arg0: str, arg1: int) -> None: ...
        def onContentAllowed(self, arg0: str) -> None: ...
        def onContentBlocked(self, arg0: str, arg1: TvContentRating) -> None: ...
        def onTimeShiftStatusChanged(self, arg0: str, arg1: int) -> None: ...
        def onAitInfoUpdated(self, arg0: str, arg1: AitInfo) -> None: ...
        def onSignalStrengthUpdated(self, arg0: str, arg1: int) -> None: ...
        def onCueingMessageAvailability(self, arg0: str, arg1: bool) -> None: ...
        def onTimeShiftMode(self, arg0: str, arg1: int) -> None: ...
        def onAvailableSpeeds(self, arg0: str, arg1: list[float]) -> None: ...
        def onTuned(self, arg0: str, arg1: Uri) -> None: ...
        def onTvMessage(self, arg0: str, arg1: int, arg2: Bundle) -> None: ...
