from typing import Any, ClassVar, overload

class AbstractAdRequestBuilder:
    zza: "zzeg"
    def __init__(self) -> None: ...
    def self(self) -> "AbstractAdRequestBuilder": ...
    def addKeyword(self, arg0: str) -> "AbstractAdRequestBuilder": ...
    def addNetworkExtrasBundle(self, arg0: type, arg1: "Bundle") -> "AbstractAdRequestBuilder": ...
    def addCustomEventExtrasBundle(self, arg0: type, arg1: "Bundle") -> "AbstractAdRequestBuilder": ...
    @overload
    def addCustomTargeting(self, arg0: str, arg1: str) -> "AbstractAdRequestBuilder": ...
    @overload
    def addCustomTargeting(self, arg0: str, arg1: list) -> "AbstractAdRequestBuilder": ...
    def setContentUrl(self, arg0: str) -> "AbstractAdRequestBuilder": ...
    def setNeighboringContentUrls(self, arg0: list) -> "AbstractAdRequestBuilder": ...
    def setRequestAgent(self, arg0: str) -> "AbstractAdRequestBuilder": ...
    def setAdString(self, arg0: str) -> "AbstractAdRequestBuilder": ...
    def setHttpTimeoutMillis(self, arg0: int) -> "AbstractAdRequestBuilder": ...
    def setPlacementId(self, arg0: int) -> "AbstractAdRequestBuilder": ...
    def zza(self, arg0: "Bundle") -> "AbstractAdRequestBuilder": ...
    def zzb(self, arg0: str) -> "AbstractAdRequestBuilder": ...
    def zzc(self, arg0: bool) -> "AbstractAdRequestBuilder": ...
    def zzd(self, arg0: bool) -> "AbstractAdRequestBuilder": ...
