from typing import Any, ClassVar, overload
from android.gms.ads.AdError import AdError
from android.gms.ads.internal.client.zzv import zzv

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Bundle:
    """Forward declaration for ``android.os.Bundle``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Bundle')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Bundle
    """
    ...
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class AdapterResponseInfo:
    def getAdapterClassName(self) -> str: ...
    def getLatencyMillis(self) -> int: ...
    def getAdError(self) -> AdError: ...
    def getCredentials(self) -> Bundle: ...
    def getAdSourceName(self) -> str: ...
    def getAdSourceId(self) -> str: ...
    def getAdSourceInstanceName(self) -> str: ...
    def getAdSourceInstanceId(self) -> str: ...
    def toString(self) -> str: ...
    @staticmethod
    def zza(arg0: zzv) -> "AdapterResponseInfo": ...
    def zzb(self) -> JSONObject: ...
