from typing import Any, ClassVar, overload

class AdError:
    UNDEFINED_DOMAIN: ClassVar[str]
    @overload
    def __init__(self, arg0: int, arg1: str, arg2: str) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: str, arg2: str, arg3: "AdError") -> None: ...
    def getCode(self) -> int: ...
    def getMessage(self) -> str: ...
    def getDomain(self) -> str: ...
    def getCause(self) -> "AdError": ...
    def toString(self) -> str: ...
    def zza(self) -> "zze": ...
    def zzb(self) -> "JSONObject": ...
