from typing import Any, ClassVar, overload

class AdListener:
    def __init__(self) -> None: ...
    def onAdClosed(self) -> None: ...
    def onAdFailedToLoad(self, arg0: "LoadAdError") -> None: ...
    def onAdOpened(self) -> None: ...
    def onAdLoaded(self) -> None: ...
    def onAdClicked(self) -> None: ...
    def onAdImpression(self) -> None: ...
    def onAdSwipeGestureClicked(self) -> None: ...
