from typing import Any, ClassVar, overload

class AdLoader:
    @overload
    def loadAd(self, arg0: "AdRequest") -> None: ...
    @overload
    def loadAd(self, arg0: "AdManagerAdRequest") -> None: ...
    def loadAds(self, arg0: "AdRequest", arg1: int) -> None: ...
    def isLoading(self) -> bool: ...

    class Builder:
        def __init__(self, arg0: "Context", arg1: str) -> None: ...
        def forNativeAd(self, arg0: "OnNativeAdLoadedListener") -> "Builder": ...
        def forCustomFormatAd(self, arg0: str, arg1: "OnCustomFormatAdLoadedListener", arg2: "OnCustomClickListener") -> "Builder": ...
        def forAdManagerAdView(self, arg0: "OnAdManagerAdViewLoadedListener", *arg1: "AdSize") -> "Builder": ...
        def withAdListener(self, arg0: "AdListener") -> "Builder": ...
        def withNativeAdOptions(self, arg0: "NativeAdOptions") -> "Builder": ...
        def withAdManagerAdViewOptions(self, arg0: "AdManagerAdViewOptions") -> "Builder": ...
        def build(self) -> "AdLoader": ...
        def zza(self, arg0: "zzg") -> "Builder": ...
        def zzb(self, arg0: str, arg1: "zze", arg2: "zzd") -> "Builder": ...
        def zzc(self, arg0: "NativeAdOptions") -> "Builder": ...
