from typing import Any, ClassVar, overload
from android.gms.ads.AdError import AdError
from android.gms.ads.ResponseInfo import ResponseInfo

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject: ...  # org.json.JSONObject

class LoadAdError:
    def __init__(self, arg0: int, arg1: str, arg2: str, arg3: AdError, arg4: ResponseInfo) -> None: ...
    def getResponseInfo(self) -> ResponseInfo: ...
    def toString(self) -> str: ...
    def zzb(self) -> JSONObject: ...
