from typing import Any, ClassVar, overload

class LoadAdError:
    def __init__(self, arg0: int, arg1: str, arg2: str, arg3: "AdError", arg4: "ResponseInfo") -> None: ...
    def getResponseInfo(self) -> "ResponseInfo": ...
    def toString(self) -> str: ...
    def zzb(self) -> "JSONObject": ...
