from typing import Any, ClassVar, overload

class MediaContent:
    def getAspectRatio(self) -> float: ...
    def getDuration(self) -> float: ...
    def getCurrentTime(self) -> float: ...
    def getVideoController(self) -> "VideoController": ...
    def hasVideoContent(self) -> bool: ...
    def setMainImage(self, arg0: "Drawable") -> None: ...
    def getMainImage(self) -> "Drawable": ...
    def zza(self) -> bool: ...
    def zzb(self) -> "zzbnc": ...
