from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class ProviderInfo: ...  # android.content.pm.ProviderInfo
class Uri: ...  # android.net.Uri
class Cursor: ...  # android.database.Cursor
class ContentValues: ...  # android.content.ContentValues

class MobileAdsInitProvider:
    def __init__(self) -> None: ...
    def attachInfo(self, arg0: Context, arg1: ProviderInfo) -> None: ...
    def onCreate(self) -> bool: ...
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str) -> Cursor: ...
    def getType(self, arg0: Uri) -> str: ...
    def insert(self, arg0: Uri, arg1: ContentValues) -> Uri: ...
    def delete(self, arg0: Uri, arg1: str, arg2: list[str]) -> int: ...
    def update(self, arg0: Uri, arg1: ContentValues, arg2: str, arg3: list[str]) -> int: ...
