from typing import Any, ClassVar, overload
from android.gms.ads.OnAdInspectorClosedListener import OnAdInspectorClosedListener
from android.gms.ads.RequestConfiguration import RequestConfiguration
from android.gms.ads.VersionInfo import VersionInfo
from android.gms.ads.initialization.InitializationStatus import InitializationStatus
from android.gms.ads.initialization.OnInitializationCompleteListener import OnInitializationCompleteListener
from android.gms.ads.preload.PreloadCallback import PreloadCallback

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class WebView: ...  # android.webkit.WebView
class CustomTabsClient: ...  # androidx.browser.customtabs.CustomTabsClient
class CustomTabsCallback: ...  # androidx.browser.customtabs.CustomTabsCallback
class CustomTabsSession: ...  # androidx.browser.customtabs.CustomTabsSession

class MobileAds:
    ERROR_DOMAIN: ClassVar[str]
    @overload
    @staticmethod
    def initialize(arg0: Context) -> None: ...
    @overload
    @staticmethod
    def initialize(arg0: Context, arg1: OnInitializationCompleteListener) -> None: ...
    @staticmethod
    def setAppVolume(arg0: float) -> None: ...
    @staticmethod
    def setAppMuted(arg0: bool) -> None: ...
    @staticmethod
    def openDebugMenu(arg0: Context, arg1: str) -> None: ...
    @staticmethod
    def registerRtbAdapter(arg0: type) -> None: ...
    @staticmethod
    def getInitializationStatus() -> InitializationStatus: ...
    @staticmethod
    def getRequestConfiguration() -> RequestConfiguration: ...
    @staticmethod
    def setRequestConfiguration(arg0: RequestConfiguration) -> None: ...
    @staticmethod
    def disableMediationAdapterInitialization(arg0: Context) -> None: ...
    @staticmethod
    def openAdInspector(arg0: Context, arg1: OnAdInspectorClosedListener) -> None: ...
    @staticmethod
    def getVersion() -> VersionInfo: ...
    @staticmethod
    def registerWebView(arg0: WebView) -> None: ...
    @staticmethod
    def putPublisherFirstPartyIdEnabled(arg0: bool) -> bool: ...
    @staticmethod
    def registerCustomTabsSession(arg0: Context, arg1: CustomTabsClient, arg2: str, arg3: CustomTabsCallback) -> CustomTabsSession: ...
    @staticmethod
    def startPreload(arg0: Context, arg1: list, arg2: PreloadCallback) -> None: ...
