from typing import Any, ClassVar, overload
from android.gms.ads.AgeRestrictedTreatment import AgeRestrictedTreatment

class RequestConfiguration:
    TAG_FOR_CHILD_DIRECTED_TREATMENT_UNSPECIFIED: ClassVar[int]
    TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE: ClassVar[int]
    TAG_FOR_CHILD_DIRECTED_TREATMENT_TRUE: ClassVar[int]
    TAG_FOR_UNDER_AGE_OF_CONSENT_TRUE: ClassVar[int]
    TAG_FOR_UNDER_AGE_OF_CONSENT_FALSE: ClassVar[int]
    TAG_FOR_UNDER_AGE_OF_CONSENT_UNSPECIFIED: ClassVar[int]
    MAX_AD_CONTENT_RATING_UNSPECIFIED: ClassVar[str]
    MAX_AD_CONTENT_RATING_G: ClassVar[str]
    MAX_AD_CONTENT_RATING_PG: ClassVar[str]
    MAX_AD_CONTENT_RATING_T: ClassVar[str]
    MAX_AD_CONTENT_RATING_MA: ClassVar[str]
    zza: ClassVar[list]
    def getAgeRestrictedTreatment(self) -> AgeRestrictedTreatment: ...
    def getTagForChildDirectedTreatment(self) -> int: ...
    def getTagForUnderAgeOfConsent(self) -> int: ...
    def getMaxAdContentRating(self) -> str: ...
    def getTestDeviceIds(self) -> list: ...
    def getPublisherPrivacyPersonalizationState(self) -> "PublisherPrivacyPersonalizationState": ...
    def toBuilder(self) -> "Builder": ...
    def zza(self) -> AgeRestrictedTreatment: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "RequestConfiguration": ...
        def setAgeRestrictedTreatment(self, arg0: AgeRestrictedTreatment) -> "Builder": ...
        def setTagForChildDirectedTreatment(self, arg0: int) -> "Builder": ...
        def setTagForUnderAgeOfConsent(self, arg0: int) -> "Builder": ...
        def setMaxAdContentRating(self, arg0: str) -> "Builder": ...
        def setTestDeviceIds(self, arg0: list) -> "Builder": ...
        def setPublisherPrivacyPersonalizationState(self, arg0: "PublisherPrivacyPersonalizationState") -> "Builder": ...

    class MaxAdContentRating:
        ...

    class PublisherPrivacyPersonalizationState:
        DEFAULT: ClassVar["PublisherPrivacyPersonalizationState"]
        ENABLED: ClassVar["PublisherPrivacyPersonalizationState"]
        DISABLED: ClassVar["PublisherPrivacyPersonalizationState"]
        @staticmethod
        def values() -> list["PublisherPrivacyPersonalizationState"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "PublisherPrivacyPersonalizationState": ...
        def getValue(self) -> int: ...

    class TagForChildDirectedTreatment:
        ...

    class TagForUnderAgeOfConsent:
        ...
