from typing import Any, ClassVar, overload
from android.gms.ads.AdapterResponseInfo import AdapterResponseInfo
from android.gms.ads.internal.client.zzdx import zzdx
from android.os.Bundle import Bundle

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class ResponseInfo:
    def getMediationAdapterClassName(self) -> str: ...
    def getResponseId(self) -> str: ...
    def getResponseExtras(self) -> Bundle: ...
    def getAdapterResponses(self) -> list: ...
    def getLoadedAdapterResponseInfo(self) -> AdapterResponseInfo: ...
    def toString(self) -> str: ...
    def zza(self) -> JSONObject: ...
    @staticmethod
    def zzb(arg0: zzdx) -> "ResponseInfo": ...
    @staticmethod
    def zzc(arg0: zzdx) -> "ResponseInfo": ...
    def zzd(self) -> zzdx: ...
