from typing import Any, ClassVar, overload

class VersionInfo:
    zza: int
    zzb: int
    zzc: int
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def getMajorVersion(self) -> int: ...
    def getMinorVersion(self) -> int: ...
    def getMicroVersion(self) -> int: ...
    def toString(self) -> str: ...
