from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzfw import zzfw

class VideoOptions:
    def __init__(self, arg0: zzfw) -> None: ...
    def getStartMuted(self) -> bool: ...
    def getCustomControlsRequested(self) -> bool: ...
    def getClickToExpandRequested(self) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setStartMuted(self, arg0: bool) -> "Builder": ...
        def setCustomControlsRequested(self, arg0: bool) -> "Builder": ...
        def setClickToExpandRequested(self, arg0: bool) -> "Builder": ...
        def build(self) -> "VideoOptions": ...
