from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AwarePairingConfig:
    CREATOR: ClassVar[Creator]
    PAIRING_BOOTSTRAPPING_NFC_READER: ClassVar[int]
    PAIRING_BOOTSTRAPPING_NFC_TAG: ClassVar[int]
    PAIRING_BOOTSTRAPPING_OPPORTUNISTIC: ClassVar[int]
    PAIRING_BOOTSTRAPPING_PASSPHRASE_DISPLAY: ClassVar[int]
    PAIRING_BOOTSTRAPPING_PASSPHRASE_KEYPAD: ClassVar[int]
    PAIRING_BOOTSTRAPPING_PIN_CODE_DISPLAY: ClassVar[int]
    PAIRING_BOOTSTRAPPING_PIN_CODE_KEYPAD: ClassVar[int]
    PAIRING_BOOTSTRAPPING_QR_DISPLAY: ClassVar[int]
    PAIRING_BOOTSTRAPPING_QR_SCAN: ClassVar[int]
    def isPairingCacheEnabled(self) -> bool: ...
    def isPairingSetupEnabled(self) -> bool: ...
    def isPairingVerificationEnabled(self) -> bool: ...
    def getBootstrappingMethods(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setPairingSetupEnabled(self, arg0: bool) -> "Builder": ...
        def setPairingVerificationEnabled(self, arg0: bool) -> "Builder": ...
        def setPairingCacheEnabled(self, arg0: bool) -> "Builder": ...
        def setBootstrappingMethods(self, arg0: int) -> "Builder": ...
        def build(self) -> "AwarePairingConfig": ...
