from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Characteristics:
    CREATOR: ClassVar[Creator]
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_128: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_256: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_PASN_128: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_PASN_256: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_SK_128: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_SK_256: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NONE: ClassVar[int]
    def getMaxServiceNameLength(self) -> int: ...
    def getMaxServiceSpecificInfoLength(self) -> int: ...
    def getMaxMatchFilterLength(self) -> int: ...
    def getNumberOfSupportedDataInterfaces(self) -> int: ...
    def getNumberOfSupportedPublishSessions(self) -> int: ...
    def getNumberOfSupportedSubscribeSessions(self) -> int: ...
    def getNumberOfSupportedDataPaths(self) -> int: ...
    def isInstantCommunicationModeSupported(self) -> bool: ...
    def isAwarePairingSupported(self) -> bool: ...
    def isSuspensionSupported(self) -> bool: ...
    def getSupportedCipherSuites(self) -> int: ...
    def getSupportedPairingCipherSuites(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
