from typing import Any, ClassVar, overload
from android.net.wifi.aware.PeerHandle import PeerHandle
from android.net.wifi.aware.PublishDiscoverySession import PublishDiscoverySession
from android.net.wifi.aware.ServiceDiscoveryInfo import ServiceDiscoveryInfo
from android.net.wifi.aware.SubscribeDiscoverySession import SubscribeDiscoverySession

class DiscoverySessionCallback:
    def __init__(self) -> None: ...
    def onPublishStarted(self, arg0: PublishDiscoverySession) -> None: ...
    def onSubscribeStarted(self, arg0: SubscribeDiscoverySession) -> None: ...
    def onSessionConfigUpdated(self) -> None: ...
    def onSessionConfigFailed(self) -> None: ...
    def onSessionTerminated(self) -> None: ...
    @overload
    def onServiceDiscovered(self, arg0: PeerHandle, arg1: list[int], arg2: list) -> None: ...
    @overload
    def onServiceDiscovered(self, arg0: ServiceDiscoveryInfo) -> None: ...
    @overload
    def onServiceDiscoveredWithinRange(self, arg0: PeerHandle, arg1: list[int], arg2: list, arg3: int) -> None: ...
    @overload
    def onServiceDiscoveredWithinRange(self, arg0: ServiceDiscoveryInfo, arg1: int) -> None: ...
    def onMessageSendSucceeded(self, arg0: int) -> None: ...
    def onMessageSendFailed(self, arg0: int) -> None: ...
    def onMessageReceived(self, arg0: PeerHandle, arg1: list[int]) -> None: ...
    def onServiceLost(self, arg0: PeerHandle, arg1: int) -> None: ...
    def onPairingSetupRequestReceived(self, arg0: PeerHandle, arg1: int) -> None: ...
    def onPairingSetupSucceeded(self, arg0: PeerHandle, arg1: str) -> None: ...
    def onPairingSetupFailed(self, arg0: PeerHandle) -> None: ...
    def onPairingVerificationSucceed(self, arg0: PeerHandle, arg1: str) -> None: ...
    def onPairingVerificationFailed(self, arg0: PeerHandle) -> None: ...
    def onBootstrappingSucceeded(self, arg0: PeerHandle, arg1: int) -> None: ...
    def onBootstrappingFailed(self, arg0: PeerHandle) -> None: ...
