from typing import Any, ClassVar, overload
from android.net.wifi.aware.AwarePairingConfig import AwarePairingConfig
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SubscribeConfig:
    CREATOR: ClassVar[Creator]
    SUBSCRIBE_TYPE_ACTIVE: ClassVar[int]
    SUBSCRIBE_TYPE_PASSIVE: ClassVar[int]
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def isInstantCommunicationModeEnabled(self) -> bool: ...
    def getInstantCommunicationBand(self) -> int: ...
    def getPairingConfig(self) -> AwarePairingConfig: ...

    class Builder:
        def __init__(self) -> None: ...
        def setServiceName(self, arg0: str) -> "Builder": ...
        def setServiceSpecificInfo(self, arg0: list[int]) -> "Builder": ...
        def setMatchFilter(self, arg0: list) -> "Builder": ...
        def setSubscribeType(self, arg0: int) -> "Builder": ...
        def setTtlSec(self, arg0: int) -> "Builder": ...
        def setTerminateNotificationEnabled(self, arg0: bool) -> "Builder": ...
        def setMinDistanceMm(self, arg0: int) -> "Builder": ...
        def setMaxDistanceMm(self, arg0: int) -> "Builder": ...
        def setInstantCommunicationModeEnabled(self, arg0: bool, arg1: int) -> "Builder": ...
        def setPairingConfig(self, arg0: AwarePairingConfig) -> "Builder": ...
        def build(self) -> "SubscribeConfig": ...
