from typing import Any, ClassVar, overload
from android.net.wifi.aware.AttachCallback import AttachCallback
from android.net.wifi.aware.AwareResources import AwareResources
from android.net.wifi.aware.Characteristics import Characteristics
from android.net.wifi.aware.IdentityChangedListener import IdentityChangedListener
from android.os.Handler import Handler
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class WifiAwareManager:
    ACTION_WIFI_AWARE_RESOURCE_CHANGED: ClassVar[str]
    ACTION_WIFI_AWARE_STATE_CHANGED: ClassVar[str]
    EXTRA_AWARE_RESOURCES: ClassVar[str]
    WIFI_AWARE_DATA_PATH_ROLE_INITIATOR: ClassVar[int]
    WIFI_AWARE_DATA_PATH_ROLE_RESPONDER: ClassVar[int]
    WIFI_AWARE_DISCOVERY_LOST_REASON_PEER_NOT_VISIBLE: ClassVar[int]
    WIFI_AWARE_DISCOVERY_LOST_REASON_UNKNOWN: ClassVar[int]
    def isAvailable(self) -> bool: ...
    def isDeviceAttached(self) -> bool: ...
    def isSetChannelOnDataPathSupported(self) -> bool: ...
    def isInstantCommunicationModeEnabled(self) -> bool: ...
    def getCharacteristics(self) -> Characteristics: ...
    def getAvailableAwareResources(self) -> AwareResources: ...
    @overload
    def attach(self, arg0: AttachCallback, arg1: Handler) -> None: ...
    @overload
    def attach(self, arg0: AttachCallback, arg1: IdentityChangedListener, arg2: Handler) -> None: ...
    def setOpportunisticModeEnabled(self, arg0: bool) -> None: ...
    def isOpportunisticModeEnabled(self, arg0: Executor, arg1: Consumer) -> None: ...
    def resetPairedDevices(self) -> None: ...
    def removePairedDevice(self, arg0: str) -> None: ...
    def getPairedDevices(self, arg0: Executor, arg1: Consumer) -> None: ...
