from typing import Any, ClassVar, overload
from android.animation.Animator import Animator
from android.animation.TimeInterpolator import TimeInterpolator

class AnimatorSet:
    def __init__(self) -> None: ...
    @overload
    def playTogether(self, *arg0: Animator) -> None: ...
    @overload
    def playTogether(self, arg0: list) -> None: ...
    @overload
    def playSequentially(self, *arg0: Animator) -> None: ...
    @overload
    def playSequentially(self, arg0: list) -> None: ...
    def getChildAnimations(self) -> list: ...
    def setTarget(self, arg0: Any) -> None: ...
    def setInterpolator(self, arg0: TimeInterpolator) -> None: ...
    def getInterpolator(self) -> TimeInterpolator: ...
    def play(self, arg0: Animator) -> "Builder": ...
    def cancel(self) -> None: ...
    def end(self) -> None: ...
    def isRunning(self) -> bool: ...
    def isStarted(self) -> bool: ...
    def getStartDelay(self) -> int: ...
    def setStartDelay(self, arg0: int) -> None: ...
    def getDuration(self) -> int: ...
    def setDuration(self, arg0: int) -> "AnimatorSet": ...
    def setupStartValues(self) -> None: ...
    def setupEndValues(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def start(self) -> None: ...
    def setCurrentPlayTime(self, arg0: int) -> None: ...
    def getCurrentPlayTime(self) -> int: ...
    def clone(self) -> "AnimatorSet": ...
    def reverse(self) -> None: ...
    def toString(self) -> str: ...
    def getTotalDuration(self) -> int: ...

    class Builder:
        def with_(self, arg0: Animator) -> "Builder": ...
        def before(self, arg0: Animator) -> "Builder": ...
        @overload
        def after(self, arg0: Animator) -> "Builder": ...
        @overload
        def after(self, arg0: int) -> "Builder": ...
