from typing import Any, ClassVar, overload
from android.animation.TimeInterpolator import TimeInterpolator

class Keyframe:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def ofInt(arg0: float, arg1: int) -> "Keyframe": ...
    @overload
    @staticmethod
    def ofInt(arg0: float) -> "Keyframe": ...
    @overload
    @staticmethod
    def ofFloat(arg0: float, arg1: float) -> "Keyframe": ...
    @overload
    @staticmethod
    def ofFloat(arg0: float) -> "Keyframe": ...
    @overload
    @staticmethod
    def ofObject(arg0: float, arg1: Any) -> "Keyframe": ...
    @overload
    @staticmethod
    def ofObject(arg0: float) -> "Keyframe": ...
    def hasValue(self) -> bool: ...
    def getValue(self) -> Any: ...
    def setValue(self, arg0: Any) -> None: ...
    def getFraction(self) -> float: ...
    def setFraction(self, arg0: float) -> None: ...
    def getInterpolator(self) -> TimeInterpolator: ...
    def setInterpolator(self, arg0: TimeInterpolator) -> None: ...
    def getType(self) -> type: ...
    def clone(self) -> "Keyframe": ...
