from typing import Any, ClassVar, overload
from android.animation.Animator import Animator
from android.animation.TimeInterpolator import TimeInterpolator
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class LayoutTransition:
    APPEARING: ClassVar[int]
    CHANGE_APPEARING: ClassVar[int]
    CHANGE_DISAPPEARING: ClassVar[int]
    CHANGING: ClassVar[int]
    DISAPPEARING: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    def setDuration(self, arg0: int) -> None: ...
    @overload
    def setDuration(self, arg0: int, arg1: int) -> None: ...
    def enableTransitionType(self, arg0: int) -> None: ...
    def disableTransitionType(self, arg0: int) -> None: ...
    def isTransitionTypeEnabled(self, arg0: int) -> bool: ...
    def setStartDelay(self, arg0: int, arg1: int) -> None: ...
    def getStartDelay(self, arg0: int) -> int: ...
    def getDuration(self, arg0: int) -> int: ...
    def setStagger(self, arg0: int, arg1: int) -> None: ...
    def getStagger(self, arg0: int) -> int: ...
    def setInterpolator(self, arg0: int, arg1: TimeInterpolator) -> None: ...
    def getInterpolator(self, arg0: int) -> TimeInterpolator: ...
    def setAnimator(self, arg0: int, arg1: Animator) -> None: ...
    def getAnimator(self, arg0: int) -> Animator: ...
    def setAnimateParentHierarchy(self, arg0: bool) -> None: ...
    def isChangingLayout(self) -> bool: ...
    def isRunning(self) -> bool: ...
    def addChild(self, arg0: ViewGroup, arg1: View) -> None: ...
    @overload
    def showChild(self, arg0: ViewGroup, arg1: View) -> None: ...
    @overload
    def showChild(self, arg0: ViewGroup, arg1: View, arg2: int) -> None: ...
    def removeChild(self, arg0: ViewGroup, arg1: View) -> None: ...
    @overload
    def hideChild(self, arg0: ViewGroup, arg1: View) -> None: ...
    @overload
    def hideChild(self, arg0: ViewGroup, arg1: View, arg2: int) -> None: ...
    def addTransitionListener(self, arg0: "TransitionListener") -> None: ...
    def removeTransitionListener(self, arg0: "TransitionListener") -> None: ...
    def getTransitionListeners(self) -> list: ...

    class TransitionListener:
        def startTransition(self, arg0: "LayoutTransition", arg1: ViewGroup, arg2: View, arg3: int) -> None: ...
        def endTransition(self, arg0: "LayoutTransition", arg1: ViewGroup, arg2: View, arg3: int) -> None: ...
