from typing import Any, ClassVar, overload
from android.animation.Keyframe import Keyframe
from android.animation.TypeConverter import TypeConverter
from android.animation.TypeEvaluator import TypeEvaluator
from android.graphics.Path import Path
from android.util.Property import Property

class PropertyValuesHolder:
    @overload
    @staticmethod
    def ofInt(arg0: str, *arg1: int) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofInt(arg0: Property, *arg1: int) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiInt(arg0: str, arg1: list[list[int]]) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiInt(arg0: str, arg1: Path) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiInt(arg0: str, arg1: TypeConverter, arg2: TypeEvaluator, *arg3: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiInt(arg0: str, arg1: TypeConverter, arg2: TypeEvaluator, *arg3: Keyframe) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofFloat(arg0: str, *arg1: float) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofFloat(arg0: Property, *arg1: float) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiFloat(arg0: str, arg1: list[list[float]]) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiFloat(arg0: str, arg1: Path) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiFloat(arg0: str, arg1: TypeConverter, arg2: TypeEvaluator, *arg3: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiFloat(arg0: str, arg1: TypeConverter, arg2: TypeEvaluator, *arg3: Keyframe) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(arg0: str, arg1: TypeEvaluator, *arg2: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(arg0: str, arg1: TypeConverter, arg2: Path) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(arg0: Property, arg1: TypeEvaluator, *arg2: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(arg0: Property, arg1: TypeConverter, arg2: TypeEvaluator, *arg3: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(arg0: Property, arg1: TypeConverter, arg2: Path) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofKeyframe(arg0: str, *arg1: Keyframe) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofKeyframe(arg0: Property, *arg1: Keyframe) -> "PropertyValuesHolder": ...
    def setIntValues(self, *arg0: int) -> None: ...
    def setFloatValues(self, *arg0: float) -> None: ...
    def setKeyframes(self, *arg0: Keyframe) -> None: ...
    def setObjectValues(self, *arg0: Any) -> None: ...
    def setConverter(self, arg0: TypeConverter) -> None: ...
    def clone(self) -> "PropertyValuesHolder": ...
    def setEvaluator(self, arg0: TypeEvaluator) -> None: ...
    def setPropertyName(self, arg0: str) -> None: ...
    def setProperty(self, arg0: Property) -> None: ...
    def getPropertyName(self) -> str: ...
    def toString(self) -> str: ...
