from typing import Any, ClassVar, overload
from android.animation.Animator import Animator

class StateListAnimator:
    def __init__(self) -> None: ...
    def addState(self, arg0: list[int], arg1: Animator) -> None: ...
    def clone(self) -> "StateListAnimator": ...
    def jumpToCurrentState(self) -> None: ...
