from typing import Any, ClassVar, overload

class TimeAnimator:
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def setCurrentPlayTime(self, arg0: int) -> None: ...
    def setTimeListener(self, arg0: "TimeListener") -> None: ...

    class TimeListener:
        def onTimeUpdate(self, arg0: "TimeAnimator", arg1: int, arg2: int) -> None: ...
