from typing import Any, ClassVar, overload
from android.animation.PropertyValuesHolder import PropertyValuesHolder
from android.animation.TimeInterpolator import TimeInterpolator
from android.animation.TypeEvaluator import TypeEvaluator

class ValueAnimator:
    INFINITE: ClassVar[int]
    RESTART: ClassVar[int]
    REVERSE: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def getDurationScale() -> float: ...
    @staticmethod
    def registerDurationScaleChangeListener(arg0: "DurationScaleChangeListener") -> bool: ...
    @staticmethod
    def unregisterDurationScaleChangeListener(arg0: "DurationScaleChangeListener") -> bool: ...
    @staticmethod
    def areAnimatorsEnabled() -> bool: ...
    @staticmethod
    def ofInt(*arg0: int) -> "ValueAnimator": ...
    @staticmethod
    def ofArgb(*arg0: int) -> "ValueAnimator": ...
    @staticmethod
    def ofFloat(*arg0: float) -> "ValueAnimator": ...
    @staticmethod
    def ofPropertyValuesHolder(*arg0: PropertyValuesHolder) -> "ValueAnimator": ...
    @staticmethod
    def ofObject(arg0: TypeEvaluator, *arg1: Any) -> "ValueAnimator": ...
    def setIntValues(self, *arg0: int) -> None: ...
    def setFloatValues(self, *arg0: float) -> None: ...
    def setObjectValues(self, *arg0: Any) -> None: ...
    def setValues(self, *arg0: PropertyValuesHolder) -> None: ...
    def getValues(self) -> list[PropertyValuesHolder]: ...
    def setDuration(self, arg0: int) -> "ValueAnimator": ...
    def getDuration(self) -> int: ...
    def getTotalDuration(self) -> int: ...
    def setCurrentPlayTime(self, arg0: int) -> None: ...
    def setCurrentFraction(self, arg0: float) -> None: ...
    def getCurrentPlayTime(self) -> int: ...
    def getStartDelay(self) -> int: ...
    def setStartDelay(self, arg0: int) -> None: ...
    @staticmethod
    def getFrameDelay() -> int: ...
    @staticmethod
    def setFrameDelay(arg0: int) -> None: ...
    @overload
    def getAnimatedValue(self) -> Any: ...
    @overload
    def getAnimatedValue(self, arg0: str) -> Any: ...
    def setRepeatCount(self, arg0: int) -> None: ...
    def getRepeatCount(self) -> int: ...
    def setRepeatMode(self, arg0: int) -> None: ...
    def getRepeatMode(self) -> int: ...
    def addUpdateListener(self, arg0: "AnimatorUpdateListener") -> None: ...
    def removeAllUpdateListeners(self) -> None: ...
    def removeUpdateListener(self, arg0: "AnimatorUpdateListener") -> None: ...
    def setInterpolator(self, arg0: TimeInterpolator) -> None: ...
    def getInterpolator(self) -> TimeInterpolator: ...
    def setEvaluator(self, arg0: TypeEvaluator) -> None: ...
    def start(self) -> None: ...
    def cancel(self) -> None: ...
    def end(self) -> None: ...
    def resume(self) -> None: ...
    def pause(self) -> None: ...
    def isRunning(self) -> bool: ...
    def isStarted(self) -> bool: ...
    def reverse(self) -> None: ...
    def getAnimatedFraction(self) -> float: ...
    def clone(self) -> "ValueAnimator": ...
    def toString(self) -> str: ...

    class AnimatorUpdateListener:
        def onAnimationUpdate(self, arg0: "ValueAnimator") -> None: ...

    class DurationScaleChangeListener:
        def onChanged(self, arg0: float) -> None: ...
