from typing import Any, ClassVar, overload
from java.util.concurrent.Executor import Executor

class ProvisioningManager:
    def registerFeatureProvisioningChangedCallback(self, arg0: Executor, arg1: "FeatureProvisioningCallback") -> None: ...
    def unregisterFeatureProvisioningChangedCallback(self, arg0: "FeatureProvisioningCallback") -> None: ...
    def setProvisioningStatusForCapability(self, arg0: int, arg1: int, arg2: bool) -> None: ...
    def getProvisioningStatusForCapability(self, arg0: int, arg1: int) -> bool: ...
    def getRcsProvisioningStatusForCapability(self, arg0: int, arg1: int) -> bool: ...
    def setRcsProvisioningStatusForCapability(self, arg0: int, arg1: int, arg2: bool) -> None: ...
    def isProvisioningRequiredForCapability(self, arg0: int, arg1: int) -> bool: ...
    def isRcsProvisioningRequiredForCapability(self, arg0: int, arg1: int) -> bool: ...

    class FeatureProvisioningCallback:
        def __init__(self) -> None: ...
        def onFeatureProvisioningChanged(self, arg0: int, arg1: int, arg2: bool) -> None: ...
        def onRcsFeatureProvisioningChanged(self, arg0: int, arg1: int, arg2: bool) -> None: ...
