from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from org.xmlpull.v1.XmlPullParser import XmlPullParser

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ApplicationMediaCapabilities:
    CREATOR: ClassVar[Creator]
    def isVideoMimeTypeSupported(self, arg0: str) -> bool: ...
    def isHdrTypeSupported(self, arg0: str) -> bool: ...
    def isFormatSpecified(self, arg0: str) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...
    def getSupportedVideoMimeTypes(self) -> list: ...
    def getUnsupportedVideoMimeTypes(self) -> list: ...
    def getSupportedHdrTypes(self) -> list: ...
    def getUnsupportedHdrTypes(self) -> list: ...
    @staticmethod
    def createFromXml(arg0: XmlPullParser) -> "ApplicationMediaCapabilities": ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "ApplicationMediaCapabilities": ...
        def addSupportedVideoMimeType(self, arg0: str) -> "Builder": ...
        def addUnsupportedVideoMimeType(self, arg0: str) -> "Builder": ...
        def addSupportedHdrType(self, arg0: str) -> "Builder": ...
        def addUnsupportedHdrType(self, arg0: str) -> "Builder": ...
