from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.media.AudioAttributes import AudioAttributes
from android.net.Uri import Uri

class AsyncPlayer:
    def __init__(self, arg0: str) -> None: ...
    @overload
    def play(self, arg0: Context, arg1: Uri, arg2: bool, arg3: int) -> None: ...
    @overload
    def play(self, arg0: Context, arg1: Uri, arg2: bool, arg3: AudioAttributes) -> None: ...
    def stop(self) -> None: ...
