from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.ComponentName import ComponentName
from android.media.AudioAttributes import AudioAttributes
from android.media.AudioDeviceCallback import AudioDeviceCallback
from android.media.AudioDeviceInfo import AudioDeviceInfo
from android.media.AudioFocusRequest import AudioFocusRequest
from android.media.AudioFormat import AudioFormat
from android.media.AudioMixerAttributes import AudioMixerAttributes
from android.media.RemoteControlClient import RemoteControlClient
from android.media.RemoteController import RemoteController
from android.media.Spatializer import Spatializer
from android.os.Handler import Handler
from android.view.KeyEvent import KeyEvent
from java.util.concurrent.Executor import Executor

class AudioManager:
    ACTION_AUDIO_BECOMING_NOISY: ClassVar[str]
    ACTION_HDMI_AUDIO_PLUG: ClassVar[str]
    ACTION_HEADSET_PLUG: ClassVar[str]
    ACTION_MICROPHONE_MUTE_CHANGED: ClassVar[str]
    ACTION_SCO_AUDIO_STATE_CHANGED: ClassVar[str]
    ACTION_SCO_AUDIO_STATE_UPDATED: ClassVar[str]
    ACTION_SPEAKERPHONE_STATE_CHANGED: ClassVar[str]
    ADJUST_LOWER: ClassVar[int]
    ADJUST_MUTE: ClassVar[int]
    ADJUST_RAISE: ClassVar[int]
    ADJUST_SAME: ClassVar[int]
    ADJUST_TOGGLE_MUTE: ClassVar[int]
    ADJUST_UNMUTE: ClassVar[int]
    AUDIOFOCUS_GAIN: ClassVar[int]
    AUDIOFOCUS_GAIN_TRANSIENT: ClassVar[int]
    AUDIOFOCUS_GAIN_TRANSIENT_EXCLUSIVE: ClassVar[int]
    AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK: ClassVar[int]
    AUDIOFOCUS_LOSS: ClassVar[int]
    AUDIOFOCUS_LOSS_TRANSIENT: ClassVar[int]
    AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK: ClassVar[int]
    AUDIOFOCUS_NONE: ClassVar[int]
    AUDIOFOCUS_REQUEST_DELAYED: ClassVar[int]
    AUDIOFOCUS_REQUEST_FAILED: ClassVar[int]
    AUDIOFOCUS_REQUEST_GRANTED: ClassVar[int]
    AUDIO_SESSION_ID_GENERATE: ClassVar[int]
    DIRECT_PLAYBACK_BITSTREAM_SUPPORTED: ClassVar[int]
    DIRECT_PLAYBACK_NOT_SUPPORTED: ClassVar[int]
    DIRECT_PLAYBACK_OFFLOAD_GAPLESS_SUPPORTED: ClassVar[int]
    DIRECT_PLAYBACK_OFFLOAD_SUPPORTED: ClassVar[int]
    ENCODED_SURROUND_OUTPUT_ALWAYS: ClassVar[int]
    ENCODED_SURROUND_OUTPUT_AUTO: ClassVar[int]
    ENCODED_SURROUND_OUTPUT_MANUAL: ClassVar[int]
    ENCODED_SURROUND_OUTPUT_NEVER: ClassVar[int]
    ENCODED_SURROUND_OUTPUT_UNKNOWN: ClassVar[int]
    ERROR: ClassVar[int]
    ERROR_DEAD_OBJECT: ClassVar[int]
    EXTRA_AUDIO_PLUG_STATE: ClassVar[str]
    EXTRA_ENCODINGS: ClassVar[str]
    EXTRA_MAX_CHANNEL_COUNT: ClassVar[str]
    EXTRA_RINGER_MODE: ClassVar[str]
    EXTRA_SCO_AUDIO_PREVIOUS_STATE: ClassVar[str]
    EXTRA_SCO_AUDIO_STATE: ClassVar[str]
    EXTRA_VIBRATE_SETTING: ClassVar[str]
    EXTRA_VIBRATE_TYPE: ClassVar[str]
    FLAG_ALLOW_RINGER_MODES: ClassVar[int]
    FLAG_PLAY_SOUND: ClassVar[int]
    FLAG_REMOVE_SOUND_AND_VIBRATE: ClassVar[int]
    FLAG_SHOW_UI: ClassVar[int]
    FLAG_VIBRATE: ClassVar[int]
    FX_BACK: ClassVar[int]
    FX_FOCUS_NAVIGATION_DOWN: ClassVar[int]
    FX_FOCUS_NAVIGATION_LEFT: ClassVar[int]
    FX_FOCUS_NAVIGATION_RIGHT: ClassVar[int]
    FX_FOCUS_NAVIGATION_UP: ClassVar[int]
    FX_KEYPRESS_DELETE: ClassVar[int]
    FX_KEYPRESS_INVALID: ClassVar[int]
    FX_KEYPRESS_RETURN: ClassVar[int]
    FX_KEYPRESS_SPACEBAR: ClassVar[int]
    FX_KEYPRESS_STANDARD: ClassVar[int]
    FX_KEY_CLICK: ClassVar[int]
    GET_DEVICES_ALL: ClassVar[int]
    GET_DEVICES_INPUTS: ClassVar[int]
    GET_DEVICES_OUTPUTS: ClassVar[int]
    MODE_CALL_REDIRECT: ClassVar[int]
    MODE_CALL_SCREENING: ClassVar[int]
    MODE_COMMUNICATION_REDIRECT: ClassVar[int]
    MODE_CURRENT: ClassVar[int]
    MODE_INVALID: ClassVar[int]
    MODE_IN_CALL: ClassVar[int]
    MODE_IN_COMMUNICATION: ClassVar[int]
    MODE_NORMAL: ClassVar[int]
    MODE_RINGTONE: ClassVar[int]
    NUM_STREAMS: ClassVar[int]
    PLAYBACK_OFFLOAD_GAPLESS_SUPPORTED: ClassVar[int]
    PLAYBACK_OFFLOAD_NOT_SUPPORTED: ClassVar[int]
    PLAYBACK_OFFLOAD_SUPPORTED: ClassVar[int]
    PROPERTY_OUTPUT_FRAMES_PER_BUFFER: ClassVar[str]
    PROPERTY_OUTPUT_SAMPLE_RATE: ClassVar[str]
    PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED: ClassVar[str]
    PROPERTY_SUPPORT_MIC_NEAR_ULTRASOUND: ClassVar[str]
    PROPERTY_SUPPORT_SPEAKER_NEAR_ULTRASOUND: ClassVar[str]
    RINGER_MODE_CHANGED_ACTION: ClassVar[str]
    RINGER_MODE_NORMAL: ClassVar[int]
    RINGER_MODE_SILENT: ClassVar[int]
    RINGER_MODE_VIBRATE: ClassVar[int]
    ROUTE_ALL: ClassVar[int]
    ROUTE_BLUETOOTH: ClassVar[int]
    ROUTE_BLUETOOTH_A2DP: ClassVar[int]
    ROUTE_BLUETOOTH_SCO: ClassVar[int]
    ROUTE_EARPIECE: ClassVar[int]
    ROUTE_HEADSET: ClassVar[int]
    ROUTE_SPEAKER: ClassVar[int]
    SCO_AUDIO_STATE_CONNECTED: ClassVar[int]
    SCO_AUDIO_STATE_CONNECTING: ClassVar[int]
    SCO_AUDIO_STATE_DISCONNECTED: ClassVar[int]
    SCO_AUDIO_STATE_ERROR: ClassVar[int]
    STREAM_ACCESSIBILITY: ClassVar[int]
    STREAM_ALARM: ClassVar[int]
    STREAM_DTMF: ClassVar[int]
    STREAM_MUSIC: ClassVar[int]
    STREAM_NOTIFICATION: ClassVar[int]
    STREAM_RING: ClassVar[int]
    STREAM_SYSTEM: ClassVar[int]
    STREAM_VOICE_CALL: ClassVar[int]
    USE_DEFAULT_STREAM_TYPE: ClassVar[int]
    VIBRATE_SETTING_CHANGED_ACTION: ClassVar[str]
    VIBRATE_SETTING_OFF: ClassVar[int]
    VIBRATE_SETTING_ON: ClassVar[int]
    VIBRATE_SETTING_ONLY_SILENT: ClassVar[int]
    VIBRATE_TYPE_NOTIFICATION: ClassVar[int]
    VIBRATE_TYPE_RINGER: ClassVar[int]
    def dispatchMediaKeyEvent(self, arg0: KeyEvent) -> None: ...
    def isVolumeFixed(self) -> bool: ...
    def adjustStreamVolume(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def adjustVolume(self, arg0: int, arg1: int) -> None: ...
    def adjustSuggestedStreamVolume(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def getRingerMode(self) -> int: ...
    def isRampingRingerEnabled(self) -> bool: ...
    def getStreamMaxVolume(self, arg0: int) -> int: ...
    def getStreamMinVolume(self, arg0: int) -> int: ...
    def getStreamVolume(self, arg0: int) -> int: ...
    def getStreamVolumeDb(self, arg0: int, arg1: int, arg2: int) -> float: ...
    def setRingerMode(self, arg0: int) -> None: ...
    def setStreamVolume(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def getVolumeGroupIdForAttributes(self, arg0: AudioAttributes) -> int: ...
    def adjustVolumeGroupVolume(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def isVolumeGroupMuted(self, arg0: int) -> bool: ...
    def setStreamSolo(self, arg0: int, arg1: bool) -> None: ...
    def setStreamMute(self, arg0: int, arg1: bool) -> None: ...
    def isStreamMute(self, arg0: int) -> bool: ...
    def shouldVibrate(self, arg0: int) -> bool: ...
    def getVibrateSetting(self, arg0: int) -> int: ...
    def setVibrateSetting(self, arg0: int, arg1: int) -> None: ...
    def setSpeakerphoneOn(self, arg0: bool) -> None: ...
    def isSpeakerphoneOn(self) -> bool: ...
    def setAllowedCapturePolicy(self, arg0: int) -> None: ...
    def getAllowedCapturePolicy(self) -> int: ...
    @staticmethod
    def getDirectPlaybackSupport(arg0: AudioFormat, arg1: AudioAttributes) -> int: ...
    @staticmethod
    def isOffloadedPlaybackSupported(arg0: AudioFormat, arg1: AudioAttributes) -> bool: ...
    @staticmethod
    def getPlaybackOffloadSupport(arg0: AudioFormat, arg1: AudioAttributes) -> int: ...
    def getSpatializer(self) -> Spatializer: ...
    def isBluetoothScoAvailableOffCall(self) -> bool: ...
    def startBluetoothSco(self) -> None: ...
    def stopBluetoothSco(self) -> None: ...
    def setBluetoothScoOn(self, arg0: bool) -> None: ...
    def isBluetoothScoOn(self) -> bool: ...
    def setBluetoothA2dpOn(self, arg0: bool) -> None: ...
    def isBluetoothA2dpOn(self) -> bool: ...
    def setWiredHeadsetOn(self, arg0: bool) -> None: ...
    def isWiredHeadsetOn(self) -> bool: ...
    def setMicrophoneMute(self, arg0: bool) -> None: ...
    def isMicrophoneMute(self) -> bool: ...
    def setMode(self, arg0: int) -> None: ...
    def getMode(self) -> int: ...
    def addOnModeChangedListener(self, arg0: Executor, arg1: "OnModeChangedListener") -> None: ...
    def removeOnModeChangedListener(self, arg0: "OnModeChangedListener") -> None: ...
    def isCallScreeningModeSupported(self) -> bool: ...
    def setRouting(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def getRouting(self, arg0: int) -> int: ...
    def isMusicActive(self) -> bool: ...
    def generateAudioSessionId(self) -> int: ...
    def setParameters(self, arg0: str) -> None: ...
    def getParameters(self, arg0: str) -> str: ...
    @overload
    def playSoundEffect(self, arg0: int) -> None: ...
    @overload
    def playSoundEffect(self, arg0: int, arg1: float) -> None: ...
    def loadSoundEffects(self) -> None: ...
    def unloadSoundEffects(self) -> None: ...
    @overload
    def requestAudioFocus(self, arg0: "OnAudioFocusChangeListener", arg1: int, arg2: int) -> int: ...
    @overload
    def requestAudioFocus(self, arg0: AudioFocusRequest) -> int: ...
    def abandonAudioFocusRequest(self, arg0: AudioFocusRequest) -> int: ...
    def abandonAudioFocus(self, arg0: "OnAudioFocusChangeListener") -> int: ...
    @overload
    def registerMediaButtonEventReceiver(self, arg0: ComponentName) -> None: ...
    @overload
    def registerMediaButtonEventReceiver(self, arg0: PendingIntent) -> None: ...
    @overload
    def unregisterMediaButtonEventReceiver(self, arg0: ComponentName) -> None: ...
    @overload
    def unregisterMediaButtonEventReceiver(self, arg0: PendingIntent) -> None: ...
    def registerRemoteControlClient(self, arg0: RemoteControlClient) -> None: ...
    def unregisterRemoteControlClient(self, arg0: RemoteControlClient) -> None: ...
    def registerRemoteController(self, arg0: RemoteController) -> bool: ...
    def unregisterRemoteController(self, arg0: RemoteController) -> None: ...
    def registerAudioPlaybackCallback(self, arg0: "AudioPlaybackCallback", arg1: Handler) -> None: ...
    def unregisterAudioPlaybackCallback(self, arg0: "AudioPlaybackCallback") -> None: ...
    def getActivePlaybackConfigurations(self) -> list: ...
    def registerAudioRecordingCallback(self, arg0: "AudioRecordingCallback", arg1: Handler) -> None: ...
    def unregisterAudioRecordingCallback(self, arg0: "AudioRecordingCallback") -> None: ...
    def getActiveRecordingConfigurations(self) -> list: ...
    def getAudioDevicesForAttributes(self, arg0: AudioAttributes) -> list: ...
    def getProperty(self, arg0: str) -> str: ...
    def getSupportedDeviceTypes(self, arg0: int) -> set: ...
    def getDevices(self, arg0: int) -> list[AudioDeviceInfo]: ...
    def registerAudioDeviceCallback(self, arg0: AudioDeviceCallback, arg1: Handler) -> None: ...
    def unregisterAudioDeviceCallback(self, arg0: AudioDeviceCallback) -> None: ...
    def getMicrophones(self) -> list: ...
    def setEncodedSurroundMode(self, arg0: int) -> bool: ...
    def getEncodedSurroundMode(self) -> int: ...
    def setSurroundFormatEnabled(self, arg0: int, arg1: bool) -> bool: ...
    def isSurroundFormatEnabled(self, arg0: int) -> bool: ...
    @staticmethod
    def isHapticPlaybackSupported() -> bool: ...
    def getAudioHwSyncForSession(self, arg0: int) -> int: ...
    def setCommunicationDevice(self, arg0: AudioDeviceInfo) -> bool: ...
    def clearCommunicationDevice(self) -> None: ...
    def getCommunicationDevice(self) -> AudioDeviceInfo: ...
    def getAvailableCommunicationDevices(self) -> list: ...
    def getDirectProfilesForAttributes(self, arg0: AudioAttributes) -> list: ...
    def addOnCommunicationDeviceChangedListener(self, arg0: Executor, arg1: "OnCommunicationDeviceChangedListener") -> None: ...
    def removeOnCommunicationDeviceChangedListener(self, arg0: "OnCommunicationDeviceChangedListener") -> None: ...
    def getSupportedMixerAttributes(self, arg0: AudioDeviceInfo) -> list: ...
    def setPreferredMixerAttributes(self, arg0: AudioAttributes, arg1: AudioDeviceInfo, arg2: AudioMixerAttributes) -> bool: ...
    def getPreferredMixerAttributes(self, arg0: AudioAttributes, arg1: AudioDeviceInfo) -> AudioMixerAttributes: ...
    def clearPreferredMixerAttributes(self, arg0: AudioAttributes, arg1: AudioDeviceInfo) -> bool: ...
    def addOnPreferredMixerAttributesChangedListener(self, arg0: Executor, arg1: "OnPreferredMixerAttributesChangedListener") -> None: ...
    def removeOnPreferredMixerAttributesChangedListener(self, arg0: "OnPreferredMixerAttributesChangedListener") -> None: ...

    class AudioPlaybackCallback:
        def __init__(self) -> None: ...
        def onPlaybackConfigChanged(self, arg0: list) -> None: ...

    class AudioRecordingCallback:
        def __init__(self) -> None: ...
        def onRecordingConfigChanged(self, arg0: list) -> None: ...

    class OnAudioFocusChangeListener:
        def onAudioFocusChange(self, arg0: int) -> None: ...

    class OnCommunicationDeviceChangedListener:
        def onCommunicationDeviceChanged(self, arg0: AudioDeviceInfo) -> None: ...

    class OnModeChangedListener:
        def onModeChanged(self, arg0: int) -> None: ...

    class OnPreferredMixerAttributesChangedListener:
        def onPreferredMixerAttributesChanged(self, arg0: AudioAttributes, arg1: AudioDeviceInfo, arg2: AudioMixerAttributes) -> None: ...
