from typing import Any, ClassVar, overload
from android.media.AudioFormat import AudioFormat
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AudioMixerAttributes:
    CREATOR: ClassVar[Creator]
    MIXER_BEHAVIOR_BIT_PERFECT: ClassVar[int]
    MIXER_BEHAVIOR_DEFAULT: ClassVar[int]
    def getFormat(self) -> AudioFormat: ...
    def getMixerBehavior(self) -> int: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self, arg0: AudioFormat) -> None: ...
        def build(self) -> "AudioMixerAttributes": ...
        def setMixerBehavior(self, arg0: int) -> "Builder": ...
