from typing import Any, ClassVar, overload
from android.media.projection.MediaProjection import MediaProjection

class AudioPlaybackCaptureConfiguration:
    def getMediaProjection(self) -> MediaProjection: ...
    def getMatchingUsages(self) -> list[int]: ...
    def getMatchingUids(self) -> list[int]: ...
    def getExcludeUsages(self) -> list[int]: ...
    def getExcludeUids(self) -> list[int]: ...

    class Builder:
        def __init__(self, arg0: MediaProjection) -> None: ...
        def addMatchingUsage(self, arg0: int) -> "Builder": ...
        def addMatchingUid(self, arg0: int) -> "Builder": ...
        def excludeUsage(self, arg0: int) -> "Builder": ...
        def excludeUid(self, arg0: int) -> "Builder": ...
        def build(self) -> "AudioPlaybackCaptureConfiguration": ...
