from typing import Any, ClassVar, overload

class AudioDeviceInfo:
    TYPE_AUX_LINE: ClassVar[int]
    TYPE_BLE_BROADCAST: ClassVar[int]
    TYPE_BLE_HEADSET: ClassVar[int]
    TYPE_BLE_SPEAKER: ClassVar[int]
    TYPE_BLUETOOTH_A2DP: ClassVar[int]
    TYPE_BLUETOOTH_SCO: ClassVar[int]
    TYPE_BUILTIN_EARPIECE: ClassVar[int]
    TYPE_BUILTIN_MIC: ClassVar[int]
    TYPE_BUILTIN_SPEAKER: ClassVar[int]
    TYPE_BUILTIN_SPEAKER_SAFE: ClassVar[int]
    TYPE_BUS: ClassVar[int]
    TYPE_DOCK: ClassVar[int]
    TYPE_DOCK_ANALOG: ClassVar[int]
    TYPE_FM: ClassVar[int]
    TYPE_FM_TUNER: ClassVar[int]
    TYPE_HDMI: ClassVar[int]
    TYPE_HDMI_ARC: ClassVar[int]
    TYPE_HDMI_EARC: ClassVar[int]
    TYPE_HEARING_AID: ClassVar[int]
    TYPE_IP: ClassVar[int]
    TYPE_LINE_ANALOG: ClassVar[int]
    TYPE_LINE_DIGITAL: ClassVar[int]
    TYPE_REMOTE_SUBMIX: ClassVar[int]
    TYPE_TELEPHONY: ClassVar[int]
    TYPE_TV_TUNER: ClassVar[int]
    TYPE_UNKNOWN: ClassVar[int]
    TYPE_USB_ACCESSORY: ClassVar[int]
    TYPE_USB_DEVICE: ClassVar[int]
    TYPE_USB_HEADSET: ClassVar[int]
    TYPE_WIRED_HEADPHONES: ClassVar[int]
    TYPE_WIRED_HEADSET: ClassVar[int]
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getId(self) -> int: ...
    def getProductName(self) -> str: ...
    def getAddress(self) -> str: ...
    def isSource(self) -> bool: ...
    def isSink(self) -> bool: ...
    def getSampleRates(self) -> list[int]: ...
    def getChannelMasks(self) -> list[int]: ...
    def getChannelIndexMasks(self) -> list[int]: ...
    def getChannelCounts(self) -> list[int]: ...
    def getEncodings(self) -> list[int]: ...
    def getAudioProfiles(self) -> list: ...
    def getAudioDescriptors(self) -> list: ...
    def getEncapsulationModes(self) -> list[int]: ...
    def getEncapsulationMetadataTypes(self) -> list[int]: ...
    def getType(self) -> int: ...
