from typing import Any, ClassVar, overload
from android.media.AudioDeviceInfo import AudioDeviceInfo

class AudioDeviceCallback:
    def __init__(self) -> None: ...
    def onAudioDevicesAdded(self, arg0: list[AudioDeviceInfo]) -> None: ...
    def onAudioDevicesRemoved(self, arg0: list[AudioDeviceInfo]) -> None: ...
