from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.media.AudioAttributes import AudioAttributes
from android.media.AudioDeviceInfo import AudioDeviceInfo
from android.media.AudioFormat import AudioFormat
from android.media.AudioMetadataReadMap import AudioMetadataReadMap
from android.media.AudioPresentation import AudioPresentation
from android.media.AudioRouting import AudioRouting
from android.media.AudioTimestamp import AudioTimestamp
from android.media.PlaybackParams import PlaybackParams
from android.media.VolumeShaper import VolumeShaper
from android.media.metrics.LogSessionId import LogSessionId
from android.os.Handler import Handler
from android.os.PersistableBundle import PersistableBundle
from java.nio.ByteBuffer import ByteBuffer
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Configuration:
    """Forward declaration for ``android.media.VolumeShaper.Configuration``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.VolumeShaper.Configuration')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/VolumeShaper/Configuration
    """
    ...

class AudioTrack:
    DUAL_MONO_MODE_LL: ClassVar[int]
    DUAL_MONO_MODE_LR: ClassVar[int]
    DUAL_MONO_MODE_OFF: ClassVar[int]
    DUAL_MONO_MODE_RR: ClassVar[int]
    ENCAPSULATION_METADATA_TYPE_DVB_AD_DESCRIPTOR: ClassVar[int]
    ENCAPSULATION_METADATA_TYPE_FRAMEWORK_TUNER: ClassVar[int]
    ENCAPSULATION_METADATA_TYPE_SUPPLEMENTARY_AUDIO_PLACEMENT: ClassVar[int]
    ENCAPSULATION_MODE_ELEMENTARY_STREAM: ClassVar[int]
    ENCAPSULATION_MODE_NONE: ClassVar[int]
    ERROR: ClassVar[int]
    ERROR_BAD_VALUE: ClassVar[int]
    ERROR_DEAD_OBJECT: ClassVar[int]
    ERROR_INVALID_OPERATION: ClassVar[int]
    MODE_STATIC: ClassVar[int]
    MODE_STREAM: ClassVar[int]
    PERFORMANCE_MODE_LOW_LATENCY: ClassVar[int]
    PERFORMANCE_MODE_NONE: ClassVar[int]
    PERFORMANCE_MODE_POWER_SAVING: ClassVar[int]
    PLAYSTATE_PAUSED: ClassVar[int]
    PLAYSTATE_PLAYING: ClassVar[int]
    PLAYSTATE_STOPPED: ClassVar[int]
    STATE_INITIALIZED: ClassVar[int]
    STATE_NO_STATIC_DATA: ClassVar[int]
    STATE_UNINITIALIZED: ClassVar[int]
    SUCCESS: ClassVar[int]
    SUPPLEMENTARY_AUDIO_PLACEMENT_LEFT: ClassVar[int]
    SUPPLEMENTARY_AUDIO_PLACEMENT_NORMAL: ClassVar[int]
    SUPPLEMENTARY_AUDIO_PLACEMENT_RIGHT: ClassVar[int]
    WRITE_BLOCKING: ClassVar[int]
    WRITE_NON_BLOCKING: ClassVar[int]
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int) -> None: ...
    @overload
    def __init__(self, arg0: AudioAttributes, arg1: AudioFormat, arg2: int, arg3: int, arg4: int) -> None: ...
    def setOffloadDelayPadding(self, arg0: int, arg1: int) -> None: ...
    def getOffloadDelay(self) -> int: ...
    def getOffloadPadding(self) -> int: ...
    def setOffloadEndOfStream(self) -> None: ...
    def isOffloadedPlayback(self) -> bool: ...
    @staticmethod
    def isDirectPlaybackSupported(arg0: AudioFormat, arg1: AudioAttributes) -> bool: ...
    def setAudioDescriptionMixLeveldB(self, arg0: float) -> bool: ...
    def getAudioDescriptionMixLeveldB(self) -> float: ...
    def setDualMonoMode(self, arg0: int) -> bool: ...
    def getDualMonoMode(self) -> int: ...
    def release(self) -> None: ...
    def finalize(self) -> None: ...
    @staticmethod
    def getMinVolume() -> float: ...
    @staticmethod
    def getMaxVolume() -> float: ...
    def getSampleRate(self) -> int: ...
    def getPlaybackRate(self) -> int: ...
    def getPlaybackParams(self) -> PlaybackParams: ...
    def getAudioAttributes(self) -> AudioAttributes: ...
    def getAudioFormat(self) -> int: ...
    def getStreamType(self) -> int: ...
    def getChannelConfiguration(self) -> int: ...
    def getFormat(self) -> AudioFormat: ...
    def getChannelCount(self) -> int: ...
    def getState(self) -> int: ...
    def getPlayState(self) -> int: ...
    def getBufferSizeInFrames(self) -> int: ...
    def setBufferSizeInFrames(self, arg0: int) -> int: ...
    def getBufferCapacityInFrames(self) -> int: ...
    def setStartThresholdInFrames(self, arg0: int) -> int: ...
    def getStartThresholdInFrames(self) -> int: ...
    def getNativeFrameCount(self) -> int: ...
    def getNotificationMarkerPosition(self) -> int: ...
    def getPositionNotificationPeriod(self) -> int: ...
    def getPlaybackHeadPosition(self) -> int: ...
    def getUnderrunCount(self) -> int: ...
    def getPerformanceMode(self) -> int: ...
    @staticmethod
    def getNativeOutputSampleRate(arg0: int) -> int: ...
    @staticmethod
    def getMinBufferSize(arg0: int, arg1: int, arg2: int) -> int: ...
    def getAudioSessionId(self) -> int: ...
    def getTimestamp(self, arg0: AudioTimestamp) -> bool: ...
    def getMetrics(self) -> PersistableBundle: ...
    @overload
    def setPlaybackPositionUpdateListener(self, arg0: "OnPlaybackPositionUpdateListener") -> None: ...
    @overload
    def setPlaybackPositionUpdateListener(self, arg0: "OnPlaybackPositionUpdateListener", arg1: Handler) -> None: ...
    def setStereoVolume(self, arg0: float, arg1: float) -> int: ...
    def setVolume(self, arg0: float) -> int: ...
    def createVolumeShaper(self, arg0: Configuration) -> VolumeShaper: ...
    def setPlaybackRate(self, arg0: int) -> int: ...
    def setPlaybackParams(self, arg0: PlaybackParams) -> None: ...
    def setNotificationMarkerPosition(self, arg0: int) -> int: ...
    def setPositionNotificationPeriod(self, arg0: int) -> int: ...
    def setPlaybackHeadPosition(self, arg0: int) -> int: ...
    def setLoopPoints(self, arg0: int, arg1: int, arg2: int) -> int: ...
    def setPresentation(self, arg0: AudioPresentation) -> int: ...
    def setState(self, arg0: int) -> None: ...
    def play(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def flush(self) -> None: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int, arg3: int) -> int: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int, arg3: int) -> int: ...
    @overload
    def write(self, arg0: list[float], arg1: int, arg2: int, arg3: int) -> int: ...
    @overload
    def write(self, arg0: ByteBuffer, arg1: int, arg2: int) -> int: ...
    @overload
    def write(self, arg0: ByteBuffer, arg1: int, arg2: int, arg3: int) -> int: ...
    def reloadStaticData(self) -> int: ...
    def attachAuxEffect(self, arg0: int) -> int: ...
    def setAuxEffectSendLevel(self, arg0: float) -> int: ...
    def setPreferredDevice(self, arg0: AudioDeviceInfo) -> bool: ...
    def getPreferredDevice(self) -> AudioDeviceInfo: ...
    def getRoutedDevice(self) -> AudioDeviceInfo: ...
    @overload
    def addOnRoutingChangedListener(self, arg0: "OnRoutingChangedListener", arg1: Handler) -> None: ...
    @overload
    def addOnRoutingChangedListener(self, arg0: "OnRoutingChangedListener", arg1: Handler) -> None: ...
    @overload
    def removeOnRoutingChangedListener(self, arg0: "OnRoutingChangedListener") -> None: ...
    @overload
    def removeOnRoutingChangedListener(self, arg0: "OnRoutingChangedListener") -> None: ...
    def addOnCodecFormatChangedListener(self, arg0: Executor, arg1: "OnCodecFormatChangedListener") -> None: ...
    def removeOnCodecFormatChangedListener(self, arg0: "OnCodecFormatChangedListener") -> None: ...
    def registerStreamEventCallback(self, arg0: Executor, arg1: "StreamEventCallback") -> None: ...
    def unregisterStreamEventCallback(self, arg0: "StreamEventCallback") -> None: ...
    def setLogSessionId(self, arg0: LogSessionId) -> None: ...
    def getLogSessionId(self) -> LogSessionId: ...

    class Builder:
        def __init__(self) -> None: ...
        def setContext(self, arg0: Context) -> "Builder": ...
        def setAudioAttributes(self, arg0: AudioAttributes) -> "Builder": ...
        def setAudioFormat(self, arg0: AudioFormat) -> "Builder": ...
        def setBufferSizeInBytes(self, arg0: int) -> "Builder": ...
        def setEncapsulationMode(self, arg0: int) -> "Builder": ...
        def setTransferMode(self, arg0: int) -> "Builder": ...
        def setSessionId(self, arg0: int) -> "Builder": ...
        def setPerformanceMode(self, arg0: int) -> "Builder": ...
        def setOffloadedPlayback(self, arg0: bool) -> "Builder": ...
        def build(self) -> "AudioTrack": ...

    class MetricsConstants:
        CHANNELMASK: ClassVar[str]
        CONTENTTYPE: ClassVar[str]
        SAMPLERATE: ClassVar[str]
        STREAMTYPE: ClassVar[str]
        USAGE: ClassVar[str]

    class OnCodecFormatChangedListener:
        def onCodecFormatChanged(self, arg0: "AudioTrack", arg1: AudioMetadataReadMap) -> None: ...

    class OnPlaybackPositionUpdateListener:
        def onMarkerReached(self, arg0: "AudioTrack") -> None: ...
        def onPeriodicNotification(self, arg0: "AudioTrack") -> None: ...

    class OnRoutingChangedListener:
        @overload
        def onRoutingChanged(self, arg0: "AudioTrack") -> None: ...
        @overload
        def onRoutingChanged(self, arg0: AudioRouting) -> None: ...

    class StreamEventCallback:
        def __init__(self) -> None: ...
        def onTearDown(self, arg0: "AudioTrack") -> None: ...
        def onPresentationEnded(self, arg0: "AudioTrack") -> None: ...
        def onDataRequest(self, arg0: "AudioTrack", arg1: int) -> None: ...
