from typing import Any, ClassVar, overload
from android.media.AudioAttributes import AudioAttributes
from android.os.Handler import Handler

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OnAudioFocusChangeListener:
    """Forward declaration for ``android.media.AudioManager.OnAudioFocusChangeListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.AudioManager.OnAudioFocusChangeListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/AudioManager/OnAudioFocusChangeListener
    """
    ...

class AudioFocusRequest:
    def getAudioAttributes(self) -> AudioAttributes: ...
    def getFocusGain(self) -> int: ...
    def willPauseWhenDucked(self) -> bool: ...
    def acceptsDelayedFocusGain(self) -> bool: ...

    class Builder:
        @overload
        def __init__(self, arg0: int) -> None: ...
        @overload
        def __init__(self, arg0: "AudioFocusRequest") -> None: ...
        def setFocusGain(self, arg0: int) -> "Builder": ...
        @overload
        def setOnAudioFocusChangeListener(self, arg0: OnAudioFocusChangeListener) -> "Builder": ...
        @overload
        def setOnAudioFocusChangeListener(self, arg0: OnAudioFocusChangeListener, arg1: Handler) -> "Builder": ...
        def setAudioAttributes(self, arg0: AudioAttributes) -> "Builder": ...
        def setWillPauseWhenDucked(self, arg0: bool) -> "Builder": ...
        def setAcceptsDelayedFocusGain(self, arg0: bool) -> "Builder": ...
        def setForceDucking(self, arg0: bool) -> "Builder": ...
        def build(self) -> "AudioFocusRequest": ...
