from typing import Any, ClassVar, overload
from android.media.Image import Image
from android.os.Handler import Handler
from android.view.Surface import Surface

class ImageReader:
    @overload
    @staticmethod
    def newInstance(arg0: int, arg1: int, arg2: int, arg3: int) -> "ImageReader": ...
    @overload
    @staticmethod
    def newInstance(arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> "ImageReader": ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getImageFormat(self) -> int: ...
    def getHardwareBufferFormat(self) -> int: ...
    def getDataSpace(self) -> int: ...
    def getMaxImages(self) -> int: ...
    def getUsage(self) -> int: ...
    def getSurface(self) -> Surface: ...
    def acquireLatestImage(self) -> Image: ...
    def acquireNextImage(self) -> Image: ...
    def setOnImageAvailableListener(self, arg0: "OnImageAvailableListener", arg1: Handler) -> None: ...
    def close(self) -> None: ...
    def discardFreeBuffers(self) -> None: ...
    def finalize(self) -> None: ...

    class Builder:
        def __init__(self, arg0: int, arg1: int) -> None: ...
        def setMaxImages(self, arg0: int) -> "Builder": ...
        def setUsage(self, arg0: int) -> "Builder": ...
        def setImageFormat(self, arg0: int) -> "Builder": ...
        def setDefaultHardwareBufferFormat(self, arg0: int) -> "Builder": ...
        def setDefaultDataSpace(self, arg0: int) -> "Builder": ...
        def build(self) -> "ImageReader": ...

    class OnImageAvailableListener:
        def onImageAvailable(self, arg0: "ImageReader") -> None: ...
