from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.hardware.HardwareBuffer import HardwareBuffer
from android.hardware.SyncFence import SyncFence
from java.nio.ByteBuffer import ByteBuffer

class Image:
    def getFormat(self) -> int: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getTimestamp(self) -> int: ...
    def getFence(self) -> SyncFence: ...
    def getHardwareBuffer(self) -> HardwareBuffer: ...
    def setTimestamp(self, arg0: int) -> None: ...
    def setFence(self, arg0: SyncFence) -> None: ...
    def getDataSpace(self) -> int: ...
    def setDataSpace(self, arg0: int) -> None: ...
    def getCropRect(self) -> Rect: ...
    def setCropRect(self, arg0: Rect) -> None: ...
    def getPlanes(self) -> list["Plane"]: ...
    def close(self) -> None: ...

    class Plane:
        def getRowStride(self) -> int: ...
        def getPixelStride(self) -> int: ...
        def getBuffer(self) -> ByteBuffer: ...
