from typing import Any, ClassVar, overload
from android.media.Image import Image
from android.os.Handler import Handler
from android.view.Surface import Surface

class ImageWriter:
    @overload
    @staticmethod
    def newInstance(arg0: Surface, arg1: int) -> "ImageWriter": ...
    @overload
    @staticmethod
    def newInstance(arg0: Surface, arg1: int, arg2: int) -> "ImageWriter": ...
    def getMaxImages(self) -> int: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def dequeueInputImage(self) -> Image: ...
    def queueInputImage(self, arg0: Image) -> None: ...
    def getFormat(self) -> int: ...
    def getUsage(self) -> int: ...
    def getHardwareBufferFormat(self) -> int: ...
    def getDataSpace(self) -> int: ...
    def setOnImageReleasedListener(self, arg0: "OnImageReleasedListener", arg1: Handler) -> None: ...
    def close(self) -> None: ...
    def finalize(self) -> None: ...

    class Builder:
        def __init__(self, arg0: Surface) -> None: ...
        def setWidthAndHeight(self, arg0: int, arg1: int) -> "Builder": ...
        def setMaxImages(self, arg0: int) -> "Builder": ...
        def setImageFormat(self, arg0: int) -> "Builder": ...
        def setHardwareBufferFormat(self, arg0: int) -> "Builder": ...
        def setDataSpace(self, arg0: int) -> "Builder": ...
        def setUsage(self, arg0: int) -> "Builder": ...
        def build(self) -> "ImageWriter": ...

    class OnImageReleasedListener:
        def onImageReleased(self, arg0: "ImageWriter") -> None: ...
