from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["MediaRouter"]

class MediaRouter(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/MediaRouter"
    CALLBACK_FLAG_PERFORM_ACTIVE_SCAN = JavaStaticField("I")
    CALLBACK_FLAG_UNFILTERED_EVENTS = JavaStaticField("I")
    ROUTE_TYPE_LIVE_AUDIO = JavaStaticField("I")
    ROUTE_TYPE_LIVE_VIDEO = JavaStaticField("I")
    ROUTE_TYPE_USER = JavaStaticField("I")
    getDefaultRoute = JavaMethod("()Landroid/media/MediaRouter$RouteInfo;")
    getSelectedRoute = JavaMethod("(I)Landroid/media/MediaRouter$RouteInfo;")
    addCallback = JavaMultipleMethod([("(ILandroid/media/MediaRouter$Callback;)V", False, False), ("(ILandroid/media/MediaRouter$Callback;I)V", False, False)])
    removeCallback = JavaMethod("(Landroid/media/MediaRouter$Callback;)V")
    selectRoute = JavaMethod("(ILandroid/media/MediaRouter$RouteInfo;)V")
    addUserRoute = JavaMethod("(Landroid/media/MediaRouter$UserRouteInfo;)V")
    removeUserRoute = JavaMethod("(Landroid/media/MediaRouter$UserRouteInfo;)V")
    clearUserRoutes = JavaMethod("()V")
    getCategoryCount = JavaMethod("()I")
    getCategoryAt = JavaMethod("(I)Landroid/media/MediaRouter$RouteCategory;")
    getRouteCount = JavaMethod("()I")
    getRouteAt = JavaMethod("(I)Landroid/media/MediaRouter$RouteInfo;")
    createUserRoute = JavaMethod("(Landroid/media/MediaRouter$RouteCategory;)Landroid/media/MediaRouter$UserRouteInfo;")
    createRouteCategory = JavaMultipleMethod([("(Ljava/lang/CharSequence;Z)Landroid/media/MediaRouter$RouteCategory;", False, False), ("(IZ)Landroid/media/MediaRouter$RouteCategory;", False, False)])

    class Callback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/MediaRouter/Callback"
        __javaconstructor__ = [("()V", False)]
        onRouteSelected = JavaMethod("(Landroid/media/MediaRouter;ILandroid/media/MediaRouter$RouteInfo;)V")
        onRouteUnselected = JavaMethod("(Landroid/media/MediaRouter;ILandroid/media/MediaRouter$RouteInfo;)V")
        onRouteAdded = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")
        onRouteRemoved = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")
        onRouteChanged = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")
        onRouteGrouped = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;Landroid/media/MediaRouter$RouteGroup;I)V")
        onRouteUngrouped = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;Landroid/media/MediaRouter$RouteGroup;)V")
        onRouteVolumeChanged = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")
        onRoutePresentationDisplayChanged = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")

    class RouteCategory(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/MediaRouter/RouteCategory"
        getName = JavaMultipleMethod([("()Ljava/lang/CharSequence;", False, False), ("(Landroid/content/Context;)Ljava/lang/CharSequence;", False, False)])
        getRoutes = JavaMethod("(Ljava/util/List;)Ljava/util/List;")
        getSupportedTypes = JavaMethod("()I")
        isGroupable = JavaMethod("()Z")
        toString = JavaMethod("()Ljava/lang/String;")

    class RouteGroup(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/MediaRouter/RouteGroup"
        addRoute = JavaMultipleMethod([("(Landroid/media/MediaRouter$RouteInfo;)V", False, False), ("(Landroid/media/MediaRouter$RouteInfo;I)V", False, False)])
        removeRoute = JavaMultipleMethod([("(Landroid/media/MediaRouter$RouteInfo;)V", False, False), ("(I)V", False, False)])
        getRouteCount = JavaMethod("()I")
        getRouteAt = JavaMethod("(I)Landroid/media/MediaRouter$RouteInfo;")
        setIconDrawable = JavaMethod("(Landroid/graphics/drawable/Drawable;)V")
        setIconResource = JavaMethod("(I)V")
        requestSetVolume = JavaMethod("(I)V")
        requestUpdateVolume = JavaMethod("(I)V")
        toString = JavaMethod("()Ljava/lang/String;")

    class RouteInfo(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/MediaRouter/RouteInfo"
        DEVICE_TYPE_BLUETOOTH = JavaStaticField("I")
        DEVICE_TYPE_SPEAKER = JavaStaticField("I")
        DEVICE_TYPE_TV = JavaStaticField("I")
        DEVICE_TYPE_UNKNOWN = JavaStaticField("I")
        PLAYBACK_TYPE_LOCAL = JavaStaticField("I")
        PLAYBACK_TYPE_REMOTE = JavaStaticField("I")
        PLAYBACK_VOLUME_FIXED = JavaStaticField("I")
        PLAYBACK_VOLUME_VARIABLE = JavaStaticField("I")
        getName = JavaMultipleMethod([("()Ljava/lang/CharSequence;", False, False), ("(Landroid/content/Context;)Ljava/lang/CharSequence;", False, False)])
        getDescription = JavaMethod("()Ljava/lang/CharSequence;")
        getStatus = JavaMethod("()Ljava/lang/CharSequence;")
        getSupportedTypes = JavaMethod("()I")
        getDeviceType = JavaMethod("()I")
        getGroup = JavaMethod("()Landroid/media/MediaRouter$RouteGroup;")
        getCategory = JavaMethod("()Landroid/media/MediaRouter$RouteCategory;")
        getIconDrawable = JavaMethod("()Landroid/graphics/drawable/Drawable;")
        setTag = JavaMethod("(Ljava/lang/Object;)V")
        getTag = JavaMethod("()Ljava/lang/Object;")
        getPlaybackType = JavaMethod("()I")
        getPlaybackStream = JavaMethod("()I")
        getVolume = JavaMethod("()I")
        requestSetVolume = JavaMethod("(I)V")
        requestUpdateVolume = JavaMethod("(I)V")
        getVolumeMax = JavaMethod("()I")
        getVolumeHandling = JavaMethod("()I")
        getPresentationDisplay = JavaMethod("()Landroid/view/Display;")
        isEnabled = JavaMethod("()Z")
        isConnecting = JavaMethod("()Z")
        toString = JavaMethod("()Ljava/lang/String;")

    class SimpleCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/MediaRouter/SimpleCallback"
        __javaconstructor__ = [("()V", False)]
        onRouteSelected = JavaMethod("(Landroid/media/MediaRouter;ILandroid/media/MediaRouter$RouteInfo;)V")
        onRouteUnselected = JavaMethod("(Landroid/media/MediaRouter;ILandroid/media/MediaRouter$RouteInfo;)V")
        onRouteAdded = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")
        onRouteRemoved = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")
        onRouteChanged = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")
        onRouteGrouped = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;Landroid/media/MediaRouter$RouteGroup;I)V")
        onRouteUngrouped = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;Landroid/media/MediaRouter$RouteGroup;)V")
        onRouteVolumeChanged = JavaMethod("(Landroid/media/MediaRouter;Landroid/media/MediaRouter$RouteInfo;)V")

    class UserRouteInfo(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/MediaRouter/UserRouteInfo"
        setName = JavaMultipleMethod([("(Ljava/lang/CharSequence;)V", False, False), ("(I)V", False, False)])
        setDescription = JavaMethod("(Ljava/lang/CharSequence;)V")
        setStatus = JavaMethod("(Ljava/lang/CharSequence;)V")
        setRemoteControlClient = JavaMethod("(Landroid/media/RemoteControlClient;)V")
        getRemoteControlClient = JavaMethod("()Landroid/media/RemoteControlClient;")
        setIconDrawable = JavaMethod("(Landroid/graphics/drawable/Drawable;)V")
        setIconResource = JavaMethod("(I)V")
        setVolumeCallback = JavaMethod("(Landroid/media/MediaRouter$VolumeCallback;)V")
        setPlaybackType = JavaMethod("(I)V")
        setVolumeHandling = JavaMethod("(I)V")
        setVolume = JavaMethod("(I)V")
        requestSetVolume = JavaMethod("(I)V")
        requestUpdateVolume = JavaMethod("(I)V")
        setVolumeMax = JavaMethod("(I)V")
        setPlaybackStream = JavaMethod("(I)V")

    class VolumeCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/MediaRouter/VolumeCallback"
        __javaconstructor__ = [("()V", False)]
        onVolumeUpdateRequest = JavaMethod("(Landroid/media/MediaRouter$RouteInfo;I)V")
        onVolumeSetRequest = JavaMethod("(Landroid/media/MediaRouter$RouteInfo;I)V")