from typing import Any, ClassVar, overload
from android.app.Notification import Notification
from android.content.Intent import Intent
from android.media.MediaSession2 import MediaSession2
from android.os.IBinder import IBinder

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class ControllerInfo:
    """Forward declaration for ``android.media.MediaSession2.ControllerInfo``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.MediaSession2.ControllerInfo')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/MediaSession2/ControllerInfo
    """
    ...

class MediaSession2Service:
    SERVICE_INTERFACE: ClassVar[str]
    def __init__(self) -> None: ...
    def onCreate(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onDestroy(self) -> None: ...
    def onGetSession(self, arg0: ControllerInfo) -> MediaSession2: ...
    def onUpdateNotification(self, arg0: MediaSession2) -> "MediaNotification": ...
    def addSession(self, arg0: MediaSession2) -> None: ...
    def removeSession(self, arg0: MediaSession2) -> None: ...
    def getSessions(self) -> list: ...

    class MediaNotification:
        def __init__(self, arg0: int, arg1: Notification) -> None: ...
        def getNotificationId(self) -> int: ...
        def getNotification(self) -> Notification: ...
