from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.media.MediaDescription import MediaDescription
from android.media.Rating import Rating
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class MediaMetadata:
    CREATOR: ClassVar[Creator]
    METADATA_KEY_ALBUM: ClassVar[str]
    METADATA_KEY_ALBUM_ART: ClassVar[str]
    METADATA_KEY_ALBUM_ARTIST: ClassVar[str]
    METADATA_KEY_ALBUM_ART_URI: ClassVar[str]
    METADATA_KEY_ART: ClassVar[str]
    METADATA_KEY_ARTIST: ClassVar[str]
    METADATA_KEY_ART_URI: ClassVar[str]
    METADATA_KEY_AUTHOR: ClassVar[str]
    METADATA_KEY_BT_FOLDER_TYPE: ClassVar[str]
    METADATA_KEY_COMPILATION: ClassVar[str]
    METADATA_KEY_COMPOSER: ClassVar[str]
    METADATA_KEY_DATE: ClassVar[str]
    METADATA_KEY_DISC_NUMBER: ClassVar[str]
    METADATA_KEY_DISPLAY_DESCRIPTION: ClassVar[str]
    METADATA_KEY_DISPLAY_ICON: ClassVar[str]
    METADATA_KEY_DISPLAY_ICON_URI: ClassVar[str]
    METADATA_KEY_DISPLAY_SUBTITLE: ClassVar[str]
    METADATA_KEY_DISPLAY_TITLE: ClassVar[str]
    METADATA_KEY_DURATION: ClassVar[str]
    METADATA_KEY_GENRE: ClassVar[str]
    METADATA_KEY_MEDIA_ID: ClassVar[str]
    METADATA_KEY_MEDIA_URI: ClassVar[str]
    METADATA_KEY_NUM_TRACKS: ClassVar[str]
    METADATA_KEY_RATING: ClassVar[str]
    METADATA_KEY_TITLE: ClassVar[str]
    METADATA_KEY_TRACK_NUMBER: ClassVar[str]
    METADATA_KEY_USER_RATING: ClassVar[str]
    METADATA_KEY_WRITER: ClassVar[str]
    METADATA_KEY_YEAR: ClassVar[str]
    def containsKey(self, arg0: str) -> bool: ...
    def getText(self, arg0: str) -> str: ...
    def getString(self, arg0: str) -> str: ...
    def getLong(self, arg0: str) -> int: ...
    def getRating(self, arg0: str) -> Rating: ...
    def getBitmap(self, arg0: str) -> Bitmap: ...
    def getBitmapDimensionLimit(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def size(self) -> int: ...
    def keySet(self) -> set: ...
    def getDescription(self) -> MediaDescription: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: "MediaMetadata") -> None: ...
        def putText(self, arg0: str, arg1: str) -> "Builder": ...
        def putString(self, arg0: str, arg1: str) -> "Builder": ...
        def putLong(self, arg0: str, arg1: int) -> "Builder": ...
        def putRating(self, arg0: str, arg1: Rating) -> "Builder": ...
        def putBitmap(self, arg0: str, arg1: Bitmap) -> "Builder": ...
        def setBitmapDimensionLimit(self, arg0: int) -> "Builder": ...
        def build(self) -> "MediaMetadata": ...
