from typing import Any, ClassVar, overload

class MediaDrmException:
    def __init__(self, arg0: str) -> None: ...
    def getVendorError(self) -> int: ...
    def getOemError(self) -> int: ...
    def getErrorContext(self) -> int: ...
