from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.net.Uri import Uri
from android.os.IBinder import IBinder

class MediaScannerConnection:
    def __init__(self, arg0: Context, arg1: "MediaScannerConnectionClient") -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self) -> bool: ...
    @overload
    def scanFile(self, arg0: str, arg1: str) -> None: ...
    @overload
    @staticmethod
    def scanFile(arg0: Context, arg1: list[str], arg2: list[str], arg3: "OnScanCompletedListener") -> None: ...
    def onServiceConnected(self, arg0: ComponentName, arg1: IBinder) -> None: ...
    def onServiceDisconnected(self, arg0: ComponentName) -> None: ...

    class MediaScannerConnectionClient:
        def onMediaScannerConnected(self) -> None: ...

    class OnScanCompletedListener:
        def onScanCompleted(self, arg0: str, arg1: Uri) -> None: ...
