from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.hardware.Camera import Camera
from android.media.AudioDeviceInfo import AudioDeviceInfo
from android.media.AudioRecordingConfiguration import AudioRecordingConfiguration
from android.media.CamcorderProfile import CamcorderProfile
from android.media.metrics.LogSessionId import LogSessionId
from android.os.Handler import Handler
from android.os.PersistableBundle import PersistableBundle
from android.view.Surface import Surface
from java.io.File import File
from java.io.FileDescriptor import FileDescriptor
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class AudioProfile:
    """Forward declaration for ``android.media.EncoderProfiles.AudioProfile``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.EncoderProfiles.AudioProfile')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/EncoderProfiles/AudioProfile
    """
    ...
class VideoProfile:
    """Forward declaration for ``android.media.EncoderProfiles.VideoProfile``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.EncoderProfiles.VideoProfile')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/EncoderProfiles/VideoProfile
    """
    ...
class OnRoutingChangedListener:
    """Forward declaration for ``android.media.AudioRouting.OnRoutingChangedListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.AudioRouting.OnRoutingChangedListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/AudioRouting/OnRoutingChangedListener
    """
    ...
class AudioRecordingCallback:
    """Forward declaration for ``android.media.AudioManager.AudioRecordingCallback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.AudioManager.AudioRecordingCallback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/AudioManager/AudioRecordingCallback
    """
    ...

class MediaRecorder:
    MEDIA_ERROR_SERVER_DIED: ClassVar[int]
    MEDIA_RECORDER_ERROR_UNKNOWN: ClassVar[int]
    MEDIA_RECORDER_INFO_MAX_DURATION_REACHED: ClassVar[int]
    MEDIA_RECORDER_INFO_MAX_FILESIZE_APPROACHING: ClassVar[int]
    MEDIA_RECORDER_INFO_MAX_FILESIZE_REACHED: ClassVar[int]
    MEDIA_RECORDER_INFO_NEXT_OUTPUT_FILE_STARTED: ClassVar[int]
    MEDIA_RECORDER_INFO_UNKNOWN: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Context) -> None: ...
    def setLogSessionId(self, arg0: LogSessionId) -> None: ...
    def getLogSessionId(self) -> LogSessionId: ...
    def setCamera(self, arg0: Camera) -> None: ...
    def getSurface(self) -> Surface: ...
    def setInputSurface(self, arg0: Surface) -> None: ...
    def setPreviewDisplay(self, arg0: Surface) -> None: ...
    def setAudioSource(self, arg0: int) -> None: ...
    @staticmethod
    def getAudioSourceMax() -> int: ...
    def setPrivacySensitive(self, arg0: bool) -> None: ...
    def isPrivacySensitive(self) -> bool: ...
    def setVideoSource(self, arg0: int) -> None: ...
    def setProfile(self, arg0: CamcorderProfile) -> None: ...
    def setAudioProfile(self, arg0: AudioProfile) -> None: ...
    def setVideoProfile(self, arg0: VideoProfile) -> None: ...
    def setCaptureRate(self, arg0: float) -> None: ...
    def setOrientationHint(self, arg0: int) -> None: ...
    def setLocation(self, arg0: float, arg1: float) -> None: ...
    def setOutputFormat(self, arg0: int) -> None: ...
    def setVideoSize(self, arg0: int, arg1: int) -> None: ...
    def setVideoFrameRate(self, arg0: int) -> None: ...
    def setMaxDuration(self, arg0: int) -> None: ...
    def setMaxFileSize(self, arg0: int) -> None: ...
    def setAudioEncoder(self, arg0: int) -> None: ...
    def setVideoEncoder(self, arg0: int) -> None: ...
    def setAudioSamplingRate(self, arg0: int) -> None: ...
    def setAudioChannels(self, arg0: int) -> None: ...
    def setAudioEncodingBitRate(self, arg0: int) -> None: ...
    def setVideoEncodingBitRate(self, arg0: int) -> None: ...
    def setVideoEncodingProfileLevel(self, arg0: int, arg1: int) -> None: ...
    @overload
    def setOutputFile(self, arg0: FileDescriptor) -> None: ...
    @overload
    def setOutputFile(self, arg0: File) -> None: ...
    @overload
    def setOutputFile(self, arg0: str) -> None: ...
    @overload
    def setNextOutputFile(self, arg0: FileDescriptor) -> None: ...
    @overload
    def setNextOutputFile(self, arg0: File) -> None: ...
    def prepare(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def reset(self) -> None: ...
    def getMaxAmplitude(self) -> int: ...
    def setOnErrorListener(self, arg0: "OnErrorListener") -> None: ...
    def setOnInfoListener(self, arg0: "OnInfoListener") -> None: ...
    def setPreferredDevice(self, arg0: AudioDeviceInfo) -> bool: ...
    def getPreferredDevice(self) -> AudioDeviceInfo: ...
    def getRoutedDevice(self) -> AudioDeviceInfo: ...
    def addOnRoutingChangedListener(self, arg0: OnRoutingChangedListener, arg1: Handler) -> None: ...
    def removeOnRoutingChangedListener(self, arg0: OnRoutingChangedListener) -> None: ...
    def getActiveMicrophones(self) -> list: ...
    def setPreferredMicrophoneDirection(self, arg0: int) -> bool: ...
    def setPreferredMicrophoneFieldDimension(self, arg0: float) -> bool: ...
    def registerAudioRecordingCallback(self, arg0: Executor, arg1: AudioRecordingCallback) -> None: ...
    def unregisterAudioRecordingCallback(self, arg0: AudioRecordingCallback) -> None: ...
    def getActiveRecordingConfiguration(self) -> AudioRecordingConfiguration: ...
    def release(self) -> None: ...
    def getMetrics(self) -> PersistableBundle: ...
    def finalize(self) -> None: ...

    class AudioEncoder:
        AAC: ClassVar[int]
        AAC_ELD: ClassVar[int]
        AMR_NB: ClassVar[int]
        AMR_WB: ClassVar[int]
        DEFAULT: ClassVar[int]
        HE_AAC: ClassVar[int]
        OPUS: ClassVar[int]
        VORBIS: ClassVar[int]

    class AudioSource:
        CAMCORDER: ClassVar[int]
        DEFAULT: ClassVar[int]
        MIC: ClassVar[int]
        REMOTE_SUBMIX: ClassVar[int]
        UNPROCESSED: ClassVar[int]
        VOICE_CALL: ClassVar[int]
        VOICE_COMMUNICATION: ClassVar[int]
        VOICE_DOWNLINK: ClassVar[int]
        VOICE_PERFORMANCE: ClassVar[int]
        VOICE_RECOGNITION: ClassVar[int]
        VOICE_UPLINK: ClassVar[int]

    class MetricsConstants:
        AUDIO_BITRATE: ClassVar[str]
        AUDIO_CHANNELS: ClassVar[str]
        AUDIO_SAMPLERATE: ClassVar[str]
        AUDIO_TIMESCALE: ClassVar[str]
        CAPTURE_FPS: ClassVar[str]
        CAPTURE_FPS_ENABLE: ClassVar[str]
        FRAMERATE: ClassVar[str]
        HEIGHT: ClassVar[str]
        MOVIE_TIMESCALE: ClassVar[str]
        ROTATION: ClassVar[str]
        VIDEO_BITRATE: ClassVar[str]
        VIDEO_IFRAME_INTERVAL: ClassVar[str]
        VIDEO_LEVEL: ClassVar[str]
        VIDEO_PROFILE: ClassVar[str]
        VIDEO_TIMESCALE: ClassVar[str]
        WIDTH: ClassVar[str]

    class OnErrorListener:
        def onError(self, arg0: "MediaRecorder", arg1: int, arg2: int) -> None: ...

    class OnInfoListener:
        def onInfo(self, arg0: "MediaRecorder", arg1: int, arg2: int) -> None: ...

    class OutputFormat:
        AAC_ADTS: ClassVar[int]
        AMR_NB: ClassVar[int]
        AMR_WB: ClassVar[int]
        DEFAULT: ClassVar[int]
        MPEG_2_TS: ClassVar[int]
        MPEG_4: ClassVar[int]
        OGG: ClassVar[int]
        RAW_AMR: ClassVar[int]
        THREE_GPP: ClassVar[int]
        WEBM: ClassVar[int]

    class VideoEncoder:
        AV1: ClassVar[int]
        DEFAULT: ClassVar[int]
        DOLBY_VISION: ClassVar[int]
        H263: ClassVar[int]
        H264: ClassVar[int]
        HEVC: ClassVar[int]
        MPEG_4_SP: ClassVar[int]
        VP8: ClassVar[int]
        VP9: ClassVar[int]

    class VideoSource:
        CAMERA: ClassVar[int]
        DEFAULT: ClassVar[int]
        SURFACE: ClassVar[int]
