from typing import Any, ClassVar, overload
from android.media.MediaFormat import MediaFormat
from android.util.Range import Range

class MediaCodecInfo:
    def getName(self) -> str: ...
    def getCanonicalName(self) -> str: ...
    def isAlias(self) -> bool: ...
    def isEncoder(self) -> bool: ...
    def isVendor(self) -> bool: ...
    def isSoftwareOnly(self) -> bool: ...
    def isHardwareAccelerated(self) -> bool: ...
    def getSupportedTypes(self) -> list[str]: ...
    def getCapabilitiesForType(self, arg0: str) -> "CodecCapabilities": ...

    class AudioCapabilities:
        def getBitrateRange(self) -> Range: ...
        def getSupportedSampleRates(self) -> list[int]: ...
        def getSupportedSampleRateRanges(self) -> list[Range]: ...
        def getMaxInputChannelCount(self) -> int: ...
        def getMinInputChannelCount(self) -> int: ...
        def getInputChannelCountRanges(self) -> list[Range]: ...
        def isSampleRateSupported(self, arg0: int) -> bool: ...

    class CodecCapabilities:
        COLOR_Format12bitRGB444: ClassVar[int]
        COLOR_Format16bitARGB1555: ClassVar[int]
        COLOR_Format16bitARGB4444: ClassVar[int]
        COLOR_Format16bitBGR565: ClassVar[int]
        COLOR_Format16bitRGB565: ClassVar[int]
        COLOR_Format18BitBGR666: ClassVar[int]
        COLOR_Format18bitARGB1665: ClassVar[int]
        COLOR_Format18bitRGB666: ClassVar[int]
        COLOR_Format19bitARGB1666: ClassVar[int]
        COLOR_Format24BitABGR6666: ClassVar[int]
        COLOR_Format24BitARGB6666: ClassVar[int]
        COLOR_Format24bitARGB1887: ClassVar[int]
        COLOR_Format24bitBGR888: ClassVar[int]
        COLOR_Format24bitRGB888: ClassVar[int]
        COLOR_Format25bitARGB1888: ClassVar[int]
        COLOR_Format32bitABGR2101010: ClassVar[int]
        COLOR_Format32bitABGR8888: ClassVar[int]
        COLOR_Format32bitARGB8888: ClassVar[int]
        COLOR_Format32bitBGRA8888: ClassVar[int]
        COLOR_Format64bitABGRFloat: ClassVar[int]
        COLOR_Format8bitRGB332: ClassVar[int]
        COLOR_FormatCbYCrY: ClassVar[int]
        COLOR_FormatCrYCbY: ClassVar[int]
        COLOR_FormatL16: ClassVar[int]
        COLOR_FormatL2: ClassVar[int]
        COLOR_FormatL24: ClassVar[int]
        COLOR_FormatL32: ClassVar[int]
        COLOR_FormatL4: ClassVar[int]
        COLOR_FormatL8: ClassVar[int]
        COLOR_FormatMonochrome: ClassVar[int]
        COLOR_FormatRGBAFlexible: ClassVar[int]
        COLOR_FormatRGBFlexible: ClassVar[int]
        COLOR_FormatRawBayer10bit: ClassVar[int]
        COLOR_FormatRawBayer8bit: ClassVar[int]
        COLOR_FormatRawBayer8bitcompressed: ClassVar[int]
        COLOR_FormatSurface: ClassVar[int]
        COLOR_FormatYCbYCr: ClassVar[int]
        COLOR_FormatYCrYCb: ClassVar[int]
        COLOR_FormatYUV411PackedPlanar: ClassVar[int]
        COLOR_FormatYUV411Planar: ClassVar[int]
        COLOR_FormatYUV420Flexible: ClassVar[int]
        COLOR_FormatYUV420PackedPlanar: ClassVar[int]
        COLOR_FormatYUV420PackedSemiPlanar: ClassVar[int]
        COLOR_FormatYUV420Planar: ClassVar[int]
        COLOR_FormatYUV420SemiPlanar: ClassVar[int]
        COLOR_FormatYUV422Flexible: ClassVar[int]
        COLOR_FormatYUV422PackedPlanar: ClassVar[int]
        COLOR_FormatYUV422PackedSemiPlanar: ClassVar[int]
        COLOR_FormatYUV422Planar: ClassVar[int]
        COLOR_FormatYUV422SemiPlanar: ClassVar[int]
        COLOR_FormatYUV444Flexible: ClassVar[int]
        COLOR_FormatYUV444Interleaved: ClassVar[int]
        COLOR_FormatYUVP010: ClassVar[int]
        COLOR_QCOM_FormatYUV420SemiPlanar: ClassVar[int]
        COLOR_TI_FormatYUV420PackedSemiPlanar: ClassVar[int]
        FEATURE_AdaptivePlayback: ClassVar[str]
        FEATURE_DetachedSurface: ClassVar[str]
        FEATURE_DynamicColorAspects: ClassVar[str]
        FEATURE_DynamicTimestamp: ClassVar[str]
        FEATURE_EncodingStatistics: ClassVar[str]
        FEATURE_FrameParsing: ClassVar[str]
        FEATURE_HdrEditing: ClassVar[str]
        FEATURE_HlgEditing: ClassVar[str]
        FEATURE_IntraRefresh: ClassVar[str]
        FEATURE_LowLatency: ClassVar[str]
        FEATURE_MultipleFrames: ClassVar[str]
        FEATURE_PartialFrame: ClassVar[str]
        FEATURE_QpBounds: ClassVar[str]
        FEATURE_Roi: ClassVar[str]
        FEATURE_SecurePlayback: ClassVar[str]
        FEATURE_TunneledPlayback: ClassVar[str]
        colorFormats: list[int]
        profileLevels: list["CodecProfileLevel"]
        def __init__(self) -> None: ...
        def isFeatureSupported(self, arg0: str) -> bool: ...
        def isFeatureRequired(self, arg0: str) -> bool: ...
        def isFormatSupported(self, arg0: MediaFormat) -> bool: ...
        def getDefaultFormat(self) -> MediaFormat: ...
        def getMimeType(self) -> str: ...
        def getMaxSupportedInstances(self) -> int: ...
        def getAudioCapabilities(self) -> "AudioCapabilities": ...
        def getEncoderCapabilities(self) -> "EncoderCapabilities": ...
        def getVideoCapabilities(self) -> "VideoCapabilities": ...
        @staticmethod
        def createFromProfileLevel(arg0: str, arg1: int, arg2: int) -> "CodecCapabilities": ...

    class CodecProfileLevel:
        AACObjectELD: ClassVar[int]
        AACObjectERLC: ClassVar[int]
        AACObjectERScalable: ClassVar[int]
        AACObjectHE: ClassVar[int]
        AACObjectHE_PS: ClassVar[int]
        AACObjectLC: ClassVar[int]
        AACObjectLD: ClassVar[int]
        AACObjectLTP: ClassVar[int]
        AACObjectMain: ClassVar[int]
        AACObjectSSR: ClassVar[int]
        AACObjectScalable: ClassVar[int]
        AACObjectXHE: ClassVar[int]
        AC4Level0: ClassVar[int]
        AC4Level1: ClassVar[int]
        AC4Level2: ClassVar[int]
        AC4Level3: ClassVar[int]
        AC4Level4: ClassVar[int]
        AC4Profile00: ClassVar[int]
        AC4Profile10: ClassVar[int]
        AC4Profile11: ClassVar[int]
        AC4Profile21: ClassVar[int]
        AC4Profile22: ClassVar[int]
        AV1Level2: ClassVar[int]
        AV1Level21: ClassVar[int]
        AV1Level22: ClassVar[int]
        AV1Level23: ClassVar[int]
        AV1Level3: ClassVar[int]
        AV1Level31: ClassVar[int]
        AV1Level32: ClassVar[int]
        AV1Level33: ClassVar[int]
        AV1Level4: ClassVar[int]
        AV1Level41: ClassVar[int]
        AV1Level42: ClassVar[int]
        AV1Level43: ClassVar[int]
        AV1Level5: ClassVar[int]
        AV1Level51: ClassVar[int]
        AV1Level52: ClassVar[int]
        AV1Level53: ClassVar[int]
        AV1Level6: ClassVar[int]
        AV1Level61: ClassVar[int]
        AV1Level62: ClassVar[int]
        AV1Level63: ClassVar[int]
        AV1Level7: ClassVar[int]
        AV1Level71: ClassVar[int]
        AV1Level72: ClassVar[int]
        AV1Level73: ClassVar[int]
        AV1ProfileMain10: ClassVar[int]
        AV1ProfileMain10HDR10: ClassVar[int]
        AV1ProfileMain10HDR10Plus: ClassVar[int]
        AV1ProfileMain8: ClassVar[int]
        AVCLevel1: ClassVar[int]
        AVCLevel11: ClassVar[int]
        AVCLevel12: ClassVar[int]
        AVCLevel13: ClassVar[int]
        AVCLevel1b: ClassVar[int]
        AVCLevel2: ClassVar[int]
        AVCLevel21: ClassVar[int]
        AVCLevel22: ClassVar[int]
        AVCLevel3: ClassVar[int]
        AVCLevel31: ClassVar[int]
        AVCLevel32: ClassVar[int]
        AVCLevel4: ClassVar[int]
        AVCLevel41: ClassVar[int]
        AVCLevel42: ClassVar[int]
        AVCLevel5: ClassVar[int]
        AVCLevel51: ClassVar[int]
        AVCLevel52: ClassVar[int]
        AVCLevel6: ClassVar[int]
        AVCLevel61: ClassVar[int]
        AVCLevel62: ClassVar[int]
        AVCProfileBaseline: ClassVar[int]
        AVCProfileConstrainedBaseline: ClassVar[int]
        AVCProfileConstrainedHigh: ClassVar[int]
        AVCProfileExtended: ClassVar[int]
        AVCProfileHigh: ClassVar[int]
        AVCProfileHigh10: ClassVar[int]
        AVCProfileHigh422: ClassVar[int]
        AVCProfileHigh444: ClassVar[int]
        AVCProfileMain: ClassVar[int]
        DTS_HDProfileHRA: ClassVar[int]
        DTS_HDProfileLBR: ClassVar[int]
        DTS_HDProfileMA: ClassVar[int]
        DTS_UHDProfileP1: ClassVar[int]
        DTS_UHDProfileP2: ClassVar[int]
        DolbyVisionLevel8k30: ClassVar[int]
        DolbyVisionLevel8k60: ClassVar[int]
        DolbyVisionLevelFhd24: ClassVar[int]
        DolbyVisionLevelFhd30: ClassVar[int]
        DolbyVisionLevelFhd60: ClassVar[int]
        DolbyVisionLevelHd24: ClassVar[int]
        DolbyVisionLevelHd30: ClassVar[int]
        DolbyVisionLevelUhd120: ClassVar[int]
        DolbyVisionLevelUhd24: ClassVar[int]
        DolbyVisionLevelUhd30: ClassVar[int]
        DolbyVisionLevelUhd48: ClassVar[int]
        DolbyVisionLevelUhd60: ClassVar[int]
        DolbyVisionProfileDvav110: ClassVar[int]
        DolbyVisionProfileDvavPen: ClassVar[int]
        DolbyVisionProfileDvavPer: ClassVar[int]
        DolbyVisionProfileDvavSe: ClassVar[int]
        DolbyVisionProfileDvheDen: ClassVar[int]
        DolbyVisionProfileDvheDer: ClassVar[int]
        DolbyVisionProfileDvheDtb: ClassVar[int]
        DolbyVisionProfileDvheDth: ClassVar[int]
        DolbyVisionProfileDvheDtr: ClassVar[int]
        DolbyVisionProfileDvheSt: ClassVar[int]
        DolbyVisionProfileDvheStn: ClassVar[int]
        H263Level10: ClassVar[int]
        H263Level20: ClassVar[int]
        H263Level30: ClassVar[int]
        H263Level40: ClassVar[int]
        H263Level45: ClassVar[int]
        H263Level50: ClassVar[int]
        H263Level60: ClassVar[int]
        H263Level70: ClassVar[int]
        H263ProfileBackwardCompatible: ClassVar[int]
        H263ProfileBaseline: ClassVar[int]
        H263ProfileH320Coding: ClassVar[int]
        H263ProfileHighCompression: ClassVar[int]
        H263ProfileHighLatency: ClassVar[int]
        H263ProfileISWV2: ClassVar[int]
        H263ProfileISWV3: ClassVar[int]
        H263ProfileInterlace: ClassVar[int]
        H263ProfileInternet: ClassVar[int]
        HEVCHighTierLevel1: ClassVar[int]
        HEVCHighTierLevel2: ClassVar[int]
        HEVCHighTierLevel21: ClassVar[int]
        HEVCHighTierLevel3: ClassVar[int]
        HEVCHighTierLevel31: ClassVar[int]
        HEVCHighTierLevel4: ClassVar[int]
        HEVCHighTierLevel41: ClassVar[int]
        HEVCHighTierLevel5: ClassVar[int]
        HEVCHighTierLevel51: ClassVar[int]
        HEVCHighTierLevel52: ClassVar[int]
        HEVCHighTierLevel6: ClassVar[int]
        HEVCHighTierLevel61: ClassVar[int]
        HEVCHighTierLevel62: ClassVar[int]
        HEVCMainTierLevel1: ClassVar[int]
        HEVCMainTierLevel2: ClassVar[int]
        HEVCMainTierLevel21: ClassVar[int]
        HEVCMainTierLevel3: ClassVar[int]
        HEVCMainTierLevel31: ClassVar[int]
        HEVCMainTierLevel4: ClassVar[int]
        HEVCMainTierLevel41: ClassVar[int]
        HEVCMainTierLevel5: ClassVar[int]
        HEVCMainTierLevel51: ClassVar[int]
        HEVCMainTierLevel52: ClassVar[int]
        HEVCMainTierLevel6: ClassVar[int]
        HEVCMainTierLevel61: ClassVar[int]
        HEVCMainTierLevel62: ClassVar[int]
        HEVCProfileMain: ClassVar[int]
        HEVCProfileMain10: ClassVar[int]
        HEVCProfileMain10HDR10: ClassVar[int]
        HEVCProfileMain10HDR10Plus: ClassVar[int]
        HEVCProfileMainStill: ClassVar[int]
        MPEG2LevelH14: ClassVar[int]
        MPEG2LevelHL: ClassVar[int]
        MPEG2LevelHP: ClassVar[int]
        MPEG2LevelLL: ClassVar[int]
        MPEG2LevelML: ClassVar[int]
        MPEG2Profile422: ClassVar[int]
        MPEG2ProfileHigh: ClassVar[int]
        MPEG2ProfileMain: ClassVar[int]
        MPEG2ProfileSNR: ClassVar[int]
        MPEG2ProfileSimple: ClassVar[int]
        MPEG2ProfileSpatial: ClassVar[int]
        MPEG4Level0: ClassVar[int]
        MPEG4Level0b: ClassVar[int]
        MPEG4Level1: ClassVar[int]
        MPEG4Level2: ClassVar[int]
        MPEG4Level3: ClassVar[int]
        MPEG4Level3b: ClassVar[int]
        MPEG4Level4: ClassVar[int]
        MPEG4Level4a: ClassVar[int]
        MPEG4Level5: ClassVar[int]
        MPEG4Level6: ClassVar[int]
        MPEG4ProfileAdvancedCoding: ClassVar[int]
        MPEG4ProfileAdvancedCore: ClassVar[int]
        MPEG4ProfileAdvancedRealTime: ClassVar[int]
        MPEG4ProfileAdvancedScalable: ClassVar[int]
        MPEG4ProfileAdvancedSimple: ClassVar[int]
        MPEG4ProfileBasicAnimated: ClassVar[int]
        MPEG4ProfileCore: ClassVar[int]
        MPEG4ProfileCoreScalable: ClassVar[int]
        MPEG4ProfileHybrid: ClassVar[int]
        MPEG4ProfileMain: ClassVar[int]
        MPEG4ProfileNbit: ClassVar[int]
        MPEG4ProfileScalableTexture: ClassVar[int]
        MPEG4ProfileSimple: ClassVar[int]
        MPEG4ProfileSimpleFBA: ClassVar[int]
        MPEG4ProfileSimpleFace: ClassVar[int]
        MPEG4ProfileSimpleScalable: ClassVar[int]
        VP8Level_Version0: ClassVar[int]
        VP8Level_Version1: ClassVar[int]
        VP8Level_Version2: ClassVar[int]
        VP8Level_Version3: ClassVar[int]
        VP8ProfileMain: ClassVar[int]
        VP9Level1: ClassVar[int]
        VP9Level11: ClassVar[int]
        VP9Level2: ClassVar[int]
        VP9Level21: ClassVar[int]
        VP9Level3: ClassVar[int]
        VP9Level31: ClassVar[int]
        VP9Level4: ClassVar[int]
        VP9Level41: ClassVar[int]
        VP9Level5: ClassVar[int]
        VP9Level51: ClassVar[int]
        VP9Level52: ClassVar[int]
        VP9Level6: ClassVar[int]
        VP9Level61: ClassVar[int]
        VP9Level62: ClassVar[int]
        VP9Profile0: ClassVar[int]
        VP9Profile1: ClassVar[int]
        VP9Profile2: ClassVar[int]
        VP9Profile2HDR: ClassVar[int]
        VP9Profile2HDR10Plus: ClassVar[int]
        VP9Profile3: ClassVar[int]
        VP9Profile3HDR: ClassVar[int]
        VP9Profile3HDR10Plus: ClassVar[int]
        level: int
        profile: int
        def __init__(self) -> None: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class EncoderCapabilities:
        BITRATE_MODE_CBR: ClassVar[int]
        BITRATE_MODE_CBR_FD: ClassVar[int]
        BITRATE_MODE_CQ: ClassVar[int]
        BITRATE_MODE_VBR: ClassVar[int]
        def getQualityRange(self) -> Range: ...
        def getComplexityRange(self) -> Range: ...
        def isBitrateModeSupported(self, arg0: int) -> bool: ...

    class VideoCapabilities:
        def getBitrateRange(self) -> Range: ...
        def getSupportedWidths(self) -> Range: ...
        def getSupportedHeights(self) -> Range: ...
        def getWidthAlignment(self) -> int: ...
        def getHeightAlignment(self) -> int: ...
        def getSupportedFrameRates(self) -> Range: ...
        def getSupportedWidthsFor(self, arg0: int) -> Range: ...
        def getSupportedHeightsFor(self, arg0: int) -> Range: ...
        def getSupportedFrameRatesFor(self, arg0: int, arg1: int) -> Range: ...
        def getAchievableFrameRatesFor(self, arg0: int, arg1: int) -> Range: ...
        def getSupportedPerformancePoints(self) -> list: ...
        def areSizeAndRateSupported(self, arg0: int, arg1: int, arg2: float) -> bool: ...
        def isSizeSupported(self, arg0: int, arg1: int) -> bool: ...

        class PerformancePoint:
            FHD_100: ClassVar["PerformancePoint"]
            FHD_120: ClassVar["PerformancePoint"]
            FHD_200: ClassVar["PerformancePoint"]
            FHD_24: ClassVar["PerformancePoint"]
            FHD_240: ClassVar["PerformancePoint"]
            FHD_25: ClassVar["PerformancePoint"]
            FHD_30: ClassVar["PerformancePoint"]
            FHD_50: ClassVar["PerformancePoint"]
            FHD_60: ClassVar["PerformancePoint"]
            HD_100: ClassVar["PerformancePoint"]
            HD_120: ClassVar["PerformancePoint"]
            HD_200: ClassVar["PerformancePoint"]
            HD_24: ClassVar["PerformancePoint"]
            HD_240: ClassVar["PerformancePoint"]
            HD_25: ClassVar["PerformancePoint"]
            HD_30: ClassVar["PerformancePoint"]
            HD_50: ClassVar["PerformancePoint"]
            HD_60: ClassVar["PerformancePoint"]
            SD_24: ClassVar["PerformancePoint"]
            SD_25: ClassVar["PerformancePoint"]
            SD_30: ClassVar["PerformancePoint"]
            SD_48: ClassVar["PerformancePoint"]
            SD_50: ClassVar["PerformancePoint"]
            SD_60: ClassVar["PerformancePoint"]
            UHD_100: ClassVar["PerformancePoint"]
            UHD_120: ClassVar["PerformancePoint"]
            UHD_200: ClassVar["PerformancePoint"]
            UHD_24: ClassVar["PerformancePoint"]
            UHD_240: ClassVar["PerformancePoint"]
            UHD_25: ClassVar["PerformancePoint"]
            UHD_30: ClassVar["PerformancePoint"]
            UHD_50: ClassVar["PerformancePoint"]
            UHD_60: ClassVar["PerformancePoint"]
            def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
            def toString(self) -> str: ...
            def hashCode(self) -> int: ...
            @overload
            def covers(self, arg0: MediaFormat) -> bool: ...
            @overload
            def covers(self, arg0: "PerformancePoint") -> bool: ...
            def equals(self, arg0: Any) -> bool: ...
