from typing import Any, ClassVar, overload
from android.hardware.HardwareBuffer import HardwareBuffer
from android.media.AudioPresentation import AudioPresentation
from android.media.Image import Image
from android.media.MediaCodecInfo import MediaCodecInfo
from android.media.MediaCrypto import MediaCrypto
from android.media.MediaDescrambler import MediaDescrambler
from android.media.MediaFormat import MediaFormat
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.os.PersistableBundle import PersistableBundle
from android.view.Surface import Surface
from java.nio.ByteBuffer import ByteBuffer
from java.util.ArrayDeque import ArrayDeque

class MediaCodec:
    BUFFER_FLAG_CODEC_CONFIG: ClassVar[int]
    BUFFER_FLAG_DECODE_ONLY: ClassVar[int]
    BUFFER_FLAG_END_OF_STREAM: ClassVar[int]
    BUFFER_FLAG_KEY_FRAME: ClassVar[int]
    BUFFER_FLAG_PARTIAL_FRAME: ClassVar[int]
    BUFFER_FLAG_SYNC_FRAME: ClassVar[int]
    CONFIGURE_FLAG_DETACHED_SURFACE: ClassVar[int]
    CONFIGURE_FLAG_ENCODE: ClassVar[int]
    CONFIGURE_FLAG_USE_BLOCK_MODEL: ClassVar[int]
    CONFIGURE_FLAG_USE_CRYPTO_ASYNC: ClassVar[int]
    CRYPTO_MODE_AES_CBC: ClassVar[int]
    CRYPTO_MODE_AES_CTR: ClassVar[int]
    CRYPTO_MODE_UNENCRYPTED: ClassVar[int]
    INFO_OUTPUT_BUFFERS_CHANGED: ClassVar[int]
    INFO_OUTPUT_FORMAT_CHANGED: ClassVar[int]
    INFO_TRY_AGAIN_LATER: ClassVar[int]
    PARAMETER_KEY_HDR10_PLUS_INFO: ClassVar[str]
    PARAMETER_KEY_LOW_LATENCY: ClassVar[str]
    PARAMETER_KEY_OFFSET_TIME: ClassVar[str]
    PARAMETER_KEY_QP_OFFSET_MAP: ClassVar[str]
    PARAMETER_KEY_QP_OFFSET_RECTS: ClassVar[str]
    PARAMETER_KEY_REQUEST_SYNC_FRAME: ClassVar[str]
    PARAMETER_KEY_SUSPEND: ClassVar[str]
    PARAMETER_KEY_SUSPEND_TIME: ClassVar[str]
    PARAMETER_KEY_TUNNEL_PEEK: ClassVar[str]
    PARAMETER_KEY_VIDEO_BITRATE: ClassVar[str]
    VIDEO_SCALING_MODE_SCALE_TO_FIT: ClassVar[int]
    VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING: ClassVar[int]
    @staticmethod
    def createDecoderByType(arg0: str) -> "MediaCodec": ...
    @staticmethod
    def createEncoderByType(arg0: str) -> "MediaCodec": ...
    @staticmethod
    def createByCodecName(arg0: str) -> "MediaCodec": ...
    def finalize(self) -> None: ...
    def reset(self) -> None: ...
    def release(self) -> None: ...
    @overload
    def configure(self, arg0: MediaFormat, arg1: Surface, arg2: MediaCrypto, arg3: int) -> None: ...
    @overload
    def configure(self, arg0: MediaFormat, arg1: Surface, arg2: int, arg3: MediaDescrambler) -> None: ...
    def setOutputSurface(self, arg0: Surface) -> None: ...
    def detachOutputSurface(self) -> None: ...
    @staticmethod
    def createPersistentInputSurface() -> Surface: ...
    def setInputSurface(self, arg0: Surface) -> None: ...
    def createInputSurface(self) -> Surface: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def flush(self) -> None: ...
    def queueInputBuffer(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def queueInputBuffers(self, arg0: int, arg1: ArrayDeque) -> None: ...
    def queueSecureInputBuffer(self, arg0: int, arg1: int, arg2: "CryptoInfo", arg3: int, arg4: int) -> None: ...
    def queueSecureInputBuffers(self, arg0: int, arg1: ArrayDeque, arg2: ArrayDeque) -> None: ...
    def dequeueInputBuffer(self, arg0: int) -> int: ...
    @staticmethod
    def mapHardwareBuffer(arg0: HardwareBuffer) -> Image: ...
    def getQueueRequest(self, arg0: int) -> "QueueRequest": ...
    def dequeueOutputBuffer(self, arg0: "BufferInfo", arg1: int) -> int: ...
    @overload
    def releaseOutputBuffer(self, arg0: int, arg1: bool) -> None: ...
    @overload
    def releaseOutputBuffer(self, arg0: int, arg1: int) -> None: ...
    def signalEndOfInputStream(self) -> None: ...
    @overload
    def getOutputFormat(self) -> MediaFormat: ...
    @overload
    def getOutputFormat(self, arg0: int) -> MediaFormat: ...
    def getInputFormat(self) -> MediaFormat: ...
    def getInputBuffers(self) -> list[ByteBuffer]: ...
    def getOutputBuffers(self) -> list[ByteBuffer]: ...
    def getInputBuffer(self, arg0: int) -> ByteBuffer: ...
    def getInputImage(self, arg0: int) -> Image: ...
    def getOutputBuffer(self, arg0: int) -> ByteBuffer: ...
    def getOutputImage(self, arg0: int) -> Image: ...
    def getOutputFrame(self, arg0: int) -> "OutputFrame": ...
    def setVideoScalingMode(self, arg0: int) -> None: ...
    def setAudioPresentation(self, arg0: AudioPresentation) -> None: ...
    def getName(self) -> str: ...
    def getCanonicalName(self) -> str: ...
    def getMetrics(self) -> PersistableBundle: ...
    def setParameters(self, arg0: Bundle) -> None: ...
    @overload
    def setCallback(self, arg0: "Callback", arg1: Handler) -> None: ...
    @overload
    def setCallback(self, arg0: "Callback") -> None: ...
    def setOnFirstTunnelFrameReadyListener(self, arg0: Handler, arg1: "OnFirstTunnelFrameReadyListener") -> None: ...
    def setOnFrameRenderedListener(self, arg0: "OnFrameRenderedListener", arg1: Handler) -> None: ...
    def getSupportedVendorParameters(self) -> list: ...
    def getParameterDescriptor(self, arg0: str) -> "ParameterDescriptor": ...
    def subscribeToVendorParameters(self, arg0: list) -> None: ...
    def unsubscribeFromVendorParameters(self, arg0: list) -> None: ...
    def getCodecInfo(self) -> MediaCodecInfo: ...

    class BufferInfo:
        flags: int
        offset: int
        presentationTimeUs: int
        size: int
        def __init__(self) -> None: ...
        def set(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...

    class Callback:
        def __init__(self) -> None: ...
        def onInputBufferAvailable(self, arg0: "MediaCodec", arg1: int) -> None: ...
        def onOutputBufferAvailable(self, arg0: "MediaCodec", arg1: int, arg2: "BufferInfo") -> None: ...
        def onOutputBuffersAvailable(self, arg0: "MediaCodec", arg1: int, arg2: ArrayDeque) -> None: ...
        def onError(self, arg0: "MediaCodec", arg1: "CodecException") -> None: ...
        def onCryptoError(self, arg0: "MediaCodec", arg1: "CryptoException") -> None: ...
        def onOutputFormatChanged(self, arg0: "MediaCodec", arg1: MediaFormat) -> None: ...

    class CodecException:
        ERROR_INSUFFICIENT_RESOURCE: ClassVar[int]
        ERROR_RECLAIMED: ClassVar[int]
        def isTransient(self) -> bool: ...
        def isRecoverable(self) -> bool: ...
        def getErrorCode(self) -> int: ...
        def getDiagnosticInfo(self) -> str: ...

    class CryptoException:
        ERROR_FRAME_TOO_LARGE: ClassVar[int]
        ERROR_INSUFFICIENT_OUTPUT_PROTECTION: ClassVar[int]
        ERROR_INSUFFICIENT_SECURITY: ClassVar[int]
        ERROR_KEY_EXPIRED: ClassVar[int]
        ERROR_LOST_STATE: ClassVar[int]
        ERROR_NO_KEY: ClassVar[int]
        ERROR_RESOURCE_BUSY: ClassVar[int]
        ERROR_SESSION_NOT_OPENED: ClassVar[int]
        ERROR_UNSUPPORTED_OPERATION: ClassVar[int]
        def __init__(self, arg0: int, arg1: str) -> None: ...
        def getErrorCode(self) -> int: ...
        def getCryptoInfo(self) -> "CryptoInfo": ...
        def getVendorError(self) -> int: ...
        def getOemError(self) -> int: ...
        def getErrorContext(self) -> int: ...

    class CryptoInfo:
        iv: list[int]
        key: list[int]
        mode: int
        numBytesOfClearData: list[int]
        numBytesOfEncryptedData: list[int]
        numSubSamples: int
        def __init__(self) -> None: ...
        def set(self, arg0: int, arg1: list[int], arg2: list[int], arg3: list[int], arg4: list[int], arg5: int) -> None: ...
        def getPattern(self) -> "Pattern": ...
        def setPattern(self, arg0: "Pattern") -> None: ...
        def toString(self) -> str: ...

        class Pattern:
            def __init__(self, arg0: int, arg1: int) -> None: ...
            def set(self, arg0: int, arg1: int) -> None: ...
            def getSkipBlocks(self) -> int: ...
            def getEncryptBlocks(self) -> int: ...

    class IncompatibleWithBlockModelException:
        ...

    class InvalidBufferFlagsException:
        ...

    class LinearBlock:
        def isMappable(self) -> bool: ...
        def map(self) -> ByteBuffer: ...
        def recycle(self) -> None: ...
        def finalize(self) -> None: ...
        @staticmethod
        def isCodecCopyFreeCompatible(arg0: list[str]) -> bool: ...
        @staticmethod
        def obtain(arg0: int, arg1: list[str]) -> "LinearBlock": ...

    class MetricsConstants:
        CODEC: ClassVar[str]
        ENCODER: ClassVar[str]
        HEIGHT: ClassVar[str]
        MIME_TYPE: ClassVar[str]
        MODE: ClassVar[str]
        MODE_AUDIO: ClassVar[str]
        MODE_VIDEO: ClassVar[str]
        ROTATION: ClassVar[str]
        SECURE: ClassVar[str]
        WIDTH: ClassVar[str]

    class OnFirstTunnelFrameReadyListener:
        def onFirstTunnelFrameReady(self, arg0: "MediaCodec") -> None: ...

    class OnFrameRenderedListener:
        def onFrameRendered(self, arg0: "MediaCodec", arg1: int, arg2: int) -> None: ...

    class OutputFrame:
        def getLinearBlock(self) -> "LinearBlock": ...
        def getHardwareBuffer(self) -> HardwareBuffer: ...
        def getPresentationTimeUs(self) -> int: ...
        def getFlags(self) -> int: ...
        def getBufferInfos(self) -> ArrayDeque: ...
        def getFormat(self) -> MediaFormat: ...
        def getChangedKeys(self) -> set: ...

    class ParameterDescriptor:
        def getName(self) -> str: ...
        def getType(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class QueueRequest:
        def setLinearBlock(self, arg0: "LinearBlock", arg1: int, arg2: int) -> "QueueRequest": ...
        def setMultiFrameLinearBlock(self, arg0: "LinearBlock", arg1: ArrayDeque) -> "QueueRequest": ...
        def setEncryptedLinearBlock(self, arg0: "LinearBlock", arg1: int, arg2: int, arg3: "CryptoInfo") -> "QueueRequest": ...
        def setMultiFrameEncryptedLinearBlock(self, arg0: "LinearBlock", arg1: ArrayDeque, arg2: ArrayDeque) -> "QueueRequest": ...
        def setHardwareBuffer(self, arg0: HardwareBuffer) -> "QueueRequest": ...
        def setPresentationTimeUs(self, arg0: int) -> "QueueRequest": ...
        def setFlags(self, arg0: int) -> "QueueRequest": ...
        def setIntegerParameter(self, arg0: str, arg1: int) -> "QueueRequest": ...
        def setLongParameter(self, arg0: str, arg1: int) -> "QueueRequest": ...
        def setFloatParameter(self, arg0: str, arg1: float) -> "QueueRequest": ...
        def setByteBufferParameter(self, arg0: str, arg1: ByteBuffer) -> "QueueRequest": ...
        def setStringParameter(self, arg0: str, arg1: str) -> "QueueRequest": ...
        def queue(self) -> None: ...
