from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class MediaRoute2Info:
    CONNECTION_STATE_CONNECTED: ClassVar[int]
    CONNECTION_STATE_CONNECTING: ClassVar[int]
    CONNECTION_STATE_DISCONNECTED: ClassVar[int]
    CREATOR: ClassVar[Creator]
    FEATURE_LIVE_AUDIO: ClassVar[str]
    FEATURE_LIVE_VIDEO: ClassVar[str]
    FEATURE_REMOTE_AUDIO_PLAYBACK: ClassVar[str]
    FEATURE_REMOTE_PLAYBACK: ClassVar[str]
    FEATURE_REMOTE_VIDEO_PLAYBACK: ClassVar[str]
    PLAYBACK_VOLUME_FIXED: ClassVar[int]
    PLAYBACK_VOLUME_VARIABLE: ClassVar[int]
    SUITABILITY_STATUS_NOT_SUITABLE_FOR_TRANSFER: ClassVar[int]
    SUITABILITY_STATUS_SUITABLE_FOR_DEFAULT_TRANSFER: ClassVar[int]
    SUITABILITY_STATUS_SUITABLE_FOR_MANUAL_TRANSFER: ClassVar[int]
    TYPE_BLE_HEADSET: ClassVar[int]
    TYPE_BLUETOOTH_A2DP: ClassVar[int]
    TYPE_BUILTIN_SPEAKER: ClassVar[int]
    TYPE_DOCK: ClassVar[int]
    TYPE_GROUP: ClassVar[int]
    TYPE_HDMI: ClassVar[int]
    TYPE_HDMI_ARC: ClassVar[int]
    TYPE_HDMI_EARC: ClassVar[int]
    TYPE_HEARING_AID: ClassVar[int]
    TYPE_REMOTE_AUDIO_VIDEO_RECEIVER: ClassVar[int]
    TYPE_REMOTE_CAR: ClassVar[int]
    TYPE_REMOTE_COMPUTER: ClassVar[int]
    TYPE_REMOTE_GAME_CONSOLE: ClassVar[int]
    TYPE_REMOTE_SMARTPHONE: ClassVar[int]
    TYPE_REMOTE_SMARTWATCH: ClassVar[int]
    TYPE_REMOTE_SPEAKER: ClassVar[int]
    TYPE_REMOTE_TABLET: ClassVar[int]
    TYPE_REMOTE_TABLET_DOCKED: ClassVar[int]
    TYPE_REMOTE_TV: ClassVar[int]
    TYPE_UNKNOWN: ClassVar[int]
    TYPE_USB_ACCESSORY: ClassVar[int]
    TYPE_USB_DEVICE: ClassVar[int]
    TYPE_USB_HEADSET: ClassVar[int]
    TYPE_WIRED_HEADPHONES: ClassVar[int]
    TYPE_WIRED_HEADSET: ClassVar[int]
    def getId(self) -> str: ...
    def getName(self) -> str: ...
    def getFeatures(self) -> list: ...
    def getType(self) -> int: ...
    def isSystemRoute(self) -> bool: ...
    def getIconUri(self) -> Uri: ...
    def getDescription(self) -> str: ...
    def getConnectionState(self) -> int: ...
    def getClientPackageName(self) -> str: ...
    def getVolumeHandling(self) -> int: ...
    def getVolumeMax(self) -> int: ...
    def getVolume(self) -> int: ...
    def getDeduplicationIds(self) -> set: ...
    def getExtras(self) -> Bundle: ...
    def getSuitabilityStatus(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        @overload
        def __init__(self, arg0: str, arg1: str) -> None: ...
        @overload
        def __init__(self, arg0: "MediaRoute2Info") -> None: ...
        def addFeature(self, arg0: str) -> "Builder": ...
        def addFeatures(self, arg0: list) -> "Builder": ...
        def clearFeatures(self) -> "Builder": ...
        def setType(self, arg0: int) -> "Builder": ...
        def setIconUri(self, arg0: Uri) -> "Builder": ...
        def setDescription(self, arg0: str) -> "Builder": ...
        def setConnectionState(self, arg0: int) -> "Builder": ...
        def setClientPackageName(self, arg0: str) -> "Builder": ...
        def setVolumeHandling(self, arg0: int) -> "Builder": ...
        def setVolumeMax(self, arg0: int) -> "Builder": ...
        def setVolume(self, arg0: int) -> "Builder": ...
        def setDeduplicationIds(self, arg0: set) -> "Builder": ...
        def setExtras(self, arg0: Bundle) -> "Builder": ...
        def setVisibilityPublic(self) -> "Builder": ...
        def setVisibilityRestricted(self, arg0: set) -> "Builder": ...
        def setSuitabilityStatus(self, arg0: int) -> "Builder": ...
        def build(self) -> "MediaRoute2Info": ...
