from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.media.Session2Command import Session2Command
from android.media.Session2CommandGroup import Session2CommandGroup
from android.media.Session2Token import Session2Token
from android.os.Bundle import Bundle
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Result:
    """Forward declaration for ``android.media.Session2Command.Result``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.Session2Command.Result')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/Session2Command/Result
    """
    ...

class MediaController2:
    def close(self) -> None: ...
    def getConnectedToken(self) -> Session2Token: ...
    def isPlaybackActive(self) -> bool: ...
    def sendSessionCommand(self, arg0: Session2Command, arg1: Bundle) -> Any: ...
    def cancelSessionCommand(self, arg0: Any) -> None: ...

    class Builder:
        def __init__(self, arg0: Context, arg1: Session2Token) -> None: ...
        def setConnectionHints(self, arg0: Bundle) -> "Builder": ...
        def setControllerCallback(self, arg0: Executor, arg1: "ControllerCallback") -> "Builder": ...
        def build(self) -> "MediaController2": ...

    class ControllerCallback:
        def __init__(self) -> None: ...
        def onConnected(self, arg0: "MediaController2", arg1: Session2CommandGroup) -> None: ...
        def onDisconnected(self, arg0: "MediaController2") -> None: ...
        def onPlaybackActiveChanged(self, arg0: "MediaController2", arg1: bool) -> None: ...
        def onSessionCommand(self, arg0: "MediaController2", arg1: Session2Command, arg2: Bundle) -> Result: ...
        def onCommandResult(self, arg0: "MediaController2", arg1: Any, arg2: Session2Command, arg3: Result) -> None: ...
