from typing import Any, ClassVar, overload
from android.media.AudioTrack import AudioTrack
from android.media.MediaTimestamp import MediaTimestamp
from android.media.PlaybackParams import PlaybackParams
from android.media.SyncParams import SyncParams
from android.os.Handler import Handler
from android.view.Surface import Surface
from java.nio.ByteBuffer import ByteBuffer

class MediaSync:
    MEDIASYNC_ERROR_AUDIOTRACK_FAIL: ClassVar[int]
    MEDIASYNC_ERROR_SURFACE_FAIL: ClassVar[int]
    def __init__(self) -> None: ...
    def finalize(self) -> None: ...
    def release(self) -> None: ...
    def setCallback(self, arg0: "Callback", arg1: Handler) -> None: ...
    def setOnErrorListener(self, arg0: "OnErrorListener", arg1: Handler) -> None: ...
    def setSurface(self, arg0: Surface) -> None: ...
    def setAudioTrack(self, arg0: AudioTrack) -> None: ...
    def createInputSurface(self) -> Surface: ...
    def setPlaybackParams(self, arg0: PlaybackParams) -> None: ...
    def getPlaybackParams(self) -> PlaybackParams: ...
    def setSyncParams(self, arg0: SyncParams) -> None: ...
    def getSyncParams(self) -> SyncParams: ...
    def flush(self) -> None: ...
    def getTimestamp(self) -> MediaTimestamp: ...
    def queueAudio(self, arg0: ByteBuffer, arg1: int, arg2: int) -> None: ...

    class Callback:
        def __init__(self) -> None: ...
        def onAudioBufferConsumed(self, arg0: "MediaSync", arg1: ByteBuffer, arg2: int) -> None: ...

    class OnErrorListener:
        def onError(self, arg0: "MediaSync", arg1: int, arg2: int) -> None: ...
