from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Looper import Looper
from android.view.KeyEvent import KeyEvent

class RemoteController:
    POSITION_SYNCHRONIZATION_CHECK: ClassVar[int]
    POSITION_SYNCHRONIZATION_NONE: ClassVar[int]
    @overload
    def __init__(self, arg0: Context, arg1: "OnClientUpdateListener") -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: "OnClientUpdateListener", arg2: Looper) -> None: ...
    def getEstimatedMediaPosition(self) -> int: ...
    def sendMediaKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def seekTo(self, arg0: int) -> bool: ...
    def setArtworkConfiguration(self, arg0: int, arg1: int) -> bool: ...
    def clearArtworkConfiguration(self) -> bool: ...
    def setSynchronizationMode(self, arg0: int) -> bool: ...
    def editMetadata(self) -> "MetadataEditor": ...

    class MetadataEditor:
        def apply(self) -> None: ...

    class OnClientUpdateListener:
        def onClientChange(self, arg0: bool) -> None: ...
        @overload
        def onClientPlaybackStateUpdate(self, arg0: int) -> None: ...
        @overload
        def onClientPlaybackStateUpdate(self, arg0: int, arg1: int, arg2: int, arg3: float) -> None: ...
        def onClientTransportControlUpdate(self, arg0: int) -> None: ...
        def onClientMetadataUpdate(self, arg0: "MetadataEditor") -> None: ...
