from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.Context import Context
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.database.Cursor import Cursor
from android.media.Ringtone import Ringtone
from android.net.Uri import Uri

class RingtoneManager:
    ACTION_RINGTONE_PICKER: ClassVar[str]
    EXTRA_RINGTONE_DEFAULT_URI: ClassVar[str]
    EXTRA_RINGTONE_EXISTING_URI: ClassVar[str]
    EXTRA_RINGTONE_INCLUDE_DRM: ClassVar[str]
    EXTRA_RINGTONE_PICKED_URI: ClassVar[str]
    EXTRA_RINGTONE_SHOW_DEFAULT: ClassVar[str]
    EXTRA_RINGTONE_SHOW_SILENT: ClassVar[str]
    EXTRA_RINGTONE_TITLE: ClassVar[str]
    EXTRA_RINGTONE_TYPE: ClassVar[str]
    ID_COLUMN_INDEX: ClassVar[int]
    TITLE_COLUMN_INDEX: ClassVar[int]
    TYPE_ALARM: ClassVar[int]
    TYPE_ALL: ClassVar[int]
    TYPE_NOTIFICATION: ClassVar[int]
    TYPE_RINGTONE: ClassVar[int]
    URI_COLUMN_INDEX: ClassVar[int]
    @overload
    def __init__(self, arg0: Activity) -> None: ...
    @overload
    def __init__(self, arg0: Context) -> None: ...
    def setType(self, arg0: int) -> None: ...
    def inferStreamType(self) -> int: ...
    def setStopPreviousRingtone(self, arg0: bool) -> None: ...
    def getStopPreviousRingtone(self) -> bool: ...
    def stopPreviousRingtone(self) -> None: ...
    def getIncludeDrm(self) -> bool: ...
    def setIncludeDrm(self, arg0: bool) -> None: ...
    def getCursor(self) -> Cursor: ...
    @overload
    def getRingtone(self, arg0: int) -> Ringtone: ...
    @overload
    @staticmethod
    def getRingtone(arg0: Context, arg1: Uri) -> Ringtone: ...
    def getRingtoneUri(self, arg0: int) -> Uri: ...
    def getRingtonePosition(self, arg0: Uri) -> int: ...
    @staticmethod
    def getValidRingtoneUri(arg0: Context) -> Uri: ...
    @staticmethod
    def getActualDefaultRingtoneUri(arg0: Context, arg1: int) -> Uri: ...
    @staticmethod
    def setActualDefaultRingtoneUri(arg0: Context, arg1: int, arg2: Uri) -> None: ...
    @staticmethod
    def isDefault(arg0: Uri) -> bool: ...
    @staticmethod
    def getDefaultType(arg0: Uri) -> int: ...
    @staticmethod
    def getDefaultUri(arg0: int) -> Uri: ...
    @staticmethod
    def openDefaultRingtoneUri(arg0: Context, arg1: Uri) -> AssetFileDescriptor: ...
    @overload
    def hasHapticChannels(self, arg0: int) -> bool: ...
    @overload
    @staticmethod
    def hasHapticChannels(arg0: Uri) -> bool: ...
    @overload
    @staticmethod
    def hasHapticChannels(arg0: Context, arg1: Uri) -> bool: ...
