from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class RouteListingPreference:
    ACTION_TRANSFER_MEDIA: ClassVar[str]
    CREATOR: ClassVar[Creator]
    EXTRA_ROUTE_ID: ClassVar[str]
    def getItems(self) -> list: ...
    def getUseSystemOrdering(self) -> bool: ...
    def getLinkedItemComponentName(self) -> ComponentName: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setItems(self, arg0: list) -> "Builder": ...
        def setUseSystemOrdering(self, arg0: bool) -> "Builder": ...
        def setLinkedItemComponentName(self, arg0: ComponentName) -> "Builder": ...
        def build(self) -> "RouteListingPreference": ...

    class Item:
        CREATOR: ClassVar[Creator]
        FLAG_ONGOING_SESSION: ClassVar[int]
        FLAG_ONGOING_SESSION_MANAGED: ClassVar[int]
        FLAG_SUGGESTED: ClassVar[int]
        SELECTION_BEHAVIOR_GO_TO_APP: ClassVar[int]
        SELECTION_BEHAVIOR_NONE: ClassVar[int]
        SELECTION_BEHAVIOR_TRANSFER: ClassVar[int]
        SUBTEXT_AD_ROUTING_DISALLOWED: ClassVar[int]
        SUBTEXT_CUSTOM: ClassVar[int]
        SUBTEXT_DEVICE_LOW_POWER: ClassVar[int]
        SUBTEXT_DOWNLOADED_CONTENT_ROUTING_DISALLOWED: ClassVar[int]
        SUBTEXT_ERROR_UNKNOWN: ClassVar[int]
        SUBTEXT_NONE: ClassVar[int]
        SUBTEXT_SUBSCRIPTION_REQUIRED: ClassVar[int]
        SUBTEXT_TRACK_UNSUPPORTED: ClassVar[int]
        SUBTEXT_UNAUTHORIZED: ClassVar[int]
        def getRouteId(self) -> str: ...
        def getSelectionBehavior(self) -> int: ...
        def getFlags(self) -> int: ...
        def getSubText(self) -> int: ...
        def getCustomSubtextMessage(self) -> str: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setSelectionBehavior(self, arg0: int) -> "Builder": ...
            def setFlags(self, arg0: int) -> "Builder": ...
            def setSubText(self, arg0: int) -> "Builder": ...
            def setCustomSubtextMessage(self, arg0: str) -> "Builder": ...
            def build(self) -> "Item": ...
