from typing import Any, ClassVar, overload
from android.media.Session2Command import Session2Command
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Session2CommandGroup:
    CREATOR: ClassVar[Creator]
    @overload
    def hasCommand(self, arg0: Session2Command) -> bool: ...
    @overload
    def hasCommand(self, arg0: int) -> bool: ...
    def getCommands(self) -> set: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: "Session2CommandGroup") -> None: ...
        def addCommand(self, arg0: Session2Command) -> "Builder": ...
        def removeCommand(self, arg0: Session2Command) -> "Builder": ...
        def build(self) -> "Session2CommandGroup": ...
