from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.media.AudioAttributes import AudioAttributes
from java.io.FileDescriptor import FileDescriptor

class SoundPool:
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def release(self) -> None: ...
    def finalize(self) -> None: ...
    @overload
    def load(self, arg0: str, arg1: int) -> int: ...
    @overload
    def load(self, arg0: Context, arg1: int, arg2: int) -> int: ...
    @overload
    def load(self, arg0: AssetFileDescriptor, arg1: int) -> int: ...
    @overload
    def load(self, arg0: FileDescriptor, arg1: int, arg2: int, arg3: int) -> int: ...
    def unload(self, arg0: int) -> bool: ...
    def play(self, arg0: int, arg1: float, arg2: float, arg3: int, arg4: int, arg5: float) -> int: ...
    def pause(self, arg0: int) -> None: ...
    def resume(self, arg0: int) -> None: ...
    def autoPause(self) -> None: ...
    def autoResume(self) -> None: ...
    def stop(self, arg0: int) -> None: ...
    def setVolume(self, arg0: int, arg1: float, arg2: float) -> None: ...
    def setPriority(self, arg0: int, arg1: int) -> None: ...
    def setLoop(self, arg0: int, arg1: int) -> None: ...
    def setRate(self, arg0: int, arg1: float) -> None: ...
    def setOnLoadCompleteListener(self, arg0: "OnLoadCompleteListener") -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setMaxStreams(self, arg0: int) -> "Builder": ...
        def setAudioAttributes(self, arg0: AudioAttributes) -> "Builder": ...
        def setAudioSessionId(self, arg0: int) -> "Builder": ...
        def setContext(self, arg0: Context) -> "Builder": ...
        def build(self) -> "SoundPool": ...

    class OnLoadCompleteListener:
        def onLoadComplete(self, arg0: "SoundPool", arg1: int, arg2: int) -> None: ...
