from typing import Any, ClassVar, overload

class TimedMetaData:
    def __init__(self, arg0: int, arg1: list[int]) -> None: ...
    def getTimestamp(self) -> int: ...
    def getMetaData(self) -> list[int]: ...
