from typing import Any, ClassVar, overload

class ToneGenerator:
    MAX_VOLUME: ClassVar[int]
    MIN_VOLUME: ClassVar[int]
    TONE_CDMA_ABBR_ALERT: ClassVar[int]
    TONE_CDMA_ABBR_INTERCEPT: ClassVar[int]
    TONE_CDMA_ABBR_REORDER: ClassVar[int]
    TONE_CDMA_ALERT_AUTOREDIAL_LITE: ClassVar[int]
    TONE_CDMA_ALERT_CALL_GUARD: ClassVar[int]
    TONE_CDMA_ALERT_INCALL_LITE: ClassVar[int]
    TONE_CDMA_ALERT_NETWORK_LITE: ClassVar[int]
    TONE_CDMA_ANSWER: ClassVar[int]
    TONE_CDMA_CALLDROP_LITE: ClassVar[int]
    TONE_CDMA_CALL_SIGNAL_ISDN_INTERGROUP: ClassVar[int]
    TONE_CDMA_CALL_SIGNAL_ISDN_NORMAL: ClassVar[int]
    TONE_CDMA_CALL_SIGNAL_ISDN_PAT3: ClassVar[int]
    TONE_CDMA_CALL_SIGNAL_ISDN_PAT5: ClassVar[int]
    TONE_CDMA_CALL_SIGNAL_ISDN_PAT6: ClassVar[int]
    TONE_CDMA_CALL_SIGNAL_ISDN_PAT7: ClassVar[int]
    TONE_CDMA_CALL_SIGNAL_ISDN_PING_RING: ClassVar[int]
    TONE_CDMA_CALL_SIGNAL_ISDN_SP_PRI: ClassVar[int]
    TONE_CDMA_CONFIRM: ClassVar[int]
    TONE_CDMA_DIAL_TONE_LITE: ClassVar[int]
    TONE_CDMA_EMERGENCY_RINGBACK: ClassVar[int]
    TONE_CDMA_HIGH_L: ClassVar[int]
    TONE_CDMA_HIGH_PBX_L: ClassVar[int]
    TONE_CDMA_HIGH_PBX_SLS: ClassVar[int]
    TONE_CDMA_HIGH_PBX_SS: ClassVar[int]
    TONE_CDMA_HIGH_PBX_SSL: ClassVar[int]
    TONE_CDMA_HIGH_PBX_S_X4: ClassVar[int]
    TONE_CDMA_HIGH_SLS: ClassVar[int]
    TONE_CDMA_HIGH_SS: ClassVar[int]
    TONE_CDMA_HIGH_SSL: ClassVar[int]
    TONE_CDMA_HIGH_SS_2: ClassVar[int]
    TONE_CDMA_HIGH_S_X4: ClassVar[int]
    TONE_CDMA_INTERCEPT: ClassVar[int]
    TONE_CDMA_KEYPAD_VOLUME_KEY_LITE: ClassVar[int]
    TONE_CDMA_LOW_L: ClassVar[int]
    TONE_CDMA_LOW_PBX_L: ClassVar[int]
    TONE_CDMA_LOW_PBX_SLS: ClassVar[int]
    TONE_CDMA_LOW_PBX_SS: ClassVar[int]
    TONE_CDMA_LOW_PBX_SSL: ClassVar[int]
    TONE_CDMA_LOW_PBX_S_X4: ClassVar[int]
    TONE_CDMA_LOW_SLS: ClassVar[int]
    TONE_CDMA_LOW_SS: ClassVar[int]
    TONE_CDMA_LOW_SSL: ClassVar[int]
    TONE_CDMA_LOW_SS_2: ClassVar[int]
    TONE_CDMA_LOW_S_X4: ClassVar[int]
    TONE_CDMA_MED_L: ClassVar[int]
    TONE_CDMA_MED_PBX_L: ClassVar[int]
    TONE_CDMA_MED_PBX_SLS: ClassVar[int]
    TONE_CDMA_MED_PBX_SS: ClassVar[int]
    TONE_CDMA_MED_PBX_SSL: ClassVar[int]
    TONE_CDMA_MED_PBX_S_X4: ClassVar[int]
    TONE_CDMA_MED_SLS: ClassVar[int]
    TONE_CDMA_MED_SS: ClassVar[int]
    TONE_CDMA_MED_SSL: ClassVar[int]
    TONE_CDMA_MED_SS_2: ClassVar[int]
    TONE_CDMA_MED_S_X4: ClassVar[int]
    TONE_CDMA_NETWORK_BUSY: ClassVar[int]
    TONE_CDMA_NETWORK_BUSY_ONE_SHOT: ClassVar[int]
    TONE_CDMA_NETWORK_CALLWAITING: ClassVar[int]
    TONE_CDMA_NETWORK_USA_RINGBACK: ClassVar[int]
    TONE_CDMA_ONE_MIN_BEEP: ClassVar[int]
    TONE_CDMA_PIP: ClassVar[int]
    TONE_CDMA_PRESSHOLDKEY_LITE: ClassVar[int]
    TONE_CDMA_REORDER: ClassVar[int]
    TONE_CDMA_SIGNAL_OFF: ClassVar[int]
    TONE_CDMA_SOFT_ERROR_LITE: ClassVar[int]
    TONE_DTMF_0: ClassVar[int]
    TONE_DTMF_1: ClassVar[int]
    TONE_DTMF_2: ClassVar[int]
    TONE_DTMF_3: ClassVar[int]
    TONE_DTMF_4: ClassVar[int]
    TONE_DTMF_5: ClassVar[int]
    TONE_DTMF_6: ClassVar[int]
    TONE_DTMF_7: ClassVar[int]
    TONE_DTMF_8: ClassVar[int]
    TONE_DTMF_9: ClassVar[int]
    TONE_DTMF_A: ClassVar[int]
    TONE_DTMF_B: ClassVar[int]
    TONE_DTMF_C: ClassVar[int]
    TONE_DTMF_D: ClassVar[int]
    TONE_DTMF_P: ClassVar[int]
    TONE_DTMF_S: ClassVar[int]
    TONE_PROP_ACK: ClassVar[int]
    TONE_PROP_BEEP: ClassVar[int]
    TONE_PROP_BEEP2: ClassVar[int]
    TONE_PROP_NACK: ClassVar[int]
    TONE_PROP_PROMPT: ClassVar[int]
    TONE_SUP_BUSY: ClassVar[int]
    TONE_SUP_CALL_WAITING: ClassVar[int]
    TONE_SUP_CONFIRM: ClassVar[int]
    TONE_SUP_CONGESTION: ClassVar[int]
    TONE_SUP_CONGESTION_ABBREV: ClassVar[int]
    TONE_SUP_DIAL: ClassVar[int]
    TONE_SUP_ERROR: ClassVar[int]
    TONE_SUP_INTERCEPT: ClassVar[int]
    TONE_SUP_INTERCEPT_ABBREV: ClassVar[int]
    TONE_SUP_PIP: ClassVar[int]
    TONE_SUP_RADIO_ACK: ClassVar[int]
    TONE_SUP_RADIO_NOTAVAIL: ClassVar[int]
    TONE_SUP_RINGTONE: ClassVar[int]
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def startTone(self, arg0: int) -> bool: ...
    @overload
    def startTone(self, arg0: int, arg1: int) -> bool: ...
    def stopTone(self) -> None: ...
    def release(self) -> None: ...
    def getAudioSessionId(self) -> int: ...
    def finalize(self) -> None: ...
