from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class VolumeShaper:
    def apply(self, arg0: "Operation") -> None: ...
    def replace(self, arg0: "Configuration", arg1: "Operation", arg2: bool) -> None: ...
    def getVolume(self) -> float: ...
    def close(self) -> None: ...
    def finalize(self) -> None: ...

    class Configuration:
        CREATOR: ClassVar[Creator]
        CUBIC_RAMP: ClassVar["Configuration"]
        INTERPOLATOR_TYPE_CUBIC: ClassVar[int]
        INTERPOLATOR_TYPE_CUBIC_MONOTONIC: ClassVar[int]
        INTERPOLATOR_TYPE_LINEAR: ClassVar[int]
        INTERPOLATOR_TYPE_STEP: ClassVar[int]
        LINEAR_RAMP: ClassVar["Configuration"]
        SCURVE_RAMP: ClassVar["Configuration"]
        SINE_RAMP: ClassVar["Configuration"]
        @staticmethod
        def getMaximumCurvePoints() -> int: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def getInterpolatorType(self) -> int: ...
        def getDuration(self) -> int: ...
        def getTimes(self) -> list[float]: ...
        def getVolumes(self) -> list[float]: ...

        class Builder:
            @overload
            def __init__(self) -> None: ...
            @overload
            def __init__(self, arg0: "Configuration") -> None: ...
            def setInterpolatorType(self, arg0: int) -> "Builder": ...
            def setDuration(self, arg0: int) -> "Builder": ...
            def setCurve(self, arg0: list[float], arg1: list[float]) -> "Builder": ...
            def reflectTimes(self) -> "Builder": ...
            def invertVolumes(self) -> "Builder": ...
            def scaleToEndVolume(self, arg0: float) -> "Builder": ...
            def scaleToStartVolume(self, arg0: float) -> "Builder": ...
            def build(self) -> "Configuration": ...

    class Operation:
        CREATOR: ClassVar[Creator]
        PLAY: ClassVar["Operation"]
        REVERSE: ClassVar["Operation"]
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
