from typing import Any, ClassVar, overload
from android.icu.math.MathContext import MathContext
from java.math.BigInteger import BigInteger

class BigDecimal:
    ONE: ClassVar["BigDecimal"]
    ROUND_CEILING: ClassVar[int]
    ROUND_DOWN: ClassVar[int]
    ROUND_FLOOR: ClassVar[int]
    ROUND_HALF_DOWN: ClassVar[int]
    ROUND_HALF_EVEN: ClassVar[int]
    ROUND_HALF_UP: ClassVar[int]
    ROUND_UNNECESSARY: ClassVar[int]
    ROUND_UP: ClassVar[int]
    TEN: ClassVar["BigDecimal"]
    ZERO: ClassVar["BigDecimal"]
    @overload
    def __init__(self, arg0: "BigDecimal") -> None: ...
    @overload
    def __init__(self, arg0: BigInteger) -> None: ...
    @overload
    def __init__(self, arg0: BigInteger, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: list[str]) -> None: ...
    @overload
    def __init__(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: float) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def abs(self) -> "BigDecimal": ...
    @overload
    def abs(self, arg0: MathContext) -> "BigDecimal": ...
    @overload
    def add(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def add(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    @overload
    def compareTo(self, arg0: "BigDecimal") -> int: ...
    @overload
    def compareTo(self, arg0: "BigDecimal", arg1: MathContext) -> int: ...
    @overload
    def divide(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def divide(self, arg0: "BigDecimal", arg1: int) -> "BigDecimal": ...
    @overload
    def divide(self, arg0: "BigDecimal", arg1: int, arg2: int) -> "BigDecimal": ...
    @overload
    def divide(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    @overload
    def divideInteger(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def divideInteger(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    @overload
    def max(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def max(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    @overload
    def min(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def min(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    @overload
    def multiply(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def multiply(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    @overload
    def negate(self) -> "BigDecimal": ...
    @overload
    def negate(self, arg0: MathContext) -> "BigDecimal": ...
    @overload
    def plus(self) -> "BigDecimal": ...
    @overload
    def plus(self, arg0: MathContext) -> "BigDecimal": ...
    @overload
    def pow(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def pow(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    @overload
    def remainder(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def remainder(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    @overload
    def subtract(self, arg0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def subtract(self, arg0: "BigDecimal", arg1: MathContext) -> "BigDecimal": ...
    def byteValueExact(self) -> int: ...
    def doubleValue(self) -> float: ...
    def equals(self, arg0: Any) -> bool: ...
    def floatValue(self) -> float: ...
    @overload
    def format(self, arg0: int, arg1: int) -> str: ...
    @overload
    def format(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> str: ...
    def hashCode(self) -> int: ...
    def intValue(self) -> int: ...
    def intValueExact(self) -> int: ...
    def longValue(self) -> int: ...
    def longValueExact(self) -> int: ...
    def movePointLeft(self, arg0: int) -> "BigDecimal": ...
    def movePointRight(self, arg0: int) -> "BigDecimal": ...
    def scale(self) -> int: ...
    @overload
    def setScale(self, arg0: int) -> "BigDecimal": ...
    @overload
    def setScale(self, arg0: int, arg1: int) -> "BigDecimal": ...
    def shortValueExact(self) -> int: ...
    def signum(self) -> int: ...
    def toBigDecimal(self) -> "BigDecimal": ...
    def toBigInteger(self) -> BigInteger: ...
    def toBigIntegerExact(self) -> BigInteger: ...
    def toCharArray(self) -> list[str]: ...
    def toString(self) -> str: ...
    def unscaledValue(self) -> BigInteger: ...
    @overload
    @staticmethod
    def valueOf(arg0: float) -> "BigDecimal": ...
    @overload
    @staticmethod
    def valueOf(arg0: int) -> "BigDecimal": ...
    @overload
    @staticmethod
    def valueOf(arg0: int, arg1: int) -> "BigDecimal": ...
