from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["CivicLocationKeys"]

class CivicLocationKeys(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/wifi/rtt/CivicLocationKeys"
    ADDITIONAL_CODE = JavaStaticField("I")
    APT = JavaStaticField("I")
    BOROUGH = JavaStaticField("I")
    BRANCH_ROAD_NAME = JavaStaticField("I")
    BUILDING = JavaStaticField("I")
    CITY = JavaStaticField("I")
    COUNTY = JavaStaticField("I")
    DESK = JavaStaticField("I")
    FLOOR = JavaStaticField("I")
    GROUP_OF_STREETS = JavaStaticField("I")
    HNO = JavaStaticField("I")
    HNS = JavaStaticField("I")
    LANGUAGE = JavaStaticField("I")
    LMK = JavaStaticField("I")
    LOC = JavaStaticField("I")
    NAM = JavaStaticField("I")
    NEIGHBORHOOD = JavaStaticField("I")
    PCN = JavaStaticField("I")
    POD = JavaStaticField("I")
    POSTAL_CODE = JavaStaticField("I")
    PO_BOX = JavaStaticField("I")
    PRD = JavaStaticField("I")
    PRIMARY_ROAD_NAME = JavaStaticField("I")
    ROAD_SECTION = JavaStaticField("I")
    ROOM = JavaStaticField("I")
    SCRIPT = JavaStaticField("I")
    STATE = JavaStaticField("I")
    STREET_NAME_POST_MODIFIER = JavaStaticField("I")
    STREET_NAME_PRE_MODIFIER = JavaStaticField("I")
    STS = JavaStaticField("I")
    SUBBRANCH_ROAD_NAME = JavaStaticField("I")
    TYPE_OF_PLACE = JavaStaticField("I")