from typing import Any, ClassVar, overload
from android.media.metrics.LogSessionId import LogSessionId
from android.os.PersistableBundle import PersistableBundle

class BundleSession:
    KEY_STATSD_ATOM: ClassVar[str]
    def reportBundleMetrics(self, arg0: PersistableBundle) -> None: ...
    def getSessionId(self) -> LogSessionId: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def close(self) -> None: ...
