from typing import Any, ClassVar, overload
from android.media.metrics.EditingEndedEvent import EditingEndedEvent
from android.media.metrics.LogSessionId import LogSessionId

class EditingSession:
    def reportEditingEndedEvent(self, arg0: EditingEndedEvent) -> None: ...
    def getSessionId(self) -> LogSessionId: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def close(self) -> None: ...
