from typing import Any, ClassVar, overload

class LogSessionId:
    LOG_SESSION_ID_NONE: ClassVar["LogSessionId"]
    def getStringId(self) -> str: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
