from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.util.Size import Size

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class MediaItemInfo:
    CREATOR: ClassVar[Creator]
    DATA_TYPE_AUDIO: ClassVar[int]
    DATA_TYPE_DEPTH: ClassVar[int]
    DATA_TYPE_GAIN_MAP: ClassVar[int]
    DATA_TYPE_GAPLESS: ClassVar[int]
    DATA_TYPE_HIGH_DYNAMIC_RANGE_VIDEO: ClassVar[int]
    DATA_TYPE_HIGH_FRAME_RATE: ClassVar[int]
    DATA_TYPE_IMAGE: ClassVar[int]
    DATA_TYPE_METADATA: ClassVar[int]
    DATA_TYPE_SPATIAL_AUDIO: ClassVar[int]
    DATA_TYPE_SPEED_SETTING_CUE_POINTS: ClassVar[int]
    DATA_TYPE_VIDEO: ClassVar[int]
    SOURCE_TYPE_CAMERA: ClassVar[int]
    SOURCE_TYPE_EDITING_SESSION: ClassVar[int]
    SOURCE_TYPE_GALLERY: ClassVar[int]
    SOURCE_TYPE_GENERATED: ClassVar[int]
    SOURCE_TYPE_LOCAL_FILE: ClassVar[int]
    SOURCE_TYPE_REMOTE_FILE: ClassVar[int]
    SOURCE_TYPE_REMOTE_LIVE_STREAM: ClassVar[int]
    SOURCE_TYPE_UNSPECIFIED: ClassVar[int]
    VALUE_UNSPECIFIED: ClassVar[int]
    def getSourceType(self) -> int: ...
    def getDataTypes(self) -> int: ...
    def getDurationMillis(self) -> int: ...
    def getClipDurationMillis(self) -> int: ...
    def getContainerMimeType(self) -> str: ...
    def getSampleMimeTypes(self) -> list: ...
    def getCodecNames(self) -> list: ...
    def getAudioSampleRateHz(self) -> int: ...
    def getAudioChannelCount(self) -> int: ...
    def getAudioSampleCount(self) -> int: ...
    def getVideoSize(self) -> Size: ...
    def getVideoDataSpace(self) -> int: ...
    def getVideoFrameRate(self) -> float: ...
    def getVideoSampleCount(self) -> int: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setSourceType(self, arg0: int) -> "Builder": ...
        def addDataType(self, arg0: int) -> "Builder": ...
        def setDurationMillis(self, arg0: int) -> "Builder": ...
        def setClipDurationMillis(self, arg0: int) -> "Builder": ...
        def setContainerMimeType(self, arg0: str) -> "Builder": ...
        def addSampleMimeType(self, arg0: str) -> "Builder": ...
        def addCodecName(self, arg0: str) -> "Builder": ...
        def setAudioSampleRateHz(self, arg0: int) -> "Builder": ...
        def setAudioChannelCount(self, arg0: int) -> "Builder": ...
        def setAudioSampleCount(self, arg0: int) -> "Builder": ...
        def setVideoSize(self, arg0: Size) -> "Builder": ...
        def setVideoDataSpace(self, arg0: int) -> "Builder": ...
        def setVideoFrameRate(self, arg0: float) -> "Builder": ...
        def setVideoSampleCount(self, arg0: int) -> "Builder": ...
        def build(self) -> "MediaItemInfo": ...
