from typing import Any, ClassVar, overload
from android.media.metrics.BundleSession import BundleSession
from android.media.metrics.EditingSession import EditingSession
from android.media.metrics.PlaybackSession import PlaybackSession
from android.media.metrics.RecordingSession import RecordingSession
from android.media.metrics.TranscodingSession import TranscodingSession

class MediaMetricsManager:
    INVALID_TIMESTAMP: ClassVar[int]
    def createPlaybackSession(self) -> PlaybackSession: ...
    def createRecordingSession(self) -> RecordingSession: ...
    def createTranscodingSession(self) -> TranscodingSession: ...
    def createEditingSession(self) -> EditingSession: ...
    def createBundleSession(self) -> BundleSession: ...
    def releaseSessionId(self, arg0: str) -> None: ...
