from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint

class OvalShape:
    def __init__(self) -> None: ...
    def draw(self, arg0: Canvas, arg1: Paint) -> None: ...
    def getOutline(self, arg0: Outline) -> None: ...
    def clone(self) -> "OvalShape": ...
