from typing import Any, ClassVar, overload
from android.content.ClipData import ClipData
from android.content.ComponentName import ComponentName
from android.net.NetworkRequest import NetworkRequest
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.os.PersistableBundle import PersistableBundle

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class JobInfo:
    BACKOFF_POLICY_EXPONENTIAL: ClassVar[int]
    BACKOFF_POLICY_LINEAR: ClassVar[int]
    CREATOR: ClassVar[Creator]
    DEFAULT_INITIAL_BACKOFF_MILLIS: ClassVar[int]
    MAX_BACKOFF_DELAY_MILLIS: ClassVar[int]
    NETWORK_BYTES_UNKNOWN: ClassVar[int]
    NETWORK_TYPE_ANY: ClassVar[int]
    NETWORK_TYPE_CELLULAR: ClassVar[int]
    NETWORK_TYPE_METERED: ClassVar[int]
    NETWORK_TYPE_NONE: ClassVar[int]
    NETWORK_TYPE_NOT_ROAMING: ClassVar[int]
    NETWORK_TYPE_UNMETERED: ClassVar[int]
    PRIORITY_DEFAULT: ClassVar[int]
    PRIORITY_HIGH: ClassVar[int]
    PRIORITY_LOW: ClassVar[int]
    PRIORITY_MAX: ClassVar[int]
    PRIORITY_MIN: ClassVar[int]
    @staticmethod
    def getMinPeriodMillis() -> int: ...
    @staticmethod
    def getMinFlexMillis() -> int: ...
    def getId(self) -> int: ...
    def getExtras(self) -> PersistableBundle: ...
    def getTransientExtras(self) -> Bundle: ...
    def getClipData(self) -> ClipData: ...
    def getClipGrantFlags(self) -> int: ...
    def getService(self) -> ComponentName: ...
    def getPriority(self) -> int: ...
    def isRequireCharging(self) -> bool: ...
    def isRequireBatteryNotLow(self) -> bool: ...
    def isRequireDeviceIdle(self) -> bool: ...
    def isRequireStorageNotLow(self) -> bool: ...
    def getTriggerContentUris(self) -> list["TriggerContentUri"]: ...
    def getTriggerContentUpdateDelay(self) -> int: ...
    def getTriggerContentMaxDelay(self) -> int: ...
    def getNetworkType(self) -> int: ...
    def getRequiredNetwork(self) -> NetworkRequest: ...
    def getEstimatedNetworkDownloadBytes(self) -> int: ...
    def getEstimatedNetworkUploadBytes(self) -> int: ...
    def getMinimumNetworkChunkBytes(self) -> int: ...
    def getMinLatencyMillis(self) -> int: ...
    def getMaxExecutionDelayMillis(self) -> int: ...
    def isPeriodic(self) -> bool: ...
    def isPersisted(self) -> bool: ...
    def getIntervalMillis(self) -> int: ...
    def getFlexMillis(self) -> int: ...
    def getInitialBackoffMillis(self) -> int: ...
    def getBackoffPolicy(self) -> int: ...
    def getDebugTags(self) -> set: ...
    def getTraceTag(self) -> str: ...
    def isExpedited(self) -> bool: ...
    def isUserInitiated(self) -> bool: ...
    def isImportantWhileForeground(self) -> bool: ...
    def isPrefetch(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: int, arg1: ComponentName) -> None: ...
        def addDebugTag(self, arg0: str) -> "Builder": ...
        def removeDebugTag(self, arg0: str) -> "Builder": ...
        def setPriority(self, arg0: int) -> "Builder": ...
        def setExtras(self, arg0: PersistableBundle) -> "Builder": ...
        def setTransientExtras(self, arg0: Bundle) -> "Builder": ...
        def setClipData(self, arg0: ClipData, arg1: int) -> "Builder": ...
        def setRequiredNetworkType(self, arg0: int) -> "Builder": ...
        def setRequiredNetwork(self, arg0: NetworkRequest) -> "Builder": ...
        def setEstimatedNetworkBytes(self, arg0: int, arg1: int) -> "Builder": ...
        def setMinimumNetworkChunkBytes(self, arg0: int) -> "Builder": ...
        def setRequiresCharging(self, arg0: bool) -> "Builder": ...
        def setRequiresBatteryNotLow(self, arg0: bool) -> "Builder": ...
        def setRequiresDeviceIdle(self, arg0: bool) -> "Builder": ...
        def setRequiresStorageNotLow(self, arg0: bool) -> "Builder": ...
        def addTriggerContentUri(self, arg0: "TriggerContentUri") -> "Builder": ...
        def setTriggerContentUpdateDelay(self, arg0: int) -> "Builder": ...
        def setTriggerContentMaxDelay(self, arg0: int) -> "Builder": ...
        @overload
        def setPeriodic(self, arg0: int) -> "Builder": ...
        @overload
        def setPeriodic(self, arg0: int, arg1: int) -> "Builder": ...
        def setMinimumLatency(self, arg0: int) -> "Builder": ...
        def setOverrideDeadline(self, arg0: int) -> "Builder": ...
        def setBackoffCriteria(self, arg0: int, arg1: int) -> "Builder": ...
        def setExpedited(self, arg0: bool) -> "Builder": ...
        def setUserInitiated(self, arg0: bool) -> "Builder": ...
        def setImportantWhileForeground(self, arg0: bool) -> "Builder": ...
        def setPrefetch(self, arg0: bool) -> "Builder": ...
        def setPersisted(self, arg0: bool) -> "Builder": ...
        def setTraceTag(self, arg0: str) -> "Builder": ...
        def build(self) -> "JobInfo": ...

    class TriggerContentUri:
        CREATOR: ClassVar[Creator]
        FLAG_NOTIFY_FOR_DESCENDANTS: ClassVar[int]
        def __init__(self, arg0: Uri, arg1: int) -> None: ...
        def getUri(self) -> Uri: ...
        def getFlags(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
