from typing import Any, ClassVar, overload
from android.app.job.JobInfo import JobInfo
from android.app.job.JobWorkItem import JobWorkItem

class JobScheduler:
    PENDING_JOB_REASON_APP: ClassVar[int]
    PENDING_JOB_REASON_APP_STANDBY: ClassVar[int]
    PENDING_JOB_REASON_BACKGROUND_RESTRICTION: ClassVar[int]
    PENDING_JOB_REASON_CONSTRAINT_BATTERY_NOT_LOW: ClassVar[int]
    PENDING_JOB_REASON_CONSTRAINT_CHARGING: ClassVar[int]
    PENDING_JOB_REASON_CONSTRAINT_CONNECTIVITY: ClassVar[int]
    PENDING_JOB_REASON_CONSTRAINT_CONTENT_TRIGGER: ClassVar[int]
    PENDING_JOB_REASON_CONSTRAINT_DEVICE_IDLE: ClassVar[int]
    PENDING_JOB_REASON_CONSTRAINT_MINIMUM_LATENCY: ClassVar[int]
    PENDING_JOB_REASON_CONSTRAINT_PREFETCH: ClassVar[int]
    PENDING_JOB_REASON_CONSTRAINT_STORAGE_NOT_LOW: ClassVar[int]
    PENDING_JOB_REASON_DEVICE_STATE: ClassVar[int]
    PENDING_JOB_REASON_EXECUTING: ClassVar[int]
    PENDING_JOB_REASON_INVALID_JOB_ID: ClassVar[int]
    PENDING_JOB_REASON_JOB_SCHEDULER_OPTIMIZATION: ClassVar[int]
    PENDING_JOB_REASON_QUOTA: ClassVar[int]
    PENDING_JOB_REASON_UNDEFINED: ClassVar[int]
    PENDING_JOB_REASON_USER: ClassVar[int]
    RESULT_FAILURE: ClassVar[int]
    RESULT_SUCCESS: ClassVar[int]
    def __init__(self) -> None: ...
    def forNamespace(self, arg0: str) -> "JobScheduler": ...
    def getNamespace(self) -> str: ...
    def schedule(self, arg0: JobInfo) -> int: ...
    def enqueue(self, arg0: JobInfo, arg1: JobWorkItem) -> int: ...
    def cancel(self, arg0: int) -> None: ...
    def cancelAll(self) -> None: ...
    def cancelInAllNamespaces(self) -> None: ...
    def getAllPendingJobs(self) -> list: ...
    def getPendingJobsInAllNamespaces(self) -> dict: ...
    def getPendingJob(self, arg0: int) -> JobInfo: ...
    def getPendingJobReason(self, arg0: int) -> int: ...
    def canRunUserInitiatedJobs(self) -> bool: ...
