from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.Parcel import Parcel
from android.os.PersistableBundle import PersistableBundle

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class JobWorkItem:
    CREATOR: ClassVar[Creator]
    @overload
    def __init__(self, arg0: Intent) -> None: ...
    @overload
    def __init__(self, arg0: Intent, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Intent, arg1: int, arg2: int, arg3: int) -> None: ...
    def getExtras(self) -> PersistableBundle: ...
    def getIntent(self) -> Intent: ...
    def getEstimatedNetworkDownloadBytes(self) -> int: ...
    def getEstimatedNetworkUploadBytes(self) -> int: ...
    def getMinimumNetworkChunkBytes(self) -> int: ...
    def getDeliveryCount(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setExtras(self, arg0: PersistableBundle) -> "Builder": ...
        def setIntent(self, arg0: Intent) -> "Builder": ...
        def setEstimatedNetworkBytes(self, arg0: int, arg1: int) -> "Builder": ...
        def setMinimumNetworkChunkBytes(self, arg0: int) -> "Builder": ...
        def build(self) -> "JobWorkItem": ...
