from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.OutputStream import OutputStream
from java.io.Writer import Writer

class StreamResult:
    FEATURE: ClassVar[str]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: OutputStream) -> None: ...
    @overload
    def __init__(self, arg0: Writer) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: File) -> None: ...
    def setOutputStream(self, arg0: OutputStream) -> None: ...
    def getOutputStream(self) -> OutputStream: ...
    def setWriter(self, arg0: Writer) -> None: ...
    def getWriter(self) -> Writer: ...
    @overload
    def setSystemId(self, arg0: str) -> None: ...
    @overload
    def setSystemId(self, arg0: File) -> None: ...
    def getSystemId(self) -> str: ...
