from typing import Any, ClassVar, overload

class CameraOfflineSession:
    def __init__(self) -> None: ...
    def close(self) -> None: ...

    class CameraOfflineSessionCallback:
        STATUS_INTERNAL_ERROR: ClassVar[int]
        def __init__(self) -> None: ...
        def onReady(self, arg0: "CameraOfflineSession") -> None: ...
        def onSwitchFailed(self, arg0: "CameraOfflineSession") -> None: ...
        def onIdle(self, arg0: "CameraOfflineSession") -> None: ...
        def onError(self, arg0: "CameraOfflineSession", arg1: int) -> None: ...
        def onClosed(self, arg0: "CameraOfflineSession") -> None: ...
