from typing import Any, ClassVar, overload
from android.hardware.camera2.CameraCharacteristics import CameraCharacteristics
from android.hardware.camera2.CameraExtensionCharacteristics import CameraExtensionCharacteristics
from android.os.Handler import Handler
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class CameraDeviceSetup:
    """Forward declaration for ``android.hardware.camera2.CameraDevice.CameraDeviceSetup``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.hardware.camera2.CameraDevice.CameraDeviceSetup')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/hardware/camera2/CameraDevice/CameraDeviceSetup
    """
    ...
class StateCallback:
    """Forward declaration for ``android.hardware.camera2.CameraDevice.StateCallback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.hardware.camera2.CameraDevice.StateCallback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/hardware/camera2/CameraDevice/StateCallback
    """
    ...

class CameraManager:
    def getCameraIdList(self) -> list[str]: ...
    def getConcurrentCameraIds(self) -> set: ...
    def isConcurrentSessionConfigurationSupported(self, arg0: dict) -> bool: ...
    @overload
    def registerAvailabilityCallback(self, arg0: "AvailabilityCallback", arg1: Handler) -> None: ...
    @overload
    def registerAvailabilityCallback(self, arg0: Executor, arg1: "AvailabilityCallback") -> None: ...
    def unregisterAvailabilityCallback(self, arg0: "AvailabilityCallback") -> None: ...
    @overload
    def registerTorchCallback(self, arg0: "TorchCallback", arg1: Handler) -> None: ...
    @overload
    def registerTorchCallback(self, arg0: Executor, arg1: "TorchCallback") -> None: ...
    def unregisterTorchCallback(self, arg0: "TorchCallback") -> None: ...
    def getCameraCharacteristics(self, arg0: str) -> CameraCharacteristics: ...
    def getCameraExtensionCharacteristics(self, arg0: str) -> CameraExtensionCharacteristics: ...
    def getCameraDeviceSetup(self, arg0: str) -> CameraDeviceSetup: ...
    def isCameraDeviceSetupSupported(self, arg0: str) -> bool: ...
    @overload
    def openCamera(self, arg0: str, arg1: StateCallback, arg2: Handler) -> None: ...
    @overload
    def openCamera(self, arg0: str, arg1: Executor, arg2: StateCallback) -> None: ...
    def setTorchMode(self, arg0: str, arg1: bool) -> None: ...
    def turnOnTorchWithStrengthLevel(self, arg0: str, arg1: int) -> None: ...
    def getTorchStrengthLevel(self, arg0: str) -> int: ...

    class AvailabilityCallback:
        def __init__(self) -> None: ...
        def onCameraAvailable(self, arg0: str) -> None: ...
        def onCameraUnavailable(self, arg0: str) -> None: ...
        def onCameraAccessPrioritiesChanged(self) -> None: ...
        def onPhysicalCameraAvailable(self, arg0: str, arg1: str) -> None: ...
        def onPhysicalCameraUnavailable(self, arg0: str, arg1: str) -> None: ...

    class TorchCallback:
        def __init__(self) -> None: ...
        def onTorchModeUnavailable(self, arg0: str) -> None: ...
        def onTorchModeChanged(self, arg0: str, arg1: bool) -> None: ...
        def onTorchStrengthLevelChanged(self, arg0: str, arg1: int) -> None: ...
