from typing import Any, ClassVar, overload
from android.hardware.camera2.CameraCharacteristics import CameraCharacteristics
from android.hardware.camera2.TotalCaptureResult import TotalCaptureResult
from android.hardware.camera2.params.ExtensionSessionConfiguration import ExtensionSessionConfiguration
from android.hardware.camera2.params.InputConfiguration import InputConfiguration
from android.hardware.camera2.params.SessionConfiguration import SessionConfiguration
from android.os.Handler import Handler
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Builder:
    """Forward declaration for ``android.hardware.camera2.CaptureRequest.Builder``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.hardware.camera2.CaptureRequest.Builder')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/hardware/camera2/CaptureRequest/Builder
    """
    ...

class CameraDevice:
    AUDIO_RESTRICTION_NONE: ClassVar[int]
    AUDIO_RESTRICTION_VIBRATION: ClassVar[int]
    AUDIO_RESTRICTION_VIBRATION_SOUND: ClassVar[int]
    TEMPLATE_MANUAL: ClassVar[int]
    TEMPLATE_PREVIEW: ClassVar[int]
    TEMPLATE_RECORD: ClassVar[int]
    TEMPLATE_STILL_CAPTURE: ClassVar[int]
    TEMPLATE_VIDEO_SNAPSHOT: ClassVar[int]
    TEMPLATE_ZERO_SHUTTER_LAG: ClassVar[int]
    def getId(self) -> str: ...
    @overload
    def createCaptureSession(self, arg0: list, arg1: "StateCallback", arg2: Handler) -> None: ...
    @overload
    def createCaptureSession(self, arg0: SessionConfiguration) -> None: ...
    def createCaptureSessionByOutputConfigurations(self, arg0: list, arg1: "StateCallback", arg2: Handler) -> None: ...
    def createReprocessableCaptureSession(self, arg0: InputConfiguration, arg1: list, arg2: "StateCallback", arg3: Handler) -> None: ...
    def createReprocessableCaptureSessionByConfigurations(self, arg0: InputConfiguration, arg1: list, arg2: "StateCallback", arg3: Handler) -> None: ...
    def createConstrainedHighSpeedCaptureSession(self, arg0: list, arg1: "StateCallback", arg2: Handler) -> None: ...
    def createExtensionSession(self, arg0: ExtensionSessionConfiguration) -> None: ...
    @overload
    def createCaptureRequest(self, arg0: int) -> Builder: ...
    @overload
    def createCaptureRequest(self, arg0: int, arg1: set) -> Builder: ...
    def createReprocessCaptureRequest(self, arg0: TotalCaptureResult) -> Builder: ...
    def close(self) -> None: ...
    def isSessionConfigurationSupported(self, arg0: SessionConfiguration) -> bool: ...
    def setCameraAudioRestriction(self, arg0: int) -> None: ...
    def getCameraAudioRestriction(self) -> int: ...

    class CameraDeviceSetup:
        def createCaptureRequest(self, arg0: int) -> Builder: ...
        def isSessionConfigurationSupported(self, arg0: SessionConfiguration) -> bool: ...
        def getSessionCharacteristics(self, arg0: SessionConfiguration) -> CameraCharacteristics: ...
        def openCamera(self, arg0: Executor, arg1: "StateCallback") -> None: ...
        def getId(self) -> str: ...

    class StateCallback:
        ERROR_CAMERA_DEVICE: ClassVar[int]
        ERROR_CAMERA_DISABLED: ClassVar[int]
        ERROR_CAMERA_IN_USE: ClassVar[int]
        ERROR_CAMERA_SERVICE: ClassVar[int]
        ERROR_MAX_CAMERAS_IN_USE: ClassVar[int]
        def __init__(self) -> None: ...
        def onOpened(self, arg0: "CameraDevice") -> None: ...
        def onClosed(self, arg0: "CameraDevice") -> None: ...
        def onDisconnected(self, arg0: "CameraDevice") -> None: ...
        def onError(self, arg0: "CameraDevice", arg1: int) -> None: ...
