from typing import Any, ClassVar, overload
from android.hardware.camera2.CameraDevice import CameraDevice
from android.hardware.camera2.CameraOfflineSession import CameraOfflineSession
from android.hardware.camera2.CaptureFailure import CaptureFailure
from android.hardware.camera2.CaptureRequest import CaptureRequest
from android.hardware.camera2.CaptureResult import CaptureResult
from android.hardware.camera2.TotalCaptureResult import TotalCaptureResult
from android.hardware.camera2.params.OutputConfiguration import OutputConfiguration
from android.os.Handler import Handler
from android.view.Surface import Surface
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class CameraOfflineSessionCallback:
    """Forward declaration for ``android.hardware.camera2.CameraOfflineSession.CameraOfflineSessionCallback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.hardware.camera2.CameraOfflineSession.CameraOfflineSessionCallback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/hardware/camera2/CameraOfflineSession/CameraOfflineSessionCallback
    """
    ...

class CameraCaptureSession:
    def __init__(self) -> None: ...
    def getDevice(self) -> CameraDevice: ...
    def prepare(self, arg0: Surface) -> None: ...
    def finalizeOutputConfigurations(self, arg0: list) -> None: ...
    def capture(self, arg0: CaptureRequest, arg1: "CaptureCallback", arg2: Handler) -> int: ...
    def captureSingleRequest(self, arg0: CaptureRequest, arg1: Executor, arg2: "CaptureCallback") -> int: ...
    def captureBurst(self, arg0: list, arg1: "CaptureCallback", arg2: Handler) -> int: ...
    def captureBurstRequests(self, arg0: list, arg1: Executor, arg2: "CaptureCallback") -> int: ...
    def setRepeatingRequest(self, arg0: CaptureRequest, arg1: "CaptureCallback", arg2: Handler) -> int: ...
    def setSingleRepeatingRequest(self, arg0: CaptureRequest, arg1: Executor, arg2: "CaptureCallback") -> int: ...
    def setRepeatingBurst(self, arg0: list, arg1: "CaptureCallback", arg2: Handler) -> int: ...
    def setRepeatingBurstRequests(self, arg0: list, arg1: Executor, arg2: "CaptureCallback") -> int: ...
    def stopRepeating(self) -> None: ...
    def abortCaptures(self) -> None: ...
    def isReprocessable(self) -> bool: ...
    def getInputSurface(self) -> Surface: ...
    def updateOutputConfiguration(self, arg0: OutputConfiguration) -> None: ...
    def switchToOffline(self, arg0: list, arg1: Executor, arg2: CameraOfflineSessionCallback) -> CameraOfflineSession: ...
    def supportsOfflineProcessing(self, arg0: Surface) -> bool: ...
    def close(self) -> None: ...

    class CaptureCallback:
        def __init__(self) -> None: ...
        def onCaptureStarted(self, arg0: "CameraCaptureSession", arg1: CaptureRequest, arg2: int, arg3: int) -> None: ...
        def onReadoutStarted(self, arg0: "CameraCaptureSession", arg1: CaptureRequest, arg2: int, arg3: int) -> None: ...
        def onCaptureProgressed(self, arg0: "CameraCaptureSession", arg1: CaptureRequest, arg2: CaptureResult) -> None: ...
        def onCaptureCompleted(self, arg0: "CameraCaptureSession", arg1: CaptureRequest, arg2: TotalCaptureResult) -> None: ...
        def onCaptureFailed(self, arg0: "CameraCaptureSession", arg1: CaptureRequest, arg2: CaptureFailure) -> None: ...
        def onCaptureSequenceCompleted(self, arg0: "CameraCaptureSession", arg1: int, arg2: int) -> None: ...
        def onCaptureSequenceAborted(self, arg0: "CameraCaptureSession", arg1: int) -> None: ...
        def onCaptureBufferLost(self, arg0: "CameraCaptureSession", arg1: CaptureRequest, arg2: Surface, arg3: int) -> None: ...

    class StateCallback:
        def __init__(self) -> None: ...
        def onConfigured(self, arg0: "CameraCaptureSession") -> None: ...
        def onConfigureFailed(self, arg0: "CameraCaptureSession") -> None: ...
        def onReady(self, arg0: "CameraCaptureSession") -> None: ...
        def onActive(self, arg0: "CameraCaptureSession") -> None: ...
        def onCaptureQueueEmpty(self, arg0: "CameraCaptureSession") -> None: ...
        def onClosed(self, arg0: "CameraCaptureSession") -> None: ...
        def onSurfacePrepared(self, arg0: "CameraCaptureSession", arg1: Surface) -> None: ...
