from typing import Any, ClassVar, overload
from android.util.Range import Range
from android.util.Size import Size

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Key:
    """Forward declaration for ``android.hardware.camera2.CameraCharacteristics.Key``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.hardware.camera2.CameraCharacteristics.Key')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics/Key
    """
    ...

class CameraExtensionCharacteristics:
    EXTENSION_AUTOMATIC: ClassVar[int]
    EXTENSION_BEAUTY: ClassVar[int]
    EXTENSION_BOKEH: ClassVar[int]
    EXTENSION_FACE_RETOUCH: ClassVar[int]
    EXTENSION_HDR: ClassVar[int]
    EXTENSION_NIGHT: ClassVar[int]
    def getSupportedExtensions(self) -> list: ...
    def get(self, arg0: int, arg1: Key) -> Any: ...
    def getKeys(self, arg0: int) -> set: ...
    def isPostviewAvailable(self, arg0: int) -> bool: ...
    def getPostviewSupportedSizes(self, arg0: int, arg1: Size, arg2: int) -> list: ...
    @overload
    def getExtensionSupportedSizes(self, arg0: int, arg1: type) -> list: ...
    @overload
    def getExtensionSupportedSizes(self, arg0: int, arg1: int) -> list: ...
    def getEstimatedCaptureLatencyRangeMillis(self, arg0: int, arg1: Size, arg2: int) -> Range: ...
    def isCaptureProcessProgressAvailable(self, arg0: int) -> bool: ...
    def getAvailableCaptureRequestKeys(self, arg0: int) -> set: ...
    def getAvailableCaptureResultKeys(self, arg0: int) -> set: ...
