from typing import Any, ClassVar, overload
from android.hardware.camera2.CameraDevice import CameraDevice
from android.hardware.camera2.CaptureRequest import CaptureRequest
from android.hardware.camera2.TotalCaptureResult import TotalCaptureResult
from java.util.concurrent.Executor import Executor

class CameraExtensionSession:
    def getDevice(self) -> CameraDevice: ...
    def capture(self, arg0: CaptureRequest, arg1: Executor, arg2: "ExtensionCaptureCallback") -> int: ...
    def setRepeatingRequest(self, arg0: CaptureRequest, arg1: Executor, arg2: "ExtensionCaptureCallback") -> int: ...
    def stopRepeating(self) -> None: ...
    def getRealtimeStillCaptureLatency(self) -> "StillCaptureLatency": ...
    def close(self) -> None: ...

    class ExtensionCaptureCallback:
        def __init__(self) -> None: ...
        def onCaptureStarted(self, arg0: "CameraExtensionSession", arg1: CaptureRequest, arg2: int) -> None: ...
        def onCaptureProcessStarted(self, arg0: "CameraExtensionSession", arg1: CaptureRequest) -> None: ...
        @overload
        def onCaptureFailed(self, arg0: "CameraExtensionSession", arg1: CaptureRequest) -> None: ...
        @overload
        def onCaptureFailed(self, arg0: "CameraExtensionSession", arg1: CaptureRequest, arg2: int) -> None: ...
        def onCaptureSequenceCompleted(self, arg0: "CameraExtensionSession", arg1: int) -> None: ...
        def onCaptureSequenceAborted(self, arg0: "CameraExtensionSession", arg1: int) -> None: ...
        def onCaptureResultAvailable(self, arg0: "CameraExtensionSession", arg1: CaptureRequest, arg2: TotalCaptureResult) -> None: ...
        def onCaptureProcessProgressed(self, arg0: "CameraExtensionSession", arg1: CaptureRequest, arg2: int) -> None: ...

    class StateCallback:
        def __init__(self) -> None: ...
        def onConfigured(self, arg0: "CameraExtensionSession") -> None: ...
        def onConfigureFailed(self, arg0: "CameraExtensionSession") -> None: ...
        def onClosed(self, arg0: "CameraExtensionSession") -> None: ...

    class StillCaptureLatency:
        def __init__(self, arg0: int, arg1: int) -> None: ...
        def getCaptureLatency(self) -> int: ...
        def getProcessingLatency(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...
