from typing import Any, ClassVar, overload

class IndexedPropertyChangeEvent:
    def __init__(self, arg0: Any, arg1: str, arg2: Any, arg3: Any, arg4: int) -> None: ...
    def getIndex(self) -> int: ...
