from typing import Any, ClassVar, overload
from java.beans.PropertyChangeEvent import PropertyChangeEvent
from java.beans.PropertyChangeListener import PropertyChangeListener

class PropertyChangeSupport:
    def __init__(self, arg0: Any) -> None: ...
    @overload
    def addPropertyChangeListener(self, arg0: PropertyChangeListener) -> None: ...
    @overload
    def addPropertyChangeListener(self, arg0: str, arg1: PropertyChangeListener) -> None: ...
    @overload
    def removePropertyChangeListener(self, arg0: PropertyChangeListener) -> None: ...
    @overload
    def removePropertyChangeListener(self, arg0: str, arg1: PropertyChangeListener) -> None: ...
    @overload
    def getPropertyChangeListeners(self) -> list[PropertyChangeListener]: ...
    @overload
    def getPropertyChangeListeners(self, arg0: str) -> list[PropertyChangeListener]: ...
    @overload
    def firePropertyChange(self, arg0: str, arg1: Any, arg2: Any) -> None: ...
    @overload
    def firePropertyChange(self, arg0: str, arg1: int, arg2: int) -> None: ...
    @overload
    def firePropertyChange(self, arg0: str, arg1: bool, arg2: bool) -> None: ...
    @overload
    def firePropertyChange(self, arg0: PropertyChangeEvent) -> None: ...
    @overload
    def fireIndexedPropertyChange(self, arg0: str, arg1: int, arg2: Any, arg3: Any) -> None: ...
    @overload
    def fireIndexedPropertyChange(self, arg0: str, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def fireIndexedPropertyChange(self, arg0: str, arg1: int, arg2: bool, arg3: bool) -> None: ...
    def hasListeners(self, arg0: str) -> bool: ...
