from typing import Any, ClassVar, overload
from android.graphics.fonts.Font import Font

class FontFamily:
    def getFont(self, arg0: int) -> Font: ...
    def getSize(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Font) -> None: ...
        def addFont(self, arg0: Font) -> "Builder": ...
        def buildVariableFamily(self) -> "FontFamily": ...
        def build(self) -> "FontFamily": ...
