from typing import Any, ClassVar, overload
from android.net.rtp.AudioCodec import AudioCodec
from android.net.rtp.AudioGroup import AudioGroup
from java.net.InetAddress import InetAddress

class AudioStream:
    def __init__(self, arg0: InetAddress) -> None: ...
    def isBusy(self) -> bool: ...
    def getGroup(self) -> AudioGroup: ...
    def join(self, arg0: AudioGroup) -> None: ...
    def getCodec(self) -> AudioCodec: ...
    def setCodec(self, arg0: AudioCodec) -> None: ...
    def getDtmfType(self) -> int: ...
    def setDtmfType(self, arg0: int) -> None: ...
