from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.animation.Transformation import Transformation

class AlphaAnimation:
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: float) -> None: ...
    def applyTransformation(self, arg0: float, arg1: Transformation) -> None: ...
    def willChangeTransformationMatrix(self) -> bool: ...
    def willChangeBounds(self) -> bool: ...
