from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.view.animation.Animation import Animation
from android.view.animation.Interpolator import Interpolator
from android.view.animation.LayoutAnimationController import LayoutAnimationController

class AnimationUtils:
    def __init__(self) -> None: ...
    @staticmethod
    def currentAnimationTimeMillis() -> int: ...
    @staticmethod
    def loadAnimation(arg0: Context, arg1: int) -> Animation: ...
    @staticmethod
    def loadLayoutAnimation(arg0: Context, arg1: int) -> LayoutAnimationController: ...
    @staticmethod
    def makeInAnimation(arg0: Context, arg1: bool) -> Animation: ...
    @staticmethod
    def makeOutAnimation(arg0: Context, arg1: bool) -> Animation: ...
    @staticmethod
    def makeInChildBottomAnimation(arg0: Context) -> Animation: ...
    @staticmethod
    def loadInterpolator(arg0: Context, arg1: int) -> Interpolator: ...
