from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.View import View
from android.view.animation.Animation import Animation

class GridLayoutAnimationController:
    DIRECTION_BOTTOM_TO_TOP: ClassVar[int]
    DIRECTION_HORIZONTAL_MASK: ClassVar[int]
    DIRECTION_LEFT_TO_RIGHT: ClassVar[int]
    DIRECTION_RIGHT_TO_LEFT: ClassVar[int]
    DIRECTION_TOP_TO_BOTTOM: ClassVar[int]
    DIRECTION_VERTICAL_MASK: ClassVar[int]
    PRIORITY_COLUMN: ClassVar[int]
    PRIORITY_NONE: ClassVar[int]
    PRIORITY_ROW: ClassVar[int]
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Animation) -> None: ...
    @overload
    def __init__(self, arg0: Animation, arg1: float, arg2: float) -> None: ...
    def getColumnDelay(self) -> float: ...
    def setColumnDelay(self, arg0: float) -> None: ...
    def getRowDelay(self) -> float: ...
    def setRowDelay(self, arg0: float) -> None: ...
    def getDirection(self) -> int: ...
    def setDirection(self, arg0: int) -> None: ...
    def getDirectionPriority(self) -> int: ...
    def setDirectionPriority(self, arg0: int) -> None: ...
    def willOverlap(self) -> bool: ...
    def getDelayForView(self, arg0: View) -> int: ...

    class AnimationParameters:
        column: int
        columnsCount: int
        row: int
        rowsCount: int
        def __init__(self) -> None: ...
