from typing import Any, ClassVar, overload
from android.graphics.Matrix import Matrix

class Transformation:
    TYPE_ALPHA: ClassVar[int]
    TYPE_BOTH: ClassVar[int]
    TYPE_IDENTITY: ClassVar[int]
    TYPE_MATRIX: ClassVar[int]
    mAlpha: float
    mMatrix: Matrix
    mTransformationType: int
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def getTransformationType(self) -> int: ...
    def setTransformationType(self, arg0: int) -> None: ...
    def set(self, arg0: "Transformation") -> None: ...
    def compose(self, arg0: "Transformation") -> None: ...
    def getMatrix(self) -> Matrix: ...
    def setAlpha(self, arg0: float) -> None: ...
    def getAlpha(self) -> float: ...
    def toString(self) -> str: ...
    def toShortString(self) -> str: ...
