from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.ByteOrder import ByteOrder
from java.nio.CharBuffer import CharBuffer
from java.nio.DoubleBuffer import DoubleBuffer
from java.nio.FloatBuffer import FloatBuffer
from java.nio.IntBuffer import IntBuffer
from java.nio.LongBuffer import LongBuffer
from java.nio.ShortBuffer import ShortBuffer

class ByteBuffer:
    @staticmethod
    def allocateDirect(arg0: int) -> "ByteBuffer": ...
    @staticmethod
    def allocate(arg0: int) -> "ByteBuffer": ...
    @overload
    @staticmethod
    def wrap(arg0: list[int], arg1: int, arg2: int) -> "ByteBuffer": ...
    @overload
    @staticmethod
    def wrap(arg0: list[int]) -> "ByteBuffer": ...
    @overload
    def slice(self) -> "ByteBuffer": ...
    @overload
    def slice(self, arg0: int, arg1: int) -> "ByteBuffer": ...
    def duplicate(self) -> "ByteBuffer": ...
    def asReadOnlyBuffer(self) -> "ByteBuffer": ...
    @overload
    def get(self) -> int: ...
    @overload
    def get(self, arg0: int) -> int: ...
    @overload
    def get(self, arg0: list[int], arg1: int, arg2: int) -> "ByteBuffer": ...
    @overload
    def get(self, arg0: list[int]) -> "ByteBuffer": ...
    @overload
    def get(self, arg0: int, arg1: list[int], arg2: int, arg3: int) -> "ByteBuffer": ...
    @overload
    def get(self, arg0: int, arg1: list[int]) -> "ByteBuffer": ...
    @overload
    def put(self, arg0: int) -> "ByteBuffer": ...
    @overload
    def put(self, arg0: int, arg1: int) -> "ByteBuffer": ...
    @overload
    def put(self, arg0: "ByteBuffer") -> "ByteBuffer": ...
    @overload
    def put(self, arg0: int, arg1: "ByteBuffer", arg2: int, arg3: int) -> "ByteBuffer": ...
    @overload
    def put(self, arg0: list[int], arg1: int, arg2: int) -> "ByteBuffer": ...
    @overload
    def put(self, arg0: list[int]) -> "ByteBuffer": ...
    @overload
    def put(self, arg0: int, arg1: list[int], arg2: int, arg3: int) -> "ByteBuffer": ...
    @overload
    def put(self, arg0: int, arg1: list[int]) -> "ByteBuffer": ...
    def hasArray(self) -> bool: ...
    def array(self) -> list[int]: ...
    def arrayOffset(self) -> int: ...
    def position(self, arg0: int) -> Buffer: ...
    def limit(self, arg0: int) -> Buffer: ...
    def mark(self) -> Buffer: ...
    def reset(self) -> Buffer: ...
    def clear(self) -> Buffer: ...
    def flip(self) -> Buffer: ...
    def rewind(self) -> Buffer: ...
    def compact(self) -> "ByteBuffer": ...
    def isDirect(self) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def compareTo(self, arg0: "ByteBuffer") -> int: ...
    def mismatch(self, arg0: "ByteBuffer") -> int: ...
    @overload
    def order(self) -> ByteOrder: ...
    @overload
    def order(self, arg0: ByteOrder) -> "ByteBuffer": ...
    def alignmentOffset(self, arg0: int, arg1: int) -> int: ...
    def alignedSlice(self, arg0: int) -> "ByteBuffer": ...
    @overload
    def getChar(self) -> str: ...
    @overload
    def getChar(self, arg0: int) -> str: ...
    @overload
    def putChar(self, arg0: str) -> "ByteBuffer": ...
    @overload
    def putChar(self, arg0: int, arg1: str) -> "ByteBuffer": ...
    def asCharBuffer(self) -> CharBuffer: ...
    @overload
    def getShort(self) -> int: ...
    @overload
    def getShort(self, arg0: int) -> int: ...
    @overload
    def putShort(self, arg0: int) -> "ByteBuffer": ...
    @overload
    def putShort(self, arg0: int, arg1: int) -> "ByteBuffer": ...
    def asShortBuffer(self) -> ShortBuffer: ...
    @overload
    def getInt(self) -> int: ...
    @overload
    def getInt(self, arg0: int) -> int: ...
    @overload
    def putInt(self, arg0: int) -> "ByteBuffer": ...
    @overload
    def putInt(self, arg0: int, arg1: int) -> "ByteBuffer": ...
    def asIntBuffer(self) -> IntBuffer: ...
    @overload
    def getLong(self) -> int: ...
    @overload
    def getLong(self, arg0: int) -> int: ...
    @overload
    def putLong(self, arg0: int) -> "ByteBuffer": ...
    @overload
    def putLong(self, arg0: int, arg1: int) -> "ByteBuffer": ...
    def asLongBuffer(self) -> LongBuffer: ...
    @overload
    def getFloat(self) -> float: ...
    @overload
    def getFloat(self, arg0: int) -> float: ...
    @overload
    def putFloat(self, arg0: float) -> "ByteBuffer": ...
    @overload
    def putFloat(self, arg0: int, arg1: float) -> "ByteBuffer": ...
    def asFloatBuffer(self) -> FloatBuffer: ...
    @overload
    def getDouble(self) -> float: ...
    @overload
    def getDouble(self, arg0: int) -> float: ...
    @overload
    def putDouble(self, arg0: float) -> "ByteBuffer": ...
    @overload
    def putDouble(self, arg0: int, arg1: float) -> "ByteBuffer": ...
    def asDoubleBuffer(self) -> DoubleBuffer: ...
