from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["CharBuffer"]

class CharBuffer(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/nio/CharBuffer"
    allocate = JavaStaticMethod("(I)Ljava/nio/CharBuffer;")
    wrap = JavaMultipleMethod([("([CII)Ljava/nio/CharBuffer;", True, False), ("([C)Ljava/nio/CharBuffer;", True, False), ("(Ljava/lang/CharSequence;II)Ljava/nio/CharBuffer;", True, False), ("(Ljava/lang/CharSequence;)Ljava/nio/CharBuffer;", True, False)])
    read = JavaMethod("(Ljava/nio/CharBuffer;)I")
    slice = JavaMultipleMethod([("()Ljava/nio/CharBuffer;", False, False), ("(II)Ljava/nio/CharBuffer;", False, False)])
    duplicate = JavaMethod("()Ljava/nio/CharBuffer;")
    asReadOnlyBuffer = JavaMethod("()Ljava/nio/CharBuffer;")
    get = JavaMultipleMethod([("()C", False, False), ("(I)C", False, False), ("([CII)Ljava/nio/CharBuffer;", False, False), ("([C)Ljava/nio/CharBuffer;", False, False), ("(I[CII)Ljava/nio/CharBuffer;", False, False), ("(I[C)Ljava/nio/CharBuffer;", False, False)])
    put = JavaMultipleMethod([("(C)Ljava/nio/CharBuffer;", False, False), ("(IC)Ljava/nio/CharBuffer;", False, False), ("(Ljava/nio/CharBuffer;)Ljava/nio/CharBuffer;", False, False), ("(ILjava/nio/CharBuffer;II)Ljava/nio/CharBuffer;", False, False), ("([CII)Ljava/nio/CharBuffer;", False, False), ("([C)Ljava/nio/CharBuffer;", False, False), ("(I[CII)Ljava/nio/CharBuffer;", False, False), ("(I[C)Ljava/nio/CharBuffer;", False, False), ("(Ljava/lang/String;II)Ljava/nio/CharBuffer;", False, False), ("(Ljava/lang/String;)Ljava/nio/CharBuffer;", False, False)])
    hasArray = JavaMethod("()Z")
    array = JavaMethod("()[C")
    arrayOffset = JavaMethod("()I")
    position = JavaMethod("(I)Ljava/nio/Buffer;")
    limit = JavaMethod("(I)Ljava/nio/Buffer;")
    mark = JavaMethod("()Ljava/nio/Buffer;")
    reset = JavaMethod("()Ljava/nio/Buffer;")
    clear = JavaMethod("()Ljava/nio/Buffer;")
    flip = JavaMethod("()Ljava/nio/Buffer;")
    rewind = JavaMethod("()Ljava/nio/Buffer;")
    compact = JavaMethod("()Ljava/nio/CharBuffer;")
    isDirect = JavaMethod("()Z")
    hashCode = JavaMethod("()I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    compareTo = JavaMethod("(Ljava/nio/CharBuffer;)I")
    mismatch = JavaMethod("(Ljava/nio/CharBuffer;)I")
    toString = JavaMethod("()Ljava/lang/String;")
    length = JavaMethod("()I")
    isEmpty = JavaMethod("()Z")
    charAt = JavaMethod("(I)C")
    subSequence = JavaMethod("(II)Ljava/nio/CharBuffer;")
    append = JavaMultipleMethod([("(Ljava/lang/CharSequence;)Ljava/nio/CharBuffer;", False, False), ("(Ljava/lang/CharSequence;II)Ljava/nio/CharBuffer;", False, False), ("(C)Ljava/nio/CharBuffer;", False, False)])
    order = JavaMethod("()Ljava/nio/ByteOrder;")
    chars = JavaMethod("()Ljava/util/stream/IntStream;")