from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.ByteOrder import ByteOrder
from java.util.stream.IntStream import IntStream

class CharBuffer:
    @staticmethod
    def allocate(arg0: int) -> "CharBuffer": ...
    @overload
    @staticmethod
    def wrap(arg0: list[str], arg1: int, arg2: int) -> "CharBuffer": ...
    @overload
    @staticmethod
    def wrap(arg0: list[str]) -> "CharBuffer": ...
    @overload
    @staticmethod
    def wrap(arg0: str, arg1: int, arg2: int) -> "CharBuffer": ...
    @overload
    @staticmethod
    def wrap(arg0: str) -> "CharBuffer": ...
    def read(self, arg0: "CharBuffer") -> int: ...
    @overload
    def slice(self) -> "CharBuffer": ...
    @overload
    def slice(self, arg0: int, arg1: int) -> "CharBuffer": ...
    def duplicate(self) -> "CharBuffer": ...
    def asReadOnlyBuffer(self) -> "CharBuffer": ...
    @overload
    def get(self) -> str: ...
    @overload
    def get(self, arg0: int) -> str: ...
    @overload
    def get(self, arg0: list[str], arg1: int, arg2: int) -> "CharBuffer": ...
    @overload
    def get(self, arg0: list[str]) -> "CharBuffer": ...
    @overload
    def get(self, arg0: int, arg1: list[str], arg2: int, arg3: int) -> "CharBuffer": ...
    @overload
    def get(self, arg0: int, arg1: list[str]) -> "CharBuffer": ...
    @overload
    def put(self, arg0: str) -> "CharBuffer": ...
    @overload
    def put(self, arg0: int, arg1: str) -> "CharBuffer": ...
    @overload
    def put(self, arg0: "CharBuffer") -> "CharBuffer": ...
    @overload
    def put(self, arg0: int, arg1: "CharBuffer", arg2: int, arg3: int) -> "CharBuffer": ...
    @overload
    def put(self, arg0: list[str], arg1: int, arg2: int) -> "CharBuffer": ...
    @overload
    def put(self, arg0: list[str]) -> "CharBuffer": ...
    @overload
    def put(self, arg0: int, arg1: list[str], arg2: int, arg3: int) -> "CharBuffer": ...
    @overload
    def put(self, arg0: int, arg1: list[str]) -> "CharBuffer": ...
    @overload
    def put(self, arg0: str, arg1: int, arg2: int) -> "CharBuffer": ...
    @overload
    def put(self, arg0: str) -> "CharBuffer": ...
    def hasArray(self) -> bool: ...
    def array(self) -> list[str]: ...
    def arrayOffset(self) -> int: ...
    def position(self, arg0: int) -> Buffer: ...
    def limit(self, arg0: int) -> Buffer: ...
    def mark(self) -> Buffer: ...
    def reset(self) -> Buffer: ...
    def clear(self) -> Buffer: ...
    def flip(self) -> Buffer: ...
    def rewind(self) -> Buffer: ...
    def compact(self) -> "CharBuffer": ...
    def isDirect(self) -> bool: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def compareTo(self, arg0: "CharBuffer") -> int: ...
    def mismatch(self, arg0: "CharBuffer") -> int: ...
    def toString(self) -> str: ...
    def length(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def charAt(self, arg0: int) -> str: ...
    def subSequence(self, arg0: int, arg1: int) -> "CharBuffer": ...
    @overload
    def append(self, arg0: str) -> "CharBuffer": ...
    @overload
    def append(self, arg0: str, arg1: int, arg2: int) -> "CharBuffer": ...
    @overload
    def append(self, arg0: str) -> "CharBuffer": ...
    def order(self) -> ByteOrder: ...
    def chars(self) -> IntStream: ...
