from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.ByteOrder import ByteOrder

class LongBuffer:
    @staticmethod
    def allocate(arg0: int) -> "LongBuffer": ...
    @overload
    @staticmethod
    def wrap(arg0: list[int], arg1: int, arg2: int) -> "LongBuffer": ...
    @overload
    @staticmethod
    def wrap(arg0: list[int]) -> "LongBuffer": ...
    @overload
    def slice(self) -> "LongBuffer": ...
    @overload
    def slice(self, arg0: int, arg1: int) -> "LongBuffer": ...
    def duplicate(self) -> "LongBuffer": ...
    def asReadOnlyBuffer(self) -> "LongBuffer": ...
    @overload
    def get(self) -> int: ...
    @overload
    def get(self, arg0: int) -> int: ...
    @overload
    def get(self, arg0: list[int], arg1: int, arg2: int) -> "LongBuffer": ...
    @overload
    def get(self, arg0: list[int]) -> "LongBuffer": ...
    @overload
    def get(self, arg0: int, arg1: list[int], arg2: int, arg3: int) -> "LongBuffer": ...
    @overload
    def get(self, arg0: int, arg1: list[int]) -> "LongBuffer": ...
    @overload
    def put(self, arg0: int) -> "LongBuffer": ...
    @overload
    def put(self, arg0: int, arg1: int) -> "LongBuffer": ...
    @overload
    def put(self, arg0: "LongBuffer") -> "LongBuffer": ...
    @overload
    def put(self, arg0: int, arg1: "LongBuffer", arg2: int, arg3: int) -> "LongBuffer": ...
    @overload
    def put(self, arg0: list[int], arg1: int, arg2: int) -> "LongBuffer": ...
    @overload
    def put(self, arg0: list[int]) -> "LongBuffer": ...
    @overload
    def put(self, arg0: int, arg1: list[int], arg2: int, arg3: int) -> "LongBuffer": ...
    @overload
    def put(self, arg0: int, arg1: list[int]) -> "LongBuffer": ...
    def hasArray(self) -> bool: ...
    def array(self) -> list[int]: ...
    def arrayOffset(self) -> int: ...
    def position(self, arg0: int) -> Buffer: ...
    def limit(self, arg0: int) -> Buffer: ...
    def mark(self) -> Buffer: ...
    def reset(self) -> Buffer: ...
    def clear(self) -> Buffer: ...
    def flip(self) -> Buffer: ...
    def rewind(self) -> Buffer: ...
    def compact(self) -> "LongBuffer": ...
    def isDirect(self) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def compareTo(self, arg0: "LongBuffer") -> int: ...
    def mismatch(self, arg0: "LongBuffer") -> int: ...
    def order(self) -> ByteOrder: ...
