from typing import Any, ClassVar, overload

class NetworkStats:
    def finalize(self) -> None: ...
    def getNextBucket(self, arg0: "Bucket") -> bool: ...
    def hasNextBucket(self) -> bool: ...
    def close(self) -> None: ...

    class Bucket:
        DEFAULT_NETWORK_ALL: ClassVar[int]
        DEFAULT_NETWORK_NO: ClassVar[int]
        DEFAULT_NETWORK_YES: ClassVar[int]
        METERED_ALL: ClassVar[int]
        METERED_NO: ClassVar[int]
        METERED_YES: ClassVar[int]
        ROAMING_ALL: ClassVar[int]
        ROAMING_NO: ClassVar[int]
        ROAMING_YES: ClassVar[int]
        STATE_ALL: ClassVar[int]
        STATE_DEFAULT: ClassVar[int]
        STATE_FOREGROUND: ClassVar[int]
        TAG_NONE: ClassVar[int]
        UID_ALL: ClassVar[int]
        UID_REMOVED: ClassVar[int]
        UID_TETHERING: ClassVar[int]
        def __init__(self) -> None: ...
        def getUid(self) -> int: ...
        def getTag(self) -> int: ...
        def getState(self) -> int: ...
        def getMetered(self) -> int: ...
        def getRoaming(self) -> int: ...
        def getDefaultNetworkStatus(self) -> int: ...
        def getStartTimeStamp(self) -> int: ...
        def getEndTimeStamp(self) -> int: ...
        def getRxBytes(self) -> int: ...
        def getTxBytes(self) -> int: ...
        def getRxPackets(self) -> int: ...
        def getTxPackets(self) -> int: ...
