from typing import Any, ClassVar, overload

class XdhKeySpec:
    def __init__(self, arg0: list[int]) -> None: ...
    def getFormat(self) -> str: ...
    def getKey(self) -> list[int]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
