from typing import Any, ClassVar, overload

class QName:
    @overload
    def __init__(self, arg0: str, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: str) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    def getNamespaceURI(self) -> str: ...
    def getLocalPart(self) -> str: ...
    def getPrefix(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    @staticmethod
    def valueOf(arg0: str) -> "QName": ...
