from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.net.MacAddress import MacAddress
from android.net.NetworkInfo import NetworkInfo
from android.net.wifi.p2p.WifiP2pConfig import WifiP2pConfig
from android.net.wifi.p2p.WifiP2pDevice import WifiP2pDevice
from android.net.wifi.p2p.WifiP2pDeviceList import WifiP2pDeviceList
from android.net.wifi.p2p.WifiP2pDiscoveryConfig import WifiP2pDiscoveryConfig
from android.net.wifi.p2p.WifiP2pGroup import WifiP2pGroup
from android.net.wifi.p2p.WifiP2pInfo import WifiP2pInfo
from android.net.wifi.p2p.WifiP2pWfdInfo import WifiP2pWfdInfo
from android.net.wifi.p2p.nsd.WifiP2pServiceInfo import WifiP2pServiceInfo
from android.net.wifi.p2p.nsd.WifiP2pServiceRequest import WifiP2pServiceRequest
from android.os.Looper import Looper
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class WifiP2pManager:
    ACTION_WIFI_P2P_LISTEN_STATE_CHANGED: ClassVar[str]
    ACTION_WIFI_P2P_REQUEST_RESPONSE_CHANGED: ClassVar[str]
    BUSY: ClassVar[int]
    CONNECTION_REQUEST_ACCEPT: ClassVar[int]
    CONNECTION_REQUEST_DEFER_SHOW_PIN_TO_SERVICE: ClassVar[int]
    CONNECTION_REQUEST_DEFER_TO_SERVICE: ClassVar[int]
    CONNECTION_REQUEST_REJECT: ClassVar[int]
    ERROR: ClassVar[int]
    EXTRA_DISCOVERY_STATE: ClassVar[str]
    EXTRA_LISTEN_STATE: ClassVar[str]
    EXTRA_NETWORK_INFO: ClassVar[str]
    EXTRA_P2P_DEVICE_LIST: ClassVar[str]
    EXTRA_REQUEST_CONFIG: ClassVar[str]
    EXTRA_REQUEST_RESPONSE: ClassVar[str]
    EXTRA_WIFI_P2P_DEVICE: ClassVar[str]
    EXTRA_WIFI_P2P_GROUP: ClassVar[str]
    EXTRA_WIFI_P2P_INFO: ClassVar[str]
    EXTRA_WIFI_STATE: ClassVar[str]
    GROUP_CREATION_FAILURE_REASON_CONNECTION_CANCELLED: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_GROUP_REMOVED: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_INVITATION_FAILED: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_PROVISION_DISCOVERY_FAILED: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_TIMED_OUT: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_USER_REJECTED: ClassVar[int]
    NO_SERVICE_REQUESTS: ClassVar[int]
    P2P_UNSUPPORTED: ClassVar[int]
    WIFI_P2P_CONNECTION_CHANGED_ACTION: ClassVar[str]
    WIFI_P2P_DISCOVERY_CHANGED_ACTION: ClassVar[str]
    WIFI_P2P_DISCOVERY_STARTED: ClassVar[int]
    WIFI_P2P_DISCOVERY_STOPPED: ClassVar[int]
    WIFI_P2P_LISTEN_STARTED: ClassVar[int]
    WIFI_P2P_LISTEN_STOPPED: ClassVar[int]
    WIFI_P2P_PEERS_CHANGED_ACTION: ClassVar[str]
    WIFI_P2P_SCAN_FULL: ClassVar[int]
    WIFI_P2P_SCAN_SINGLE_FREQ: ClassVar[int]
    WIFI_P2P_SCAN_SOCIAL: ClassVar[int]
    WIFI_P2P_STATE_CHANGED_ACTION: ClassVar[str]
    WIFI_P2P_STATE_DISABLED: ClassVar[int]
    WIFI_P2P_STATE_ENABLED: ClassVar[int]
    WIFI_P2P_THIS_DEVICE_CHANGED_ACTION: ClassVar[str]
    def registerWifiP2pListener(self, arg0: Executor, arg1: "WifiP2pListener") -> None: ...
    def unregisterWifiP2pListener(self, arg0: "WifiP2pListener") -> None: ...
    def initialize(self, arg0: Context, arg1: Looper, arg2: "ChannelListener") -> "Channel": ...
    def discoverPeers(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def discoverPeersOnSocialChannels(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def discoverPeersOnSpecificFrequency(self, arg0: "Channel", arg1: int, arg2: "ActionListener") -> None: ...
    def startPeerDiscovery(self, arg0: "Channel", arg1: WifiP2pDiscoveryConfig, arg2: "ActionListener") -> None: ...
    def stopPeerDiscovery(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def connect(self, arg0: "Channel", arg1: WifiP2pConfig, arg2: "ActionListener") -> None: ...
    def cancelConnect(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    @overload
    def createGroup(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    @overload
    def createGroup(self, arg0: "Channel", arg1: WifiP2pConfig, arg2: "ActionListener") -> None: ...
    def removeGroup(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def startListening(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def stopListening(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def addLocalService(self, arg0: "Channel", arg1: WifiP2pServiceInfo, arg2: "ActionListener") -> None: ...
    def removeLocalService(self, arg0: "Channel", arg1: WifiP2pServiceInfo, arg2: "ActionListener") -> None: ...
    def clearLocalServices(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def setServiceResponseListener(self, arg0: "Channel", arg1: "ServiceResponseListener") -> None: ...
    def setDnsSdResponseListeners(self, arg0: "Channel", arg1: "DnsSdServiceResponseListener", arg2: "DnsSdTxtRecordListener") -> None: ...
    def setUpnpServiceResponseListener(self, arg0: "Channel", arg1: "UpnpServiceResponseListener") -> None: ...
    def discoverServices(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def addServiceRequest(self, arg0: "Channel", arg1: WifiP2pServiceRequest, arg2: "ActionListener") -> None: ...
    def removeServiceRequest(self, arg0: "Channel", arg1: WifiP2pServiceRequest, arg2: "ActionListener") -> None: ...
    def clearServiceRequests(self, arg0: "Channel", arg1: "ActionListener") -> None: ...
    def requestPeers(self, arg0: "Channel", arg1: "PeerListListener") -> None: ...
    def requestConnectionInfo(self, arg0: "Channel", arg1: "ConnectionInfoListener") -> None: ...
    def requestGroupInfo(self, arg0: "Channel", arg1: "GroupInfoListener") -> None: ...
    def setWfdInfo(self, arg0: "Channel", arg1: WifiP2pWfdInfo, arg2: "ActionListener") -> None: ...
    def removeClient(self, arg0: "Channel", arg1: MacAddress, arg2: "ActionListener") -> None: ...
    def isSetVendorElementsSupported(self) -> bool: ...
    def isChannelConstrainedDiscoverySupported(self) -> bool: ...
    def isGroupClientRemovalSupported(self) -> bool: ...
    def isGroupOwnerIPv6LinkLocalAddressProvided(self) -> bool: ...
    def requestP2pState(self, arg0: "Channel", arg1: "P2pStateListener") -> None: ...
    def requestDiscoveryState(self, arg0: "Channel", arg1: "DiscoveryStateListener") -> None: ...
    def getListenState(self, arg0: "Channel", arg1: Executor, arg2: Consumer) -> None: ...
    def requestNetworkInfo(self, arg0: "Channel", arg1: "NetworkInfoListener") -> None: ...
    def requestDeviceInfo(self, arg0: "Channel", arg1: "DeviceInfoListener") -> None: ...
    def addExternalApprover(self, arg0: "Channel", arg1: MacAddress, arg2: "ExternalApproverRequestListener") -> None: ...
    def removeExternalApprover(self, arg0: "Channel", arg1: MacAddress, arg2: "ActionListener") -> None: ...
    @overload
    def setConnectionRequestResult(self, arg0: "Channel", arg1: MacAddress, arg2: int, arg3: "ActionListener") -> None: ...
    @overload
    def setConnectionRequestResult(self, arg0: "Channel", arg1: MacAddress, arg2: int, arg3: str, arg4: "ActionListener") -> None: ...
    def setVendorElements(self, arg0: "Channel", arg1: list, arg2: "ActionListener") -> None: ...
    @staticmethod
    def getP2pMaxAllowedVendorElementsLengthBytes() -> int: ...

    class ActionListener:
        def onSuccess(self) -> None: ...
        def onFailure(self, arg0: int) -> None: ...

    class Channel:
        def close(self) -> None: ...
        def finalize(self) -> None: ...

    class ChannelListener:
        def onChannelDisconnected(self) -> None: ...

    class ConnectionInfoListener:
        def onConnectionInfoAvailable(self, arg0: WifiP2pInfo) -> None: ...

    class DeviceInfoListener:
        def onDeviceInfoAvailable(self, arg0: WifiP2pDevice) -> None: ...

    class DiscoveryStateListener:
        def onDiscoveryStateAvailable(self, arg0: int) -> None: ...

    class DnsSdServiceResponseListener:
        def onDnsSdServiceAvailable(self, arg0: str, arg1: str, arg2: WifiP2pDevice) -> None: ...

    class DnsSdTxtRecordListener:
        def onDnsSdTxtRecordAvailable(self, arg0: str, arg1: dict, arg2: WifiP2pDevice) -> None: ...

    class ExternalApproverRequestListener:
        APPROVER_DETACH_REASON_CLOSE: ClassVar[int]
        APPROVER_DETACH_REASON_FAILURE: ClassVar[int]
        APPROVER_DETACH_REASON_REMOVE: ClassVar[int]
        APPROVER_DETACH_REASON_REPLACE: ClassVar[int]
        REQUEST_TYPE_INVITATION: ClassVar[int]
        REQUEST_TYPE_JOIN: ClassVar[int]
        REQUEST_TYPE_NEGOTIATION: ClassVar[int]
        def onAttached(self, arg0: MacAddress) -> None: ...
        def onDetached(self, arg0: MacAddress, arg1: int) -> None: ...
        def onConnectionRequested(self, arg0: int, arg1: WifiP2pConfig, arg2: WifiP2pDevice) -> None: ...
        def onPinGenerated(self, arg0: MacAddress, arg1: str) -> None: ...

    class GroupInfoListener:
        def onGroupInfoAvailable(self, arg0: WifiP2pGroup) -> None: ...

    class NetworkInfoListener:
        def onNetworkInfoAvailable(self, arg0: NetworkInfo) -> None: ...

    class P2pStateListener:
        def onP2pStateAvailable(self, arg0: int) -> None: ...

    class PeerListListener:
        def onPeersAvailable(self, arg0: WifiP2pDeviceList) -> None: ...

    class ServiceResponseListener:
        def onServiceAvailable(self, arg0: int, arg1: list[int], arg2: WifiP2pDevice) -> None: ...

    class UpnpServiceResponseListener:
        def onUpnpServiceAvailable(self, arg0: list, arg1: WifiP2pDevice) -> None: ...

    class WifiP2pListener:
        def onP2pStateChanged(self, arg0: int) -> None: ...
        def onDiscoveryStateChanged(self, arg0: int) -> None: ...
        def onListenStateChanged(self, arg0: int) -> None: ...
        def onDeviceConfigurationChanged(self, arg0: WifiP2pDevice) -> None: ...
        def onPeerListChanged(self, arg0: WifiP2pDeviceList) -> None: ...
        def onGroupCreating(self) -> None: ...
        def onGroupNegotiationRejectedByUser(self) -> None: ...
        def onGroupCreationFailed(self, arg0: int) -> None: ...
        def onGroupCreated(self, arg0: WifiP2pInfo, arg1: WifiP2pGroup) -> None: ...
        def onPeerClientJoined(self, arg0: WifiP2pInfo, arg1: WifiP2pGroup) -> None: ...
        def onPeerClientDisconnected(self, arg0: WifiP2pInfo, arg1: WifiP2pGroup) -> None: ...
        def onFrequencyChanged(self, arg0: WifiP2pInfo, arg1: WifiP2pGroup) -> None: ...
        def onGroupRemoved(self) -> None: ...
