from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class WifiP2pWfdInfo:
    CREATOR: ClassVar[Creator]
    DEVICE_INFO_AUDIO_ONLY_SUPPORT_AT_SOURCE: ClassVar[int]
    DEVICE_INFO_AUDIO_UNSUPPORTED_AT_PRIMARY_SINK: ClassVar[int]
    DEVICE_INFO_CONTENT_PROTECTION_SUPPORT: ClassVar[int]
    DEVICE_INFO_COUPLED_SINK_SUPPORT_AT_SINK: ClassVar[int]
    DEVICE_INFO_COUPLED_SINK_SUPPORT_AT_SOURCE: ClassVar[int]
    DEVICE_INFO_DEVICE_TYPE_MASK: ClassVar[int]
    DEVICE_INFO_PREFERRED_CONNECTIVITY_MASK: ClassVar[int]
    DEVICE_INFO_SESSION_AVAILABLE_MASK: ClassVar[int]
    DEVICE_INFO_TDLS_PERSISTENT_GROUP: ClassVar[int]
    DEVICE_INFO_TDLS_PERSISTENT_GROUP_REINVOKE: ClassVar[int]
    DEVICE_INFO_TIME_SYNCHRONIZATION_SUPPORT: ClassVar[int]
    DEVICE_INFO_WFD_SERVICE_DISCOVERY_SUPPORT: ClassVar[int]
    DEVICE_TYPE_PRIMARY_SINK: ClassVar[int]
    DEVICE_TYPE_SECONDARY_SINK: ClassVar[int]
    DEVICE_TYPE_SOURCE_OR_PRIMARY_SINK: ClassVar[int]
    DEVICE_TYPE_WFD_SOURCE: ClassVar[int]
    PREFERRED_CONNECTIVITY_P2P: ClassVar[int]
    PREFERRED_CONNECTIVITY_TDLS: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "WifiP2pWfdInfo") -> None: ...
    def getDeviceInfo(self) -> int: ...
    def getR2DeviceInfo(self) -> int: ...
    def isEnabled(self) -> bool: ...
    def isR2Supported(self) -> bool: ...
    def setEnabled(self, arg0: bool) -> None: ...
    def setR2DeviceType(self, arg0: int) -> bool: ...
    def getDeviceType(self) -> int: ...
    def getR2DeviceType(self) -> int: ...
    def setDeviceType(self, arg0: int) -> bool: ...
    def isSessionAvailable(self) -> bool: ...
    def setSessionAvailable(self, arg0: bool) -> None: ...
    def isContentProtectionSupported(self) -> bool: ...
    def setContentProtectionSupported(self, arg0: bool) -> None: ...
    def isCoupledSinkSupportedAtSource(self) -> bool: ...
    def setCoupledSinkSupportAtSource(self, arg0: bool) -> None: ...
    def isCoupledSinkSupportedAtSink(self) -> bool: ...
    def setCoupledSinkSupportAtSink(self, arg0: bool) -> None: ...
    def getControlPort(self) -> int: ...
    def setControlPort(self, arg0: int) -> None: ...
    def setMaxThroughput(self, arg0: int) -> None: ...
    def getMaxThroughput(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
