from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class VerifiedDisplayHash:
    CREATOR: ClassVar[Creator]
    def __init__(self, arg0: int, arg1: Rect, arg2: str, arg3: list[int]) -> None: ...
    def getTimeMillis(self) -> int: ...
    def getBoundsInWindow(self) -> Rect: ...
    def getHashAlgorithm(self) -> str: ...
    def getImageHash(self) -> list[int]: ...
    def toString(self) -> str: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
