from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.app.LocalActivityManager import LocalActivityManager
from android.os.Bundle import Bundle

class ActivityGroup:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: bool) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onResume(self) -> None: ...
    def onSaveInstanceState(self, arg0: Bundle) -> None: ...
    def onPause(self) -> None: ...
    def onStop(self) -> None: ...
    def onDestroy(self) -> None: ...
    def getCurrentActivity(self) -> Activity: ...
    def getLocalActivityManager(self) -> LocalActivityManager: ...
