from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["AlertDialog"]

class AlertDialog(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/app/AlertDialog"
    __javaconstructor__ = [("(Landroid/content/Context;)V", False), ("(Landroid/content/Context;ZLandroid/content/DialogInterface$OnCancelListener;)V", False), ("(Landroid/content/Context;I)V", False)]
    THEME_DEVICE_DEFAULT_DARK = JavaStaticField("I")
    THEME_DEVICE_DEFAULT_LIGHT = JavaStaticField("I")
    THEME_HOLO_DARK = JavaStaticField("I")
    THEME_HOLO_LIGHT = JavaStaticField("I")
    THEME_TRADITIONAL = JavaStaticField("I")
    getButton = JavaMethod("(I)Landroid/widget/Button;")
    getListView = JavaMethod("()Landroid/widget/ListView;")
    setTitle = JavaMethod("(Ljava/lang/CharSequence;)V")
    setCustomTitle = JavaMethod("(Landroid/view/View;)V")
    setMessage = JavaMethod("(Ljava/lang/CharSequence;)V")
    setView = JavaMultipleMethod([("(Landroid/view/View;)V", False, False), ("(Landroid/view/View;IIII)V", False, False)])
    setButton = JavaMultipleMethod([("(ILjava/lang/CharSequence;Landroid/os/Message;)V", False, False), ("(ILjava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)V", False, False), ("(Ljava/lang/CharSequence;Landroid/os/Message;)V", False, False), ("(Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)V", False, False)])
    setButton2 = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/os/Message;)V", False, False), ("(Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)V", False, False)])
    setButton3 = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/os/Message;)V", False, False), ("(Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)V", False, False)])
    setIcon = JavaMultipleMethod([("(I)V", False, False), ("(Landroid/graphics/drawable/Drawable;)V", False, False)])
    setIconAttribute = JavaMethod("(I)V")
    setInverseBackgroundForced = JavaMethod("(Z)V")
    onCreate = JavaMethod("(Landroid/os/Bundle;)V")
    onKeyDown = JavaMethod("(ILandroid/view/KeyEvent;)Z")
    onKeyUp = JavaMethod("(ILandroid/view/KeyEvent;)Z")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/app/AlertDialog/Builder"
        __javaconstructor__ = [("(Landroid/content/Context;)V", False), ("(Landroid/content/Context;I)V", False)]
        getContext = JavaMethod("()Landroid/content/Context;")
        setTitle = JavaMultipleMethod([("(I)Landroid/app/AlertDialog$Builder;", False, False), ("(Ljava/lang/CharSequence;)Landroid/app/AlertDialog$Builder;", False, False)])
        setCustomTitle = JavaMethod("(Landroid/view/View;)Landroid/app/AlertDialog$Builder;")
        setMessage = JavaMultipleMethod([("(I)Landroid/app/AlertDialog$Builder;", False, False), ("(Ljava/lang/CharSequence;)Landroid/app/AlertDialog$Builder;", False, False)])
        setIcon = JavaMultipleMethod([("(I)Landroid/app/AlertDialog$Builder;", False, False), ("(Landroid/graphics/drawable/Drawable;)Landroid/app/AlertDialog$Builder;", False, False)])
        setIconAttribute = JavaMethod("(I)Landroid/app/AlertDialog$Builder;")
        setPositiveButton = JavaMultipleMethod([("(ILandroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("(Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False)])
        setNegativeButton = JavaMultipleMethod([("(ILandroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("(Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False)])
        setNeutralButton = JavaMultipleMethod([("(ILandroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("(Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False)])
        setCancelable = JavaMethod("(Z)Landroid/app/AlertDialog$Builder;")
        setOnCancelListener = JavaMethod("(Landroid/content/DialogInterface$OnCancelListener;)Landroid/app/AlertDialog$Builder;")
        setOnDismissListener = JavaMethod("(Landroid/content/DialogInterface$OnDismissListener;)Landroid/app/AlertDialog$Builder;")
        setOnKeyListener = JavaMethod("(Landroid/content/DialogInterface$OnKeyListener;)Landroid/app/AlertDialog$Builder;")
        setItems = JavaMultipleMethod([("(ILandroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("([Ljava/lang/CharSequence;Landroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False)])
        setAdapter = JavaMethod("(Landroid/widget/ListAdapter;Landroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;")
        setCursor = JavaMethod("(Landroid/database/Cursor;Landroid/content/DialogInterface$OnClickListener;Ljava/lang/String;)Landroid/app/AlertDialog$Builder;")
        setMultiChoiceItems = JavaMultipleMethod([("(I[ZLandroid/content/DialogInterface$OnMultiChoiceClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("([Ljava/lang/CharSequence;[ZLandroid/content/DialogInterface$OnMultiChoiceClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("(Landroid/database/Cursor;Ljava/lang/String;Ljava/lang/String;Landroid/content/DialogInterface$OnMultiChoiceClickListener;)Landroid/app/AlertDialog$Builder;", False, False)])
        setSingleChoiceItems = JavaMultipleMethod([("(IILandroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("(Landroid/database/Cursor;ILjava/lang/String;Landroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("([Ljava/lang/CharSequence;ILandroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False), ("(Landroid/widget/ListAdapter;ILandroid/content/DialogInterface$OnClickListener;)Landroid/app/AlertDialog$Builder;", False, False)])
        setOnItemSelectedListener = JavaMethod("(Landroid/widget/AdapterView$OnItemSelectedListener;)Landroid/app/AlertDialog$Builder;")
        setView = JavaMultipleMethod([("(I)Landroid/app/AlertDialog$Builder;", False, False), ("(Landroid/view/View;)Landroid/app/AlertDialog$Builder;", False, False)])
        setInverseBackgroundForced = JavaMethod("(Z)Landroid/app/AlertDialog$Builder;")
        create = JavaMethod("()Landroid/app/AlertDialog;")
        show = JavaMethod("()Landroid/app/AlertDialog;")