from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.app.Application import Application
from android.app.Service import Service
from android.content.BroadcastReceiver import BroadcastReceiver
from android.content.ContentProvider import ContentProvider
from android.content.Intent import Intent
from android.content.pm.ApplicationInfo import ApplicationInfo
from java.lang.ClassLoader import ClassLoader

class AppComponentFactory:
    def __init__(self) -> None: ...
    def instantiateClassLoader(self, arg0: ClassLoader, arg1: ApplicationInfo) -> ClassLoader: ...
    def instantiateApplication(self, arg0: ClassLoader, arg1: str) -> Application: ...
    def instantiateActivity(self, arg0: ClassLoader, arg1: str, arg2: Intent) -> Activity: ...
    def instantiateReceiver(self, arg0: ClassLoader, arg1: str, arg2: Intent) -> BroadcastReceiver: ...
    def instantiateService(self, arg0: ClassLoader, arg1: str, arg2: Intent) -> Service: ...
    def instantiateProvider(self, arg0: ClassLoader, arg1: str) -> ContentProvider: ...
