from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.os.UserHandle import UserHandle
from java.io.InputStream import InputStream

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ApplicationExitInfo:
    CREATOR: ClassVar[Creator]
    REASON_ANR: ClassVar[int]
    REASON_CRASH: ClassVar[int]
    REASON_CRASH_NATIVE: ClassVar[int]
    REASON_DEPENDENCY_DIED: ClassVar[int]
    REASON_EXCESSIVE_RESOURCE_USAGE: ClassVar[int]
    REASON_EXIT_SELF: ClassVar[int]
    REASON_FREEZER: ClassVar[int]
    REASON_INITIALIZATION_FAILURE: ClassVar[int]
    REASON_LOW_MEMORY: ClassVar[int]
    REASON_OTHER: ClassVar[int]
    REASON_PACKAGE_STATE_CHANGE: ClassVar[int]
    REASON_PACKAGE_UPDATED: ClassVar[int]
    REASON_PERMISSION_CHANGE: ClassVar[int]
    REASON_SIGNALED: ClassVar[int]
    REASON_UNKNOWN: ClassVar[int]
    REASON_USER_REQUESTED: ClassVar[int]
    REASON_USER_STOPPED: ClassVar[int]
    def getPid(self) -> int: ...
    def getRealUid(self) -> int: ...
    def getPackageUid(self) -> int: ...
    def getDefiningUid(self) -> int: ...
    def getProcessName(self) -> str: ...
    def getReason(self) -> int: ...
    def getStatus(self) -> int: ...
    def getImportance(self) -> int: ...
    def getPss(self) -> int: ...
    def getRss(self) -> int: ...
    def getTimestamp(self) -> int: ...
    def getDescription(self) -> str: ...
    def getUserHandle(self) -> UserHandle: ...
    def getProcessStateSummary(self) -> list[int]: ...
    def getTraceInputStream(self) -> InputStream: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
