from typing import Any, ClassVar, overload
from android.app.AsyncNotedAppOp import AsyncNotedAppOp
from android.app.SyncNotedAppOp import SyncNotedAppOp
from java.util.concurrent.Executor import Executor

class AppOpsManager:
    MODE_ALLOWED: ClassVar[int]
    MODE_DEFAULT: ClassVar[int]
    MODE_ERRORED: ClassVar[int]
    MODE_FOREGROUND: ClassVar[int]
    MODE_IGNORED: ClassVar[int]
    OPSTR_ADD_VOICEMAIL: ClassVar[str]
    OPSTR_ANSWER_PHONE_CALLS: ClassVar[str]
    OPSTR_BODY_SENSORS: ClassVar[str]
    OPSTR_CALL_PHONE: ClassVar[str]
    OPSTR_CAMERA: ClassVar[str]
    OPSTR_COARSE_LOCATION: ClassVar[str]
    OPSTR_FINE_LOCATION: ClassVar[str]
    OPSTR_GET_USAGE_STATS: ClassVar[str]
    OPSTR_MOCK_LOCATION: ClassVar[str]
    OPSTR_MONITOR_HIGH_POWER_LOCATION: ClassVar[str]
    OPSTR_MONITOR_LOCATION: ClassVar[str]
    OPSTR_PICTURE_IN_PICTURE: ClassVar[str]
    OPSTR_PROCESS_OUTGOING_CALLS: ClassVar[str]
    OPSTR_READ_CALENDAR: ClassVar[str]
    OPSTR_READ_CALL_LOG: ClassVar[str]
    OPSTR_READ_CELL_BROADCASTS: ClassVar[str]
    OPSTR_READ_CONTACTS: ClassVar[str]
    OPSTR_READ_EXTERNAL_STORAGE: ClassVar[str]
    OPSTR_READ_PHONE_NUMBERS: ClassVar[str]
    OPSTR_READ_PHONE_STATE: ClassVar[str]
    OPSTR_READ_SMS: ClassVar[str]
    OPSTR_RECEIVE_MMS: ClassVar[str]
    OPSTR_RECEIVE_SMS: ClassVar[str]
    OPSTR_RECEIVE_WAP_PUSH: ClassVar[str]
    OPSTR_RECORD_AUDIO: ClassVar[str]
    OPSTR_SEND_SMS: ClassVar[str]
    OPSTR_SYSTEM_ALERT_WINDOW: ClassVar[str]
    OPSTR_USE_FINGERPRINT: ClassVar[str]
    OPSTR_USE_SIP: ClassVar[str]
    OPSTR_WRITE_CALENDAR: ClassVar[str]
    OPSTR_WRITE_CALL_LOG: ClassVar[str]
    OPSTR_WRITE_CONTACTS: ClassVar[str]
    OPSTR_WRITE_EXTERNAL_STORAGE: ClassVar[str]
    OPSTR_WRITE_SETTINGS: ClassVar[str]
    WATCH_FOREGROUND_CHANGES: ClassVar[int]
    @staticmethod
    def permissionToOp(arg0: str) -> str: ...
    @overload
    def startWatchingMode(self, arg0: str, arg1: str, arg2: "OnOpChangedListener") -> None: ...
    @overload
    def startWatchingMode(self, arg0: str, arg1: str, arg2: int, arg3: "OnOpChangedListener") -> None: ...
    def stopWatchingMode(self, arg0: "OnOpChangedListener") -> None: ...
    def startWatchingActive(self, arg0: list[str], arg1: Executor, arg2: "OnOpActiveChangedListener") -> None: ...
    def stopWatchingActive(self, arg0: "OnOpActiveChangedListener") -> None: ...
    def unsafeCheckOp(self, arg0: str, arg1: int, arg2: str) -> int: ...
    def checkOp(self, arg0: str, arg1: int, arg2: str) -> int: ...
    def unsafeCheckOpNoThrow(self, arg0: str, arg1: int, arg2: str) -> int: ...
    def checkOpNoThrow(self, arg0: str, arg1: int, arg2: str) -> int: ...
    def unsafeCheckOpRaw(self, arg0: str, arg1: int, arg2: str) -> int: ...
    def unsafeCheckOpRawNoThrow(self, arg0: str, arg1: int, arg2: str) -> int: ...
    @overload
    def noteOp(self, arg0: str, arg1: int, arg2: str) -> int: ...
    @overload
    def noteOp(self, arg0: str, arg1: int, arg2: str, arg3: str, arg4: str) -> int: ...
    @overload
    def noteOpNoThrow(self, arg0: str, arg1: int, arg2: str) -> int: ...
    @overload
    def noteOpNoThrow(self, arg0: str, arg1: int, arg2: str, arg3: str, arg4: str) -> int: ...
    @overload
    def noteProxyOp(self, arg0: str, arg1: str) -> int: ...
    @overload
    def noteProxyOp(self, arg0: str, arg1: str, arg2: int, arg3: str, arg4: str) -> int: ...
    @overload
    def noteProxyOpNoThrow(self, arg0: str, arg1: str) -> int: ...
    @overload
    def noteProxyOpNoThrow(self, arg0: str, arg1: str, arg2: int) -> int: ...
    @overload
    def noteProxyOpNoThrow(self, arg0: str, arg1: str, arg2: int, arg3: str, arg4: str) -> int: ...
    def checkPackage(self, arg0: int, arg1: str) -> None: ...
    @overload
    def startOp(self, arg0: str, arg1: int, arg2: str) -> int: ...
    @overload
    def startOp(self, arg0: str, arg1: int, arg2: str, arg3: str, arg4: str) -> int: ...
    @overload
    def startOpNoThrow(self, arg0: str, arg1: int, arg2: str) -> int: ...
    @overload
    def startOpNoThrow(self, arg0: str, arg1: int, arg2: str, arg3: str, arg4: str) -> int: ...
    def startProxyOp(self, arg0: str, arg1: int, arg2: str, arg3: str, arg4: str) -> int: ...
    def startProxyOpNoThrow(self, arg0: str, arg1: int, arg2: str, arg3: str, arg4: str) -> int: ...
    @overload
    def finishOp(self, arg0: str, arg1: int, arg2: str) -> None: ...
    @overload
    def finishOp(self, arg0: str, arg1: int, arg2: str, arg3: str) -> None: ...
    def finishProxyOp(self, arg0: str, arg1: int, arg2: str, arg3: str) -> None: ...
    def isOpActive(self, arg0: str, arg1: int, arg2: str) -> bool: ...
    def setOnOpNotedCallback(self, arg0: Executor, arg1: "OnOpNotedCallback") -> None: ...

    class OnOpActiveChangedListener:
        @overload
        def onOpActiveChanged(self, arg0: str, arg1: int, arg2: str, arg3: bool) -> None: ...
        @overload
        def onOpActiveChanged(self, arg0: str, arg1: int, arg2: str, arg3: str, arg4: int, arg5: bool, arg6: int, arg7: int) -> None: ...

    class OnOpChangedListener:
        @overload
        def onOpChanged(self, arg0: str, arg1: str) -> None: ...
        @overload
        def onOpChanged(self, arg0: str, arg1: str, arg2: int, arg3: str) -> None: ...

    class OnOpNotedCallback:
        def __init__(self) -> None: ...
        def onNoted(self, arg0: SyncNotedAppOp) -> None: ...
        def onSelfNoted(self, arg0: SyncNotedAppOp) -> None: ...
        def onAsyncNoted(self, arg0: AsyncNotedAppOp) -> None: ...
