from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["AutomaticZenRule"]

class AutomaticZenRule(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/app/AutomaticZenRule"
    __javaconstructor__ = [("(Ljava/lang/String;Landroid/content/ComponentName;Landroid/net/Uri;IZ)V", False), ("(Ljava/lang/String;Landroid/content/ComponentName;Landroid/content/ComponentName;Landroid/net/Uri;Landroid/service/notification/ZenPolicy;IZ)V", False), ("(Landroid/os/Parcel;)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    TYPE_BEDTIME = JavaStaticField("I")
    TYPE_DRIVING = JavaStaticField("I")
    TYPE_IMMERSIVE = JavaStaticField("I")
    TYPE_MANAGED = JavaStaticField("I")
    TYPE_OTHER = JavaStaticField("I")
    TYPE_SCHEDULE_CALENDAR = JavaStaticField("I")
    TYPE_SCHEDULE_TIME = JavaStaticField("I")
    TYPE_THEATER = JavaStaticField("I")
    TYPE_UNKNOWN = JavaStaticField("I")
    getOwner = JavaMethod("()Landroid/content/ComponentName;")
    getConfigurationActivity = JavaMethod("()Landroid/content/ComponentName;")
    getConditionId = JavaMethod("()Landroid/net/Uri;")
    getInterruptionFilter = JavaMethod("()I")
    getName = JavaMethod("()Ljava/lang/String;")
    isEnabled = JavaMethod("()Z")
    getZenPolicy = JavaMethod("()Landroid/service/notification/ZenPolicy;")
    getDeviceEffects = JavaMethod("()Landroid/service/notification/ZenDeviceEffects;")
    getCreationTime = JavaMethod("()J")
    setConditionId = JavaMethod("(Landroid/net/Uri;)V")
    setInterruptionFilter = JavaMethod("(I)V")
    setName = JavaMethod("(Ljava/lang/String;)V")
    setEnabled = JavaMethod("(Z)V")
    setZenPolicy = JavaMethod("(Landroid/service/notification/ZenPolicy;)V")
    setDeviceEffects = JavaMethod("(Landroid/service/notification/ZenDeviceEffects;)V")
    setConfigurationActivity = JavaMethod("(Landroid/content/ComponentName;)V")
    getType = JavaMethod("()I")
    getTriggerDescription = JavaMethod("()Ljava/lang/String;")
    getIconResId = JavaMethod("()I")
    isManualInvocationAllowed = JavaMethod("()Z")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    toString = JavaMethod("()Ljava/lang/String;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    hashCode = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/app/AutomaticZenRule/Builder"
        __javaconstructor__ = [("(Landroid/app/AutomaticZenRule;)V", False), ("(Ljava/lang/String;Landroid/net/Uri;)V", False)]
        setName = JavaMethod("(Ljava/lang/String;)Landroid/app/AutomaticZenRule$Builder;")
        setOwner = JavaMethod("(Landroid/content/ComponentName;)Landroid/app/AutomaticZenRule$Builder;")
        setConditionId = JavaMethod("(Landroid/net/Uri;)Landroid/app/AutomaticZenRule$Builder;")
        setInterruptionFilter = JavaMethod("(I)Landroid/app/AutomaticZenRule$Builder;")
        setEnabled = JavaMethod("(Z)Landroid/app/AutomaticZenRule$Builder;")
        setConfigurationActivity = JavaMethod("(Landroid/content/ComponentName;)Landroid/app/AutomaticZenRule$Builder;")
        setZenPolicy = JavaMethod("(Landroid/service/notification/ZenPolicy;)Landroid/app/AutomaticZenRule$Builder;")
        setDeviceEffects = JavaMethod("(Landroid/service/notification/ZenDeviceEffects;)Landroid/app/AutomaticZenRule$Builder;")
        setType = JavaMethod("(I)Landroid/app/AutomaticZenRule$Builder;")
        setTriggerDescription = JavaMethod("(Ljava/lang/String;)Landroid/app/AutomaticZenRule$Builder;")
        setIconResId = JavaMethod("(I)Landroid/app/AutomaticZenRule$Builder;")
        setManualInvocationAllowed = JavaMethod("(Z)Landroid/app/AutomaticZenRule$Builder;")
        build = JavaMethod("()Landroid/app/AutomaticZenRule;")