from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.net.Uri import Uri
from android.os.Parcel import Parcel
from android.service.notification.ZenDeviceEffects import ZenDeviceEffects
from android.service.notification.ZenPolicy import ZenPolicy

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AutomaticZenRule:
    CREATOR: ClassVar[Creator]
    TYPE_BEDTIME: ClassVar[int]
    TYPE_DRIVING: ClassVar[int]
    TYPE_IMMERSIVE: ClassVar[int]
    TYPE_MANAGED: ClassVar[int]
    TYPE_OTHER: ClassVar[int]
    TYPE_SCHEDULE_CALENDAR: ClassVar[int]
    TYPE_SCHEDULE_TIME: ClassVar[int]
    TYPE_THEATER: ClassVar[int]
    TYPE_UNKNOWN: ClassVar[int]
    @overload
    def __init__(self, arg0: str, arg1: ComponentName, arg2: Uri, arg3: int, arg4: bool) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: ComponentName, arg2: ComponentName, arg3: Uri, arg4: ZenPolicy, arg5: int, arg6: bool) -> None: ...
    @overload
    def __init__(self, arg0: Parcel) -> None: ...
    def getOwner(self) -> ComponentName: ...
    def getConfigurationActivity(self) -> ComponentName: ...
    def getConditionId(self) -> Uri: ...
    def getInterruptionFilter(self) -> int: ...
    def getName(self) -> str: ...
    def isEnabled(self) -> bool: ...
    def getZenPolicy(self) -> ZenPolicy: ...
    def getDeviceEffects(self) -> ZenDeviceEffects: ...
    def getCreationTime(self) -> int: ...
    def setConditionId(self, arg0: Uri) -> None: ...
    def setInterruptionFilter(self, arg0: int) -> None: ...
    def setName(self, arg0: str) -> None: ...
    def setEnabled(self, arg0: bool) -> None: ...
    def setZenPolicy(self, arg0: ZenPolicy) -> None: ...
    def setDeviceEffects(self, arg0: ZenDeviceEffects) -> None: ...
    def setConfigurationActivity(self, arg0: ComponentName) -> None: ...
    def getType(self) -> int: ...
    def getTriggerDescription(self) -> str: ...
    def getIconResId(self) -> int: ...
    def isManualInvocationAllowed(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, arg0: "AutomaticZenRule") -> None: ...
        @overload
        def __init__(self, arg0: str, arg1: Uri) -> None: ...
        def setName(self, arg0: str) -> "Builder": ...
        def setOwner(self, arg0: ComponentName) -> "Builder": ...
        def setConditionId(self, arg0: Uri) -> "Builder": ...
        def setInterruptionFilter(self, arg0: int) -> "Builder": ...
        def setEnabled(self, arg0: bool) -> "Builder": ...
        def setConfigurationActivity(self, arg0: ComponentName) -> "Builder": ...
        def setZenPolicy(self, arg0: ZenPolicy) -> "Builder": ...
        def setDeviceEffects(self, arg0: ZenDeviceEffects) -> "Builder": ...
        def setType(self, arg0: int) -> "Builder": ...
        def setTriggerDescription(self, arg0: str) -> "Builder": ...
        def setIconResId(self, arg0: int) -> "Builder": ...
        def setManualInvocationAllowed(self, arg0: bool) -> "Builder": ...
        def build(self) -> "AutomaticZenRule": ...
