from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.DialogInterface import DialogInterface
from android.os.Bundle import Bundle
from android.widget.DatePicker import DatePicker

class DatePickerDialog:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: "OnDateSetListener", arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: "OnDateSetListener", arg3: int, arg4: int, arg5: int) -> None: ...
    def onDateChanged(self, arg0: DatePicker, arg1: int, arg2: int, arg3: int) -> None: ...
    def setOnDateSetListener(self, arg0: "OnDateSetListener") -> None: ...
    def onClick(self, arg0: DialogInterface, arg1: int) -> None: ...
    def getDatePicker(self) -> DatePicker: ...
    def updateDate(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def onSaveInstanceState(self) -> Bundle: ...
    def onRestoreInstanceState(self, arg0: Bundle) -> None: ...

    class OnDateSetListener:
        def onDateSet(self, arg0: DatePicker, arg1: int, arg2: int, arg3: int) -> None: ...
