from typing import Any, ClassVar, overload
from android.app.Dialog import Dialog
from android.app.FragmentManager import FragmentManager
from android.app.FragmentTransaction import FragmentTransaction
from android.content.Context import Context
from android.content.DialogInterface import DialogInterface
from android.os.Bundle import Bundle
from android.view.LayoutInflater import LayoutInflater
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class DialogFragment:
    STYLE_NORMAL: ClassVar[int]
    STYLE_NO_FRAME: ClassVar[int]
    STYLE_NO_INPUT: ClassVar[int]
    STYLE_NO_TITLE: ClassVar[int]
    def __init__(self) -> None: ...
    def setStyle(self, arg0: int, arg1: int) -> None: ...
    @overload
    def show(self, arg0: FragmentManager, arg1: str) -> None: ...
    @overload
    def show(self, arg0: FragmentTransaction, arg1: str) -> int: ...
    def dismiss(self) -> None: ...
    def dismissAllowingStateLoss(self) -> None: ...
    def getDialog(self) -> Dialog: ...
    def getTheme(self) -> int: ...
    def setCancelable(self, arg0: bool) -> None: ...
    def isCancelable(self) -> bool: ...
    def setShowsDialog(self, arg0: bool) -> None: ...
    def getShowsDialog(self) -> bool: ...
    def onAttach(self, arg0: Context) -> None: ...
    def onDetach(self) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onGetLayoutInflater(self, arg0: Bundle) -> LayoutInflater: ...
    def onCreateDialog(self, arg0: Bundle) -> Dialog: ...
    def onCancel(self, arg0: DialogInterface) -> None: ...
    def onDismiss(self, arg0: DialogInterface) -> None: ...
    def onActivityCreated(self, arg0: Bundle) -> None: ...
    def onStart(self) -> None: ...
    def onSaveInstanceState(self, arg0: Bundle) -> None: ...
    def onStop(self) -> None: ...
    def onDestroyView(self) -> None: ...
    def dump(self, arg0: str, arg1: FileDescriptor, arg2: PrintWriter, arg3: list[str]) -> None: ...
