from typing import Any, ClassVar, overload
from android.app.Fragment import Fragment
from android.view.View import View
from java.lang.Runnable import Runnable

class FragmentTransaction:
    TRANSIT_ENTER_MASK: ClassVar[int]
    TRANSIT_EXIT_MASK: ClassVar[int]
    TRANSIT_FRAGMENT_CLOSE: ClassVar[int]
    TRANSIT_FRAGMENT_FADE: ClassVar[int]
    TRANSIT_FRAGMENT_OPEN: ClassVar[int]
    TRANSIT_NONE: ClassVar[int]
    TRANSIT_UNSET: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    def add(self, arg0: Fragment, arg1: str) -> "FragmentTransaction": ...
    @overload
    def add(self, arg0: int, arg1: Fragment) -> "FragmentTransaction": ...
    @overload
    def add(self, arg0: int, arg1: Fragment, arg2: str) -> "FragmentTransaction": ...
    @overload
    def replace(self, arg0: int, arg1: Fragment) -> "FragmentTransaction": ...
    @overload
    def replace(self, arg0: int, arg1: Fragment, arg2: str) -> "FragmentTransaction": ...
    def remove(self, arg0: Fragment) -> "FragmentTransaction": ...
    def hide(self, arg0: Fragment) -> "FragmentTransaction": ...
    def show(self, arg0: Fragment) -> "FragmentTransaction": ...
    def detach(self, arg0: Fragment) -> "FragmentTransaction": ...
    def attach(self, arg0: Fragment) -> "FragmentTransaction": ...
    def setPrimaryNavigationFragment(self, arg0: Fragment) -> "FragmentTransaction": ...
    def isEmpty(self) -> bool: ...
    @overload
    def setCustomAnimations(self, arg0: int, arg1: int) -> "FragmentTransaction": ...
    @overload
    def setCustomAnimations(self, arg0: int, arg1: int, arg2: int, arg3: int) -> "FragmentTransaction": ...
    def setTransition(self, arg0: int) -> "FragmentTransaction": ...
    def addSharedElement(self, arg0: View, arg1: str) -> "FragmentTransaction": ...
    def setTransitionStyle(self, arg0: int) -> "FragmentTransaction": ...
    def addToBackStack(self, arg0: str) -> "FragmentTransaction": ...
    def isAddToBackStackAllowed(self) -> bool: ...
    def disallowAddToBackStack(self) -> "FragmentTransaction": ...
    @overload
    def setBreadCrumbTitle(self, arg0: int) -> "FragmentTransaction": ...
    @overload
    def setBreadCrumbTitle(self, arg0: str) -> "FragmentTransaction": ...
    @overload
    def setBreadCrumbShortTitle(self, arg0: int) -> "FragmentTransaction": ...
    @overload
    def setBreadCrumbShortTitle(self, arg0: str) -> "FragmentTransaction": ...
    def setReorderingAllowed(self, arg0: bool) -> "FragmentTransaction": ...
    def runOnCommit(self, arg0: Runnable) -> "FragmentTransaction": ...
    def commit(self) -> int: ...
    def commitAllowingStateLoss(self) -> int: ...
    def commitNow(self) -> None: ...
    def commitNowAllowingStateLoss(self) -> None: ...
