from typing import Any, ClassVar, overload
from android.animation.Animator import Animator
from android.app.Activity import Activity
from android.app.FragmentManager import FragmentManager
from android.app.LoaderManager import LoaderManager
from android.app.SharedElementCallback import SharedElementCallback
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.IntentSender import IntentSender
from android.content.res.Configuration import Configuration
from android.content.res.Resources import Resources
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.transition.Transition import Transition
from android.util.AttributeSet import AttributeSet
from android.view.ContextMenu import ContextMenu
from android.view.LayoutInflater import LayoutInflater
from android.view.Menu import Menu
from android.view.MenuInflater import MenuInflater
from android.view.MenuItem import MenuItem
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter
from java.lang.Exception import Exception

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class ContextMenuInfo:
    """Forward declaration for ``android.view.ContextMenu.ContextMenuInfo``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ContextMenu.ContextMenuInfo')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ContextMenu/ContextMenuInfo
    """
    ...
class ClassLoaderCreator:
    """Forward declaration for ``android.os.Parcelable.ClassLoaderCreator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.ClassLoaderCreator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/ClassLoaderCreator
    """
    ...

class Fragment:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def instantiate(arg0: Context, arg1: str) -> "Fragment": ...
    @overload
    @staticmethod
    def instantiate(arg0: Context, arg1: str, arg2: Bundle) -> "Fragment": ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def getId(self) -> int: ...
    def getTag(self) -> str: ...
    def setArguments(self, arg0: Bundle) -> None: ...
    def getArguments(self) -> Bundle: ...
    def isStateSaved(self) -> bool: ...
    def setInitialSavedState(self, arg0: "SavedState") -> None: ...
    def setTargetFragment(self, arg0: "Fragment", arg1: int) -> None: ...
    def getTargetFragment(self) -> "Fragment": ...
    def getTargetRequestCode(self) -> int: ...
    def getContext(self) -> Context: ...
    def getActivity(self) -> Activity: ...
    def getHost(self) -> Any: ...
    def getResources(self) -> Resources: ...
    def getText(self, arg0: int) -> str: ...
    @overload
    def getString(self, arg0: int) -> str: ...
    @overload
    def getString(self, arg0: int, *arg1: Any) -> str: ...
    def getFragmentManager(self) -> FragmentManager: ...
    def getChildFragmentManager(self) -> FragmentManager: ...
    def getParentFragment(self) -> "Fragment": ...
    def isAdded(self) -> bool: ...
    def isDetached(self) -> bool: ...
    def isRemoving(self) -> bool: ...
    def isInLayout(self) -> bool: ...
    def isResumed(self) -> bool: ...
    def isVisible(self) -> bool: ...
    def isHidden(self) -> bool: ...
    def onHiddenChanged(self, arg0: bool) -> None: ...
    def setRetainInstance(self, arg0: bool) -> None: ...
    def getRetainInstance(self) -> bool: ...
    def setHasOptionsMenu(self, arg0: bool) -> None: ...
    def setMenuVisibility(self, arg0: bool) -> None: ...
    def setUserVisibleHint(self, arg0: bool) -> None: ...
    def getUserVisibleHint(self) -> bool: ...
    def getLoaderManager(self) -> LoaderManager: ...
    @overload
    def startActivity(self, arg0: Intent) -> None: ...
    @overload
    def startActivity(self, arg0: Intent, arg1: Bundle) -> None: ...
    @overload
    def startActivityForResult(self, arg0: Intent, arg1: int) -> None: ...
    @overload
    def startActivityForResult(self, arg0: Intent, arg1: int, arg2: Bundle) -> None: ...
    def startIntentSenderForResult(self, arg0: IntentSender, arg1: int, arg2: Intent, arg3: int, arg4: int, arg5: int, arg6: Bundle) -> None: ...
    def onActivityResult(self, arg0: int, arg1: int, arg2: Intent) -> None: ...
    def requestPermissions(self, arg0: list[str], arg1: int) -> None: ...
    def onRequestPermissionsResult(self, arg0: int, arg1: list[str], arg2: list[int]) -> None: ...
    def shouldShowRequestPermissionRationale(self, arg0: str) -> bool: ...
    def onGetLayoutInflater(self, arg0: Bundle) -> LayoutInflater: ...
    def getLayoutInflater(self) -> LayoutInflater: ...
    @overload
    def onInflate(self, arg0: AttributeSet, arg1: Bundle) -> None: ...
    @overload
    def onInflate(self, arg0: Context, arg1: AttributeSet, arg2: Bundle) -> None: ...
    @overload
    def onInflate(self, arg0: Activity, arg1: AttributeSet, arg2: Bundle) -> None: ...
    def onAttachFragment(self, arg0: "Fragment") -> None: ...
    @overload
    def onAttach(self, arg0: Context) -> None: ...
    @overload
    def onAttach(self, arg0: Activity) -> None: ...
    def onCreateAnimator(self, arg0: int, arg1: bool, arg2: int) -> Animator: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onCreateView(self, arg0: LayoutInflater, arg1: ViewGroup, arg2: Bundle) -> View: ...
    def onViewCreated(self, arg0: View, arg1: Bundle) -> None: ...
    def getView(self) -> View: ...
    def onActivityCreated(self, arg0: Bundle) -> None: ...
    def onViewStateRestored(self, arg0: Bundle) -> None: ...
    def onStart(self) -> None: ...
    def onResume(self) -> None: ...
    def onSaveInstanceState(self, arg0: Bundle) -> None: ...
    @overload
    def onMultiWindowModeChanged(self, arg0: bool, arg1: Configuration) -> None: ...
    @overload
    def onMultiWindowModeChanged(self, arg0: bool) -> None: ...
    @overload
    def onPictureInPictureModeChanged(self, arg0: bool, arg1: Configuration) -> None: ...
    @overload
    def onPictureInPictureModeChanged(self, arg0: bool) -> None: ...
    def onConfigurationChanged(self, arg0: Configuration) -> None: ...
    def onPause(self) -> None: ...
    def onStop(self) -> None: ...
    def onLowMemory(self) -> None: ...
    def onTrimMemory(self, arg0: int) -> None: ...
    def onDestroyView(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onDetach(self) -> None: ...
    def onCreateOptionsMenu(self, arg0: Menu, arg1: MenuInflater) -> None: ...
    def onPrepareOptionsMenu(self, arg0: Menu) -> None: ...
    def onDestroyOptionsMenu(self) -> None: ...
    def onOptionsItemSelected(self, arg0: MenuItem) -> bool: ...
    def onOptionsMenuClosed(self, arg0: Menu) -> None: ...
    def onCreateContextMenu(self, arg0: ContextMenu, arg1: View, arg2: ContextMenuInfo) -> None: ...
    def registerForContextMenu(self, arg0: View) -> None: ...
    def unregisterForContextMenu(self, arg0: View) -> None: ...
    def onContextItemSelected(self, arg0: MenuItem) -> bool: ...
    def setEnterSharedElementCallback(self, arg0: SharedElementCallback) -> None: ...
    def setExitSharedElementCallback(self, arg0: SharedElementCallback) -> None: ...
    def setEnterTransition(self, arg0: Transition) -> None: ...
    def getEnterTransition(self) -> Transition: ...
    def setReturnTransition(self, arg0: Transition) -> None: ...
    def getReturnTransition(self) -> Transition: ...
    def setExitTransition(self, arg0: Transition) -> None: ...
    def getExitTransition(self) -> Transition: ...
    def setReenterTransition(self, arg0: Transition) -> None: ...
    def getReenterTransition(self) -> Transition: ...
    def setSharedElementEnterTransition(self, arg0: Transition) -> None: ...
    def getSharedElementEnterTransition(self) -> Transition: ...
    def setSharedElementReturnTransition(self, arg0: Transition) -> None: ...
    def getSharedElementReturnTransition(self) -> Transition: ...
    def setAllowEnterTransitionOverlap(self, arg0: bool) -> None: ...
    def getAllowEnterTransitionOverlap(self) -> bool: ...
    def setAllowReturnTransitionOverlap(self, arg0: bool) -> None: ...
    def getAllowReturnTransitionOverlap(self) -> bool: ...
    def postponeEnterTransition(self) -> None: ...
    def startPostponedEnterTransition(self) -> None: ...
    def dump(self, arg0: str, arg1: FileDescriptor, arg2: PrintWriter, arg3: list[str]) -> None: ...

    class InstantiationException:
        def __init__(self, arg0: str, arg1: Exception) -> None: ...

    class SavedState:
        CREATOR: ClassVar[ClassLoaderCreator]
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
