from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.app.Application import Application
from android.app.ComponentCaller import ComponentCaller
from android.app.UiAutomation import UiAutomation
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.IntentFilter import IntentFilter
from android.content.pm.ActivityInfo import ActivityInfo
from android.os.Bundle import Bundle
from android.os.IBinder import IBinder
from android.os.Looper import Looper
from android.os.PersistableBundle import PersistableBundle
from android.os.TestLooperManager import TestLooperManager
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from java.lang.ClassLoader import ClassLoader
from java.lang.Runnable import Runnable
from java.lang.Throwable import Throwable

class Instrumentation:
    REPORT_KEY_IDENTIFIER: ClassVar[str]
    REPORT_KEY_STREAMRESULT: ClassVar[str]
    def __init__(self) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def start(self) -> None: ...
    def onStart(self) -> None: ...
    def onException(self, arg0: Any, arg1: Throwable) -> bool: ...
    def sendStatus(self, arg0: int, arg1: Bundle) -> None: ...
    def addResults(self, arg0: Bundle) -> None: ...
    def finish(self, arg0: int, arg1: Bundle) -> None: ...
    def setAutomaticPerformanceSnapshots(self) -> None: ...
    def startPerformanceSnapshot(self) -> None: ...
    def endPerformanceSnapshot(self) -> None: ...
    def onDestroy(self) -> None: ...
    def getContext(self) -> Context: ...
    def getComponentName(self) -> ComponentName: ...
    def getTargetContext(self) -> Context: ...
    def getProcessName(self) -> str: ...
    def isProfiling(self) -> bool: ...
    def startProfiling(self) -> None: ...
    def stopProfiling(self) -> None: ...
    def setInTouchMode(self, arg0: bool) -> None: ...
    def resetInTouchMode(self) -> None: ...
    def waitForIdle(self, arg0: Runnable) -> None: ...
    def waitForIdleSync(self) -> None: ...
    def runOnMainSync(self, arg0: Runnable) -> None: ...
    @overload
    def startActivitySync(self, arg0: Intent) -> Activity: ...
    @overload
    def startActivitySync(self, arg0: Intent, arg1: Bundle) -> Activity: ...
    @overload
    def addMonitor(self, arg0: "ActivityMonitor") -> None: ...
    @overload
    def addMonitor(self, arg0: IntentFilter, arg1: "ActivityResult", arg2: bool) -> "ActivityMonitor": ...
    @overload
    def addMonitor(self, arg0: str, arg1: "ActivityResult", arg2: bool) -> "ActivityMonitor": ...
    def checkMonitorHit(self, arg0: "ActivityMonitor", arg1: int) -> bool: ...
    def waitForMonitor(self, arg0: "ActivityMonitor") -> Activity: ...
    def waitForMonitorWithTimeout(self, arg0: "ActivityMonitor", arg1: int) -> Activity: ...
    def removeMonitor(self, arg0: "ActivityMonitor") -> None: ...
    def invokeMenuActionSync(self, arg0: Activity, arg1: int, arg2: int) -> bool: ...
    def invokeContextMenuAction(self, arg0: Activity, arg1: int, arg2: int) -> bool: ...
    def sendStringSync(self, arg0: str) -> None: ...
    def sendKeySync(self, arg0: KeyEvent) -> None: ...
    def sendKeyDownUpSync(self, arg0: int) -> None: ...
    def sendCharacterSync(self, arg0: int) -> None: ...
    def sendPointerSync(self, arg0: MotionEvent) -> None: ...
    def sendTrackballEventSync(self, arg0: MotionEvent) -> None: ...
    @overload
    def newApplication(self, arg0: ClassLoader, arg1: str, arg2: Context) -> Application: ...
    @overload
    @staticmethod
    def newApplication(arg0: type, arg1: Context) -> Application: ...
    def callApplicationOnCreate(self, arg0: Application) -> None: ...
    @overload
    def newActivity(self, arg0: type, arg1: Context, arg2: IBinder, arg3: Application, arg4: Intent, arg5: ActivityInfo, arg6: str, arg7: Activity, arg8: str, arg9: Any) -> Activity: ...
    @overload
    def newActivity(self, arg0: ClassLoader, arg1: str, arg2: Intent) -> Activity: ...
    @overload
    def callActivityOnCreate(self, arg0: Activity, arg1: Bundle) -> None: ...
    @overload
    def callActivityOnCreate(self, arg0: Activity, arg1: Bundle, arg2: PersistableBundle) -> None: ...
    def callActivityOnDestroy(self, arg0: Activity) -> None: ...
    @overload
    def callActivityOnRestoreInstanceState(self, arg0: Activity, arg1: Bundle) -> None: ...
    @overload
    def callActivityOnRestoreInstanceState(self, arg0: Activity, arg1: Bundle, arg2: PersistableBundle) -> None: ...
    @overload
    def callActivityOnPostCreate(self, arg0: Activity, arg1: Bundle) -> None: ...
    @overload
    def callActivityOnPostCreate(self, arg0: Activity, arg1: Bundle, arg2: PersistableBundle) -> None: ...
    @overload
    def callActivityOnNewIntent(self, arg0: Activity, arg1: Intent) -> None: ...
    @overload
    def callActivityOnNewIntent(self, arg0: Activity, arg1: Intent, arg2: ComponentCaller) -> None: ...
    def callActivityOnStart(self, arg0: Activity) -> None: ...
    def callActivityOnRestart(self, arg0: Activity) -> None: ...
    def callActivityOnResume(self, arg0: Activity) -> None: ...
    def callActivityOnStop(self, arg0: Activity) -> None: ...
    @overload
    def callActivityOnSaveInstanceState(self, arg0: Activity, arg1: Bundle) -> None: ...
    @overload
    def callActivityOnSaveInstanceState(self, arg0: Activity, arg1: Bundle, arg2: PersistableBundle) -> None: ...
    def callActivityOnPause(self, arg0: Activity) -> None: ...
    def callActivityOnUserLeaving(self, arg0: Activity) -> None: ...
    def callActivityOnPictureInPictureRequested(self, arg0: Activity) -> None: ...
    def startAllocCounting(self) -> None: ...
    def stopAllocCounting(self) -> None: ...
    def getAllocCounts(self) -> Bundle: ...
    def getBinderCounts(self) -> Bundle: ...
    @overload
    def getUiAutomation(self) -> UiAutomation: ...
    @overload
    def getUiAutomation(self, arg0: int) -> UiAutomation: ...
    def acquireLooperManager(self, arg0: Looper) -> TestLooperManager: ...

    class ActivityMonitor:
        @overload
        def __init__(self, arg0: IntentFilter, arg1: "ActivityResult", arg2: bool) -> None: ...
        @overload
        def __init__(self, arg0: str, arg1: "ActivityResult", arg2: bool) -> None: ...
        @overload
        def __init__(self) -> None: ...
        def getFilter(self) -> IntentFilter: ...
        def getResult(self) -> "ActivityResult": ...
        def isBlocking(self) -> bool: ...
        def getHits(self) -> int: ...
        def getLastActivity(self) -> Activity: ...
        def waitForActivity(self) -> Activity: ...
        def waitForActivityWithTimeout(self, arg0: int) -> Activity: ...
        def onStartActivity(self, arg0: Intent) -> "ActivityResult": ...

    class ActivityResult:
        def __init__(self, arg0: int, arg1: Intent) -> None: ...
        def getResultCode(self) -> int: ...
        def getResultData(self) -> Intent: ...
