from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.Intent import Intent
from java.util.concurrent.Executor import Executor

class KeyguardManager:
    def createConfirmDeviceCredentialIntent(self, arg0: str, arg1: str) -> Intent: ...
    def newKeyguardLock(self, arg0: str) -> "KeyguardLock": ...
    def isKeyguardLocked(self) -> bool: ...
    def isKeyguardSecure(self) -> bool: ...
    def inKeyguardRestrictedInputMode(self) -> bool: ...
    def isDeviceLocked(self) -> bool: ...
    def isDeviceSecure(self) -> bool: ...
    def requestDismissKeyguard(self, arg0: Activity, arg1: "KeyguardDismissCallback") -> None: ...
    def exitKeyguardSecurely(self, arg0: "OnKeyguardExitResult") -> None: ...
    def addKeyguardLockedStateListener(self, arg0: Executor, arg1: "KeyguardLockedStateListener") -> None: ...
    def removeKeyguardLockedStateListener(self, arg0: "KeyguardLockedStateListener") -> None: ...

    class KeyguardDismissCallback:
        def __init__(self) -> None: ...
        def onDismissError(self) -> None: ...
        def onDismissSucceeded(self) -> None: ...
        def onDismissCancelled(self) -> None: ...

    class KeyguardLock:
        def disableKeyguard(self) -> None: ...
        def reenableKeyguard(self) -> None: ...

    class KeyguardLockedStateListener:
        def onKeyguardLockedStateChanged(self, arg0: bool) -> None: ...

    class OnKeyguardExitResult:
        def onKeyguardExitResult(self, arg0: bool) -> None: ...
