from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.content.pm.ResolveInfo import ResolveInfo
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.view.View import View
from android.widget.ListView import ListView

class LauncherActivity:
    def __init__(self) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    @overload
    def setTitle(self, arg0: str) -> None: ...
    @overload
    def setTitle(self, arg0: int) -> None: ...
    def onSetContentView(self) -> None: ...
    def onListItemClick(self, arg0: ListView, arg1: View, arg2: int, arg3: int) -> None: ...
    def intentForPosition(self, arg0: int) -> Intent: ...
    def itemForPosition(self, arg0: int) -> "ListItem": ...
    def getTargetIntent(self) -> Intent: ...
    def onQueryPackageManager(self, arg0: Intent) -> list: ...
    def makeListItems(self) -> list: ...

    class IconResizer:
        def __init__(self, arg0: "LauncherActivity") -> None: ...
        def createIconThumbnail(self, arg0: Drawable) -> Drawable: ...

    class ListItem:
        className: str
        extras: Bundle
        icon: Drawable
        label: str
        packageName: str
        resolveInfo: ResolveInfo
        def __init__(self) -> None: ...
