from typing import Any, ClassVar, overload
from android.content.Loader import Loader
from android.os.Bundle import Bundle
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class LoaderManager:
    def __init__(self) -> None: ...
    def initLoader(self, arg0: int, arg1: Bundle, arg2: "LoaderCallbacks") -> Loader: ...
    def restartLoader(self, arg0: int, arg1: Bundle, arg2: "LoaderCallbacks") -> Loader: ...
    def destroyLoader(self, arg0: int) -> None: ...
    def getLoader(self, arg0: int) -> Loader: ...
    def dump(self, arg0: str, arg1: FileDescriptor, arg2: PrintWriter, arg3: list[str]) -> None: ...
    @staticmethod
    def enableDebugLogging(arg0: bool) -> None: ...

    class LoaderCallbacks:
        def onCreateLoader(self, arg0: int, arg1: Bundle) -> Loader: ...
        def onLoadFinished(self, arg0: Loader, arg1: Any) -> None: ...
        def onLoaderReset(self, arg0: Loader) -> None: ...
