from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Canvas import Canvas
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OnClickListener:
    """Forward declaration for ``android.view.View.OnClickListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.View.OnClickListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/View/OnClickListener
    """
    ...

class MediaRouteButton:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def getRouteTypes(self) -> int: ...
    def setRouteTypes(self, arg0: int) -> None: ...
    def setExtendedSettingsClickListener(self, arg0: OnClickListener) -> None: ...
    def showDialog(self) -> None: ...
    def setContentDescription(self, arg0: str) -> None: ...
    def performClick(self) -> bool: ...
    def onCreateDrawableState(self, arg0: int) -> list[int]: ...
    def drawableStateChanged(self) -> None: ...
    def verifyDrawable(self, arg0: Drawable) -> bool: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def setVisibility(self, arg0: int) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onDraw(self, arg0: Canvas) -> None: ...
