from typing import Any, ClassVar, overload
from android.content.res.Configuration import Configuration
from android.os.Bundle import Bundle
from android.view.InputQueue import InputQueue
from android.view.SurfaceHolder import SurfaceHolder

class NativeActivity:
    META_DATA_FUNC_NAME: ClassVar[str]
    META_DATA_LIB_NAME: ClassVar[str]
    def __init__(self) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onDestroy(self) -> None: ...
    def onPause(self) -> None: ...
    def onResume(self) -> None: ...
    def onSaveInstanceState(self, arg0: Bundle) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    def onConfigurationChanged(self, arg0: Configuration) -> None: ...
    def onLowMemory(self) -> None: ...
    def onWindowFocusChanged(self, arg0: bool) -> None: ...
    def surfaceCreated(self, arg0: SurfaceHolder) -> None: ...
    def surfaceChanged(self, arg0: SurfaceHolder, arg1: int, arg2: int, arg3: int) -> None: ...
    def surfaceRedrawNeeded(self, arg0: SurfaceHolder) -> None: ...
    def surfaceDestroyed(self, arg0: SurfaceHolder) -> None: ...
    def onInputQueueCreated(self, arg0: InputQueue) -> None: ...
    def onInputQueueDestroyed(self, arg0: InputQueue) -> None: ...
    def onGlobalLayout(self) -> None: ...
