from typing import Any, ClassVar, overload
from android.media.AudioAttributes import AudioAttributes
from android.net.Uri import Uri
from android.os.Parcel import Parcel
from android.os.VibrationEffect import VibrationEffect

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class NotificationChannel:
    CREATOR: ClassVar[Creator]
    DEFAULT_CHANNEL_ID: ClassVar[str]
    EDIT_CONVERSATION: ClassVar[str]
    EDIT_IMPORTANCE: ClassVar[str]
    EDIT_LAUNCHER: ClassVar[str]
    EDIT_LOCKED_DEVICE: ClassVar[str]
    EDIT_SOUND: ClassVar[str]
    EDIT_VIBRATION: ClassVar[str]
    EDIT_ZEN: ClassVar[str]
    def __init__(self, arg0: str, arg1: str, arg2: int) -> None: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def setBlockable(self, arg0: bool) -> None: ...
    def setName(self, arg0: str) -> None: ...
    def setDescription(self, arg0: str) -> None: ...
    def setGroup(self, arg0: str) -> None: ...
    def setShowBadge(self, arg0: bool) -> None: ...
    def setSound(self, arg0: Uri, arg1: AudioAttributes) -> None: ...
    def enableLights(self, arg0: bool) -> None: ...
    def setLightColor(self, arg0: int) -> None: ...
    def enableVibration(self, arg0: bool) -> None: ...
    def setVibrationPattern(self, arg0: list[int]) -> None: ...
    def setVibrationEffect(self, arg0: VibrationEffect) -> None: ...
    def setImportance(self, arg0: int) -> None: ...
    def setBypassDnd(self, arg0: bool) -> None: ...
    def setLockscreenVisibility(self, arg0: int) -> None: ...
    def setAllowBubbles(self, arg0: bool) -> None: ...
    def setConversationId(self, arg0: str, arg1: str) -> None: ...
    def getId(self) -> str: ...
    def getName(self) -> str: ...
    def getDescription(self) -> str: ...
    def getImportance(self) -> int: ...
    def canBypassDnd(self) -> bool: ...
    def isConversation(self) -> bool: ...
    def isImportantConversation(self) -> bool: ...
    def getSound(self) -> Uri: ...
    def getAudioAttributes(self) -> AudioAttributes: ...
    def shouldShowLights(self) -> bool: ...
    def getLightColor(self) -> int: ...
    def shouldVibrate(self) -> bool: ...
    def getVibrationPattern(self) -> list[int]: ...
    def getVibrationEffect(self) -> VibrationEffect: ...
    def getLockscreenVisibility(self) -> int: ...
    def canShowBadge(self) -> bool: ...
    def getGroup(self) -> str: ...
    def canBubble(self) -> bool: ...
    def getParentChannelId(self) -> str: ...
    def getConversationId(self) -> str: ...
    def isBlockable(self) -> bool: ...
    def isDemoted(self) -> bool: ...
    def hasUserSetImportance(self) -> bool: ...
    def hasUserSetSound(self) -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
