from typing import Any, ClassVar, overload
from android.app.AutomaticZenRule import AutomaticZenRule
from android.app.Notification import Notification
from android.app.NotificationChannel import NotificationChannel
from android.app.NotificationChannelGroup import NotificationChannelGroup
from android.content.ComponentName import ComponentName
from android.net.Uri import Uri
from android.os.Parcel import Parcel
from android.service.notification.Condition import Condition
from android.service.notification.StatusBarNotification import StatusBarNotification

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class NotificationManager:
    ACTION_APP_BLOCK_STATE_CHANGED: ClassVar[str]
    ACTION_AUTOMATIC_ZEN_RULE: ClassVar[str]
    ACTION_AUTOMATIC_ZEN_RULE_STATUS_CHANGED: ClassVar[str]
    ACTION_CONSOLIDATED_NOTIFICATION_POLICY_CHANGED: ClassVar[str]
    ACTION_INTERRUPTION_FILTER_CHANGED: ClassVar[str]
    ACTION_NOTIFICATION_CHANNEL_BLOCK_STATE_CHANGED: ClassVar[str]
    ACTION_NOTIFICATION_CHANNEL_GROUP_BLOCK_STATE_CHANGED: ClassVar[str]
    ACTION_NOTIFICATION_POLICY_ACCESS_GRANTED_CHANGED: ClassVar[str]
    ACTION_NOTIFICATION_POLICY_CHANGED: ClassVar[str]
    AUTOMATIC_RULE_STATUS_ACTIVATED: ClassVar[int]
    AUTOMATIC_RULE_STATUS_DEACTIVATED: ClassVar[int]
    AUTOMATIC_RULE_STATUS_DISABLED: ClassVar[int]
    AUTOMATIC_RULE_STATUS_ENABLED: ClassVar[int]
    AUTOMATIC_RULE_STATUS_REMOVED: ClassVar[int]
    AUTOMATIC_RULE_STATUS_UNKNOWN: ClassVar[int]
    BUBBLE_PREFERENCE_ALL: ClassVar[int]
    BUBBLE_PREFERENCE_NONE: ClassVar[int]
    BUBBLE_PREFERENCE_SELECTED: ClassVar[int]
    EXTRA_AUTOMATIC_RULE_ID: ClassVar[str]
    EXTRA_AUTOMATIC_ZEN_RULE_ID: ClassVar[str]
    EXTRA_AUTOMATIC_ZEN_RULE_STATUS: ClassVar[str]
    EXTRA_BLOCKED_STATE: ClassVar[str]
    EXTRA_NOTIFICATION_CHANNEL_GROUP_ID: ClassVar[str]
    EXTRA_NOTIFICATION_CHANNEL_ID: ClassVar[str]
    EXTRA_NOTIFICATION_POLICY: ClassVar[str]
    IMPORTANCE_DEFAULT: ClassVar[int]
    IMPORTANCE_HIGH: ClassVar[int]
    IMPORTANCE_LOW: ClassVar[int]
    IMPORTANCE_MAX: ClassVar[int]
    IMPORTANCE_MIN: ClassVar[int]
    IMPORTANCE_NONE: ClassVar[int]
    IMPORTANCE_UNSPECIFIED: ClassVar[int]
    INTERRUPTION_FILTER_ALARMS: ClassVar[int]
    INTERRUPTION_FILTER_ALL: ClassVar[int]
    INTERRUPTION_FILTER_NONE: ClassVar[int]
    INTERRUPTION_FILTER_PRIORITY: ClassVar[int]
    INTERRUPTION_FILTER_UNKNOWN: ClassVar[int]
    META_DATA_AUTOMATIC_RULE_TYPE: ClassVar[str]
    META_DATA_RULE_INSTANCE_LIMIT: ClassVar[str]
    @overload
    def notify(self, arg0: int, arg1: Notification) -> None: ...
    @overload
    def notify(self, arg0: str, arg1: int, arg2: Notification) -> None: ...
    def notifyAsPackage(self, arg0: str, arg1: str, arg2: int, arg3: Notification) -> None: ...
    @overload
    def cancel(self, arg0: int) -> None: ...
    @overload
    def cancel(self, arg0: str, arg1: int) -> None: ...
    def cancelAsPackage(self, arg0: str, arg1: str, arg2: int) -> None: ...
    def cancelAll(self) -> None: ...
    def setNotificationDelegate(self, arg0: str) -> None: ...
    def getNotificationDelegate(self) -> str: ...
    def canNotifyAsPackage(self, arg0: str) -> bool: ...
    def canUseFullScreenIntent(self) -> bool: ...
    def createNotificationChannelGroup(self, arg0: NotificationChannelGroup) -> None: ...
    def createNotificationChannelGroups(self, arg0: list) -> None: ...
    def createNotificationChannel(self, arg0: NotificationChannel) -> None: ...
    def createNotificationChannels(self, arg0: list) -> None: ...
    @overload
    def getNotificationChannel(self, arg0: str) -> NotificationChannel: ...
    @overload
    def getNotificationChannel(self, arg0: str, arg1: str) -> NotificationChannel: ...
    def getNotificationChannels(self) -> list: ...
    def deleteNotificationChannel(self, arg0: str) -> None: ...
    def getNotificationChannelGroup(self, arg0: str) -> NotificationChannelGroup: ...
    def getNotificationChannelGroups(self) -> list: ...
    def deleteNotificationChannelGroup(self, arg0: str) -> None: ...
    def getConsolidatedNotificationPolicy(self) -> "Policy": ...
    def areAutomaticZenRulesUserManaged(self) -> bool: ...
    def getAutomaticZenRules(self) -> dict: ...
    def getAutomaticZenRule(self, arg0: str) -> AutomaticZenRule: ...
    def addAutomaticZenRule(self, arg0: AutomaticZenRule) -> str: ...
    def updateAutomaticZenRule(self, arg0: str, arg1: AutomaticZenRule) -> bool: ...
    def getAutomaticZenRuleState(self, arg0: str) -> int: ...
    def setAutomaticZenRuleState(self, arg0: str, arg1: Condition) -> None: ...
    def removeAutomaticZenRule(self, arg0: str) -> bool: ...
    def getImportance(self) -> int: ...
    def areNotificationsEnabled(self) -> bool: ...
    def areBubblesAllowed(self) -> bool: ...
    def areBubblesEnabled(self) -> bool: ...
    def getBubblePreference(self) -> int: ...
    def areNotificationsPaused(self) -> bool: ...
    def isNotificationPolicyAccessGranted(self) -> bool: ...
    def isNotificationListenerAccessGranted(self, arg0: ComponentName) -> bool: ...
    def shouldHideSilentStatusBarIcons(self) -> bool: ...
    def getNotificationPolicy(self) -> "Policy": ...
    def setNotificationPolicy(self, arg0: "Policy") -> None: ...
    def getActiveNotifications(self) -> list[StatusBarNotification]: ...
    def getCurrentInterruptionFilter(self) -> int: ...
    def setInterruptionFilter(self, arg0: int) -> None: ...
    def matchesCallFilter(self, arg0: Uri) -> bool: ...

    class Policy:
        CONVERSATION_SENDERS_ANYONE: ClassVar[int]
        CONVERSATION_SENDERS_IMPORTANT: ClassVar[int]
        CONVERSATION_SENDERS_NONE: ClassVar[int]
        CREATOR: ClassVar[Creator]
        PRIORITY_CATEGORY_ALARMS: ClassVar[int]
        PRIORITY_CATEGORY_CALLS: ClassVar[int]
        PRIORITY_CATEGORY_CONVERSATIONS: ClassVar[int]
        PRIORITY_CATEGORY_EVENTS: ClassVar[int]
        PRIORITY_CATEGORY_MEDIA: ClassVar[int]
        PRIORITY_CATEGORY_MESSAGES: ClassVar[int]
        PRIORITY_CATEGORY_REMINDERS: ClassVar[int]
        PRIORITY_CATEGORY_REPEAT_CALLERS: ClassVar[int]
        PRIORITY_CATEGORY_SYSTEM: ClassVar[int]
        PRIORITY_SENDERS_ANY: ClassVar[int]
        PRIORITY_SENDERS_CONTACTS: ClassVar[int]
        PRIORITY_SENDERS_STARRED: ClassVar[int]
        SUPPRESSED_EFFECT_AMBIENT: ClassVar[int]
        SUPPRESSED_EFFECT_BADGE: ClassVar[int]
        SUPPRESSED_EFFECT_FULL_SCREEN_INTENT: ClassVar[int]
        SUPPRESSED_EFFECT_LIGHTS: ClassVar[int]
        SUPPRESSED_EFFECT_NOTIFICATION_LIST: ClassVar[int]
        SUPPRESSED_EFFECT_PEEK: ClassVar[int]
        SUPPRESSED_EFFECT_SCREEN_OFF: ClassVar[int]
        SUPPRESSED_EFFECT_SCREEN_ON: ClassVar[int]
        SUPPRESSED_EFFECT_STATUS_BAR: ClassVar[int]
        priorityCallSenders: int
        priorityCategories: int
        priorityConversationSenders: int
        priorityMessageSenders: int
        suppressedVisualEffects: int
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def describeContents(self) -> int: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def toString(self) -> str: ...
        @staticmethod
        def suppressedEffectsToString(arg0: int) -> str: ...
        @staticmethod
        def priorityCategoriesToString(arg0: int) -> str: ...
        @staticmethod
        def prioritySendersToString(arg0: int) -> str: ...
