from typing import Any, ClassVar, overload
from android.graphics.drawable.Icon import Icon
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Person:
    CREATOR: ClassVar[Creator]
    def toBuilder(self) -> "Builder": ...
    def getUri(self) -> str: ...
    def getName(self) -> str: ...
    def getIcon(self) -> Icon: ...
    def getKey(self) -> str: ...
    def isBot(self) -> bool: ...
    def isImportant(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setName(self, arg0: str) -> "Builder": ...
        def setIcon(self, arg0: Icon) -> "Builder": ...
        def setUri(self, arg0: str) -> "Builder": ...
        def setKey(self, arg0: str) -> "Builder": ...
        def setImportant(self, arg0: bool) -> "Builder": ...
        def setBot(self, arg0: bool) -> "Builder": ...
        def build(self) -> "Person": ...
