from typing import Any, ClassVar, overload
from android.app.RemoteAction import RemoteAction
from android.graphics.Rect import Rect
from android.os.Parcel import Parcel
from android.util.Rational import Rational

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class PictureInPictureParams:
    CREATOR: ClassVar[Creator]
    def getAspectRatio(self) -> Rational: ...
    def getExpandedAspectRatio(self) -> Rational: ...
    def getActions(self) -> list: ...
    def getCloseAction(self) -> RemoteAction: ...
    def getSourceRectHint(self) -> Rect: ...
    def isAutoEnterEnabled(self) -> bool: ...
    def isSeamlessResizeEnabled(self) -> bool: ...
    def getTitle(self) -> str: ...
    def getSubtitle(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: "PictureInPictureParams") -> None: ...
        def setAspectRatio(self, arg0: Rational) -> "Builder": ...
        def setExpandedAspectRatio(self, arg0: Rational) -> "Builder": ...
        def setActions(self, arg0: list) -> "Builder": ...
        def setCloseAction(self, arg0: RemoteAction) -> "Builder": ...
        def setSourceRectHint(self, arg0: Rect) -> "Builder": ...
        def setAutoEnterEnabled(self, arg0: bool) -> "Builder": ...
        def setSeamlessResizeEnabled(self, arg0: bool) -> "Builder": ...
        def setTitle(self, arg0: str) -> "Builder": ...
        def setSubtitle(self, arg0: str) -> "Builder": ...
        def build(self) -> "PictureInPictureParams": ...
