from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class RemoteInput:
    CREATOR: ClassVar[Creator]
    EDIT_CHOICES_BEFORE_SENDING_AUTO: ClassVar[int]
    EDIT_CHOICES_BEFORE_SENDING_DISABLED: ClassVar[int]
    EDIT_CHOICES_BEFORE_SENDING_ENABLED: ClassVar[int]
    EXTRA_RESULTS_DATA: ClassVar[str]
    RESULTS_CLIP_LABEL: ClassVar[str]
    SOURCE_CHOICE: ClassVar[int]
    SOURCE_FREE_FORM_INPUT: ClassVar[int]
    def getResultKey(self) -> str: ...
    def getLabel(self) -> str: ...
    def getChoices(self) -> list[str]: ...
    def getAllowedDataTypes(self) -> set: ...
    def isDataOnly(self) -> bool: ...
    def getAllowFreeFormInput(self) -> bool: ...
    def getEditChoicesBeforeSending(self) -> int: ...
    def getExtras(self) -> Bundle: ...
    @staticmethod
    def getDataResultsFromIntent(arg0: Intent, arg1: str) -> dict: ...
    @staticmethod
    def getResultsFromIntent(arg0: Intent) -> Bundle: ...
    @staticmethod
    def addResultsToIntent(arg0: list["RemoteInput"], arg1: Intent, arg2: Bundle) -> None: ...
    @staticmethod
    def addDataResultToIntent(arg0: "RemoteInput", arg1: Intent, arg2: dict) -> None: ...
    @staticmethod
    def setResultsSource(arg0: Intent, arg1: int) -> None: ...
    @staticmethod
    def getResultsSource(arg0: Intent) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self, arg0: str) -> None: ...
        def setLabel(self, arg0: str) -> "Builder": ...
        def setChoices(self, arg0: list[str]) -> "Builder": ...
        def setAllowDataType(self, arg0: str, arg1: bool) -> "Builder": ...
        def setAllowFreeFormInput(self, arg0: bool) -> "Builder": ...
        def setEditChoicesBeforeSending(self, arg0: int) -> "Builder": ...
        def addExtras(self, arg0: Bundle) -> "Builder": ...
        def getExtras(self) -> Bundle: ...
        def build(self) -> "RemoteInput": ...
