from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Matrix import Matrix
from android.graphics.RectF import RectF
from android.os.Parcelable import Parcelable
from android.view.View import View

class SharedElementCallback:
    def __init__(self) -> None: ...
    def onSharedElementStart(self, arg0: list, arg1: list, arg2: list) -> None: ...
    def onSharedElementEnd(self, arg0: list, arg1: list, arg2: list) -> None: ...
    def onRejectSharedElements(self, arg0: list) -> None: ...
    def onMapSharedElements(self, arg0: list, arg1: dict) -> None: ...
    def onCaptureSharedElementSnapshot(self, arg0: View, arg1: Matrix, arg2: RectF) -> Parcelable: ...
    def onCreateSnapshotView(self, arg0: Context, arg1: Parcelable) -> View: ...
    def onSharedElementsArrived(self, arg0: list, arg1: list, arg2: "OnSharedElementsReadyListener") -> None: ...

    class OnSharedElementsReadyListener:
        def onSharedElementsReady(self) -> None: ...
