from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.os.Bundle import Bundle
from android.widget.TabHost import TabHost
from android.widget.TabWidget import TabWidget

class TabActivity:
    def __init__(self) -> None: ...
    @overload
    def setDefaultTab(self, arg0: str) -> None: ...
    @overload
    def setDefaultTab(self, arg0: int) -> None: ...
    def onRestoreInstanceState(self, arg0: Bundle) -> None: ...
    def onPostCreate(self, arg0: Bundle) -> None: ...
    def onSaveInstanceState(self, arg0: Bundle) -> None: ...
    def onContentChanged(self) -> None: ...
    def onChildTitleChanged(self, arg0: Activity, arg1: str) -> None: ...
    def getTabHost(self) -> TabHost: ...
    def getTabWidget(self) -> TabWidget: ...
