from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.content.pm.PackageManager import PackageManager
from android.content.pm.ResolveInfo import ResolveInfo
from android.content.pm.ServiceInfo import ServiceInfo
from android.graphics.drawable.Drawable import Drawable
from android.net.Uri import Uri
from android.os.Parcel import Parcel
from android.util.Printer import Printer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class WallpaperInfo:
    CREATOR: ClassVar[Creator]
    def __init__(self, arg0: Context, arg1: ResolveInfo) -> None: ...
    def getPackageName(self) -> str: ...
    def getServiceName(self) -> str: ...
    def getServiceInfo(self) -> ServiceInfo: ...
    def getComponent(self) -> ComponentName: ...
    def loadLabel(self, arg0: PackageManager) -> str: ...
    def loadIcon(self, arg0: PackageManager) -> Drawable: ...
    def loadThumbnail(self, arg0: PackageManager) -> Drawable: ...
    def loadAuthor(self, arg0: PackageManager) -> str: ...
    def loadDescription(self, arg0: PackageManager) -> str: ...
    def loadContextUri(self, arg0: PackageManager) -> Uri: ...
    def loadContextDescription(self, arg0: PackageManager) -> str: ...
    def getShowMetadataInPreview(self) -> bool: ...
    def getSettingsActivity(self) -> str: ...
    def getSettingsSliceUri(self) -> Uri: ...
    def supportsMultipleDisplays(self) -> bool: ...
    def shouldUseDefaultUnfoldTransition(self) -> bool: ...
    def dump(self, arg0: Printer, arg1: str) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
