from typing import Any, ClassVar, overload
from android.app.WallpaperColors import WallpaperColors
from android.app.WallpaperInfo import WallpaperInfo
from android.content.Context import Context
from android.content.Intent import Intent
from android.graphics.Bitmap import Bitmap
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.os.IBinder import IBinder
from android.os.ParcelFileDescriptor import ParcelFileDescriptor
from java.io.InputStream import InputStream

class WallpaperManager:
    ACTION_CHANGE_LIVE_WALLPAPER: ClassVar[str]
    ACTION_CROP_AND_SET_WALLPAPER: ClassVar[str]
    ACTION_LIVE_WALLPAPER_CHOOSER: ClassVar[str]
    COMMAND_DROP: ClassVar[str]
    COMMAND_SECONDARY_TAP: ClassVar[str]
    COMMAND_TAP: ClassVar[str]
    EXTRA_LIVE_WALLPAPER_COMPONENT: ClassVar[str]
    FLAG_LOCK: ClassVar[int]
    FLAG_SYSTEM: ClassVar[int]
    WALLPAPER_PREVIEW_META_DATA: ClassVar[str]
    @staticmethod
    def getInstance(arg0: Context) -> "WallpaperManager": ...
    @overload
    def getDrawable(self) -> Drawable: ...
    @overload
    def getDrawable(self, arg0: int) -> Drawable: ...
    @overload
    def getBuiltInDrawable(self) -> Drawable: ...
    @overload
    def getBuiltInDrawable(self, arg0: int) -> Drawable: ...
    @overload
    def getBuiltInDrawable(self, arg0: int, arg1: int, arg2: bool, arg3: float, arg4: float) -> Drawable: ...
    @overload
    def getBuiltInDrawable(self, arg0: int, arg1: int, arg2: bool, arg3: float, arg4: float, arg5: int) -> Drawable: ...
    @overload
    def peekDrawable(self) -> Drawable: ...
    @overload
    def peekDrawable(self, arg0: int) -> Drawable: ...
    @overload
    def getFastDrawable(self) -> Drawable: ...
    @overload
    def getFastDrawable(self, arg0: int) -> Drawable: ...
    @overload
    def peekFastDrawable(self) -> Drawable: ...
    @overload
    def peekFastDrawable(self, arg0: int) -> Drawable: ...
    def getWallpaperFile(self, arg0: int) -> ParcelFileDescriptor: ...
    def addOnColorsChangedListener(self, arg0: "OnColorsChangedListener", arg1: Handler) -> None: ...
    def removeOnColorsChangedListener(self, arg0: "OnColorsChangedListener") -> None: ...
    def getWallpaperColors(self, arg0: int) -> WallpaperColors: ...
    def forgetLoadedWallpaper(self) -> None: ...
    @overload
    def getWallpaperInfo(self) -> WallpaperInfo: ...
    @overload
    def getWallpaperInfo(self, arg0: int) -> WallpaperInfo: ...
    def getWallpaperId(self, arg0: int) -> int: ...
    def getCropAndSetWallpaperIntent(self, arg0: Uri) -> Intent: ...
    @overload
    def setResource(self, arg0: int) -> None: ...
    @overload
    def setResource(self, arg0: int, arg1: int) -> int: ...
    @overload
    def setBitmap(self, arg0: Bitmap) -> None: ...
    @overload
    def setBitmap(self, arg0: Bitmap, arg1: Rect, arg2: bool) -> int: ...
    @overload
    def setBitmap(self, arg0: Bitmap, arg1: Rect, arg2: bool, arg3: int) -> int: ...
    @overload
    def setStream(self, arg0: InputStream) -> None: ...
    @overload
    def setStream(self, arg0: InputStream, arg1: Rect, arg2: bool) -> int: ...
    @overload
    def setStream(self, arg0: InputStream, arg1: Rect, arg2: bool, arg3: int) -> int: ...
    def hasResourceWallpaper(self, arg0: int) -> bool: ...
    def getDesiredMinimumWidth(self) -> int: ...
    def getDesiredMinimumHeight(self) -> int: ...
    def suggestDesiredDimensions(self, arg0: int, arg1: int) -> None: ...
    def setDisplayPadding(self, arg0: Rect) -> None: ...
    def clearWallpaper(self) -> None: ...
    def setWallpaperOffsets(self, arg0: IBinder, arg1: float, arg2: float) -> None: ...
    def setWallpaperOffsetSteps(self, arg0: float, arg1: float) -> None: ...
    def sendWallpaperCommand(self, arg0: IBinder, arg1: str, arg2: int, arg3: int, arg4: int, arg5: Bundle) -> None: ...
    def isWallpaperSupported(self) -> bool: ...
    def isSetWallpaperAllowed(self) -> bool: ...
    def clearWallpaperOffsets(self, arg0: IBinder) -> None: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self, arg0: int) -> None: ...

    class OnColorsChangedListener:
        def onColorsChanged(self, arg0: WallpaperColors, arg1: int) -> None: ...
