from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress
from java.net.Socket import Socket

class SocketFactory:
    def __init__(self) -> None: ...
    @staticmethod
    def getDefault() -> "SocketFactory": ...
    @overload
    def createSocket(self) -> Socket: ...
    @overload
    def createSocket(self, arg0: str, arg1: int) -> Socket: ...
    @overload
    def createSocket(self, arg0: str, arg1: int, arg2: InetAddress, arg3: int) -> Socket: ...
    @overload
    def createSocket(self, arg0: InetAddress, arg1: int) -> Socket: ...
    @overload
    def createSocket(self, arg0: InetAddress, arg1: int, arg2: InetAddress, arg3: int) -> Socket: ...
