from typing import Any, ClassVar, overload
from java.time.DayOfWeek import DayOfWeek
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.util.function.UnaryOperator import UnaryOperator

class TemporalAdjusters:
    @staticmethod
    def ofDateAdjuster(arg0: UnaryOperator) -> TemporalAdjuster: ...
    @staticmethod
    def firstDayOfMonth() -> TemporalAdjuster: ...
    @staticmethod
    def lastDayOfMonth() -> TemporalAdjuster: ...
    @staticmethod
    def firstDayOfNextMonth() -> TemporalAdjuster: ...
    @staticmethod
    def firstDayOfYear() -> TemporalAdjuster: ...
    @staticmethod
    def lastDayOfYear() -> TemporalAdjuster: ...
    @staticmethod
    def firstDayOfNextYear() -> TemporalAdjuster: ...
    @staticmethod
    def firstInMonth(arg0: DayOfWeek) -> TemporalAdjuster: ...
    @staticmethod
    def lastInMonth(arg0: DayOfWeek) -> TemporalAdjuster: ...
    @staticmethod
    def dayOfWeekInMonth(arg0: int, arg1: DayOfWeek) -> TemporalAdjuster: ...
    @staticmethod
    def next(arg0: DayOfWeek) -> TemporalAdjuster: ...
    @staticmethod
    def nextOrSame(arg0: DayOfWeek) -> TemporalAdjuster: ...
    @staticmethod
    def previous(arg0: DayOfWeek) -> TemporalAdjuster: ...
    @staticmethod
    def previousOrSame(arg0: DayOfWeek) -> TemporalAdjuster: ...
