from typing import Any, ClassVar, overload
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalUnit import TemporalUnit

class TemporalAmount:
    def get(self, arg0: TemporalUnit) -> int: ...
    def getUnits(self) -> list: ...
    def addTo(self, arg0: Temporal) -> Temporal: ...
    def subtractFrom(self, arg0: Temporal) -> Temporal: ...
