from typing import Any, ClassVar, overload
from android.content.ContentResolver import ContentResolver
from android.database.CharArrayBuffer import CharArrayBuffer
from android.database.ContentObserver import ContentObserver
from android.database.CursorWindow import CursorWindow
from android.database.DataSetObserver import DataSetObserver
from android.net.Uri import Uri
from android.os.Bundle import Bundle

class AbstractCursor:
    mClosed: bool
    mContentResolver: ContentResolver
    mPos: int
    def __init__(self) -> None: ...
    def getCount(self) -> int: ...
    def getColumnNames(self) -> list[str]: ...
    def getString(self, arg0: int) -> str: ...
    def getShort(self, arg0: int) -> int: ...
    def getInt(self, arg0: int) -> int: ...
    def getLong(self, arg0: int) -> int: ...
    def getFloat(self, arg0: int) -> float: ...
    def getDouble(self, arg0: int) -> float: ...
    def isNull(self, arg0: int) -> bool: ...
    def getType(self, arg0: int) -> int: ...
    def getBlob(self, arg0: int) -> list[int]: ...
    def getWindow(self) -> CursorWindow: ...
    def getColumnCount(self) -> int: ...
    def deactivate(self) -> None: ...
    def requery(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def close(self) -> None: ...
    def onMove(self, arg0: int, arg1: int) -> bool: ...
    def copyStringToBuffer(self, arg0: int, arg1: CharArrayBuffer) -> None: ...
    def getPosition(self) -> int: ...
    def moveToPosition(self, arg0: int) -> bool: ...
    def fillWindow(self, arg0: int, arg1: CursorWindow) -> None: ...
    def move(self, arg0: int) -> bool: ...
    def moveToFirst(self) -> bool: ...
    def moveToLast(self) -> bool: ...
    def moveToNext(self) -> bool: ...
    def moveToPrevious(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def isLast(self) -> bool: ...
    def isBeforeFirst(self) -> bool: ...
    def isAfterLast(self) -> bool: ...
    def getColumnIndex(self, arg0: str) -> int: ...
    def getColumnIndexOrThrow(self, arg0: str) -> int: ...
    def getColumnName(self, arg0: int) -> str: ...
    def registerContentObserver(self, arg0: ContentObserver) -> None: ...
    def unregisterContentObserver(self, arg0: ContentObserver) -> None: ...
    def registerDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def onChange(self, arg0: bool) -> None: ...
    def setNotificationUri(self, arg0: ContentResolver, arg1: Uri) -> None: ...
    def setNotificationUris(self, arg0: ContentResolver, arg1: list) -> None: ...
    def getNotificationUri(self) -> Uri: ...
    def getNotificationUris(self) -> list: ...
    def getWantsAllOnMoveCalls(self) -> bool: ...
    def setExtras(self, arg0: Bundle) -> None: ...
    def getExtras(self) -> Bundle: ...
    def respond(self, arg0: Bundle) -> Bundle: ...
    def isFieldUpdated(self, arg0: int) -> bool: ...
    def getUpdatedField(self, arg0: int) -> Any: ...
    def checkPosition(self) -> None: ...
    def finalize(self) -> None: ...

    class SelfContentObserver:
        def __init__(self, arg0: "AbstractCursor") -> None: ...
        def deliverSelfNotifications(self) -> bool: ...
        def onChange(self, arg0: bool) -> None: ...
