from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Handler import Handler

class ContentObserver:
    def __init__(self, arg0: Handler) -> None: ...
    def deliverSelfNotifications(self) -> bool: ...
    @overload
    def onChange(self, arg0: bool) -> None: ...
    @overload
    def onChange(self, arg0: bool, arg1: Uri) -> None: ...
    @overload
    def onChange(self, arg0: bool, arg1: Uri, arg2: int) -> None: ...
    @overload
    def onChange(self, arg0: bool, arg1: list, arg2: int) -> None: ...
    @overload
    def dispatchChange(self, arg0: bool) -> None: ...
    @overload
    def dispatchChange(self, arg0: bool, arg1: Uri) -> None: ...
    @overload
    def dispatchChange(self, arg0: bool, arg1: Uri, arg2: int) -> None: ...
    @overload
    def dispatchChange(self, arg0: bool, arg1: list, arg2: int) -> None: ...
