from typing import Any, ClassVar, overload
from android.database.Cursor import Cursor
from java.util.Iterator import Iterator

class CursorJoiner:
    def __init__(self, arg0: Cursor, arg1: list[str], arg2: Cursor, arg3: list[str]) -> None: ...
    def iterator(self) -> Iterator: ...
    def hasNext(self) -> bool: ...
    def next(self) -> "Result": ...
    def remove(self) -> None: ...

    class Result:
        RIGHT: ClassVar["Result"]
        LEFT: ClassVar["Result"]
        BOTH: ClassVar["Result"]
        @staticmethod
        def values() -> list["Result"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Result": ...
