from typing import Any, ClassVar, overload
from android.content.ContentResolver import ContentResolver
from android.database.CharArrayBuffer import CharArrayBuffer
from android.database.ContentObserver import ContentObserver
from android.database.DataSetObserver import DataSetObserver
from android.net.Uri import Uri
from android.os.Bundle import Bundle

class Cursor:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    def getCount(self) -> int: ...
    def getPosition(self) -> int: ...
    def move(self, arg0: int) -> bool: ...
    def moveToPosition(self, arg0: int) -> bool: ...
    def moveToFirst(self) -> bool: ...
    def moveToLast(self) -> bool: ...
    def moveToNext(self) -> bool: ...
    def moveToPrevious(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def isLast(self) -> bool: ...
    def isBeforeFirst(self) -> bool: ...
    def isAfterLast(self) -> bool: ...
    def getColumnIndex(self, arg0: str) -> int: ...
    def getColumnIndexOrThrow(self, arg0: str) -> int: ...
    def getColumnName(self, arg0: int) -> str: ...
    def getColumnNames(self) -> list[str]: ...
    def getColumnCount(self) -> int: ...
    def getBlob(self, arg0: int) -> list[int]: ...
    def getString(self, arg0: int) -> str: ...
    def copyStringToBuffer(self, arg0: int, arg1: CharArrayBuffer) -> None: ...
    def getShort(self, arg0: int) -> int: ...
    def getInt(self, arg0: int) -> int: ...
    def getLong(self, arg0: int) -> int: ...
    def getFloat(self, arg0: int) -> float: ...
    def getDouble(self, arg0: int) -> float: ...
    def getType(self, arg0: int) -> int: ...
    def isNull(self, arg0: int) -> bool: ...
    def deactivate(self) -> None: ...
    def requery(self) -> bool: ...
    def close(self) -> None: ...
    def isClosed(self) -> bool: ...
    def registerContentObserver(self, arg0: ContentObserver) -> None: ...
    def unregisterContentObserver(self, arg0: ContentObserver) -> None: ...
    def registerDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def setNotificationUri(self, arg0: ContentResolver, arg1: Uri) -> None: ...
    def setNotificationUris(self, arg0: ContentResolver, arg1: list) -> None: ...
    def getNotificationUri(self) -> Uri: ...
    def getNotificationUris(self) -> list: ...
    def getWantsAllOnMoveCalls(self) -> bool: ...
    def setExtras(self, arg0: Bundle) -> None: ...
    def getExtras(self) -> Bundle: ...
    def respond(self, arg0: Bundle) -> Bundle: ...
