from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.view.textclassifier.TextClassification import TextClassification
from android.view.textclassifier.TextClassificationSessionId import TextClassificationSessionId
from android.view.textclassifier.TextSelection import TextSelection

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SelectionEvent:
    ACTION_ABANDON: ClassVar[int]
    ACTION_COPY: ClassVar[int]
    ACTION_CUT: ClassVar[int]
    ACTION_DRAG: ClassVar[int]
    ACTION_OTHER: ClassVar[int]
    ACTION_OVERTYPE: ClassVar[int]
    ACTION_PASTE: ClassVar[int]
    ACTION_RESET: ClassVar[int]
    ACTION_SELECT_ALL: ClassVar[int]
    ACTION_SHARE: ClassVar[int]
    ACTION_SMART_SHARE: ClassVar[int]
    CREATOR: ClassVar[Creator]
    EVENT_AUTO_SELECTION: ClassVar[int]
    EVENT_SELECTION_MODIFIED: ClassVar[int]
    EVENT_SELECTION_STARTED: ClassVar[int]
    EVENT_SMART_SELECTION_MULTI: ClassVar[int]
    EVENT_SMART_SELECTION_SINGLE: ClassVar[int]
    INVOCATION_LINK: ClassVar[int]
    INVOCATION_MANUAL: ClassVar[int]
    INVOCATION_UNKNOWN: ClassVar[int]
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    @staticmethod
    def createSelectionStartedEvent(arg0: int, arg1: int) -> "SelectionEvent": ...
    @overload
    @staticmethod
    def createSelectionModifiedEvent(arg0: int, arg1: int) -> "SelectionEvent": ...
    @overload
    @staticmethod
    def createSelectionModifiedEvent(arg0: int, arg1: int, arg2: TextClassification) -> "SelectionEvent": ...
    @overload
    @staticmethod
    def createSelectionModifiedEvent(arg0: int, arg1: int, arg2: TextSelection) -> "SelectionEvent": ...
    @overload
    @staticmethod
    def createSelectionActionEvent(arg0: int, arg1: int, arg2: int) -> "SelectionEvent": ...
    @overload
    @staticmethod
    def createSelectionActionEvent(arg0: int, arg1: int, arg2: int, arg3: TextClassification) -> "SelectionEvent": ...
    def getEventType(self) -> int: ...
    def getEntityType(self) -> str: ...
    def getPackageName(self) -> str: ...
    def getWidgetType(self) -> str: ...
    def getWidgetVersion(self) -> str: ...
    def getInvocationMethod(self) -> int: ...
    def getResultId(self) -> str: ...
    def getEventTime(self) -> int: ...
    def getDurationSinceSessionStart(self) -> int: ...
    def getDurationSincePreviousEvent(self) -> int: ...
    def getEventIndex(self) -> int: ...
    def getSessionId(self) -> TextClassificationSessionId: ...
    def getStart(self) -> int: ...
    def getEnd(self) -> int: ...
    def getSmartStart(self) -> int: ...
    def getSmartEnd(self) -> int: ...
    @staticmethod
    def isTerminal(arg0: int) -> bool: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
