from typing import Any, ClassVar, overload
from android.view.textclassifier.TextClassificationContext import TextClassificationContext
from android.view.textclassifier.TextClassificationSessionFactory import TextClassificationSessionFactory
from android.view.textclassifier.TextClassifier import TextClassifier

class TextClassificationManager:
    def getTextClassifier(self) -> TextClassifier: ...
    def setTextClassifier(self, arg0: TextClassifier) -> None: ...
    def createTextClassificationSession(self, arg0: TextClassificationContext) -> TextClassifier: ...
    def setTextClassificationSessionFactory(self, arg0: TextClassificationSessionFactory) -> None: ...
