from typing import Any, ClassVar, overload
from android.icu.util.ULocale import ULocale
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class TextLanguage:
    CREATOR: ClassVar[Creator]
    def getId(self) -> str: ...
    def getLocaleHypothesisCount(self) -> int: ...
    def getLocale(self, arg0: int) -> ULocale: ...
    def getConfidenceScore(self, arg0: ULocale) -> float: ...
    def getExtras(self) -> Bundle: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def putLocale(self, arg0: ULocale, arg1: float) -> "Builder": ...
        def setId(self, arg0: str) -> "Builder": ...
        def setExtras(self, arg0: Bundle) -> "Builder": ...
        def build(self) -> "TextLanguage": ...

    class Request:
        CREATOR: ClassVar[Creator]
        def getText(self) -> str: ...
        def getCallingPackageName(self) -> str: ...
        def getExtras(self) -> Bundle: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setExtras(self, arg0: Bundle) -> "Builder": ...
            def build(self) -> "Request": ...
