from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from android.text.Spannable import Spannable
from android.view.View import View
from java.time.ZonedDateTime import ZonedDateTime
from java.util.function.Function import Function

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...
class EntityConfig:
    """Forward declaration for ``android.view.textclassifier.TextClassifier.EntityConfig``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.textclassifier.TextClassifier.EntityConfig')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/textclassifier/TextClassifier/EntityConfig
    """
    ...

class TextLinks:
    APPLY_STRATEGY_IGNORE: ClassVar[int]
    APPLY_STRATEGY_REPLACE: ClassVar[int]
    CREATOR: ClassVar[Creator]
    STATUS_DIFFERENT_TEXT: ClassVar[int]
    STATUS_LINKS_APPLIED: ClassVar[int]
    STATUS_NO_LINKS_APPLIED: ClassVar[int]
    STATUS_NO_LINKS_FOUND: ClassVar[int]
    STATUS_UNSUPPORTED_CHARACTER: ClassVar[int]
    def getText(self) -> str: ...
    def getLinks(self) -> list: ...
    def getExtras(self) -> Bundle: ...
    def apply(self, arg0: Spannable, arg1: int, arg2: Function) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self, arg0: str) -> None: ...
        @overload
        def addLink(self, arg0: int, arg1: int, arg2: dict) -> "Builder": ...
        @overload
        def addLink(self, arg0: int, arg1: int, arg2: dict, arg3: Bundle) -> "Builder": ...
        def clearTextLinks(self) -> "Builder": ...
        def setExtras(self, arg0: Bundle) -> "Builder": ...
        def build(self) -> "TextLinks": ...

    class Request:
        CREATOR: ClassVar[Creator]
        def getText(self) -> str: ...
        def getDefaultLocales(self) -> LocaleList: ...
        def getEntityConfig(self) -> EntityConfig: ...
        def getReferenceTime(self) -> ZonedDateTime: ...
        def getCallingPackageName(self) -> str: ...
        def getExtras(self) -> Bundle: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

        class Builder:
            def __init__(self, arg0: str) -> None: ...
            def setDefaultLocales(self, arg0: LocaleList) -> "Builder": ...
            def setEntityConfig(self, arg0: EntityConfig) -> "Builder": ...
            def setExtras(self, arg0: Bundle) -> "Builder": ...
            def setReferenceTime(self, arg0: ZonedDateTime) -> "Builder": ...
            def build(self) -> "Request": ...

    class TextLink:
        CREATOR: ClassVar[Creator]
        def getStart(self) -> int: ...
        def getEnd(self) -> int: ...
        def getEntityCount(self) -> int: ...
        def getEntity(self, arg0: int) -> str: ...
        def getConfidenceScore(self, arg0: str) -> float: ...
        def getExtras(self) -> Bundle: ...
        def toString(self) -> str: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class TextLinkSpan:
        def __init__(self, arg0: "TextLink") -> None: ...
        def onClick(self, arg0: View) -> None: ...
        def getTextLink(self) -> "TextLink": ...
