from typing import Any, ClassVar, overload

class BrowserCompatHostnameVerifier:
    def __init__(self) -> None: ...
    def verify(self, arg0: str, arg1: list[str], arg2: list[str]) -> None: ...
    def toString(self) -> str: ...
