from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress
from java.net.Socket import Socket
from java.security.KeyStore import KeyStore
from java.security.SecureRandom import SecureRandom
from org.apache.http.conn.scheme.HostNameResolver import HostNameResolver
from org.apache.http.conn.ssl.X509HostnameVerifier import X509HostnameVerifier
from org.apache.http.params.HttpParams import HttpParams

class SSLSocketFactory:
    ALLOW_ALL_HOSTNAME_VERIFIER: ClassVar[X509HostnameVerifier]
    BROWSER_COMPATIBLE_HOSTNAME_VERIFIER: ClassVar[X509HostnameVerifier]
    SSL: ClassVar[str]
    SSLV2: ClassVar[str]
    STRICT_HOSTNAME_VERIFIER: ClassVar[X509HostnameVerifier]
    TLS: ClassVar[str]
    @overload
    def __init__(self, arg0: str, arg1: KeyStore, arg2: str, arg3: KeyStore, arg4: SecureRandom, arg5: HostNameResolver) -> None: ...
    @overload
    def __init__(self, arg0: KeyStore, arg1: str, arg2: KeyStore) -> None: ...
    @overload
    def __init__(self, arg0: KeyStore, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: KeyStore) -> None: ...
    @staticmethod
    def getSocketFactory() -> "SSLSocketFactory": ...
    @overload
    def createSocket(self) -> Socket: ...
    @overload
    def createSocket(self, arg0: Socket, arg1: str, arg2: int, arg3: bool) -> Socket: ...
    def connectSocket(self, arg0: Socket, arg1: str, arg2: int, arg3: InetAddress, arg4: int, arg5: HttpParams) -> Socket: ...
    def isSecure(self, arg0: Socket) -> bool: ...
    def setHostnameVerifier(self, arg0: X509HostnameVerifier) -> None: ...
    def getHostnameVerifier(self) -> X509HostnameVerifier: ...
