from typing import Any, ClassVar, overload
from android.adservices.adselection.AdSelectionFromOutcomesConfig import AdSelectionFromOutcomesConfig
from android.adservices.common.AdSelectionSignals import AdSelectionSignals

class AddAdSelectionFromOutcomesOverrideRequest:
    def __init__(self, arg0: AdSelectionFromOutcomesConfig, arg1: str, arg2: AdSelectionSignals) -> None: ...
    def getAdSelectionFromOutcomesConfig(self) -> AdSelectionFromOutcomesConfig: ...
    def getOutcomeSelectionLogicJs(self) -> str: ...
    def getOutcomeSelectionTrustedSignals(self) -> AdSelectionSignals: ...
