from typing import Any, ClassVar, overload
from android.adservices.adselection.AdSelectionConfig import AdSelectionConfig
from android.adservices.adselection.AdSelectionFromOutcomesConfig import AdSelectionFromOutcomesConfig
from android.adservices.adselection.GetAdSelectionDataRequest import GetAdSelectionDataRequest
from android.adservices.adselection.PersistAdSelectionResultRequest import PersistAdSelectionResultRequest
from android.adservices.adselection.ReportEventRequest import ReportEventRequest
from android.adservices.adselection.ReportImpressionRequest import ReportImpressionRequest
from android.adservices.adselection.SetAppInstallAdvertisersRequest import SetAppInstallAdvertisersRequest
from android.adservices.adselection.TestAdSelectionManager import TestAdSelectionManager
from android.adservices.adselection.UpdateAdCounterHistogramRequest import UpdateAdCounterHistogramRequest
from android.content.Context import Context
from android.os.OutcomeReceiver import OutcomeReceiver
from java.util.concurrent.Executor import Executor

class AdSelectionManager:
    @staticmethod
    def get(arg0: Context) -> "AdSelectionManager": ...
    def getTestAdSelectionManager(self) -> TestAdSelectionManager: ...
    def getAdSelectionData(self, arg0: GetAdSelectionDataRequest, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def persistAdSelectionResult(self, arg0: PersistAdSelectionResultRequest, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    @overload
    def selectAds(self, arg0: AdSelectionConfig, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    @overload
    def selectAds(self, arg0: AdSelectionFromOutcomesConfig, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def reportImpression(self, arg0: ReportImpressionRequest, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def reportEvent(self, arg0: ReportEventRequest, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def setAppInstallAdvertisers(self, arg0: SetAppInstallAdvertisersRequest, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def updateAdCounterHistogram(self, arg0: UpdateAdCounterHistogramRequest, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
