from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class AdSelectionOutcome:
    NO_OUTCOME: ClassVar["AdSelectionOutcome"]
    def getRenderUri(self) -> Uri: ...
    def getAdSelectionId(self) -> int: ...
    def hasOutcome(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setAdSelectionId(self, arg0: int) -> "Builder": ...
        def setRenderUri(self, arg0: Uri) -> "Builder": ...
        def build(self) -> "AdSelectionOutcome": ...
