from typing import Any, ClassVar, overload
from android.adservices.common.AdTechIdentifier import AdTechIdentifier

class PersistAdSelectionResultRequest:
    def getAdSelectionId(self) -> int: ...
    def getAdSelectionDataId(self) -> int: ...
    def getSeller(self) -> AdTechIdentifier: ...
    def getAdSelectionResult(self) -> list[int]: ...

    class Builder:
        def __init__(self) -> None: ...
        def setAdSelectionId(self, arg0: int) -> "Builder": ...
        def setAdSelectionDataId(self, arg0: int) -> "Builder": ...
        def setSeller(self, arg0: AdTechIdentifier) -> "Builder": ...
        def setAdSelectionResult(self, arg0: list[int]) -> "Builder": ...
        def build(self) -> "PersistAdSelectionResultRequest": ...
