from typing import Any, ClassVar, overload
from android.adservices.adselection.AdSelectionConfig import AdSelectionConfig

class ReportImpressionRequest:
    @overload
    def __init__(self, arg0: int, arg1: AdSelectionConfig) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    def getAdSelectionId(self) -> int: ...
    def getAdSelectionConfig(self) -> AdSelectionConfig: ...
