from typing import Any, ClassVar, overload

class SetAppInstallAdvertisersRequest:
    def getAdvertisers(self) -> set: ...

    class Builder:
        def __init__(self) -> None: ...
        def setAdvertisers(self, arg0: set) -> "Builder": ...
        def build(self) -> "SetAppInstallAdvertisersRequest": ...
