from typing import Any, ClassVar, overload
from android.adservices.common.AdTechIdentifier import AdTechIdentifier

class UpdateAdCounterHistogramRequest:
    def getAdSelectionId(self) -> int: ...
    def getAdEventType(self) -> int: ...
    def getCallerAdTech(self) -> AdTechIdentifier: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: int, arg1: int, arg2: AdTechIdentifier) -> None: ...
        def setAdSelectionId(self, arg0: int) -> "Builder": ...
        def setAdEventType(self, arg0: int) -> "Builder": ...
        def setCallerAdTech(self, arg0: AdTechIdentifier) -> "Builder": ...
        def build(self) -> "UpdateAdCounterHistogramRequest": ...
