from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.net.Uri import Uri

class DelegatedAdminReceiver:
    def __init__(self) -> None: ...
    def onChoosePrivateKeyAlias(self, arg0: Context, arg1: Intent, arg2: int, arg3: Uri, arg4: str) -> str: ...
    def onNetworkLogsAvailable(self, arg0: Context, arg1: Intent, arg2: int, arg3: int) -> None: ...
    def onSecurityLogsAvailable(self, arg0: Context, arg1: Intent) -> None: ...
    def onReceive(self, arg0: Context, arg1: Intent) -> None: ...
