from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.content.pm.ActivityInfo import ActivityInfo
from android.content.pm.PackageManager import PackageManager
from android.content.pm.ResolveInfo import ResolveInfo
from android.graphics.drawable.Drawable import Drawable
from android.os.Parcel import Parcel
from android.util.Printer import Printer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class DeviceAdminInfo:
    CREATOR: ClassVar[Creator]
    HEADLESS_DEVICE_OWNER_MODE_AFFILIATED: ClassVar[int]
    HEADLESS_DEVICE_OWNER_MODE_SINGLE_USER: ClassVar[int]
    HEADLESS_DEVICE_OWNER_MODE_UNSUPPORTED: ClassVar[int]
    USES_ENCRYPTED_STORAGE: ClassVar[int]
    USES_POLICY_DISABLE_CAMERA: ClassVar[int]
    USES_POLICY_DISABLE_KEYGUARD_FEATURES: ClassVar[int]
    USES_POLICY_EXPIRE_PASSWORD: ClassVar[int]
    USES_POLICY_FORCE_LOCK: ClassVar[int]
    USES_POLICY_LIMIT_PASSWORD: ClassVar[int]
    USES_POLICY_RESET_PASSWORD: ClassVar[int]
    USES_POLICY_WATCH_LOGIN: ClassVar[int]
    USES_POLICY_WIPE_DATA: ClassVar[int]
    def __init__(self, arg0: Context, arg1: ResolveInfo) -> None: ...
    def getPackageName(self) -> str: ...
    def getReceiverName(self) -> str: ...
    def getActivityInfo(self) -> ActivityInfo: ...
    def getComponent(self) -> ComponentName: ...
    def loadLabel(self, arg0: PackageManager) -> str: ...
    def loadDescription(self, arg0: PackageManager) -> str: ...
    def loadIcon(self, arg0: PackageManager) -> Drawable: ...
    def isVisible(self) -> bool: ...
    def usesPolicy(self, arg0: int) -> bool: ...
    def getTagForPolicy(self, arg0: int) -> str: ...
    def supportsTransferOwnership(self) -> bool: ...
    def getHeadlessDeviceOwnerMode(self) -> int: ...
    def dump(self, arg0: Printer, arg1: str) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
