from typing import Any, ClassVar, overload
from java.time.MonthDay import MonthDay

class FreezePeriod:
    def __init__(self, arg0: MonthDay, arg1: MonthDay) -> None: ...
    def getStart(self) -> MonthDay: ...
    def getEnd(self) -> MonthDay: ...
    def toString(self) -> str: ...
