from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class PreferentialNetworkServiceConfig:
    CREATOR: ClassVar[Creator]
    PREFERENTIAL_NETWORK_ID_1: ClassVar[int]
    PREFERENTIAL_NETWORK_ID_2: ClassVar[int]
    PREFERENTIAL_NETWORK_ID_3: ClassVar[int]
    PREFERENTIAL_NETWORK_ID_4: ClassVar[int]
    PREFERENTIAL_NETWORK_ID_5: ClassVar[int]
    def isEnabled(self) -> bool: ...
    def isFallbackToDefaultConnectionAllowed(self) -> bool: ...
    def shouldBlockNonMatchingNetworks(self) -> bool: ...
    def getIncludedUids(self) -> list[int]: ...
    def getExcludedUids(self) -> list[int]: ...
    def getNetworkId(self) -> int: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setEnabled(self, arg0: bool) -> "Builder": ...
        def setFallbackToDefaultConnectionAllowed(self, arg0: bool) -> "Builder": ...
        def setShouldBlockNonMatchingNetworks(self, arg0: bool) -> "Builder": ...
        def setIncludedUids(self, arg0: list[int]) -> "Builder": ...
        def setExcludedUids(self, arg0: list[int]) -> "Builder": ...
        def build(self) -> "PreferentialNetworkServiceConfig": ...
        def setNetworkId(self, arg0: int) -> "Builder": ...
