from typing import Any, ClassVar, overload
from android.gms.ads.query.QueryInfo import QueryInfo

class QueryInfoGenerationCallback:
    def __init__(self) -> None: ...
    def onSuccess(self, arg0: QueryInfo) -> None: ...
    def onFailure(self, arg0: str) -> None: ...
