from typing import Any, ClassVar, overload

class BassBoost:
    PARAM_STRENGTH: ClassVar[int]
    PARAM_STRENGTH_SUPPORTED: ClassVar[int]
    def __init__(self, arg0: int, arg1: int) -> None: ...
    def getStrengthSupported(self) -> bool: ...
    def setStrength(self, arg0: int) -> None: ...
    def getRoundedStrength(self) -> int: ...
    def setParameterListener(self, arg0: "OnParameterChangeListener") -> None: ...
    def getProperties(self) -> "Settings": ...
    def setProperties(self, arg0: "Settings") -> None: ...

    class OnParameterChangeListener:
        def onParameterChange(self, arg0: "BassBoost", arg1: int, arg2: int, arg3: int) -> None: ...

    class Settings:
        strength: int
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: str) -> None: ...
        def toString(self) -> str: ...
