from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["DynamicsProcessing"]

class DynamicsProcessing(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/audiofx/DynamicsProcessing"
    __javaconstructor__ = [("(I)V", False), ("(IILandroid/media/audiofx/DynamicsProcessing$Config;)V", False)]
    VARIANT_FAVOR_FREQUENCY_RESOLUTION = JavaStaticField("I")
    VARIANT_FAVOR_TIME_RESOLUTION = JavaStaticField("I")
    getConfig = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Config;")
    getChannelByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Channel;")
    setChannelTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Channel;)V")
    setAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Channel;)V")
    getInputGainByChannelIndex = JavaMethod("(I)F")
    setInputGainbyChannel = JavaMethod("(IF)V")
    setInputGainAllChannelsTo = JavaMethod("(F)V")
    getPreEqByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Eq;")
    setPreEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)V")
    setPreEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
    getPreEqBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
    setPreEqBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
    setPreEqBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
    getMbcByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Mbc;")
    setMbcByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Mbc;)V")
    setMbcAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)V")
    getMbcBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$MbcBand;")
    setMbcBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
    setMbcBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
    getPostEqByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Eq;")
    setPostEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)V")
    setPostEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
    getPostEqBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
    setPostEqBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
    setPostEqBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
    getLimiterByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Limiter;")
    setLimiterByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Limiter;)V")
    setLimiterAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)V")
    getChannelCount = JavaMethod("()I")

    class BandBase(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/BandBase"
        __javaconstructor__ = [("(ZF)V", False)]
        toString = JavaMethod("()Ljava/lang/String;")
        isEnabled = JavaMethod("()Z")
        setEnabled = JavaMethod("(Z)V")
        getCutoffFrequency = JavaMethod("()F")
        setCutoffFrequency = JavaMethod("(F)V")

    class BandStage(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/BandStage"
        __javaconstructor__ = [("(ZZI)V", False)]
        getBandCount = JavaMethod("()I")
        toString = JavaMethod("()Ljava/lang/String;")

    class Channel(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/Channel"
        __javaconstructor__ = [("(FZIZIZIZ)V", False), ("(Landroid/media/audiofx/DynamicsProcessing$Channel;)V", False)]
        toString = JavaMethod("()Ljava/lang/String;")
        getInputGain = JavaMethod("()F")
        setInputGain = JavaMethod("(F)V")
        getPreEq = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Eq;")
        setPreEq = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
        getPreEqBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        setPreEqBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        getMbc = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Mbc;")
        setMbc = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)V")
        getMbcBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$MbcBand;")
        setMbcBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
        getPostEq = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Eq;")
        setPostEq = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
        getPostEqBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        setPostEqBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        getLimiter = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Limiter;")
        setLimiter = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)V")

    class Config(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/Config"
        toString = JavaMethod("()Ljava/lang/String;")
        getVariant = JavaMethod("()I")
        getPreferredFrameDuration = JavaMethod("()F")
        isPreEqInUse = JavaMethod("()Z")
        getPreEqBandCount = JavaMethod("()I")
        isMbcInUse = JavaMethod("()Z")
        getMbcBandCount = JavaMethod("()I")
        isPostEqInUse = JavaMethod("()Z")
        getPostEqBandCount = JavaMethod("()I")
        isLimiterInUse = JavaMethod("()Z")
        getChannelByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Channel;")
        setChannelTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Channel;)V")
        setAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Channel;)V")
        getInputGainByChannelIndex = JavaMethod("(I)F")
        setInputGainByChannelIndex = JavaMethod("(IF)V")
        setInputGainAllChannelsTo = JavaMethod("(F)V")
        getPreEqByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Eq;")
        setPreEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)V")
        setPreEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
        getPreEqBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        setPreEqBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        setPreEqBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        getMbcByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Mbc;")
        setMbcByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Mbc;)V")
        setMbcAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)V")
        getMbcBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$MbcBand;")
        setMbcBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
        setMbcBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
        getPostEqByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Eq;")
        setPostEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)V")
        setPostEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
        getPostEqBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        setPostEqBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        setPostEqBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        getLimiterByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Limiter;")
        setLimiterByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Limiter;)V")
        setLimiterAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)V")

        class Builder(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/media/audiofx/DynamicsProcessing/Config/Builder"
            __javaconstructor__ = [("(IIZIZIZIZ)V", False)]
            setPreferredFrameDuration = JavaMethod("(F)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setInputGainByChannelIndex = JavaMethod("(IF)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setInputGainAllChannelsTo = JavaMethod("(F)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setChannelTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Channel;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Channel;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPreEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPreEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setMbcByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Mbc;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setMbcAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPostEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPostEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setLimiterByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Limiter;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setLimiterAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            build = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Config;")

    class Eq(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/Eq"
        __javaconstructor__ = [("(ZZI)V", False), ("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V", False)]
        toString = JavaMethod("()Ljava/lang/String;")
        setBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        getBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$EqBand;")

    class EqBand(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/EqBand"
        __javaconstructor__ = [("(ZFF)V", False), ("(Landroid/media/audiofx/DynamicsProcessing$EqBand;)V", False)]
        toString = JavaMethod("()Ljava/lang/String;")
        getGain = JavaMethod("()F")
        setGain = JavaMethod("(F)V")

    class Limiter(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/Limiter"
        __javaconstructor__ = [("(ZZIFFFFF)V", False), ("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)V", False)]
        toString = JavaMethod("()Ljava/lang/String;")
        getLinkGroup = JavaMethod("()I")
        setLinkGroup = JavaMethod("(I)V")
        getAttackTime = JavaMethod("()F")
        setAttackTime = JavaMethod("(F)V")
        getReleaseTime = JavaMethod("()F")
        setReleaseTime = JavaMethod("(F)V")
        getRatio = JavaMethod("()F")
        setRatio = JavaMethod("(F)V")
        getThreshold = JavaMethod("()F")
        setThreshold = JavaMethod("(F)V")
        getPostGain = JavaMethod("()F")
        setPostGain = JavaMethod("(F)V")

    class Mbc(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/Mbc"
        __javaconstructor__ = [("(ZZI)V", False), ("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)V", False)]
        toString = JavaMethod("()Ljava/lang/String;")
        setBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
        getBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$MbcBand;")

    class MbcBand(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/MbcBand"
        __javaconstructor__ = [("(ZFFFFFFFFFF)V", False), ("(Landroid/media/audiofx/DynamicsProcessing$MbcBand;)V", False)]
        toString = JavaMethod("()Ljava/lang/String;")
        getAttackTime = JavaMethod("()F")
        setAttackTime = JavaMethod("(F)V")
        getReleaseTime = JavaMethod("()F")
        setReleaseTime = JavaMethod("(F)V")
        getRatio = JavaMethod("()F")
        setRatio = JavaMethod("(F)V")
        getThreshold = JavaMethod("()F")
        setThreshold = JavaMethod("(F)V")
        getKneeWidth = JavaMethod("()F")
        setKneeWidth = JavaMethod("(F)V")
        getNoiseGateThreshold = JavaMethod("()F")
        setNoiseGateThreshold = JavaMethod("(F)V")
        getExpanderRatio = JavaMethod("()F")
        setExpanderRatio = JavaMethod("(F)V")
        getPreGain = JavaMethod("()F")
        setPreGain = JavaMethod("(F)V")
        getPostGain = JavaMethod("()F")
        setPostGain = JavaMethod("(F)V")

    class Stage(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing/Stage"
        __javaconstructor__ = [("(ZZ)V", False)]
        isEnabled = JavaMethod("()Z")
        setEnabled = JavaMethod("(Z)V")
        isInUse = JavaMethod("()Z")
        toString = JavaMethod("()Ljava/lang/String;")