from typing import Any, ClassVar, overload

class DynamicsProcessing:
    VARIANT_FAVOR_FREQUENCY_RESOLUTION: ClassVar[int]
    VARIANT_FAVOR_TIME_RESOLUTION: ClassVar[int]
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: "Config") -> None: ...
    def getConfig(self) -> "Config": ...
    def getChannelByChannelIndex(self, arg0: int) -> "Channel": ...
    def setChannelTo(self, arg0: int, arg1: "Channel") -> None: ...
    def setAllChannelsTo(self, arg0: "Channel") -> None: ...
    def getInputGainByChannelIndex(self, arg0: int) -> float: ...
    def setInputGainbyChannel(self, arg0: int, arg1: float) -> None: ...
    def setInputGainAllChannelsTo(self, arg0: float) -> None: ...
    def getPreEqByChannelIndex(self, arg0: int) -> "Eq": ...
    def setPreEqByChannelIndex(self, arg0: int, arg1: "Eq") -> None: ...
    def setPreEqAllChannelsTo(self, arg0: "Eq") -> None: ...
    def getPreEqBandByChannelIndex(self, arg0: int, arg1: int) -> "EqBand": ...
    def setPreEqBandByChannelIndex(self, arg0: int, arg1: int, arg2: "EqBand") -> None: ...
    def setPreEqBandAllChannelsTo(self, arg0: int, arg1: "EqBand") -> None: ...
    def getMbcByChannelIndex(self, arg0: int) -> "Mbc": ...
    def setMbcByChannelIndex(self, arg0: int, arg1: "Mbc") -> None: ...
    def setMbcAllChannelsTo(self, arg0: "Mbc") -> None: ...
    def getMbcBandByChannelIndex(self, arg0: int, arg1: int) -> "MbcBand": ...
    def setMbcBandByChannelIndex(self, arg0: int, arg1: int, arg2: "MbcBand") -> None: ...
    def setMbcBandAllChannelsTo(self, arg0: int, arg1: "MbcBand") -> None: ...
    def getPostEqByChannelIndex(self, arg0: int) -> "Eq": ...
    def setPostEqByChannelIndex(self, arg0: int, arg1: "Eq") -> None: ...
    def setPostEqAllChannelsTo(self, arg0: "Eq") -> None: ...
    def getPostEqBandByChannelIndex(self, arg0: int, arg1: int) -> "EqBand": ...
    def setPostEqBandByChannelIndex(self, arg0: int, arg1: int, arg2: "EqBand") -> None: ...
    def setPostEqBandAllChannelsTo(self, arg0: int, arg1: "EqBand") -> None: ...
    def getLimiterByChannelIndex(self, arg0: int) -> "Limiter": ...
    def setLimiterByChannelIndex(self, arg0: int, arg1: "Limiter") -> None: ...
    def setLimiterAllChannelsTo(self, arg0: "Limiter") -> None: ...
    def getChannelCount(self) -> int: ...

    class BandBase:
        def __init__(self, arg0: bool, arg1: float) -> None: ...
        def toString(self) -> str: ...
        def isEnabled(self) -> bool: ...
        def setEnabled(self, arg0: bool) -> None: ...
        def getCutoffFrequency(self) -> float: ...
        def setCutoffFrequency(self, arg0: float) -> None: ...

    class BandStage:
        def __init__(self, arg0: bool, arg1: bool, arg2: int) -> None: ...
        def getBandCount(self) -> int: ...
        def toString(self) -> str: ...

    class Channel:
        @overload
        def __init__(self, arg0: float, arg1: bool, arg2: int, arg3: bool, arg4: int, arg5: bool, arg6: int, arg7: bool) -> None: ...
        @overload
        def __init__(self, arg0: "Channel") -> None: ...
        def toString(self) -> str: ...
        def getInputGain(self) -> float: ...
        def setInputGain(self, arg0: float) -> None: ...
        def getPreEq(self) -> "Eq": ...
        def setPreEq(self, arg0: "Eq") -> None: ...
        def getPreEqBand(self, arg0: int) -> "EqBand": ...
        def setPreEqBand(self, arg0: int, arg1: "EqBand") -> None: ...
        def getMbc(self) -> "Mbc": ...
        def setMbc(self, arg0: "Mbc") -> None: ...
        def getMbcBand(self, arg0: int) -> "MbcBand": ...
        def setMbcBand(self, arg0: int, arg1: "MbcBand") -> None: ...
        def getPostEq(self) -> "Eq": ...
        def setPostEq(self, arg0: "Eq") -> None: ...
        def getPostEqBand(self, arg0: int) -> "EqBand": ...
        def setPostEqBand(self, arg0: int, arg1: "EqBand") -> None: ...
        def getLimiter(self) -> "Limiter": ...
        def setLimiter(self, arg0: "Limiter") -> None: ...

    class Config:
        def toString(self) -> str: ...
        def getVariant(self) -> int: ...
        def getPreferredFrameDuration(self) -> float: ...
        def isPreEqInUse(self) -> bool: ...
        def getPreEqBandCount(self) -> int: ...
        def isMbcInUse(self) -> bool: ...
        def getMbcBandCount(self) -> int: ...
        def isPostEqInUse(self) -> bool: ...
        def getPostEqBandCount(self) -> int: ...
        def isLimiterInUse(self) -> bool: ...
        def getChannelByChannelIndex(self, arg0: int) -> "Channel": ...
        def setChannelTo(self, arg0: int, arg1: "Channel") -> None: ...
        def setAllChannelsTo(self, arg0: "Channel") -> None: ...
        def getInputGainByChannelIndex(self, arg0: int) -> float: ...
        def setInputGainByChannelIndex(self, arg0: int, arg1: float) -> None: ...
        def setInputGainAllChannelsTo(self, arg0: float) -> None: ...
        def getPreEqByChannelIndex(self, arg0: int) -> "Eq": ...
        def setPreEqByChannelIndex(self, arg0: int, arg1: "Eq") -> None: ...
        def setPreEqAllChannelsTo(self, arg0: "Eq") -> None: ...
        def getPreEqBandByChannelIndex(self, arg0: int, arg1: int) -> "EqBand": ...
        def setPreEqBandByChannelIndex(self, arg0: int, arg1: int, arg2: "EqBand") -> None: ...
        def setPreEqBandAllChannelsTo(self, arg0: int, arg1: "EqBand") -> None: ...
        def getMbcByChannelIndex(self, arg0: int) -> "Mbc": ...
        def setMbcByChannelIndex(self, arg0: int, arg1: "Mbc") -> None: ...
        def setMbcAllChannelsTo(self, arg0: "Mbc") -> None: ...
        def getMbcBandByChannelIndex(self, arg0: int, arg1: int) -> "MbcBand": ...
        def setMbcBandByChannelIndex(self, arg0: int, arg1: int, arg2: "MbcBand") -> None: ...
        def setMbcBandAllChannelsTo(self, arg0: int, arg1: "MbcBand") -> None: ...
        def getPostEqByChannelIndex(self, arg0: int) -> "Eq": ...
        def setPostEqByChannelIndex(self, arg0: int, arg1: "Eq") -> None: ...
        def setPostEqAllChannelsTo(self, arg0: "Eq") -> None: ...
        def getPostEqBandByChannelIndex(self, arg0: int, arg1: int) -> "EqBand": ...
        def setPostEqBandByChannelIndex(self, arg0: int, arg1: int, arg2: "EqBand") -> None: ...
        def setPostEqBandAllChannelsTo(self, arg0: int, arg1: "EqBand") -> None: ...
        def getLimiterByChannelIndex(self, arg0: int) -> "Limiter": ...
        def setLimiterByChannelIndex(self, arg0: int, arg1: "Limiter") -> None: ...
        def setLimiterAllChannelsTo(self, arg0: "Limiter") -> None: ...

        class Builder:
            def __init__(self, arg0: int, arg1: int, arg2: bool, arg3: int, arg4: bool, arg5: int, arg6: bool, arg7: int, arg8: bool) -> None: ...
            def setPreferredFrameDuration(self, arg0: float) -> "Builder": ...
            def setInputGainByChannelIndex(self, arg0: int, arg1: float) -> "Builder": ...
            def setInputGainAllChannelsTo(self, arg0: float) -> "Builder": ...
            def setChannelTo(self, arg0: int, arg1: "Channel") -> "Builder": ...
            def setAllChannelsTo(self, arg0: "Channel") -> "Builder": ...
            def setPreEqByChannelIndex(self, arg0: int, arg1: "Eq") -> "Builder": ...
            def setPreEqAllChannelsTo(self, arg0: "Eq") -> "Builder": ...
            def setMbcByChannelIndex(self, arg0: int, arg1: "Mbc") -> "Builder": ...
            def setMbcAllChannelsTo(self, arg0: "Mbc") -> "Builder": ...
            def setPostEqByChannelIndex(self, arg0: int, arg1: "Eq") -> "Builder": ...
            def setPostEqAllChannelsTo(self, arg0: "Eq") -> "Builder": ...
            def setLimiterByChannelIndex(self, arg0: int, arg1: "Limiter") -> "Builder": ...
            def setLimiterAllChannelsTo(self, arg0: "Limiter") -> "Builder": ...
            def build(self) -> "Config": ...

    class Eq:
        @overload
        def __init__(self, arg0: bool, arg1: bool, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: "Eq") -> None: ...
        def toString(self) -> str: ...
        def setBand(self, arg0: int, arg1: "EqBand") -> None: ...
        def getBand(self, arg0: int) -> "EqBand": ...

    class EqBand:
        @overload
        def __init__(self, arg0: bool, arg1: float, arg2: float) -> None: ...
        @overload
        def __init__(self, arg0: "EqBand") -> None: ...
        def toString(self) -> str: ...
        def getGain(self) -> float: ...
        def setGain(self, arg0: float) -> None: ...

    class Limiter:
        @overload
        def __init__(self, arg0: bool, arg1: bool, arg2: int, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float) -> None: ...
        @overload
        def __init__(self, arg0: "Limiter") -> None: ...
        def toString(self) -> str: ...
        def getLinkGroup(self) -> int: ...
        def setLinkGroup(self, arg0: int) -> None: ...
        def getAttackTime(self) -> float: ...
        def setAttackTime(self, arg0: float) -> None: ...
        def getReleaseTime(self) -> float: ...
        def setReleaseTime(self, arg0: float) -> None: ...
        def getRatio(self) -> float: ...
        def setRatio(self, arg0: float) -> None: ...
        def getThreshold(self) -> float: ...
        def setThreshold(self, arg0: float) -> None: ...
        def getPostGain(self) -> float: ...
        def setPostGain(self, arg0: float) -> None: ...

    class Mbc:
        @overload
        def __init__(self, arg0: bool, arg1: bool, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: "Mbc") -> None: ...
        def toString(self) -> str: ...
        def setBand(self, arg0: int, arg1: "MbcBand") -> None: ...
        def getBand(self, arg0: int) -> "MbcBand": ...

    class MbcBand:
        @overload
        def __init__(self, arg0: bool, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: float, arg10: float) -> None: ...
        @overload
        def __init__(self, arg0: "MbcBand") -> None: ...
        def toString(self) -> str: ...
        def getAttackTime(self) -> float: ...
        def setAttackTime(self, arg0: float) -> None: ...
        def getReleaseTime(self) -> float: ...
        def setReleaseTime(self, arg0: float) -> None: ...
        def getRatio(self) -> float: ...
        def setRatio(self, arg0: float) -> None: ...
        def getThreshold(self) -> float: ...
        def setThreshold(self, arg0: float) -> None: ...
        def getKneeWidth(self) -> float: ...
        def setKneeWidth(self, arg0: float) -> None: ...
        def getNoiseGateThreshold(self) -> float: ...
        def setNoiseGateThreshold(self, arg0: float) -> None: ...
        def getExpanderRatio(self) -> float: ...
        def setExpanderRatio(self, arg0: float) -> None: ...
        def getPreGain(self) -> float: ...
        def setPreGain(self, arg0: float) -> None: ...
        def getPostGain(self) -> float: ...
        def setPostGain(self, arg0: float) -> None: ...

    class Stage:
        def __init__(self, arg0: bool, arg1: bool) -> None: ...
        def isEnabled(self) -> bool: ...
        def setEnabled(self, arg0: bool) -> None: ...
        def isInUse(self) -> bool: ...
        def toString(self) -> str: ...
