from typing import Any, ClassVar, overload
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.content.res.XmlResourceParser import XmlResourceParser
from java.io.InputStream import InputStream

class AssetManager:
    ACCESS_BUFFER: ClassVar[int]
    ACCESS_RANDOM: ClassVar[int]
    ACCESS_STREAMING: ClassVar[int]
    ACCESS_UNKNOWN: ClassVar[int]
    def close(self) -> None: ...
    @overload
    def open(self, arg0: str) -> InputStream: ...
    @overload
    def open(self, arg0: str, arg1: int) -> InputStream: ...
    def openFd(self, arg0: str) -> AssetFileDescriptor: ...
    def list(self, arg0: str) -> list[str]: ...
    @overload
    def openNonAssetFd(self, arg0: str) -> AssetFileDescriptor: ...
    @overload
    def openNonAssetFd(self, arg0: int, arg1: str) -> AssetFileDescriptor: ...
    @overload
    def openXmlResourceParser(self, arg0: str) -> XmlResourceParser: ...
    @overload
    def openXmlResourceParser(self, arg0: int, arg1: str) -> XmlResourceParser: ...
    def finalize(self) -> None: ...
    def getLocales(self) -> list[str]: ...

    class AssetInputStream:
        @overload
        def read(self) -> int: ...
        @overload
        def read(self, arg0: list[int]) -> int: ...
        @overload
        def read(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
        def skip(self, arg0: int) -> int: ...
        def available(self) -> int: ...
        def markSupported(self) -> bool: ...
        def mark(self, arg0: int) -> None: ...
        def reset(self) -> None: ...
        def close(self) -> None: ...
        def finalize(self) -> None: ...
