from typing import Any, ClassVar, overload

class FontScaleConverter:
    def convertSpToDp(self, arg0: float) -> float: ...
    def convertDpToSp(self, arg0: float) -> float: ...
    @staticmethod
    def isNonLinearFontScalingActive(arg0: float) -> bool: ...
    @staticmethod
    def forScale(arg0: float) -> "FontScaleConverter": ...
