from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["Resources"]

class Resources(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/content/res/Resources"
    __javaconstructor__ = [("(Landroid/content/res/AssetManager;Landroid/util/DisplayMetrics;Landroid/content/res/Configuration;)V", False)]
    ID_NULL = JavaStaticField("I")
    getSystem = JavaStaticMethod("()Landroid/content/res/Resources;")
    getText = JavaMultipleMethod([("(I)Ljava/lang/CharSequence;", False, False), ("(ILjava/lang/CharSequence;)Ljava/lang/CharSequence;", False, False)])
    getFont = JavaMethod("(I)Landroid/graphics/Typeface;")
    getQuantityText = JavaMethod("(II)Ljava/lang/CharSequence;")
    getString = JavaMultipleMethod([("(I)Ljava/lang/String;", False, False), ("(I[Ljava/lang/Object;)Ljava/lang/String;", False, True)])
    getQuantityString = JavaMultipleMethod([("(II[Ljava/lang/Object;)Ljava/lang/String;", False, True), ("(II)Ljava/lang/String;", False, False)])
    getTextArray = JavaMethod("(I)[Ljava/lang/CharSequence;")
    getStringArray = JavaMethod("(I)[Ljava/lang/String;")
    getIntArray = JavaMethod("(I)[I")
    obtainTypedArray = JavaMethod("(I)Landroid/content/res/TypedArray;")
    getDimension = JavaMethod("(I)F")
    getDimensionPixelOffset = JavaMethod("(I)I")
    getDimensionPixelSize = JavaMethod("(I)I")
    getFraction = JavaMethod("(III)F")
    getDrawable = JavaMultipleMethod([("(I)Landroid/graphics/drawable/Drawable;", False, False), ("(ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;", False, False)])
    getDrawableForDensity = JavaMultipleMethod([("(II)Landroid/graphics/drawable/Drawable;", False, False), ("(IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;", False, False)])
    getMovie = JavaMethod("(I)Landroid/graphics/Movie;")
    getColor = JavaMultipleMethod([("(I)I", False, False), ("(ILandroid/content/res/Resources$Theme;)I", False, False)])
    getColorStateList = JavaMultipleMethod([("(I)Landroid/content/res/ColorStateList;", False, False), ("(ILandroid/content/res/Resources$Theme;)Landroid/content/res/ColorStateList;", False, False)])
    getBoolean = JavaMethod("(I)Z")
    getInteger = JavaMethod("(I)I")
    getFloat = JavaMethod("(I)F")
    getLayout = JavaMethod("(I)Landroid/content/res/XmlResourceParser;")
    getAnimation = JavaMethod("(I)Landroid/content/res/XmlResourceParser;")
    getXml = JavaMethod("(I)Landroid/content/res/XmlResourceParser;")
    openRawResource = JavaMultipleMethod([("(I)Ljava/io/InputStream;", False, False), ("(ILandroid/util/TypedValue;)Ljava/io/InputStream;", False, False)])
    openRawResourceFd = JavaMethod("(I)Landroid/content/res/AssetFileDescriptor;")
    getValue = JavaMultipleMethod([("(ILandroid/util/TypedValue;Z)V", False, False), ("(Ljava/lang/String;Landroid/util/TypedValue;Z)V", False, False)])
    getValueForDensity = JavaMethod("(IILandroid/util/TypedValue;Z)V")
    getAttributeSetSourceResId = JavaStaticMethod("(Landroid/util/AttributeSet;)I")
    newTheme = JavaMethod("()Landroid/content/res/Resources$Theme;")
    obtainAttributes = JavaMethod("(Landroid/util/AttributeSet;[I)Landroid/content/res/TypedArray;")
    updateConfiguration = JavaMethod("(Landroid/content/res/Configuration;Landroid/util/DisplayMetrics;)V")
    getDisplayMetrics = JavaMethod("()Landroid/util/DisplayMetrics;")
    getConfiguration = JavaMethod("()Landroid/content/res/Configuration;")
    getIdentifier = JavaMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I")
    getResourceName = JavaMethod("(I)Ljava/lang/String;")
    getResourcePackageName = JavaMethod("(I)Ljava/lang/String;")
    getResourceTypeName = JavaMethod("(I)Ljava/lang/String;")
    getResourceEntryName = JavaMethod("(I)Ljava/lang/String;")
    parseBundleExtras = JavaMethod("(Landroid/content/res/XmlResourceParser;Landroid/os/Bundle;)V")
    parseBundleExtra = JavaMethod("(Ljava/lang/String;Landroid/util/AttributeSet;Landroid/os/Bundle;)V")
    getAssets = JavaMethod("()Landroid/content/res/AssetManager;")
    flushLayoutCache = JavaMethod("()V")
    finishPreloading = JavaMethod("()V")
    addLoaders = JavaMethod("([Landroid/content/res/loader/ResourcesLoader;)V", varargs=True)
    removeLoaders = JavaMethod("([Landroid/content/res/loader/ResourcesLoader;)V", varargs=True)
    registerResourcePaths = JavaStaticMethod("(Ljava/lang/String;Landroid/content/pm/ApplicationInfo;)V")

    class NotFoundException(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/content/res/Resources/NotFoundException"
        __javaconstructor__ = [("()V", False), ("(Ljava/lang/String;)V", False), ("(Ljava/lang/String;Ljava/lang/Exception;)V", False)]

    class Theme(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/content/res/Resources/Theme"
        applyStyle = JavaMethod("(IZ)V")
        setTo = JavaMethod("(Landroid/content/res/Resources$Theme;)V")
        obtainStyledAttributes = JavaMultipleMethod([("([I)Landroid/content/res/TypedArray;", False, False), ("(I[I)Landroid/content/res/TypedArray;", False, False), ("(Landroid/util/AttributeSet;[III)Landroid/content/res/TypedArray;", False, False)])
        resolveAttribute = JavaMethod("(ILandroid/util/TypedValue;Z)Z")
        getResources = JavaMethod("()Landroid/content/res/Resources;")
        getDrawable = JavaMethod("(I)Landroid/graphics/drawable/Drawable;")
        getChangingConfigurations = JavaMethod("()I")
        dump = JavaMethod("(ILjava/lang/String;Ljava/lang/String;)V")
        rebase = JavaMethod("()V")
        getExplicitStyle = JavaMethod("(Landroid/util/AttributeSet;)I")
        getAttributeResolutionStack = JavaMethod("(III)[I")
        hashCode = JavaMethod("()I")
        equals = JavaMethod("(Ljava/lang/Object;)Z")
        toString = JavaMethod("()Ljava/lang/String;")