from typing import Any, ClassVar, overload
from android.content.res.ColorStateList import ColorStateList
from android.content.res.Resources import Resources
from android.graphics.Typeface import Typeface
from android.graphics.drawable.Drawable import Drawable
from android.util.TypedValue import TypedValue

class TypedArray:
    def length(self) -> int: ...
    def getIndexCount(self) -> int: ...
    def getIndex(self, arg0: int) -> int: ...
    def getResources(self) -> Resources: ...
    def getText(self, arg0: int) -> str: ...
    def getString(self, arg0: int) -> str: ...
    def getNonResourceString(self, arg0: int) -> str: ...
    def getBoolean(self, arg0: int, arg1: bool) -> bool: ...
    def getInt(self, arg0: int, arg1: int) -> int: ...
    def getFloat(self, arg0: int, arg1: float) -> float: ...
    def getColor(self, arg0: int, arg1: int) -> int: ...
    def getColorStateList(self, arg0: int) -> ColorStateList: ...
    def getInteger(self, arg0: int, arg1: int) -> int: ...
    def getDimension(self, arg0: int, arg1: float) -> float: ...
    def getDimensionPixelOffset(self, arg0: int, arg1: int) -> int: ...
    def getDimensionPixelSize(self, arg0: int, arg1: int) -> int: ...
    @overload
    def getLayoutDimension(self, arg0: int, arg1: str) -> int: ...
    @overload
    def getLayoutDimension(self, arg0: int, arg1: int) -> int: ...
    def getFraction(self, arg0: int, arg1: int, arg2: int, arg3: float) -> float: ...
    def getResourceId(self, arg0: int, arg1: int) -> int: ...
    def getDrawable(self, arg0: int) -> Drawable: ...
    def getFont(self, arg0: int) -> Typeface: ...
    def getTextArray(self, arg0: int) -> list[str]: ...
    def getValue(self, arg0: int, arg1: TypedValue) -> bool: ...
    def getType(self, arg0: int) -> int: ...
    def getSourceResourceId(self, arg0: int, arg1: int) -> int: ...
    def hasValue(self, arg0: int) -> bool: ...
    def hasValueOrEmpty(self, arg0: int) -> bool: ...
    def peekValue(self, arg0: int) -> TypedValue: ...
    def getPositionDescription(self) -> str: ...
    def recycle(self) -> None: ...
    def close(self) -> None: ...
    def getChangingConfigurations(self) -> int: ...
    def toString(self) -> str: ...
