from typing import Any, ClassVar, overload
from java.nio.file.attribute.DosFileAttributes import DosFileAttributes

class DosFileAttributeView:
    def name(self) -> str: ...
    def readAttributes(self) -> DosFileAttributes: ...
    def setReadOnly(self, arg0: bool) -> None: ...
    def setHidden(self, arg0: bool) -> None: ...
    def setSystem(self, arg0: bool) -> None: ...
    def setArchive(self, arg0: bool) -> None: ...
