from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.util.concurrent.TimeUnit import TimeUnit

class FileTime:
    @overload
    @staticmethod
    def from_(arg0: int, arg1: TimeUnit) -> "FileTime": ...
    @overload
    @staticmethod
    def from_(arg0: Instant) -> "FileTime": ...
    @staticmethod
    def fromMillis(arg0: int) -> "FileTime": ...
    def to(self, arg0: TimeUnit) -> int: ...
    def toMillis(self) -> int: ...
    def toInstant(self) -> Instant: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def compareTo(self, arg0: "FileTime") -> int: ...
    def toString(self) -> str: ...
