from typing import Any, ClassVar, overload
from java.nio.file.attribute.UserPrincipal import UserPrincipal

class FileOwnerAttributeView:
    def name(self) -> str: ...
    def getOwner(self) -> UserPrincipal: ...
    def setOwner(self, arg0: UserPrincipal) -> None: ...
