from typing import Any, ClassVar, overload
from java.nio.file.attribute.GroupPrincipal import GroupPrincipal
from java.nio.file.attribute.UserPrincipal import UserPrincipal

class UserPrincipalLookupService:
    def __init__(self) -> None: ...
    def lookupPrincipalByName(self, arg0: str) -> UserPrincipal: ...
    def lookupPrincipalByGroupName(self, arg0: str) -> GroupPrincipal: ...
