from typing import Any, ClassVar, overload
from android.hardware.lights.Light import Light
from android.hardware.lights.LightState import LightState

class LightsRequest:
    def getLights(self) -> list: ...
    def getLightStates(self) -> list: ...
    def getLightsAndStates(self) -> dict: ...

    class Builder:
        def __init__(self) -> None: ...
        def addLight(self, arg0: Light, arg1: LightState) -> "Builder": ...
        def clearLight(self, arg0: Light) -> "Builder": ...
        def build(self) -> "LightsRequest": ...
