from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.nio.channels.CompletionHandler import CompletionHandler
from java.nio.channels.FileLock import FileLock
from java.nio.file.OpenOption import OpenOption
from java.nio.file.Path import Path
from java.nio.file.attribute.FileAttribute import FileAttribute
from java.util.concurrent.ExecutorService import ExecutorService
from java.util.concurrent.Future import Future

class AsynchronousFileChannel:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def open(arg0: Path, arg1: set, arg2: ExecutorService, *arg3: FileAttribute) -> "AsynchronousFileChannel": ...
    @overload
    @staticmethod
    def open(arg0: Path, *arg1: OpenOption) -> "AsynchronousFileChannel": ...
    def size(self) -> int: ...
    def truncate(self, arg0: int) -> "AsynchronousFileChannel": ...
    def force(self, arg0: bool) -> None: ...
    @overload
    def lock(self, arg0: int, arg1: int, arg2: bool, arg3: Any, arg4: CompletionHandler) -> None: ...
    @overload
    def lock(self, arg0: Any, arg1: CompletionHandler) -> None: ...
    @overload
    def lock(self, arg0: int, arg1: int, arg2: bool) -> Future: ...
    @overload
    def lock(self) -> Future: ...
    @overload
    def tryLock(self, arg0: int, arg1: int, arg2: bool) -> FileLock: ...
    @overload
    def tryLock(self) -> FileLock: ...
    @overload
    def read(self, arg0: ByteBuffer, arg1: int, arg2: Any, arg3: CompletionHandler) -> None: ...
    @overload
    def read(self, arg0: ByteBuffer, arg1: int) -> Future: ...
    @overload
    def write(self, arg0: ByteBuffer, arg1: int, arg2: Any, arg3: CompletionHandler) -> None: ...
    @overload
    def write(self, arg0: ByteBuffer, arg1: int) -> Future: ...
