from typing import Any, ClassVar, overload
from java.net.SocketAddress import SocketAddress
from java.net.SocketOption import SocketOption
from java.nio.ByteBuffer import ByteBuffer
from java.nio.channels.AsynchronousChannelGroup import AsynchronousChannelGroup
from java.nio.channels.CompletionHandler import CompletionHandler
from java.nio.channels.spi.AsynchronousChannelProvider import AsynchronousChannelProvider
from java.util.concurrent.Future import Future
from java.util.concurrent.TimeUnit import TimeUnit

class AsynchronousSocketChannel:
    def __init__(self, arg0: AsynchronousChannelProvider) -> None: ...
    def provider(self) -> AsynchronousChannelProvider: ...
    @overload
    @staticmethod
    def open(arg0: AsynchronousChannelGroup) -> "AsynchronousSocketChannel": ...
    @overload
    @staticmethod
    def open() -> "AsynchronousSocketChannel": ...
    def bind(self, arg0: SocketAddress) -> "AsynchronousSocketChannel": ...
    def setOption(self, arg0: SocketOption, arg1: Any) -> "AsynchronousSocketChannel": ...
    def shutdownInput(self) -> "AsynchronousSocketChannel": ...
    def shutdownOutput(self) -> "AsynchronousSocketChannel": ...
    def getRemoteAddress(self) -> SocketAddress: ...
    @overload
    def connect(self, arg0: SocketAddress, arg1: Any, arg2: CompletionHandler) -> None: ...
    @overload
    def connect(self, arg0: SocketAddress) -> Future: ...
    @overload
    def read(self, arg0: ByteBuffer, arg1: int, arg2: TimeUnit, arg3: Any, arg4: CompletionHandler) -> None: ...
    @overload
    def read(self, arg0: ByteBuffer, arg1: Any, arg2: CompletionHandler) -> None: ...
    @overload
    def read(self, arg0: ByteBuffer) -> Future: ...
    @overload
    def read(self, arg0: list[ByteBuffer], arg1: int, arg2: int, arg3: int, arg4: TimeUnit, arg5: Any, arg6: CompletionHandler) -> None: ...
    @overload
    def write(self, arg0: ByteBuffer, arg1: int, arg2: TimeUnit, arg3: Any, arg4: CompletionHandler) -> None: ...
    @overload
    def write(self, arg0: ByteBuffer, arg1: Any, arg2: CompletionHandler) -> None: ...
    @overload
    def write(self, arg0: ByteBuffer) -> Future: ...
    @overload
    def write(self, arg0: list[ByteBuffer], arg1: int, arg2: int, arg3: int, arg4: TimeUnit, arg5: Any, arg6: CompletionHandler) -> None: ...
    def getLocalAddress(self) -> SocketAddress: ...
