from typing import Any, ClassVar, overload
from java.net.DatagramSocket import DatagramSocket
from java.net.ProtocolFamily import ProtocolFamily
from java.net.SocketAddress import SocketAddress
from java.net.SocketOption import SocketOption
from java.nio.ByteBuffer import ByteBuffer
from java.nio.channels.spi.SelectorProvider import SelectorProvider

class DatagramChannel:
    def __init__(self, arg0: SelectorProvider) -> None: ...
    @overload
    @staticmethod
    def open() -> "DatagramChannel": ...
    @overload
    @staticmethod
    def open(arg0: ProtocolFamily) -> "DatagramChannel": ...
    def validOps(self) -> int: ...
    def bind(self, arg0: SocketAddress) -> "DatagramChannel": ...
    def setOption(self, arg0: SocketOption, arg1: Any) -> "DatagramChannel": ...
    def socket(self) -> DatagramSocket: ...
    def isConnected(self) -> bool: ...
    def connect(self, arg0: SocketAddress) -> "DatagramChannel": ...
    def disconnect(self) -> "DatagramChannel": ...
    def getRemoteAddress(self) -> SocketAddress: ...
    def receive(self, arg0: ByteBuffer) -> SocketAddress: ...
    def send(self, arg0: ByteBuffer, arg1: SocketAddress) -> int: ...
    @overload
    def read(self, arg0: ByteBuffer) -> int: ...
    @overload
    def read(self, arg0: list[ByteBuffer], arg1: int, arg2: int) -> int: ...
    @overload
    def read(self, arg0: list[ByteBuffer]) -> int: ...
    @overload
    def write(self, arg0: ByteBuffer) -> int: ...
    @overload
    def write(self, arg0: list[ByteBuffer], arg1: int, arg2: int) -> int: ...
    @overload
    def write(self, arg0: list[ByteBuffer]) -> int: ...
    def getLocalAddress(self) -> SocketAddress: ...
