from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress
from java.net.NetworkInterface import NetworkInterface
from java.nio.channels.MulticastChannel import MulticastChannel

class MembershipKey:
    def __init__(self) -> None: ...
    def isValid(self) -> bool: ...
    def drop(self) -> None: ...
    def block(self, arg0: InetAddress) -> "MembershipKey": ...
    def unblock(self, arg0: InetAddress) -> "MembershipKey": ...
    def channel(self) -> MulticastChannel: ...
    def group(self) -> InetAddress: ...
    def networkInterface(self) -> NetworkInterface: ...
    def sourceAddress(self) -> InetAddress: ...
