from typing import Any, ClassVar, overload
from java.net.SocketAddress import SocketAddress
from java.net.SocketOption import SocketOption

class NetworkChannel:
    def bind(self, arg0: SocketAddress) -> "NetworkChannel": ...
    def getLocalAddress(self) -> SocketAddress: ...
    def setOption(self, arg0: SocketOption, arg1: Any) -> "NetworkChannel": ...
    def getOption(self, arg0: SocketOption) -> Any: ...
    def supportedOptions(self) -> set: ...
