from typing import Any, ClassVar, overload
from java.nio.channels.spi.SelectorProvider import SelectorProvider

class Pipe:
    def __init__(self) -> None: ...
    def source(self) -> "SourceChannel": ...
    def sink(self) -> "SinkChannel": ...
    @staticmethod
    def open() -> "Pipe": ...

    class SinkChannel:
        def __init__(self, arg0: SelectorProvider) -> None: ...
        def validOps(self) -> int: ...

    class SourceChannel:
        def __init__(self, arg0: SelectorProvider) -> None: ...
        def validOps(self) -> int: ...
