from typing import Any, ClassVar, overload
from java.nio.channels.SelectionKey import SelectionKey
from java.nio.channels.Selector import Selector
from java.nio.channels.spi.SelectorProvider import SelectorProvider

class SelectableChannel:
    def __init__(self) -> None: ...
    def provider(self) -> SelectorProvider: ...
    def validOps(self) -> int: ...
    def isRegistered(self) -> bool: ...
    def keyFor(self, arg0: Selector) -> SelectionKey: ...
    @overload
    def register(self, arg0: Selector, arg1: int, arg2: Any) -> SelectionKey: ...
    @overload
    def register(self, arg0: Selector, arg1: int) -> SelectionKey: ...
    def configureBlocking(self, arg0: bool) -> "SelectableChannel": ...
    def isBlocking(self) -> bool: ...
    def blockingLock(self) -> Any: ...
