from typing import Any, ClassVar, overload
from java.net.ServerSocket import ServerSocket
from java.net.SocketAddress import SocketAddress
from java.net.SocketOption import SocketOption
from java.nio.channels.SocketChannel import SocketChannel
from java.nio.channels.spi.SelectorProvider import SelectorProvider

class ServerSocketChannel:
    def __init__(self, arg0: SelectorProvider) -> None: ...
    @staticmethod
    def open() -> "ServerSocketChannel": ...
    def validOps(self) -> int: ...
    @overload
    def bind(self, arg0: SocketAddress) -> "ServerSocketChannel": ...
    @overload
    def bind(self, arg0: SocketAddress, arg1: int) -> "ServerSocketChannel": ...
    def setOption(self, arg0: SocketOption, arg1: Any) -> "ServerSocketChannel": ...
    def socket(self) -> ServerSocket: ...
    def accept(self) -> SocketChannel: ...
    def getLocalAddress(self) -> SocketAddress: ...
