from typing import Any, ClassVar, overload
from java.net.Socket import Socket
from java.net.SocketAddress import SocketAddress
from java.net.SocketOption import SocketOption
from java.nio.ByteBuffer import ByteBuffer
from java.nio.channels.spi.SelectorProvider import SelectorProvider

class SocketChannel:
    def __init__(self, arg0: SelectorProvider) -> None: ...
    @overload
    @staticmethod
    def open() -> "SocketChannel": ...
    @overload
    @staticmethod
    def open(arg0: SocketAddress) -> "SocketChannel": ...
    def validOps(self) -> int: ...
    def bind(self, arg0: SocketAddress) -> "SocketChannel": ...
    def setOption(self, arg0: SocketOption, arg1: Any) -> "SocketChannel": ...
    def shutdownInput(self) -> "SocketChannel": ...
    def shutdownOutput(self) -> "SocketChannel": ...
    def socket(self) -> Socket: ...
    def isConnected(self) -> bool: ...
    def isConnectionPending(self) -> bool: ...
    def connect(self, arg0: SocketAddress) -> bool: ...
    def finishConnect(self) -> bool: ...
    def getRemoteAddress(self) -> SocketAddress: ...
    @overload
    def read(self, arg0: ByteBuffer) -> int: ...
    @overload
    def read(self, arg0: list[ByteBuffer], arg1: int, arg2: int) -> int: ...
    @overload
    def read(self, arg0: list[ByteBuffer]) -> int: ...
    @overload
    def write(self, arg0: ByteBuffer) -> int: ...
    @overload
    def write(self, arg0: list[ByteBuffer], arg1: int, arg2: int) -> int: ...
    @overload
    def write(self, arg0: list[ByteBuffer]) -> int: ...
    def getLocalAddress(self) -> SocketAddress: ...
