from typing import Any, ClassVar, overload
from android.accounts.Account import Account
from android.accounts.AccountAuthenticatorResponse import AccountAuthenticatorResponse
from android.content.Context import Context
from android.os.Bundle import Bundle
from android.os.IBinder import IBinder

class AbstractAccountAuthenticator:
    KEY_CUSTOM_TOKEN_EXPIRY: ClassVar[str]
    def __init__(self, arg0: Context) -> None: ...
    def getIBinder(self) -> IBinder: ...
    def editProperties(self, arg0: AccountAuthenticatorResponse, arg1: str) -> Bundle: ...
    def addAccount(self, arg0: AccountAuthenticatorResponse, arg1: str, arg2: str, arg3: list[str], arg4: Bundle) -> Bundle: ...
    def confirmCredentials(self, arg0: AccountAuthenticatorResponse, arg1: Account, arg2: Bundle) -> Bundle: ...
    def getAuthToken(self, arg0: AccountAuthenticatorResponse, arg1: Account, arg2: str, arg3: Bundle) -> Bundle: ...
    def getAuthTokenLabel(self, arg0: str) -> str: ...
    def updateCredentials(self, arg0: AccountAuthenticatorResponse, arg1: Account, arg2: str, arg3: Bundle) -> Bundle: ...
    def hasFeatures(self, arg0: AccountAuthenticatorResponse, arg1: Account, arg2: list[str]) -> Bundle: ...
    def getAccountRemovalAllowed(self, arg0: AccountAuthenticatorResponse, arg1: Account) -> Bundle: ...
    def getAccountCredentialsForCloning(self, arg0: AccountAuthenticatorResponse, arg1: Account) -> Bundle: ...
    def addAccountFromCredentials(self, arg0: AccountAuthenticatorResponse, arg1: Account, arg2: Bundle) -> Bundle: ...
    def startAddAccountSession(self, arg0: AccountAuthenticatorResponse, arg1: str, arg2: str, arg3: list[str], arg4: Bundle) -> Bundle: ...
    def startUpdateCredentialsSession(self, arg0: AccountAuthenticatorResponse, arg1: Account, arg2: str, arg3: Bundle) -> Bundle: ...
    def finishSession(self, arg0: AccountAuthenticatorResponse, arg1: str, arg2: Bundle) -> Bundle: ...
    def isCredentialsUpdateSuggested(self, arg0: AccountAuthenticatorResponse, arg1: Account, arg2: str) -> Bundle: ...
