from typing import Any, ClassVar, overload

class FloatAction:
    @overload
    def __init__(self, arg0: str, arg1: float) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: float, arg2: str) -> None: ...
    def getNewValue(self) -> float: ...
    def getActionType(self) -> int: ...
