from typing import Any, ClassVar, overload
from org.w3c.dom.DOMConfiguration import DOMConfiguration
from org.w3c.dom.Node import Node
from org.w3c.dom.ls.LSOutput import LSOutput

class LSSerializer:
    def getDomConfig(self) -> DOMConfiguration: ...
    def getNewLine(self) -> str: ...
    def setNewLine(self, arg0: str) -> None: ...
    def write(self, arg0: Node, arg1: LSOutput) -> bool: ...
    def writeToURI(self, arg0: Node, arg1: str) -> bool: ...
    def writeToString(self, arg0: Node) -> str: ...
