from typing import Any, ClassVar, overload
from android.os.Handler import Handler

class AccessibilityButtonController:
    def isAccessibilityButtonAvailable(self) -> bool: ...
    @overload
    def registerAccessibilityButtonCallback(self, arg0: "AccessibilityButtonCallback") -> None: ...
    @overload
    def registerAccessibilityButtonCallback(self, arg0: "AccessibilityButtonCallback", arg1: Handler) -> None: ...
    def unregisterAccessibilityButtonCallback(self, arg0: "AccessibilityButtonCallback") -> None: ...

    class AccessibilityButtonCallback:
        def __init__(self) -> None: ...
        def onClicked(self, arg0: "AccessibilityButtonController") -> None: ...
        def onAvailabilityChanged(self, arg0: "AccessibilityButtonController", arg1: bool) -> None: ...
