from typing import Any, ClassVar, overload
from android.accessibilityservice.AccessibilityButtonController import AccessibilityButtonController
from android.accessibilityservice.AccessibilityGestureEvent import AccessibilityGestureEvent
from android.accessibilityservice.AccessibilityServiceInfo import AccessibilityServiceInfo
from android.accessibilityservice.BrailleDisplayController import BrailleDisplayController
from android.accessibilityservice.FingerprintGestureController import FingerprintGestureController
from android.accessibilityservice.GestureDescription import GestureDescription
from android.accessibilityservice.InputMethod import InputMethod
from android.accessibilityservice.MagnificationConfig import MagnificationConfig
from android.accessibilityservice.TouchInteractionController import TouchInteractionController
from android.content.Context import Context
from android.content.Intent import Intent
from android.graphics.ColorSpace import ColorSpace
from android.graphics.Region import Region
from android.hardware.HardwareBuffer import HardwareBuffer
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.os.IBinder import IBinder
from android.util.SparseArray import SparseArray
from android.view.Display import Display
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.SurfaceControl import SurfaceControl
from android.view.accessibility.AccessibilityEvent import AccessibilityEvent
from android.view.accessibility.AccessibilityNodeInfo import AccessibilityNodeInfo
from java.util.concurrent.Executor import Executor

class AccessibilityService:
    ERROR_TAKE_SCREENSHOT_INTERNAL_ERROR: ClassVar[int]
    ERROR_TAKE_SCREENSHOT_INTERVAL_TIME_SHORT: ClassVar[int]
    ERROR_TAKE_SCREENSHOT_INVALID_DISPLAY: ClassVar[int]
    ERROR_TAKE_SCREENSHOT_INVALID_WINDOW: ClassVar[int]
    ERROR_TAKE_SCREENSHOT_NO_ACCESSIBILITY_ACCESS: ClassVar[int]
    ERROR_TAKE_SCREENSHOT_SECURE_WINDOW: ClassVar[int]
    GESTURE_2_FINGER_DOUBLE_TAP: ClassVar[int]
    GESTURE_2_FINGER_DOUBLE_TAP_AND_HOLD: ClassVar[int]
    GESTURE_2_FINGER_SINGLE_TAP: ClassVar[int]
    GESTURE_2_FINGER_SWIPE_DOWN: ClassVar[int]
    GESTURE_2_FINGER_SWIPE_LEFT: ClassVar[int]
    GESTURE_2_FINGER_SWIPE_RIGHT: ClassVar[int]
    GESTURE_2_FINGER_SWIPE_UP: ClassVar[int]
    GESTURE_2_FINGER_TRIPLE_TAP: ClassVar[int]
    GESTURE_2_FINGER_TRIPLE_TAP_AND_HOLD: ClassVar[int]
    GESTURE_3_FINGER_DOUBLE_TAP: ClassVar[int]
    GESTURE_3_FINGER_DOUBLE_TAP_AND_HOLD: ClassVar[int]
    GESTURE_3_FINGER_SINGLE_TAP: ClassVar[int]
    GESTURE_3_FINGER_SINGLE_TAP_AND_HOLD: ClassVar[int]
    GESTURE_3_FINGER_SWIPE_DOWN: ClassVar[int]
    GESTURE_3_FINGER_SWIPE_LEFT: ClassVar[int]
    GESTURE_3_FINGER_SWIPE_RIGHT: ClassVar[int]
    GESTURE_3_FINGER_SWIPE_UP: ClassVar[int]
    GESTURE_3_FINGER_TRIPLE_TAP: ClassVar[int]
    GESTURE_3_FINGER_TRIPLE_TAP_AND_HOLD: ClassVar[int]
    GESTURE_4_FINGER_DOUBLE_TAP: ClassVar[int]
    GESTURE_4_FINGER_DOUBLE_TAP_AND_HOLD: ClassVar[int]
    GESTURE_4_FINGER_SINGLE_TAP: ClassVar[int]
    GESTURE_4_FINGER_SWIPE_DOWN: ClassVar[int]
    GESTURE_4_FINGER_SWIPE_LEFT: ClassVar[int]
    GESTURE_4_FINGER_SWIPE_RIGHT: ClassVar[int]
    GESTURE_4_FINGER_SWIPE_UP: ClassVar[int]
    GESTURE_4_FINGER_TRIPLE_TAP: ClassVar[int]
    GESTURE_DOUBLE_TAP: ClassVar[int]
    GESTURE_DOUBLE_TAP_AND_HOLD: ClassVar[int]
    GESTURE_SWIPE_DOWN: ClassVar[int]
    GESTURE_SWIPE_DOWN_AND_LEFT: ClassVar[int]
    GESTURE_SWIPE_DOWN_AND_RIGHT: ClassVar[int]
    GESTURE_SWIPE_DOWN_AND_UP: ClassVar[int]
    GESTURE_SWIPE_LEFT: ClassVar[int]
    GESTURE_SWIPE_LEFT_AND_DOWN: ClassVar[int]
    GESTURE_SWIPE_LEFT_AND_RIGHT: ClassVar[int]
    GESTURE_SWIPE_LEFT_AND_UP: ClassVar[int]
    GESTURE_SWIPE_RIGHT: ClassVar[int]
    GESTURE_SWIPE_RIGHT_AND_DOWN: ClassVar[int]
    GESTURE_SWIPE_RIGHT_AND_LEFT: ClassVar[int]
    GESTURE_SWIPE_RIGHT_AND_UP: ClassVar[int]
    GESTURE_SWIPE_UP: ClassVar[int]
    GESTURE_SWIPE_UP_AND_DOWN: ClassVar[int]
    GESTURE_SWIPE_UP_AND_LEFT: ClassVar[int]
    GESTURE_SWIPE_UP_AND_RIGHT: ClassVar[int]
    GESTURE_UNKNOWN: ClassVar[int]
    GLOBAL_ACTION_ACCESSIBILITY_ALL_APPS: ClassVar[int]
    GLOBAL_ACTION_ACCESSIBILITY_BUTTON: ClassVar[int]
    GLOBAL_ACTION_ACCESSIBILITY_BUTTON_CHOOSER: ClassVar[int]
    GLOBAL_ACTION_ACCESSIBILITY_SHORTCUT: ClassVar[int]
    GLOBAL_ACTION_BACK: ClassVar[int]
    GLOBAL_ACTION_DISMISS_NOTIFICATION_SHADE: ClassVar[int]
    GLOBAL_ACTION_DPAD_CENTER: ClassVar[int]
    GLOBAL_ACTION_DPAD_DOWN: ClassVar[int]
    GLOBAL_ACTION_DPAD_LEFT: ClassVar[int]
    GLOBAL_ACTION_DPAD_RIGHT: ClassVar[int]
    GLOBAL_ACTION_DPAD_UP: ClassVar[int]
    GLOBAL_ACTION_HOME: ClassVar[int]
    GLOBAL_ACTION_KEYCODE_HEADSETHOOK: ClassVar[int]
    GLOBAL_ACTION_LOCK_SCREEN: ClassVar[int]
    GLOBAL_ACTION_NOTIFICATIONS: ClassVar[int]
    GLOBAL_ACTION_POWER_DIALOG: ClassVar[int]
    GLOBAL_ACTION_QUICK_SETTINGS: ClassVar[int]
    GLOBAL_ACTION_RECENTS: ClassVar[int]
    GLOBAL_ACTION_TAKE_SCREENSHOT: ClassVar[int]
    GLOBAL_ACTION_TOGGLE_SPLIT_SCREEN: ClassVar[int]
    SERVICE_INTERFACE: ClassVar[str]
    SERVICE_META_DATA: ClassVar[str]
    SHOW_MODE_AUTO: ClassVar[int]
    SHOW_MODE_HIDDEN: ClassVar[int]
    SHOW_MODE_IGNORE_HARD_KEYBOARD: ClassVar[int]
    def __init__(self) -> None: ...
    def onAccessibilityEvent(self, arg0: AccessibilityEvent) -> None: ...
    def onInterrupt(self) -> None: ...
    def onServiceConnected(self) -> None: ...
    @overload
    def onGesture(self, arg0: int) -> bool: ...
    @overload
    def onGesture(self, arg0: AccessibilityGestureEvent) -> bool: ...
    def onKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def onMotionEvent(self, arg0: MotionEvent) -> None: ...
    def getWindows(self) -> list: ...
    def getWindowsOnAllDisplays(self) -> SparseArray: ...
    @overload
    def getRootInActiveWindow(self) -> AccessibilityNodeInfo: ...
    @overload
    def getRootInActiveWindow(self, arg0: int) -> AccessibilityNodeInfo: ...
    def disableSelf(self) -> None: ...
    def createDisplayContext(self, arg0: Display) -> Context: ...
    @overload
    def createWindowContext(self, arg0: int, arg1: Bundle) -> Context: ...
    @overload
    def createWindowContext(self, arg0: Display, arg1: int, arg2: Bundle) -> Context: ...
    def getMagnificationController(self) -> "MagnificationController": ...
    def getFingerprintGestureController(self) -> FingerprintGestureController: ...
    def dispatchGesture(self, arg0: GestureDescription, arg1: "GestureResultCallback", arg2: Handler) -> bool: ...
    def getSoftKeyboardController(self) -> "SoftKeyboardController": ...
    def onCreateInputMethod(self) -> InputMethod: ...
    def getInputMethod(self) -> InputMethod: ...
    @overload
    def getAccessibilityButtonController(self) -> AccessibilityButtonController: ...
    @overload
    def getAccessibilityButtonController(self, arg0: int) -> AccessibilityButtonController: ...
    def setCacheEnabled(self, arg0: bool) -> bool: ...
    def clearCachedSubtree(self, arg0: AccessibilityNodeInfo) -> bool: ...
    def clearCache(self) -> bool: ...
    def isNodeInCache(self, arg0: AccessibilityNodeInfo) -> bool: ...
    def isCacheEnabled(self) -> bool: ...
    def onSystemActionsChanged(self) -> None: ...
    def getSystemActions(self) -> list: ...
    def performGlobalAction(self, arg0: int) -> bool: ...
    def findFocus(self, arg0: int) -> AccessibilityNodeInfo: ...
    def getServiceInfo(self) -> AccessibilityServiceInfo: ...
    def setServiceInfo(self, arg0: AccessibilityServiceInfo) -> None: ...
    def getSystemService(self, arg0: str) -> Any: ...
    def takeScreenshot(self, arg0: int, arg1: Executor, arg2: "TakeScreenshotCallback") -> None: ...
    def takeScreenshotOfWindow(self, arg0: int, arg1: Executor, arg2: "TakeScreenshotCallback") -> None: ...
    def setAccessibilityFocusAppearance(self, arg0: int, arg1: int) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def setGestureDetectionPassthroughRegion(self, arg0: int, arg1: Region) -> None: ...
    def setTouchExplorationPassthroughRegion(self, arg0: int, arg1: Region) -> None: ...
    def setAnimationScale(self, arg0: float) -> None: ...
    def getTouchInteractionController(self, arg0: int) -> TouchInteractionController: ...
    def attachAccessibilityOverlayToDisplay(self, arg0: int, arg1: SurfaceControl) -> None: ...
    def attachAccessibilityOverlayToWindow(self, arg0: int, arg1: SurfaceControl) -> None: ...
    def getBrailleDisplayController(self) -> BrailleDisplayController: ...

    class GestureResultCallback:
        def __init__(self) -> None: ...
        def onCompleted(self, arg0: GestureDescription) -> None: ...
        def onCancelled(self, arg0: GestureDescription) -> None: ...

    class MagnificationController:
        @overload
        def addListener(self, arg0: "OnMagnificationChangedListener") -> None: ...
        @overload
        def addListener(self, arg0: "OnMagnificationChangedListener", arg1: Handler) -> None: ...
        def removeListener(self, arg0: "OnMagnificationChangedListener") -> bool: ...
        def getMagnificationConfig(self) -> MagnificationConfig: ...
        def getScale(self) -> float: ...
        def getCenterX(self) -> float: ...
        def getCenterY(self) -> float: ...
        def getMagnificationRegion(self) -> Region: ...
        def getCurrentMagnificationRegion(self) -> Region: ...
        def reset(self, arg0: bool) -> bool: ...
        def resetCurrentMagnification(self, arg0: bool) -> bool: ...
        def setMagnificationConfig(self, arg0: MagnificationConfig, arg1: bool) -> bool: ...
        def setScale(self, arg0: float, arg1: bool) -> bool: ...
        def setCenter(self, arg0: float, arg1: float, arg2: bool) -> bool: ...

        class OnMagnificationChangedListener:
            @overload
            def onMagnificationChanged(self, arg0: "MagnificationController", arg1: Region, arg2: float, arg3: float, arg4: float) -> None: ...
            @overload
            def onMagnificationChanged(self, arg0: "MagnificationController", arg1: Region, arg2: MagnificationConfig) -> None: ...

    class ScreenshotResult:
        def getColorSpace(self) -> ColorSpace: ...
        def getHardwareBuffer(self) -> HardwareBuffer: ...
        def getTimestamp(self) -> int: ...

    class SoftKeyboardController:
        ENABLE_IME_FAIL_BY_ADMIN: ClassVar[int]
        ENABLE_IME_FAIL_UNKNOWN: ClassVar[int]
        ENABLE_IME_SUCCESS: ClassVar[int]
        @overload
        def addOnShowModeChangedListener(self, arg0: "OnShowModeChangedListener") -> None: ...
        @overload
        def addOnShowModeChangedListener(self, arg0: "OnShowModeChangedListener", arg1: Handler) -> None: ...
        def removeOnShowModeChangedListener(self, arg0: "OnShowModeChangedListener") -> bool: ...
        def getShowMode(self) -> int: ...
        def setShowMode(self, arg0: int) -> bool: ...
        def switchToInputMethod(self, arg0: str) -> bool: ...
        def setInputMethodEnabled(self, arg0: str, arg1: bool) -> int: ...

        class OnShowModeChangedListener:
            def onShowModeChanged(self, arg0: "SoftKeyboardController", arg1: int) -> None: ...

    class TakeScreenshotCallback:
        def onSuccess(self, arg0: "ScreenshotResult") -> None: ...
        def onFailure(self, arg0: int) -> None: ...
