from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from android.hardware.usb.UsbDevice import UsbDevice
from java.util.concurrent.Executor import Executor

class BrailleDisplayController:
    @overload
    def connect(self, arg0: BluetoothDevice, arg1: "BrailleDisplayCallback") -> None: ...
    @overload
    def connect(self, arg0: BluetoothDevice, arg1: Executor, arg2: "BrailleDisplayCallback") -> None: ...
    @overload
    def connect(self, arg0: UsbDevice, arg1: "BrailleDisplayCallback") -> None: ...
    @overload
    def connect(self, arg0: UsbDevice, arg1: Executor, arg2: "BrailleDisplayCallback") -> None: ...
    def isConnected(self) -> bool: ...
    def write(self, arg0: list[int]) -> None: ...
    def disconnect(self) -> None: ...

    class BrailleDisplayCallback:
        FLAG_ERROR_BRAILLE_DISPLAY_NOT_FOUND: ClassVar[int]
        FLAG_ERROR_CANNOT_ACCESS: ClassVar[int]
        def onConnected(self, arg0: list[int]) -> None: ...
        def onConnectionFailed(self, arg0: int) -> None: ...
        def onInput(self, arg0: list[int]) -> None: ...
        def onDisconnected(self) -> None: ...
