from typing import Any, ClassVar, overload
from android.graphics.Path import Path

class GestureDescription:
    @staticmethod
    def getMaxStrokeCount() -> int: ...
    @staticmethod
    def getMaxGestureDuration() -> int: ...
    def getStrokeCount(self) -> int: ...
    def getStroke(self, arg0: int) -> "StrokeDescription": ...
    def getDisplayId(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def addStroke(self, arg0: "StrokeDescription") -> "Builder": ...
        def setDisplayId(self, arg0: int) -> "Builder": ...
        def build(self) -> "GestureDescription": ...

    class StrokeDescription:
        @overload
        def __init__(self, arg0: Path, arg1: int, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: Path, arg1: int, arg2: int, arg3: bool) -> None: ...
        def getPath(self) -> Path: ...
        def getStartTime(self) -> int: ...
        def getDuration(self) -> int: ...
        def continueStroke(self, arg0: Path, arg1: int, arg2: int, arg3: bool) -> "StrokeDescription": ...
        def willContinue(self) -> bool: ...
