from typing import Any, ClassVar, overload
from android.accessibilityservice.AccessibilityService import AccessibilityService
from android.view.KeyEvent import KeyEvent
from android.view.inputmethod.EditorInfo import EditorInfo
from android.view.inputmethod.SurroundingText import SurroundingText
from android.view.inputmethod.TextAttribute import TextAttribute

class InputMethod:
    def __init__(self, arg0: AccessibilityService) -> None: ...
    def getCurrentInputConnection(self) -> "AccessibilityInputConnection": ...
    def getCurrentInputStarted(self) -> bool: ...
    def getCurrentInputEditorInfo(self) -> EditorInfo: ...
    def onStartInput(self, arg0: EditorInfo, arg1: bool) -> None: ...
    def onFinishInput(self) -> None: ...
    def onUpdateSelection(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...

    class AccessibilityInputConnection:
        def commitText(self, arg0: str, arg1: int, arg2: TextAttribute) -> None: ...
        def setSelection(self, arg0: int, arg1: int) -> None: ...
        def getSurroundingText(self, arg0: int, arg1: int, arg2: int) -> SurroundingText: ...
        def deleteSurroundingText(self, arg0: int, arg1: int) -> None: ...
        def sendKeyEvent(self, arg0: KeyEvent) -> None: ...
        def performEditorAction(self, arg0: int) -> None: ...
        def performContextMenuAction(self, arg0: int) -> None: ...
        def getCursorCapsMode(self, arg0: int) -> int: ...
        def clearMetaKeyStates(self, arg0: int) -> None: ...
