from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class MagnificationConfig:
    CREATOR: ClassVar[Creator]
    MAGNIFICATION_MODE_DEFAULT: ClassVar[int]
    MAGNIFICATION_MODE_FULLSCREEN: ClassVar[int]
    MAGNIFICATION_MODE_WINDOW: ClassVar[int]
    def getMode(self) -> int: ...
    def isActivated(self) -> bool: ...
    def getScale(self) -> float: ...
    def getCenterX(self) -> float: ...
    def getCenterY(self) -> float: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setMode(self, arg0: int) -> "Builder": ...
        def setActivated(self, arg0: bool) -> "Builder": ...
        def setScale(self, arg0: float) -> "Builder": ...
        def setCenterX(self, arg0: float) -> "Builder": ...
        def setCenterY(self, arg0: float) -> "Builder": ...
        def build(self) -> "MagnificationConfig": ...
