from typing import Any, ClassVar, overload
from android.view.MotionEvent import MotionEvent
from java.util.concurrent.Executor import Executor

class TouchInteractionController:
    STATE_CLEAR: ClassVar[int]
    STATE_DELEGATING: ClassVar[int]
    STATE_DRAGGING: ClassVar[int]
    STATE_TOUCH_EXPLORING: ClassVar[int]
    STATE_TOUCH_INTERACTING: ClassVar[int]
    def registerCallback(self, arg0: Executor, arg1: "Callback") -> None: ...
    def unregisterCallback(self, arg0: "Callback") -> bool: ...
    def unregisterAllCallbacks(self) -> None: ...
    def requestTouchExploration(self) -> None: ...
    def requestDragging(self, arg0: int) -> None: ...
    def requestDelegating(self) -> None: ...
    def performClick(self) -> None: ...
    def performLongClickAndStartDrag(self) -> None: ...
    def getMaxPointerCount(self) -> int: ...
    def getDisplayId(self) -> int: ...
    def getState(self) -> int: ...
    @staticmethod
    def stateToString(arg0: int) -> str: ...

    class Callback:
        def onMotionEvent(self, arg0: MotionEvent) -> None: ...
        def onStateChanged(self, arg0: int) -> None: ...
