from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AdvertiseSettings:
    ADVERTISE_MODE_BALANCED: ClassVar[int]
    ADVERTISE_MODE_LOW_LATENCY: ClassVar[int]
    ADVERTISE_MODE_LOW_POWER: ClassVar[int]
    ADVERTISE_TX_POWER_HIGH: ClassVar[int]
    ADVERTISE_TX_POWER_LOW: ClassVar[int]
    ADVERTISE_TX_POWER_MEDIUM: ClassVar[int]
    ADVERTISE_TX_POWER_ULTRA_LOW: ClassVar[int]
    CREATOR: ClassVar[Creator]
    def getMode(self) -> int: ...
    def getTxPowerLevel(self) -> int: ...
    def isConnectable(self) -> bool: ...
    def isDiscoverable(self) -> bool: ...
    def getTimeout(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setAdvertiseMode(self, arg0: int) -> "Builder": ...
        def setTxPowerLevel(self, arg0: int) -> "Builder": ...
        def setConnectable(self, arg0: bool) -> "Builder": ...
        def setDiscoverable(self, arg0: bool) -> "Builder": ...
        def setTimeout(self, arg0: int) -> "Builder": ...
        def build(self) -> "AdvertiseSettings": ...
