from typing import Any, ClassVar, overload
from android.bluetooth.le.ScanResult import ScanResult
from android.os.Parcel import Parcel
from android.os.ParcelUuid import ParcelUuid

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ScanFilter:
    CREATOR: ClassVar[Creator]
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getDeviceName(self) -> str: ...
    def getServiceUuid(self) -> ParcelUuid: ...
    def getServiceUuidMask(self) -> ParcelUuid: ...
    def getServiceSolicitationUuid(self) -> ParcelUuid: ...
    def getServiceSolicitationUuidMask(self) -> ParcelUuid: ...
    def getDeviceAddress(self) -> str: ...
    def getServiceData(self) -> list[int]: ...
    def getServiceDataMask(self) -> list[int]: ...
    def getServiceDataUuid(self) -> ParcelUuid: ...
    def getManufacturerId(self) -> int: ...
    def getManufacturerData(self) -> list[int]: ...
    def getManufacturerDataMask(self) -> list[int]: ...
    def getAdvertisingDataType(self) -> int: ...
    def getAdvertisingData(self) -> list[int]: ...
    def getAdvertisingDataMask(self) -> list[int]: ...
    def matches(self, arg0: ScanResult) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setDeviceName(self, arg0: str) -> "Builder": ...
        def setDeviceAddress(self, arg0: str) -> "Builder": ...
        @overload
        def setServiceUuid(self, arg0: ParcelUuid) -> "Builder": ...
        @overload
        def setServiceUuid(self, arg0: ParcelUuid, arg1: ParcelUuid) -> "Builder": ...
        @overload
        def setServiceSolicitationUuid(self, arg0: ParcelUuid) -> "Builder": ...
        @overload
        def setServiceSolicitationUuid(self, arg0: ParcelUuid, arg1: ParcelUuid) -> "Builder": ...
        @overload
        def setServiceData(self, arg0: ParcelUuid, arg1: list[int]) -> "Builder": ...
        @overload
        def setServiceData(self, arg0: ParcelUuid, arg1: list[int], arg2: list[int]) -> "Builder": ...
        @overload
        def setManufacturerData(self, arg0: int, arg1: list[int]) -> "Builder": ...
        @overload
        def setManufacturerData(self, arg0: int, arg1: list[int], arg2: list[int]) -> "Builder": ...
        def setAdvertisingDataTypeWithData(self, arg0: int, arg1: list[int], arg2: list[int]) -> "Builder": ...
        def setAdvertisingDataType(self, arg0: int) -> "Builder": ...
        def build(self) -> "ScanFilter": ...
