from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.os.ParcelUuid import ParcelUuid
from java.util.regex.Pattern import Pattern

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class BluetoothDeviceFilter:
    CREATOR: ClassVar[Creator]
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setNamePattern(self, arg0: Pattern) -> "Builder": ...
        def setAddress(self, arg0: str) -> "Builder": ...
        def addServiceUuid(self, arg0: ParcelUuid, arg1: ParcelUuid) -> "Builder": ...
        def build(self) -> "BluetoothDeviceFilter": ...
