from typing import Any, ClassVar, overload
from android.companion.AssociationInfo import AssociationInfo
from android.content.Intent import Intent
from android.os.IBinder import IBinder
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream

class CompanionDeviceService:
    SERVICE_INTERFACE: ClassVar[str]
    def __init__(self) -> None: ...
    @overload
    def onDeviceAppeared(self, arg0: str) -> None: ...
    @overload
    def onDeviceAppeared(self, arg0: AssociationInfo) -> None: ...
    @overload
    def onDeviceDisappeared(self, arg0: str) -> None: ...
    @overload
    def onDeviceDisappeared(self, arg0: AssociationInfo) -> None: ...
    def attachSystemDataTransport(self, arg0: int, arg1: InputStream, arg2: OutputStream) -> None: ...
    def detachSystemDataTransport(self, arg0: int) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
