from typing import Any, ClassVar, overload

class AbstractInterruptibleChannel:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def implCloseChannel(self) -> None: ...
    def isOpen(self) -> bool: ...
    def begin(self) -> None: ...
    def end(self, arg0: bool) -> None: ...
