from typing import Any, ClassVar, overload
from java.nio.channels.SelectableChannel import SelectableChannel
from java.nio.channels.SelectionKey import SelectionKey
from java.nio.channels.Selector import Selector
from java.nio.channels.spi.SelectorProvider import SelectorProvider

class AbstractSelectableChannel:
    def __init__(self, arg0: SelectorProvider) -> None: ...
    def provider(self) -> SelectorProvider: ...
    def isRegistered(self) -> bool: ...
    def keyFor(self, arg0: Selector) -> SelectionKey: ...
    def register(self, arg0: Selector, arg1: int, arg2: Any) -> SelectionKey: ...
    def implCloseChannel(self) -> None: ...
    def implCloseSelectableChannel(self) -> None: ...
    def isBlocking(self) -> bool: ...
    def blockingLock(self) -> Any: ...
    def configureBlocking(self, arg0: bool) -> SelectableChannel: ...
    def implConfigureBlocking(self, arg0: bool) -> None: ...
