from typing import Any, ClassVar, overload
from java.nio.channels.AsynchronousChannelGroup import AsynchronousChannelGroup
from java.nio.channels.AsynchronousServerSocketChannel import AsynchronousServerSocketChannel
from java.nio.channels.AsynchronousSocketChannel import AsynchronousSocketChannel
from java.util.concurrent.ExecutorService import ExecutorService
from java.util.concurrent.ThreadFactory import ThreadFactory

class AsynchronousChannelProvider:
    def __init__(self) -> None: ...
    @staticmethod
    def provider() -> "AsynchronousChannelProvider": ...
    @overload
    def openAsynchronousChannelGroup(self, arg0: int, arg1: ThreadFactory) -> AsynchronousChannelGroup: ...
    @overload
    def openAsynchronousChannelGroup(self, arg0: ExecutorService, arg1: int) -> AsynchronousChannelGroup: ...
    def openAsynchronousServerSocketChannel(self, arg0: AsynchronousChannelGroup) -> AsynchronousServerSocketChannel: ...
    def openAsynchronousSocketChannel(self, arg0: AsynchronousChannelGroup) -> AsynchronousSocketChannel: ...
