from typing import Any, ClassVar, overload
from java.net.ProtocolFamily import ProtocolFamily
from java.nio.channels.Channel import Channel
from java.nio.channels.DatagramChannel import DatagramChannel
from java.nio.channels.Pipe import Pipe
from java.nio.channels.ServerSocketChannel import ServerSocketChannel
from java.nio.channels.SocketChannel import SocketChannel
from java.nio.channels.spi.AbstractSelector import AbstractSelector

class SelectorProvider:
    def __init__(self) -> None: ...
    @staticmethod
    def provider() -> "SelectorProvider": ...
    @overload
    def openDatagramChannel(self) -> DatagramChannel: ...
    @overload
    def openDatagramChannel(self, arg0: ProtocolFamily) -> DatagramChannel: ...
    def openPipe(self) -> Pipe: ...
    def openSelector(self) -> AbstractSelector: ...
    def openServerSocketChannel(self) -> ServerSocketChannel: ...
    def openSocketChannel(self) -> SocketChannel: ...
    def inheritedChannel(self) -> Channel: ...
