from typing import Any, ClassVar, overload
from android.hardware.usb.UsbDevice import UsbDevice
from android.hardware.usb.UsbDeviceConnection import UsbDeviceConnection
from android.mtp.MtpDeviceInfo import MtpDeviceInfo
from android.mtp.MtpEvent import MtpEvent
from android.mtp.MtpObjectInfo import MtpObjectInfo
from android.mtp.MtpStorageInfo import MtpStorageInfo
from android.os.CancellationSignal import CancellationSignal
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class MtpDevice:
    def __init__(self, arg0: UsbDevice) -> None: ...
    def open(self, arg0: UsbDeviceConnection) -> bool: ...
    def close(self) -> None: ...
    def finalize(self) -> None: ...
    def getDeviceName(self) -> str: ...
    def getDeviceId(self) -> int: ...
    def toString(self) -> str: ...
    def getDeviceInfo(self) -> MtpDeviceInfo: ...
    def getStorageIds(self) -> list[int]: ...
    def getObjectHandles(self, arg0: int, arg1: int, arg2: int) -> list[int]: ...
    def getObject(self, arg0: int, arg1: int) -> list[int]: ...
    def getPartialObject(self, arg0: int, arg1: int, arg2: int, arg3: list[int]) -> int: ...
    def getPartialObject64(self, arg0: int, arg1: int, arg2: int, arg3: list[int]) -> int: ...
    def getThumbnail(self, arg0: int) -> list[int]: ...
    def getStorageInfo(self, arg0: int) -> MtpStorageInfo: ...
    def getObjectInfo(self, arg0: int) -> MtpObjectInfo: ...
    def deleteObject(self, arg0: int) -> bool: ...
    def getParent(self, arg0: int) -> int: ...
    def getStorageId(self, arg0: int) -> int: ...
    @overload
    def importFile(self, arg0: int, arg1: str) -> bool: ...
    @overload
    def importFile(self, arg0: int, arg1: ParcelFileDescriptor) -> bool: ...
    def sendObject(self, arg0: int, arg1: int, arg2: ParcelFileDescriptor) -> bool: ...
    def sendObjectInfo(self, arg0: MtpObjectInfo) -> MtpObjectInfo: ...
    def readEvent(self, arg0: CancellationSignal) -> MtpEvent: ...
