from typing import Any, ClassVar, overload
from org.xml.sax.AttributeList import AttributeList
from org.xml.sax.Locator import Locator

class DocumentHandler:
    def setDocumentLocator(self, arg0: Locator) -> None: ...
    def startDocument(self) -> None: ...
    def endDocument(self) -> None: ...
    def startElement(self, arg0: str, arg1: AttributeList) -> None: ...
    def endElement(self, arg0: str) -> None: ...
    def characters(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    def ignorableWhitespace(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    def processingInstruction(self, arg0: str, arg1: str) -> None: ...
