from typing import Any, ClassVar, overload
from org.xml.sax.SAXParseException import SAXParseException

class ErrorHandler:
    def warning(self, arg0: SAXParseException) -> None: ...
    def error(self, arg0: SAXParseException) -> None: ...
    def fatalError(self, arg0: SAXParseException) -> None: ...
