from typing import Any, ClassVar, overload
from java.lang.Exception import Exception
from org.xml.sax.Locator import Locator

class SAXParseException:
    @overload
    def __init__(self, arg0: str, arg1: Locator) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Locator, arg2: Exception) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: str, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: str, arg3: int, arg4: int, arg5: Exception) -> None: ...
    def getPublicId(self) -> str: ...
    def getSystemId(self) -> str: ...
    def getLineNumber(self) -> int: ...
    def getColumnNumber(self) -> int: ...
