from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.TypedArray import TypedArray
from android.os.Bundle import Bundle
from android.os.Parcelable import Parcelable
from android.util.AttributeSet import AttributeSet
from android.view.View import View
from android.widget.EditText import EditText

class EditTextPreference:
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context) -> None: ...
    def setText(self, arg0: str) -> None: ...
    def getText(self) -> str: ...
    def onBindDialogView(self, arg0: View) -> None: ...
    def showDialog(self, arg0: Bundle) -> None: ...
    def onAddEditTextToDialogView(self, arg0: View, arg1: EditText) -> None: ...
    def onDialogClosed(self, arg0: bool) -> None: ...
    def onGetDefaultValue(self, arg0: TypedArray, arg1: int) -> Any: ...
    def onSetInitialValue(self, arg0: bool, arg1: Any) -> None: ...
    def shouldDisableDependents(self) -> bool: ...
    def getEditText(self) -> EditText: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, arg0: Parcelable) -> None: ...
