from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Bundle import Bundle
from android.preference.Preference import Preference
from android.util.AttributeSet import AttributeSet

class PreferenceGroup:
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    def setOrderingAsAdded(self, arg0: bool) -> None: ...
    def isOrderingAsAdded(self) -> bool: ...
    def addItemFromInflater(self, arg0: Preference) -> None: ...
    def getPreferenceCount(self) -> int: ...
    def getPreference(self, arg0: int) -> Preference: ...
    def addPreference(self, arg0: Preference) -> bool: ...
    def removePreference(self, arg0: Preference) -> bool: ...
    def removeAll(self) -> None: ...
    def onPrepareAddPreference(self, arg0: Preference) -> bool: ...
    def findPreference(self, arg0: str) -> Preference: ...
    def isOnSameScreenAsChildren(self) -> bool: ...
    def onAttachedToActivity(self) -> None: ...
    def onPrepareForRemoval(self) -> None: ...
    def notifyDependencyChange(self, arg0: bool) -> None: ...
    def dispatchSaveInstanceState(self, arg0: Bundle) -> None: ...
    def dispatchRestoreInstanceState(self, arg0: Bundle) -> None: ...
