from typing import Any, ClassVar, overload
from android.app.Fragment import Fragment
from android.content.Intent import Intent
from android.content.res.Resources import Resources
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.preference.Preference import Preference
from android.preference.PreferenceFragment import PreferenceFragment
from android.preference.PreferenceManager import PreferenceManager
from android.preference.PreferenceScreen import PreferenceScreen
from android.view.MenuItem import MenuItem
from android.view.View import View
from android.widget.ListView import ListView

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OnClickListener:
    """Forward declaration for ``android.view.View.OnClickListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.View.OnClickListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/View/OnClickListener
    """
    ...
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class PreferenceActivity:
    EXTRA_NO_HEADERS: ClassVar[str]
    EXTRA_SHOW_FRAGMENT: ClassVar[str]
    EXTRA_SHOW_FRAGMENT_ARGUMENTS: ClassVar[str]
    EXTRA_SHOW_FRAGMENT_SHORT_TITLE: ClassVar[str]
    EXTRA_SHOW_FRAGMENT_TITLE: ClassVar[str]
    HEADER_ID_UNDEFINED: ClassVar[int]
    def __init__(self) -> None: ...
    def onOptionsItemSelected(self, arg0: MenuItem) -> bool: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onBackPressed(self) -> None: ...
    def hasHeaders(self) -> bool: ...
    def isMultiPane(self) -> bool: ...
    def onIsMultiPane(self) -> bool: ...
    def onIsHidingHeaders(self) -> bool: ...
    def onGetInitialHeader(self) -> "Header": ...
    def onGetNewHeader(self) -> "Header": ...
    def onBuildHeaders(self, arg0: list) -> None: ...
    def invalidateHeaders(self) -> None: ...
    def loadHeadersFromResource(self, arg0: int, arg1: list) -> None: ...
    def isValidFragment(self, arg0: str) -> bool: ...
    def setListFooter(self, arg0: View) -> None: ...
    def onStop(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onSaveInstanceState(self, arg0: Bundle) -> None: ...
    def onRestoreInstanceState(self, arg0: Bundle) -> None: ...
    def onActivityResult(self, arg0: int, arg1: int, arg2: Intent) -> None: ...
    def onContentChanged(self) -> None: ...
    def onListItemClick(self, arg0: ListView, arg1: View, arg2: int, arg3: int) -> None: ...
    def onHeaderClick(self, arg0: "Header", arg1: int) -> None: ...
    def onBuildStartFragmentIntent(self, arg0: str, arg1: Bundle, arg2: int, arg3: int) -> Intent: ...
    @overload
    def startWithFragment(self, arg0: str, arg1: Bundle, arg2: Fragment, arg3: int) -> None: ...
    @overload
    def startWithFragment(self, arg0: str, arg1: Bundle, arg2: Fragment, arg3: int, arg4: int, arg5: int) -> None: ...
    def showBreadCrumbs(self, arg0: str, arg1: str) -> None: ...
    def setParentTitle(self, arg0: str, arg1: str, arg2: OnClickListener) -> None: ...
    @overload
    def switchToHeader(self, arg0: str, arg1: Bundle) -> None: ...
    @overload
    def switchToHeader(self, arg0: "Header") -> None: ...
    def startPreferenceFragment(self, arg0: Fragment, arg1: bool) -> None: ...
    def startPreferencePanel(self, arg0: str, arg1: Bundle, arg2: int, arg3: str, arg4: Fragment, arg5: int) -> None: ...
    def finishPreferencePanel(self, arg0: Fragment, arg1: int, arg2: Intent) -> None: ...
    def onPreferenceStartFragment(self, arg0: PreferenceFragment, arg1: Preference) -> bool: ...
    def getPreferenceManager(self) -> PreferenceManager: ...
    def setPreferenceScreen(self, arg0: PreferenceScreen) -> None: ...
    def getPreferenceScreen(self) -> PreferenceScreen: ...
    def addPreferencesFromIntent(self, arg0: Intent) -> None: ...
    def addPreferencesFromResource(self, arg0: int) -> None: ...
    def onPreferenceTreeClick(self, arg0: PreferenceScreen, arg1: Preference) -> bool: ...
    def findPreference(self, arg0: str) -> Preference: ...
    def onNewIntent(self, arg0: Intent) -> None: ...

    class Header:
        CREATOR: ClassVar[Creator]
        breadCrumbShortTitle: str
        breadCrumbShortTitleRes: int
        breadCrumbTitle: str
        breadCrumbTitleRes: int
        extras: Bundle
        fragment: str
        fragmentArguments: Bundle
        iconRes: int
        id: int
        intent: Intent
        summary: str
        summaryRes: int
        title: str
        titleRes: int
        def __init__(self) -> None: ...
        def getTitle(self, arg0: Resources) -> str: ...
        def getSummary(self, arg0: Resources) -> str: ...
        def getBreadCrumbTitle(self, arg0: Resources) -> str: ...
        def getBreadCrumbShortTitle(self, arg0: Resources) -> str: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def readFromParcel(self, arg0: Parcel) -> None: ...
