from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.Bundle import Bundle
from android.preference.Preference import Preference
from android.preference.PreferenceManager import PreferenceManager
from android.preference.PreferenceScreen import PreferenceScreen
from android.view.LayoutInflater import LayoutInflater
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class PreferenceFragment:
    def __init__(self) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onCreateView(self, arg0: LayoutInflater, arg1: ViewGroup, arg2: Bundle) -> View: ...
    def onViewCreated(self, arg0: View, arg1: Bundle) -> None: ...
    def onActivityCreated(self, arg0: Bundle) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    def onDestroyView(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onSaveInstanceState(self, arg0: Bundle) -> None: ...
    def onActivityResult(self, arg0: int, arg1: int, arg2: Intent) -> None: ...
    def getPreferenceManager(self) -> PreferenceManager: ...
    def setPreferenceScreen(self, arg0: PreferenceScreen) -> None: ...
    def getPreferenceScreen(self) -> PreferenceScreen: ...
    def addPreferencesFromIntent(self, arg0: Intent) -> None: ...
    def addPreferencesFromResource(self, arg0: int) -> None: ...
    def onPreferenceTreeClick(self, arg0: PreferenceScreen, arg1: Preference) -> bool: ...
    def findPreference(self, arg0: str) -> Preference: ...

    class OnPreferenceStartFragmentCallback:
        def onPreferenceStartFragment(self, arg0: "PreferenceFragment", arg1: Preference) -> bool: ...
