from typing import Any, ClassVar, overload

class PreferenceDataStore:
    def putString(self, arg0: str, arg1: str) -> None: ...
    def putStringSet(self, arg0: str, arg1: set) -> None: ...
    def putInt(self, arg0: str, arg1: int) -> None: ...
    def putLong(self, arg0: str, arg1: int) -> None: ...
    def putFloat(self, arg0: str, arg1: float) -> None: ...
    def putBoolean(self, arg0: str, arg1: bool) -> None: ...
    def getString(self, arg0: str, arg1: str) -> str: ...
    def getStringSet(self, arg0: str, arg1: set) -> set: ...
    def getInt(self, arg0: str, arg1: int) -> int: ...
    def getLong(self, arg0: str, arg1: int) -> int: ...
    def getFloat(self, arg0: str, arg1: float) -> float: ...
    def getBoolean(self, arg0: str, arg1: bool) -> bool: ...
