from typing import Any, ClassVar, overload

class PatternSyntaxException:
    def __init__(self, arg0: str, arg1: str, arg2: int) -> None: ...
    def getIndex(self) -> int: ...
    def getDescription(self) -> str: ...
    def getPattern(self) -> str: ...
    def getMessage(self) -> str: ...
