from typing import Any, ClassVar, overload
from java.lang.Exception import Exception
from java.lang.Throwable import Throwable

class AndroidException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: Exception) -> None: ...
