from typing import Any, ClassVar, overload
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BiFunction import BiFunction

class ArrayMap:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: "ArrayMap") -> None: ...
    def clear(self) -> None: ...
    def ensureCapacity(self, arg0: int) -> None: ...
    def containsKey(self, arg0: Any) -> bool: ...
    def indexOfKey(self, arg0: Any) -> int: ...
    def indexOfValue(self, arg0: Any) -> int: ...
    def containsValue(self, arg0: Any) -> bool: ...
    def get(self, arg0: Any) -> Any: ...
    def keyAt(self, arg0: int) -> Any: ...
    def valueAt(self, arg0: int) -> Any: ...
    def setValueAt(self, arg0: int, arg1: Any) -> Any: ...
    def isEmpty(self) -> bool: ...
    def put(self, arg0: Any, arg1: Any) -> Any: ...
    @overload
    def putAll(self, arg0: "ArrayMap") -> None: ...
    @overload
    def putAll(self, arg0: dict) -> None: ...
    def remove(self, arg0: Any) -> Any: ...
    def removeAt(self, arg0: int) -> Any: ...
    def size(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def containsAll(self, arg0: list) -> bool: ...
    def forEach(self, arg0: BiConsumer) -> None: ...
    def removeAll(self, arg0: list) -> bool: ...
    def replaceAll(self, arg0: BiFunction) -> None: ...
    def retainAll(self, arg0: list) -> bool: ...
    def entrySet(self) -> set: ...
    def keySet(self) -> set: ...
    def values(self) -> list: ...
