from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.FileInputStream import FileInputStream
from java.io.FileOutputStream import FileOutputStream

class AtomicFile:
    def __init__(self, arg0: File) -> None: ...
    def getBaseFile(self) -> File: ...
    def delete(self) -> None: ...
    def startWrite(self) -> FileOutputStream: ...
    def finishWrite(self, arg0: FileOutputStream) -> None: ...
    def failWrite(self, arg0: FileOutputStream) -> None: ...
    def openRead(self) -> FileInputStream: ...
    def getLastModifiedTime(self) -> int: ...
    def readFully(self) -> list[int]: ...
    def toString(self) -> str: ...
