from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream

class Base64OutputStream:
    def __init__(self, arg0: OutputStream, arg1: int) -> None: ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    def close(self) -> None: ...
