from typing import Any, ClassVar, overload

class IntProperty:
    def __init__(self, arg0: str) -> None: ...
    def setValue(self, arg0: Any, arg1: int) -> None: ...
    def set(self, arg0: Any, arg1: int) -> None: ...
