from typing import Any, ClassVar, overload
from java.io.PrintWriter import PrintWriter

class PrintWriterPrinter:
    def __init__(self, arg0: PrintWriter) -> None: ...
    def println(self, arg0: str) -> None: ...
