from typing import Any, ClassVar, overload

class Rational:
    NEGATIVE_INFINITY: ClassVar["Rational"]
    NaN: ClassVar["Rational"]
    POSITIVE_INFINITY: ClassVar["Rational"]
    ZERO: ClassVar["Rational"]
    def __init__(self, arg0: int, arg1: int) -> None: ...
    def getNumerator(self) -> int: ...
    def getDenominator(self) -> int: ...
    def isNaN(self) -> bool: ...
    def isInfinite(self) -> bool: ...
    def isFinite(self) -> bool: ...
    def isZero(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def doubleValue(self) -> float: ...
    def floatValue(self) -> float: ...
    def intValue(self) -> int: ...
    def longValue(self) -> int: ...
    def shortValue(self) -> int: ...
    def compareTo(self, arg0: "Rational") -> int: ...
    @staticmethod
    def parseRational(arg0: str) -> "Rational": ...
