from typing import Any, ClassVar, overload

class SparseIntArray:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    def clone(self) -> "SparseIntArray": ...
    @overload
    def get(self, arg0: int) -> int: ...
    @overload
    def get(self, arg0: int, arg1: int) -> int: ...
    def delete(self, arg0: int) -> None: ...
    def removeAt(self, arg0: int) -> None: ...
    def put(self, arg0: int, arg1: int) -> None: ...
    def size(self) -> int: ...
    def keyAt(self, arg0: int) -> int: ...
    def valueAt(self, arg0: int) -> int: ...
    def setValueAt(self, arg0: int, arg1: int) -> None: ...
    def indexOfKey(self, arg0: int) -> int: ...
    def indexOfValue(self, arg0: int) -> int: ...
    def clear(self) -> None: ...
    def append(self, arg0: int, arg1: int) -> None: ...
    def toString(self) -> str: ...
