from typing import Any, ClassVar, overload

class SparseArray:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    def clone(self) -> "SparseArray": ...
    def contains(self, arg0: int) -> bool: ...
    @overload
    def get(self, arg0: int) -> Any: ...
    @overload
    def get(self, arg0: int, arg1: Any) -> Any: ...
    def delete(self, arg0: int) -> None: ...
    def remove(self, arg0: int) -> None: ...
    def removeAt(self, arg0: int) -> None: ...
    def removeAtRange(self, arg0: int, arg1: int) -> None: ...
    def set(self, arg0: int, arg1: Any) -> None: ...
    def put(self, arg0: int, arg1: Any) -> None: ...
    def size(self) -> int: ...
    def keyAt(self, arg0: int) -> int: ...
    def valueAt(self, arg0: int) -> Any: ...
    def setValueAt(self, arg0: int, arg1: Any) -> None: ...
    def indexOfKey(self, arg0: int) -> int: ...
    def indexOfValue(self, arg0: Any) -> int: ...
    def clear(self) -> None: ...
    def append(self, arg0: int, arg1: Any) -> None: ...
    def toString(self) -> str: ...
    def contentEquals(self, arg0: "SparseArray") -> bool: ...
    def contentHashCode(self) -> int: ...
