from typing import Any, ClassVar, overload

class StatsLog:
    @staticmethod
    def logStart(arg0: int) -> bool: ...
    @staticmethod
    def logStop(arg0: int) -> bool: ...
    @staticmethod
    def logEvent(arg0: int) -> bool: ...
    @staticmethod
    def logBinaryPushStateChanged(arg0: str, arg1: int, arg2: int, arg3: int, arg4: list[int]) -> bool: ...
