from typing import Any, ClassVar, overload
from android.gms.ads.AdRequest import AdRequest
from android.gms.ads.FullScreenContentCallback import FullScreenContentCallback
from android.gms.ads.OnPaidEventListener import OnPaidEventListener
from android.gms.ads.ResponseInfo import ResponseInfo
from android.gms.ads.interstitial.InterstitialAdLoadCallback import InterstitialAdLoadCallback

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context:
    """Forward declaration for ``android.content.Context``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.Context')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/Context
    """
    ...
class Activity:
    """Forward declaration for ``android.app.Activity``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.app.Activity')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/app/Activity
    """
    ...

class InterstitialAd:
    def __init__(self) -> None: ...
    @staticmethod
    def load(arg0: Context, arg1: str, arg2: AdRequest, arg3: InterstitialAdLoadCallback) -> None: ...
    @staticmethod
    def isAdAvailable(arg0: Context, arg1: str) -> bool: ...
    @staticmethod
    def pollAd(arg0: Context, arg1: str) -> "InterstitialAd": ...
    def getAdUnitId(self) -> str: ...
    def show(self, arg0: Activity) -> None: ...
    def setFullScreenContentCallback(self, arg0: FullScreenContentCallback) -> None: ...
    def getFullScreenContentCallback(self) -> FullScreenContentCallback: ...
    def setImmersiveMode(self, arg0: bool) -> None: ...
    def getResponseInfo(self) -> ResponseInfo: ...
    def setOnPaidEventListener(self, arg0: OnPaidEventListener) -> None: ...
    def getOnPaidEventListener(self) -> OnPaidEventListener: ...
    def getPlacementId(self) -> int: ...
    def setPlacementId(self, arg0: int) -> None: ...
