from typing import Any, ClassVar, overload
from android.graphics.Insets import Insets
from android.graphics.Path import Path
from android.graphics.Rect import Rect

class DisplayCutout:
    @overload
    def __init__(self, arg0: Insets, arg1: Rect, arg2: Rect, arg3: Rect, arg4: Rect) -> None: ...
    @overload
    def __init__(self, arg0: Insets, arg1: Rect, arg2: Rect, arg3: Rect, arg4: Rect, arg5: Insets) -> None: ...
    @overload
    def __init__(self, arg0: Rect, arg1: list) -> None: ...
    def getWaterfallInsets(self) -> Insets: ...
    def getSafeInsetTop(self) -> int: ...
    def getSafeInsetBottom(self) -> int: ...
    def getSafeInsetLeft(self) -> int: ...
    def getSafeInsetRight(self) -> int: ...
    def getBoundingRects(self) -> list: ...
    def getBoundingRectLeft(self) -> Rect: ...
    def getBoundingRectTop(self) -> Rect: ...
    def getBoundingRectRight(self) -> Rect: ...
    def getBoundingRectBottom(self) -> Rect: ...
    def getCutoutPath(self) -> Path: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "DisplayCutout": ...
        def setSafeInsets(self, arg0: Insets) -> "Builder": ...
        def setWaterfallInsets(self, arg0: Insets) -> "Builder": ...
        def setBoundingRectLeft(self, arg0: Rect) -> "Builder": ...
        def setBoundingRectTop(self, arg0: Rect) -> "Builder": ...
        def setBoundingRectRight(self, arg0: Rect) -> "Builder": ...
        def setBoundingRectBottom(self, arg0: Rect) -> "Builder": ...
        def setCutoutPath(self, arg0: Path) -> "Builder": ...
