from typing import Any, ClassVar, overload

class HapticFeedbackConstants:
    CLOCK_TICK: ClassVar[int]
    CONFIRM: ClassVar[int]
    CONTEXT_CLICK: ClassVar[int]
    DRAG_START: ClassVar[int]
    FLAG_IGNORE_GLOBAL_SETTING: ClassVar[int]
    FLAG_IGNORE_VIEW_SETTING: ClassVar[int]
    GESTURE_END: ClassVar[int]
    GESTURE_START: ClassVar[int]
    GESTURE_THRESHOLD_ACTIVATE: ClassVar[int]
    GESTURE_THRESHOLD_DEACTIVATE: ClassVar[int]
    KEYBOARD_PRESS: ClassVar[int]
    KEYBOARD_RELEASE: ClassVar[int]
    KEYBOARD_TAP: ClassVar[int]
    LONG_PRESS: ClassVar[int]
    NO_HAPTICS: ClassVar[int]
    REJECT: ClassVar[int]
    SEGMENT_FREQUENT_TICK: ClassVar[int]
    SEGMENT_TICK: ClassVar[int]
    TEXT_HANDLE_MOVE: ClassVar[int]
    TOGGLE_OFF: ClassVar[int]
    TOGGLE_ON: ClassVar[int]
    VIRTUAL_KEY: ClassVar[int]
    VIRTUAL_KEY_RELEASE: ClassVar[int]
