from typing import Any, ClassVar, overload

class InputQueue:
    def finalize(self) -> None: ...

    class Callback:
        def onInputQueueCreated(self, arg0: "InputQueue") -> None: ...
        def onInputQueueDestroyed(self, arg0: "InputQueue") -> None: ...
