from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Intent import Intent
from android.view.KeyEvent import KeyEvent
from android.view.MenuItem import MenuItem
from android.view.SubMenu import SubMenu

class Menu:
    CATEGORY_ALTERNATIVE: ClassVar[int]
    CATEGORY_CONTAINER: ClassVar[int]
    CATEGORY_SECONDARY: ClassVar[int]
    CATEGORY_SYSTEM: ClassVar[int]
    FIRST: ClassVar[int]
    FLAG_ALWAYS_PERFORM_CLOSE: ClassVar[int]
    FLAG_APPEND_TO_GROUP: ClassVar[int]
    FLAG_PERFORM_NO_CLOSE: ClassVar[int]
    NONE: ClassVar[int]
    SUPPORTED_MODIFIERS_MASK: ClassVar[int]
    @overload
    def add(self, arg0: str) -> MenuItem: ...
    @overload
    def add(self, arg0: int) -> MenuItem: ...
    @overload
    def add(self, arg0: int, arg1: int, arg2: int, arg3: str) -> MenuItem: ...
    @overload
    def add(self, arg0: int, arg1: int, arg2: int, arg3: int) -> MenuItem: ...
    @overload
    def addSubMenu(self, arg0: str) -> SubMenu: ...
    @overload
    def addSubMenu(self, arg0: int) -> SubMenu: ...
    @overload
    def addSubMenu(self, arg0: int, arg1: int, arg2: int, arg3: str) -> SubMenu: ...
    @overload
    def addSubMenu(self, arg0: int, arg1: int, arg2: int, arg3: int) -> SubMenu: ...
    def addIntentOptions(self, arg0: int, arg1: int, arg2: int, arg3: ComponentName, arg4: list[Intent], arg5: Intent, arg6: int, arg7: list[MenuItem]) -> int: ...
    def removeItem(self, arg0: int) -> None: ...
    def removeGroup(self, arg0: int) -> None: ...
    def clear(self) -> None: ...
    def setGroupCheckable(self, arg0: int, arg1: bool, arg2: bool) -> None: ...
    def setGroupVisible(self, arg0: int, arg1: bool) -> None: ...
    def setGroupEnabled(self, arg0: int, arg1: bool) -> None: ...
    def hasVisibleItems(self) -> bool: ...
    def findItem(self, arg0: int) -> MenuItem: ...
    def size(self) -> int: ...
    def getItem(self, arg0: int) -> MenuItem: ...
    def close(self) -> None: ...
    def performShortcut(self, arg0: int, arg1: KeyEvent, arg2: int) -> bool: ...
    def isShortcutKey(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def performIdentifierAction(self, arg0: int, arg1: int) -> bool: ...
    def setQwertyMode(self, arg0: bool) -> None: ...
    def setGroupDividerEnabled(self, arg0: bool) -> None: ...
