from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["Menu"]

class Menu(JavaInterface, metaclass=MetaJavaClass):
    __javaclass__ = "android/view/Menu"
    CATEGORY_ALTERNATIVE = JavaStaticField("I")
    CATEGORY_CONTAINER = JavaStaticField("I")
    CATEGORY_SECONDARY = JavaStaticField("I")
    CATEGORY_SYSTEM = JavaStaticField("I")
    FIRST = JavaStaticField("I")
    FLAG_ALWAYS_PERFORM_CLOSE = JavaStaticField("I")
    FLAG_APPEND_TO_GROUP = JavaStaticField("I")
    FLAG_PERFORM_NO_CLOSE = JavaStaticField("I")
    NONE = JavaStaticField("I")
    SUPPORTED_MODIFIERS_MASK = JavaStaticField("I")
    add = JavaMultipleMethod([("(Ljava/lang/CharSequence;)Landroid/view/MenuItem;", False, False), ("(I)Landroid/view/MenuItem;", False, False), ("(IIILjava/lang/CharSequence;)Landroid/view/MenuItem;", False, False), ("(IIII)Landroid/view/MenuItem;", False, False)])
    addSubMenu = JavaMultipleMethod([("(Ljava/lang/CharSequence;)Landroid/view/SubMenu;", False, False), ("(I)Landroid/view/SubMenu;", False, False), ("(IIILjava/lang/CharSequence;)Landroid/view/SubMenu;", False, False), ("(IIII)Landroid/view/SubMenu;", False, False)])
    addIntentOptions = JavaMethod("(IIILandroid/content/ComponentName;[Landroid/content/Intent;Landroid/content/Intent;I[Landroid/view/MenuItem;)I")
    removeItem = JavaMethod("(I)V")
    removeGroup = JavaMethod("(I)V")
    clear = JavaMethod("()V")
    setGroupCheckable = JavaMethod("(IZZ)V")
    setGroupVisible = JavaMethod("(IZ)V")
    setGroupEnabled = JavaMethod("(IZ)V")
    hasVisibleItems = JavaMethod("()Z")
    findItem = JavaMethod("(I)Landroid/view/MenuItem;")
    size = JavaMethod("()I")
    getItem = JavaMethod("(I)Landroid/view/MenuItem;")
    close = JavaMethod("()V")
    performShortcut = JavaMethod("(ILandroid/view/KeyEvent;I)Z")
    isShortcutKey = JavaMethod("(ILandroid/view/KeyEvent;)Z")
    performIdentifierAction = JavaMethod("(II)Z")
    setQwertyMode = JavaMethod("(Z)V")
    setGroupDividerEnabled = JavaMethod("(Z)V")