from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.view.MotionEvent import MotionEvent

class MotionPredictor:
    def __init__(self, arg0: Context) -> None: ...
    def record(self, arg0: MotionEvent) -> None: ...
    def predict(self, arg0: int) -> MotionEvent: ...
    def isPredictionAvailable(self, arg0: int, arg1: int) -> bool: ...
