from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.graphics.Rect import Rect
from android.view.ScrollCaptureCallback import ScrollCaptureCallback
from android.view.View import View

class ScrollCaptureTarget:
    def __init__(self, arg0: View, arg1: Rect, arg2: Point, arg3: ScrollCaptureCallback) -> None: ...
    def getHint(self) -> int: ...
    def getCallback(self) -> ScrollCaptureCallback: ...
    def getContainingView(self) -> View: ...
    def getLocalVisibleRect(self) -> Rect: ...
    def getPositionInWindow(self) -> Point: ...
    def getScrollBounds(self) -> Rect: ...
    def setScrollBounds(self, arg0: Rect) -> None: ...
    def updatePositionInWindow(self) -> None: ...
    def toString(self) -> str: ...
