from typing import Any, ClassVar, overload
from android.graphics.drawable.Drawable import Drawable
from android.view.MenuItem import MenuItem
from android.view.View import View

class SubMenu:
    @overload
    def setHeaderTitle(self, arg0: int) -> "SubMenu": ...
    @overload
    def setHeaderTitle(self, arg0: str) -> "SubMenu": ...
    @overload
    def setHeaderIcon(self, arg0: int) -> "SubMenu": ...
    @overload
    def setHeaderIcon(self, arg0: Drawable) -> "SubMenu": ...
    def setHeaderView(self, arg0: View) -> "SubMenu": ...
    def clearHeader(self) -> None: ...
    @overload
    def setIcon(self, arg0: int) -> "SubMenu": ...
    @overload
    def setIcon(self, arg0: Drawable) -> "SubMenu": ...
    def getItem(self) -> MenuItem: ...
