from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.graphics.Region import Region
from android.hardware.HardwareBuffer import HardwareBuffer
from android.hardware.SyncFence import SyncFence
from android.os.Parcel import Parcel
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SurfaceControl:
    BUFFER_TRANSFORM_IDENTITY: ClassVar[int]
    BUFFER_TRANSFORM_MIRROR_HORIZONTAL: ClassVar[int]
    BUFFER_TRANSFORM_MIRROR_VERTICAL: ClassVar[int]
    BUFFER_TRANSFORM_ROTATE_180: ClassVar[int]
    BUFFER_TRANSFORM_ROTATE_270: ClassVar[int]
    BUFFER_TRANSFORM_ROTATE_90: ClassVar[int]
    CREATOR: ClassVar[Creator]
    def readFromParcel(self, arg0: Parcel) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def finalize(self) -> None: ...
    def release(self) -> None: ...
    def isValid(self) -> bool: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "SurfaceControl": ...
        def setName(self, arg0: str) -> "Builder": ...
        def setBufferSize(self, arg0: int, arg1: int) -> "Builder": ...
        def setFormat(self, arg0: int) -> "Builder": ...
        def setOpaque(self, arg0: bool) -> "Builder": ...
        def setHidden(self, arg0: bool) -> "Builder": ...
        def setParent(self, arg0: "SurfaceControl") -> "Builder": ...

    class Transaction:
        CREATOR: ClassVar[Creator]
        def __init__(self) -> None: ...
        def apply(self) -> None: ...
        def close(self) -> None: ...
        def setVisibility(self, arg0: "SurfaceControl", arg1: bool) -> "Transaction": ...
        def setPosition(self, arg0: "SurfaceControl", arg1: float, arg2: float) -> "Transaction": ...
        def setScale(self, arg0: "SurfaceControl", arg1: float, arg2: float) -> "Transaction": ...
        def setBufferSize(self, arg0: "SurfaceControl", arg1: int, arg2: int) -> "Transaction": ...
        def setLayer(self, arg0: "SurfaceControl", arg1: int) -> "Transaction": ...
        def setAlpha(self, arg0: "SurfaceControl", arg1: float) -> "Transaction": ...
        def setGeometry(self, arg0: "SurfaceControl", arg1: Rect, arg2: Rect, arg3: int) -> "Transaction": ...
        def setCrop(self, arg0: "SurfaceControl", arg1: Rect) -> "Transaction": ...
        def reparent(self, arg0: "SurfaceControl", arg1: "SurfaceControl") -> "Transaction": ...
        def setOpaque(self, arg0: "SurfaceControl", arg1: bool) -> "Transaction": ...
        @overload
        def setFrameRate(self, arg0: "SurfaceControl", arg1: float, arg2: int) -> "Transaction": ...
        @overload
        def setFrameRate(self, arg0: "SurfaceControl", arg1: float, arg2: int, arg3: int) -> "Transaction": ...
        def clearFrameRate(self, arg0: "SurfaceControl") -> "Transaction": ...
        @overload
        def setBuffer(self, arg0: "SurfaceControl", arg1: HardwareBuffer) -> "Transaction": ...
        @overload
        def setBuffer(self, arg0: "SurfaceControl", arg1: HardwareBuffer, arg2: SyncFence) -> "Transaction": ...
        @overload
        def setBuffer(self, arg0: "SurfaceControl", arg1: HardwareBuffer, arg2: SyncFence, arg3: Consumer) -> "Transaction": ...
        def setBufferTransform(self, arg0: "SurfaceControl", arg1: int) -> "Transaction": ...
        def setDamageRegion(self, arg0: "SurfaceControl", arg1: Region) -> "Transaction": ...
        def setDataSpace(self, arg0: "SurfaceControl", arg1: int) -> "Transaction": ...
        def setExtendedRangeBrightness(self, arg0: "SurfaceControl", arg1: float, arg2: float) -> "Transaction": ...
        def setDesiredHdrHeadroom(self, arg0: "SurfaceControl", arg1: float) -> "Transaction": ...
        def merge(self, arg0: "Transaction") -> "Transaction": ...
        def setFrameTimeline(self, arg0: int) -> "Transaction": ...
        def addTransactionCommittedListener(self, arg0: Executor, arg1: "TransactionCommittedListener") -> "Transaction": ...
        def addTransactionCompletedListener(self, arg0: Executor, arg1: Consumer) -> "Transaction": ...
        def setTrustedPresentationCallback(self, arg0: "SurfaceControl", arg1: "TrustedPresentationThresholds", arg2: Executor, arg3: Consumer) -> "Transaction": ...
        def clearTrustedPresentationCallback(self, arg0: "SurfaceControl") -> "Transaction": ...
        def setDesiredPresentTimeNanos(self, arg0: int) -> "Transaction": ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def describeContents(self) -> int: ...

    class TransactionCommittedListener:
        def onTransactionCommitted(self) -> None: ...

    class TransactionStats:
        def getLatchTimeNanos(self) -> int: ...
        def getPresentFence(self) -> SyncFence: ...

    class TrustedPresentationThresholds:
        def __init__(self, arg0: float, arg1: float, arg2: int) -> None: ...
