from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.Configuration import Configuration
from android.os.IBinder import IBinder
from android.os.Parcel import Parcel
from android.view.Display import Display
from android.view.SurfaceControl import SurfaceControl
from android.view.View import View
from android.window.InputTransferToken import InputTransferToken

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SurfaceControlViewHost:
    @overload
    def __init__(self, arg0: Context, arg1: Display, arg2: IBinder) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Display, arg2: InputTransferToken) -> None: ...
    def finalize(self) -> None: ...
    def getSurfacePackage(self) -> "SurfacePackage": ...
    def setView(self, arg0: View, arg1: int, arg2: int) -> None: ...
    def getView(self) -> View: ...
    def relayout(self, arg0: int, arg1: int) -> None: ...
    def release(self) -> None: ...
    def transferTouchGestureToHost(self) -> bool: ...

    class SurfacePackage:
        CREATOR: ClassVar[Creator]
        def __init__(self, arg0: "SurfacePackage") -> None: ...
        def getSurfaceControl(self) -> SurfaceControl: ...
        def notifyConfigurationChanged(self, arg0: Configuration) -> None: ...
        def notifyDetachedFromWindow(self) -> None: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def release(self) -> None: ...
        def getInputTransferToken(self) -> InputTransferToken: ...
        def toString(self) -> str: ...
