from typing import Any, ClassVar, overload
from android.view.View import View

class ViewDebug:
    TRACE_HIERARCHY: ClassVar[bool]
    TRACE_RECYCLER: ClassVar[bool]
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def trace(arg0: View, arg1: "RecyclerTraceType", *arg2: int) -> None: ...
    @overload
    @staticmethod
    def trace(arg0: View, arg1: "HierarchyTraceType") -> None: ...
    @staticmethod
    def startRecyclerTracing(arg0: str, arg1: View) -> None: ...
    @staticmethod
    def stopRecyclerTracing() -> None: ...
    @staticmethod
    def startHierarchyTracing(arg0: str, arg1: View) -> None: ...
    @staticmethod
    def stopHierarchyTracing() -> None: ...
    @staticmethod
    def dumpCapturedView(arg0: str, arg1: Any) -> None: ...

    class CapturedViewProperty:
        def retrieveReturn(self) -> bool: ...

    class ExportedProperty:
        def resolveId(self) -> bool: ...
        def mapping(self) -> list["IntToString"]: ...
        def indexMapping(self) -> list["IntToString"]: ...
        def flagMapping(self) -> list["FlagToString"]: ...
        def deepExport(self) -> bool: ...
        def prefix(self) -> str: ...
        def category(self) -> str: ...
        def formatToHexString(self) -> bool: ...
        def hasAdjacentMapping(self) -> bool: ...

    class FlagToString:
        def mask(self) -> int: ...
        def equals(self) -> int: ...
        def name(self) -> str: ...
        def outputIf(self) -> bool: ...

    class HierarchyTraceType:
        INVALIDATE: ClassVar["HierarchyTraceType"]
        INVALIDATE_CHILD: ClassVar["HierarchyTraceType"]
        INVALIDATE_CHILD_IN_PARENT: ClassVar["HierarchyTraceType"]
        REQUEST_LAYOUT: ClassVar["HierarchyTraceType"]
        ON_LAYOUT: ClassVar["HierarchyTraceType"]
        ON_MEASURE: ClassVar["HierarchyTraceType"]
        DRAW: ClassVar["HierarchyTraceType"]
        BUILD_CACHE: ClassVar["HierarchyTraceType"]
        @staticmethod
        def values() -> list["HierarchyTraceType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "HierarchyTraceType": ...

    class IntToString:
        def from_(self) -> int: ...
        def to(self) -> str: ...

    class RecyclerTraceType:
        NEW_VIEW: ClassVar["RecyclerTraceType"]
        BIND_VIEW: ClassVar["RecyclerTraceType"]
        RECYCLE_FROM_ACTIVE_HEAP: ClassVar["RecyclerTraceType"]
        RECYCLE_FROM_SCRAP_HEAP: ClassVar["RecyclerTraceType"]
        MOVE_TO_SCRAP_HEAP: ClassVar["RecyclerTraceType"]
        MOVE_FROM_ACTIVE_TO_SCRAP_HEAP: ClassVar["RecyclerTraceType"]
        @staticmethod
        def values() -> list["RecyclerTraceType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "RecyclerTraceType": ...
