from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.graphics.Rect import Rect
from android.os.Bundle import Bundle
from android.view.ActionMode import ActionMode
from android.view.ContextMenu import ContextMenu
from android.view.View import View
from android.view.accessibility.AccessibilityEvent import AccessibilityEvent
from android.window.OnBackInvokedDispatcher import OnBackInvokedDispatcher

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Callback:
    """Forward declaration for ``android.view.ActionMode.Callback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ActionMode.Callback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ActionMode/Callback
    """
    ...

class ViewParent:
    def requestLayout(self) -> None: ...
    def isLayoutRequested(self) -> bool: ...
    def requestTransparentRegion(self, arg0: View) -> None: ...
    def onDescendantInvalidated(self, arg0: View, arg1: View) -> None: ...
    def invalidateChild(self, arg0: View, arg1: Rect) -> None: ...
    def invalidateChildInParent(self, arg0: list[int], arg1: Rect) -> "ViewParent": ...
    def getParent(self) -> "ViewParent": ...
    def requestChildFocus(self, arg0: View, arg1: View) -> None: ...
    def recomputeViewAttributes(self, arg0: View) -> None: ...
    def clearChildFocus(self, arg0: View) -> None: ...
    def getChildVisibleRect(self, arg0: View, arg1: Rect, arg2: Point) -> bool: ...
    def focusSearch(self, arg0: View, arg1: int) -> View: ...
    def keyboardNavigationClusterSearch(self, arg0: View, arg1: int) -> View: ...
    def bringChildToFront(self, arg0: View) -> None: ...
    def focusableViewAvailable(self, arg0: View) -> None: ...
    @overload
    def showContextMenuForChild(self, arg0: View) -> bool: ...
    @overload
    def showContextMenuForChild(self, arg0: View, arg1: float, arg2: float) -> bool: ...
    def createContextMenu(self, arg0: ContextMenu) -> None: ...
    @overload
    def startActionModeForChild(self, arg0: View, arg1: Callback) -> ActionMode: ...
    @overload
    def startActionModeForChild(self, arg0: View, arg1: Callback, arg2: int) -> ActionMode: ...
    def childDrawableStateChanged(self, arg0: View) -> None: ...
    def requestDisallowInterceptTouchEvent(self, arg0: bool) -> None: ...
    def requestChildRectangleOnScreen(self, arg0: View, arg1: Rect, arg2: bool) -> bool: ...
    def requestSendAccessibilityEvent(self, arg0: View, arg1: AccessibilityEvent) -> bool: ...
    def childHasTransientStateChanged(self, arg0: View, arg1: bool) -> None: ...
    def requestFitSystemWindows(self) -> None: ...
    def getParentForAccessibility(self) -> "ViewParent": ...
    def notifySubtreeAccessibilityStateChanged(self, arg0: View, arg1: View, arg2: int) -> None: ...
    def canResolveLayoutDirection(self) -> bool: ...
    def isLayoutDirectionResolved(self) -> bool: ...
    def getLayoutDirection(self) -> int: ...
    def canResolveTextDirection(self) -> bool: ...
    def isTextDirectionResolved(self) -> bool: ...
    def getTextDirection(self) -> int: ...
    def canResolveTextAlignment(self) -> bool: ...
    def isTextAlignmentResolved(self) -> bool: ...
    def getTextAlignment(self) -> int: ...
    def onStartNestedScroll(self, arg0: View, arg1: View, arg2: int) -> bool: ...
    def onNestedScrollAccepted(self, arg0: View, arg1: View, arg2: int) -> None: ...
    def onStopNestedScroll(self, arg0: View) -> None: ...
    def onNestedScroll(self, arg0: View, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def onNestedPreScroll(self, arg0: View, arg1: int, arg2: int, arg3: list[int]) -> None: ...
    def onNestedFling(self, arg0: View, arg1: float, arg2: float, arg3: bool) -> bool: ...
    def onNestedPreFling(self, arg0: View, arg1: float, arg2: float) -> bool: ...
    def onNestedPrePerformAccessibilityAction(self, arg0: View, arg1: int, arg2: Bundle) -> bool: ...
    def findOnBackInvokedDispatcherForChild(self, arg0: View, arg1: View) -> OnBackInvokedDispatcher: ...
