from typing import Any, ClassVar, overload
from android.view.View import View
from java.lang.Runnable import Runnable
from java.util.function.Consumer import Consumer

class ViewTreeObserver:
    def addOnWindowAttachListener(self, arg0: "OnWindowAttachListener") -> None: ...
    def removeOnWindowAttachListener(self, arg0: "OnWindowAttachListener") -> None: ...
    def addOnWindowFocusChangeListener(self, arg0: "OnWindowFocusChangeListener") -> None: ...
    def removeOnWindowFocusChangeListener(self, arg0: "OnWindowFocusChangeListener") -> None: ...
    def addOnWindowVisibilityChangeListener(self, arg0: "OnWindowVisibilityChangeListener") -> None: ...
    def removeOnWindowVisibilityChangeListener(self, arg0: "OnWindowVisibilityChangeListener") -> None: ...
    def addOnGlobalFocusChangeListener(self, arg0: "OnGlobalFocusChangeListener") -> None: ...
    def removeOnGlobalFocusChangeListener(self, arg0: "OnGlobalFocusChangeListener") -> None: ...
    def addOnGlobalLayoutListener(self, arg0: "OnGlobalLayoutListener") -> None: ...
    def removeGlobalOnLayoutListener(self, arg0: "OnGlobalLayoutListener") -> None: ...
    def removeOnGlobalLayoutListener(self, arg0: "OnGlobalLayoutListener") -> None: ...
    def addOnPreDrawListener(self, arg0: "OnPreDrawListener") -> None: ...
    def removeOnPreDrawListener(self, arg0: "OnPreDrawListener") -> None: ...
    def addOnDrawListener(self, arg0: "OnDrawListener") -> None: ...
    def removeOnDrawListener(self, arg0: "OnDrawListener") -> None: ...
    def registerFrameCommitCallback(self, arg0: Runnable) -> None: ...
    def unregisterFrameCommitCallback(self, arg0: Runnable) -> bool: ...
    def addOnScrollChangedListener(self, arg0: "OnScrollChangedListener") -> None: ...
    def removeOnScrollChangedListener(self, arg0: "OnScrollChangedListener") -> None: ...
    def addOnTouchModeChangeListener(self, arg0: "OnTouchModeChangeListener") -> None: ...
    def removeOnTouchModeChangeListener(self, arg0: "OnTouchModeChangeListener") -> None: ...
    def addOnSystemGestureExclusionRectsChangedListener(self, arg0: Consumer) -> None: ...
    def removeOnSystemGestureExclusionRectsChangedListener(self, arg0: Consumer) -> None: ...
    def isAlive(self) -> bool: ...
    def dispatchOnGlobalLayout(self) -> None: ...
    def dispatchOnPreDraw(self) -> bool: ...
    def dispatchOnDraw(self) -> None: ...

    class OnDrawListener:
        def onDraw(self) -> None: ...

    class OnGlobalFocusChangeListener:
        def onGlobalFocusChanged(self, arg0: View, arg1: View) -> None: ...

    class OnGlobalLayoutListener:
        def onGlobalLayout(self) -> None: ...

    class OnPreDrawListener:
        def onPreDraw(self) -> bool: ...

    class OnScrollChangedListener:
        def onScrollChanged(self) -> None: ...

    class OnTouchModeChangeListener:
        def onTouchModeChanged(self, arg0: bool) -> None: ...

    class OnWindowAttachListener:
        def onWindowAttached(self) -> None: ...
        def onWindowDetached(self) -> None: ...

    class OnWindowFocusChangeListener:
        def onWindowFocusChanged(self, arg0: bool) -> None: ...

    class OnWindowVisibilityChangeListener:
        def onWindowVisibilityChanged(self, arg0: int) -> None: ...
