from typing import Any, ClassVar, overload
from android.graphics.Insets import Insets
from android.graphics.Rect import Rect
from android.util.Size import Size
from android.view.DisplayCutout import DisplayCutout
from android.view.DisplayShape import DisplayShape
from android.view.RoundedCorner import RoundedCorner

class WindowInsets:
    CONSUMED: ClassVar["WindowInsets"]
    def __init__(self, arg0: "WindowInsets") -> None: ...
    def getSystemWindowInsets(self) -> Insets: ...
    def getInsets(self, arg0: int) -> Insets: ...
    def getInsetsIgnoringVisibility(self, arg0: int) -> Insets: ...
    def isVisible(self, arg0: int) -> bool: ...
    def getSystemWindowInsetLeft(self) -> int: ...
    def getSystemWindowInsetTop(self) -> int: ...
    def getSystemWindowInsetRight(self) -> int: ...
    def getSystemWindowInsetBottom(self) -> int: ...
    def hasSystemWindowInsets(self) -> bool: ...
    def hasInsets(self) -> bool: ...
    def getBoundingRects(self, arg0: int) -> list: ...
    def getBoundingRectsIgnoringVisibility(self, arg0: int) -> list: ...
    def getDisplayCutout(self) -> DisplayCutout: ...
    def getRoundedCorner(self, arg0: int) -> RoundedCorner: ...
    def getPrivacyIndicatorBounds(self) -> Rect: ...
    def getDisplayShape(self) -> DisplayShape: ...
    def consumeDisplayCutout(self) -> "WindowInsets": ...
    def isConsumed(self) -> bool: ...
    def isRound(self) -> bool: ...
    def consumeSystemWindowInsets(self) -> "WindowInsets": ...
    @overload
    def replaceSystemWindowInsets(self, arg0: int, arg1: int, arg2: int, arg3: int) -> "WindowInsets": ...
    @overload
    def replaceSystemWindowInsets(self, arg0: Rect) -> "WindowInsets": ...
    def getStableInsets(self) -> Insets: ...
    def getStableInsetTop(self) -> int: ...
    def getStableInsetLeft(self) -> int: ...
    def getStableInsetRight(self) -> int: ...
    def getStableInsetBottom(self) -> int: ...
    def hasStableInsets(self) -> bool: ...
    def getSystemGestureInsets(self) -> Insets: ...
    def getMandatorySystemGestureInsets(self) -> Insets: ...
    def getTappableElementInsets(self) -> Insets: ...
    def consumeStableInsets(self) -> "WindowInsets": ...
    def toString(self) -> str: ...
    @overload
    def inset(self, arg0: Insets) -> "WindowInsets": ...
    @overload
    def inset(self, arg0: int, arg1: int, arg2: int, arg3: int) -> "WindowInsets": ...
    def getFrame(self) -> Size: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: "WindowInsets") -> None: ...
        def setSystemWindowInsets(self, arg0: Insets) -> "Builder": ...
        def setSystemGestureInsets(self, arg0: Insets) -> "Builder": ...
        def setMandatorySystemGestureInsets(self, arg0: Insets) -> "Builder": ...
        def setTappableElementInsets(self, arg0: Insets) -> "Builder": ...
        def setInsets(self, arg0: int, arg1: Insets) -> "Builder": ...
        def setInsetsIgnoringVisibility(self, arg0: int, arg1: Insets) -> "Builder": ...
        def setVisible(self, arg0: int, arg1: bool) -> "Builder": ...
        def setStableInsets(self, arg0: Insets) -> "Builder": ...
        def setDisplayCutout(self, arg0: DisplayCutout) -> "Builder": ...
        def setRoundedCorner(self, arg0: int, arg1: RoundedCorner) -> "Builder": ...
        def setPrivacyIndicatorBounds(self, arg0: Rect) -> "Builder": ...
        def setDisplayShape(self, arg0: DisplayShape) -> "Builder": ...
        def setBoundingRects(self, arg0: int, arg1: list) -> "Builder": ...
        def setBoundingRectsIgnoringVisibility(self, arg0: int, arg1: list) -> "Builder": ...
        def setFrame(self, arg0: int, arg1: int) -> "Builder": ...
        def build(self) -> "WindowInsets": ...

    class Side:
        BOTTOM: ClassVar[int]
        LEFT: ClassVar[int]
        RIGHT: ClassVar[int]
        TOP: ClassVar[int]
        @staticmethod
        def all() -> int: ...

    class Type:
        @staticmethod
        def statusBars() -> int: ...
        @staticmethod
        def navigationBars() -> int: ...
        @staticmethod
        def captionBar() -> int: ...
        @staticmethod
        def ime() -> int: ...
        @staticmethod
        def systemGestures() -> int: ...
        @staticmethod
        def mandatorySystemGestures() -> int: ...
        @staticmethod
        def tappableElement() -> int: ...
        @staticmethod
        def displayCutout() -> int: ...
        @staticmethod
        def systemOverlays() -> int: ...
        @staticmethod
        def systemBars() -> int: ...
