from typing import Any, ClassVar, overload
from android.graphics.Insets import Insets

class WindowInsetsAnimationController:
    def getHiddenStateInsets(self) -> Insets: ...
    def getShownStateInsets(self) -> Insets: ...
    def getCurrentInsets(self) -> Insets: ...
    def getCurrentFraction(self) -> float: ...
    def getCurrentAlpha(self) -> float: ...
    def getTypes(self) -> int: ...
    def setInsetsAndAlpha(self, arg0: Insets, arg1: float, arg2: float) -> None: ...
    def finish(self, arg0: bool) -> None: ...
    def isReady(self) -> bool: ...
    def isFinished(self) -> bool: ...
    def isCancelled(self) -> bool: ...
