from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["WindowInsets"]

class WindowInsets(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/view/WindowInsets"
    __javaconstructor__ = [("(Landroid/view/WindowInsets;)V", False)]
    CONSUMED = JavaStaticField("Landroid/view/WindowInsets;")
    getSystemWindowInsets = JavaMethod("()Landroid/graphics/Insets;")
    getInsets = JavaMethod("(I)Landroid/graphics/Insets;")
    getInsetsIgnoringVisibility = JavaMethod("(I)Landroid/graphics/Insets;")
    isVisible = JavaMethod("(I)Z")
    getSystemWindowInsetLeft = JavaMethod("()I")
    getSystemWindowInsetTop = JavaMethod("()I")
    getSystemWindowInsetRight = JavaMethod("()I")
    getSystemWindowInsetBottom = JavaMethod("()I")
    hasSystemWindowInsets = JavaMethod("()Z")
    hasInsets = JavaMethod("()Z")
    getBoundingRects = JavaMethod("(I)Ljava/util/List;")
    getBoundingRectsIgnoringVisibility = JavaMethod("(I)Ljava/util/List;")
    getDisplayCutout = JavaMethod("()Landroid/view/DisplayCutout;")
    getRoundedCorner = JavaMethod("(I)Landroid/view/RoundedCorner;")
    getPrivacyIndicatorBounds = JavaMethod("()Landroid/graphics/Rect;")
    getDisplayShape = JavaMethod("()Landroid/view/DisplayShape;")
    consumeDisplayCutout = JavaMethod("()Landroid/view/WindowInsets;")
    isConsumed = JavaMethod("()Z")
    isRound = JavaMethod("()Z")
    consumeSystemWindowInsets = JavaMethod("()Landroid/view/WindowInsets;")
    replaceSystemWindowInsets = JavaMultipleMethod([("(IIII)Landroid/view/WindowInsets;", False, False), ("(Landroid/graphics/Rect;)Landroid/view/WindowInsets;", False, False)])
    getStableInsets = JavaMethod("()Landroid/graphics/Insets;")
    getStableInsetTop = JavaMethod("()I")
    getStableInsetLeft = JavaMethod("()I")
    getStableInsetRight = JavaMethod("()I")
    getStableInsetBottom = JavaMethod("()I")
    hasStableInsets = JavaMethod("()Z")
    getSystemGestureInsets = JavaMethod("()Landroid/graphics/Insets;")
    getMandatorySystemGestureInsets = JavaMethod("()Landroid/graphics/Insets;")
    getTappableElementInsets = JavaMethod("()Landroid/graphics/Insets;")
    consumeStableInsets = JavaMethod("()Landroid/view/WindowInsets;")
    toString = JavaMethod("()Ljava/lang/String;")
    inset = JavaMultipleMethod([("(Landroid/graphics/Insets;)Landroid/view/WindowInsets;", False, False), ("(IIII)Landroid/view/WindowInsets;", False, False)])
    getFrame = JavaMethod("()Landroid/util/Size;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    hashCode = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/view/WindowInsets/Builder"
        __javaconstructor__ = [("()V", False), ("(Landroid/view/WindowInsets;)V", False)]
        setSystemWindowInsets = JavaMethod("(Landroid/graphics/Insets;)Landroid/view/WindowInsets$Builder;")
        setSystemGestureInsets = JavaMethod("(Landroid/graphics/Insets;)Landroid/view/WindowInsets$Builder;")
        setMandatorySystemGestureInsets = JavaMethod("(Landroid/graphics/Insets;)Landroid/view/WindowInsets$Builder;")
        setTappableElementInsets = JavaMethod("(Landroid/graphics/Insets;)Landroid/view/WindowInsets$Builder;")
        setInsets = JavaMethod("(ILandroid/graphics/Insets;)Landroid/view/WindowInsets$Builder;")
        setInsetsIgnoringVisibility = JavaMethod("(ILandroid/graphics/Insets;)Landroid/view/WindowInsets$Builder;")
        setVisible = JavaMethod("(IZ)Landroid/view/WindowInsets$Builder;")
        setStableInsets = JavaMethod("(Landroid/graphics/Insets;)Landroid/view/WindowInsets$Builder;")
        setDisplayCutout = JavaMethod("(Landroid/view/DisplayCutout;)Landroid/view/WindowInsets$Builder;")
        setRoundedCorner = JavaMethod("(ILandroid/view/RoundedCorner;)Landroid/view/WindowInsets$Builder;")
        setPrivacyIndicatorBounds = JavaMethod("(Landroid/graphics/Rect;)Landroid/view/WindowInsets$Builder;")
        setDisplayShape = JavaMethod("(Landroid/view/DisplayShape;)Landroid/view/WindowInsets$Builder;")
        setBoundingRects = JavaMethod("(ILjava/util/List;)Landroid/view/WindowInsets$Builder;")
        setBoundingRectsIgnoringVisibility = JavaMethod("(ILjava/util/List;)Landroid/view/WindowInsets$Builder;")
        setFrame = JavaMethod("(II)Landroid/view/WindowInsets$Builder;")
        build = JavaMethod("()Landroid/view/WindowInsets;")

    class Side(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/view/WindowInsets/Side"
        BOTTOM = JavaStaticField("I")
        LEFT = JavaStaticField("I")
        RIGHT = JavaStaticField("I")
        TOP = JavaStaticField("I")
        all = JavaStaticMethod("()I")

    class Type(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/view/WindowInsets/Type"
        statusBars = JavaStaticMethod("()I")
        navigationBars = JavaStaticMethod("()I")
        captionBar = JavaStaticMethod("()I")
        ime = JavaStaticMethod("()I")
        systemGestures = JavaStaticMethod("()I")
        mandatorySystemGestures = JavaStaticMethod("()I")
        tappableElement = JavaStaticMethod("()I")
        displayCutout = JavaStaticMethod("()I")
        systemOverlays = JavaStaticMethod("()I")
        systemBars = JavaStaticMethod("()I")