from typing import Any, ClassVar, overload
from android.graphics.Insets import Insets
from android.view.WindowInsets import WindowInsets
from android.view.animation.Interpolator import Interpolator

class WindowInsetsAnimation:
    def __init__(self, arg0: int, arg1: Interpolator, arg2: int) -> None: ...
    def getTypeMask(self) -> int: ...
    def getFraction(self) -> float: ...
    def getInterpolatedFraction(self) -> float: ...
    def getInterpolator(self) -> Interpolator: ...
    def getDurationMillis(self) -> int: ...
    def setFraction(self, arg0: float) -> None: ...
    def getAlpha(self) -> float: ...
    def setAlpha(self, arg0: float) -> None: ...

    class Bounds:
        def __init__(self, arg0: Insets, arg1: Insets) -> None: ...
        def getLowerBound(self) -> Insets: ...
        def getUpperBound(self) -> Insets: ...
        def inset(self, arg0: Insets) -> "Bounds": ...
        def toString(self) -> str: ...

    class Callback:
        DISPATCH_MODE_CONTINUE_ON_SUBTREE: ClassVar[int]
        DISPATCH_MODE_STOP: ClassVar[int]
        def __init__(self, arg0: int) -> None: ...
        def getDispatchMode(self) -> int: ...
        def onPrepare(self, arg0: "WindowInsetsAnimation") -> None: ...
        def onStart(self, arg0: "WindowInsetsAnimation", arg1: "Bounds") -> "Bounds": ...
        def onProgress(self, arg0: WindowInsets, arg1: list) -> WindowInsets: ...
        def onEnd(self, arg0: "WindowInsetsAnimation") -> None: ...
