from typing import Any, ClassVar, overload
from android.os.CancellationSignal import CancellationSignal
from android.view.WindowInsetsAnimationControlListener import WindowInsetsAnimationControlListener
from android.view.animation.Interpolator import Interpolator

class WindowInsetsController:
    APPEARANCE_LIGHT_CAPTION_BARS: ClassVar[int]
    APPEARANCE_LIGHT_NAVIGATION_BARS: ClassVar[int]
    APPEARANCE_LIGHT_STATUS_BARS: ClassVar[int]
    APPEARANCE_TRANSPARENT_CAPTION_BAR_BACKGROUND: ClassVar[int]
    BEHAVIOR_DEFAULT: ClassVar[int]
    BEHAVIOR_SHOW_BARS_BY_SWIPE: ClassVar[int]
    BEHAVIOR_SHOW_BARS_BY_TOUCH: ClassVar[int]
    BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE: ClassVar[int]
    def show(self, arg0: int) -> None: ...
    def hide(self, arg0: int) -> None: ...
    def controlWindowInsetsAnimation(self, arg0: int, arg1: int, arg2: Interpolator, arg3: CancellationSignal, arg4: WindowInsetsAnimationControlListener) -> None: ...
    def setSystemBarsAppearance(self, arg0: int, arg1: int) -> None: ...
    def getSystemBarsAppearance(self) -> int: ...
    def setSystemBarsBehavior(self, arg0: int) -> None: ...
    def getSystemBarsBehavior(self) -> int: ...
    def addOnControllableInsetsChangedListener(self, arg0: "OnControllableInsetsChangedListener") -> None: ...
    def removeOnControllableInsetsChangedListener(self, arg0: "OnControllableInsetsChangedListener") -> None: ...

    class OnControllableInsetsChangedListener:
        def onControllableInsetsChanged(self, arg0: "WindowInsetsController", arg1: int) -> None: ...
