from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from java.security.cert.Certificate import Certificate
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.CipherSpi import CipherSpi
from javax.crypto.ExemptionMechanism import ExemptionMechanism

class Cipher:
    DECRYPT_MODE: ClassVar[int]
    ENCRYPT_MODE: ClassVar[int]
    PRIVATE_KEY: ClassVar[int]
    PUBLIC_KEY: ClassVar[int]
    SECRET_KEY: ClassVar[int]
    UNWRAP_MODE: ClassVar[int]
    WRAP_MODE: ClassVar[int]
    def __init__(self, arg0: CipherSpi, arg1: Provider, arg2: str) -> None: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "Cipher": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "Cipher": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "Cipher": ...
    def getProvider(self) -> Provider: ...
    def getAlgorithm(self) -> str: ...
    def getBlockSize(self) -> int: ...
    def getOutputSize(self, arg0: int) -> int: ...
    def getIV(self) -> list[int]: ...
    def getParameters(self) -> AlgorithmParameters: ...
    def getExemptionMechanism(self) -> ExemptionMechanism: ...
    @overload
    def init(self, arg0: int, arg1: Key) -> None: ...
    @overload
    def init(self, arg0: int, arg1: Key, arg2: SecureRandom) -> None: ...
    @overload
    def init(self, arg0: int, arg1: Key, arg2: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, arg0: int, arg1: Key, arg2: AlgorithmParameterSpec, arg3: SecureRandom) -> None: ...
    @overload
    def init(self, arg0: int, arg1: Key, arg2: AlgorithmParameters) -> None: ...
    @overload
    def init(self, arg0: int, arg1: Key, arg2: AlgorithmParameters, arg3: SecureRandom) -> None: ...
    @overload
    def init(self, arg0: int, arg1: Certificate) -> None: ...
    @overload
    def init(self, arg0: int, arg1: Certificate, arg2: SecureRandom) -> None: ...
    @overload
    def update(self, arg0: list[int]) -> list[int]: ...
    @overload
    def update(self, arg0: list[int], arg1: int, arg2: int) -> list[int]: ...
    @overload
    def update(self, arg0: list[int], arg1: int, arg2: int, arg3: list[int]) -> int: ...
    @overload
    def update(self, arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int) -> int: ...
    @overload
    def update(self, arg0: ByteBuffer, arg1: ByteBuffer) -> int: ...
    @overload
    def doFinal(self) -> list[int]: ...
    @overload
    def doFinal(self, arg0: list[int], arg1: int) -> int: ...
    @overload
    def doFinal(self, arg0: list[int]) -> list[int]: ...
    @overload
    def doFinal(self, arg0: list[int], arg1: int, arg2: int) -> list[int]: ...
    @overload
    def doFinal(self, arg0: list[int], arg1: int, arg2: int, arg3: list[int]) -> int: ...
    @overload
    def doFinal(self, arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int) -> int: ...
    @overload
    def doFinal(self, arg0: ByteBuffer, arg1: ByteBuffer) -> int: ...
    def wrap(self, arg0: Key) -> list[int]: ...
    def unwrap(self, arg0: list[int], arg1: str, arg2: int) -> Key: ...
    @staticmethod
    def getMaxAllowedKeyLength(arg0: str) -> int: ...
    @staticmethod
    def getMaxAllowedParameterSpec(arg0: str) -> AlgorithmParameterSpec: ...
    @overload
    def updateAAD(self, arg0: list[int]) -> None: ...
    @overload
    def updateAAD(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    def updateAAD(self, arg0: ByteBuffer) -> None: ...
