from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from javax.crypto.Cipher import Cipher

class CipherInputStream:
    @overload
    def __init__(self, arg0: InputStream, arg1: Cipher) -> None: ...
    @overload
    def __init__(self, arg0: InputStream) -> None: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[int]) -> int: ...
    @overload
    def read(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    def skip(self, arg0: int) -> int: ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def markSupported(self) -> bool: ...
