from typing import Any, ClassVar, overload
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.spec.PKCS8EncodedKeySpec import PKCS8EncodedKeySpec
from javax.crypto.Cipher import Cipher

class EncryptedPrivateKeyInfo:
    @overload
    def __init__(self, arg0: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: AlgorithmParameters, arg1: list[int]) -> None: ...
    def getAlgName(self) -> str: ...
    def getAlgParameters(self) -> AlgorithmParameters: ...
    def getEncryptedData(self) -> list[int]: ...
    @overload
    def getKeySpec(self, arg0: Cipher) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, arg0: Key) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, arg0: Key, arg1: str) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, arg0: Key, arg1: Provider) -> PKCS8EncodedKeySpec: ...
    def getEncoded(self) -> list[int]: ...
