from typing import Any, ClassVar, overload
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.ExemptionMechanismSpi import ExemptionMechanismSpi

class ExemptionMechanism:
    def __init__(self, arg0: ExemptionMechanismSpi, arg1: Provider, arg2: str) -> None: ...
    def getName(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "ExemptionMechanism": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "ExemptionMechanism": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "ExemptionMechanism": ...
    def getProvider(self) -> Provider: ...
    def isCryptoAllowed(self, arg0: Key) -> bool: ...
    def getOutputSize(self, arg0: int) -> int: ...
    @overload
    def init(self, arg0: Key) -> None: ...
    @overload
    def init(self, arg0: Key, arg1: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, arg0: Key, arg1: AlgorithmParameters) -> None: ...
    @overload
    def genExemptionBlob(self) -> list[int]: ...
    @overload
    def genExemptionBlob(self, arg0: list[int]) -> int: ...
    @overload
    def genExemptionBlob(self, arg0: list[int], arg1: int) -> int: ...
