from typing import Any, ClassVar, overload
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.KeyAgreementSpi import KeyAgreementSpi
from javax.crypto.SecretKey import SecretKey

class KeyAgreement:
    def __init__(self, arg0: KeyAgreementSpi, arg1: Provider, arg2: str) -> None: ...
    def getAlgorithm(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "KeyAgreement": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "KeyAgreement": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "KeyAgreement": ...
    def getProvider(self) -> Provider: ...
    @overload
    def init(self, arg0: Key) -> None: ...
    @overload
    def init(self, arg0: Key, arg1: SecureRandom) -> None: ...
    @overload
    def init(self, arg0: Key, arg1: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, arg0: Key, arg1: AlgorithmParameterSpec, arg2: SecureRandom) -> None: ...
    def doPhase(self, arg0: Key, arg1: bool) -> Key: ...
    @overload
    def generateSecret(self) -> list[int]: ...
    @overload
    def generateSecret(self, arg0: list[int], arg1: int) -> int: ...
    @overload
    def generateSecret(self, arg0: str) -> SecretKey: ...
