from typing import Any, ClassVar, overload
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.SecretKey import SecretKey

class KeyGeneratorSpi:
    def __init__(self) -> None: ...
    @overload
    def engineInit(self, arg0: SecureRandom) -> None: ...
    @overload
    def engineInit(self, arg0: AlgorithmParameterSpec, arg1: SecureRandom) -> None: ...
    @overload
    def engineInit(self, arg0: int, arg1: SecureRandom) -> None: ...
    def engineGenerateKey(self) -> SecretKey: ...
