from typing import Any, ClassVar, overload

class Time:
    EPOCH_JULIAN_DAY: ClassVar[int]
    FRIDAY: ClassVar[int]
    HOUR: ClassVar[int]
    MINUTE: ClassVar[int]
    MONDAY: ClassVar[int]
    MONDAY_BEFORE_JULIAN_EPOCH: ClassVar[int]
    MONTH: ClassVar[int]
    MONTH_DAY: ClassVar[int]
    SATURDAY: ClassVar[int]
    SECOND: ClassVar[int]
    SUNDAY: ClassVar[int]
    THURSDAY: ClassVar[int]
    TIMEZONE_UTC: ClassVar[str]
    TUESDAY: ClassVar[int]
    WEDNESDAY: ClassVar[int]
    WEEK_DAY: ClassVar[int]
    WEEK_NUM: ClassVar[int]
    YEAR: ClassVar[int]
    YEAR_DAY: ClassVar[int]
    allDay: bool
    gmtoff: int
    hour: int
    isDst: int
    minute: int
    month: int
    monthDay: int
    second: int
    timezone: str
    weekDay: int
    year: int
    yearDay: int
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "Time") -> None: ...
    def normalize(self, arg0: bool) -> int: ...
    def switchTimezone(self, arg0: str) -> None: ...
    def getActualMaximum(self, arg0: int) -> int: ...
    def clear(self, arg0: str) -> None: ...
    @staticmethod
    def compare(arg0: "Time", arg1: "Time") -> int: ...
    def format(self, arg0: str) -> str: ...
    def toString(self) -> str: ...
    def parse(self, arg0: str) -> bool: ...
    def parse3339(self, arg0: str) -> bool: ...
    @staticmethod
    def getCurrentTimezone() -> str: ...
    def setToNow(self) -> None: ...
    def toMillis(self, arg0: bool) -> int: ...
    @overload
    def set(self, arg0: int) -> None: ...
    @overload
    def set(self, arg0: "Time") -> None: ...
    @overload
    def set(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    @overload
    def set(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def format2445(self) -> str: ...
    def before(self, arg0: "Time") -> bool: ...
    def after(self, arg0: "Time") -> bool: ...
    def getWeekNumber(self) -> int: ...
    def format3339(self, arg0: bool) -> str: ...
    @staticmethod
    def isEpoch(arg0: "Time") -> bool: ...
    @staticmethod
    def getJulianDay(arg0: int, arg1: int) -> int: ...
    def setJulianDay(self, arg0: int) -> int: ...
    @staticmethod
    def getWeeksSinceEpochFromJulianDay(arg0: int, arg1: int) -> int: ...
    @staticmethod
    def getJulianMondayFromWeeksSinceEpoch(arg0: int) -> int: ...
