from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable

class BatchUpdateException:
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: list[int]) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: list[int], arg1: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: list[int], arg2: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: list[int], arg3: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: list[int], arg4: Throwable) -> None: ...
    def getUpdateCounts(self) -> list[int]: ...
