from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream

class Blob:
    def length(self) -> int: ...
    def getBytes(self, arg0: int, arg1: int) -> list[int]: ...
    @overload
    def getBinaryStream(self) -> InputStream: ...
    @overload
    def getBinaryStream(self, arg0: int, arg1: int) -> InputStream: ...
    @overload
    def position(self, arg0: list[int], arg1: int) -> int: ...
    @overload
    def position(self, arg0: "Blob", arg1: int) -> int: ...
    @overload
    def setBytes(self, arg0: int, arg1: list[int]) -> int: ...
    @overload
    def setBytes(self, arg0: int, arg1: list[int], arg2: int, arg3: int) -> int: ...
    def setBinaryStream(self, arg0: int) -> OutputStream: ...
    def truncate(self, arg0: int) -> None: ...
    def free(self) -> None: ...
