from typing import Any, ClassVar, overload
from java.sql.Connection import Connection
from java.sql.ResultSet import ResultSet
from java.sql.RowIdLifetime import RowIdLifetime

class DatabaseMetaData:
    attributeNoNulls: ClassVar[int]
    attributeNullable: ClassVar[int]
    attributeNullableUnknown: ClassVar[int]
    bestRowNotPseudo: ClassVar[int]
    bestRowPseudo: ClassVar[int]
    bestRowSession: ClassVar[int]
    bestRowTemporary: ClassVar[int]
    bestRowTransaction: ClassVar[int]
    bestRowUnknown: ClassVar[int]
    columnNoNulls: ClassVar[int]
    columnNullable: ClassVar[int]
    columnNullableUnknown: ClassVar[int]
    functionColumnIn: ClassVar[int]
    functionColumnInOut: ClassVar[int]
    functionColumnOut: ClassVar[int]
    functionColumnResult: ClassVar[int]
    functionColumnUnknown: ClassVar[int]
    functionNoNulls: ClassVar[int]
    functionNoTable: ClassVar[int]
    functionNullable: ClassVar[int]
    functionNullableUnknown: ClassVar[int]
    functionResultUnknown: ClassVar[int]
    functionReturn: ClassVar[int]
    functionReturnsTable: ClassVar[int]
    importedKeyCascade: ClassVar[int]
    importedKeyInitiallyDeferred: ClassVar[int]
    importedKeyInitiallyImmediate: ClassVar[int]
    importedKeyNoAction: ClassVar[int]
    importedKeyNotDeferrable: ClassVar[int]
    importedKeyRestrict: ClassVar[int]
    importedKeySetDefault: ClassVar[int]
    importedKeySetNull: ClassVar[int]
    procedureColumnIn: ClassVar[int]
    procedureColumnInOut: ClassVar[int]
    procedureColumnOut: ClassVar[int]
    procedureColumnResult: ClassVar[int]
    procedureColumnReturn: ClassVar[int]
    procedureColumnUnknown: ClassVar[int]
    procedureNoNulls: ClassVar[int]
    procedureNoResult: ClassVar[int]
    procedureNullable: ClassVar[int]
    procedureNullableUnknown: ClassVar[int]
    procedureResultUnknown: ClassVar[int]
    procedureReturnsResult: ClassVar[int]
    sqlStateSQL: ClassVar[int]
    sqlStateSQL99: ClassVar[int]
    sqlStateXOpen: ClassVar[int]
    tableIndexClustered: ClassVar[int]
    tableIndexHashed: ClassVar[int]
    tableIndexOther: ClassVar[int]
    tableIndexStatistic: ClassVar[int]
    typeNoNulls: ClassVar[int]
    typeNullable: ClassVar[int]
    typeNullableUnknown: ClassVar[int]
    typePredBasic: ClassVar[int]
    typePredChar: ClassVar[int]
    typePredNone: ClassVar[int]
    typeSearchable: ClassVar[int]
    versionColumnNotPseudo: ClassVar[int]
    versionColumnPseudo: ClassVar[int]
    versionColumnUnknown: ClassVar[int]
    def allProceduresAreCallable(self) -> bool: ...
    def allTablesAreSelectable(self) -> bool: ...
    def getURL(self) -> str: ...
    def getUserName(self) -> str: ...
    def isReadOnly(self) -> bool: ...
    def nullsAreSortedHigh(self) -> bool: ...
    def nullsAreSortedLow(self) -> bool: ...
    def nullsAreSortedAtStart(self) -> bool: ...
    def nullsAreSortedAtEnd(self) -> bool: ...
    def getDatabaseProductName(self) -> str: ...
    def getDatabaseProductVersion(self) -> str: ...
    def getDriverName(self) -> str: ...
    def getDriverVersion(self) -> str: ...
    def getDriverMajorVersion(self) -> int: ...
    def getDriverMinorVersion(self) -> int: ...
    def usesLocalFiles(self) -> bool: ...
    def usesLocalFilePerTable(self) -> bool: ...
    def supportsMixedCaseIdentifiers(self) -> bool: ...
    def storesUpperCaseIdentifiers(self) -> bool: ...
    def storesLowerCaseIdentifiers(self) -> bool: ...
    def storesMixedCaseIdentifiers(self) -> bool: ...
    def supportsMixedCaseQuotedIdentifiers(self) -> bool: ...
    def storesUpperCaseQuotedIdentifiers(self) -> bool: ...
    def storesLowerCaseQuotedIdentifiers(self) -> bool: ...
    def storesMixedCaseQuotedIdentifiers(self) -> bool: ...
    def getIdentifierQuoteString(self) -> str: ...
    def getSQLKeywords(self) -> str: ...
    def getNumericFunctions(self) -> str: ...
    def getStringFunctions(self) -> str: ...
    def getSystemFunctions(self) -> str: ...
    def getTimeDateFunctions(self) -> str: ...
    def getSearchStringEscape(self) -> str: ...
    def getExtraNameCharacters(self) -> str: ...
    def supportsAlterTableWithAddColumn(self) -> bool: ...
    def supportsAlterTableWithDropColumn(self) -> bool: ...
    def supportsColumnAliasing(self) -> bool: ...
    def nullPlusNonNullIsNull(self) -> bool: ...
    @overload
    def supportsConvert(self) -> bool: ...
    @overload
    def supportsConvert(self, arg0: int, arg1: int) -> bool: ...
    def supportsTableCorrelationNames(self) -> bool: ...
    def supportsDifferentTableCorrelationNames(self) -> bool: ...
    def supportsExpressionsInOrderBy(self) -> bool: ...
    def supportsOrderByUnrelated(self) -> bool: ...
    def supportsGroupBy(self) -> bool: ...
    def supportsGroupByUnrelated(self) -> bool: ...
    def supportsGroupByBeyondSelect(self) -> bool: ...
    def supportsLikeEscapeClause(self) -> bool: ...
    def supportsMultipleResultSets(self) -> bool: ...
    def supportsMultipleTransactions(self) -> bool: ...
    def supportsNonNullableColumns(self) -> bool: ...
    def supportsMinimumSQLGrammar(self) -> bool: ...
    def supportsCoreSQLGrammar(self) -> bool: ...
    def supportsExtendedSQLGrammar(self) -> bool: ...
    def supportsANSI92EntryLevelSQL(self) -> bool: ...
    def supportsANSI92IntermediateSQL(self) -> bool: ...
    def supportsANSI92FullSQL(self) -> bool: ...
    def supportsIntegrityEnhancementFacility(self) -> bool: ...
    def supportsOuterJoins(self) -> bool: ...
    def supportsFullOuterJoins(self) -> bool: ...
    def supportsLimitedOuterJoins(self) -> bool: ...
    def getSchemaTerm(self) -> str: ...
    def getProcedureTerm(self) -> str: ...
    def getCatalogTerm(self) -> str: ...
    def isCatalogAtStart(self) -> bool: ...
    def getCatalogSeparator(self) -> str: ...
    def supportsSchemasInDataManipulation(self) -> bool: ...
    def supportsSchemasInProcedureCalls(self) -> bool: ...
    def supportsSchemasInTableDefinitions(self) -> bool: ...
    def supportsSchemasInIndexDefinitions(self) -> bool: ...
    def supportsSchemasInPrivilegeDefinitions(self) -> bool: ...
    def supportsCatalogsInDataManipulation(self) -> bool: ...
    def supportsCatalogsInProcedureCalls(self) -> bool: ...
    def supportsCatalogsInTableDefinitions(self) -> bool: ...
    def supportsCatalogsInIndexDefinitions(self) -> bool: ...
    def supportsCatalogsInPrivilegeDefinitions(self) -> bool: ...
    def supportsPositionedDelete(self) -> bool: ...
    def supportsPositionedUpdate(self) -> bool: ...
    def supportsSelectForUpdate(self) -> bool: ...
    def supportsStoredProcedures(self) -> bool: ...
    def supportsSubqueriesInComparisons(self) -> bool: ...
    def supportsSubqueriesInExists(self) -> bool: ...
    def supportsSubqueriesInIns(self) -> bool: ...
    def supportsSubqueriesInQuantifieds(self) -> bool: ...
    def supportsCorrelatedSubqueries(self) -> bool: ...
    def supportsUnion(self) -> bool: ...
    def supportsUnionAll(self) -> bool: ...
    def supportsOpenCursorsAcrossCommit(self) -> bool: ...
    def supportsOpenCursorsAcrossRollback(self) -> bool: ...
    def supportsOpenStatementsAcrossCommit(self) -> bool: ...
    def supportsOpenStatementsAcrossRollback(self) -> bool: ...
    def getMaxBinaryLiteralLength(self) -> int: ...
    def getMaxCharLiteralLength(self) -> int: ...
    def getMaxColumnNameLength(self) -> int: ...
    def getMaxColumnsInGroupBy(self) -> int: ...
    def getMaxColumnsInIndex(self) -> int: ...
    def getMaxColumnsInOrderBy(self) -> int: ...
    def getMaxColumnsInSelect(self) -> int: ...
    def getMaxColumnsInTable(self) -> int: ...
    def getMaxConnections(self) -> int: ...
    def getMaxCursorNameLength(self) -> int: ...
    def getMaxIndexLength(self) -> int: ...
    def getMaxSchemaNameLength(self) -> int: ...
    def getMaxProcedureNameLength(self) -> int: ...
    def getMaxCatalogNameLength(self) -> int: ...
    def getMaxRowSize(self) -> int: ...
    def doesMaxRowSizeIncludeBlobs(self) -> bool: ...
    def getMaxStatementLength(self) -> int: ...
    def getMaxStatements(self) -> int: ...
    def getMaxTableNameLength(self) -> int: ...
    def getMaxTablesInSelect(self) -> int: ...
    def getMaxUserNameLength(self) -> int: ...
    def getDefaultTransactionIsolation(self) -> int: ...
    def supportsTransactions(self) -> bool: ...
    def supportsTransactionIsolationLevel(self, arg0: int) -> bool: ...
    def supportsDataDefinitionAndDataManipulationTransactions(self) -> bool: ...
    def supportsDataManipulationTransactionsOnly(self) -> bool: ...
    def dataDefinitionCausesTransactionCommit(self) -> bool: ...
    def dataDefinitionIgnoredInTransactions(self) -> bool: ...
    def getProcedures(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getProcedureColumns(self, arg0: str, arg1: str, arg2: str, arg3: str) -> ResultSet: ...
    def getTables(self, arg0: str, arg1: str, arg2: str, arg3: list[str]) -> ResultSet: ...
    @overload
    def getSchemas(self) -> ResultSet: ...
    @overload
    def getSchemas(self, arg0: str, arg1: str) -> ResultSet: ...
    def getCatalogs(self) -> ResultSet: ...
    def getTableTypes(self) -> ResultSet: ...
    def getColumns(self, arg0: str, arg1: str, arg2: str, arg3: str) -> ResultSet: ...
    def getColumnPrivileges(self, arg0: str, arg1: str, arg2: str, arg3: str) -> ResultSet: ...
    def getTablePrivileges(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getBestRowIdentifier(self, arg0: str, arg1: str, arg2: str, arg3: int, arg4: bool) -> ResultSet: ...
    def getVersionColumns(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getPrimaryKeys(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getImportedKeys(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getExportedKeys(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getCrossReference(self, arg0: str, arg1: str, arg2: str, arg3: str, arg4: str, arg5: str) -> ResultSet: ...
    def getTypeInfo(self) -> ResultSet: ...
    def getIndexInfo(self, arg0: str, arg1: str, arg2: str, arg3: bool, arg4: bool) -> ResultSet: ...
    def supportsResultSetType(self, arg0: int) -> bool: ...
    def supportsResultSetConcurrency(self, arg0: int, arg1: int) -> bool: ...
    def ownUpdatesAreVisible(self, arg0: int) -> bool: ...
    def ownDeletesAreVisible(self, arg0: int) -> bool: ...
    def ownInsertsAreVisible(self, arg0: int) -> bool: ...
    def othersUpdatesAreVisible(self, arg0: int) -> bool: ...
    def othersDeletesAreVisible(self, arg0: int) -> bool: ...
    def othersInsertsAreVisible(self, arg0: int) -> bool: ...
    def updatesAreDetected(self, arg0: int) -> bool: ...
    def deletesAreDetected(self, arg0: int) -> bool: ...
    def insertsAreDetected(self, arg0: int) -> bool: ...
    def supportsBatchUpdates(self) -> bool: ...
    def getUDTs(self, arg0: str, arg1: str, arg2: str, arg3: list[int]) -> ResultSet: ...
    def getConnection(self) -> Connection: ...
    def supportsSavepoints(self) -> bool: ...
    def supportsNamedParameters(self) -> bool: ...
    def supportsMultipleOpenResults(self) -> bool: ...
    def supportsGetGeneratedKeys(self) -> bool: ...
    def getSuperTypes(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getSuperTables(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getAttributes(self, arg0: str, arg1: str, arg2: str, arg3: str) -> ResultSet: ...
    def supportsResultSetHoldability(self, arg0: int) -> bool: ...
    def getResultSetHoldability(self) -> int: ...
    def getDatabaseMajorVersion(self) -> int: ...
    def getDatabaseMinorVersion(self) -> int: ...
    def getJDBCMajorVersion(self) -> int: ...
    def getJDBCMinorVersion(self) -> int: ...
    def getSQLStateType(self) -> int: ...
    def locatorsUpdateCopy(self) -> bool: ...
    def supportsStatementPooling(self) -> bool: ...
    def getRowIdLifetime(self) -> RowIdLifetime: ...
    def supportsStoredFunctionsUsingCallSyntax(self) -> bool: ...
    def autoCommitFailureClosesAllResultSets(self) -> bool: ...
    def getClientInfoProperties(self) -> ResultSet: ...
    def getFunctions(self, arg0: str, arg1: str, arg2: str) -> ResultSet: ...
    def getFunctionColumns(self, arg0: str, arg1: str, arg2: str, arg3: str) -> ResultSet: ...
