from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable

class DataTruncation:
    @overload
    def __init__(self, arg0: int, arg1: bool, arg2: bool, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: bool, arg2: bool, arg3: int, arg4: int, arg5: Throwable) -> None: ...
    def getIndex(self) -> int: ...
    def getParameter(self) -> bool: ...
    def getRead(self) -> bool: ...
    def getDataSize(self) -> int: ...
    def getTransferSize(self) -> int: ...
