from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.Reader import Reader
from java.math.BigDecimal import BigDecimal
from java.net.URL import URL
from java.sql.Array import Array
from java.sql.Blob import Blob
from java.sql.Clob import Clob
from java.sql.Date import Date
from java.sql.NClob import NClob
from java.sql.ParameterMetaData import ParameterMetaData
from java.sql.Ref import Ref
from java.sql.ResultSet import ResultSet
from java.sql.ResultSetMetaData import ResultSetMetaData
from java.sql.RowId import RowId
from java.sql.SQLXML import SQLXML
from java.sql.Time import Time
from java.sql.Timestamp import Timestamp
from java.util.Calendar import Calendar

class PreparedStatement:
    def executeQuery(self) -> ResultSet: ...
    def executeUpdate(self) -> int: ...
    @overload
    def setNull(self, arg0: int, arg1: int) -> None: ...
    @overload
    def setNull(self, arg0: int, arg1: int, arg2: str) -> None: ...
    def setBoolean(self, arg0: int, arg1: bool) -> None: ...
    def setByte(self, arg0: int, arg1: int) -> None: ...
    def setShort(self, arg0: int, arg1: int) -> None: ...
    def setInt(self, arg0: int, arg1: int) -> None: ...
    def setLong(self, arg0: int, arg1: int) -> None: ...
    def setFloat(self, arg0: int, arg1: float) -> None: ...
    def setDouble(self, arg0: int, arg1: float) -> None: ...
    def setBigDecimal(self, arg0: int, arg1: BigDecimal) -> None: ...
    def setString(self, arg0: int, arg1: str) -> None: ...
    def setBytes(self, arg0: int, arg1: list[int]) -> None: ...
    @overload
    def setDate(self, arg0: int, arg1: Date) -> None: ...
    @overload
    def setDate(self, arg0: int, arg1: Date, arg2: Calendar) -> None: ...
    @overload
    def setTime(self, arg0: int, arg1: Time) -> None: ...
    @overload
    def setTime(self, arg0: int, arg1: Time, arg2: Calendar) -> None: ...
    @overload
    def setTimestamp(self, arg0: int, arg1: Timestamp) -> None: ...
    @overload
    def setTimestamp(self, arg0: int, arg1: Timestamp, arg2: Calendar) -> None: ...
    @overload
    def setAsciiStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def setAsciiStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def setAsciiStream(self, arg0: int, arg1: InputStream) -> None: ...
    def setUnicodeStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def setBinaryStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def setBinaryStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def setBinaryStream(self, arg0: int, arg1: InputStream) -> None: ...
    def clearParameters(self) -> None: ...
    @overload
    def setObject(self, arg0: int, arg1: Any, arg2: int) -> None: ...
    @overload
    def setObject(self, arg0: int, arg1: Any) -> None: ...
    @overload
    def setObject(self, arg0: int, arg1: Any, arg2: int, arg3: int) -> None: ...
    def execute(self) -> bool: ...
    def addBatch(self) -> None: ...
    @overload
    def setCharacterStream(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def setCharacterStream(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def setCharacterStream(self, arg0: int, arg1: Reader) -> None: ...
    def setRef(self, arg0: int, arg1: Ref) -> None: ...
    @overload
    def setBlob(self, arg0: int, arg1: Blob) -> None: ...
    @overload
    def setBlob(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def setBlob(self, arg0: int, arg1: InputStream) -> None: ...
    @overload
    def setClob(self, arg0: int, arg1: Clob) -> None: ...
    @overload
    def setClob(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def setClob(self, arg0: int, arg1: Reader) -> None: ...
    def setArray(self, arg0: int, arg1: Array) -> None: ...
    def getMetaData(self) -> ResultSetMetaData: ...
    def setURL(self, arg0: int, arg1: URL) -> None: ...
    def getParameterMetaData(self) -> ParameterMetaData: ...
    def setRowId(self, arg0: int, arg1: RowId) -> None: ...
    def setNString(self, arg0: int, arg1: str) -> None: ...
    @overload
    def setNCharacterStream(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def setNCharacterStream(self, arg0: int, arg1: Reader) -> None: ...
    @overload
    def setNClob(self, arg0: int, arg1: NClob) -> None: ...
    @overload
    def setNClob(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def setNClob(self, arg0: int, arg1: Reader) -> None: ...
    def setSQLXML(self, arg0: int, arg1: SQLXML) -> None: ...
