from typing import Any, ClassVar, overload

class Ref:
    def getBaseTypeName(self) -> str: ...
    @overload
    def getObject(self, arg0: dict) -> Any: ...
    @overload
    def getObject(self) -> Any: ...
    def setObject(self, arg0: Any) -> None: ...
