from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.Reader import Reader
from java.math.BigDecimal import BigDecimal
from java.net.URL import URL
from java.sql.Array import Array
from java.sql.Blob import Blob
from java.sql.Clob import Clob
from java.sql.Date import Date
from java.sql.NClob import NClob
from java.sql.Ref import Ref
from java.sql.ResultSetMetaData import ResultSetMetaData
from java.sql.RowId import RowId
from java.sql.SQLWarning import SQLWarning
from java.sql.SQLXML import SQLXML
from java.sql.Statement import Statement
from java.sql.Time import Time
from java.sql.Timestamp import Timestamp
from java.util.Calendar import Calendar

class ResultSet:
    CLOSE_CURSORS_AT_COMMIT: ClassVar[int]
    CONCUR_READ_ONLY: ClassVar[int]
    CONCUR_UPDATABLE: ClassVar[int]
    FETCH_FORWARD: ClassVar[int]
    FETCH_REVERSE: ClassVar[int]
    FETCH_UNKNOWN: ClassVar[int]
    HOLD_CURSORS_OVER_COMMIT: ClassVar[int]
    TYPE_FORWARD_ONLY: ClassVar[int]
    TYPE_SCROLL_INSENSITIVE: ClassVar[int]
    TYPE_SCROLL_SENSITIVE: ClassVar[int]
    def next(self) -> bool: ...
    def close(self) -> None: ...
    def wasNull(self) -> bool: ...
    @overload
    def getString(self, arg0: int) -> str: ...
    @overload
    def getString(self, arg0: str) -> str: ...
    @overload
    def getBoolean(self, arg0: int) -> bool: ...
    @overload
    def getBoolean(self, arg0: str) -> bool: ...
    @overload
    def getByte(self, arg0: int) -> int: ...
    @overload
    def getByte(self, arg0: str) -> int: ...
    @overload
    def getShort(self, arg0: int) -> int: ...
    @overload
    def getShort(self, arg0: str) -> int: ...
    @overload
    def getInt(self, arg0: int) -> int: ...
    @overload
    def getInt(self, arg0: str) -> int: ...
    @overload
    def getLong(self, arg0: int) -> int: ...
    @overload
    def getLong(self, arg0: str) -> int: ...
    @overload
    def getFloat(self, arg0: int) -> float: ...
    @overload
    def getFloat(self, arg0: str) -> float: ...
    @overload
    def getDouble(self, arg0: int) -> float: ...
    @overload
    def getDouble(self, arg0: str) -> float: ...
    @overload
    def getBigDecimal(self, arg0: int, arg1: int) -> BigDecimal: ...
    @overload
    def getBigDecimal(self, arg0: str, arg1: int) -> BigDecimal: ...
    @overload
    def getBigDecimal(self, arg0: int) -> BigDecimal: ...
    @overload
    def getBigDecimal(self, arg0: str) -> BigDecimal: ...
    @overload
    def getBytes(self, arg0: int) -> list[int]: ...
    @overload
    def getBytes(self, arg0: str) -> list[int]: ...
    @overload
    def getDate(self, arg0: int) -> Date: ...
    @overload
    def getDate(self, arg0: str) -> Date: ...
    @overload
    def getDate(self, arg0: int, arg1: Calendar) -> Date: ...
    @overload
    def getDate(self, arg0: str, arg1: Calendar) -> Date: ...
    @overload
    def getTime(self, arg0: int) -> Time: ...
    @overload
    def getTime(self, arg0: str) -> Time: ...
    @overload
    def getTime(self, arg0: int, arg1: Calendar) -> Time: ...
    @overload
    def getTime(self, arg0: str, arg1: Calendar) -> Time: ...
    @overload
    def getTimestamp(self, arg0: int) -> Timestamp: ...
    @overload
    def getTimestamp(self, arg0: str) -> Timestamp: ...
    @overload
    def getTimestamp(self, arg0: int, arg1: Calendar) -> Timestamp: ...
    @overload
    def getTimestamp(self, arg0: str, arg1: Calendar) -> Timestamp: ...
    @overload
    def getAsciiStream(self, arg0: int) -> InputStream: ...
    @overload
    def getAsciiStream(self, arg0: str) -> InputStream: ...
    @overload
    def getUnicodeStream(self, arg0: int) -> InputStream: ...
    @overload
    def getUnicodeStream(self, arg0: str) -> InputStream: ...
    @overload
    def getBinaryStream(self, arg0: int) -> InputStream: ...
    @overload
    def getBinaryStream(self, arg0: str) -> InputStream: ...
    def getWarnings(self) -> SQLWarning: ...
    def clearWarnings(self) -> None: ...
    def getCursorName(self) -> str: ...
    def getMetaData(self) -> ResultSetMetaData: ...
    @overload
    def getObject(self, arg0: int) -> Any: ...
    @overload
    def getObject(self, arg0: str) -> Any: ...
    @overload
    def getObject(self, arg0: int, arg1: dict) -> Any: ...
    @overload
    def getObject(self, arg0: str, arg1: dict) -> Any: ...
    def findColumn(self, arg0: str) -> int: ...
    @overload
    def getCharacterStream(self, arg0: int) -> Reader: ...
    @overload
    def getCharacterStream(self, arg0: str) -> Reader: ...
    def isBeforeFirst(self) -> bool: ...
    def isAfterLast(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def isLast(self) -> bool: ...
    def beforeFirst(self) -> None: ...
    def afterLast(self) -> None: ...
    def first(self) -> bool: ...
    def last(self) -> bool: ...
    def getRow(self) -> int: ...
    def absolute(self, arg0: int) -> bool: ...
    def relative(self, arg0: int) -> bool: ...
    def previous(self) -> bool: ...
    def setFetchDirection(self, arg0: int) -> None: ...
    def getFetchDirection(self) -> int: ...
    def setFetchSize(self, arg0: int) -> None: ...
    def getFetchSize(self) -> int: ...
    def getType(self) -> int: ...
    def getConcurrency(self) -> int: ...
    def rowUpdated(self) -> bool: ...
    def rowInserted(self) -> bool: ...
    def rowDeleted(self) -> bool: ...
    @overload
    def updateNull(self, arg0: int) -> None: ...
    @overload
    def updateNull(self, arg0: str) -> None: ...
    @overload
    def updateBoolean(self, arg0: int, arg1: bool) -> None: ...
    @overload
    def updateBoolean(self, arg0: str, arg1: bool) -> None: ...
    @overload
    def updateByte(self, arg0: int, arg1: int) -> None: ...
    @overload
    def updateByte(self, arg0: str, arg1: int) -> None: ...
    @overload
    def updateShort(self, arg0: int, arg1: int) -> None: ...
    @overload
    def updateShort(self, arg0: str, arg1: int) -> None: ...
    @overload
    def updateInt(self, arg0: int, arg1: int) -> None: ...
    @overload
    def updateInt(self, arg0: str, arg1: int) -> None: ...
    @overload
    def updateLong(self, arg0: int, arg1: int) -> None: ...
    @overload
    def updateLong(self, arg0: str, arg1: int) -> None: ...
    @overload
    def updateFloat(self, arg0: int, arg1: float) -> None: ...
    @overload
    def updateFloat(self, arg0: str, arg1: float) -> None: ...
    @overload
    def updateDouble(self, arg0: int, arg1: float) -> None: ...
    @overload
    def updateDouble(self, arg0: str, arg1: float) -> None: ...
    @overload
    def updateBigDecimal(self, arg0: int, arg1: BigDecimal) -> None: ...
    @overload
    def updateBigDecimal(self, arg0: str, arg1: BigDecimal) -> None: ...
    @overload
    def updateString(self, arg0: int, arg1: str) -> None: ...
    @overload
    def updateString(self, arg0: str, arg1: str) -> None: ...
    @overload
    def updateBytes(self, arg0: int, arg1: list[int]) -> None: ...
    @overload
    def updateBytes(self, arg0: str, arg1: list[int]) -> None: ...
    @overload
    def updateDate(self, arg0: int, arg1: Date) -> None: ...
    @overload
    def updateDate(self, arg0: str, arg1: Date) -> None: ...
    @overload
    def updateTime(self, arg0: int, arg1: Time) -> None: ...
    @overload
    def updateTime(self, arg0: str, arg1: Time) -> None: ...
    @overload
    def updateTimestamp(self, arg0: int, arg1: Timestamp) -> None: ...
    @overload
    def updateTimestamp(self, arg0: str, arg1: Timestamp) -> None: ...
    @overload
    def updateAsciiStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateAsciiStream(self, arg0: str, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateAsciiStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateAsciiStream(self, arg0: str, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateAsciiStream(self, arg0: int, arg1: InputStream) -> None: ...
    @overload
    def updateAsciiStream(self, arg0: str, arg1: InputStream) -> None: ...
    @overload
    def updateBinaryStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateBinaryStream(self, arg0: str, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateBinaryStream(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateBinaryStream(self, arg0: str, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateBinaryStream(self, arg0: int, arg1: InputStream) -> None: ...
    @overload
    def updateBinaryStream(self, arg0: str, arg1: InputStream) -> None: ...
    @overload
    def updateCharacterStream(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateCharacterStream(self, arg0: str, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateCharacterStream(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateCharacterStream(self, arg0: str, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateCharacterStream(self, arg0: int, arg1: Reader) -> None: ...
    @overload
    def updateCharacterStream(self, arg0: str, arg1: Reader) -> None: ...
    @overload
    def updateObject(self, arg0: int, arg1: Any, arg2: int) -> None: ...
    @overload
    def updateObject(self, arg0: int, arg1: Any) -> None: ...
    @overload
    def updateObject(self, arg0: str, arg1: Any, arg2: int) -> None: ...
    @overload
    def updateObject(self, arg0: str, arg1: Any) -> None: ...
    def insertRow(self) -> None: ...
    def updateRow(self) -> None: ...
    def deleteRow(self) -> None: ...
    def refreshRow(self) -> None: ...
    def cancelRowUpdates(self) -> None: ...
    def moveToInsertRow(self) -> None: ...
    def moveToCurrentRow(self) -> None: ...
    def getStatement(self) -> Statement: ...
    @overload
    def getRef(self, arg0: int) -> Ref: ...
    @overload
    def getRef(self, arg0: str) -> Ref: ...
    @overload
    def getBlob(self, arg0: int) -> Blob: ...
    @overload
    def getBlob(self, arg0: str) -> Blob: ...
    @overload
    def getClob(self, arg0: int) -> Clob: ...
    @overload
    def getClob(self, arg0: str) -> Clob: ...
    @overload
    def getArray(self, arg0: int) -> Array: ...
    @overload
    def getArray(self, arg0: str) -> Array: ...
    @overload
    def getURL(self, arg0: int) -> URL: ...
    @overload
    def getURL(self, arg0: str) -> URL: ...
    @overload
    def updateRef(self, arg0: int, arg1: Ref) -> None: ...
    @overload
    def updateRef(self, arg0: str, arg1: Ref) -> None: ...
    @overload
    def updateBlob(self, arg0: int, arg1: Blob) -> None: ...
    @overload
    def updateBlob(self, arg0: str, arg1: Blob) -> None: ...
    @overload
    def updateBlob(self, arg0: int, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateBlob(self, arg0: str, arg1: InputStream, arg2: int) -> None: ...
    @overload
    def updateBlob(self, arg0: int, arg1: InputStream) -> None: ...
    @overload
    def updateBlob(self, arg0: str, arg1: InputStream) -> None: ...
    @overload
    def updateClob(self, arg0: int, arg1: Clob) -> None: ...
    @overload
    def updateClob(self, arg0: str, arg1: Clob) -> None: ...
    @overload
    def updateClob(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateClob(self, arg0: str, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateClob(self, arg0: int, arg1: Reader) -> None: ...
    @overload
    def updateClob(self, arg0: str, arg1: Reader) -> None: ...
    @overload
    def updateArray(self, arg0: int, arg1: Array) -> None: ...
    @overload
    def updateArray(self, arg0: str, arg1: Array) -> None: ...
    @overload
    def getRowId(self, arg0: int) -> RowId: ...
    @overload
    def getRowId(self, arg0: str) -> RowId: ...
    @overload
    def updateRowId(self, arg0: int, arg1: RowId) -> None: ...
    @overload
    def updateRowId(self, arg0: str, arg1: RowId) -> None: ...
    def getHoldability(self) -> int: ...
    def isClosed(self) -> bool: ...
    @overload
    def updateNString(self, arg0: int, arg1: str) -> None: ...
    @overload
    def updateNString(self, arg0: str, arg1: str) -> None: ...
    @overload
    def updateNClob(self, arg0: int, arg1: NClob) -> None: ...
    @overload
    def updateNClob(self, arg0: str, arg1: NClob) -> None: ...
    @overload
    def updateNClob(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateNClob(self, arg0: str, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateNClob(self, arg0: int, arg1: Reader) -> None: ...
    @overload
    def updateNClob(self, arg0: str, arg1: Reader) -> None: ...
    @overload
    def getNClob(self, arg0: int) -> NClob: ...
    @overload
    def getNClob(self, arg0: str) -> NClob: ...
    @overload
    def getSQLXML(self, arg0: int) -> SQLXML: ...
    @overload
    def getSQLXML(self, arg0: str) -> SQLXML: ...
    @overload
    def updateSQLXML(self, arg0: int, arg1: SQLXML) -> None: ...
    @overload
    def updateSQLXML(self, arg0: str, arg1: SQLXML) -> None: ...
    @overload
    def getNString(self, arg0: int) -> str: ...
    @overload
    def getNString(self, arg0: str) -> str: ...
    @overload
    def getNCharacterStream(self, arg0: int) -> Reader: ...
    @overload
    def getNCharacterStream(self, arg0: str) -> Reader: ...
    @overload
    def updateNCharacterStream(self, arg0: int, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateNCharacterStream(self, arg0: str, arg1: Reader, arg2: int) -> None: ...
    @overload
    def updateNCharacterStream(self, arg0: int, arg1: Reader) -> None: ...
    @overload
    def updateNCharacterStream(self, arg0: str, arg1: Reader) -> None: ...
