from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable

class SQLClientInfoException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: dict) -> None: ...
    @overload
    def __init__(self, arg0: dict, arg1: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: dict) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: dict, arg2: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: dict) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: dict, arg3: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: dict) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: dict, arg4: Throwable) -> None: ...
    def getFailedProperties(self) -> dict: ...
