from typing import Any, ClassVar, overload
from java.sql.SQLInput import SQLInput
from java.sql.SQLOutput import SQLOutput

class SQLData:
    def getSQLTypeName(self) -> str: ...
    def readSQL(self, arg0: SQLInput, arg1: str) -> None: ...
    def writeSQL(self, arg0: SQLOutput) -> None: ...
