from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.Reader import Reader
from java.math.BigDecimal import BigDecimal
from java.net.URL import URL
from java.sql.Array import Array
from java.sql.Blob import Blob
from java.sql.Clob import Clob
from java.sql.Date import Date
from java.sql.NClob import NClob
from java.sql.Ref import Ref
from java.sql.RowId import RowId
from java.sql.SQLData import SQLData
from java.sql.SQLXML import SQLXML
from java.sql.Struct import Struct
from java.sql.Time import Time
from java.sql.Timestamp import Timestamp

class SQLOutput:
    def writeString(self, arg0: str) -> None: ...
    def writeBoolean(self, arg0: bool) -> None: ...
    def writeByte(self, arg0: int) -> None: ...
    def writeShort(self, arg0: int) -> None: ...
    def writeInt(self, arg0: int) -> None: ...
    def writeLong(self, arg0: int) -> None: ...
    def writeFloat(self, arg0: float) -> None: ...
    def writeDouble(self, arg0: float) -> None: ...
    def writeBigDecimal(self, arg0: BigDecimal) -> None: ...
    def writeBytes(self, arg0: list[int]) -> None: ...
    def writeDate(self, arg0: Date) -> None: ...
    def writeTime(self, arg0: Time) -> None: ...
    def writeTimestamp(self, arg0: Timestamp) -> None: ...
    def writeCharacterStream(self, arg0: Reader) -> None: ...
    def writeAsciiStream(self, arg0: InputStream) -> None: ...
    def writeBinaryStream(self, arg0: InputStream) -> None: ...
    def writeObject(self, arg0: SQLData) -> None: ...
    def writeRef(self, arg0: Ref) -> None: ...
    def writeBlob(self, arg0: Blob) -> None: ...
    def writeClob(self, arg0: Clob) -> None: ...
    def writeStruct(self, arg0: Struct) -> None: ...
    def writeArray(self, arg0: Array) -> None: ...
    def writeURL(self, arg0: URL) -> None: ...
    def writeNString(self, arg0: str) -> None: ...
    def writeNClob(self, arg0: NClob) -> None: ...
    def writeRowId(self, arg0: RowId) -> None: ...
    def writeSQLXML(self, arg0: SQLXML) -> None: ...
