from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable

class SQLRecoverableException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: Throwable) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: Throwable) -> None: ...
