from typing import Any, ClassVar, overload
from java.sql.Connection import Connection
from java.sql.ResultSet import ResultSet
from java.sql.SQLWarning import SQLWarning

class Statement:
    CLOSE_ALL_RESULTS: ClassVar[int]
    CLOSE_CURRENT_RESULT: ClassVar[int]
    EXECUTE_FAILED: ClassVar[int]
    KEEP_CURRENT_RESULT: ClassVar[int]
    NO_GENERATED_KEYS: ClassVar[int]
    RETURN_GENERATED_KEYS: ClassVar[int]
    SUCCESS_NO_INFO: ClassVar[int]
    def executeQuery(self, arg0: str) -> ResultSet: ...
    @overload
    def executeUpdate(self, arg0: str) -> int: ...
    @overload
    def executeUpdate(self, arg0: str, arg1: int) -> int: ...
    @overload
    def executeUpdate(self, arg0: str, arg1: list[int]) -> int: ...
    @overload
    def executeUpdate(self, arg0: str, arg1: list[str]) -> int: ...
    def close(self) -> None: ...
    def getMaxFieldSize(self) -> int: ...
    def setMaxFieldSize(self, arg0: int) -> None: ...
    def getMaxRows(self) -> int: ...
    def setMaxRows(self, arg0: int) -> None: ...
    def setEscapeProcessing(self, arg0: bool) -> None: ...
    def getQueryTimeout(self) -> int: ...
    def setQueryTimeout(self, arg0: int) -> None: ...
    def cancel(self) -> None: ...
    def getWarnings(self) -> SQLWarning: ...
    def clearWarnings(self) -> None: ...
    def setCursorName(self, arg0: str) -> None: ...
    @overload
    def execute(self, arg0: str) -> bool: ...
    @overload
    def execute(self, arg0: str, arg1: int) -> bool: ...
    @overload
    def execute(self, arg0: str, arg1: list[int]) -> bool: ...
    @overload
    def execute(self, arg0: str, arg1: list[str]) -> bool: ...
    def getResultSet(self) -> ResultSet: ...
    def getUpdateCount(self) -> int: ...
    @overload
    def getMoreResults(self) -> bool: ...
    @overload
    def getMoreResults(self, arg0: int) -> bool: ...
    def setFetchDirection(self, arg0: int) -> None: ...
    def getFetchDirection(self) -> int: ...
    def setFetchSize(self, arg0: int) -> None: ...
    def getFetchSize(self) -> int: ...
    def getResultSetConcurrency(self) -> int: ...
    def getResultSetType(self) -> int: ...
    def addBatch(self, arg0: str) -> None: ...
    def clearBatch(self) -> None: ...
    def executeBatch(self) -> list[int]: ...
    def getConnection(self) -> Connection: ...
    def getGeneratedKeys(self) -> ResultSet: ...
    def getResultSetHoldability(self) -> int: ...
    def isClosed(self) -> bool: ...
    def setPoolable(self, arg0: bool) -> None: ...
    def isPoolable(self) -> bool: ...
