from typing import Any, ClassVar, overload
from java.util.Date import Date

class Timestamp:
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    def setTime(self, arg0: int) -> None: ...
    def getTime(self) -> int: ...
    @staticmethod
    def valueOf(arg0: str) -> "Timestamp": ...
    def toString(self) -> str: ...
    def getNanos(self) -> int: ...
    def setNanos(self, arg0: int) -> None: ...
    @overload
    def equals(self, arg0: "Timestamp") -> bool: ...
    @overload
    def equals(self, arg0: Any) -> bool: ...
    def before(self, arg0: "Timestamp") -> bool: ...
    def after(self, arg0: "Timestamp") -> bool: ...
    @overload
    def compareTo(self, arg0: "Timestamp") -> int: ...
    @overload
    def compareTo(self, arg0: Date) -> int: ...
    def hashCode(self) -> int: ...
