from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class MloLink:
    CREATOR: ClassVar[Creator]
    INVALID_MLO_LINK_ID: ClassVar[int]
    MLO_LINK_STATE_ACTIVE: ClassVar[int]
    MLO_LINK_STATE_IDLE: ClassVar[int]
    MLO_LINK_STATE_INVALID: ClassVar[int]
    MLO_LINK_STATE_UNASSOCIATED: ClassVar[int]
    def __init__(self) -> None: ...
    def getBand(self) -> int: ...
    def getChannel(self) -> int: ...
    def getLinkId(self) -> int: ...
    def getState(self) -> int: ...
    def getApMacAddress(self) -> MacAddress: ...
    def getStaMacAddress(self) -> MacAddress: ...
    def getRxLinkSpeedMbps(self) -> int: ...
    def getTxLinkSpeedMbps(self) -> int: ...
    def getRssi(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
