from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.WifiSsid import WifiSsid
from android.os.Parcel import Parcel
from java.nio.ByteBuffer import ByteBuffer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ScanResult:
    CHANNEL_WIDTH_160MHZ: ClassVar[int]
    CHANNEL_WIDTH_20MHZ: ClassVar[int]
    CHANNEL_WIDTH_320MHZ: ClassVar[int]
    CHANNEL_WIDTH_40MHZ: ClassVar[int]
    CHANNEL_WIDTH_80MHZ: ClassVar[int]
    CHANNEL_WIDTH_80MHZ_PLUS_MHZ: ClassVar[int]
    CREATOR: ClassVar[Creator]
    PREAMBLE_EHT: ClassVar[int]
    PREAMBLE_HE: ClassVar[int]
    PREAMBLE_HT: ClassVar[int]
    PREAMBLE_LEGACY: ClassVar[int]
    PREAMBLE_VHT: ClassVar[int]
    UNSPECIFIED: ClassVar[int]
    WIFI_BAND_24_GHZ: ClassVar[int]
    WIFI_BAND_5_GHZ: ClassVar[int]
    WIFI_BAND_60_GHZ: ClassVar[int]
    WIFI_BAND_6_GHZ: ClassVar[int]
    WIFI_STANDARD_11AC: ClassVar[int]
    WIFI_STANDARD_11AD: ClassVar[int]
    WIFI_STANDARD_11AX: ClassVar[int]
    WIFI_STANDARD_11BE: ClassVar[int]
    WIFI_STANDARD_11N: ClassVar[int]
    WIFI_STANDARD_LEGACY: ClassVar[int]
    WIFI_STANDARD_UNKNOWN: ClassVar[int]
    BSSID: str
    SSID: str
    capabilities: str
    centerFreq0: int
    centerFreq1: int
    channelWidth: int
    frequency: int
    level: int
    operatorFriendlyName: str
    timestamp: int
    venueName: str
    @overload
    def __init__(self, arg0: "ScanResult") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getWifiSsid(self) -> WifiSsid: ...
    def getApMldMacAddress(self) -> MacAddress: ...
    def getApMloLinkId(self) -> int: ...
    def getAffiliatedMloLinks(self) -> list: ...
    def getWifiStandard(self) -> int: ...
    def is80211mcResponder(self) -> bool: ...
    def is80211azNtbResponder(self) -> bool: ...
    def isPasspointNetwork(self) -> bool: ...
    def isTwtResponder(self) -> bool: ...
    @staticmethod
    def convertChannelToFrequencyMhzIfSupported(arg0: int, arg1: int) -> int: ...
    @staticmethod
    def convertFrequencyMhzToChannelIfSupported(arg0: int) -> int: ...
    def getInformationElements(self) -> list: ...
    def getSecurityTypes(self) -> list[int]: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class InformationElement:
        CREATOR: ClassVar[Creator]
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: list[int]) -> None: ...
        @overload
        def __init__(self, arg0: "InformationElement") -> None: ...
        def getId(self) -> int: ...
        def getIdExt(self) -> int: ...
        def getBytes(self) -> ByteBuffer: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
