from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.WifiSsid import WifiSsid
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SoftApConfiguration:
    CREATOR: ClassVar[Creator]
    SECURITY_TYPE_OPEN: ClassVar[int]
    SECURITY_TYPE_WPA2_PSK: ClassVar[int]
    SECURITY_TYPE_WPA3_OWE: ClassVar[int]
    SECURITY_TYPE_WPA3_OWE_TRANSITION: ClassVar[int]
    SECURITY_TYPE_WPA3_SAE: ClassVar[int]
    SECURITY_TYPE_WPA3_SAE_TRANSITION: ClassVar[int]
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSsid(self) -> str: ...
    def getWifiSsid(self) -> WifiSsid: ...
    def getBssid(self) -> MacAddress: ...
    def getPassphrase(self) -> str: ...
    def isHiddenSsid(self) -> bool: ...
    def getSecurityType(self) -> int: ...
