from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.WifiEnterpriseConfig import WifiEnterpriseConfig
from android.net.wifi.WifiSsid import WifiSsid
from android.net.wifi.hotspot2.PasspointConfiguration import PasspointConfiguration
from android.os.Parcel import Parcel
from android.os.ParcelUuid import ParcelUuid

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class WifiNetworkSuggestion:
    CREATOR: ClassVar[Creator]
    RANDOMIZATION_NON_PERSISTENT: ClassVar[int]
    RANDOMIZATION_PERSISTENT: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
    def getBssid(self) -> MacAddress: ...
    def isCredentialSharedWithUser(self) -> bool: ...
    def isAppInteractionRequired(self) -> bool: ...
    def isEnhancedOpen(self) -> bool: ...
    def isHiddenSsid(self) -> bool: ...
    def isInitialAutojoinEnabled(self) -> bool: ...
    def isMetered(self) -> bool: ...
    def isUserInteractionRequired(self) -> bool: ...
    def getPasspointConfig(self) -> PasspointConfiguration: ...
    def getPriority(self) -> int: ...
    def getSsid(self) -> str: ...
    def getWifiSsid(self) -> WifiSsid: ...
    def isUntrusted(self) -> bool: ...
    def isRestricted(self) -> bool: ...
    def isCarrierMerged(self) -> bool: ...
    def getEnterpriseConfig(self) -> WifiEnterpriseConfig: ...
    def getPassphrase(self) -> str: ...
    def getPriorityGroup(self) -> int: ...
    def getSubscriptionId(self) -> int: ...
    def getMacRandomizationSetting(self) -> int: ...
    def getSubscriptionGroup(self) -> ParcelUuid: ...
    def isWifi7Enabled(self) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setSsid(self, arg0: str) -> "Builder": ...
        def setWifiSsid(self, arg0: WifiSsid) -> "Builder": ...
        def setBssid(self, arg0: MacAddress) -> "Builder": ...
        def setIsEnhancedOpen(self, arg0: bool) -> "Builder": ...
        def setWpa2Passphrase(self, arg0: str) -> "Builder": ...
        def setWpa3Passphrase(self, arg0: str) -> "Builder": ...
        def setWpa2EnterpriseConfig(self, arg0: WifiEnterpriseConfig) -> "Builder": ...
        def setWpa3EnterpriseConfig(self, arg0: WifiEnterpriseConfig) -> "Builder": ...
        def setWpa3EnterpriseStandardModeConfig(self, arg0: WifiEnterpriseConfig) -> "Builder": ...
        def setWpa3Enterprise192BitModeConfig(self, arg0: WifiEnterpriseConfig) -> "Builder": ...
        def setPasspointConfig(self, arg0: PasspointConfiguration) -> "Builder": ...
        def setSubscriptionId(self, arg0: int) -> "Builder": ...
        def setSubscriptionGroup(self, arg0: ParcelUuid) -> "Builder": ...
        def setPriorityGroup(self, arg0: int) -> "Builder": ...
        def setWapiPassphrase(self, arg0: str) -> "Builder": ...
        def setWapiEnterpriseConfig(self, arg0: WifiEnterpriseConfig) -> "Builder": ...
        def setIsHiddenSsid(self, arg0: bool) -> "Builder": ...
        def setMacRandomizationSetting(self, arg0: int) -> "Builder": ...
        def setIsAppInteractionRequired(self, arg0: bool) -> "Builder": ...
        def setIsUserInteractionRequired(self, arg0: bool) -> "Builder": ...
        def setPriority(self, arg0: int) -> "Builder": ...
        def setIsMetered(self, arg0: bool) -> "Builder": ...
        def setCredentialSharedWithUser(self, arg0: bool) -> "Builder": ...
        def setIsInitialAutojoinEnabled(self, arg0: bool) -> "Builder": ...
        def setUntrusted(self, arg0: bool) -> "Builder": ...
        def setRestricted(self, arg0: bool) -> "Builder": ...
        def setWifi7Enabled(self, arg0: bool) -> "Builder": ...
        def setCarrierMerged(self, arg0: bool) -> "Builder": ...
        def setIsWpa3SaeH2eOnlyModeEnabled(self, arg0: bool) -> "Builder": ...
        def build(self) -> "WifiNetworkSuggestion": ...
