from typing import Any, ClassVar, overload
from android.net.DhcpInfo import DhcpInfo
from android.net.wifi.SoftApConfiguration import SoftApConfiguration
from android.net.wifi.WifiConfiguration import WifiConfiguration
from android.net.wifi.WifiInfo import WifiInfo
from android.net.wifi.WifiNetworkSpecifier import WifiNetworkSpecifier
from android.net.wifi.WifiNetworkSuggestion import WifiNetworkSuggestion
from android.net.wifi.WifiSsid import WifiSsid
from android.net.wifi.WpsInfo import WpsInfo
from android.net.wifi.hotspot2.PasspointConfiguration import PasspointConfiguration
from android.os.Handler import Handler
from android.os.Parcel import Parcel
from android.os.WorkSource import WorkSource
from java.net.InetAddress import InetAddress
from java.util.concurrent.Executor import Executor
from java.util.function.BiConsumer import BiConsumer
from java.util.function.Consumer import Consumer
from java.util.function.IntConsumer import IntConsumer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class WifiManager:
    ACTION_PICK_WIFI_NETWORK: ClassVar[str]
    ACTION_REMOVE_SUGGESTION_DISCONNECT: ClassVar[int]
    ACTION_REMOVE_SUGGESTION_LINGER: ClassVar[int]
    ACTION_REQUEST_SCAN_ALWAYS_AVAILABLE: ClassVar[str]
    ACTION_WIFI_NETWORK_SUGGESTION_POST_CONNECTION: ClassVar[str]
    ACTION_WIFI_SCAN_AVAILABILITY_CHANGED: ClassVar[str]
    CHANNEL_DATA_KEY_FREQUENCY_MHZ: ClassVar[str]
    CHANNEL_DATA_KEY_NUM_AP: ClassVar[str]
    ERROR_AUTHENTICATING: ClassVar[int]
    EXTRA_BSSID: ClassVar[str]
    EXTRA_NETWORK_INFO: ClassVar[str]
    EXTRA_NETWORK_SUGGESTION: ClassVar[str]
    EXTRA_NEW_RSSI: ClassVar[str]
    EXTRA_NEW_STATE: ClassVar[str]
    EXTRA_PREVIOUS_WIFI_STATE: ClassVar[str]
    EXTRA_RESULTS_UPDATED: ClassVar[str]
    EXTRA_SCAN_AVAILABLE: ClassVar[str]
    EXTRA_SUPPLICANT_CONNECTED: ClassVar[str]
    EXTRA_SUPPLICANT_ERROR: ClassVar[str]
    EXTRA_WIFI_INFO: ClassVar[str]
    EXTRA_WIFI_STATE: ClassVar[str]
    FLAG_SEND_DHCP_HOSTNAME_RESTRICTION_OPEN: ClassVar[int]
    FLAG_SEND_DHCP_HOSTNAME_RESTRICTION_SECURE: ClassVar[int]
    NETWORK_IDS_CHANGED_ACTION: ClassVar[str]
    NETWORK_STATE_CHANGED_ACTION: ClassVar[str]
    ROAMING_MODE_AGGRESSIVE: ClassVar[int]
    ROAMING_MODE_NONE: ClassVar[int]
    ROAMING_MODE_NORMAL: ClassVar[int]
    RSSI_CHANGED_ACTION: ClassVar[str]
    SCAN_RESULTS_AVAILABLE_ACTION: ClassVar[str]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_ASSOCIATION: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_AUTHENTICATION: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_IP_PROVISIONING: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_NOT_FOUND: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_NO_RESPONSE: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_UNKNOWN: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_DUPLICATE: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_EXCEEDS_MAX_PER_APP: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_INVALID: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_NOT_ALLOWED: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_APP_DISALLOWED: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_INTERNAL: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_REMOVE_INVALID: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_RESTRICTED_BY_ADMIN: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_SUCCESS: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_APPROVED_BY_CARRIER_PRIVILEGE: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_APPROVED_BY_USER: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_PENDING: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_REJECTED_BY_USER: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_UNKNOWN: ClassVar[int]
    STATUS_SUGGESTION_CONNECTION_FAILURE_ASSOCIATION: ClassVar[int]
    STATUS_SUGGESTION_CONNECTION_FAILURE_AUTHENTICATION: ClassVar[int]
    STATUS_SUGGESTION_CONNECTION_FAILURE_IP_PROVISIONING: ClassVar[int]
    STATUS_SUGGESTION_CONNECTION_FAILURE_UNKNOWN: ClassVar[int]
    SUPPLICANT_CONNECTION_CHANGE_ACTION: ClassVar[str]
    SUPPLICANT_STATE_CHANGED_ACTION: ClassVar[str]
    UNKNOWN_SSID: ClassVar[str]
    WIFI_INTERFACE_TYPE_AP: ClassVar[int]
    WIFI_INTERFACE_TYPE_AWARE: ClassVar[int]
    WIFI_INTERFACE_TYPE_DIRECT: ClassVar[int]
    WIFI_INTERFACE_TYPE_STA: ClassVar[int]
    WIFI_MODE_FULL: ClassVar[int]
    WIFI_MODE_FULL_HIGH_PERF: ClassVar[int]
    WIFI_MODE_FULL_LOW_LATENCY: ClassVar[int]
    WIFI_MODE_SCAN_ONLY: ClassVar[int]
    WIFI_MULTI_INTERNET_MODE_DBS_AP: ClassVar[int]
    WIFI_MULTI_INTERNET_MODE_DISABLED: ClassVar[int]
    WIFI_MULTI_INTERNET_MODE_MULTI_AP: ClassVar[int]
    WIFI_STATE_CHANGED_ACTION: ClassVar[str]
    WIFI_STATE_DISABLED: ClassVar[int]
    WIFI_STATE_DISABLING: ClassVar[int]
    WIFI_STATE_ENABLED: ClassVar[int]
    WIFI_STATE_ENABLING: ClassVar[int]
    WIFI_STATE_UNKNOWN: ClassVar[int]
    WPS_AUTH_FAILURE: ClassVar[int]
    WPS_OVERLAP_ERROR: ClassVar[int]
    WPS_TIMED_OUT: ClassVar[int]
    WPS_TKIP_ONLY_PROHIBITED: ClassVar[int]
    WPS_WEP_PROHIBITED: ClassVar[int]
    def getConfiguredNetworks(self) -> list: ...
    def getCallerConfiguredNetworks(self) -> list: ...
    def addNetwork(self, arg0: WifiConfiguration) -> int: ...
    def addNetworkPrivileged(self, arg0: WifiConfiguration) -> "AddNetworkResult": ...
    def updateNetwork(self, arg0: WifiConfiguration) -> int: ...
    def addNetworkSuggestions(self, arg0: list) -> int: ...
    @overload
    def removeNetworkSuggestions(self, arg0: list) -> int: ...
    @overload
    def removeNetworkSuggestions(self, arg0: list, arg1: int) -> int: ...
    def getNetworkSuggestions(self) -> list: ...
    def getMaxNumberOfNetworkSuggestionsPerApp(self) -> int: ...
    def addOrUpdatePasspointConfiguration(self, arg0: PasspointConfiguration) -> None: ...
    def removePasspointConfiguration(self, arg0: str) -> None: ...
    def getPasspointConfigurations(self) -> list: ...
    def removeNetwork(self, arg0: int) -> bool: ...
    def removeNonCallerConfiguredNetworks(self) -> bool: ...
    def enableNetwork(self, arg0: int, arg1: bool) -> bool: ...
    def disableNetwork(self, arg0: int) -> bool: ...
    def disconnect(self) -> bool: ...
    def reconnect(self) -> bool: ...
    def reassociate(self) -> bool: ...
    def pingSupplicant(self) -> bool: ...
    def isP2pSupported(self) -> bool: ...
    def isStaApConcurrencySupported(self) -> bool: ...
    def isStaConcurrencyForLocalOnlyConnectionsSupported(self) -> bool: ...
    def isMakeBeforeBreakWifiSwitchingSupported(self) -> bool: ...
    def isStaConcurrencyForMultiInternetSupported(self) -> bool: ...
    def isDeviceToApRttSupported(self) -> bool: ...
    def isPreferredNetworkOffloadSupported(self) -> bool: ...
    def isTdlsSupported(self) -> bool: ...
    def isEnhancedPowerReportingSupported(self) -> bool: ...
    def is24GHzBandSupported(self) -> bool: ...
    def is5GHzBandSupported(self) -> bool: ...
    def is60GHzBandSupported(self) -> bool: ...
    def is6GHzBandSupported(self) -> bool: ...
    def isWifiStandardSupported(self, arg0: int) -> bool: ...
    def isStaBridgedApConcurrencySupported(self) -> bool: ...
    def isBridgedApConcurrencySupported(self) -> bool: ...
    def isD2dSupportedWhenInfraStaDisabled(self) -> bool: ...
    def startScan(self) -> bool: ...
    def getConnectionInfo(self) -> WifiInfo: ...
    def getScanResults(self) -> list: ...
    def isScanAlwaysAvailable(self) -> bool: ...
    def getChannelData(self, arg0: Executor, arg1: Consumer) -> None: ...
    def saveConfiguration(self) -> bool: ...
    def getDhcpInfo(self) -> DhcpInfo: ...
    def setWifiEnabled(self, arg0: bool) -> bool: ...
    def registerSubsystemRestartTrackingCallback(self, arg0: Executor, arg1: "SubsystemRestartTrackingCallback") -> None: ...
    def unregisterSubsystemRestartTrackingCallback(self, arg0: "SubsystemRestartTrackingCallback") -> None: ...
    def getWifiState(self) -> int: ...
    def isWifiEnabled(self) -> bool: ...
    @overload
    @staticmethod
    def calculateSignalLevel(arg0: int, arg1: int) -> int: ...
    @overload
    def calculateSignalLevel(self, arg0: int) -> int: ...
    def getMaxSignalLevel(self) -> int: ...
    @staticmethod
    def compareSignalLevel(arg0: int, arg1: int) -> int: ...
    def validateSoftApConfiguration(self, arg0: SoftApConfiguration) -> bool: ...
    def startLocalOnlyHotspot(self, arg0: "LocalOnlyHotspotCallback", arg1: Handler) -> None: ...
    @overload
    def setTdlsEnabled(self, arg0: InetAddress, arg1: bool) -> None: ...
    @overload
    def setTdlsEnabled(self, arg0: InetAddress, arg1: bool, arg2: Executor, arg3: Consumer) -> None: ...
    @overload
    def setTdlsEnabledWithMacAddress(self, arg0: str, arg1: bool) -> None: ...
    @overload
    def setTdlsEnabledWithMacAddress(self, arg0: str, arg1: bool, arg2: Executor, arg3: Consumer) -> None: ...
    def isTdlsOperationCurrentlyAvailable(self, arg0: Executor, arg1: Consumer) -> None: ...
    def getMaxSupportedConcurrentTdlsSessions(self, arg0: Executor, arg1: Consumer) -> None: ...
    def getNumberOfEnabledTdlsSessions(self, arg0: Executor, arg1: Consumer) -> None: ...
    def allowAutojoinGlobal(self, arg0: bool) -> None: ...
    def queryAutojoinGlobal(self, arg0: Executor, arg1: Consumer) -> None: ...
    def startWps(self, arg0: WpsInfo, arg1: "WpsCallback") -> None: ...
    def cancelWps(self, arg0: "WpsCallback") -> None: ...
    @overload
    def createWifiLock(self, arg0: int, arg1: str) -> "WifiLock": ...
    @overload
    def createWifiLock(self, arg0: str) -> "WifiLock": ...
    def createMulticastLock(self, arg0: str) -> "MulticastLock": ...
    def isWpa3SaeSupported(self) -> bool: ...
    def isWpa3SuiteBSupported(self) -> bool: ...
    def isEnhancedOpenSupported(self) -> bool: ...
    def isEasyConnectSupported(self) -> bool: ...
    def isEasyConnectEnrolleeResponderModeSupported(self) -> bool: ...
    def isWapiSupported(self) -> bool: ...
    def isWpa3SaePublicKeySupported(self) -> bool: ...
    def isPasspointTermsAndConditionsSupported(self) -> bool: ...
    def isWpa3SaeH2eSupported(self) -> bool: ...
    def isWifiDisplayR2Supported(self) -> bool: ...
    def isDecoratedIdentitySupported(self) -> bool: ...
    def isTrustOnFirstUseSupported(self) -> bool: ...
    def isEasyConnectDppAkmSupported(self) -> bool: ...
    def isTlsMinimumVersionSupported(self) -> bool: ...
    def isTlsV13Supported(self) -> bool: ...
    def isDualBandSimultaneousSupported(self) -> bool: ...
    def isTidToLinkMappingNegotiationSupported(self) -> bool: ...
    def isWepSupported(self) -> bool: ...
    def isWpaPersonalSupported(self) -> bool: ...
    def registerScanResultsCallback(self, arg0: Executor, arg1: "ScanResultsCallback") -> None: ...
    def unregisterScanResultsCallback(self, arg0: "ScanResultsCallback") -> None: ...
    def addSuggestionConnectionStatusListener(self, arg0: Executor, arg1: "SuggestionConnectionStatusListener") -> None: ...
    def removeSuggestionConnectionStatusListener(self, arg0: "SuggestionConnectionStatusListener") -> None: ...
    def addLocalOnlyConnectionFailureListener(self, arg0: Executor, arg1: "LocalOnlyConnectionFailureListener") -> None: ...
    def removeLocalOnlyConnectionFailureListener(self, arg0: "LocalOnlyConnectionFailureListener") -> None: ...
    def isScanThrottleEnabled(self) -> bool: ...
    def isAutoWakeupEnabled(self) -> bool: ...
    def isCarrierNetworkOffloadEnabled(self, arg0: int, arg1: bool) -> bool: ...
    def addSuggestionUserApprovalStatusListener(self, arg0: Executor, arg1: "SuggestionUserApprovalStatusListener") -> None: ...
    def removeSuggestionUserApprovalStatusListener(self, arg0: "SuggestionUserApprovalStatusListener") -> None: ...
    def flushPasspointAnqpCache(self) -> None: ...
    def getAllowedChannels(self, arg0: int, arg1: int) -> list: ...
    def getUsableChannels(self, arg0: int, arg1: int) -> list: ...
    def isWifiPasspointEnabled(self) -> bool: ...
    def getStaConcurrencyForMultiInternetMode(self) -> int: ...
    def reportCreateInterfaceImpact(self, arg0: int, arg1: bool, arg2: Executor, arg3: BiConsumer) -> None: ...
    def getMaxNumberOfChannelsPerNetworkSpecifierRequest(self) -> int: ...
    def setSendDhcpHostnameRestriction(self, arg0: int) -> None: ...
    def querySendDhcpHostnameRestriction(self, arg0: Executor, arg1: IntConsumer) -> None: ...
    def isAggressiveRoamingModeSupported(self) -> bool: ...
    def setPerSsidRoamingMode(self, arg0: WifiSsid, arg1: int) -> None: ...
    def removePerSsidRoamingMode(self, arg0: WifiSsid) -> None: ...
    def getPerSsidRoamingModes(self, arg0: Executor, arg1: Consumer) -> None: ...

    class AddNetworkResult:
        CREATOR: ClassVar[Creator]
        STATUS_ADD_PASSPOINT_FAILURE: ClassVar[int]
        STATUS_ADD_WIFI_CONFIG_FAILURE: ClassVar[int]
        STATUS_FAILURE_UNKNOWN: ClassVar[int]
        STATUS_FAILURE_UPDATE_NETWORK_KEYS: ClassVar[int]
        STATUS_INVALID_CONFIGURATION: ClassVar[int]
        STATUS_INVALID_CONFIGURATION_ENTERPRISE: ClassVar[int]
        STATUS_NO_PERMISSION: ClassVar[int]
        STATUS_NO_PERMISSION_MODIFY_CONFIG: ClassVar[int]
        STATUS_NO_PERMISSION_MODIFY_MAC_RANDOMIZATION: ClassVar[int]
        STATUS_NO_PERMISSION_MODIFY_PROXY_SETTING: ClassVar[int]
        STATUS_SUCCESS: ClassVar[int]
        networkId: int
        statusCode: int
        def __init__(self, arg0: int, arg1: int) -> None: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class InterfaceCreationImpact:
        def __init__(self, arg0: int, arg1: set) -> None: ...
        def getInterfaceType(self) -> int: ...
        def getPackages(self) -> set: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...

    class LocalOnlyConnectionFailureListener:
        def onConnectionFailed(self, arg0: WifiNetworkSpecifier, arg1: int) -> None: ...

    class LocalOnlyHotspotCallback:
        ERROR_GENERIC: ClassVar[int]
        ERROR_INCOMPATIBLE_MODE: ClassVar[int]
        ERROR_NO_CHANNEL: ClassVar[int]
        ERROR_TETHERING_DISALLOWED: ClassVar[int]
        def __init__(self) -> None: ...
        def onStarted(self, arg0: "LocalOnlyHotspotReservation") -> None: ...
        def onStopped(self) -> None: ...
        def onFailed(self, arg0: int) -> None: ...

    class LocalOnlyHotspotReservation:
        def getWifiConfiguration(self) -> WifiConfiguration: ...
        def getSoftApConfiguration(self) -> SoftApConfiguration: ...
        def close(self) -> None: ...
        def finalize(self) -> None: ...

    class MulticastLock:
        def acquire(self) -> None: ...
        def release(self) -> None: ...
        def setReferenceCounted(self, arg0: bool) -> None: ...
        def isHeld(self) -> bool: ...
        def toString(self) -> str: ...
        def finalize(self) -> None: ...

    class ScanResultsCallback:
        def __init__(self) -> None: ...
        def onScanResultsAvailable(self) -> None: ...

    class SubsystemRestartTrackingCallback:
        def __init__(self) -> None: ...
        def onSubsystemRestarting(self) -> None: ...
        def onSubsystemRestarted(self) -> None: ...

    class SuggestionConnectionStatusListener:
        def onConnectionStatus(self, arg0: WifiNetworkSuggestion, arg1: int) -> None: ...

    class SuggestionUserApprovalStatusListener:
        def onUserApprovalStatusChange(self, arg0: int) -> None: ...

    class WifiLock:
        def acquire(self) -> None: ...
        def release(self) -> None: ...
        def setReferenceCounted(self, arg0: bool) -> None: ...
        def isHeld(self) -> bool: ...
        def setWorkSource(self, arg0: WorkSource) -> None: ...
        def toString(self) -> str: ...
        def finalize(self) -> None: ...

    class WpsCallback:
        def __init__(self) -> None: ...
        def onStarted(self, arg0: str) -> None: ...
        def onSucceeded(self) -> None: ...
        def onFailed(self, arg0: int) -> None: ...
