from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.SupplicantState import SupplicantState
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class DetailedState:
    """Forward declaration for ``android.net.NetworkInfo.DetailedState``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.net.NetworkInfo.DetailedState')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/net/NetworkInfo/DetailedState
    """
    ...

class WifiInfo:
    FREQUENCY_UNITS: ClassVar[str]
    LINK_SPEED_UNITS: ClassVar[str]
    LINK_SPEED_UNKNOWN: ClassVar[int]
    SECURITY_TYPE_DPP: ClassVar[int]
    SECURITY_TYPE_EAP: ClassVar[int]
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE: ClassVar[int]
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE_192_BIT: ClassVar[int]
    SECURITY_TYPE_OPEN: ClassVar[int]
    SECURITY_TYPE_OSEN: ClassVar[int]
    SECURITY_TYPE_OWE: ClassVar[int]
    SECURITY_TYPE_PASSPOINT_R1_R2: ClassVar[int]
    SECURITY_TYPE_PASSPOINT_R3: ClassVar[int]
    SECURITY_TYPE_PSK: ClassVar[int]
    SECURITY_TYPE_SAE: ClassVar[int]
    SECURITY_TYPE_UNKNOWN: ClassVar[int]
    SECURITY_TYPE_WAPI_CERT: ClassVar[int]
    SECURITY_TYPE_WAPI_PSK: ClassVar[int]
    SECURITY_TYPE_WEP: ClassVar[int]
    def getSSID(self) -> str: ...
    def getBSSID(self) -> str: ...
    def getApMldMacAddress(self) -> MacAddress: ...
    def getApMloLinkId(self) -> int: ...
    def getAffiliatedMloLinks(self) -> list: ...
    def getAssociatedMloLinks(self) -> list: ...
    def getRssi(self) -> int: ...
    def getWifiStandard(self) -> int: ...
    def getLinkSpeed(self) -> int: ...
    def getTxLinkSpeedMbps(self) -> int: ...
    def getMaxSupportedTxLinkSpeedMbps(self) -> int: ...
    def getRxLinkSpeedMbps(self) -> int: ...
    def getMaxSupportedRxLinkSpeedMbps(self) -> int: ...
    def getFrequency(self) -> int: ...
    def getMacAddress(self) -> str: ...
    def isRestricted(self) -> bool: ...
    def getPasspointFqdn(self) -> str: ...
    def getPasspointProviderFriendlyName(self) -> str: ...
    def getSubscriptionId(self) -> int: ...
    def getNetworkId(self) -> int: ...
    def getSupplicantState(self) -> SupplicantState: ...
    def getIpAddress(self) -> int: ...
    def getHiddenSSID(self) -> bool: ...
    @staticmethod
    def getDetailedStateOf(arg0: SupplicantState) -> DetailedState: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getPasspointUniqueId(self) -> str: ...
    def getInformationElements(self) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def makeCopy(self, arg0: int) -> "WifiInfo": ...
    def getApplicableRedactions(self) -> int: ...
    def getCurrentSecurityType(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setSsid(self, arg0: list[int]) -> "Builder": ...
        def setBssid(self, arg0: str) -> "Builder": ...
        def setRssi(self, arg0: int) -> "Builder": ...
        def setNetworkId(self, arg0: int) -> "Builder": ...
        def setSubscriptionId(self, arg0: int) -> "Builder": ...
        def setCurrentSecurityType(self, arg0: int) -> "Builder": ...
        def build(self) -> "WifiInfo": ...
