from typing import Any, ClassVar, overload

class CustomEventInterstitial:
    def requestInterstitialAd(self, arg0: "Context", arg1: "CustomEventInterstitialListener", arg2: str, arg3: "MediationAdRequest", arg4: "Bundle") -> None: ...
    def showInterstitial(self) -> None: ...
