from typing import Any, ClassVar, overload

class CustomEventAdapter:
    def __init__(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onPause(self) -> None: ...
    def onResume(self) -> None: ...
    def getBannerView(self) -> "View": ...
    def requestBannerAd(self, arg0: "Context", arg1: "MediationBannerListener", arg2: "Bundle", arg3: "AdSize", arg4: "MediationAdRequest", arg5: "Bundle") -> None: ...
    def requestInterstitialAd(self, arg0: "Context", arg1: "MediationInterstitialListener", arg2: "Bundle", arg3: "MediationAdRequest", arg4: "Bundle") -> None: ...
    def requestNativeAd(self, arg0: "Context", arg1: "MediationNativeListener", arg2: "Bundle", arg3: "NativeMediationAdRequest", arg4: "Bundle") -> None: ...
    def showInterstitial(self) -> None: ...
