from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.view.SurfaceControl import SurfaceControl

class InlineContentView:
    def getSurfaceControl(self) -> SurfaceControl: ...
    def setClipBounds(self, arg0: Rect) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def setSurfaceControlCallback(self, arg0: "SurfaceControlCallback") -> None: ...
    def isZOrderedOnTop(self) -> bool: ...
    def setZOrderedOnTop(self, arg0: bool) -> bool: ...

    class SurfaceControlCallback:
        def onCreated(self, arg0: SurfaceControl) -> None: ...
        def onDestroyed(self, arg0: SurfaceControl) -> None: ...
