from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.Bundle import Bundle
from android.os.IBinder import IBinder
from android.view.textservice.SentenceSuggestionsInfo import SentenceSuggestionsInfo
from android.view.textservice.SuggestionsInfo import SuggestionsInfo
from android.view.textservice.TextInfo import TextInfo

class SpellCheckerService:
    SERVICE_INTERFACE: ClassVar[str]
    def __init__(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def createSession(self) -> "Session": ...

    class Session:
        def __init__(self) -> None: ...
        def onCreate(self) -> None: ...
        def onGetSuggestions(self, arg0: TextInfo, arg1: int) -> SuggestionsInfo: ...
        def onGetSuggestionsMultiple(self, arg0: list[TextInfo], arg1: int, arg2: bool) -> list[SuggestionsInfo]: ...
        def onGetSentenceSuggestionsMultiple(self, arg0: list[TextInfo], arg1: int) -> list[SentenceSuggestionsInfo]: ...
        def onCancel(self) -> None: ...
        def onClose(self) -> None: ...
        def getLocale(self) -> str: ...
        def getBundle(self) -> Bundle: ...
        def getSupportedAttributes(self) -> int: ...
