from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from android.bluetooth.BluetoothGattCharacteristic import BluetoothGattCharacteristic
from android.bluetooth.BluetoothGattDescriptor import BluetoothGattDescriptor
from android.bluetooth.BluetoothGattService import BluetoothGattService
from java.util.UUID import UUID

class BluetoothGatt:
    CONNECTION_PRIORITY_BALANCED: ClassVar[int]
    CONNECTION_PRIORITY_DCK: ClassVar[int]
    CONNECTION_PRIORITY_HIGH: ClassVar[int]
    CONNECTION_PRIORITY_LOW_POWER: ClassVar[int]
    GATT_CONNECTION_CONGESTED: ClassVar[int]
    GATT_CONNECTION_TIMEOUT: ClassVar[int]
    GATT_FAILURE: ClassVar[int]
    GATT_INSUFFICIENT_AUTHENTICATION: ClassVar[int]
    GATT_INSUFFICIENT_AUTHORIZATION: ClassVar[int]
    GATT_INSUFFICIENT_ENCRYPTION: ClassVar[int]
    GATT_INVALID_ATTRIBUTE_LENGTH: ClassVar[int]
    GATT_INVALID_OFFSET: ClassVar[int]
    GATT_READ_NOT_PERMITTED: ClassVar[int]
    GATT_REQUEST_NOT_SUPPORTED: ClassVar[int]
    GATT_SUCCESS: ClassVar[int]
    GATT_WRITE_NOT_PERMITTED: ClassVar[int]
    def close(self) -> None: ...
    def disconnect(self) -> None: ...
    def connect(self) -> bool: ...
    def setPreferredPhy(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def readPhy(self) -> None: ...
    def getDevice(self) -> BluetoothDevice: ...
    def discoverServices(self) -> bool: ...
    def getServices(self) -> list: ...
    def getService(self, arg0: UUID) -> BluetoothGattService: ...
    def readCharacteristic(self, arg0: BluetoothGattCharacteristic) -> bool: ...
    @overload
    def writeCharacteristic(self, arg0: BluetoothGattCharacteristic) -> bool: ...
    @overload
    def writeCharacteristic(self, arg0: BluetoothGattCharacteristic, arg1: list[int], arg2: int) -> int: ...
    def readDescriptor(self, arg0: BluetoothGattDescriptor) -> bool: ...
    @overload
    def writeDescriptor(self, arg0: BluetoothGattDescriptor) -> bool: ...
    @overload
    def writeDescriptor(self, arg0: BluetoothGattDescriptor, arg1: list[int]) -> int: ...
    def beginReliableWrite(self) -> bool: ...
    def executeReliableWrite(self) -> bool: ...
    @overload
    def abortReliableWrite(self) -> None: ...
    @overload
    def abortReliableWrite(self, arg0: BluetoothDevice) -> None: ...
    def setCharacteristicNotification(self, arg0: BluetoothGattCharacteristic, arg1: bool) -> bool: ...
    def readRemoteRssi(self) -> bool: ...
    def requestMtu(self, arg0: int) -> bool: ...
    def requestConnectionPriority(self, arg0: int) -> bool: ...
    def getConnectionState(self, arg0: BluetoothDevice) -> int: ...
    def getConnectedDevices(self) -> list: ...
    def getDevicesMatchingConnectionStates(self, arg0: list[int]) -> list: ...
