from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from android.bluetooth.BluetoothProfile import BluetoothProfile
from android.bluetooth.BluetoothServerSocket import BluetoothServerSocket
from android.bluetooth.le.BluetoothLeAdvertiser import BluetoothLeAdvertiser
from android.bluetooth.le.BluetoothLeScanner import BluetoothLeScanner
from android.content.Context import Context
from java.time.Duration import Duration
from java.util.UUID import UUID

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class ServiceListener:
    """Forward declaration for ``android.bluetooth.BluetoothProfile.ServiceListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.bluetooth.BluetoothProfile.ServiceListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/bluetooth/BluetoothProfile/ServiceListener
    """
    ...

class BluetoothAdapter:
    ACTION_CONNECTION_STATE_CHANGED: ClassVar[str]
    ACTION_DISCOVERY_FINISHED: ClassVar[str]
    ACTION_DISCOVERY_STARTED: ClassVar[str]
    ACTION_LOCAL_NAME_CHANGED: ClassVar[str]
    ACTION_REQUEST_DISCOVERABLE: ClassVar[str]
    ACTION_REQUEST_ENABLE: ClassVar[str]
    ACTION_SCAN_MODE_CHANGED: ClassVar[str]
    ACTION_STATE_CHANGED: ClassVar[str]
    ERROR: ClassVar[int]
    EXTRA_CONNECTION_STATE: ClassVar[str]
    EXTRA_DISCOVERABLE_DURATION: ClassVar[str]
    EXTRA_LOCAL_NAME: ClassVar[str]
    EXTRA_PREVIOUS_CONNECTION_STATE: ClassVar[str]
    EXTRA_PREVIOUS_SCAN_MODE: ClassVar[str]
    EXTRA_PREVIOUS_STATE: ClassVar[str]
    EXTRA_SCAN_MODE: ClassVar[str]
    EXTRA_STATE: ClassVar[str]
    SCAN_MODE_CONNECTABLE: ClassVar[int]
    SCAN_MODE_CONNECTABLE_DISCOVERABLE: ClassVar[int]
    SCAN_MODE_NONE: ClassVar[int]
    STATE_CONNECTED: ClassVar[int]
    STATE_CONNECTING: ClassVar[int]
    STATE_DISCONNECTED: ClassVar[int]
    STATE_DISCONNECTING: ClassVar[int]
    STATE_OFF: ClassVar[int]
    STATE_ON: ClassVar[int]
    STATE_TURNING_OFF: ClassVar[int]
    STATE_TURNING_ON: ClassVar[int]
    @staticmethod
    def getDefaultAdapter() -> "BluetoothAdapter": ...
    @overload
    def getRemoteDevice(self, arg0: str) -> BluetoothDevice: ...
    @overload
    def getRemoteDevice(self, arg0: list[int]) -> BluetoothDevice: ...
    def getRemoteLeDevice(self, arg0: str, arg1: int) -> BluetoothDevice: ...
    def getBluetoothLeAdvertiser(self) -> BluetoothLeAdvertiser: ...
    def getBluetoothLeScanner(self) -> BluetoothLeScanner: ...
    def isEnabled(self) -> bool: ...
    def getState(self) -> int: ...
    def enable(self) -> bool: ...
    def disable(self) -> bool: ...
    def getAddress(self) -> str: ...
    def getName(self) -> str: ...
    def setName(self, arg0: str) -> bool: ...
    def getScanMode(self) -> int: ...
    def getDiscoverableTimeout(self) -> Duration: ...
    def startDiscovery(self) -> bool: ...
    def cancelDiscovery(self) -> bool: ...
    def isDiscovering(self) -> bool: ...
    def isMultipleAdvertisementSupported(self) -> bool: ...
    def isOffloadedFilteringSupported(self) -> bool: ...
    def isOffloadedScanBatchingSupported(self) -> bool: ...
    def isLe2MPhySupported(self) -> bool: ...
    def isLeCodedPhySupported(self) -> bool: ...
    def isLeExtendedAdvertisingSupported(self) -> bool: ...
    def isLePeriodicAdvertisingSupported(self) -> bool: ...
    def isLeAudioSupported(self) -> int: ...
    def isLeAudioBroadcastSourceSupported(self) -> int: ...
    def isLeAudioBroadcastAssistantSupported(self) -> int: ...
    def getLeMaximumAdvertisingDataLength(self) -> int: ...
    def getMaxConnectedAudioDevices(self) -> int: ...
    def getBondedDevices(self) -> set: ...
    def getProfileConnectionState(self, arg0: int) -> int: ...
    def listenUsingRfcommWithServiceRecord(self, arg0: str, arg1: UUID) -> BluetoothServerSocket: ...
    def listenUsingInsecureRfcommWithServiceRecord(self, arg0: str, arg1: UUID) -> BluetoothServerSocket: ...
    def getProfileProxy(self, arg0: Context, arg1: ServiceListener, arg2: int) -> bool: ...
    def closeProfileProxy(self, arg0: int, arg1: BluetoothProfile) -> None: ...
    def finalize(self) -> None: ...
    @staticmethod
    def checkBluetoothAddress(arg0: str) -> bool: ...
    @overload
    def startLeScan(self, arg0: "LeScanCallback") -> bool: ...
    @overload
    def startLeScan(self, arg0: list[UUID], arg1: "LeScanCallback") -> bool: ...
    def stopLeScan(self, arg0: "LeScanCallback") -> None: ...
    def listenUsingL2capChannel(self) -> BluetoothServerSocket: ...
    def listenUsingInsecureL2capChannel(self) -> BluetoothServerSocket: ...

    class LeScanCallback:
        def onLeScan(self, arg0: BluetoothDevice, arg1: int, arg2: list[int]) -> None: ...
