from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice

class BluetoothA2dp:
    ACTION_CONNECTION_STATE_CHANGED: ClassVar[str]
    ACTION_PLAYING_STATE_CHANGED: ClassVar[str]
    STATE_NOT_PLAYING: ClassVar[int]
    STATE_PLAYING: ClassVar[int]
    def finalize(self) -> None: ...
    def getConnectedDevices(self) -> list: ...
    def getDevicesMatchingConnectionStates(self, arg0: list[int]) -> list: ...
    def getConnectionState(self, arg0: BluetoothDevice) -> int: ...
    def isA2dpPlaying(self, arg0: BluetoothDevice) -> bool: ...
    def getSupportedCodecTypes(self) -> list: ...
