from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice

class BluetoothLeAudio:
    ACTION_LE_AUDIO_CONNECTION_STATE_CHANGED: ClassVar[str]
    GROUP_ID_INVALID: ClassVar[int]
    def close(self) -> None: ...
    def finalize(self) -> None: ...
    def getConnectedGroupLeadDevice(self, arg0: int) -> BluetoothDevice: ...
    def getConnectedDevices(self) -> list: ...
    def getDevicesMatchingConnectionStates(self, arg0: list[int]) -> list: ...
    def getConnectionState(self, arg0: BluetoothDevice) -> int: ...
    def getGroupId(self, arg0: BluetoothDevice) -> int: ...
