from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothLeAudioCodecConfig import BluetoothLeAudioCodecConfig
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class BluetoothLeAudioCodecStatus:
    CREATOR: ClassVar[Creator]
    EXTRA_LE_AUDIO_CODEC_STATUS: ClassVar[str]
    def __init__(self, arg0: BluetoothLeAudioCodecConfig, arg1: BluetoothLeAudioCodecConfig, arg2: list, arg3: list, arg4: list, arg5: list) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def isInputCodecConfigSelectable(self, arg0: BluetoothLeAudioCodecConfig) -> bool: ...
    def isOutputCodecConfigSelectable(self, arg0: BluetoothLeAudioCodecConfig) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getInputCodecConfig(self) -> BluetoothLeAudioCodecConfig: ...
    def getOutputCodecConfig(self) -> BluetoothLeAudioCodecConfig: ...
    def getInputCodecLocalCapabilities(self) -> list: ...
    def getOutputCodecLocalCapabilities(self) -> list: ...
    def getInputCodecSelectableCapabilities(self) -> list: ...
    def getOutputCodecSelectableCapabilities(self) -> list: ...
