from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothGatt import BluetoothGatt
from android.bluetooth.BluetoothGattCharacteristic import BluetoothGattCharacteristic
from android.bluetooth.BluetoothGattDescriptor import BluetoothGattDescriptor

class BluetoothGattCallback:
    def __init__(self) -> None: ...
    def onPhyUpdate(self, arg0: BluetoothGatt, arg1: int, arg2: int, arg3: int) -> None: ...
    def onPhyRead(self, arg0: BluetoothGatt, arg1: int, arg2: int, arg3: int) -> None: ...
    def onConnectionStateChange(self, arg0: BluetoothGatt, arg1: int, arg2: int) -> None: ...
    def onServicesDiscovered(self, arg0: BluetoothGatt, arg1: int) -> None: ...
    @overload
    def onCharacteristicRead(self, arg0: BluetoothGatt, arg1: BluetoothGattCharacteristic, arg2: int) -> None: ...
    @overload
    def onCharacteristicRead(self, arg0: BluetoothGatt, arg1: BluetoothGattCharacteristic, arg2: list[int], arg3: int) -> None: ...
    def onCharacteristicWrite(self, arg0: BluetoothGatt, arg1: BluetoothGattCharacteristic, arg2: int) -> None: ...
    @overload
    def onCharacteristicChanged(self, arg0: BluetoothGatt, arg1: BluetoothGattCharacteristic) -> None: ...
    @overload
    def onCharacteristicChanged(self, arg0: BluetoothGatt, arg1: BluetoothGattCharacteristic, arg2: list[int]) -> None: ...
    @overload
    def onDescriptorRead(self, arg0: BluetoothGatt, arg1: BluetoothGattDescriptor, arg2: int) -> None: ...
    @overload
    def onDescriptorRead(self, arg0: BluetoothGatt, arg1: BluetoothGattDescriptor, arg2: int, arg3: list[int]) -> None: ...
    def onDescriptorWrite(self, arg0: BluetoothGatt, arg1: BluetoothGattDescriptor, arg2: int) -> None: ...
    def onReliableWriteCompleted(self, arg0: BluetoothGatt, arg1: int) -> None: ...
    def onReadRemoteRssi(self, arg0: BluetoothGatt, arg1: int, arg2: int) -> None: ...
    def onMtuChanged(self, arg0: BluetoothGatt, arg1: int, arg2: int) -> None: ...
    def onServiceChanged(self, arg0: BluetoothGatt) -> None: ...
