from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice

class BluetoothHeadset:
    ACTION_AUDIO_STATE_CHANGED: ClassVar[str]
    ACTION_CONNECTION_STATE_CHANGED: ClassVar[str]
    ACTION_VENDOR_SPECIFIC_HEADSET_EVENT: ClassVar[str]
    AT_CMD_TYPE_ACTION: ClassVar[int]
    AT_CMD_TYPE_BASIC: ClassVar[int]
    AT_CMD_TYPE_READ: ClassVar[int]
    AT_CMD_TYPE_SET: ClassVar[int]
    AT_CMD_TYPE_TEST: ClassVar[int]
    EXTRA_VENDOR_SPECIFIC_HEADSET_EVENT_ARGS: ClassVar[str]
    EXTRA_VENDOR_SPECIFIC_HEADSET_EVENT_CMD: ClassVar[str]
    EXTRA_VENDOR_SPECIFIC_HEADSET_EVENT_CMD_TYPE: ClassVar[str]
    STATE_AUDIO_CONNECTED: ClassVar[int]
    STATE_AUDIO_CONNECTING: ClassVar[int]
    STATE_AUDIO_DISCONNECTED: ClassVar[int]
    VENDOR_RESULT_CODE_COMMAND_ANDROID: ClassVar[str]
    VENDOR_SPECIFIC_HEADSET_EVENT_COMPANY_ID_CATEGORY: ClassVar[str]
    def finalize(self) -> None: ...
    def getConnectedDevices(self) -> list: ...
    def getDevicesMatchingConnectionStates(self, arg0: list[int]) -> list: ...
    def getConnectionState(self, arg0: BluetoothDevice) -> int: ...
    def isNoiseReductionSupported(self, arg0: BluetoothDevice) -> bool: ...
    def isVoiceRecognitionSupported(self, arg0: BluetoothDevice) -> bool: ...
    def startVoiceRecognition(self, arg0: BluetoothDevice) -> bool: ...
    def stopVoiceRecognition(self, arg0: BluetoothDevice) -> bool: ...
    def isAudioConnected(self, arg0: BluetoothDevice) -> bool: ...
    def sendVendorSpecificResultCode(self, arg0: BluetoothDevice, arg1: str, arg2: str) -> bool: ...
