from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class BluetoothLeAudioCodecConfig:
    BITS_PER_SAMPLE_16: ClassVar[int]
    BITS_PER_SAMPLE_24: ClassVar[int]
    BITS_PER_SAMPLE_32: ClassVar[int]
    BITS_PER_SAMPLE_NONE: ClassVar[int]
    CHANNEL_COUNT_1: ClassVar[int]
    CHANNEL_COUNT_2: ClassVar[int]
    CHANNEL_COUNT_NONE: ClassVar[int]
    CODEC_PRIORITY_DEFAULT: ClassVar[int]
    CODEC_PRIORITY_DISABLED: ClassVar[int]
    CODEC_PRIORITY_HIGHEST: ClassVar[int]
    CREATOR: ClassVar[Creator]
    FRAME_DURATION_10000: ClassVar[int]
    FRAME_DURATION_7500: ClassVar[int]
    FRAME_DURATION_NONE: ClassVar[int]
    SAMPLE_RATE_11025: ClassVar[int]
    SAMPLE_RATE_16000: ClassVar[int]
    SAMPLE_RATE_176400: ClassVar[int]
    SAMPLE_RATE_192000: ClassVar[int]
    SAMPLE_RATE_22050: ClassVar[int]
    SAMPLE_RATE_24000: ClassVar[int]
    SAMPLE_RATE_32000: ClassVar[int]
    SAMPLE_RATE_384000: ClassVar[int]
    SAMPLE_RATE_44100: ClassVar[int]
    SAMPLE_RATE_48000: ClassVar[int]
    SAMPLE_RATE_8000: ClassVar[int]
    SAMPLE_RATE_88200: ClassVar[int]
    SAMPLE_RATE_96000: ClassVar[int]
    SAMPLE_RATE_NONE: ClassVar[int]
    SOURCE_CODEC_TYPE_INVALID: ClassVar[int]
    SOURCE_CODEC_TYPE_LC3: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...
    def getCodecType(self) -> int: ...
    def getCodecName(self) -> str: ...
    def getCodecPriority(self) -> int: ...
    def getSampleRate(self) -> int: ...
    def getBitsPerSample(self) -> int: ...
    def getChannelCount(self) -> int: ...
    def getFrameDuration(self) -> int: ...
    def getOctetsPerFrame(self) -> int: ...
    def getMinOctetsPerFrame(self) -> int: ...
    def getMaxOctetsPerFrame(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: "BluetoothLeAudioCodecConfig") -> None: ...
        def setCodecType(self, arg0: int) -> "Builder": ...
        def setCodecPriority(self, arg0: int) -> "Builder": ...
        def setSampleRate(self, arg0: int) -> "Builder": ...
        def setBitsPerSample(self, arg0: int) -> "Builder": ...
        def setChannelCount(self, arg0: int) -> "Builder": ...
        def setFrameDuration(self, arg0: int) -> "Builder": ...
        def setOctetsPerFrame(self, arg0: int) -> "Builder": ...
        def setMinOctetsPerFrame(self, arg0: int) -> "Builder": ...
        def setMaxOctetsPerFrame(self, arg0: int) -> "Builder": ...
        def build(self) -> "BluetoothLeAudioCodecConfig": ...
