from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothGattCharacteristic import BluetoothGattCharacteristic
from android.os.Parcel import Parcel
from java.util.UUID import UUID

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class BluetoothGattService:
    CREATOR: ClassVar[Creator]
    SERVICE_TYPE_PRIMARY: ClassVar[int]
    SERVICE_TYPE_SECONDARY: ClassVar[int]
    mCharacteristics: list
    mIncludedServices: list
    def __init__(self, arg0: UUID, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def addService(self, arg0: "BluetoothGattService") -> bool: ...
    def addCharacteristic(self, arg0: BluetoothGattCharacteristic) -> bool: ...
    def getUuid(self) -> UUID: ...
    def getInstanceId(self) -> int: ...
    def getType(self) -> int: ...
    def getIncludedServices(self) -> list: ...
    def getCharacteristics(self) -> list: ...
    def getCharacteristic(self, arg0: UUID) -> BluetoothGattCharacteristic: ...
