from typing import Any, ClassVar, overload
from java.time.Duration import Duration

class DnsOptions:
    DNS_OPTION_DISABLED: ClassVar[int]
    DNS_OPTION_ENABLED: ClassVar[int]
    DNS_OPTION_UNSPECIFIED: ClassVar[int]
    def getUseHttpStackDnsResolver(self) -> int: ...
    def getPersistHostCache(self) -> int: ...
    def getStaleDns(self) -> int: ...
    def getPersistHostCachePeriod(self) -> Duration: ...
    def getPreestablishConnectionsToStaleDnsResults(self) -> int: ...
    def getStaleDnsOptions(self) -> "StaleDnsOptions": ...

    class Builder:
        def __init__(self) -> None: ...
        def setUseHttpStackDnsResolver(self, arg0: int) -> "Builder": ...
        def setStaleDns(self, arg0: int) -> "Builder": ...
        def setStaleDnsOptions(self, arg0: "StaleDnsOptions") -> "Builder": ...
        def setPreestablishConnectionsToStaleDnsResults(self, arg0: int) -> "Builder": ...
        def setPersistHostCache(self, arg0: int) -> "Builder": ...
        def setPersistHostCachePeriod(self, arg0: Duration) -> "Builder": ...
        def build(self) -> "DnsOptions": ...

    class StaleDnsOptions:
        def getFreshLookupTimeout(self) -> Duration: ...
        def getMaxExpiredDelay(self) -> Duration: ...
        def getAllowCrossNetworkUsage(self) -> int: ...
        def getUseStaleOnNameNotResolved(self) -> int: ...

        class Builder:
            def __init__(self) -> None: ...
            def setFreshLookupTimeout(self, arg0: Duration) -> "Builder": ...
            def setMaxExpiredDelay(self, arg0: Duration) -> "Builder": ...
            def setAllowCrossNetworkUsage(self, arg0: int) -> "Builder": ...
            def setUseStaleOnNameNotResolved(self, arg0: int) -> "Builder": ...
            def build(self) -> "StaleDnsOptions": ...
