from typing import Any, ClassVar, overload
from java.io.File import File
from java.net.CacheRequest import CacheRequest
from java.net.CacheResponse import CacheResponse
from java.net.URI import URI
from java.net.URLConnection import URLConnection

class HttpResponseCache:
    @staticmethod
    def getInstalled() -> "HttpResponseCache": ...
    @staticmethod
    def install(arg0: File, arg1: int) -> "HttpResponseCache": ...
    def get(self, arg0: URI, arg1: str, arg2: dict) -> CacheResponse: ...
    def put(self, arg0: URI, arg1: URLConnection) -> CacheRequest: ...
    def size(self) -> int: ...
    def maxSize(self) -> int: ...
    def flush(self) -> None: ...
    def getNetworkCount(self) -> int: ...
    def getHitCount(self) -> int: ...
    def getRequestCount(self) -> int: ...
    def close(self) -> None: ...
    def delete(self) -> None: ...
