from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from java.security.cert.X509Certificate import X509Certificate
from java.util.Date import Date

class SslCertificate:
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: str, arg3: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: Date, arg3: Date) -> None: ...
    @overload
    def __init__(self, arg0: X509Certificate) -> None: ...
    @staticmethod
    def saveState(arg0: "SslCertificate") -> Bundle: ...
    @staticmethod
    def restoreState(arg0: Bundle) -> "SslCertificate": ...
    def getValidNotBeforeDate(self) -> Date: ...
    def getValidNotBefore(self) -> str: ...
    def getValidNotAfterDate(self) -> Date: ...
    def getValidNotAfter(self) -> str: ...
    def getIssuedTo(self) -> "DName": ...
    def getIssuedBy(self) -> "DName": ...
    def getX509Certificate(self) -> X509Certificate: ...
    def toString(self) -> str: ...

    class DName:
        def __init__(self, arg0: "SslCertificate", arg1: str) -> None: ...
        def getDName(self) -> str: ...
        def getCName(self) -> str: ...
        def getOName(self) -> str: ...
        def getUName(self) -> str: ...
