from typing import Any, ClassVar, overload
from android.net.http.SslCertificate import SslCertificate
from java.security.cert.X509Certificate import X509Certificate

class SslError:
    SSL_DATE_INVALID: ClassVar[int]
    SSL_EXPIRED: ClassVar[int]
    SSL_IDMISMATCH: ClassVar[int]
    SSL_INVALID: ClassVar[int]
    SSL_MAX_ERROR: ClassVar[int]
    SSL_NOTYETVALID: ClassVar[int]
    SSL_UNTRUSTED: ClassVar[int]
    @overload
    def __init__(self, arg0: int, arg1: SslCertificate) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: X509Certificate) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: SslCertificate, arg2: str) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: X509Certificate, arg2: str) -> None: ...
    def getCertificate(self) -> SslCertificate: ...
    def getUrl(self) -> str: ...
    def addError(self, arg0: int) -> bool: ...
    def hasError(self, arg0: int) -> bool: ...
    def getPrimaryError(self) -> int: ...
    def toString(self) -> str: ...
