from typing import Any, ClassVar, overload
from android.net.Network import Network
from android.net.http.HeaderBlock import HeaderBlock
from android.net.http.HttpException import HttpException
from android.net.http.UploadDataProvider import UploadDataProvider
from android.net.http.UrlResponseInfo import UrlResponseInfo
from java.nio.ByteBuffer import ByteBuffer
from java.util.concurrent.Executor import Executor

class UrlRequest:
    REQUEST_PRIORITY_HIGHEST: ClassVar[int]
    REQUEST_PRIORITY_IDLE: ClassVar[int]
    REQUEST_PRIORITY_LOW: ClassVar[int]
    REQUEST_PRIORITY_LOWEST: ClassVar[int]
    REQUEST_PRIORITY_MEDIUM: ClassVar[int]
    def getHttpMethod(self) -> str: ...
    def getHeaders(self) -> HeaderBlock: ...
    def isCacheDisabled(self) -> bool: ...
    def isDirectExecutorAllowed(self) -> bool: ...
    def getPriority(self) -> int: ...
    def hasTrafficStatsTag(self) -> bool: ...
    def getTrafficStatsTag(self) -> int: ...
    def hasTrafficStatsUid(self) -> bool: ...
    def getTrafficStatsUid(self) -> int: ...
    def start(self) -> None: ...
    def followRedirect(self) -> None: ...
    def read(self, arg0: ByteBuffer) -> None: ...
    def cancel(self) -> None: ...
    def isDone(self) -> bool: ...
    def getStatus(self, arg0: "StatusListener") -> None: ...

    class Builder:
        def setHttpMethod(self, arg0: str) -> "Builder": ...
        def addHeader(self, arg0: str, arg1: str) -> "Builder": ...
        def setCacheDisabled(self, arg0: bool) -> "Builder": ...
        def setPriority(self, arg0: int) -> "Builder": ...
        def setUploadDataProvider(self, arg0: UploadDataProvider, arg1: Executor) -> "Builder": ...
        def setDirectExecutorAllowed(self, arg0: bool) -> "Builder": ...
        def bindToNetwork(self, arg0: Network) -> "Builder": ...
        def setTrafficStatsTag(self, arg0: int) -> "Builder": ...
        def setTrafficStatsUid(self, arg0: int) -> "Builder": ...
        def build(self) -> "UrlRequest": ...

    class Callback:
        def onRedirectReceived(self, arg0: "UrlRequest", arg1: UrlResponseInfo, arg2: str) -> None: ...
        def onResponseStarted(self, arg0: "UrlRequest", arg1: UrlResponseInfo) -> None: ...
        def onReadCompleted(self, arg0: "UrlRequest", arg1: UrlResponseInfo, arg2: ByteBuffer) -> None: ...
        def onSucceeded(self, arg0: "UrlRequest", arg1: UrlResponseInfo) -> None: ...
        def onFailed(self, arg0: "UrlRequest", arg1: UrlResponseInfo, arg2: HttpException) -> None: ...
        def onCanceled(self, arg0: "UrlRequest", arg1: UrlResponseInfo) -> None: ...

    class Status:
        CONNECTING: ClassVar[int]
        DOWNLOADING_PAC_FILE: ClassVar[int]
        ESTABLISHING_PROXY_TUNNEL: ClassVar[int]
        IDLE: ClassVar[int]
        INVALID: ClassVar[int]
        READING_RESPONSE: ClassVar[int]
        RESOLVING_HOST: ClassVar[int]
        RESOLVING_HOST_IN_PAC_FILE: ClassVar[int]
        RESOLVING_PROXY_FOR_URL: ClassVar[int]
        SENDING_REQUEST: ClassVar[int]
        SSL_HANDSHAKE: ClassVar[int]
        WAITING_FOR_AVAILABLE_SOCKET: ClassVar[int]
        WAITING_FOR_CACHE: ClassVar[int]
        WAITING_FOR_DELEGATE: ClassVar[int]
        WAITING_FOR_RESPONSE: ClassVar[int]
        WAITING_FOR_STALLED_SOCKET_POOL: ClassVar[int]

    class StatusListener:
        def onStatus(self, arg0: int) -> None: ...
