from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.media.Session2Token import Session2Token
from android.os.Handler import Handler
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Token:
    """Forward declaration for ``android.media.session.MediaSession.Token``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.media.session.MediaSession.Token')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/media/session/MediaSession/Token
    """
    ...

class MediaSessionManager:
    def notifySession2Created(self, arg0: Session2Token) -> None: ...
    def getActiveSessions(self, arg0: ComponentName) -> list: ...
    def getMediaKeyEventSession(self) -> Token: ...
    def getMediaKeyEventSessionPackageName(self) -> str: ...
    def getSession2Tokens(self) -> list: ...
    @overload
    def addOnActiveSessionsChangedListener(self, arg0: "OnActiveSessionsChangedListener", arg1: ComponentName) -> None: ...
    @overload
    def addOnActiveSessionsChangedListener(self, arg0: "OnActiveSessionsChangedListener", arg1: ComponentName, arg2: Handler) -> None: ...
    def removeOnActiveSessionsChangedListener(self, arg0: "OnActiveSessionsChangedListener") -> None: ...
    @overload
    def addOnSession2TokensChangedListener(self, arg0: "OnSession2TokensChangedListener") -> None: ...
    @overload
    def addOnSession2TokensChangedListener(self, arg0: "OnSession2TokensChangedListener", arg1: Handler) -> None: ...
    def removeOnSession2TokensChangedListener(self, arg0: "OnSession2TokensChangedListener") -> None: ...
    def isTrustedForMediaControl(self, arg0: "RemoteUserInfo") -> bool: ...
    def addOnMediaKeyEventSessionChangedListener(self, arg0: Executor, arg1: "OnMediaKeyEventSessionChangedListener") -> None: ...
    def removeOnMediaKeyEventSessionChangedListener(self, arg0: "OnMediaKeyEventSessionChangedListener") -> None: ...

    class OnActiveSessionsChangedListener:
        def onActiveSessionsChanged(self, arg0: list) -> None: ...

    class OnMediaKeyEventSessionChangedListener:
        def onMediaKeyEventSessionChanged(self, arg0: str, arg1: Token) -> None: ...

    class OnSession2TokensChangedListener:
        def onSession2TokensChanged(self, arg0: list) -> None: ...

    class RemoteUserInfo:
        def __init__(self, arg0: str, arg1: int, arg2: int) -> None: ...
        def getPackageName(self) -> str: ...
        def getPid(self) -> int: ...
        def getUid(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
