from typing import Any, ClassVar, overload
from android.content.ContentValues import ContentValues
from android.content.Context import Context
from android.drm.DrmConvertedStatus import DrmConvertedStatus
from android.drm.DrmErrorEvent import DrmErrorEvent
from android.drm.DrmEvent import DrmEvent
from android.drm.DrmInfo import DrmInfo
from android.drm.DrmInfoEvent import DrmInfoEvent
from android.drm.DrmInfoRequest import DrmInfoRequest
from android.drm.DrmRights import DrmRights
from android.net.Uri import Uri

class DrmManagerClient:
    ERROR_NONE: ClassVar[int]
    ERROR_UNKNOWN: ClassVar[int]
    def __init__(self, arg0: Context) -> None: ...
    def finalize(self) -> None: ...
    def close(self) -> None: ...
    def release(self) -> None: ...
    def setOnInfoListener(self, arg0: "OnInfoListener") -> None: ...
    def setOnEventListener(self, arg0: "OnEventListener") -> None: ...
    def setOnErrorListener(self, arg0: "OnErrorListener") -> None: ...
    def getAvailableDrmEngines(self) -> list[str]: ...
    def getAvailableDrmSupportInfo(self) -> list: ...
    @overload
    def getConstraints(self, arg0: str, arg1: int) -> ContentValues: ...
    @overload
    def getConstraints(self, arg0: Uri, arg1: int) -> ContentValues: ...
    @overload
    def getMetadata(self, arg0: str) -> ContentValues: ...
    @overload
    def getMetadata(self, arg0: Uri) -> ContentValues: ...
    def saveRights(self, arg0: DrmRights, arg1: str, arg2: str) -> int: ...
    @overload
    def canHandle(self, arg0: str, arg1: str) -> bool: ...
    @overload
    def canHandle(self, arg0: Uri, arg1: str) -> bool: ...
    def processDrmInfo(self, arg0: DrmInfo) -> int: ...
    def acquireDrmInfo(self, arg0: DrmInfoRequest) -> DrmInfo: ...
    def acquireRights(self, arg0: DrmInfoRequest) -> int: ...
    @overload
    def getDrmObjectType(self, arg0: str, arg1: str) -> int: ...
    @overload
    def getDrmObjectType(self, arg0: Uri, arg1: str) -> int: ...
    @overload
    def getOriginalMimeType(self, arg0: str) -> str: ...
    @overload
    def getOriginalMimeType(self, arg0: Uri) -> str: ...
    @overload
    def checkRightsStatus(self, arg0: str) -> int: ...
    @overload
    def checkRightsStatus(self, arg0: Uri) -> int: ...
    @overload
    def checkRightsStatus(self, arg0: str, arg1: int) -> int: ...
    @overload
    def checkRightsStatus(self, arg0: Uri, arg1: int) -> int: ...
    @overload
    def removeRights(self, arg0: str) -> int: ...
    @overload
    def removeRights(self, arg0: Uri) -> int: ...
    def removeAllRights(self) -> int: ...
    def openConvertSession(self, arg0: str) -> int: ...
    def convertData(self, arg0: int, arg1: list[int]) -> DrmConvertedStatus: ...
    def closeConvertSession(self, arg0: int) -> DrmConvertedStatus: ...

    class OnErrorListener:
        def onError(self, arg0: "DrmManagerClient", arg1: DrmErrorEvent) -> None: ...

    class OnEventListener:
        def onEvent(self, arg0: "DrmManagerClient", arg1: DrmEvent) -> None: ...

    class OnInfoListener:
        def onInfo(self, arg0: "DrmManagerClient", arg1: DrmInfoEvent) -> None: ...
