from typing import Any, ClassVar, overload
from java.util.function.BinaryOperator import BinaryOperator
from java.util.function.UnaryOperator import UnaryOperator

class AtomicReference:
    @overload
    def __init__(self, arg0: Any) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def get(self) -> Any: ...
    def set(self, arg0: Any) -> None: ...
    def lazySet(self, arg0: Any) -> None: ...
    def compareAndSet(self, arg0: Any, arg1: Any) -> bool: ...
    def weakCompareAndSet(self, arg0: Any, arg1: Any) -> bool: ...
    def weakCompareAndSetPlain(self, arg0: Any, arg1: Any) -> bool: ...
    def getAndSet(self, arg0: Any) -> Any: ...
    def getAndUpdate(self, arg0: UnaryOperator) -> Any: ...
    def updateAndGet(self, arg0: UnaryOperator) -> Any: ...
    def getAndAccumulate(self, arg0: Any, arg1: BinaryOperator) -> Any: ...
    def accumulateAndGet(self, arg0: Any, arg1: BinaryOperator) -> Any: ...
    def toString(self) -> str: ...
    def getPlain(self) -> Any: ...
    def setPlain(self, arg0: Any) -> None: ...
    def getOpaque(self) -> Any: ...
    def setOpaque(self, arg0: Any) -> None: ...
    def getAcquire(self) -> Any: ...
    def setRelease(self, arg0: Any) -> None: ...
    def compareAndExchange(self, arg0: Any, arg1: Any) -> Any: ...
    def compareAndExchangeAcquire(self, arg0: Any, arg1: Any) -> Any: ...
    def compareAndExchangeRelease(self, arg0: Any, arg1: Any) -> Any: ...
    def weakCompareAndSetVolatile(self, arg0: Any, arg1: Any) -> bool: ...
    def weakCompareAndSetAcquire(self, arg0: Any, arg1: Any) -> bool: ...
    def weakCompareAndSetRelease(self, arg0: Any, arg1: Any) -> bool: ...
