from typing import Any, ClassVar, overload

class AtomicStampedReference:
    def __init__(self, arg0: Any, arg1: int) -> None: ...
    def getReference(self) -> Any: ...
    def getStamp(self) -> int: ...
    def get(self, arg0: list[int]) -> Any: ...
    def weakCompareAndSet(self, arg0: Any, arg1: Any, arg2: int, arg3: int) -> bool: ...
    def compareAndSet(self, arg0: Any, arg1: Any, arg2: int, arg3: int) -> bool: ...
    def set(self, arg0: Any, arg1: int) -> None: ...
    def attemptStamp(self, arg0: Any, arg1: int) -> bool: ...
