from typing import Any, ClassVar, overload
from java.util.function.DoubleBinaryOperator import DoubleBinaryOperator

class DoubleAccumulator:
    def __init__(self, arg0: DoubleBinaryOperator, arg1: float) -> None: ...
    def accumulate(self, arg0: float) -> None: ...
    def get(self) -> float: ...
    def reset(self) -> None: ...
    def getThenReset(self) -> float: ...
    def toString(self) -> str: ...
    def doubleValue(self) -> float: ...
    def longValue(self) -> int: ...
    def intValue(self) -> int: ...
    def floatValue(self) -> float: ...
