from typing import Any, ClassVar, overload
from java.util.function.LongBinaryOperator import LongBinaryOperator

class LongAccumulator:
    def __init__(self, arg0: LongBinaryOperator, arg1: int) -> None: ...
    def accumulate(self, arg0: int) -> None: ...
    def get(self) -> int: ...
    def reset(self) -> None: ...
    def getThenReset(self) -> int: ...
    def toString(self) -> str: ...
    def longValue(self) -> int: ...
    def intValue(self) -> int: ...
    def floatValue(self) -> float: ...
    def doubleValue(self) -> float: ...
