from typing import Any, ClassVar, overload
from java.security.Principal import Principal
from java.security.acl.AclEntry import AclEntry
from java.security.acl.Permission import Permission
from java.util.Enumeration import Enumeration

class Acl:
    def setName(self, arg0: Principal, arg1: str) -> None: ...
    def getName(self) -> str: ...
    def addEntry(self, arg0: Principal, arg1: AclEntry) -> bool: ...
    def removeEntry(self, arg0: Principal, arg1: AclEntry) -> bool: ...
    def getPermissions(self, arg0: Principal) -> Enumeration: ...
    def entries(self) -> Enumeration: ...
    def checkPermission(self, arg0: Principal, arg1: Permission) -> bool: ...
    def toString(self) -> str: ...
