from typing import Any, ClassVar, overload
from java.security.Principal import Principal
from java.util.Enumeration import Enumeration

class Group:
    def addMember(self, arg0: Principal) -> bool: ...
    def removeMember(self, arg0: Principal) -> bool: ...
    def isMember(self, arg0: Principal) -> bool: ...
    def members(self) -> Enumeration: ...
