from typing import Any, ClassVar, overload
from java.security.Principal import Principal

class Owner:
    def addOwner(self, arg0: Principal, arg1: Principal) -> bool: ...
    def deleteOwner(self, arg0: Principal, arg1: Principal) -> bool: ...
    def isOwner(self, arg0: Principal) -> bool: ...
