from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.Iterator import Iterator
from java.util.Spliterator import Spliterator

class BaseStream:
    def iterator(self) -> Iterator: ...
    def spliterator(self) -> Spliterator: ...
    def isParallel(self) -> bool: ...
    def sequential(self) -> "BaseStream": ...
    def parallel(self) -> "BaseStream": ...
    def unordered(self) -> "BaseStream": ...
    def onClose(self, arg0: Runnable) -> "BaseStream": ...
    def close(self) -> None: ...
