from typing import Any, ClassVar, overload
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BinaryOperator import BinaryOperator
from java.util.function.Function import Function
from java.util.function.Supplier import Supplier

class Collector:
    def supplier(self) -> Supplier: ...
    def accumulator(self) -> BiConsumer: ...
    def combiner(self) -> BinaryOperator: ...
    def finisher(self) -> Function: ...
    def characteristics(self) -> set: ...
    @overload
    @staticmethod
    def of(arg0: Supplier, arg1: BiConsumer, arg2: BinaryOperator, *arg3: "Characteristics") -> "Collector": ...
    @overload
    @staticmethod
    def of(arg0: Supplier, arg1: BiConsumer, arg2: BinaryOperator, arg3: Function, *arg4: "Characteristics") -> "Collector": ...

    class Characteristics:
        CONCURRENT: ClassVar["Characteristics"]
        UNORDERED: ClassVar["Characteristics"]
        IDENTITY_FINISH: ClassVar["Characteristics"]
        @staticmethod
        def values() -> list["Characteristics"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Characteristics": ...
