from typing import Any, ClassVar, overload
from java.util.DoubleSummaryStatistics import DoubleSummaryStatistics
from java.util.OptionalDouble import OptionalDouble
from java.util.function.BiConsumer import BiConsumer
from java.util.function.DoubleBinaryOperator import DoubleBinaryOperator
from java.util.function.DoubleConsumer import DoubleConsumer
from java.util.function.DoubleFunction import DoubleFunction
from java.util.function.DoublePredicate import DoublePredicate
from java.util.function.DoubleSupplier import DoubleSupplier
from java.util.function.DoubleToIntFunction import DoubleToIntFunction
from java.util.function.DoubleToLongFunction import DoubleToLongFunction
from java.util.function.DoubleUnaryOperator import DoubleUnaryOperator
from java.util.function.ObjDoubleConsumer import ObjDoubleConsumer
from java.util.function.Supplier import Supplier
from java.util.stream.IntStream import IntStream
from java.util.stream.LongStream import LongStream
from java.util.stream.Stream import Stream

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OfDouble:
    """Forward declaration for ``java.util.PrimitiveIterator.OfDouble``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.util.PrimitiveIterator.OfDouble')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/util/PrimitiveIterator/OfDouble.html
    """
    ...

class DoubleStream:
    def filter(self, arg0: DoublePredicate) -> "DoubleStream": ...
    def map(self, arg0: DoubleUnaryOperator) -> "DoubleStream": ...
    def mapToObj(self, arg0: DoubleFunction) -> Stream: ...
    def mapToInt(self, arg0: DoubleToIntFunction) -> IntStream: ...
    def mapToLong(self, arg0: DoubleToLongFunction) -> LongStream: ...
    def flatMap(self, arg0: DoubleFunction) -> "DoubleStream": ...
    def mapMulti(self, arg0: "DoubleMapMultiConsumer") -> "DoubleStream": ...
    def distinct(self) -> "DoubleStream": ...
    def sorted(self) -> "DoubleStream": ...
    def peek(self, arg0: DoubleConsumer) -> "DoubleStream": ...
    def limit(self, arg0: int) -> "DoubleStream": ...
    def skip(self, arg0: int) -> "DoubleStream": ...
    def takeWhile(self, arg0: DoublePredicate) -> "DoubleStream": ...
    def dropWhile(self, arg0: DoublePredicate) -> "DoubleStream": ...
    def forEach(self, arg0: DoubleConsumer) -> None: ...
    def forEachOrdered(self, arg0: DoubleConsumer) -> None: ...
    def toArray(self) -> list[float]: ...
    @overload
    def reduce(self, arg0: float, arg1: DoubleBinaryOperator) -> float: ...
    @overload
    def reduce(self, arg0: DoubleBinaryOperator) -> OptionalDouble: ...
    def collect(self, arg0: Supplier, arg1: ObjDoubleConsumer, arg2: BiConsumer) -> Any: ...
    def sum(self) -> float: ...
    def min(self) -> OptionalDouble: ...
    def max(self) -> OptionalDouble: ...
    def count(self) -> int: ...
    def average(self) -> OptionalDouble: ...
    def summaryStatistics(self) -> DoubleSummaryStatistics: ...
    def anyMatch(self, arg0: DoublePredicate) -> bool: ...
    def allMatch(self, arg0: DoublePredicate) -> bool: ...
    def noneMatch(self, arg0: DoublePredicate) -> bool: ...
    def findFirst(self) -> OptionalDouble: ...
    def findAny(self) -> OptionalDouble: ...
    def boxed(self) -> Stream: ...
    def sequential(self) -> "DoubleStream": ...
    def parallel(self) -> "DoubleStream": ...
    def iterator(self) -> OfDouble: ...
    def spliterator(self) -> OfDouble: ...
    @staticmethod
    def builder() -> "Builder": ...
    @staticmethod
    def empty() -> "DoubleStream": ...
    @overload
    @staticmethod
    def of(arg0: float) -> "DoubleStream": ...
    @overload
    @staticmethod
    def of(*arg0: float) -> "DoubleStream": ...
    @overload
    @staticmethod
    def iterate(arg0: float, arg1: DoubleUnaryOperator) -> "DoubleStream": ...
    @overload
    @staticmethod
    def iterate(arg0: float, arg1: DoublePredicate, arg2: DoubleUnaryOperator) -> "DoubleStream": ...
    @staticmethod
    def generate(arg0: DoubleSupplier) -> "DoubleStream": ...
    @staticmethod
    def concat(arg0: "DoubleStream", arg1: "DoubleStream") -> "DoubleStream": ...

    class Builder:
        def accept(self, arg0: float) -> None: ...
        def add(self, arg0: float) -> "Builder": ...
        def build(self) -> "DoubleStream": ...

    class DoubleMapMultiConsumer:
        def accept(self, arg0: float, arg1: DoubleConsumer) -> None: ...
