from typing import Any, ClassVar, overload
from java.util.IntSummaryStatistics import IntSummaryStatistics
from java.util.OptionalDouble import OptionalDouble
from java.util.OptionalInt import OptionalInt
from java.util.function.BiConsumer import BiConsumer
from java.util.function.IntBinaryOperator import IntBinaryOperator
from java.util.function.IntConsumer import IntConsumer
from java.util.function.IntFunction import IntFunction
from java.util.function.IntPredicate import IntPredicate
from java.util.function.IntSupplier import IntSupplier
from java.util.function.IntToDoubleFunction import IntToDoubleFunction
from java.util.function.IntToLongFunction import IntToLongFunction
from java.util.function.IntUnaryOperator import IntUnaryOperator
from java.util.function.ObjIntConsumer import ObjIntConsumer
from java.util.function.Supplier import Supplier
from java.util.stream.DoubleStream import DoubleStream
from java.util.stream.LongStream import LongStream
from java.util.stream.Stream import Stream

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OfInt:
    """Forward declaration for ``java.util.PrimitiveIterator.OfInt``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.util.PrimitiveIterator.OfInt')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/util/PrimitiveIterator/OfInt.html
    """
    ...

class IntStream:
    def filter(self, arg0: IntPredicate) -> "IntStream": ...
    def map(self, arg0: IntUnaryOperator) -> "IntStream": ...
    def mapToObj(self, arg0: IntFunction) -> Stream: ...
    def mapToLong(self, arg0: IntToLongFunction) -> LongStream: ...
    def mapToDouble(self, arg0: IntToDoubleFunction) -> DoubleStream: ...
    def flatMap(self, arg0: IntFunction) -> "IntStream": ...
    def mapMulti(self, arg0: "IntMapMultiConsumer") -> "IntStream": ...
    def distinct(self) -> "IntStream": ...
    def sorted(self) -> "IntStream": ...
    def peek(self, arg0: IntConsumer) -> "IntStream": ...
    def limit(self, arg0: int) -> "IntStream": ...
    def skip(self, arg0: int) -> "IntStream": ...
    def takeWhile(self, arg0: IntPredicate) -> "IntStream": ...
    def dropWhile(self, arg0: IntPredicate) -> "IntStream": ...
    def forEach(self, arg0: IntConsumer) -> None: ...
    def forEachOrdered(self, arg0: IntConsumer) -> None: ...
    def toArray(self) -> list[int]: ...
    @overload
    def reduce(self, arg0: int, arg1: IntBinaryOperator) -> int: ...
    @overload
    def reduce(self, arg0: IntBinaryOperator) -> OptionalInt: ...
    def collect(self, arg0: Supplier, arg1: ObjIntConsumer, arg2: BiConsumer) -> Any: ...
    def sum(self) -> int: ...
    def min(self) -> OptionalInt: ...
    def max(self) -> OptionalInt: ...
    def count(self) -> int: ...
    def average(self) -> OptionalDouble: ...
    def summaryStatistics(self) -> IntSummaryStatistics: ...
    def anyMatch(self, arg0: IntPredicate) -> bool: ...
    def allMatch(self, arg0: IntPredicate) -> bool: ...
    def noneMatch(self, arg0: IntPredicate) -> bool: ...
    def findFirst(self) -> OptionalInt: ...
    def findAny(self) -> OptionalInt: ...
    def asLongStream(self) -> LongStream: ...
    def asDoubleStream(self) -> DoubleStream: ...
    def boxed(self) -> Stream: ...
    def sequential(self) -> "IntStream": ...
    def parallel(self) -> "IntStream": ...
    def iterator(self) -> OfInt: ...
    def spliterator(self) -> OfInt: ...
    @staticmethod
    def builder() -> "Builder": ...
    @staticmethod
    def empty() -> "IntStream": ...
    @overload
    @staticmethod
    def of(arg0: int) -> "IntStream": ...
    @overload
    @staticmethod
    def of(*arg0: int) -> "IntStream": ...
    @overload
    @staticmethod
    def iterate(arg0: int, arg1: IntUnaryOperator) -> "IntStream": ...
    @overload
    @staticmethod
    def iterate(arg0: int, arg1: IntPredicate, arg2: IntUnaryOperator) -> "IntStream": ...
    @staticmethod
    def generate(arg0: IntSupplier) -> "IntStream": ...
    @staticmethod
    def range(arg0: int, arg1: int) -> "IntStream": ...
    @staticmethod
    def rangeClosed(arg0: int, arg1: int) -> "IntStream": ...
    @staticmethod
    def concat(arg0: "IntStream", arg1: "IntStream") -> "IntStream": ...

    class Builder:
        def accept(self, arg0: int) -> None: ...
        def add(self, arg0: int) -> "Builder": ...
        def build(self) -> "IntStream": ...

    class IntMapMultiConsumer:
        def accept(self, arg0: int, arg1: IntConsumer) -> None: ...
