from typing import Any, ClassVar, overload
from android.net.ipsec.ike.IkeTunnelConnectionParams import IkeTunnelConnectionParams

class VcnGatewayConnectionConfig:
    VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY: ClassVar[int]
    def getGatewayConnectionName(self) -> str: ...
    def getExposedCapabilities(self) -> list[int]: ...
    def getVcnUnderlyingNetworkPriorities(self) -> list: ...
    def getRetryIntervalsMillis(self) -> list[int]: ...
    def getMaxMtu(self) -> int: ...
    def getMinUdpPort4500NatTimeoutSeconds(self) -> int: ...
    def isSafeModeEnabled(self) -> bool: ...
    def hasGatewayOption(self, arg0: int) -> bool: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...

    class Builder:
        def __init__(self, arg0: str, arg1: IkeTunnelConnectionParams) -> None: ...
        def addExposedCapability(self, arg0: int) -> "Builder": ...
        def removeExposedCapability(self, arg0: int) -> "Builder": ...
        def setVcnUnderlyingNetworkPriorities(self, arg0: list) -> "Builder": ...
        def setRetryIntervalsMillis(self, arg0: list[int]) -> "Builder": ...
        def setMaxMtu(self, arg0: int) -> "Builder": ...
        def setMinUdpPort4500NatTimeoutSeconds(self, arg0: int) -> "Builder": ...
        def addGatewayOption(self, arg0: int) -> "Builder": ...
        def removeGatewayOption(self, arg0: int) -> "Builder": ...
        def setSafeModeEnabled(self, arg0: bool) -> "Builder": ...
        def build(self) -> "VcnGatewayConnectionConfig": ...
