from typing import Any, ClassVar, overload
from android.net.vcn.VcnConfig import VcnConfig
from android.os.ParcelUuid import ParcelUuid
from java.lang.Throwable import Throwable
from java.util.concurrent.Executor import Executor

class VcnManager:
    VCN_ERROR_CODE_CONFIG_ERROR: ClassVar[int]
    VCN_ERROR_CODE_INTERNAL_ERROR: ClassVar[int]
    VCN_ERROR_CODE_NETWORK_ERROR: ClassVar[int]
    VCN_STATUS_CODE_ACTIVE: ClassVar[int]
    VCN_STATUS_CODE_INACTIVE: ClassVar[int]
    VCN_STATUS_CODE_NOT_CONFIGURED: ClassVar[int]
    VCN_STATUS_CODE_SAFE_MODE: ClassVar[int]
    def setVcnConfig(self, arg0: ParcelUuid, arg1: VcnConfig) -> None: ...
    def clearVcnConfig(self, arg0: ParcelUuid) -> None: ...
    def getConfiguredSubscriptionGroups(self) -> list: ...
    def registerVcnStatusCallback(self, arg0: ParcelUuid, arg1: Executor, arg2: "VcnStatusCallback") -> None: ...
    def unregisterVcnStatusCallback(self, arg0: "VcnStatusCallback") -> None: ...

    class VcnStatusCallback:
        def __init__(self) -> None: ...
        def onStatusChanged(self, arg0: int) -> None: ...
        def onGatewayConnectionError(self, arg0: str, arg1: int, arg2: Throwable) -> None: ...
