from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.IBinder import IBinder
from android.os.PersistableBundle import PersistableBundle
from android.service.carrier.CarrierIdentifier import CarrierIdentifier

class CarrierService:
    CARRIER_SERVICE_INTERFACE: ClassVar[str]
    def __init__(self) -> None: ...
    @overload
    def onLoadConfig(self, arg0: CarrierIdentifier) -> PersistableBundle: ...
    @overload
    def onLoadConfig(self, arg0: int, arg1: CarrierIdentifier) -> PersistableBundle: ...
    @overload
    def notifyCarrierNetworkChange(self, arg0: bool) -> None: ...
    @overload
    def notifyCarrierNetworkChange(self, arg0: int, arg1: bool) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
