from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.Intent import Intent
from android.net.Uri import Uri
from android.os.IBinder import IBinder
from android.service.notification.Condition import Condition

class ConditionProviderService:
    EXTRA_RULE_ID: ClassVar[str]
    META_DATA_CONFIGURATION_ACTIVITY: ClassVar[str]
    META_DATA_RULE_INSTANCE_LIMIT: ClassVar[str]
    META_DATA_RULE_TYPE: ClassVar[str]
    SERVICE_INTERFACE: ClassVar[str]
    def __init__(self) -> None: ...
    def onConnected(self) -> None: ...
    def onRequestConditions(self, arg0: int) -> None: ...
    def onSubscribe(self, arg0: Uri) -> None: ...
    def onUnsubscribe(self, arg0: Uri) -> None: ...
    @staticmethod
    def requestRebind(arg0: ComponentName) -> None: ...
    def requestUnbind(self) -> None: ...
    def notifyCondition(self, arg0: Condition) -> None: ...
    def notifyConditions(self, *arg0: Condition) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
