from typing import Any, ClassVar, overload
from android.app.Notification import Notification
from android.os.Parcel import Parcel
from android.os.UserHandle import UserHandle

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class StatusBarNotification:
    CREATOR: ClassVar[Creator]
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: str, arg4: int, arg5: int, arg6: int, arg7: Notification, arg8: UserHandle, arg9: int) -> None: ...
    @overload
    def __init__(self, arg0: Parcel) -> None: ...
    def isGroup(self) -> bool: ...
    def isAppGroup(self) -> bool: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def clone(self) -> "StatusBarNotification": ...
    def toString(self) -> str: ...
    def isOngoing(self) -> bool: ...
    def isClearable(self) -> bool: ...
    def getUserId(self) -> int: ...
    def getPackageName(self) -> str: ...
    def getId(self) -> int: ...
    def getTag(self) -> str: ...
    def getUid(self) -> int: ...
    def getOpPkg(self) -> str: ...
    def getNotification(self) -> Notification: ...
    def getUser(self) -> UserHandle: ...
    def getPostTime(self) -> int: ...
    def getKey(self) -> str: ...
    def getGroupKey(self) -> str: ...
    def setOverrideGroupKey(self, arg0: str) -> None: ...
    def getOverrideGroupKey(self) -> str: ...
