from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ZenDeviceEffects:
    CREATOR: ClassVar[Creator]
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def shouldDisplayGrayscale(self) -> bool: ...
    def shouldSuppressAmbientDisplay(self) -> bool: ...
    def shouldDimWallpaper(self) -> bool: ...
    def shouldUseNightMode(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: "ZenDeviceEffects") -> None: ...
        def setShouldDisplayGrayscale(self, arg0: bool) -> "Builder": ...
        def setShouldSuppressAmbientDisplay(self, arg0: bool) -> "Builder": ...
        def setShouldDimWallpaper(self, arg0: bool) -> "Builder": ...
        def setShouldUseNightMode(self, arg0: bool) -> "Builder": ...
        def build(self) -> "ZenDeviceEffects": ...
