from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ZenPolicy:
    CONVERSATION_SENDERS_ANYONE: ClassVar[int]
    CONVERSATION_SENDERS_IMPORTANT: ClassVar[int]
    CONVERSATION_SENDERS_NONE: ClassVar[int]
    CONVERSATION_SENDERS_UNSET: ClassVar[int]
    CREATOR: ClassVar[Creator]
    PEOPLE_TYPE_ANYONE: ClassVar[int]
    PEOPLE_TYPE_CONTACTS: ClassVar[int]
    PEOPLE_TYPE_NONE: ClassVar[int]
    PEOPLE_TYPE_STARRED: ClassVar[int]
    PEOPLE_TYPE_UNSET: ClassVar[int]
    STATE_ALLOW: ClassVar[int]
    STATE_DISALLOW: ClassVar[int]
    STATE_UNSET: ClassVar[int]
    def getPriorityConversationSenders(self) -> int: ...
    def getPriorityMessageSenders(self) -> int: ...
    def getPriorityCallSenders(self) -> int: ...
    def getPriorityCategoryConversations(self) -> int: ...
    def getPriorityCategoryReminders(self) -> int: ...
    def getPriorityCategoryEvents(self) -> int: ...
    def getPriorityCategoryMessages(self) -> int: ...
    def getPriorityCategoryCalls(self) -> int: ...
    def getPriorityCategoryRepeatCallers(self) -> int: ...
    def getPriorityCategoryAlarms(self) -> int: ...
    def getPriorityCategoryMedia(self) -> int: ...
    def getPriorityCategorySystem(self) -> int: ...
    def getVisualEffectFullScreenIntent(self) -> int: ...
    def getVisualEffectLights(self) -> int: ...
    def getVisualEffectPeek(self) -> int: ...
    def getVisualEffectStatusBar(self) -> int: ...
    def getVisualEffectBadge(self) -> int: ...
    def getVisualEffectAmbient(self) -> int: ...
    def getVisualEffectNotificationList(self) -> int: ...
    def getPriorityChannelsAllowed(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "ZenPolicy": ...
        def allowAllSounds(self) -> "Builder": ...
        def disallowAllSounds(self) -> "Builder": ...
        def showAllVisualEffects(self) -> "Builder": ...
        def hideAllVisualEffects(self) -> "Builder": ...
        def allowReminders(self, arg0: bool) -> "Builder": ...
        def allowEvents(self, arg0: bool) -> "Builder": ...
        def allowConversations(self, arg0: int) -> "Builder": ...
        def allowMessages(self, arg0: int) -> "Builder": ...
        def allowCalls(self, arg0: int) -> "Builder": ...
        def allowRepeatCallers(self, arg0: bool) -> "Builder": ...
        def allowAlarms(self, arg0: bool) -> "Builder": ...
        def allowMedia(self, arg0: bool) -> "Builder": ...
        def allowSystem(self, arg0: bool) -> "Builder": ...
        def showFullScreenIntent(self, arg0: bool) -> "Builder": ...
        def showLights(self, arg0: bool) -> "Builder": ...
        def showPeeking(self, arg0: bool) -> "Builder": ...
        def showStatusBarIcons(self, arg0: bool) -> "Builder": ...
        def showBadges(self, arg0: bool) -> "Builder": ...
        def showInAmbientDisplay(self, arg0: bool) -> "Builder": ...
        def showInNotificationList(self, arg0: bool) -> "Builder": ...
        def allowPriorityChannels(self, arg0: bool) -> "Builder": ...
