from typing import Any, ClassVar, overload
from android.app.sdksandbox.SandboxedSdk import SandboxedSdk
from android.content.Context import Context
from android.os.Bundle import Bundle
from android.view.View import View

class SandboxedSdkProvider:
    def __init__(self) -> None: ...
    def attachContext(self, arg0: Context) -> None: ...
    def getContext(self) -> Context: ...
    def onLoadSdk(self, arg0: Bundle) -> SandboxedSdk: ...
    def beforeUnloadSdk(self) -> None: ...
    def getView(self, arg0: Context, arg1: Bundle, arg2: int, arg3: int) -> View: ...
