from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.app.slice.Slice import Slice
from android.content.ContentValues import ContentValues
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.pm.ProviderInfo import ProviderInfo
from android.database.Cursor import Cursor
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.CancellationSignal import CancellationSignal

class SliceProvider:
    SLICE_TYPE: ClassVar[str]
    @overload
    def __init__(self, *arg0: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def attachInfo(self, arg0: Context, arg1: ProviderInfo) -> None: ...
    def onBindSlice(self, arg0: Uri, arg1: set) -> Slice: ...
    def onSlicePinned(self, arg0: Uri) -> None: ...
    def onSliceUnpinned(self, arg0: Uri) -> None: ...
    def onGetSliceDescendants(self, arg0: Uri) -> list: ...
    def onMapIntentToUri(self, arg0: Intent) -> Uri: ...
    def onCreatePermissionRequest(self, arg0: Uri) -> PendingIntent: ...
    def update(self, arg0: Uri, arg1: ContentValues, arg2: str, arg3: list[str]) -> int: ...
    def delete(self, arg0: Uri, arg1: str, arg2: list[str]) -> int: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str) -> Cursor: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str, arg5: CancellationSignal) -> Cursor: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: Bundle, arg3: CancellationSignal) -> Cursor: ...
    def insert(self, arg0: Uri, arg1: ContentValues) -> Uri: ...
    def getType(self, arg0: Uri) -> str: ...
    def call(self, arg0: str, arg1: str, arg2: Bundle) -> Bundle: ...
