from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.app.RemoteInput import RemoteInput
from android.app.slice.Slice import Slice
from android.graphics.drawable.Icon import Icon
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class SliceItem:
    CREATOR: ClassVar[Creator]
    FORMAT_ACTION: ClassVar[str]
    FORMAT_BUNDLE: ClassVar[str]
    FORMAT_IMAGE: ClassVar[str]
    FORMAT_INT: ClassVar[str]
    FORMAT_LONG: ClassVar[str]
    FORMAT_REMOTE_INPUT: ClassVar[str]
    FORMAT_SLICE: ClassVar[str]
    FORMAT_TEXT: ClassVar[str]
    def getHints(self) -> list: ...
    def getFormat(self) -> str: ...
    def getSubType(self) -> str: ...
    def getText(self) -> str: ...
    def getBundle(self) -> Bundle: ...
    def getIcon(self) -> Icon: ...
    def getAction(self) -> PendingIntent: ...
    def getRemoteInput(self) -> RemoteInput: ...
    def getInt(self) -> int: ...
    def getSlice(self) -> Slice: ...
    def getLong(self) -> int: ...
    def hasHint(self, arg0: str) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
