from typing import Any, ClassVar, overload
from android.gesture.OrientedBoundingBox import OrientedBoundingBox
from android.graphics.Path import Path
from android.graphics.RectF import RectF

class GestureStroke:
    boundingBox: RectF
    length: float
    points: list[float]
    def __init__(self, arg0: list) -> None: ...
    def clone(self) -> Any: ...
    def getPath(self) -> Path: ...
    def toPath(self, arg0: float, arg1: float, arg2: int) -> Path: ...
    def clearPath(self) -> None: ...
    def computeOrientedBoundingBox(self) -> OrientedBoundingBox: ...
