from typing import Any, ClassVar, overload
from android.credentials.CredentialOption import CredentialOption
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class GetCredentialRequest:
    CREATOR: ClassVar[Creator]
    def getCredentialOptions(self) -> list: ...
    def getData(self) -> Bundle: ...
    def getOrigin(self) -> str: ...
    def alwaysSendAppInfoToProvider(self) -> bool: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: Bundle) -> None: ...
        def addCredentialOption(self, arg0: CredentialOption) -> "Builder": ...
        def setAlwaysSendAppInfoToProvider(self, arg0: bool) -> "Builder": ...
        def setCredentialOptions(self, arg0: list) -> "Builder": ...
        def setOrigin(self, arg0: str) -> "Builder": ...
        def build(self) -> "GetCredentialRequest": ...
