from typing import Any, ClassVar, overload

class PrepareGetCredentialResponse:
    def hasCredentialResults(self, arg0: str) -> bool: ...
    def hasAuthenticationResults(self) -> bool: ...
    def hasRemoteResults(self) -> bool: ...
    def getPendingGetCredentialHandle(self) -> "PendingGetCredentialHandle": ...

    class PendingGetCredentialHandle:
        ...
