from typing import Any, ClassVar, overload

class CredentialDataResult:
    def getDeviceNameSpaces(self) -> list[int]: ...
    def getDeviceMac(self) -> list[int]: ...
    def getDeviceSignature(self) -> list[int]: ...
    def getStaticAuthenticationData(self) -> list[int]: ...
    def getDeviceSignedEntries(self) -> "Entries": ...
    def getIssuerSignedEntries(self) -> "Entries": ...

    class Entries:
        STATUS_NOT_IN_REQUEST_MESSAGE: ClassVar[int]
        STATUS_NOT_REQUESTED: ClassVar[int]
        STATUS_NO_ACCESS_CONTROL_PROFILES: ClassVar[int]
        STATUS_NO_SUCH_ENTRY: ClassVar[int]
        STATUS_OK: ClassVar[int]
        STATUS_READER_AUTHENTICATION_FAILED: ClassVar[int]
        STATUS_USER_AUTHENTICATION_FAILED: ClassVar[int]
        def getNamespaces(self) -> list: ...
        def getEntryNames(self, arg0: str) -> list: ...
        def getRetrievedEntryNames(self, arg0: str) -> list: ...
        def getStatus(self, arg0: str, arg1: str) -> int: ...
        def getEntry(self, arg0: str, arg1: str) -> list[int]: ...
