from typing import Any, ClassVar, overload
from android.security.identity.AccessControlProfile import AccessControlProfile

class PersonalizationData:

    class Builder:
        def __init__(self) -> None: ...
        def putEntry(self, arg0: str, arg1: str, arg2: list, arg3: list[int]) -> "Builder": ...
        def addAccessControlProfile(self, arg0: AccessControlProfile) -> "Builder": ...
        def build(self) -> "PersonalizationData": ...
