from typing import Any, ClassVar, overload
from android.security.identity.CredentialDataRequest import CredentialDataRequest
from android.security.identity.CredentialDataResult import CredentialDataResult
from java.security.KeyPair import KeyPair
from java.security.PublicKey import PublicKey

class PresentationSession:
    def getEphemeralKeyPair(self) -> KeyPair: ...
    def setReaderEphemeralPublicKey(self, arg0: PublicKey) -> None: ...
    def setSessionTranscript(self, arg0: list[int]) -> None: ...
    def getCredentialData(self, arg0: str, arg1: CredentialDataRequest) -> CredentialDataResult: ...
