from typing import Any, ClassVar, overload
from java.security.Provider import Provider
from java.security.PublicKey import PublicKey

class Certificate:
    def __init__(self, arg0: str) -> None: ...
    def getType(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getEncoded(self) -> list[int]: ...
    @overload
    def verify(self, arg0: PublicKey) -> None: ...
    @overload
    def verify(self, arg0: PublicKey, arg1: str) -> None: ...
    @overload
    def verify(self, arg0: PublicKey, arg1: Provider) -> None: ...
    def toString(self) -> str: ...
    def getPublicKey(self) -> PublicKey: ...
    def writeReplace(self) -> Any: ...

    class CertificateRep:
        def __init__(self, arg0: str, arg1: list[int]) -> None: ...
        def readResolve(self) -> Any: ...
