from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator

class CertPath:
    def __init__(self, arg0: str) -> None: ...
    def getType(self) -> str: ...
    def getEncodings(self) -> Iterator: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    @overload
    def getEncoded(self) -> list[int]: ...
    @overload
    def getEncoded(self, arg0: str) -> list[int]: ...
    def getCertificates(self) -> list: ...
    def writeReplace(self) -> Any: ...

    class CertPathRep:
        def __init__(self, arg0: str, arg1: list[int]) -> None: ...
        def readResolve(self) -> Any: ...
