from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.security.Provider import Provider
from java.security.cert.CRL import CRL
from java.security.cert.CertPath import CertPath
from java.security.cert.Certificate import Certificate
from java.security.cert.CertificateFactorySpi import CertificateFactorySpi
from java.util.Iterator import Iterator

class CertificateFactory:
    def __init__(self, arg0: CertificateFactorySpi, arg1: Provider, arg2: str) -> None: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "CertificateFactory": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: str) -> "CertificateFactory": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: Provider) -> "CertificateFactory": ...
    def getProvider(self) -> Provider: ...
    def getType(self) -> str: ...
    def generateCertificate(self, arg0: InputStream) -> Certificate: ...
    def getCertPathEncodings(self) -> Iterator: ...
    @overload
    def generateCertPath(self, arg0: InputStream) -> CertPath: ...
    @overload
    def generateCertPath(self, arg0: InputStream, arg1: str) -> CertPath: ...
    @overload
    def generateCertPath(self, arg0: list) -> CertPath: ...
    def generateCertificates(self, arg0: InputStream) -> list: ...
    def generateCRL(self, arg0: InputStream) -> CRL: ...
    def generateCRLs(self, arg0: InputStream) -> list: ...
