from typing import Any, ClassVar, overload
from java.security.cert.Certificate import Certificate

class CertPathChecker:
    def init(self, arg0: bool) -> None: ...
    def isForwardCheckingSupported(self) -> bool: ...
    def check(self, arg0: Certificate) -> None: ...
