from typing import Any, ClassVar, overload
from java.security.cert.CRLSelector import CRLSelector
from java.security.cert.CertSelector import CertSelector
from java.security.cert.CertStoreParameters import CertStoreParameters

class CertStoreSpi:
    def __init__(self, arg0: CertStoreParameters) -> None: ...
    def engineGetCertificates(self, arg0: CertSelector) -> list: ...
    def engineGetCRLs(self, arg0: CRLSelector) -> list: ...
