from typing import Any, ClassVar, overload
from java.security.PublicKey import PublicKey
from java.security.cert.PolicyNode import PolicyNode
from java.security.cert.TrustAnchor import TrustAnchor

class PKIXCertPathValidatorResult:
    def __init__(self, arg0: TrustAnchor, arg1: PolicyNode, arg2: PublicKey) -> None: ...
    def getTrustAnchor(self) -> TrustAnchor: ...
    def getPolicyTree(self) -> PolicyNode: ...
    def getPublicKey(self) -> PublicKey: ...
    def clone(self) -> Any: ...
    def toString(self) -> str: ...
