from typing import Any, ClassVar, overload
from java.security.KeyStore import KeyStore
from java.security.cert.CertSelector import CertSelector

class PKIXBuilderParameters:
    @overload
    def __init__(self, arg0: set, arg1: CertSelector) -> None: ...
    @overload
    def __init__(self, arg0: KeyStore, arg1: CertSelector) -> None: ...
    def setMaxPathLength(self, arg0: int) -> None: ...
    def getMaxPathLength(self) -> int: ...
    def toString(self) -> str: ...
