from typing import Any, ClassVar, overload
from java.security.cert.Certificate import Certificate

class PKIXCertPathChecker:
    def __init__(self) -> None: ...
    def init(self, arg0: bool) -> None: ...
    def isForwardCheckingSupported(self) -> bool: ...
    def getSupportedExtensions(self) -> set: ...
    @overload
    def check(self, arg0: Certificate, arg1: list) -> None: ...
    @overload
    def check(self, arg0: Certificate) -> None: ...
    def clone(self) -> Any: ...
