from typing import Any, ClassVar, overload

class PolicyQualifierInfo:
    def __init__(self, arg0: list[int]) -> None: ...
    def getPolicyQualifierId(self) -> str: ...
    def getEncoded(self) -> list[int]: ...
    def getPolicyQualifier(self) -> list[int]: ...
    def toString(self) -> str: ...
