from typing import Any, ClassVar, overload
from java.security.PublicKey import PublicKey
from java.security.cert.X509Certificate import X509Certificate
from javax.security.auth.x500.X500Principal import X500Principal

class TrustAnchor:
    @overload
    def __init__(self, arg0: X509Certificate, arg1: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: X500Principal, arg1: PublicKey, arg2: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: PublicKey, arg2: list[int]) -> None: ...
    def getTrustedCert(self) -> X509Certificate: ...
    def getCA(self) -> X500Principal: ...
    def getCAName(self) -> str: ...
    def getCAPublicKey(self) -> PublicKey: ...
    def getNameConstraints(self) -> list[int]: ...
    def toString(self) -> str: ...
