from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.PublicKey import PublicKey
from java.security.cert.Certificate import Certificate
from java.security.cert.X509Certificate import X509Certificate
from java.util.Date import Date
from javax.security.auth.x500.X500Principal import X500Principal

class X509CertSelector:
    def __init__(self) -> None: ...
    def setCertificate(self, arg0: X509Certificate) -> None: ...
    def setSerialNumber(self, arg0: BigInteger) -> None: ...
    @overload
    def setIssuer(self, arg0: X500Principal) -> None: ...
    @overload
    def setIssuer(self, arg0: str) -> None: ...
    @overload
    def setIssuer(self, arg0: list[int]) -> None: ...
    @overload
    def setSubject(self, arg0: X500Principal) -> None: ...
    @overload
    def setSubject(self, arg0: str) -> None: ...
    @overload
    def setSubject(self, arg0: list[int]) -> None: ...
    def setSubjectKeyIdentifier(self, arg0: list[int]) -> None: ...
    def setAuthorityKeyIdentifier(self, arg0: list[int]) -> None: ...
    def setCertificateValid(self, arg0: Date) -> None: ...
    def setPrivateKeyValid(self, arg0: Date) -> None: ...
    def setSubjectPublicKeyAlgID(self, arg0: str) -> None: ...
    @overload
    def setSubjectPublicKey(self, arg0: PublicKey) -> None: ...
    @overload
    def setSubjectPublicKey(self, arg0: list[int]) -> None: ...
    def setKeyUsage(self, arg0: list[bool]) -> None: ...
    def setExtendedKeyUsage(self, arg0: set) -> None: ...
    def setMatchAllSubjectAltNames(self, arg0: bool) -> None: ...
    def setSubjectAlternativeNames(self, arg0: list) -> None: ...
    @overload
    def addSubjectAlternativeName(self, arg0: int, arg1: str) -> None: ...
    @overload
    def addSubjectAlternativeName(self, arg0: int, arg1: list[int]) -> None: ...
    def setNameConstraints(self, arg0: list[int]) -> None: ...
    def setBasicConstraints(self, arg0: int) -> None: ...
    def setPolicy(self, arg0: set) -> None: ...
    def setPathToNames(self, arg0: list) -> None: ...
    @overload
    def addPathToName(self, arg0: int, arg1: str) -> None: ...
    @overload
    def addPathToName(self, arg0: int, arg1: list[int]) -> None: ...
    def getCertificate(self) -> X509Certificate: ...
    def getSerialNumber(self) -> BigInteger: ...
    def getIssuer(self) -> X500Principal: ...
    def getIssuerAsString(self) -> str: ...
    def getIssuerAsBytes(self) -> list[int]: ...
    def getSubject(self) -> X500Principal: ...
    def getSubjectAsString(self) -> str: ...
    def getSubjectAsBytes(self) -> list[int]: ...
    def getSubjectKeyIdentifier(self) -> list[int]: ...
    def getAuthorityKeyIdentifier(self) -> list[int]: ...
    def getCertificateValid(self) -> Date: ...
    def getPrivateKeyValid(self) -> Date: ...
    def getSubjectPublicKeyAlgID(self) -> str: ...
    def getSubjectPublicKey(self) -> PublicKey: ...
    def getKeyUsage(self) -> list[bool]: ...
    def getExtendedKeyUsage(self) -> set: ...
    def getMatchAllSubjectAltNames(self) -> bool: ...
    def getSubjectAlternativeNames(self) -> list: ...
    def getNameConstraints(self) -> list[int]: ...
    def getBasicConstraints(self) -> int: ...
    def getPolicy(self) -> set: ...
    def getPathToNames(self) -> list: ...
    def toString(self) -> str: ...
    def match_(self, arg0: Certificate) -> bool: ...
    def clone(self) -> Any: ...
