from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.Principal import Principal
from java.security.Provider import Provider
from java.security.PublicKey import PublicKey
from java.util.Date import Date
from javax.security.auth.x500.X500Principal import X500Principal

class X509Certificate:
    def __init__(self) -> None: ...
    @overload
    def checkValidity(self) -> None: ...
    @overload
    def checkValidity(self, arg0: Date) -> None: ...
    def getVersion(self) -> int: ...
    def getSerialNumber(self) -> BigInteger: ...
    def getIssuerDN(self) -> Principal: ...
    def getIssuerX500Principal(self) -> X500Principal: ...
    def getSubjectDN(self) -> Principal: ...
    def getSubjectX500Principal(self) -> X500Principal: ...
    def getNotBefore(self) -> Date: ...
    def getNotAfter(self) -> Date: ...
    def getTBSCertificate(self) -> list[int]: ...
    def getSignature(self) -> list[int]: ...
    def getSigAlgName(self) -> str: ...
    def getSigAlgOID(self) -> str: ...
    def getSigAlgParams(self) -> list[int]: ...
    def getIssuerUniqueID(self) -> list[bool]: ...
    def getSubjectUniqueID(self) -> list[bool]: ...
    def getKeyUsage(self) -> list[bool]: ...
    def getExtendedKeyUsage(self) -> list: ...
    def getBasicConstraints(self) -> int: ...
    def getSubjectAlternativeNames(self) -> list: ...
    def getIssuerAlternativeNames(self) -> list: ...
    def verify(self, arg0: PublicKey, arg1: Provider) -> None: ...
