from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.Principal import Principal
from java.security.Provider import Provider
from java.security.PublicKey import PublicKey
from java.security.cert.X509CRLEntry import X509CRLEntry
from java.security.cert.X509Certificate import X509Certificate
from java.util.Date import Date
from javax.security.auth.x500.X500Principal import X500Principal

class X509CRL:
    def __init__(self) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getEncoded(self) -> list[int]: ...
    @overload
    def verify(self, arg0: PublicKey) -> None: ...
    @overload
    def verify(self, arg0: PublicKey, arg1: str) -> None: ...
    @overload
    def verify(self, arg0: PublicKey, arg1: Provider) -> None: ...
    def getVersion(self) -> int: ...
    def getIssuerDN(self) -> Principal: ...
    def getIssuerX500Principal(self) -> X500Principal: ...
    def getThisUpdate(self) -> Date: ...
    def getNextUpdate(self) -> Date: ...
    @overload
    def getRevokedCertificate(self, arg0: BigInteger) -> X509CRLEntry: ...
    @overload
    def getRevokedCertificate(self, arg0: X509Certificate) -> X509CRLEntry: ...
    def getRevokedCertificates(self) -> set: ...
    def getTBSCertList(self) -> list[int]: ...
    def getSignature(self) -> list[int]: ...
    def getSigAlgName(self) -> str: ...
    def getSigAlgOID(self) -> str: ...
    def getSigAlgParams(self) -> list[int]: ...
