from typing import Any, ClassVar, overload

class DownloadCompletedOutput:
    def getRetainedKeys(self) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRetainedKeys(self, arg0: list) -> "Builder": ...
        def addRetainedKey(self, arg0: str) -> "Builder": ...
        def build(self) -> "DownloadCompletedOutput": ...
