from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.RequestLogRecord import RequestLogRecord
from android.content.ContentValues import ContentValues
from android.os.Parcel import Parcel
from java.time.Instant import Instant

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class EventLogRecord:
    CREATOR: ClassVar[Creator]
    def getTime(self) -> Instant: ...
    def getRowIndex(self) -> int: ...
    def getType(self) -> int: ...
    def getData(self) -> ContentValues: ...
    def getRequestLogRecord(self) -> RequestLogRecord: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRowIndex(self, arg0: int) -> "Builder": ...
        def setType(self, arg0: int) -> "Builder": ...
        def setData(self, arg0: ContentValues) -> "Builder": ...
        def setRequestLogRecord(self, arg0: RequestLogRecord) -> "Builder": ...
        def build(self) -> "EventLogRecord": ...
