from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.EventLogRecord import EventLogRecord

class EventOutput:
    def getEventLogRecord(self) -> EventLogRecord: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setEventLogRecord(self, arg0: EventLogRecord) -> "Builder": ...
        def build(self) -> "EventOutput": ...
