from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.EventLogRecord import EventLogRecord
from android.adservices.ondevicepersonalization.RenderingConfig import RenderingConfig
from android.adservices.ondevicepersonalization.RequestLogRecord import RequestLogRecord

class ExecuteOutput:
    def getRequestLogRecord(self) -> RequestLogRecord: ...
    def getRenderingConfig(self) -> RenderingConfig: ...
    def getEventLogRecords(self) -> list: ...
    def getOutputData(self) -> list[int]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRequestLogRecord(self, arg0: RequestLogRecord) -> "Builder": ...
        def setRenderingConfig(self, arg0: RenderingConfig) -> "Builder": ...
        def setEventLogRecords(self, arg0: list) -> "Builder": ...
        def addEventLogRecord(self, arg0: EventLogRecord) -> "Builder": ...
        def setOutputData(self, *arg0: int) -> "Builder": ...
        def build(self) -> "ExecuteOutput": ...
