from typing import Any, ClassVar, overload

class FederatedComputeInput:
    def getPopulationName(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setPopulationName(self, arg0: str) -> "Builder": ...
        def build(self) -> "FederatedComputeInput": ...
