from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.InferenceOutput import InferenceOutput
from android.adservices.ondevicepersonalization.KeyValueStore import KeyValueStore

class InferenceInput:
    def getParams(self) -> "Params": ...
    def getInputData(self) -> list: ...
    def getBatchSize(self) -> int: ...
    def getExpectedOutputStructure(self) -> InferenceOutput: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, arg0: "Params", arg1: list, arg2: InferenceOutput) -> None: ...
        def setParams(self, arg0: "Params") -> "Builder": ...
        def setInputData(self, *arg0: Any) -> "Builder": ...
        def setBatchSize(self, arg0: int) -> "Builder": ...
        def setExpectedOutputStructure(self, arg0: InferenceOutput) -> "Builder": ...
        def build(self) -> "InferenceInput": ...

    class Params:
        DELEGATE_CPU: ClassVar[int]
        MODEL_TYPE_TENSORFLOW_LITE: ClassVar[int]
        def getKeyValueStore(self) -> KeyValueStore: ...
        def getModelKey(self) -> str: ...
        def getDelegateType(self) -> int: ...
        def getModelType(self) -> int: ...
        def getRecommendedNumThreads(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

        class Builder:
            def __init__(self, arg0: KeyValueStore, arg1: str) -> None: ...
            def setKeyValueStore(self, arg0: KeyValueStore) -> "Builder": ...
            def setModelKey(self, arg0: str) -> "Builder": ...
            def setDelegateType(self, arg0: int) -> "Builder": ...
            def setModelType(self, arg0: int) -> "Builder": ...
            def setRecommendedNumThreads(self, arg0: int) -> "Builder": ...
            def build(self) -> "Params": ...
