from typing import Any, ClassVar, overload

class InferenceOutput:
    def getDataOutputs(self) -> dict: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setDataOutputs(self, arg0: dict) -> "Builder": ...
        def addDataOutput(self, arg0: int, arg1: Any) -> "Builder": ...
        def build(self) -> "InferenceOutput": ...
