from typing import Any, ClassVar, overload
from android.os.PersistableBundle import PersistableBundle

class RenderOutput:
    def getContent(self) -> str: ...
    def getTemplateId(self) -> str: ...
    def getTemplateParams(self) -> PersistableBundle: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setContent(self, arg0: str) -> "Builder": ...
        def setTemplateId(self, arg0: str) -> "Builder": ...
        def setTemplateParams(self, arg0: PersistableBundle) -> "Builder": ...
        def build(self) -> "RenderOutput": ...
