from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.TrainingExampleRecord import TrainingExampleRecord

class TrainingExamplesOutput:
    def getTrainingExampleRecords(self) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setTrainingExampleRecords(self, arg0: list) -> "Builder": ...
        def addTrainingExampleRecord(self, arg0: TrainingExampleRecord) -> "Builder": ...
        def build(self) -> "TrainingExamplesOutput": ...
