from typing import Any, ClassVar, overload

class TrainingExamplesInput:
    def getPopulationName(self) -> str: ...
    def getTaskName(self) -> str: ...
    def getResumptionToken(self) -> list[int]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
