from typing import Any, ClassVar, overload
from java.time.Duration import Duration

class TrainingInterval:
    SCHEDULING_MODE_ONE_TIME: ClassVar[int]
    SCHEDULING_MODE_RECURRENT: ClassVar[int]
    def getSchedulingMode(self) -> int: ...
    def getMinimumInterval(self) -> Duration: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setSchedulingMode(self, arg0: int) -> "Builder": ...
        def setMinimumInterval(self, arg0: Duration) -> "Builder": ...
        def build(self) -> "TrainingInterval": ...
