from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class WebTriggerInput:
    def getDestinationUrl(self) -> Uri: ...
    def getAppPackageName(self) -> str: ...
    def getData(self) -> list[int]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
