from typing import Any, ClassVar, overload

class BidiClassifier:
    def __init__(self, arg0: Any) -> None: ...
    def setContext(self, arg0: Any) -> None: ...
    def getContext(self) -> Any: ...
    def classify(self, arg0: int) -> int: ...
