from typing import Any, ClassVar, overload

class CollationKey:
    def __init__(self, arg0: str, arg1: list[int]) -> None: ...
    def getSourceString(self) -> str: ...
    def toByteArray(self) -> list[int]: ...
    def compareTo(self, arg0: "CollationKey") -> int: ...
    @overload
    def equals(self, arg0: Any) -> bool: ...
    @overload
    def equals(self, arg0: "CollationKey") -> bool: ...
    def hashCode(self) -> int: ...
    def getBound(self, arg0: int, arg1: int) -> "CollationKey": ...
    def merge(self, arg0: "CollationKey") -> "CollationKey": ...

    class BoundMode:
        LOWER: ClassVar[int]
        UPPER: ClassVar[int]
        UPPER_LONG: ClassVar[int]
