from typing import Any, ClassVar, overload
from android.icu.text.UCharacterIterator import UCharacterIterator
from java.text.CharacterIterator import CharacterIterator

class CollationElementIterator:
    IGNORABLE: ClassVar[int]
    NULLORDER: ClassVar[int]
    @staticmethod
    def primaryOrder(arg0: int) -> int: ...
    @staticmethod
    def secondaryOrder(arg0: int) -> int: ...
    @staticmethod
    def tertiaryOrder(arg0: int) -> int: ...
    def getOffset(self) -> int: ...
    def next(self) -> int: ...
    def previous(self) -> int: ...
    def reset(self) -> None: ...
    def setOffset(self, arg0: int) -> None: ...
    @overload
    def setText(self, arg0: str) -> None: ...
    @overload
    def setText(self, arg0: UCharacterIterator) -> None: ...
    @overload
    def setText(self, arg0: CharacterIterator) -> None: ...
    def getMaxExpansion(self, arg0: int) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
