from typing import Any, ClassVar, overload
from android.icu.math.BigDecimal import BigDecimal
from android.icu.math.MathContext import MathContext
from android.icu.text.CurrencyPluralInfo import CurrencyPluralInfo
from android.icu.text.DecimalFormatSymbols import DecimalFormatSymbols
from android.icu.util.Currency import Currency
from android.icu.util.CurrencyAmount import CurrencyAmount
from java.lang.StringBuffer import StringBuffer
from java.math.BigDecimal import BigDecimal
from java.math.BigInteger import BigInteger
from java.math.MathContext import MathContext
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class CurrencyUsage:
    """Forward declaration for ``android.icu.util.Currency.CurrencyUsage``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.icu.util.Currency.CurrencyUsage')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/icu/util/Currency/CurrencyUsage
    """
    ...

class DecimalFormat:
    MINIMUM_GROUPING_DIGITS_AUTO: ClassVar[int]
    MINIMUM_GROUPING_DIGITS_MIN2: ClassVar[int]
    PAD_AFTER_PREFIX: ClassVar[int]
    PAD_AFTER_SUFFIX: ClassVar[int]
    PAD_BEFORE_PREFIX: ClassVar[int]
    PAD_BEFORE_SUFFIX: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: DecimalFormatSymbols) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: DecimalFormatSymbols, arg2: CurrencyPluralInfo, arg3: int) -> None: ...
    def applyPattern(self, arg0: str) -> None: ...
    def applyLocalizedPattern(self, arg0: str) -> None: ...
    def clone(self) -> Any: ...
    @overload
    def format(self, arg0: float, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: int, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: BigInteger, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: BigDecimal, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: BigDecimal, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: CurrencyAmount, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    def formatToCharacterIterator(self, arg0: Any) -> AttributedCharacterIterator: ...
    def parse(self, arg0: str, arg1: ParsePosition) -> float: ...
    def parseCurrency(self, arg0: str, arg1: ParsePosition) -> CurrencyAmount: ...
    def getDecimalFormatSymbols(self) -> DecimalFormatSymbols: ...
    def setDecimalFormatSymbols(self, arg0: DecimalFormatSymbols) -> None: ...
    def getPositivePrefix(self) -> str: ...
    def setPositivePrefix(self, arg0: str) -> None: ...
    def getNegativePrefix(self) -> str: ...
    def setNegativePrefix(self, arg0: str) -> None: ...
    def getPositiveSuffix(self) -> str: ...
    def setPositiveSuffix(self, arg0: str) -> None: ...
    def getNegativeSuffix(self) -> str: ...
    def setNegativeSuffix(self, arg0: str) -> None: ...
    def isSignAlwaysShown(self) -> bool: ...
    def setSignAlwaysShown(self, arg0: bool) -> None: ...
    def getMultiplier(self) -> int: ...
    def setMultiplier(self, arg0: int) -> None: ...
    def getRoundingIncrement(self) -> BigDecimal: ...
    @overload
    def setRoundingIncrement(self, arg0: BigDecimal) -> None: ...
    @overload
    def setRoundingIncrement(self, arg0: BigDecimal) -> None: ...
    @overload
    def setRoundingIncrement(self, arg0: float) -> None: ...
    def getRoundingMode(self) -> int: ...
    def setRoundingMode(self, arg0: int) -> None: ...
    def getMathContext(self) -> MathContext: ...
    def setMathContext(self, arg0: MathContext) -> None: ...
    def getMathContextICU(self) -> MathContext: ...
    def setMathContextICU(self, arg0: MathContext) -> None: ...
    def getMinimumIntegerDigits(self) -> int: ...
    def setMinimumIntegerDigits(self, arg0: int) -> None: ...
    def getMaximumIntegerDigits(self) -> int: ...
    def setMaximumIntegerDigits(self, arg0: int) -> None: ...
    def getMinimumFractionDigits(self) -> int: ...
    def setMinimumFractionDigits(self, arg0: int) -> None: ...
    def getMaximumFractionDigits(self) -> int: ...
    def setMaximumFractionDigits(self, arg0: int) -> None: ...
    def areSignificantDigitsUsed(self) -> bool: ...
    def setSignificantDigitsUsed(self, arg0: bool) -> None: ...
    def getMinimumSignificantDigits(self) -> int: ...
    def setMinimumSignificantDigits(self, arg0: int) -> None: ...
    def getMaximumSignificantDigits(self) -> int: ...
    def setMaximumSignificantDigits(self, arg0: int) -> None: ...
    def getFormatWidth(self) -> int: ...
    def setFormatWidth(self, arg0: int) -> None: ...
    def getPadCharacter(self) -> str: ...
    def setPadCharacter(self, arg0: str) -> None: ...
    def getPadPosition(self) -> int: ...
    def setPadPosition(self, arg0: int) -> None: ...
    def isScientificNotation(self) -> bool: ...
    def setScientificNotation(self, arg0: bool) -> None: ...
    def getMinimumExponentDigits(self) -> int: ...
    def setMinimumExponentDigits(self, arg0: int) -> None: ...
    def isExponentSignAlwaysShown(self) -> bool: ...
    def setExponentSignAlwaysShown(self, arg0: bool) -> None: ...
    def isGroupingUsed(self) -> bool: ...
    def setGroupingUsed(self, arg0: bool) -> None: ...
    def getGroupingSize(self) -> int: ...
    def setGroupingSize(self, arg0: int) -> None: ...
    def getSecondaryGroupingSize(self) -> int: ...
    def setSecondaryGroupingSize(self, arg0: int) -> None: ...
    def getMinimumGroupingDigits(self) -> int: ...
    def setMinimumGroupingDigits(self, arg0: int) -> None: ...
    def isDecimalSeparatorAlwaysShown(self) -> bool: ...
    def setDecimalSeparatorAlwaysShown(self, arg0: bool) -> None: ...
    def getCurrency(self) -> Currency: ...
    def setCurrency(self, arg0: Currency) -> None: ...
    def getCurrencyUsage(self) -> CurrencyUsage: ...
    def setCurrencyUsage(self, arg0: CurrencyUsage) -> None: ...
    def getCurrencyPluralInfo(self) -> CurrencyPluralInfo: ...
    def setCurrencyPluralInfo(self, arg0: CurrencyPluralInfo) -> None: ...
    def isParseBigDecimal(self) -> bool: ...
    def setParseBigDecimal(self, arg0: bool) -> None: ...
    def getParseMaxDigits(self) -> int: ...
    def setParseMaxDigits(self, arg0: int) -> None: ...
    def isParseStrict(self) -> bool: ...
    def setParseStrict(self, arg0: bool) -> None: ...
    def isParseIntegerOnly(self) -> bool: ...
    def setParseIntegerOnly(self, arg0: bool) -> None: ...
    def isDecimalPatternMatchRequired(self) -> bool: ...
    def setDecimalPatternMatchRequired(self, arg0: bool) -> None: ...
    def isParseNoExponent(self) -> bool: ...
    def setParseNoExponent(self, arg0: bool) -> None: ...
    def isParseCaseSensitive(self) -> bool: ...
    def setParseCaseSensitive(self, arg0: bool) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def toPattern(self) -> str: ...
    def toLocalizedPattern(self) -> str: ...
