from typing import Any, ClassVar, overload
from android.icu.text.ConstrainedFieldPosition import ConstrainedFieldPosition
from android.icu.util.ULocale import ULocale
from java.lang.Appendable import Appendable
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.util.Locale import Locale

class ListFormatter:
    @overload
    @staticmethod
    def getInstance(arg0: ULocale, arg1: "Type", arg2: "Width") -> "ListFormatter": ...
    @overload
    @staticmethod
    def getInstance(arg0: Locale, arg1: "Type", arg2: "Width") -> "ListFormatter": ...
    @overload
    @staticmethod
    def getInstance(arg0: ULocale) -> "ListFormatter": ...
    @overload
    @staticmethod
    def getInstance(arg0: Locale) -> "ListFormatter": ...
    @overload
    @staticmethod
    def getInstance() -> "ListFormatter": ...
    @overload
    def format(self, *arg0: Any) -> str: ...
    @overload
    def format(self, arg0: list) -> str: ...
    @overload
    def formatToValue(self, *arg0: Any) -> "FormattedList": ...
    @overload
    def formatToValue(self, arg0: list) -> "FormattedList": ...
    def getPatternForNumItems(self, arg0: int) -> str: ...

    class FormattedList:
        def toString(self) -> str: ...
        def length(self) -> int: ...
        def charAt(self, arg0: int) -> str: ...
        def subSequence(self, arg0: int, arg1: int) -> str: ...
        def appendTo(self, arg0: Appendable) -> Appendable: ...
        def nextPosition(self, arg0: ConstrainedFieldPosition) -> bool: ...
        def toCharacterIterator(self) -> AttributedCharacterIterator: ...

    class Type:
        AND: ClassVar["Type"]
        OR: ClassVar["Type"]
        UNITS: ClassVar["Type"]
        @staticmethod
        def values() -> list["Type"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Type": ...

    class Width:
        WIDE: ClassVar["Width"]
        SHORT: ClassVar["Width"]
        NARROW: ClassVar["Width"]
        @staticmethod
        def values() -> list["Width"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Width": ...
