from typing import Any, ClassVar, overload

class MessagePattern:
    ARG_NAME_NOT_NUMBER: ClassVar[int]
    ARG_NAME_NOT_VALID: ClassVar[int]
    NO_NUMERIC_VALUE: ClassVar[float]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "ApostropheMode") -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    def parse(self, arg0: str) -> "MessagePattern": ...
    def parseChoiceStyle(self, arg0: str) -> "MessagePattern": ...
    def parsePluralStyle(self, arg0: str) -> "MessagePattern": ...
    def parseSelectStyle(self, arg0: str) -> "MessagePattern": ...
    def clear(self) -> None: ...
    def clearPatternAndSetApostropheMode(self, arg0: "ApostropheMode") -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getApostropheMode(self) -> "ApostropheMode": ...
    def getPatternString(self) -> str: ...
    def hasNamedArguments(self) -> bool: ...
    def hasNumberedArguments(self) -> bool: ...
    def toString(self) -> str: ...
    @staticmethod
    def validateArgumentName(arg0: str) -> int: ...
    def autoQuoteApostropheDeep(self) -> str: ...
    def countParts(self) -> int: ...
    def getPart(self, arg0: int) -> "Part": ...
    def getPartType(self, arg0: int) -> "Type": ...
    def getPatternIndex(self, arg0: int) -> int: ...
    def getSubstring(self, arg0: "Part") -> str: ...
    def partSubstringMatches(self, arg0: "Part", arg1: str) -> bool: ...
    def getNumericValue(self, arg0: "Part") -> float: ...
    def getPluralOffset(self, arg0: int) -> float: ...
    def getLimitPartIndex(self, arg0: int) -> int: ...
    def clone(self) -> Any: ...
    def cloneAsThawed(self) -> "MessagePattern": ...
    def freeze(self) -> "MessagePattern": ...
    def isFrozen(self) -> bool: ...

    class ApostropheMode:
        DOUBLE_OPTIONAL: ClassVar["ApostropheMode"]
        DOUBLE_REQUIRED: ClassVar["ApostropheMode"]
        @staticmethod
        def values() -> list["ApostropheMode"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "ApostropheMode": ...

    class ArgType:
        NONE: ClassVar["ArgType"]
        SIMPLE: ClassVar["ArgType"]
        CHOICE: ClassVar["ArgType"]
        PLURAL: ClassVar["ArgType"]
        SELECT: ClassVar["ArgType"]
        SELECTORDINAL: ClassVar["ArgType"]
        @staticmethod
        def values() -> list["ArgType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "ArgType": ...
        def hasPluralStyle(self) -> bool: ...

    class Part:
        def getType(self) -> "Type": ...
        def getIndex(self) -> int: ...
        def getLength(self) -> int: ...
        def getLimit(self) -> int: ...
        def getValue(self) -> int: ...
        def getArgType(self) -> "ArgType": ...
        def toString(self) -> str: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

        class Type:
            MSG_START: ClassVar["Type"]
            MSG_LIMIT: ClassVar["Type"]
            SKIP_SYNTAX: ClassVar["Type"]
            INSERT_CHAR: ClassVar["Type"]
            REPLACE_NUMBER: ClassVar["Type"]
            ARG_START: ClassVar["Type"]
            ARG_LIMIT: ClassVar["Type"]
            ARG_NUMBER: ClassVar["Type"]
            ARG_NAME: ClassVar["Type"]
            ARG_TYPE: ClassVar["Type"]
            ARG_STYLE: ClassVar["Type"]
            ARG_SELECTOR: ClassVar["Type"]
            ARG_INT: ClassVar["Type"]
            ARG_DOUBLE: ClassVar["Type"]
            @staticmethod
            def values() -> list["Type"]: ...
            @staticmethod
            def valueOf(arg0: str) -> "Type": ...
            def hasNumericValue(self) -> bool: ...
