from typing import Any, ClassVar, overload
from android.icu.text.DateFormatSymbols import DateFormatSymbols
from android.icu.text.DisplayContext import DisplayContext
from android.icu.text.NumberFormat import NumberFormat
from android.icu.text.TimeZoneFormat import TimeZoneFormat
from android.icu.util.Calendar import Calendar
from android.icu.util.ULocale import ULocale
from java.lang.StringBuffer import StringBuffer
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition
from java.util.Date import Date
from java.util.Locale import Locale

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Field:
    """Forward declaration for ``android.icu.text.DateFormat.Field``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.icu.text.DateFormat.Field')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/icu/text/DateFormat/Field
    """
    ...

class SimpleDateFormat:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Locale) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: ULocale) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: ULocale) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: DateFormatSymbols) -> None: ...
    def set2DigitYearStart(self, arg0: Date) -> None: ...
    def get2DigitYearStart(self) -> Date: ...
    def setContext(self, arg0: DisplayContext) -> None: ...
    def format(self, arg0: Calendar, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    def patternCharToDateFormatField(self, arg0: str) -> Field: ...
    def subFormat(self, arg0: str, arg1: int, arg2: int, arg3: FieldPosition, arg4: DateFormatSymbols, arg5: Calendar) -> str: ...
    @overload
    def setNumberFormat(self, arg0: NumberFormat) -> None: ...
    @overload
    def setNumberFormat(self, arg0: str, arg1: NumberFormat) -> None: ...
    def zeroPaddingNumber(self, arg0: int, arg1: int, arg2: int) -> str: ...
    def parse(self, arg0: str, arg1: Calendar, arg2: ParsePosition) -> None: ...
    def matchString(self, arg0: str, arg1: int, arg2: int, arg3: list[str], arg4: Calendar) -> int: ...
    def matchQuarterString(self, arg0: str, arg1: int, arg2: int, arg3: list[str], arg4: Calendar) -> int: ...
    def subParse(self, arg0: str, arg1: int, arg2: str, arg3: int, arg4: bool, arg5: bool, arg6: list[bool], arg7: Calendar) -> int: ...
    def toPattern(self) -> str: ...
    def toLocalizedPattern(self) -> str: ...
    def applyPattern(self, arg0: str) -> None: ...
    def applyLocalizedPattern(self, arg0: str) -> None: ...
    def getDateFormatSymbols(self) -> DateFormatSymbols: ...
    def setDateFormatSymbols(self, arg0: DateFormatSymbols) -> None: ...
    def getSymbols(self) -> DateFormatSymbols: ...
    def getTimeZoneFormat(self) -> TimeZoneFormat: ...
    def setTimeZoneFormat(self, arg0: TimeZoneFormat) -> None: ...
    def clone(self) -> Any: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def formatToCharacterIterator(self, arg0: Any) -> AttributedCharacterIterator: ...
    def getNumberFormat(self, arg0: str) -> NumberFormat: ...
