from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["TimeZoneFormat"]

class TimeZoneFormat(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/icu/text/TimeZoneFormat"
    __javaconstructor__ = [("(Landroid/icu/util/ULocale;)V", False)]
    getInstance = JavaMultipleMethod([("(Landroid/icu/util/ULocale;)Landroid/icu/text/TimeZoneFormat;", True, False), ("(Ljava/util/Locale;)Landroid/icu/text/TimeZoneFormat;", True, False)])
    getTimeZoneNames = JavaMethod("()Landroid/icu/text/TimeZoneNames;")
    setTimeZoneNames = JavaMethod("(Landroid/icu/text/TimeZoneNames;)Landroid/icu/text/TimeZoneFormat;")
    getGMTPattern = JavaMethod("()Ljava/lang/String;")
    setGMTPattern = JavaMethod("(Ljava/lang/String;)Landroid/icu/text/TimeZoneFormat;")
    getGMTOffsetPattern = JavaMethod("(Landroid/icu/text/TimeZoneFormat$GMTOffsetPatternType;)Ljava/lang/String;")
    setGMTOffsetPattern = JavaMethod("(Landroid/icu/text/TimeZoneFormat$GMTOffsetPatternType;Ljava/lang/String;)Landroid/icu/text/TimeZoneFormat;")
    getGMTOffsetDigits = JavaMethod("()Ljava/lang/String;")
    setGMTOffsetDigits = JavaMethod("(Ljava/lang/String;)Landroid/icu/text/TimeZoneFormat;")
    getGMTZeroFormat = JavaMethod("()Ljava/lang/String;")
    setGMTZeroFormat = JavaMethod("(Ljava/lang/String;)Landroid/icu/text/TimeZoneFormat;")
    setDefaultParseOptions = JavaMethod("(Ljava/util/EnumSet;)Landroid/icu/text/TimeZoneFormat;")
    getDefaultParseOptions = JavaMethod("()Ljava/util/EnumSet;")
    formatOffsetISO8601Basic = JavaMethod("(IZZZ)Ljava/lang/String;")
    formatOffsetISO8601Extended = JavaMethod("(IZZZ)Ljava/lang/String;")
    formatOffsetLocalizedGMT = JavaMethod("(I)Ljava/lang/String;")
    formatOffsetShortLocalizedGMT = JavaMethod("(I)Ljava/lang/String;")
    format = JavaMultipleMethod([("(Landroid/icu/text/TimeZoneFormat$Style;Landroid/icu/util/TimeZone;J)Ljava/lang/String;", False, False), ("(Landroid/icu/text/TimeZoneFormat$Style;Landroid/icu/util/TimeZone;JLandroid/icu/util/Output;)Ljava/lang/String;", False, False), ("(Ljava/lang/Object;Ljava/lang/StringBuffer;Ljava/text/FieldPosition;)Ljava/lang/StringBuffer;", False, False)])
    parseOffsetISO8601 = JavaMethod("(Ljava/lang/String;Ljava/text/ParsePosition;)I")
    parseOffsetLocalizedGMT = JavaMethod("(Ljava/lang/String;Ljava/text/ParsePosition;)I")
    parseOffsetShortLocalizedGMT = JavaMethod("(Ljava/lang/String;Ljava/text/ParsePosition;)I")
    parse = JavaMultipleMethod([("(Landroid/icu/text/TimeZoneFormat$Style;Ljava/lang/String;Ljava/text/ParsePosition;Ljava/util/EnumSet;Landroid/icu/util/Output;)Landroid/icu/util/TimeZone;", False, False), ("(Landroid/icu/text/TimeZoneFormat$Style;Ljava/lang/String;Ljava/text/ParsePosition;Landroid/icu/util/Output;)Landroid/icu/util/TimeZone;", False, False), ("(Ljava/lang/String;Ljava/text/ParsePosition;)Landroid/icu/util/TimeZone;", False, False), ("(Ljava/lang/String;)Landroid/icu/util/TimeZone;", False, False)])
    formatToCharacterIterator = JavaMethod("(Ljava/lang/Object;)Ljava/text/AttributedCharacterIterator;")
    parseObject = JavaMethod("(Ljava/lang/String;Ljava/text/ParsePosition;)Ljava/lang/Object;")
    isFrozen = JavaMethod("()Z")
    freeze = JavaMethod("()Landroid/icu/text/TimeZoneFormat;")
    cloneAsThawed = JavaMethod("()Landroid/icu/text/TimeZoneFormat;")

    class GMTOffsetPatternType(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/icu/text/TimeZoneFormat/GMTOffsetPatternType"
        values = JavaStaticMethod("()[Landroid/icu/text/TimeZoneFormat$GMTOffsetPatternType;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/icu/text/TimeZoneFormat$GMTOffsetPatternType;")
        POSITIVE_HM = JavaStaticField("Landroid/icu/text/TimeZoneFormat/GMTOffsetPatternType;")
        POSITIVE_HMS = JavaStaticField("Landroid/icu/text/TimeZoneFormat/GMTOffsetPatternType;")
        NEGATIVE_HM = JavaStaticField("Landroid/icu/text/TimeZoneFormat/GMTOffsetPatternType;")
        NEGATIVE_HMS = JavaStaticField("Landroid/icu/text/TimeZoneFormat/GMTOffsetPatternType;")
        POSITIVE_H = JavaStaticField("Landroid/icu/text/TimeZoneFormat/GMTOffsetPatternType;")
        NEGATIVE_H = JavaStaticField("Landroid/icu/text/TimeZoneFormat/GMTOffsetPatternType;")

    class ParseOption(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/icu/text/TimeZoneFormat/ParseOption"
        values = JavaStaticMethod("()[Landroid/icu/text/TimeZoneFormat$ParseOption;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/icu/text/TimeZoneFormat$ParseOption;")
        ALL_STYLES = JavaStaticField("Landroid/icu/text/TimeZoneFormat/ParseOption;")
        TZ_DATABASE_ABBREVIATIONS = JavaStaticField("Landroid/icu/text/TimeZoneFormat/ParseOption;")

    class Style(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/icu/text/TimeZoneFormat/Style"
        values = JavaStaticMethod("()[Landroid/icu/text/TimeZoneFormat$Style;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/icu/text/TimeZoneFormat$Style;")
        GENERIC_LOCATION = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        GENERIC_LONG = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        GENERIC_SHORT = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        SPECIFIC_LONG = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        SPECIFIC_SHORT = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        LOCALIZED_GMT = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        LOCALIZED_GMT_SHORT = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_BASIC_SHORT = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_BASIC_LOCAL_SHORT = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_BASIC_FIXED = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_BASIC_LOCAL_FIXED = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_BASIC_FULL = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_BASIC_LOCAL_FULL = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_EXTENDED_FIXED = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_EXTENDED_LOCAL_FIXED = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_EXTENDED_FULL = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ISO_EXTENDED_LOCAL_FULL = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ZONE_ID = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        ZONE_ID_SHORT = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")
        EXEMPLAR_LOCATION = JavaStaticField("Landroid/icu/text/TimeZoneFormat/Style;")

    class TimeType(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/icu/text/TimeZoneFormat/TimeType"
        values = JavaStaticMethod("()[Landroid/icu/text/TimeZoneFormat$TimeType;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/icu/text/TimeZoneFormat$TimeType;")
        UNKNOWN = JavaStaticField("Landroid/icu/text/TimeZoneFormat/TimeType;")
        STANDARD = JavaStaticField("Landroid/icu/text/TimeZoneFormat/TimeType;")
        DAYLIGHT = JavaStaticField("Landroid/icu/text/TimeZoneFormat/TimeType;")