from typing import Any, ClassVar, overload
from android.icu.text.Replaceable import Replaceable
from android.icu.text.UnicodeFilter import UnicodeFilter
from android.icu.text.UnicodeSet import UnicodeSet
from android.icu.util.ULocale import ULocale
from java.util.Enumeration import Enumeration
from java.util.Locale import Locale

class Transliterator:
    FORWARD: ClassVar[int]
    REVERSE: ClassVar[int]
    @overload
    def transliterate(self, arg0: Replaceable, arg1: int, arg2: int) -> int: ...
    @overload
    def transliterate(self, arg0: Replaceable) -> None: ...
    @overload
    def transliterate(self, arg0: str) -> str: ...
    @overload
    def transliterate(self, arg0: Replaceable, arg1: "Position", arg2: str) -> None: ...
    @overload
    def transliterate(self, arg0: Replaceable, arg1: "Position", arg2: int) -> None: ...
    @overload
    def transliterate(self, arg0: Replaceable, arg1: "Position") -> None: ...
    def finishTransliteration(self, arg0: Replaceable, arg1: "Position") -> None: ...
    def filteredTransliterate(self, arg0: Replaceable, arg1: "Position", arg2: bool) -> None: ...
    def getMaximumContextLength(self) -> int: ...
    def getID(self) -> str: ...
    @overload
    @staticmethod
    def getDisplayName(arg0: str) -> str: ...
    @overload
    @staticmethod
    def getDisplayName(arg0: str, arg1: Locale) -> str: ...
    @overload
    @staticmethod
    def getDisplayName(arg0: str, arg1: ULocale) -> str: ...
    def getFilter(self) -> UnicodeFilter: ...
    def setFilter(self, arg0: UnicodeFilter) -> None: ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "Transliterator": ...
    @overload
    @staticmethod
    def getInstance(arg0: str, arg1: int) -> "Transliterator": ...
    @staticmethod
    def createFromRules(arg0: str, arg1: str, arg2: int) -> "Transliterator": ...
    def toRules(self, arg0: bool) -> str: ...
    def getElements(self) -> list["Transliterator"]: ...
    def getSourceSet(self) -> UnicodeSet: ...
    def getTargetSet(self) -> UnicodeSet: ...
    def getInverse(self) -> "Transliterator": ...
    @staticmethod
    def getAvailableIDs() -> Enumeration: ...
    @staticmethod
    def getAvailableSources() -> Enumeration: ...
    @staticmethod
    def getAvailableTargets(arg0: str) -> Enumeration: ...
    @staticmethod
    def getAvailableVariants(arg0: str, arg1: str) -> Enumeration: ...

    class Position:
        contextLimit: int
        contextStart: int
        limit: int
        start: int
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
        @overload
        def __init__(self, arg0: "Position") -> None: ...
        def set(self, arg0: "Position") -> None: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...
        def validate(self, arg0: int) -> None: ...
