from typing import Any, ClassVar, overload
from android.icu.text.Replaceable import Replaceable
from java.lang.StringBuffer import StringBuffer
from java.text.CharacterIterator import CharacterIterator

class UCharacterIterator:
    DONE: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def getInstance(arg0: Replaceable) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(arg0: str) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(arg0: list[str]) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(arg0: list[str], arg1: int, arg2: int) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(arg0: StringBuffer) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(arg0: CharacterIterator) -> "UCharacterIterator": ...
    def getCharacterIterator(self) -> CharacterIterator: ...
    def current(self) -> int: ...
    def currentCodePoint(self) -> int: ...
    def getLength(self) -> int: ...
    def getIndex(self) -> int: ...
    def next(self) -> int: ...
    def nextCodePoint(self) -> int: ...
    def previous(self) -> int: ...
    def previousCodePoint(self) -> int: ...
    def setIndex(self, arg0: int) -> None: ...
    def setToLimit(self) -> None: ...
    def setToStart(self) -> None: ...
    @overload
    def getText(self, arg0: list[str], arg1: int) -> int: ...
    @overload
    def getText(self, arg0: list[str]) -> int: ...
    @overload
    def getText(self) -> str: ...
    def moveIndex(self, arg0: int) -> int: ...
    def moveCodePointIndex(self, arg0: int) -> int: ...
    def clone(self) -> Any: ...
