from typing import Any, ClassVar, overload
from android.icu.text.UnicodeSet import UnicodeSet

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class SpanCondition:
    """Forward declaration for ``android.icu.text.UnicodeSet.SpanCondition``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.icu.text.UnicodeSet.SpanCondition')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/icu/text/UnicodeSet/SpanCondition
    """
    ...

class UnicodeSetSpanner:
    def __init__(self, arg0: UnicodeSet) -> None: ...
    def getUnicodeSet(self) -> UnicodeSet: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def countIn(self, arg0: str) -> int: ...
    @overload
    def countIn(self, arg0: str, arg1: "CountMethod") -> int: ...
    @overload
    def countIn(self, arg0: str, arg1: "CountMethod", arg2: SpanCondition) -> int: ...
    @overload
    def deleteFrom(self, arg0: str) -> str: ...
    @overload
    def deleteFrom(self, arg0: str, arg1: SpanCondition) -> str: ...
    @overload
    def replaceFrom(self, arg0: str, arg1: str) -> str: ...
    @overload
    def replaceFrom(self, arg0: str, arg1: str, arg2: "CountMethod") -> str: ...
    @overload
    def replaceFrom(self, arg0: str, arg1: str, arg2: "CountMethod", arg3: SpanCondition) -> str: ...
    @overload
    def trim(self, arg0: str) -> str: ...
    @overload
    def trim(self, arg0: str, arg1: "TrimOption") -> str: ...
    @overload
    def trim(self, arg0: str, arg1: "TrimOption", arg2: SpanCondition) -> str: ...

    class CountMethod:
        WHOLE_SPAN: ClassVar["CountMethod"]
        MIN_ELEMENTS: ClassVar["CountMethod"]
        @staticmethod
        def values() -> list["CountMethod"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "CountMethod": ...

    class TrimOption:
        LEADING: ClassVar["TrimOption"]
        BOTH: ClassVar["TrimOption"]
        TRAILING: ClassVar["TrimOption"]
        @staticmethod
        def values() -> list["TrimOption"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "TrimOption": ...
