from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class WebView: ...  # android.webkit.WebView
class WebViewClient: ...  # android.webkit.WebViewClient

class H5AdsWebViewClient:
    def __init__(self, arg0: Context, arg1: WebView) -> None: ...
    def clearAdObjects(self) -> None: ...
    def setDelegateWebViewClient(self, arg0: WebViewClient) -> None: ...
    def getDelegateWebViewClient(self) -> WebViewClient: ...
    def getDelegate(self) -> WebViewClient: ...
