from typing import Any, ClassVar, overload
from android.gms.ads.h5.OnH5AdsEventListener import OnH5AdsEventListener

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context

class H5AdsRequestHandler:
    def __init__(self, arg0: Context, arg1: OnH5AdsEventListener) -> None: ...
    def clearAdObjects(self) -> None: ...
    def shouldInterceptRequest(self, arg0: str) -> bool: ...
    def handleH5AdsRequest(self, arg0: str) -> bool: ...
