from typing import Any, ClassVar, overload

class Attributes2:
    @overload
    def isDeclared(self, arg0: int) -> bool: ...
    @overload
    def isDeclared(self, arg0: str) -> bool: ...
    @overload
    def isDeclared(self, arg0: str, arg1: str) -> bool: ...
    @overload
    def isSpecified(self, arg0: int) -> bool: ...
    @overload
    def isSpecified(self, arg0: str, arg1: str) -> bool: ...
    @overload
    def isSpecified(self, arg0: str) -> bool: ...
