from typing import Any, ClassVar, overload
from org.xml.sax.Locator import Locator

class Locator2Impl:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Locator) -> None: ...
    def getXMLVersion(self) -> str: ...
    def getEncoding(self) -> str: ...
    def setXMLVersion(self, arg0: str) -> None: ...
    def setEncoding(self, arg0: str) -> None: ...
