from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.spec.ECParameterSpec import ECParameterSpec

class ECPrivateKeySpec:
    def __init__(self, arg0: BigInteger, arg1: ECParameterSpec) -> None: ...
    def getS(self) -> BigInteger: ...
    def getParams(self) -> ECParameterSpec: ...
