from typing import Any, ClassVar, overload
from java.util.Optional import Optional

class EdDSAParameterSpec:
    @overload
    def __init__(self, arg0: bool) -> None: ...
    @overload
    def __init__(self, arg0: bool, arg1: list[int]) -> None: ...
    def isPrehash(self) -> bool: ...
    def getContext(self) -> Optional: ...
