from typing import Any, ClassVar, overload
from java.security.spec.EdECPoint import EdECPoint
from java.security.spec.NamedParameterSpec import NamedParameterSpec

class EdECPublicKeySpec:
    def __init__(self, arg0: NamedParameterSpec, arg1: EdECPoint) -> None: ...
    def getParams(self) -> NamedParameterSpec: ...
    def getPoint(self) -> EdECPoint: ...
