from typing import Any, ClassVar, overload
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class PSSParameterSpec:
    DEFAULT: ClassVar["PSSParameterSpec"]
    TRAILER_FIELD_BC: ClassVar[int]
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: AlgorithmParameterSpec, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    def getDigestAlgorithm(self) -> str: ...
    def getMGFAlgorithm(self) -> str: ...
    def getMGFParameters(self) -> AlgorithmParameterSpec: ...
    def getSaltLength(self) -> int: ...
    def getTrailerField(self) -> int: ...
    def toString(self) -> str: ...
