from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger

class RSAOtherPrimeInfo:
    def __init__(self, arg0: BigInteger, arg1: BigInteger, arg2: BigInteger) -> None: ...
    def getPrime(self) -> BigInteger: ...
    def getExponent(self) -> BigInteger: ...
    def getCrtCoefficient(self) -> BigInteger: ...
