from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class RSAPrivateKeySpec:
    @overload
    def __init__(self, arg0: BigInteger, arg1: BigInteger) -> None: ...
    @overload
    def __init__(self, arg0: BigInteger, arg1: BigInteger, arg2: AlgorithmParameterSpec) -> None: ...
    def getModulus(self) -> BigInteger: ...
    def getPrivateExponent(self) -> BigInteger: ...
    def getParams(self) -> AlgorithmParameterSpec: ...
