from typing import Any, ClassVar, overload

class X509EncodedKeySpec:
    @overload
    def __init__(self, arg0: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: list[int], arg1: str) -> None: ...
    def getEncoded(self) -> list[int]: ...
    def getFormat(self) -> str: ...
