from typing import Any, ClassVar, overload
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class XECPrivateKeySpec:
    def __init__(self, arg0: AlgorithmParameterSpec, arg1: list[int]) -> None: ...
    def getParams(self) -> AlgorithmParameterSpec: ...
    def getScalar(self) -> list[int]: ...
