from typing import Any, ClassVar, overload

class InputConfiguration:
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: list, arg1: int) -> None: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getFormat(self) -> int: ...
    def isMultiResolution(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
