from typing import Any, ClassVar, overload

class LensIntrinsicsSample:
    def __init__(self, arg0: int, arg1: list[float]) -> None: ...
    def getTimestampNanos(self) -> int: ...
    def getLensIntrinsics(self) -> list[float]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
