from typing import Any, ClassVar, overload

class MultiResolutionStreamConfigurationMap:
    def getOutputFormats(self) -> list[int]: ...
    def getInputFormats(self) -> list[int]: ...
    def getOutputInfo(self, arg0: int) -> list: ...
    def getInputInfo(self, arg0: int) -> list: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
