from typing import Any, ClassVar, overload

class OisSample:
    def __init__(self, arg0: int, arg1: float, arg2: float) -> None: ...
    def getTimestamp(self) -> int: ...
    def getXshift(self) -> float: ...
    def getYshift(self) -> float: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
