from typing import Any, ClassVar, overload
from android.graphics.ColorSpace import ColorSpace
from android.hardware.camera2.CaptureRequest import CaptureRequest
from android.hardware.camera2.params.InputConfiguration import InputConfiguration
from android.os.Parcel import Parcel
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...
class StateCallback:
    """Forward declaration for ``android.hardware.camera2.CameraCaptureSession.StateCallback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.hardware.camera2.CameraCaptureSession.StateCallback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/hardware/camera2/CameraCaptureSession/StateCallback
    """
    ...
class Named:
    """Forward declaration for ``android.graphics.ColorSpace.Named``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.ColorSpace.Named')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/ColorSpace/Named
    """
    ...

class SessionConfiguration:
    CREATOR: ClassVar[Creator]
    SESSION_HIGH_SPEED: ClassVar[int]
    SESSION_REGULAR: ClassVar[int]
    @overload
    def __init__(self, arg0: int, arg1: list, arg2: Executor, arg3: StateCallback) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: list) -> None: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getSessionType(self) -> int: ...
    def getOutputConfigurations(self) -> list: ...
    def getStateCallback(self) -> StateCallback: ...
    def getExecutor(self) -> Executor: ...
    def setInputConfiguration(self, arg0: InputConfiguration) -> None: ...
    def getInputConfiguration(self) -> InputConfiguration: ...
    def setSessionParameters(self, arg0: CaptureRequest) -> None: ...
    def getSessionParameters(self) -> CaptureRequest: ...
    def setColorSpace(self, arg0: Named) -> None: ...
    def clearColorSpace(self) -> None: ...
    def getColorSpace(self) -> ColorSpace: ...
    def setStateCallback(self, arg0: Executor, arg1: StateCallback) -> None: ...
