from typing import Any, ClassVar, overload
from android.util.Range import Range
from android.util.Size import Size
from android.view.Surface import Surface

class StreamConfigurationMap:
    def getOutputFormats(self) -> list[int]: ...
    def getValidOutputFormatsForInput(self, arg0: int) -> list[int]: ...
    def getInputFormats(self) -> list[int]: ...
    def getInputSizes(self, arg0: int) -> list[Size]: ...
    @overload
    def isOutputSupportedFor(self, arg0: int) -> bool: ...
    @overload
    @staticmethod
    def isOutputSupportedFor(arg0: type) -> bool: ...
    @overload
    def isOutputSupportedFor(self, arg0: Surface) -> bool: ...
    @overload
    def getOutputSizes(self, arg0: type) -> list[Size]: ...
    @overload
    def getOutputSizes(self, arg0: int) -> list[Size]: ...
    def getHighSpeedVideoSizes(self) -> list[Size]: ...
    def getHighSpeedVideoFpsRangesFor(self, arg0: Size) -> list[Range]: ...
    def getHighSpeedVideoFpsRanges(self) -> list[Range]: ...
    def getHighSpeedVideoSizesFor(self, arg0: Range) -> list[Size]: ...
    def getHighResolutionOutputSizes(self, arg0: int) -> list[Size]: ...
    @overload
    def getOutputMinFrameDuration(self, arg0: int, arg1: Size) -> int: ...
    @overload
    def getOutputMinFrameDuration(self, arg0: type, arg1: Size) -> int: ...
    @overload
    def getOutputStallDuration(self, arg0: int, arg1: Size) -> int: ...
    @overload
    def getOutputStallDuration(self, arg0: type, arg1: Size) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
