from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.text.TextPaint import TextPaint

class BackgroundColorSpan:
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: Parcel) -> None: ...
    def getSpanTypeId(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getBackgroundColor(self) -> int: ...
    def updateDrawState(self, arg0: TextPaint) -> None: ...
    def toString(self) -> str: ...
