from typing import Any, ClassVar, overload
from android.text.TextPaint import TextPaint
from android.view.View import View

class ClickableSpan:
    def __init__(self) -> None: ...
    def onClick(self, arg0: View) -> None: ...
    def updateDrawState(self, arg0: TextPaint) -> None: ...
    def toString(self) -> str: ...
