from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.os.Parcel import Parcel

class EasyEditSpan:
    EXTRA_TEXT_CHANGED_TYPE: ClassVar[str]
    TEXT_DELETED: ClassVar[int]
    TEXT_MODIFIED: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: PendingIntent) -> None: ...
    @overload
    def __init__(self, arg0: Parcel) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getSpanTypeId(self) -> int: ...
