from typing import Any, ClassVar, overload
from android.text.TextPaint import TextPaint

class MetricAffectingSpan:
    def __init__(self) -> None: ...
    def updateMeasureState(self, arg0: TextPaint) -> None: ...
    def getUnderlying(self) -> "MetricAffectingSpan": ...
