from typing import Any, ClassVar, overload

class TabStopSpan:
    def getTabStop(self) -> int: ...

    class Standard:
        def __init__(self, arg0: int) -> None: ...
        def getTabStop(self) -> int: ...
        def toString(self) -> str: ...
