from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.ColorStateList import ColorStateList
from android.graphics.Typeface import Typeface
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from android.text.TextPaint import TextPaint

class TextAppearanceSpan:
    @overload
    def __init__(self, arg0: Context, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int, arg2: int, arg3: ColorStateList, arg4: ColorStateList) -> None: ...
    @overload
    def __init__(self, arg0: Parcel) -> None: ...
    def getSpanTypeId(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getFamily(self) -> str: ...
    def getTextColor(self) -> ColorStateList: ...
    def getLinkTextColor(self) -> ColorStateList: ...
    def getTextSize(self) -> int: ...
    def getTextStyle(self) -> int: ...
    def getTextFontWeight(self) -> int: ...
    def getTextLocales(self) -> LocaleList: ...
    def getTypeface(self) -> Typeface: ...
    def getShadowColor(self) -> int: ...
    def getShadowDx(self) -> float: ...
    def getShadowDy(self) -> float: ...
    def getShadowRadius(self) -> float: ...
    def getFontFeatureSettings(self) -> str: ...
    def getFontVariationSettings(self) -> str: ...
    def isElegantTextHeight(self) -> bool: ...
    def getLetterSpacing(self) -> float: ...
    def updateDrawState(self, arg0: TextPaint) -> None: ...
    def updateMeasureState(self, arg0: TextPaint) -> None: ...
    def toString(self) -> str: ...
