from typing import Any, ClassVar, overload
from android.graphics.Typeface import Typeface
from android.os.Parcel import Parcel
from android.text.TextPaint import TextPaint

class TypefaceSpan:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: Typeface) -> None: ...
    @overload
    def __init__(self, arg0: Parcel) -> None: ...
    def getSpanTypeId(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getFamily(self) -> str: ...
    def getTypeface(self) -> Typeface: ...
    def updateDrawState(self, arg0: TextPaint) -> None: ...
    def updateMeasureState(self, arg0: TextPaint) -> None: ...
    def toString(self) -> str: ...
