from typing import Any, ClassVar, overload
from java.security.Principal import Principal
from java.security.PrivateKey import PrivateKey
from java.security.cert.X509Certificate import X509Certificate

class ClientCertRequest:
    def __init__(self) -> None: ...
    def getKeyTypes(self) -> list[str]: ...
    def getPrincipals(self) -> list[Principal]: ...
    def getHost(self) -> str: ...
    def getPort(self) -> int: ...
    def proceed(self, arg0: PrivateKey, arg1: list[X509Certificate]) -> None: ...
    def ignore(self) -> None: ...
    def cancel(self) -> None: ...
