from typing import Any, ClassVar, overload

class ConsoleMessage:
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: "MessageLevel") -> None: ...
    def messageLevel(self) -> "MessageLevel": ...
    def message(self) -> str: ...
    def sourceId(self) -> str: ...
    def lineNumber(self) -> int: ...

    class MessageLevel:
        TIP: ClassVar["MessageLevel"]
        LOG: ClassVar["MessageLevel"]
        WARNING: ClassVar["MessageLevel"]
        ERROR: ClassVar["MessageLevel"]
        DEBUG: ClassVar["MessageLevel"]
        @staticmethod
        def values() -> list["MessageLevel"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "MessageLevel": ...
