from typing import Any, ClassVar, overload
from android.webkit.ValueCallback import ValueCallback
from android.webkit.WebView import WebView

class CookieManager:
    def __init__(self) -> None: ...
    def clone(self) -> Any: ...
    @staticmethod
    def getInstance() -> "CookieManager": ...
    def setAcceptCookie(self, arg0: bool) -> None: ...
    def acceptCookie(self) -> bool: ...
    def setAcceptThirdPartyCookies(self, arg0: WebView, arg1: bool) -> None: ...
    def acceptThirdPartyCookies(self, arg0: WebView) -> bool: ...
    @overload
    def setCookie(self, arg0: str, arg1: str) -> None: ...
    @overload
    def setCookie(self, arg0: str, arg1: str, arg2: ValueCallback) -> None: ...
    def getCookie(self, arg0: str) -> str: ...
    def removeSessionCookie(self) -> None: ...
    def removeSessionCookies(self, arg0: ValueCallback) -> None: ...
    def removeAllCookie(self) -> None: ...
    def removeAllCookies(self, arg0: ValueCallback) -> None: ...
    def hasCookies(self) -> bool: ...
    def removeExpiredCookie(self) -> None: ...
    def flush(self) -> None: ...
    @staticmethod
    def allowFileSchemeCookies() -> bool: ...
    @staticmethod
    def setAcceptFileSchemeCookies(arg0: bool) -> None: ...
