from typing import Any, ClassVar, overload
from android.content.Context import Context

class DateSorter:
    DAY_COUNT: ClassVar[int]
    def __init__(self, arg0: Context) -> None: ...
    def getIndex(self, arg0: int) -> int: ...
    def getLabel(self, arg0: int) -> str: ...
    def getBoundary(self, arg0: int) -> int: ...
