from typing import Any, ClassVar, overload

class HttpAuthHandler:
    def useHttpAuthUsernamePassword(self) -> bool: ...
    def cancel(self) -> None: ...
    def proceed(self, arg0: str, arg1: str) -> None: ...
