from typing import Any, ClassVar, overload

class MimeTypeMap:
    @staticmethod
    def getFileExtensionFromUrl(arg0: str) -> str: ...
    def hasMimeType(self, arg0: str) -> bool: ...
    def getMimeTypeFromExtension(self, arg0: str) -> str: ...
    def hasExtension(self, arg0: str) -> bool: ...
    def getExtensionFromMimeType(self, arg0: str) -> str: ...
    @staticmethod
    def getSingleton() -> "MimeTypeMap": ...
