from typing import Any, ClassVar, overload

class ServiceWorkerWebSettings:
    def __init__(self) -> None: ...
    def setCacheMode(self, arg0: int) -> None: ...
    def getCacheMode(self) -> int: ...
    def setAllowContentAccess(self, arg0: bool) -> None: ...
    def getAllowContentAccess(self) -> bool: ...
    def setAllowFileAccess(self, arg0: bool) -> None: ...
    def getAllowFileAccess(self) -> bool: ...
    def setBlockNetworkLoads(self, arg0: bool) -> None: ...
    def getBlockNetworkLoads(self) -> bool: ...
