from typing import Any, ClassVar, overload

class TracingConfig:
    CATEGORIES_ALL: ClassVar[int]
    CATEGORIES_ANDROID_WEBVIEW: ClassVar[int]
    CATEGORIES_FRAME_VIEWER: ClassVar[int]
    CATEGORIES_INPUT_LATENCY: ClassVar[int]
    CATEGORIES_JAVASCRIPT_AND_RENDERING: ClassVar[int]
    CATEGORIES_NONE: ClassVar[int]
    CATEGORIES_RENDERING: ClassVar[int]
    CATEGORIES_WEB_DEVELOPER: ClassVar[int]
    RECORD_CONTINUOUSLY: ClassVar[int]
    RECORD_UNTIL_FULL: ClassVar[int]
    def getPredefinedCategories(self) -> int: ...
    def getCustomIncludedCategories(self) -> list: ...
    def getTracingMode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "TracingConfig": ...
        @overload
        def addCategories(self, *arg0: int) -> "Builder": ...
        @overload
        def addCategories(self, *arg0: str) -> "Builder": ...
        @overload
        def addCategories(self, arg0: list) -> "Builder": ...
        def setTracingMode(self, arg0: int) -> "Builder": ...
