from typing import Any, ClassVar, overload

class URLUtil:
    def __init__(self) -> None: ...
    @staticmethod
    def guessUrl(arg0: str) -> str: ...
    @staticmethod
    def composeSearchUrl(arg0: str, arg1: str, arg2: str) -> str: ...
    @staticmethod
    def decode(arg0: list[int]) -> list[int]: ...
    @staticmethod
    def isAssetUrl(arg0: str) -> bool: ...
    @staticmethod
    def isCookielessProxyUrl(arg0: str) -> bool: ...
    @staticmethod
    def isFileUrl(arg0: str) -> bool: ...
    @staticmethod
    def isAboutUrl(arg0: str) -> bool: ...
    @staticmethod
    def isDataUrl(arg0: str) -> bool: ...
    @staticmethod
    def isJavaScriptUrl(arg0: str) -> bool: ...
    @staticmethod
    def isHttpUrl(arg0: str) -> bool: ...
    @staticmethod
    def isHttpsUrl(arg0: str) -> bool: ...
    @staticmethod
    def isNetworkUrl(arg0: str) -> bool: ...
    @staticmethod
    def isContentUrl(arg0: str) -> bool: ...
    @staticmethod
    def isValidUrl(arg0: str) -> bool: ...
    @staticmethod
    def stripAnchor(arg0: str) -> str: ...
    @staticmethod
    def guessFileName(arg0: str, arg1: str, arg2: str) -> str: ...
