from typing import Any, ClassVar, overload
from android.webkit.WebHistoryItem import WebHistoryItem

class WebBackForwardList:
    def __init__(self) -> None: ...
    def getCurrentItem(self) -> WebHistoryItem: ...
    def getCurrentIndex(self) -> int: ...
    def getItemAtIndex(self, arg0: int) -> WebHistoryItem: ...
    def getSize(self) -> int: ...
    def clone(self) -> "WebBackForwardList": ...
