from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap

class WebIconDatabase:
    def __init__(self) -> None: ...
    def open(self, arg0: str) -> None: ...
    def close(self) -> None: ...
    def removeAllIcons(self) -> None: ...
    def requestIconForPageUrl(self, arg0: str, arg1: "IconListener") -> None: ...
    def retainIconForPageUrl(self, arg0: str) -> None: ...
    def releaseIconForPageUrl(self, arg0: str) -> None: ...
    @staticmethod
    def getInstance() -> "WebIconDatabase": ...

    class IconListener:
        def onReceivedIcon(self, arg0: str, arg1: Bitmap) -> None: ...
