from typing import Any, ClassVar, overload
from android.webkit.WebMessagePort import WebMessagePort

class WebMessage:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: list[WebMessagePort]) -> None: ...
    def getData(self) -> str: ...
    def getPorts(self) -> list[WebMessagePort]: ...
