from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream

class WebResourceResponse:
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: InputStream) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int, arg3: str, arg4: dict, arg5: InputStream) -> None: ...
    def setMimeType(self, arg0: str) -> None: ...
    def getMimeType(self) -> str: ...
    def setEncoding(self, arg0: str) -> None: ...
    def getEncoding(self) -> str: ...
    def setStatusCodeAndReasonPhrase(self, arg0: int, arg1: str) -> None: ...
    def getStatusCode(self) -> int: ...
    def getReasonPhrase(self) -> str: ...
    def setResponseHeaders(self, arg0: dict) -> None: ...
    def getResponseHeaders(self) -> dict: ...
    def setData(self, arg0: InputStream) -> None: ...
    def getData(self) -> InputStream: ...
