from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class WebResourceRequest:
    def getUrl(self) -> Uri: ...
    def isForMainFrame(self) -> bool: ...
    def isRedirect(self) -> bool: ...
    def hasGesture(self) -> bool: ...
    def getMethod(self) -> str: ...
    def getRequestHeaders(self) -> dict: ...
