from typing import Any, ClassVar, overload
from android.webkit.ValueCallback import ValueCallback

class WebStorage:
    def getOrigins(self, arg0: ValueCallback) -> None: ...
    def getUsageForOrigin(self, arg0: str, arg1: ValueCallback) -> None: ...
    def getQuotaForOrigin(self, arg0: str, arg1: ValueCallback) -> None: ...
    def setQuotaForOrigin(self, arg0: str, arg1: int) -> None: ...
    def deleteOrigin(self, arg0: str) -> None: ...
    def deleteAllData(self) -> None: ...
    @staticmethod
    def getInstance() -> "WebStorage": ...

    class Origin:
        def getOrigin(self) -> str: ...
        def getQuota(self) -> int: ...
        def getUsage(self) -> int: ...

    class QuotaUpdater:
        def updateQuota(self, arg0: int) -> None: ...
