from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.view.LayoutInflater import LayoutInflater
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from android.webkit.WebView import WebView

class WebViewFragment:
    def __init__(self) -> None: ...
    def onCreateView(self, arg0: LayoutInflater, arg1: ViewGroup, arg2: Bundle) -> View: ...
    def onPause(self) -> None: ...
    def onResume(self) -> None: ...
    def onDestroyView(self) -> None: ...
    def onDestroy(self) -> None: ...
    def getWebView(self) -> WebView: ...
