from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.net.http.SslError import SslError
from android.os.Message import Message
from android.view.KeyEvent import KeyEvent
from android.webkit.ClientCertRequest import ClientCertRequest
from android.webkit.HttpAuthHandler import HttpAuthHandler
from android.webkit.RenderProcessGoneDetail import RenderProcessGoneDetail
from android.webkit.SafeBrowsingResponse import SafeBrowsingResponse
from android.webkit.SslErrorHandler import SslErrorHandler
from android.webkit.WebResourceError import WebResourceError
from android.webkit.WebResourceRequest import WebResourceRequest
from android.webkit.WebResourceResponse import WebResourceResponse
from android.webkit.WebView import WebView

class WebViewClient:
    ERROR_AUTHENTICATION: ClassVar[int]
    ERROR_BAD_URL: ClassVar[int]
    ERROR_CONNECT: ClassVar[int]
    ERROR_FAILED_SSL_HANDSHAKE: ClassVar[int]
    ERROR_FILE: ClassVar[int]
    ERROR_FILE_NOT_FOUND: ClassVar[int]
    ERROR_HOST_LOOKUP: ClassVar[int]
    ERROR_IO: ClassVar[int]
    ERROR_PROXY_AUTHENTICATION: ClassVar[int]
    ERROR_REDIRECT_LOOP: ClassVar[int]
    ERROR_TIMEOUT: ClassVar[int]
    ERROR_TOO_MANY_REQUESTS: ClassVar[int]
    ERROR_UNKNOWN: ClassVar[int]
    ERROR_UNSAFE_RESOURCE: ClassVar[int]
    ERROR_UNSUPPORTED_AUTH_SCHEME: ClassVar[int]
    ERROR_UNSUPPORTED_SCHEME: ClassVar[int]
    SAFE_BROWSING_THREAT_BILLING: ClassVar[int]
    SAFE_BROWSING_THREAT_MALWARE: ClassVar[int]
    SAFE_BROWSING_THREAT_PHISHING: ClassVar[int]
    SAFE_BROWSING_THREAT_UNKNOWN: ClassVar[int]
    SAFE_BROWSING_THREAT_UNWANTED_SOFTWARE: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    def shouldOverrideUrlLoading(self, arg0: WebView, arg1: str) -> bool: ...
    @overload
    def shouldOverrideUrlLoading(self, arg0: WebView, arg1: WebResourceRequest) -> bool: ...
    def onPageStarted(self, arg0: WebView, arg1: str, arg2: Bitmap) -> None: ...
    def onPageFinished(self, arg0: WebView, arg1: str) -> None: ...
    def onLoadResource(self, arg0: WebView, arg1: str) -> None: ...
    def onPageCommitVisible(self, arg0: WebView, arg1: str) -> None: ...
    @overload
    def shouldInterceptRequest(self, arg0: WebView, arg1: str) -> WebResourceResponse: ...
    @overload
    def shouldInterceptRequest(self, arg0: WebView, arg1: WebResourceRequest) -> WebResourceResponse: ...
    def onTooManyRedirects(self, arg0: WebView, arg1: Message, arg2: Message) -> None: ...
    @overload
    def onReceivedError(self, arg0: WebView, arg1: int, arg2: str, arg3: str) -> None: ...
    @overload
    def onReceivedError(self, arg0: WebView, arg1: WebResourceRequest, arg2: WebResourceError) -> None: ...
    def onReceivedHttpError(self, arg0: WebView, arg1: WebResourceRequest, arg2: WebResourceResponse) -> None: ...
    def onFormResubmission(self, arg0: WebView, arg1: Message, arg2: Message) -> None: ...
    def doUpdateVisitedHistory(self, arg0: WebView, arg1: str, arg2: bool) -> None: ...
    def onReceivedSslError(self, arg0: WebView, arg1: SslErrorHandler, arg2: SslError) -> None: ...
    def onReceivedClientCertRequest(self, arg0: WebView, arg1: ClientCertRequest) -> None: ...
    def onReceivedHttpAuthRequest(self, arg0: WebView, arg1: HttpAuthHandler, arg2: str, arg3: str) -> None: ...
    def shouldOverrideKeyEvent(self, arg0: WebView, arg1: KeyEvent) -> bool: ...
    def onUnhandledKeyEvent(self, arg0: WebView, arg1: KeyEvent) -> None: ...
    def onScaleChanged(self, arg0: WebView, arg1: float, arg2: float) -> None: ...
    def onReceivedLoginRequest(self, arg0: WebView, arg1: str, arg2: str, arg3: str) -> None: ...
    def onRenderProcessGone(self, arg0: WebView, arg1: RenderProcessGoneDetail) -> bool: ...
    def onSafeBrowsingHit(self, arg0: WebView, arg1: WebResourceRequest, arg2: int, arg3: SafeBrowsingResponse) -> None: ...
