from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress
from java.net.PasswordAuthentication import PasswordAuthentication
from java.net.URL import URL

class Authenticator:
    def __init__(self) -> None: ...
    @staticmethod
    def setDefault(arg0: "Authenticator") -> None: ...
    @overload
    @staticmethod
    def requestPasswordAuthentication(arg0: InetAddress, arg1: int, arg2: str, arg3: str, arg4: str) -> PasswordAuthentication: ...
    @overload
    @staticmethod
    def requestPasswordAuthentication(arg0: str, arg1: InetAddress, arg2: int, arg3: str, arg4: str, arg5: str) -> PasswordAuthentication: ...
    @overload
    @staticmethod
    def requestPasswordAuthentication(arg0: str, arg1: InetAddress, arg2: int, arg3: str, arg4: str, arg5: str, arg6: URL, arg7: "RequestorType") -> PasswordAuthentication: ...
    def getRequestingHost(self) -> str: ...
    def getRequestingSite(self) -> InetAddress: ...
    def getRequestingPort(self) -> int: ...
    def getRequestingProtocol(self) -> str: ...
    def getRequestingPrompt(self) -> str: ...
    def getRequestingScheme(self) -> str: ...
    def getPasswordAuthentication(self) -> PasswordAuthentication: ...
    def getRequestingURL(self) -> URL: ...
    def getRequestorType(self) -> "RequestorType": ...

    class RequestorType:
        PROXY: ClassVar["RequestorType"]
        SERVER: ClassVar["RequestorType"]
        @staticmethod
        def values() -> list["RequestorType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "RequestorType": ...
