from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream

class CacheResponse:
    def __init__(self) -> None: ...
    def getHeaders(self) -> dict: ...
    def getBody(self) -> InputStream: ...
