from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream

class CacheRequest:
    def __init__(self) -> None: ...
    def getBody(self) -> OutputStream: ...
    def abort(self) -> None: ...
