from typing import Any, ClassVar, overload
from java.net.CookiePolicy import CookiePolicy
from java.net.CookieStore import CookieStore
from java.net.URI import URI

class CookieManager:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: CookieStore, arg1: CookiePolicy) -> None: ...
    def setCookiePolicy(self, arg0: CookiePolicy) -> None: ...
    def getCookieStore(self) -> CookieStore: ...
    def get(self, arg0: URI, arg1: dict) -> dict: ...
    def put(self, arg0: URI, arg1: dict) -> None: ...
