from typing import Any, ClassVar, overload
from java.net.DatagramPacket import DatagramPacket
from java.net.DatagramSocketImpl import DatagramSocketImpl
from java.net.DatagramSocketImplFactory import DatagramSocketImplFactory
from java.net.InetAddress import InetAddress
from java.net.SocketAddress import SocketAddress
from java.net.SocketOption import SocketOption
from java.nio.channels.DatagramChannel import DatagramChannel

class DatagramSocket:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: DatagramSocketImpl) -> None: ...
    @overload
    def __init__(self, arg0: SocketAddress) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: InetAddress) -> None: ...
    def bind(self, arg0: SocketAddress) -> None: ...
    @overload
    def connect(self, arg0: InetAddress, arg1: int) -> None: ...
    @overload
    def connect(self, arg0: SocketAddress) -> None: ...
    def disconnect(self) -> None: ...
    def isBound(self) -> bool: ...
    def isConnected(self) -> bool: ...
    def getInetAddress(self) -> InetAddress: ...
    def getPort(self) -> int: ...
    def getRemoteSocketAddress(self) -> SocketAddress: ...
    def getLocalSocketAddress(self) -> SocketAddress: ...
    def send(self, arg0: DatagramPacket) -> None: ...
    def receive(self, arg0: DatagramPacket) -> None: ...
    def getLocalAddress(self) -> InetAddress: ...
    def getLocalPort(self) -> int: ...
    def setSoTimeout(self, arg0: int) -> None: ...
    def getSoTimeout(self) -> int: ...
    def setSendBufferSize(self, arg0: int) -> None: ...
    def getSendBufferSize(self) -> int: ...
    def setReceiveBufferSize(self, arg0: int) -> None: ...
    def getReceiveBufferSize(self) -> int: ...
    def setReuseAddress(self, arg0: bool) -> None: ...
    def getReuseAddress(self) -> bool: ...
    def setBroadcast(self, arg0: bool) -> None: ...
    def getBroadcast(self) -> bool: ...
    def setTrafficClass(self, arg0: int) -> None: ...
    def getTrafficClass(self) -> int: ...
    def close(self) -> None: ...
    def isClosed(self) -> bool: ...
    def getChannel(self) -> DatagramChannel: ...
    @staticmethod
    def setDatagramSocketImplFactory(arg0: DatagramSocketImplFactory) -> None: ...
    def setOption(self, arg0: SocketOption, arg1: Any) -> "DatagramSocket": ...
    def getOption(self, arg0: SocketOption) -> Any: ...
    def supportedOptions(self) -> set: ...
