from typing import Any, ClassVar, overload

class HttpCookie:
    def __init__(self, arg0: str, arg1: str) -> None: ...
    @staticmethod
    def parse(arg0: str) -> list: ...
    def hasExpired(self) -> bool: ...
    def setComment(self, arg0: str) -> None: ...
    def getComment(self) -> str: ...
    def setCommentURL(self, arg0: str) -> None: ...
    def getCommentURL(self) -> str: ...
    def setDiscard(self, arg0: bool) -> None: ...
    def getDiscard(self) -> bool: ...
    def setPortlist(self, arg0: str) -> None: ...
    def getPortlist(self) -> str: ...
    def setDomain(self, arg0: str) -> None: ...
    def getDomain(self) -> str: ...
    def setMaxAge(self, arg0: int) -> None: ...
    def getMaxAge(self) -> int: ...
    def setPath(self, arg0: str) -> None: ...
    def getPath(self) -> str: ...
    def setSecure(self, arg0: bool) -> None: ...
    def getSecure(self) -> bool: ...
    def getName(self) -> str: ...
    def setValue(self, arg0: str) -> None: ...
    def getValue(self) -> str: ...
    def getVersion(self) -> int: ...
    def setVersion(self, arg0: int) -> None: ...
    def isHttpOnly(self) -> bool: ...
    def setHttpOnly(self, arg0: bool) -> None: ...
    @staticmethod
    def domainMatches(arg0: str, arg1: str) -> bool: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
