from typing import Any, ClassVar, overload
from java.net.NetworkInterface import NetworkInterface

class InetAddress:
    def isMulticastAddress(self) -> bool: ...
    def isAnyLocalAddress(self) -> bool: ...
    def isLoopbackAddress(self) -> bool: ...
    def isLinkLocalAddress(self) -> bool: ...
    def isSiteLocalAddress(self) -> bool: ...
    def isMCGlobal(self) -> bool: ...
    def isMCNodeLocal(self) -> bool: ...
    def isMCLinkLocal(self) -> bool: ...
    def isMCSiteLocal(self) -> bool: ...
    def isMCOrgLocal(self) -> bool: ...
    @overload
    def isReachable(self, arg0: int) -> bool: ...
    @overload
    def isReachable(self, arg0: NetworkInterface, arg1: int, arg2: int) -> bool: ...
    def getHostName(self) -> str: ...
    def getCanonicalHostName(self) -> str: ...
    def getAddress(self) -> list[int]: ...
    def getHostAddress(self) -> str: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
    @overload
    @staticmethod
    def getByAddress(arg0: str, arg1: list[int]) -> "InetAddress": ...
    @overload
    @staticmethod
    def getByAddress(arg0: list[int]) -> "InetAddress": ...
    @staticmethod
    def getByName(arg0: str) -> "InetAddress": ...
    @staticmethod
    def getAllByName(arg0: str) -> list["InetAddress"]: ...
    @staticmethod
    def getLoopbackAddress() -> "InetAddress": ...
    @staticmethod
    def getLocalHost() -> "InetAddress": ...
