from typing import Any, ClassVar, overload

class Inet4Address:
    def isMulticastAddress(self) -> bool: ...
    def isAnyLocalAddress(self) -> bool: ...
    def isLoopbackAddress(self) -> bool: ...
    def isLinkLocalAddress(self) -> bool: ...
    def isSiteLocalAddress(self) -> bool: ...
    def isMCGlobal(self) -> bool: ...
    def isMCNodeLocal(self) -> bool: ...
    def isMCLinkLocal(self) -> bool: ...
    def isMCSiteLocal(self) -> bool: ...
    def isMCOrgLocal(self) -> bool: ...
    def getAddress(self) -> list[int]: ...
    def getHostAddress(self) -> str: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
