from typing import Any, ClassVar, overload
from java.net.DatagramPacket import DatagramPacket
from java.net.InetAddress import InetAddress
from java.net.NetworkInterface import NetworkInterface
from java.net.SocketAddress import SocketAddress

class MulticastSocket:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: SocketAddress) -> None: ...
    def setTTL(self, arg0: int) -> None: ...
    def setTimeToLive(self, arg0: int) -> None: ...
    def getTTL(self) -> int: ...
    def getTimeToLive(self) -> int: ...
    @overload
    def joinGroup(self, arg0: InetAddress) -> None: ...
    @overload
    def joinGroup(self, arg0: SocketAddress, arg1: NetworkInterface) -> None: ...
    @overload
    def leaveGroup(self, arg0: InetAddress) -> None: ...
    @overload
    def leaveGroup(self, arg0: SocketAddress, arg1: NetworkInterface) -> None: ...
    def setInterface(self, arg0: InetAddress) -> None: ...
    def getInterface(self) -> InetAddress: ...
    def setNetworkInterface(self, arg0: NetworkInterface) -> None: ...
    def getNetworkInterface(self) -> NetworkInterface: ...
    def setLoopbackMode(self, arg0: bool) -> None: ...
    def getLoopbackMode(self) -> bool: ...
    def send(self, arg0: DatagramPacket, arg1: int) -> None: ...
    def supportedOptions(self) -> set: ...
