from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress
from java.util.Enumeration import Enumeration

class NetworkInterface:
    def getName(self) -> str: ...
    def getInetAddresses(self) -> Enumeration: ...
    def getInterfaceAddresses(self) -> list: ...
    def getSubInterfaces(self) -> Enumeration: ...
    def getParent(self) -> "NetworkInterface": ...
    def getIndex(self) -> int: ...
    def getDisplayName(self) -> str: ...
    @staticmethod
    def getByName(arg0: str) -> "NetworkInterface": ...
    @staticmethod
    def getByIndex(arg0: int) -> "NetworkInterface": ...
    @staticmethod
    def getByInetAddress(arg0: InetAddress) -> "NetworkInterface": ...
    @staticmethod
    def getNetworkInterfaces() -> Enumeration: ...
    def isUp(self) -> bool: ...
    def isLoopback(self) -> bool: ...
    def isPointToPoint(self) -> bool: ...
    def supportsMulticast(self) -> bool: ...
    def getHardwareAddress(self) -> list[int]: ...
    def getMTU(self) -> int: ...
    def isVirtual(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
