from typing import Any, ClassVar, overload
from java.net.SocketAddress import SocketAddress

class Proxy:
    NO_PROXY: ClassVar["Proxy"]
    def __init__(self, arg0: "Type", arg1: SocketAddress) -> None: ...
    def type(self) -> "Type": ...
    def address(self) -> SocketAddress: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Type:
        DIRECT: ClassVar["Type"]
        HTTP: ClassVar["Type"]
        SOCKS: ClassVar["Type"]
        @staticmethod
        def values() -> list["Type"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Type": ...
