from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress
from java.net.Socket import Socket
from java.net.SocketAddress import SocketAddress
from java.net.SocketImplFactory import SocketImplFactory
from java.net.SocketOption import SocketOption
from java.nio.channels.ServerSocketChannel import ServerSocketChannel

class ServerSocket:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: InetAddress) -> None: ...
    @overload
    def bind(self, arg0: SocketAddress) -> None: ...
    @overload
    def bind(self, arg0: SocketAddress, arg1: int) -> None: ...
    def getInetAddress(self) -> InetAddress: ...
    def getLocalPort(self) -> int: ...
    def getLocalSocketAddress(self) -> SocketAddress: ...
    def accept(self) -> Socket: ...
    def implAccept(self, arg0: Socket) -> None: ...
    def close(self) -> None: ...
    def getChannel(self) -> ServerSocketChannel: ...
    def isBound(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def setSoTimeout(self, arg0: int) -> None: ...
    def getSoTimeout(self) -> int: ...
    def setReuseAddress(self, arg0: bool) -> None: ...
    def getReuseAddress(self) -> bool: ...
    def toString(self) -> str: ...
    @staticmethod
    def setSocketFactory(arg0: SocketImplFactory) -> None: ...
    def setReceiveBufferSize(self, arg0: int) -> None: ...
    def getReceiveBufferSize(self) -> int: ...
    def setPerformancePreferences(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def setOption(self, arg0: SocketOption, arg1: Any) -> "ServerSocket": ...
    def getOption(self, arg0: SocketOption) -> Any: ...
    def supportedOptions(self) -> set: ...
