from typing import Any, ClassVar, overload

class URISyntaxException:
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str) -> None: ...
    def getInput(self) -> str: ...
    def getReason(self) -> str: ...
    def getIndex(self) -> int: ...
    def getMessage(self) -> str: ...
