from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["Contacts"]

class Contacts(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/provider/Contacts"
    AUTHORITY = JavaStaticField("Ljava/lang/String;")
    CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
    KIND_EMAIL = JavaStaticField("I")
    KIND_IM = JavaStaticField("I")
    KIND_ORGANIZATION = JavaStaticField("I")
    KIND_PHONE = JavaStaticField("I")
    KIND_POSTAL = JavaStaticField("I")

    class ContactMethods(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/ContactMethods"
        CONTENT_EMAIL_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_EMAIL_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_EMAIL_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_IM_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_POSTAL_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_POSTAL_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        PERSON_ID = JavaStaticField("Ljava/lang/String;")
        POSTAL_LOCATION_LATITUDE = JavaStaticField("Ljava/lang/String;")
        POSTAL_LOCATION_LONGITUDE = JavaStaticField("Ljava/lang/String;")
        PROTOCOL_AIM = JavaStaticField("I")
        PROTOCOL_GOOGLE_TALK = JavaStaticField("I")
        PROTOCOL_ICQ = JavaStaticField("I")
        PROTOCOL_JABBER = JavaStaticField("I")
        PROTOCOL_MSN = JavaStaticField("I")
        PROTOCOL_QQ = JavaStaticField("I")
        PROTOCOL_SKYPE = JavaStaticField("I")
        PROTOCOL_YAHOO = JavaStaticField("I")
        encodePredefinedImProtocol = JavaStaticMethod("(I)Ljava/lang/String;")
        encodeCustomImProtocol = JavaStaticMethod("(Ljava/lang/String;)Ljava/lang/String;")
        decodeImProtocol = JavaStaticMethod("(Ljava/lang/String;)Ljava/lang/Object;")
        getDisplayLabel = JavaStaticMethod("(Landroid/content/Context;IILjava/lang/CharSequence;)Ljava/lang/CharSequence;")
        addPostalLocation = JavaMethod("(Landroid/content/Context;JDD)V")

    class ContactMethodsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/ContactMethodsColumns"
        AUX_DATA = JavaStaticField("Ljava/lang/String;")
        DATA = JavaStaticField("Ljava/lang/String;")
        ISPRIMARY = JavaStaticField("Ljava/lang/String;")
        KIND = JavaStaticField("Ljava/lang/String;")
        LABEL = JavaStaticField("Ljava/lang/String;")
        TYPE = JavaStaticField("Ljava/lang/String;")
        TYPE_CUSTOM = JavaStaticField("I")
        TYPE_HOME = JavaStaticField("I")
        TYPE_OTHER = JavaStaticField("I")
        TYPE_WORK = JavaStaticField("I")

    class Extensions(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/Extensions"
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        PERSON_ID = JavaStaticField("Ljava/lang/String;")

    class ExtensionsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/ExtensionsColumns"
        NAME = JavaStaticField("Ljava/lang/String;")
        VALUE = JavaStaticField("Ljava/lang/String;")

    class GroupMembership(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/GroupMembership"
        CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        GROUP_ID = JavaStaticField("Ljava/lang/String;")
        GROUP_SYNC_ACCOUNT = JavaStaticField("Ljava/lang/String;")
        GROUP_SYNC_ACCOUNT_TYPE = JavaStaticField("Ljava/lang/String;")
        GROUP_SYNC_ID = JavaStaticField("Ljava/lang/String;")
        PERSON_ID = JavaStaticField("Ljava/lang/String;")
        RAW_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")

    class Groups(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/Groups"
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        DELETED_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        GROUP_ANDROID_STARRED = JavaStaticField("Ljava/lang/String;")
        GROUP_MY_CONTACTS = JavaStaticField("Ljava/lang/String;")

    class GroupsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/GroupsColumns"
        NAME = JavaStaticField("Ljava/lang/String;")
        NOTES = JavaStaticField("Ljava/lang/String;")
        SHOULD_SYNC = JavaStaticField("Ljava/lang/String;")
        SYSTEM_ID = JavaStaticField("Ljava/lang/String;")

    class Intents(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/Intents"
        __javaconstructor__ = [("()V", False)]
        ATTACH_IMAGE = JavaStaticField("Ljava/lang/String;")
        EXTRA_CREATE_DESCRIPTION = JavaStaticField("Ljava/lang/String;")
        EXTRA_FORCE_CREATE = JavaStaticField("Ljava/lang/String;")
        SEARCH_SUGGESTION_CLICKED = JavaStaticField("Ljava/lang/String;")
        SEARCH_SUGGESTION_CREATE_CONTACT_CLICKED = JavaStaticField("Ljava/lang/String;")
        SEARCH_SUGGESTION_DIAL_NUMBER_CLICKED = JavaStaticField("Ljava/lang/String;")
        SHOW_OR_CREATE_CONTACT = JavaStaticField("Ljava/lang/String;")

        class Insert(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/Contacts/Intents/Insert"
            __javaconstructor__ = [("()V", False)]
            ACTION = JavaStaticField("Ljava/lang/String;")
            COMPANY = JavaStaticField("Ljava/lang/String;")
            EMAIL = JavaStaticField("Ljava/lang/String;")
            EMAIL_ISPRIMARY = JavaStaticField("Ljava/lang/String;")
            EMAIL_TYPE = JavaStaticField("Ljava/lang/String;")
            FULL_MODE = JavaStaticField("Ljava/lang/String;")
            IM_HANDLE = JavaStaticField("Ljava/lang/String;")
            IM_ISPRIMARY = JavaStaticField("Ljava/lang/String;")
            IM_PROTOCOL = JavaStaticField("Ljava/lang/String;")
            JOB_TITLE = JavaStaticField("Ljava/lang/String;")
            NAME = JavaStaticField("Ljava/lang/String;")
            NOTES = JavaStaticField("Ljava/lang/String;")
            PHONE = JavaStaticField("Ljava/lang/String;")
            PHONETIC_NAME = JavaStaticField("Ljava/lang/String;")
            PHONE_ISPRIMARY = JavaStaticField("Ljava/lang/String;")
            PHONE_TYPE = JavaStaticField("Ljava/lang/String;")
            POSTAL = JavaStaticField("Ljava/lang/String;")
            POSTAL_ISPRIMARY = JavaStaticField("Ljava/lang/String;")
            POSTAL_TYPE = JavaStaticField("Ljava/lang/String;")
            SECONDARY_EMAIL = JavaStaticField("Ljava/lang/String;")
            SECONDARY_EMAIL_TYPE = JavaStaticField("Ljava/lang/String;")
            SECONDARY_PHONE = JavaStaticField("Ljava/lang/String;")
            SECONDARY_PHONE_TYPE = JavaStaticField("Ljava/lang/String;")
            TERTIARY_EMAIL = JavaStaticField("Ljava/lang/String;")
            TERTIARY_EMAIL_TYPE = JavaStaticField("Ljava/lang/String;")
            TERTIARY_PHONE = JavaStaticField("Ljava/lang/String;")
            TERTIARY_PHONE_TYPE = JavaStaticField("Ljava/lang/String;")

        class UI(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/Contacts/Intents/UI"
            __javaconstructor__ = [("()V", False)]
            FILTER_CONTACTS_ACTION = JavaStaticField("Ljava/lang/String;")
            FILTER_TEXT_EXTRA_KEY = JavaStaticField("Ljava/lang/String;")
            GROUP_NAME_EXTRA_KEY = JavaStaticField("Ljava/lang/String;")
            LIST_ALL_CONTACTS_ACTION = JavaStaticField("Ljava/lang/String;")
            LIST_CONTACTS_WITH_PHONES_ACTION = JavaStaticField("Ljava/lang/String;")
            LIST_DEFAULT = JavaStaticField("Ljava/lang/String;")
            LIST_FREQUENT_ACTION = JavaStaticField("Ljava/lang/String;")
            LIST_GROUP_ACTION = JavaStaticField("Ljava/lang/String;")
            LIST_STARRED_ACTION = JavaStaticField("Ljava/lang/String;")
            LIST_STREQUENT_ACTION = JavaStaticField("Ljava/lang/String;")
            TITLE_EXTRA_KEY = JavaStaticField("Ljava/lang/String;")

    class OrganizationColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/OrganizationColumns"
        COMPANY = JavaStaticField("Ljava/lang/String;")
        ISPRIMARY = JavaStaticField("Ljava/lang/String;")
        LABEL = JavaStaticField("Ljava/lang/String;")
        PERSON_ID = JavaStaticField("Ljava/lang/String;")
        TITLE = JavaStaticField("Ljava/lang/String;")
        TYPE = JavaStaticField("Ljava/lang/String;")
        TYPE_CUSTOM = JavaStaticField("I")
        TYPE_OTHER = JavaStaticField("I")
        TYPE_WORK = JavaStaticField("I")

    class Organizations(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/Organizations"
        CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        getDisplayLabel = JavaStaticMethod("(Landroid/content/Context;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

    class People(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/People"
        CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        DELETED_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        PRIMARY_EMAIL_ID = JavaStaticField("Ljava/lang/String;")
        PRIMARY_ORGANIZATION_ID = JavaStaticField("Ljava/lang/String;")
        PRIMARY_PHONE_ID = JavaStaticField("Ljava/lang/String;")
        markAsContacted = JavaStaticMethod("(Landroid/content/ContentResolver;J)V")
        addToMyContactsGroup = JavaStaticMethod("(Landroid/content/ContentResolver;J)Landroid/net/Uri;")
        addToGroup = JavaMultipleMethod([("(Landroid/content/ContentResolver;JLjava/lang/String;)Landroid/net/Uri;", True, False), ("(Landroid/content/ContentResolver;JJ)Landroid/net/Uri;", True, False)])
        createPersonInMyContactsGroup = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/content/ContentValues;)Landroid/net/Uri;")
        queryGroups = JavaStaticMethod("(Landroid/content/ContentResolver;J)Landroid/database/Cursor;")
        setPhotoData = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;[B)V")
        openContactPhotoInputStream = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;)Ljava/io/InputStream;")
        loadContactPhoto = JavaStaticMethod("(Landroid/content/Context;Landroid/net/Uri;ILandroid/graphics/BitmapFactory$Options;)Landroid/graphics/Bitmap;")

        class ContactMethods(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/Contacts/People/ContactMethods"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")

        class Extensions(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/Contacts/People/Extensions"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            PERSON_ID = JavaStaticField("Ljava/lang/String;")

        class Phones(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/Contacts/People/Phones"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")

    class PeopleColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/PeopleColumns"
        CUSTOM_RINGTONE = JavaStaticField("Ljava/lang/String;")
        DISPLAY_NAME = JavaStaticField("Ljava/lang/String;")
        LAST_TIME_CONTACTED = JavaStaticField("Ljava/lang/String;")
        NAME = JavaStaticField("Ljava/lang/String;")
        NOTES = JavaStaticField("Ljava/lang/String;")
        PHONETIC_NAME = JavaStaticField("Ljava/lang/String;")
        PHOTO_VERSION = JavaStaticField("Ljava/lang/String;")
        SEND_TO_VOICEMAIL = JavaStaticField("Ljava/lang/String;")
        STARRED = JavaStaticField("Ljava/lang/String;")
        TIMES_CONTACTED = JavaStaticField("Ljava/lang/String;")

    class Phones(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/Phones"
        CONTENT_FILTER_URL = JavaStaticField("Landroid/net/Uri;")
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        PERSON_ID = JavaStaticField("Ljava/lang/String;")
        getDisplayLabel = JavaMultipleMethod([("(Landroid/content/Context;ILjava/lang/CharSequence;[Ljava/lang/CharSequence;)Ljava/lang/CharSequence;", True, False), ("(Landroid/content/Context;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;", True, False)])

    class PhonesColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/PhonesColumns"
        ISPRIMARY = JavaStaticField("Ljava/lang/String;")
        LABEL = JavaStaticField("Ljava/lang/String;")
        NUMBER = JavaStaticField("Ljava/lang/String;")
        NUMBER_KEY = JavaStaticField("Ljava/lang/String;")
        TYPE = JavaStaticField("Ljava/lang/String;")
        TYPE_CUSTOM = JavaStaticField("I")
        TYPE_FAX_HOME = JavaStaticField("I")
        TYPE_FAX_WORK = JavaStaticField("I")
        TYPE_HOME = JavaStaticField("I")
        TYPE_MOBILE = JavaStaticField("I")
        TYPE_OTHER = JavaStaticField("I")
        TYPE_PAGER = JavaStaticField("I")
        TYPE_WORK = JavaStaticField("I")

    class Photos(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/Photos"
        CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")

    class PhotosColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/PhotosColumns"
        DATA = JavaStaticField("Ljava/lang/String;")
        DOWNLOAD_REQUIRED = JavaStaticField("Ljava/lang/String;")
        EXISTS_ON_SERVER = JavaStaticField("Ljava/lang/String;")
        LOCAL_VERSION = JavaStaticField("Ljava/lang/String;")
        PERSON_ID = JavaStaticField("Ljava/lang/String;")
        SYNC_ERROR = JavaStaticField("Ljava/lang/String;")

    class PresenceColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/PresenceColumns"
        AVAILABLE = JavaStaticField("I")
        AWAY = JavaStaticField("I")
        DO_NOT_DISTURB = JavaStaticField("I")
        IDLE = JavaStaticField("I")
        IM_ACCOUNT = JavaStaticField("Ljava/lang/String;")
        IM_HANDLE = JavaStaticField("Ljava/lang/String;")
        IM_PROTOCOL = JavaStaticField("Ljava/lang/String;")
        INVISIBLE = JavaStaticField("I")
        OFFLINE = JavaStaticField("I")
        PRESENCE_CUSTOM_STATUS = JavaStaticField("Ljava/lang/String;")
        PRESENCE_STATUS = JavaStaticField("Ljava/lang/String;")
        PRIORITY = JavaStaticField("Ljava/lang/String;")

    class Settings(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/Settings"
        CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        SYNC_EVERYTHING = JavaStaticField("Ljava/lang/String;")
        getSetting = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
        setSetting = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V")

    class SettingsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/Contacts/SettingsColumns"
        KEY = JavaStaticField("Ljava/lang/String;")
        VALUE = JavaStaticField("Ljava/lang/String;")
        _SYNC_ACCOUNT = JavaStaticField("Ljava/lang/String;")
        _SYNC_ACCOUNT_TYPE = JavaStaticField("Ljava/lang/String;")