from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["ContactsContract"]

class ContactsContract(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/provider/ContactsContract"
    __javaconstructor__ = [("()V", False)]
    AUTHORITY = JavaStaticField("Ljava/lang/String;")
    AUTHORITY_URI = JavaStaticField("Landroid/net/Uri;")
    CALLER_IS_SYNCADAPTER = JavaStaticField("Ljava/lang/String;")
    DEFERRED_SNIPPETING = JavaStaticField("Ljava/lang/String;")
    DEFERRED_SNIPPETING_QUERY = JavaStaticField("Ljava/lang/String;")
    DIRECTORY_PARAM_KEY = JavaStaticField("Ljava/lang/String;")
    LIMIT_PARAM_KEY = JavaStaticField("Ljava/lang/String;")
    PRIMARY_ACCOUNT_NAME = JavaStaticField("Ljava/lang/String;")
    PRIMARY_ACCOUNT_TYPE = JavaStaticField("Ljava/lang/String;")
    REMOVE_DUPLICATE_ENTRIES = JavaStaticField("Ljava/lang/String;")
    STREQUENT_PHONE_ONLY = JavaStaticField("Ljava/lang/String;")
    isProfileId = JavaStaticMethod("(J)Z")

    class AggregationExceptions(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/AggregationExceptions"
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        RAW_CONTACT_ID1 = JavaStaticField("Ljava/lang/String;")
        RAW_CONTACT_ID2 = JavaStaticField("Ljava/lang/String;")
        TYPE = JavaStaticField("Ljava/lang/String;")
        TYPE_AUTOMATIC = JavaStaticField("I")
        TYPE_KEEP_SEPARATE = JavaStaticField("I")
        TYPE_KEEP_TOGETHER = JavaStaticField("I")

    class BaseSyncColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/BaseSyncColumns"
        SYNC1 = JavaStaticField("Ljava/lang/String;")
        SYNC2 = JavaStaticField("Ljava/lang/String;")
        SYNC3 = JavaStaticField("Ljava/lang/String;")
        SYNC4 = JavaStaticField("Ljava/lang/String;")

    class CommonDataKinds(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/CommonDataKinds"

        class BaseTypes(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/BaseTypes"
            TYPE_CUSTOM = JavaStaticField("I")

        class Callable(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Callable"
            __javaconstructor__ = [("()V", False)]
            CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
            CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            ENTERPRISE_CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")

        class CommonColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/CommonColumns"
            DATA = JavaStaticField("Ljava/lang/String;")
            LABEL = JavaStaticField("Ljava/lang/String;")
            TYPE = JavaStaticField("Ljava/lang/String;")

        class Contactables(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Contactables"
            __javaconstructor__ = [("()V", False)]
            CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
            CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            VISIBLE_CONTACTS_ONLY = JavaStaticField("Ljava/lang/String;")

        class Email(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Email"
            ADDRESS = JavaStaticField("Ljava/lang/String;")
            CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            CONTENT_LOOKUP_URI = JavaStaticField("Landroid/net/Uri;")
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            DISPLAY_NAME = JavaStaticField("Ljava/lang/String;")
            ENTERPRISE_CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
            ENTERPRISE_CONTENT_LOOKUP_URI = JavaStaticField("Landroid/net/Uri;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            TYPE_HOME = JavaStaticField("I")
            TYPE_MOBILE = JavaStaticField("I")
            TYPE_OTHER = JavaStaticField("I")
            TYPE_WORK = JavaStaticField("I")
            getTypeLabelResource = JavaStaticMethod("(I)I")
            getTypeLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

        class Event(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Event"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            START_DATE = JavaStaticField("Ljava/lang/String;")
            TYPE_ANNIVERSARY = JavaStaticField("I")
            TYPE_BIRTHDAY = JavaStaticField("I")
            TYPE_OTHER = JavaStaticField("I")
            getTypeResource = JavaStaticMethod("(Ljava/lang/Integer;)I")
            getTypeLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

        class GroupMembership(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/GroupMembership"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            GROUP_ROW_ID = JavaStaticField("Ljava/lang/String;")
            GROUP_SOURCE_ID = JavaStaticField("Ljava/lang/String;")

        class Identity(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Identity"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            IDENTITY = JavaStaticField("Ljava/lang/String;")
            NAMESPACE = JavaStaticField("Ljava/lang/String;")

        class Im(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Im"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            CUSTOM_PROTOCOL = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            PROTOCOL = JavaStaticField("Ljava/lang/String;")
            PROTOCOL_AIM = JavaStaticField("I")
            PROTOCOL_CUSTOM = JavaStaticField("I")
            PROTOCOL_GOOGLE_TALK = JavaStaticField("I")
            PROTOCOL_ICQ = JavaStaticField("I")
            PROTOCOL_JABBER = JavaStaticField("I")
            PROTOCOL_MSN = JavaStaticField("I")
            PROTOCOL_NETMEETING = JavaStaticField("I")
            PROTOCOL_QQ = JavaStaticField("I")
            PROTOCOL_SKYPE = JavaStaticField("I")
            PROTOCOL_YAHOO = JavaStaticField("I")
            TYPE_HOME = JavaStaticField("I")
            TYPE_OTHER = JavaStaticField("I")
            TYPE_WORK = JavaStaticField("I")
            getTypeLabelResource = JavaStaticMethod("(I)I")
            getTypeLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")
            getProtocolLabelResource = JavaStaticMethod("(I)I")
            getProtocolLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

        class Nickname(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Nickname"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            NAME = JavaStaticField("Ljava/lang/String;")
            TYPE_DEFAULT = JavaStaticField("I")
            TYPE_INITIALS = JavaStaticField("I")
            TYPE_MAIDEN_NAME = JavaStaticField("I")
            TYPE_MAINDEN_NAME = JavaStaticField("I")
            TYPE_OTHER_NAME = JavaStaticField("I")
            TYPE_SHORT_NAME = JavaStaticField("I")

        class Note(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Note"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            NOTE = JavaStaticField("Ljava/lang/String;")

        class Organization(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Organization"
            COMPANY = JavaStaticField("Ljava/lang/String;")
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            DEPARTMENT = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            JOB_DESCRIPTION = JavaStaticField("Ljava/lang/String;")
            OFFICE_LOCATION = JavaStaticField("Ljava/lang/String;")
            PHONETIC_NAME = JavaStaticField("Ljava/lang/String;")
            PHONETIC_NAME_STYLE = JavaStaticField("Ljava/lang/String;")
            SYMBOL = JavaStaticField("Ljava/lang/String;")
            TITLE = JavaStaticField("Ljava/lang/String;")
            TYPE_OTHER = JavaStaticField("I")
            TYPE_WORK = JavaStaticField("I")
            getTypeLabelResource = JavaStaticMethod("(I)I")
            getTypeLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

        class Phone(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Phone"
            CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            ENTERPRISE_CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
            ENTERPRISE_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            NORMALIZED_NUMBER = JavaStaticField("Ljava/lang/String;")
            NUMBER = JavaStaticField("Ljava/lang/String;")
            SEARCH_DISPLAY_NAME_KEY = JavaStaticField("Ljava/lang/String;")
            SEARCH_PHONE_NUMBER_KEY = JavaStaticField("Ljava/lang/String;")
            TYPE_ASSISTANT = JavaStaticField("I")
            TYPE_CALLBACK = JavaStaticField("I")
            TYPE_CAR = JavaStaticField("I")
            TYPE_COMPANY_MAIN = JavaStaticField("I")
            TYPE_FAX_HOME = JavaStaticField("I")
            TYPE_FAX_WORK = JavaStaticField("I")
            TYPE_HOME = JavaStaticField("I")
            TYPE_ISDN = JavaStaticField("I")
            TYPE_MAIN = JavaStaticField("I")
            TYPE_MMS = JavaStaticField("I")
            TYPE_MOBILE = JavaStaticField("I")
            TYPE_OTHER = JavaStaticField("I")
            TYPE_OTHER_FAX = JavaStaticField("I")
            TYPE_PAGER = JavaStaticField("I")
            TYPE_RADIO = JavaStaticField("I")
            TYPE_TELEX = JavaStaticField("I")
            TYPE_TTY_TDD = JavaStaticField("I")
            TYPE_WORK = JavaStaticField("I")
            TYPE_WORK_MOBILE = JavaStaticField("I")
            TYPE_WORK_PAGER = JavaStaticField("I")
            getTypeLabelResource = JavaStaticMethod("(I)I")
            getTypeLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

        class Photo(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Photo"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            PHOTO = JavaStaticField("Ljava/lang/String;")
            PHOTO_FILE_ID = JavaStaticField("Ljava/lang/String;")

        class Relation(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Relation"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            NAME = JavaStaticField("Ljava/lang/String;")
            TYPE_ASSISTANT = JavaStaticField("I")
            TYPE_BROTHER = JavaStaticField("I")
            TYPE_CHILD = JavaStaticField("I")
            TYPE_DOMESTIC_PARTNER = JavaStaticField("I")
            TYPE_FATHER = JavaStaticField("I")
            TYPE_FRIEND = JavaStaticField("I")
            TYPE_MANAGER = JavaStaticField("I")
            TYPE_MOTHER = JavaStaticField("I")
            TYPE_PARENT = JavaStaticField("I")
            TYPE_PARTNER = JavaStaticField("I")
            TYPE_REFERRED_BY = JavaStaticField("I")
            TYPE_RELATIVE = JavaStaticField("I")
            TYPE_SISTER = JavaStaticField("I")
            TYPE_SPOUSE = JavaStaticField("I")
            getTypeLabelResource = JavaStaticMethod("(I)I")
            getTypeLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

        class SipAddress(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/SipAddress"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            SIP_ADDRESS = JavaStaticField("Ljava/lang/String;")
            TYPE_HOME = JavaStaticField("I")
            TYPE_OTHER = JavaStaticField("I")
            TYPE_WORK = JavaStaticField("I")
            getTypeLabelResource = JavaStaticMethod("(I)I")
            getTypeLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

        class StructuredName(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/StructuredName"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            DISPLAY_NAME = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            FAMILY_NAME = JavaStaticField("Ljava/lang/String;")
            FULL_NAME_STYLE = JavaStaticField("Ljava/lang/String;")
            GIVEN_NAME = JavaStaticField("Ljava/lang/String;")
            MIDDLE_NAME = JavaStaticField("Ljava/lang/String;")
            PHONETIC_FAMILY_NAME = JavaStaticField("Ljava/lang/String;")
            PHONETIC_GIVEN_NAME = JavaStaticField("Ljava/lang/String;")
            PHONETIC_MIDDLE_NAME = JavaStaticField("Ljava/lang/String;")
            PHONETIC_NAME_STYLE = JavaStaticField("Ljava/lang/String;")
            PREFIX = JavaStaticField("Ljava/lang/String;")
            SUFFIX = JavaStaticField("Ljava/lang/String;")

        class StructuredPostal(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/StructuredPostal"
            CITY = JavaStaticField("Ljava/lang/String;")
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            COUNTRY = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            FORMATTED_ADDRESS = JavaStaticField("Ljava/lang/String;")
            NEIGHBORHOOD = JavaStaticField("Ljava/lang/String;")
            POBOX = JavaStaticField("Ljava/lang/String;")
            POSTCODE = JavaStaticField("Ljava/lang/String;")
            REGION = JavaStaticField("Ljava/lang/String;")
            STREET = JavaStaticField("Ljava/lang/String;")
            TYPE_HOME = JavaStaticField("I")
            TYPE_OTHER = JavaStaticField("I")
            TYPE_WORK = JavaStaticField("I")
            getTypeLabelResource = JavaStaticMethod("(I)I")
            getTypeLabel = JavaStaticMethod("(Landroid/content/res/Resources;ILjava/lang/CharSequence;)Ljava/lang/CharSequence;")

        class Website(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/CommonDataKinds/Website"
            CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
            EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
            TYPE_BLOG = JavaStaticField("I")
            TYPE_FTP = JavaStaticField("I")
            TYPE_HOME = JavaStaticField("I")
            TYPE_HOMEPAGE = JavaStaticField("I")
            TYPE_OTHER = JavaStaticField("I")
            TYPE_PROFILE = JavaStaticField("I")
            TYPE_WORK = JavaStaticField("I")
            URL = JavaStaticField("Ljava/lang/String;")

    class ContactNameColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/ContactNameColumns"
        DISPLAY_NAME_ALTERNATIVE = JavaStaticField("Ljava/lang/String;")
        DISPLAY_NAME_PRIMARY = JavaStaticField("Ljava/lang/String;")
        DISPLAY_NAME_SOURCE = JavaStaticField("Ljava/lang/String;")
        PHONETIC_NAME = JavaStaticField("Ljava/lang/String;")
        PHONETIC_NAME_STYLE = JavaStaticField("Ljava/lang/String;")
        SORT_KEY_ALTERNATIVE = JavaStaticField("Ljava/lang/String;")
        SORT_KEY_PRIMARY = JavaStaticField("Ljava/lang/String;")

    class ContactOptionsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/ContactOptionsColumns"
        CUSTOM_RINGTONE = JavaStaticField("Ljava/lang/String;")
        LAST_TIME_CONTACTED = JavaStaticField("Ljava/lang/String;")
        PINNED = JavaStaticField("Ljava/lang/String;")
        SEND_TO_VOICEMAIL = JavaStaticField("Ljava/lang/String;")
        STARRED = JavaStaticField("Ljava/lang/String;")
        TIMES_CONTACTED = JavaStaticField("Ljava/lang/String;")

    class ContactStatusColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/ContactStatusColumns"
        CONTACT_CHAT_CAPABILITY = JavaStaticField("Ljava/lang/String;")
        CONTACT_PRESENCE = JavaStaticField("Ljava/lang/String;")
        CONTACT_STATUS = JavaStaticField("Ljava/lang/String;")
        CONTACT_STATUS_ICON = JavaStaticField("Ljava/lang/String;")
        CONTACT_STATUS_LABEL = JavaStaticField("Ljava/lang/String;")
        CONTACT_STATUS_RES_PACKAGE = JavaStaticField("Ljava/lang/String;")
        CONTACT_STATUS_TIMESTAMP = JavaStaticField("Ljava/lang/String;")

    class Contacts(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/Contacts"
        CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_FREQUENT_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_GROUP_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_LOOKUP_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_MULTI_VCARD_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_STREQUENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_STREQUENT_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_VCARD_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_VCARD_URI = JavaStaticField("Landroid/net/Uri;")
        ENTERPRISE_CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
        ENTERPRISE_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
        EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
        EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
        QUERY_PARAMETER_VCARD_NO_PHOTO = JavaStaticField("Ljava/lang/String;")
        getLookupUri = JavaMultipleMethod([("(Landroid/content/ContentResolver;Landroid/net/Uri;)Landroid/net/Uri;", True, False), ("(JLjava/lang/String;)Landroid/net/Uri;", True, False)])
        lookupContact = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;)Landroid/net/Uri;")
        markAsContacted = JavaStaticMethod("(Landroid/content/ContentResolver;J)V")
        isEnterpriseContactId = JavaStaticMethod("(J)Z")
        openContactPhotoInputStream = JavaMultipleMethod([("(Landroid/content/ContentResolver;Landroid/net/Uri;Z)Ljava/io/InputStream;", True, False), ("(Landroid/content/ContentResolver;Landroid/net/Uri;)Ljava/io/InputStream;", True, False)])

        class AggregationSuggestions(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/Contacts/AggregationSuggestions"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")

            class Builder(JavaClass, metaclass=MetaJavaClass):
                __javaclass__ = "android/provider/ContactsContract/Contacts/AggregationSuggestions/Builder"
                __javaconstructor__ = [("()V", False)]
                setContactId = JavaMethod("(J)Landroid/provider/ContactsContract$Contacts$AggregationSuggestions$Builder;")
                addNameParameter = JavaMethod("(Ljava/lang/String;)Landroid/provider/ContactsContract$Contacts$AggregationSuggestions$Builder;")
                setLimit = JavaMethod("(I)Landroid/provider/ContactsContract$Contacts$AggregationSuggestions$Builder;")
                build = JavaMethod("()Landroid/net/Uri;")

        class Data(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/Contacts/Data"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")

        class Entity(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/Contacts/Entity"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
            DATA_ID = JavaStaticField("Ljava/lang/String;")
            RAW_CONTACT_ID = JavaStaticField("Ljava/lang/String;")

        class Photo(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/Contacts/Photo"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
            DISPLAY_PHOTO = JavaStaticField("Ljava/lang/String;")
            PHOTO = JavaStaticField("Ljava/lang/String;")
            PHOTO_FILE_ID = JavaStaticField("Ljava/lang/String;")

    class ContactsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/ContactsColumns"
        CONTACT_LAST_UPDATED_TIMESTAMP = JavaStaticField("Ljava/lang/String;")
        DISPLAY_NAME = JavaStaticField("Ljava/lang/String;")
        HAS_PHONE_NUMBER = JavaStaticField("Ljava/lang/String;")
        IN_DEFAULT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
        IN_VISIBLE_GROUP = JavaStaticField("Ljava/lang/String;")
        IS_USER_PROFILE = JavaStaticField("Ljava/lang/String;")
        LOOKUP_KEY = JavaStaticField("Ljava/lang/String;")
        NAME_RAW_CONTACT_ID = JavaStaticField("Ljava/lang/String;")
        PHOTO_FILE_ID = JavaStaticField("Ljava/lang/String;")
        PHOTO_ID = JavaStaticField("Ljava/lang/String;")
        PHOTO_THUMBNAIL_URI = JavaStaticField("Ljava/lang/String;")
        PHOTO_URI = JavaStaticField("Ljava/lang/String;")

    class Data(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/Data"
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        EXTRA_ADDRESS_BOOK_INDEX = JavaStaticField("Ljava/lang/String;")
        EXTRA_ADDRESS_BOOK_INDEX_COUNTS = JavaStaticField("Ljava/lang/String;")
        EXTRA_ADDRESS_BOOK_INDEX_TITLES = JavaStaticField("Ljava/lang/String;")
        VISIBLE_CONTACTS_ONLY = JavaStaticField("Ljava/lang/String;")
        getContactLookupUri = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;)Landroid/net/Uri;")

    class DataColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/DataColumns"
        CARRIER_PRESENCE = JavaStaticField("Ljava/lang/String;")
        CARRIER_PRESENCE_VT_CAPABLE = JavaStaticField("I")
        DATA1 = JavaStaticField("Ljava/lang/String;")
        DATA10 = JavaStaticField("Ljava/lang/String;")
        DATA11 = JavaStaticField("Ljava/lang/String;")
        DATA12 = JavaStaticField("Ljava/lang/String;")
        DATA13 = JavaStaticField("Ljava/lang/String;")
        DATA14 = JavaStaticField("Ljava/lang/String;")
        DATA15 = JavaStaticField("Ljava/lang/String;")
        DATA2 = JavaStaticField("Ljava/lang/String;")
        DATA3 = JavaStaticField("Ljava/lang/String;")
        DATA4 = JavaStaticField("Ljava/lang/String;")
        DATA5 = JavaStaticField("Ljava/lang/String;")
        DATA6 = JavaStaticField("Ljava/lang/String;")
        DATA7 = JavaStaticField("Ljava/lang/String;")
        DATA8 = JavaStaticField("Ljava/lang/String;")
        DATA9 = JavaStaticField("Ljava/lang/String;")
        DATA_VERSION = JavaStaticField("Ljava/lang/String;")
        IS_PRIMARY = JavaStaticField("Ljava/lang/String;")
        IS_READ_ONLY = JavaStaticField("Ljava/lang/String;")
        IS_SUPER_PRIMARY = JavaStaticField("Ljava/lang/String;")
        MIMETYPE = JavaStaticField("Ljava/lang/String;")
        PREFERRED_PHONE_ACCOUNT_COMPONENT_NAME = JavaStaticField("Ljava/lang/String;")
        PREFERRED_PHONE_ACCOUNT_ID = JavaStaticField("Ljava/lang/String;")
        RAW_CONTACT_ID = JavaStaticField("Ljava/lang/String;")
        RES_PACKAGE = JavaStaticField("Ljava/lang/String;")
        SYNC1 = JavaStaticField("Ljava/lang/String;")
        SYNC2 = JavaStaticField("Ljava/lang/String;")
        SYNC3 = JavaStaticField("Ljava/lang/String;")
        SYNC4 = JavaStaticField("Ljava/lang/String;")

    class DataColumnsWithJoins(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/DataColumnsWithJoins"

    class DataUsageFeedback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/DataUsageFeedback"
        __javaconstructor__ = [("()V", False)]
        DELETE_USAGE_URI = JavaStaticField("Landroid/net/Uri;")
        FEEDBACK_URI = JavaStaticField("Landroid/net/Uri;")
        USAGE_TYPE = JavaStaticField("Ljava/lang/String;")
        USAGE_TYPE_CALL = JavaStaticField("Ljava/lang/String;")
        USAGE_TYPE_LONG_TEXT = JavaStaticField("Ljava/lang/String;")
        USAGE_TYPE_SHORT_TEXT = JavaStaticField("Ljava/lang/String;")

    class DataUsageStatColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/DataUsageStatColumns"
        LAST_TIME_USED = JavaStaticField("Ljava/lang/String;")
        TIMES_USED = JavaStaticField("Ljava/lang/String;")

    class DeletedContacts(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/DeletedContacts"
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DAYS_KEPT_MILLISECONDS = JavaStaticField("J")

    class DeletedContactsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/DeletedContactsColumns"
        CONTACT_DELETED_TIMESTAMP = JavaStaticField("Ljava/lang/String;")
        CONTACT_ID = JavaStaticField("Ljava/lang/String;")

    class Directory(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/Directory"
        ACCOUNT_NAME = JavaStaticField("Ljava/lang/String;")
        ACCOUNT_TYPE = JavaStaticField("Ljava/lang/String;")
        CALLER_PACKAGE_PARAM_KEY = JavaStaticField("Ljava/lang/String;")
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DEFAULT = JavaStaticField("J")
        DIRECTORY_AUTHORITY = JavaStaticField("Ljava/lang/String;")
        DISPLAY_NAME = JavaStaticField("Ljava/lang/String;")
        ENTERPRISE_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        ENTERPRISE_DEFAULT = JavaStaticField("J")
        ENTERPRISE_LOCAL_INVISIBLE = JavaStaticField("J")
        EXPORT_SUPPORT = JavaStaticField("Ljava/lang/String;")
        EXPORT_SUPPORT_ANY_ACCOUNT = JavaStaticField("I")
        EXPORT_SUPPORT_NONE = JavaStaticField("I")
        EXPORT_SUPPORT_SAME_ACCOUNT_ONLY = JavaStaticField("I")
        LOCAL_INVISIBLE = JavaStaticField("J")
        PACKAGE_NAME = JavaStaticField("Ljava/lang/String;")
        PHOTO_SUPPORT = JavaStaticField("Ljava/lang/String;")
        PHOTO_SUPPORT_FULL = JavaStaticField("I")
        PHOTO_SUPPORT_FULL_SIZE_ONLY = JavaStaticField("I")
        PHOTO_SUPPORT_NONE = JavaStaticField("I")
        PHOTO_SUPPORT_THUMBNAIL_ONLY = JavaStaticField("I")
        SHORTCUT_SUPPORT = JavaStaticField("Ljava/lang/String;")
        SHORTCUT_SUPPORT_DATA_ITEMS_ONLY = JavaStaticField("I")
        SHORTCUT_SUPPORT_FULL = JavaStaticField("I")
        SHORTCUT_SUPPORT_NONE = JavaStaticField("I")
        TYPE_RESOURCE_ID = JavaStaticField("Ljava/lang/String;")
        isRemoteDirectoryId = JavaStaticMethod("(J)Z")
        isEnterpriseDirectoryId = JavaStaticMethod("(J)Z")
        notifyDirectoryChange = JavaStaticMethod("(Landroid/content/ContentResolver;)V")

    class DisplayNameSources(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/DisplayNameSources"
        EMAIL = JavaStaticField("I")
        NICKNAME = JavaStaticField("I")
        ORGANIZATION = JavaStaticField("I")
        PHONE = JavaStaticField("I")
        STRUCTURED_NAME = JavaStaticField("I")
        STRUCTURED_PHONETIC_NAME = JavaStaticField("I")
        UNDEFINED = JavaStaticField("I")

    class DisplayPhoto(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/DisplayPhoto"
        CONTENT_MAX_DIMENSIONS_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DISPLAY_MAX_DIM = JavaStaticField("Ljava/lang/String;")
        THUMBNAIL_MAX_DIM = JavaStaticField("Ljava/lang/String;")

    class FullNameStyle(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/FullNameStyle"
        CHINESE = JavaStaticField("I")
        CJK = JavaStaticField("I")
        JAPANESE = JavaStaticField("I")
        KOREAN = JavaStaticField("I")
        UNDEFINED = JavaStaticField("I")
        WESTERN = JavaStaticField("I")

    class Groups(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/Groups"
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_SUMMARY_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        newEntityIterator = JavaStaticMethod("(Landroid/database/Cursor;)Landroid/content/EntityIterator;")

    class GroupsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/GroupsColumns"
        AUTO_ADD = JavaStaticField("Ljava/lang/String;")
        DATA_SET = JavaStaticField("Ljava/lang/String;")
        DELETED = JavaStaticField("Ljava/lang/String;")
        FAVORITES = JavaStaticField("Ljava/lang/String;")
        GROUP_IS_READ_ONLY = JavaStaticField("Ljava/lang/String;")
        GROUP_VISIBLE = JavaStaticField("Ljava/lang/String;")
        NOTES = JavaStaticField("Ljava/lang/String;")
        RES_PACKAGE = JavaStaticField("Ljava/lang/String;")
        SHOULD_SYNC = JavaStaticField("Ljava/lang/String;")
        SUMMARY_COUNT = JavaStaticField("Ljava/lang/String;")
        SUMMARY_WITH_PHONES = JavaStaticField("Ljava/lang/String;")
        SYSTEM_ID = JavaStaticField("Ljava/lang/String;")
        TITLE = JavaStaticField("Ljava/lang/String;")
        TITLE_RES = JavaStaticField("Ljava/lang/String;")

    class Intents(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/Intents"
        __javaconstructor__ = [("()V", False)]
        ACTION_VOICE_SEND_MESSAGE_TO_CONTACTS = JavaStaticField("Ljava/lang/String;")
        ATTACH_IMAGE = JavaStaticField("Ljava/lang/String;")
        CONTACTS_DATABASE_CREATED = JavaStaticField("Ljava/lang/String;")
        EXTRA_CREATE_DESCRIPTION = JavaStaticField("Ljava/lang/String;")
        EXTRA_FORCE_CREATE = JavaStaticField("Ljava/lang/String;")
        EXTRA_RECIPIENT_CONTACT_CHAT_ID = JavaStaticField("Ljava/lang/String;")
        EXTRA_RECIPIENT_CONTACT_NAME = JavaStaticField("Ljava/lang/String;")
        EXTRA_RECIPIENT_CONTACT_URI = JavaStaticField("Ljava/lang/String;")
        INVITE_CONTACT = JavaStaticField("Ljava/lang/String;")
        METADATA_ACCOUNT_TYPE = JavaStaticField("Ljava/lang/String;")
        METADATA_MIMETYPE = JavaStaticField("Ljava/lang/String;")
        SEARCH_SUGGESTION_CLICKED = JavaStaticField("Ljava/lang/String;")
        SEARCH_SUGGESTION_CREATE_CONTACT_CLICKED = JavaStaticField("Ljava/lang/String;")
        SEARCH_SUGGESTION_DIAL_NUMBER_CLICKED = JavaStaticField("Ljava/lang/String;")
        SHOW_OR_CREATE_CONTACT = JavaStaticField("Ljava/lang/String;")

        class Insert(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/Intents/Insert"
            __javaconstructor__ = [("()V", False)]
            ACTION = JavaStaticField("Ljava/lang/String;")
            COMPANY = JavaStaticField("Ljava/lang/String;")
            DATA = JavaStaticField("Ljava/lang/String;")
            EMAIL = JavaStaticField("Ljava/lang/String;")
            EMAIL_ISPRIMARY = JavaStaticField("Ljava/lang/String;")
            EMAIL_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTRA_ACCOUNT = JavaStaticField("Ljava/lang/String;")
            EXTRA_DATA_SET = JavaStaticField("Ljava/lang/String;")
            FULL_MODE = JavaStaticField("Ljava/lang/String;")
            IM_HANDLE = JavaStaticField("Ljava/lang/String;")
            IM_ISPRIMARY = JavaStaticField("Ljava/lang/String;")
            IM_PROTOCOL = JavaStaticField("Ljava/lang/String;")
            JOB_TITLE = JavaStaticField("Ljava/lang/String;")
            NAME = JavaStaticField("Ljava/lang/String;")
            NOTES = JavaStaticField("Ljava/lang/String;")
            PHONE = JavaStaticField("Ljava/lang/String;")
            PHONETIC_NAME = JavaStaticField("Ljava/lang/String;")
            PHONE_ISPRIMARY = JavaStaticField("Ljava/lang/String;")
            PHONE_TYPE = JavaStaticField("Ljava/lang/String;")
            POSTAL = JavaStaticField("Ljava/lang/String;")
            POSTAL_ISPRIMARY = JavaStaticField("Ljava/lang/String;")
            POSTAL_TYPE = JavaStaticField("Ljava/lang/String;")
            SECONDARY_EMAIL = JavaStaticField("Ljava/lang/String;")
            SECONDARY_EMAIL_TYPE = JavaStaticField("Ljava/lang/String;")
            SECONDARY_PHONE = JavaStaticField("Ljava/lang/String;")
            SECONDARY_PHONE_TYPE = JavaStaticField("Ljava/lang/String;")
            TERTIARY_EMAIL = JavaStaticField("Ljava/lang/String;")
            TERTIARY_EMAIL_TYPE = JavaStaticField("Ljava/lang/String;")
            TERTIARY_PHONE = JavaStaticField("Ljava/lang/String;")
            TERTIARY_PHONE_TYPE = JavaStaticField("Ljava/lang/String;")

    class PhoneLookup(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/PhoneLookup"
        CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
        ENTERPRISE_CONTENT_FILTER_URI = JavaStaticField("Landroid/net/Uri;")
        QUERY_PARAMETER_SIP_ADDRESS = JavaStaticField("Ljava/lang/String;")

    class PhoneLookupColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/PhoneLookupColumns"
        CONTACT_ID = JavaStaticField("Ljava/lang/String;")
        DATA_ID = JavaStaticField("Ljava/lang/String;")
        LABEL = JavaStaticField("Ljava/lang/String;")
        NORMALIZED_NUMBER = JavaStaticField("Ljava/lang/String;")
        NUMBER = JavaStaticField("Ljava/lang/String;")
        TYPE = JavaStaticField("Ljava/lang/String;")

    class PhoneticNameStyle(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/PhoneticNameStyle"
        JAPANESE = JavaStaticField("I")
        KOREAN = JavaStaticField("I")
        PINYIN = JavaStaticField("I")
        UNDEFINED = JavaStaticField("I")

    class PinnedPositions(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/PinnedPositions"
        __javaconstructor__ = [("()V", False)]
        DEMOTED = JavaStaticField("I")
        UNPINNED = JavaStaticField("I")
        undemote = JavaStaticMethod("(Landroid/content/ContentResolver;J)V")
        pin = JavaStaticMethod("(Landroid/content/ContentResolver;JI)V")

    class Presence(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/Presence"
        __javaconstructor__ = [("()V", False)]

    class PresenceColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/PresenceColumns"
        CUSTOM_PROTOCOL = JavaStaticField("Ljava/lang/String;")
        DATA_ID = JavaStaticField("Ljava/lang/String;")
        IM_ACCOUNT = JavaStaticField("Ljava/lang/String;")
        IM_HANDLE = JavaStaticField("Ljava/lang/String;")
        PROTOCOL = JavaStaticField("Ljava/lang/String;")

    class Profile(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/Profile"
        CONTENT_RAW_CONTACTS_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        CONTENT_VCARD_URI = JavaStaticField("Landroid/net/Uri;")
        MIN_ID = JavaStaticField("J")

    class ProfileSyncState(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/ProfileSyncState"
        CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        get = JavaStaticMethod("(Landroid/content/ContentProviderClient;Landroid/accounts/Account;)[B")
        getWithUri = JavaStaticMethod("(Landroid/content/ContentProviderClient;Landroid/accounts/Account;)Landroid/util/Pair;")
        set = JavaStaticMethod("(Landroid/content/ContentProviderClient;Landroid/accounts/Account;[B)V")
        newSetOperation = JavaStaticMethod("(Landroid/accounts/Account;[B)Landroid/content/ContentProviderOperation;")

    class ProviderStatus(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/ProviderStatus"
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DATABASE_CREATION_TIMESTAMP = JavaStaticField("Ljava/lang/String;")
        STATUS = JavaStaticField("Ljava/lang/String;")
        STATUS_BUSY = JavaStaticField("I")
        STATUS_EMPTY = JavaStaticField("I")
        STATUS_NORMAL = JavaStaticField("I")

    class QuickContact(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/QuickContact"
        __javaconstructor__ = [("()V", False)]
        ACTION_QUICK_CONTACT = JavaStaticField("Ljava/lang/String;")
        EXTRA_EXCLUDE_MIMES = JavaStaticField("Ljava/lang/String;")
        EXTRA_MODE = JavaStaticField("Ljava/lang/String;")
        EXTRA_PRIORITIZED_MIMETYPE = JavaStaticField("Ljava/lang/String;")
        MODE_LARGE = JavaStaticField("I")
        MODE_MEDIUM = JavaStaticField("I")
        MODE_SMALL = JavaStaticField("I")
        showQuickContact = JavaMultipleMethod([("(Landroid/content/Context;Landroid/view/View;Landroid/net/Uri;I[Ljava/lang/String;)V", True, False), ("(Landroid/content/Context;Landroid/graphics/Rect;Landroid/net/Uri;I[Ljava/lang/String;)V", True, False), ("(Landroid/content/Context;Landroid/view/View;Landroid/net/Uri;[Ljava/lang/String;Ljava/lang/String;)V", True, False), ("(Landroid/content/Context;Landroid/graphics/Rect;Landroid/net/Uri;[Ljava/lang/String;Ljava/lang/String;)V", True, False)])

    class RawContacts(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/RawContacts"
        AGGREGATION_MODE_DEFAULT = JavaStaticField("I")
        AGGREGATION_MODE_DISABLED = JavaStaticField("I")
        AGGREGATION_MODE_IMMEDIATE = JavaStaticField("I")
        AGGREGATION_MODE_SUSPENDED = JavaStaticField("I")
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        getContactLookupUri = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;)Landroid/net/Uri;")
        getLocalAccountName = JavaStaticMethod("(Landroid/content/Context;)Ljava/lang/String;")
        getLocalAccountType = JavaStaticMethod("(Landroid/content/Context;)Ljava/lang/String;")
        newEntityIterator = JavaStaticMethod("(Landroid/database/Cursor;)Landroid/content/EntityIterator;")

        class Data(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/RawContacts/Data"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")

        class DisplayPhoto(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/RawContacts/DisplayPhoto"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")

        class Entity(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/ContactsContract/RawContacts/Entity"
            CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
            DATA_ID = JavaStaticField("Ljava/lang/String;")

    class RawContactsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/RawContactsColumns"
        ACCOUNT_TYPE_AND_DATA_SET = JavaStaticField("Ljava/lang/String;")
        AGGREGATION_MODE = JavaStaticField("Ljava/lang/String;")
        BACKUP_ID = JavaStaticField("Ljava/lang/String;")
        CONTACT_ID = JavaStaticField("Ljava/lang/String;")
        DATA_SET = JavaStaticField("Ljava/lang/String;")
        DELETED = JavaStaticField("Ljava/lang/String;")
        METADATA_DIRTY = JavaStaticField("Ljava/lang/String;")
        RAW_CONTACT_IS_READ_ONLY = JavaStaticField("Ljava/lang/String;")
        RAW_CONTACT_IS_USER_PROFILE = JavaStaticField("Ljava/lang/String;")

    class RawContactsEntity(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/RawContactsEntity"
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        DATA_ID = JavaStaticField("Ljava/lang/String;")
        PROFILE_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")

    class SearchSnippets(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/SearchSnippets"
        __javaconstructor__ = [("()V", False)]
        DEFERRED_SNIPPETING_KEY = JavaStaticField("Ljava/lang/String;")
        SNIPPET = JavaStaticField("Ljava/lang/String;")

    class Settings(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/Settings"
        ACTION_SET_DEFAULT_ACCOUNT = JavaStaticField("Ljava/lang/String;")
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        getDefaultAccount = JavaStaticMethod("(Landroid/content/ContentResolver;)Landroid/accounts/Account;")

    class SettingsColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/SettingsColumns"
        ACCOUNT_NAME = JavaStaticField("Ljava/lang/String;")
        ACCOUNT_TYPE = JavaStaticField("Ljava/lang/String;")
        ANY_UNSYNCED = JavaStaticField("Ljava/lang/String;")
        DATA_SET = JavaStaticField("Ljava/lang/String;")
        SHOULD_SYNC = JavaStaticField("Ljava/lang/String;")
        UNGROUPED_COUNT = JavaStaticField("Ljava/lang/String;")
        UNGROUPED_VISIBLE = JavaStaticField("Ljava/lang/String;")
        UNGROUPED_WITH_PHONES = JavaStaticField("Ljava/lang/String;")

    class SimAccount(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/SimAccount"
        ADN_EF_TYPE = JavaStaticField("I")
        CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
        FDN_EF_TYPE = JavaStaticField("I")
        SDN_EF_TYPE = JavaStaticField("I")
        UNKNOWN_EF_TYPE = JavaStaticField("I")
        getAccountName = JavaMethod("()Ljava/lang/String;")
        getAccountType = JavaMethod("()Ljava/lang/String;")
        getSimSlotIndex = JavaMethod("()I")
        getEfType = JavaMethod("()I")
        hashCode = JavaMethod("()I")
        equals = JavaMethod("(Ljava/lang/Object;)Z")
        writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
        describeContents = JavaMethod("()I")

    class SimContacts(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/SimContacts"
        ACTION_SIM_ACCOUNTS_CHANGED = JavaStaticField("Ljava/lang/String;")
        getSimAccounts = JavaStaticMethod("(Landroid/content/ContentResolver;)Ljava/util/List;")

    class StatusColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/StatusColumns"
        AVAILABLE = JavaStaticField("I")
        AWAY = JavaStaticField("I")
        CAPABILITY_HAS_CAMERA = JavaStaticField("I")
        CAPABILITY_HAS_VIDEO = JavaStaticField("I")
        CAPABILITY_HAS_VOICE = JavaStaticField("I")
        CHAT_CAPABILITY = JavaStaticField("Ljava/lang/String;")
        DO_NOT_DISTURB = JavaStaticField("I")
        IDLE = JavaStaticField("I")
        INVISIBLE = JavaStaticField("I")
        OFFLINE = JavaStaticField("I")
        PRESENCE = JavaStaticField("Ljava/lang/String;")
        PRESENCE_CUSTOM_STATUS = JavaStaticField("Ljava/lang/String;")
        PRESENCE_STATUS = JavaStaticField("Ljava/lang/String;")
        STATUS = JavaStaticField("Ljava/lang/String;")
        STATUS_ICON = JavaStaticField("Ljava/lang/String;")
        STATUS_LABEL = JavaStaticField("Ljava/lang/String;")
        STATUS_RES_PACKAGE = JavaStaticField("Ljava/lang/String;")
        STATUS_TIMESTAMP = JavaStaticField("Ljava/lang/String;")

    class StatusUpdates(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/StatusUpdates"
        CONTENT_ITEM_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        PROFILE_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        getPresenceIconResourceId = JavaStaticMethod("(I)I")
        getPresencePrecedence = JavaStaticMethod("(I)I")

    class SyncColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/SyncColumns"
        ACCOUNT_NAME = JavaStaticField("Ljava/lang/String;")
        ACCOUNT_TYPE = JavaStaticField("Ljava/lang/String;")
        DIRTY = JavaStaticField("Ljava/lang/String;")
        SOURCE_ID = JavaStaticField("Ljava/lang/String;")
        VERSION = JavaStaticField("Ljava/lang/String;")

    class SyncState(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/ContactsContract/SyncState"
        CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
        CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        get = JavaStaticMethod("(Landroid/content/ContentProviderClient;Landroid/accounts/Account;)[B")
        getWithUri = JavaStaticMethod("(Landroid/content/ContentProviderClient;Landroid/accounts/Account;)Landroid/util/Pair;")
        set = JavaStaticMethod("(Landroid/content/ContentProviderClient;Landroid/accounts/Account;[B)V")
        newSetOperation = JavaStaticMethod("(Landroid/accounts/Account;[B)Landroid/content/ContentProviderOperation;")