from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["MediaStore"]

class MediaStore(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/provider/MediaStore"
    __javaconstructor__ = [("()V", False)]
    ACCESS_MEDIA_OWNER_PACKAGE_NAME_PERMISSION = JavaStaticField("Ljava/lang/String;")
    ACTION_IMAGE_CAPTURE = JavaStaticField("Ljava/lang/String;")
    ACTION_IMAGE_CAPTURE_SECURE = JavaStaticField("Ljava/lang/String;")
    ACTION_PICK_IMAGES = JavaStaticField("Ljava/lang/String;")
    ACTION_PICK_IMAGES_SETTINGS = JavaStaticField("Ljava/lang/String;")
    ACTION_REVIEW = JavaStaticField("Ljava/lang/String;")
    ACTION_REVIEW_SECURE = JavaStaticField("Ljava/lang/String;")
    ACTION_VIDEO_CAPTURE = JavaStaticField("Ljava/lang/String;")
    AUTHORITY = JavaStaticField("Ljava/lang/String;")
    AUTHORITY_URI = JavaStaticField("Landroid/net/Uri;")
    EXTRA_ACCEPT_ORIGINAL_MEDIA_FORMAT = JavaStaticField("Ljava/lang/String;")
    EXTRA_BRIGHTNESS = JavaStaticField("Ljava/lang/String;")
    EXTRA_DURATION_LIMIT = JavaStaticField("Ljava/lang/String;")
    EXTRA_FINISH_ON_COMPLETION = JavaStaticField("Ljava/lang/String;")
    EXTRA_FULL_SCREEN = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_ALBUM = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_ARTIST = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_CAPABILITIES = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_CAPABILITIES_UID = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_FOCUS = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_GENRE = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_PLAYLIST = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_RADIO_CHANNEL = JavaStaticField("Ljava/lang/String;")
    EXTRA_MEDIA_TITLE = JavaStaticField("Ljava/lang/String;")
    EXTRA_OUTPUT = JavaStaticField("Ljava/lang/String;")
    EXTRA_PICK_IMAGES_ACCENT_COLOR = JavaStaticField("Ljava/lang/String;")
    EXTRA_PICK_IMAGES_IN_ORDER = JavaStaticField("Ljava/lang/String;")
    EXTRA_PICK_IMAGES_LAUNCH_TAB = JavaStaticField("Ljava/lang/String;")
    EXTRA_PICK_IMAGES_MAX = JavaStaticField("Ljava/lang/String;")
    EXTRA_SCREEN_ORIENTATION = JavaStaticField("Ljava/lang/String;")
    EXTRA_SHOW_ACTION_ICONS = JavaStaticField("Ljava/lang/String;")
    EXTRA_SIZE_LIMIT = JavaStaticField("Ljava/lang/String;")
    EXTRA_VIDEO_QUALITY = JavaStaticField("Ljava/lang/String;")
    INTENT_ACTION_MEDIA_PLAY_FROM_SEARCH = JavaStaticField("Ljava/lang/String;")
    INTENT_ACTION_MEDIA_SEARCH = JavaStaticField("Ljava/lang/String;")
    INTENT_ACTION_MUSIC_PLAYER = JavaStaticField("Ljava/lang/String;")
    INTENT_ACTION_STILL_IMAGE_CAMERA = JavaStaticField("Ljava/lang/String;")
    INTENT_ACTION_STILL_IMAGE_CAMERA_SECURE = JavaStaticField("Ljava/lang/String;")
    INTENT_ACTION_TEXT_OPEN_FROM_SEARCH = JavaStaticField("Ljava/lang/String;")
    INTENT_ACTION_VIDEO_CAMERA = JavaStaticField("Ljava/lang/String;")
    INTENT_ACTION_VIDEO_PLAY_FROM_SEARCH = JavaStaticField("Ljava/lang/String;")
    MATCH_DEFAULT = JavaStaticField("I")
    MATCH_EXCLUDE = JavaStaticField("I")
    MATCH_INCLUDE = JavaStaticField("I")
    MATCH_ONLY = JavaStaticField("I")
    MEDIA_IGNORE_FILENAME = JavaStaticField("Ljava/lang/String;")
    MEDIA_SCANNER_VOLUME = JavaStaticField("Ljava/lang/String;")
    META_DATA_REVIEW_GALLERY_PREWARM_SERVICE = JavaStaticField("Ljava/lang/String;")
    META_DATA_STILL_IMAGE_CAMERA_PREWARM_SERVICE = JavaStaticField("Ljava/lang/String;")
    PICK_IMAGES_TAB_ALBUMS = JavaStaticField("I")
    PICK_IMAGES_TAB_IMAGES = JavaStaticField("I")
    QUERY_ARG_INCLUDE_RECENTLY_UNMOUNTED_VOLUMES = JavaStaticField("Ljava/lang/String;")
    QUERY_ARG_LATEST_SELECTION_ONLY = JavaStaticField("Ljava/lang/String;")
    QUERY_ARG_MATCH_FAVORITE = JavaStaticField("Ljava/lang/String;")
    QUERY_ARG_MATCH_PENDING = JavaStaticField("Ljava/lang/String;")
    QUERY_ARG_MATCH_TRASHED = JavaStaticField("Ljava/lang/String;")
    QUERY_ARG_RELATED_URI = JavaStaticField("Ljava/lang/String;")
    UNKNOWN_STRING = JavaStaticField("Ljava/lang/String;")
    VOLUME_EXTERNAL = JavaStaticField("Ljava/lang/String;")
    VOLUME_EXTERNAL_PRIMARY = JavaStaticField("Ljava/lang/String;")
    VOLUME_INTERNAL = JavaStaticField("Ljava/lang/String;")
    getPickImagesMaxLimit = JavaStaticMethod("()I")
    setIncludePending = JavaStaticMethod("(Landroid/net/Uri;)Landroid/net/Uri;")
    setRequireOriginal = JavaStaticMethod("(Landroid/net/Uri;)Landroid/net/Uri;")
    getRequireOriginal = JavaStaticMethod("(Landroid/net/Uri;)Z")
    getOriginalMediaFormatFileDescriptor = JavaStaticMethod("(Landroid/content/Context;Landroid/os/ParcelFileDescriptor;)Landroid/os/ParcelFileDescriptor;")
    createWriteRequest = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/util/Collection;)Landroid/app/PendingIntent;")
    createTrashRequest = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/util/Collection;Z)Landroid/app/PendingIntent;")
    createFavoriteRequest = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/util/Collection;Z)Landroid/app/PendingIntent;")
    createDeleteRequest = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/util/Collection;)Landroid/app/PendingIntent;")
    getExternalVolumeNames = JavaStaticMethod("(Landroid/content/Context;)Ljava/util/Set;")
    getRecentExternalVolumeNames = JavaStaticMethod("(Landroid/content/Context;)Ljava/util/Set;")
    getVolumeName = JavaStaticMethod("(Landroid/net/Uri;)Ljava/lang/String;")
    getMediaScannerUri = JavaStaticMethod("()Landroid/net/Uri;")
    getVersion = JavaMultipleMethod([("(Landroid/content/Context;)Ljava/lang/String;", True, False), ("(Landroid/content/Context;Ljava/lang/String;)Ljava/lang/String;", True, False)])
    getGeneration = JavaStaticMethod("(Landroid/content/Context;Ljava/lang/String;)J")
    getDocumentUri = JavaStaticMethod("(Landroid/content/Context;Landroid/net/Uri;)Landroid/net/Uri;")
    getMediaUri = JavaStaticMethod("(Landroid/content/Context;Landroid/net/Uri;)Landroid/net/Uri;")
    isCurrentSystemGallery = JavaStaticMethod("(Landroid/content/ContentResolver;ILjava/lang/String;)Z")
    getRedactedUri = JavaMultipleMethod([("(Landroid/content/ContentResolver;Landroid/net/Uri;)Landroid/net/Uri;", True, False), ("(Landroid/content/ContentResolver;Ljava/util/List;)Ljava/util/List;", True, False)])
    canManageMedia = JavaStaticMethod("(Landroid/content/Context;)Z")
    isCurrentCloudMediaProviderAuthority = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/lang/String;)Z")
    isSupportedCloudMediaProviderAuthority = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/lang/String;)Z")
    notifyCloudMediaChangedEvent = JavaStaticMethod("(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;)V")

    class Audio(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/MediaStore/Audio"
        __javaconstructor__ = [("()V", False)]
        keyFor = JavaStaticMethod("(Ljava/lang/String;)Ljava/lang/String;")

        class AlbumColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/AlbumColumns"
            ALBUM = JavaStaticField("Ljava/lang/String;")
            ALBUM_ART = JavaStaticField("Ljava/lang/String;")
            ALBUM_ID = JavaStaticField("Ljava/lang/String;")
            ALBUM_KEY = JavaStaticField("Ljava/lang/String;")
            ARTIST = JavaStaticField("Ljava/lang/String;")
            ARTIST_ID = JavaStaticField("Ljava/lang/String;")
            ARTIST_KEY = JavaStaticField("Ljava/lang/String;")
            FIRST_YEAR = JavaStaticField("Ljava/lang/String;")
            LAST_YEAR = JavaStaticField("Ljava/lang/String;")
            NUMBER_OF_SONGS = JavaStaticField("Ljava/lang/String;")
            NUMBER_OF_SONGS_FOR_ARTIST = JavaStaticField("Ljava/lang/String;")

        class Albums(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/Albums"
            __javaconstructor__ = [("()V", False)]
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            ENTRY_CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            getContentUri = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/Uri;")

        class ArtistColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/ArtistColumns"
            ARTIST = JavaStaticField("Ljava/lang/String;")
            ARTIST_KEY = JavaStaticField("Ljava/lang/String;")
            NUMBER_OF_ALBUMS = JavaStaticField("Ljava/lang/String;")
            NUMBER_OF_TRACKS = JavaStaticField("Ljava/lang/String;")

        class Artists(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/Artists"
            __javaconstructor__ = [("()V", False)]
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            ENTRY_CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            getContentUri = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/Uri;")

            class Albums(JavaClass, metaclass=MetaJavaClass):
                __javaclass__ = "android/provider/MediaStore/Audio/Artists/Albums"
                __javaconstructor__ = [("()V", False)]
                getContentUri = JavaStaticMethod("(Ljava/lang/String;J)Landroid/net/Uri;")

        class AudioColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/AudioColumns"
            ALBUM_ID = JavaStaticField("Ljava/lang/String;")
            ALBUM_KEY = JavaStaticField("Ljava/lang/String;")
            ARTIST_ID = JavaStaticField("Ljava/lang/String;")
            ARTIST_KEY = JavaStaticField("Ljava/lang/String;")
            BOOKMARK = JavaStaticField("Ljava/lang/String;")
            GENRE = JavaStaticField("Ljava/lang/String;")
            GENRE_ID = JavaStaticField("Ljava/lang/String;")
            GENRE_KEY = JavaStaticField("Ljava/lang/String;")
            IS_ALARM = JavaStaticField("Ljava/lang/String;")
            IS_AUDIOBOOK = JavaStaticField("Ljava/lang/String;")
            IS_MUSIC = JavaStaticField("Ljava/lang/String;")
            IS_NOTIFICATION = JavaStaticField("Ljava/lang/String;")
            IS_PODCAST = JavaStaticField("Ljava/lang/String;")
            IS_RECORDING = JavaStaticField("Ljava/lang/String;")
            IS_RINGTONE = JavaStaticField("Ljava/lang/String;")
            TITLE_KEY = JavaStaticField("Ljava/lang/String;")
            TITLE_RESOURCE_URI = JavaStaticField("Ljava/lang/String;")
            TRACK = JavaStaticField("Ljava/lang/String;")
            YEAR = JavaStaticField("Ljava/lang/String;")

        class Genres(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/Genres"
            __javaconstructor__ = [("()V", False)]
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            ENTRY_CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            getContentUri = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/Uri;")
            getContentUriForAudioId = JavaStaticMethod("(Ljava/lang/String;I)Landroid/net/Uri;")

            class Members(JavaClass, metaclass=MetaJavaClass):
                __javaclass__ = "android/provider/MediaStore/Audio/Genres/Members"
                __javaconstructor__ = [("()V", False)]
                AUDIO_ID = JavaStaticField("Ljava/lang/String;")
                CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
                DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
                GENRE_ID = JavaStaticField("Ljava/lang/String;")
                getContentUri = JavaStaticMethod("(Ljava/lang/String;J)Landroid/net/Uri;")

        class GenresColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/GenresColumns"
            NAME = JavaStaticField("Ljava/lang/String;")

        class Media(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/Media"
            __javaconstructor__ = [("()V", False)]
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            ENTRY_CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            EXTRA_MAX_BYTES = JavaStaticField("Ljava/lang/String;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            RECORD_SOUND_ACTION = JavaStaticField("Ljava/lang/String;")
            getContentUri = JavaMultipleMethod([("(Ljava/lang/String;)Landroid/net/Uri;", True, False), ("(Ljava/lang/String;J)Landroid/net/Uri;", True, False)])
            getContentUriForPath = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/Uri;")

        class Playlists(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/Playlists"
            __javaconstructor__ = [("()V", False)]
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            ENTRY_CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            getContentUri = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/Uri;")

            class Members(JavaClass, metaclass=MetaJavaClass):
                __javaclass__ = "android/provider/MediaStore/Audio/Playlists/Members"
                __javaconstructor__ = [("()V", False)]
                AUDIO_ID = JavaStaticField("Ljava/lang/String;")
                CONTENT_DIRECTORY = JavaStaticField("Ljava/lang/String;")
                DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
                PLAYLIST_ID = JavaStaticField("Ljava/lang/String;")
                PLAY_ORDER = JavaStaticField("Ljava/lang/String;")
                _ID = JavaStaticField("Ljava/lang/String;")
                getContentUri = JavaStaticMethod("(Ljava/lang/String;J)Landroid/net/Uri;")
                moveItem = JavaStaticMethod("(Landroid/content/ContentResolver;JII)Z")

        class PlaylistsColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/PlaylistsColumns"
            DATA = JavaStaticField("Ljava/lang/String;")
            DATE_ADDED = JavaStaticField("Ljava/lang/String;")
            DATE_MODIFIED = JavaStaticField("Ljava/lang/String;")
            NAME = JavaStaticField("Ljava/lang/String;")

        class Radio(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Audio/Radio"
            ENTRY_CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")

    class DownloadColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/MediaStore/DownloadColumns"
        DOWNLOAD_URI = JavaStaticField("Ljava/lang/String;")
        REFERER_URI = JavaStaticField("Ljava/lang/String;")

    class Downloads(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/MediaStore/Downloads"
        CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
        EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
        getContentUri = JavaMultipleMethod([("(Ljava/lang/String;)Landroid/net/Uri;", True, False), ("(Ljava/lang/String;J)Landroid/net/Uri;", True, False)])

    class Files(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/MediaStore/Files"
        __javaconstructor__ = [("()V", False)]
        getContentUri = JavaMultipleMethod([("(Ljava/lang/String;)Landroid/net/Uri;", True, False), ("(Ljava/lang/String;J)Landroid/net/Uri;", True, False)])

        class FileColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Files/FileColumns"
            MEDIA_TYPE = JavaStaticField("Ljava/lang/String;")
            MEDIA_TYPE_AUDIO = JavaStaticField("I")
            MEDIA_TYPE_DOCUMENT = JavaStaticField("I")
            MEDIA_TYPE_IMAGE = JavaStaticField("I")
            MEDIA_TYPE_NONE = JavaStaticField("I")
            MEDIA_TYPE_PLAYLIST = JavaStaticField("I")
            MEDIA_TYPE_SUBTITLE = JavaStaticField("I")
            MEDIA_TYPE_VIDEO = JavaStaticField("I")
            MIME_TYPE = JavaStaticField("Ljava/lang/String;")
            PARENT = JavaStaticField("Ljava/lang/String;")

    class Images(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/MediaStore/Images"
        __javaconstructor__ = [("()V", False)]

        class ImageColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Images/ImageColumns"
            DESCRIPTION = JavaStaticField("Ljava/lang/String;")
            EXPOSURE_TIME = JavaStaticField("Ljava/lang/String;")
            F_NUMBER = JavaStaticField("Ljava/lang/String;")
            ISO = JavaStaticField("Ljava/lang/String;")
            IS_PRIVATE = JavaStaticField("Ljava/lang/String;")
            LATITUDE = JavaStaticField("Ljava/lang/String;")
            LONGITUDE = JavaStaticField("Ljava/lang/String;")
            MINI_THUMB_MAGIC = JavaStaticField("Ljava/lang/String;")
            PICASA_ID = JavaStaticField("Ljava/lang/String;")
            SCENE_CAPTURE_TYPE = JavaStaticField("Ljava/lang/String;")

        class Media(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Images/Media"
            __javaconstructor__ = [("()V", False)]
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            query = JavaMultipleMethod([("(Landroid/content/ContentResolver;Landroid/net/Uri;[Ljava/lang/String;)Landroid/database/Cursor;", True, False), ("(Landroid/content/ContentResolver;Landroid/net/Uri;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;", True, False), ("(Landroid/content/ContentResolver;Landroid/net/Uri;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;", True, False)])
            getBitmap = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;)Landroid/graphics/Bitmap;")
            insertImage = JavaMultipleMethod([("(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", True, False), ("(Landroid/content/ContentResolver;Landroid/graphics/Bitmap;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", True, False)])
            getContentUri = JavaMultipleMethod([("(Ljava/lang/String;)Landroid/net/Uri;", True, False), ("(Ljava/lang/String;J)Landroid/net/Uri;", True, False)])

        class Thumbnails(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Images/Thumbnails"
            __javaconstructor__ = [("()V", False)]
            DATA = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            FULL_SCREEN_KIND = JavaStaticField("I")
            HEIGHT = JavaStaticField("Ljava/lang/String;")
            IMAGE_ID = JavaStaticField("Ljava/lang/String;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            KIND = JavaStaticField("Ljava/lang/String;")
            MICRO_KIND = JavaStaticField("I")
            MINI_KIND = JavaStaticField("I")
            THUMB_DATA = JavaStaticField("Ljava/lang/String;")
            WIDTH = JavaStaticField("Ljava/lang/String;")
            query = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;[Ljava/lang/String;)Landroid/database/Cursor;")
            queryMiniThumbnails = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;I[Ljava/lang/String;)Landroid/database/Cursor;")
            queryMiniThumbnail = JavaStaticMethod("(Landroid/content/ContentResolver;JI[Ljava/lang/String;)Landroid/database/Cursor;")
            cancelThumbnailRequest = JavaMultipleMethod([("(Landroid/content/ContentResolver;J)V", True, False), ("(Landroid/content/ContentResolver;JJ)V", True, False)])
            getThumbnail = JavaMultipleMethod([("(Landroid/content/ContentResolver;JILandroid/graphics/BitmapFactory$Options;)Landroid/graphics/Bitmap;", True, False), ("(Landroid/content/ContentResolver;JJILandroid/graphics/BitmapFactory$Options;)Landroid/graphics/Bitmap;", True, False)])
            getContentUri = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/Uri;")
            getKindSize = JavaStaticMethod("(I)Landroid/util/Size;")

    class MediaColumns(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/MediaStore/MediaColumns"
        ALBUM = JavaStaticField("Ljava/lang/String;")
        ALBUM_ARTIST = JavaStaticField("Ljava/lang/String;")
        ARTIST = JavaStaticField("Ljava/lang/String;")
        AUTHOR = JavaStaticField("Ljava/lang/String;")
        BITRATE = JavaStaticField("Ljava/lang/String;")
        BUCKET_DISPLAY_NAME = JavaStaticField("Ljava/lang/String;")
        BUCKET_ID = JavaStaticField("Ljava/lang/String;")
        CAPTURE_FRAMERATE = JavaStaticField("Ljava/lang/String;")
        CD_TRACK_NUMBER = JavaStaticField("Ljava/lang/String;")
        COMPILATION = JavaStaticField("Ljava/lang/String;")
        COMPOSER = JavaStaticField("Ljava/lang/String;")
        DATA = JavaStaticField("Ljava/lang/String;")
        DATE_ADDED = JavaStaticField("Ljava/lang/String;")
        DATE_EXPIRES = JavaStaticField("Ljava/lang/String;")
        DATE_MODIFIED = JavaStaticField("Ljava/lang/String;")
        DATE_TAKEN = JavaStaticField("Ljava/lang/String;")
        DISC_NUMBER = JavaStaticField("Ljava/lang/String;")
        DISPLAY_NAME = JavaStaticField("Ljava/lang/String;")
        DOCUMENT_ID = JavaStaticField("Ljava/lang/String;")
        DURATION = JavaStaticField("Ljava/lang/String;")
        GENERATION_ADDED = JavaStaticField("Ljava/lang/String;")
        GENERATION_MODIFIED = JavaStaticField("Ljava/lang/String;")
        GENRE = JavaStaticField("Ljava/lang/String;")
        HEIGHT = JavaStaticField("Ljava/lang/String;")
        INSTANCE_ID = JavaStaticField("Ljava/lang/String;")
        IS_DOWNLOAD = JavaStaticField("Ljava/lang/String;")
        IS_DRM = JavaStaticField("Ljava/lang/String;")
        IS_FAVORITE = JavaStaticField("Ljava/lang/String;")
        IS_PENDING = JavaStaticField("Ljava/lang/String;")
        IS_TRASHED = JavaStaticField("Ljava/lang/String;")
        MIME_TYPE = JavaStaticField("Ljava/lang/String;")
        NUM_TRACKS = JavaStaticField("Ljava/lang/String;")
        ORIENTATION = JavaStaticField("Ljava/lang/String;")
        ORIGINAL_DOCUMENT_ID = JavaStaticField("Ljava/lang/String;")
        OWNER_PACKAGE_NAME = JavaStaticField("Ljava/lang/String;")
        RELATIVE_PATH = JavaStaticField("Ljava/lang/String;")
        RESOLUTION = JavaStaticField("Ljava/lang/String;")
        SIZE = JavaStaticField("Ljava/lang/String;")
        TITLE = JavaStaticField("Ljava/lang/String;")
        VOLUME_NAME = JavaStaticField("Ljava/lang/String;")
        WIDTH = JavaStaticField("Ljava/lang/String;")
        WRITER = JavaStaticField("Ljava/lang/String;")
        XMP = JavaStaticField("Ljava/lang/String;")
        YEAR = JavaStaticField("Ljava/lang/String;")

    class PickerMediaColumns(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/MediaStore/PickerMediaColumns"
        DATA = JavaStaticField("Ljava/lang/String;")
        DATE_TAKEN = JavaStaticField("Ljava/lang/String;")
        DISPLAY_NAME = JavaStaticField("Ljava/lang/String;")
        DURATION_MILLIS = JavaStaticField("Ljava/lang/String;")
        HEIGHT = JavaStaticField("Ljava/lang/String;")
        MIME_TYPE = JavaStaticField("Ljava/lang/String;")
        ORIENTATION = JavaStaticField("Ljava/lang/String;")
        SIZE = JavaStaticField("Ljava/lang/String;")
        WIDTH = JavaStaticField("Ljava/lang/String;")

    class Video(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/provider/MediaStore/Video"
        __javaconstructor__ = [("()V", False)]
        DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
        query = JavaStaticMethod("(Landroid/content/ContentResolver;Landroid/net/Uri;[Ljava/lang/String;)Landroid/database/Cursor;")

        class Media(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Video/Media"
            __javaconstructor__ = [("()V", False)]
            CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            getContentUri = JavaMultipleMethod([("(Ljava/lang/String;)Landroid/net/Uri;", True, False), ("(Ljava/lang/String;J)Landroid/net/Uri;", True, False)])

        class Thumbnails(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Video/Thumbnails"
            __javaconstructor__ = [("()V", False)]
            DATA = JavaStaticField("Ljava/lang/String;")
            DEFAULT_SORT_ORDER = JavaStaticField("Ljava/lang/String;")
            EXTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            FULL_SCREEN_KIND = JavaStaticField("I")
            HEIGHT = JavaStaticField("Ljava/lang/String;")
            INTERNAL_CONTENT_URI = JavaStaticField("Landroid/net/Uri;")
            KIND = JavaStaticField("Ljava/lang/String;")
            MICRO_KIND = JavaStaticField("I")
            MINI_KIND = JavaStaticField("I")
            VIDEO_ID = JavaStaticField("Ljava/lang/String;")
            WIDTH = JavaStaticField("Ljava/lang/String;")
            cancelThumbnailRequest = JavaMultipleMethod([("(Landroid/content/ContentResolver;J)V", True, False), ("(Landroid/content/ContentResolver;JJ)V", True, False)])
            getThumbnail = JavaMultipleMethod([("(Landroid/content/ContentResolver;JILandroid/graphics/BitmapFactory$Options;)Landroid/graphics/Bitmap;", True, False), ("(Landroid/content/ContentResolver;JJILandroid/graphics/BitmapFactory$Options;)Landroid/graphics/Bitmap;", True, False)])
            getContentUri = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/Uri;")
            getKindSize = JavaStaticMethod("(I)Landroid/util/Size;")

        class VideoColumns(JavaInterface, metaclass=MetaJavaClass):
            __javaclass__ = "android/provider/MediaStore/Video/VideoColumns"
            BOOKMARK = JavaStaticField("Ljava/lang/String;")
            CATEGORY = JavaStaticField("Ljava/lang/String;")
            COLOR_RANGE = JavaStaticField("Ljava/lang/String;")
            COLOR_STANDARD = JavaStaticField("Ljava/lang/String;")
            COLOR_TRANSFER = JavaStaticField("Ljava/lang/String;")
            DESCRIPTION = JavaStaticField("Ljava/lang/String;")
            IS_PRIVATE = JavaStaticField("Ljava/lang/String;")
            LANGUAGE = JavaStaticField("Ljava/lang/String;")
            LATITUDE = JavaStaticField("Ljava/lang/String;")
            LONGITUDE = JavaStaticField("Ljava/lang/String;")
            MINI_THUMB_MAGIC = JavaStaticField("Ljava/lang/String;")
            TAGS = JavaStaticField("Ljava/lang/String;")