from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class VoicemailContract:
    ACTION_FETCH_VOICEMAIL: ClassVar[str]
    ACTION_NEW_VOICEMAIL: ClassVar[str]
    ACTION_SYNC_VOICEMAIL: ClassVar[str]
    AUTHORITY: ClassVar[str]
    EXTRA_PHONE_ACCOUNT_HANDLE: ClassVar[str]
    EXTRA_SELF_CHANGE: ClassVar[str]
    PARAM_KEY_SOURCE_PACKAGE: ClassVar[str]

    class Status:
        CONFIGURATION_STATE: ClassVar[str]
        CONFIGURATION_STATE_CAN_BE_CONFIGURED: ClassVar[int]
        CONFIGURATION_STATE_CONFIGURING: ClassVar[int]
        CONFIGURATION_STATE_DISABLED: ClassVar[int]
        CONFIGURATION_STATE_FAILED: ClassVar[int]
        CONFIGURATION_STATE_NOT_CONFIGURED: ClassVar[int]
        CONFIGURATION_STATE_OK: ClassVar[int]
        CONTENT_URI: ClassVar[Uri]
        DATA_CHANNEL_STATE: ClassVar[str]
        DATA_CHANNEL_STATE_BAD_CONFIGURATION: ClassVar[int]
        DATA_CHANNEL_STATE_COMMUNICATION_ERROR: ClassVar[int]
        DATA_CHANNEL_STATE_NO_CONNECTION: ClassVar[int]
        DATA_CHANNEL_STATE_NO_CONNECTION_CELLULAR_REQUIRED: ClassVar[int]
        DATA_CHANNEL_STATE_OK: ClassVar[int]
        DATA_CHANNEL_STATE_SERVER_CONNECTION_ERROR: ClassVar[int]
        DATA_CHANNEL_STATE_SERVER_ERROR: ClassVar[int]
        DIR_TYPE: ClassVar[str]
        ITEM_TYPE: ClassVar[str]
        NOTIFICATION_CHANNEL_STATE: ClassVar[str]
        NOTIFICATION_CHANNEL_STATE_MESSAGE_WAITING: ClassVar[int]
        NOTIFICATION_CHANNEL_STATE_NO_CONNECTION: ClassVar[int]
        NOTIFICATION_CHANNEL_STATE_OK: ClassVar[int]
        PHONE_ACCOUNT_COMPONENT_NAME: ClassVar[str]
        PHONE_ACCOUNT_ID: ClassVar[str]
        QUOTA_OCCUPIED: ClassVar[str]
        QUOTA_TOTAL: ClassVar[str]
        QUOTA_UNAVAILABLE: ClassVar[int]
        SETTINGS_URI: ClassVar[str]
        SOURCE_PACKAGE: ClassVar[str]
        SOURCE_TYPE: ClassVar[str]
        VOICEMAIL_ACCESS_URI: ClassVar[str]
        @staticmethod
        def buildSourceUri(arg0: str) -> Uri: ...

    class Voicemails:
        ARCHIVED: ClassVar[str]
        BACKED_UP: ClassVar[str]
        CONTENT_URI: ClassVar[Uri]
        DATE: ClassVar[str]
        DELETED: ClassVar[str]
        DIRTY: ClassVar[str]
        DIRTY_RETAIN: ClassVar[int]
        DIR_TYPE: ClassVar[str]
        DURATION: ClassVar[str]
        HAS_CONTENT: ClassVar[str]
        IS_OMTP_VOICEMAIL: ClassVar[str]
        IS_READ: ClassVar[str]
        ITEM_TYPE: ClassVar[str]
        LAST_MODIFIED: ClassVar[str]
        MIME_TYPE: ClassVar[str]
        NEW: ClassVar[str]
        NUMBER: ClassVar[str]
        PHONE_ACCOUNT_COMPONENT_NAME: ClassVar[str]
        PHONE_ACCOUNT_ID: ClassVar[str]
        RESTORED: ClassVar[str]
        SOURCE_DATA: ClassVar[str]
        SOURCE_PACKAGE: ClassVar[str]
        TRANSCRIPTION: ClassVar[str]
        @staticmethod
        def buildSourceUri(arg0: str) -> Uri: ...
