from typing import Any, ClassVar, overload
from java.nio.charset.Charset import Charset
from java.util.Iterator import Iterator

class CharsetProvider:
    def __init__(self) -> None: ...
    def charsets(self) -> Iterator: ...
    def charsetForName(self, arg0: str) -> Charset: ...
