from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator
from org.json.JSONArray import JSONArray
from org.json.JSONTokener import JSONTokener

class JSONObject:
    NULL: ClassVar[Any]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: dict) -> None: ...
    @overload
    def __init__(self, arg0: JSONTokener) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: "JSONObject", arg1: list[str]) -> None: ...
    def length(self) -> int: ...
    @overload
    def put(self, arg0: str, arg1: bool) -> "JSONObject": ...
    @overload
    def put(self, arg0: str, arg1: float) -> "JSONObject": ...
    @overload
    def put(self, arg0: str, arg1: int) -> "JSONObject": ...
    @overload
    def put(self, arg0: str, arg1: int) -> "JSONObject": ...
    @overload
    def put(self, arg0: str, arg1: Any) -> "JSONObject": ...
    def putOpt(self, arg0: str, arg1: Any) -> "JSONObject": ...
    def accumulate(self, arg0: str, arg1: Any) -> "JSONObject": ...
    def append(self, arg0: str, arg1: Any) -> "JSONObject": ...
    def remove(self, arg0: str) -> Any: ...
    def isNull(self, arg0: str) -> bool: ...
    def has(self, arg0: str) -> bool: ...
    def get(self, arg0: str) -> Any: ...
    def opt(self, arg0: str) -> Any: ...
    def getBoolean(self, arg0: str) -> bool: ...
    @overload
    def optBoolean(self, arg0: str) -> bool: ...
    @overload
    def optBoolean(self, arg0: str, arg1: bool) -> bool: ...
    def getDouble(self, arg0: str) -> float: ...
    @overload
    def optDouble(self, arg0: str) -> float: ...
    @overload
    def optDouble(self, arg0: str, arg1: float) -> float: ...
    def getInt(self, arg0: str) -> int: ...
    @overload
    def optInt(self, arg0: str) -> int: ...
    @overload
    def optInt(self, arg0: str, arg1: int) -> int: ...
    def getLong(self, arg0: str) -> int: ...
    @overload
    def optLong(self, arg0: str) -> int: ...
    @overload
    def optLong(self, arg0: str, arg1: int) -> int: ...
    def getString(self, arg0: str) -> str: ...
    @overload
    def optString(self, arg0: str) -> str: ...
    @overload
    def optString(self, arg0: str, arg1: str) -> str: ...
    def getJSONArray(self, arg0: str) -> JSONArray: ...
    def optJSONArray(self, arg0: str) -> JSONArray: ...
    def getJSONObject(self, arg0: str) -> "JSONObject": ...
    def optJSONObject(self, arg0: str) -> "JSONObject": ...
    def toJSONArray(self, arg0: JSONArray) -> JSONArray: ...
    def keys(self) -> Iterator: ...
    def names(self) -> JSONArray: ...
    @overload
    def toString(self) -> str: ...
    @overload
    def toString(self, arg0: int) -> str: ...
    @staticmethod
    def numberToString(arg0: float) -> str: ...
    @staticmethod
    def quote(arg0: str) -> str: ...
    @staticmethod
    def wrap(arg0: Any) -> Any: ...
