from typing import Any, ClassVar, overload

class EncryptedTopic:
    def __init__(self, arg0: list[int], arg1: str, arg2: list[int]) -> None: ...
    def getEncryptedTopic(self) -> list[int]: ...
    def getKeyIdentifier(self) -> str: ...
    def getEncapsulatedKey(self) -> list[int]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
