from typing import Any, ClassVar, overload

class GetTopicsRequest:
    def getAdsSdkName(self) -> str: ...
    def shouldRecordObservation(self) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setAdsSdkName(self, arg0: str) -> "Builder": ...
        def setShouldRecordObservation(self, arg0: bool) -> "Builder": ...
        def build(self) -> "GetTopicsRequest": ...
