from typing import Any, ClassVar, overload

class DocumentChangeInfo:
    def __init__(self, arg0: str, arg1: str, arg2: str, arg3: str, arg4: set) -> None: ...
    def getPackageName(self) -> str: ...
    def getDatabaseName(self) -> str: ...
    def getNamespace(self) -> str: ...
    def getSchemaName(self) -> str: ...
    def getChangedDocumentIds(self) -> set: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
