from typing import Any, ClassVar, overload

class SchemaChangeInfo:
    def __init__(self, arg0: str, arg1: str, arg2: set) -> None: ...
    def getPackageName(self) -> str: ...
    def getDatabaseName(self) -> str: ...
    def getChangedSchemaNames(self) -> set: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
