from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Rect import Rect
from android.media.PlaybackParams import PlaybackParams
from android.media.tv.TvRecordingInfo import TvRecordingInfo
from android.media.tv.TvView import TvView
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.util.AttributeSet import AttributeSet
from android.view.InputEvent import InputEvent
from android.view.KeyEvent import KeyEvent
from android.view.View import View
from java.util.concurrent.Executor import Executor

class TvInteractiveAppView:
    BI_INTERACTIVE_APP_KEY_ALIAS: ClassVar[str]
    BI_INTERACTIVE_APP_KEY_CERTIFICATE: ClassVar[str]
    BI_INTERACTIVE_APP_KEY_HTTP_ADDITIONAL_HEADERS: ClassVar[str]
    BI_INTERACTIVE_APP_KEY_HTTP_USER_AGENT: ClassVar[str]
    BI_INTERACTIVE_APP_KEY_PRIVATE_KEY: ClassVar[str]
    ERROR_KEY_METHOD_NAME: ClassVar[str]
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    def setCallback(self, arg0: Executor, arg1: "TvInteractiveAppCallback") -> None: ...
    def clearCallback(self) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onVisibilityChanged(self, arg0: View, arg1: int) -> None: ...
    def reset(self) -> None: ...
    def dispatchUnhandledInputEvent(self, arg0: InputEvent) -> bool: ...
    def onUnhandledInputEvent(self, arg0: InputEvent) -> bool: ...
    def setOnUnhandledInputEventListener(self, arg0: Executor, arg1: "OnUnhandledInputEventListener") -> None: ...
    def getOnUnhandledInputEventListener(self) -> "OnUnhandledInputEventListener": ...
    def clearOnUnhandledInputEventListener(self) -> None: ...
    def dispatchKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def prepareInteractiveApp(self, arg0: str, arg1: int) -> None: ...
    def startInteractiveApp(self) -> None: ...
    def stopInteractiveApp(self) -> None: ...
    def resetInteractiveApp(self) -> None: ...
    def sendCurrentVideoBounds(self, arg0: Rect) -> None: ...
    def sendCurrentChannelUri(self, arg0: Uri) -> None: ...
    def sendCurrentChannelLcn(self, arg0: int) -> None: ...
    def sendStreamVolume(self, arg0: float) -> None: ...
    def sendTrackInfoList(self, arg0: list) -> None: ...
    def sendCurrentTvInputId(self, arg0: str) -> None: ...
    def sendTimeShiftMode(self, arg0: int) -> None: ...
    def sendAvailableSpeeds(self, arg0: list[float]) -> None: ...
    def sendTvRecordingInfo(self, arg0: TvRecordingInfo) -> None: ...
    def sendTvRecordingInfoList(self, arg0: list) -> None: ...
    def notifyRecordingStarted(self, arg0: str, arg1: str) -> None: ...
    def notifyRecordingStopped(self, arg0: str) -> None: ...
    def sendSigningResult(self, arg0: str, arg1: list[int]) -> None: ...
    def notifyError(self, arg0: str, arg1: Bundle) -> None: ...
    def notifyTimeShiftPlaybackParams(self, arg0: PlaybackParams) -> None: ...
    def notifyTimeShiftStatusChanged(self, arg0: str, arg1: int) -> None: ...
    def notifyTimeShiftStartPositionChanged(self, arg0: str, arg1: int) -> None: ...
    def notifyTimeShiftCurrentPositionChanged(self, arg0: str, arg1: int) -> None: ...
    def notifyRecordingScheduled(self, arg0: str, arg1: str) -> None: ...
    def notifyTvMessage(self, arg0: int, arg1: Bundle) -> None: ...
    def createBiInteractiveApp(self, arg0: Uri, arg1: Bundle) -> None: ...
    def destroyBiInteractiveApp(self, arg0: str) -> None: ...
    def setTvView(self, arg0: TvView) -> int: ...
    def setTeletextAppEnabled(self, arg0: bool) -> None: ...

    class OnUnhandledInputEventListener:
        def onUnhandledInputEvent(self, arg0: InputEvent) -> bool: ...

    class TvInteractiveAppCallback:
        def __init__(self) -> None: ...
        def onPlaybackCommandRequest(self, arg0: str, arg1: str, arg2: Bundle) -> None: ...
        def onTimeShiftCommandRequest(self, arg0: str, arg1: str, arg2: Bundle) -> None: ...
        def onStateChanged(self, arg0: str, arg1: int, arg2: int) -> None: ...
        def onBiInteractiveAppCreated(self, arg0: str, arg1: Uri, arg2: str) -> None: ...
        def onTeletextAppStateChanged(self, arg0: str, arg1: int) -> None: ...
        def onSetVideoBounds(self, arg0: str, arg1: Rect) -> None: ...
        def onRequestCurrentVideoBounds(self, arg0: str) -> None: ...
        def onRequestCurrentChannelUri(self, arg0: str) -> None: ...
        def onRequestCurrentChannelLcn(self, arg0: str) -> None: ...
        def onRequestStreamVolume(self, arg0: str) -> None: ...
        def onRequestTrackInfoList(self, arg0: str) -> None: ...
        def onRequestCurrentTvInputId(self, arg0: str) -> None: ...
        def onRequestTimeShiftMode(self, arg0: str) -> None: ...
        def onRequestAvailableSpeeds(self, arg0: str) -> None: ...
        def onRequestStartRecording(self, arg0: str, arg1: str, arg2: Uri) -> None: ...
        def onRequestStopRecording(self, arg0: str, arg1: str) -> None: ...
        @overload
        def onRequestScheduleRecording(self, arg0: str, arg1: str, arg2: str, arg3: Uri, arg4: Uri, arg5: Bundle) -> None: ...
        @overload
        def onRequestScheduleRecording(self, arg0: str, arg1: str, arg2: str, arg3: Uri, arg4: int, arg5: int, arg6: int, arg7: Bundle) -> None: ...
        def onRequestSigning(self, arg0: str, arg1: str, arg2: str, arg3: str, arg4: list[int]) -> None: ...
        def onSetTvRecordingInfo(self, arg0: str, arg1: str, arg2: TvRecordingInfo) -> None: ...
        def onRequestTvRecordingInfo(self, arg0: str, arg1: str) -> None: ...
        def onRequestTvRecordingInfoList(self, arg0: str, arg1: int) -> None: ...
