from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["TvInteractiveAppManager"]

class TvInteractiveAppManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/tv/interactive/TvInteractiveAppManager"
    ACTION_APP_LINK_COMMAND = JavaStaticField("Ljava/lang/String;")
    APP_LINK_KEY_BACK_URI = JavaStaticField("Ljava/lang/String;")
    APP_LINK_KEY_CLASS_NAME = JavaStaticField("Ljava/lang/String;")
    APP_LINK_KEY_COMMAND_TYPE = JavaStaticField("Ljava/lang/String;")
    APP_LINK_KEY_PACKAGE_NAME = JavaStaticField("Ljava/lang/String;")
    APP_LINK_KEY_SERVICE_ID = JavaStaticField("Ljava/lang/String;")
    ERROR_BLOCKED = JavaStaticField("I")
    ERROR_ENCRYPTED = JavaStaticField("I")
    ERROR_NONE = JavaStaticField("I")
    ERROR_NOT_SUPPORTED = JavaStaticField("I")
    ERROR_RESOURCE_UNAVAILABLE = JavaStaticField("I")
    ERROR_UNKNOWN = JavaStaticField("I")
    ERROR_UNKNOWN_CHANNEL = JavaStaticField("I")
    ERROR_WEAK_SIGNAL = JavaStaticField("I")
    INTENT_KEY_BI_INTERACTIVE_APP_TYPE = JavaStaticField("Ljava/lang/String;")
    INTENT_KEY_BI_INTERACTIVE_APP_URI = JavaStaticField("Ljava/lang/String;")
    INTENT_KEY_CHANNEL_URI = JavaStaticField("Ljava/lang/String;")
    INTENT_KEY_COMMAND_TYPE = JavaStaticField("Ljava/lang/String;")
    INTENT_KEY_INTERACTIVE_APP_SERVICE_ID = JavaStaticField("Ljava/lang/String;")
    INTENT_KEY_TV_INPUT_ID = JavaStaticField("Ljava/lang/String;")
    INTERACTIVE_APP_STATE_ERROR = JavaStaticField("I")
    INTERACTIVE_APP_STATE_RUNNING = JavaStaticField("I")
    INTERACTIVE_APP_STATE_STOPPED = JavaStaticField("I")
    SERVICE_STATE_ERROR = JavaStaticField("I")
    SERVICE_STATE_PREPARING = JavaStaticField("I")
    SERVICE_STATE_READY = JavaStaticField("I")
    SERVICE_STATE_UNREALIZED = JavaStaticField("I")
    TELETEXT_APP_STATE_ERROR = JavaStaticField("I")
    TELETEXT_APP_STATE_HIDE = JavaStaticField("I")
    TELETEXT_APP_STATE_SHOW = JavaStaticField("I")
    getTvInteractiveAppServiceList = JavaMethod("()Ljava/util/List;")
    getAppLinkInfoList = JavaMethod("()Ljava/util/List;")
    registerAppLinkInfo = JavaMethod("(Ljava/lang/String;Landroid/media/tv/interactive/AppLinkInfo;)V")
    unregisterAppLinkInfo = JavaMethod("(Ljava/lang/String;Landroid/media/tv/interactive/AppLinkInfo;)V")
    sendAppLinkCommand = JavaMethod("(Ljava/lang/String;Landroid/os/Bundle;)V")
    registerCallback = JavaMethod("(Ljava/util/concurrent/Executor;Landroid/media/tv/interactive/TvInteractiveAppManager$TvInteractiveAppCallback;)V")
    unregisterCallback = JavaMethod("(Landroid/media/tv/interactive/TvInteractiveAppManager$TvInteractiveAppCallback;)V")

    class TvInteractiveAppCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/tv/interactive/TvInteractiveAppManager/TvInteractiveAppCallback"
        __javaconstructor__ = [("()V", False)]
        onInteractiveAppServiceAdded = JavaMethod("(Ljava/lang/String;)V")
        onInteractiveAppServiceRemoved = JavaMethod("(Ljava/lang/String;)V")
        onInteractiveAppServiceUpdated = JavaMethod("(Ljava/lang/String;)V")
        onTvInteractiveAppServiceStateChanged = JavaMethod("(Ljava/lang/String;III)V")