from typing import Any, ClassVar, overload

class ChaCha20ParameterSpec:
    def __init__(self, arg0: list[int], arg1: int) -> None: ...
    def getNonce(self) -> list[int]: ...
    def getCounter(self) -> int: ...
