from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger

class DHParameterSpec:
    @overload
    def __init__(self, arg0: BigInteger, arg1: BigInteger) -> None: ...
    @overload
    def __init__(self, arg0: BigInteger, arg1: BigInteger, arg2: int) -> None: ...
    def getP(self) -> BigInteger: ...
    def getG(self) -> BigInteger: ...
    def getL(self) -> int: ...
