from typing import Any, ClassVar, overload

class GCMParameterSpec:
    @overload
    def __init__(self, arg0: int, arg1: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: list[int], arg2: int, arg3: int) -> None: ...
    def getTLen(self) -> int: ...
    def getIV(self) -> list[int]: ...
