from typing import Any, ClassVar, overload
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class PBEParameterSpec:
    @overload
    def __init__(self, arg0: list[int], arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: list[int], arg1: int, arg2: AlgorithmParameterSpec) -> None: ...
    def getSalt(self) -> list[int]: ...
    def getIterationCount(self) -> int: ...
    def getParameterSpec(self) -> AlgorithmParameterSpec: ...
