from typing import Any, ClassVar, overload

class RC5ParameterSpec:
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: list[int], arg4: int) -> None: ...
    def getVersion(self) -> int: ...
    def getRounds(self) -> int: ...
    def getWordSize(self) -> int: ...
    def getIV(self) -> list[int]: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
