from typing import Any, ClassVar, overload

class AsusHomeBadger:
    def __init__(self) -> None: ...
    def executeBadge(self, arg0: "Context", arg1: "ComponentName", arg2: int) -> None: ...
    def getSupportLaunchers(self) -> list: ...
