from typing import Any, ClassVar, overload
from android.content.Intent import Intent

class UnsafeIntentLaunchViolation:
    def __init__(self, arg0: Intent) -> None: ...
    def getIntent(self) -> Intent: ...
