from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.service.credentials.CreateEntry import CreateEntry
from android.service.credentials.RemoteEntry import RemoteEntry

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class BeginCreateCredentialResponse:
    CREATOR: ClassVar[Creator]
    def __init__(self) -> None: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getCreateEntries(self) -> list: ...
    def getRemoteCreateEntry(self) -> RemoteEntry: ...

    class Builder:
        def __init__(self) -> None: ...
        def setCreateEntries(self, arg0: list) -> "Builder": ...
        def addCreateEntry(self, arg0: CreateEntry) -> "Builder": ...
        def setRemoteCreateEntry(self, arg0: RemoteEntry) -> "Builder": ...
        def build(self) -> "BeginCreateCredentialResponse": ...
