from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.service.credentials.Action import Action
from android.service.credentials.CredentialEntry import CredentialEntry
from android.service.credentials.RemoteEntry import RemoteEntry

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class BeginGetCredentialResponse:
    CREATOR: ClassVar[Creator]
    def __init__(self) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getCredentialEntries(self) -> list: ...
    def getAuthenticationActions(self) -> list: ...
    def getActions(self) -> list: ...
    def getRemoteCredentialEntry(self) -> RemoteEntry: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRemoteCredentialEntry(self, arg0: RemoteEntry) -> "Builder": ...
        def addCredentialEntry(self, arg0: CredentialEntry) -> "Builder": ...
        def addAuthenticationAction(self, arg0: Action) -> "Builder": ...
        def addAction(self, arg0: Action) -> "Builder": ...
        def setActions(self, arg0: list) -> "Builder": ...
        def setCredentialEntries(self, arg0: list) -> "Builder": ...
        def setAuthenticationActions(self, arg0: list) -> "Builder": ...
        def build(self) -> "BeginGetCredentialResponse": ...
