from typing import Any, ClassVar, overload

class AdManagerInterstitialAd:
    def __init__(self) -> None: ...
    @staticmethod
    def load(arg0: "Context", arg1: str, arg2: "AdManagerAdRequest", arg3: "AdManagerInterstitialAdLoadCallback") -> None: ...
    def getAppEventListener(self) -> "AppEventListener": ...
    def setAppEventListener(self, arg0: "AppEventListener") -> None: ...
