from typing import Any, ClassVar, overload

class AdManagerAdView:
    @overload
    def __init__(self, arg0: "Context") -> None: ...
    @overload
    def __init__(self, arg0: "Context", arg1: "AttributeSet") -> None: ...
    @overload
    def __init__(self, arg0: "Context", arg1: "AttributeSet", arg2: int) -> None: ...
    def getVideoController(self) -> "VideoController": ...
    def setVideoOptions(self, arg0: "VideoOptions") -> None: ...
    def getVideoOptions(self) -> "VideoOptions": ...
    def getAdSizes(self) -> list["AdSize"]: ...
    def getAppEventListener(self) -> "AppEventListener": ...
    def loadAd(self, arg0: "AdManagerAdRequest") -> None: ...
    def setManualImpressionsEnabled(self, arg0: bool) -> None: ...
    def recordManualImpression(self) -> None: ...
    def setAdSizes(self, *arg0: "AdSize") -> None: ...
    def setAppEventListener(self, arg0: "AppEventListener") -> None: ...
    def zza(self, arg0: "zzbu") -> bool: ...
