from typing import Any, ClassVar, overload
from android.net.Network import Network
from android.net.NetworkRequest import NetworkRequest
from android.net.nsd.DiscoveryRequest import DiscoveryRequest
from android.net.nsd.NsdServiceInfo import NsdServiceInfo
from java.util.concurrent.Executor import Executor

class NsdManager:
    ACTION_NSD_STATE_CHANGED: ClassVar[str]
    EXTRA_NSD_STATE: ClassVar[str]
    FAILURE_ALREADY_ACTIVE: ClassVar[int]
    FAILURE_BAD_PARAMETERS: ClassVar[int]
    FAILURE_INTERNAL_ERROR: ClassVar[int]
    FAILURE_MAX_LIMIT: ClassVar[int]
    FAILURE_OPERATION_NOT_RUNNING: ClassVar[int]
    NSD_STATE_DISABLED: ClassVar[int]
    NSD_STATE_ENABLED: ClassVar[int]
    PROTOCOL_DNS_SD: ClassVar[int]
    @overload
    def registerService(self, arg0: NsdServiceInfo, arg1: int, arg2: "RegistrationListener") -> None: ...
    @overload
    def registerService(self, arg0: NsdServiceInfo, arg1: int, arg2: Executor, arg3: "RegistrationListener") -> None: ...
    def unregisterService(self, arg0: "RegistrationListener") -> None: ...
    @overload
    def discoverServices(self, arg0: str, arg1: int, arg2: "DiscoveryListener") -> None: ...
    @overload
    def discoverServices(self, arg0: str, arg1: int, arg2: Network, arg3: Executor, arg4: "DiscoveryListener") -> None: ...
    @overload
    def discoverServices(self, arg0: DiscoveryRequest, arg1: Executor, arg2: "DiscoveryListener") -> None: ...
    @overload
    def discoverServices(self, arg0: str, arg1: int, arg2: NetworkRequest, arg3: Executor, arg4: "DiscoveryListener") -> None: ...
    def stopServiceDiscovery(self, arg0: "DiscoveryListener") -> None: ...
    @overload
    def resolveService(self, arg0: NsdServiceInfo, arg1: "ResolveListener") -> None: ...
    @overload
    def resolveService(self, arg0: NsdServiceInfo, arg1: Executor, arg2: "ResolveListener") -> None: ...
    def stopServiceResolution(self, arg0: "ResolveListener") -> None: ...
    def registerServiceInfoCallback(self, arg0: NsdServiceInfo, arg1: Executor, arg2: "ServiceInfoCallback") -> None: ...
    def unregisterServiceInfoCallback(self, arg0: "ServiceInfoCallback") -> None: ...

    class DiscoveryListener:
        def onStartDiscoveryFailed(self, arg0: str, arg1: int) -> None: ...
        def onStopDiscoveryFailed(self, arg0: str, arg1: int) -> None: ...
        def onDiscoveryStarted(self, arg0: str) -> None: ...
        def onDiscoveryStopped(self, arg0: str) -> None: ...
        def onServiceFound(self, arg0: NsdServiceInfo) -> None: ...
        def onServiceLost(self, arg0: NsdServiceInfo) -> None: ...

    class RegistrationListener:
        def onRegistrationFailed(self, arg0: NsdServiceInfo, arg1: int) -> None: ...
        def onUnregistrationFailed(self, arg0: NsdServiceInfo, arg1: int) -> None: ...
        def onServiceRegistered(self, arg0: NsdServiceInfo) -> None: ...
        def onServiceUnregistered(self, arg0: NsdServiceInfo) -> None: ...

    class ResolveListener:
        def onResolveFailed(self, arg0: NsdServiceInfo, arg1: int) -> None: ...
        def onServiceResolved(self, arg0: NsdServiceInfo) -> None: ...
        def onResolutionStopped(self, arg0: NsdServiceInfo) -> None: ...
        def onStopResolutionFailed(self, arg0: NsdServiceInfo, arg1: int) -> None: ...

    class ServiceInfoCallback:
        def onServiceInfoCallbackRegistrationFailed(self, arg0: int) -> None: ...
        def onServiceUpdated(self, arg0: NsdServiceInfo) -> None: ...
        def onServiceLost(self) -> None: ...
        def onServiceInfoCallbackUnregistered(self) -> None: ...
