from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Parcelable import Parcelable
from android.util.AttributeSet import AttributeSet
from android.util.SparseArray import SparseArray
from android.view.View import View
from android.view.autofill.AutofillValue import AutofillValue
from android.widget.SpinnerAdapter import SpinnerAdapter

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class LayoutParams:
    """Forward declaration for ``android.view.ViewGroup.LayoutParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ViewGroup.LayoutParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ViewGroup/LayoutParams
    """
    ...

class AbsSpinner:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setAdapter(self, arg0: SpinnerAdapter) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def generateDefaultLayoutParams(self) -> LayoutParams: ...
    @overload
    def setSelection(self, arg0: int, arg1: bool) -> None: ...
    @overload
    def setSelection(self, arg0: int) -> None: ...
    def getSelectedView(self) -> View: ...
    def requestLayout(self) -> None: ...
    def getAdapter(self) -> SpinnerAdapter: ...
    def getCount(self) -> int: ...
    def pointToPosition(self, arg0: int, arg1: int) -> int: ...
    def dispatchRestoreInstanceState(self, arg0: SparseArray) -> None: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, arg0: Parcelable) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def autofill(self, arg0: AutofillValue) -> None: ...
    def getAutofillType(self) -> int: ...
    def getAutofillValue(self) -> AutofillValue: ...
