from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.ColorStateList import ColorStateList
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Mode:
    """Forward declaration for ``android.graphics.PorterDuff.Mode``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.PorterDuff.Mode')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/PorterDuff/Mode
    """
    ...

class AbsSeekBar:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setThumb(self, arg0: Drawable) -> None: ...
    def getThumb(self) -> Drawable: ...
    def setThumbTintList(self, arg0: ColorStateList) -> None: ...
    def getThumbTintList(self) -> ColorStateList: ...
    def setThumbTintMode(self, arg0: Mode) -> None: ...
    def setThumbTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getThumbTintMode(self) -> Mode: ...
    def getThumbTintBlendMode(self) -> BlendMode: ...
    def getThumbOffset(self) -> int: ...
    def setThumbOffset(self, arg0: int) -> None: ...
    def setSplitTrack(self, arg0: bool) -> None: ...
    def getSplitTrack(self) -> bool: ...
    def setTickMark(self, arg0: Drawable) -> None: ...
    def getTickMark(self) -> Drawable: ...
    def setTickMarkTintList(self, arg0: ColorStateList) -> None: ...
    def getTickMarkTintList(self) -> ColorStateList: ...
    def setTickMarkTintMode(self, arg0: Mode) -> None: ...
    def setTickMarkTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getTickMarkTintMode(self) -> Mode: ...
    def getTickMarkTintBlendMode(self) -> BlendMode: ...
    def setKeyProgressIncrement(self, arg0: int) -> None: ...
    def getKeyProgressIncrement(self) -> int: ...
    def setMin(self, arg0: int) -> None: ...
    def setMax(self, arg0: int) -> None: ...
    def verifyDrawable(self, arg0: Drawable) -> bool: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def drawableStateChanged(self) -> None: ...
    def drawableHotspotChanged(self, arg0: float, arg1: float) -> None: ...
    def onSizeChanged(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def setSystemGestureExclusionRects(self, arg0: list) -> None: ...
    def onDraw(self, arg0: Canvas) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def onKeyDown(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def getAccessibilityClassName(self) -> str: ...
    def onRtlPropertiesChanged(self, arg0: int) -> None: ...
