from typing import Any, ClassVar, overload
from android.animation.ObjectAnimator import ObjectAnimator
from android.content.Context import Context
from android.content.Intent import Intent
from android.os.Parcelable import Parcelable
from android.util.AttributeSet import AttributeSet
from android.view.MotionEvent import MotionEvent
from android.view.View import View
from android.widget.Adapter import Adapter

class AdapterViewAnimator:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setDisplayedChild(self, arg0: int) -> None: ...
    def getDisplayedChild(self) -> int: ...
    def showNext(self) -> None: ...
    def showPrevious(self) -> None: ...
    def onTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, arg0: Parcelable) -> None: ...
    def getCurrentView(self) -> View: ...
    def getInAnimation(self) -> ObjectAnimator: ...
    @overload
    def setInAnimation(self, arg0: ObjectAnimator) -> None: ...
    @overload
    def setInAnimation(self, arg0: Context, arg1: int) -> None: ...
    def getOutAnimation(self) -> ObjectAnimator: ...
    @overload
    def setOutAnimation(self, arg0: ObjectAnimator) -> None: ...
    @overload
    def setOutAnimation(self, arg0: Context, arg1: int) -> None: ...
    def setAnimateFirstView(self, arg0: bool) -> None: ...
    def getBaseline(self) -> int: ...
    def getAdapter(self) -> Adapter: ...
    def setAdapter(self, arg0: Adapter) -> None: ...
    def setRemoteViewsAdapter(self, arg0: Intent) -> None: ...
    def setSelection(self, arg0: int) -> None: ...
    def getSelectedView(self) -> View: ...
    def deferNotifyDataSetChanged(self) -> None: ...
    def onRemoteAdapterConnected(self) -> bool: ...
    def onRemoteAdapterDisconnected(self) -> None: ...
    def advance(self) -> None: ...
    def fyiWillBeAdvancedByHostKThx(self) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
