from typing import Any, ClassVar, overload
from android.database.Cursor import Cursor

class AlphabetIndexer:
    mAlphabet: str
    mColumnIndex: int
    mDataCursor: Cursor
    def __init__(self, arg0: Cursor, arg1: int, arg2: str) -> None: ...
    def getSections(self) -> list: ...
    def setCursor(self, arg0: Cursor) -> None: ...
    def compare(self, arg0: str, arg1: str) -> int: ...
    def getPositionForSection(self, arg0: int) -> int: ...
    def getSectionForPosition(self, arg0: int) -> int: ...
    def onChanged(self) -> None: ...
    def onInvalidated(self) -> None: ...
