from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from android.widget.Filter import Filter
from java.util.Comparator import Comparator

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...

class ArrayAdapter:
    @overload
    def __init__(self, arg0: Context, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: list) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: int, arg3: list) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: list) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: int, arg3: list) -> None: ...
    def add(self, arg0: Any) -> None: ...
    @overload
    def addAll(self, arg0: list) -> None: ...
    @overload
    def addAll(self, *arg0: Any) -> None: ...
    def insert(self, arg0: Any, arg1: int) -> None: ...
    def remove(self, arg0: Any) -> None: ...
    def clear(self) -> None: ...
    def sort(self, arg0: Comparator) -> None: ...
    def notifyDataSetChanged(self) -> None: ...
    def setNotifyOnChange(self, arg0: bool) -> None: ...
    def getContext(self) -> Context: ...
    def getCount(self) -> int: ...
    def getItem(self, arg0: int) -> Any: ...
    def getPosition(self, arg0: Any) -> int: ...
    def getItemId(self, arg0: int) -> int: ...
    def getView(self, arg0: int, arg1: View, arg2: ViewGroup) -> View: ...
    def setDropDownViewResource(self, arg0: int) -> None: ...
    def setDropDownViewTheme(self, arg0: Theme) -> None: ...
    def getDropDownViewTheme(self) -> Theme: ...
    def getDropDownView(self, arg0: int, arg1: View, arg2: ViewGroup) -> View: ...
    @staticmethod
    def createFromResource(arg0: Context, arg1: int, arg2: int) -> "ArrayAdapter": ...
    def getFilter(self) -> Filter: ...
    def getAutofillOptions(self) -> list[str]: ...
