from typing import Any, ClassVar, overload
from android.database.DataSetObserver import DataSetObserver

class BaseExpandableListAdapter:
    def __init__(self) -> None: ...
    def registerDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def notifyDataSetInvalidated(self) -> None: ...
    def notifyDataSetChanged(self) -> None: ...
    def areAllItemsEnabled(self) -> bool: ...
    def onGroupCollapsed(self, arg0: int) -> None: ...
    def onGroupExpanded(self, arg0: int) -> None: ...
    def getCombinedChildId(self, arg0: int, arg1: int) -> int: ...
    def getCombinedGroupId(self, arg0: int) -> int: ...
    def isEmpty(self) -> bool: ...
    def getChildType(self, arg0: int, arg1: int) -> int: ...
    def getChildTypeCount(self) -> int: ...
    def getGroupType(self, arg0: int) -> int: ...
    def getGroupTypeCount(self) -> int: ...
