from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.ColorStateList import ColorStateList
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.drawable.Drawable import Drawable
from android.os.Parcelable import Parcelable
from android.util.AttributeSet import AttributeSet

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Mode:
    """Forward declaration for ``android.graphics.PorterDuff.Mode``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.PorterDuff.Mode')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/PorterDuff/Mode
    """
    ...

class CheckedTextView:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def toggle(self) -> None: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, arg0: bool) -> None: ...
    @overload
    def setCheckMarkDrawable(self, arg0: int) -> None: ...
    @overload
    def setCheckMarkDrawable(self, arg0: Drawable) -> None: ...
    def setCheckMarkTintList(self, arg0: ColorStateList) -> None: ...
    def getCheckMarkTintList(self) -> ColorStateList: ...
    def setCheckMarkTintMode(self, arg0: Mode) -> None: ...
    def setCheckMarkTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getCheckMarkTintMode(self) -> Mode: ...
    def getCheckMarkTintBlendMode(self) -> BlendMode: ...
    def setVisibility(self, arg0: int) -> None: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def verifyDrawable(self, arg0: Drawable) -> bool: ...
    def getCheckMarkDrawable(self) -> Drawable: ...
    def onRtlPropertiesChanged(self, arg0: int) -> None: ...
    def onDraw(self, arg0: Canvas) -> None: ...
    def onCreateDrawableState(self, arg0: int) -> list[int]: ...
    def drawableStateChanged(self) -> None: ...
    def drawableHotspotChanged(self, arg0: float, arg1: float) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, arg0: Parcelable) -> None: ...
