from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.View import View

class Chronometer:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setCountDown(self, arg0: bool) -> None: ...
    def isCountDown(self) -> bool: ...
    def isTheFinalCountDown(self) -> bool: ...
    def setBase(self, arg0: int) -> None: ...
    def getBase(self) -> int: ...
    def setFormat(self, arg0: str) -> None: ...
    def getFormat(self) -> str: ...
    def setOnChronometerTickListener(self, arg0: "OnChronometerTickListener") -> None: ...
    def getOnChronometerTickListener(self) -> "OnChronometerTickListener": ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onWindowVisibilityChanged(self, arg0: int) -> None: ...
    def onVisibilityChanged(self, arg0: View, arg1: int) -> None: ...
    def getContentDescription(self) -> str: ...
    def getAccessibilityClassName(self) -> str: ...

    class OnChronometerTickListener:
        def onChronometerTick(self, arg0: "Chronometer") -> None: ...
