from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from android.widget.Filter import Filter
from android.widget.FilterQueryProvider import FilterQueryProvider

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...

class CursorAdapter:
    FLAG_AUTO_REQUERY: ClassVar[int]
    FLAG_REGISTER_CONTENT_OBSERVER: ClassVar[int]
    @overload
    def __init__(self, arg0: Context, arg1: Cursor) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Cursor, arg2: bool) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Cursor, arg2: int) -> None: ...
    def init(self, arg0: Context, arg1: Cursor, arg2: bool) -> None: ...
    def setDropDownViewTheme(self, arg0: Theme) -> None: ...
    def getDropDownViewTheme(self) -> Theme: ...
    def getCursor(self) -> Cursor: ...
    def getCount(self) -> int: ...
    def getItem(self, arg0: int) -> Any: ...
    def getItemId(self, arg0: int) -> int: ...
    def hasStableIds(self) -> bool: ...
    def getView(self, arg0: int, arg1: View, arg2: ViewGroup) -> View: ...
    def getDropDownView(self, arg0: int, arg1: View, arg2: ViewGroup) -> View: ...
    def newView(self, arg0: Context, arg1: Cursor, arg2: ViewGroup) -> View: ...
    def newDropDownView(self, arg0: Context, arg1: Cursor, arg2: ViewGroup) -> View: ...
    def bindView(self, arg0: View, arg1: Context, arg2: Cursor) -> None: ...
    def changeCursor(self, arg0: Cursor) -> None: ...
    def swapCursor(self, arg0: Cursor) -> Cursor: ...
    def convertToString(self, arg0: Cursor) -> str: ...
    def runQueryOnBackgroundThread(self, arg0: str) -> Cursor: ...
    def getFilter(self) -> Filter: ...
    def getFilterQueryProvider(self) -> FilterQueryProvider: ...
    def setFilterQueryProvider(self, arg0: FilterQueryProvider) -> None: ...
    def onContentChanged(self) -> None: ...
