from typing import Any, ClassVar, overload
from android.database.DataSetObserver import DataSetObserver
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class ExpandableListAdapter:
    def registerDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def getGroupCount(self) -> int: ...
    def getChildrenCount(self, arg0: int) -> int: ...
    def getGroup(self, arg0: int) -> Any: ...
    def getChild(self, arg0: int, arg1: int) -> Any: ...
    def getGroupId(self, arg0: int) -> int: ...
    def getChildId(self, arg0: int, arg1: int) -> int: ...
    def hasStableIds(self) -> bool: ...
    def getGroupView(self, arg0: int, arg1: bool, arg2: View, arg3: ViewGroup) -> View: ...
    def getChildView(self, arg0: int, arg1: int, arg2: bool, arg3: View, arg4: ViewGroup) -> View: ...
    def isChildSelectable(self, arg0: int, arg1: int) -> bool: ...
    def areAllItemsEnabled(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def onGroupExpanded(self, arg0: int) -> None: ...
    def onGroupCollapsed(self, arg0: int) -> None: ...
    def getCombinedChildId(self, arg0: int, arg1: int) -> int: ...
    def getCombinedGroupId(self, arg0: int) -> int: ...
