from typing import Any, ClassVar, overload

class Filter:
    def __init__(self) -> None: ...
    @overload
    def filter(self, arg0: str) -> None: ...
    @overload
    def filter(self, arg0: str, arg1: "FilterListener") -> None: ...
    def performFiltering(self, arg0: str) -> "FilterResults": ...
    def publishResults(self, arg0: str, arg1: "FilterResults") -> None: ...
    def convertResultToString(self, arg0: Any) -> str: ...

    class FilterListener:
        def onFilterComplete(self, arg0: int) -> None: ...

    class FilterResults:
        count: int
        values: Any
        def __init__(self) -> None: ...
