from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class MarginLayoutParams:
    """Forward declaration for ``android.view.ViewGroup.MarginLayoutParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ViewGroup.MarginLayoutParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ViewGroup/MarginLayoutParams
    """
    ...

class FrameLayout:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setForegroundGravity(self, arg0: int) -> None: ...
    def generateDefaultLayoutParams(self) -> "LayoutParams": ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def setMeasureAllChildren(self, arg0: bool) -> None: ...
    def getConsiderGoneChildrenWhenMeasuring(self) -> bool: ...
    def getMeasureAllChildren(self) -> bool: ...
    @overload
    def generateLayoutParams(self, arg0: AttributeSet) -> "LayoutParams": ...
    @overload
    def generateLayoutParams(self, arg0: "LayoutParams") -> "LayoutParams": ...
    def shouldDelayChildPressedState(self) -> bool: ...
    def checkLayoutParams(self, arg0: "LayoutParams") -> bool: ...
    def getAccessibilityClassName(self) -> str: ...

    class LayoutParams:
        UNSPECIFIED_GRAVITY: ClassVar[int]
        gravity: int
        @overload
        def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: "LayoutParams") -> None: ...
        @overload
        def __init__(self, arg0: MarginLayoutParams) -> None: ...
        @overload
        def __init__(self, arg0: "LayoutParams") -> None: ...
