from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.graphics.Rect import Rect
from android.util.AttributeSet import AttributeSet
from android.view.KeyEvent import KeyEvent
from android.view.View import View
from android.view.accessibility.AccessibilityNodeInfo import AccessibilityNodeInfo
from android.widget.ListAdapter import ListAdapter

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class LayoutParams:
    """Forward declaration for ``android.view.ViewGroup.LayoutParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ViewGroup.LayoutParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ViewGroup/LayoutParams
    """
    ...

class GridView:
    AUTO_FIT: ClassVar[int]
    NO_STRETCH: ClassVar[int]
    STRETCH_COLUMN_WIDTH: ClassVar[int]
    STRETCH_SPACING: ClassVar[int]
    STRETCH_SPACING_UNIFORM: ClassVar[int]
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def getAdapter(self) -> ListAdapter: ...
    def setRemoteViewsAdapter(self, arg0: Intent) -> None: ...
    def setAdapter(self, arg0: ListAdapter) -> None: ...
    def smoothScrollToPosition(self, arg0: int) -> None: ...
    def smoothScrollByOffset(self, arg0: int) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def attachLayoutAnimationParameters(self, arg0: View, arg1: LayoutParams, arg2: int, arg3: int) -> None: ...
    def layoutChildren(self) -> None: ...
    def setSelection(self, arg0: int) -> None: ...
    def onKeyDown(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def onKeyMultiple(self, arg0: int, arg1: int, arg2: KeyEvent) -> bool: ...
    def onKeyUp(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def onFocusChanged(self, arg0: bool, arg1: int, arg2: Rect) -> None: ...
    def setGravity(self, arg0: int) -> None: ...
    def getGravity(self) -> int: ...
    def setHorizontalSpacing(self, arg0: int) -> None: ...
    def getHorizontalSpacing(self) -> int: ...
    def getRequestedHorizontalSpacing(self) -> int: ...
    def setVerticalSpacing(self, arg0: int) -> None: ...
    def getVerticalSpacing(self) -> int: ...
    def setStretchMode(self, arg0: int) -> None: ...
    def getStretchMode(self) -> int: ...
    def setColumnWidth(self, arg0: int) -> None: ...
    def getColumnWidth(self) -> int: ...
    def getRequestedColumnWidth(self) -> int: ...
    def setNumColumns(self, arg0: int) -> None: ...
    def getNumColumns(self) -> int: ...
    def computeVerticalScrollExtent(self) -> int: ...
    def computeVerticalScrollOffset(self) -> int: ...
    def computeVerticalScrollRange(self) -> int: ...
    def getAccessibilityClassName(self) -> str: ...
    def onInitializeAccessibilityNodeInfoForItem(self, arg0: View, arg1: int, arg2: AccessibilityNodeInfo) -> None: ...
