from typing import Any, ClassVar, overload
from android.database.DataSetObserver import DataSetObserver
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from android.widget.Filter import Filter
from android.widget.ListAdapter import ListAdapter

class HeaderViewListAdapter:
    def __init__(self, arg0: list, arg1: list, arg2: ListAdapter) -> None: ...
    def getHeadersCount(self) -> int: ...
    def getFootersCount(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def removeHeader(self, arg0: View) -> bool: ...
    def removeFooter(self, arg0: View) -> bool: ...
    def getCount(self) -> int: ...
    def areAllItemsEnabled(self) -> bool: ...
    def isEnabled(self, arg0: int) -> bool: ...
    def getItem(self, arg0: int) -> Any: ...
    def getItemId(self, arg0: int) -> int: ...
    def hasStableIds(self) -> bool: ...
    def getView(self, arg0: int, arg1: View, arg2: ViewGroup) -> View: ...
    def getItemViewType(self, arg0: int) -> int: ...
    def getViewTypeCount(self) -> int: ...
    def registerDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, arg0: DataSetObserver) -> None: ...
    def getFilter(self) -> Filter: ...
    def getWrappedAdapter(self) -> ListAdapter: ...
