from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Canvas import Canvas
from android.graphics.Rect import Rect
from android.os.Parcelable import Parcelable
from android.util.AttributeSet import AttributeSet
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.View import View

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class LayoutParams:
    """Forward declaration for ``android.view.ViewGroup.LayoutParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ViewGroup.LayoutParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ViewGroup/LayoutParams
    """
    ...

class HorizontalScrollView:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def getLeftFadingEdgeStrength(self) -> float: ...
    def getRightFadingEdgeStrength(self) -> float: ...
    def setEdgeEffectColor(self, arg0: int) -> None: ...
    def setRightEdgeEffectColor(self, arg0: int) -> None: ...
    def setLeftEdgeEffectColor(self, arg0: int) -> None: ...
    def getLeftEdgeEffectColor(self) -> int: ...
    def getRightEdgeEffectColor(self) -> int: ...
    def getMaxScrollAmount(self) -> int: ...
    @overload
    def addView(self, arg0: View) -> None: ...
    @overload
    def addView(self, arg0: View, arg1: int) -> None: ...
    @overload
    def addView(self, arg0: View, arg1: LayoutParams) -> None: ...
    @overload
    def addView(self, arg0: View, arg1: int, arg2: LayoutParams) -> None: ...
    def isFillViewport(self) -> bool: ...
    def setFillViewport(self, arg0: bool) -> None: ...
    def isSmoothScrollingEnabled(self) -> bool: ...
    def setSmoothScrollingEnabled(self, arg0: bool) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def dispatchKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def executeKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def requestDisallowInterceptTouchEvent(self, arg0: bool) -> None: ...
    def onInterceptTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def onTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def onGenericMotionEvent(self, arg0: MotionEvent) -> bool: ...
    def shouldDelayChildPressedState(self) -> bool: ...
    def onOverScrolled(self, arg0: int, arg1: int, arg2: bool, arg3: bool) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def pageScroll(self, arg0: int) -> bool: ...
    def fullScroll(self, arg0: int) -> bool: ...
    def arrowScroll(self, arg0: int) -> bool: ...
    def smoothScrollBy(self, arg0: int, arg1: int) -> None: ...
    def smoothScrollTo(self, arg0: int, arg1: int) -> None: ...
    def computeHorizontalScrollRange(self) -> int: ...
    def computeHorizontalScrollOffset(self) -> int: ...
    def measureChild(self, arg0: View, arg1: int, arg2: int) -> None: ...
    def measureChildWithMargins(self, arg0: View, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def computeScroll(self) -> None: ...
    def computeScrollDeltaToGetChildRectOnScreen(self, arg0: Rect) -> int: ...
    def requestChildFocus(self, arg0: View, arg1: View) -> None: ...
    def onRequestFocusInDescendants(self, arg0: int, arg1: Rect) -> bool: ...
    def requestChildRectangleOnScreen(self, arg0: View, arg1: Rect, arg2: bool) -> bool: ...
    def requestLayout(self) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def onSizeChanged(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def fling(self, arg0: int) -> None: ...
    def scrollTo(self, arg0: int, arg1: int) -> None: ...
    def draw(self, arg0: Canvas) -> None: ...
    def onRestoreInstanceState(self, arg0: Parcelable) -> None: ...
    def onSaveInstanceState(self) -> Parcelable: ...
