from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.ColorStateList import ColorStateList
from android.graphics.Bitmap import Bitmap
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Matrix import Matrix
from android.graphics.drawable.Drawable import Drawable
from android.graphics.drawable.Icon import Icon
from android.net.Uri import Uri
from android.util.AttributeSet import AttributeSet

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Mode:
    """Forward declaration for ``android.graphics.PorterDuff.Mode``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.PorterDuff.Mode')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/PorterDuff/Mode
    """
    ...

class ImageView:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def verifyDrawable(self, arg0: Drawable) -> bool: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def invalidateDrawable(self, arg0: Drawable) -> None: ...
    def hasOverlappingRendering(self) -> bool: ...
    def getAdjustViewBounds(self) -> bool: ...
    def setAdjustViewBounds(self, arg0: bool) -> None: ...
    def getMaxWidth(self) -> int: ...
    def setMaxWidth(self, arg0: int) -> None: ...
    def getMaxHeight(self) -> int: ...
    def setMaxHeight(self, arg0: int) -> None: ...
    def getDrawable(self) -> Drawable: ...
    def setImageResource(self, arg0: int) -> None: ...
    def setImageURI(self, arg0: Uri) -> None: ...
    def setImageDrawable(self, arg0: Drawable) -> None: ...
    def setImageIcon(self, arg0: Icon) -> None: ...
    def setImageTintList(self, arg0: ColorStateList) -> None: ...
    def getImageTintList(self) -> ColorStateList: ...
    def setImageTintMode(self, arg0: Mode) -> None: ...
    def setImageTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getImageTintMode(self) -> Mode: ...
    def getImageTintBlendMode(self) -> BlendMode: ...
    def setImageBitmap(self, arg0: Bitmap) -> None: ...
    def setImageState(self, arg0: list[int], arg1: bool) -> None: ...
    def setSelected(self, arg0: bool) -> None: ...
    def setImageLevel(self, arg0: int) -> None: ...
    def setScaleType(self, arg0: "ScaleType") -> None: ...
    def getScaleType(self) -> "ScaleType": ...
    def getImageMatrix(self) -> Matrix: ...
    def setImageMatrix(self, arg0: Matrix) -> None: ...
    def getCropToPadding(self) -> bool: ...
    def setCropToPadding(self, arg0: bool) -> None: ...
    def onCreateDrawableState(self, arg0: int) -> list[int]: ...
    def onRtlPropertiesChanged(self, arg0: int) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def setFrame(self, arg0: int, arg1: int, arg2: int, arg3: int) -> bool: ...
    def drawableStateChanged(self) -> None: ...
    def drawableHotspotChanged(self, arg0: float, arg1: float) -> None: ...
    def animateTransform(self, arg0: Matrix) -> None: ...
    def onDraw(self, arg0: Canvas) -> None: ...
    def getBaseline(self) -> int: ...
    def setBaseline(self, arg0: int) -> None: ...
    def setBaselineAlignBottom(self, arg0: bool) -> None: ...
    def getBaselineAlignBottom(self) -> bool: ...
    @overload
    def setColorFilter(self, arg0: int, arg1: Mode) -> None: ...
    @overload
    def setColorFilter(self, arg0: int) -> None: ...
    @overload
    def setColorFilter(self, arg0: ColorFilter) -> None: ...
    def clearColorFilter(self) -> None: ...
    def getColorFilter(self) -> ColorFilter: ...
    def getImageAlpha(self) -> int: ...
    def setImageAlpha(self, arg0: int) -> None: ...
    def setAlpha(self, arg0: int) -> None: ...
    def isOpaque(self) -> bool: ...
    def onVisibilityAggregated(self, arg0: bool) -> None: ...
    def setVisibility(self, arg0: int) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def getAccessibilityClassName(self) -> str: ...

    class ScaleType:
        MATRIX: ClassVar["ScaleType"]
        FIT_XY: ClassVar["ScaleType"]
        FIT_START: ClassVar["ScaleType"]
        FIT_CENTER: ClassVar["ScaleType"]
        FIT_END: ClassVar["ScaleType"]
        CENTER: ClassVar["ScaleType"]
        CENTER_CROP: ClassVar["ScaleType"]
        CENTER_INSIDE: ClassVar["ScaleType"]
        @staticmethod
        def values() -> list["ScaleType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "ScaleType": ...
