from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.drawable.Drawable import Drawable
from android.net.Uri import Uri
from android.util.AttributeSet import AttributeSet

class ImageSwitcher:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    def setImageResource(self, arg0: int) -> None: ...
    def setImageURI(self, arg0: Uri) -> None: ...
    def setImageDrawable(self, arg0: Drawable) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
