from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["LinearLayout"]

class LinearLayout(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/widget/LinearLayout"
    __javaconstructor__ = [("(Landroid/content/Context;)V", False), ("(Landroid/content/Context;Landroid/util/AttributeSet;)V", False), ("(Landroid/content/Context;Landroid/util/AttributeSet;I)V", False), ("(Landroid/content/Context;Landroid/util/AttributeSet;II)V", False)]
    HORIZONTAL = JavaStaticField("I")
    SHOW_DIVIDER_BEGINNING = JavaStaticField("I")
    SHOW_DIVIDER_END = JavaStaticField("I")
    SHOW_DIVIDER_MIDDLE = JavaStaticField("I")
    SHOW_DIVIDER_NONE = JavaStaticField("I")
    VERTICAL = JavaStaticField("I")
    setShowDividers = JavaMethod("(I)V")
    shouldDelayChildPressedState = JavaMethod("()Z")
    getShowDividers = JavaMethod("()I")
    getDividerDrawable = JavaMethod("()Landroid/graphics/drawable/Drawable;")
    setDividerDrawable = JavaMethod("(Landroid/graphics/drawable/Drawable;)V")
    setDividerPadding = JavaMethod("(I)V")
    getDividerPadding = JavaMethod("()I")
    onDraw = JavaMethod("(Landroid/graphics/Canvas;)V")
    isBaselineAligned = JavaMethod("()Z")
    setBaselineAligned = JavaMethod("(Z)V")
    isMeasureWithLargestChildEnabled = JavaMethod("()Z")
    setMeasureWithLargestChildEnabled = JavaMethod("(Z)V")
    getBaseline = JavaMethod("()I")
    getBaselineAlignedChildIndex = JavaMethod("()I")
    setBaselineAlignedChildIndex = JavaMethod("(I)V")
    getWeightSum = JavaMethod("()F")
    setWeightSum = JavaMethod("(F)V")
    onMeasure = JavaMethod("(II)V")
    onLayout = JavaMethod("(ZIIII)V")
    onRtlPropertiesChanged = JavaMethod("(I)V")
    setOrientation = JavaMethod("(I)V")
    getOrientation = JavaMethod("()I")
    setGravity = JavaMethod("(I)V")
    getGravity = JavaMethod("()I")
    setHorizontalGravity = JavaMethod("(I)V")
    setVerticalGravity = JavaMethod("(I)V")
    generateLayoutParams = JavaMultipleMethod([("(Landroid/util/AttributeSet;)Landroid/widget/LinearLayout$LayoutParams;", False, False), ("(Landroid/view/ViewGroup$LayoutParams;)Landroid/widget/LinearLayout$LayoutParams;", False, False)])
    generateDefaultLayoutParams = JavaMethod("()Landroid/widget/LinearLayout$LayoutParams;")
    checkLayoutParams = JavaMethod("(Landroid/view/ViewGroup$LayoutParams;)Z")
    getAccessibilityClassName = JavaMethod("()Ljava/lang/CharSequence;")

    class LayoutParams(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/widget/LinearLayout/LayoutParams"
        __javaconstructor__ = [("(Landroid/content/Context;Landroid/util/AttributeSet;)V", False), ("(II)V", False), ("(IIF)V", False), ("(Landroid/view/ViewGroup$LayoutParams;)V", False), ("(Landroid/view/ViewGroup$MarginLayoutParams;)V", False), ("(Landroid/widget/LinearLayout$LayoutParams;)V", False)]
        gravity = JavaField("I")
        weight = JavaField("F")
        debug = JavaMethod("(Ljava/lang/String;)Ljava/lang/String;")