from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from android.view.KeyEvent import KeyEvent
from android.view.View import View
from android.widget.ListAdapter import ListAdapter
from android.widget.ListView import ListView

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OnItemClickListener:
    """Forward declaration for ``android.widget.AdapterView.OnItemClickListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.widget.AdapterView.OnItemClickListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/widget/AdapterView/OnItemClickListener
    """
    ...
class OnItemSelectedListener:
    """Forward declaration for ``android.widget.AdapterView.OnItemSelectedListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.widget.AdapterView.OnItemSelectedListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/widget/AdapterView/OnItemSelectedListener
    """
    ...
class OnDismissListener:
    """Forward declaration for ``android.widget.PopupWindow.OnDismissListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.widget.PopupWindow.OnDismissListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/widget/PopupWindow/OnDismissListener
    """
    ...
class OnTouchListener:
    """Forward declaration for ``android.view.View.OnTouchListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.View.OnTouchListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/View/OnTouchListener
    """
    ...

class ListPopupWindow:
    INPUT_METHOD_FROM_FOCUSABLE: ClassVar[int]
    INPUT_METHOD_NEEDED: ClassVar[int]
    INPUT_METHOD_NOT_NEEDED: ClassVar[int]
    MATCH_PARENT: ClassVar[int]
    POSITION_PROMPT_ABOVE: ClassVar[int]
    POSITION_PROMPT_BELOW: ClassVar[int]
    WRAP_CONTENT: ClassVar[int]
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setAdapter(self, arg0: ListAdapter) -> None: ...
    def setPromptPosition(self, arg0: int) -> None: ...
    def getPromptPosition(self) -> int: ...
    def setModal(self, arg0: bool) -> None: ...
    def isModal(self) -> bool: ...
    def setSoftInputMode(self, arg0: int) -> None: ...
    def getSoftInputMode(self) -> int: ...
    def setListSelector(self, arg0: Drawable) -> None: ...
    def getBackground(self) -> Drawable: ...
    def setBackgroundDrawable(self, arg0: Drawable) -> None: ...
    def setAnimationStyle(self, arg0: int) -> None: ...
    def getAnimationStyle(self) -> int: ...
    def getAnchorView(self) -> View: ...
    def setAnchorView(self, arg0: View) -> None: ...
    def getHorizontalOffset(self) -> int: ...
    def setHorizontalOffset(self, arg0: int) -> None: ...
    def getVerticalOffset(self) -> int: ...
    def setVerticalOffset(self, arg0: int) -> None: ...
    def setEpicenterBounds(self, arg0: Rect) -> None: ...
    def getEpicenterBounds(self) -> Rect: ...
    def setDropDownGravity(self, arg0: int) -> None: ...
    def getWidth(self) -> int: ...
    def setWidth(self, arg0: int) -> None: ...
    def setContentWidth(self, arg0: int) -> None: ...
    def getHeight(self) -> int: ...
    def setHeight(self, arg0: int) -> None: ...
    def setWindowLayoutType(self, arg0: int) -> None: ...
    def setOnItemClickListener(self, arg0: OnItemClickListener) -> None: ...
    def setOnItemSelectedListener(self, arg0: OnItemSelectedListener) -> None: ...
    def setPromptView(self, arg0: View) -> None: ...
    def postShow(self) -> None: ...
    def show(self) -> None: ...
    def dismiss(self) -> None: ...
    def setOnDismissListener(self, arg0: OnDismissListener) -> None: ...
    def setInputMethodMode(self, arg0: int) -> None: ...
    def getInputMethodMode(self) -> int: ...
    def setSelection(self, arg0: int) -> None: ...
    def clearListSelection(self) -> None: ...
    def isShowing(self) -> bool: ...
    def isInputMethodNotNeeded(self) -> bool: ...
    def performItemClick(self, arg0: int) -> bool: ...
    def getSelectedItem(self) -> Any: ...
    def getSelectedItemPosition(self) -> int: ...
    def getSelectedItemId(self) -> int: ...
    def getSelectedView(self) -> View: ...
    def getListView(self) -> ListView: ...
    def onKeyDown(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def onKeyUp(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def onKeyPreIme(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def createDragToOpenListener(self, arg0: View) -> OnTouchListener: ...
