from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.View import View

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OnClickListener:
    """Forward declaration for ``android.view.View.OnClickListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.View.OnClickListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/View/OnClickListener
    """
    ...

class MediaController:
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: bool) -> None: ...
    @overload
    def __init__(self, arg0: Context) -> None: ...
    def onFinishInflate(self) -> None: ...
    def setMediaPlayer(self, arg0: "MediaPlayerControl") -> None: ...
    def setAnchorView(self, arg0: View) -> None: ...
    @overload
    def show(self) -> None: ...
    @overload
    def show(self, arg0: int) -> None: ...
    def isShowing(self) -> bool: ...
    def hide(self) -> None: ...
    def onTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def onTrackballEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def setEnabled(self, arg0: bool) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def setPrevNextListeners(self, arg0: OnClickListener, arg1: OnClickListener) -> None: ...

    class MediaPlayerControl:
        def start(self) -> None: ...
        def pause(self) -> None: ...
        def getDuration(self) -> int: ...
        def getCurrentPosition(self) -> int: ...
        def seekTo(self, arg0: int) -> None: ...
        def isPlaying(self) -> bool: ...
        def getBufferPercentage(self) -> int: ...
        def canPause(self) -> bool: ...
        def canSeekBackward(self) -> bool: ...
        def canSeekForward(self) -> bool: ...
        def getAudioSessionId(self) -> int: ...
