from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Canvas import Canvas
from android.util.AttributeSet import AttributeSet
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.accessibility.AccessibilityNodeProvider import AccessibilityNodeProvider

class NumberPicker:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onInterceptTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def onTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchKeyEvent(self, arg0: KeyEvent) -> bool: ...
    def dispatchTrackballEvent(self, arg0: MotionEvent) -> bool: ...
    def dispatchHoverEvent(self, arg0: MotionEvent) -> bool: ...
    def computeScroll(self) -> None: ...
    def setEnabled(self, arg0: bool) -> None: ...
    def scrollBy(self, arg0: int, arg1: int) -> None: ...
    def computeVerticalScrollOffset(self) -> int: ...
    def computeVerticalScrollRange(self) -> int: ...
    def computeVerticalScrollExtent(self) -> int: ...
    def getSolidColor(self) -> int: ...
    def setOnValueChangedListener(self, arg0: "OnValueChangeListener") -> None: ...
    def setOnScrollListener(self, arg0: "OnScrollListener") -> None: ...
    def setFormatter(self, arg0: "Formatter") -> None: ...
    def setValue(self, arg0: int) -> None: ...
    def performClick(self) -> bool: ...
    def performLongClick(self) -> bool: ...
    def getWrapSelectorWheel(self) -> bool: ...
    def setWrapSelectorWheel(self, arg0: bool) -> None: ...
    def setOnLongPressUpdateInterval(self, arg0: int) -> None: ...
    def getValue(self) -> int: ...
    def getMinValue(self) -> int: ...
    def setMinValue(self, arg0: int) -> None: ...
    def getMaxValue(self) -> int: ...
    def setMaxValue(self, arg0: int) -> None: ...
    def getDisplayedValues(self) -> list[str]: ...
    def setDisplayedValues(self, arg0: list[str]) -> None: ...
    def setSelectionDividerHeight(self, arg0: int) -> None: ...
    def getSelectionDividerHeight(self) -> int: ...
    def getTopFadingEdgeStrength(self) -> float: ...
    def getBottomFadingEdgeStrength(self) -> float: ...
    def onDetachedFromWindow(self) -> None: ...
    def drawableStateChanged(self) -> None: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def onDraw(self, arg0: Canvas) -> None: ...
    def getAccessibilityNodeProvider(self) -> AccessibilityNodeProvider: ...
    def setTextColor(self, arg0: int) -> None: ...
    def getTextColor(self) -> int: ...
    def setTextSize(self, arg0: float) -> None: ...
    def getTextSize(self) -> float: ...

    class Formatter:
        def format(self, arg0: int) -> str: ...

    class OnScrollListener:
        SCROLL_STATE_FLING: ClassVar[int]
        SCROLL_STATE_IDLE: ClassVar[int]
        SCROLL_STATE_TOUCH_SCROLL: ClassVar[int]
        def onScrollStateChange(self, arg0: "NumberPicker", arg1: int) -> None: ...

    class OnValueChangeListener:
        def onValueChange(self, arg0: "NumberPicker", arg1: int, arg2: int) -> None: ...
