from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.view.animation.Interpolator import Interpolator

class OverScroller:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Interpolator) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Interpolator, arg2: float, arg3: float) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Interpolator, arg2: float, arg3: float, arg4: bool) -> None: ...
    def setFriction(self, arg0: float) -> None: ...
    def isFinished(self) -> bool: ...
    def forceFinished(self, arg0: bool) -> None: ...
    def getCurrX(self) -> int: ...
    def getCurrY(self) -> int: ...
    def getCurrVelocity(self) -> float: ...
    def getStartX(self) -> int: ...
    def getStartY(self) -> int: ...
    def getFinalX(self) -> int: ...
    def getFinalY(self) -> int: ...
    def computeScrollOffset(self) -> bool: ...
    @overload
    def startScroll(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def startScroll(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def springBack(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> bool: ...
    @overload
    def fling(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int) -> None: ...
    @overload
    def fling(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int, arg8: int, arg9: int) -> None: ...
    def notifyHorizontalEdgeReached(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def notifyVerticalEdgeReached(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def isOverScrolled(self) -> bool: ...
    def abortAnimation(self) -> None: ...
