from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.ColorStateList import ColorStateList
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.drawable.Drawable import Drawable
from android.os.Parcelable import Parcelable
from android.util.AttributeSet import AttributeSet
from android.view.animation.Interpolator import Interpolator

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Mode:
    """Forward declaration for ``android.graphics.PorterDuff.Mode``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.PorterDuff.Mode')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/PorterDuff/Mode
    """
    ...

class ProgressBar:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setMinWidth(self, arg0: int) -> None: ...
    def getMinWidth(self) -> int: ...
    def setMaxWidth(self, arg0: int) -> None: ...
    def getMaxWidth(self) -> int: ...
    def setMinHeight(self, arg0: int) -> None: ...
    def getMinHeight(self) -> int: ...
    def setMaxHeight(self, arg0: int) -> None: ...
    def getMaxHeight(self) -> int: ...
    def isIndeterminate(self) -> bool: ...
    def setIndeterminate(self, arg0: bool) -> None: ...
    def getIndeterminateDrawable(self) -> Drawable: ...
    def setIndeterminateDrawable(self, arg0: Drawable) -> None: ...
    def setIndeterminateTintList(self, arg0: ColorStateList) -> None: ...
    def getIndeterminateTintList(self) -> ColorStateList: ...
    def setIndeterminateTintMode(self, arg0: Mode) -> None: ...
    def setIndeterminateTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getIndeterminateTintMode(self) -> Mode: ...
    def getIndeterminateTintBlendMode(self) -> BlendMode: ...
    def setIndeterminateDrawableTiled(self, arg0: Drawable) -> None: ...
    def getProgressDrawable(self) -> Drawable: ...
    def setProgressDrawable(self, arg0: Drawable) -> None: ...
    def setProgressTintList(self, arg0: ColorStateList) -> None: ...
    def getProgressTintList(self) -> ColorStateList: ...
    def setProgressTintMode(self, arg0: Mode) -> None: ...
    def setProgressTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getProgressTintMode(self) -> Mode: ...
    def getProgressTintBlendMode(self) -> BlendMode: ...
    def setProgressBackgroundTintList(self, arg0: ColorStateList) -> None: ...
    def getProgressBackgroundTintList(self) -> ColorStateList: ...
    def setProgressBackgroundTintMode(self, arg0: Mode) -> None: ...
    def setProgressBackgroundTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getProgressBackgroundTintMode(self) -> Mode: ...
    def getProgressBackgroundTintBlendMode(self) -> BlendMode: ...
    def setSecondaryProgressTintList(self, arg0: ColorStateList) -> None: ...
    def getSecondaryProgressTintList(self) -> ColorStateList: ...
    def setSecondaryProgressTintMode(self, arg0: Mode) -> None: ...
    def setSecondaryProgressTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getSecondaryProgressTintMode(self) -> Mode: ...
    def getSecondaryProgressTintBlendMode(self) -> BlendMode: ...
    def setProgressDrawableTiled(self, arg0: Drawable) -> None: ...
    def getCurrentDrawable(self) -> Drawable: ...
    def verifyDrawable(self, arg0: Drawable) -> bool: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def postInvalidate(self) -> None: ...
    def setStateDescription(self, arg0: str) -> None: ...
    @overload
    def setProgress(self, arg0: int) -> None: ...
    @overload
    def setProgress(self, arg0: int, arg1: bool) -> None: ...
    def setSecondaryProgress(self, arg0: int) -> None: ...
    def getProgress(self) -> int: ...
    def getSecondaryProgress(self) -> int: ...
    def getMin(self) -> int: ...
    def getMax(self) -> int: ...
    def setMin(self, arg0: int) -> None: ...
    def setMax(self, arg0: int) -> None: ...
    def incrementProgressBy(self, arg0: int) -> None: ...
    def incrementSecondaryProgressBy(self, arg0: int) -> None: ...
    @overload
    def setInterpolator(self, arg0: Context, arg1: int) -> None: ...
    @overload
    def setInterpolator(self, arg0: Interpolator) -> None: ...
    def getInterpolator(self) -> Interpolator: ...
    def onVisibilityAggregated(self, arg0: bool) -> None: ...
    def invalidateDrawable(self, arg0: Drawable) -> None: ...
    def onSizeChanged(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def onDraw(self, arg0: Canvas) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def drawableStateChanged(self) -> None: ...
    def drawableHotspotChanged(self, arg0: float, arg1: float) -> None: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, arg0: Parcelable) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def isAnimating(self) -> bool: ...
