from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.TypedArray import TypedArray
from android.util.AttributeSet import AttributeSet
from android.view.View import View
from android.view.accessibility.AccessibilityNodeInfo import AccessibilityNodeInfo
from android.view.autofill.AutofillValue import AutofillValue

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OnHierarchyChangeListener:
    """Forward declaration for ``android.view.ViewGroup.OnHierarchyChangeListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ViewGroup.OnHierarchyChangeListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ViewGroup/OnHierarchyChangeListener
    """
    ...
class MarginLayoutParams:
    """Forward declaration for ``android.view.ViewGroup.MarginLayoutParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ViewGroup.MarginLayoutParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ViewGroup/MarginLayoutParams
    """
    ...

class RadioGroup:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    def setOnHierarchyChangeListener(self, arg0: OnHierarchyChangeListener) -> None: ...
    def onFinishInflate(self) -> None: ...
    def addView(self, arg0: View, arg1: int, arg2: "LayoutParams") -> None: ...
    def check(self, arg0: int) -> None: ...
    def getCheckedRadioButtonId(self) -> int: ...
    def clearCheck(self) -> None: ...
    def setOnCheckedChangeListener(self, arg0: "OnCheckedChangeListener") -> None: ...
    def generateLayoutParams(self, arg0: AttributeSet) -> "LayoutParams": ...
    def checkLayoutParams(self, arg0: "LayoutParams") -> bool: ...
    def generateDefaultLayoutParams(self) -> "LayoutParams": ...
    def getAccessibilityClassName(self) -> str: ...
    def autofill(self, arg0: AutofillValue) -> None: ...
    def getAutofillType(self) -> int: ...
    def getAutofillValue(self) -> AutofillValue: ...
    def onInitializeAccessibilityNodeInfo(self, arg0: AccessibilityNodeInfo) -> None: ...

    class LayoutParams:
        @overload
        def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: float) -> None: ...
        @overload
        def __init__(self, arg0: "LayoutParams") -> None: ...
        @overload
        def __init__(self, arg0: MarginLayoutParams) -> None: ...
        def setBaseAttributes(self, arg0: TypedArray, arg1: int, arg2: int) -> None: ...

    class OnCheckedChangeListener:
        def onCheckedChanged(self, arg0: "RadioGroup", arg1: int) -> None: ...
