from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.accessibility.AccessibilityNodeInfo import AccessibilityNodeInfo

class RadioButton:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def toggle(self) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def onInitializeAccessibilityNodeInfo(self, arg0: AccessibilityNodeInfo) -> None: ...
