from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class RatingBar:
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context) -> None: ...
    def setOnRatingBarChangeListener(self, arg0: "OnRatingBarChangeListener") -> None: ...
    def getOnRatingBarChangeListener(self) -> "OnRatingBarChangeListener": ...
    def setIsIndicator(self, arg0: bool) -> None: ...
    def isIndicator(self) -> bool: ...
    def setNumStars(self, arg0: int) -> None: ...
    def getNumStars(self) -> int: ...
    def setRating(self, arg0: float) -> None: ...
    def getRating(self) -> float: ...
    def setStepSize(self, arg0: float) -> None: ...
    def getStepSize(self) -> float: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def setMax(self, arg0: int) -> None: ...
    def getAccessibilityClassName(self) -> str: ...

    class OnRatingBarChangeListener:
        def onRatingChanged(self, arg0: "RatingBar", arg1: float, arg2: bool) -> None: ...
