from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.IBinder import IBinder
from android.widget.RemoteViews import RemoteViews

class RemoteViewsService:
    def __init__(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onGetViewFactory(self, arg0: Intent) -> "RemoteViewsFactory": ...

    class RemoteViewsFactory:
        def onCreate(self) -> None: ...
        def onDataSetChanged(self) -> None: ...
        def onDestroy(self) -> None: ...
        def getCount(self) -> int: ...
        def getViewAt(self, arg0: int) -> RemoteViews: ...
        def getLoadingView(self) -> RemoteViews: ...
        def getViewTypeCount(self) -> int: ...
        def getItemId(self, arg0: int) -> int: ...
        def hasStableIds(self) -> bool: ...
