from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class ResourceCursorTreeAdapter:
    @overload
    def __init__(self, arg0: Context, arg1: Cursor, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Cursor, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Cursor, arg2: int, arg3: int) -> None: ...
    def newChildView(self, arg0: Context, arg1: Cursor, arg2: bool, arg3: ViewGroup) -> View: ...
    def newGroupView(self, arg0: Context, arg1: Cursor, arg2: bool, arg3: ViewGroup) -> View: ...
