from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class SeekBar:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setOnSeekBarChangeListener(self, arg0: "OnSeekBarChangeListener") -> None: ...
    def getAccessibilityClassName(self) -> str: ...

    class OnSeekBarChangeListener:
        def onProgressChanged(self, arg0: "SeekBar", arg1: int, arg2: bool) -> None: ...
        def onStartTrackingTouch(self, arg0: "SeekBar") -> None: ...
        def onStopTrackingTouch(self, arg0: "SeekBar") -> None: ...
