from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.view.View import View
from android.widget.ImageView import ImageView
from android.widget.TextView import TextView

class SimpleCursorTreeAdapter:
    @overload
    def __init__(self, arg0: Context, arg1: Cursor, arg2: int, arg3: int, arg4: list[str], arg5: list[int], arg6: int, arg7: int, arg8: list[str], arg9: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Cursor, arg2: int, arg3: int, arg4: list[str], arg5: list[int], arg6: int, arg7: list[str], arg8: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: Cursor, arg2: int, arg3: list[str], arg4: list[int], arg5: int, arg6: list[str], arg7: list[int]) -> None: ...
    def getViewBinder(self) -> "ViewBinder": ...
    def setViewBinder(self, arg0: "ViewBinder") -> None: ...
    def bindChildView(self, arg0: View, arg1: Context, arg2: Cursor, arg3: bool) -> None: ...
    def bindGroupView(self, arg0: View, arg1: Context, arg2: Cursor, arg3: bool) -> None: ...
    def setViewImage(self, arg0: ImageView, arg1: str) -> None: ...
    def setViewText(self, arg0: TextView, arg1: str) -> None: ...

    class ViewBinder:
        def setViewValue(self, arg0: View, arg1: Cursor, arg2: int) -> bool: ...
