from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.view.View import View
from android.widget.ImageView import ImageView
from android.widget.TextView import TextView

class SimpleCursorAdapter:
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: Cursor, arg3: list[str], arg4: list[int]) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: int, arg2: Cursor, arg3: list[str], arg4: list[int], arg5: int) -> None: ...
    def bindView(self, arg0: View, arg1: Context, arg2: Cursor) -> None: ...
    def getViewBinder(self) -> "ViewBinder": ...
    def setViewBinder(self, arg0: "ViewBinder") -> None: ...
    def setViewImage(self, arg0: ImageView, arg1: str) -> None: ...
    def setViewText(self, arg0: TextView, arg1: str) -> None: ...
    def getStringConversionColumn(self) -> int: ...
    def setStringConversionColumn(self, arg0: int) -> None: ...
    def getCursorToStringConverter(self) -> "CursorToStringConverter": ...
    def setCursorToStringConverter(self, arg0: "CursorToStringConverter") -> None: ...
    def convertToString(self, arg0: Cursor) -> str: ...
    def swapCursor(self, arg0: Cursor) -> Cursor: ...
    def changeCursorAndColumns(self, arg0: Cursor, arg1: list[str], arg2: list[int]) -> None: ...

    class CursorToStringConverter:
        def convertToString(self, arg0: Cursor) -> str: ...

    class ViewBinder:
        def setViewValue(self, arg0: View, arg1: Cursor, arg2: int) -> bool: ...
