from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Canvas import Canvas
from android.util.AttributeSet import AttributeSet

class Space:
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context) -> None: ...
    def draw(self, arg0: Canvas) -> None: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
