from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.ColorStateList import ColorStateList
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.Typeface import Typeface
from android.graphics.drawable.Drawable import Drawable
from android.graphics.drawable.Icon import Icon
from android.util.AttributeSet import AttributeSet
from android.view.MotionEvent import MotionEvent

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Mode:
    """Forward declaration for ``android.graphics.PorterDuff.Mode``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.PorterDuff.Mode')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/PorterDuff/Mode
    """
    ...

class Switch:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setSwitchTextAppearance(self, arg0: Context, arg1: int) -> None: ...
    @overload
    def setSwitchTypeface(self, arg0: Typeface, arg1: int) -> None: ...
    @overload
    def setSwitchTypeface(self, arg0: Typeface) -> None: ...
    def setSwitchPadding(self, arg0: int) -> None: ...
    def getSwitchPadding(self) -> int: ...
    def setSwitchMinWidth(self, arg0: int) -> None: ...
    def getSwitchMinWidth(self) -> int: ...
    def setThumbTextPadding(self, arg0: int) -> None: ...
    def getThumbTextPadding(self) -> int: ...
    def setTrackDrawable(self, arg0: Drawable) -> None: ...
    def setTrackResource(self, arg0: int) -> None: ...
    def getTrackDrawable(self) -> Drawable: ...
    def setTrackIcon(self, arg0: Icon) -> None: ...
    def setTrackTintList(self, arg0: ColorStateList) -> None: ...
    def getTrackTintList(self) -> ColorStateList: ...
    def setTrackTintMode(self, arg0: Mode) -> None: ...
    def setTrackTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getTrackTintMode(self) -> Mode: ...
    def getTrackTintBlendMode(self) -> BlendMode: ...
    def setThumbDrawable(self, arg0: Drawable) -> None: ...
    def setThumbResource(self, arg0: int) -> None: ...
    def getThumbDrawable(self) -> Drawable: ...
    def setThumbIcon(self, arg0: Icon) -> None: ...
    def setThumbTintList(self, arg0: ColorStateList) -> None: ...
    def getThumbTintList(self) -> ColorStateList: ...
    def setThumbTintMode(self, arg0: Mode) -> None: ...
    def setThumbTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getThumbTintMode(self) -> Mode: ...
    def getThumbTintBlendMode(self) -> BlendMode: ...
    def setSplitTrack(self, arg0: bool) -> None: ...
    def getSplitTrack(self) -> bool: ...
    def getTextOn(self) -> str: ...
    def setTextOn(self, arg0: str) -> None: ...
    def getTextOff(self) -> str: ...
    def setTextOff(self, arg0: str) -> None: ...
    def setShowText(self, arg0: bool) -> None: ...
    def getShowText(self) -> bool: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def toggle(self) -> None: ...
    def setChecked(self, arg0: bool) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    def draw(self, arg0: Canvas) -> None: ...
    def onDraw(self, arg0: Canvas) -> None: ...
    def getCompoundPaddingLeft(self) -> int: ...
    def getCompoundPaddingRight(self) -> int: ...
    def onCreateDrawableState(self, arg0: int) -> list[int]: ...
    def drawableStateChanged(self) -> None: ...
    def drawableHotspotChanged(self, arg0: float, arg1: float) -> None: ...
    def verifyDrawable(self, arg0: Drawable) -> bool: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
