from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Canvas import Canvas
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from android.view.MotionEvent import MotionEvent
from android.view.PointerIcon import PointerIcon
from android.view.View import View

class TabWidget:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def onSizeChanged(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def getChildDrawingOrder(self, arg0: int, arg1: int) -> int: ...
    def getChildTabViewAt(self, arg0: int) -> View: ...
    def getTabCount(self) -> int: ...
    @overload
    def setDividerDrawable(self, arg0: Drawable) -> None: ...
    @overload
    def setDividerDrawable(self, arg0: int) -> None: ...
    @overload
    def setLeftStripDrawable(self, arg0: Drawable) -> None: ...
    @overload
    def setLeftStripDrawable(self, arg0: int) -> None: ...
    def getLeftStripDrawable(self) -> Drawable: ...
    @overload
    def setRightStripDrawable(self, arg0: Drawable) -> None: ...
    @overload
    def setRightStripDrawable(self, arg0: int) -> None: ...
    def getRightStripDrawable(self) -> Drawable: ...
    def setStripEnabled(self, arg0: bool) -> None: ...
    def isStripEnabled(self) -> bool: ...
    def childDrawableStateChanged(self, arg0: View) -> None: ...
    def dispatchDraw(self, arg0: Canvas) -> None: ...
    def setCurrentTab(self, arg0: int) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def focusCurrentTab(self, arg0: int) -> None: ...
    def setEnabled(self, arg0: bool) -> None: ...
    def addView(self, arg0: View) -> None: ...
    def removeAllViews(self) -> None: ...
    def onResolvePointerIcon(self, arg0: MotionEvent, arg1: int) -> PointerIcon: ...
    def onFocusChange(self, arg0: View, arg1: bool) -> None: ...
