from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class TextClock:
    DEFAULT_FORMAT_12_HOUR: ClassVar[str]
    DEFAULT_FORMAT_24_HOUR: ClassVar[str]
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def getFormat12Hour(self) -> str: ...
    def setFormat12Hour(self, arg0: str) -> None: ...
    def getFormat24Hour(self) -> str: ...
    def setFormat24Hour(self, arg0: str) -> None: ...
    def refreshTime(self) -> None: ...
    def is24HourModeEnabled(self) -> bool: ...
    def getTimeZone(self) -> str: ...
    def setTimeZone(self, arg0: str) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onVisibilityAggregated(self, arg0: bool) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
