from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.ColorStateList import ColorStateList
from android.content.res.Configuration import Configuration
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.Rect import Rect
from android.graphics.Typeface import Typeface
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from android.os.Parcelable import Parcelable
from android.text.Editable import Editable
from android.text.Highlights import Highlights
from android.text.InputFilter import InputFilter
from android.text.Layout import Layout
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint
from android.text.TextWatcher import TextWatcher
from android.text.method.KeyListener import KeyListener
from android.text.method.MovementMethod import MovementMethod
from android.text.method.TransformationMethod import TransformationMethod
from android.text.style.URLSpan import URLSpan
from android.util.AttributeSet import AttributeSet
from android.view.ContentInfo import ContentInfo
from android.view.ContextMenu import ContextMenu
from android.view.DragEvent import DragEvent
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.PointerIcon import PointerIcon
from android.view.View import View
from android.view.accessibility.AccessibilityEvent import AccessibilityEvent
from android.view.accessibility.AccessibilityNodeInfo import AccessibilityNodeInfo
from android.view.autofill.AutofillValue import AutofillValue
from android.view.inputmethod.CompletionInfo import CompletionInfo
from android.view.inputmethod.CorrectionInfo import CorrectionInfo
from android.view.inputmethod.EditorInfo import EditorInfo
from android.view.inputmethod.ExtractedText import ExtractedText
from android.view.inputmethod.ExtractedTextRequest import ExtractedTextRequest
from android.view.inputmethod.InputConnection import InputConnection
from android.view.textclassifier.TextClassifier import TextClassifier
from android.widget.Scroller import Scroller
from java.util.Locale import Locale
from java.util.function.Consumer import Consumer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Mode:
    """Forward declaration for ``android.graphics.PorterDuff.Mode``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.PorterDuff.Mode')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/PorterDuff/Mode
    """
    ...
class FontMetrics:
    """Forward declaration for ``android.graphics.Paint.FontMetrics``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.Paint.FontMetrics')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/Paint/FontMetrics
    """
    ...
class Params:
    """Forward declaration for ``android.text.PrecomputedText.Params``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.text.PrecomputedText.Params')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/text/PrecomputedText/Params
    """
    ...
class Factory:
    """Forward declaration for ``android.text.Editable.Factory``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.text.Editable.Factory')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/text/Editable/Factory
    """
    ...
class TruncateAt:
    """Forward declaration for ``android.text.TextUtils.TruncateAt``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.text.TextUtils.TruncateAt')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/text/TextUtils/TruncateAt
    """
    ...
class Callback:
    """Forward declaration for ``android.view.ActionMode.Callback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ActionMode.Callback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ActionMode/Callback
    """
    ...
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class TextView:
    AUTO_SIZE_TEXT_TYPE_NONE: ClassVar[int]
    AUTO_SIZE_TEXT_TYPE_UNIFORM: ClassVar[int]
    FOCUSED_SEARCH_RESULT_INDEX_NONE: ClassVar[int]
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def setAutoSizeTextTypeWithDefaults(self, arg0: int) -> None: ...
    def setAutoSizeTextTypeUniformWithConfiguration(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def setAutoSizeTextTypeUniformWithPresetSizes(self, arg0: list[int], arg1: int) -> None: ...
    def getAutoSizeTextType(self) -> int: ...
    def getAutoSizeStepGranularity(self) -> int: ...
    def getAutoSizeMinTextSize(self) -> int: ...
    def getAutoSizeMaxTextSize(self) -> int: ...
    def getAutoSizeTextAvailableSizes(self) -> list[int]: ...
    def setEnabled(self, arg0: bool) -> None: ...
    @overload
    def setTypeface(self, arg0: Typeface, arg1: int) -> None: ...
    @overload
    def setTypeface(self, arg0: Typeface) -> None: ...
    def getDefaultEditable(self) -> bool: ...
    def getDefaultMovementMethod(self) -> MovementMethod: ...
    def getText(self) -> str: ...
    def length(self) -> int: ...
    def getEditableText(self) -> Editable: ...
    def getLineHeight(self) -> int: ...
    def getLayout(self) -> Layout: ...
    def getKeyListener(self) -> KeyListener: ...
    def setKeyListener(self, arg0: KeyListener) -> None: ...
    def getMovementMethod(self) -> MovementMethod: ...
    def setMovementMethod(self, arg0: MovementMethod) -> None: ...
    def getTransformationMethod(self) -> TransformationMethod: ...
    def setTransformationMethod(self, arg0: TransformationMethod) -> None: ...
    def getCompoundPaddingTop(self) -> int: ...
    def getCompoundPaddingBottom(self) -> int: ...
    def getCompoundPaddingLeft(self) -> int: ...
    def getCompoundPaddingRight(self) -> int: ...
    def getCompoundPaddingStart(self) -> int: ...
    def getCompoundPaddingEnd(self) -> int: ...
    def getExtendedPaddingTop(self) -> int: ...
    def getExtendedPaddingBottom(self) -> int: ...
    def getTotalPaddingLeft(self) -> int: ...
    def getTotalPaddingRight(self) -> int: ...
    def getTotalPaddingStart(self) -> int: ...
    def getTotalPaddingEnd(self) -> int: ...
    def getTotalPaddingTop(self) -> int: ...
    def getTotalPaddingBottom(self) -> int: ...
    def setCompoundDrawables(self, arg0: Drawable, arg1: Drawable, arg2: Drawable, arg3: Drawable) -> None: ...
    @overload
    def setCompoundDrawablesWithIntrinsicBounds(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def setCompoundDrawablesWithIntrinsicBounds(self, arg0: Drawable, arg1: Drawable, arg2: Drawable, arg3: Drawable) -> None: ...
    def setCompoundDrawablesRelative(self, arg0: Drawable, arg1: Drawable, arg2: Drawable, arg3: Drawable) -> None: ...
    @overload
    def setCompoundDrawablesRelativeWithIntrinsicBounds(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def setCompoundDrawablesRelativeWithIntrinsicBounds(self, arg0: Drawable, arg1: Drawable, arg2: Drawable, arg3: Drawable) -> None: ...
    def getCompoundDrawables(self) -> list[Drawable]: ...
    def getCompoundDrawablesRelative(self) -> list[Drawable]: ...
    def setCompoundDrawablePadding(self, arg0: int) -> None: ...
    def getCompoundDrawablePadding(self) -> int: ...
    def setCompoundDrawableTintList(self, arg0: ColorStateList) -> None: ...
    def getCompoundDrawableTintList(self) -> ColorStateList: ...
    def setCompoundDrawableTintMode(self, arg0: Mode) -> None: ...
    def setCompoundDrawableTintBlendMode(self, arg0: BlendMode) -> None: ...
    def getCompoundDrawableTintMode(self) -> Mode: ...
    def getCompoundDrawableTintBlendMode(self) -> BlendMode: ...
    def setPadding(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def setPaddingRelative(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def setFirstBaselineToTopHeight(self, arg0: int) -> None: ...
    def setLastBaselineToBottomHeight(self, arg0: int) -> None: ...
    def getFirstBaselineToTopHeight(self) -> int: ...
    def getLastBaselineToBottomHeight(self) -> int: ...
    def getAutoLinkMask(self) -> int: ...
    @overload
    def setTextSelectHandle(self, arg0: Drawable) -> None: ...
    @overload
    def setTextSelectHandle(self, arg0: int) -> None: ...
    def getTextSelectHandle(self) -> Drawable: ...
    @overload
    def setTextSelectHandleLeft(self, arg0: Drawable) -> None: ...
    @overload
    def setTextSelectHandleLeft(self, arg0: int) -> None: ...
    def getTextSelectHandleLeft(self) -> Drawable: ...
    @overload
    def setTextSelectHandleRight(self, arg0: Drawable) -> None: ...
    @overload
    def setTextSelectHandleRight(self, arg0: int) -> None: ...
    def getTextSelectHandleRight(self) -> Drawable: ...
    @overload
    def setTextCursorDrawable(self, arg0: Drawable) -> None: ...
    @overload
    def setTextCursorDrawable(self, arg0: int) -> None: ...
    def getTextCursorDrawable(self) -> Drawable: ...
    @overload
    def setTextAppearance(self, arg0: int) -> None: ...
    @overload
    def setTextAppearance(self, arg0: Context, arg1: int) -> None: ...
    def getTextLocale(self) -> Locale: ...
    def getTextLocales(self) -> LocaleList: ...
    def setTextLocale(self, arg0: Locale) -> None: ...
    def setTextLocales(self, arg0: LocaleList) -> None: ...
    def onConfigurationChanged(self, arg0: Configuration) -> None: ...
    def getTextSize(self) -> float: ...
    @overload
    def setTextSize(self, arg0: float) -> None: ...
    @overload
    def setTextSize(self, arg0: int, arg1: float) -> None: ...
    def getTextSizeUnit(self) -> int: ...
    def getTextScaleX(self) -> float: ...
    def setTextScaleX(self, arg0: float) -> None: ...
    def getTypeface(self) -> Typeface: ...
    def setElegantTextHeight(self, arg0: bool) -> None: ...
    def setFallbackLineSpacing(self, arg0: bool) -> None: ...
    def setUseBoundsForWidth(self, arg0: bool) -> None: ...
    def getUseBoundsForWidth(self) -> bool: ...
    def setShiftDrawingOffsetForStartOverhang(self, arg0: bool) -> None: ...
    def getShiftDrawingOffsetForStartOverhang(self) -> bool: ...
    def setMinimumFontMetrics(self, arg0: FontMetrics) -> None: ...
    def getMinimumFontMetrics(self) -> FontMetrics: ...
    def isLocalePreferredLineHeightForMinimumUsed(self) -> bool: ...
    def setLocalePreferredLineHeightForMinimumUsed(self, arg0: bool) -> None: ...
    def isFallbackLineSpacing(self) -> bool: ...
    def isElegantTextHeight(self) -> bool: ...
    def getLetterSpacing(self) -> float: ...
    def setLetterSpacing(self, arg0: float) -> None: ...
    def getFontFeatureSettings(self) -> str: ...
    def getFontVariationSettings(self) -> str: ...
    def setBreakStrategy(self, arg0: int) -> None: ...
    def getBreakStrategy(self) -> int: ...
    def setHyphenationFrequency(self, arg0: int) -> None: ...
    def getHyphenationFrequency(self) -> int: ...
    def setLineBreakStyle(self, arg0: int) -> None: ...
    def setLineBreakWordStyle(self, arg0: int) -> None: ...
    def getLineBreakStyle(self) -> int: ...
    def getLineBreakWordStyle(self) -> int: ...
    def getTextMetricsParams(self) -> Params: ...
    def setTextMetricsParams(self, arg0: Params) -> None: ...
    def setJustificationMode(self, arg0: int) -> None: ...
    def getJustificationMode(self) -> int: ...
    def setFontFeatureSettings(self, arg0: str) -> None: ...
    def setFontVariationSettings(self, arg0: str) -> bool: ...
    @overload
    def setTextColor(self, arg0: int) -> None: ...
    @overload
    def setTextColor(self, arg0: ColorStateList) -> None: ...
    def getTextColors(self) -> ColorStateList: ...
    def getCurrentTextColor(self) -> int: ...
    def setHighlightColor(self, arg0: int) -> None: ...
    def getHighlightColor(self) -> int: ...
    def setShowSoftInputOnFocus(self, arg0: bool) -> None: ...
    def getShowSoftInputOnFocus(self) -> bool: ...
    def setShadowLayer(self, arg0: float, arg1: float, arg2: float, arg3: int) -> None: ...
    def getShadowRadius(self) -> float: ...
    def getShadowDx(self) -> float: ...
    def getShadowDy(self) -> float: ...
    def getShadowColor(self) -> int: ...
    def getPaint(self) -> TextPaint: ...
    def setAutoLinkMask(self, arg0: int) -> None: ...
    def setLinksClickable(self, arg0: bool) -> None: ...
    def getLinksClickable(self) -> bool: ...
    def getUrls(self) -> list[URLSpan]: ...
    @overload
    def setHintTextColor(self, arg0: int) -> None: ...
    @overload
    def setHintTextColor(self, arg0: ColorStateList) -> None: ...
    def getHintTextColors(self) -> ColorStateList: ...
    def getCurrentHintTextColor(self) -> int: ...
    @overload
    def setLinkTextColor(self, arg0: int) -> None: ...
    @overload
    def setLinkTextColor(self, arg0: ColorStateList) -> None: ...
    def getLinkTextColors(self) -> ColorStateList: ...
    def setGravity(self, arg0: int) -> None: ...
    def getGravity(self) -> int: ...
    def getPaintFlags(self) -> int: ...
    def setPaintFlags(self, arg0: int) -> None: ...
    def setHorizontallyScrolling(self, arg0: bool) -> None: ...
    def isHorizontallyScrollable(self) -> bool: ...
    def setMinLines(self, arg0: int) -> None: ...
    def getMinLines(self) -> int: ...
    def setMinHeight(self, arg0: int) -> None: ...
    def getMinHeight(self) -> int: ...
    def setMaxLines(self, arg0: int) -> None: ...
    def getMaxLines(self) -> int: ...
    def setMaxHeight(self, arg0: int) -> None: ...
    def getMaxHeight(self) -> int: ...
    def setLines(self, arg0: int) -> None: ...
    def setHeight(self, arg0: int) -> None: ...
    def setMinEms(self, arg0: int) -> None: ...
    def getMinEms(self) -> int: ...
    def setMinWidth(self, arg0: int) -> None: ...
    def getMinWidth(self) -> int: ...
    def setMaxEms(self, arg0: int) -> None: ...
    def getMaxEms(self) -> int: ...
    def setMaxWidth(self, arg0: int) -> None: ...
    def getMaxWidth(self) -> int: ...
    def setEms(self, arg0: int) -> None: ...
    def setWidth(self, arg0: int) -> None: ...
    def setLineSpacing(self, arg0: float, arg1: float) -> None: ...
    def getLineSpacingMultiplier(self) -> float: ...
    def getLineSpacingExtra(self) -> float: ...
    @overload
    def setLineHeight(self, arg0: int) -> None: ...
    @overload
    def setLineHeight(self, arg0: int, arg1: float) -> None: ...
    def setHighlights(self, arg0: Highlights) -> None: ...
    def getHighlights(self) -> Highlights: ...
    def setSearchResultHighlights(self, *arg0: int) -> None: ...
    def getSearchResultHighlights(self) -> list[int]: ...
    def setFocusedSearchResultIndex(self, arg0: int) -> None: ...
    def getFocusedSearchResultIndex(self) -> int: ...
    def setSearchResultHighlightColor(self, arg0: int) -> None: ...
    def getSearchResultHighlightColor(self) -> int: ...
    def setFocusedSearchResultHighlightColor(self, arg0: int) -> None: ...
    def getFocusedSearchResultHighlightColor(self) -> int: ...
    @overload
    def append(self, arg0: str) -> None: ...
    @overload
    def append(self, arg0: str, arg1: int, arg2: int) -> None: ...
    def drawableStateChanged(self) -> None: ...
    def drawableHotspotChanged(self, arg0: float, arg1: float) -> None: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, arg0: Parcelable) -> None: ...
    def setFreezesText(self, arg0: bool) -> None: ...
    def getFreezesText(self) -> bool: ...
    def setEditableFactory(self, arg0: Factory) -> None: ...
    def setSpannableFactory(self, arg0: Factory) -> None: ...
    @overload
    def setText(self, arg0: str) -> None: ...
    @overload
    def setText(self, arg0: str, arg1: "BufferType") -> None: ...
    @overload
    def setText(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    @overload
    def setText(self, arg0: int) -> None: ...
    @overload
    def setText(self, arg0: int, arg1: "BufferType") -> None: ...
    @overload
    def setTextKeepState(self, arg0: str) -> None: ...
    @overload
    def setTextKeepState(self, arg0: str, arg1: "BufferType") -> None: ...
    @overload
    def setHint(self, arg0: str) -> None: ...
    @overload
    def setHint(self, arg0: int) -> None: ...
    def getHint(self) -> str: ...
    def isSingleLine(self) -> bool: ...
    def setInputType(self, arg0: int) -> None: ...
    def setRawInputType(self, arg0: int) -> None: ...
    def getAutofillHints(self) -> list[str]: ...
    def getInputType(self) -> int: ...
    def setImeOptions(self, arg0: int) -> None: ...
    def getImeOptions(self) -> int: ...
    def setImeActionLabel(self, arg0: str, arg1: int) -> None: ...
    def getImeActionLabel(self) -> str: ...
    def getImeActionId(self) -> int: ...
    def setOnEditorActionListener(self, arg0: "OnEditorActionListener") -> None: ...
    def onEditorAction(self, arg0: int) -> None: ...
    def setPrivateImeOptions(self, arg0: str) -> None: ...
    def getPrivateImeOptions(self) -> str: ...
    def setInputExtras(self, arg0: int) -> None: ...
    def getInputExtras(self, arg0: bool) -> Bundle: ...
    def setImeHintLocales(self, arg0: LocaleList) -> None: ...
    def getImeHintLocales(self) -> LocaleList: ...
    def getError(self) -> str: ...
    @overload
    def setError(self, arg0: str) -> None: ...
    @overload
    def setError(self, arg0: str, arg1: Drawable) -> None: ...
    def setFrame(self, arg0: int, arg1: int, arg2: int, arg3: int) -> bool: ...
    def setFilters(self, arg0: list[InputFilter]) -> None: ...
    def getFilters(self) -> list[InputFilter]: ...
    def onPreDraw(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onScreenStateChanged(self, arg0: int) -> None: ...
    def isPaddingOffsetRequired(self) -> bool: ...
    def getLeftPaddingOffset(self) -> int: ...
    def getTopPaddingOffset(self) -> int: ...
    def getBottomPaddingOffset(self) -> int: ...
    def getRightPaddingOffset(self) -> int: ...
    def verifyDrawable(self, arg0: Drawable) -> bool: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def invalidateDrawable(self, arg0: Drawable) -> None: ...
    def hasOverlappingRendering(self) -> bool: ...
    def isTextSelectable(self) -> bool: ...
    def setTextIsSelectable(self, arg0: bool) -> None: ...
    def onCreateDrawableState(self, arg0: int) -> list[int]: ...
    def onDraw(self, arg0: Canvas) -> None: ...
    def getFocusedRect(self, arg0: Rect) -> None: ...
    def getLineCount(self) -> int: ...
    def getLineBounds(self, arg0: int, arg1: Rect) -> int: ...
    def getBaseline(self) -> int: ...
    def onResolvePointerIcon(self, arg0: MotionEvent, arg1: int) -> PointerIcon: ...
    def onKeyPreIme(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def onKeyDown(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def onKeyMultiple(self, arg0: int, arg1: int, arg2: KeyEvent) -> bool: ...
    def onKeyUp(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def onCheckIsTextEditor(self) -> bool: ...
    def onCreateInputConnection(self, arg0: EditorInfo) -> InputConnection: ...
    def extractText(self, arg0: ExtractedTextRequest, arg1: ExtractedText) -> bool: ...
    def setExtractedText(self, arg0: ExtractedText) -> None: ...
    def onCommitCompletion(self, arg0: CompletionInfo) -> None: ...
    def onCommitCorrection(self, arg0: CorrectionInfo) -> None: ...
    def beginBatchEdit(self) -> None: ...
    def endBatchEdit(self) -> None: ...
    def onBeginBatchEdit(self) -> None: ...
    def onEndBatchEdit(self) -> None: ...
    def onPrivateIMECommand(self, arg0: str, arg1: Bundle) -> bool: ...
    def setIncludeFontPadding(self, arg0: bool) -> None: ...
    def getIncludeFontPadding(self) -> bool: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def bringPointIntoView(self, arg0: int) -> bool: ...
    @overload
    def bringPointIntoView(self, arg0: int, arg1: bool) -> bool: ...
    def moveCursorToVisibleOffset(self) -> bool: ...
    def computeScroll(self) -> None: ...
    def debug(self, arg0: int) -> None: ...
    def getSelectionStart(self) -> int: ...
    def getSelectionEnd(self) -> int: ...
    def hasSelection(self) -> bool: ...
    @overload
    def setSingleLine(self) -> None: ...
    @overload
    def setSingleLine(self, arg0: bool) -> None: ...
    def setAllCaps(self, arg0: bool) -> None: ...
    def isAllCaps(self) -> bool: ...
    def setEllipsize(self, arg0: TruncateAt) -> None: ...
    def setMarqueeRepeatLimit(self, arg0: int) -> None: ...
    def getMarqueeRepeatLimit(self) -> int: ...
    def getEllipsize(self) -> TruncateAt: ...
    def setSelectAllOnFocus(self, arg0: bool) -> None: ...
    def setCursorVisible(self, arg0: bool) -> None: ...
    def isCursorVisible(self) -> bool: ...
    def onTextChanged(self, arg0: str, arg1: int, arg2: int, arg3: int) -> None: ...
    def onSelectionChanged(self, arg0: int, arg1: int) -> None: ...
    def addTextChangedListener(self, arg0: TextWatcher) -> None: ...
    def removeTextChangedListener(self, arg0: TextWatcher) -> None: ...
    def onFocusChanged(self, arg0: bool, arg1: int, arg2: Rect) -> None: ...
    def onWindowFocusChanged(self, arg0: bool) -> None: ...
    def onVisibilityChanged(self, arg0: View, arg1: int) -> None: ...
    def onVisibilityAggregated(self, arg0: bool) -> None: ...
    def clearComposingText(self) -> None: ...
    def setSelected(self, arg0: bool) -> None: ...
    def onTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def onGenericMotionEvent(self, arg0: MotionEvent) -> bool: ...
    def onCreateContextMenu(self, arg0: ContextMenu) -> None: ...
    @overload
    def showContextMenu(self) -> bool: ...
    @overload
    def showContextMenu(self, arg0: float, arg1: float) -> bool: ...
    def didTouchFocusSelect(self) -> bool: ...
    def cancelLongPress(self) -> None: ...
    def onTrackballEvent(self, arg0: MotionEvent) -> bool: ...
    def setScroller(self, arg0: Scroller) -> None: ...
    def getLeftFadingEdgeStrength(self) -> float: ...
    def getRightFadingEdgeStrength(self) -> float: ...
    def computeHorizontalScrollRange(self) -> int: ...
    def computeVerticalScrollRange(self) -> int: ...
    def computeVerticalScrollExtent(self) -> int: ...
    def findViewsWithText(self, arg0: list, arg1: str, arg2: int) -> None: ...
    def onKeyShortcut(self, arg0: int, arg1: KeyEvent) -> bool: ...
    def isAutoHandwritingEnabled(self) -> bool: ...
    def getAccessibilityClassName(self) -> str: ...
    def autofill(self, arg0: AutofillValue) -> None: ...
    def getAutofillType(self) -> int: ...
    def getAutofillValue(self) -> AutofillValue: ...
    def addExtraDataToAccessibilityNodeInfo(self, arg0: AccessibilityNodeInfo, arg1: str, arg2: Bundle) -> None: ...
    def sendAccessibilityEventUnchecked(self, arg0: AccessibilityEvent) -> None: ...
    def isInputMethodTarget(self) -> bool: ...
    def onTextContextMenuItem(self, arg0: int) -> bool: ...
    def performLongClick(self) -> bool: ...
    def onScrollChanged(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def isSuggestionsEnabled(self) -> bool: ...
    def setCustomSelectionActionModeCallback(self, arg0: Callback) -> None: ...
    def getCustomSelectionActionModeCallback(self) -> Callback: ...
    def setCustomInsertionActionModeCallback(self, arg0: Callback) -> None: ...
    def getCustomInsertionActionModeCallback(self) -> Callback: ...
    def setTextClassifier(self, arg0: TextClassifier) -> None: ...
    def getTextClassifier(self) -> TextClassifier: ...
    def getOffsetForPosition(self, arg0: float, arg1: float) -> int: ...
    def onDragEvent(self, arg0: DragEvent) -> bool: ...
    def onRtlPropertiesChanged(self, arg0: int) -> None: ...
    def getTextDirectionHeuristic(self) -> TextDirectionHeuristic: ...
    def onReceiveContent(self, arg0: ContentInfo) -> ContentInfo: ...
    def onCreateViewTranslationRequest(self, arg0: list[int], arg1: Consumer) -> None: ...

    class BufferType:
        NORMAL: ClassVar["BufferType"]
        SPANNABLE: ClassVar["BufferType"]
        EDITABLE: ClassVar["BufferType"]
        @staticmethod
        def values() -> list["BufferType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "BufferType": ...

    class OnEditorActionListener:
        def onEditorAction(self, arg0: "TextView", arg1: int, arg2: KeyEvent) -> bool: ...

    class SavedState:
        CREATOR: ClassVar[Creator]
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def toString(self) -> str: ...
