from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.drawable.Drawable import Drawable
from android.os.Parcelable import Parcelable
from android.util.AttributeSet import AttributeSet
from android.view.Menu import Menu
from android.view.MenuItem import MenuItem
from android.view.MotionEvent import MotionEvent

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OnClickListener:
    """Forward declaration for ``android.view.View.OnClickListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.View.OnClickListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/View/OnClickListener
    """
    ...
class MarginLayoutParams:
    """Forward declaration for ``android.view.ViewGroup.MarginLayoutParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ViewGroup.MarginLayoutParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ViewGroup/MarginLayoutParams
    """
    ...

class Toolbar:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def setPopupTheme(self, arg0: int) -> None: ...
    def getPopupTheme(self) -> int: ...
    def setTitleMargin(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    def getTitleMarginStart(self) -> int: ...
    def setTitleMarginStart(self, arg0: int) -> None: ...
    def getTitleMarginTop(self) -> int: ...
    def setTitleMarginTop(self, arg0: int) -> None: ...
    def getTitleMarginEnd(self) -> int: ...
    def setTitleMarginEnd(self, arg0: int) -> None: ...
    def getTitleMarginBottom(self) -> int: ...
    def setTitleMarginBottom(self, arg0: int) -> None: ...
    def onRtlPropertiesChanged(self, arg0: int) -> None: ...
    @overload
    def setLogo(self, arg0: int) -> None: ...
    @overload
    def setLogo(self, arg0: Drawable) -> None: ...
    def isOverflowMenuShowing(self) -> bool: ...
    def showOverflowMenu(self) -> bool: ...
    def hideOverflowMenu(self) -> bool: ...
    def dismissPopupMenus(self) -> None: ...
    def getLogo(self) -> Drawable: ...
    @overload
    def setLogoDescription(self, arg0: int) -> None: ...
    @overload
    def setLogoDescription(self, arg0: str) -> None: ...
    def getLogoDescription(self) -> str: ...
    def hasExpandedActionView(self) -> bool: ...
    def collapseActionView(self) -> None: ...
    def getTitle(self) -> str: ...
    @overload
    def setTitle(self, arg0: int) -> None: ...
    @overload
    def setTitle(self, arg0: str) -> None: ...
    def getSubtitle(self) -> str: ...
    @overload
    def setSubtitle(self, arg0: int) -> None: ...
    @overload
    def setSubtitle(self, arg0: str) -> None: ...
    def setTitleTextAppearance(self, arg0: Context, arg1: int) -> None: ...
    def setSubtitleTextAppearance(self, arg0: Context, arg1: int) -> None: ...
    def setTitleTextColor(self, arg0: int) -> None: ...
    def setSubtitleTextColor(self, arg0: int) -> None: ...
    def getNavigationContentDescription(self) -> str: ...
    @overload
    def setNavigationContentDescription(self, arg0: int) -> None: ...
    @overload
    def setNavigationContentDescription(self, arg0: str) -> None: ...
    @overload
    def setNavigationIcon(self, arg0: int) -> None: ...
    @overload
    def setNavigationIcon(self, arg0: Drawable) -> None: ...
    def getNavigationIcon(self) -> Drawable: ...
    def setNavigationOnClickListener(self, arg0: OnClickListener) -> None: ...
    def getCollapseContentDescription(self) -> str: ...
    @overload
    def setCollapseContentDescription(self, arg0: int) -> None: ...
    @overload
    def setCollapseContentDescription(self, arg0: str) -> None: ...
    def getCollapseIcon(self) -> Drawable: ...
    @overload
    def setCollapseIcon(self, arg0: int) -> None: ...
    @overload
    def setCollapseIcon(self, arg0: Drawable) -> None: ...
    def getMenu(self) -> Menu: ...
    def setOverflowIcon(self, arg0: Drawable) -> None: ...
    def getOverflowIcon(self) -> Drawable: ...
    def inflateMenu(self, arg0: int) -> None: ...
    def setOnMenuItemClickListener(self, arg0: "OnMenuItemClickListener") -> None: ...
    def setContentInsetsRelative(self, arg0: int, arg1: int) -> None: ...
    def getContentInsetStart(self) -> int: ...
    def getContentInsetEnd(self) -> int: ...
    def setContentInsetsAbsolute(self, arg0: int, arg1: int) -> None: ...
    def getContentInsetLeft(self) -> int: ...
    def getContentInsetRight(self) -> int: ...
    def getContentInsetStartWithNavigation(self) -> int: ...
    def setContentInsetStartWithNavigation(self, arg0: int) -> None: ...
    def getContentInsetEndWithActions(self) -> int: ...
    def setContentInsetEndWithActions(self, arg0: int) -> None: ...
    def getCurrentContentInsetStart(self) -> int: ...
    def getCurrentContentInsetEnd(self) -> int: ...
    def getCurrentContentInsetLeft(self) -> int: ...
    def getCurrentContentInsetRight(self) -> int: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, arg0: Parcelable) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onTouchEvent(self, arg0: MotionEvent) -> bool: ...
    def onMeasure(self, arg0: int, arg1: int) -> None: ...
    def onLayout(self, arg0: bool, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def generateLayoutParams(self, arg0: AttributeSet) -> "LayoutParams": ...
    @overload
    def generateLayoutParams(self, arg0: "LayoutParams") -> "LayoutParams": ...
    def generateDefaultLayoutParams(self) -> "LayoutParams": ...
    def checkLayoutParams(self, arg0: "LayoutParams") -> bool: ...

    class LayoutParams:
        @overload
        def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: int) -> None: ...
        @overload
        def __init__(self, arg0: "LayoutParams") -> None: ...
        @overload
        def __init__(self, arg0: "LayoutParams") -> None: ...
        @overload
        def __init__(self, arg0: MarginLayoutParams) -> None: ...
        @overload
        def __init__(self, arg0: "LayoutParams") -> None: ...

    class OnMenuItemClickListener:
        def onMenuItemClick(self, arg0: MenuItem) -> bool: ...
