from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.widget.TextView import TextView

class TwoLineListItem:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet, arg2: int, arg3: int) -> None: ...
    def onFinishInflate(self) -> None: ...
    def getText1(self) -> TextView: ...
    def getText2(self) -> TextView: ...
    def getAccessibilityClassName(self) -> str: ...
