from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class ViewFlipper:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onWindowVisibilityChanged(self, arg0: int) -> None: ...
    def setFlipInterval(self, arg0: int) -> None: ...
    def getFlipInterval(self) -> int: ...
    def startFlipping(self) -> None: ...
    def stopFlipping(self) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def isFlipping(self) -> bool: ...
    def setAutoStart(self, arg0: bool) -> None: ...
    def isAutoStart(self) -> bool: ...
