from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.View import View
from android.view.animation.Animation import Animation

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class LayoutParams:
    """Forward declaration for ``android.view.ViewGroup.LayoutParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.view.ViewGroup.LayoutParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/view/ViewGroup/LayoutParams
    """
    ...

class ViewAnimator:
    @overload
    def __init__(self, arg0: Context) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    def setDisplayedChild(self, arg0: int) -> None: ...
    def getDisplayedChild(self) -> int: ...
    def showNext(self) -> None: ...
    def showPrevious(self) -> None: ...
    def addView(self, arg0: View, arg1: int, arg2: LayoutParams) -> None: ...
    def removeAllViews(self) -> None: ...
    def removeView(self, arg0: View) -> None: ...
    def removeViewAt(self, arg0: int) -> None: ...
    def removeViewInLayout(self, arg0: View) -> None: ...
    def removeViews(self, arg0: int, arg1: int) -> None: ...
    def removeViewsInLayout(self, arg0: int, arg1: int) -> None: ...
    def getCurrentView(self) -> View: ...
    def getInAnimation(self) -> Animation: ...
    @overload
    def setInAnimation(self, arg0: Animation) -> None: ...
    @overload
    def setInAnimation(self, arg0: Context, arg1: int) -> None: ...
    def getOutAnimation(self) -> Animation: ...
    @overload
    def setOutAnimation(self, arg0: Animation) -> None: ...
    @overload
    def setOutAnimation(self, arg0: Context, arg1: int) -> None: ...
    def getAnimateFirstView(self) -> bool: ...
    def setAnimateFirstView(self, arg0: bool) -> None: ...
    def getBaseline(self) -> int: ...
    def getAccessibilityClassName(self) -> str: ...
