from typing import Any, ClassVar, overload

class LiteSdkInfo:
    def __init__(self, arg0: "Context") -> None: ...
    def getLiteSdkVersion(self) -> "zzez": ...
    def getAdapterCreator(self) -> "zzbvj": ...
