from typing import Any, ClassVar, overload

class zzaz:
    def __init__(self) -> None: ...
    def zza(self, arg0: "AdListener") -> None: ...
    def onAdClosed(self) -> None: ...
    def onAdFailedToLoad(self, arg0: "LoadAdError") -> None: ...
    def onAdOpened(self) -> None: ...
    def onAdLoaded(self) -> None: ...
    def onAdImpression(self) -> None: ...
    def onAdClicked(self) -> None: ...
