from typing import Any, ClassVar, overload

class zzba:
    def __init__(self) -> None: ...
    @staticmethod
    def zza() -> "zzbiq": ...
    @staticmethod
    def zzb() -> "zzbip": ...
    @staticmethod
    def zzc() -> "zzbiv": ...
    @staticmethod
    def zzd() -> "zzbig": ...
