from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zze import zze

class zzbh:
    def zzb(self) -> None: ...
    def zzc(self, arg0: int) -> None: ...
    def zze(self) -> None: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzh(self) -> None: ...
    def zzj(self) -> None: ...
    def zzd(self, arg0: zze) -> None: ...
    def zzi(self) -> None: ...
