from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzbe import zzbe
from android.gms.ads.internal.client.zzbh import zzbh
from android.gms.ads.internal.client.zzbk import zzbk
from android.gms.ads.internal.client.zzby import zzby
from android.gms.ads.internal.client.zzcl import zzcl
from android.gms.ads.internal.client.zzcp import zzcp
from android.gms.ads.internal.client.zzcs import zzcs
from android.gms.ads.internal.client.zzdq import zzdq
from android.gms.ads.internal.client.zzdx import zzdx
from android.gms.ads.internal.client.zzea import zzea
from android.gms.ads.internal.client.zzee import zzee
from android.gms.ads.internal.client.zzfw import zzfw
from android.gms.ads.internal.client.zzm import zzm
from android.gms.ads.internal.client.zzr import zzr
from android.gms.ads.internal.client.zzx import zzx
from android.gms.internal.ads.zzbgt import zzbgt
from android.gms.internal.ads.zzbjs import zzbjs
from android.gms.internal.ads.zzbzr import zzbzr
from android.gms.internal.ads.zzbzu import zzbzu
from android.gms.internal.ads.zzccc import zzccc

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...
class Bundle:
    """Forward declaration for ``android.os.Bundle``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Bundle')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Bundle
    """
    ...

class zzbu:
    def zzb(self) -> IObjectWrapper: ...
    def zzc(self) -> None: ...
    def zzd(self) -> bool: ...
    def zze(self, arg0: zzm) -> bool: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzdS(self, arg0: zzbh) -> None: ...
    def zzi(self, arg0: zzcl) -> None: ...
    def zzl(self) -> None: ...
    def zzm(self) -> None: ...
    def zzn(self) -> zzr: ...
    def zzo(self, arg0: zzr) -> None: ...
    def zzp(self, arg0: zzbzr) -> None: ...
    def zzq(self, arg0: zzbzu, arg1: str) -> None: ...
    def zzr(self) -> str: ...
    def zzx(self, arg0: zzbjs) -> None: ...
    def zzy(self, arg0: zzbe) -> None: ...
    def zzz(self, arg0: bool) -> None: ...
    def zzB(self) -> bool: ...
    def zzC(self, arg0: zzccc) -> None: ...
    def zzD(self, arg0: str) -> None: ...
    def zzF(self) -> zzea: ...
    def zzG(self, arg0: zzfw) -> None: ...
    def zzH(self, arg0: zzee) -> None: ...
    def zzu(self) -> str: ...
    def zzv(self) -> zzcl: ...
    def zzw(self) -> zzbh: ...
    def zzK(self, arg0: bool) -> None: ...
    def zzs(self) -> str: ...
    def zzj(self, arg0: zzby) -> None: ...
    def zzk(self) -> Bundle: ...
    def zzE(self, arg0: str) -> None: ...
    def zzI(self, arg0: zzx) -> None: ...
    def zzJ(self, arg0: zzbgt) -> None: ...
    def zzt(self) -> zzdx: ...
    def zzP(self, arg0: zzdq) -> None: ...
    def zzQ(self, arg0: zzm, arg1: zzbk) -> None: ...
    def zzR(self, arg0: IObjectWrapper) -> None: ...
    def zzS(self, arg0: zzcs) -> None: ...
    def zzA(self) -> bool: ...
    def zzU(self) -> int: ...
    def zzT(self, arg0: int) -> None: ...
    def zzY(self, arg0: zzcp) -> None: ...
