from typing import Any, ClassVar, overload

class zzbu:
    def zzb(self) -> "IObjectWrapper": ...
    def zzc(self) -> None: ...
    def zzd(self) -> bool: ...
    def zze(self, arg0: "zzm") -> bool: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzdS(self, arg0: "zzbh") -> None: ...
    def zzi(self, arg0: "zzcl") -> None: ...
    def zzl(self) -> None: ...
    def zzm(self) -> None: ...
    def zzn(self) -> "zzr": ...
    def zzo(self, arg0: "zzr") -> None: ...
    def zzp(self, arg0: "zzbzr") -> None: ...
    def zzq(self, arg0: "zzbzu", arg1: str) -> None: ...
    def zzr(self) -> str: ...
    def zzx(self, arg0: "zzbjs") -> None: ...
    def zzy(self, arg0: "zzbe") -> None: ...
    def zzz(self, arg0: bool) -> None: ...
    def zzB(self) -> bool: ...
    def zzC(self, arg0: "zzccc") -> None: ...
    def zzD(self, arg0: str) -> None: ...
    def zzF(self) -> "zzea": ...
    def zzG(self, arg0: "zzfw") -> None: ...
    def zzH(self, arg0: "zzee") -> None: ...
    def zzu(self) -> str: ...
    def zzv(self) -> "zzcl": ...
    def zzw(self) -> "zzbh": ...
    def zzK(self, arg0: bool) -> None: ...
    def zzs(self) -> str: ...
    def zzj(self, arg0: "zzby") -> None: ...
    def zzk(self) -> "Bundle": ...
    def zzE(self, arg0: str) -> None: ...
    def zzI(self, arg0: "zzx") -> None: ...
    def zzJ(self, arg0: "zzbgt") -> None: ...
    def zzt(self) -> "zzdx": ...
    def zzP(self, arg0: "zzdq") -> None: ...
    def zzQ(self, arg0: "zzm", arg1: "zzbk") -> None: ...
    def zzR(self, arg0: "IObjectWrapper") -> None: ...
    def zzS(self, arg0: "zzcs") -> None: ...
    def zzA(self) -> bool: ...
    def zzU(self) -> int: ...
    def zzT(self, arg0: int) -> None: ...
    def zzY(self, arg0: "zzcp") -> None: ...
