from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzdx import zzdx
from android.gms.ads.internal.client.zze import zze

class zzcc:
    def zze(self, arg0: str, arg1: zzdx) -> None: ...
    def zzf(self, arg0: str) -> None: ...
    def zzg(self, arg0: str, arg1: zze) -> None: ...
