from typing import Any, ClassVar, overload

class zzce:
    def zze(self, arg0: str, arg1: "zzdx") -> None: ...
    def zzf(self, arg0: str) -> None: ...
    def zzg(self, arg0: str, arg1: "zze") -> None: ...
