from typing import Any, ClassVar, overload

class zzcf:
    def zze(self, arg0: list, arg1: "zzcb") -> None: ...
    def zzf(self, arg0: str) -> bool: ...
    def zzg(self, arg0: str) -> "zzccp": ...
    def zzh(self, arg0: str) -> bool: ...
    def zzi(self, arg0: str) -> "zzbgq": ...
    def zzj(self, arg0: str) -> bool: ...
    def zzk(self, arg0: str) -> "zzbu": ...
    def zzl(self, arg0: "zzbvj") -> None: ...
    def zzm(self, arg0: str, arg1: "zzfp", arg2: "zzce") -> bool: ...
    def zzn(self, arg0: int, arg1: str) -> bool: ...
    def zzo(self, arg0: str) -> "zzbu": ...
    def zzp(self, arg0: str) -> "zzbgq": ...
    def zzq(self, arg0: str) -> "zzccp": ...
    def zzr(self, arg0: int, arg1: str) -> "zzfp": ...
    def zzs(self, arg0: int) -> "Bundle": ...
    def zzt(self, arg0: int, arg1: str) -> int: ...
    def zzu(self, arg0: int, arg1: str) -> bool: ...
    def zzv(self, arg0: int) -> None: ...
