from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzbq import zzbq
from android.gms.ads.internal.client.zzbu import zzbu
from android.gms.ads.internal.client.zzch import zzch
from android.gms.ads.internal.client.zzcy import zzcy
from android.gms.ads.internal.client.zzdt import zzdt
from android.gms.ads.internal.client.zzr import zzr
from android.gms.internal.ads.zzbmp import zzbmp
from android.gms.internal.ads.zzbmu import zzbmu
from android.gms.internal.ads.zzbqx import zzbqx
from android.gms.internal.ads.zzbra import zzbra
from android.gms.internal.ads.zzbvj import zzbvj
from android.gms.internal.ads.zzbzb import zzbzb
from android.gms.internal.ads.zzbzi import zzbzi
from android.gms.internal.ads.zzcbz import zzcbz
from android.gms.internal.ads.zzccp import zzccp
from android.gms.internal.ads.zzcet import zzcet

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper: ...  # com.google.android.gms.dynamic.IObjectWrapper

class zzcm:
    def zzb(self, arg0: IObjectWrapper, arg1: zzr, arg2: str, arg3: zzbvj, arg4: int) -> zzbu: ...
    def zzc(self, arg0: IObjectWrapper, arg1: zzr, arg2: str, arg3: zzbvj, arg4: int) -> zzbu: ...
    def zzd(self, arg0: IObjectWrapper, arg1: str, arg2: zzbvj, arg3: int) -> zzbq: ...
    def zze(self, arg0: IObjectWrapper, arg1: IObjectWrapper) -> zzbmp: ...
    def zzf(self, arg0: IObjectWrapper, arg1: zzbvj, arg2: int) -> zzcbz: ...
    def zzg(self, arg0: IObjectWrapper) -> zzbzi: ...
    def zzi(self, arg0: IObjectWrapper, arg1: int) -> zzcy: ...
    def zzj(self, arg0: IObjectWrapper, arg1: zzr, arg2: str, arg3: int) -> zzbu: ...
    def zzk(self, arg0: IObjectWrapper, arg1: IObjectWrapper, arg2: IObjectWrapper) -> zzbmu: ...
    def zzl(self, arg0: IObjectWrapper, arg1: str, arg2: zzbvj, arg3: int) -> zzccp: ...
    def zzm(self, arg0: IObjectWrapper, arg1: zzr, arg2: str, arg3: zzbvj, arg4: int) -> zzbu: ...
    def zzn(self, arg0: IObjectWrapper, arg1: zzbvj, arg2: int) -> zzcet: ...
    def zzo(self, arg0: IObjectWrapper, arg1: zzbvj, arg2: int) -> zzbzb: ...
    def zzp(self, arg0: IObjectWrapper, arg1: zzbvj, arg2: int, arg3: zzbqx) -> zzbra: ...
    def zzq(self, arg0: IObjectWrapper, arg1: zzbvj, arg2: int) -> zzdt: ...
    def zzh(self, arg0: IObjectWrapper, arg1: zzbvj, arg2: int) -> zzch: ...
