from typing import Any, ClassVar, overload

class zzcu:
    def __init__(self) -> None: ...
    @staticmethod
    def asInterface(arg0: "IBinder") -> "zzcv": ...
    def zzdd(self, arg0: int, arg1: "Parcel", arg2: "Parcel", arg3: int) -> bool: ...
