from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzdk import zzdk
from android.gms.ads.internal.client.zzfr import zzfr
from android.gms.internal.ads.zzbsd import zzbsd
from android.gms.internal.ads.zzbvj import zzbvj

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class IObjectWrapper:
    """Forward declaration for ``com.google.android.gms.dynamic.IObjectWrapper``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.dynamic.IObjectWrapper')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/dynamic/IObjectWrapper
    """
    ...

class zzcw:
    def zze(self) -> None: ...
    def zzf(self, arg0: float) -> None: ...
    def zzg(self, arg0: str) -> None: ...
    def zzh(self, arg0: bool) -> None: ...
    def zzi(self, arg0: IObjectWrapper, arg1: str) -> None: ...
    def zzj(self, arg0: str, arg1: IObjectWrapper) -> None: ...
    def zzk(self) -> float: ...
    def zzl(self) -> bool: ...
    def zzm(self) -> str: ...
    def zzn(self, arg0: str) -> None: ...
    def zzo(self, arg0: zzbvj) -> None: ...
    def zzp(self, arg0: zzbsd) -> None: ...
    def zzq(self) -> list: ...
    def zzr(self, arg0: zzfr) -> None: ...
    def zzs(self) -> None: ...
    def zzt(self, arg0: zzdk) -> None: ...
    def zzu(self, arg0: bool) -> None: ...
    def zzv(self, arg0: str) -> None: ...
    def zzw(self) -> None: ...
