from typing import Any, ClassVar, overload

class zzdv:
    def zze(self) -> str: ...
    def zzf(self) -> str: ...
    def zzg(self) -> list: ...
    def zzh(self) -> "zzv": ...
    def zzi(self) -> "Bundle": ...
    def zzj(self) -> str: ...
