from typing import Any, ClassVar, overload
from android.gms.ads.internal.client.zzv import zzv

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Bundle: ...  # android.os.Bundle

class zzdx:
    def zze(self) -> str: ...
    def zzf(self) -> str: ...
    def zzg(self) -> list: ...
    def zzh(self) -> zzv: ...
    def zzi(self) -> Bundle: ...
    def zzj(self) -> str: ...
