from typing import Any, ClassVar, overload
from android.gms.ads.AdFormat import AdFormat
from android.gms.ads.OnAdInspectorClosedListener import OnAdInspectorClosedListener
from android.gms.ads.RequestConfiguration import RequestConfiguration
from android.gms.ads.initialization.InitializationStatus import InitializationStatus
from android.gms.ads.initialization.OnInitializationCompleteListener import OnInitializationCompleteListener
from android.gms.ads.preload.PreloadCallback import PreloadCallback
from android.gms.ads.preload.zzb import zzb

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class Status: ...  # com.google.android.gms.common.api.Status

class zzeu:
    zza: ClassVar[set]
    def zza(self, arg0: AdFormat) -> zzb: ...
    @staticmethod
    def zzb() -> "zzeu": ...
    def zzc(self, arg0: Context, arg1: str, arg2: OnInitializationCompleteListener) -> None: ...
    def zzd(self) -> None: ...
    def zze(self, arg0: Context, arg1: list, arg2: PreloadCallback) -> Status: ...
    def zzf(self, arg0: float) -> None: ...
    def zzg(self) -> float: ...
    def zzh(self, arg0: bool) -> None: ...
    def zzi(self) -> bool: ...
    def zzj(self, arg0: Context, arg1: str) -> None: ...
    def zzk(self, arg0: type) -> None: ...
    def zzl(self) -> InitializationStatus: ...
    def zzm(self, arg0: Context) -> None: ...
    def zzn(self, arg0: Context, arg1: OnAdInspectorClosedListener) -> None: ...
    def zzo(self) -> str: ...
    def zzp(self) -> RequestConfiguration: ...
    def zzq(self, arg0: RequestConfiguration) -> None: ...
    def zzr(self, arg0: bool) -> bool: ...
    def zzs(self, arg0: str) -> None: ...
