from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Bundle: ...  # android.os.Bundle

class zzex:
    def __init__(self, arg0: str, arg1: Bundle, arg2: str) -> None: ...
    def zza(self) -> str: ...
    def zzb(self) -> str: ...
    def zzc(self) -> Bundle: ...
