from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle

class zzex:
    def __init__(self, arg0: str, arg1: Bundle, arg2: str) -> None: ...
    def zza(self) -> str: ...
    def zzb(self) -> str: ...
    def zzc(self) -> Bundle: ...
