from typing import Any, ClassVar, overload
from android.gms.ads.VideoController import VideoController
from android.gms.internal.ads.zzbmi import zzbmi
from android.gms.internal.ads.zzbnc import zzbnc

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Drawable: ...  # android.graphics.drawable.Drawable

class zzfb:
    def __init__(self, arg0: zzbmi, arg1: zzbnc) -> None: ...
    def getAspectRatio(self) -> float: ...
    def getDuration(self) -> float: ...
    def getCurrentTime(self) -> float: ...
    def getVideoController(self) -> VideoController: ...
    def hasVideoContent(self) -> bool: ...
    def zza(self) -> bool: ...
    def setMainImage(self, arg0: Drawable) -> None: ...
    def getMainImage(self) -> Drawable: ...
    def zzc(self) -> zzbmi: ...
    def zzb(self) -> zzbnc: ...
