from typing import Any, ClassVar, overload
from android.gms.ads.OnPaidEventListener import OnPaidEventListener
from android.gms.ads.internal.client.zzt import zzt

class zzfo:
    def __init__(self, arg0: OnPaidEventListener) -> None: ...
    def zzf(self) -> bool: ...
    def zze(self, arg0: zzt) -> None: ...
