from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class VideoLifecycleCallbacks:
    """Forward declaration for ``com.google.android.gms.ads.VideoController.VideoLifecycleCallbacks``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.google.android.gms.ads.VideoController.VideoLifecycleCallbacks')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developers.google.com/android/reference/com/google/android/gms/ads/VideoController/VideoLifecycleCallbacks
    """
    ...

class zzfv:
    def __init__(self, arg0: VideoLifecycleCallbacks) -> None: ...
    def zze(self) -> None: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzh(self) -> None: ...
    def zzi(self, arg0: bool) -> None: ...
