from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class VideoLifecycleCallbacks: ...  # com.google.android.gms.ads.VideoController.VideoLifecycleCallbacks

class zzfv:
    def __init__(self, arg0: VideoLifecycleCallbacks) -> None: ...
    def zze(self) -> None: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzh(self) -> None: ...
    def zzi(self, arg0: bool) -> None: ...
