from typing import Any, ClassVar, overload

class zzg:
    def __init__(self, arg0: "AdListener") -> None: ...
    def zzb(self) -> None: ...
    def zzc(self, arg0: int) -> None: ...
    def zzd(self, arg0: "zze") -> None: ...
    def zze(self) -> None: ...
    def zzf(self) -> None: ...
    def zzg(self) -> None: ...
    def zzh(self) -> None: ...
    def zzi(self) -> None: ...
    def zzj(self) -> None: ...
    def zzk(self) -> "AdListener": ...
