from typing import Any, ClassVar, overload

class zzh:
    def __init__(self, arg0: "AdLoadCallback", arg1: Any) -> None: ...
    def zzb(self) -> None: ...
    def zzc(self, arg0: "zze") -> None: ...
