from typing import Any, ClassVar, overload

class zzn:
    def __init__(self) -> None: ...
    def zza(self) -> "zzm": ...
    def zzb(self, arg0: "Bundle") -> "zzn": ...
    def zzc(self, arg0: list) -> "zzn": ...
    def zzd(self, arg0: bool) -> "zzn": ...
    def zze(self, arg0: int) -> "zzn": ...
    def zzf(self, arg0: int) -> "zzn": ...
    def zzg(self, arg0: str) -> "zzn": ...
    def zzh(self, arg0: int) -> "zzn": ...
    def zzi(self, arg0: int) -> "zzn": ...
