from typing import Any, ClassVar, overload
from android.window.BackEvent import BackEvent

class OnBackAnimationCallback:
    def onBackStarted(self, arg0: BackEvent) -> None: ...
    def onBackProgressed(self, arg0: BackEvent) -> None: ...
    def onBackCancelled(self) -> None: ...
