from typing import Any, ClassVar, overload
from android.content.om.OverlayIdentifier import OverlayIdentifier
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class FabricatedOverlay:
    def __init__(self, arg0: str, arg1: str) -> None: ...
    def getIdentifier(self) -> OverlayIdentifier: ...
    def setTargetOverlayable(self, arg0: str) -> None: ...
    @overload
    def setResourceValue(self, arg0: str, arg1: int, arg2: int, arg3: str) -> None: ...
    @overload
    def setResourceValue(self, arg0: str, arg1: int, arg2: str, arg3: str) -> None: ...
    @overload
    def setResourceValue(self, arg0: str, arg1: ParcelFileDescriptor, arg2: str) -> None: ...
    @overload
    def setResourceValue(self, arg0: str, arg1: AssetFileDescriptor, arg2: str) -> None: ...
    def setNinePatchResourceValue(self, arg0: str, arg1: ParcelFileDescriptor, arg2: str) -> None: ...
