from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class DeviceProductInfo:
    CONNECTION_TO_SINK_BUILT_IN: ClassVar[int]
    CONNECTION_TO_SINK_DIRECT: ClassVar[int]
    CONNECTION_TO_SINK_TRANSITIVE: ClassVar[int]
    CONNECTION_TO_SINK_UNKNOWN: ClassVar[int]
    CREATOR: ClassVar[Creator]
    def __init__(self, arg0: str, arg1: str, arg2: str, arg3: int, arg4: int) -> None: ...
    def getName(self) -> str: ...
    def getManufacturerPnpId(self) -> str: ...
    def getProductId(self) -> str: ...
    def getModelYear(self) -> int: ...
    def getManufactureYear(self) -> int: ...
    def getManufactureWeek(self) -> int: ...
    def getConnectionToSinkType(self) -> int: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
