from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.view.Surface import Surface

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class VirtualDisplayConfig:
    CREATOR: ClassVar[Creator]
    def getName(self) -> str: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getDensityDpi(self) -> int: ...
    def getFlags(self) -> int: ...
    def getSurface(self) -> Surface: ...
    def getDisplayCategories(self) -> set: ...
    def getRequestedRefreshRate(self) -> float: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: str, arg1: int, arg2: int, arg3: int) -> None: ...
        def setFlags(self, arg0: int) -> "Builder": ...
        def setSurface(self, arg0: Surface) -> "Builder": ...
        def setDisplayCategories(self, arg0: set) -> "Builder": ...
        def addDisplayCategory(self, arg0: str) -> "Builder": ...
        def setRequestedRefreshRate(self, arg0: float) -> "Builder": ...
        def build(self) -> "VirtualDisplayConfig": ...
