from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class Intent: ...  # android.content.Intent

class ADMMessageHandlerJob:
    def __init__(self) -> None: ...
    def onMessage(self, arg0: Context, arg1: Intent) -> None: ...
    def onRegistered(self, arg0: Context, arg1: str) -> None: ...
    def onUnregistered(self, arg0: Context, arg1: str) -> None: ...
    def onRegistrationError(self, arg0: Context, arg1: str) -> None: ...
