from typing import Any, ClassVar, overload

class ADMMessageHandlerJob:
    def __init__(self) -> None: ...
    def onMessage(self, arg0: "Context", arg1: "Intent") -> None: ...
    def onRegistered(self, arg0: "Context", arg1: str) -> None: ...
    def onUnregistered(self, arg0: "Context", arg1: str) -> None: ...
    def onRegistrationError(self, arg0: "Context", arg1: str) -> None: ...
