from typing import Any, ClassVar, overload
from android.os.Parcelable import Parcelable

class BundleCompat:
    def putString(self, arg0: str, arg1: str) -> None: ...
    def putInt(self, arg0: str, arg1: int) -> None: ...
    def putLong(self, arg0: str, arg1: int) -> None: ...
    def putBoolean(self, arg0: str, arg1: bool) -> None: ...
    def getString(self, arg0: str) -> str: ...
    def getInt(self, arg0: str) -> int: ...
    def getLong(self, arg0: str) -> int: ...
    @overload
    def getBoolean(self, arg0: str) -> bool: ...
    @overload
    def getBoolean(self, arg0: str, arg1: bool) -> bool: ...
    def containsKey(self, arg0: str) -> bool: ...
    def getBundle(self) -> Any: ...
    def setBundle(self, arg0: Parcelable) -> None: ...
