from typing import Any, ClassVar, overload

class GenerateNotificationOpenIntent:
    def __init__(self, arg0: "Context", arg1: "Intent", arg2: bool) -> None: ...
    def getIntentVisible(self) -> "Intent": ...
