from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class PackageInfo:
    """Forward declaration for ``android.content.pm.PackageInfo``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.pm.PackageInfo')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/pm/PackageInfo
    """
    ...

class GetPackageInfoResult:
    def __init__(self, arg0: bool, arg1: PackageInfo) -> None: ...
    def getSuccessful(self) -> bool: ...
    def getPackageInfo(self) -> PackageInfo: ...
    def component1(self) -> bool: ...
    def component2(self) -> PackageInfo: ...
    def copy(self, arg0: bool, arg1: PackageInfo) -> "GetPackageInfoResult": ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
