from typing import Any, ClassVar, overload

class IntentGeneratorForAttachingToNotifications:
    def __init__(self, arg0: "Context") -> None: ...
    def getContext(self) -> "Context": ...
    def getNewBaseIntent(self, arg0: int) -> "Intent": ...
    def getNewActionPendingIntent(self, arg0: int, arg1: "Intent") -> "PendingIntent": ...
