from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class Intent: ...  # android.content.Intent
class PendingIntent: ...  # android.app.PendingIntent

class IntentGeneratorForAttachingToNotifications:
    def __init__(self, arg0: Context) -> None: ...
    def getContext(self) -> Context: ...
    def getNewBaseIntent(self, arg0: int) -> Intent: ...
    def getNewActionPendingIntent(self, arg0: int, arg1: Intent) -> PendingIntent: ...
