from typing import Any, ClassVar, overload

class NotificationPermissionController:
    INSTANCE: ClassVar["NotificationPermissionController"]
    def prompt(self, arg0: bool, arg1: "PromptForPushNotificationPermissionResponseHandler") -> None: ...
    def onAccept(self) -> None: ...
    def onReject(self, arg0: bool) -> None: ...
    def onAppForegrounded(self) -> None: ...
