from typing import Any, ClassVar, overload

class NotificationOpenedReceiverBase:
    def __init__(self) -> None: ...
    def onCreate(self, arg0: "Bundle") -> None: ...
    def onNewIntent(self, arg0: "Intent") -> None: ...
