from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.Bundle import Bundle

class NotificationOpenedActivityHMS:
    def __init__(self) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onNewIntent(self, arg0: Intent) -> None: ...
