from typing import Any, ClassVar, overload
from OneSignalApiResponseHandler import OneSignalApiResponseHandler

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject: ...  # org.json.JSONObject

class OneSignalAPIClient:
    def put(self, arg0: str, arg1: JSONObject, arg2: OneSignalApiResponseHandler) -> None: ...
    def post(self, arg0: str, arg1: JSONObject, arg2: OneSignalApiResponseHandler) -> None: ...
    def get(self, arg0: str, arg1: OneSignalApiResponseHandler, arg2: str) -> None: ...
    def getSync(self, arg0: str, arg1: OneSignalApiResponseHandler, arg2: str) -> None: ...
    def putSync(self, arg0: str, arg1: JSONObject, arg2: OneSignalApiResponseHandler) -> None: ...
    def postSync(self, arg0: str, arg1: JSONObject, arg2: OneSignalApiResponseHandler) -> None: ...
