from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject: ...  # org.json.JSONObject

class OSDeviceState:
    def areNotificationsEnabled(self) -> bool: ...
    def isPushDisabled(self) -> bool: ...
    def isSubscribed(self) -> bool: ...
    def getUserId(self) -> str: ...
    def getPushToken(self) -> str: ...
    def isEmailSubscribed(self) -> bool: ...
    def getEmailUserId(self) -> str: ...
    def getEmailAddress(self) -> str: ...
    def isSMSSubscribed(self) -> bool: ...
    def getSMSUserId(self) -> str: ...
    def getSMSNumber(self) -> str: ...
    def toJSONObject(self) -> JSONObject: ...
