from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class OSDeviceState:
    def areNotificationsEnabled(self) -> bool: ...
    def isPushDisabled(self) -> bool: ...
    def isSubscribed(self) -> bool: ...
    def getUserId(self) -> str: ...
    def getPushToken(self) -> str: ...
    def isEmailSubscribed(self) -> bool: ...
    def getEmailUserId(self) -> str: ...
    def getEmailAddress(self) -> str: ...
    def isSMSSubscribed(self) -> bool: ...
    def getSMSUserId(self) -> str: ...
    def getSMSNumber(self) -> str: ...
    def toJSONObject(self) -> JSONObject: ...
