from typing import Any, ClassVar, overload
from OSEmailSubscriptionState import OSEmailSubscriptionState

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject: ...  # org.json.JSONObject

class OSEmailSubscriptionStateChanges:
    def __init__(self, arg0: OSEmailSubscriptionState, arg1: OSEmailSubscriptionState) -> None: ...
    def getTo(self) -> OSEmailSubscriptionState: ...
    def getFrom(self) -> OSEmailSubscriptionState: ...
    def toJSONObject(self) -> JSONObject: ...
    def toString(self) -> str: ...
