from typing import Any, ClassVar, overload

class OSEmailSubscriptionStateChanges:
    def __init__(self, arg0: "OSEmailSubscriptionState", arg1: "OSEmailSubscriptionState") -> None: ...
    def getTo(self) -> "OSEmailSubscriptionState": ...
    def getFrom(self) -> "OSEmailSubscriptionState": ...
    def toJSONObject(self) -> "JSONObject": ...
    def toString(self) -> str: ...
