from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class WorkerParameters: ...  # androidx.work.WorkerParameters
class Result: ...  # androidx.work.ListenableWorker.Result

class OSFocusHandler:
    Companion: ClassVar["Companion"]
    def __init__(self) -> None: ...
    def hasBackgrounded(self) -> bool: ...
    def hasCompleted(self) -> bool: ...
    def startOnFocusWork(self) -> None: ...
    def startOnStartFocusWork(self) -> None: ...
    def startOnStopFocusWork(self) -> None: ...
    def startOnLostFocusWorker(self, arg0: str, arg1: int, arg2: Context) -> None: ...
    def cancelOnLostFocusWorker(self, arg0: str, arg1: Context) -> None: ...

    class Companion:
        def onLostFocusDoWork(self) -> None: ...

    class OnLostFocusWorker:
        def __init__(self, arg0: Context, arg1: WorkerParameters) -> None: ...
        def doWork(self) -> Result: ...
