from typing import Any, ClassVar, overload

class OSInAppMessageTag:
    def toJSONObject(self) -> "JSONObject": ...
    def getTagsToAdd(self) -> "JSONObject": ...
    def setTagsToAdd(self, arg0: "JSONObject") -> None: ...
    def getTagsToRemove(self) -> "JSONArray": ...
    def setTagsToRemove(self, arg0: "JSONArray") -> None: ...
    def toString(self) -> str: ...
