from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...
class Position:
    """Forward declaration for ``com.onesignal.WebViewManager.Position``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('com.onesignal.WebViewManager.Position')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class OSInAppMessageContent:
    def __init__(self, arg0: JSONObject) -> None: ...
    def getContentHtml(self) -> str: ...
    def setContentHtml(self, arg0: str) -> None: ...
    def getUseHeightMargin(self) -> bool: ...
    def setUseHeightMargin(self, arg0: bool) -> None: ...
    def getUseWidthMargin(self) -> bool: ...
    def setUseWidthMargin(self, arg0: bool) -> None: ...
    def isFullBleed(self) -> bool: ...
    def setFullBleed(self, arg0: bool) -> None: ...
    def getDisplayLocation(self) -> Position: ...
    def setDisplayLocation(self, arg0: Position) -> None: ...
    def getDisplayDuration(self) -> float: ...
    def setDisplayDuration(self, arg0: float) -> None: ...
    def getPageHeight(self) -> int: ...
    def setPageHeight(self, arg0: int) -> None: ...
