from typing import Any, ClassVar, overload

class OSInAppMessageContent:
    def __init__(self, arg0: "JSONObject") -> None: ...
    def getContentHtml(self) -> str: ...
    def setContentHtml(self, arg0: str) -> None: ...
    def getUseHeightMargin(self) -> bool: ...
    def setUseHeightMargin(self, arg0: bool) -> None: ...
    def getUseWidthMargin(self) -> bool: ...
    def setUseWidthMargin(self, arg0: bool) -> None: ...
    def isFullBleed(self) -> bool: ...
    def setFullBleed(self, arg0: bool) -> None: ...
    def getDisplayLocation(self) -> "Position": ...
    def setDisplayLocation(self, arg0: "Position") -> None: ...
    def getDisplayDuration(self) -> float: ...
    def setDisplayDuration(self, arg0: float) -> None: ...
    def getPageHeight(self) -> int: ...
    def setPageHeight(self, arg0: int) -> None: ...
