from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject: ...  # org.json.JSONObject

class OSInAppMessagePage:
    def __init__(self, arg0: JSONObject) -> None: ...
    def getPageId(self) -> str: ...
    def setPageId(self, arg0: str) -> None: ...
    def getPageIndex(self) -> str: ...
    def setPageIndex(self, arg0: str) -> None: ...
    def toJSONObject(self) -> JSONObject: ...
