from typing import Any, ClassVar, overload

class OSInAppMessageOutcome:
    def toJSONObject(self) -> "JSONObject": ...
    def getName(self) -> str: ...
    def setName(self, arg0: str) -> None: ...
    def getWeight(self) -> float: ...
    def setWeight(self, arg0: float) -> None: ...
    def isUnique(self) -> bool: ...
    def setUnique(self, arg0: bool) -> None: ...
    def toString(self) -> str: ...
