from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Throwable: ...  # java.lang.Throwable

class OSLogger:
    def verbose(self, arg0: str) -> None: ...
    def debug(self, arg0: str) -> None: ...
    def info(self, arg0: str) -> None: ...
    def warning(self, arg0: str) -> None: ...
    @overload
    def error(self, arg0: str) -> None: ...
    @overload
    def error(self, arg0: str, arg1: Throwable) -> None: ...
