from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray: ...  # org.json.JSONArray
class JSONObject: ...  # org.json.JSONObject

class OSNotificationIntentExtras:
    def __init__(self, arg0: JSONArray, arg1: JSONObject) -> None: ...
    def getDataArray(self) -> JSONArray: ...
    def setDataArray(self, arg0: JSONArray) -> None: ...
    def getJsonData(self) -> JSONObject: ...
    def setJsonData(self, arg0: JSONObject) -> None: ...
    def component1(self) -> JSONArray: ...
    def component2(self) -> JSONObject: ...
    def copy(self, arg0: JSONArray, arg1: JSONObject) -> "OSNotificationIntentExtras": ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
