from typing import Any, ClassVar, overload
from OSNotification import OSNotification
from OSNotificationAction import OSNotificationAction

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class AppEntryAction: ...  # com.onesignal.OneSignal.AppEntryAction
class JSONObject: ...  # org.json.JSONObject

class OSNotificationOpenedResult:
    def __init__(self, arg0: OSNotification, arg1: OSNotificationAction) -> None: ...
    def onEntryStateChange(self, arg0: AppEntryAction) -> None: ...
    def stringify(self) -> str: ...
    def toJSONObject(self) -> JSONObject: ...
    def getNotification(self) -> OSNotification: ...
    def getAction(self) -> OSNotificationAction: ...
    def toString(self) -> str: ...
