from typing import Any, ClassVar, overload
from OSNotification import OSNotification

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Context: ...  # android.content.Context
class JSONObject: ...  # org.json.JSONObject
class Uri: ...  # android.net.Uri

class OSNotificationGenerationJob:
    def getNotification(self) -> OSNotification: ...
    def setNotification(self, arg0: OSNotification) -> None: ...
    def getContext(self) -> Context: ...
    def setContext(self, arg0: Context) -> None: ...
    def getJsonPayload(self) -> JSONObject: ...
    def setJsonPayload(self, arg0: JSONObject) -> None: ...
    def isRestoring(self) -> bool: ...
    def setRestoring(self, arg0: bool) -> None: ...
    def getShownTimeStamp(self) -> int: ...
    def setShownTimeStamp(self, arg0: int) -> None: ...
    def getOverriddenBodyFromExtender(self) -> str: ...
    def setOverriddenBodyFromExtender(self, arg0: str) -> None: ...
    def getOverriddenTitleFromExtender(self) -> str: ...
    def setOverriddenTitleFromExtender(self, arg0: str) -> None: ...
    def getOverriddenSound(self) -> Uri: ...
    def setOverriddenSound(self, arg0: Uri) -> None: ...
    def getOverriddenFlags(self) -> int: ...
    def setOverriddenFlags(self, arg0: int) -> None: ...
    def getOrgFlags(self) -> int: ...
    def setOrgFlags(self, arg0: int) -> None: ...
    def getOrgSound(self) -> Uri: ...
    def setOrgSound(self, arg0: Uri) -> None: ...
    def toString(self) -> str: ...
