from typing import Any, ClassVar, overload
from OSMutableNotification import OSMutableNotification

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Extender:
    """Forward declaration for ``androidx.core.app.NotificationCompat.Extender``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('androidx.core.app.NotificationCompat.Extender')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/androidx/core/app/NotificationCompat/Extender
    """
    ...
class JSONObject:
    """Forward declaration for ``org.json.JSONObject``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('org.json.JSONObject')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.
    """
    ...

class OSNotification:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "OSNotification") -> None: ...
    def mutableCopy(self) -> OSMutableNotification: ...
    def getNotificationExtender(self) -> Extender: ...
    def setNotificationExtender(self, arg0: Extender) -> None: ...
    def getAndroidNotificationId(self) -> int: ...
    def setAndroidNotificationId(self, arg0: int) -> None: ...
    def getGroupedNotifications(self) -> list: ...
    def getNotificationId(self) -> str: ...
    def getTemplateName(self) -> str: ...
    def getTemplateId(self) -> str: ...
    def getTitle(self) -> str: ...
    def getBody(self) -> str: ...
    def getAdditionalData(self) -> JSONObject: ...
    def getSmallIcon(self) -> str: ...
    def getLargeIcon(self) -> str: ...
    def getBigPicture(self) -> str: ...
    def getSmallIconAccentColor(self) -> str: ...
    def getLaunchURL(self) -> str: ...
    def getSound(self) -> str: ...
    def getLedColor(self) -> str: ...
    def getLockScreenVisibility(self) -> int: ...
    def getGroupKey(self) -> str: ...
    def getGroupMessage(self) -> str: ...
    def getActionButtons(self) -> list: ...
    def getFromProjectNumber(self) -> str: ...
    def getBackgroundImageLayout(self) -> "BackgroundImageLayout": ...
    def getCollapseId(self) -> str: ...
    def getPriority(self) -> int: ...
    def getRawPayload(self) -> str: ...
    def getSentTime(self) -> int: ...
    def getTtl(self) -> int: ...
    def toJSONObject(self) -> JSONObject: ...
    def toString(self) -> str: ...

    class ActionButton:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: JSONObject) -> None: ...
        @overload
        def __init__(self, arg0: str, arg1: str, arg2: str) -> None: ...
        def toJSONObject(self) -> JSONObject: ...
        def getId(self) -> str: ...
        def getText(self) -> str: ...
        def getIcon(self) -> str: ...

    class BackgroundImageLayout:
        def __init__(self) -> None: ...
        def getImage(self) -> str: ...
        def getTitleTextColor(self) -> str: ...
        def getBodyTextColor(self) -> str: ...

    class OSNotificationBuilder:
        def __init__(self) -> None: ...
        def setNotificationExtender(self, arg0: Extender) -> "OSNotificationBuilder": ...
        def setGroupedNotifications(self, arg0: list) -> "OSNotificationBuilder": ...
        def setAndroidNotificationId(self, arg0: int) -> "OSNotificationBuilder": ...
        def setNotificationId(self, arg0: str) -> "OSNotificationBuilder": ...
        def setTemplateName(self, arg0: str) -> "OSNotificationBuilder": ...
        def setTemplateId(self, arg0: str) -> "OSNotificationBuilder": ...
        def setTitle(self, arg0: str) -> "OSNotificationBuilder": ...
        def setBody(self, arg0: str) -> "OSNotificationBuilder": ...
        def setAdditionalData(self, arg0: JSONObject) -> "OSNotificationBuilder": ...
        def setSmallIcon(self, arg0: str) -> "OSNotificationBuilder": ...
        def setLargeIcon(self, arg0: str) -> "OSNotificationBuilder": ...
        def setBigPicture(self, arg0: str) -> "OSNotificationBuilder": ...
        def setSmallIconAccentColor(self, arg0: str) -> "OSNotificationBuilder": ...
        def setLaunchURL(self, arg0: str) -> "OSNotificationBuilder": ...
        def setSound(self, arg0: str) -> "OSNotificationBuilder": ...
        def setLedColor(self, arg0: str) -> "OSNotificationBuilder": ...
        def setLockScreenVisibility(self, arg0: int) -> "OSNotificationBuilder": ...
        def setGroupKey(self, arg0: str) -> "OSNotificationBuilder": ...
        def setGroupMessage(self, arg0: str) -> "OSNotificationBuilder": ...
        def setActionButtons(self, arg0: list) -> "OSNotificationBuilder": ...
        def setFromProjectNumber(self, arg0: str) -> "OSNotificationBuilder": ...
        def setBackgroundImageLayout(self, arg0: "BackgroundImageLayout") -> "OSNotificationBuilder": ...
        def setCollapseId(self, arg0: str) -> "OSNotificationBuilder": ...
        def setPriority(self, arg0: int) -> "OSNotificationBuilder": ...
        def setRawPayload(self, arg0: str) -> "OSNotificationBuilder": ...
        def setSenttime(self, arg0: int) -> "OSNotificationBuilder": ...
        def setTTL(self, arg0: int) -> "OSNotificationBuilder": ...
        def build(self) -> "OSNotification": ...
