from typing import Any, ClassVar, overload
from OSNotification import OSNotification

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject: ...  # org.json.JSONObject

class OSNotificationReceivedEvent:
    def complete(self, arg0: OSNotification) -> None: ...
    def getNotification(self) -> OSNotification: ...
    def toJSONObject(self) -> JSONObject: ...
    def toString(self) -> str: ...
