from typing import Any, ClassVar, overload

class OSNotificationReceivedEvent:
    def complete(self, arg0: "OSNotification") -> None: ...
    def getNotification(self) -> "OSNotification": ...
    def toJSONObject(self) -> "JSONObject": ...
    def toString(self) -> str: ...
