from typing import Any, ClassVar, overload

class OSNotificationOpenedResult:
    def __init__(self, arg0: "OSNotification", arg1: "OSNotificationAction") -> None: ...
    def onEntryStateChange(self, arg0: "AppEntryAction") -> None: ...
    def stringify(self) -> str: ...
    def toJSONObject(self) -> "JSONObject": ...
    def getNotification(self) -> "OSNotification": ...
    def getAction(self) -> "OSNotificationAction": ...
    def toString(self) -> str: ...
