from typing import Any, ClassVar, overload

class OSPermissionState:
    def areNotificationsEnabled(self) -> bool: ...
    def getObservable(self) -> "OSObservable": ...
    def clone(self) -> Any: ...
    def toJSONObject(self) -> "JSONObject": ...
    def toString(self) -> str: ...
