from typing import Any, ClassVar, overload

class OSSubscriptionStateChanges:
    def __init__(self, arg0: "OSSubscriptionState", arg1: "OSSubscriptionState") -> None: ...
    def getTo(self) -> "OSSubscriptionState": ...
    def getFrom(self) -> "OSSubscriptionState": ...
    def toJSONObject(self) -> "JSONObject": ...
    def toString(self) -> str: ...
