from typing import Any, ClassVar, overload
from OSSubscriptionState import OSSubscriptionState

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONObject: ...  # org.json.JSONObject

class OSSubscriptionStateChanges:
    def __init__(self, arg0: OSSubscriptionState, arg1: OSSubscriptionState) -> None: ...
    def getTo(self) -> OSSubscriptionState: ...
    def getFrom(self) -> OSSubscriptionState: ...
    def toJSONObject(self) -> JSONObject: ...
    def toString(self) -> str: ...
