from typing import Any, ClassVar, overload

class OSWebView:
    def __init__(self, arg0: "Context") -> None: ...
    def overScrollBy(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int, arg8: bool) -> bool: ...
    def scrollTo(self, arg0: int, arg1: int) -> None: ...
    def computeScroll(self) -> None: ...
