from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class PermissionCallback: ...  # com.onesignal.PermissionsActivity.PermissionCallback
class Bundle: ...  # android.os.Bundle
class Intent: ...  # android.content.Intent

class PermissionsActivity:
    def __init__(self) -> None: ...
    @staticmethod
    def registerAsCallback(arg0: str, arg1: PermissionCallback) -> None: ...
    def onCreate(self, arg0: Bundle) -> None: ...
    def onNewIntent(self, arg0: Intent) -> None: ...
    def onRequestPermissionsResult(self, arg0: int, arg1: list[str], arg2: list[int]) -> None: ...
