from typing import Any, ClassVar, overload

class PermissionsActivity:
    def __init__(self) -> None: ...
    @staticmethod
    def registerAsCallback(arg0: str, arg1: "PermissionCallback") -> None: ...
    def onCreate(self, arg0: "Bundle") -> None: ...
    def onNewIntent(self, arg0: "Intent") -> None: ...
    def onRequestPermissionsResult(self, arg0: int, arg1: list[str], arg2: list[int]) -> None: ...
