from typing import Any, ClassVar, overload
from android.app.job.JobParameters import JobParameters

class SyncJobService:
    def __init__(self) -> None: ...
    def onStartJob(self, arg0: JobParameters) -> bool: ...
    def onStopJob(self, arg0: JobParameters) -> bool: ...
