from typing import Any, ClassVar, overload

class SyncService:
    def __init__(self) -> None: ...
    def onStartCommand(self, arg0: "Intent", arg1: int, arg2: int) -> int: ...
    def onBind(self, arg0: "Intent") -> "IBinder": ...
