from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.DatabaseErrorHandler import DatabaseErrorHandler
from android.database.sqlite.SQLiteDatabase import SQLiteDatabase

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class CursorFactory:
    """Forward declaration for ``android.database.sqlite.SQLiteDatabase.CursorFactory``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.database.sqlite.SQLiteDatabase.CursorFactory')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase/CursorFactory
    """
    ...
class OpenParams:
    """Forward declaration for ``android.database.sqlite.SQLiteDatabase.OpenParams``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.database.sqlite.SQLiteDatabase.OpenParams')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase/OpenParams
    """
    ...

class SQLiteOpenHelper:
    @overload
    def __init__(self, arg0: Context, arg1: str, arg2: CursorFactory, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: str, arg2: CursorFactory, arg3: int, arg4: DatabaseErrorHandler) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: str, arg2: int, arg3: OpenParams) -> None: ...
    def getDatabaseName(self) -> str: ...
    def setWriteAheadLoggingEnabled(self, arg0: bool) -> None: ...
    def setLookasideConfig(self, arg0: int, arg1: int) -> None: ...
    def setOpenParams(self, arg0: OpenParams) -> None: ...
    def setIdleConnectionTimeout(self, arg0: int) -> None: ...
    def getWritableDatabase(self) -> SQLiteDatabase: ...
    def getReadableDatabase(self) -> SQLiteDatabase: ...
    def close(self) -> None: ...
    def onConfigure(self, arg0: SQLiteDatabase) -> None: ...
    def onCreate(self, arg0: SQLiteDatabase) -> None: ...
    def onUpgrade(self, arg0: SQLiteDatabase, arg1: int, arg2: int) -> None: ...
    def onDowngrade(self, arg0: SQLiteDatabase, arg1: int, arg2: int) -> None: ...
    def onOpen(self, arg0: SQLiteDatabase) -> None: ...
