from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["SQLiteRawStatement"]

class SQLiteRawStatement(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/database/sqlite/SQLiteRawStatement"
    SQLITE_DATA_TYPE_BLOB = JavaStaticField("I")
    SQLITE_DATA_TYPE_FLOAT = JavaStaticField("I")
    SQLITE_DATA_TYPE_INTEGER = JavaStaticField("I")
    SQLITE_DATA_TYPE_NULL = JavaStaticField("I")
    SQLITE_DATA_TYPE_TEXT = JavaStaticField("I")
    close = JavaMethod("()V")
    isOpen = JavaMethod("()Z")
    step = JavaMethod("()Z")
    reset = JavaMethod("()V")
    clearBindings = JavaMethod("()V")
    getParameterCount = JavaMethod("()I")
    getParameterIndex = JavaMethod("(Ljava/lang/String;)I")
    getParameterName = JavaMethod("(I)Ljava/lang/String;")
    bindBlob = JavaMultipleMethod([("(I[B)V", False, False), ("(I[BII)V", False, False)])
    bindDouble = JavaMethod("(ID)V")
    bindInt = JavaMethod("(II)V")
    bindLong = JavaMethod("(IJ)V")
    bindNull = JavaMethod("(I)V")
    bindText = JavaMethod("(ILjava/lang/String;)V")
    getResultColumnCount = JavaMethod("()I")
    getColumnType = JavaMethod("(I)I")
    getColumnName = JavaMethod("(I)Ljava/lang/String;")
    getColumnLength = JavaMethod("(I)I")
    getColumnBlob = JavaMethod("(I)[B")
    readColumnBlob = JavaMethod("(I[BIII)I")
    getColumnDouble = JavaMethod("(I)D")
    getColumnInt = JavaMethod("(I)I")
    getColumnLong = JavaMethod("(I)J")
    getColumnText = JavaMethod("(I)Ljava/lang/String;")
    toString = JavaMethod("()Ljava/lang/String;")