from typing import Any, ClassVar, overload
from android.content.ContentValues import ContentValues
from android.database.Cursor import Cursor
from android.database.DatabaseErrorHandler import DatabaseErrorHandler
from android.database.sqlite.SQLiteCursorDriver import SQLiteCursorDriver
from android.database.sqlite.SQLiteQuery import SQLiteQuery
from android.database.sqlite.SQLiteRawStatement import SQLiteRawStatement
from android.database.sqlite.SQLiteStatement import SQLiteStatement
from android.database.sqlite.SQLiteTransactionListener import SQLiteTransactionListener
from android.os.CancellationSignal import CancellationSignal
from java.io.File import File
from java.util.Locale import Locale
from java.util.function.BinaryOperator import BinaryOperator
from java.util.function.UnaryOperator import UnaryOperator

class SQLiteDatabase:
    CONFLICT_ABORT: ClassVar[int]
    CONFLICT_FAIL: ClassVar[int]
    CONFLICT_IGNORE: ClassVar[int]
    CONFLICT_NONE: ClassVar[int]
    CONFLICT_REPLACE: ClassVar[int]
    CONFLICT_ROLLBACK: ClassVar[int]
    CREATE_IF_NECESSARY: ClassVar[int]
    ENABLE_WRITE_AHEAD_LOGGING: ClassVar[int]
    JOURNAL_MODE_DELETE: ClassVar[str]
    JOURNAL_MODE_MEMORY: ClassVar[str]
    JOURNAL_MODE_OFF: ClassVar[str]
    JOURNAL_MODE_PERSIST: ClassVar[str]
    JOURNAL_MODE_TRUNCATE: ClassVar[str]
    JOURNAL_MODE_WAL: ClassVar[str]
    MAX_SQL_CACHE_SIZE: ClassVar[int]
    NO_LOCALIZED_COLLATORS: ClassVar[int]
    OPEN_READONLY: ClassVar[int]
    OPEN_READWRITE: ClassVar[int]
    SQLITE_MAX_LIKE_PATTERN_LENGTH: ClassVar[int]
    SYNC_MODE_EXTRA: ClassVar[str]
    SYNC_MODE_FULL: ClassVar[str]
    SYNC_MODE_NORMAL: ClassVar[str]
    SYNC_MODE_OFF: ClassVar[str]
    def finalize(self) -> None: ...
    def onAllReferencesReleased(self) -> None: ...
    @staticmethod
    def releaseMemory() -> int: ...
    def setLockingEnabled(self, arg0: bool) -> None: ...
    def beginTransaction(self) -> None: ...
    def beginTransactionNonExclusive(self) -> None: ...
    def beginTransactionReadOnly(self) -> None: ...
    def beginTransactionWithListener(self, arg0: SQLiteTransactionListener) -> None: ...
    def beginTransactionWithListenerNonExclusive(self, arg0: SQLiteTransactionListener) -> None: ...
    def beginTransactionWithListenerReadOnly(self, arg0: SQLiteTransactionListener) -> None: ...
    def endTransaction(self) -> None: ...
    def setTransactionSuccessful(self) -> None: ...
    def inTransaction(self) -> bool: ...
    def isDbLockedByCurrentThread(self) -> bool: ...
    def isDbLockedByOtherThreads(self) -> bool: ...
    def yieldIfContended(self) -> bool: ...
    @overload
    def yieldIfContendedSafely(self) -> bool: ...
    @overload
    def yieldIfContendedSafely(self, arg0: int) -> bool: ...
    def getSyncedTables(self) -> dict: ...
    @overload
    @staticmethod
    def openDatabase(arg0: str, arg1: "CursorFactory", arg2: int) -> "SQLiteDatabase": ...
    @overload
    @staticmethod
    def openDatabase(arg0: File, arg1: "OpenParams") -> "SQLiteDatabase": ...
    @overload
    @staticmethod
    def openDatabase(arg0: str, arg1: "CursorFactory", arg2: int, arg3: DatabaseErrorHandler) -> "SQLiteDatabase": ...
    @overload
    @staticmethod
    def openOrCreateDatabase(arg0: File, arg1: "CursorFactory") -> "SQLiteDatabase": ...
    @overload
    @staticmethod
    def openOrCreateDatabase(arg0: str, arg1: "CursorFactory") -> "SQLiteDatabase": ...
    @overload
    @staticmethod
    def openOrCreateDatabase(arg0: str, arg1: "CursorFactory", arg2: DatabaseErrorHandler) -> "SQLiteDatabase": ...
    @staticmethod
    def deleteDatabase(arg0: File) -> bool: ...
    @staticmethod
    def create(arg0: "CursorFactory") -> "SQLiteDatabase": ...
    @staticmethod
    def createInMemory(arg0: "OpenParams") -> "SQLiteDatabase": ...
    def setCustomScalarFunction(self, arg0: str, arg1: UnaryOperator) -> None: ...
    def setCustomAggregateFunction(self, arg0: str, arg1: BinaryOperator) -> None: ...
    def execPerConnectionSQL(self, arg0: str, arg1: list) -> None: ...
    def getVersion(self) -> int: ...
    def setVersion(self, arg0: int) -> None: ...
    def getMaximumSize(self) -> int: ...
    def setMaximumSize(self, arg0: int) -> int: ...
    def getPageSize(self) -> int: ...
    def setPageSize(self, arg0: int) -> None: ...
    @overload
    def markTableSyncable(self, arg0: str, arg1: str) -> None: ...
    @overload
    def markTableSyncable(self, arg0: str, arg1: str, arg2: str) -> None: ...
    @staticmethod
    def findEditTable(arg0: str) -> str: ...
    def compileStatement(self, arg0: str) -> SQLiteStatement: ...
    @overload
    def query(self, arg0: bool, arg1: str, arg2: list[str], arg3: str, arg4: list[str], arg5: str, arg6: str, arg7: str, arg8: str) -> Cursor: ...
    @overload
    def query(self, arg0: bool, arg1: str, arg2: list[str], arg3: str, arg4: list[str], arg5: str, arg6: str, arg7: str, arg8: str, arg9: CancellationSignal) -> Cursor: ...
    @overload
    def query(self, arg0: str, arg1: list[str], arg2: str, arg3: list[str], arg4: str, arg5: str, arg6: str) -> Cursor: ...
    @overload
    def query(self, arg0: str, arg1: list[str], arg2: str, arg3: list[str], arg4: str, arg5: str, arg6: str, arg7: str) -> Cursor: ...
    @overload
    def queryWithFactory(self, arg0: "CursorFactory", arg1: bool, arg2: str, arg3: list[str], arg4: str, arg5: list[str], arg6: str, arg7: str, arg8: str, arg9: str) -> Cursor: ...
    @overload
    def queryWithFactory(self, arg0: "CursorFactory", arg1: bool, arg2: str, arg3: list[str], arg4: str, arg5: list[str], arg6: str, arg7: str, arg8: str, arg9: str, arg10: CancellationSignal) -> Cursor: ...
    @overload
    def rawQuery(self, arg0: str, arg1: list[str]) -> Cursor: ...
    @overload
    def rawQuery(self, arg0: str, arg1: list[str], arg2: CancellationSignal) -> Cursor: ...
    @overload
    def rawQueryWithFactory(self, arg0: "CursorFactory", arg1: str, arg2: list[str], arg3: str) -> Cursor: ...
    @overload
    def rawQueryWithFactory(self, arg0: "CursorFactory", arg1: str, arg2: list[str], arg3: str, arg4: CancellationSignal) -> Cursor: ...
    def insert(self, arg0: str, arg1: str, arg2: ContentValues) -> int: ...
    def insertOrThrow(self, arg0: str, arg1: str, arg2: ContentValues) -> int: ...
    def replace(self, arg0: str, arg1: str, arg2: ContentValues) -> int: ...
    def replaceOrThrow(self, arg0: str, arg1: str, arg2: ContentValues) -> int: ...
    def insertWithOnConflict(self, arg0: str, arg1: str, arg2: ContentValues, arg3: int) -> int: ...
    def delete(self, arg0: str, arg1: str, arg2: list[str]) -> int: ...
    def update(self, arg0: str, arg1: ContentValues, arg2: str, arg3: list[str]) -> int: ...
    def updateWithOnConflict(self, arg0: str, arg1: ContentValues, arg2: str, arg3: list[str], arg4: int) -> int: ...
    @overload
    def execSQL(self, arg0: str) -> None: ...
    @overload
    def execSQL(self, arg0: str, arg1: list) -> None: ...
    def createRawStatement(self, arg0: str) -> SQLiteRawStatement: ...
    def getLastInsertRowId(self) -> int: ...
    def getLastChangedRowCount(self) -> int: ...
    def getTotalChangedRowCount(self) -> int: ...
    def validateSql(self, arg0: str, arg1: CancellationSignal) -> None: ...
    def isReadOnly(self) -> bool: ...
    def isOpen(self) -> bool: ...
    def needUpgrade(self, arg0: int) -> bool: ...
    def getPath(self) -> str: ...
    def setLocale(self, arg0: Locale) -> None: ...
    def setMaxSqlCacheSize(self, arg0: int) -> None: ...
    def setForeignKeyConstraintsEnabled(self, arg0: bool) -> None: ...
    def enableWriteAheadLogging(self) -> bool: ...
    def disableWriteAheadLogging(self) -> None: ...
    def isWriteAheadLoggingEnabled(self) -> bool: ...
    def getAttachedDbs(self) -> list: ...
    def isDatabaseIntegrityOk(self) -> bool: ...
    def toString(self) -> str: ...

    class CursorFactory:
        def newCursor(self, arg0: "SQLiteDatabase", arg1: SQLiteCursorDriver, arg2: str, arg3: SQLiteQuery) -> Cursor: ...

    class OpenParams:
        def getLookasideSlotSize(self) -> int: ...
        def getLookasideSlotCount(self) -> int: ...
        def getOpenFlags(self) -> int: ...
        def getCursorFactory(self) -> "CursorFactory": ...
        def getErrorHandler(self) -> DatabaseErrorHandler: ...
        def getIdleConnectionTimeout(self) -> int: ...
        def getJournalMode(self) -> str: ...
        def getSynchronousMode(self) -> str: ...

        class Builder:
            @overload
            def __init__(self) -> None: ...
            @overload
            def __init__(self, arg0: "OpenParams") -> None: ...
            def setLookasideConfig(self, arg0: int, arg1: int) -> "Builder": ...
            def setOpenFlags(self, arg0: int) -> "Builder": ...
            def addOpenFlags(self, arg0: int) -> "Builder": ...
            def removeOpenFlags(self, arg0: int) -> "Builder": ...
            def setCursorFactory(self, arg0: "CursorFactory") -> "Builder": ...
            def setErrorHandler(self, arg0: DatabaseErrorHandler) -> "Builder": ...
            def setIdleConnectionTimeout(self, arg0: int) -> "Builder": ...
            def setJournalMode(self, arg0: str) -> "Builder": ...
            def setSynchronousMode(self, arg0: str) -> "Builder": ...
            def build(self) -> "OpenParams": ...
