from typing import Any, ClassVar, overload

class SQLiteClosable:
    def __init__(self) -> None: ...
    def onAllReferencesReleased(self) -> None: ...
    def onAllReferencesReleasedFromContainer(self) -> None: ...
    def acquireReference(self) -> None: ...
    def releaseReference(self) -> None: ...
    def releaseReferenceFromContainer(self) -> None: ...
    def close(self) -> None: ...
