from typing import Any, ClassVar, overload
from java.text.CharacterIterator import CharacterIterator
from java.util.Locale import Locale

class BreakIterator:
    DONE: ClassVar[int]
    def __init__(self) -> None: ...
    def clone(self) -> Any: ...
    def first(self) -> int: ...
    def last(self) -> int: ...
    @overload
    def next(self, arg0: int) -> int: ...
    @overload
    def next(self) -> int: ...
    def previous(self) -> int: ...
    def following(self, arg0: int) -> int: ...
    def preceding(self, arg0: int) -> int: ...
    def isBoundary(self, arg0: int) -> bool: ...
    def current(self) -> int: ...
    def getText(self) -> CharacterIterator: ...
    @overload
    def setText(self, arg0: str) -> None: ...
    @overload
    def setText(self, arg0: CharacterIterator) -> None: ...
    @overload
    @staticmethod
    def getWordInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getWordInstance(arg0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getLineInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getLineInstance(arg0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getCharacterInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getCharacterInstance(arg0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getSentenceInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getSentenceInstance(arg0: Locale) -> "BreakIterator": ...
    @staticmethod
    def getAvailableLocales() -> list[Locale]: ...
