from typing import Any, ClassVar, overload

class CollationKey:
    def __init__(self, arg0: str) -> None: ...
    def compareTo(self, arg0: "CollationKey") -> int: ...
    def getSourceString(self) -> str: ...
    def toByteArray(self) -> list[int]: ...
