from typing import Any, ClassVar, overload
from java.text.CollationKey import CollationKey
from java.util.Locale import Locale

class Collator:
    CANONICAL_DECOMPOSITION: ClassVar[int]
    FULL_DECOMPOSITION: ClassVar[int]
    IDENTICAL: ClassVar[int]
    NO_DECOMPOSITION: ClassVar[int]
    PRIMARY: ClassVar[int]
    SECONDARY: ClassVar[int]
    TERTIARY: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def getInstance() -> "Collator": ...
    @overload
    @staticmethod
    def getInstance(arg0: Locale) -> "Collator": ...
    @overload
    def compare(self, arg0: str, arg1: str) -> int: ...
    @overload
    def compare(self, arg0: Any, arg1: Any) -> int: ...
    def getCollationKey(self, arg0: str) -> CollationKey: ...
    @overload
    def equals(self, arg0: str, arg1: str) -> bool: ...
    @overload
    def equals(self, arg0: Any) -> bool: ...
    def getStrength(self) -> int: ...
    def setStrength(self, arg0: int) -> None: ...
    def getDecomposition(self) -> int: ...
    def setDecomposition(self, arg0: int) -> None: ...
    @staticmethod
    def getAvailableLocales() -> list[Locale]: ...
    def clone(self) -> Any: ...
    def hashCode(self) -> int: ...
