from typing import Any, ClassVar, overload
from java.text.CharacterIterator import CharacterIterator

class CollationElementIterator:
    NULLORDER: ClassVar[int]
    def reset(self) -> None: ...
    def next(self) -> int: ...
    def previous(self) -> int: ...
    @staticmethod
    def primaryOrder(arg0: int) -> int: ...
    @staticmethod
    def secondaryOrder(arg0: int) -> int: ...
    @staticmethod
    def tertiaryOrder(arg0: int) -> int: ...
    def setOffset(self, arg0: int) -> None: ...
    def getOffset(self) -> int: ...
    def getMaxExpansion(self, arg0: int) -> int: ...
    @overload
    def setText(self, arg0: str) -> None: ...
    @overload
    def setText(self, arg0: CharacterIterator) -> None: ...
