from typing import Any, ClassVar, overload
from java.lang.StringBuffer import StringBuffer
from java.math.RoundingMode import RoundingMode
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.text.DecimalFormatSymbols import DecimalFormatSymbols
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition
from java.util.Currency import Currency

class DecimalFormat:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: DecimalFormatSymbols) -> None: ...
    @overload
    def format(self, arg0: Any, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: float, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: int, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    def formatToCharacterIterator(self, arg0: Any) -> AttributedCharacterIterator: ...
    def parse(self, arg0: str, arg1: ParsePosition) -> float: ...
    def getDecimalFormatSymbols(self) -> DecimalFormatSymbols: ...
    def setDecimalFormatSymbols(self, arg0: DecimalFormatSymbols) -> None: ...
    def getPositivePrefix(self) -> str: ...
    def setPositivePrefix(self, arg0: str) -> None: ...
    def getNegativePrefix(self) -> str: ...
    def setNegativePrefix(self, arg0: str) -> None: ...
    def getPositiveSuffix(self) -> str: ...
    def setPositiveSuffix(self, arg0: str) -> None: ...
    def getNegativeSuffix(self) -> str: ...
    def setNegativeSuffix(self, arg0: str) -> None: ...
    def getMultiplier(self) -> int: ...
    def setMultiplier(self, arg0: int) -> None: ...
    def setGroupingUsed(self, arg0: bool) -> None: ...
    def isGroupingUsed(self) -> bool: ...
    def getGroupingSize(self) -> int: ...
    def setGroupingSize(self, arg0: int) -> None: ...
    def isDecimalSeparatorAlwaysShown(self) -> bool: ...
    def setDecimalSeparatorAlwaysShown(self, arg0: bool) -> None: ...
    def isParseBigDecimal(self) -> bool: ...
    def setParseBigDecimal(self, arg0: bool) -> None: ...
    def isParseIntegerOnly(self) -> bool: ...
    def setParseIntegerOnly(self, arg0: bool) -> None: ...
    def clone(self) -> Any: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toPattern(self) -> str: ...
    def toLocalizedPattern(self) -> str: ...
    def applyPattern(self, arg0: str) -> None: ...
    def applyLocalizedPattern(self, arg0: str) -> None: ...
    def setMaximumIntegerDigits(self, arg0: int) -> None: ...
    def setMinimumIntegerDigits(self, arg0: int) -> None: ...
    def setMaximumFractionDigits(self, arg0: int) -> None: ...
    def setMinimumFractionDigits(self, arg0: int) -> None: ...
    def getMaximumIntegerDigits(self) -> int: ...
    def getMinimumIntegerDigits(self) -> int: ...
    def getMaximumFractionDigits(self) -> int: ...
    def getMinimumFractionDigits(self) -> int: ...
    def getCurrency(self) -> Currency: ...
    def setCurrency(self, arg0: Currency) -> None: ...
    def getRoundingMode(self) -> RoundingMode: ...
    def setRoundingMode(self, arg0: RoundingMode) -> None: ...
