from typing import Any, ClassVar, overload
from java.util.Currency import Currency
from java.util.Locale import Locale

class DecimalFormatSymbols:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Locale) -> None: ...
    @staticmethod
    def getAvailableLocales() -> list[Locale]: ...
    @overload
    @staticmethod
    def getInstance() -> "DecimalFormatSymbols": ...
    @overload
    @staticmethod
    def getInstance(arg0: Locale) -> "DecimalFormatSymbols": ...
    def getZeroDigit(self) -> str: ...
    def setZeroDigit(self, arg0: str) -> None: ...
    def getGroupingSeparator(self) -> str: ...
    def setGroupingSeparator(self, arg0: str) -> None: ...
    def getDecimalSeparator(self) -> str: ...
    def setDecimalSeparator(self, arg0: str) -> None: ...
    def getPerMill(self) -> str: ...
    def setPerMill(self, arg0: str) -> None: ...
    def getPercent(self) -> str: ...
    def setPercent(self, arg0: str) -> None: ...
    def getDigit(self) -> str: ...
    def setDigit(self, arg0: str) -> None: ...
    def getPatternSeparator(self) -> str: ...
    def setPatternSeparator(self, arg0: str) -> None: ...
    def getInfinity(self) -> str: ...
    def setInfinity(self, arg0: str) -> None: ...
    def getNaN(self) -> str: ...
    def setNaN(self, arg0: str) -> None: ...
    def getMinusSign(self) -> str: ...
    def setMinusSign(self, arg0: str) -> None: ...
    def getCurrencySymbol(self) -> str: ...
    def setCurrencySymbol(self, arg0: str) -> None: ...
    def getInternationalCurrencySymbol(self) -> str: ...
    def setInternationalCurrencySymbol(self, arg0: str) -> None: ...
    def getCurrency(self) -> Currency: ...
    def setCurrency(self, arg0: Currency) -> None: ...
    def getMonetaryDecimalSeparator(self) -> str: ...
    def setMonetaryDecimalSeparator(self, arg0: str) -> None: ...
    def getExponentSeparator(self) -> str: ...
    def setExponentSeparator(self, arg0: str) -> None: ...
    def getMonetaryGroupingSeparator(self) -> str: ...
    def setMonetaryGroupingSeparator(self, arg0: str) -> None: ...
    def clone(self) -> Any: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
