from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Field:
    """Forward declaration for ``java.text.Format.Field``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.text.Format.Field')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/text/Format/Field.html
    """
    ...

class FieldPosition:
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: Field) -> None: ...
    @overload
    def __init__(self, arg0: Field, arg1: int) -> None: ...
    def getFieldAttribute(self) -> Field: ...
    def getField(self) -> int: ...
    def getBeginIndex(self) -> int: ...
    def getEndIndex(self) -> int: ...
    def setBeginIndex(self, arg0: int) -> None: ...
    def setEndIndex(self, arg0: int) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
