from typing import Any, ClassVar, overload
from java.lang.StringBuffer import StringBuffer
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.text.FieldPosition import FieldPosition
from java.text.Format import Format
from java.text.ParsePosition import ParsePosition
from java.util.Locale import Locale

class MessageFormat:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Locale) -> None: ...
    def setLocale(self, arg0: Locale) -> None: ...
    def getLocale(self) -> Locale: ...
    def applyPattern(self, arg0: str) -> None: ...
    def toPattern(self) -> str: ...
    def setFormatsByArgumentIndex(self, arg0: list[Format]) -> None: ...
    def setFormats(self, arg0: list[Format]) -> None: ...
    def setFormatByArgumentIndex(self, arg0: int, arg1: Format) -> None: ...
    def setFormat(self, arg0: int, arg1: Format) -> None: ...
    def getFormatsByArgumentIndex(self) -> list[Format]: ...
    def getFormats(self) -> list[Format]: ...
    @overload
    def format(self, arg0: list, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    @staticmethod
    def format(arg0: str, *arg1: Any) -> str: ...
    @overload
    def format(self, arg0: Any, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    def formatToCharacterIterator(self, arg0: Any) -> AttributedCharacterIterator: ...
    @overload
    def parse(self, arg0: str, arg1: ParsePosition) -> list: ...
    @overload
    def parse(self, arg0: str) -> list: ...
    def parseObject(self, arg0: str, arg1: ParsePosition) -> Any: ...
    def clone(self) -> Any: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Field:
        ARGUMENT: ClassVar["Field"]
        def __init__(self, arg0: str) -> None: ...
        def readResolve(self) -> Any: ...
