from typing import Any, ClassVar, overload
from java.lang.StringBuffer import StringBuffer
from java.math.RoundingMode import RoundingMode
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition
from java.util.Currency import Currency
from java.util.Locale import Locale

class NumberFormat:
    FRACTION_FIELD: ClassVar[int]
    INTEGER_FIELD: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    def format(self, arg0: Any, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: float) -> str: ...
    @overload
    def format(self, arg0: int) -> str: ...
    @overload
    def format(self, arg0: float, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, arg0: int, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    def parseObject(self, arg0: str, arg1: ParsePosition) -> Any: ...
    @overload
    def parse(self, arg0: str, arg1: ParsePosition) -> float: ...
    @overload
    def parse(self, arg0: str) -> float: ...
    def isParseIntegerOnly(self) -> bool: ...
    def setParseIntegerOnly(self, arg0: bool) -> None: ...
    @overload
    @staticmethod
    def getInstance() -> "NumberFormat": ...
    @overload
    @staticmethod
    def getInstance(arg0: Locale) -> "NumberFormat": ...
    @overload
    @staticmethod
    def getNumberInstance() -> "NumberFormat": ...
    @overload
    @staticmethod
    def getNumberInstance(arg0: Locale) -> "NumberFormat": ...
    @overload
    @staticmethod
    def getIntegerInstance() -> "NumberFormat": ...
    @overload
    @staticmethod
    def getIntegerInstance(arg0: Locale) -> "NumberFormat": ...
    @overload
    @staticmethod
    def getCurrencyInstance() -> "NumberFormat": ...
    @overload
    @staticmethod
    def getCurrencyInstance(arg0: Locale) -> "NumberFormat": ...
    @overload
    @staticmethod
    def getPercentInstance() -> "NumberFormat": ...
    @overload
    @staticmethod
    def getPercentInstance(arg0: Locale) -> "NumberFormat": ...
    @staticmethod
    def getAvailableLocales() -> list[Locale]: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def clone(self) -> Any: ...
    def isGroupingUsed(self) -> bool: ...
    def setGroupingUsed(self, arg0: bool) -> None: ...
    def getMaximumIntegerDigits(self) -> int: ...
    def setMaximumIntegerDigits(self, arg0: int) -> None: ...
    def getMinimumIntegerDigits(self) -> int: ...
    def setMinimumIntegerDigits(self, arg0: int) -> None: ...
    def getMaximumFractionDigits(self) -> int: ...
    def setMaximumFractionDigits(self, arg0: int) -> None: ...
    def getMinimumFractionDigits(self) -> int: ...
    def setMinimumFractionDigits(self, arg0: int) -> None: ...
    def getCurrency(self) -> Currency: ...
    def setCurrency(self, arg0: Currency) -> None: ...
    def getRoundingMode(self) -> RoundingMode: ...
    def setRoundingMode(self, arg0: RoundingMode) -> None: ...

    class Field:
        CURRENCY: ClassVar["Field"]
        DECIMAL_SEPARATOR: ClassVar["Field"]
        EXPONENT: ClassVar["Field"]
        EXPONENT_SIGN: ClassVar["Field"]
        EXPONENT_SYMBOL: ClassVar["Field"]
        FRACTION: ClassVar["Field"]
        GROUPING_SEPARATOR: ClassVar["Field"]
        INTEGER: ClassVar["Field"]
        PERCENT: ClassVar["Field"]
        PERMILLE: ClassVar["Field"]
        SIGN: ClassVar["Field"]
        def __init__(self, arg0: str) -> None: ...
        def readResolve(self) -> Any: ...
