from typing import Any, ClassVar, overload

class ParsePosition:
    def __init__(self, arg0: int) -> None: ...
    def getIndex(self) -> int: ...
    def setIndex(self, arg0: int) -> None: ...
    def setErrorIndex(self, arg0: int) -> None: ...
    def getErrorIndex(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
