from typing import Any, ClassVar, overload
from java.text.CharacterIterator import CharacterIterator
from java.text.CollationElementIterator import CollationElementIterator
from java.text.CollationKey import CollationKey

class RuleBasedCollator:
    def __init__(self, arg0: str) -> None: ...
    def getRules(self) -> str: ...
    @overload
    def getCollationElementIterator(self, arg0: str) -> CollationElementIterator: ...
    @overload
    def getCollationElementIterator(self, arg0: CharacterIterator) -> CollationElementIterator: ...
    def compare(self, arg0: str, arg1: str) -> int: ...
    def getCollationKey(self, arg0: str) -> CollationKey: ...
    def clone(self) -> Any: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
