from typing import Any, ClassVar, overload
from java.lang.StringBuffer import StringBuffer
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.text.DateFormatSymbols import DateFormatSymbols
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition
from java.util.Date import Date
from java.util.Locale import Locale

class SimpleDateFormat:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Locale) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: DateFormatSymbols) -> None: ...
    def set2DigitYearStart(self, arg0: Date) -> None: ...
    def get2DigitYearStart(self) -> Date: ...
    def format(self, arg0: Date, arg1: StringBuffer, arg2: FieldPosition) -> StringBuffer: ...
    def formatToCharacterIterator(self, arg0: Any) -> AttributedCharacterIterator: ...
    def parse(self, arg0: str, arg1: ParsePosition) -> Date: ...
    def toPattern(self) -> str: ...
    def toLocalizedPattern(self) -> str: ...
    def applyPattern(self, arg0: str) -> None: ...
    def applyLocalizedPattern(self, arg0: str) -> None: ...
    def getDateFormatSymbols(self) -> DateFormatSymbols: ...
    def setDateFormatSymbols(self, arg0: DateFormatSymbols) -> None: ...
    def clone(self) -> Any: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
