from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class UpdateSignalsRequest:
    def getUpdateUri(self) -> Uri: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: Uri) -> None: ...
        def setUpdateUri(self, arg0: Uri) -> "Builder": ...
        def build(self) -> "UpdateSignalsRequest": ...
