from typing import Any, ClassVar, overload
from javax.microedition.khronos.opengles.GL10 import GL10

class GLU:
    def __init__(self) -> None: ...
    @staticmethod
    def gluErrorString(arg0: int) -> str: ...
    @staticmethod
    def gluLookAt(arg0: GL10, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: float) -> None: ...
    @staticmethod
    def gluOrtho2D(arg0: GL10, arg1: float, arg2: float, arg3: float, arg4: float) -> None: ...
    @staticmethod
    def gluPerspective(arg0: GL10, arg1: float, arg2: float, arg3: float, arg4: float) -> None: ...
    @staticmethod
    def gluProject(arg0: float, arg1: float, arg2: float, arg3: list[float], arg4: int, arg5: list[float], arg6: int, arg7: list[int], arg8: int, arg9: list[float], arg10: int) -> int: ...
    @staticmethod
    def gluUnProject(arg0: float, arg1: float, arg2: float, arg3: list[float], arg4: int, arg5: list[float], arg6: int, arg7: list[int], arg8: int, arg9: list[float], arg10: int) -> int: ...
