from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap

class GLUtils:
    @staticmethod
    def getInternalFormat(arg0: Bitmap) -> int: ...
    @staticmethod
    def getType(arg0: Bitmap) -> int: ...
    @overload
    @staticmethod
    def texImage2D(arg0: int, arg1: int, arg2: int, arg3: Bitmap, arg4: int) -> None: ...
    @overload
    @staticmethod
    def texImage2D(arg0: int, arg1: int, arg2: int, arg3: Bitmap, arg4: int, arg5: int) -> None: ...
    @overload
    @staticmethod
    def texImage2D(arg0: int, arg1: int, arg2: Bitmap, arg3: int) -> None: ...
    @overload
    @staticmethod
    def texSubImage2D(arg0: int, arg1: int, arg2: int, arg3: int, arg4: Bitmap) -> None: ...
    @overload
    @staticmethod
    def texSubImage2D(arg0: int, arg1: int, arg2: int, arg3: int, arg4: Bitmap, arg5: int, arg6: int) -> None: ...
    @staticmethod
    def getEGLErrorString(arg0: int) -> str: ...
