from typing import Any, ClassVar, overload

class Visibility:
    def __init__(self) -> None: ...
    @staticmethod
    def visibilityTest(arg0: list[float], arg1: int, arg2: list[float], arg3: int, arg4: list[str], arg5: int, arg6: int) -> int: ...
    @staticmethod
    def frustumCullSpheres(arg0: list[float], arg1: int, arg2: list[float], arg3: int, arg4: int, arg5: list[int], arg6: int, arg7: int) -> int: ...
    @staticmethod
    def computeBoundingSphere(arg0: list[float], arg1: int, arg2: int, arg3: list[float], arg4: int) -> None: ...
