from typing import Any, ClassVar, overload
from android.adservices.common.AdFilters import AdFilters
from android.net.Uri import Uri
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AdData:
    CREATOR: ClassVar[Creator]
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getRenderUri(self) -> Uri: ...
    def getMetadata(self) -> str: ...
    def getAdCounterKeys(self) -> set: ...
    def getAdFilters(self) -> AdFilters: ...
    def getAdRenderId(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRenderUri(self, arg0: Uri) -> "Builder": ...
        def setMetadata(self, arg0: str) -> "Builder": ...
        def setAdCounterKeys(self, arg0: set) -> "Builder": ...
        def setAdFilters(self, arg0: AdFilters) -> "Builder": ...
        def setAdRenderId(self, arg0: str) -> "Builder": ...
        def build(self) -> "AdData": ...
