from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.time.Duration import Duration

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class KeyedFrequencyCap:
    CREATOR: ClassVar[Creator]
    def getAdCounterKey(self) -> int: ...
    def getMaxCount(self) -> int: ...
    def getInterval(self) -> Duration: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: int, arg1: int, arg2: Duration) -> None: ...
        def setAdCounterKey(self, arg0: int) -> "Builder": ...
        def setMaxCount(self, arg0: int) -> "Builder": ...
        def setInterval(self, arg0: Duration) -> "Builder": ...
        def build(self) -> "KeyedFrequencyCap": ...
