from typing import Any, ClassVar, overload

class OSInfluenceChannel:
    IAM: ClassVar["OSInfluenceChannel"]
    NOTIFICATION: ClassVar["OSInfluenceChannel"]
    Companion: ClassVar["Companion"]
    def equalsName(self, arg0: str) -> bool: ...
    def toString(self) -> str: ...
    @staticmethod
    def values() -> list["OSInfluenceChannel"]: ...
    @staticmethod
    def valueOf(arg0: str) -> "OSInfluenceChannel": ...
    @staticmethod
    def fromString(arg0: str) -> "OSInfluenceChannel": ...

    class Companion:
        def fromString(self, arg0: str) -> "OSInfluenceChannel": ...
