from typing import Any, ClassVar, overload
from influence.domain.OSInfluenceChannel import OSInfluenceChannel
from influence.domain.OSInfluenceType import OSInfluenceType

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class JSONArray: ...  # org.json.JSONArray

class OSInfluence:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: OSInfluenceChannel, arg1: OSInfluenceType, arg2: JSONArray) -> None: ...
    def getInfluenceType(self) -> OSInfluenceType: ...
    def setInfluenceType(self, arg0: OSInfluenceType) -> None: ...
    def getInfluenceChannel(self) -> OSInfluenceChannel: ...
    def getIds(self) -> JSONArray: ...
    def setIds(self, arg0: JSONArray) -> None: ...
    def getDirectId(self) -> str: ...
    def copy(self) -> "OSInfluence": ...
    def toJSONString(self) -> str: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
