from typing import Any, ClassVar, overload
from android.companion.virtual.VirtualDevice import VirtualDevice
from java.util.concurrent.Executor import Executor

class VirtualDeviceManager:
    def getVirtualDevices(self) -> list: ...
    def getVirtualDevice(self, arg0: int) -> VirtualDevice: ...
    def registerVirtualDeviceListener(self, arg0: Executor, arg1: "VirtualDeviceListener") -> None: ...
    def unregisterVirtualDeviceListener(self, arg0: "VirtualDeviceListener") -> None: ...

    class VirtualDeviceListener:
        def onVirtualDeviceCreated(self, arg0: int) -> None: ...
        def onVirtualDeviceClosed(self, arg0: int) -> None: ...
