from typing import Any, ClassVar, overload

class MbmsDownloadSessionCallback:
    def __init__(self) -> None: ...
    def onError(self, arg0: int, arg1: str) -> None: ...
    def onFileServicesUpdated(self, arg0: list) -> None: ...
    def onMiddlewareReady(self) -> None: ...
