from typing import Any, ClassVar, overload
from java.util.Date import Date
from java.util.Locale import Locale

class ServiceInfo:
    def getNameForLocale(self, arg0: Locale) -> str: ...
    def getNamedContentLocales(self) -> set: ...
    def getServiceClassName(self) -> str: ...
    def getLocales(self) -> list: ...
    def getServiceId(self) -> str: ...
    def getSessionStartTime(self) -> Date: ...
    def getSessionEndTime(self) -> Date: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
