from typing import Any, ClassVar, overload
from android.icu.text.DateFormat import DateFormat
from android.icu.util.TimeZone import TimeZone
from android.icu.util.ULocale import ULocale
from java.util.Date import Date
from java.util.Locale import Locale

class ChineseCalendar:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Date) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int) -> None: ...
    @overload
    def __init__(self, arg0: Locale) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone, arg1: Locale) -> None: ...
    @overload
    def __init__(self, arg0: ULocale) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone, arg1: ULocale) -> None: ...
    def handleGetLimit(self, arg0: int, arg1: int) -> int: ...
    def handleGetExtendedYear(self) -> int: ...
    def handleGetMonthLength(self, arg0: int, arg1: int) -> int: ...
    def handleGetDateFormat(self, arg0: str, arg1: str, arg2: ULocale) -> DateFormat: ...
    def getFieldResolutionTable(self) -> list[list[list[int]]]: ...
    def add(self, arg0: int, arg1: int) -> None: ...
    def roll(self, arg0: int, arg1: int) -> None: ...
    def handleComputeFields(self, arg0: int) -> None: ...
    def handleComputeMonthStart(self, arg0: int, arg1: int, arg2: bool) -> int: ...
    def getType(self) -> str: ...
