from typing import Any, ClassVar, overload
from android.icu.util.TimeZone import TimeZone
from android.icu.util.ULocale import ULocale
from java.util.Date import Date
from java.util.Locale import Locale

class CopticCalendar:
    AMSHIR: ClassVar[int]
    BABA: ClassVar[int]
    BARAMHAT: ClassVar[int]
    BARAMOUDA: ClassVar[int]
    BASHANS: ClassVar[int]
    EPEP: ClassVar[int]
    HATOR: ClassVar[int]
    KIAHK: ClassVar[int]
    MESRA: ClassVar[int]
    NASIE: ClassVar[int]
    PAONA: ClassVar[int]
    TOBA: ClassVar[int]
    TOUT: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone) -> None: ...
    @overload
    def __init__(self, arg0: Locale) -> None: ...
    @overload
    def __init__(self, arg0: ULocale) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone, arg1: Locale) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone, arg1: ULocale) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Date) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    def getType(self) -> str: ...
    def handleGetExtendedYear(self) -> int: ...
    def handleComputeFields(self, arg0: int) -> None: ...
    def handleComputeMonthStart(self, arg0: int, arg1: int, arg2: bool) -> int: ...
    def handleGetLimit(self, arg0: int, arg1: int) -> int: ...
