from typing import Any, ClassVar, overload
from android.icu.util.TimeZone import TimeZone
from android.icu.util.ULocale import ULocale
from java.util.Date import Date
from java.util.Locale import Locale

class HebrewCalendar:
    ADAR: ClassVar[int]
    ADAR_1: ClassVar[int]
    AV: ClassVar[int]
    ELUL: ClassVar[int]
    HESHVAN: ClassVar[int]
    IYAR: ClassVar[int]
    KISLEV: ClassVar[int]
    NISAN: ClassVar[int]
    SHEVAT: ClassVar[int]
    SIVAN: ClassVar[int]
    TAMUZ: ClassVar[int]
    TEVET: ClassVar[int]
    TISHRI: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone) -> None: ...
    @overload
    def __init__(self, arg0: Locale) -> None: ...
    @overload
    def __init__(self, arg0: ULocale) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone, arg1: Locale) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone, arg1: ULocale) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: Date) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    def add(self, arg0: int, arg1: int) -> None: ...
    def roll(self, arg0: int, arg1: int) -> None: ...
    def handleGetLimit(self, arg0: int, arg1: int) -> int: ...
    def handleGetMonthLength(self, arg0: int, arg1: int) -> int: ...
    def handleGetYearLength(self, arg0: int) -> int: ...
    def validateField(self, arg0: int) -> None: ...
    def handleComputeFields(self, arg0: int) -> None: ...
    def handleGetExtendedYear(self) -> int: ...
    def handleComputeMonthStart(self, arg0: int, arg1: int, arg2: bool) -> int: ...
    def getType(self) -> str: ...
