from typing import Any, ClassVar, overload

class ValueIterator:
    def next(self, arg0: "Element") -> bool: ...
    def reset(self) -> None: ...
    def setRange(self, arg0: int, arg1: int) -> None: ...

    class Element:
        integer: int
        value: Any
        def __init__(self) -> None: ...
