from typing import Any, ClassVar, overload
from java.util.logging.LogRecord import LogRecord

class ConsoleHandler:
    def __init__(self) -> None: ...
    def publish(self, arg0: LogRecord) -> None: ...
    def close(self) -> None: ...
