from typing import Any, ClassVar, overload

class Level:
    ALL: ClassVar["Level"]
    CONFIG: ClassVar["Level"]
    FINE: ClassVar["Level"]
    FINER: ClassVar["Level"]
    FINEST: ClassVar["Level"]
    INFO: ClassVar["Level"]
    OFF: ClassVar["Level"]
    SEVERE: ClassVar["Level"]
    WARNING: ClassVar["Level"]
    @overload
    def __init__(self, arg0: str, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int, arg2: str) -> None: ...
    def getResourceBundleName(self) -> str: ...
    def getName(self) -> str: ...
    def getLocalizedName(self) -> str: ...
    def toString(self) -> str: ...
    def intValue(self) -> int: ...
    @staticmethod
    def parse(arg0: str) -> "Level": ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
