from typing import Any, ClassVar, overload

class LoggingMXBean:
    def getLoggerNames(self) -> list: ...
    def getLoggerLevel(self, arg0: str) -> str: ...
    def setLoggerLevel(self, arg0: str, arg1: str) -> None: ...
    def getParentLoggerName(self, arg0: str) -> str: ...
