from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from java.util.logging.Formatter import Formatter
from java.util.logging.LogRecord import LogRecord

class StreamHandler:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: OutputStream, arg1: Formatter) -> None: ...
    def setOutputStream(self, arg0: OutputStream) -> None: ...
    def setEncoding(self, arg0: str) -> None: ...
    def publish(self, arg0: LogRecord) -> None: ...
    def isLoggable(self, arg0: LogRecord) -> bool: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
