from typing import Any, ClassVar, overload
from java.util.logging.Handler import Handler
from java.util.logging.LogRecord import LogRecord

class XMLFormatter:
    def __init__(self) -> None: ...
    def format(self, arg0: LogRecord) -> str: ...
    def getHead(self, arg0: Handler) -> str: ...
    def getTail(self, arg0: Handler) -> str: ...
