from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["CardEmulation"]

class CardEmulation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/nfc/cardemulation/CardEmulation"
    ACTION_CHANGE_DEFAULT = JavaStaticField("Ljava/lang/String;")
    CATEGORY_OTHER = JavaStaticField("Ljava/lang/String;")
    CATEGORY_PAYMENT = JavaStaticField("Ljava/lang/String;")
    EXTRA_CATEGORY = JavaStaticField("Ljava/lang/String;")
    EXTRA_SERVICE_COMPONENT = JavaStaticField("Ljava/lang/String;")
    SELECTION_MODE_ALWAYS_ASK = JavaStaticField("I")
    SELECTION_MODE_ASK_IF_CONFLICT = JavaStaticField("I")
    SELECTION_MODE_PREFER_DEFAULT = JavaStaticField("I")
    getInstance = JavaStaticMethod("(Landroid/nfc/NfcAdapter;)Landroid/nfc/cardemulation/CardEmulation;")
    isDefaultServiceForCategory = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;)Z")
    isDefaultServiceForAid = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;)Z")
    categoryAllowsForegroundPreference = JavaMethod("(Ljava/lang/String;)Z")
    getSelectionModeForCategory = JavaMethod("(Ljava/lang/String;)I")
    setShouldDefaultToObserveModeForService = JavaMethod("(Landroid/content/ComponentName;Z)Z")
    registerPollingLoopFilterForService = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;Z)Z")
    removePollingLoopFilterForService = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;)Z")
    registerPollingLoopPatternFilterForService = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;Z)Z")
    removePollingLoopPatternFilterForService = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;)Z")
    registerAidsForService = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;Ljava/util/List;)Z")
    unsetOffHostForService = JavaMethod("(Landroid/content/ComponentName;)Z")
    setOffHostForService = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;)Z")
    getAidsForService = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;)Ljava/util/List;")
    removeAidsForService = JavaMethod("(Landroid/content/ComponentName;Ljava/lang/String;)Z")
    setPreferredService = JavaMethod("(Landroid/app/Activity;Landroid/content/ComponentName;)Z")
    unsetPreferredService = JavaMethod("(Landroid/app/Activity;)Z")
    supportsAidPrefixRegistration = JavaMethod("()Z")
    getAidsForPreferredPaymentService = JavaMethod("()Ljava/util/List;")
    getRouteDestinationForPreferredPaymentService = JavaMethod("()Ljava/lang/String;")
    getDescriptionForPreferredPaymentService = JavaMethod("()Ljava/lang/CharSequence;")