from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.ComponentName import ComponentName
from android.nfc.NfcAdapter import NfcAdapter

class CardEmulation:
    ACTION_CHANGE_DEFAULT: ClassVar[str]
    CATEGORY_OTHER: ClassVar[str]
    CATEGORY_PAYMENT: ClassVar[str]
    EXTRA_CATEGORY: ClassVar[str]
    EXTRA_SERVICE_COMPONENT: ClassVar[str]
    SELECTION_MODE_ALWAYS_ASK: ClassVar[int]
    SELECTION_MODE_ASK_IF_CONFLICT: ClassVar[int]
    SELECTION_MODE_PREFER_DEFAULT: ClassVar[int]
    @staticmethod
    def getInstance(arg0: NfcAdapter) -> "CardEmulation": ...
    def isDefaultServiceForCategory(self, arg0: ComponentName, arg1: str) -> bool: ...
    def isDefaultServiceForAid(self, arg0: ComponentName, arg1: str) -> bool: ...
    def categoryAllowsForegroundPreference(self, arg0: str) -> bool: ...
    def getSelectionModeForCategory(self, arg0: str) -> int: ...
    def setShouldDefaultToObserveModeForService(self, arg0: ComponentName, arg1: bool) -> bool: ...
    def registerPollingLoopFilterForService(self, arg0: ComponentName, arg1: str, arg2: bool) -> bool: ...
    def removePollingLoopFilterForService(self, arg0: ComponentName, arg1: str) -> bool: ...
    def registerPollingLoopPatternFilterForService(self, arg0: ComponentName, arg1: str, arg2: bool) -> bool: ...
    def removePollingLoopPatternFilterForService(self, arg0: ComponentName, arg1: str) -> bool: ...
    def registerAidsForService(self, arg0: ComponentName, arg1: str, arg2: list) -> bool: ...
    def unsetOffHostForService(self, arg0: ComponentName) -> bool: ...
    def setOffHostForService(self, arg0: ComponentName, arg1: str) -> bool: ...
    def getAidsForService(self, arg0: ComponentName, arg1: str) -> list: ...
    def removeAidsForService(self, arg0: ComponentName, arg1: str) -> bool: ...
    def setPreferredService(self, arg0: Activity, arg1: ComponentName) -> bool: ...
    def unsetPreferredService(self, arg0: Activity) -> bool: ...
    def supportsAidPrefixRegistration(self) -> bool: ...
    def getAidsForPreferredPaymentService(self) -> list: ...
    def getRouteDestinationForPreferredPaymentService(self) -> str: ...
    def getDescriptionForPreferredPaymentService(self) -> str: ...
