from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.Bundle import Bundle
from android.os.IBinder import IBinder

class HostApduService:
    DEACTIVATION_DESELECTED: ClassVar[int]
    DEACTIVATION_LINK_LOSS: ClassVar[int]
    SERVICE_INTERFACE: ClassVar[str]
    SERVICE_META_DATA: ClassVar[str]
    def __init__(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def sendResponseApdu(self, arg0: list[int]) -> None: ...
    def notifyUnhandled(self) -> None: ...
    def processPollingFrames(self, arg0: list) -> None: ...
    def processCommandApdu(self, arg0: list[int], arg1: Bundle) -> list[int]: ...
    def onDeactivated(self, arg0: int) -> None: ...
