from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.ComponentName import ComponentName
from android.nfc.NfcAdapter import NfcAdapter

class NfcFCardEmulation:
    @staticmethod
    def getInstance(arg0: NfcAdapter) -> "NfcFCardEmulation": ...
    def getSystemCodeForService(self, arg0: ComponentName) -> str: ...
    def registerSystemCodeForService(self, arg0: ComponentName, arg1: str) -> bool: ...
    def unregisterSystemCodeForService(self, arg0: ComponentName) -> bool: ...
    def getNfcid2ForService(self, arg0: ComponentName) -> str: ...
    def setNfcid2ForService(self, arg0: ComponentName, arg1: str) -> bool: ...
    def enableService(self, arg0: Activity, arg1: ComponentName) -> bool: ...
    def disableService(self, arg0: Activity) -> bool: ...
