from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.os.Parcelable.Creator import Creator

class AdManagerAdViewOptions:
    CREATOR: ClassVar[Creator]
    def getManualImpressionsEnabled(self) -> bool: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setManualImpressionsEnabled(self, arg0: bool) -> "Builder": ...
        def build(self) -> "AdManagerAdViewOptions": ...
