from typing import Any, ClassVar, overload

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator: ...  # android.os.Parcelable.Creator
class Parcel: ...  # android.os.Parcel

class AdManagerAdViewOptions:
    CREATOR: ClassVar[Creator]
    def getManualImpressionsEnabled(self) -> bool: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setManualImpressionsEnabled(self, arg0: bool) -> "Builder": ...
        def build(self) -> "AdManagerAdViewOptions": ...
