from typing import Any, ClassVar, overload
from android.animation.Animator import Animator
from android.content.Context import Context
from android.transition.TransitionValues import TransitionValues
from android.util.AttributeSet import AttributeSet
from android.view.ViewGroup import ViewGroup

class ChangeTransform:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    def getReparentWithOverlay(self) -> bool: ...
    def setReparentWithOverlay(self, arg0: bool) -> None: ...
    def getReparent(self) -> bool: ...
    def setReparent(self, arg0: bool) -> None: ...
    def getTransitionProperties(self) -> list[str]: ...
    def captureStartValues(self, arg0: TransitionValues) -> None: ...
    def captureEndValues(self, arg0: TransitionValues) -> None: ...
    def createAnimator(self, arg0: ViewGroup, arg1: TransitionValues, arg2: TransitionValues) -> Animator: ...
