from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from java.lang.Runnable import Runnable

class Scene:
    @overload
    def __init__(self, arg0: ViewGroup) -> None: ...
    @overload
    def __init__(self, arg0: ViewGroup, arg1: View) -> None: ...
    @overload
    def __init__(self, arg0: ViewGroup, arg1: ViewGroup) -> None: ...
    @staticmethod
    def getSceneForLayout(arg0: ViewGroup, arg1: int, arg2: Context) -> "Scene": ...
    def getSceneRoot(self) -> ViewGroup: ...
    def exit(self) -> None: ...
    def enter(self) -> None: ...
    @staticmethod
    def getCurrentScene(arg0: ViewGroup) -> "Scene": ...
    def setEnterAction(self, arg0: Runnable) -> None: ...
    def setExitAction(self, arg0: Runnable) -> None: ...
