from typing import Any, ClassVar, overload
from android.animation.TimeInterpolator import TimeInterpolator
from android.content.Context import Context
from android.transition.PathMotion import PathMotion
from android.transition.Transition import Transition
from android.transition.TransitionPropagation import TransitionPropagation
from android.transition.TransitionValues import TransitionValues
from android.util.AttributeSet import AttributeSet
from android.view.View import View

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class TransitionListener:
    """Forward declaration for ``android.transition.Transition.TransitionListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.transition.Transition.TransitionListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/transition/Transition/TransitionListener
    """
    ...
class EpicenterCallback:
    """Forward declaration for ``android.transition.Transition.EpicenterCallback``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.transition.Transition.EpicenterCallback')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/transition/Transition/EpicenterCallback
    """
    ...

class TransitionSet:
    ORDERING_SEQUENTIAL: ClassVar[int]
    ORDERING_TOGETHER: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Context, arg1: AttributeSet) -> None: ...
    def setOrdering(self, arg0: int) -> "TransitionSet": ...
    def getOrdering(self) -> int: ...
    def addTransition(self, arg0: Transition) -> "TransitionSet": ...
    def getTransitionCount(self) -> int: ...
    def getTransitionAt(self, arg0: int) -> Transition: ...
    def setDuration(self, arg0: int) -> "TransitionSet": ...
    def setStartDelay(self, arg0: int) -> "TransitionSet": ...
    def setInterpolator(self, arg0: TimeInterpolator) -> "TransitionSet": ...
    @overload
    def addTarget(self, arg0: View) -> "TransitionSet": ...
    @overload
    def addTarget(self, arg0: int) -> "TransitionSet": ...
    @overload
    def addTarget(self, arg0: str) -> "TransitionSet": ...
    @overload
    def addTarget(self, arg0: type) -> "TransitionSet": ...
    def addListener(self, arg0: TransitionListener) -> "TransitionSet": ...
    @overload
    def removeTarget(self, arg0: int) -> "TransitionSet": ...
    @overload
    def removeTarget(self, arg0: View) -> "TransitionSet": ...
    @overload
    def removeTarget(self, arg0: type) -> "TransitionSet": ...
    @overload
    def removeTarget(self, arg0: str) -> "TransitionSet": ...
    @overload
    def excludeTarget(self, arg0: View, arg1: bool) -> Transition: ...
    @overload
    def excludeTarget(self, arg0: str, arg1: bool) -> Transition: ...
    @overload
    def excludeTarget(self, arg0: int, arg1: bool) -> Transition: ...
    @overload
    def excludeTarget(self, arg0: type, arg1: bool) -> Transition: ...
    def removeListener(self, arg0: TransitionListener) -> "TransitionSet": ...
    def setPathMotion(self, arg0: PathMotion) -> None: ...
    def removeTransition(self, arg0: Transition) -> "TransitionSet": ...
    def captureStartValues(self, arg0: TransitionValues) -> None: ...
    def captureEndValues(self, arg0: TransitionValues) -> None: ...
    def setPropagation(self, arg0: TransitionPropagation) -> None: ...
    def setEpicenterCallback(self, arg0: EpicenterCallback) -> None: ...
    def clone(self) -> "TransitionSet": ...
