from typing import Any, ClassVar, overload
from android.transition.TransitionValues import TransitionValues

class VisibilityPropagation:
    def __init__(self) -> None: ...
    def captureValues(self, arg0: TransitionValues) -> None: ...
    def getPropagationProperties(self) -> list[str]: ...
    def getViewVisibility(self, arg0: TransitionValues) -> int: ...
    def getViewX(self, arg0: TransitionValues) -> int: ...
    def getViewY(self, arg0: TransitionValues) -> int: ...
