from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class CRC32:
    def __init__(self) -> None: ...
    @overload
    def update(self, arg0: int) -> None: ...
    @overload
    def update(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    def update(self, arg0: list[int]) -> None: ...
    @overload
    def update(self, arg0: ByteBuffer) -> None: ...
    def reset(self) -> None: ...
    def getValue(self) -> int: ...
