from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.util.zip.Deflater import Deflater

class DeflaterInputStream:
    buf: list[int]
    def_: Deflater
    @overload
    def __init__(self, arg0: InputStream) -> None: ...
    @overload
    def __init__(self, arg0: InputStream, arg1: Deflater) -> None: ...
    @overload
    def __init__(self, arg0: InputStream, arg1: Deflater, arg2: int) -> None: ...
    def close(self) -> None: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    def skip(self, arg0: int) -> int: ...
    def available(self) -> int: ...
    def markSupported(self) -> bool: ...
    def mark(self, arg0: int) -> None: ...
    def reset(self) -> None: ...
