from typing import Any, ClassVar, overload
from android.nfc.Tag import Tag

class MifareUltralight:
    PAGE_SIZE: ClassVar[int]
    TYPE_ULTRALIGHT: ClassVar[int]
    TYPE_ULTRALIGHT_C: ClassVar[int]
    TYPE_UNKNOWN: ClassVar[int]
    @staticmethod
    def get(arg0: Tag) -> "MifareUltralight": ...
    def getType(self) -> int: ...
    def readPages(self, arg0: int) -> list[int]: ...
    def writePage(self, arg0: int, arg1: list[int]) -> None: ...
    def transceive(self, arg0: list[int]) -> list[int]: ...
    def getMaxTransceiveLength(self) -> int: ...
    def setTimeout(self, arg0: int) -> None: ...
    def getTimeout(self) -> int: ...
    def isConnected(self) -> bool: ...
    def getTag(self) -> Tag: ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
