from typing import Any, ClassVar, overload
from android.nfc.NdefMessage import NdefMessage
from android.nfc.Tag import Tag

class Ndef:
    MIFARE_CLASSIC: ClassVar[str]
    NFC_FORUM_TYPE_1: ClassVar[str]
    NFC_FORUM_TYPE_2: ClassVar[str]
    NFC_FORUM_TYPE_3: ClassVar[str]
    NFC_FORUM_TYPE_4: ClassVar[str]
    @staticmethod
    def get(arg0: Tag) -> "Ndef": ...
    def getCachedNdefMessage(self) -> NdefMessage: ...
    def getType(self) -> str: ...
    def getMaxSize(self) -> int: ...
    def isWritable(self) -> bool: ...
    def getNdefMessage(self) -> NdefMessage: ...
    def writeNdefMessage(self, arg0: NdefMessage) -> None: ...
    def canMakeReadOnly(self) -> bool: ...
    def makeReadOnly(self) -> bool: ...
    def isConnected(self) -> bool: ...
    def getTag(self) -> Tag: ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
