from typing import Any, ClassVar, overload
from android.nfc.Tag import Tag

class NfcA:
    @staticmethod
    def get(arg0: Tag) -> "NfcA": ...
    def getAtqa(self) -> list[int]: ...
    def getSak(self) -> int: ...
    def transceive(self, arg0: list[int]) -> list[int]: ...
    def getMaxTransceiveLength(self) -> int: ...
    def setTimeout(self, arg0: int) -> None: ...
    def getTimeout(self) -> int: ...
    def isConnected(self) -> bool: ...
    def getTag(self) -> Tag: ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
