from typing import Any, ClassVar, overload
from android.nfc.Tag import Tag

class NfcB:
    @staticmethod
    def get(arg0: Tag) -> "NfcB": ...
    def getApplicationData(self) -> list[int]: ...
    def getProtocolInfo(self) -> list[int]: ...
    def transceive(self, arg0: list[int]) -> list[int]: ...
    def getMaxTransceiveLength(self) -> int: ...
    def isConnected(self) -> bool: ...
    def getTag(self) -> Tag: ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
