from typing import Any, ClassVar, overload
from android.nfc.Tag import Tag

class NfcV:
    @staticmethod
    def get(arg0: Tag) -> "NfcV": ...
    def getResponseFlags(self) -> int: ...
    def getDsfId(self) -> int: ...
    def transceive(self, arg0: list[int]) -> list[int]: ...
    def getMaxTransceiveLength(self) -> int: ...
    def isConnected(self) -> bool: ...
    def getTag(self) -> Tag: ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
