from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.OutcomeReceiver import OutcomeReceiver
from android.os.ParcelUuid import ParcelUuid
from android.telecom.CallEndpoint import CallEndpoint
from android.telecom.DisconnectCause import DisconnectCause
from java.util.concurrent.Executor import Executor

class CallControl:
    def getCallId(self) -> ParcelUuid: ...
    def setActive(self, arg0: Executor, arg1: OutcomeReceiver) -> None: ...
    def answer(self, arg0: int, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def setInactive(self, arg0: Executor, arg1: OutcomeReceiver) -> None: ...
    def disconnect(self, arg0: DisconnectCause, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def startCallStreaming(self, arg0: Executor, arg1: OutcomeReceiver) -> None: ...
    def requestCallEndpointChange(self, arg0: CallEndpoint, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def requestMuteState(self, arg0: bool, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def requestVideoState(self, arg0: int, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def sendEvent(self, arg0: str, arg1: Bundle) -> None: ...
