from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.IBinder import IBinder

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Details:
    """Forward declaration for ``android.telecom.Call.Details``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.telecom.Call.Details')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/telecom/Call/Details
    """
    ...

class CallScreeningService:
    SERVICE_INTERFACE: ClassVar[str]
    def __init__(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onUnbind(self, arg0: Intent) -> bool: ...
    def onScreenCall(self, arg0: Details) -> None: ...
    def respondToCall(self, arg0: Details, arg1: "CallResponse") -> None: ...

    class CallResponse:
        CALL_COMPOSER_ATTACHMENT_LOCATION: ClassVar[int]
        CALL_COMPOSER_ATTACHMENT_PICTURE: ClassVar[int]
        CALL_COMPOSER_ATTACHMENT_PRIORITY: ClassVar[int]
        CALL_COMPOSER_ATTACHMENT_SUBJECT: ClassVar[int]
        def getDisallowCall(self) -> bool: ...
        def getRejectCall(self) -> bool: ...
        def getSilenceCall(self) -> bool: ...
        def getSkipCallLog(self) -> bool: ...
        def getSkipNotification(self) -> bool: ...
        def getCallComposerAttachmentsToShow(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...

        class Builder:
            def __init__(self) -> None: ...
            def setDisallowCall(self, arg0: bool) -> "Builder": ...
            def setRejectCall(self, arg0: bool) -> "Builder": ...
            def setSilenceCall(self, arg0: bool) -> "Builder": ...
            def setSkipCallLog(self, arg0: bool) -> "Builder": ...
            def setSkipNotification(self, arg0: bool) -> "Builder": ...
            def setCallComposerAttachmentsToShow(self, arg0: int) -> "Builder": ...
            def build(self) -> "CallResponse": ...
