from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.telecom.CallAudioState import CallAudioState
from android.telecom.CallEndpoint import CallEndpoint
from android.telecom.Connection import Connection
from android.telecom.DisconnectCause import DisconnectCause
from android.telecom.PhoneAccountHandle import PhoneAccountHandle
from android.telecom.StatusHints import StatusHints

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class VideoProvider:
    """Forward declaration for ``android.telecom.Connection.VideoProvider``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.telecom.Connection.VideoProvider')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/telecom/Connection/VideoProvider
    """
    ...

class Conference:
    CONNECT_TIME_NOT_SPECIFIED: ClassVar[int]
    def __init__(self, arg0: PhoneAccountHandle) -> None: ...
    def getPhoneAccountHandle(self) -> PhoneAccountHandle: ...
    def getConnections(self) -> list: ...
    def getState(self) -> int: ...
    def isRingbackRequested(self) -> bool: ...
    def getConnectionCapabilities(self) -> int: ...
    def getConnectionProperties(self) -> int: ...
    def getCallAudioState(self) -> CallAudioState: ...
    def getCurrentCallEndpoint(self) -> CallEndpoint: ...
    def getVideoProvider(self) -> VideoProvider: ...
    def getVideoState(self) -> int: ...
    def onDisconnect(self) -> None: ...
    def onSeparate(self, arg0: Connection) -> None: ...
    @overload
    def onMerge(self, arg0: Connection) -> None: ...
    @overload
    def onMerge(self) -> None: ...
    def onHold(self) -> None: ...
    def onUnhold(self) -> None: ...
    def onSwap(self) -> None: ...
    def onPlayDtmfTone(self, arg0: str) -> None: ...
    def onStopDtmfTone(self) -> None: ...
    def onCallAudioStateChanged(self, arg0: CallAudioState) -> None: ...
    def onCallEndpointChanged(self, arg0: CallEndpoint) -> None: ...
    def onAvailableCallEndpointsChanged(self, arg0: list) -> None: ...
    def onMuteStateChanged(self, arg0: bool) -> None: ...
    def onConnectionAdded(self, arg0: Connection) -> None: ...
    def onAddConferenceParticipants(self, arg0: list) -> None: ...
    def onAnswer(self, arg0: int) -> None: ...
    def onReject(self) -> None: ...
    def setOnHold(self) -> None: ...
    def setDialing(self) -> None: ...
    def setRinging(self) -> None: ...
    def setActive(self) -> None: ...
    def setDisconnected(self, arg0: DisconnectCause) -> None: ...
    def getDisconnectCause(self) -> DisconnectCause: ...
    def setConnectionCapabilities(self, arg0: int) -> None: ...
    def setConnectionProperties(self, arg0: int) -> None: ...
    def addConnection(self, arg0: Connection) -> bool: ...
    def removeConnection(self, arg0: Connection) -> None: ...
    def setConferenceableConnections(self, arg0: list) -> None: ...
    def setRingbackRequested(self, arg0: bool) -> None: ...
    def setVideoState(self, arg0: Connection, arg1: int) -> None: ...
    def setVideoProvider(self, arg0: Connection, arg1: VideoProvider) -> None: ...
    def getConferenceableConnections(self) -> list: ...
    def destroy(self) -> None: ...
    def setConnectionTime(self, arg0: int) -> None: ...
    def setConnectionStartElapsedRealTime(self, arg0: int) -> None: ...
    def setConnectionStartElapsedRealtimeMillis(self, arg0: int) -> None: ...
    def getConnectionTime(self) -> int: ...
    def getConnectionStartElapsedRealtimeMillis(self) -> int: ...
    @staticmethod
    def createFailedConference(arg0: DisconnectCause, arg1: PhoneAccountHandle) -> "Conference": ...
    def toString(self) -> str: ...
    def setStatusHints(self, arg0: StatusHints) -> None: ...
    def getStatusHints(self) -> StatusHints: ...
    def setExtras(self, arg0: Bundle) -> None: ...
    def putExtras(self, arg0: Bundle) -> None: ...
    @overload
    def removeExtras(self, arg0: list) -> None: ...
    @overload
    def removeExtras(self, *arg0: str) -> None: ...
    def getExtras(self) -> Bundle: ...
    def onExtrasChanged(self, arg0: Bundle) -> None: ...
    def sendConferenceEvent(self, arg0: str, arg1: Bundle) -> None: ...
