from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.OutcomeReceiver import OutcomeReceiver
from android.telecom.CallAudioState import CallAudioState
from android.telecom.CallEndpoint import CallEndpoint
from android.telecom.Conference import Conference
from android.telecom.DisconnectCause import DisconnectCause
from android.telecom.StatusHints import StatusHints
from android.telecom.VideoProfile import VideoProfile
from android.view.Surface import Surface
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class CameraCapabilities:
    """Forward declaration for ``android.telecom.VideoProfile.CameraCapabilities``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.telecom.VideoProfile.CameraCapabilities')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/telecom/VideoProfile/CameraCapabilities
    """
    ...

class Connection:
    AUDIO_CODEC_AMR: ClassVar[int]
    AUDIO_CODEC_AMR_WB: ClassVar[int]
    AUDIO_CODEC_EVRC: ClassVar[int]
    AUDIO_CODEC_EVRC_B: ClassVar[int]
    AUDIO_CODEC_EVRC_NW: ClassVar[int]
    AUDIO_CODEC_EVRC_WB: ClassVar[int]
    AUDIO_CODEC_EVS_FB: ClassVar[int]
    AUDIO_CODEC_EVS_NB: ClassVar[int]
    AUDIO_CODEC_EVS_SWB: ClassVar[int]
    AUDIO_CODEC_EVS_WB: ClassVar[int]
    AUDIO_CODEC_G711A: ClassVar[int]
    AUDIO_CODEC_G711AB: ClassVar[int]
    AUDIO_CODEC_G711U: ClassVar[int]
    AUDIO_CODEC_G722: ClassVar[int]
    AUDIO_CODEC_G723: ClassVar[int]
    AUDIO_CODEC_G729: ClassVar[int]
    AUDIO_CODEC_GSM_EFR: ClassVar[int]
    AUDIO_CODEC_GSM_FR: ClassVar[int]
    AUDIO_CODEC_GSM_HR: ClassVar[int]
    AUDIO_CODEC_NONE: ClassVar[int]
    AUDIO_CODEC_QCELP13K: ClassVar[int]
    CAPABILITY_ADD_PARTICIPANT: ClassVar[int]
    CAPABILITY_CANNOT_DOWNGRADE_VIDEO_TO_AUDIO: ClassVar[int]
    CAPABILITY_CAN_PAUSE_VIDEO: ClassVar[int]
    CAPABILITY_CAN_PULL_CALL: ClassVar[int]
    CAPABILITY_CAN_SEND_RESPONSE_VIA_CONNECTION: ClassVar[int]
    CAPABILITY_CAN_UPGRADE_TO_VIDEO: ClassVar[int]
    CAPABILITY_DISCONNECT_FROM_CONFERENCE: ClassVar[int]
    CAPABILITY_HOLD: ClassVar[int]
    CAPABILITY_MANAGE_CONFERENCE: ClassVar[int]
    CAPABILITY_MERGE_CONFERENCE: ClassVar[int]
    CAPABILITY_MUTE: ClassVar[int]
    CAPABILITY_REMOTE_PARTY_SUPPORTS_RTT: ClassVar[int]
    CAPABILITY_RESPOND_VIA_TEXT: ClassVar[int]
    CAPABILITY_SEPARATE_FROM_CONFERENCE: ClassVar[int]
    CAPABILITY_SUPPORTS_VT_LOCAL_BIDIRECTIONAL: ClassVar[int]
    CAPABILITY_SUPPORTS_VT_LOCAL_RX: ClassVar[int]
    CAPABILITY_SUPPORTS_VT_LOCAL_TX: ClassVar[int]
    CAPABILITY_SUPPORTS_VT_REMOTE_BIDIRECTIONAL: ClassVar[int]
    CAPABILITY_SUPPORTS_VT_REMOTE_RX: ClassVar[int]
    CAPABILITY_SUPPORTS_VT_REMOTE_TX: ClassVar[int]
    CAPABILITY_SUPPORT_DEFLECT: ClassVar[int]
    CAPABILITY_SUPPORT_HOLD: ClassVar[int]
    CAPABILITY_SWAP_CONFERENCE: ClassVar[int]
    EVENT_CALL_HOLD_FAILED: ClassVar[str]
    EVENT_CALL_MERGE_FAILED: ClassVar[str]
    EVENT_CALL_PULL_FAILED: ClassVar[str]
    EVENT_CALL_REMOTELY_HELD: ClassVar[str]
    EVENT_CALL_REMOTELY_UNHELD: ClassVar[str]
    EVENT_CALL_SWITCH_FAILED: ClassVar[str]
    EVENT_MERGE_COMPLETE: ClassVar[str]
    EVENT_MERGE_START: ClassVar[str]
    EVENT_ON_HOLD_TONE_END: ClassVar[str]
    EVENT_ON_HOLD_TONE_START: ClassVar[str]
    EVENT_RTT_AUDIO_INDICATION_CHANGED: ClassVar[str]
    EXTRA_ANSWERING_DROPS_FG_CALL: ClassVar[str]
    EXTRA_ANSWERING_DROPS_FG_CALL_APP_NAME: ClassVar[str]
    EXTRA_AUDIO_CODEC: ClassVar[str]
    EXTRA_AUDIO_CODEC_BANDWIDTH_KHZ: ClassVar[str]
    EXTRA_AUDIO_CODEC_BITRATE_KBPS: ClassVar[str]
    EXTRA_CALL_SUBJECT: ClassVar[str]
    EXTRA_CHILD_ADDRESS: ClassVar[str]
    EXTRA_IS_RTT_AUDIO_PRESENT: ClassVar[str]
    EXTRA_LAST_FORWARDED_NUMBER: ClassVar[str]
    EXTRA_LAST_KNOWN_CELL_IDENTITY: ClassVar[str]
    EXTRA_SIP_INVITE: ClassVar[str]
    PROPERTY_ASSISTED_DIALING: ClassVar[int]
    PROPERTY_CROSS_SIM: ClassVar[int]
    PROPERTY_HAS_CDMA_VOICE_PRIVACY: ClassVar[int]
    PROPERTY_HIGH_DEF_AUDIO: ClassVar[int]
    PROPERTY_IS_ADHOC_CONFERENCE: ClassVar[int]
    PROPERTY_IS_EXTERNAL_CALL: ClassVar[int]
    PROPERTY_IS_RTT: ClassVar[int]
    PROPERTY_NETWORK_IDENTIFIED_EMERGENCY_CALL: ClassVar[int]
    PROPERTY_SELF_MANAGED: ClassVar[int]
    PROPERTY_WIFI: ClassVar[int]
    STATE_ACTIVE: ClassVar[int]
    STATE_DIALING: ClassVar[int]
    STATE_DISCONNECTED: ClassVar[int]
    STATE_HOLDING: ClassVar[int]
    STATE_INITIALIZING: ClassVar[int]
    STATE_NEW: ClassVar[int]
    STATE_PULLING_CALL: ClassVar[int]
    STATE_RINGING: ClassVar[int]
    VERIFICATION_STATUS_FAILED: ClassVar[int]
    VERIFICATION_STATUS_NOT_VERIFIED: ClassVar[int]
    VERIFICATION_STATUS_PASSED: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def capabilitiesToString(arg0: int) -> str: ...
    @staticmethod
    def propertiesToString(arg0: int) -> str: ...
    def getAddress(self) -> Uri: ...
    def getAddressPresentation(self) -> int: ...
    def getCallerDisplayName(self) -> str: ...
    def getCallerDisplayNamePresentation(self) -> int: ...
    def getState(self) -> int: ...
    def getVideoState(self) -> int: ...
    def getCallAudioState(self) -> CallAudioState: ...
    def getConference(self) -> Conference: ...
    def isRingbackRequested(self) -> bool: ...
    def getAudioModeIsVoip(self) -> bool: ...
    def getStatusHints(self) -> StatusHints: ...
    def getExtras(self) -> Bundle: ...
    def getDisconnectCause(self) -> DisconnectCause: ...
    @staticmethod
    def stateToString(arg0: int) -> str: ...
    def getConnectionCapabilities(self) -> int: ...
    def getConnectionProperties(self) -> int: ...
    def setAddress(self, arg0: Uri, arg1: int) -> None: ...
    def setCallerDisplayName(self, arg0: str, arg1: int) -> None: ...
    def setVideoState(self, arg0: int) -> None: ...
    def setActive(self) -> None: ...
    def setRinging(self) -> None: ...
    def setInitializing(self) -> None: ...
    def setInitialized(self) -> None: ...
    def setDialing(self) -> None: ...
    def setPulling(self) -> None: ...
    def setOnHold(self) -> None: ...
    def setVideoProvider(self, arg0: "VideoProvider") -> None: ...
    def getVideoProvider(self) -> "VideoProvider": ...
    def setDisconnected(self, arg0: DisconnectCause) -> None: ...
    def setPostDialWait(self, arg0: str) -> None: ...
    def setNextPostDialChar(self, arg0: str) -> None: ...
    def setRingbackRequested(self, arg0: bool) -> None: ...
    def setConnectionCapabilities(self, arg0: int) -> None: ...
    def setConnectionProperties(self, arg0: int) -> None: ...
    def destroy(self) -> None: ...
    def setAudioModeIsVoip(self, arg0: bool) -> None: ...
    def setStatusHints(self, arg0: StatusHints) -> None: ...
    def setConferenceableConnections(self, arg0: list) -> None: ...
    def setConferenceables(self, arg0: list) -> None: ...
    def getConferenceables(self) -> list: ...
    def setExtras(self, arg0: Bundle) -> None: ...
    def putExtras(self, arg0: Bundle) -> None: ...
    @overload
    def removeExtras(self, arg0: list) -> None: ...
    @overload
    def removeExtras(self, *arg0: str) -> None: ...
    def setAudioRoute(self, arg0: int) -> None: ...
    def requestBluetoothAudio(self, arg0: BluetoothDevice) -> None: ...
    def requestCallEndpointChange(self, arg0: CallEndpoint, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def getCurrentCallEndpoint(self) -> CallEndpoint: ...
    def sendRttInitiationSuccess(self) -> None: ...
    def sendRttInitiationFailure(self, arg0: int) -> None: ...
    def sendRttSessionRemotelyTerminated(self) -> None: ...
    def sendRemoteRttRequest(self) -> None: ...
    def queryLocationForEmergency(self, arg0: int, arg1: str, arg2: Executor, arg3: OutcomeReceiver) -> None: ...
    def onCallAudioStateChanged(self, arg0: CallAudioState) -> None: ...
    def onCallEndpointChanged(self, arg0: CallEndpoint) -> None: ...
    def onAvailableCallEndpointsChanged(self, arg0: list) -> None: ...
    def onMuteStateChanged(self, arg0: bool) -> None: ...
    def onUsingAlternativeUi(self, arg0: bool) -> None: ...
    def onTrackedByNonUiService(self, arg0: bool) -> None: ...
    def onStateChanged(self, arg0: int) -> None: ...
    def onPlayDtmfTone(self, arg0: str) -> None: ...
    def onStopDtmfTone(self) -> None: ...
    def onDisconnect(self) -> None: ...
    def onSeparate(self) -> None: ...
    def onAddConferenceParticipants(self, arg0: list) -> None: ...
    def onAbort(self) -> None: ...
    def onHold(self) -> None: ...
    def onUnhold(self) -> None: ...
    @overload
    def onAnswer(self, arg0: int) -> None: ...
    @overload
    def onAnswer(self) -> None: ...
    def onDeflect(self, arg0: Uri) -> None: ...
    @overload
    def onReject(self) -> None: ...
    @overload
    def onReject(self, arg0: int) -> None: ...
    @overload
    def onReject(self, arg0: str) -> None: ...
    def onSilence(self) -> None: ...
    def onPostDialContinue(self, arg0: bool) -> None: ...
    def onPullExternalCall(self) -> None: ...
    def onCallEvent(self, arg0: str, arg1: Bundle) -> None: ...
    def onHandoverComplete(self) -> None: ...
    def onExtrasChanged(self, arg0: Bundle) -> None: ...
    def onShowIncomingCallUi(self) -> None: ...
    def onStartRtt(self, arg0: "RttTextStream") -> None: ...
    def onStopRtt(self) -> None: ...
    def handleRttUpgradeResponse(self, arg0: "RttTextStream") -> None: ...
    @staticmethod
    def createFailedConnection(arg0: DisconnectCause) -> "Connection": ...
    @staticmethod
    def createCanceledConnection() -> "Connection": ...
    def notifyConferenceMergeFailed(self) -> None: ...
    def sendConnectionEvent(self, arg0: str, arg1: Bundle) -> None: ...
    def getCallerNumberVerificationStatus(self) -> int: ...
    def setCallerNumberVerificationStatus(self, arg0: int) -> None: ...

    class RttModifyStatus:
        SESSION_MODIFY_REQUEST_FAIL: ClassVar[int]
        SESSION_MODIFY_REQUEST_INVALID: ClassVar[int]
        SESSION_MODIFY_REQUEST_REJECTED_BY_REMOTE: ClassVar[int]
        SESSION_MODIFY_REQUEST_SUCCESS: ClassVar[int]
        SESSION_MODIFY_REQUEST_TIMED_OUT: ClassVar[int]

    class RttTextStream:
        def write(self, arg0: str) -> None: ...
        def read(self) -> str: ...
        def readImmediately(self) -> str: ...

    class VideoProvider:
        SESSION_EVENT_CAMERA_FAILURE: ClassVar[int]
        SESSION_EVENT_CAMERA_PERMISSION_ERROR: ClassVar[int]
        SESSION_EVENT_CAMERA_READY: ClassVar[int]
        SESSION_EVENT_RX_PAUSE: ClassVar[int]
        SESSION_EVENT_RX_RESUME: ClassVar[int]
        SESSION_EVENT_TX_START: ClassVar[int]
        SESSION_EVENT_TX_STOP: ClassVar[int]
        SESSION_MODIFY_REQUEST_FAIL: ClassVar[int]
        SESSION_MODIFY_REQUEST_INVALID: ClassVar[int]
        SESSION_MODIFY_REQUEST_REJECTED_BY_REMOTE: ClassVar[int]
        SESSION_MODIFY_REQUEST_SUCCESS: ClassVar[int]
        SESSION_MODIFY_REQUEST_TIMED_OUT: ClassVar[int]
        def __init__(self) -> None: ...
        def onSetCamera(self, arg0: str) -> None: ...
        def onSetPreviewSurface(self, arg0: Surface) -> None: ...
        def onSetDisplaySurface(self, arg0: Surface) -> None: ...
        def onSetDeviceOrientation(self, arg0: int) -> None: ...
        def onSetZoom(self, arg0: float) -> None: ...
        def onSendSessionModifyRequest(self, arg0: VideoProfile, arg1: VideoProfile) -> None: ...
        def onSendSessionModifyResponse(self, arg0: VideoProfile) -> None: ...
        def onRequestCameraCapabilities(self) -> None: ...
        def onRequestConnectionDataUsage(self) -> None: ...
        def onSetPauseImage(self, arg0: Uri) -> None: ...
        def receiveSessionModifyRequest(self, arg0: VideoProfile) -> None: ...
        def receiveSessionModifyResponse(self, arg0: int, arg1: VideoProfile, arg2: VideoProfile) -> None: ...
        def handleCallSessionEvent(self, arg0: int) -> None: ...
        def changePeerDimensions(self, arg0: int, arg1: int) -> None: ...
        def setCallDataUsage(self, arg0: int) -> None: ...
        def changeCameraCapabilities(self, arg0: CameraCapabilities) -> None: ...
        def changeVideoQuality(self, arg0: int) -> None: ...
