from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.telecom.PhoneAccountHandle import PhoneAccountHandle

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...
class RttTextStream:
    """Forward declaration for ``android.telecom.Connection.RttTextStream``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.telecom.Connection.RttTextStream')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/telecom/Connection/RttTextStream
    """
    ...

class ConnectionRequest:
    CREATOR: ClassVar[Creator]
    @overload
    def __init__(self, arg0: PhoneAccountHandle, arg1: Uri, arg2: Bundle) -> None: ...
    @overload
    def __init__(self, arg0: PhoneAccountHandle, arg1: Uri, arg2: Bundle, arg3: int) -> None: ...
    def getAccountHandle(self) -> PhoneAccountHandle: ...
    def getAddress(self) -> Uri: ...
    def getParticipants(self) -> list: ...
    def getExtras(self) -> Bundle: ...
    def getVideoState(self) -> int: ...
    def isAdhocConferenceCall(self) -> bool: ...
    def getRttTextStream(self) -> RttTextStream: ...
    def isRequestingRtt(self) -> bool: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
