from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from android.content.Intent import Intent
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.os.IBinder import IBinder
from android.os.OutcomeReceiver import OutcomeReceiver
from android.telecom.Call import Call
from android.telecom.CallAudioState import CallAudioState
from android.telecom.CallEndpoint import CallEndpoint
from android.telecom.VideoProfile import VideoProfile
from android.view.Surface import Surface
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class CameraCapabilities:
    """Forward declaration for ``android.telecom.VideoProfile.CameraCapabilities``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.telecom.VideoProfile.CameraCapabilities')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/telecom/VideoProfile/CameraCapabilities
    """
    ...

class InCallService:
    SERVICE_INTERFACE: ClassVar[str]
    def __init__(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onUnbind(self, arg0: Intent) -> bool: ...
    def getCalls(self) -> list: ...
    def canAddCall(self) -> bool: ...
    def getCallAudioState(self) -> CallAudioState: ...
    def setMuted(self, arg0: bool) -> None: ...
    def setAudioRoute(self, arg0: int) -> None: ...
    def requestBluetoothAudio(self, arg0: BluetoothDevice) -> None: ...
    def requestCallEndpointChange(self, arg0: CallEndpoint, arg1: Executor, arg2: OutcomeReceiver) -> None: ...
    def getCurrentCallEndpoint(self) -> CallEndpoint: ...
    def onCallAudioStateChanged(self, arg0: CallAudioState) -> None: ...
    def onCallEndpointChanged(self, arg0: CallEndpoint) -> None: ...
    def onAvailableCallEndpointsChanged(self, arg0: list) -> None: ...
    def onMuteStateChanged(self, arg0: bool) -> None: ...
    def onBringToForeground(self, arg0: bool) -> None: ...
    def onCallAdded(self, arg0: Call) -> None: ...
    def onCallRemoved(self, arg0: Call) -> None: ...
    def onCanAddCallChanged(self, arg0: bool) -> None: ...
    def onSilenceRinger(self) -> None: ...
    def onConnectionEvent(self, arg0: Call, arg1: str, arg2: Bundle) -> None: ...

    class VideoCall:
        def __init__(self) -> None: ...
        @overload
        def registerCallback(self, arg0: "Callback") -> None: ...
        @overload
        def registerCallback(self, arg0: "Callback", arg1: Handler) -> None: ...
        def unregisterCallback(self, arg0: "Callback") -> None: ...
        def setCamera(self, arg0: str) -> None: ...
        def setPreviewSurface(self, arg0: Surface) -> None: ...
        def setDisplaySurface(self, arg0: Surface) -> None: ...
        def setDeviceOrientation(self, arg0: int) -> None: ...
        def setZoom(self, arg0: float) -> None: ...
        def sendSessionModifyRequest(self, arg0: VideoProfile) -> None: ...
        def sendSessionModifyResponse(self, arg0: VideoProfile) -> None: ...
        def requestCameraCapabilities(self) -> None: ...
        def requestCallDataUsage(self) -> None: ...
        def setPauseImage(self, arg0: Uri) -> None: ...

        class Callback:
            def __init__(self) -> None: ...
            def onSessionModifyRequestReceived(self, arg0: VideoProfile) -> None: ...
            def onSessionModifyResponseReceived(self, arg0: int, arg1: VideoProfile, arg2: VideoProfile) -> None: ...
            def onCallSessionEvent(self, arg0: int) -> None: ...
            def onPeerDimensionsChanged(self, arg0: int, arg1: int) -> None: ...
            def onVideoQualityChanged(self, arg0: int) -> None: ...
            def onCallDataUsageChanged(self, arg0: int) -> None: ...
            def onCameraCapabilitiesChanged(self, arg0: CameraCapabilities) -> None: ...
