"""
OneSignal Android SDK 4.8.10 — pyjnius usage example.

This shows how to call the OneSignal Java API from Python (Kivy / android).
The wrappers in src/onesignal_pyjnius/ are auto-generated by pyjnius-wrap from
the OneSignal-4.8.10.aar bytecode.

Regenerate with:
    swift run pyjnius-wrap OneSignal-4.8.10.aar src/onesignal_pyjnius/

On-device only (requires Android + pyjnius).
"""

from onesignal_pyjnius.com.onesignal.OneSignal import OneSignal
from onesignal_pyjnius.com.onesignal.OSDeviceState import OSDeviceState


def init_onesignal(context, app_id: str) -> None:
    OneSignal.setAppId(app_id)
    OneSignal.initWithContext(context)


def get_player_id() -> str | None:
    state: OSDeviceState = OneSignal.getDeviceState()
    if state is None:
        return None
    return state.getUserId()


def set_push_notification_handler(handler) -> None:
    """
    handler must implement OneSignal.OSNotificationWillShowInForegroundHandler.
    Use PythonJavaClass to create one:

        from jnius import PythonJavaClass, java_method

        class MyHandler(PythonJavaClass):
            __javainterfaces__ = [
                "com/onesignal/OneSignal$OSNotificationWillShowInForegroundHandler"
            ]

            @java_method("(Lcom/onesignal/OSNotificationReceivedEvent;)V")
            def notificationWillShowInForeground(self, event):
                event.complete(event.getNotification())  # show as-is
    """
    OneSignal.setNotificationWillShowInForegroundHandler(handler)


def send_tag(key: str, value: str) -> None:
    OneSignal.sendTag(key, value)


def set_external_user_id(user_id: str) -> None:
    OneSignal.setExternalUserId(user_id)
