from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.graphics.BlendMode import BlendMode
from android.graphics.DrawFilter import DrawFilter
from android.graphics.Matrix import Matrix
from android.graphics.Matrix44 import Matrix44
from android.graphics.Mesh import Mesh
from android.graphics.NinePatch import NinePatch
from android.graphics.Paint import Paint
from android.graphics.Path import Path
from android.graphics.Picture import Picture
from android.graphics.Rect import Rect
from android.graphics.RectF import RectF
from android.graphics.RenderNode import RenderNode
from android.graphics.Shader import Shader
from android.graphics.fonts.Font import Font
from android.graphics.text.MeasuredText import MeasuredText

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Op:
    """Forward declaration for ``android.graphics.Region.Op``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.Region.Op')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/Region/Op
    """
    ...
class Mode:
    """Forward declaration for ``android.graphics.PorterDuff.Mode``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.graphics.PorterDuff.Mode')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/graphics/PorterDuff/Mode
    """
    ...

class Canvas:
    ALL_SAVE_FLAG: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Bitmap) -> None: ...
    def isHardwareAccelerated(self) -> bool: ...
    def setBitmap(self, arg0: Bitmap) -> None: ...
    def enableZ(self) -> None: ...
    def disableZ(self) -> None: ...
    def isOpaque(self) -> bool: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getDensity(self) -> int: ...
    def setDensity(self, arg0: int) -> None: ...
    def getMaximumBitmapWidth(self) -> int: ...
    def getMaximumBitmapHeight(self) -> int: ...
    def save(self) -> int: ...
    @overload
    def saveLayer(self, arg0: RectF, arg1: Paint, arg2: int) -> int: ...
    @overload
    def saveLayer(self, arg0: RectF, arg1: Paint) -> int: ...
    @overload
    def saveLayer(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: Paint, arg5: int) -> int: ...
    @overload
    def saveLayer(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: Paint) -> int: ...
    @overload
    def saveLayerAlpha(self, arg0: RectF, arg1: int, arg2: int) -> int: ...
    @overload
    def saveLayerAlpha(self, arg0: RectF, arg1: int) -> int: ...
    @overload
    def saveLayerAlpha(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: int, arg5: int) -> int: ...
    @overload
    def saveLayerAlpha(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: int) -> int: ...
    def restore(self) -> None: ...
    def getSaveCount(self) -> int: ...
    def restoreToCount(self, arg0: int) -> None: ...
    def translate(self, arg0: float, arg1: float) -> None: ...
    @overload
    def scale(self, arg0: float, arg1: float) -> None: ...
    @overload
    def scale(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    @overload
    def rotate(self, arg0: float) -> None: ...
    @overload
    def rotate(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def skew(self, arg0: float, arg1: float) -> None: ...
    @overload
    def concat(self, arg0: Matrix) -> None: ...
    @overload
    def concat(self, arg0: Matrix44) -> None: ...
    def setMatrix(self, arg0: Matrix) -> None: ...
    @overload
    def getMatrix(self, arg0: Matrix) -> None: ...
    @overload
    def getMatrix(self) -> Matrix: ...
    @overload
    def clipRect(self, arg0: RectF, arg1: Op) -> bool: ...
    @overload
    def clipRect(self, arg0: Rect, arg1: Op) -> bool: ...
    @overload
    def clipRect(self, arg0: RectF) -> bool: ...
    @overload
    def clipRect(self, arg0: Rect) -> bool: ...
    @overload
    def clipRect(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: Op) -> bool: ...
    @overload
    def clipRect(self, arg0: float, arg1: float, arg2: float, arg3: float) -> bool: ...
    @overload
    def clipRect(self, arg0: int, arg1: int, arg2: int, arg3: int) -> bool: ...
    @overload
    def clipOutRect(self, arg0: RectF) -> bool: ...
    @overload
    def clipOutRect(self, arg0: Rect) -> bool: ...
    @overload
    def clipOutRect(self, arg0: float, arg1: float, arg2: float, arg3: float) -> bool: ...
    @overload
    def clipOutRect(self, arg0: int, arg1: int, arg2: int, arg3: int) -> bool: ...
    @overload
    def clipPath(self, arg0: Path, arg1: Op) -> bool: ...
    @overload
    def clipPath(self, arg0: Path) -> bool: ...
    def clipOutPath(self, arg0: Path) -> bool: ...
    def clipShader(self, arg0: Shader) -> None: ...
    def clipOutShader(self, arg0: Shader) -> None: ...
    def getDrawFilter(self) -> DrawFilter: ...
    def setDrawFilter(self, arg0: DrawFilter) -> None: ...
    @overload
    def quickReject(self, arg0: RectF, arg1: "EdgeType") -> bool: ...
    @overload
    def quickReject(self, arg0: RectF) -> bool: ...
    @overload
    def quickReject(self, arg0: Path, arg1: "EdgeType") -> bool: ...
    @overload
    def quickReject(self, arg0: Path) -> bool: ...
    @overload
    def quickReject(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: "EdgeType") -> bool: ...
    @overload
    def quickReject(self, arg0: float, arg1: float, arg2: float, arg3: float) -> bool: ...
    @overload
    def getClipBounds(self, arg0: Rect) -> bool: ...
    @overload
    def getClipBounds(self) -> Rect: ...
    @overload
    def drawPicture(self, arg0: Picture) -> None: ...
    @overload
    def drawPicture(self, arg0: Picture, arg1: RectF) -> None: ...
    @overload
    def drawPicture(self, arg0: Picture, arg1: Rect) -> None: ...
    @overload
    def drawArc(self, arg0: RectF, arg1: float, arg2: float, arg3: bool, arg4: Paint) -> None: ...
    @overload
    def drawArc(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: bool, arg7: Paint) -> None: ...
    def drawARGB(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def drawBitmap(self, arg0: Bitmap, arg1: float, arg2: float, arg3: Paint) -> None: ...
    @overload
    def drawBitmap(self, arg0: Bitmap, arg1: Rect, arg2: RectF, arg3: Paint) -> None: ...
    @overload
    def drawBitmap(self, arg0: Bitmap, arg1: Rect, arg2: Rect, arg3: Paint) -> None: ...
    @overload
    def drawBitmap(self, arg0: list[int], arg1: int, arg2: int, arg3: float, arg4: float, arg5: int, arg6: int, arg7: bool, arg8: Paint) -> None: ...
    @overload
    def drawBitmap(self, arg0: list[int], arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: bool, arg8: Paint) -> None: ...
    @overload
    def drawBitmap(self, arg0: Bitmap, arg1: Matrix, arg2: Paint) -> None: ...
    def drawBitmapMesh(self, arg0: Bitmap, arg1: int, arg2: int, arg3: list[float], arg4: int, arg5: list[int], arg6: int, arg7: Paint) -> None: ...
    def drawCircle(self, arg0: float, arg1: float, arg2: float, arg3: Paint) -> None: ...
    @overload
    def drawColor(self, arg0: int) -> None: ...
    @overload
    def drawColor(self, arg0: int) -> None: ...
    @overload
    def drawColor(self, arg0: int, arg1: Mode) -> None: ...
    @overload
    def drawColor(self, arg0: int, arg1: BlendMode) -> None: ...
    @overload
    def drawColor(self, arg0: int, arg1: BlendMode) -> None: ...
    def drawLine(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: Paint) -> None: ...
    @overload
    def drawLines(self, arg0: list[float], arg1: int, arg2: int, arg3: Paint) -> None: ...
    @overload
    def drawLines(self, arg0: list[float], arg1: Paint) -> None: ...
    @overload
    def drawOval(self, arg0: RectF, arg1: Paint) -> None: ...
    @overload
    def drawOval(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: Paint) -> None: ...
    def drawPaint(self, arg0: Paint) -> None: ...
    @overload
    def drawPatch(self, arg0: NinePatch, arg1: Rect, arg2: Paint) -> None: ...
    @overload
    def drawPatch(self, arg0: NinePatch, arg1: RectF, arg2: Paint) -> None: ...
    def drawPath(self, arg0: Path, arg1: Paint) -> None: ...
    def drawPoint(self, arg0: float, arg1: float, arg2: Paint) -> None: ...
    @overload
    def drawPoints(self, arg0: list[float], arg1: int, arg2: int, arg3: Paint) -> None: ...
    @overload
    def drawPoints(self, arg0: list[float], arg1: Paint) -> None: ...
    @overload
    def drawPosText(self, arg0: list[str], arg1: int, arg2: int, arg3: list[float], arg4: Paint) -> None: ...
    @overload
    def drawPosText(self, arg0: str, arg1: list[float], arg2: Paint) -> None: ...
    @overload
    def drawRect(self, arg0: RectF, arg1: Paint) -> None: ...
    @overload
    def drawRect(self, arg0: Rect, arg1: Paint) -> None: ...
    @overload
    def drawRect(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: Paint) -> None: ...
    def drawRGB(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def drawRoundRect(self, arg0: RectF, arg1: float, arg2: float, arg3: Paint) -> None: ...
    @overload
    def drawRoundRect(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: Paint) -> None: ...
    @overload
    def drawDoubleRoundRect(self, arg0: RectF, arg1: float, arg2: float, arg3: RectF, arg4: float, arg5: float, arg6: Paint) -> None: ...
    @overload
    def drawDoubleRoundRect(self, arg0: RectF, arg1: list[float], arg2: RectF, arg3: list[float], arg4: Paint) -> None: ...
    def drawGlyphs(self, arg0: list[int], arg1: int, arg2: list[float], arg3: int, arg4: int, arg5: Font, arg6: Paint) -> None: ...
    @overload
    def drawText(self, arg0: list[str], arg1: int, arg2: int, arg3: float, arg4: float, arg5: Paint) -> None: ...
    @overload
    def drawText(self, arg0: str, arg1: float, arg2: float, arg3: Paint) -> None: ...
    @overload
    def drawText(self, arg0: str, arg1: int, arg2: int, arg3: float, arg4: float, arg5: Paint) -> None: ...
    @overload
    def drawText(self, arg0: str, arg1: int, arg2: int, arg3: float, arg4: float, arg5: Paint) -> None: ...
    @overload
    def drawTextOnPath(self, arg0: list[str], arg1: int, arg2: int, arg3: Path, arg4: float, arg5: float, arg6: Paint) -> None: ...
    @overload
    def drawTextOnPath(self, arg0: str, arg1: Path, arg2: float, arg3: float, arg4: Paint) -> None: ...
    @overload
    def drawTextRun(self, arg0: list[str], arg1: int, arg2: int, arg3: int, arg4: int, arg5: float, arg6: float, arg7: bool, arg8: Paint) -> None: ...
    @overload
    def drawTextRun(self, arg0: str, arg1: int, arg2: int, arg3: int, arg4: int, arg5: float, arg6: float, arg7: bool, arg8: Paint) -> None: ...
    @overload
    def drawTextRun(self, arg0: MeasuredText, arg1: int, arg2: int, arg3: int, arg4: int, arg5: float, arg6: float, arg7: bool, arg8: Paint) -> None: ...
    def drawVertices(self, arg0: "VertexMode", arg1: int, arg2: list[float], arg3: int, arg4: list[float], arg5: int, arg6: list[int], arg7: int, arg8: list[int], arg9: int, arg10: int, arg11: Paint) -> None: ...
    def drawRenderNode(self, arg0: RenderNode) -> None: ...
    def drawMesh(self, arg0: Mesh, arg1: BlendMode, arg2: Paint) -> None: ...

    class EdgeType:
        BW: ClassVar["EdgeType"]
        AA: ClassVar["EdgeType"]
        @staticmethod
        def values() -> list["EdgeType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "EdgeType": ...

    class VertexMode:
        TRIANGLES: ClassVar["VertexMode"]
        TRIANGLE_STRIP: ClassVar["VertexMode"]
        TRIANGLE_FAN: ClassVar["VertexMode"]
        @staticmethod
        def values() -> list["VertexMode"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "VertexMode": ...
