from typing import Any, ClassVar, overload

class ColorMatrix:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: list[float]) -> None: ...
    @overload
    def __init__(self, arg0: "ColorMatrix") -> None: ...
    def getArray(self) -> list[float]: ...
    def reset(self) -> None: ...
    @overload
    def set(self, arg0: "ColorMatrix") -> None: ...
    @overload
    def set(self, arg0: list[float]) -> None: ...
    def setScale(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def setRotate(self, arg0: int, arg1: float) -> None: ...
    def setConcat(self, arg0: "ColorMatrix", arg1: "ColorMatrix") -> None: ...
    def preConcat(self, arg0: "ColorMatrix") -> None: ...
    def postConcat(self, arg0: "ColorMatrix") -> None: ...
    def setSaturation(self, arg0: float) -> None: ...
    def setRGB2YUV(self) -> None: ...
    def setYUV2RGB(self) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
