from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Gainmap:
    CREATOR: ClassVar[Creator]
    @overload
    def __init__(self, arg0: Bitmap) -> None: ...
    @overload
    def __init__(self, arg0: "Gainmap", arg1: Bitmap) -> None: ...
    def getGainmapContents(self) -> Bitmap: ...
    def setGainmapContents(self, arg0: Bitmap) -> None: ...
    def setRatioMin(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def getRatioMin(self) -> list[float]: ...
    def setRatioMax(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def getRatioMax(self) -> list[float]: ...
    def setGamma(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def getGamma(self) -> list[float]: ...
    def setEpsilonSdr(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def getEpsilonSdr(self) -> list[float]: ...
    def setEpsilonHdr(self, arg0: float, arg1: float, arg2: float) -> None: ...
    def getEpsilonHdr(self) -> list[float]: ...
    def setDisplayRatioForFullHdr(self, arg0: float) -> None: ...
    def getDisplayRatioForFullHdr(self) -> float: ...
    def setMinDisplayRatioForHdrTransition(self, arg0: float) -> None: ...
    def getMinDisplayRatioForHdrTransition(self) -> float: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
