from typing import Any, ClassVar, overload

class LightingColorFilter:
    def __init__(self, arg0: int, arg1: int) -> None: ...
    def getColorMultiply(self) -> int: ...
    def getColorAdd(self) -> int: ...
