from typing import Any, ClassVar, overload
from android.graphics.Matrix import Matrix

class Matrix44:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Matrix) -> None: ...
    def getValues(self, arg0: list[float]) -> None: ...
    def setValues(self, arg0: list[float]) -> None: ...
    def get(self, arg0: int, arg1: int) -> float: ...
    def set(self, arg0: int, arg1: int, arg2: float) -> None: ...
    def reset(self) -> None: ...
    def invert(self) -> bool: ...
    def isIdentity(self) -> bool: ...
    @overload
    def map(self, arg0: float, arg1: float, arg2: float, arg3: float) -> list[float]: ...
    @overload
    def map(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: list[float]) -> None: ...
    def concat(self, arg0: "Matrix44") -> "Matrix44": ...
    def rotate(self, arg0: float, arg1: float, arg2: float, arg3: float) -> "Matrix44": ...
    def scale(self, arg0: float, arg1: float, arg2: float) -> "Matrix44": ...
    def translate(self, arg0: float, arg1: float, arg2: float) -> "Matrix44": ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
