from typing import Any, ClassVar, overload
from android.graphics.RectF import RectF
from java.io.PrintWriter import PrintWriter

class Matrix:
    IDENTITY_MATRIX: ClassVar["Matrix"]
    MPERSP_0: ClassVar[int]
    MPERSP_1: ClassVar[int]
    MPERSP_2: ClassVar[int]
    MSCALE_X: ClassVar[int]
    MSCALE_Y: ClassVar[int]
    MSKEW_X: ClassVar[int]
    MSKEW_Y: ClassVar[int]
    MTRANS_X: ClassVar[int]
    MTRANS_Y: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "Matrix") -> None: ...
    def isIdentity(self) -> bool: ...
    def isAffine(self) -> bool: ...
    def rectStaysRect(self) -> bool: ...
    def set(self, arg0: "Matrix") -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def reset(self) -> None: ...
    def setTranslate(self, arg0: float, arg1: float) -> None: ...
    @overload
    def setScale(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    @overload
    def setScale(self, arg0: float, arg1: float) -> None: ...
    @overload
    def setRotate(self, arg0: float, arg1: float, arg2: float) -> None: ...
    @overload
    def setRotate(self, arg0: float) -> None: ...
    @overload
    def setSinCos(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    @overload
    def setSinCos(self, arg0: float, arg1: float) -> None: ...
    @overload
    def setSkew(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    @overload
    def setSkew(self, arg0: float, arg1: float) -> None: ...
    def setConcat(self, arg0: "Matrix", arg1: "Matrix") -> bool: ...
    def preTranslate(self, arg0: float, arg1: float) -> bool: ...
    @overload
    def preScale(self, arg0: float, arg1: float, arg2: float, arg3: float) -> bool: ...
    @overload
    def preScale(self, arg0: float, arg1: float) -> bool: ...
    @overload
    def preRotate(self, arg0: float, arg1: float, arg2: float) -> bool: ...
    @overload
    def preRotate(self, arg0: float) -> bool: ...
    @overload
    def preSkew(self, arg0: float, arg1: float, arg2: float, arg3: float) -> bool: ...
    @overload
    def preSkew(self, arg0: float, arg1: float) -> bool: ...
    def preConcat(self, arg0: "Matrix") -> bool: ...
    def postTranslate(self, arg0: float, arg1: float) -> bool: ...
    @overload
    def postScale(self, arg0: float, arg1: float, arg2: float, arg3: float) -> bool: ...
    @overload
    def postScale(self, arg0: float, arg1: float) -> bool: ...
    @overload
    def postRotate(self, arg0: float, arg1: float, arg2: float) -> bool: ...
    @overload
    def postRotate(self, arg0: float) -> bool: ...
    @overload
    def postSkew(self, arg0: float, arg1: float, arg2: float, arg3: float) -> bool: ...
    @overload
    def postSkew(self, arg0: float, arg1: float) -> bool: ...
    def postConcat(self, arg0: "Matrix") -> bool: ...
    def setRectToRect(self, arg0: RectF, arg1: RectF, arg2: "ScaleToFit") -> bool: ...
    def setPolyToPoly(self, arg0: list[float], arg1: int, arg2: list[float], arg3: int, arg4: int) -> bool: ...
    def invert(self, arg0: "Matrix") -> bool: ...
    @overload
    def mapPoints(self, arg0: list[float], arg1: int, arg2: list[float], arg3: int, arg4: int) -> None: ...
    @overload
    def mapPoints(self, arg0: list[float], arg1: list[float]) -> None: ...
    @overload
    def mapPoints(self, arg0: list[float]) -> None: ...
    @overload
    def mapVectors(self, arg0: list[float], arg1: int, arg2: list[float], arg3: int, arg4: int) -> None: ...
    @overload
    def mapVectors(self, arg0: list[float], arg1: list[float]) -> None: ...
    @overload
    def mapVectors(self, arg0: list[float]) -> None: ...
    @overload
    def mapRect(self, arg0: RectF, arg1: RectF) -> bool: ...
    @overload
    def mapRect(self, arg0: RectF) -> bool: ...
    def mapRadius(self, arg0: float) -> float: ...
    def getValues(self, arg0: list[float]) -> None: ...
    def setValues(self, arg0: list[float]) -> None: ...
    def toString(self) -> str: ...
    def toShortString(self) -> str: ...
    def dump(self, arg0: PrintWriter) -> None: ...

    class ScaleToFit:
        FILL: ClassVar["ScaleToFit"]
        START: ClassVar["ScaleToFit"]
        CENTER: ClassVar["ScaleToFit"]
        END: ClassVar["ScaleToFit"]
        @staticmethod
        def values() -> list["ScaleToFit"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "ScaleToFit": ...
