from typing import Any, ClassVar, overload
from android.graphics.ColorSpace import ColorSpace

class MeshSpecification:
    ALPHA_TYPE_OPAQUE: ClassVar[int]
    ALPHA_TYPE_PREMULTIPLIED: ClassVar[int]
    ALPHA_TYPE_UNKNOWN: ClassVar[int]
    ALPHA_TYPE_UNPREMULTIPLIED: ClassVar[int]
    TYPE_FLOAT: ClassVar[int]
    TYPE_FLOAT2: ClassVar[int]
    TYPE_FLOAT3: ClassVar[int]
    TYPE_FLOAT4: ClassVar[int]
    TYPE_UBYTE4: ClassVar[int]
    @overload
    @staticmethod
    def make(arg0: list["Attribute"], arg1: int, arg2: list["Varying"], arg3: str, arg4: str) -> "MeshSpecification": ...
    @overload
    @staticmethod
    def make(arg0: list["Attribute"], arg1: int, arg2: list["Varying"], arg3: str, arg4: str, arg5: ColorSpace) -> "MeshSpecification": ...
    @overload
    @staticmethod
    def make(arg0: list["Attribute"], arg1: int, arg2: list["Varying"], arg3: str, arg4: str, arg5: ColorSpace, arg6: int) -> "MeshSpecification": ...

    class Attribute:
        def __init__(self, arg0: int, arg1: int, arg2: str) -> None: ...
        def getType(self) -> int: ...
        def getOffset(self) -> int: ...
        def getName(self) -> str: ...
        def toString(self) -> str: ...

    class Varying:
        def __init__(self, arg0: int, arg1: str) -> None: ...
        def getType(self) -> int: ...
        def getName(self) -> str: ...
        def toString(self) -> str: ...
