from typing import Any, ClassVar, overload
from android.graphics.Path import Path
from android.graphics.Rect import Rect

class Outline:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "Outline") -> None: ...
    def setEmpty(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def canClip(self) -> bool: ...
    def setAlpha(self, arg0: float) -> None: ...
    def getAlpha(self) -> float: ...
    def set(self, arg0: "Outline") -> None: ...
    @overload
    def setRect(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def setRect(self, arg0: Rect) -> None: ...
    @overload
    def setRoundRect(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: float) -> None: ...
    @overload
    def setRoundRect(self, arg0: Rect, arg1: float) -> None: ...
    def getRect(self, arg0: Rect) -> bool: ...
    def getRadius(self) -> float: ...
    @overload
    def setOval(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def setOval(self, arg0: Rect) -> None: ...
    def setConvexPath(self, arg0: Path) -> None: ...
    def setPath(self, arg0: Path) -> None: ...
    def offset(self, arg0: int, arg1: int) -> None: ...
