from typing import Any, ClassVar, overload
from android.graphics.Matrix import Matrix
from android.graphics.PathIterator import PathIterator
from android.graphics.RectF import RectF

class Path:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "Path") -> None: ...
    def reset(self) -> None: ...
    def rewind(self) -> None: ...
    def set(self, arg0: "Path") -> None: ...
    def getPathIterator(self) -> PathIterator: ...
    @overload
    def op(self, arg0: "Path", arg1: "Op") -> bool: ...
    @overload
    def op(self, arg0: "Path", arg1: "Path", arg2: "Op") -> bool: ...
    def isConvex(self) -> bool: ...
    def getFillType(self) -> "FillType": ...
    def setFillType(self, arg0: "FillType") -> None: ...
    def isInverseFillType(self) -> bool: ...
    def toggleInverseFillType(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def isRect(self, arg0: RectF) -> bool: ...
    def computeBounds(self, arg0: RectF, arg1: bool) -> None: ...
    def incReserve(self, arg0: int) -> None: ...
    def moveTo(self, arg0: float, arg1: float) -> None: ...
    def rMoveTo(self, arg0: float, arg1: float) -> None: ...
    def lineTo(self, arg0: float, arg1: float) -> None: ...
    def rLineTo(self, arg0: float, arg1: float) -> None: ...
    def quadTo(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def rQuadTo(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def conicTo(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float) -> None: ...
    def rConicTo(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float) -> None: ...
    def cubicTo(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None: ...
    def rCubicTo(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None: ...
    @overload
    def arcTo(self, arg0: RectF, arg1: float, arg2: float, arg3: bool) -> None: ...
    @overload
    def arcTo(self, arg0: RectF, arg1: float, arg2: float) -> None: ...
    @overload
    def arcTo(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: bool) -> None: ...
    def close(self) -> None: ...
    @overload
    def addRect(self, arg0: RectF, arg1: "Direction") -> None: ...
    @overload
    def addRect(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: "Direction") -> None: ...
    @overload
    def addOval(self, arg0: RectF, arg1: "Direction") -> None: ...
    @overload
    def addOval(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: "Direction") -> None: ...
    def addCircle(self, arg0: float, arg1: float, arg2: float, arg3: "Direction") -> None: ...
    @overload
    def addArc(self, arg0: RectF, arg1: float, arg2: float) -> None: ...
    @overload
    def addArc(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None: ...
    @overload
    def addRoundRect(self, arg0: RectF, arg1: float, arg2: float, arg3: "Direction") -> None: ...
    @overload
    def addRoundRect(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: "Direction") -> None: ...
    @overload
    def addRoundRect(self, arg0: RectF, arg1: list[float], arg2: "Direction") -> None: ...
    @overload
    def addRoundRect(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: list[float], arg5: "Direction") -> None: ...
    @overload
    def addPath(self, arg0: "Path", arg1: float, arg2: float) -> None: ...
    @overload
    def addPath(self, arg0: "Path") -> None: ...
    @overload
    def addPath(self, arg0: "Path", arg1: Matrix) -> None: ...
    @overload
    def offset(self, arg0: float, arg1: float, arg2: "Path") -> None: ...
    @overload
    def offset(self, arg0: float, arg1: float) -> None: ...
    def setLastPoint(self, arg0: float, arg1: float) -> None: ...
    @overload
    def transform(self, arg0: Matrix, arg1: "Path") -> None: ...
    @overload
    def transform(self, arg0: Matrix) -> None: ...
    def approximate(self, arg0: float) -> list[float]: ...
    def getGenerationId(self) -> int: ...
    def isInterpolatable(self, arg0: "Path") -> bool: ...
    def interpolate(self, arg0: "Path", arg1: float, arg2: "Path") -> bool: ...

    class Direction:
        CW: ClassVar["Direction"]
        CCW: ClassVar["Direction"]
        @staticmethod
        def values() -> list["Direction"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Direction": ...

    class FillType:
        WINDING: ClassVar["FillType"]
        EVEN_ODD: ClassVar["FillType"]
        INVERSE_WINDING: ClassVar["FillType"]
        INVERSE_EVEN_ODD: ClassVar["FillType"]
        @staticmethod
        def values() -> list["FillType"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "FillType": ...

    class Op:
        DIFFERENCE: ClassVar["Op"]
        INTERSECT: ClassVar["Op"]
        UNION: ClassVar["Op"]
        XOR: ClassVar["Op"]
        REVERSE_DIFFERENCE: ClassVar["Op"]
        @staticmethod
        def values() -> list["Op"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "Op": ...
