from typing import Any, ClassVar, overload

class PathIterator:
    VERB_CLOSE: ClassVar[int]
    VERB_CONIC: ClassVar[int]
    VERB_CUBIC: ClassVar[int]
    VERB_DONE: ClassVar[int]
    VERB_LINE: ClassVar[int]
    VERB_MOVE: ClassVar[int]
    VERB_QUAD: ClassVar[int]
    @overload
    def next(self, arg0: list[float], arg1: int) -> int: ...
    @overload
    def next(self) -> "Segment": ...
    def hasNext(self) -> bool: ...
    def peek(self) -> int: ...

    class Segment:
        def getVerb(self) -> int: ...
        def getPoints(self) -> list[float]: ...
        def getConicWeight(self) -> float: ...
