from typing import Any, ClassVar, overload
from android.graphics.Insets import Insets
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Rect:
    CREATOR: ClassVar[Creator]
    bottom: int
    left: int
    right: int
    top: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def __init__(self, arg0: "Rect") -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def toShortString(self) -> str: ...
    def flattenToString(self) -> str: ...
    @staticmethod
    def unflattenFromString(arg0: str) -> "Rect": ...
    def isEmpty(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def centerX(self) -> int: ...
    def centerY(self) -> int: ...
    def exactCenterX(self) -> float: ...
    def exactCenterY(self) -> float: ...
    def setEmpty(self) -> None: ...
    @overload
    def set(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def set(self, arg0: "Rect") -> None: ...
    def offset(self, arg0: int, arg1: int) -> None: ...
    def offsetTo(self, arg0: int, arg1: int) -> None: ...
    @overload
    def inset(self, arg0: int, arg1: int) -> None: ...
    @overload
    def inset(self, arg0: Insets) -> None: ...
    @overload
    def inset(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def contains(self, arg0: int, arg1: int) -> bool: ...
    @overload
    def contains(self, arg0: int, arg1: int, arg2: int, arg3: int) -> bool: ...
    @overload
    def contains(self, arg0: "Rect") -> bool: ...
    @overload
    def intersect(self, arg0: int, arg1: int, arg2: int, arg3: int) -> bool: ...
    @overload
    def intersect(self, arg0: "Rect") -> bool: ...
    def setIntersect(self, arg0: "Rect", arg1: "Rect") -> bool: ...
    @overload
    def intersects(self, arg0: int, arg1: int, arg2: int, arg3: int) -> bool: ...
    @overload
    @staticmethod
    def intersects(arg0: "Rect", arg1: "Rect") -> bool: ...
    @overload
    def union(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def union(self, arg0: "Rect") -> None: ...
    @overload
    def union(self, arg0: int, arg1: int) -> None: ...
    def sort(self) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def readFromParcel(self, arg0: Parcel) -> None: ...
