from typing import Any, ClassVar, overload
from android.graphics.BitmapShader import BitmapShader
from android.graphics.Color import Color
from android.graphics.Shader import Shader

class RuntimeShader:
    def __init__(self, arg0: str) -> None: ...
    @overload
    def setColorUniform(self, arg0: str, arg1: int) -> None: ...
    @overload
    def setColorUniform(self, arg0: str, arg1: int) -> None: ...
    @overload
    def setColorUniform(self, arg0: str, arg1: Color) -> None: ...
    @overload
    def setFloatUniform(self, arg0: str, arg1: float) -> None: ...
    @overload
    def setFloatUniform(self, arg0: str, arg1: float, arg2: float) -> None: ...
    @overload
    def setFloatUniform(self, arg0: str, arg1: float, arg2: float, arg3: float) -> None: ...
    @overload
    def setFloatUniform(self, arg0: str, arg1: float, arg2: float, arg3: float, arg4: float) -> None: ...
    @overload
    def setFloatUniform(self, arg0: str, arg1: list[float]) -> None: ...
    @overload
    def setIntUniform(self, arg0: str, arg1: int) -> None: ...
    @overload
    def setIntUniform(self, arg0: str, arg1: int, arg2: int) -> None: ...
    @overload
    def setIntUniform(self, arg0: str, arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    def setIntUniform(self, arg0: str, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def setIntUniform(self, arg0: str, arg1: list[int]) -> None: ...
    def setInputShader(self, arg0: str, arg1: Shader) -> None: ...
    def setInputBuffer(self, arg0: str, arg1: BitmapShader) -> None: ...
