from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.os.Parcel import Parcel
from android.print.PrinterCapabilitiesInfo import PrinterCapabilitiesInfo
from android.print.PrinterId import PrinterId

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class PrinterInfo:
    CREATOR: ClassVar[Creator]
    STATUS_BUSY: ClassVar[int]
    STATUS_IDLE: ClassVar[int]
    STATUS_UNAVAILABLE: ClassVar[int]
    def getId(self) -> PrinterId: ...
    def getName(self) -> str: ...
    def getStatus(self) -> int: ...
    def getDescription(self) -> str: ...
    def getCapabilities(self) -> PrinterCapabilitiesInfo: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...

    class Builder:
        @overload
        def __init__(self, arg0: PrinterId, arg1: str, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: "PrinterInfo") -> None: ...
        def setStatus(self, arg0: int) -> "Builder": ...
        def setIconResourceId(self, arg0: int) -> "Builder": ...
        def setHasCustomPrinterIcon(self, arg0: bool) -> "Builder": ...
        def setName(self, arg0: str) -> "Builder": ...
        def setDescription(self, arg0: str) -> "Builder": ...
        def setInfoIntent(self, arg0: PendingIntent) -> "Builder": ...
        def setCapabilities(self, arg0: PrinterCapabilitiesInfo) -> "Builder": ...
        def build(self) -> "PrinterInfo": ...
