from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.print.PageRange import PageRange
from android.print.PrintAttributes import PrintAttributes
from android.print.PrintJobId import PrintJobId
from android.print.PrinterId import PrinterId

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class PrintJobInfo:
    CREATOR: ClassVar[Creator]
    STATE_BLOCKED: ClassVar[int]
    STATE_CANCELED: ClassVar[int]
    STATE_COMPLETED: ClassVar[int]
    STATE_CREATED: ClassVar[int]
    STATE_FAILED: ClassVar[int]
    STATE_QUEUED: ClassVar[int]
    STATE_STARTED: ClassVar[int]
    def getId(self) -> PrintJobId: ...
    def getLabel(self) -> str: ...
    def getPrinterId(self) -> PrinterId: ...
    def getState(self) -> int: ...
    def getCreationTime(self) -> int: ...
    def getCopies(self) -> int: ...
    def getPages(self) -> list[PageRange]: ...
    def getAttributes(self) -> PrintAttributes: ...
    def hasAdvancedOption(self, arg0: str) -> bool: ...
    def getAdvancedStringOption(self, arg0: str) -> str: ...
    def getAdvancedIntOption(self, arg0: str) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: "PrintJobInfo") -> None: ...
        def setCopies(self, arg0: int) -> None: ...
        def setAttributes(self, arg0: PrintAttributes) -> None: ...
        def setPages(self, arg0: list[PageRange]) -> None: ...
        @overload
        def putAdvancedOption(self, arg0: str, arg1: str) -> None: ...
        @overload
        def putAdvancedOption(self, arg0: str, arg1: int) -> None: ...
        def build(self) -> "PrintJobInfo": ...
