from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class PrintDocumentInfo:
    CONTENT_TYPE_DOCUMENT: ClassVar[int]
    CONTENT_TYPE_PHOTO: ClassVar[int]
    CONTENT_TYPE_UNKNOWN: ClassVar[int]
    CREATOR: ClassVar[Creator]
    PAGE_COUNT_UNKNOWN: ClassVar[int]
    def getName(self) -> str: ...
    def getPageCount(self) -> int: ...
    def getContentType(self) -> int: ...
    def getDataSize(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, arg0: str) -> None: ...
        def setPageCount(self, arg0: int) -> "Builder": ...
        def setContentType(self, arg0: int) -> "Builder": ...
        def build(self) -> "PrintDocumentInfo": ...
