from typing import Any, ClassVar, overload
from android.content.Context import Context
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class AsyncTaskLoader:
    def __init__(self, arg0: Context) -> None: ...
    def setUpdateThrottle(self, arg0: int) -> None: ...
    def onForceLoad(self) -> None: ...
    def onCancelLoad(self) -> bool: ...
    def onCanceled(self, arg0: Any) -> None: ...
    def loadInBackground(self) -> Any: ...
    def onLoadInBackground(self) -> Any: ...
    def cancelLoadInBackground(self) -> None: ...
    def isLoadInBackgroundCanceled(self) -> bool: ...
    def dump(self, arg0: str, arg1: FileDescriptor, arg2: PrintWriter, arg3: list[str]) -> None: ...
