from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AttributionSource:
    CREATOR: ClassVar[Creator]
    @staticmethod
    def myAttributionSource() -> "AttributionSource": ...
    def enforceCallingUid(self) -> None: ...
    def checkCallingUid(self) -> bool: ...
    def toString(self) -> str: ...
    def isTrusted(self, arg0: Context) -> bool: ...
    def getUid(self) -> int: ...
    def getPid(self) -> int: ...
    def getPackageName(self) -> str: ...
    def getAttributionTag(self) -> str: ...
    def getDeviceId(self) -> int: ...
    def getNext(self) -> "AttributionSource": ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, arg0: int) -> None: ...
        @overload
        def __init__(self, arg0: "AttributionSource") -> None: ...
        def setPid(self, arg0: int) -> "Builder": ...
        def setPackageName(self, arg0: str) -> "Builder": ...
        def setAttributionTag(self, arg0: str) -> "Builder": ...
        def setDeviceId(self, arg0: int) -> "Builder": ...
        def setNext(self, arg0: "AttributionSource") -> "Builder": ...
        def build(self) -> "AttributionSource": ...
