from typing import Any, ClassVar, overload
from android.content.ContentProvider import ContentProvider
from android.content.ContentProviderResult import ContentProviderResult
from android.content.ContentValues import ContentValues
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ContentProviderOperation:
    CREATOR: ClassVar[Creator]
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    @staticmethod
    def newInsert(arg0: Uri) -> "Builder": ...
    @staticmethod
    def newUpdate(arg0: Uri) -> "Builder": ...
    @staticmethod
    def newDelete(arg0: Uri) -> "Builder": ...
    @staticmethod
    def newAssertQuery(arg0: Uri) -> "Builder": ...
    @staticmethod
    def newCall(arg0: Uri, arg1: str, arg2: str) -> "Builder": ...
    def getUri(self) -> Uri: ...
    def isYieldAllowed(self) -> bool: ...
    def isExceptionAllowed(self) -> bool: ...
    def isInsert(self) -> bool: ...
    def isDelete(self) -> bool: ...
    def isUpdate(self) -> bool: ...
    def isAssertQuery(self) -> bool: ...
    def isCall(self) -> bool: ...
    def isWriteOperation(self) -> bool: ...
    def isReadOperation(self) -> bool: ...
    def apply(self, arg0: ContentProvider, arg1: list[ContentProviderResult], arg2: int) -> ContentProviderResult: ...
    def resolveValueBackReferences(self, arg0: list[ContentProviderResult], arg1: int) -> ContentValues: ...
    def resolveExtrasBackReferences(self, arg0: list[ContentProviderResult], arg1: int) -> Bundle: ...
    def resolveSelectionArgsBackReferences(self, arg0: list[ContentProviderResult], arg1: int) -> list[str]: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...

    class Builder:
        def build(self) -> "ContentProviderOperation": ...
        def withValues(self, arg0: ContentValues) -> "Builder": ...
        def withValue(self, arg0: str, arg1: Any) -> "Builder": ...
        def withValueBackReferences(self, arg0: ContentValues) -> "Builder": ...
        @overload
        def withValueBackReference(self, arg0: str, arg1: int) -> "Builder": ...
        @overload
        def withValueBackReference(self, arg0: str, arg1: int, arg2: str) -> "Builder": ...
        def withExtras(self, arg0: Bundle) -> "Builder": ...
        def withExtra(self, arg0: str, arg1: Any) -> "Builder": ...
        @overload
        def withExtraBackReference(self, arg0: str, arg1: int) -> "Builder": ...
        @overload
        def withExtraBackReference(self, arg0: str, arg1: int, arg2: str) -> "Builder": ...
        def withSelection(self, arg0: str, arg1: list[str]) -> "Builder": ...
        @overload
        def withSelectionBackReference(self, arg0: int, arg1: int) -> "Builder": ...
        @overload
        def withSelectionBackReference(self, arg0: int, arg1: int, arg2: str) -> "Builder": ...
        def withExpectedCount(self, arg0: int) -> "Builder": ...
        def withYieldAllowed(self, arg0: bool) -> "Builder": ...
        def withExceptionAllowed(self, arg0: bool) -> "Builder": ...
