from typing import Any, ClassVar, overload
from android.content.AttributionSource import AttributionSource
from android.content.ContentProviderResult import ContentProviderResult
from android.content.ContentValues import ContentValues
from android.content.Context import Context
from android.content.pm.PathPermission import PathPermission
from android.content.pm.ProviderInfo import ProviderInfo
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.content.res.Configuration import Configuration
from android.database.Cursor import Cursor
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.CancellationSignal import CancellationSignal
from android.os.ParcelFileDescriptor import ParcelFileDescriptor
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class ContentProvider:
    def __init__(self) -> None: ...
    def getContext(self) -> Context: ...
    def requireContext(self) -> Context: ...
    def getCallingPackage(self) -> str: ...
    def getCallingAttributionSource(self) -> AttributionSource: ...
    def getCallingAttributionTag(self) -> str: ...
    def getCallingPackageUnchecked(self) -> str: ...
    def onCallingPackageChanged(self) -> None: ...
    def clearCallingIdentity(self) -> "CallingIdentity": ...
    def restoreCallingIdentity(self, arg0: "CallingIdentity") -> None: ...
    def setReadPermission(self, arg0: str) -> None: ...
    def getReadPermission(self) -> str: ...
    def setWritePermission(self, arg0: str) -> None: ...
    def getWritePermission(self) -> str: ...
    def setPathPermissions(self, arg0: list[PathPermission]) -> None: ...
    def getPathPermissions(self) -> list[PathPermission]: ...
    def onCreate(self) -> bool: ...
    def onConfigurationChanged(self, arg0: Configuration) -> None: ...
    def onLowMemory(self) -> None: ...
    def onTrimMemory(self, arg0: int) -> None: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str) -> Cursor: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str, arg5: CancellationSignal) -> Cursor: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: Bundle, arg3: CancellationSignal) -> Cursor: ...
    def getType(self, arg0: Uri) -> str: ...
    def getTypeAnonymous(self, arg0: Uri) -> str: ...
    def canonicalize(self, arg0: Uri) -> Uri: ...
    def uncanonicalize(self, arg0: Uri) -> Uri: ...
    def refresh(self, arg0: Uri, arg1: Bundle, arg2: CancellationSignal) -> bool: ...
    @overload
    def insert(self, arg0: Uri, arg1: ContentValues) -> Uri: ...
    @overload
    def insert(self, arg0: Uri, arg1: ContentValues, arg2: Bundle) -> Uri: ...
    def bulkInsert(self, arg0: Uri, arg1: list[ContentValues]) -> int: ...
    @overload
    def delete(self, arg0: Uri, arg1: str, arg2: list[str]) -> int: ...
    @overload
    def delete(self, arg0: Uri, arg1: Bundle) -> int: ...
    @overload
    def update(self, arg0: Uri, arg1: ContentValues, arg2: str, arg3: list[str]) -> int: ...
    @overload
    def update(self, arg0: Uri, arg1: ContentValues, arg2: Bundle) -> int: ...
    @overload
    def openFile(self, arg0: Uri, arg1: str) -> ParcelFileDescriptor: ...
    @overload
    def openFile(self, arg0: Uri, arg1: str, arg2: CancellationSignal) -> ParcelFileDescriptor: ...
    @overload
    def openAssetFile(self, arg0: Uri, arg1: str) -> AssetFileDescriptor: ...
    @overload
    def openAssetFile(self, arg0: Uri, arg1: str, arg2: CancellationSignal) -> AssetFileDescriptor: ...
    def openFileHelper(self, arg0: Uri, arg1: str) -> ParcelFileDescriptor: ...
    def getStreamTypes(self, arg0: Uri, arg1: str) -> list[str]: ...
    @overload
    def openTypedAssetFile(self, arg0: Uri, arg1: str, arg2: Bundle) -> AssetFileDescriptor: ...
    @overload
    def openTypedAssetFile(self, arg0: Uri, arg1: str, arg2: Bundle, arg3: CancellationSignal) -> AssetFileDescriptor: ...
    def openPipeHelper(self, arg0: Uri, arg1: str, arg2: Bundle, arg3: Any, arg4: "PipeDataWriter") -> ParcelFileDescriptor: ...
    def isTemporary(self) -> bool: ...
    def attachInfo(self, arg0: Context, arg1: ProviderInfo) -> None: ...
    @overload
    def applyBatch(self, arg0: str, arg1: list) -> list[ContentProviderResult]: ...
    @overload
    def applyBatch(self, arg0: list) -> list[ContentProviderResult]: ...
    @overload
    def call(self, arg0: str, arg1: str, arg2: str, arg3: Bundle) -> Bundle: ...
    @overload
    def call(self, arg0: str, arg1: str, arg2: Bundle) -> Bundle: ...
    def shutdown(self) -> None: ...
    def dump(self, arg0: FileDescriptor, arg1: PrintWriter, arg2: list[str]) -> None: ...

    class CallingIdentity:
        ...

    class PipeDataWriter:
        def writeDataToPipe(self, arg0: ParcelFileDescriptor, arg1: Uri, arg2: str, arg3: Bundle, arg4: Any) -> None: ...
