from typing import Any, ClassVar, overload
from android.accounts.Account import Account
from android.content.ContentProvider import ContentProvider
from android.content.ContentProviderClient import ContentProviderClient
from android.content.ContentProviderResult import ContentProviderResult
from android.content.ContentValues import ContentValues
from android.content.Context import Context
from android.content.SyncAdapterType import SyncAdapterType
from android.content.SyncInfo import SyncInfo
from android.content.SyncRequest import SyncRequest
from android.content.SyncStatusObserver import SyncStatusObserver
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.database.ContentObserver import ContentObserver
from android.database.Cursor import Cursor
from android.graphics.Bitmap import Bitmap
from android.graphics.drawable.Icon import Icon
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.CancellationSignal import CancellationSignal
from android.os.ParcelFileDescriptor import ParcelFileDescriptor
from android.util.Size import Size
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream

class ContentResolver:
    ANY_CURSOR_ITEM_TYPE: ClassVar[str]
    CURSOR_DIR_BASE_TYPE: ClassVar[str]
    CURSOR_ITEM_BASE_TYPE: ClassVar[str]
    EXTRA_HONORED_ARGS: ClassVar[str]
    EXTRA_REFRESH_SUPPORTED: ClassVar[str]
    EXTRA_SIZE: ClassVar[str]
    EXTRA_TOTAL_COUNT: ClassVar[str]
    NOTIFY_DELETE: ClassVar[int]
    NOTIFY_INSERT: ClassVar[int]
    NOTIFY_SKIP_NOTIFY_FOR_DESCENDANTS: ClassVar[int]
    NOTIFY_SYNC_TO_NETWORK: ClassVar[int]
    NOTIFY_UPDATE: ClassVar[int]
    QUERY_ARG_GROUP_COLUMNS: ClassVar[str]
    QUERY_ARG_LIMIT: ClassVar[str]
    QUERY_ARG_OFFSET: ClassVar[str]
    QUERY_ARG_SORT_COLLATION: ClassVar[str]
    QUERY_ARG_SORT_COLUMNS: ClassVar[str]
    QUERY_ARG_SORT_DIRECTION: ClassVar[str]
    QUERY_ARG_SORT_LOCALE: ClassVar[str]
    QUERY_ARG_SQL_GROUP_BY: ClassVar[str]
    QUERY_ARG_SQL_HAVING: ClassVar[str]
    QUERY_ARG_SQL_LIMIT: ClassVar[str]
    QUERY_ARG_SQL_SELECTION: ClassVar[str]
    QUERY_ARG_SQL_SELECTION_ARGS: ClassVar[str]
    QUERY_ARG_SQL_SORT_ORDER: ClassVar[str]
    QUERY_SORT_DIRECTION_ASCENDING: ClassVar[int]
    QUERY_SORT_DIRECTION_DESCENDING: ClassVar[int]
    SCHEME_ANDROID_RESOURCE: ClassVar[str]
    SCHEME_CONTENT: ClassVar[str]
    SCHEME_FILE: ClassVar[str]
    SYNC_EXTRAS_ACCOUNT: ClassVar[str]
    SYNC_EXTRAS_DISCARD_LOCAL_DELETIONS: ClassVar[str]
    SYNC_EXTRAS_DO_NOT_RETRY: ClassVar[str]
    SYNC_EXTRAS_EXPEDITED: ClassVar[str]
    SYNC_EXTRAS_FORCE: ClassVar[str]
    SYNC_EXTRAS_IGNORE_BACKOFF: ClassVar[str]
    SYNC_EXTRAS_IGNORE_SETTINGS: ClassVar[str]
    SYNC_EXTRAS_INITIALIZE: ClassVar[str]
    SYNC_EXTRAS_MANUAL: ClassVar[str]
    SYNC_EXTRAS_OVERRIDE_TOO_MANY_DELETIONS: ClassVar[str]
    SYNC_EXTRAS_REQUIRE_CHARGING: ClassVar[str]
    SYNC_EXTRAS_SCHEDULE_AS_EXPEDITED_JOB: ClassVar[str]
    SYNC_EXTRAS_UPLOAD: ClassVar[str]
    SYNC_OBSERVER_TYPE_ACTIVE: ClassVar[int]
    SYNC_OBSERVER_TYPE_PENDING: ClassVar[int]
    SYNC_OBSERVER_TYPE_SETTINGS: ClassVar[int]
    def __init__(self, arg0: Context) -> None: ...
    @overload
    @staticmethod
    def wrap(arg0: ContentProvider) -> "ContentResolver": ...
    @overload
    @staticmethod
    def wrap(arg0: ContentProviderClient) -> "ContentResolver": ...
    def getType(self, arg0: Uri) -> str: ...
    def getStreamTypes(self, arg0: Uri, arg1: str) -> list[str]: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str) -> Cursor: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str, arg5: CancellationSignal) -> Cursor: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: Bundle, arg3: CancellationSignal) -> Cursor: ...
    def canonicalize(self, arg0: Uri) -> Uri: ...
    def uncanonicalize(self, arg0: Uri) -> Uri: ...
    def refresh(self, arg0: Uri, arg1: Bundle, arg2: CancellationSignal) -> bool: ...
    def openInputStream(self, arg0: Uri) -> InputStream: ...
    @overload
    def openOutputStream(self, arg0: Uri) -> OutputStream: ...
    @overload
    def openOutputStream(self, arg0: Uri, arg1: str) -> OutputStream: ...
    def openFile(self, arg0: Uri, arg1: str, arg2: CancellationSignal) -> ParcelFileDescriptor: ...
    @overload
    def openFileDescriptor(self, arg0: Uri, arg1: str) -> ParcelFileDescriptor: ...
    @overload
    def openFileDescriptor(self, arg0: Uri, arg1: str, arg2: CancellationSignal) -> ParcelFileDescriptor: ...
    def openAssetFile(self, arg0: Uri, arg1: str, arg2: CancellationSignal) -> AssetFileDescriptor: ...
    @overload
    def openAssetFileDescriptor(self, arg0: Uri, arg1: str) -> AssetFileDescriptor: ...
    @overload
    def openAssetFileDescriptor(self, arg0: Uri, arg1: str, arg2: CancellationSignal) -> AssetFileDescriptor: ...
    def openTypedAssetFile(self, arg0: Uri, arg1: str, arg2: Bundle, arg3: CancellationSignal) -> AssetFileDescriptor: ...
    @overload
    def openTypedAssetFileDescriptor(self, arg0: Uri, arg1: str, arg2: Bundle) -> AssetFileDescriptor: ...
    @overload
    def openTypedAssetFileDescriptor(self, arg0: Uri, arg1: str, arg2: Bundle, arg3: CancellationSignal) -> AssetFileDescriptor: ...
    @overload
    def insert(self, arg0: Uri, arg1: ContentValues) -> Uri: ...
    @overload
    def insert(self, arg0: Uri, arg1: ContentValues, arg2: Bundle) -> Uri: ...
    def applyBatch(self, arg0: str, arg1: list) -> list[ContentProviderResult]: ...
    def bulkInsert(self, arg0: Uri, arg1: list[ContentValues]) -> int: ...
    @overload
    def delete(self, arg0: Uri, arg1: str, arg2: list[str]) -> int: ...
    @overload
    def delete(self, arg0: Uri, arg1: Bundle) -> int: ...
    @overload
    def update(self, arg0: Uri, arg1: ContentValues, arg2: str, arg3: list[str]) -> int: ...
    @overload
    def update(self, arg0: Uri, arg1: ContentValues, arg2: Bundle) -> int: ...
    @overload
    def call(self, arg0: Uri, arg1: str, arg2: str, arg3: Bundle) -> Bundle: ...
    @overload
    def call(self, arg0: str, arg1: str, arg2: str, arg3: Bundle) -> Bundle: ...
    @overload
    def acquireContentProviderClient(self, arg0: Uri) -> ContentProviderClient: ...
    @overload
    def acquireContentProviderClient(self, arg0: str) -> ContentProviderClient: ...
    @overload
    def acquireUnstableContentProviderClient(self, arg0: Uri) -> ContentProviderClient: ...
    @overload
    def acquireUnstableContentProviderClient(self, arg0: str) -> ContentProviderClient: ...
    def registerContentObserver(self, arg0: Uri, arg1: bool, arg2: ContentObserver) -> None: ...
    def unregisterContentObserver(self, arg0: ContentObserver) -> None: ...
    @overload
    def notifyChange(self, arg0: Uri, arg1: ContentObserver) -> None: ...
    @overload
    def notifyChange(self, arg0: Uri, arg1: ContentObserver, arg2: bool) -> None: ...
    @overload
    def notifyChange(self, arg0: Uri, arg1: ContentObserver, arg2: int) -> None: ...
    @overload
    def notifyChange(self, arg0: list, arg1: ContentObserver, arg2: int) -> None: ...
    def takePersistableUriPermission(self, arg0: Uri, arg1: int) -> None: ...
    def releasePersistableUriPermission(self, arg0: Uri, arg1: int) -> None: ...
    def getPersistedUriPermissions(self) -> list: ...
    def getOutgoingPersistedUriPermissions(self) -> list: ...
    def startSync(self, arg0: Uri, arg1: Bundle) -> None: ...
    @overload
    @staticmethod
    def requestSync(arg0: Account, arg1: str, arg2: Bundle) -> None: ...
    @overload
    @staticmethod
    def requestSync(arg0: SyncRequest) -> None: ...
    @staticmethod
    def validateSyncExtrasBundle(arg0: Bundle) -> None: ...
    @overload
    def cancelSync(self, arg0: Uri) -> None: ...
    @overload
    @staticmethod
    def cancelSync(arg0: Account, arg1: str) -> None: ...
    @overload
    @staticmethod
    def cancelSync(arg0: SyncRequest) -> None: ...
    @staticmethod
    def getSyncAdapterTypes() -> list[SyncAdapterType]: ...
    @staticmethod
    def getSyncAutomatically(arg0: Account, arg1: str) -> bool: ...
    @staticmethod
    def setSyncAutomatically(arg0: Account, arg1: str, arg2: bool) -> None: ...
    @staticmethod
    def addPeriodicSync(arg0: Account, arg1: str, arg2: Bundle, arg3: int) -> None: ...
    @staticmethod
    def removePeriodicSync(arg0: Account, arg1: str, arg2: Bundle) -> None: ...
    @staticmethod
    def getPeriodicSyncs(arg0: Account, arg1: str) -> list: ...
    @staticmethod
    def getIsSyncable(arg0: Account, arg1: str) -> int: ...
    @staticmethod
    def setIsSyncable(arg0: Account, arg1: str, arg2: int) -> None: ...
    @staticmethod
    def getMasterSyncAutomatically() -> bool: ...
    @staticmethod
    def setMasterSyncAutomatically(arg0: bool) -> None: ...
    @staticmethod
    def isSyncActive(arg0: Account, arg1: str) -> bool: ...
    @staticmethod
    def getCurrentSync() -> SyncInfo: ...
    @staticmethod
    def getCurrentSyncs() -> list: ...
    @staticmethod
    def isSyncPending(arg0: Account, arg1: str) -> bool: ...
    @staticmethod
    def addStatusChangeListener(arg0: int, arg1: SyncStatusObserver) -> Any: ...
    @staticmethod
    def removeStatusChangeListener(arg0: Any) -> None: ...
    def getTypeInfo(self, arg0: str) -> "MimeTypeInfo": ...
    def loadThumbnail(self, arg0: Uri, arg1: Size, arg2: CancellationSignal) -> Bitmap: ...

    class MimeTypeInfo:
        def getIcon(self) -> Icon: ...
        def getLabel(self) -> str: ...
        def getContentDescription(self) -> str: ...
