from typing import Any, ClassVar, overload
from android.content.ContentValues import ContentValues
from android.database.Cursor import Cursor
from android.os.Handler import Handler

class ContentQueryMap:
    def __init__(self, arg0: Cursor, arg1: str, arg2: bool, arg3: Handler) -> None: ...
    def setKeepUpdated(self, arg0: bool) -> None: ...
    def getValues(self, arg0: str) -> ContentValues: ...
    def requery(self) -> None: ...
    def getRows(self) -> dict: ...
    def close(self) -> None: ...
    def finalize(self) -> None: ...
