from typing import Any, ClassVar, overload
from android.content.AttributionSource import AttributionSource
from android.content.BroadcastReceiver import BroadcastReceiver
from android.content.ComponentCallbacks import ComponentCallbacks
from android.content.ComponentName import ComponentName
from android.content.ContentResolver import ContentResolver
from android.content.Context import Context
from android.content.ContextParams import ContextParams
from android.content.Intent import Intent
from android.content.IntentFilter import IntentFilter
from android.content.IntentSender import IntentSender
from android.content.ServiceConnection import ServiceConnection
from android.content.SharedPreferences import SharedPreferences
from android.content.pm.ApplicationInfo import ApplicationInfo
from android.content.pm.PackageManager import PackageManager
from android.content.res.AssetManager import AssetManager
from android.content.res.Configuration import Configuration
from android.content.res.Resources import Resources
from android.database.DatabaseErrorHandler import DatabaseErrorHandler
from android.database.sqlite.SQLiteDatabase import SQLiteDatabase
from android.graphics.Bitmap import Bitmap
from android.graphics.drawable.Drawable import Drawable
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.os.Looper import Looper
from android.os.UserHandle import UserHandle
from android.view.Display import Display
from java.io.File import File
from java.io.FileInputStream import FileInputStream
from java.io.FileOutputStream import FileOutputStream
from java.io.InputStream import InputStream
from java.lang.ClassLoader import ClassLoader
from java.util.concurrent.Executor import Executor
from java.util.function.IntConsumer import IntConsumer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Theme:
    """Forward declaration for ``android.content.res.Resources.Theme``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.res.Resources.Theme')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/res/Resources/Theme
    """
    ...
class CursorFactory:
    """Forward declaration for ``android.database.sqlite.SQLiteDatabase.CursorFactory``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.database.sqlite.SQLiteDatabase.CursorFactory')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase/CursorFactory
    """
    ...
class BindServiceFlags:
    """Forward declaration for ``android.content.Context.BindServiceFlags``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.Context.BindServiceFlags')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/Context/BindServiceFlags
    """
    ...

class ContextWrapper:
    def __init__(self, arg0: Context) -> None: ...
    def attachBaseContext(self, arg0: Context) -> None: ...
    def getBaseContext(self) -> Context: ...
    def getAssets(self) -> AssetManager: ...
    def getResources(self) -> Resources: ...
    def getPackageManager(self) -> PackageManager: ...
    def getContentResolver(self) -> ContentResolver: ...
    def getMainLooper(self) -> Looper: ...
    def getMainExecutor(self) -> Executor: ...
    def getApplicationContext(self) -> Context: ...
    def setTheme(self, arg0: int) -> None: ...
    def getTheme(self) -> Theme: ...
    def getClassLoader(self) -> ClassLoader: ...
    def getPackageName(self) -> str: ...
    def getOpPackageName(self) -> str: ...
    def getAttributionTag(self) -> str: ...
    def getParams(self) -> ContextParams: ...
    def getApplicationInfo(self) -> ApplicationInfo: ...
    def getPackageResourcePath(self) -> str: ...
    def getPackageCodePath(self) -> str: ...
    def getSharedPreferences(self, arg0: str, arg1: int) -> SharedPreferences: ...
    def moveSharedPreferencesFrom(self, arg0: Context, arg1: str) -> bool: ...
    def deleteSharedPreferences(self, arg0: str) -> bool: ...
    def openFileInput(self, arg0: str) -> FileInputStream: ...
    def openFileOutput(self, arg0: str, arg1: int) -> FileOutputStream: ...
    def deleteFile(self, arg0: str) -> bool: ...
    def getFileStreamPath(self, arg0: str) -> File: ...
    def fileList(self) -> list[str]: ...
    def getDataDir(self) -> File: ...
    def getFilesDir(self) -> File: ...
    def getNoBackupFilesDir(self) -> File: ...
    def getExternalFilesDir(self, arg0: str) -> File: ...
    def getExternalFilesDirs(self, arg0: str) -> list[File]: ...
    def getObbDir(self) -> File: ...
    def getObbDirs(self) -> list[File]: ...
    def getCacheDir(self) -> File: ...
    def getCodeCacheDir(self) -> File: ...
    def getExternalCacheDir(self) -> File: ...
    def getExternalCacheDirs(self) -> list[File]: ...
    def getExternalMediaDirs(self) -> list[File]: ...
    def getDir(self, arg0: str, arg1: int) -> File: ...
    @overload
    def openOrCreateDatabase(self, arg0: str, arg1: int, arg2: CursorFactory) -> SQLiteDatabase: ...
    @overload
    def openOrCreateDatabase(self, arg0: str, arg1: int, arg2: CursorFactory, arg3: DatabaseErrorHandler) -> SQLiteDatabase: ...
    def moveDatabaseFrom(self, arg0: Context, arg1: str) -> bool: ...
    def deleteDatabase(self, arg0: str) -> bool: ...
    def getDatabasePath(self, arg0: str) -> File: ...
    def databaseList(self) -> list[str]: ...
    def getWallpaper(self) -> Drawable: ...
    def peekWallpaper(self) -> Drawable: ...
    def getWallpaperDesiredMinimumWidth(self) -> int: ...
    def getWallpaperDesiredMinimumHeight(self) -> int: ...
    @overload
    def setWallpaper(self, arg0: Bitmap) -> None: ...
    @overload
    def setWallpaper(self, arg0: InputStream) -> None: ...
    def clearWallpaper(self) -> None: ...
    @overload
    def startActivity(self, arg0: Intent) -> None: ...
    @overload
    def startActivity(self, arg0: Intent, arg1: Bundle) -> None: ...
    @overload
    def startActivities(self, arg0: list[Intent]) -> None: ...
    @overload
    def startActivities(self, arg0: list[Intent], arg1: Bundle) -> None: ...
    @overload
    def startIntentSender(self, arg0: IntentSender, arg1: Intent, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def startIntentSender(self, arg0: IntentSender, arg1: Intent, arg2: int, arg3: int, arg4: int, arg5: Bundle) -> None: ...
    @overload
    def sendBroadcast(self, arg0: Intent) -> None: ...
    @overload
    def sendBroadcast(self, arg0: Intent, arg1: str) -> None: ...
    @overload
    def sendBroadcast(self, arg0: Intent, arg1: str, arg2: Bundle) -> None: ...
    @overload
    def sendOrderedBroadcast(self, arg0: Intent, arg1: str) -> None: ...
    @overload
    def sendOrderedBroadcast(self, arg0: Intent, arg1: str, arg2: Bundle) -> None: ...
    @overload
    def sendOrderedBroadcast(self, arg0: Intent, arg1: str, arg2: BroadcastReceiver, arg3: Handler, arg4: int, arg5: str, arg6: Bundle) -> None: ...
    @overload
    def sendOrderedBroadcast(self, arg0: Intent, arg1: str, arg2: Bundle, arg3: BroadcastReceiver, arg4: Handler, arg5: int, arg6: str, arg7: Bundle) -> None: ...
    @overload
    def sendOrderedBroadcast(self, arg0: Intent, arg1: str, arg2: str, arg3: BroadcastReceiver, arg4: Handler, arg5: int, arg6: str, arg7: Bundle) -> None: ...
    @overload
    def sendOrderedBroadcast(self, arg0: Intent, arg1: int, arg2: str, arg3: str, arg4: BroadcastReceiver, arg5: Handler, arg6: str, arg7: Bundle, arg8: Bundle) -> None: ...
    @overload
    def sendBroadcastAsUser(self, arg0: Intent, arg1: UserHandle) -> None: ...
    @overload
    def sendBroadcastAsUser(self, arg0: Intent, arg1: UserHandle, arg2: str) -> None: ...
    def sendOrderedBroadcastAsUser(self, arg0: Intent, arg1: UserHandle, arg2: str, arg3: BroadcastReceiver, arg4: Handler, arg5: int, arg6: str, arg7: Bundle) -> None: ...
    @overload
    def sendStickyBroadcast(self, arg0: Intent) -> None: ...
    @overload
    def sendStickyBroadcast(self, arg0: Intent, arg1: Bundle) -> None: ...
    def sendStickyOrderedBroadcast(self, arg0: Intent, arg1: BroadcastReceiver, arg2: Handler, arg3: int, arg4: str, arg5: Bundle) -> None: ...
    def removeStickyBroadcast(self, arg0: Intent) -> None: ...
    def sendStickyBroadcastAsUser(self, arg0: Intent, arg1: UserHandle) -> None: ...
    def sendStickyOrderedBroadcastAsUser(self, arg0: Intent, arg1: UserHandle, arg2: BroadcastReceiver, arg3: Handler, arg4: int, arg5: str, arg6: Bundle) -> None: ...
    def removeStickyBroadcastAsUser(self, arg0: Intent, arg1: UserHandle) -> None: ...
    @overload
    def registerReceiver(self, arg0: BroadcastReceiver, arg1: IntentFilter) -> Intent: ...
    @overload
    def registerReceiver(self, arg0: BroadcastReceiver, arg1: IntentFilter, arg2: int) -> Intent: ...
    @overload
    def registerReceiver(self, arg0: BroadcastReceiver, arg1: IntentFilter, arg2: str, arg3: Handler) -> Intent: ...
    @overload
    def registerReceiver(self, arg0: BroadcastReceiver, arg1: IntentFilter, arg2: str, arg3: Handler, arg4: int) -> Intent: ...
    def unregisterReceiver(self, arg0: BroadcastReceiver) -> None: ...
    def startService(self, arg0: Intent) -> ComponentName: ...
    def startForegroundService(self, arg0: Intent) -> ComponentName: ...
    def stopService(self, arg0: Intent) -> bool: ...
    @overload
    def bindService(self, arg0: Intent, arg1: ServiceConnection, arg2: int) -> bool: ...
    @overload
    def bindService(self, arg0: Intent, arg1: ServiceConnection, arg2: BindServiceFlags) -> bool: ...
    @overload
    def bindService(self, arg0: Intent, arg1: int, arg2: Executor, arg3: ServiceConnection) -> bool: ...
    @overload
    def bindService(self, arg0: Intent, arg1: BindServiceFlags, arg2: Executor, arg3: ServiceConnection) -> bool: ...
    def bindIsolatedService(self, arg0: Intent, arg1: int, arg2: str, arg3: Executor, arg4: ServiceConnection) -> bool: ...
    @overload
    def bindServiceAsUser(self, arg0: Intent, arg1: ServiceConnection, arg2: int, arg3: UserHandle) -> bool: ...
    @overload
    def bindServiceAsUser(self, arg0: Intent, arg1: ServiceConnection, arg2: BindServiceFlags, arg3: UserHandle) -> bool: ...
    def updateServiceGroup(self, arg0: ServiceConnection, arg1: int, arg2: int) -> None: ...
    def unbindService(self, arg0: ServiceConnection) -> None: ...
    def startInstrumentation(self, arg0: ComponentName, arg1: str, arg2: Bundle) -> bool: ...
    def getSystemService(self, arg0: str) -> Any: ...
    def getSystemServiceName(self, arg0: type) -> str: ...
    def checkPermission(self, arg0: str, arg1: int, arg2: int) -> int: ...
    def checkCallingPermission(self, arg0: str) -> int: ...
    def checkCallingOrSelfPermission(self, arg0: str) -> int: ...
    def checkSelfPermission(self, arg0: str) -> int: ...
    def enforcePermission(self, arg0: str, arg1: int, arg2: int, arg3: str) -> None: ...
    def enforceCallingPermission(self, arg0: str, arg1: str) -> None: ...
    def enforceCallingOrSelfPermission(self, arg0: str, arg1: str) -> None: ...
    def grantUriPermission(self, arg0: str, arg1: Uri, arg2: int) -> None: ...
    @overload
    def revokeUriPermission(self, arg0: Uri, arg1: int) -> None: ...
    @overload
    def revokeUriPermission(self, arg0: str, arg1: Uri, arg2: int) -> None: ...
    @overload
    def checkUriPermission(self, arg0: Uri, arg1: int, arg2: int, arg3: int) -> int: ...
    @overload
    def checkUriPermission(self, arg0: Uri, arg1: str, arg2: str, arg3: int, arg4: int, arg5: int) -> int: ...
    def checkContentUriPermissionFull(self, arg0: Uri, arg1: int, arg2: int, arg3: int) -> int: ...
    def checkUriPermissions(self, arg0: list, arg1: int, arg2: int, arg3: int) -> list[int]: ...
    def checkCallingUriPermission(self, arg0: Uri, arg1: int) -> int: ...
    def checkCallingUriPermissions(self, arg0: list, arg1: int) -> list[int]: ...
    def checkCallingOrSelfUriPermission(self, arg0: Uri, arg1: int) -> int: ...
    def checkCallingOrSelfUriPermissions(self, arg0: list, arg1: int) -> list[int]: ...
    @overload
    def enforceUriPermission(self, arg0: Uri, arg1: int, arg2: int, arg3: int, arg4: str) -> None: ...
    @overload
    def enforceUriPermission(self, arg0: Uri, arg1: str, arg2: str, arg3: int, arg4: int, arg5: int, arg6: str) -> None: ...
    def enforceCallingUriPermission(self, arg0: Uri, arg1: int, arg2: str) -> None: ...
    def enforceCallingOrSelfUriPermission(self, arg0: Uri, arg1: int, arg2: str) -> None: ...
    def revokeSelfPermissionsOnKill(self, arg0: list) -> None: ...
    def createPackageContext(self, arg0: str, arg1: int) -> Context: ...
    def createContextForSplit(self, arg0: str) -> Context: ...
    def createConfigurationContext(self, arg0: Configuration) -> Context: ...
    def createDisplayContext(self, arg0: Display) -> Context: ...
    def createDeviceContext(self, arg0: int) -> Context: ...
    @overload
    def createWindowContext(self, arg0: int, arg1: Bundle) -> Context: ...
    @overload
    def createWindowContext(self, arg0: Display, arg1: int, arg2: Bundle) -> Context: ...
    def createContext(self, arg0: ContextParams) -> Context: ...
    def createAttributionContext(self, arg0: str) -> Context: ...
    def getAttributionSource(self) -> AttributionSource: ...
    def isRestricted(self) -> bool: ...
    def getDisplay(self) -> Display: ...
    def getDeviceId(self) -> int: ...
    def registerDeviceIdChangeListener(self, arg0: Executor, arg1: IntConsumer) -> None: ...
    def unregisterDeviceIdChangeListener(self, arg0: IntConsumer) -> None: ...
    def createDeviceProtectedStorageContext(self) -> Context: ...
    def isDeviceProtectedStorage(self) -> bool: ...
    def isUiContext(self) -> bool: ...
    def registerComponentCallbacks(self, arg0: ComponentCallbacks) -> None: ...
    def unregisterComponentCallbacks(self, arg0: ComponentCallbacks) -> None: ...
