from typing import Any, ClassVar, overload
from android.content.ContentProvider import ContentProvider
from android.content.ContentProviderResult import ContentProviderResult
from android.content.ContentValues import ContentValues
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.database.Cursor import Cursor
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.CancellationSignal import CancellationSignal
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class ContentProviderClient:
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str) -> Cursor: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str, arg5: CancellationSignal) -> Cursor: ...
    @overload
    def query(self, arg0: Uri, arg1: list[str], arg2: Bundle, arg3: CancellationSignal) -> Cursor: ...
    def getType(self, arg0: Uri) -> str: ...
    def getStreamTypes(self, arg0: Uri, arg1: str) -> list[str]: ...
    def canonicalize(self, arg0: Uri) -> Uri: ...
    def uncanonicalize(self, arg0: Uri) -> Uri: ...
    def refresh(self, arg0: Uri, arg1: Bundle, arg2: CancellationSignal) -> bool: ...
    @overload
    def insert(self, arg0: Uri, arg1: ContentValues) -> Uri: ...
    @overload
    def insert(self, arg0: Uri, arg1: ContentValues, arg2: Bundle) -> Uri: ...
    def bulkInsert(self, arg0: Uri, arg1: list[ContentValues]) -> int: ...
    @overload
    def delete(self, arg0: Uri, arg1: str, arg2: list[str]) -> int: ...
    @overload
    def delete(self, arg0: Uri, arg1: Bundle) -> int: ...
    @overload
    def update(self, arg0: Uri, arg1: ContentValues, arg2: str, arg3: list[str]) -> int: ...
    @overload
    def update(self, arg0: Uri, arg1: ContentValues, arg2: Bundle) -> int: ...
    @overload
    def openFile(self, arg0: Uri, arg1: str) -> ParcelFileDescriptor: ...
    @overload
    def openFile(self, arg0: Uri, arg1: str, arg2: CancellationSignal) -> ParcelFileDescriptor: ...
    @overload
    def openAssetFile(self, arg0: Uri, arg1: str) -> AssetFileDescriptor: ...
    @overload
    def openAssetFile(self, arg0: Uri, arg1: str, arg2: CancellationSignal) -> AssetFileDescriptor: ...
    @overload
    def openTypedAssetFileDescriptor(self, arg0: Uri, arg1: str, arg2: Bundle) -> AssetFileDescriptor: ...
    @overload
    def openTypedAssetFileDescriptor(self, arg0: Uri, arg1: str, arg2: Bundle, arg3: CancellationSignal) -> AssetFileDescriptor: ...
    def openTypedAssetFile(self, arg0: Uri, arg1: str, arg2: Bundle, arg3: CancellationSignal) -> AssetFileDescriptor: ...
    @overload
    def applyBatch(self, arg0: list) -> list[ContentProviderResult]: ...
    @overload
    def applyBatch(self, arg0: str, arg1: list) -> list[ContentProviderResult]: ...
    @overload
    def call(self, arg0: str, arg1: str, arg2: Bundle) -> Bundle: ...
    @overload
    def call(self, arg0: str, arg1: str, arg2: str, arg3: Bundle) -> Bundle: ...
    def close(self) -> None: ...
    def release(self) -> bool: ...
    def finalize(self) -> None: ...
    def getLocalContentProvider(self) -> ContentProvider: ...
