from typing import Any, ClassVar, overload
from android.content.ContentValues import ContentValues
from android.net.Uri import Uri

class Entity:
    def __init__(self, arg0: ContentValues) -> None: ...
    def getEntityValues(self) -> ContentValues: ...
    def getSubValues(self) -> list: ...
    def addSubValue(self, arg0: Uri, arg1: ContentValues) -> None: ...
    def toString(self) -> str: ...

    class NamedContentValues:
        uri: Uri
        values: ContentValues
        def __init__(self, arg0: Uri, arg1: ContentValues) -> None: ...
