from typing import Any, ClassVar, overload
from android.content.ContentValues import ContentValues
from android.database.Cursor import Cursor
from android.net.Uri import Uri

class SearchRecentSuggestionsProvider:
    DATABASE_MODE_2LINES: ClassVar[int]
    DATABASE_MODE_QUERIES: ClassVar[int]
    def __init__(self) -> None: ...
    def setupSuggestions(self, arg0: str, arg1: int) -> None: ...
    def delete(self, arg0: Uri, arg1: str, arg2: list[str]) -> int: ...
    def getType(self, arg0: Uri) -> str: ...
    def insert(self, arg0: Uri, arg1: ContentValues) -> Uri: ...
    def onCreate(self) -> bool: ...
    def query(self, arg0: Uri, arg1: list[str], arg2: str, arg3: list[str], arg4: str) -> Cursor: ...
    def update(self, arg0: Uri, arg1: ContentValues, arg2: str, arg3: list[str]) -> int: ...
