from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.os.IBinder import IBinder

class ServiceConnection:
    def onServiceConnected(self, arg0: ComponentName, arg1: IBinder) -> None: ...
    def onServiceDisconnected(self, arg0: ComponentName) -> None: ...
    def onBindingDied(self, arg0: ComponentName) -> None: ...
    def onNullBinding(self, arg0: ComponentName) -> None: ...
