from typing import Any, ClassVar, overload

class SharedPreferences:
    def getAll(self) -> dict: ...
    def getString(self, arg0: str, arg1: str) -> str: ...
    def getStringSet(self, arg0: str, arg1: set) -> set: ...
    def getInt(self, arg0: str, arg1: int) -> int: ...
    def getLong(self, arg0: str, arg1: int) -> int: ...
    def getFloat(self, arg0: str, arg1: float) -> float: ...
    def getBoolean(self, arg0: str, arg1: bool) -> bool: ...
    def contains(self, arg0: str) -> bool: ...
    def edit(self) -> "Editor": ...
    def registerOnSharedPreferenceChangeListener(self, arg0: "OnSharedPreferenceChangeListener") -> None: ...
    def unregisterOnSharedPreferenceChangeListener(self, arg0: "OnSharedPreferenceChangeListener") -> None: ...

    class Editor:
        def putString(self, arg0: str, arg1: str) -> "Editor": ...
        def putStringSet(self, arg0: str, arg1: set) -> "Editor": ...
        def putInt(self, arg0: str, arg1: int) -> "Editor": ...
        def putLong(self, arg0: str, arg1: int) -> "Editor": ...
        def putFloat(self, arg0: str, arg1: float) -> "Editor": ...
        def putBoolean(self, arg0: str, arg1: bool) -> "Editor": ...
        def remove(self, arg0: str) -> "Editor": ...
        def clear(self) -> "Editor": ...
        def commit(self) -> bool: ...
        def apply(self) -> None: ...

    class OnSharedPreferenceChangeListener:
        def onSharedPreferenceChanged(self, arg0: "SharedPreferences", arg1: str) -> None: ...
