from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class UriRelativeFilter:
    FRAGMENT: ClassVar[int]
    PATH: ClassVar[int]
    QUERY: ClassVar[int]
    def __init__(self, arg0: int, arg1: int, arg2: str) -> None: ...
    def getUriPart(self) -> int: ...
    def getPatternType(self) -> int: ...
    def getFilter(self) -> str: ...
    def matchData(self, arg0: Uri) -> bool: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
