from typing import Any, ClassVar, overload
from java.time.Duration import Duration
from java.time.Instant import Instant
from java.time.LocalDateTime import LocalDateTime
from java.time.ZoneOffset import ZoneOffset

class ZoneOffsetTransition:
    @staticmethod
    def of(arg0: LocalDateTime, arg1: ZoneOffset, arg2: ZoneOffset) -> "ZoneOffsetTransition": ...
    def getInstant(self) -> Instant: ...
    def toEpochSecond(self) -> int: ...
    def getDateTimeBefore(self) -> LocalDateTime: ...
    def getDateTimeAfter(self) -> LocalDateTime: ...
    def getOffsetBefore(self) -> ZoneOffset: ...
    def getOffsetAfter(self) -> ZoneOffset: ...
    def getDuration(self) -> Duration: ...
    def isGap(self) -> bool: ...
    def isOverlap(self) -> bool: ...
    def isValidOffset(self, arg0: ZoneOffset) -> bool: ...
    def compareTo(self, arg0: "ZoneOffsetTransition") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
