from typing import Any, ClassVar, overload
from java.time.DayOfWeek import DayOfWeek
from java.time.LocalDateTime import LocalDateTime
from java.time.LocalTime import LocalTime
from java.time.Month import Month
from java.time.ZoneOffset import ZoneOffset
from java.time.zone.ZoneOffsetTransition import ZoneOffsetTransition

class ZoneOffsetTransitionRule:
    @staticmethod
    def of(arg0: Month, arg1: int, arg2: DayOfWeek, arg3: LocalTime, arg4: bool, arg5: "TimeDefinition", arg6: ZoneOffset, arg7: ZoneOffset, arg8: ZoneOffset) -> "ZoneOffsetTransitionRule": ...
    def getMonth(self) -> Month: ...
    def getDayOfMonthIndicator(self) -> int: ...
    def getDayOfWeek(self) -> DayOfWeek: ...
    def getLocalTime(self) -> LocalTime: ...
    def isMidnightEndOfDay(self) -> bool: ...
    def getTimeDefinition(self) -> "TimeDefinition": ...
    def getStandardOffset(self) -> ZoneOffset: ...
    def getOffsetBefore(self) -> ZoneOffset: ...
    def getOffsetAfter(self) -> ZoneOffset: ...
    def createTransition(self, arg0: int) -> ZoneOffsetTransition: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class TimeDefinition:
        UTC: ClassVar["TimeDefinition"]
        WALL: ClassVar["TimeDefinition"]
        STANDARD: ClassVar["TimeDefinition"]
        @staticmethod
        def values() -> list["TimeDefinition"]: ...
        @staticmethod
        def valueOf(arg0: str) -> "TimeDefinition": ...
        def createDateTime(self, arg0: LocalDateTime, arg1: ZoneOffset, arg2: ZoneOffset) -> LocalDateTime: ...
