from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class DownloadableSubscription:
    CREATOR: ClassVar[Creator]
    def getEncodedActivationCode(self) -> str: ...
    @staticmethod
    def forActivationCode(arg0: str) -> "DownloadableSubscription": ...
    def getConfirmationCode(self) -> str: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, arg0: "DownloadableSubscription") -> None: ...
        @overload
        def __init__(self, arg0: str) -> None: ...
        def build(self) -> "DownloadableSubscription": ...
        def setEncodedActivationCode(self, arg0: str) -> "Builder": ...
        def setConfirmationCode(self, arg0: str) -> "Builder": ...
