from typing import Any, ClassVar, overload

class Energy:
    @staticmethod
    def fromCalories(arg0: float) -> "Energy": ...
    def getInCalories(self) -> float: ...
    def compareTo(self, arg0: "Energy") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
