from typing import Any, ClassVar, overload

class Length:
    @staticmethod
    def fromMeters(arg0: float) -> "Length": ...
    def getInMeters(self) -> float: ...
    def compareTo(self, arg0: "Length") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
