from typing import Any, ClassVar, overload

class Mass:
    @staticmethod
    def fromGrams(arg0: float) -> "Mass": ...
    def getInGrams(self) -> float: ...
    def compareTo(self, arg0: "Mass") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
