from typing import Any, ClassVar, overload

class Power:
    @staticmethod
    def fromWatts(arg0: float) -> "Power": ...
    def getInWatts(self) -> float: ...
    def compareTo(self, arg0: "Power") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
