from typing import Any, ClassVar, overload

class Velocity:
    @staticmethod
    def fromMetersPerSecond(arg0: float) -> "Velocity": ...
    def getInMetersPerSecond(self) -> float: ...
    def compareTo(self, arg0: "Velocity") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
