from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.graphics.Region import Region
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.util.Size import Size
from android.view.View import View
from android.view.accessibility.AccessibilityWindowInfo import AccessibilityWindowInfo
from java.time.Duration import Duration

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class AccessibilityNodeInfo:
    ACTION_ACCESSIBILITY_FOCUS: ClassVar[int]
    ACTION_ARGUMENT_COLUMN_INT: ClassVar[str]
    ACTION_ARGUMENT_DIRECTION_INT: ClassVar[str]
    ACTION_ARGUMENT_EXTEND_SELECTION_BOOLEAN: ClassVar[str]
    ACTION_ARGUMENT_HTML_ELEMENT_STRING: ClassVar[str]
    ACTION_ARGUMENT_MOVEMENT_GRANULARITY_INT: ClassVar[str]
    ACTION_ARGUMENT_MOVE_WINDOW_X: ClassVar[str]
    ACTION_ARGUMENT_MOVE_WINDOW_Y: ClassVar[str]
    ACTION_ARGUMENT_PRESS_AND_HOLD_DURATION_MILLIS_INT: ClassVar[str]
    ACTION_ARGUMENT_PROGRESS_VALUE: ClassVar[str]
    ACTION_ARGUMENT_ROW_INT: ClassVar[str]
    ACTION_ARGUMENT_SCROLL_AMOUNT_FLOAT: ClassVar[str]
    ACTION_ARGUMENT_SELECTION_END_INT: ClassVar[str]
    ACTION_ARGUMENT_SELECTION_START_INT: ClassVar[str]
    ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE: ClassVar[str]
    ACTION_CLEAR_ACCESSIBILITY_FOCUS: ClassVar[int]
    ACTION_CLEAR_FOCUS: ClassVar[int]
    ACTION_CLEAR_SELECTION: ClassVar[int]
    ACTION_CLICK: ClassVar[int]
    ACTION_COLLAPSE: ClassVar[int]
    ACTION_COPY: ClassVar[int]
    ACTION_CUT: ClassVar[int]
    ACTION_DISMISS: ClassVar[int]
    ACTION_EXPAND: ClassVar[int]
    ACTION_FOCUS: ClassVar[int]
    ACTION_LONG_CLICK: ClassVar[int]
    ACTION_NEXT_AT_MOVEMENT_GRANULARITY: ClassVar[int]
    ACTION_NEXT_HTML_ELEMENT: ClassVar[int]
    ACTION_PASTE: ClassVar[int]
    ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY: ClassVar[int]
    ACTION_PREVIOUS_HTML_ELEMENT: ClassVar[int]
    ACTION_SCROLL_BACKWARD: ClassVar[int]
    ACTION_SCROLL_FORWARD: ClassVar[int]
    ACTION_SELECT: ClassVar[int]
    ACTION_SET_SELECTION: ClassVar[int]
    ACTION_SET_TEXT: ClassVar[int]
    CREATOR: ClassVar[Creator]
    EXTRA_DATA_RENDERING_INFO_KEY: ClassVar[str]
    EXTRA_DATA_TEXT_CHARACTER_LOCATION_ARG_LENGTH: ClassVar[str]
    EXTRA_DATA_TEXT_CHARACTER_LOCATION_ARG_MAX_LENGTH: ClassVar[int]
    EXTRA_DATA_TEXT_CHARACTER_LOCATION_ARG_START_INDEX: ClassVar[str]
    EXTRA_DATA_TEXT_CHARACTER_LOCATION_KEY: ClassVar[str]
    FLAG_PREFETCH_ANCESTORS: ClassVar[int]
    FLAG_PREFETCH_DESCENDANTS_BREADTH_FIRST: ClassVar[int]
    FLAG_PREFETCH_DESCENDANTS_DEPTH_FIRST: ClassVar[int]
    FLAG_PREFETCH_DESCENDANTS_HYBRID: ClassVar[int]
    FLAG_PREFETCH_SIBLINGS: ClassVar[int]
    FLAG_PREFETCH_UNINTERRUPTIBLE: ClassVar[int]
    FOCUS_ACCESSIBILITY: ClassVar[int]
    FOCUS_INPUT: ClassVar[int]
    MAX_NUMBER_OF_PREFETCHED_NODES: ClassVar[int]
    MOVEMENT_GRANULARITY_CHARACTER: ClassVar[int]
    MOVEMENT_GRANULARITY_LINE: ClassVar[int]
    MOVEMENT_GRANULARITY_PAGE: ClassVar[int]
    MOVEMENT_GRANULARITY_PARAGRAPH: ClassVar[int]
    MOVEMENT_GRANULARITY_WORD: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: View) -> None: ...
    @overload
    def __init__(self, arg0: View, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: "AccessibilityNodeInfo") -> None: ...
    @overload
    def setSource(self, arg0: View) -> None: ...
    @overload
    def setSource(self, arg0: View, arg1: int) -> None: ...
    def findFocus(self, arg0: int) -> "AccessibilityNodeInfo": ...
    def focusSearch(self, arg0: int) -> "AccessibilityNodeInfo": ...
    def getWindowId(self) -> int: ...
    def refresh(self) -> bool: ...
    def refreshWithExtraData(self, arg0: str, arg1: Bundle) -> bool: ...
    def getChildCount(self) -> int: ...
    @overload
    def getChild(self, arg0: int) -> "AccessibilityNodeInfo": ...
    @overload
    def getChild(self, arg0: int, arg1: int) -> "AccessibilityNodeInfo": ...
    @overload
    def addChild(self, arg0: View) -> None: ...
    @overload
    def addChild(self, arg0: View, arg1: int) -> None: ...
    @overload
    def removeChild(self, arg0: View) -> bool: ...
    @overload
    def removeChild(self, arg0: View, arg1: int) -> bool: ...
    def getActionList(self) -> list: ...
    def getActions(self) -> int: ...
    @overload
    def addAction(self, arg0: "AccessibilityAction") -> None: ...
    @overload
    def addAction(self, arg0: int) -> None: ...
    @overload
    def removeAction(self, arg0: int) -> None: ...
    @overload
    def removeAction(self, arg0: "AccessibilityAction") -> bool: ...
    def getTraversalBefore(self) -> "AccessibilityNodeInfo": ...
    @overload
    def setTraversalBefore(self, arg0: View) -> None: ...
    @overload
    def setTraversalBefore(self, arg0: View, arg1: int) -> None: ...
    def getTraversalAfter(self) -> "AccessibilityNodeInfo": ...
    @overload
    def setTraversalAfter(self, arg0: View) -> None: ...
    @overload
    def setTraversalAfter(self, arg0: View, arg1: int) -> None: ...
    def getAvailableExtraData(self) -> list: ...
    def setAvailableExtraData(self, arg0: list) -> None: ...
    def setMaxTextLength(self, arg0: int) -> None: ...
    def getMaxTextLength(self) -> int: ...
    def setMovementGranularities(self, arg0: int) -> None: ...
    def getMovementGranularities(self) -> int: ...
    def setMinDurationBetweenContentChanges(self, arg0: Duration) -> None: ...
    def getMinDurationBetweenContentChanges(self) -> Duration: ...
    @overload
    def performAction(self, arg0: int) -> bool: ...
    @overload
    def performAction(self, arg0: int, arg1: Bundle) -> bool: ...
    def findAccessibilityNodeInfosByText(self, arg0: str) -> list: ...
    def findAccessibilityNodeInfosByViewId(self, arg0: str) -> list: ...
    def getWindow(self) -> AccessibilityWindowInfo: ...
    @overload
    def getParent(self) -> "AccessibilityNodeInfo": ...
    @overload
    def getParent(self, arg0: int) -> "AccessibilityNodeInfo": ...
    @overload
    def setParent(self, arg0: View) -> None: ...
    @overload
    def setParent(self, arg0: View, arg1: int) -> None: ...
    def getBoundsInParent(self, arg0: Rect) -> None: ...
    def setBoundsInParent(self, arg0: Rect) -> None: ...
    def getBoundsInScreen(self, arg0: Rect) -> None: ...
    def setBoundsInScreen(self, arg0: Rect) -> None: ...
    def getBoundsInWindow(self, arg0: Rect) -> None: ...
    def setBoundsInWindow(self, arg0: Rect) -> None: ...
    def isCheckable(self) -> bool: ...
    def setCheckable(self, arg0: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, arg0: bool) -> None: ...
    def isFocusable(self) -> bool: ...
    def setFocusable(self, arg0: bool) -> None: ...
    def isFocused(self) -> bool: ...
    def setFocused(self, arg0: bool) -> None: ...
    def isVisibleToUser(self) -> bool: ...
    def setVisibleToUser(self, arg0: bool) -> None: ...
    def isAccessibilityFocused(self) -> bool: ...
    def setAccessibilityFocused(self, arg0: bool) -> None: ...
    def isSelected(self) -> bool: ...
    def setSelected(self, arg0: bool) -> None: ...
    def isClickable(self) -> bool: ...
    def setClickable(self, arg0: bool) -> None: ...
    def isLongClickable(self) -> bool: ...
    def setLongClickable(self, arg0: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setEnabled(self, arg0: bool) -> None: ...
    def isPassword(self) -> bool: ...
    def setPassword(self, arg0: bool) -> None: ...
    def isScrollable(self) -> bool: ...
    def setScrollable(self, arg0: bool) -> None: ...
    def isGranularScrollingSupported(self) -> bool: ...
    def setGranularScrollingSupported(self, arg0: bool) -> None: ...
    def isTextSelectable(self) -> bool: ...
    def setTextSelectable(self, arg0: bool) -> None: ...
    def hasRequestInitialAccessibilityFocus(self) -> bool: ...
    def setRequestInitialAccessibilityFocus(self, arg0: bool) -> None: ...
    def isEditable(self) -> bool: ...
    def setEditable(self, arg0: bool) -> None: ...
    def isAccessibilityDataSensitive(self) -> bool: ...
    def setAccessibilityDataSensitive(self, arg0: bool) -> None: ...
    def setPaneTitle(self, arg0: str) -> None: ...
    def getPaneTitle(self) -> str: ...
    def getDrawingOrder(self) -> int: ...
    def setDrawingOrder(self, arg0: int) -> None: ...
    def getCollectionInfo(self) -> "CollectionInfo": ...
    def setCollectionInfo(self, arg0: "CollectionInfo") -> None: ...
    def getCollectionItemInfo(self) -> "CollectionItemInfo": ...
    def setCollectionItemInfo(self, arg0: "CollectionItemInfo") -> None: ...
    def getRangeInfo(self) -> "RangeInfo": ...
    def setRangeInfo(self, arg0: "RangeInfo") -> None: ...
    def getExtraRenderingInfo(self) -> "ExtraRenderingInfo": ...
    def isContentInvalid(self) -> bool: ...
    def setContentInvalid(self, arg0: bool) -> None: ...
    def isContextClickable(self) -> bool: ...
    def setContextClickable(self, arg0: bool) -> None: ...
    def getLiveRegion(self) -> int: ...
    def setLiveRegion(self, arg0: int) -> None: ...
    def isMultiLine(self) -> bool: ...
    def setMultiLine(self, arg0: bool) -> None: ...
    def canOpenPopup(self) -> bool: ...
    def setCanOpenPopup(self, arg0: bool) -> None: ...
    def isDismissable(self) -> bool: ...
    def setDismissable(self, arg0: bool) -> None: ...
    def isImportantForAccessibility(self) -> bool: ...
    def setImportantForAccessibility(self, arg0: bool) -> None: ...
    def isScreenReaderFocusable(self) -> bool: ...
    def setScreenReaderFocusable(self, arg0: bool) -> None: ...
    def isShowingHintText(self) -> bool: ...
    def setShowingHintText(self, arg0: bool) -> None: ...
    def isHeading(self) -> bool: ...
    def setHeading(self, arg0: bool) -> None: ...
    def isTextEntryKey(self) -> bool: ...
    def setTextEntryKey(self, arg0: bool) -> None: ...
    def getPackageName(self) -> str: ...
    def setPackageName(self, arg0: str) -> None: ...
    def getClassName(self) -> str: ...
    def setClassName(self, arg0: str) -> None: ...
    def getText(self) -> str: ...
    def setText(self, arg0: str) -> None: ...
    def getHintText(self) -> str: ...
    def setHintText(self, arg0: str) -> None: ...
    def setError(self, arg0: str) -> None: ...
    def getError(self) -> str: ...
    def getStateDescription(self) -> str: ...
    def getContentDescription(self) -> str: ...
    def setStateDescription(self, arg0: str) -> None: ...
    def setContentDescription(self, arg0: str) -> None: ...
    def getTooltipText(self) -> str: ...
    def setTooltipText(self, arg0: str) -> None: ...
    @overload
    def setLabelFor(self, arg0: View) -> None: ...
    @overload
    def setLabelFor(self, arg0: View, arg1: int) -> None: ...
    def getLabelFor(self) -> "AccessibilityNodeInfo": ...
    @overload
    def setLabeledBy(self, arg0: View) -> None: ...
    @overload
    def setLabeledBy(self, arg0: View, arg1: int) -> None: ...
    def getLabeledBy(self) -> "AccessibilityNodeInfo": ...
    def setViewIdResourceName(self, arg0: str) -> None: ...
    def getViewIdResourceName(self) -> str: ...
    def getTextSelectionStart(self) -> int: ...
    def getTextSelectionEnd(self) -> int: ...
    def setTextSelection(self, arg0: int, arg1: int) -> None: ...
    def getInputType(self) -> int: ...
    def setInputType(self, arg0: int) -> None: ...
    def getExtras(self) -> Bundle: ...
    def getTouchDelegateInfo(self) -> "TouchDelegateInfo": ...
    def setTouchDelegateInfo(self, arg0: "TouchDelegateInfo") -> None: ...
    def describeContents(self) -> int: ...
    def setUniqueId(self, arg0: str) -> None: ...
    def getUniqueId(self) -> str: ...
    def setContainerTitle(self, arg0: str) -> None: ...
    def getContainerTitle(self) -> str: ...
    def setQueryFromAppProcessEnabled(self, arg0: View, arg1: bool) -> None: ...
    @overload
    @staticmethod
    def obtain(arg0: View) -> "AccessibilityNodeInfo": ...
    @overload
    @staticmethod
    def obtain(arg0: View, arg1: int) -> "AccessibilityNodeInfo": ...
    @overload
    @staticmethod
    def obtain() -> "AccessibilityNodeInfo": ...
    @overload
    @staticmethod
    def obtain(arg0: "AccessibilityNodeInfo") -> "AccessibilityNodeInfo": ...
    def recycle(self) -> None: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class AccessibilityAction:
        ACTION_ACCESSIBILITY_FOCUS: ClassVar["AccessibilityAction"]
        ACTION_CLEAR_ACCESSIBILITY_FOCUS: ClassVar["AccessibilityAction"]
        ACTION_CLEAR_FOCUS: ClassVar["AccessibilityAction"]
        ACTION_CLEAR_SELECTION: ClassVar["AccessibilityAction"]
        ACTION_CLICK: ClassVar["AccessibilityAction"]
        ACTION_COLLAPSE: ClassVar["AccessibilityAction"]
        ACTION_CONTEXT_CLICK: ClassVar["AccessibilityAction"]
        ACTION_COPY: ClassVar["AccessibilityAction"]
        ACTION_CUT: ClassVar["AccessibilityAction"]
        ACTION_DISMISS: ClassVar["AccessibilityAction"]
        ACTION_DRAG_CANCEL: ClassVar["AccessibilityAction"]
        ACTION_DRAG_DROP: ClassVar["AccessibilityAction"]
        ACTION_DRAG_START: ClassVar["AccessibilityAction"]
        ACTION_EXPAND: ClassVar["AccessibilityAction"]
        ACTION_FOCUS: ClassVar["AccessibilityAction"]
        ACTION_HIDE_TOOLTIP: ClassVar["AccessibilityAction"]
        ACTION_IME_ENTER: ClassVar["AccessibilityAction"]
        ACTION_LONG_CLICK: ClassVar["AccessibilityAction"]
        ACTION_MOVE_WINDOW: ClassVar["AccessibilityAction"]
        ACTION_NEXT_AT_MOVEMENT_GRANULARITY: ClassVar["AccessibilityAction"]
        ACTION_NEXT_HTML_ELEMENT: ClassVar["AccessibilityAction"]
        ACTION_PAGE_DOWN: ClassVar["AccessibilityAction"]
        ACTION_PAGE_LEFT: ClassVar["AccessibilityAction"]
        ACTION_PAGE_RIGHT: ClassVar["AccessibilityAction"]
        ACTION_PAGE_UP: ClassVar["AccessibilityAction"]
        ACTION_PASTE: ClassVar["AccessibilityAction"]
        ACTION_PRESS_AND_HOLD: ClassVar["AccessibilityAction"]
        ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY: ClassVar["AccessibilityAction"]
        ACTION_PREVIOUS_HTML_ELEMENT: ClassVar["AccessibilityAction"]
        ACTION_SCROLL_BACKWARD: ClassVar["AccessibilityAction"]
        ACTION_SCROLL_DOWN: ClassVar["AccessibilityAction"]
        ACTION_SCROLL_FORWARD: ClassVar["AccessibilityAction"]
        ACTION_SCROLL_IN_DIRECTION: ClassVar["AccessibilityAction"]
        ACTION_SCROLL_LEFT: ClassVar["AccessibilityAction"]
        ACTION_SCROLL_RIGHT: ClassVar["AccessibilityAction"]
        ACTION_SCROLL_TO_POSITION: ClassVar["AccessibilityAction"]
        ACTION_SCROLL_UP: ClassVar["AccessibilityAction"]
        ACTION_SELECT: ClassVar["AccessibilityAction"]
        ACTION_SET_PROGRESS: ClassVar["AccessibilityAction"]
        ACTION_SET_SELECTION: ClassVar["AccessibilityAction"]
        ACTION_SET_TEXT: ClassVar["AccessibilityAction"]
        ACTION_SHOW_ON_SCREEN: ClassVar["AccessibilityAction"]
        ACTION_SHOW_TEXT_SUGGESTIONS: ClassVar["AccessibilityAction"]
        ACTION_SHOW_TOOLTIP: ClassVar["AccessibilityAction"]
        CREATOR: ClassVar[Creator]
        def __init__(self, arg0: int, arg1: str) -> None: ...
        def getId(self) -> int: ...
        def getLabel(self) -> str: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def toString(self) -> str: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class CollectionInfo:
        SELECTION_MODE_MULTIPLE: ClassVar[int]
        SELECTION_MODE_NONE: ClassVar[int]
        SELECTION_MODE_SINGLE: ClassVar[int]
        UNDEFINED: ClassVar[int]
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: bool) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: bool, arg3: int) -> None: ...
        @overload
        @staticmethod
        def obtain(arg0: int, arg1: int, arg2: bool) -> "CollectionInfo": ...
        @overload
        @staticmethod
        def obtain(arg0: int, arg1: int, arg2: bool, arg3: int) -> "CollectionInfo": ...
        def getRowCount(self) -> int: ...
        def getColumnCount(self) -> int: ...
        def isHierarchical(self) -> bool: ...
        def getSelectionMode(self) -> int: ...
        def getItemCount(self) -> int: ...
        def getImportantForAccessibilityItemCount(self) -> int: ...

        class Builder:
            def __init__(self) -> None: ...
            def setRowCount(self, arg0: int) -> "Builder": ...
            def setColumnCount(self, arg0: int) -> "Builder": ...
            def setHierarchical(self, arg0: bool) -> "Builder": ...
            def setSelectionMode(self, arg0: int) -> "Builder": ...
            def setItemCount(self, arg0: int) -> "Builder": ...
            def setImportantForAccessibilityItemCount(self, arg0: int) -> "Builder": ...
            def build(self) -> "CollectionInfo": ...

    class CollectionItemInfo:
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: bool) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: bool, arg5: bool) -> None: ...
        @overload
        @staticmethod
        def obtain(arg0: int, arg1: int, arg2: int, arg3: int, arg4: bool) -> "CollectionItemInfo": ...
        @overload
        @staticmethod
        def obtain(arg0: int, arg1: int, arg2: int, arg3: int, arg4: bool, arg5: bool) -> "CollectionItemInfo": ...
        def getColumnIndex(self) -> int: ...
        def getRowIndex(self) -> int: ...
        def getColumnSpan(self) -> int: ...
        def getRowSpan(self) -> int: ...
        def isHeading(self) -> bool: ...
        def isSelected(self) -> bool: ...
        def getRowTitle(self) -> str: ...
        def getColumnTitle(self) -> str: ...

        class Builder:
            def __init__(self) -> None: ...
            def setHeading(self, arg0: bool) -> "Builder": ...
            def setColumnIndex(self, arg0: int) -> "Builder": ...
            def setRowIndex(self, arg0: int) -> "Builder": ...
            def setColumnSpan(self, arg0: int) -> "Builder": ...
            def setRowSpan(self, arg0: int) -> "Builder": ...
            def setSelected(self, arg0: bool) -> "Builder": ...
            def setRowTitle(self, arg0: str) -> "Builder": ...
            def setColumnTitle(self, arg0: str) -> "Builder": ...
            def build(self) -> "CollectionItemInfo": ...

    class ExtraRenderingInfo:
        def getLayoutSize(self) -> Size: ...
        def getTextSizeInPx(self) -> float: ...
        def getTextSizeUnit(self) -> int: ...

    class RangeInfo:
        RANGE_TYPE_FLOAT: ClassVar[int]
        RANGE_TYPE_INT: ClassVar[int]
        RANGE_TYPE_PERCENT: ClassVar[int]
        def __init__(self, arg0: int, arg1: float, arg2: float, arg3: float) -> None: ...
        @staticmethod
        def obtain(arg0: int, arg1: float, arg2: float, arg3: float) -> "RangeInfo": ...
        def getType(self) -> int: ...
        def getMin(self) -> float: ...
        def getMax(self) -> float: ...
        def getCurrent(self) -> float: ...

    class TouchDelegateInfo:
        CREATOR: ClassVar[Creator]
        def __init__(self, arg0: dict) -> None: ...
        def getRegionCount(self) -> int: ...
        def getRegionAt(self, arg0: int) -> Region: ...
        def getTargetForRegion(self, arg0: Region) -> "AccessibilityNodeInfo": ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
