from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["AccessibilityWindowInfo"]

class AccessibilityWindowInfo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/view/accessibility/AccessibilityWindowInfo"
    __javaconstructor__ = [("()V", False), ("(Landroid/view/accessibility/AccessibilityWindowInfo;)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    TYPE_ACCESSIBILITY_OVERLAY = JavaStaticField("I")
    TYPE_APPLICATION = JavaStaticField("I")
    TYPE_INPUT_METHOD = JavaStaticField("I")
    TYPE_MAGNIFICATION_OVERLAY = JavaStaticField("I")
    TYPE_SPLIT_SCREEN_DIVIDER = JavaStaticField("I")
    TYPE_SYSTEM = JavaStaticField("I")
    getTitle = JavaMethod("()Ljava/lang/CharSequence;")
    getType = JavaMethod("()I")
    getLayer = JavaMethod("()I")
    getRoot = JavaMultipleMethod([("()Landroid/view/accessibility/AccessibilityNodeInfo;", False, False), ("(I)Landroid/view/accessibility/AccessibilityNodeInfo;", False, False)])
    getAnchor = JavaMethod("()Landroid/view/accessibility/AccessibilityNodeInfo;")
    isInPictureInPictureMode = JavaMethod("()Z")
    getParent = JavaMethod("()Landroid/view/accessibility/AccessibilityWindowInfo;")
    getId = JavaMethod("()I")
    getRegionInScreen = JavaMethod("(Landroid/graphics/Region;)V")
    getBoundsInScreen = JavaMethod("(Landroid/graphics/Rect;)V")
    isActive = JavaMethod("()Z")
    isFocused = JavaMethod("()Z")
    isAccessibilityFocused = JavaMethod("()Z")
    getChildCount = JavaMethod("()I")
    getChild = JavaMethod("(I)Landroid/view/accessibility/AccessibilityWindowInfo;")
    getDisplayId = JavaMethod("()I")
    getTransitionTimeMillis = JavaMethod("()J")
    getLocales = JavaMethod("()Landroid/os/LocaleList;")
    obtain = JavaMultipleMethod([("()Landroid/view/accessibility/AccessibilityWindowInfo;", True, False), ("(Landroid/view/accessibility/AccessibilityWindowInfo;)Landroid/view/accessibility/AccessibilityWindowInfo;", True, False)])
    recycle = JavaMethod("()V")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    hashCode = JavaMethod("()I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")