from typing import Any, ClassVar, overload
from android.graphics.Typeface import Typeface
from java.util.Locale import Locale

class CaptioningManager:
    def isEnabled(self) -> bool: ...
    def getLocale(self) -> Locale: ...
    def getFontScale(self) -> float: ...
    def getUserStyle(self) -> "CaptionStyle": ...
    def isSystemAudioCaptioningEnabled(self) -> bool: ...
    def isSystemAudioCaptioningUiEnabled(self) -> bool: ...
    def addCaptioningChangeListener(self, arg0: "CaptioningChangeListener") -> None: ...
    def removeCaptioningChangeListener(self, arg0: "CaptioningChangeListener") -> None: ...
    def isCallCaptioningEnabled(self) -> bool: ...

    class CaptionStyle:
        EDGE_TYPE_DEPRESSED: ClassVar[int]
        EDGE_TYPE_DROP_SHADOW: ClassVar[int]
        EDGE_TYPE_NONE: ClassVar[int]
        EDGE_TYPE_OUTLINE: ClassVar[int]
        EDGE_TYPE_RAISED: ClassVar[int]
        EDGE_TYPE_UNSPECIFIED: ClassVar[int]
        backgroundColor: int
        edgeColor: int
        edgeType: int
        foregroundColor: int
        windowColor: int
        def hasBackgroundColor(self) -> bool: ...
        def hasForegroundColor(self) -> bool: ...
        def hasEdgeType(self) -> bool: ...
        def hasEdgeColor(self) -> bool: ...
        def hasWindowColor(self) -> bool: ...
        def getTypeface(self) -> Typeface: ...

    class CaptioningChangeListener:
        def __init__(self) -> None: ...
        def onEnabledChanged(self, arg0: bool) -> None: ...
        def onUserStyleChanged(self, arg0: "CaptionStyle") -> None: ...
        def onLocaleChanged(self, arg0: Locale) -> None: ...
        def onFontScaleChanged(self, arg0: float) -> None: ...
        def onSystemAudioCaptioningChanged(self, arg0: bool) -> None: ...
        def onSystemAudioCaptioningUiChanged(self, arg0: bool) -> None: ...
