from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator
from java.util.ListIterator import ListIterator

class AbstractSequentialList:
    def __init__(self) -> None: ...
    def get(self, arg0: int) -> Any: ...
    def set(self, arg0: int, arg1: Any) -> Any: ...
    def add(self, arg0: int, arg1: Any) -> None: ...
    def remove(self, arg0: int) -> Any: ...
    def addAll(self, arg0: int, arg1: list) -> bool: ...
    def iterator(self) -> Iterator: ...
    def listIterator(self, arg0: int) -> ListIterator: ...
