from typing import Any, ClassVar, overload
from java.lang.Comparable import Comparable
from java.util.Comparator import Comparator
from java.util.Spliterator import Spliterator
from java.util.function.BinaryOperator import BinaryOperator
from java.util.function.DoubleBinaryOperator import DoubleBinaryOperator
from java.util.function.IntBinaryOperator import IntBinaryOperator
from java.util.function.IntFunction import IntFunction
from java.util.function.IntToDoubleFunction import IntToDoubleFunction
from java.util.function.IntToLongFunction import IntToLongFunction
from java.util.function.IntUnaryOperator import IntUnaryOperator
from java.util.function.LongBinaryOperator import LongBinaryOperator
from java.util.stream.DoubleStream import DoubleStream
from java.util.stream.IntStream import IntStream
from java.util.stream.LongStream import LongStream
from java.util.stream.Stream import Stream

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OfInt:
    """Forward declaration for ``java.util.Spliterator.OfInt``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.util.Spliterator.OfInt')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/util/Spliterator/OfInt.html
    """
    ...
class OfLong:
    """Forward declaration for ``java.util.Spliterator.OfLong``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.util.Spliterator.OfLong')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/util/Spliterator/OfLong.html
    """
    ...
class OfDouble:
    """Forward declaration for ``java.util.Spliterator.OfDouble``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.util.Spliterator.OfDouble')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/util/Spliterator/OfDouble.html
    """
    ...

class Arrays:
    @overload
    @staticmethod
    def sort(arg0: list[int]) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[int]) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[int]) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[str]) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[str], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[int]) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[float]) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[float], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[float]) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list[float], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list, arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list, arg1: Comparator) -> None: ...
    @overload
    @staticmethod
    def sort(arg0: list, arg1: int, arg2: int, arg3: Comparator) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[int]) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[str]) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[str], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[int]) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[int]) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[int]) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[int], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[float]) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[float], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[float]) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[float], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[Comparable]) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list[Comparable], arg1: int, arg2: int) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list, arg1: Comparator) -> None: ...
    @overload
    @staticmethod
    def parallelSort(arg0: list, arg1: int, arg2: int, arg3: Comparator) -> None: ...
    @overload
    @staticmethod
    def parallelPrefix(arg0: list, arg1: BinaryOperator) -> None: ...
    @overload
    @staticmethod
    def parallelPrefix(arg0: list, arg1: int, arg2: int, arg3: BinaryOperator) -> None: ...
    @overload
    @staticmethod
    def parallelPrefix(arg0: list[int], arg1: LongBinaryOperator) -> None: ...
    @overload
    @staticmethod
    def parallelPrefix(arg0: list[int], arg1: int, arg2: int, arg3: LongBinaryOperator) -> None: ...
    @overload
    @staticmethod
    def parallelPrefix(arg0: list[float], arg1: DoubleBinaryOperator) -> None: ...
    @overload
    @staticmethod
    def parallelPrefix(arg0: list[float], arg1: int, arg2: int, arg3: DoubleBinaryOperator) -> None: ...
    @overload
    @staticmethod
    def parallelPrefix(arg0: list[int], arg1: IntBinaryOperator) -> None: ...
    @overload
    @staticmethod
    def parallelPrefix(arg0: list[int], arg1: int, arg2: int, arg3: IntBinaryOperator) -> None: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[int], arg1: int) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[int], arg1: int, arg2: int, arg3: int) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[int], arg1: int) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[int], arg1: int, arg2: int, arg3: int) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[int], arg1: int) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[int], arg1: int, arg2: int, arg3: int) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[str], arg1: str) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[str], arg1: int, arg2: int, arg3: str) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[int], arg1: int) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[int], arg1: int, arg2: int, arg3: int) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[float], arg1: float) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[float], arg1: int, arg2: int, arg3: float) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[float], arg1: float) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list[float], arg1: int, arg2: int, arg3: float) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list, arg1: Any) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list, arg1: int, arg2: int, arg3: Any) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list, arg1: Any, arg2: Comparator) -> int: ...
    @overload
    @staticmethod
    def binarySearch(arg0: list, arg1: int, arg2: int, arg3: Any, arg4: Comparator) -> int: ...
    @overload
    @staticmethod
    def equals(arg0: list[int], arg1: list[int]) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[int], arg1: list[int]) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[int], arg1: list[int]) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[str], arg1: list[str]) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[str], arg1: int, arg2: int, arg3: list[str], arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[int], arg1: list[int]) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[bool], arg1: list[bool]) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[bool], arg1: int, arg2: int, arg3: list[bool], arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[float], arg1: list[float]) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[float], arg1: int, arg2: int, arg3: list[float], arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[float], arg1: list[float]) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list[float], arg1: int, arg2: int, arg3: list[float], arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list, arg1: list) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list, arg1: int, arg2: int, arg3: list, arg4: int, arg5: int) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list, arg1: list, arg2: Comparator) -> bool: ...
    @overload
    @staticmethod
    def equals(arg0: list, arg1: int, arg2: int, arg3: list, arg4: int, arg5: int, arg6: Comparator) -> bool: ...
    @overload
    @staticmethod
    def fill(arg0: list[int], arg1: int) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[int], arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[int], arg1: int) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[int], arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[int], arg1: int) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[int], arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[str], arg1: str) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[str], arg1: int, arg2: int, arg3: str) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[int], arg1: int) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[int], arg1: int, arg2: int, arg3: int) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[bool], arg1: bool) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[bool], arg1: int, arg2: int, arg3: bool) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[float], arg1: float) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[float], arg1: int, arg2: int, arg3: float) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[float], arg1: float) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list[float], arg1: int, arg2: int, arg3: float) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list, arg1: Any) -> None: ...
    @overload
    @staticmethod
    def fill(arg0: list, arg1: int, arg2: int, arg3: Any) -> None: ...
    @overload
    @staticmethod
    def copyOf(arg0: list, arg1: int) -> list: ...
    @overload
    @staticmethod
    def copyOf(arg0: list, arg1: int, arg2: type) -> list: ...
    @overload
    @staticmethod
    def copyOf(arg0: list[int], arg1: int) -> list[int]: ...
    @overload
    @staticmethod
    def copyOf(arg0: list[int], arg1: int) -> list[int]: ...
    @overload
    @staticmethod
    def copyOf(arg0: list[int], arg1: int) -> list[int]: ...
    @overload
    @staticmethod
    def copyOf(arg0: list[int], arg1: int) -> list[int]: ...
    @overload
    @staticmethod
    def copyOf(arg0: list[str], arg1: int) -> list[str]: ...
    @overload
    @staticmethod
    def copyOf(arg0: list[float], arg1: int) -> list[float]: ...
    @overload
    @staticmethod
    def copyOf(arg0: list[float], arg1: int) -> list[float]: ...
    @overload
    @staticmethod
    def copyOf(arg0: list[bool], arg1: int) -> list[bool]: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list, arg1: int, arg2: int) -> list: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list, arg1: int, arg2: int, arg3: type) -> list: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list[int], arg1: int, arg2: int) -> list[int]: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list[int], arg1: int, arg2: int) -> list[int]: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list[int], arg1: int, arg2: int) -> list[int]: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list[int], arg1: int, arg2: int) -> list[int]: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list[str], arg1: int, arg2: int) -> list[str]: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list[float], arg1: int, arg2: int) -> list[float]: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list[float], arg1: int, arg2: int) -> list[float]: ...
    @overload
    @staticmethod
    def copyOfRange(arg0: list[bool], arg1: int, arg2: int) -> list[bool]: ...
    @staticmethod
    def asList(*arg0: Any) -> list: ...
    @overload
    @staticmethod
    def hashCode(arg0: list[int]) -> int: ...
    @overload
    @staticmethod
    def hashCode(arg0: list[int]) -> int: ...
    @overload
    @staticmethod
    def hashCode(arg0: list[int]) -> int: ...
    @overload
    @staticmethod
    def hashCode(arg0: list[str]) -> int: ...
    @overload
    @staticmethod
    def hashCode(arg0: list[int]) -> int: ...
    @overload
    @staticmethod
    def hashCode(arg0: list[bool]) -> int: ...
    @overload
    @staticmethod
    def hashCode(arg0: list[float]) -> int: ...
    @overload
    @staticmethod
    def hashCode(arg0: list[float]) -> int: ...
    @overload
    @staticmethod
    def hashCode(arg0: list) -> int: ...
    @staticmethod
    def deepHashCode(arg0: list) -> int: ...
    @staticmethod
    def deepEquals(arg0: list, arg1: list) -> bool: ...
    @overload
    @staticmethod
    def toString(arg0: list[int]) -> str: ...
    @overload
    @staticmethod
    def toString(arg0: list[int]) -> str: ...
    @overload
    @staticmethod
    def toString(arg0: list[int]) -> str: ...
    @overload
    @staticmethod
    def toString(arg0: list[str]) -> str: ...
    @overload
    @staticmethod
    def toString(arg0: list[int]) -> str: ...
    @overload
    @staticmethod
    def toString(arg0: list[bool]) -> str: ...
    @overload
    @staticmethod
    def toString(arg0: list[float]) -> str: ...
    @overload
    @staticmethod
    def toString(arg0: list[float]) -> str: ...
    @overload
    @staticmethod
    def toString(arg0: list) -> str: ...
    @staticmethod
    def deepToString(arg0: list) -> str: ...
    @overload
    @staticmethod
    def setAll(arg0: list, arg1: IntFunction) -> None: ...
    @overload
    @staticmethod
    def setAll(arg0: list[int], arg1: IntUnaryOperator) -> None: ...
    @overload
    @staticmethod
    def setAll(arg0: list[int], arg1: IntToLongFunction) -> None: ...
    @overload
    @staticmethod
    def setAll(arg0: list[float], arg1: IntToDoubleFunction) -> None: ...
    @overload
    @staticmethod
    def parallelSetAll(arg0: list, arg1: IntFunction) -> None: ...
    @overload
    @staticmethod
    def parallelSetAll(arg0: list[int], arg1: IntUnaryOperator) -> None: ...
    @overload
    @staticmethod
    def parallelSetAll(arg0: list[int], arg1: IntToLongFunction) -> None: ...
    @overload
    @staticmethod
    def parallelSetAll(arg0: list[float], arg1: IntToDoubleFunction) -> None: ...
    @overload
    @staticmethod
    def spliterator(arg0: list) -> Spliterator: ...
    @overload
    @staticmethod
    def spliterator(arg0: list, arg1: int, arg2: int) -> Spliterator: ...
    @overload
    @staticmethod
    def spliterator(arg0: list[int]) -> OfInt: ...
    @overload
    @staticmethod
    def spliterator(arg0: list[int], arg1: int, arg2: int) -> OfInt: ...
    @overload
    @staticmethod
    def spliterator(arg0: list[int]) -> OfLong: ...
    @overload
    @staticmethod
    def spliterator(arg0: list[int], arg1: int, arg2: int) -> OfLong: ...
    @overload
    @staticmethod
    def spliterator(arg0: list[float]) -> OfDouble: ...
    @overload
    @staticmethod
    def spliterator(arg0: list[float], arg1: int, arg2: int) -> OfDouble: ...
    @overload
    @staticmethod
    def stream(arg0: list) -> Stream: ...
    @overload
    @staticmethod
    def stream(arg0: list, arg1: int, arg2: int) -> Stream: ...
    @overload
    @staticmethod
    def stream(arg0: list[int]) -> IntStream: ...
    @overload
    @staticmethod
    def stream(arg0: list[int], arg1: int, arg2: int) -> IntStream: ...
    @overload
    @staticmethod
    def stream(arg0: list[int]) -> LongStream: ...
    @overload
    @staticmethod
    def stream(arg0: list[int], arg1: int, arg2: int) -> LongStream: ...
    @overload
    @staticmethod
    def stream(arg0: list[float]) -> DoubleStream: ...
    @overload
    @staticmethod
    def stream(arg0: list[float], arg1: int, arg2: int) -> DoubleStream: ...
    @overload
    @staticmethod
    def compare(arg0: list[bool], arg1: list[bool]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[bool], arg1: int, arg2: int, arg3: list[bool], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[str], arg1: list[str]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[str], arg1: int, arg2: int, arg3: list[str], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[float], arg1: list[float]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[float], arg1: int, arg2: int, arg3: list[float], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[float], arg1: list[float]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[float], arg1: int, arg2: int, arg3: list[float], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[Comparable], arg1: list[Comparable]) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list[Comparable], arg1: int, arg2: int, arg3: list[Comparable], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list, arg1: list, arg2: Comparator) -> int: ...
    @overload
    @staticmethod
    def compare(arg0: list, arg1: int, arg2: int, arg3: list, arg4: int, arg5: int, arg6: Comparator) -> int: ...
    @overload
    @staticmethod
    def compareUnsigned(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def compareUnsigned(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compareUnsigned(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def compareUnsigned(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compareUnsigned(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def compareUnsigned(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def compareUnsigned(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def compareUnsigned(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[bool], arg1: list[bool]) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[bool], arg1: int, arg2: int, arg3: list[bool], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[str], arg1: list[str]) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[str], arg1: int, arg2: int, arg3: list[str], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[int], arg1: list[int]) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[int], arg1: int, arg2: int, arg3: list[int], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[float], arg1: list[float]) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[float], arg1: int, arg2: int, arg3: list[float], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[float], arg1: list[float]) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list[float], arg1: int, arg2: int, arg3: list[float], arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list, arg1: list) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list, arg1: int, arg2: int, arg3: list, arg4: int, arg5: int) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list, arg1: list, arg2: Comparator) -> int: ...
    @overload
    @staticmethod
    def mismatch(arg0: list, arg1: int, arg2: int, arg3: list, arg4: int, arg5: int, arg6: Comparator) -> int: ...
