from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.util.Date import Date
from java.util.Locale import Locale
from java.util.TimeZone import TimeZone

class Calendar:
    ALL_STYLES: ClassVar[int]
    AM: ClassVar[int]
    AM_PM: ClassVar[int]
    APRIL: ClassVar[int]
    AUGUST: ClassVar[int]
    DATE: ClassVar[int]
    DAY_OF_MONTH: ClassVar[int]
    DAY_OF_WEEK: ClassVar[int]
    DAY_OF_WEEK_IN_MONTH: ClassVar[int]
    DAY_OF_YEAR: ClassVar[int]
    DECEMBER: ClassVar[int]
    DST_OFFSET: ClassVar[int]
    ERA: ClassVar[int]
    FEBRUARY: ClassVar[int]
    FIELD_COUNT: ClassVar[int]
    FRIDAY: ClassVar[int]
    HOUR: ClassVar[int]
    HOUR_OF_DAY: ClassVar[int]
    JANUARY: ClassVar[int]
    JULY: ClassVar[int]
    JUNE: ClassVar[int]
    LONG: ClassVar[int]
    LONG_FORMAT: ClassVar[int]
    LONG_STANDALONE: ClassVar[int]
    MARCH: ClassVar[int]
    MAY: ClassVar[int]
    MILLISECOND: ClassVar[int]
    MINUTE: ClassVar[int]
    MONDAY: ClassVar[int]
    MONTH: ClassVar[int]
    NARROW_FORMAT: ClassVar[int]
    NARROW_STANDALONE: ClassVar[int]
    NOVEMBER: ClassVar[int]
    OCTOBER: ClassVar[int]
    PM: ClassVar[int]
    SATURDAY: ClassVar[int]
    SECOND: ClassVar[int]
    SEPTEMBER: ClassVar[int]
    SHORT: ClassVar[int]
    SHORT_FORMAT: ClassVar[int]
    SHORT_STANDALONE: ClassVar[int]
    SUNDAY: ClassVar[int]
    THURSDAY: ClassVar[int]
    TUESDAY: ClassVar[int]
    UNDECIMBER: ClassVar[int]
    WEDNESDAY: ClassVar[int]
    WEEK_OF_MONTH: ClassVar[int]
    WEEK_OF_YEAR: ClassVar[int]
    YEAR: ClassVar[int]
    ZONE_OFFSET: ClassVar[int]
    areFieldsSet: bool
    fields: list[int]
    isSet: list[bool]
    isTimeSet: bool
    time: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: TimeZone, arg1: Locale) -> None: ...
    @overload
    @staticmethod
    def getInstance() -> "Calendar": ...
    @overload
    @staticmethod
    def getInstance(arg0: TimeZone) -> "Calendar": ...
    @overload
    @staticmethod
    def getInstance(arg0: Locale) -> "Calendar": ...
    @overload
    @staticmethod
    def getInstance(arg0: TimeZone, arg1: Locale) -> "Calendar": ...
    @staticmethod
    def getAvailableLocales() -> list[Locale]: ...
    def computeTime(self) -> None: ...
    def computeFields(self) -> None: ...
    def getTime(self) -> Date: ...
    def setTime(self, arg0: Date) -> None: ...
    def getTimeInMillis(self) -> int: ...
    def setTimeInMillis(self, arg0: int) -> None: ...
    def get(self, arg0: int) -> int: ...
    def internalGet(self, arg0: int) -> int: ...
    @overload
    def set(self, arg0: int, arg1: int) -> None: ...
    @overload
    def set(self, arg0: int, arg1: int, arg2: int) -> None: ...
    @overload
    def set(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def set(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> None: ...
    @overload
    def clear(self) -> None: ...
    @overload
    def clear(self, arg0: int) -> None: ...
    def isSet(self, arg0: int) -> bool: ...
    def getDisplayName(self, arg0: int, arg1: int, arg2: Locale) -> str: ...
    def getDisplayNames(self, arg0: int, arg1: int, arg2: Locale) -> dict: ...
    def complete(self) -> None: ...
    @staticmethod
    def getAvailableCalendarTypes() -> set: ...
    def getCalendarType(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def before(self, arg0: Any) -> bool: ...
    def after(self, arg0: Any) -> bool: ...
    def compareTo(self, arg0: "Calendar") -> int: ...
    def add(self, arg0: int, arg1: int) -> None: ...
    @overload
    def roll(self, arg0: int, arg1: bool) -> None: ...
    @overload
    def roll(self, arg0: int, arg1: int) -> None: ...
    def setTimeZone(self, arg0: TimeZone) -> None: ...
    def getTimeZone(self) -> TimeZone: ...
    def setLenient(self, arg0: bool) -> None: ...
    def isLenient(self) -> bool: ...
    def setFirstDayOfWeek(self, arg0: int) -> None: ...
    def getFirstDayOfWeek(self) -> int: ...
    def setMinimalDaysInFirstWeek(self, arg0: int) -> None: ...
    def getMinimalDaysInFirstWeek(self) -> int: ...
    def isWeekDateSupported(self) -> bool: ...
    def getWeekYear(self) -> int: ...
    def setWeekDate(self, arg0: int, arg1: int, arg2: int) -> None: ...
    def getWeeksInWeekYear(self) -> int: ...
    def getMinimum(self, arg0: int) -> int: ...
    def getMaximum(self, arg0: int) -> int: ...
    def getGreatestMinimum(self, arg0: int) -> int: ...
    def getLeastMaximum(self, arg0: int) -> int: ...
    def getActualMinimum(self, arg0: int) -> int: ...
    def getActualMaximum(self, arg0: int) -> int: ...
    def clone(self) -> Any: ...
    def toString(self) -> str: ...
    def toInstant(self) -> Instant: ...

    class Builder:
        def __init__(self) -> None: ...
        @overload
        def setInstant(self, arg0: int) -> "Builder": ...
        @overload
        def setInstant(self, arg0: Date) -> "Builder": ...
        def set(self, arg0: int, arg1: int) -> "Builder": ...
        def setFields(self, *arg0: int) -> "Builder": ...
        def setDate(self, arg0: int, arg1: int, arg2: int) -> "Builder": ...
        @overload
        def setTimeOfDay(self, arg0: int, arg1: int, arg2: int) -> "Builder": ...
        @overload
        def setTimeOfDay(self, arg0: int, arg1: int, arg2: int, arg3: int) -> "Builder": ...
        def setWeekDate(self, arg0: int, arg1: int, arg2: int) -> "Builder": ...
        def setTimeZone(self, arg0: TimeZone) -> "Builder": ...
        def setLenient(self, arg0: bool) -> "Builder": ...
        def setCalendarType(self, arg0: str) -> "Builder": ...
        def setLocale(self, arg0: Locale) -> "Builder": ...
        def setWeekDefinition(self, arg0: int, arg1: int) -> "Builder": ...
        def build(self) -> "Calendar": ...
