from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator

class Enumeration:
    def hasMoreElements(self) -> bool: ...
    def nextElement(self) -> Any: ...
    def asIterator(self) -> Iterator: ...
