from typing import Any, ClassVar, overload

class FormatFlagsConversionMismatchException:
    def __init__(self, arg0: str, arg1: str) -> None: ...
    def getFlags(self) -> str: ...
    def getConversion(self) -> str: ...
    def getMessage(self) -> str: ...
