from typing import Any, ClassVar, overload
from java.lang.Appendable import Appendable

class HexFormat:
    @staticmethod
    def of() -> "HexFormat": ...
    @staticmethod
    def ofDelimiter(arg0: str) -> "HexFormat": ...
    def withDelimiter(self, arg0: str) -> "HexFormat": ...
    def withPrefix(self, arg0: str) -> "HexFormat": ...
    def withSuffix(self, arg0: str) -> "HexFormat": ...
    def withUpperCase(self) -> "HexFormat": ...
    def withLowerCase(self) -> "HexFormat": ...
    def delimiter(self) -> str: ...
    def prefix(self) -> str: ...
    def suffix(self) -> str: ...
    def isUpperCase(self) -> bool: ...
    @overload
    def formatHex(self, arg0: list[int]) -> str: ...
    @overload
    def formatHex(self, arg0: list[int], arg1: int, arg2: int) -> str: ...
    @overload
    def formatHex(self, arg0: Appendable, arg1: list[int]) -> Appendable: ...
    @overload
    def formatHex(self, arg0: Appendable, arg1: list[int], arg2: int, arg3: int) -> Appendable: ...
    @overload
    def parseHex(self, arg0: str) -> list[int]: ...
    @overload
    def parseHex(self, arg0: str, arg1: int, arg2: int) -> list[int]: ...
    @overload
    def parseHex(self, arg0: list[str], arg1: int, arg2: int) -> list[int]: ...
    def toLowHexDigit(self, arg0: int) -> str: ...
    def toHighHexDigit(self, arg0: int) -> str: ...
    @overload
    def toHexDigits(self, arg0: Appendable, arg1: int) -> Appendable: ...
    @overload
    def toHexDigits(self, arg0: int) -> str: ...
    @overload
    def toHexDigits(self, arg0: str) -> str: ...
    @overload
    def toHexDigits(self, arg0: int) -> str: ...
    @overload
    def toHexDigits(self, arg0: int) -> str: ...
    @overload
    def toHexDigits(self, arg0: int) -> str: ...
    @overload
    def toHexDigits(self, arg0: int, arg1: int) -> str: ...
    @staticmethod
    def isHexDigit(arg0: int) -> bool: ...
    @staticmethod
    def fromHexDigit(arg0: int) -> int: ...
    @overload
    @staticmethod
    def fromHexDigits(arg0: str) -> int: ...
    @overload
    @staticmethod
    def fromHexDigits(arg0: str, arg1: int, arg2: int) -> int: ...
    @overload
    @staticmethod
    def fromHexDigitsToLong(arg0: str) -> int: ...
    @overload
    @staticmethod
    def fromHexDigitsToLong(arg0: str, arg1: int, arg2: int) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
