from typing import Any, ClassVar, overload

class IllegalFormatPrecisionException:
    def __init__(self, arg0: int) -> None: ...
    def getPrecision(self) -> int: ...
    def getMessage(self) -> str: ...
