from typing import Any, ClassVar, overload

class IllegalFormatConversionException:
    def __init__(self, arg0: str, arg1: type) -> None: ...
    def getConversion(self) -> str: ...
    def getArgumentClass(self) -> type: ...
    def getMessage(self) -> str: ...
