from typing import Any, ClassVar, overload

class IllegalFormatCodePointException:
    def __init__(self, arg0: int) -> None: ...
    def getCodePoint(self) -> int: ...
    def getMessage(self) -> str: ...
