from typing import Any, ClassVar, overload
from java.util.SequencedCollection import SequencedCollection
from java.util.SequencedMap import SequencedMap
from java.util.SequencedSet import SequencedSet
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BiFunction import BiFunction

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Entry:
    """Forward declaration for ``java.util.Map.Entry``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.util.Map.Entry')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/util/Map/Entry.html
    """
    ...

class LinkedHashMap:
    @overload
    def __init__(self, arg0: int, arg1: float) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: dict) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: float, arg2: bool) -> None: ...
    def putFirst(self, arg0: Any, arg1: Any) -> Any: ...
    def putLast(self, arg0: Any, arg1: Any) -> Any: ...
    def containsValue(self, arg0: Any) -> bool: ...
    def get(self, arg0: Any) -> Any: ...
    def getOrDefault(self, arg0: Any, arg1: Any) -> Any: ...
    def clear(self) -> None: ...
    def removeEldestEntry(self, arg0: Entry) -> bool: ...
    def keySet(self) -> set: ...
    def sequencedKeySet(self) -> SequencedSet: ...
    def values(self) -> list: ...
    def sequencedValues(self) -> SequencedCollection: ...
    def entrySet(self) -> set: ...
    def sequencedEntrySet(self) -> SequencedSet: ...
    def forEach(self, arg0: BiConsumer) -> None: ...
    def replaceAll(self, arg0: BiFunction) -> None: ...
    @staticmethod
    def newLinkedHashMap(arg0: int) -> dict: ...
    def reversed(self) -> SequencedMap: ...
