from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator
from java.util.Iterator import Iterator
from java.util.ListIterator import ListIterator
from java.util.Spliterator import Spliterator
from java.util.function.UnaryOperator import UnaryOperator

class List:
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def contains(self, arg0: Any) -> bool: ...
    def iterator(self) -> Iterator: ...
    @overload
    def toArray(self) -> list: ...
    @overload
    def toArray(self, arg0: list) -> list: ...
    @overload
    def add(self, arg0: Any) -> bool: ...
    @overload
    def add(self, arg0: int, arg1: Any) -> None: ...
    @overload
    def remove(self, arg0: Any) -> bool: ...
    @overload
    def remove(self, arg0: int) -> Any: ...
    def containsAll(self, arg0: list) -> bool: ...
    @overload
    def addAll(self, arg0: list) -> bool: ...
    @overload
    def addAll(self, arg0: int, arg1: list) -> bool: ...
    def removeAll(self, arg0: list) -> bool: ...
    def retainAll(self, arg0: list) -> bool: ...
    def replaceAll(self, arg0: UnaryOperator) -> None: ...
    def sort(self, arg0: Comparator) -> None: ...
    def clear(self) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def get(self, arg0: int) -> Any: ...
    def set(self, arg0: int, arg1: Any) -> Any: ...
    def indexOf(self, arg0: Any) -> int: ...
    def lastIndexOf(self, arg0: Any) -> int: ...
    @overload
    def listIterator(self) -> ListIterator: ...
    @overload
    def listIterator(self, arg0: int) -> ListIterator: ...
    def subList(self, arg0: int, arg1: int) -> list: ...
    def spliterator(self) -> Spliterator: ...
    def addFirst(self, arg0: Any) -> None: ...
    def addLast(self, arg0: Any) -> None: ...
    def getFirst(self) -> Any: ...
    def getLast(self) -> Any: ...
    def removeFirst(self) -> Any: ...
    def removeLast(self) -> Any: ...
    def reversed(self) -> list: ...
    @overload
    @staticmethod
    def of() -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any, arg2: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any, arg2: Any, arg3: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any, arg2: Any, arg3: Any, arg4: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any, arg2: Any, arg3: Any, arg4: Any, arg5: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any, arg2: Any, arg3: Any, arg4: Any, arg5: Any, arg6: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any, arg2: Any, arg3: Any, arg4: Any, arg5: Any, arg6: Any, arg7: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any, arg2: Any, arg3: Any, arg4: Any, arg5: Any, arg6: Any, arg7: Any, arg8: Any) -> list: ...
    @overload
    @staticmethod
    def of(arg0: Any, arg1: Any, arg2: Any, arg3: Any, arg4: Any, arg5: Any, arg6: Any, arg7: Any, arg8: Any, arg9: Any) -> list: ...
    @overload
    @staticmethod
    def of(*arg0: Any) -> list: ...
    @staticmethod
    def copyOf(arg0: list) -> list: ...
