from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator
from java.util.SortedSet import SortedSet

class NavigableSet:
    def lower(self, arg0: Any) -> Any: ...
    def floor(self, arg0: Any) -> Any: ...
    def ceiling(self, arg0: Any) -> Any: ...
    def higher(self, arg0: Any) -> Any: ...
    def pollFirst(self) -> Any: ...
    def pollLast(self) -> Any: ...
    def iterator(self) -> Iterator: ...
    def descendingSet(self) -> "NavigableSet": ...
    def descendingIterator(self) -> Iterator: ...
    @overload
    def subSet(self, arg0: Any, arg1: bool, arg2: Any, arg3: bool) -> "NavigableSet": ...
    @overload
    def subSet(self, arg0: Any, arg1: Any) -> SortedSet: ...
    @overload
    def headSet(self, arg0: Any, arg1: bool) -> "NavigableSet": ...
    @overload
    def headSet(self, arg0: Any) -> SortedSet: ...
    @overload
    def tailSet(self, arg0: Any, arg1: bool) -> "NavigableSet": ...
    @overload
    def tailSet(self, arg0: Any) -> SortedSet: ...
    def removeFirst(self) -> Any: ...
    def removeLast(self) -> Any: ...
    def reversed(self) -> "NavigableSet": ...
