from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.function.Consumer import Consumer
from java.util.function.Function import Function
from java.util.function.Predicate import Predicate
from java.util.function.Supplier import Supplier
from java.util.stream.Stream import Stream

class Optional:
    @staticmethod
    def empty() -> "Optional": ...
    @staticmethod
    def of(arg0: Any) -> "Optional": ...
    @staticmethod
    def ofNullable(arg0: Any) -> "Optional": ...
    def get(self) -> Any: ...
    def isPresent(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def ifPresent(self, arg0: Consumer) -> None: ...
    def ifPresentOrElse(self, arg0: Consumer, arg1: Runnable) -> None: ...
    def filter(self, arg0: Predicate) -> "Optional": ...
    def map(self, arg0: Function) -> "Optional": ...
    def flatMap(self, arg0: Function) -> "Optional": ...
    def or_(self, arg0: Supplier) -> "Optional": ...
    def stream(self) -> Stream: ...
    def orElse(self, arg0: Any) -> Any: ...
    def orElseGet(self, arg0: Supplier) -> Any: ...
    @overload
    def orElseThrow(self) -> Any: ...
    @overload
    def orElseThrow(self, arg0: Supplier) -> Any: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
