from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.function.IntConsumer import IntConsumer
from java.util.function.IntSupplier import IntSupplier
from java.util.function.Supplier import Supplier
from java.util.stream.IntStream import IntStream

class OptionalInt:
    @staticmethod
    def empty() -> "OptionalInt": ...
    @staticmethod
    def of(arg0: int) -> "OptionalInt": ...
    def getAsInt(self) -> int: ...
    def isPresent(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def ifPresent(self, arg0: IntConsumer) -> None: ...
    def ifPresentOrElse(self, arg0: IntConsumer, arg1: Runnable) -> None: ...
    def stream(self) -> IntStream: ...
    def orElse(self, arg0: int) -> int: ...
    def orElseGet(self, arg0: IntSupplier) -> int: ...
    @overload
    def orElseThrow(self) -> int: ...
    @overload
    def orElseThrow(self, arg0: Supplier) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
