from typing import Any, ClassVar, overload
from java.util.function.Consumer import Consumer
from java.util.function.DoubleConsumer import DoubleConsumer
from java.util.function.IntConsumer import IntConsumer
from java.util.function.LongConsumer import LongConsumer

class PrimitiveIterator:
    def forEachRemaining(self, arg0: Any) -> None: ...

    class OfDouble:
        def nextDouble(self) -> float: ...
        @overload
        def forEachRemaining(self, arg0: DoubleConsumer) -> None: ...
        @overload
        def forEachRemaining(self, arg0: Consumer) -> None: ...
        def next(self) -> float: ...

    class OfInt:
        def nextInt(self) -> int: ...
        @overload
        def forEachRemaining(self, arg0: IntConsumer) -> None: ...
        @overload
        def forEachRemaining(self, arg0: Consumer) -> None: ...
        def next(self) -> int: ...

    class OfLong:
        def nextLong(self) -> int: ...
        @overload
        def forEachRemaining(self, arg0: LongConsumer) -> None: ...
        @overload
        def forEachRemaining(self, arg0: Consumer) -> None: ...
        def next(self) -> int: ...
