from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.io.PrintStream import PrintStream
from java.io.PrintWriter import PrintWriter
from java.io.Reader import Reader
from java.io.Writer import Writer
from java.nio.charset.Charset import Charset
from java.util.Enumeration import Enumeration
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BiFunction import BiFunction
from java.util.function.Function import Function

class Properties:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: "Properties") -> None: ...
    def setProperty(self, arg0: str, arg1: str) -> Any: ...
    @overload
    def load(self, arg0: Reader) -> None: ...
    @overload
    def load(self, arg0: InputStream) -> None: ...
    def save(self, arg0: OutputStream, arg1: str) -> None: ...
    @overload
    def store(self, arg0: Writer, arg1: str) -> None: ...
    @overload
    def store(self, arg0: OutputStream, arg1: str) -> None: ...
    def loadFromXML(self, arg0: InputStream) -> None: ...
    @overload
    def storeToXML(self, arg0: OutputStream, arg1: str) -> None: ...
    @overload
    def storeToXML(self, arg0: OutputStream, arg1: str, arg2: str) -> None: ...
    @overload
    def storeToXML(self, arg0: OutputStream, arg1: str, arg2: Charset) -> None: ...
    @overload
    def getProperty(self, arg0: str) -> str: ...
    @overload
    def getProperty(self, arg0: str, arg1: str) -> str: ...
    def propertyNames(self) -> Enumeration: ...
    def stringPropertyNames(self) -> set: ...
    @overload
    def list(self, arg0: PrintStream) -> None: ...
    @overload
    def list(self, arg0: PrintWriter) -> None: ...
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def keys(self) -> Enumeration: ...
    def elements(self) -> Enumeration: ...
    def contains(self, arg0: Any) -> bool: ...
    def containsValue(self, arg0: Any) -> bool: ...
    def containsKey(self, arg0: Any) -> bool: ...
    def get(self, arg0: Any) -> Any: ...
    def put(self, arg0: Any, arg1: Any) -> Any: ...
    @overload
    def remove(self, arg0: Any) -> Any: ...
    @overload
    def remove(self, arg0: Any, arg1: Any) -> bool: ...
    def putAll(self, arg0: dict) -> None: ...
    def clear(self) -> None: ...
    def toString(self) -> str: ...
    def keySet(self) -> set: ...
    def values(self) -> list: ...
    def entrySet(self) -> set: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getOrDefault(self, arg0: Any, arg1: Any) -> Any: ...
    def forEach(self, arg0: BiConsumer) -> None: ...
    def replaceAll(self, arg0: BiFunction) -> None: ...
    def putIfAbsent(self, arg0: Any, arg1: Any) -> Any: ...
    @overload
    def replace(self, arg0: Any, arg1: Any, arg2: Any) -> bool: ...
    @overload
    def replace(self, arg0: Any, arg1: Any) -> Any: ...
    def computeIfAbsent(self, arg0: Any, arg1: Function) -> Any: ...
    def computeIfPresent(self, arg0: Any, arg1: BiFunction) -> Any: ...
    def compute(self, arg0: Any, arg1: BiFunction) -> Any: ...
    def merge(self, arg0: Any, arg1: Any, arg2: BiFunction) -> Any: ...
    def rehash(self) -> None: ...
    def clone(self) -> Any: ...
