from typing import Any, ClassVar, overload

class Queue:
    def add(self, arg0: Any) -> bool: ...
    def offer(self, arg0: Any) -> bool: ...
    def remove(self) -> Any: ...
    def poll(self) -> Any: ...
    def element(self) -> Any: ...
    def peek(self) -> Any: ...
