from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator

class SortedMap:
    def comparator(self) -> Comparator: ...
    def subMap(self, arg0: Any, arg1: Any) -> "SortedMap": ...
    def headMap(self, arg0: Any) -> "SortedMap": ...
    def tailMap(self, arg0: Any) -> "SortedMap": ...
    def firstKey(self) -> Any: ...
    def lastKey(self) -> Any: ...
    def keySet(self) -> set: ...
    def values(self) -> list: ...
    def entrySet(self) -> set: ...
    def putFirst(self, arg0: Any, arg1: Any) -> Any: ...
    def putLast(self, arg0: Any, arg1: Any) -> Any: ...
    def reversed(self) -> "SortedMap": ...
