from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator
from java.util.Spliterator import Spliterator

class SortedSet:
    def comparator(self) -> Comparator: ...
    def subSet(self, arg0: Any, arg1: Any) -> "SortedSet": ...
    def headSet(self, arg0: Any) -> "SortedSet": ...
    def tailSet(self, arg0: Any) -> "SortedSet": ...
    def first(self) -> Any: ...
    def last(self) -> Any: ...
    def spliterator(self) -> Spliterator: ...
    def addFirst(self, arg0: Any) -> None: ...
    def addLast(self, arg0: Any) -> None: ...
    def getFirst(self) -> Any: ...
    def getLast(self) -> Any: ...
    def removeFirst(self) -> Any: ...
    def removeLast(self) -> Any: ...
    def reversed(self) -> "SortedSet": ...
