from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator
from java.util.function.Consumer import Consumer
from java.util.function.DoubleConsumer import DoubleConsumer
from java.util.function.IntConsumer import IntConsumer
from java.util.function.LongConsumer import LongConsumer

class Spliterator:
    CONCURRENT: ClassVar[int]
    DISTINCT: ClassVar[int]
    IMMUTABLE: ClassVar[int]
    NONNULL: ClassVar[int]
    ORDERED: ClassVar[int]
    SIZED: ClassVar[int]
    SORTED: ClassVar[int]
    SUBSIZED: ClassVar[int]
    def tryAdvance(self, arg0: Consumer) -> bool: ...
    def forEachRemaining(self, arg0: Consumer) -> None: ...
    def trySplit(self) -> "Spliterator": ...
    def estimateSize(self) -> int: ...
    def getExactSizeIfKnown(self) -> int: ...
    def characteristics(self) -> int: ...
    def hasCharacteristics(self, arg0: int) -> bool: ...
    def getComparator(self) -> Comparator: ...

    class OfDouble:
        def trySplit(self) -> "OfDouble": ...
        @overload
        def tryAdvance(self, arg0: DoubleConsumer) -> bool: ...
        @overload
        def tryAdvance(self, arg0: Consumer) -> bool: ...
        @overload
        def forEachRemaining(self, arg0: DoubleConsumer) -> None: ...
        @overload
        def forEachRemaining(self, arg0: Consumer) -> None: ...

    class OfInt:
        def trySplit(self) -> "OfInt": ...
        @overload
        def tryAdvance(self, arg0: IntConsumer) -> bool: ...
        @overload
        def tryAdvance(self, arg0: Consumer) -> bool: ...
        @overload
        def forEachRemaining(self, arg0: IntConsumer) -> None: ...
        @overload
        def forEachRemaining(self, arg0: Consumer) -> None: ...

    class OfLong:
        def trySplit(self) -> "OfLong": ...
        @overload
        def tryAdvance(self, arg0: LongConsumer) -> bool: ...
        @overload
        def tryAdvance(self, arg0: Consumer) -> bool: ...
        @overload
        def forEachRemaining(self, arg0: LongConsumer) -> None: ...
        @overload
        def forEachRemaining(self, arg0: Consumer) -> None: ...

    class OfPrimitive:
        def trySplit(self) -> "OfPrimitive": ...
        def tryAdvance(self, arg0: Any) -> bool: ...
        def forEachRemaining(self, arg0: Any) -> None: ...
