from typing import Any, ClassVar, overload
from java.util.stream.DoubleStream import DoubleStream
from java.util.stream.IntStream import IntStream
from java.util.stream.LongStream import LongStream
from java.util.stream.Stream import Stream

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class SplittableGenerator:
    """Forward declaration for ``java.util.random.RandomGenerator.SplittableGenerator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.util.random.RandomGenerator.SplittableGenerator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/util/random/RandomGenerator/SplittableGenerator.html
    """
    ...

class SplittableRandom:
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def split(self) -> "SplittableRandom": ...
    @overload
    def split(self, arg0: SplittableGenerator) -> "SplittableRandom": ...
    def nextInt(self) -> int: ...
    def nextLong(self) -> int: ...
    def nextBytes(self, arg0: list[int]) -> None: ...
    @overload
    def splits(self) -> Stream: ...
    @overload
    def splits(self, arg0: int) -> Stream: ...
    @overload
    def splits(self, arg0: SplittableGenerator) -> Stream: ...
    @overload
    def splits(self, arg0: int, arg1: SplittableGenerator) -> Stream: ...
    @overload
    def ints(self, arg0: int) -> IntStream: ...
    @overload
    def ints(self) -> IntStream: ...
    @overload
    def ints(self, arg0: int, arg1: int, arg2: int) -> IntStream: ...
    @overload
    def ints(self, arg0: int, arg1: int) -> IntStream: ...
    @overload
    def longs(self, arg0: int) -> LongStream: ...
    @overload
    def longs(self) -> LongStream: ...
    @overload
    def longs(self, arg0: int, arg1: int, arg2: int) -> LongStream: ...
    @overload
    def longs(self, arg0: int, arg1: int) -> LongStream: ...
    @overload
    def doubles(self, arg0: int) -> DoubleStream: ...
    @overload
    def doubles(self) -> DoubleStream: ...
    @overload
    def doubles(self, arg0: int, arg1: float, arg2: float) -> DoubleStream: ...
    @overload
    def doubles(self, arg0: float, arg1: float) -> DoubleStream: ...
