from typing import Any, ClassVar, overload

class StringJoiner:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, arg2: str) -> None: ...
    def setEmptyValue(self, arg0: str) -> "StringJoiner": ...
    def toString(self) -> str: ...
    def add(self, arg0: str) -> "StringJoiner": ...
    def merge(self, arg0: "StringJoiner") -> "StringJoiner": ...
    def length(self) -> int: ...
