from typing import Any, ClassVar, overload
from java.time.ZoneId import ZoneId
from java.util.Date import Date
from java.util.Locale import Locale

class TimeZone:
    LONG: ClassVar[int]
    SHORT: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    def getOffset(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> int: ...
    @overload
    def getOffset(self, arg0: int) -> int: ...
    def setRawOffset(self, arg0: int) -> None: ...
    def getRawOffset(self) -> int: ...
    def getID(self) -> str: ...
    def setID(self, arg0: str) -> None: ...
    @overload
    def getDisplayName(self) -> str: ...
    @overload
    def getDisplayName(self, arg0: Locale) -> str: ...
    @overload
    def getDisplayName(self, arg0: bool, arg1: int) -> str: ...
    @overload
    def getDisplayName(self, arg0: bool, arg1: int, arg2: Locale) -> str: ...
    def getDSTSavings(self) -> int: ...
    def useDaylightTime(self) -> bool: ...
    def observesDaylightTime(self) -> bool: ...
    def inDaylightTime(self, arg0: Date) -> bool: ...
    @overload
    @staticmethod
    def getTimeZone(arg0: str) -> "TimeZone": ...
    @overload
    @staticmethod
    def getTimeZone(arg0: ZoneId) -> "TimeZone": ...
    def toZoneId(self) -> ZoneId: ...
    @overload
    @staticmethod
    def getAvailableIDs(arg0: int) -> list[str]: ...
    @overload
    @staticmethod
    def getAvailableIDs() -> list[str]: ...
    @staticmethod
    def getDefault() -> "TimeZone": ...
    @staticmethod
    def setDefault(arg0: "TimeZone") -> None: ...
    def hasSameRules(self, arg0: "TimeZone") -> bool: ...
    def clone(self) -> Any: ...
