from typing import Any, ClassVar, overload
from java.util.Date import Date
from java.util.TimerTask import TimerTask

class Timer:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: bool) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: bool) -> None: ...
    @overload
    def schedule(self, arg0: TimerTask, arg1: int) -> None: ...
    @overload
    def schedule(self, arg0: TimerTask, arg1: Date) -> None: ...
    @overload
    def schedule(self, arg0: TimerTask, arg1: int, arg2: int) -> None: ...
    @overload
    def schedule(self, arg0: TimerTask, arg1: Date, arg2: int) -> None: ...
    @overload
    def scheduleAtFixedRate(self, arg0: TimerTask, arg1: int, arg2: int) -> None: ...
    @overload
    def scheduleAtFixedRate(self, arg0: TimerTask, arg1: Date, arg2: int) -> None: ...
    def cancel(self) -> None: ...
    def purge(self) -> int: ...
