from typing import Any, ClassVar, overload
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BiFunction import BiFunction

class WeakHashMap:
    @overload
    def __init__(self, arg0: int, arg1: float) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: dict) -> None: ...
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def get(self, arg0: Any) -> Any: ...
    def containsKey(self, arg0: Any) -> bool: ...
    def put(self, arg0: Any, arg1: Any) -> Any: ...
    def putAll(self, arg0: dict) -> None: ...
    def remove(self, arg0: Any) -> Any: ...
    def clear(self) -> None: ...
    def containsValue(self, arg0: Any) -> bool: ...
    def keySet(self) -> set: ...
    def values(self) -> list: ...
    def entrySet(self) -> set: ...
    def forEach(self, arg0: BiConsumer) -> None: ...
    def replaceAll(self, arg0: BiFunction) -> None: ...
