from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class FormWidgetInfo:
    CREATOR: ClassVar[Creator]
    WIDGET_TYPE_CHECKBOX: ClassVar[int]
    WIDGET_TYPE_COMBOBOX: ClassVar[int]
    WIDGET_TYPE_LISTBOX: ClassVar[int]
    WIDGET_TYPE_PUSHBUTTON: ClassVar[int]
    WIDGET_TYPE_RADIOBUTTON: ClassVar[int]
    WIDGET_TYPE_SIGNATURE: ClassVar[int]
    WIDGET_TYPE_TEXTFIELD: ClassVar[int]
    WIDGET_TYPE_UNKNOWN: ClassVar[int]
    def getWidgetType(self) -> int: ...
    def getWidgetIndex(self) -> int: ...
    def getWidgetRect(self) -> Rect: ...
    def isReadOnly(self) -> bool: ...
    def getTextValue(self) -> str: ...
    def getAccessibilityLabel(self) -> str: ...
    def isEditableText(self) -> bool: ...
    def isMultiSelect(self) -> bool: ...
    def isMultiLineText(self) -> bool: ...
    def getMaxLength(self) -> int: ...
    def getFontSize(self) -> float: ...
    def getListItems(self) -> list: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class Builder:
        def __init__(self, arg0: int, arg1: int, arg2: Rect, arg3: str, arg4: str) -> None: ...
        def setReadOnly(self, arg0: bool) -> "Builder": ...
        def setEditableText(self, arg0: bool) -> "Builder": ...
        def setMultiSelect(self, arg0: bool) -> "Builder": ...
        def setMultiLineText(self, arg0: bool) -> "Builder": ...
        def setMaxLength(self, arg0: int) -> "Builder": ...
        def setFontSize(self, arg0: float) -> "Builder": ...
        def setListItems(self, arg0: list) -> "Builder": ...
        def build(self) -> "FormWidgetInfo": ...
