from typing import Any, ClassVar, overload
from android.app.WallpaperColors import WallpaperColors
from android.content.Context import Context
from android.content.Intent import Intent
from android.os.Bundle import Bundle
from android.os.IBinder import IBinder
from android.view.MotionEvent import MotionEvent
from android.view.SurfaceHolder import SurfaceHolder
from android.view.WindowInsets import WindowInsets
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class WallpaperService:
    SERVICE_INTERFACE: ClassVar[str]
    SERVICE_META_DATA: ClassVar[str]
    def __init__(self) -> None: ...
    def onCreate(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onCreateEngine(self) -> "Engine": ...
    def dump(self, arg0: FileDescriptor, arg1: PrintWriter, arg2: list[str]) -> None: ...

    class Engine:
        def __init__(self, arg0: "WallpaperService") -> None: ...
        def getSurfaceHolder(self) -> SurfaceHolder: ...
        def getWallpaperFlags(self) -> int: ...
        def getDesiredMinimumWidth(self) -> int: ...
        def getDesiredMinimumHeight(self) -> int: ...
        def isVisible(self) -> bool: ...
        def isPreview(self) -> bool: ...
        def setTouchEventsEnabled(self, arg0: bool) -> None: ...
        def setOffsetNotificationsEnabled(self, arg0: bool) -> None: ...
        def onCreate(self, arg0: SurfaceHolder) -> None: ...
        def onDestroy(self) -> None: ...
        def onVisibilityChanged(self, arg0: bool) -> None: ...
        def onApplyWindowInsets(self, arg0: WindowInsets) -> None: ...
        def onTouchEvent(self, arg0: MotionEvent) -> None: ...
        def onOffsetsChanged(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: int, arg5: int) -> None: ...
        def onCommand(self, arg0: str, arg1: int, arg2: int, arg3: int, arg4: Bundle, arg5: bool) -> Bundle: ...
        def onDesiredSizeChanged(self, arg0: int, arg1: int) -> None: ...
        def onSurfaceChanged(self, arg0: SurfaceHolder, arg1: int, arg2: int, arg3: int) -> None: ...
        def onSurfaceRedrawNeeded(self, arg0: SurfaceHolder) -> None: ...
        def onSurfaceCreated(self, arg0: SurfaceHolder) -> None: ...
        def onSurfaceDestroyed(self, arg0: SurfaceHolder) -> None: ...
        def onWallpaperFlagsChanged(self, arg0: int) -> None: ...
        def onZoomChanged(self, arg0: float) -> None: ...
        def notifyColorsChanged(self) -> None: ...
        def onComputeColors(self) -> WallpaperColors: ...
        def dump(self, arg0: str, arg1: FileDescriptor, arg2: PrintWriter, arg3: list[str]) -> None: ...
        def getDisplayContext(self) -> Context: ...
