from typing import Any, ClassVar, overload

class PasswordCallback:
    def __init__(self, arg0: str, arg1: bool) -> None: ...
    def getPrompt(self) -> str: ...
    def isEchoOn(self) -> bool: ...
    def setPassword(self, arg0: list[str]) -> None: ...
    def getPassword(self) -> list[str]: ...
    def clearPassword(self) -> None: ...
