from typing import Any, ClassVar, overload
from javax.security.auth.callback.Callback import Callback

class UnsupportedCallbackException:
    @overload
    def __init__(self, arg0: Callback) -> None: ...
    @overload
    def __init__(self, arg0: Callback, arg1: str) -> None: ...
    def getCallback(self) -> Callback: ...
