from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from java.util.Date import Date
from javax.security.auth.x500.X500Principal import X500Principal

class KeyGenParameterSpec:
    def getKeystoreAlias(self) -> str: ...
    def getKeySize(self) -> int: ...
    def getAlgorithmParameterSpec(self) -> AlgorithmParameterSpec: ...
    def getCertificateSubject(self) -> X500Principal: ...
    def getCertificateSerialNumber(self) -> BigInteger: ...
    def getCertificateNotBefore(self) -> Date: ...
    def getCertificateNotAfter(self) -> Date: ...
    def getKeyValidityStart(self) -> Date: ...
    def getKeyValidityForConsumptionEnd(self) -> Date: ...
    def getKeyValidityForOriginationEnd(self) -> Date: ...
    def getPurposes(self) -> int: ...
    def getDigests(self) -> list[str]: ...
    def isDigestsSpecified(self) -> bool: ...
    def getMgf1Digests(self) -> set: ...
    def isMgf1DigestsSpecified(self) -> bool: ...
    def getEncryptionPaddings(self) -> list[str]: ...
    def getSignaturePaddings(self) -> list[str]: ...
    def getBlockModes(self) -> list[str]: ...
    def isRandomizedEncryptionRequired(self) -> bool: ...
    def isUserAuthenticationRequired(self) -> bool: ...
    def isUserConfirmationRequired(self) -> bool: ...
    def getUserAuthenticationValidityDurationSeconds(self) -> int: ...
    def getUserAuthenticationType(self) -> int: ...
    def isUserPresenceRequired(self) -> bool: ...
    def getAttestationChallenge(self) -> list[int]: ...
    def isDevicePropertiesAttestationIncluded(self) -> bool: ...
    def isUserAuthenticationValidWhileOnBody(self) -> bool: ...
    def isInvalidatedByBiometricEnrollment(self) -> bool: ...
    def isStrongBoxBacked(self) -> bool: ...
    def isUnlockedDeviceRequired(self) -> bool: ...
    def getMaxUsageCount(self) -> int: ...
    def getAttestKeyAlias(self) -> str: ...

    class Builder:
        def __init__(self, arg0: str, arg1: int) -> None: ...
        def setKeySize(self, arg0: int) -> "Builder": ...
        def setAlgorithmParameterSpec(self, arg0: AlgorithmParameterSpec) -> "Builder": ...
        def setCertificateSubject(self, arg0: X500Principal) -> "Builder": ...
        def setCertificateSerialNumber(self, arg0: BigInteger) -> "Builder": ...
        def setCertificateNotBefore(self, arg0: Date) -> "Builder": ...
        def setCertificateNotAfter(self, arg0: Date) -> "Builder": ...
        def setKeyValidityStart(self, arg0: Date) -> "Builder": ...
        def setKeyValidityEnd(self, arg0: Date) -> "Builder": ...
        def setKeyValidityForOriginationEnd(self, arg0: Date) -> "Builder": ...
        def setKeyValidityForConsumptionEnd(self, arg0: Date) -> "Builder": ...
        def setDigests(self, *arg0: str) -> "Builder": ...
        def setMgf1Digests(self, *arg0: str) -> "Builder": ...
        def setEncryptionPaddings(self, *arg0: str) -> "Builder": ...
        def setSignaturePaddings(self, *arg0: str) -> "Builder": ...
        def setBlockModes(self, *arg0: str) -> "Builder": ...
        def setRandomizedEncryptionRequired(self, arg0: bool) -> "Builder": ...
        def setUserAuthenticationRequired(self, arg0: bool) -> "Builder": ...
        def setUserConfirmationRequired(self, arg0: bool) -> "Builder": ...
        def setUserAuthenticationValidityDurationSeconds(self, arg0: int) -> "Builder": ...
        def setUserAuthenticationParameters(self, arg0: int, arg1: int) -> "Builder": ...
        def setUserPresenceRequired(self, arg0: bool) -> "Builder": ...
        def setAttestationChallenge(self, arg0: list[int]) -> "Builder": ...
        def setDevicePropertiesAttestationIncluded(self, arg0: bool) -> "Builder": ...
        def setUserAuthenticationValidWhileOnBody(self, arg0: bool) -> "Builder": ...
        def setInvalidatedByBiometricEnrollment(self, arg0: bool) -> "Builder": ...
        def setIsStrongBoxBacked(self, arg0: bool) -> "Builder": ...
        def setUnlockedDeviceRequired(self, arg0: bool) -> "Builder": ...
        def setMaxUsageCount(self, arg0: int) -> "Builder": ...
        def setAttestKeyAlias(self, arg0: str) -> "Builder": ...
        def build(self) -> "KeyGenParameterSpec": ...
