from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Bitmap import Bitmap
from android.hardware.biometrics.PromptContentView import PromptContentView
from android.os.CancellationSignal import CancellationSignal
from android.security.identity.IdentityCredential import IdentityCredential
from android.security.identity.PresentationSession import PresentationSession
from java.security.Signature import Signature
from java.util.concurrent.Executor import Executor
from javax.crypto.Cipher import Cipher
from javax.crypto.Mac import Mac

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class OnClickListener:
    """Forward declaration for ``android.content.DialogInterface.OnClickListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.DialogInterface.OnClickListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/DialogInterface/OnClickListener
    """
    ...

class BiometricPrompt:
    AUTHENTICATION_RESULT_TYPE_BIOMETRIC: ClassVar[int]
    AUTHENTICATION_RESULT_TYPE_DEVICE_CREDENTIAL: ClassVar[int]
    BIOMETRIC_ACQUIRED_GOOD: ClassVar[int]
    BIOMETRIC_ACQUIRED_IMAGER_DIRTY: ClassVar[int]
    BIOMETRIC_ACQUIRED_INSUFFICIENT: ClassVar[int]
    BIOMETRIC_ACQUIRED_PARTIAL: ClassVar[int]
    BIOMETRIC_ACQUIRED_TOO_FAST: ClassVar[int]
    BIOMETRIC_ACQUIRED_TOO_SLOW: ClassVar[int]
    BIOMETRIC_ERROR_CANCELED: ClassVar[int]
    BIOMETRIC_ERROR_HW_NOT_PRESENT: ClassVar[int]
    BIOMETRIC_ERROR_HW_UNAVAILABLE: ClassVar[int]
    BIOMETRIC_ERROR_LOCKOUT: ClassVar[int]
    BIOMETRIC_ERROR_LOCKOUT_PERMANENT: ClassVar[int]
    BIOMETRIC_ERROR_NO_BIOMETRICS: ClassVar[int]
    BIOMETRIC_ERROR_NO_DEVICE_CREDENTIAL: ClassVar[int]
    BIOMETRIC_ERROR_NO_SPACE: ClassVar[int]
    BIOMETRIC_ERROR_SECURITY_UPDATE_REQUIRED: ClassVar[int]
    BIOMETRIC_ERROR_TIMEOUT: ClassVar[int]
    BIOMETRIC_ERROR_UNABLE_TO_PROCESS: ClassVar[int]
    BIOMETRIC_ERROR_USER_CANCELED: ClassVar[int]
    BIOMETRIC_ERROR_VENDOR: ClassVar[int]
    BIOMETRIC_NO_AUTHENTICATION: ClassVar[int]
    def getLogoRes(self) -> int: ...
    def getLogoBitmap(self) -> Bitmap: ...
    def getLogoDescription(self) -> str: ...
    def getTitle(self) -> str: ...
    def getSubtitle(self) -> str: ...
    def getDescription(self) -> str: ...
    def getContentView(self) -> PromptContentView: ...
    def getNegativeButtonText(self) -> str: ...
    def isConfirmationRequired(self) -> bool: ...
    def getAllowedAuthenticators(self) -> int: ...
    @overload
    def authenticate(self, arg0: "CryptoObject", arg1: CancellationSignal, arg2: Executor, arg3: "AuthenticationCallback") -> None: ...
    @overload
    def authenticate(self, arg0: CancellationSignal, arg1: Executor, arg2: "AuthenticationCallback") -> None: ...

    class AuthenticationCallback:
        def __init__(self) -> None: ...
        def onAuthenticationError(self, arg0: int, arg1: str) -> None: ...
        def onAuthenticationHelp(self, arg0: int, arg1: str) -> None: ...
        def onAuthenticationSucceeded(self, arg0: "AuthenticationResult") -> None: ...
        def onAuthenticationFailed(self) -> None: ...

    class AuthenticationResult:
        def getCryptoObject(self) -> "CryptoObject": ...
        def getAuthenticationType(self) -> int: ...

    class Builder:
        def __init__(self, arg0: Context) -> None: ...
        def setLogoRes(self, arg0: int) -> "Builder": ...
        def setLogoBitmap(self, arg0: Bitmap) -> "Builder": ...
        def setLogoDescription(self, arg0: str) -> "Builder": ...
        def setTitle(self, arg0: str) -> "Builder": ...
        def setSubtitle(self, arg0: str) -> "Builder": ...
        def setDescription(self, arg0: str) -> "Builder": ...
        def setContentView(self, arg0: PromptContentView) -> "Builder": ...
        def setNegativeButton(self, arg0: str, arg1: Executor, arg2: OnClickListener) -> "Builder": ...
        def setConfirmationRequired(self, arg0: bool) -> "Builder": ...
        def setDeviceCredentialAllowed(self, arg0: bool) -> "Builder": ...
        def setAllowedAuthenticators(self, arg0: int) -> "Builder": ...
        def build(self) -> "BiometricPrompt": ...

    class CryptoObject:
        @overload
        def __init__(self, arg0: Signature) -> None: ...
        @overload
        def __init__(self, arg0: Cipher) -> None: ...
        @overload
        def __init__(self, arg0: Mac) -> None: ...
        @overload
        def __init__(self, arg0: IdentityCredential) -> None: ...
        @overload
        def __init__(self, arg0: PresentationSession) -> None: ...
        @overload
        def __init__(self, arg0: int) -> None: ...
        def getSignature(self) -> Signature: ...
        def getCipher(self) -> Cipher: ...
        def getMac(self) -> Mac: ...
        def getIdentityCredential(self) -> IdentityCredential: ...
        def getPresentationSession(self) -> PresentationSession: ...
        def getOperationHandle(self) -> int: ...
