from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream

class BufferedOutputStream:
    buf: list[int]
    count: int
    @overload
    def __init__(self, arg0: OutputStream) -> None: ...
    @overload
    def __init__(self, arg0: OutputStream, arg1: int) -> None: ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    def flush(self) -> None: ...
