from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream

class BufferedInputStream:
    count: int
    marklimit: int
    markpos: int
    pos: int
    @overload
    def __init__(self, arg0: InputStream) -> None: ...
    @overload
    def __init__(self, arg0: InputStream, arg1: int) -> None: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    def skip(self, arg0: int) -> int: ...
    def available(self) -> int: ...
    def mark(self, arg0: int) -> None: ...
    def reset(self) -> None: ...
    def markSupported(self) -> bool: ...
    def close(self) -> None: ...
