from typing import Any, ClassVar, overload
from java.io.Writer import Writer

class BufferedWriter:
    @overload
    def __init__(self, arg0: Writer) -> None: ...
    @overload
    def __init__(self, arg0: Writer, arg1: int) -> None: ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    @overload
    def write(self, arg0: str, arg1: int, arg2: int) -> None: ...
    def newLine(self) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
