from typing import Any, ClassVar, overload
from java.nio.CharBuffer import CharBuffer

class CharArrayReader:
    buf: list[str]
    count: int
    markedPos: int
    pos: int
    @overload
    def __init__(self, arg0: list[str]) -> None: ...
    @overload
    def __init__(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[str], arg1: int, arg2: int) -> int: ...
    @overload
    def read(self, arg0: CharBuffer) -> int: ...
    def skip(self, arg0: int) -> int: ...
    def ready(self) -> bool: ...
    def markSupported(self) -> bool: ...
    def mark(self, arg0: int) -> None: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...
