from typing import Any, ClassVar, overload
from java.io.Writer import Writer

class CharArrayWriter:
    buf: list[str]
    count: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    @overload
    def write(self, arg0: str, arg1: int, arg2: int) -> None: ...
    def writeTo(self, arg0: Writer) -> None: ...
    @overload
    def append(self, arg0: str) -> "CharArrayWriter": ...
    @overload
    def append(self, arg0: str, arg1: int, arg2: int) -> "CharArrayWriter": ...
    @overload
    def append(self, arg0: str) -> "CharArrayWriter": ...
    def reset(self) -> None: ...
    def toCharArray(self) -> list[str]: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
