from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.FileDescriptor import FileDescriptor
from java.nio.charset.Charset import Charset

class FileReader:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: File) -> None: ...
    @overload
    def __init__(self, arg0: FileDescriptor) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: Charset) -> None: ...
    @overload
    def __init__(self, arg0: File, arg1: Charset) -> None: ...
