from typing import Any, ClassVar, overload
from java.io.FileFilter import FileFilter
from java.io.FilenameFilter import FilenameFilter
from java.net.URI import URI
from java.net.URL import URL
from java.nio.file.Path import Path

class File:
    pathSeparator: ClassVar[str]
    pathSeparatorChar: ClassVar[str]
    separator: ClassVar[str]
    separatorChar: ClassVar[str]
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: "File", arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: URI) -> None: ...
    def getName(self) -> str: ...
    def getParent(self) -> str: ...
    def getParentFile(self) -> "File": ...
    def getPath(self) -> str: ...
    def isAbsolute(self) -> bool: ...
    def getAbsolutePath(self) -> str: ...
    def getAbsoluteFile(self) -> "File": ...
    def getCanonicalPath(self) -> str: ...
    def getCanonicalFile(self) -> "File": ...
    def toURL(self) -> URL: ...
    def toURI(self) -> URI: ...
    def canRead(self) -> bool: ...
    def canWrite(self) -> bool: ...
    def exists(self) -> bool: ...
    def isDirectory(self) -> bool: ...
    def isFile(self) -> bool: ...
    def isHidden(self) -> bool: ...
    def lastModified(self) -> int: ...
    def length(self) -> int: ...
    def createNewFile(self) -> bool: ...
    def delete(self) -> bool: ...
    def deleteOnExit(self) -> None: ...
    @overload
    def list(self) -> list[str]: ...
    @overload
    def list(self, arg0: FilenameFilter) -> list[str]: ...
    @overload
    def listFiles(self) -> list["File"]: ...
    @overload
    def listFiles(self, arg0: FilenameFilter) -> list["File"]: ...
    @overload
    def listFiles(self, arg0: FileFilter) -> list["File"]: ...
    def mkdir(self) -> bool: ...
    def mkdirs(self) -> bool: ...
    def renameTo(self, arg0: "File") -> bool: ...
    def setLastModified(self, arg0: int) -> bool: ...
    def setReadOnly(self) -> bool: ...
    @overload
    def setWritable(self, arg0: bool, arg1: bool) -> bool: ...
    @overload
    def setWritable(self, arg0: bool) -> bool: ...
    @overload
    def setReadable(self, arg0: bool, arg1: bool) -> bool: ...
    @overload
    def setReadable(self, arg0: bool) -> bool: ...
    @overload
    def setExecutable(self, arg0: bool, arg1: bool) -> bool: ...
    @overload
    def setExecutable(self, arg0: bool) -> bool: ...
    def canExecute(self) -> bool: ...
    @staticmethod
    def listRoots() -> list["File"]: ...
    def getTotalSpace(self) -> int: ...
    def getFreeSpace(self) -> int: ...
    def getUsableSpace(self) -> int: ...
    @overload
    @staticmethod
    def createTempFile(arg0: str, arg1: str, arg2: "File") -> "File": ...
    @overload
    @staticmethod
    def createTempFile(arg0: str, arg1: str) -> "File": ...
    def compareTo(self, arg0: "File") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def toPath(self) -> Path: ...
