from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream

class FilterOutputStream:
    out: OutputStream
    def __init__(self, arg0: OutputStream) -> None: ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[int]) -> None: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
