from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.nio.CharBuffer import CharBuffer
from java.nio.charset.Charset import Charset
from java.nio.charset.CharsetDecoder import CharsetDecoder

class InputStreamReader:
    @overload
    def __init__(self, arg0: InputStream) -> None: ...
    @overload
    def __init__(self, arg0: InputStream, arg1: str) -> None: ...
    @overload
    def __init__(self, arg0: InputStream, arg1: Charset) -> None: ...
    @overload
    def __init__(self, arg0: InputStream, arg1: CharsetDecoder) -> None: ...
    def getEncoding(self) -> str: ...
    @overload
    def read(self, arg0: CharBuffer) -> int: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[str], arg1: int, arg2: int) -> int: ...
    def ready(self) -> bool: ...
    def close(self) -> None: ...
