from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream

class InputStream:
    def __init__(self) -> None: ...
    @staticmethod
    def nullInputStream() -> "InputStream": ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[int]) -> int: ...
    @overload
    def read(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    def readAllBytes(self) -> list[int]: ...
    @overload
    def readNBytes(self, arg0: int) -> list[int]: ...
    @overload
    def readNBytes(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    def skip(self, arg0: int) -> int: ...
    def skipNBytes(self, arg0: int) -> None: ...
    def available(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, arg0: int) -> None: ...
    def reset(self) -> None: ...
    def markSupported(self) -> bool: ...
    def transferTo(self, arg0: OutputStream) -> int: ...
