from typing import Any, ClassVar, overload
from java.io.Reader import Reader

class LineNumberReader:
    @overload
    def __init__(self, arg0: Reader) -> None: ...
    @overload
    def __init__(self, arg0: Reader, arg1: int) -> None: ...
    def setLineNumber(self, arg0: int) -> None: ...
    def getLineNumber(self) -> int: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[str], arg1: int, arg2: int) -> int: ...
    def readLine(self) -> str: ...
    def skip(self, arg0: int) -> int: ...
    def mark(self, arg0: int) -> None: ...
    def reset(self) -> None: ...
