from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["ObjectStreamConstants"]

class ObjectStreamConstants(JavaInterface, metaclass=MetaJavaClass):
    __javaclass__ = "java/io/ObjectStreamConstants"
    PROTOCOL_VERSION_1 = JavaStaticField("I")
    PROTOCOL_VERSION_2 = JavaStaticField("I")
    SC_BLOCK_DATA = JavaStaticField("B")
    SC_ENUM = JavaStaticField("B")
    SC_EXTERNALIZABLE = JavaStaticField("B")
    SC_SERIALIZABLE = JavaStaticField("B")
    SC_WRITE_METHOD = JavaStaticField("B")
    STREAM_MAGIC = JavaStaticField("S")
    STREAM_VERSION = JavaStaticField("S")
    SUBCLASS_IMPLEMENTATION_PERMISSION = JavaStaticField("Ljava/io/SerializablePermission;")
    SUBSTITUTION_PERMISSION = JavaStaticField("Ljava/io/SerializablePermission;")
    TC_ARRAY = JavaStaticField("B")
    TC_BASE = JavaStaticField("B")
    TC_BLOCKDATA = JavaStaticField("B")
    TC_BLOCKDATALONG = JavaStaticField("B")
    TC_CLASS = JavaStaticField("B")
    TC_CLASSDESC = JavaStaticField("B")
    TC_ENDBLOCKDATA = JavaStaticField("B")
    TC_ENUM = JavaStaticField("B")
    TC_EXCEPTION = JavaStaticField("B")
    TC_LONGSTRING = JavaStaticField("B")
    TC_MAX = JavaStaticField("B")
    TC_NULL = JavaStaticField("B")
    TC_OBJECT = JavaStaticField("B")
    TC_PROXYCLASSDESC = JavaStaticField("B")
    TC_REFERENCE = JavaStaticField("B")
    TC_RESET = JavaStaticField("B")
    TC_STRING = JavaStaticField("B")
    baseWireHandle = JavaStaticField("I")