from typing import Any, ClassVar, overload

class ObjectOutput:
    def writeObject(self, arg0: Any) -> None: ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[int]) -> None: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
