from typing import Any, ClassVar, overload
from java.io.ObjectStreamField import ObjectStreamField

class ObjectStreamClass:
    NO_FIELDS: ClassVar[list[ObjectStreamField]]
    @staticmethod
    def lookup(arg0: type) -> "ObjectStreamClass": ...
    @staticmethod
    def lookupAny(arg0: type) -> "ObjectStreamClass": ...
    def getName(self) -> str: ...
    def getSerialVersionUID(self) -> int: ...
    def forClass(self) -> type: ...
    def getFields(self) -> list[ObjectStreamField]: ...
    def getField(self, arg0: str) -> ObjectStreamField: ...
    def toString(self) -> str: ...
