from typing import Any, ClassVar, overload

class OutputStream:
    def __init__(self) -> None: ...
    @staticmethod
    def nullOutputStream() -> "OutputStream": ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[int]) -> None: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
