from typing import Any, ClassVar, overload
from java.io.PipedInputStream import PipedInputStream

class PipedOutputStream:
    @overload
    def __init__(self, arg0: PipedInputStream) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def connect(self, arg0: PipedInputStream) -> None: ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[int], arg1: int, arg2: int) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
