from typing import Any, ClassVar, overload
from java.io.Writer import Writer
from java.nio.CharBuffer import CharBuffer

class Reader:
    lock: Any
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Any) -> None: ...
    @staticmethod
    def nullReader() -> "Reader": ...
    @overload
    def read(self, arg0: CharBuffer) -> int: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[str]) -> int: ...
    @overload
    def read(self, arg0: list[str], arg1: int, arg2: int) -> int: ...
    def skip(self, arg0: int) -> int: ...
    def ready(self) -> bool: ...
    def markSupported(self) -> bool: ...
    def mark(self, arg0: int) -> None: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...
    def transferTo(self, arg0: Writer) -> int: ...
