from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.util.Enumeration import Enumeration

class SequenceInputStream:
    @overload
    def __init__(self, arg0: Enumeration) -> None: ...
    @overload
    def __init__(self, arg0: InputStream, arg1: InputStream) -> None: ...
    def available(self) -> int: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, arg0: list[int], arg1: int, arg2: int) -> int: ...
    def close(self) -> None: ...
