from typing import Any, ClassVar, overload

class Writer:
    lock: Any
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Any) -> None: ...
    @staticmethod
    def nullWriter() -> "Writer": ...
    @overload
    def write(self, arg0: int) -> None: ...
    @overload
    def write(self, arg0: list[str]) -> None: ...
    @overload
    def write(self, arg0: list[str], arg1: int, arg2: int) -> None: ...
    @overload
    def write(self, arg0: str) -> None: ...
    @overload
    def write(self, arg0: str, arg1: int, arg2: int) -> None: ...
    @overload
    def append(self, arg0: str) -> "Writer": ...
    @overload
    def append(self, arg0: str, arg1: int, arg2: int) -> "Writer": ...
    @overload
    def append(self, arg0: str) -> "Writer": ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
