from typing import Any, ClassVar, overload
from java.time.Instant import Instant

class DeletionRequest:
    DELETION_MODE_ALL: ClassVar[int]
    DELETION_MODE_EXCLUDE_INTERNAL_DATA: ClassVar[int]
    MATCH_BEHAVIOR_DELETE: ClassVar[int]
    MATCH_BEHAVIOR_PRESERVE: ClassVar[int]
    def getOriginUris(self) -> list: ...
    def getDomainUris(self) -> list: ...
    def getDeletionMode(self) -> int: ...
    def getMatchBehavior(self) -> int: ...
    def getStart(self) -> Instant: ...
    def getEnd(self) -> Instant: ...

    class Builder:
        def __init__(self) -> None: ...
        def setOriginUris(self, arg0: list) -> "Builder": ...
        def setDomainUris(self, arg0: list) -> "Builder": ...
        def setMatchBehavior(self, arg0: int) -> "Builder": ...
        def setDeletionMode(self, arg0: int) -> "Builder": ...
        def setStart(self, arg0: Instant) -> "Builder": ...
        def setEnd(self, arg0: Instant) -> "Builder": ...
        def build(self) -> "DeletionRequest": ...
