from typing import Any, ClassVar, overload

class HttpParams:
    def getParameter(self, arg0: str) -> Any: ...
    def setParameter(self, arg0: str, arg1: Any) -> "HttpParams": ...
    def copy(self) -> "HttpParams": ...
    def removeParameter(self, arg0: str) -> bool: ...
    def getLongParameter(self, arg0: str, arg1: int) -> int: ...
    def setLongParameter(self, arg0: str, arg1: int) -> "HttpParams": ...
    def getIntParameter(self, arg0: str, arg1: int) -> int: ...
    def setIntParameter(self, arg0: str, arg1: int) -> "HttpParams": ...
    def getDoubleParameter(self, arg0: str, arg1: float) -> float: ...
    def setDoubleParameter(self, arg0: str, arg1: float) -> "HttpParams": ...
    def getBooleanParameter(self, arg0: str, arg1: bool) -> bool: ...
    def setBooleanParameter(self, arg0: str, arg1: bool) -> "HttpParams": ...
    def isParameterTrue(self, arg0: str) -> bool: ...
    def isParameterFalse(self, arg0: str) -> bool: ...
