from typing import Any, ClassVar, overload
from org.apache.http.params.HttpParams import HttpParams

class HttpConnectionParams:
    @staticmethod
    def getSoTimeout(arg0: HttpParams) -> int: ...
    @staticmethod
    def setSoTimeout(arg0: HttpParams, arg1: int) -> None: ...
    @staticmethod
    def getTcpNoDelay(arg0: HttpParams) -> bool: ...
    @staticmethod
    def setTcpNoDelay(arg0: HttpParams, arg1: bool) -> None: ...
    @staticmethod
    def getSocketBufferSize(arg0: HttpParams) -> int: ...
    @staticmethod
    def setSocketBufferSize(arg0: HttpParams, arg1: int) -> None: ...
    @staticmethod
    def getLinger(arg0: HttpParams) -> int: ...
    @staticmethod
    def setLinger(arg0: HttpParams, arg1: int) -> None: ...
    @staticmethod
    def getConnectionTimeout(arg0: HttpParams) -> int: ...
    @staticmethod
    def setConnectionTimeout(arg0: HttpParams, arg1: int) -> None: ...
    @staticmethod
    def isStaleCheckingEnabled(arg0: HttpParams) -> bool: ...
    @staticmethod
    def setStaleCheckingEnabled(arg0: HttpParams, arg1: bool) -> None: ...
