from typing import Any, ClassVar, overload
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalUnit import TemporalUnit

class Duration:
    ZERO: ClassVar["Duration"]
    @staticmethod
    def ofDays(arg0: int) -> "Duration": ...
    @staticmethod
    def ofHours(arg0: int) -> "Duration": ...
    @staticmethod
    def ofMinutes(arg0: int) -> "Duration": ...
    @overload
    @staticmethod
    def ofSeconds(arg0: int) -> "Duration": ...
    @overload
    @staticmethod
    def ofSeconds(arg0: int, arg1: int) -> "Duration": ...
    @staticmethod
    def ofMillis(arg0: int) -> "Duration": ...
    @staticmethod
    def ofNanos(arg0: int) -> "Duration": ...
    @staticmethod
    def of(arg0: int, arg1: TemporalUnit) -> "Duration": ...
    @staticmethod
    def from_(arg0: TemporalAmount) -> "Duration": ...
    @staticmethod
    def parse(arg0: str) -> "Duration": ...
    @staticmethod
    def between(arg0: Temporal, arg1: Temporal) -> "Duration": ...
    def get(self, arg0: TemporalUnit) -> int: ...
    def getUnits(self) -> list: ...
    def isZero(self) -> bool: ...
    def isNegative(self) -> bool: ...
    def getSeconds(self) -> int: ...
    def getNano(self) -> int: ...
    def withSeconds(self, arg0: int) -> "Duration": ...
    def withNanos(self, arg0: int) -> "Duration": ...
    @overload
    def plus(self, arg0: "Duration") -> "Duration": ...
    @overload
    def plus(self, arg0: int, arg1: TemporalUnit) -> "Duration": ...
    def plusDays(self, arg0: int) -> "Duration": ...
    def plusHours(self, arg0: int) -> "Duration": ...
    def plusMinutes(self, arg0: int) -> "Duration": ...
    def plusSeconds(self, arg0: int) -> "Duration": ...
    def plusMillis(self, arg0: int) -> "Duration": ...
    def plusNanos(self, arg0: int) -> "Duration": ...
    @overload
    def minus(self, arg0: "Duration") -> "Duration": ...
    @overload
    def minus(self, arg0: int, arg1: TemporalUnit) -> "Duration": ...
    def minusDays(self, arg0: int) -> "Duration": ...
    def minusHours(self, arg0: int) -> "Duration": ...
    def minusMinutes(self, arg0: int) -> "Duration": ...
    def minusSeconds(self, arg0: int) -> "Duration": ...
    def minusMillis(self, arg0: int) -> "Duration": ...
    def minusNanos(self, arg0: int) -> "Duration": ...
    def multipliedBy(self, arg0: int) -> "Duration": ...
    @overload
    def dividedBy(self, arg0: int) -> "Duration": ...
    @overload
    def dividedBy(self, arg0: "Duration") -> int: ...
    def negated(self) -> "Duration": ...
    def abs(self) -> "Duration": ...
    def addTo(self, arg0: Temporal) -> Temporal: ...
    def subtractFrom(self, arg0: Temporal) -> Temporal: ...
    def toDays(self) -> int: ...
    def toHours(self) -> int: ...
    def toMinutes(self) -> int: ...
    def toSeconds(self) -> int: ...
    def toMillis(self) -> int: ...
    def toNanos(self) -> int: ...
    def toDaysPart(self) -> int: ...
    def toHoursPart(self) -> int: ...
    def toMinutesPart(self) -> int: ...
    def toSecondsPart(self) -> int: ...
    def toMillisPart(self) -> int: ...
    def toNanosPart(self) -> int: ...
    def truncatedTo(self, arg0: TemporalUnit) -> "Duration": ...
    def compareTo(self, arg0: "Duration") -> int: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
