from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.OffsetDateTime import OffsetDateTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.ZonedDateTime import ZonedDateTime
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class Instant:
    EPOCH: ClassVar["Instant"]
    MAX: ClassVar["Instant"]
    MIN: ClassVar["Instant"]
    @overload
    @staticmethod
    def now() -> "Instant": ...
    @overload
    @staticmethod
    def now(arg0: Clock) -> "Instant": ...
    @overload
    @staticmethod
    def ofEpochSecond(arg0: int) -> "Instant": ...
    @overload
    @staticmethod
    def ofEpochSecond(arg0: int, arg1: int) -> "Instant": ...
    @staticmethod
    def ofEpochMilli(arg0: int) -> "Instant": ...
    @staticmethod
    def from_(arg0: TemporalAccessor) -> "Instant": ...
    @staticmethod
    def parse(arg0: str) -> "Instant": ...
    @overload
    def isSupported(self, arg0: TemporalField) -> bool: ...
    @overload
    def isSupported(self, arg0: TemporalUnit) -> bool: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def get(self, arg0: TemporalField) -> int: ...
    def getLong(self, arg0: TemporalField) -> int: ...
    def getEpochSecond(self) -> int: ...
    def getNano(self) -> int: ...
    @overload
    def with_(self, arg0: TemporalAdjuster) -> "Instant": ...
    @overload
    def with_(self, arg0: TemporalField, arg1: int) -> "Instant": ...
    def truncatedTo(self, arg0: TemporalUnit) -> "Instant": ...
    @overload
    def plus(self, arg0: TemporalAmount) -> "Instant": ...
    @overload
    def plus(self, arg0: int, arg1: TemporalUnit) -> "Instant": ...
    def plusSeconds(self, arg0: int) -> "Instant": ...
    def plusMillis(self, arg0: int) -> "Instant": ...
    def plusNanos(self, arg0: int) -> "Instant": ...
    @overload
    def minus(self, arg0: TemporalAmount) -> "Instant": ...
    @overload
    def minus(self, arg0: int, arg1: TemporalUnit) -> "Instant": ...
    def minusSeconds(self, arg0: int) -> "Instant": ...
    def minusMillis(self, arg0: int) -> "Instant": ...
    def minusNanos(self, arg0: int) -> "Instant": ...
    def query(self, arg0: TemporalQuery) -> Any: ...
    def adjustInto(self, arg0: Temporal) -> Temporal: ...
    def until(self, arg0: Temporal, arg1: TemporalUnit) -> int: ...
    def atOffset(self, arg0: ZoneOffset) -> OffsetDateTime: ...
    def atZone(self, arg0: ZoneId) -> ZonedDateTime: ...
    def toEpochMilli(self) -> int: ...
    def compareTo(self, arg0: "Instant") -> int: ...
    def isAfter(self, arg0: "Instant") -> bool: ...
    def isBefore(self, arg0: "Instant") -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
