from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.DayOfWeek import DayOfWeek
from java.time.Instant import Instant
from java.time.LocalDate import LocalDate
from java.time.LocalTime import LocalTime
from java.time.Month import Month
from java.time.OffsetDateTime import OffsetDateTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.ZonedDateTime import ZonedDateTime
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class LocalDateTime:
    MAX: ClassVar["LocalDateTime"]
    MIN: ClassVar["LocalDateTime"]
    @overload
    @staticmethod
    def now() -> "LocalDateTime": ...
    @overload
    @staticmethod
    def now(arg0: ZoneId) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def now(arg0: Clock) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(arg0: int, arg1: Month, arg2: int, arg3: int, arg4: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(arg0: int, arg1: Month, arg2: int, arg3: int, arg4: int, arg5: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(arg0: int, arg1: Month, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(arg0: LocalDate, arg1: LocalTime) -> "LocalDateTime": ...
    @staticmethod
    def ofInstant(arg0: Instant, arg1: ZoneId) -> "LocalDateTime": ...
    @staticmethod
    def ofEpochSecond(arg0: int, arg1: int, arg2: ZoneOffset) -> "LocalDateTime": ...
    @staticmethod
    def from_(arg0: TemporalAccessor) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def parse(arg0: str) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def parse(arg0: str, arg1: DateTimeFormatter) -> "LocalDateTime": ...
    @overload
    def isSupported(self, arg0: TemporalField) -> bool: ...
    @overload
    def isSupported(self, arg0: TemporalUnit) -> bool: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def get(self, arg0: TemporalField) -> int: ...
    def getLong(self, arg0: TemporalField) -> int: ...
    def toLocalDate(self) -> LocalDate: ...
    def getYear(self) -> int: ...
    def getMonthValue(self) -> int: ...
    def getMonth(self) -> Month: ...
    def getDayOfMonth(self) -> int: ...
    def getDayOfYear(self) -> int: ...
    def getDayOfWeek(self) -> DayOfWeek: ...
    def toLocalTime(self) -> LocalTime: ...
    def getHour(self) -> int: ...
    def getMinute(self) -> int: ...
    def getSecond(self) -> int: ...
    def getNano(self) -> int: ...
    @overload
    def with_(self, arg0: TemporalAdjuster) -> "LocalDateTime": ...
    @overload
    def with_(self, arg0: TemporalField, arg1: int) -> "LocalDateTime": ...
    def withYear(self, arg0: int) -> "LocalDateTime": ...
    def withMonth(self, arg0: int) -> "LocalDateTime": ...
    def withDayOfMonth(self, arg0: int) -> "LocalDateTime": ...
    def withDayOfYear(self, arg0: int) -> "LocalDateTime": ...
    def withHour(self, arg0: int) -> "LocalDateTime": ...
    def withMinute(self, arg0: int) -> "LocalDateTime": ...
    def withSecond(self, arg0: int) -> "LocalDateTime": ...
    def withNano(self, arg0: int) -> "LocalDateTime": ...
    def truncatedTo(self, arg0: TemporalUnit) -> "LocalDateTime": ...
    @overload
    def plus(self, arg0: TemporalAmount) -> "LocalDateTime": ...
    @overload
    def plus(self, arg0: int, arg1: TemporalUnit) -> "LocalDateTime": ...
    def plusYears(self, arg0: int) -> "LocalDateTime": ...
    def plusMonths(self, arg0: int) -> "LocalDateTime": ...
    def plusWeeks(self, arg0: int) -> "LocalDateTime": ...
    def plusDays(self, arg0: int) -> "LocalDateTime": ...
    def plusHours(self, arg0: int) -> "LocalDateTime": ...
    def plusMinutes(self, arg0: int) -> "LocalDateTime": ...
    def plusSeconds(self, arg0: int) -> "LocalDateTime": ...
    def plusNanos(self, arg0: int) -> "LocalDateTime": ...
    @overload
    def minus(self, arg0: TemporalAmount) -> "LocalDateTime": ...
    @overload
    def minus(self, arg0: int, arg1: TemporalUnit) -> "LocalDateTime": ...
    def minusYears(self, arg0: int) -> "LocalDateTime": ...
    def minusMonths(self, arg0: int) -> "LocalDateTime": ...
    def minusWeeks(self, arg0: int) -> "LocalDateTime": ...
    def minusDays(self, arg0: int) -> "LocalDateTime": ...
    def minusHours(self, arg0: int) -> "LocalDateTime": ...
    def minusMinutes(self, arg0: int) -> "LocalDateTime": ...
    def minusSeconds(self, arg0: int) -> "LocalDateTime": ...
    def minusNanos(self, arg0: int) -> "LocalDateTime": ...
    def query(self, arg0: TemporalQuery) -> Any: ...
    def adjustInto(self, arg0: Temporal) -> Temporal: ...
    def until(self, arg0: Temporal, arg1: TemporalUnit) -> int: ...
    def format(self, arg0: DateTimeFormatter) -> str: ...
    def atOffset(self, arg0: ZoneOffset) -> OffsetDateTime: ...
    def atZone(self, arg0: ZoneId) -> ZonedDateTime: ...
    def compareTo(self, arg0: ChronoLocalDateTime) -> int: ...
    def isAfter(self, arg0: ChronoLocalDateTime) -> bool: ...
    def isBefore(self, arg0: ChronoLocalDateTime) -> bool: ...
    def isEqual(self, arg0: ChronoLocalDateTime) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
