from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class Month:
    JANUARY: ClassVar["Month"]
    FEBRUARY: ClassVar["Month"]
    MARCH: ClassVar["Month"]
    APRIL: ClassVar["Month"]
    MAY: ClassVar["Month"]
    JUNE: ClassVar["Month"]
    JULY: ClassVar["Month"]
    AUGUST: ClassVar["Month"]
    SEPTEMBER: ClassVar["Month"]
    OCTOBER: ClassVar["Month"]
    NOVEMBER: ClassVar["Month"]
    DECEMBER: ClassVar["Month"]
    @staticmethod
    def values() -> list["Month"]: ...
    @staticmethod
    def valueOf(arg0: str) -> "Month": ...
    @staticmethod
    def of(arg0: int) -> "Month": ...
    @staticmethod
    def from_(arg0: TemporalAccessor) -> "Month": ...
    def getValue(self) -> int: ...
    def getDisplayName(self, arg0: TextStyle, arg1: Locale) -> str: ...
    def isSupported(self, arg0: TemporalField) -> bool: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def get(self, arg0: TemporalField) -> int: ...
    def getLong(self, arg0: TemporalField) -> int: ...
    def plus(self, arg0: int) -> "Month": ...
    def minus(self, arg0: int) -> "Month": ...
    def length(self, arg0: bool) -> int: ...
    def minLength(self) -> int: ...
    def maxLength(self) -> int: ...
    def firstDayOfYear(self, arg0: bool) -> int: ...
    def firstMonthOfQuarter(self) -> "Month": ...
    def query(self, arg0: TemporalQuery) -> Any: ...
    def adjustInto(self, arg0: Temporal) -> Temporal: ...
