from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalDate import LocalDate
from java.time.Month import Month
from java.time.MonthDay import MonthDay
from java.time.YearMonth import YearMonth
from java.time.ZoneId import ZoneId
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class Year:
    MAX_VALUE: ClassVar[int]
    MIN_VALUE: ClassVar[int]
    @overload
    @staticmethod
    def now() -> "Year": ...
    @overload
    @staticmethod
    def now(arg0: ZoneId) -> "Year": ...
    @overload
    @staticmethod
    def now(arg0: Clock) -> "Year": ...
    @staticmethod
    def of(arg0: int) -> "Year": ...
    @staticmethod
    def from_(arg0: TemporalAccessor) -> "Year": ...
    @overload
    @staticmethod
    def parse(arg0: str) -> "Year": ...
    @overload
    @staticmethod
    def parse(arg0: str, arg1: DateTimeFormatter) -> "Year": ...
    @overload
    @staticmethod
    def isLeap(arg0: int) -> bool: ...
    @overload
    def isLeap(self) -> bool: ...
    def getValue(self) -> int: ...
    @overload
    def isSupported(self, arg0: TemporalField) -> bool: ...
    @overload
    def isSupported(self, arg0: TemporalUnit) -> bool: ...
    def range(self, arg0: TemporalField) -> ValueRange: ...
    def get(self, arg0: TemporalField) -> int: ...
    def getLong(self, arg0: TemporalField) -> int: ...
    def isValidMonthDay(self, arg0: MonthDay) -> bool: ...
    def length(self) -> int: ...
    @overload
    def with_(self, arg0: TemporalAdjuster) -> "Year": ...
    @overload
    def with_(self, arg0: TemporalField, arg1: int) -> "Year": ...
    @overload
    def plus(self, arg0: TemporalAmount) -> "Year": ...
    @overload
    def plus(self, arg0: int, arg1: TemporalUnit) -> "Year": ...
    def plusYears(self, arg0: int) -> "Year": ...
    @overload
    def minus(self, arg0: TemporalAmount) -> "Year": ...
    @overload
    def minus(self, arg0: int, arg1: TemporalUnit) -> "Year": ...
    def minusYears(self, arg0: int) -> "Year": ...
    def query(self, arg0: TemporalQuery) -> Any: ...
    def adjustInto(self, arg0: Temporal) -> Temporal: ...
    def until(self, arg0: Temporal, arg1: TemporalUnit) -> int: ...
    def format(self, arg0: DateTimeFormatter) -> str: ...
    def atDay(self, arg0: int) -> LocalDate: ...
    @overload
    def atMonth(self, arg0: Month) -> YearMonth: ...
    @overload
    def atMonth(self, arg0: int) -> YearMonth: ...
    def atMonthDay(self, arg0: MonthDay) -> LocalDate: ...
    def compareTo(self, arg0: "Year") -> int: ...
    def isAfter(self, arg0: "Year") -> bool: ...
    def isBefore(self, arg0: "Year") -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
