from typing import Any, ClassVar, overload
from android.app.Dialog import Dialog
from android.app.PendingIntent import PendingIntent
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.content.Intent import Intent
from android.os.IBinder import IBinder
from android.service.quicksettings.Tile import Tile
from java.lang.Runnable import Runnable

class TileService:
    ACTION_QS_TILE: ClassVar[str]
    ACTION_QS_TILE_PREFERENCES: ClassVar[str]
    META_DATA_ACTIVE_TILE: ClassVar[str]
    META_DATA_TOGGLEABLE_TILE: ClassVar[str]
    def __init__(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onTileAdded(self) -> None: ...
    def onTileRemoved(self) -> None: ...
    def onStartListening(self) -> None: ...
    def onStopListening(self) -> None: ...
    def onClick(self) -> None: ...
    def showDialog(self, arg0: Dialog) -> None: ...
    def unlockAndRun(self, arg0: Runnable) -> None: ...
    def isSecure(self) -> bool: ...
    def isLocked(self) -> bool: ...
    @overload
    def startActivityAndCollapse(self, arg0: Intent) -> None: ...
    @overload
    def startActivityAndCollapse(self, arg0: PendingIntent) -> None: ...
    def getQsTile(self) -> Tile: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    @staticmethod
    def requestListeningState(arg0: Context, arg1: ComponentName) -> None: ...
