from typing import Any, ClassVar, overload
from android.net.LinkProperties import LinkProperties
from android.net.Network import Network
from android.net.NetworkCapabilities import NetworkCapabilities
from android.net.NetworkRequest import NetworkRequest
from android.os.Parcel import Parcel
from android.os.PersistableBundle import PersistableBundle
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class ConnectivityDiagnosticsManager:
    def registerConnectivityDiagnosticsCallback(self, arg0: NetworkRequest, arg1: Executor, arg2: "ConnectivityDiagnosticsCallback") -> None: ...
    def unregisterConnectivityDiagnosticsCallback(self, arg0: "ConnectivityDiagnosticsCallback") -> None: ...

    class ConnectivityDiagnosticsCallback:
        def __init__(self) -> None: ...
        def onConnectivityReportAvailable(self, arg0: "ConnectivityReport") -> None: ...
        def onDataStallSuspected(self, arg0: "DataStallReport") -> None: ...
        def onNetworkConnectivityReported(self, arg0: Network, arg1: bool) -> None: ...

    class ConnectivityReport:
        CREATOR: ClassVar[Creator]
        KEY_NETWORK_PROBES_ATTEMPTED_BITMASK: ClassVar[str]
        KEY_NETWORK_PROBES_SUCCEEDED_BITMASK: ClassVar[str]
        KEY_NETWORK_VALIDATION_RESULT: ClassVar[str]
        NETWORK_PROBE_DNS: ClassVar[int]
        NETWORK_PROBE_FALLBACK: ClassVar[int]
        NETWORK_PROBE_HTTP: ClassVar[int]
        NETWORK_PROBE_HTTPS: ClassVar[int]
        NETWORK_PROBE_PRIVATE_DNS: ClassVar[int]
        NETWORK_VALIDATION_RESULT_INVALID: ClassVar[int]
        NETWORK_VALIDATION_RESULT_PARTIALLY_VALID: ClassVar[int]
        NETWORK_VALIDATION_RESULT_SKIPPED: ClassVar[int]
        NETWORK_VALIDATION_RESULT_VALID: ClassVar[int]
        def __init__(self, arg0: Network, arg1: int, arg2: LinkProperties, arg3: NetworkCapabilities, arg4: PersistableBundle) -> None: ...
        def getNetwork(self) -> Network: ...
        def getReportTimestamp(self) -> int: ...
        def getLinkProperties(self) -> LinkProperties: ...
        def getNetworkCapabilities(self) -> NetworkCapabilities: ...
        def getAdditionalInfo(self) -> PersistableBundle: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class DataStallReport:
        CREATOR: ClassVar[Creator]
        DETECTION_METHOD_DNS_EVENTS: ClassVar[int]
        DETECTION_METHOD_TCP_METRICS: ClassVar[int]
        KEY_DNS_CONSECUTIVE_TIMEOUTS: ClassVar[str]
        KEY_TCP_METRICS_COLLECTION_PERIOD_MILLIS: ClassVar[str]
        KEY_TCP_PACKET_FAIL_RATE: ClassVar[str]
        def __init__(self, arg0: Network, arg1: int, arg2: int, arg3: LinkProperties, arg4: NetworkCapabilities, arg5: PersistableBundle) -> None: ...
        def getNetwork(self) -> Network: ...
        def getReportTimestamp(self) -> int: ...
        def getDetectionMethod(self) -> int: ...
        def getLinkProperties(self) -> LinkProperties: ...
        def getNetworkCapabilities(self) -> NetworkCapabilities: ...
        def getStallDetails(self) -> PersistableBundle: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
