from typing import Any, ClassVar, overload
from android.net.IpPrefix import IpPrefix
from android.net.ProxyInfo import ProxyInfo
from android.net.RouteInfo import RouteInfo
from android.os.Parcel import Parcel
from java.net.Inet4Address import Inet4Address

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class LinkProperties:
    CREATOR: ClassVar[Creator]
    def __init__(self) -> None: ...
    def setInterfaceName(self, arg0: str) -> None: ...
    def getInterfaceName(self) -> str: ...
    def getLinkAddresses(self) -> list: ...
    def setLinkAddresses(self, arg0: list) -> None: ...
    def setDnsServers(self, arg0: list) -> None: ...
    def getDnsServers(self) -> list: ...
    def isPrivateDnsActive(self) -> bool: ...
    def setDhcpServerAddress(self, arg0: Inet4Address) -> None: ...
    def getDhcpServerAddress(self) -> Inet4Address: ...
    def getPrivateDnsServerName(self) -> str: ...
    def setDomains(self, arg0: str) -> None: ...
    def getDomains(self) -> str: ...
    def setMtu(self, arg0: int) -> None: ...
    def getMtu(self) -> int: ...
    def addRoute(self, arg0: RouteInfo) -> bool: ...
    def getRoutes(self) -> list: ...
    def setHttpProxy(self, arg0: ProxyInfo) -> None: ...
    def getHttpProxy(self) -> ProxyInfo: ...
    def getNat64Prefix(self) -> IpPrefix: ...
    def setNat64Prefix(self, arg0: IpPrefix) -> None: ...
    def clear(self) -> None: ...
    def describeContents(self) -> int: ...
    def toString(self) -> str: ...
    def isWakeOnLanSupported(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
