from typing import Any, ClassVar, overload
from android.net.LocalSocket import LocalSocket
from android.net.LocalSocketAddress import LocalSocketAddress
from java.io.FileDescriptor import FileDescriptor

class LocalServerSocket:
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: FileDescriptor) -> None: ...
    def getLocalSocketAddress(self) -> LocalSocketAddress: ...
    def accept(self) -> LocalSocket: ...
    def getFileDescriptor(self) -> FileDescriptor: ...
    def close(self) -> None: ...
