from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.io.FileDescriptor import FileDescriptor
from java.net.DatagramSocket import DatagramSocket
from java.net.InetAddress import InetAddress
from java.net.Proxy import Proxy
from java.net.Socket import Socket
from java.net.URL import URL
from java.net.URLConnection import URLConnection
from javax.net.SocketFactory import SocketFactory

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Network:
    CREATOR: ClassVar[Creator]
    def getAllByName(self, arg0: str) -> list[InetAddress]: ...
    def getByName(self, arg0: str) -> InetAddress: ...
    def getSocketFactory(self) -> SocketFactory: ...
    @overload
    def openConnection(self, arg0: URL) -> URLConnection: ...
    @overload
    def openConnection(self, arg0: URL, arg1: Proxy) -> URLConnection: ...
    @overload
    def bindSocket(self, arg0: DatagramSocket) -> None: ...
    @overload
    def bindSocket(self, arg0: Socket) -> None: ...
    @overload
    def bindSocket(self, arg0: FileDescriptor) -> None: ...
    @staticmethod
    def fromNetworkHandle(arg0: int) -> "Network": ...
    def getNetworkHandle(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
