from typing import Any, ClassVar, overload
from android.net.NetworkCapabilities import NetworkCapabilities
from android.net.NetworkSpecifier import NetworkSpecifier
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class NetworkRequest:
    CREATOR: ClassVar[Creator]
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def hasCapability(self, arg0: int) -> bool: ...
    def canBeSatisfiedBy(self, arg0: NetworkCapabilities) -> bool: ...
    def hasTransport(self, arg0: int) -> bool: ...
    def getNetworkSpecifier(self) -> NetworkSpecifier: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getCapabilities(self) -> list[int]: ...
    def getTransportTypes(self) -> list[int]: ...
    def getSubscriptionIds(self) -> set: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: "NetworkRequest") -> None: ...
        def build(self) -> "NetworkRequest": ...
        def addCapability(self, arg0: int) -> "Builder": ...
        def removeCapability(self, arg0: int) -> "Builder": ...
        def clearCapabilities(self) -> "Builder": ...
        def addTransportType(self, arg0: int) -> "Builder": ...
        def removeTransportType(self, arg0: int) -> "Builder": ...
        @overload
        def setNetworkSpecifier(self, arg0: str) -> "Builder": ...
        @overload
        def setNetworkSpecifier(self, arg0: NetworkSpecifier) -> "Builder": ...
        def setSubscriptionIds(self, arg0: set) -> "Builder": ...
        def setIncludeOtherUidNetworks(self, arg0: bool) -> "Builder": ...
