from typing import Any, ClassVar, overload

class PlatformVpnProfile:
    TYPE_IKEV2_IPSEC_PSK: ClassVar[int]
    TYPE_IKEV2_IPSEC_RSA: ClassVar[int]
    TYPE_IKEV2_IPSEC_USER_PASS: ClassVar[int]
    def getType(self) -> int: ...
    def areLocalRoutesExcluded(self) -> bool: ...
    def isInternetValidationRequired(self) -> bool: ...
    def getTypeString(self) -> str: ...
