from typing import Any, ClassVar, overload
from android.content.Context import Context

class Proxy:
    PROXY_CHANGE_ACTION: ClassVar[str]
    def __init__(self) -> None: ...
    @staticmethod
    def getHost(arg0: Context) -> str: ...
    @staticmethod
    def getPort(arg0: Context) -> int: ...
    @staticmethod
    def getDefaultHost() -> str: ...
    @staticmethod
    def getDefaultPort() -> int: ...
