from typing import Any, ClassVar, overload
from android.net.IpPrefix import IpPrefix
from android.os.Parcel import Parcel
from java.net.InetAddress import InetAddress

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class RouteInfo:
    CREATOR: ClassVar[Creator]
    RTN_THROW: ClassVar[int]
    RTN_UNICAST: ClassVar[int]
    RTN_UNREACHABLE: ClassVar[int]
    def getDestination(self) -> IpPrefix: ...
    def getGateway(self) -> InetAddress: ...
    def getInterface(self) -> str: ...
    def getType(self) -> int: ...
    def isDefaultRoute(self) -> bool: ...
    def hasGateway(self) -> bool: ...
    def matches(self, arg0: InetAddress) -> bool: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
