from typing import Any, ClassVar, overload

class SocketKeepalive:
    ERROR_HARDWARE_ERROR: ClassVar[int]
    ERROR_INSUFFICIENT_RESOURCES: ClassVar[int]
    ERROR_INVALID_INTERVAL: ClassVar[int]
    ERROR_INVALID_IP_ADDRESS: ClassVar[int]
    ERROR_INVALID_LENGTH: ClassVar[int]
    ERROR_INVALID_NETWORK: ClassVar[int]
    ERROR_INVALID_PORT: ClassVar[int]
    ERROR_INVALID_SOCKET: ClassVar[int]
    ERROR_SOCKET_NOT_IDLE: ClassVar[int]
    ERROR_UNSUPPORTED: ClassVar[int]
    def start(self, arg0: int) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...

    class Callback:
        def __init__(self) -> None: ...
        def onStarted(self) -> None: ...
        def onStopped(self) -> None: ...
        def onError(self, arg0: int) -> None: ...
        def onDataReceived(self) -> None: ...
