from typing import Any, ClassVar, overload
from android.net.SSLSessionCache import SSLSessionCache
from java.net.InetAddress import InetAddress
from java.net.Socket import Socket
from javax.net.SocketFactory import SocketFactory
from javax.net.ssl.KeyManager import KeyManager
from javax.net.ssl.SSLSocketFactory import SSLSocketFactory
from javax.net.ssl.TrustManager import TrustManager

class SSLCertificateSocketFactory:
    def __init__(self, arg0: int) -> None: ...
    @overload
    @staticmethod
    def getDefault(arg0: int) -> SocketFactory: ...
    @overload
    @staticmethod
    def getDefault(arg0: int, arg1: SSLSessionCache) -> SSLSocketFactory: ...
    @staticmethod
    def getInsecure(arg0: int, arg1: SSLSessionCache) -> SSLSocketFactory: ...
    def setTrustManagers(self, arg0: list[TrustManager]) -> None: ...
    def setNpnProtocols(self, arg0: list[list[int]]) -> None: ...
    def getNpnSelectedProtocol(self, arg0: Socket) -> list[int]: ...
    def setKeyManagers(self, arg0: list[KeyManager]) -> None: ...
    def setUseSessionTickets(self, arg0: Socket, arg1: bool) -> None: ...
    def setHostname(self, arg0: Socket, arg1: str) -> None: ...
    @overload
    def createSocket(self, arg0: Socket, arg1: str, arg2: int, arg3: bool) -> Socket: ...
    @overload
    def createSocket(self) -> Socket: ...
    @overload
    def createSocket(self, arg0: InetAddress, arg1: int, arg2: InetAddress, arg3: int) -> Socket: ...
    @overload
    def createSocket(self, arg0: InetAddress, arg1: int) -> Socket: ...
    @overload
    def createSocket(self, arg0: str, arg1: int, arg2: InetAddress, arg3: int) -> Socket: ...
    @overload
    def createSocket(self, arg0: str, arg1: int) -> Socket: ...
    def getDefaultCipherSuites(self) -> list[str]: ...
    def getSupportedCipherSuites(self) -> list[str]: ...
