from typing import Any, ClassVar, overload
from java.io.FileDescriptor import FileDescriptor
from java.net.DatagramSocket import DatagramSocket
from java.net.Socket import Socket

class TrafficStats:
    UNSUPPORTED: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def setThreadStatsTag(arg0: int) -> None: ...
    @staticmethod
    def getAndSetThreadStatsTag(arg0: int) -> int: ...
    @staticmethod
    def getThreadStatsTag() -> int: ...
    @staticmethod
    def clearThreadStatsTag() -> None: ...
    @staticmethod
    def setThreadStatsUid(arg0: int) -> None: ...
    @staticmethod
    def getThreadStatsUid() -> int: ...
    @staticmethod
    def clearThreadStatsUid() -> None: ...
    @staticmethod
    def tagSocket(arg0: Socket) -> None: ...
    @staticmethod
    def untagSocket(arg0: Socket) -> None: ...
    @staticmethod
    def tagDatagramSocket(arg0: DatagramSocket) -> None: ...
    @staticmethod
    def untagDatagramSocket(arg0: DatagramSocket) -> None: ...
    @staticmethod
    def tagFileDescriptor(arg0: FileDescriptor) -> None: ...
    @staticmethod
    def untagFileDescriptor(arg0: FileDescriptor) -> None: ...
    @overload
    @staticmethod
    def incrementOperationCount(arg0: int) -> None: ...
    @overload
    @staticmethod
    def incrementOperationCount(arg0: int, arg1: int) -> None: ...
    @staticmethod
    def getMobileTxPackets() -> int: ...
    @staticmethod
    def getMobileRxPackets() -> int: ...
    @staticmethod
    def getMobileTxBytes() -> int: ...
    @staticmethod
    def getMobileRxBytes() -> int: ...
    @staticmethod
    def getTxPackets(arg0: str) -> int: ...
    @staticmethod
    def getRxPackets(arg0: str) -> int: ...
    @staticmethod
    def getTxBytes(arg0: str) -> int: ...
    @staticmethod
    def getRxBytes(arg0: str) -> int: ...
    @staticmethod
    def getTotalTxPackets() -> int: ...
    @staticmethod
    def getTotalRxPackets() -> int: ...
    @staticmethod
    def getTotalTxBytes() -> int: ...
    @staticmethod
    def getTotalRxBytes() -> int: ...
    @staticmethod
    def getUidTxBytes(arg0: int) -> int: ...
    @staticmethod
    def getUidRxBytes(arg0: int) -> int: ...
    @staticmethod
    def getUidTxPackets(arg0: int) -> int: ...
    @staticmethod
    def getUidRxPackets(arg0: int) -> int: ...
    @staticmethod
    def getUidTcpTxBytes(arg0: int) -> int: ...
    @staticmethod
    def getUidTcpRxBytes(arg0: int) -> int: ...
    @staticmethod
    def getUidUdpTxBytes(arg0: int) -> int: ...
    @staticmethod
    def getUidUdpRxBytes(arg0: int) -> int: ...
    @staticmethod
    def getUidTcpTxSegments(arg0: int) -> int: ...
    @staticmethod
    def getUidTcpRxSegments(arg0: int) -> int: ...
    @staticmethod
    def getUidUdpTxPackets(arg0: int) -> int: ...
    @staticmethod
    def getUidUdpRxPackets(arg0: int) -> int: ...
