from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.io.File import File

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class Uri:
    CREATOR: ClassVar[Creator]
    EMPTY: ClassVar["Uri"]
    def isHierarchical(self) -> bool: ...
    def isOpaque(self) -> bool: ...
    def isRelative(self) -> bool: ...
    def isAbsolute(self) -> bool: ...
    def getScheme(self) -> str: ...
    def getSchemeSpecificPart(self) -> str: ...
    def getEncodedSchemeSpecificPart(self) -> str: ...
    def getAuthority(self) -> str: ...
    def getEncodedAuthority(self) -> str: ...
    def getUserInfo(self) -> str: ...
    def getEncodedUserInfo(self) -> str: ...
    def getHost(self) -> str: ...
    def getPort(self) -> int: ...
    def getPath(self) -> str: ...
    def getEncodedPath(self) -> str: ...
    def getQuery(self) -> str: ...
    def getEncodedQuery(self) -> str: ...
    def getFragment(self) -> str: ...
    def getEncodedFragment(self) -> str: ...
    def getPathSegments(self) -> list: ...
    def getLastPathSegment(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def compareTo(self, arg0: "Uri") -> int: ...
    def toString(self) -> str: ...
    def buildUpon(self) -> "Builder": ...
    @staticmethod
    def parse(arg0: str) -> "Uri": ...
    @staticmethod
    def fromFile(arg0: File) -> "Uri": ...
    @staticmethod
    def fromParts(arg0: str, arg1: str, arg2: str) -> "Uri": ...
    def getQueryParameterNames(self) -> set: ...
    def getQueryParameters(self, arg0: str) -> list: ...
    def getQueryParameter(self, arg0: str) -> str: ...
    def getBooleanQueryParameter(self, arg0: str, arg1: bool) -> bool: ...
    def normalizeScheme(self) -> "Uri": ...
    @staticmethod
    def writeToParcel(arg0: Parcel, arg1: "Uri") -> None: ...
    @overload
    @staticmethod
    def encode(arg0: str) -> str: ...
    @overload
    @staticmethod
    def encode(arg0: str, arg1: str) -> str: ...
    @staticmethod
    def decode(arg0: str) -> str: ...
    @staticmethod
    def withAppendedPath(arg0: "Uri", arg1: str) -> "Uri": ...

    class Builder:
        def __init__(self) -> None: ...
        def scheme(self, arg0: str) -> "Builder": ...
        def opaquePart(self, arg0: str) -> "Builder": ...
        def encodedOpaquePart(self, arg0: str) -> "Builder": ...
        def authority(self, arg0: str) -> "Builder": ...
        def encodedAuthority(self, arg0: str) -> "Builder": ...
        def path(self, arg0: str) -> "Builder": ...
        def encodedPath(self, arg0: str) -> "Builder": ...
        def appendPath(self, arg0: str) -> "Builder": ...
        def appendEncodedPath(self, arg0: str) -> "Builder": ...
        def query(self, arg0: str) -> "Builder": ...
        def encodedQuery(self, arg0: str) -> "Builder": ...
        def fragment(self, arg0: str) -> "Builder": ...
        def encodedFragment(self, arg0: str) -> "Builder": ...
        def appendQueryParameter(self, arg0: str, arg1: str) -> "Builder": ...
        def clearQuery(self) -> "Builder": ...
        def build(self) -> "Uri": ...
        def toString(self) -> str: ...
