from typing import Any, ClassVar, overload

class UrlQuerySanitizer:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    def getUnregisteredParameterValueSanitizer(self) -> "ValueSanitizer": ...
    def setUnregisteredParameterValueSanitizer(self, arg0: "ValueSanitizer") -> None: ...
    @staticmethod
    def getAllIllegal() -> "ValueSanitizer": ...
    @staticmethod
    def getAllButNulLegal() -> "ValueSanitizer": ...
    @staticmethod
    def getAllButWhitespaceLegal() -> "ValueSanitizer": ...
    @staticmethod
    def getUrlLegal() -> "ValueSanitizer": ...
    @staticmethod
    def getUrlAndSpaceLegal() -> "ValueSanitizer": ...
    @staticmethod
    def getAmpLegal() -> "ValueSanitizer": ...
    @staticmethod
    def getAmpAndSpaceLegal() -> "ValueSanitizer": ...
    @staticmethod
    def getSpaceLegal() -> "ValueSanitizer": ...
    @staticmethod
    def getAllButNulAndAngleBracketsLegal() -> "ValueSanitizer": ...
    def parseUrl(self, arg0: str) -> None: ...
    def parseQuery(self, arg0: str) -> None: ...
    def getParameterSet(self) -> set: ...
    def getParameterList(self) -> list: ...
    def hasParameter(self, arg0: str) -> bool: ...
    def getValue(self, arg0: str) -> str: ...
    def registerParameter(self, arg0: str, arg1: "ValueSanitizer") -> None: ...
    def registerParameters(self, arg0: list[str], arg1: "ValueSanitizer") -> None: ...
    def setAllowUnregisteredParamaters(self, arg0: bool) -> None: ...
    def getAllowUnregisteredParamaters(self) -> bool: ...
    def setPreferFirstRepeatedParameter(self, arg0: bool) -> None: ...
    def getPreferFirstRepeatedParameter(self) -> bool: ...
    def parseEntry(self, arg0: str, arg1: str) -> None: ...
    def addSanitizedEntry(self, arg0: str, arg1: str) -> None: ...
    def getValueSanitizer(self, arg0: str) -> "ValueSanitizer": ...
    def getEffectiveValueSanitizer(self, arg0: str) -> "ValueSanitizer": ...
    def unescape(self, arg0: str) -> str: ...
    def isHexDigit(self, arg0: str) -> bool: ...
    def decodeHexDigit(self, arg0: str) -> int: ...
    def clear(self) -> None: ...

    class IllegalCharacterValueSanitizer:
        ALL_BUT_NUL_AND_ANGLE_BRACKETS_LEGAL: ClassVar[int]
        ALL_BUT_NUL_LEGAL: ClassVar[int]
        ALL_BUT_WHITESPACE_LEGAL: ClassVar[int]
        ALL_ILLEGAL: ClassVar[int]
        ALL_OK: ClassVar[int]
        ALL_WHITESPACE_OK: ClassVar[int]
        AMP_AND_SPACE_LEGAL: ClassVar[int]
        AMP_LEGAL: ClassVar[int]
        AMP_OK: ClassVar[int]
        DQUOTE_OK: ClassVar[int]
        GT_OK: ClassVar[int]
        LT_OK: ClassVar[int]
        NON_7_BIT_ASCII_OK: ClassVar[int]
        NUL_OK: ClassVar[int]
        OTHER_WHITESPACE_OK: ClassVar[int]
        PCT_OK: ClassVar[int]
        SCRIPT_URL_OK: ClassVar[int]
        SPACE_LEGAL: ClassVar[int]
        SPACE_OK: ClassVar[int]
        SQUOTE_OK: ClassVar[int]
        URL_AND_SPACE_LEGAL: ClassVar[int]
        URL_LEGAL: ClassVar[int]
        def __init__(self, arg0: int) -> None: ...
        def sanitize(self, arg0: str) -> str: ...

    class ParameterValuePair:
        mParameter: str
        mValue: str
        def __init__(self, arg0: "UrlQuerySanitizer", arg1: str, arg2: str) -> None: ...

    class ValueSanitizer:
        def sanitize(self, arg0: str) -> str: ...
