from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.Context import Context
from android.content.Intent import Intent
from android.net.IpPrefix import IpPrefix
from android.net.Network import Network
from android.net.ProxyInfo import ProxyInfo
from android.os.IBinder import IBinder
from android.os.ParcelFileDescriptor import ParcelFileDescriptor
from java.net.DatagramSocket import DatagramSocket
from java.net.InetAddress import InetAddress
from java.net.Socket import Socket

class VpnService:
    SERVICE_INTERFACE: ClassVar[str]
    SERVICE_META_DATA_SUPPORTS_ALWAYS_ON: ClassVar[str]
    def __init__(self) -> None: ...
    @staticmethod
    def prepare(arg0: Context) -> Intent: ...
    @overload
    def protect(self, arg0: int) -> bool: ...
    @overload
    def protect(self, arg0: Socket) -> bool: ...
    @overload
    def protect(self, arg0: DatagramSocket) -> bool: ...
    def setUnderlyingNetworks(self, arg0: list[Network]) -> bool: ...
    def isAlwaysOn(self) -> bool: ...
    def isLockdownEnabled(self) -> bool: ...
    def onBind(self, arg0: Intent) -> IBinder: ...
    def onRevoke(self) -> None: ...

    class Builder:
        def __init__(self, arg0: "VpnService") -> None: ...
        def setSession(self, arg0: str) -> "Builder": ...
        def setConfigureIntent(self, arg0: PendingIntent) -> "Builder": ...
        def setMtu(self, arg0: int) -> "Builder": ...
        def setHttpProxy(self, arg0: ProxyInfo) -> "Builder": ...
        @overload
        def addAddress(self, arg0: InetAddress, arg1: int) -> "Builder": ...
        @overload
        def addAddress(self, arg0: str, arg1: int) -> "Builder": ...
        @overload
        def addRoute(self, arg0: InetAddress, arg1: int) -> "Builder": ...
        @overload
        def addRoute(self, arg0: IpPrefix) -> "Builder": ...
        @overload
        def addRoute(self, arg0: str, arg1: int) -> "Builder": ...
        def excludeRoute(self, arg0: IpPrefix) -> "Builder": ...
        @overload
        def addDnsServer(self, arg0: InetAddress) -> "Builder": ...
        @overload
        def addDnsServer(self, arg0: str) -> "Builder": ...
        def addSearchDomain(self, arg0: str) -> "Builder": ...
        def allowFamily(self, arg0: int) -> "Builder": ...
        def addAllowedApplication(self, arg0: str) -> "Builder": ...
        def addDisallowedApplication(self, arg0: str) -> "Builder": ...
        def allowBypass(self) -> "Builder": ...
        def setBlocking(self, arg0: bool) -> "Builder": ...
        def setUnderlyingNetworks(self, arg0: list[Network]) -> "Builder": ...
        def setMetered(self, arg0: bool) -> "Builder": ...
        def establish(self) -> ParcelFileDescriptor: ...
