from typing import Any, ClassVar, overload
from android.content.res.loader.ResourcesProvider import ResourcesProvider

class ResourcesLoader:
    def __init__(self) -> None: ...
    def getProviders(self) -> list: ...
    def addProvider(self, arg0: ResourcesProvider) -> None: ...
    def removeProvider(self, arg0: ResourcesProvider) -> None: ...
    def setProviders(self, arg0: list) -> None: ...
    def clearProviders(self) -> None: ...
