from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.om.OverlayInfo import OverlayInfo
from android.content.res.loader.AssetsProvider import AssetsProvider
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class ResourcesProvider:
    @staticmethod
    def empty(arg0: AssetsProvider) -> "ResourcesProvider": ...
    @staticmethod
    def loadOverlay(arg0: OverlayInfo) -> "ResourcesProvider": ...
    @overload
    @staticmethod
    def loadFromApk(arg0: ParcelFileDescriptor) -> "ResourcesProvider": ...
    @overload
    @staticmethod
    def loadFromApk(arg0: ParcelFileDescriptor, arg1: AssetsProvider) -> "ResourcesProvider": ...
    @staticmethod
    def loadFromTable(arg0: ParcelFileDescriptor, arg1: AssetsProvider) -> "ResourcesProvider": ...
    @staticmethod
    def loadFromSplit(arg0: Context, arg1: str) -> "ResourcesProvider": ...
    @staticmethod
    def loadFromDirectory(arg0: str, arg1: AssetsProvider) -> "ResourcesProvider": ...
    def close(self) -> None: ...
    def finalize(self) -> None: ...
