from typing import Any, ClassVar, overload
from java.security.cert.X509Certificate import X509Certificate

class EapSessionConfig:
    def getEapIdentity(self) -> list[int]: ...
    def getEapSimConfig(self) -> "EapSimConfig": ...
    def getEapAkaConfig(self) -> "EapAkaConfig": ...
    def getEapAkaPrimeConfig(self) -> "EapAkaPrimeConfig": ...
    def getEapMsChapV2Config(self) -> "EapMsChapV2Config": ...
    def getEapTtlsConfig(self) -> "EapTtlsConfig": ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setEapIdentity(self, arg0: list[int]) -> "Builder": ...
        def setEapSimConfig(self, arg0: int, arg1: int) -> "Builder": ...
        @overload
        def setEapAkaConfig(self, arg0: int, arg1: int) -> "Builder": ...
        @overload
        def setEapAkaConfig(self, arg0: int, arg1: int, arg2: "EapAkaOption") -> "Builder": ...
        def setEapAkaPrimeConfig(self, arg0: int, arg1: int, arg2: str, arg3: bool) -> "Builder": ...
        def setEapMsChapV2Config(self, arg0: str, arg1: str) -> "Builder": ...
        def setEapTtlsConfig(self, arg0: X509Certificate, arg1: "EapSessionConfig") -> "Builder": ...
        def build(self) -> "EapSessionConfig": ...

    class EapAkaConfig:
        def getEapAkaOption(self) -> "EapAkaOption": ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def getSubId(self) -> int: ...
        def getAppType(self) -> int: ...

    class EapAkaOption:
        def getReauthId(self) -> list[int]: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...

        class Builder:
            def __init__(self) -> None: ...
            def setReauthId(self, arg0: list[int]) -> "Builder": ...
            def build(self) -> "EapAkaOption": ...

    class EapAkaPrimeConfig:
        def getNetworkName(self) -> str: ...
        def allowsMismatchedNetworkNames(self) -> bool: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...

    class EapMethodConfig:
        EAP_TYPE_AKA: ClassVar[int]
        EAP_TYPE_AKA_PRIME: ClassVar[int]
        EAP_TYPE_MSCHAP_V2: ClassVar[int]
        EAP_TYPE_SIM: ClassVar[int]
        EAP_TYPE_TTLS: ClassVar[int]
        def getMethodType(self) -> int: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...

    class EapMsChapV2Config:
        def getUsername(self) -> str: ...
        def getPassword(self) -> str: ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...

    class EapSimConfig:
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
        def getSubId(self) -> int: ...
        def getAppType(self) -> int: ...

    class EapTtlsConfig:
        def getServerCaCert(self) -> X509Certificate: ...
        def getInnerEapSessionConfig(self) -> "EapSessionConfig": ...
        def hashCode(self) -> int: ...
        def equals(self, arg0: Any) -> bool: ...
