from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class AggregateRecordsGroupedByDurationResponse:
    def getStartTime(self) -> Instant: ...
    def getEndTime(self) -> Instant: ...
    def get(self, arg0: AggregationType) -> Any: ...
    def getZoneOffset(self, arg0: AggregationType) -> ZoneOffset: ...
    def getDataOrigins(self, arg0: AggregationType) -> set: ...
