from typing import Any, ClassVar, overload
from java.time.Instant import Instant

class TimeInstantRangeFilter:
    def getStartTime(self) -> Instant: ...
    def getEndTime(self) -> Instant: ...
    def isBounded(self) -> bool: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setStartTime(self, arg0: Instant) -> "Builder": ...
        def setEndTime(self, arg0: Instant) -> "Builder": ...
        def build(self) -> "TimeInstantRangeFilter": ...
