from typing import Any, ClassVar, overload
from android.content.pm.SigningInfo import SigningInfo

class ArchivedPackageInfo:
    def __init__(self, arg0: str, arg1: SigningInfo, arg2: list) -> None: ...
    def getPackageName(self) -> str: ...
    def getSigningInfo(self) -> SigningInfo: ...
    def getVersionCode(self) -> int: ...
    def getVersionCodeMajor(self) -> int: ...
    def getTargetSdkVersion(self) -> int: ...
    def getDefaultToDeviceProtectedStorage(self) -> str: ...
    def getRequestLegacyExternalStorage(self) -> str: ...
    def getUserDataFragile(self) -> str: ...
    def getLauncherActivities(self) -> list: ...
    def setPackageName(self, arg0: str) -> "ArchivedPackageInfo": ...
    def setSigningInfo(self, arg0: SigningInfo) -> "ArchivedPackageInfo": ...
    def setVersionCode(self, arg0: int) -> "ArchivedPackageInfo": ...
    def setVersionCodeMajor(self, arg0: int) -> "ArchivedPackageInfo": ...
    def setTargetSdkVersion(self, arg0: int) -> "ArchivedPackageInfo": ...
    def setDefaultToDeviceProtectedStorage(self, arg0: str) -> "ArchivedPackageInfo": ...
    def setRequestLegacyExternalStorage(self, arg0: str) -> "ArchivedPackageInfo": ...
    def setUserDataFragile(self, arg0: str) -> "ArchivedPackageInfo": ...
    def setLauncherActivities(self, arg0: list) -> "ArchivedPackageInfo": ...
