from typing import Any, ClassVar, overload
from android.content.pm.ApplicationInfo import ApplicationInfo
from android.os.Parcel import Parcel
from android.util.Printer import Printer

class ComponentInfo:
    applicationInfo: ApplicationInfo
    attributionTags: list[str]
    descriptionRes: int
    directBootAware: bool
    enabled: bool
    exported: bool
    processName: str
    splitName: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: "ComponentInfo") -> None: ...
    @overload
    def __init__(self, arg0: Parcel) -> None: ...
    def isEnabled(self) -> bool: ...
    def getIconResource(self) -> int: ...
    def getLogoResource(self) -> int: ...
    def getBannerResource(self) -> int: ...
    def dumpFront(self, arg0: Printer, arg1: str) -> None: ...
    def dumpBack(self, arg0: Printer, arg1: str) -> None: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
