from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.ComponentName import ComponentName
from android.content.Intent import Intent
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.os.UserHandle import UserHandle

class CrossProfileApps:
    ACTION_CAN_INTERACT_ACROSS_PROFILES_CHANGED: ClassVar[str]
    @overload
    def startMainActivity(self, arg0: ComponentName, arg1: UserHandle) -> None: ...
    @overload
    def startMainActivity(self, arg0: ComponentName, arg1: UserHandle, arg2: Activity, arg3: Bundle) -> None: ...
    @overload
    def startActivity(self, arg0: Intent, arg1: UserHandle, arg2: Activity) -> None: ...
    @overload
    def startActivity(self, arg0: Intent, arg1: UserHandle, arg2: Activity, arg3: Bundle) -> None: ...
    def getTargetUserProfiles(self) -> list: ...
    def isProfile(self, arg0: UserHandle) -> bool: ...
    def isManagedProfile(self, arg0: UserHandle) -> bool: ...
    def getProfileSwitchingLabel(self, arg0: UserHandle) -> str: ...
    def getProfileSwitchingIconDrawable(self, arg0: UserHandle) -> Drawable: ...
    def canRequestInteractAcrossProfiles(self) -> bool: ...
    def canInteractAcrossProfiles(self) -> bool: ...
    def createRequestInteractAcrossProfilesIntent(self) -> Intent: ...
