from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.Intent import Intent
from android.content.IntentSender import IntentSender
from android.content.pm.ArchivedPackageInfo import ArchivedPackageInfo
from android.content.pm.VersionedPackage import VersionedPackage
from android.graphics.Bitmap import Bitmap
from android.icu.util.ULocale import ULocale
from android.net.Uri import Uri
from android.os.Handler import Handler
from android.os.Parcel import Parcel
from android.os.PersistableBundle import PersistableBundle
from android.os.UserHandle import UserHandle
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...
class OnChecksumsReadyListener:
    """Forward declaration for ``android.content.pm.PackageManager.OnChecksumsReadyListener``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.content.pm.PackageManager.OnChecksumsReadyListener')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/content/pm/PackageManager/OnChecksumsReadyListener
    """
    ...

class PackageInstaller:
    ACTION_SESSION_COMMITTED: ClassVar[str]
    ACTION_SESSION_DETAILS: ClassVar[str]
    ACTION_SESSION_UPDATED: ClassVar[str]
    EXTRA_INSTALL_CONSTRAINTS: ClassVar[str]
    EXTRA_INSTALL_CONSTRAINTS_RESULT: ClassVar[str]
    EXTRA_OTHER_PACKAGE_NAME: ClassVar[str]
    EXTRA_PACKAGE_NAME: ClassVar[str]
    EXTRA_PRE_APPROVAL: ClassVar[str]
    EXTRA_SESSION: ClassVar[str]
    EXTRA_SESSION_ID: ClassVar[str]
    EXTRA_STATUS: ClassVar[str]
    EXTRA_STATUS_MESSAGE: ClassVar[str]
    EXTRA_STORAGE_PATH: ClassVar[str]
    EXTRA_UNARCHIVE_ALL_USERS: ClassVar[str]
    EXTRA_UNARCHIVE_ID: ClassVar[str]
    EXTRA_UNARCHIVE_PACKAGE_NAME: ClassVar[str]
    EXTRA_UNARCHIVE_STATUS: ClassVar[str]
    PACKAGE_SOURCE_DOWNLOADED_FILE: ClassVar[int]
    PACKAGE_SOURCE_LOCAL_FILE: ClassVar[int]
    PACKAGE_SOURCE_OTHER: ClassVar[int]
    PACKAGE_SOURCE_STORE: ClassVar[int]
    PACKAGE_SOURCE_UNSPECIFIED: ClassVar[int]
    STATUS_FAILURE: ClassVar[int]
    STATUS_FAILURE_ABORTED: ClassVar[int]
    STATUS_FAILURE_BLOCKED: ClassVar[int]
    STATUS_FAILURE_CONFLICT: ClassVar[int]
    STATUS_FAILURE_INCOMPATIBLE: ClassVar[int]
    STATUS_FAILURE_INVALID: ClassVar[int]
    STATUS_FAILURE_STORAGE: ClassVar[int]
    STATUS_FAILURE_TIMEOUT: ClassVar[int]
    STATUS_PENDING_USER_ACTION: ClassVar[int]
    STATUS_SUCCESS: ClassVar[int]
    UNARCHIVAL_ERROR_INSTALLER_DISABLED: ClassVar[int]
    UNARCHIVAL_ERROR_INSTALLER_UNINSTALLED: ClassVar[int]
    UNARCHIVAL_ERROR_INSUFFICIENT_STORAGE: ClassVar[int]
    UNARCHIVAL_ERROR_NO_CONNECTIVITY: ClassVar[int]
    UNARCHIVAL_ERROR_USER_ACTION_NEEDED: ClassVar[int]
    UNARCHIVAL_GENERIC_ERROR: ClassVar[int]
    UNARCHIVAL_OK: ClassVar[int]
    def createSession(self, arg0: "SessionParams") -> int: ...
    def openSession(self, arg0: int) -> "Session": ...
    def updateSessionAppIcon(self, arg0: int, arg1: Bitmap) -> None: ...
    def updateSessionAppLabel(self, arg0: int, arg1: str) -> None: ...
    def abandonSession(self, arg0: int) -> None: ...
    def getSessionInfo(self, arg0: int) -> "SessionInfo": ...
    def getAllSessions(self) -> list: ...
    def getMySessions(self) -> list: ...
    def getStagedSessions(self) -> list: ...
    def getActiveStagedSession(self) -> "SessionInfo": ...
    def getActiveStagedSessions(self) -> list: ...
    @overload
    def uninstall(self, arg0: str, arg1: IntentSender) -> None: ...
    @overload
    def uninstall(self, arg0: VersionedPackage, arg1: IntentSender) -> None: ...
    @overload
    def uninstall(self, arg0: VersionedPackage, arg1: int, arg2: IntentSender) -> None: ...
    def installExistingPackage(self, arg0: str, arg1: int, arg2: IntentSender) -> None: ...
    def uninstallExistingPackage(self, arg0: str, arg1: IntentSender) -> None: ...
    def installPackageArchived(self, arg0: ArchivedPackageInfo, arg1: "SessionParams", arg2: IntentSender) -> None: ...
    def checkInstallConstraints(self, arg0: list, arg1: "InstallConstraints", arg2: Executor, arg3: Consumer) -> None: ...
    def waitForInstallConstraints(self, arg0: list, arg1: "InstallConstraints", arg2: IntentSender, arg3: int) -> None: ...
    def commitSessionAfterInstallConstraintsAreMet(self, arg0: int, arg1: IntentSender, arg2: "InstallConstraints", arg3: int) -> None: ...
    @overload
    def registerSessionCallback(self, arg0: "SessionCallback") -> None: ...
    @overload
    def registerSessionCallback(self, arg0: "SessionCallback", arg1: Handler) -> None: ...
    def unregisterSessionCallback(self, arg0: "SessionCallback") -> None: ...
    def requestArchive(self, arg0: str, arg1: IntentSender) -> None: ...
    def requestUnarchive(self, arg0: str, arg1: IntentSender) -> None: ...
    def reportUnarchivalStatus(self, arg0: int, arg1: int, arg2: int, arg3: PendingIntent) -> None: ...
    def reportUnarchivalState(self, arg0: "UnarchivalState") -> None: ...

    class InstallConstraints:
        CREATOR: ClassVar[Creator]
        GENTLE_UPDATE: ClassVar["InstallConstraints"]
        def isDeviceIdleRequired(self) -> bool: ...
        def isAppNotForegroundRequired(self) -> bool: ...
        def isAppNotInteractingRequired(self) -> bool: ...
        def isAppNotTopVisibleRequired(self) -> bool: ...
        def isNotInCallRequired(self) -> bool: ...
        def equals(self, arg0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def describeContents(self) -> int: ...

        class Builder:
            def __init__(self) -> None: ...
            def setDeviceIdleRequired(self) -> "Builder": ...
            def setAppNotForegroundRequired(self) -> "Builder": ...
            def setAppNotInteractingRequired(self) -> "Builder": ...
            def setAppNotTopVisibleRequired(self) -> "Builder": ...
            def setNotInCallRequired(self) -> "Builder": ...
            def build(self) -> "InstallConstraints": ...

    class InstallConstraintsResult:
        CREATOR: ClassVar[Creator]
        def areAllConstraintsSatisfied(self) -> bool: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def describeContents(self) -> int: ...

    class PreapprovalDetails:
        CREATOR: ClassVar[Creator]
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getIcon(self) -> Bitmap: ...
        def getLabel(self) -> str: ...
        def getLocale(self) -> ULocale: ...
        def getPackageName(self) -> str: ...
        def toString(self) -> str: ...

        class Builder:
            def __init__(self) -> None: ...
            def setIcon(self, arg0: Bitmap) -> "Builder": ...
            def setLabel(self, arg0: str) -> "Builder": ...
            def setLocale(self, arg0: ULocale) -> "Builder": ...
            def setPackageName(self, arg0: str) -> "Builder": ...
            def build(self) -> "PreapprovalDetails": ...

    class Session:
        def setStagingProgress(self, arg0: float) -> None: ...
        def openWrite(self, arg0: str, arg1: int, arg2: int) -> OutputStream: ...
        def fsync(self, arg0: OutputStream) -> None: ...
        def getNames(self) -> list[str]: ...
        def openRead(self, arg0: str) -> InputStream: ...
        def removeSplit(self, arg0: str) -> None: ...
        def setChecksums(self, arg0: str, arg1: list, arg2: list[int]) -> None: ...
        def requestChecksums(self, arg0: str, arg1: int, arg2: list, arg3: Executor, arg4: OnChecksumsReadyListener) -> None: ...
        def commit(self, arg0: IntentSender) -> None: ...
        def transfer(self, arg0: str) -> None: ...
        def close(self) -> None: ...
        def abandon(self) -> None: ...
        def isMultiPackage(self) -> bool: ...
        def isStaged(self) -> bool: ...
        def getParentSessionId(self) -> int: ...
        def getChildSessionIds(self) -> list[int]: ...
        def addChildSessionId(self, arg0: int) -> None: ...
        def removeChildSessionId(self, arg0: int) -> None: ...
        def getAppMetadata(self) -> PersistableBundle: ...
        def setAppMetadata(self, arg0: PersistableBundle) -> None: ...
        def requestUserPreapproval(self, arg0: "PreapprovalDetails", arg1: IntentSender) -> None: ...
        def isApplicationEnabledSettingPersistent(self) -> bool: ...
        def isRequestUpdateOwnership(self) -> bool: ...

    class SessionCallback:
        def __init__(self) -> None: ...
        def onCreated(self, arg0: int) -> None: ...
        def onBadgingChanged(self, arg0: int) -> None: ...
        def onActiveChanged(self, arg0: int, arg1: bool) -> None: ...
        def onProgressChanged(self, arg0: int, arg1: float) -> None: ...
        def onFinished(self, arg0: int, arg1: bool) -> None: ...

    class SessionInfo:
        CREATOR: ClassVar[Creator]
        INVALID_ID: ClassVar[int]
        SESSION_ACTIVATION_FAILED: ClassVar[int]
        SESSION_CONFLICT: ClassVar[int]
        SESSION_NO_ERROR: ClassVar[int]
        SESSION_UNKNOWN_ERROR: ClassVar[int]
        SESSION_VERIFICATION_FAILED: ClassVar[int]
        STAGED_SESSION_ACTIVATION_FAILED: ClassVar[int]
        STAGED_SESSION_CONFLICT: ClassVar[int]
        STAGED_SESSION_NO_ERROR: ClassVar[int]
        STAGED_SESSION_UNKNOWN: ClassVar[int]
        STAGED_SESSION_VERIFICATION_FAILED: ClassVar[int]
        def getSessionId(self) -> int: ...
        def getUser(self) -> UserHandle: ...
        def getInstallerPackageName(self) -> str: ...
        def getInstallerAttributionTag(self) -> str: ...
        def getProgress(self) -> float: ...
        def isActive(self) -> bool: ...
        def isSealed(self) -> bool: ...
        def getInstallReason(self) -> int: ...
        def getAppPackageName(self) -> str: ...
        def getAppIcon(self) -> Bitmap: ...
        def getAppLabel(self) -> str: ...
        def createDetailsIntent(self) -> Intent: ...
        def getMode(self) -> int: ...
        def getInstallLocation(self) -> int: ...
        def getSize(self) -> int: ...
        def getOriginatingUri(self) -> Uri: ...
        def getOriginatingUid(self) -> int: ...
        def getReferrerUri(self) -> Uri: ...
        def getDontKillApp(self) -> bool: ...
        def getPackageSource(self) -> int: ...
        def isMultiPackage(self) -> bool: ...
        def isStaged(self) -> bool: ...
        def isStagedSessionActive(self) -> bool: ...
        def getParentSessionId(self) -> int: ...
        def hasParentSessionId(self) -> bool: ...
        def getChildSessionIds(self) -> list[int]: ...
        def isStagedSessionApplied(self) -> bool: ...
        def isStagedSessionReady(self) -> bool: ...
        def isStagedSessionFailed(self) -> bool: ...
        def getStagedSessionErrorCode(self) -> int: ...
        def getStagedSessionErrorMessage(self) -> str: ...
        def isCommitted(self) -> bool: ...
        def getCreatedMillis(self) -> int: ...
        def getUpdatedMillis(self) -> int: ...
        def getRequireUserAction(self) -> int: ...
        def getInstallerUid(self) -> int: ...
        def isApplicationEnabledSettingPersistent(self) -> bool: ...
        def isPreApprovalRequested(self) -> bool: ...
        def isRequestUpdateOwnership(self) -> bool: ...
        def isUnarchival(self) -> bool: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class SessionParams:
        CREATOR: ClassVar[Creator]
        MODE_FULL_INSTALL: ClassVar[int]
        MODE_INHERIT_EXISTING: ClassVar[int]
        PERMISSION_STATE_DEFAULT: ClassVar[int]
        PERMISSION_STATE_DENIED: ClassVar[int]
        PERMISSION_STATE_GRANTED: ClassVar[int]
        RESTRICTED_PERMISSIONS_ALL: ClassVar[set]
        USER_ACTION_NOT_REQUIRED: ClassVar[int]
        USER_ACTION_REQUIRED: ClassVar[int]
        USER_ACTION_UNSPECIFIED: ClassVar[int]
        def __init__(self, arg0: int) -> None: ...
        def setInstallLocation(self, arg0: int) -> None: ...
        def setSize(self, arg0: int) -> None: ...
        def setAppPackageName(self, arg0: str) -> None: ...
        def setAppIcon(self, arg0: Bitmap) -> None: ...
        def setAppLabel(self, arg0: str) -> None: ...
        def setOriginatingUri(self, arg0: Uri) -> None: ...
        def setOriginatingUid(self, arg0: int) -> None: ...
        def setReferrerUri(self, arg0: Uri) -> None: ...
        def setPermissionState(self, arg0: str, arg1: int) -> "SessionParams": ...
        def setPackageSource(self, arg0: int) -> None: ...
        def setWhitelistedRestrictedPermissions(self, arg0: set) -> None: ...
        def setAutoRevokePermissionsMode(self, arg0: bool) -> None: ...
        def setDontKillApp(self, arg0: bool) -> None: ...
        def setInstallReason(self, arg0: int) -> None: ...
        def setInstallerPackageName(self, arg0: str) -> None: ...
        def setMultiPackage(self) -> None: ...
        def setRequireUserAction(self, arg0: int) -> None: ...
        def setInstallScenario(self, arg0: int) -> None: ...
        def setApplicationEnabledSettingPersistent(self) -> None: ...
        def setRequestUpdateOwnership(self, arg0: bool) -> None: ...
        def setUnarchiveId(self, arg0: int) -> None: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...

    class UnarchivalState:
        @staticmethod
        def createOkState(arg0: int) -> "UnarchivalState": ...
        @staticmethod
        def createUserActionRequiredState(arg0: int, arg1: PendingIntent) -> "UnarchivalState": ...
        @staticmethod
        def createInsufficientStorageState(arg0: int, arg1: int, arg2: PendingIntent) -> "UnarchivalState": ...
        @staticmethod
        def createNoConnectivityState(arg0: int) -> "UnarchivalState": ...
        @staticmethod
        def createGenericErrorState(arg0: int) -> "UnarchivalState": ...
