"""
Google AdMob (play-services-ads-api 25.3.0) — pyjnius usage example.

The wrappers in src/admob_pyjnius/ are auto-generated by pyjnius-wrap from
play-services-ads-api-25.3.0.aar bytecode.

Regenerate with:
    swift run pyjnius-wrap play-services-ads-api-25.3.0.aar src/admob_pyjnius/

On-device only (requires Android + pyjnius).
"""

from jnius import PythonJavaClass, java_method

from admob_pyjnius.com.google.android.gms.ads.MobileAds import MobileAds
from admob_pyjnius.com.google.android.gms.ads.AdRequest import AdRequest
from admob_pyjnius.com.google.android.gms.ads.AdView import AdView
from admob_pyjnius.com.google.android.gms.ads.AdSize import AdSize
from admob_pyjnius.com.google.android.gms.ads.AdListener import AdListener
from admob_pyjnius.com.google.android.gms.ads.LoadAdError import LoadAdError
from admob_pyjnius.com.google.android.gms.ads.FullScreenContentCallback import FullScreenContentCallback
from admob_pyjnius.com.google.android.gms.ads.interstitial.InterstitialAd import InterstitialAd
from admob_pyjnius.com.google.android.gms.ads.interstitial.InterstitialAdLoadCallback import InterstitialAdLoadCallback
from admob_pyjnius.com.google.android.gms.ads.rewarded.RewardedAd import RewardedAd
from admob_pyjnius.com.google.android.gms.ads.rewarded.RewardedAdLoadCallback import RewardedAdLoadCallback


def init_admob(context) -> None:
    MobileAds.initialize(context)


def build_ad_request():
    return AdRequest.Builder().build()


# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------

class MyAdListener(PythonJavaClass):
    __javainterfaces__ = ["com/google/android/gms/ads/AdListener"]

    def __init__(self, on_loaded=None, on_failed=None):
        self._on_loaded = on_loaded
        self._on_failed = on_failed
        super().__init__()

    @java_method("()V")
    def onAdLoaded(self):
        if self._on_loaded:
            self._on_loaded()

    @java_method("(Lcom/google/android/gms/ads/LoadAdError;)V")
    def onAdFailedToLoad(self, error):
        if self._on_failed:
            self._on_failed(str(error.getMessage()))


def load_banner(context, ad_unit_id: str, on_loaded=None, on_failed=None) -> AdView:
    banner = AdView(context)
    banner.setAdUnitId(ad_unit_id)
    banner.setAdSize(AdSize.BANNER)
    banner.setAdListener(MyAdListener(on_loaded, on_failed))
    banner.loadAd(build_ad_request())
    return banner


# ---------------------------------------------------------------------------
# Interstitial
# ---------------------------------------------------------------------------

class MyInterstitialLoadCallback(PythonJavaClass):
    __javainterfaces__ = ["com/google/android/gms/ads/interstitial/InterstitialAdLoadCallback"]

    def __init__(self, on_loaded=None, on_failed=None):
        self._on_loaded = on_loaded
        self._on_failed = on_failed
        super().__init__()

    @java_method("(Lcom/google/android/gms/ads/interstitial/InterstitialAd;)V")
    def onAdLoaded(self, ad):
        if self._on_loaded:
            self._on_loaded(ad)

    @java_method("(Lcom/google/android/gms/ads/LoadAdError;)V")
    def onAdFailedToLoad(self, error):
        if self._on_failed:
            self._on_failed(str(error.getMessage()))


def load_interstitial(context, ad_unit_id: str, on_loaded=None, on_failed=None) -> None:
    InterstitialAd.load(context, ad_unit_id, build_ad_request(),
                        MyInterstitialLoadCallback(on_loaded, on_failed))


# ---------------------------------------------------------------------------
# Rewarded
# ---------------------------------------------------------------------------

class MyRewardedLoadCallback(PythonJavaClass):
    __javainterfaces__ = ["com/google/android/gms/ads/rewarded/RewardedAdLoadCallback"]

    def __init__(self, on_loaded=None, on_failed=None):
        self._on_loaded = on_loaded
        self._on_failed = on_failed
        super().__init__()

    @java_method("(Lcom/google/android/gms/ads/rewarded/RewardedAd;)V")
    def onAdLoaded(self, ad):
        if self._on_loaded:
            self._on_loaded(ad)

    @java_method("(Lcom/google/android/gms/ads/LoadAdError;)V")
    def onAdFailedToLoad(self, error):
        if self._on_failed:
            self._on_failed(str(error.getMessage()))


def load_rewarded(context, ad_unit_id: str, on_loaded=None, on_failed=None) -> None:
    RewardedAd.load(context, ad_unit_id, build_ad_request(),
                    MyRewardedLoadCallback(on_loaded, on_failed))
