from typing import Any, ClassVar, overload
from org.xml.sax.ContentHandler import ContentHandler
from org.xml.sax.ext.LexicalHandler import LexicalHandler

class SAXResult:
    FEATURE: ClassVar[str]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: ContentHandler) -> None: ...
    def setHandler(self, arg0: ContentHandler) -> None: ...
    def getHandler(self) -> ContentHandler: ...
    def setLexicalHandler(self, arg0: LexicalHandler) -> None: ...
    def getLexicalHandler(self) -> LexicalHandler: ...
    def setSystemId(self, arg0: str) -> None: ...
    def getSystemId(self) -> str: ...
