from typing import Any, ClassVar, overload
from javax.xml.transform.Templates import Templates

class TemplatesHandler:
    def getTemplates(self) -> Templates: ...
    def setSystemId(self, arg0: str) -> None: ...
    def getSystemId(self) -> str: ...
