from typing import Any, ClassVar, overload
from javax.xml.transform.Result import Result
from javax.xml.transform.Transformer import Transformer

class TransformerHandler:
    def setResult(self, arg0: Result) -> None: ...
    def setSystemId(self, arg0: str) -> None: ...
    def getSystemId(self) -> str: ...
    def getTransformer(self) -> Transformer: ...
