from typing import Any, ClassVar, overload

class RestoreObserver:
    def __init__(self) -> None: ...
    def restoreStarting(self, arg0: int) -> None: ...
    def onUpdate(self, arg0: int, arg1: str) -> None: ...
    def restoreFinished(self, arg0: int) -> None: ...
