from typing import Any, ClassVar, overload

class ChildSessionConfiguration:
    def getInboundTrafficSelectors(self) -> list: ...
    def getOutboundTrafficSelectors(self) -> list: ...

    class Builder:
        def __init__(self, arg0: list, arg1: list) -> None: ...
        def build(self) -> "ChildSessionConfiguration": ...
