from typing import Any, ClassVar, overload

class IkeRfc822AddrIdentification:
    rfc822Name: str
    def __init__(self, arg0: str) -> None: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
