from typing import Any, ClassVar, overload

class IkeSaProposal:
    @staticmethod
    def getSupportedEncryptionAlgorithms() -> set: ...
    @staticmethod
    def getSupportedIntegrityAlgorithms() -> set: ...
    @staticmethod
    def getSupportedPseudorandomFunctions() -> set: ...
    def getPseudorandomFunctions(self) -> list: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def addEncryptionAlgorithm(self, arg0: int, arg1: int) -> "Builder": ...
        def addIntegrityAlgorithm(self, arg0: int) -> "Builder": ...
        def addDhGroup(self, arg0: int) -> "Builder": ...
        def addPseudorandomFunction(self, arg0: int) -> "Builder": ...
        def build(self) -> "IkeSaProposal": ...
