from typing import Any, ClassVar, overload
from android.net.ipsec.ike.IkeSessionConfiguration import IkeSessionConfiguration
from android.net.ipsec.ike.exceptions.IkeException import IkeException

class IkeSessionCallback:
    def onOpened(self, arg0: IkeSessionConfiguration) -> None: ...
    def onClosed(self) -> None: ...
    def onClosedWithException(self, arg0: IkeException) -> None: ...
    def onError(self, arg0: IkeException) -> None: ...
