from typing import Any, ClassVar, overload
from android.net.ipsec.ike.IkeSessionParams import IkeSessionParams
from android.net.ipsec.ike.TunnelModeChildSessionParams import TunnelModeChildSessionParams

class IkeTunnelConnectionParams:
    def __init__(self, arg0: IkeSessionParams, arg1: TunnelModeChildSessionParams) -> None: ...
    def getIkeSessionParams(self) -> IkeSessionParams: ...
    def getTunnelModeChildSessionParams(self) -> TunnelModeChildSessionParams: ...
    def hashCode(self) -> int: ...
    def equals(self, arg0: Any) -> bool: ...
