from typing import Any, ClassVar, overload
from android.net.ipsec.ike.ChildSaProposal import ChildSaProposal
from android.net.ipsec.ike.IkeTrafficSelector import IkeTrafficSelector

class TransportModeChildSessionParams:

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: "TransportModeChildSessionParams") -> None: ...
        def addChildSaProposal(self, arg0: ChildSaProposal) -> "Builder": ...
        def addInboundTrafficSelectors(self, arg0: IkeTrafficSelector) -> "Builder": ...
        def addOutboundTrafficSelectors(self, arg0: IkeTrafficSelector) -> "Builder": ...
        def setLifetimeSeconds(self, arg0: int, arg1: int) -> "Builder": ...
        def build(self) -> "TransportModeChildSessionParams": ...
