from typing import Any, ClassVar, overload

class SourceLocator:
    def getPublicId(self) -> str: ...
    def getSystemId(self) -> str: ...
    def getLineNumber(self) -> int: ...
    def getColumnNumber(self) -> int: ...
