from typing import Any, ClassVar, overload
from java.lang.ClassLoader import ClassLoader
from javax.xml.transform.ErrorListener import ErrorListener
from javax.xml.transform.Source import Source
from javax.xml.transform.Templates import Templates
from javax.xml.transform.Transformer import Transformer
from javax.xml.transform.URIResolver import URIResolver

class TransformerFactory:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def newInstance() -> "TransformerFactory": ...
    @overload
    @staticmethod
    def newInstance(arg0: str, arg1: ClassLoader) -> "TransformerFactory": ...
    @overload
    def newTransformer(self, arg0: Source) -> Transformer: ...
    @overload
    def newTransformer(self) -> Transformer: ...
    def newTemplates(self, arg0: Source) -> Templates: ...
    def getAssociatedStylesheet(self, arg0: Source, arg1: str, arg2: str, arg3: str) -> Source: ...
    def setURIResolver(self, arg0: URIResolver) -> None: ...
    def getURIResolver(self) -> URIResolver: ...
    def setFeature(self, arg0: str, arg1: bool) -> None: ...
    def getFeature(self, arg0: str) -> bool: ...
    def setAttribute(self, arg0: str, arg1: Any) -> None: ...
    def getAttribute(self, arg0: str) -> Any: ...
    def setErrorListener(self, arg0: ErrorListener) -> None: ...
    def getErrorListener(self) -> ErrorListener: ...
