from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["CompletableFuture"]

class CompletableFuture(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/concurrent/CompletableFuture"
    __javaconstructor__ = [("()V", False)]
    supplyAsync = JavaMultipleMethod([("(Ljava/util/function/Supplier;)Ljava/util/concurrent/CompletableFuture;", True, False), ("(Ljava/util/function/Supplier;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", True, False)])
    runAsync = JavaMultipleMethod([("(Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;", True, False), ("(Ljava/lang/Runnable;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", True, False)])
    completedFuture = JavaStaticMethod("(Ljava/lang/Object;)Ljava/util/concurrent/CompletableFuture;")
    isDone = JavaMethod("()Z")
    get = JavaMultipleMethod([("()Ljava/lang/Object;", False, False), ("(JLjava/util/concurrent/TimeUnit;)Ljava/lang/Object;", False, False)])
    join = JavaMethod("()Ljava/lang/Object;")
    getNow = JavaMethod("(Ljava/lang/Object;)Ljava/lang/Object;")
    complete = JavaMethod("(Ljava/lang/Object;)Z")
    completeExceptionally = JavaMethod("(Ljava/lang/Throwable;)Z")
    thenApply = JavaMethod("(Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;")
    thenApplyAsync = JavaMultipleMethod([("(Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/function/Function;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    thenAccept = JavaMethod("(Ljava/util/function/Consumer;)Ljava/util/concurrent/CompletableFuture;")
    thenAcceptAsync = JavaMultipleMethod([("(Ljava/util/function/Consumer;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/function/Consumer;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    thenRun = JavaMethod("(Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;")
    thenRunAsync = JavaMultipleMethod([("(Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/lang/Runnable;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    thenCombine = JavaMethod("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/BiFunction;)Ljava/util/concurrent/CompletableFuture;")
    thenCombineAsync = JavaMultipleMethod([("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/BiFunction;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/BiFunction;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    thenAcceptBoth = JavaMethod("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/BiConsumer;)Ljava/util/concurrent/CompletableFuture;")
    thenAcceptBothAsync = JavaMultipleMethod([("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/BiConsumer;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/BiConsumer;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    runAfterBoth = JavaMethod("(Ljava/util/concurrent/CompletionStage;Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;")
    runAfterBothAsync = JavaMultipleMethod([("(Ljava/util/concurrent/CompletionStage;Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/concurrent/CompletionStage;Ljava/lang/Runnable;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    applyToEither = JavaMethod("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;")
    applyToEitherAsync = JavaMultipleMethod([("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/Function;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    acceptEither = JavaMethod("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/Consumer;)Ljava/util/concurrent/CompletableFuture;")
    acceptEitherAsync = JavaMultipleMethod([("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/Consumer;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/concurrent/CompletionStage;Ljava/util/function/Consumer;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    runAfterEither = JavaMethod("(Ljava/util/concurrent/CompletionStage;Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;")
    runAfterEitherAsync = JavaMultipleMethod([("(Ljava/util/concurrent/CompletionStage;Ljava/lang/Runnable;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/concurrent/CompletionStage;Ljava/lang/Runnable;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    thenCompose = JavaMethod("(Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;")
    thenComposeAsync = JavaMultipleMethod([("(Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/function/Function;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    whenComplete = JavaMethod("(Ljava/util/function/BiConsumer;)Ljava/util/concurrent/CompletableFuture;")
    whenCompleteAsync = JavaMultipleMethod([("(Ljava/util/function/BiConsumer;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/function/BiConsumer;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    handle = JavaMethod("(Ljava/util/function/BiFunction;)Ljava/util/concurrent/CompletableFuture;")
    handleAsync = JavaMultipleMethod([("(Ljava/util/function/BiFunction;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/function/BiFunction;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    toCompletableFuture = JavaMethod("()Ljava/util/concurrent/CompletableFuture;")
    exceptionally = JavaMethod("(Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;")
    exceptionallyAsync = JavaMultipleMethod([("(Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/function/Function;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    exceptionallyCompose = JavaMethod("(Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;")
    exceptionallyComposeAsync = JavaMultipleMethod([("(Ljava/util/function/Function;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/function/Function;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    allOf = JavaStaticMethod("([Ljava/util/concurrent/CompletableFuture;)Ljava/util/concurrent/CompletableFuture;", varargs=True)
    anyOf = JavaStaticMethod("([Ljava/util/concurrent/CompletableFuture;)Ljava/util/concurrent/CompletableFuture;", varargs=True)
    cancel = JavaMethod("(Z)Z")
    isCancelled = JavaMethod("()Z")
    isCompletedExceptionally = JavaMethod("()Z")
    obtrudeValue = JavaMethod("(Ljava/lang/Object;)V")
    obtrudeException = JavaMethod("(Ljava/lang/Throwable;)V")
    getNumberOfDependents = JavaMethod("()I")
    toString = JavaMethod("()Ljava/lang/String;")
    newIncompleteFuture = JavaMethod("()Ljava/util/concurrent/CompletableFuture;")
    defaultExecutor = JavaMethod("()Ljava/util/concurrent/Executor;")
    copy = JavaMethod("()Ljava/util/concurrent/CompletableFuture;")
    minimalCompletionStage = JavaMethod("()Ljava/util/concurrent/CompletionStage;")
    completeAsync = JavaMultipleMethod([("(Ljava/util/function/Supplier;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture;", False, False), ("(Ljava/util/function/Supplier;)Ljava/util/concurrent/CompletableFuture;", False, False)])
    orTimeout = JavaMethod("(JLjava/util/concurrent/TimeUnit;)Ljava/util/concurrent/CompletableFuture;")
    completeOnTimeout = JavaMethod("(Ljava/lang/Object;JLjava/util/concurrent/TimeUnit;)Ljava/util/concurrent/CompletableFuture;")
    delayedExecutor = JavaMultipleMethod([("(JLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/Executor;", True, False), ("(JLjava/util/concurrent/TimeUnit;)Ljava/util/concurrent/Executor;", True, False)])
    completedStage = JavaStaticMethod("(Ljava/lang/Object;)Ljava/util/concurrent/CompletionStage;")
    failedFuture = JavaStaticMethod("(Ljava/lang/Throwable;)Ljava/util/concurrent/CompletableFuture;")
    failedStage = JavaStaticMethod("(Ljava/lang/Throwable;)Ljava/util/concurrent/CompletionStage;")

    class AsynchronousCompletionTask(JavaInterface, metaclass=MetaJavaClass):
        __javaclass__ = "java/util/concurrent/CompletableFuture/AsynchronousCompletionTask"