from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.CompletableFuture import CompletableFuture
from java.util.concurrent.Executor import Executor
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BiFunction import BiFunction
from java.util.function.Consumer import Consumer
from java.util.function.Function import Function

class CompletionStage:
    def thenApply(self, arg0: Function) -> "CompletionStage": ...
    @overload
    def thenApplyAsync(self, arg0: Function) -> "CompletionStage": ...
    @overload
    def thenApplyAsync(self, arg0: Function, arg1: Executor) -> "CompletionStage": ...
    def thenAccept(self, arg0: Consumer) -> "CompletionStage": ...
    @overload
    def thenAcceptAsync(self, arg0: Consumer) -> "CompletionStage": ...
    @overload
    def thenAcceptAsync(self, arg0: Consumer, arg1: Executor) -> "CompletionStage": ...
    def thenRun(self, arg0: Runnable) -> "CompletionStage": ...
    @overload
    def thenRunAsync(self, arg0: Runnable) -> "CompletionStage": ...
    @overload
    def thenRunAsync(self, arg0: Runnable, arg1: Executor) -> "CompletionStage": ...
    def thenCombine(self, arg0: "CompletionStage", arg1: BiFunction) -> "CompletionStage": ...
    @overload
    def thenCombineAsync(self, arg0: "CompletionStage", arg1: BiFunction) -> "CompletionStage": ...
    @overload
    def thenCombineAsync(self, arg0: "CompletionStage", arg1: BiFunction, arg2: Executor) -> "CompletionStage": ...
    def thenAcceptBoth(self, arg0: "CompletionStage", arg1: BiConsumer) -> "CompletionStage": ...
    @overload
    def thenAcceptBothAsync(self, arg0: "CompletionStage", arg1: BiConsumer) -> "CompletionStage": ...
    @overload
    def thenAcceptBothAsync(self, arg0: "CompletionStage", arg1: BiConsumer, arg2: Executor) -> "CompletionStage": ...
    def runAfterBoth(self, arg0: "CompletionStage", arg1: Runnable) -> "CompletionStage": ...
    @overload
    def runAfterBothAsync(self, arg0: "CompletionStage", arg1: Runnable) -> "CompletionStage": ...
    @overload
    def runAfterBothAsync(self, arg0: "CompletionStage", arg1: Runnable, arg2: Executor) -> "CompletionStage": ...
    def applyToEither(self, arg0: "CompletionStage", arg1: Function) -> "CompletionStage": ...
    @overload
    def applyToEitherAsync(self, arg0: "CompletionStage", arg1: Function) -> "CompletionStage": ...
    @overload
    def applyToEitherAsync(self, arg0: "CompletionStage", arg1: Function, arg2: Executor) -> "CompletionStage": ...
    def acceptEither(self, arg0: "CompletionStage", arg1: Consumer) -> "CompletionStage": ...
    @overload
    def acceptEitherAsync(self, arg0: "CompletionStage", arg1: Consumer) -> "CompletionStage": ...
    @overload
    def acceptEitherAsync(self, arg0: "CompletionStage", arg1: Consumer, arg2: Executor) -> "CompletionStage": ...
    def runAfterEither(self, arg0: "CompletionStage", arg1: Runnable) -> "CompletionStage": ...
    @overload
    def runAfterEitherAsync(self, arg0: "CompletionStage", arg1: Runnable) -> "CompletionStage": ...
    @overload
    def runAfterEitherAsync(self, arg0: "CompletionStage", arg1: Runnable, arg2: Executor) -> "CompletionStage": ...
    def thenCompose(self, arg0: Function) -> "CompletionStage": ...
    @overload
    def thenComposeAsync(self, arg0: Function) -> "CompletionStage": ...
    @overload
    def thenComposeAsync(self, arg0: Function, arg1: Executor) -> "CompletionStage": ...
    def handle(self, arg0: BiFunction) -> "CompletionStage": ...
    @overload
    def handleAsync(self, arg0: BiFunction) -> "CompletionStage": ...
    @overload
    def handleAsync(self, arg0: BiFunction, arg1: Executor) -> "CompletionStage": ...
    def whenComplete(self, arg0: BiConsumer) -> "CompletionStage": ...
    @overload
    def whenCompleteAsync(self, arg0: BiConsumer) -> "CompletionStage": ...
    @overload
    def whenCompleteAsync(self, arg0: BiConsumer, arg1: Executor) -> "CompletionStage": ...
    def exceptionally(self, arg0: Function) -> "CompletionStage": ...
    @overload
    def exceptionallyAsync(self, arg0: Function) -> "CompletionStage": ...
    @overload
    def exceptionallyAsync(self, arg0: Function, arg1: Executor) -> "CompletionStage": ...
    def exceptionallyCompose(self, arg0: Function) -> "CompletionStage": ...
    @overload
    def exceptionallyComposeAsync(self, arg0: Function) -> "CompletionStage": ...
    @overload
    def exceptionallyComposeAsync(self, arg0: Function, arg1: Executor) -> "CompletionStage": ...
    def toCompletableFuture(self) -> CompletableFuture: ...
