from typing import Any, ClassVar, overload
from java.util.NavigableSet import NavigableSet

class ConcurrentNavigableMap:
    @overload
    def subMap(self, arg0: Any, arg1: bool, arg2: Any, arg3: bool) -> "ConcurrentNavigableMap": ...
    @overload
    def subMap(self, arg0: Any, arg1: Any) -> "ConcurrentNavigableMap": ...
    @overload
    def headMap(self, arg0: Any, arg1: bool) -> "ConcurrentNavigableMap": ...
    @overload
    def headMap(self, arg0: Any) -> "ConcurrentNavigableMap": ...
    @overload
    def tailMap(self, arg0: Any, arg1: bool) -> "ConcurrentNavigableMap": ...
    @overload
    def tailMap(self, arg0: Any) -> "ConcurrentNavigableMap": ...
    def descendingMap(self) -> "ConcurrentNavigableMap": ...
    def navigableKeySet(self) -> NavigableSet: ...
    def keySet(self) -> NavigableSet: ...
    def descendingKeySet(self) -> NavigableSet: ...
