from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator
from java.util.Spliterator import Spliterator
from java.util.function.Consumer import Consumer
from java.util.function.Predicate import Predicate

class CopyOnWriteArraySet:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: list) -> None: ...
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def contains(self, arg0: Any) -> bool: ...
    @overload
    def toArray(self) -> list: ...
    @overload
    def toArray(self, arg0: list) -> list: ...
    def clear(self) -> None: ...
    def remove(self, arg0: Any) -> bool: ...
    def add(self, arg0: Any) -> bool: ...
    def containsAll(self, arg0: list) -> bool: ...
    def addAll(self, arg0: list) -> bool: ...
    def removeAll(self, arg0: list) -> bool: ...
    def retainAll(self, arg0: list) -> bool: ...
    def iterator(self) -> Iterator: ...
    def equals(self, arg0: Any) -> bool: ...
    def removeIf(self, arg0: Predicate) -> bool: ...
    def forEach(self, arg0: Consumer) -> None: ...
    def spliterator(self) -> Spliterator: ...
