from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator
from java.util.Iterator import Iterator
from java.util.ListIterator import ListIterator
from java.util.Spliterator import Spliterator
from java.util.function.Consumer import Consumer
from java.util.function.Predicate import Predicate
from java.util.function.UnaryOperator import UnaryOperator

class CopyOnWriteArrayList:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: list) -> None: ...
    @overload
    def __init__(self, arg0: list) -> None: ...
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def contains(self, arg0: Any) -> bool: ...
    @overload
    def indexOf(self, arg0: Any) -> int: ...
    @overload
    def indexOf(self, arg0: Any, arg1: int) -> int: ...
    @overload
    def lastIndexOf(self, arg0: Any) -> int: ...
    @overload
    def lastIndexOf(self, arg0: Any, arg1: int) -> int: ...
    def clone(self) -> Any: ...
    @overload
    def toArray(self) -> list: ...
    @overload
    def toArray(self, arg0: list) -> list: ...
    def get(self, arg0: int) -> Any: ...
    def getFirst(self) -> Any: ...
    def getLast(self) -> Any: ...
    def set(self, arg0: int, arg1: Any) -> Any: ...
    @overload
    def add(self, arg0: Any) -> bool: ...
    @overload
    def add(self, arg0: int, arg1: Any) -> None: ...
    def addFirst(self, arg0: Any) -> None: ...
    def addLast(self, arg0: Any) -> None: ...
    @overload
    def remove(self, arg0: int) -> Any: ...
    @overload
    def remove(self, arg0: Any) -> bool: ...
    def removeFirst(self) -> Any: ...
    def removeLast(self) -> Any: ...
    def addIfAbsent(self, arg0: Any) -> bool: ...
    def containsAll(self, arg0: list) -> bool: ...
    def removeAll(self, arg0: list) -> bool: ...
    def retainAll(self, arg0: list) -> bool: ...
    def addAllAbsent(self, arg0: list) -> int: ...
    def clear(self) -> None: ...
    @overload
    def addAll(self, arg0: list) -> bool: ...
    @overload
    def addAll(self, arg0: int, arg1: list) -> bool: ...
    def forEach(self, arg0: Consumer) -> None: ...
    def removeIf(self, arg0: Predicate) -> bool: ...
    def replaceAll(self, arg0: UnaryOperator) -> None: ...
    def sort(self, arg0: Comparator) -> None: ...
    def toString(self) -> str: ...
    def equals(self, arg0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def iterator(self) -> Iterator: ...
    @overload
    def listIterator(self) -> ListIterator: ...
    @overload
    def listIterator(self, arg0: int) -> ListIterator: ...
    def spliterator(self) -> Spliterator: ...
    def subList(self, arg0: int, arg1: int) -> list: ...
    def reversed(self) -> list: ...
