from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.BlockingQueue import BlockingQueue
from java.util.concurrent.Callable import Callable
from java.util.concurrent.Executor import Executor
from java.util.concurrent.Future import Future
from java.util.concurrent.TimeUnit import TimeUnit

class ExecutorCompletionService:
    @overload
    def __init__(self, arg0: Executor) -> None: ...
    @overload
    def __init__(self, arg0: Executor, arg1: BlockingQueue) -> None: ...
    @overload
    def submit(self, arg0: Callable) -> Future: ...
    @overload
    def submit(self, arg0: Runnable, arg1: Any) -> Future: ...
    def take(self) -> Future: ...
    @overload
    def poll(self) -> Future: ...
    @overload
    def poll(self, arg0: int, arg1: TimeUnit) -> Future: ...
