from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.security.PrivilegedAction import PrivilegedAction
from java.security.PrivilegedExceptionAction import PrivilegedExceptionAction
from java.util.concurrent.Callable import Callable
from java.util.concurrent.ExecutorService import ExecutorService
from java.util.concurrent.ScheduledExecutorService import ScheduledExecutorService
from java.util.concurrent.ThreadFactory import ThreadFactory

class Executors:
    @overload
    @staticmethod
    def newFixedThreadPool(arg0: int) -> ExecutorService: ...
    @overload
    @staticmethod
    def newFixedThreadPool(arg0: int, arg1: ThreadFactory) -> ExecutorService: ...
    @overload
    @staticmethod
    def newWorkStealingPool(arg0: int) -> ExecutorService: ...
    @overload
    @staticmethod
    def newWorkStealingPool() -> ExecutorService: ...
    @overload
    @staticmethod
    def newSingleThreadExecutor() -> ExecutorService: ...
    @overload
    @staticmethod
    def newSingleThreadExecutor(arg0: ThreadFactory) -> ExecutorService: ...
    @overload
    @staticmethod
    def newCachedThreadPool() -> ExecutorService: ...
    @overload
    @staticmethod
    def newCachedThreadPool(arg0: ThreadFactory) -> ExecutorService: ...
    @overload
    @staticmethod
    def newSingleThreadScheduledExecutor() -> ScheduledExecutorService: ...
    @overload
    @staticmethod
    def newSingleThreadScheduledExecutor(arg0: ThreadFactory) -> ScheduledExecutorService: ...
    @overload
    @staticmethod
    def newScheduledThreadPool(arg0: int) -> ScheduledExecutorService: ...
    @overload
    @staticmethod
    def newScheduledThreadPool(arg0: int, arg1: ThreadFactory) -> ScheduledExecutorService: ...
    @staticmethod
    def unconfigurableExecutorService(arg0: ExecutorService) -> ExecutorService: ...
    @staticmethod
    def unconfigurableScheduledExecutorService(arg0: ScheduledExecutorService) -> ScheduledExecutorService: ...
    @staticmethod
    def defaultThreadFactory() -> ThreadFactory: ...
    @staticmethod
    def privilegedThreadFactory() -> ThreadFactory: ...
    @overload
    @staticmethod
    def callable(arg0: Runnable, arg1: Any) -> Callable: ...
    @overload
    @staticmethod
    def callable(arg0: Runnable) -> Callable: ...
    @overload
    @staticmethod
    def callable(arg0: PrivilegedAction) -> Callable: ...
    @overload
    @staticmethod
    def callable(arg0: PrivilegedExceptionAction) -> Callable: ...
    @staticmethod
    def privilegedCallable(arg0: Callable) -> Callable: ...
    @staticmethod
    def privilegedCallableUsingCurrentClassLoader(arg0: Callable) -> Callable: ...
