from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.Callable import Callable
from java.util.concurrent.ForkJoinTask import ForkJoinTask
from java.util.concurrent.ForkJoinWorkerThread import ForkJoinWorkerThread
from java.util.concurrent.RunnableFuture import RunnableFuture
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.function.Predicate import Predicate

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class UncaughtExceptionHandler:
    """Forward declaration for ``java.lang.Thread.UncaughtExceptionHandler``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.lang.Thread.UncaughtExceptionHandler')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/lang/Thread/UncaughtExceptionHandler.html
    """
    ...

class ForkJoinPool:
    defaultForkJoinWorkerThreadFactory: ClassVar["ForkJoinWorkerThreadFactory"]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: "ForkJoinWorkerThreadFactory", arg2: UncaughtExceptionHandler, arg3: bool) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: "ForkJoinWorkerThreadFactory", arg2: UncaughtExceptionHandler, arg3: bool, arg4: int, arg5: int, arg6: int, arg7: Predicate, arg8: int, arg9: TimeUnit) -> None: ...
    @staticmethod
    def commonPool() -> "ForkJoinPool": ...
    def invoke(self, arg0: ForkJoinTask) -> Any: ...
    @overload
    def execute(self, arg0: ForkJoinTask) -> None: ...
    @overload
    def execute(self, arg0: Runnable) -> None: ...
    @overload
    def submit(self, arg0: ForkJoinTask) -> ForkJoinTask: ...
    @overload
    def submit(self, arg0: Callable) -> ForkJoinTask: ...
    @overload
    def submit(self, arg0: Runnable, arg1: Any) -> ForkJoinTask: ...
    @overload
    def submit(self, arg0: Runnable) -> ForkJoinTask: ...
    @overload
    def invokeAll(self, arg0: list) -> list: ...
    @overload
    def invokeAll(self, arg0: list, arg1: int, arg2: TimeUnit) -> list: ...
    @overload
    def invokeAny(self, arg0: list) -> Any: ...
    @overload
    def invokeAny(self, arg0: list, arg1: int, arg2: TimeUnit) -> Any: ...
    def getFactory(self) -> "ForkJoinWorkerThreadFactory": ...
    def getUncaughtExceptionHandler(self) -> UncaughtExceptionHandler: ...
    def getParallelism(self) -> int: ...
    @staticmethod
    def getCommonPoolParallelism() -> int: ...
    def getPoolSize(self) -> int: ...
    def getAsyncMode(self) -> bool: ...
    def getRunningThreadCount(self) -> int: ...
    def getActiveThreadCount(self) -> int: ...
    def isQuiescent(self) -> bool: ...
    def getStealCount(self) -> int: ...
    def getQueuedTaskCount(self) -> int: ...
    def getQueuedSubmissionCount(self) -> int: ...
    def hasQueuedSubmissions(self) -> bool: ...
    def pollSubmission(self) -> ForkJoinTask: ...
    def drainTasksTo(self, arg0: list) -> int: ...
    def toString(self) -> str: ...
    def shutdown(self) -> None: ...
    def shutdownNow(self) -> list: ...
    def isTerminated(self) -> bool: ...
    def isTerminating(self) -> bool: ...
    def isShutdown(self) -> bool: ...
    def awaitTermination(self, arg0: int, arg1: TimeUnit) -> bool: ...
    def awaitQuiescence(self, arg0: int, arg1: TimeUnit) -> bool: ...
    @staticmethod
    def managedBlock(arg0: "ManagedBlocker") -> None: ...
    @overload
    def newTaskFor(self, arg0: Runnable, arg1: Any) -> RunnableFuture: ...
    @overload
    def newTaskFor(self, arg0: Callable) -> RunnableFuture: ...

    class ForkJoinWorkerThreadFactory:
        def newThread(self, arg0: "ForkJoinPool") -> ForkJoinWorkerThread: ...

    class ManagedBlocker:
        def block(self) -> bool: ...
        def isReleasable(self) -> bool: ...
