from typing import Any, ClassVar, overload
from java.util.concurrent.TimeUnit import TimeUnit

class Future:
    def cancel(self, arg0: bool) -> bool: ...
    def isCancelled(self) -> bool: ...
    def isDone(self) -> bool: ...
    @overload
    def get(self) -> Any: ...
    @overload
    def get(self, arg0: int, arg1: TimeUnit) -> Any: ...
