from typing import Any, ClassVar, overload
from java.lang.Void import Void

class RecursiveAction:
    def __init__(self) -> None: ...
    def compute(self) -> None: ...
    def getRawResult(self) -> Void: ...
    def setRawResult(self, arg0: Void) -> None: ...
    def exec(self) -> bool: ...
