from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.BlockingQueue import BlockingQueue
from java.util.concurrent.Callable import Callable
from java.util.concurrent.Future import Future
from java.util.concurrent.RejectedExecutionHandler import RejectedExecutionHandler
from java.util.concurrent.RunnableScheduledFuture import RunnableScheduledFuture
from java.util.concurrent.ScheduledFuture import ScheduledFuture
from java.util.concurrent.ThreadFactory import ThreadFactory
from java.util.concurrent.TimeUnit import TimeUnit

class ScheduledThreadPoolExecutor:
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: ThreadFactory) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: RejectedExecutionHandler) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: ThreadFactory, arg2: RejectedExecutionHandler) -> None: ...
    @overload
    def decorateTask(self, arg0: Runnable, arg1: RunnableScheduledFuture) -> RunnableScheduledFuture: ...
    @overload
    def decorateTask(self, arg0: Callable, arg1: RunnableScheduledFuture) -> RunnableScheduledFuture: ...
    @overload
    def schedule(self, arg0: Runnable, arg1: int, arg2: TimeUnit) -> ScheduledFuture: ...
    @overload
    def schedule(self, arg0: Callable, arg1: int, arg2: TimeUnit) -> ScheduledFuture: ...
    def scheduleAtFixedRate(self, arg0: Runnable, arg1: int, arg2: int, arg3: TimeUnit) -> ScheduledFuture: ...
    def scheduleWithFixedDelay(self, arg0: Runnable, arg1: int, arg2: int, arg3: TimeUnit) -> ScheduledFuture: ...
    def execute(self, arg0: Runnable) -> None: ...
    @overload
    def submit(self, arg0: Runnable) -> Future: ...
    @overload
    def submit(self, arg0: Runnable, arg1: Any) -> Future: ...
    @overload
    def submit(self, arg0: Callable) -> Future: ...
    def setContinueExistingPeriodicTasksAfterShutdownPolicy(self, arg0: bool) -> None: ...
    def getContinueExistingPeriodicTasksAfterShutdownPolicy(self) -> bool: ...
    def setExecuteExistingDelayedTasksAfterShutdownPolicy(self, arg0: bool) -> None: ...
    def getExecuteExistingDelayedTasksAfterShutdownPolicy(self) -> bool: ...
    def setRemoveOnCancelPolicy(self, arg0: bool) -> None: ...
    def getRemoveOnCancelPolicy(self) -> bool: ...
    def shutdown(self) -> None: ...
    def shutdownNow(self) -> list: ...
    def getQueue(self) -> BlockingQueue: ...
