from typing import Any, ClassVar, overload
from java.util.concurrent.TimeUnit import TimeUnit

class Semaphore:
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: bool) -> None: ...
    @overload
    def acquire(self) -> None: ...
    @overload
    def acquire(self, arg0: int) -> None: ...
    @overload
    def acquireUninterruptibly(self) -> None: ...
    @overload
    def acquireUninterruptibly(self, arg0: int) -> None: ...
    @overload
    def tryAcquire(self) -> bool: ...
    @overload
    def tryAcquire(self, arg0: int, arg1: TimeUnit) -> bool: ...
    @overload
    def tryAcquire(self, arg0: int) -> bool: ...
    @overload
    def tryAcquire(self, arg0: int, arg1: int, arg2: TimeUnit) -> bool: ...
    @overload
    def release(self) -> None: ...
    @overload
    def release(self, arg0: int) -> None: ...
    def availablePermits(self) -> int: ...
    def drainPermits(self) -> int: ...
    def reducePermits(self, arg0: int) -> None: ...
    def isFair(self) -> bool: ...
    def hasQueuedThreads(self) -> bool: ...
    def getQueueLength(self) -> int: ...
    def getQueuedThreads(self) -> list: ...
    def toString(self) -> str: ...
