from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable
from java.util.concurrent.CompletableFuture import CompletableFuture
from java.util.concurrent.Executor import Executor
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BiPredicate import BiPredicate
from java.util.function.Consumer import Consumer

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Subscriber:
    """Forward declaration for ``java.util.concurrent.Flow.Subscriber``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.util.concurrent.Flow.Subscriber')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Flow/Subscriber.html
    """
    ...

class SubmissionPublisher:
    @overload
    def __init__(self, arg0: Executor, arg1: int, arg2: BiConsumer) -> None: ...
    @overload
    def __init__(self, arg0: Executor, arg1: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def subscribe(self, arg0: Subscriber) -> None: ...
    def submit(self, arg0: Any) -> int: ...
    @overload
    def offer(self, arg0: Any, arg1: BiPredicate) -> int: ...
    @overload
    def offer(self, arg0: Any, arg1: int, arg2: TimeUnit, arg3: BiPredicate) -> int: ...
    def close(self) -> None: ...
    def closeExceptionally(self, arg0: Throwable) -> None: ...
    def isClosed(self) -> bool: ...
    def getClosedException(self) -> Throwable: ...
    def hasSubscribers(self) -> bool: ...
    def getNumberOfSubscribers(self) -> int: ...
    def getExecutor(self) -> Executor: ...
    def getMaxBufferCapacity(self) -> int: ...
    def getSubscribers(self) -> list: ...
    def isSubscribed(self, arg0: Subscriber) -> bool: ...
    def estimateMinimumDemand(self) -> int: ...
    def estimateMaximumLag(self) -> int: ...
    def consume(self, arg0: Consumer) -> CompletableFuture: ...
