from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator
from java.util.Spliterator import Spliterator
from java.util.concurrent.TimeUnit import TimeUnit

class SynchronousQueue:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: bool) -> None: ...
    def put(self, arg0: Any) -> None: ...
    @overload
    def offer(self, arg0: Any, arg1: int, arg2: TimeUnit) -> bool: ...
    @overload
    def offer(self, arg0: Any) -> bool: ...
    def take(self) -> Any: ...
    @overload
    def poll(self, arg0: int, arg1: TimeUnit) -> Any: ...
    @overload
    def poll(self) -> Any: ...
    def isEmpty(self) -> bool: ...
    def size(self) -> int: ...
    def remainingCapacity(self) -> int: ...
    def clear(self) -> None: ...
    def contains(self, arg0: Any) -> bool: ...
    def remove(self, arg0: Any) -> bool: ...
    def containsAll(self, arg0: list) -> bool: ...
    def removeAll(self, arg0: list) -> bool: ...
    def retainAll(self, arg0: list) -> bool: ...
    def peek(self) -> Any: ...
    def iterator(self) -> Iterator: ...
    def spliterator(self) -> Spliterator: ...
    @overload
    def toArray(self) -> list: ...
    @overload
    def toArray(self, arg0: list) -> list: ...
    def toString(self) -> str: ...
    @overload
    def drainTo(self, arg0: list) -> int: ...
    @overload
    def drainTo(self, arg0: list, arg1: int) -> int: ...
