from typing import Any, ClassVar, overload
from java.util.stream.DoubleStream import DoubleStream
from java.util.stream.IntStream import IntStream
from java.util.stream.LongStream import LongStream

class ThreadLocalRandom:
    @staticmethod
    def current() -> "ThreadLocalRandom": ...
    def setSeed(self, arg0: int) -> None: ...
    def next(self, arg0: int) -> int: ...
    def nextBoolean(self) -> bool: ...
    @overload
    def nextInt(self) -> int: ...
    @overload
    def nextInt(self, arg0: int) -> int: ...
    @overload
    def nextInt(self, arg0: int, arg1: int) -> int: ...
    @overload
    def nextLong(self) -> int: ...
    @overload
    def nextLong(self, arg0: int) -> int: ...
    @overload
    def nextLong(self, arg0: int, arg1: int) -> int: ...
    @overload
    def nextFloat(self) -> float: ...
    @overload
    def nextFloat(self, arg0: float) -> float: ...
    @overload
    def nextFloat(self, arg0: float, arg1: float) -> float: ...
    @overload
    def nextDouble(self) -> float: ...
    @overload
    def nextDouble(self, arg0: float) -> float: ...
    @overload
    def nextDouble(self, arg0: float, arg1: float) -> float: ...
    @overload
    def ints(self, arg0: int) -> IntStream: ...
    @overload
    def ints(self) -> IntStream: ...
    @overload
    def ints(self, arg0: int, arg1: int, arg2: int) -> IntStream: ...
    @overload
    def ints(self, arg0: int, arg1: int) -> IntStream: ...
    @overload
    def longs(self, arg0: int) -> LongStream: ...
    @overload
    def longs(self) -> LongStream: ...
    @overload
    def longs(self, arg0: int, arg1: int, arg2: int) -> LongStream: ...
    @overload
    def longs(self, arg0: int, arg1: int) -> LongStream: ...
    @overload
    def doubles(self, arg0: int) -> DoubleStream: ...
    @overload
    def doubles(self) -> DoubleStream: ...
    @overload
    def doubles(self, arg0: int, arg1: float, arg2: float) -> DoubleStream: ...
    @overload
    def doubles(self, arg0: float, arg1: float) -> DoubleStream: ...
