from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.lang.Thread import Thread
from java.lang.Throwable import Throwable
from java.util.concurrent.BlockingQueue import BlockingQueue
from java.util.concurrent.RejectedExecutionHandler import RejectedExecutionHandler
from java.util.concurrent.ThreadFactory import ThreadFactory
from java.util.concurrent.TimeUnit import TimeUnit

class ThreadPoolExecutor:
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: TimeUnit, arg4: BlockingQueue) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: TimeUnit, arg4: BlockingQueue, arg5: ThreadFactory) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: TimeUnit, arg4: BlockingQueue, arg5: RejectedExecutionHandler) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: TimeUnit, arg4: BlockingQueue, arg5: ThreadFactory, arg6: RejectedExecutionHandler) -> None: ...
    def execute(self, arg0: Runnable) -> None: ...
    def shutdown(self) -> None: ...
    def shutdownNow(self) -> list: ...
    def isShutdown(self) -> bool: ...
    def isTerminating(self) -> bool: ...
    def isTerminated(self) -> bool: ...
    def awaitTermination(self, arg0: int, arg1: TimeUnit) -> bool: ...
    def finalize(self) -> None: ...
    def setThreadFactory(self, arg0: ThreadFactory) -> None: ...
    def getThreadFactory(self) -> ThreadFactory: ...
    def setRejectedExecutionHandler(self, arg0: RejectedExecutionHandler) -> None: ...
    def getRejectedExecutionHandler(self) -> RejectedExecutionHandler: ...
    def setCorePoolSize(self, arg0: int) -> None: ...
    def getCorePoolSize(self) -> int: ...
    def prestartCoreThread(self) -> bool: ...
    def prestartAllCoreThreads(self) -> int: ...
    def allowsCoreThreadTimeOut(self) -> bool: ...
    def allowCoreThreadTimeOut(self, arg0: bool) -> None: ...
    def setMaximumPoolSize(self, arg0: int) -> None: ...
    def getMaximumPoolSize(self) -> int: ...
    def setKeepAliveTime(self, arg0: int, arg1: TimeUnit) -> None: ...
    def getKeepAliveTime(self, arg0: TimeUnit) -> int: ...
    def getQueue(self) -> BlockingQueue: ...
    def remove(self, arg0: Runnable) -> bool: ...
    def purge(self) -> None: ...
    def getPoolSize(self) -> int: ...
    def getActiveCount(self) -> int: ...
    def getLargestPoolSize(self) -> int: ...
    def getTaskCount(self) -> int: ...
    def getCompletedTaskCount(self) -> int: ...
    def toString(self) -> str: ...
    def beforeExecute(self, arg0: Thread, arg1: Runnable) -> None: ...
    def afterExecute(self, arg0: Runnable, arg1: Throwable) -> None: ...
    def terminated(self) -> None: ...

    class AbortPolicy:
        def __init__(self) -> None: ...
        def rejectedExecution(self, arg0: Runnable, arg1: "ThreadPoolExecutor") -> None: ...

    class CallerRunsPolicy:
        def __init__(self) -> None: ...
        def rejectedExecution(self, arg0: Runnable, arg1: "ThreadPoolExecutor") -> None: ...

    class DiscardOldestPolicy:
        def __init__(self) -> None: ...
        def rejectedExecution(self, arg0: Runnable, arg1: "ThreadPoolExecutor") -> None: ...

    class DiscardPolicy:
        def __init__(self) -> None: ...
        def rejectedExecution(self, arg0: Runnable, arg1: "ThreadPoolExecutor") -> None: ...
