from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.view.textservice.SentenceSuggestionsInfo import SentenceSuggestionsInfo
from android.view.textservice.SpellCheckerInfo import SpellCheckerInfo
from android.view.textservice.SuggestionsInfo import SuggestionsInfo
from android.view.textservice.TextInfo import TextInfo
from java.util.Locale import Locale

class SpellCheckerSession:
    SERVICE_META_DATA: ClassVar[str]
    def isSessionDisconnected(self) -> bool: ...
    def getSpellChecker(self) -> SpellCheckerInfo: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...
    def getSentenceSuggestions(self, arg0: list[TextInfo], arg1: int) -> None: ...
    @overload
    def getSuggestions(self, arg0: TextInfo, arg1: int) -> None: ...
    @overload
    def getSuggestions(self, arg0: list[TextInfo], arg1: int, arg2: bool) -> None: ...
    def finalize(self) -> None: ...

    class SpellCheckerSessionListener:
        def onGetSuggestions(self, arg0: list[SuggestionsInfo]) -> None: ...
        def onGetSentenceSuggestions(self, arg0: list[SentenceSuggestionsInfo]) -> None: ...

    class SpellCheckerSessionParams:
        def getLocale(self) -> Locale: ...
        def shouldReferToSpellCheckerLanguageSettings(self) -> bool: ...
        def getSupportedAttributes(self) -> int: ...
        def getExtras(self) -> Bundle: ...

        class Builder:
            def __init__(self) -> None: ...
            def build(self) -> "SpellCheckerSessionParams": ...
            def setLocale(self, arg0: Locale) -> "Builder": ...
            def setShouldReferToSpellCheckerLanguageSettings(self, arg0: bool) -> "Builder": ...
            def setSupportedAttributes(self, arg0: int) -> "Builder": ...
            def setExtras(self, arg0: Bundle) -> "Builder": ...
