from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class Creator:
    """Forward declaration for ``android.os.Parcelable.Creator``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('android.os.Parcelable.Creator')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://developer.android.com/reference/android/os/Parcelable/Creator
    """
    ...

class TextInfo:
    CREATOR: ClassVar[Creator]
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int, arg2: int) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...
    @overload
    def __init__(self, arg0: Parcel) -> None: ...
    def writeToParcel(self, arg0: Parcel, arg1: int) -> None: ...
    def getText(self) -> str: ...
    def getCharSequence(self) -> str: ...
    def getCookie(self) -> int: ...
    def getSequence(self) -> int: ...
    def describeContents(self) -> int: ...
